import { FaceReincarnationTranslations } from '../merge';

export const batch15: FaceReincarnationTranslations = {
  14: {
    reincarnation: {
      era: {
        en: ['You were an ancient Babylonian astronomer.', 'In your past life, you were an ancient Egyptian astronomer.', 'You were a Greek astronomer.', 'In your past life, you were an Islamic Golden Age astronomer.', 'You were a Chinese astronomer.', 'In your past life, you were an Indian astronomer.', 'You were a Mayan astronomer.', 'In your past life, you were a Persian astronomer.', 'You were a Roman astronomer.', 'In your past life, you were a Tibetan astronomer.'],
        ja: ['あなたは古代バビロニアの天文学者でした。', '前世であなたは古代エジプトの天文学者でした。', 'あなたはギリシャの天文学者でした。', '前世であなたはイスラム黄金時代の天文学者でした。', 'あなたは中国の天文学者でした。', '前世であなたはインドの天文学者でした。', 'あなたはマヤの天文学者でした。', '前世であなたはペルシャの天文学者でした。', 'あなたはローマの天文学者でした。', '前世であなたはチベットの天文学者でした。'],
        'zh-CN': ['你是古巴比伦的天文学家。', '你的前世是古埃及的天文学家。', '你是希腊的天文学家。', '你的前世是伊斯兰黄金时代的天文学家。', '你是中国的天文学家。', '你的前世是印度的天文学家。', '你是玛雅的天文学家。', '你的前世是波斯的天文学家。', '你是罗马的天文学家。', '你的前世是西藏的天文学家。'],
        'zh-TW': ['你是古巴比倫的天文學家。', '你的前世是古埃及的天文學家。', '你是希臘的天文學家。', '你的前世是伊斯蘭黃金時代的天文學家。', '你是中國的天文學家。', '你的前世是印度的天文學家。', '你是瑪雅的天文學家。', '你的前世是波斯的天文學家。', '你是羅馬的天文學家。', '你的前世是西藏的天文學家。'],
        vi: ['Bạn là một nhà thiên văn Babylon cổ đại.', 'Ở kiếp trước, bạn là một nhà thiên văn Ai Cập cổ đại.', 'Bạn là một nhà thiên văn Hy Lạp.', 'Ở kiếp trước, bạn là một nhà thiên văn thời kỳ vàng son Hồi giáo.', 'Bạn là một nhà thiên văn Trung Quốc.', 'Ở kiếp trước, bạn là một nhà thiên văn Ấn Độ.', 'Bạn là một nhà thiên văn Maya.', 'Ở kiếp trước, bạn là một nhà thiên văn Ba Tư.', 'Bạn là một nhà thiên văn La Mã.', 'Ở kiếp trước, bạn là một nhà thiên văn Tây Tạng.'],
        id: ['Anda adalah astronom Babilonia kuno.', 'Di kehidupan lampau, Anda adalah astronom Mesir kuno.', 'Anda adalah astronom Yunani.', 'Di kehidupan lampau, Anda adalah astronom Zaman Keemasan Islam.', 'Anda adalah astronom Tiongkok.', 'Di kehidupan lampau, Anda adalah astronom India.', 'Anda adalah astronom Maya.', 'Di kehidupan lampau, Anda adalah astronom Persia.', 'Anda adalah astronom Romawi.', 'Di kehidupan lampau, Anda adalah astronom Tibet.']
      },
      occupation: {
        en: ['You were a star observer in your past life.', 'In your past life, you were a calendar maker.', 'You were a celestial mapper in your past life.', 'In your past life, you were a temple astronomer.', 'You were a royal astronomer in your past life.', 'In your past life, you were a navigation expert.', 'You were a timekeeper in your past life.', 'In your past life, you were a cosmic researcher.', 'You were a celestial predictor in your past life.', 'In your past life, you were an astronomical teacher.'],
        ja: ['あなたは前世で星の観測者でした。', '前世であなたは暦の製作者でした。', 'あなたは前世で天体図製作者でした。', '前世であなたは神殿の天文学者でした。', 'あなたは前世で王室の天文学者でした。', '前世であなたは航海の専門家でした。', 'あなたは前世で時計係でした。', '前世であなたは宇宙研究者でした。', 'あなたは前世で天体予測者でした。', '前世であなたは天文学教師でした。'],
        'zh-CN': ['你的前世是星象观测者。', '你的前世是历法制定者。', '你的前世是天体图绘制者。', '你的前世是神庙天文学家。', '你的前世是王室天文学家。', '你的前世是航海专家。', '你的前世是计时员。', '你的前世是宇宙研究者。', '你的前世是天体预测者。', '你的前世是天文学教师。'],
        'zh-TW': ['你的前世是星象觀測者。', '你的前世是曆法制定者。', '你的前世是天體圖繪製者。', '你的前世是神廟天文學家。', '你的前世是王室天文學家。', '你的前世是航海專家。', '你的前世是計時員。', '你的前世是宇宙研究者。', '你的前世是天體預測者。', '你的前世是天文學教師。'],
        vi: ['Bạn từng là người quan sát sao ở kiếp trước.', 'Ở kiếp trước, bạn là người làm lịch.', 'Bạn từng là người vẽ bản đồ thiên thể ở kiếp trước.', 'Ở kiếp trước, bạn là nhà thiên văn đền thờ.', 'Bạn từng là nhà thiên văn hoàng gia ở kiếp trước.', 'Ở kiếp trước, bạn là chuyên gia hàng hải.', 'Bạn từng là người giữ thời gian ở kiếp trước.', 'Ở kiếp trước, bạn là nhà nghiên cứu vũ trụ.', 'Bạn từng là người dự đoán thiên thể ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên thiên văn học.'],
        id: ['Di kehidupan lampau, Anda adalah pengamat bintang.', 'Di kehidupan lampau, Anda adalah pembuat kalender.', 'Di kehidupan lampau, Anda adalah pembuat peta langit.', 'Di kehidupan lampau, Anda adalah astronom kuil.', 'Di kehidupan lampau, Anda adalah astronom kerajaan.', 'Di kehidupan lampau, Anda adalah ahli navigasi.', 'Di kehidupan lampau, Anda adalah penjaga waktu.', 'Di kehidupan lampau, Anda adalah peneliti kosmos.', 'Di kehidupan lampau, Anda adalah peramal langit.', 'Di kehidupan lampau, Anda adalah guru astronomi.']
      },
      reason: {
        en: ['You came to use past cosmic knowledge in scientific exploration.', 'You returned to apply observation skills to modern research.', 'You came to use celestial wisdom for life guidance.', 'You returned to use astronomical precision in daily life.', 'You came to use cosmic perspective for problem solving.', 'You returned to use star knowledge for navigation.', 'You came to use time measurement skills for organization.', 'You returned to use cosmic understanding for spiritual growth.', 'You came to use celestial patterns for prediction.', 'You returned to use astronomical teaching for education.'],
        ja: ['前世の宇宙知識を今生の科学探求に活かすために来ました。', '前世の観測技術を今生の現代研究に用いるために来ました。', '前世の天体の知恵を今生の人生指導に活かすために来ました。', '前世の天文学的精密さを今生の日常生活に用いるために来ました。', '前世の宇宙的視点を今生の問題解決に活かすために来ました。', '前世の星の知識を今生の航海に用いるために来ました。', '前世の時間測定技術を今生の組織化に活かすために来ました。', '前世の宇宙理解を今生の精神的成長に用いるために来ました。', '前世の天体パターンを今生の予測に活かすために来ました。', '前世の天文学教育を今生の教育に用いるために来ました。'],
        'zh-CN': ['你为了将前世的宇宙知识用于今生的科学探索而来。', '你为了将前世的观测技能用于今生的现代研究而来。', '你为了将前世的天体智慧用于今生的人生指导而来。', '你为了将前世的天文精度用于今生的日常生活而来。', '你为了将前世的宇宙视角用于今生的问题解决而来。', '你为了将前世的星象知识用于今生的导航而来。', '你为了将前世的时间测量技能用于今生的组织管理而来。', '你为了将前世的宇宙理解用于今生的精神成长而来。', '你为了将前世的天体模式用于今生的预测而来。', '你为了将前世的天文教学用于今生的教育而来。'],
        'zh-TW': ['你為了將前世的宇宙知識用於今生的科學探索而來。', '你為了將前世的觀測技能用於今生的現代研究而來。', '你為了將前世的天體智慧用於今生的人生指導而來。', '你為了將前世的天文精度用於今生的日常生活而來。', '你為了將前世的宇宙視角用於今生的問題解決而來。', '你為了將前世的星象知識用於今生的導航而來。', '你為了將前世的時間測量技能用於今生的組織管理而來。', '你為了將前世的宇宙理解用於今生的精神成長而來。', '你為了將前世的天體模式用於今生的預測而來。', '你為了將前世的天文教學用於今生的教育而來。'],
        vi: ['Bạn đến để sử dụng kiến thức vũ trụ từ kiếp trước trong khám phá khoa học.', 'Bạn trở lại để áp dụng kỹ năng quan sát vào nghiên cứu hiện đại.', 'Bạn đến để sử dụng trí tuệ thiên thể cho hướng dẫn cuộc sống.', 'Bạn trở lại để sử dụng độ chính xác thiên văn trong cuộc sống hàng ngày.', 'Bạn đến để sử dụng góc nhìn vũ trụ cho giải quyết vấn đề.', 'Bạn trở lại để sử dụng kiến thức sao cho điều hướng.', 'Bạn đến để sử dụng kỹ năng đo thời gian cho tổ chức.', 'Bạn trở lại để sử dụng hiểu biết vũ trụ cho phát triển tinh thần.', 'Bạn đến để sử dụng mẫu thiên thể cho dự đoán.', 'Bạn trở lại để sử dụng giảng dạy thiên văn cho giáo dục.'],
        id: ['Anda datang untuk menggunakan pengetahuan kosmos masa lalu dalam eksplorasi ilmiah.', 'Anda kembali untuk menerapkan keterampilan observasi dalam penelitian modern.', 'Anda datang untuk menggunakan kebijaksanaan langit untuk bimbingan hidup.', 'Anda kembali untuk menggunakan presisi astronomi dalam kehidupan sehari-hari.', 'Anda datang untuk menggunakan perspektif kosmos untuk pemecahan masalah.', 'Anda kembali untuk menggunakan pengetahuan bintang untuk navigasi.', 'Anda datang untuk menggunakan keterampilan pengukuran waktu untuk organisasi.', 'Anda kembali untuk menggunakan pemahaman kosmos untuk pertumbuhan spiritual.', 'Anda datang untuk menggunakan pola langit untuk prediksi.', 'Anda kembali untuk menggunakan pengajaran astronomi untuk pendidikan.']
      },
      lifeCount: {
        en: ['This is your 18th reincarnation.', 'You have lived a total of 25 lives so far.', 'This life is your 12th experience.', 'You have reincarnated 21 times up to this life.', 'This life follows your 14th past life.', 'You have lived 28 lives so far.', 'This is your 16th life.', 'You have reincarnated 23 times up to this life.', 'This life is a new beginning after your 19th past life.', 'You have built cosmic experience through 31 lives.'],
        ja: ['これはあなたの18回目の転生です。', 'これまでに合計25回の人生を生きました。', '今生は12回目の経験です。', '今生までに21回転生しました。', '今生は14番目の前世の後に続きます。', 'これまでに28回の人生を生きました。', '今生は16回目の人生です。', '今生までに23回転生しました。', '今生は19番目の前世を経た新たな始まりです。', 'これまでに31回の人生で宇宙の経験を積みました。'],
        'zh-CN': ['这是你的第18次转生。', '截至目前你总共经历了25次人生。', '今生是你的第12次体验。', '到今生为止你已经转生了21次。', '今生延续自你的第14次前世。', '截至目前你已经经历了28次人生。', '今生是你的第16次人生。', '到今生为止你已经转生了23次。', '今生是你第19次前世后的新开始。', '通过31次人生你积累了宇宙经验。'],
        'zh-TW': ['這是你的第18次轉生。', '截至目前你總共經歷了25次人生。', '今生是你的第12次體驗。', '到今生為止你已經轉生了21次。', '今生延續自你的第14次前世。', '截至目前你已經經歷了28次人生。', '今生是你的第16次人生。', '到今生為止你已經轉生了23次。', '今生是你第19次前世後的新開始。', '通過31次人生你積累了宇宙經驗。'],
        vi: ['Đây là lần tái sinh thứ 18 của bạn.', 'Bạn đã sống tổng cộng 25 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 12 của bạn.', 'Bạn đã tái sinh 21 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 14 của bạn.', 'Bạn đã sống 28 kiếp cho đến nay.', 'Đây là kiếp thứ 16 của bạn.', 'Bạn đã tái sinh 23 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 19 của bạn.', 'Bạn đã tích lũy kinh nghiệm vũ trụ qua 31 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-18 Anda.', 'Anda telah menjalani total 25 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-12 Anda.', 'Anda telah bereinkarnasi 21 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-14 Anda.', 'Anda telah menjalani 28 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-16 Anda.', 'Anda telah bereinkarnasi 23 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-19 Anda.', 'Anda telah membangun pengalaman kosmos melalui 31 kehidupan.']
      }
    }
  },
  15: {
    reincarnation: {
      era: {
        en: ['You were an ancient Greek mathematician.', 'In your past life, you were an ancient Egyptian mathematician.', 'You were an Indian mathematician.', 'In your past life, you were an Islamic Golden Age mathematician.', 'You were a Chinese mathematician.', 'In your past life, you were a Babylonian mathematician.', 'You were a Roman mathematician.', 'In your past life, you were a Persian mathematician.', 'You were a Mayan mathematician.', 'In your past life, you were a Tibetan mathematician.'],
        ja: ['あなたは古代ギリシャの数学者でした。', '前世であなたは古代エジプトの数学者でした。', 'あなたはインドの数学者でした。', '前世であなたはイスラム黄金時代の数学者でした。', 'あなたは中国の数学者でした。', '前世であなたはバビロニアの数学者でした。', 'あなたはローマの数学者でした。', '前世であなたはペルシャの数学者でした。', 'あなたはマヤの数学者でした。', '前世であなたはチベットの数学者でした。'],
        'zh-CN': ['你是古希腊的数学家。', '你的前世是古埃及的数学家。', '你是印度的数学家。', '你的前世是伊斯兰黄金时代的数学家。', '你是中国的数学家。', '你的前世是巴比伦的数学家。', '你是罗马的数学家。', '你的前世是波斯的数学家。', '你是玛雅的数学家。', '你的前世是西藏的数学家。'],
        'zh-TW': ['你是古希臘的數學家。', '你的前世是古埃及的數學家。', '你是印度的數學家。', '你的前世是伊斯蘭黃金時代的數學家。', '你是中國的數學家。', '你的前世是巴比倫的數學家。', '你是羅馬的數學家。', '你的前世是波斯的數學家。', '你是瑪雅的數學家。', '你的前世是西藏的數學家。'],
        vi: ['Bạn là một nhà toán học Hy Lạp cổ đại.', 'Ở kiếp trước, bạn là một nhà toán học Ai Cập cổ đại.', 'Bạn là một nhà toán học Ấn Độ.', 'Ở kiếp trước, bạn là một nhà toán học thời kỳ vàng son Hồi giáo.', 'Bạn là một nhà toán học Trung Quốc.', 'Ở kiếp trước, bạn là một nhà toán học Babylon.', 'Bạn là một nhà toán học La Mã.', 'Ở kiếp trước, bạn là một nhà toán học Ba Tư.', 'Bạn là một nhà toán học Maya.', 'Ở kiếp trước, bạn là một nhà toán học Tây Tạng.'],
        id: ['Anda adalah matematikawan Yunani kuno.', 'Di kehidupan lampau, Anda adalah matematikawan Mesir kuno.', 'Anda adalah matematikawan India.', 'Di kehidupan lampau, Anda adalah matematikawan Zaman Keemasan Islam.', 'Anda adalah matematikawan Tiongkok.', 'Di kehidupan lampau, Anda adalah matematikawan Babilonia.', 'Anda adalah matematikawan Romawi.', 'Di kehidupan lampau, Anda adalah matematikawan Persia.', 'Anda adalah matematikawan Maya.', 'Di kehidupan lampau, Anda adalah matematikawan Tibet.']
      },
      occupation: {
        en: ['You were a number theorist in your past life.', 'In your past life, you were a geometry expert.', 'You were a calculation master in your past life.', 'In your past life, you were a measurement specialist.', 'You were a problem solver in your past life.', 'In your past life, you were a mathematical teacher.', 'You were a formula developer in your past life.', 'In your past life, you were a mathematical researcher.', 'You were a calculation advisor in your past life.', 'In your past life, you were a mathematical philosopher.'],
        ja: ['あなたは前世で数論学者でした。', '前世であなたは幾何学の専門家でした。', 'あなたは前世で計算の達人でした。', '前世であなたは測定の専門家でした。', 'あなたは前世で問題解決者でした。', '前世であなたは数学教師でした。', 'あなたは前世で公式開発者でした。', '前世であなたは数学研究者でした。', 'あなたは前世で計算顧問でした。', '前世であなたは数学哲学者でした。'],
        'zh-CN': ['你的前世是数论学者。', '你的前世是几何学专家。', '你的前世是计算大师。', '你的前世是测量专家。', '你的前世是问题解决者。', '你的前世是数学教师。', '你的前世是公式开发者。', '你的前世是数学研究者。', '你的前世是计算顾问。', '你的前世是数学哲学家。'],
        'zh-TW': ['你的前世是數論學者。', '你的前世是幾何學專家。', '你的前世是計算大師。', '你的前世是測量專家。', '你的前世是問題解決者。', '你的前世是數學教師。', '你的前世是公式開發者。', '你的前世是數學研究者。', '你的前世是計算顧問。', '你的前世是數學哲學家。'],
        vi: ['Bạn từng là nhà lý thuyết số ở kiếp trước.', 'Ở kiếp trước, bạn là chuyên gia hình học.', 'Bạn từng là bậc thầy tính toán ở kiếp trước.', 'Ở kiếp trước, bạn là chuyên gia đo lường.', 'Bạn từng là người giải quyết vấn đề ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên toán học.', 'Bạn từng là người phát triển công thức ở kiếp trước.', 'Ở kiếp trước, bạn là nhà nghiên cứu toán học.', 'Bạn từng là cố vấn tính toán ở kiếp trước.', 'Ở kiếp trước, bạn là triết gia toán học.'],
        id: ['Di kehidupan lampau, Anda adalah ahli teori bilangan.', 'Di kehidupan lampau, Anda adalah ahli geometri.', 'Di kehidupan lampau, Anda adalah master perhitungan.', 'Di kehidupan lampau, Anda adalah spesialis pengukuran.', 'Di kehidupan lampau, Anda adalah pemecah masalah.', 'Di kehidupan lampau, Anda adalah guru matematika.', 'Di kehidupan lampau, Anda adalah pengembang rumus.', 'Di kehidupan lampau, Anda adalah peneliti matematika.', 'Di kehidupan lampau, Anda adalah penasihat perhitungan.', 'Di kehidupan lampau, Anda adalah filsuf matematika.']
      },
      reason: {
        en: ['You came to use past mathematical logic in problem solving.', 'You returned to apply calculation skills to modern challenges.', 'You came to use mathematical precision in daily life.', 'You returned to use geometric thinking for spatial understanding.', 'You came to use number theory for pattern recognition.', 'You returned to use mathematical teaching for education.', 'You came to use formula development for innovation.', 'You returned to use mathematical research for discovery.', 'You came to use calculation expertise for efficiency.', 'You returned to use mathematical philosophy for wisdom.'],
        ja: ['前世の数学的論理を今生の問題解決に活かすために来ました。', '前世の計算技術を今生の現代の課題に用いるために来ました。', '前世の数学的精密さを今生の日常生活に活かすために来ました。', '前世の幾何学的思考を今生の空間理解に用いるために来ました。', '前世の数論を今生のパターン認識に活かすために来ました。', '前世の数学教育を今生の教育に用いるために来ました。', '前世の公式開発を今生の革新に活かすために来ました。', '前世の数学研究を今生の発見に用いるために来ました。', '前世の計算専門知識を今生の効率性に活かすために来ました。', '前世の数学哲学を今生の知恵に用いるために来ました。'],
        'zh-CN': ['你为了将前世的数学逻辑用于今生的问题解决而来。', '你为了将前世的计算技能用于今生的现代挑战而来。', '你为了将前世的数学精度用于今生的日常生活而来。', '你为了将前世的几何思维用于今生的空间理解而来。', '你为了将前世的数论用于今生的模式识别而来。', '你为了将前世的数学教学用于今生的教育而来。', '你为了将前世的公式开发用于今生的创新而来。', '你为了将前世的数学研究用于今生的发现而来。', '你为了将前世的计算专长用于今生的效率而来。', '你为了将前世的数学哲学用于今生的智慧而来。'],
        'zh-TW': ['你為了將前世的數學邏輯用於今生的問題解決而來。', '你為了將前世的计算技能用於今生的現代挑戰而來。', '你為了將前世的數學精度用於今生的日常生活而來。', '你為了將前世的幾何思維用於今生的空間理解而來。', '你為了將前世的數論用於今生的模式識別而來。', '你為了將前世的數學教學用於今生的教育而來。', '你為了將前世的公式開發用於今生的創新而來。', '你為了將前世的數學研究用於今生的發現而來。', '你為了將前世的计算專長用於今生的效率而來。', '你為了將前世的數學哲學用於今生的智慧而來。'],
        vi: ['Bạn đến để sử dụng logic toán học từ kiếp trước trong giải quyết vấn đề.', 'Bạn trở lại để áp dụng kỹ năng tính toán vào thử thách hiện đại.', 'Bạn đến để sử dụng độ chính xác toán học trong cuộc sống hàng ngày.', 'Bạn trở lại để sử dụng tư duy hình học cho hiểu biết không gian.', 'Bạn đến để sử dụng lý thuyết số cho nhận dạng mẫu.', 'Bạn trở lại để sử dụng giảng dạy toán học cho giáo dục.', 'Bạn đến để sử dụng phát triển công thức cho đổi mới.', 'Bạn trở lại để sử dụng nghiên cứu toán học cho khám phá.', 'Bạn đến để sử dụng chuyên môn tính toán cho hiệu quả.', 'Bạn trở lại để sử dụng triết học toán học cho trí tuệ.'],
        id: ['Anda datang untuk menggunakan logika matematika masa lalu dalam pemecahan masalah.', 'Anda kembali untuk menerapkan keterampilan perhitungan pada tantangan modern.', 'Anda datang untuk menggunakan presisi matematika dalam kehidupan sehari-hari.', 'Anda kembali untuk menggunakan pemikiran geometris untuk pemahaman spasial.', 'Anda datang untuk menggunakan teori bilangan untuk pengenalan pola.', 'Anda kembali untuk menggunakan pengajaran matematika untuk pendidikan.', 'Anda datang untuk menggunakan pengembangan rumus untuk inovasi.', 'Anda kembali untuk menggunakan penelitian matematika untuk penemuan.', 'Anda datang untuk menggunakan keahlian perhitungan untuk efisiensi.', 'Anda kembali untuk menggunakan filsafat matematika untuk kebijaksanaan.']
      },
      lifeCount: {
        en: ['This is your 13th reincarnation.', 'You have lived a total of 20 lives so far.', 'This life is your 7th experience.', 'You have reincarnated 16 times up to this life.', 'This life follows your 9th past life.', 'You have lived 23 lives so far.', 'This is your 11th life.', 'You have reincarnated 18 times up to this life.', 'This life is a new beginning after your 14th past life.', 'You have built mathematical experience through 26 lives.'],
        ja: ['これはあなたの13回目の転生です。', 'これまでに合計20回の人生を生きました。', '今生は7回目の経験です。', '今生までに16回転生しました。', '今生は9番目の前世の後に続きます。', 'これまでに23回の人生を生きました。', '今生は11回目の人生です。', '今生までに18回転生しました。', '今生は14番目の前世を経た新たな始まりです。', 'これまでに26回の人生で数学の経験を積みました。'],
        'zh-CN': ['这是你的第13次转生。', '截至目前你总共经历了20次人生。', '今生是你的第7次体验。', '到今生为止你已经转生了16次。', '今生延续自你的第9次前世。', '截至目前你已经经历了23次人生。', '今生是你的第11次人生。', '到今生为止你已经转生了18次。', '今生是你第14次前世后的新开始。', '通过26次人生你积累了数学经验。'],
        'zh-TW': ['這是你的第13次轉生。', '截至目前你總共經歷了20次人生。', '今生是你的第7次體驗。', '到今生為止你已經轉生了16次。', '今生延續自你的第9次前世。', '截至目前你已經經歷了23次人生。', '今生是你的第11次人生。', '到今生為止你已經轉生了18次。', '今生是你第14次前世後的新開始。', '通過26次人生你積累了數學經驗。'],
        vi: ['Đây là lần tái sinh thứ 13 của bạn.', 'Bạn đã sống tổng cộng 20 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 7 của bạn.', 'Bạn đã tái sinh 16 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 9 của bạn.', 'Bạn đã sống 23 kiếp cho đến nay.', 'Đây là kiếp thứ 11 của bạn.', 'Bạn đã tái sinh 18 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 14 của bạn.', 'Bạn đã tích lũy kinh nghiệm toán học qua 26 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-13 Anda.', 'Anda telah menjalani total 20 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-7 Anda.', 'Anda telah bereinkarnasi 16 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-9 Anda.', 'Anda telah menjalani 23 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-11 Anda.', 'Anda telah bereinkarnasi 18 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-14 Anda.', 'Anda telah membangun pengalaman matematika melalui 26 kehidupan.']
      }
    }
  },
  16: {
    reincarnation: {
      era: {
        en: ['You were an ancient Egyptian doctor.', 'In your past life, you were an ancient Greek physician.', 'You were a Chinese traditional doctor.', 'In your past life, you were an Islamic Golden Age physician.', 'You were an Indian Ayurvedic doctor.', 'In your past life, you were a Roman physician.', 'You were a Persian doctor.', 'In your past life, you were a Tibetan medicine practitioner.', 'You were a Mayan healer.', 'In your past life, you were a Babylonian physician.'],
        ja: ['あなたは古代エジプトの医者でした。', '前世であなたは古代ギリシャの医師でした。', 'あなたは中国の伝統医者でした。', '前世であなたはイスラム黄金時代の医師でした。', 'あなたはインドのアーユルヴェーダ医者でした。', '前世であなたはローマの医師でした。', 'あなたはペルシャの医者でした。', '前世であなたはチベット医学の実践者でした。', 'あなたはマヤの治療者でした。', '前世であなたはバビロニアの医師でした。'],
        'zh-CN': ['你是古埃及的医生。', '你的前世是古希腊的医师。', '你是中国的传统医生。', '你的前世是伊斯兰黄金时代的医师。', '你是印度的阿育吠陀医生。', '你的前世是罗马的医师。', '你是波斯的医生。', '你的前世是西藏医学实践者。', '你是玛雅的治愈者。', '你的前世是巴比伦的医师。'],
        'zh-TW': ['你是古埃及的醫生。', '你的前世是古希臘的醫師。', '你是中國的傳統醫生。', '你的前世是伊斯蘭黃金時代的醫師。', '你是印度的阿育吠陀醫生。', '你的前世是羅馬的醫師。', '你是波斯的醫生。', '你的前世是西藏醫學實踐者。', '你是瑪雅的治癒者。', '你的前世是巴比倫的醫師。'],
        vi: ['Bạn là một bác sĩ Ai Cập cổ đại.', 'Ở kiếp trước, bạn là một bác sĩ Hy Lạp cổ đại.', 'Bạn là một bác sĩ truyền thống Trung Quốc.', 'Ở kiếp trước, bạn là một bác sĩ thời kỳ vàng son Hồi giáo.', 'Bạn là một bác sĩ Ayurveda Ấn Độ.', 'Ở kiếp trước, bạn là một bác sĩ La Mã.', 'Bạn là một bác sĩ Ba Tư.', 'Ở kiếp trước, bạn là một người thực hành y học Tây Tạng.', 'Bạn là một người chữa bệnh Maya.', 'Ở kiếp trước, bạn là một bác sĩ Babylon.'],
        id: ['Anda adalah dokter Mesir kuno.', 'Di kehidupan lampau, Anda adalah dokter Yunani kuno.', 'Anda adalah dokter tradisional Tiongkok.', 'Di kehidupan lampau, Anda adalah dokter Zaman Keemasan Islam.', 'Anda adalah dokter Ayurveda India.', 'Di kehidupan lampau, Anda adalah dokter Romawi.', 'Anda adalah dokter Persia.', 'Di kehidupan lampau, Anda adalah praktisi pengobatan Tibet.', 'Anda adalah penyembuh Maya.', 'Di kehidupan lampau, Anda adalah dokter Babilonia.']
      },
      occupation: {
        en: ['You were a royal physician in your past life.', 'In your past life, you were a temple healer.', 'You were a village doctor in your past life.', 'In your past life, you were a military surgeon.', 'You were a court physician in your past life.', 'In your past life, you were a traveling healer.', 'You were a monastery doctor in your past life.', 'In your past life, you were a herbal medicine expert.', 'You were a bone setter in your past life.', 'In your past life, you were a medical teacher.'],
        ja: ['あなたは前世で王室の医師でした。', '前世であなたは神殿の治療者でした。', 'あなたは前世で村の医者でした。', '前世であなたは軍の外科医でした。', 'あなたは前世で宮廷医師でした。', '前世であなたは旅の治療者でした。', 'あなたは前世で修道院の医者でした。', '前世であなたは漢方薬の専門家でした。', 'あなたは前世で接骨師でした。', '前世であなたは医学教師でした。'],
        'zh-CN': ['你的前世是王室医师。', '你的前世是神庙治愈者。', '你的前世是乡村医生。', '你的前世是军医。', '你的前世是宫廷医师。', '你的前世是游方医者。', '你的前世是修道院医生。', '你的前世是草药专家。', '你的前世是接骨师。', '你的前世是医学教师。'],
        'zh-TW': ['你的前世是王室醫師。', '你的前世是神廟治癒者。', '你的前世是鄉村醫生。', '你的前世是軍醫。', '你的前世是宮廷醫師。', '你的前世是遊方醫者。', '你的前世是修道院醫生。', '你的前世是草藥專家。', '你的前世是接骨師。', '你的前世是醫學教師。'],
        vi: ['Bạn từng là bác sĩ hoàng gia ở kiếp trước.', 'Ở kiếp trước, bạn là người chữa bệnh đền thờ.', 'Bạn từng là bác sĩ làng ở kiếp trước.', 'Ở kiếp trước, bạn là bác sĩ phẫu thuật quân đội.', 'Bạn từng là bác sĩ cung đình ở kiếp trước.', 'Ở kiếp trước, bạn là người chữa bệnh du hành.', 'Bạn từng là bác sĩ tu viện ở kiếp trước.', 'Ở kiếp trước, bạn là chuyên gia thuốc thảo dược.', 'Bạn từng là thầy nắn xương ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên y học.'],
        id: ['Di kehidupan lampau, Anda adalah dokter kerajaan.', 'Di kehidupan lampau, Anda adalah penyembuh kuil.', 'Di kehidupan lampau, Anda adalah dokter desa.', 'Di kehidupan lampau, Anda adalah ahli bedah militer.', 'Di kehidupan lampau, Anda adalah dokter istana.', 'Di kehidupan lampau, Anda adalah penyembuh keliling.', 'Di kehidupan lampau, Anda adalah dokter biara.', 'Di kehidupan lampau, Anda adalah ahli obat herbal.', 'Di kehidupan lampau, Anda adalah tukang urut tulang.', 'Di kehidupan lampau, Anda adalah guru kedokteran.']
      },
      reason: {
        en: ['You came to use past healing knowledge in modern medicine.', 'You returned to apply medical wisdom to help others.', 'You came to use diagnostic skills for problem solving.', 'You returned to use healing compassion for service.', 'You came to use medical precision for accuracy.', 'You returned to use therapeutic knowledge for wellness.', 'You came to use surgical skills for precision work.', 'You returned to use herbal wisdom for natural healing.', 'You came to use bone setting techniques for physical therapy.', 'You returned to use medical teaching for education.'],
        ja: ['前世の治療知識を今生の現代医学に活かすために来ました。', '前世の医学的知恵を今生の他者支援に用いるために来ました。', '前世の診断技術を今生の問題解決に活かすために来ました。', '前世の治療的慈悲を今生の奉仕に用いるために来ました。', '前世の医学的精密さを今生の正確性に活かすために来ました。', '前世の治療知識を今生の健康に用いるために来ました。', '前世の外科技術を今生の精密作業に活かすために来ました。', '前世の漢方知恵を今生の自然治癒に用いるために来ました。', '前世の接骨技術を今生の理学療法に活かすために来ました。', '前世の医学教育を今生の教育に用いるために来ました。'],
        'zh-CN': ['你为了将前世的治疗知识用于今生的现代医学而来。', '你为了将前世的医学智慧用于今生的帮助他人而来。', '你为了将前世的诊断技能用于今生的问题解决而来。', '你为了将前世的治疗慈悲用于今生的服务而来。', '你为了将前世的医学精度用于今生的准确性而来。', '你为了将前世的治疗知识用于今生的健康而来。', '你为了将前世的外科技能用于今生的精密工作而来。', '你为了将前世的草药智慧用于今生的自然治愈而来。', '你为了将前世的接骨技术用于今生的物理治疗而来。', '你为了将前世的医学教学用于今生的教育而来。'],
        'zh-TW': ['你為了將前世的治療知識用於今生的現代醫學而來。', '你為了將前世的醫學智慧用於今生的幫助他人而來。', '你為了將前世的診斷技能用於今生的問題解決而來。', '你為了將前世的治療慈悲用於今生的服務而來。', '你為了將前世的醫學精度用於今生的準確性而來。', '你為了將前世的治療知識用於今生的健康而來。', '你為了將前世的外科技能用於今生的精密工作而來。', '你為了將前世的草藥智慧用於今生的自然治癒而來。', '你為了將前世的接骨技術用於今生的物理治療而來。', '你為了將前世的醫學教學用於今生的教育而來。'],
        vi: ['Bạn đến để sử dụng kiến thức chữa bệnh từ kiếp trước trong y học hiện đại.', 'Bạn trở lại để áp dụng trí tuệ y học để giúp đỡ người khác.', 'Bạn đến để sử dụng kỹ năng chẩn đoán cho giải quyết vấn đề.', 'Bạn trở lại để sử dụng lòng từ bi chữa bệnh cho phục vụ.', 'Bạn đến để sử dụng độ chính xác y học cho sự chính xác.', 'Bạn trở lại để sử dụng kiến thức trị liệu cho sức khỏe.', 'Bạn đến để sử dụng kỹ năng phẫu thuật cho công việc chính xác.', 'Bạn trở lại để sử dụng trí tuệ thảo dược cho chữa bệnh tự nhiên.', 'Bạn đến để sử dụng kỹ thuật nắn xương cho vật lý trị liệu.', 'Bạn trở lại để sử dụng giảng dạy y học cho giáo dục.'],
        id: ['Anda datang untuk menggunakan pengetahuan penyembuhan masa lalu dalam pengobatan modern.', 'Anda kembali untuk menerapkan kebijaksanaan medis untuk membantu orang lain.', 'Anda datang untuk menggunakan keterampilan diagnostik untuk pemecahan masalah.', 'Anda kembali untuk menggunakan belas kasih penyembuhan untuk pelayanan.', 'Anda datang untuk menggunakan presisi medis untuk akurasi.', 'Anda kembali untuk menggunakan pengetahuan terapeutik untuk kesehatan.', 'Anda datang untuk menggunakan keterampilan bedah untuk pekerjaan presisi.', 'Anda kembali untuk menggunakan kebijaksanaan herbal untuk penyembuhan alami.', 'Anda datang untuk menggunakan teknik pengaturan tulang untuk terapi fisik.', 'Anda kembali untuk menggunakan pengajaran medis untuk pendidikan.']
      },
      lifeCount: {
        en: ['This is your 8th reincarnation.', 'You have lived a total of 15 lives so far.', 'This life is your 3rd experience.', 'You have reincarnated 12 times up to this life.', 'This life follows your 5th past life.', 'You have lived 18 lives so far.', 'This is your 6th life.', 'You have reincarnated 13 times up to this life.', 'This life is a new beginning after your 10th past life.', 'You have built healing experience through 21 lives.'],
        ja: ['これはあなたの8回目の転生です。', 'これまでに合計15回の人生を生きました。', '今生は3回目の経験です。', '今生までに12回転生しました。', '今生は5番目の前世の後に続きます。', 'これまでに18回の人生を生きました。', '今生は6回目の人生です。', '今生までに13回転生しました。', '今生は10番目の前世を経た新たな始まりです。', 'これまでに21回の人生で治療の経験を積みました。'],
        'zh-CN': ['这是你的第8次转生。', '截至目前你总共经历了15次人生。', '今生是你的第3次体验。', '到今生为止你已经转生了12次。', '今生延续自你的第5次前世。', '截至目前你已经经历了18次人生。', '今生是你的第6次人生。', '到今生为止你已经转生了13次。', '今生是你第10次前世后的新开始。', '通过21次人生你积累了治疗经验。'],
        'zh-TW': ['這是你的第8次轉生。', '截至目前你總共經歷了15次人生。', '今生是你的第3次體驗。', '到今生為止你已經轉生了12次。', '今生延續自你的第5次前世。', '截至目前你已經經歷了18次人生。', '今生是你的第6次人生。', '到今生為止你已經轉生了13次。', '今生是你第10次前世後的新開始。', '通過21次人生你積累了治療經驗。'],
        vi: ['Đây là lần tái sinh thứ 8 của bạn.', 'Bạn đã sống tổng cộng 15 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 3 của bạn.', 'Bạn đã tái sinh 12 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 5 của bạn.', 'Bạn đã sống 18 kiếp cho đến nay.', 'Đây là kiếp thứ 6 của bạn.', 'Bạn đã tái sinh 13 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 10 của bạn.', 'Bạn đã tích lũy kinh nghiệm chữa bệnh qua 21 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-8 Anda.', 'Anda telah menjalani total 15 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-3 Anda.', 'Anda telah bereinkarnasi 12 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-5 Anda.', 'Anda telah menjalani 18 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-6 Anda.', 'Anda telah bereinkarnasi 13 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-10 Anda.', 'Anda telah membangun pengalaman penyembuhan melalui 21 kehidupan.']
      }
    }
  }
};