import { FaceReincarnationTranslations } from '../merge';

export const batch28: FaceReincarnationTranslations = {
  36: {
    reincarnation: {
      era: {
        en: ['You were an ancient Egyptian farmer.', 'In your past life, you were an ancient Chinese farmer.', 'You were a Roman farmer.', 'In your past life, you were a Greek farmer.', 'You were a Japanese farmer.', 'In your past life, you were an Indian farmer.', 'You were a Celtic farmer.', 'In your past life, you were a Persian farmer.', 'You were a Mayan farmer.', 'In your past life, you were a Korean farmer.'],
        ja: ['あなたは古代エジプトの農民でした。', '前世であなたは古代中国の農民でした。', 'あなたはローマの農民でした。', '前世であなたはギリシャの農民でした。', 'あなたは日本の農民でした。', '前世であなたはインドの農民でした。', 'あなたはケルトの農民でした。', '前世であなたはペルシャの農民でした。', 'あなたはマヤの農民でした。', '前世であなたは韓国の農民でした。'],
        'zh-CN': ['你是古埃及的农民。', '你的前世是古代中国的农民。', '你是罗马的农民。', '你的前世是希腊的农民。', '你是日本的农民。', '你的前世是印度的农民。', '你是凯尔特的农民。', '你的前世是波斯的农民。', '你是玛雅的农民。', '你的前世是韩国的农民。'],
        'zh-TW': ['你是古埃及的農民。', '你的前世是古代中國的農民。', '你是羅馬的農民。', '你的前世是希臘的農民。', '你是日本的農民。', '你的前世是印度的農民。', '你是凱爾特的農民。', '你的前世是波斯的農民。', '你是瑪雅的農民。', '你的前世是韓國的農民。'],
        vi: ['Bạn là một nông dân Ai Cập cổ đại.', 'Ở kiếp trước, bạn là một nông dân Trung Quốc cổ đại.', 'Bạn là một nông dân La Mã.', 'Ở kiếp trước, bạn là một nông dân Hy Lạp.', 'Bạn là một nông dân Nhật Bản.', 'Ở kiếp trước, bạn là một nông dân Ấn Độ.', 'Bạn là một nông dân Celtic.', 'Ở kiếp trước, bạn là một nông dân Ba Tư.', 'Bạn là một nông dân Maya.', 'Ở kiếp trước, bạn là một nông dân Hàn Quốc.'],
        id: ['Anda adalah petani Mesir kuno.', 'Di kehidupan lampau, Anda adalah petani Tiongkok kuno.', 'Anda adalah petani Romawi.', 'Di kehidupan lampau, Anda adalah petani Yunani.', 'Anda adalah petani Jepang.', 'Di kehidupan lampau, Anda adalah petani India.', 'Anda adalah petani Celtic.', 'Di kehidupan lampau, Anda adalah petani Persia.', 'Anda adalah petani Maya.', 'Di kehidupan lampau, Anda adalah petani Korea.']
      },
      occupation: {
        en: ['You were a grain farmer in your past life.', 'In your past life, you were a vegetable farmer.', 'You were a fruit farmer in your past life.', 'In your past life, you were a rice farmer.', 'You were a wheat farmer in your past life.', 'In your past life, you were a corn farmer.', 'You were a cotton farmer in your past life.', 'In your past life, you were a tobacco farmer.', 'You were a sugar farmer in your past life.', 'In your past life, you were a farming teacher.'],
        ja: ['あなたは前世で穀物農民でした。', '前世であなたは野菜農民でした。', 'あなたは前世で果物農民でした。', '前世であなたは米農民でした。', 'あなたは前世で小麦農民でした。', '前世であなたはトウモロコシ農民でした。', 'あなたは前世で綿農民でした。', '前世であなたはタバコ農民でした。', 'あなたは前世で砂糖農民でした。', '前世であなたは農業教師でした。'],
        'zh-CN': ['你的前世是谷物农民。', '你的前世是蔬菜农民。', '你的前世是水果农民。', '你的前世是稻米农民。', '你的前世是小麦农民。', '你的前世是玉米农民。', '你的前世是棉花农民。', '你的前世是烟草农民。', '你的前世是甘蔗农民。', '你的前世是农业教师。'],
        'zh-TW': ['你的前世是穀物農民。', '你的前世是蔬菜農民。', '你的前世是水果農民。', '你的前世是稻米農民。', '你的前世是小麥農民。', '你的前世是玉米農民。', '你的前世是棉花農民。', '你的前世是煙草農民。', '你的前世是甘蔗農民。', '你的前世是農業教師。'],
        vi: ['Bạn từng là nông dân trồng ngũ cốc ở kiếp trước.', 'Ở kiếp trước, bạn là nông dân trồng rau.', 'Bạn từng là nông dân trồng trái cây ở kiếp trước.', 'Ở kiếp trước, bạn là nông dân trồng lúa.', 'Bạn từng là nông dân trồng lúa mì ở kiếp trước.', 'Ở kiếp trước, bạn là nông dân trồng ngô.', 'Bạn từng là nông dân trồng bông ở kiếp trước.', 'Ở kiếp trước, bạn là nông dân trồng thuốc lá.', 'Bạn từng là nông dân trồng mía ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên nông nghiệp.'],
        id: ['Di kehidupan lampau, Anda adalah petani biji-bijian.', 'Di kehidupan lampau, Anda adalah petani sayuran.', 'Di kehidupan lampau, Anda adalah petani buah-buahan.', 'Di kehidupan lampau, Anda adalah petani padi.', 'Di kehidupan lampau, Anda adalah petani gandum.', 'Di kehidupan lampau, Anda adalah petani jagung.', 'Di kehidupan lampau, Anda adalah petani kapas.', 'Di kehidupan lampau, Anda adalah petani tembakau.', 'Di kehidupan lampau, Anda adalah petani tebu.', 'Di kehidupan lampau, Anda adalah guru pertanian.']
      },
      reason: {
        en: ['You came to use past farming skills in patience and nurturing.', 'You returned to apply earth wisdom to growth and development.', 'You came to use farming patience for long-term goals.', 'You returned to use earth knowledge for sustainability.', 'You came to use farming precision for detailed work.', 'You returned to use earth instincts for intuition.', 'You came to use farming responsibility for provision.', 'You returned to use earth teaching for guidance.', 'You came to use farming mastery for foundation building.', 'You returned to use earth knowledge for innovation.'],
        ja: ['前世の農業技術を今生の忍耐と育成に活かすために来ました。', '前世の土の知恵を今生の成長と発展に用いるために来ました。', '前世の農業忍耐を今生の長期目標に活かすために来ました。', '前世の土の知識を今生の持続可能性に用いるために来ました。', '前世の農業精密さを今生の詳細作業に活かすために来ました。', '前世の土の本能を今生の直感に用いるために来ました。', '前世の農業責任を今生の供給に活かすために来ました。', '前世の土の教育を今生の指導に用いるために来ました。', '前世の農業習得を今生の基盤構築に活かすために来ました。', '前世の土の知識を今生の革新に用いるために来ました。'],
        'zh-CN': ['你为了将前世的农业技能用于今生的耐心和培育而来。', '你为了将前世的土智慧用于今生的成长和发展而来。', '你为了将前世的农业耐心用于今生的长期目标而来。', '你为了将前世的土知识用于今生的可持续性而来。', '你为了将前世的农业精度用于今生的细致工作而来。', '你为了将前世的土本能用于今生的直觉而来。', '你为了将前世的农业责任用于今生的供给而来。', '你为了将前世的土教学用于今生的指导而来。', '你为了将前世的农业掌握用于今生的基础建设而来。', '你为了将前世的土知识用于今生的创新而来。'],
        'zh-TW': ['你為了將前世的農業技能用於今生的耐心和培育而來。', '你為了將前世的土智慧用於今生的成長和發展而來。', '你為了將前世的農業耐心用於今生的長期目標而來。', '你為了將前世的土知識用於今生的可持續性而來。', '你為了將前世的農業精度用於今生的細緻工作而來。', '你為了將前世的土本能用於今生的直覺而來。', '你為了將前世的農業責任用於今生的供給而來。', '你為了將前世的土教學用於今生的指導而來。', '你為了將前世的農業掌握用於今生的基礎建設而來。', '你為了將前世的土知識用於今生的創新而來。'],
        vi: ['Bạn đến để sử dụng kỹ năng nông nghiệp từ kiếp trước trong sự kiên nhẫn và nuôi dưỡng.', 'Bạn trở lại để áp dụng trí tuệ đất vào tăng trưởng và phát triển.', 'Bạn đến để sử dụng sự kiên nhẫn nông nghiệp cho mục tiêu dài hạn.', 'Bạn trở lại để sử dụng kiến thức đất cho tính bền vững.', 'Bạn đến để sử dụng độ chính xác nông nghiệp cho công việc chi tiết.', 'Bạn trở lại để sử dụng bản năng đất cho trực giác.', 'Bạn đến để sử dụng trách nhiệm nông nghiệp cho cung cấp.', 'Bạn trở lại để sử dụng giảng dạy đất cho hướng dẫn.', 'Bạn đến để sử dụng sự thành thạo nông nghiệp cho xây dựng nền tảng.', 'Bạn trở lại để sử dụng kiến thức đất cho đổi mới.'],
        id: ['Anda datang untuk menggunakan keterampilan pertanian masa lalu dalam kesabaran dan pemeliharaan.', 'Anda kembali untuk menerapkan kebijaksanaan tanah pada pertumbuhan dan pengembangan.', 'Anda datang untuk menggunakan kesabaran pertanian untuk tujuan jangka panjang.', 'Anda kembali untuk menggunakan pengetahuan tanah untuk keberlanjutan.', 'Anda datang untuk menggunakan presisi pertanian untuk pekerjaan detail.', 'Anda kembali untuk menggunakan insting tanah untuk intuisi.', 'Anda datang untuk menggunakan tanggung jawab pertanian untuk penyediaan.', 'Anda kembali untuk menggunakan pengajaran tanah untuk bimbingan.', 'Anda datang untuk menggunakan penguasaan pertanian untuk membangun fondasi.', 'Anda kembali untuk menggunakan pengetahuan tanah untuk inovasi.']
      },
      lifeCount: {
        en: ['This is your 20th reincarnation.', 'You have lived a total of 27 lives so far.', 'This life is your 18th experience.', 'You have reincarnated 24 times up to this life.', 'This life follows your 19th past life.', 'You have lived 30 lives so far.', 'This is your 21st life.', 'You have reincarnated 26 times up to this life.', 'This life is a new beginning after your 22nd past life.', 'You have built farming experience through 33 lives.'],
        ja: ['これはあなたの20回目の転生です。', 'これまでに合計27回の人生を生きました。', '今生は18回目の経験です。', '今生までに24回転生しました。', '今生は19番目の前世の後に続きます。', 'これまでに30回の人生を生きました。', '今生は21回目の人生です。', '今生までに26回転生しました。', '今生は22番目の前世を経た新たな始まりです。', 'これまでに33回の人生で農業の経験を積みました。'],
        'zh-CN': ['这是你的第20次转生。', '截至目前你总共经历了27次人生。', '今生是你的第18次体验。', '到今生为止你已经转生了24次。', '今生延续自你的第19次前世。', '截至目前你已经经历了30次人生。', '今生是你的第21次人生。', '到今生为止你已经转生了26次。', '今生是你第22次前世后的新开始。', '通过33次人生你积累了农业经验。'],
        'zh-TW': ['這是你的第20次轉生。', '截至目前你總共經歷了27次人生。', '今生是你的第18次體驗。', '到今生為止你已經轉生了24次。', '今生延續自你的第19次前世。', '截至目前你已經經歷了30次人生。', '今生是你的第21次人生。', '到今生為止你已經轉生了26次。', '今生是你第22次前世後的新開始。', '通過33次人生你積累了農業經驗。'],
        vi: ['Đây là lần tái sinh thứ 20 của bạn.', 'Bạn đã sống tổng cộng 27 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 18 của bạn.', 'Bạn đã tái sinh 24 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 19 của bạn.', 'Bạn đã sống 30 kiếp cho đến nay.', 'Đây là kiếp thứ 21 của bạn.', 'Bạn đã tái sinh 26 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 22 của bạn.', 'Bạn đã tích lũy kinh nghiệm nông nghiệp qua 33 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-20 Anda.', 'Anda telah menjalani total 27 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-18 Anda.', 'Anda telah bereinkarnasi 24 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-19 Anda.', 'Anda telah menjalani 30 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-21 Anda.', 'Anda telah bereinkarnasi 26 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-22 Anda.', 'Anda telah membangun pengalaman pertanian melalui 33 kehidupan.']
      }
    }
  },
  37: {
    reincarnation: {
      era: {
        en: ['You were an ancient Egyptian shepherd.', 'In your past life, you were an ancient Chinese shepherd.', 'You were a Roman shepherd.', 'In your past life, you were a Greek shepherd.', 'You were a Japanese shepherd.', 'In your past life, you were an Indian shepherd.', 'You were a Celtic shepherd.', 'In your past life, you were a Persian shepherd.', 'You were a Mayan shepherd.', 'In your past life, you were a Korean shepherd.'],
        ja: ['あなたは古代エジプトの羊飼いでした。', '前世であなたは古代中国の羊飼いでした。', 'あなたはローマの羊飼いでした。', '前世であなたはギリシャの羊飼いでした。', 'あなたは日本の羊飼いでした。', '前世であなたはインドの羊飼いでした。', 'あなたはケルトの羊飼いでした。', '前世であなたはペルシャの羊飼いでした。', 'あなたはマヤの羊飼いでした。', '前世であなたは韓国の羊飼いでした。'],
        'zh-CN': ['你是古埃及的牧羊人。', '你的前世是古代中国的牧羊人。', '你是罗马的牧羊人。', '你的前世是希腊的牧羊人。', '你是日本的牧羊人。', '你的前世是印度的牧羊人。', '你是凯尔特的牧羊人。', '你的前世是波斯的牧羊人。', '你是玛雅的牧羊人。', '你的前世是韩国的牧羊人。'],
        'zh-TW': ['你是古埃及的牧羊人。', '你的前世是古代中國的牧羊人。', '你是羅馬的牧羊人。', '你的前世是希臘的牧羊人。', '你是日本的牧羊人。', '你的前世是印度的牧羊人。', '你是凱爾特的牧羊人。', '你的前世是波斯的牧羊人。', '你是瑪雅的牧羊人。', '你的前世是韓國的牧羊人。'],
        vi: ['Bạn là một người chăn cừu Ai Cập cổ đại.', 'Ở kiếp trước, bạn là một người chăn cừu Trung Quốc cổ đại.', 'Bạn là một người chăn cừu La Mã.', 'Ở kiếp trước, bạn là một người chăn cừu Hy Lạp.', 'Bạn là một người chăn cừu Nhật Bản.', 'Ở kiếp trước, bạn là một người chăn cừu Ấn Độ.', 'Bạn là một người chăn cừu Celtic.', 'Ở kiếp trước, bạn là một người chăn cừu Ba Tư.', 'Bạn là một người chăn cừu Maya.', 'Ở kiếp trước, bạn là một người chăn cừu Hàn Quốc.'],
        id: ['Anda adalah penggembala Mesir kuno.', 'Di kehidupan lampau, Anda adalah penggembala Tiongkok kuno.', 'Anda adalah penggembala Romawi.', 'Di kehidupan lampau, Anda adalah penggembala Yunani.', 'Anda adalah penggembala Jepang.', 'Di kehidupan lampau, Anda adalah penggembala India.', 'Anda adalah penggembala Celtic.', 'Di kehidupan lampau, Anda adalah penggembala Persia.', 'Anda adalah penggembala Maya.', 'Di kehidupan lampau, Anda adalah penggembala Korea.']
      },
      occupation: {
        en: ['You were a sheep shepherd in your past life.', 'In your past life, you were a goat shepherd.', 'You were a cattle shepherd in your past life.', 'In your past life, you were a mixed flock shepherd.', 'You were a mountain shepherd in your past life.', 'In your past life, you were a valley shepherd.', 'You were a nomadic shepherd in your past life.', 'In your past life, you were a settled shepherd.', 'You were a royal shepherd in your past life.', 'In your past life, you were a shepherding teacher.'],
        ja: ['あなたは前世で羊の羊飼いでした。', '前世であなたは山羊の羊飼いでした。', 'あなたは前世で牛の羊飼いでした。', '前世であなたは混合群の羊飼いでした。', 'あなたは前世で山の羊飼いでした。', '前世であなたは谷の羊飼いでした。', 'あなたは前世で遊牧羊飼いでした。', '前世であなたは定住羊飼いでした。', 'あなたは前世で王室羊飼いでした。', '前世であなたは羊飼い教師でした。'],
        'zh-CN': ['你的前世是牧羊人。', '你的前世是牧羊人。', '你的前世是牧牛人。', '你的前世是混合羊群牧人。', '你的前世是山地牧人。', '你的前世是谷地牧人。', '你的前世是游牧牧人。', '你的前世是定居牧人。', '你的前世是王室牧人。', '你的前世是牧羊教师。'],
        'zh-TW': ['你的前世是牧羊人。', '你的前世是牧羊人。', '你的前世是牧牛人。', '你的前世是混合羊群牧人。', '你的前世是山地牧人。', '你的前世是谷地牧人。', '你的前世是遊牧牧人。', '你的前世是定居牧人。', '你的前世是王室牧人。', '你的前世是牧羊教師。'],
        vi: ['Bạn từng là người chăn cừu ở kiếp trước.', 'Ở kiếp trước, bạn là người chăn dê.', 'Bạn từng là người chăn bò ở kiếp trước.', 'Ở kiếp trước, bạn là người chăn đàn hỗn hợp.', 'Bạn từng là người chăn núi ở kiếp trước.', 'Ở kiếp trước, bạn là người chăn thung lũng.', 'Bạn từng là người chăn du mục ở kiếp trước.', 'Ở kiếp trước, bạn là người chăn định cư.', 'Bạn từng là người chăn hoàng gia ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên chăn cừu.'],
        id: ['Di kehidupan lampau, Anda adalah penggembala domba.', 'Di kehidupan lampau, Anda adalah penggembala kambing.', 'Di kehidupan lampau, Anda adalah penggembala sapi.', 'Di kehidupan lampau, Anda adalah penggembala kawanan campuran.', 'Di kehidupan lampau, Anda adalah penggembala gunung.', 'Di kehidupan lampau, Anda adalah penggembala lembah.', 'Di kehidupan lampau, Anda adalah penggembala nomaden.', 'Di kehidupan lampau, Anda adalah penggembala menetap.', 'Di kehidupan lampau, Anda adalah penggembala kerajaan.', 'Di kehidupan lampau, Anda adalah guru penggembalaan.']
      },
      reason: {
        en: ['You came to use past shepherding skills in leadership and guidance.', 'You returned to apply animal wisdom to nurturing others.', 'You came to use shepherding patience for persistence.', 'You returned to use animal knowledge for protection.', 'You came to use shepherding precision for detailed work.', 'You returned to use animal instincts for intuition.', 'You came to use shepherding responsibility for care.', 'You returned to use animal teaching for guidance.', 'You came to use shepherding mastery for foundation building.', 'You returned to use animal knowledge for innovation.'],
        ja: ['前世の羊飼い技術を今生のリーダーシップと指導に活かすために来ました。', '前世の動物知恵を今生の他者育成に用いるために来ました。', '前世の羊飼い忍耐を今生の持続性に活かすために来ました。', '前世の動物知識を今生の保護に用いるために来ました。', '前世の羊飼い精密さを今生の詳細作業に活かすために来ました。', '前世の動物本能を今生の直感に用いるために来ました。', '前世の羊飼い責任を今生のケアに活かすために来ました。', '前世の動物教育を今生の指導に用いるために来ました。', '前世の羊飼い習得を今生の基盤構築に活かすために来ました。', '前世の動物知識を今生の革新に用いるために来ました。'],
        'zh-CN': ['你为了将前世的牧羊技能用于今生的领导力和指导而来。', '你为了将前世的动物智慧用于今生的培育他人而来。', '你为了将前世的牧羊耐心用于今生的坚持而来。', '你为了将前世的动物知识用于今生的保护而来。', '你为了将前世的牧羊精度用于今生的细致工作而来。', '你为了将前世的动物本能用于今生的直觉而来。', '你为了将前世的牧羊责任用于今生的照顾而来。', '你为了将前世的动物教学用于今生的指导而来。', '你为了将前世的牧羊掌握用于今生的基础建设而来。', '你为了将前世的动物知识用于今生的创新而来。'],
        'zh-TW': ['你為了將前世的牧羊技能用於今生的領導力和指導而來。', '你為了將前世的動物智慧用於今生的培育他人而來。', '你為了將前世的牧羊耐心用於今生的堅持而來。', '你為了將前世的動物知識用於今生的保護而來。', '你為了將前世的牧羊精度用於今生的細緻工作而來。', '你為了將前世的動物本能用於今生的直覺而來。', '你為了將前世的牧羊責任用於今生的照顧而來。', '你為了將前世的動物教學用於今生的指導而來。', '你為了將前世的牧羊掌握用於今生的基礎建設而來。', '你為了將前世的動物知識用於今生的創新而來。'],
        vi: ['Bạn đến để sử dụng kỹ năng chăn cừu từ kiếp trước trong lãnh đạo và hướng dẫn.', 'Bạn trở lại để áp dụng trí tuệ động vật vào nuôi dưỡng người khác.', 'Bạn đến để sử dụng sự kiên nhẫn chăn cừu cho sự bền bỉ.', 'Bạn trở lại để sử dụng kiến thức động vật cho bảo vệ.', 'Bạn đến để sử dụng độ chính xác chăn cừu cho công việc chi tiết.', 'Bạn trở lại để sử dụng bản năng động vật cho trực giác.', 'Bạn đến để sử dụng trách nhiệm chăn cừu cho chăm sóc.', 'Bạn trở lại để sử dụng giảng dạy động vật cho hướng dẫn.', 'Bạn đến để sử dụng sự thành thạo chăn cừu cho xây dựng nền tảng.', 'Bạn trở lại để sử dụng kiến thức động vật cho đổi mới.'],
        id: ['Anda datang untuk menggunakan keterampilan penggembalaan masa lalu dalam kepemimpinan dan bimbingan.', 'Anda kembali untuk menerapkan kebijaksanaan hewan pada memelihara orang lain.', 'Anda datang untuk menggunakan kesabaran penggembalaan untuk ketekunan.', 'Anda kembali untuk menggunakan pengetahuan hewan untuk perlindungan.', 'Anda datang untuk menggunakan presisi penggembalaan untuk pekerjaan detail.', 'Anda kembali untuk menggunakan insting hewan untuk intuisi.', 'Anda datang untuk menggunakan tanggung jawab penggembalaan untuk perawatan.', 'Anda kembali untuk menggunakan pengajaran hewan untuk bimbingan.', 'Anda datang untuk menggunakan penguasaan penggembalaan untuk membangun fondasi.', 'Anda kembali untuk menggunakan pengetahuan hewan untuk inovasi.']
      },
      lifeCount: {
        en: ['This is your 21st reincarnation.', 'You have lived a total of 28 lives so far.', 'This life is your 19th experience.', 'You have reincarnated 25 times up to this life.', 'This life follows your 20th past life.', 'You have lived 31 lives so far.', 'This is your 22nd life.', 'You have reincarnated 27 times up to this life.', 'This life is a new beginning after your 23rd past life.', 'You have built shepherding experience through 34 lives.'],
        ja: ['これはあなたの21回目の転生です。', 'これまでに合計28回の人生を生きました。', '今生は19回目の経験です。', '今生までに25回転生しました。', '今生は20番目の前世の後に続きます。', 'これまでに31回の人生を生きました。', '今生は22回目の人生です。', '今生までに27回転生しました。', '今生は23番目の前世を経た新たな始まりです。', 'これまでに34回の人生で羊飼いの経験を積みました。'],
        'zh-CN': ['这是你的第21次转生。', '截至目前你总共经历了28次人生。', '今生是你的第19次体验。', '到今生为止你已经转生了25次。', '今生延续自你的第20次前世。', '截至目前你已经经历了31次人生。', '今生是你的第22次人生。', '到今生为止你已经转生了27次。', '今生是你第23次前世后的新开始。', '通过34次人生你积累了牧羊经验。'],
        'zh-TW': ['這是你的第21次轉生。', '截至目前你總共經歷了28次人生。', '今生是你的第19次體驗。', '到今生為止你已經轉生了25次。', '今生延續自你的第20次前世。', '截至目前你已經經歷了31次人生。', '今生是你的第22次人生。', '到今生為止你已經轉生了27次。', '今生是你第23次前世後的新開始。', '通過34次人生你積累了牧羊經驗。'],
        vi: ['Đây là lần tái sinh thứ 21 của bạn.', 'Bạn đã sống tổng cộng 28 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 19 của bạn.', 'Bạn đã tái sinh 25 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 20 của bạn.', 'Bạn đã sống 31 kiếp cho đến nay.', 'Đây là kiếp thứ 22 của bạn.', 'Bạn đã tái sinh 27 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 23 của bạn.', 'Bạn đã tích lũy kinh nghiệm chăn cừu qua 34 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-21 Anda.', 'Anda telah menjalani total 28 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-19 Anda.', 'Anda telah bereinkarnasi 25 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-20 Anda.', 'Anda telah menjalani 31 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-22 Anda.', 'Anda telah bereinkarnasi 27 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-23 Anda.', 'Anda telah membangun pengalaman penggembalaan melalui 34 kehidupan.']
      }
    }
  }
};