import { FaceReincarnationTranslations } from '../merge';

export const batch29: FaceReincarnationTranslations = {
  38: {
    reincarnation: {
      era: {
        en: ['You were an ancient Egyptian fisherman.', 'In your past life, you were an ancient Chinese fisherman.', 'You were a Roman fisherman.', 'In your past life, you were a Greek fisherman.', 'You were a Japanese fisherman.', 'In your past life, you were an Indian fisherman.', 'You were a Celtic fisherman.', 'In your past life, you were a Persian fisherman.', 'You were a Mayan fisherman.', 'In your past life, you were a Korean fisherman.'],
        ja: ['あなたは古代エジプトの漁師でした。', '前世であなたは古代中国の漁師でした。', 'あなたはローマの漁師でした。', '前世であなたはギリシャの漁師でした。', 'あなたは日本の漁師でした。', '前世であなたはインドの漁師でした。', 'あなたはケルトの漁師でした。', '前世であなたはペルシャの漁師でした。', 'あなたはマヤの漁師でした。', '前世であなたは韓国の漁師でした。'],
        'zh-CN': ['你是古埃及的渔夫。', '你的前世是古代中国的渔夫。', '你是罗马的渔夫。', '你的前世是希腊的渔夫。', '你是日本的渔夫。', '你的前世是印度的渔夫。', '你是凯尔特的渔夫。', '你的前世是波斯的渔夫。', '你是玛雅的渔夫。', '你的前世是韩国的渔夫。'],
        'zh-TW': ['你是古埃及的漁夫。', '你的前世是古代中國的漁夫。', '你是羅馬的漁夫。', '你的前世是希臘的漁夫。', '你是日本的漁夫。', '你的前世是印度的漁夫。', '你是凱爾特的漁夫。', '你的前世是波斯的漁夫。', '你是瑪雅的漁夫。', '你的前世是韓國的漁夫。'],
        vi: ['Bạn là một ngư dân Ai Cập cổ đại.', 'Ở kiếp trước, bạn là một ngư dân Trung Quốc cổ đại.', 'Bạn là một ngư dân La Mã.', 'Ở kiếp trước, bạn là một ngư dân Hy Lạp.', 'Bạn là một ngư dân Nhật Bản.', 'Ở kiếp trước, bạn là một ngư dân Ấn Độ.', 'Bạn là một ngư dân Celtic.', 'Ở kiếp trước, bạn là một ngư dân Ba Tư.', 'Bạn là một ngư dân Maya.', 'Ở kiếp trước, bạn là một ngư dân Hàn Quốc.'],
        id: ['Anda adalah nelayan Mesir kuno.', 'Di kehidupan lampau, Anda adalah nelayan Tiongkok kuno.', 'Anda adalah nelayan Romawi.', 'Di kehidupan lampau, Anda adalah nelayan Yunani.', 'Anda adalah nelayan Jepang.', 'Di kehidupan lampau, Anda adalah nelayan India.', 'Anda adalah nelayan Celtic.', 'Di kehidupan lampau, Anda adalah nelayan Persia.', 'Anda adalah nelayan Maya.', 'Di kehidupan lampau, Anda adalah nelayan Korea.']
      },
      occupation: {
        en: ['You were a deep sea fisherman in your past life.', 'In your past life, you were a river fisherman.', 'You were a lake fisherman in your past life.', 'In your past life, you were a coastal fisherman.', 'You were a commercial fisherman in your past life.', 'In your past life, you were a subsistence fisherman.', 'You were a ceremonial fisherman in your past life.', 'In your past life, you were a fish trader.', 'You were a net maker in your past life.', 'In your past life, you were a fishing teacher.'],
        ja: ['あなたは前世で深海漁師でした。', '前世であなたは川漁師でした。', 'あなたは前世で湖漁師でした。', '前世であなたは沿岸漁師でした。', 'あなたは前世で商業漁師でした。', '前世であなたは自給漁師でした。', 'あなたは前世で儀式用漁師でした。', '前世であなたは魚商人でした。', 'あなたは前世で網職人でした。', '前世であなたは漁業教師でした。'],
        'zh-CN': ['你的前世是深海渔夫。', '你的前世是河渔夫。', '你的前世是湖渔夫。', '你的前世是沿海渔夫。', '你的前世是商业渔夫。', '你的前世是自给渔夫。', '你的前世是仪式渔夫。', '你的前世是鱼商。', '你的前世是制网师。', '你的前世是渔业教师。'],
        'zh-TW': ['你的前世是深海漁夫。', '你的前世是河漁夫。', '你的前世是湖漁夫。', '你的前世是沿海漁夫。', '你的前世是商業漁夫。', '你的前世是自給漁夫。', '你的前世是儀式漁夫。', '你的前世是魚商。', '你的前世是製網師。', '你的前世是漁業教師。'],
        vi: ['Bạn từng là ngư dân biển sâu ở kiếp trước.', 'Ở kiếp trước, bạn là ngư dân sông.', 'Bạn từng là ngư dân hồ ở kiếp trước.', 'Ở kiếp trước, bạn là ngư dân ven biển.', 'Bạn từng là ngư dân thương mại ở kiếp trước.', 'Ở kiếp trước, bạn là ngư dân tự cung tự cấp.', 'Bạn từng là ngư dân nghi lễ ở kiếp trước.', 'Ở kiếp trước, bạn là thương nhân cá.', 'Bạn từng là thợ làm lưới ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên đánh cá.'],
        id: ['Di kehidupan lampau, Anda adalah nelayan laut dalam.', 'Di kehidupan lampau, Anda adalah nelayan sungai.', 'Di kehidupan lampau, Anda adalah nelayan danau.', 'Di kehidupan lampau, Anda adalah nelayan pantai.', 'Di kehidupan lampau, Anda adalah nelayan komersial.', 'Di kehidupan lampau, Anda adalah nelayan subsisten.', 'Di kehidupan lampau, Anda adalah nelayan upacara.', 'Di kehidupan lampau, Anda adalah pedagang ikan.', 'Di kehidupan lampau, Anda adalah pembuat jaring.', 'Di kehidupan lampau, Anda adalah guru memancing.']
      },
      reason: {
        en: ['You came to use past fishing skills in patience and persistence.', 'You returned to apply water wisdom to emotional flow.', 'You came to use fishing patience for long-term goals.', 'You returned to use water knowledge for adaptability.', 'You came to use fishing precision for detailed work.', 'You returned to use water instincts for intuition.', 'You came to use fishing responsibility for provision.', 'You returned to use water teaching for guidance.', 'You came to use fishing mastery for foundation building.', 'You returned to use water knowledge for innovation.'],
        ja: ['前世の漁業技術を今生の忍耐と持続性に活かすために来ました。', '前世の水の知恵を今生の感情の流れに用いるために来ました。', '前世の漁業忍耐を今生の長期目標に活かすために来ました。', '前世の水の知識を今生の適応性に用いるために来ました。', '前世の漁業精密さを今生の詳細作業に活かすために来ました。', '前世の水の本能を今生の直感に用いるために来ました。', '前世の漁業責任を今生の供給に活かすために来ました。', '前世の水の教育を今生の指導に用いるために来ました。', '前世の漁業習得を今生の基盤構築に活かすために来ました。', '前世の水の知識を今生の革新に用いるために来ました。'],
        'zh-CN': ['你为了将前世的捕鱼技能用于今生的耐心和坚持而来。', '你为了将前世的水智慧用于今生的情感流动而来。', '你为了将前世的捕鱼耐心用于今生的长期目标而来。', '你为了将前世的水知识用于今生的适应性而来。', '你为了将前世的捕鱼精度用于今生的细致工作而来。', '你为了将前世的水本能用于今生的直觉而来。', '你为了将前世的捕鱼责任用于今生的供给而来。', '你为了将前世的水教学用于今生的指导而来。', '你为了将前世的捕鱼掌握用于今生的基础建设而来。', '你为了将前世的水知识用于今生的创新而来。'],
        'zh-TW': ['你為了將前世的捕魚技能用於今生的耐心和堅持而來。', '你為了將前世的水智慧用於今生的情感流動而來。', '你為了將前世的捕魚耐心用於今生的長期目標而來。', '你為了將前世的水知識用於今生的適應性而來。', '你為了將前世的捕魚精度用於今生的細緻工作而來。', '你為了將前世的水本能用於今生的直覺而來。', '你為了將前世的捕魚責任用於今生的供給而來。', '你為了將前世的水教學用於今生的指導而來。', '你為了將前世的捕魚掌握用於今生的基礎建設而來。', '你為了將前世的水知識用於今生的創新而來。'],
        vi: ['Bạn đến để sử dụng kỹ năng đánh cá từ kiếp trước trong sự kiên nhẫn và bền bỉ.', 'Bạn trở lại để áp dụng trí tuệ nước vào dòng chảy cảm xúc.', 'Bạn đến để sử dụng sự kiên nhẫn đánh cá cho mục tiêu dài hạn.', 'Bạn trở lại để sử dụng kiến thức nước cho khả năng thích ứng.', 'Bạn đến để sử dụng độ chính xác đánh cá cho công việc chi tiết.', 'Bạn trở lại để sử dụng bản năng nước cho trực giác.', 'Bạn đến để sử dụng trách nhiệm đánh cá cho cung cấp.', 'Bạn trở lại để sử dụng giảng dạy nước cho hướng dẫn.', 'Bạn đến để sử dụng sự thành thạo đánh cá cho xây dựng nền tảng.', 'Bạn trở lại để sử dụng kiến thức nước cho đổi mới.'],
        id: ['Anda datang untuk menggunakan keterampilan memancing masa lalu dalam kesabaran dan ketekunan.', 'Anda kembali untuk menerapkan kebijaksanaan air pada aliran emosional.', 'Anda datang untuk menggunakan kesabaran memancing untuk tujuan jangka panjang.', 'Anda kembali untuk menggunakan pengetahuan air untuk adaptabilitas.', 'Anda datang untuk menggunakan presisi memancing untuk pekerjaan detail.', 'Anda kembali untuk menggunakan insting air untuk intuisi.', 'Anda datang untuk menggunakan tanggung jawab memancing untuk penyediaan.', 'Anda kembali untuk menggunakan pengajaran air untuk bimbingan.', 'Anda datang untuk menggunakan penguasaan memancing untuk membangun fondasi.', 'Anda kembali untuk menggunakan pengetahuan air untuk inovasi.']
      },
      lifeCount: {
        en: ['This is your 22nd reincarnation.', 'You have lived a total of 29 lives so far.', 'This life is your 20th experience.', 'You have reincarnated 26 times up to this life.', 'This life follows your 21st past life.', 'You have lived 32 lives so far.', 'This is your 23rd life.', 'You have reincarnated 28 times up to this life.', 'This life is a new beginning after your 24th past life.', 'You have built fishing experience through 35 lives.'],
        ja: ['これはあなたの22回目の転生です。', 'これまでに合計29回の人生を生きました。', '今生は20回目の経験です。', '今生までに26回転生しました。', '今生は21番目の前世の後に続きます。', 'これまでに32回の人生を生きました。', '今生は23回目の人生です。', '今生までに28回転生しました。', '今生は24番目の前世を経た新たな始まりです。', 'これまでに35回の人生で漁業の経験を積みました。'],
        'zh-CN': ['这是你的第22次转生。', '截至目前你总共经历了29次人生。', '今生是你的第20次体验。', '到今生为止你已经转生了26次。', '今生延续自你的第21次前世。', '截至目前你已经经历了32次人生。', '今生是你的第23次人生。', '到今生为止你已经转生了28次。', '今生是你第24次前世后的新开始。', '通过35次人生你积累了捕鱼经验。'],
        'zh-TW': ['這是你的第22次轉生。', '截至目前你總共經歷了29次人生。', '今生是你的第20次體驗。', '到今生為止你已經轉生了26次。', '今生延續自你的第21次前世。', '截至目前你已經經歷了32次人生。', '今生是你的第23次人生。', '到今生為止你已經轉生了28次。', '今生是你第24次前世後的新開始。', '通過35次人生你積累了捕魚經驗。'],
        vi: ['Đây là lần tái sinh thứ 22 của bạn.', 'Bạn đã sống tổng cộng 29 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 20 của bạn.', 'Bạn đã tái sinh 26 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 21 của bạn.', 'Bạn đã sống 32 kiếp cho đến nay.', 'Đây là kiếp thứ 23 của bạn.', 'Bạn đã tái sinh 28 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 24 của bạn.', 'Bạn đã tích lũy kinh nghiệm đánh cá qua 35 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-22 Anda.', 'Anda telah menjalani total 29 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-20 Anda.', 'Anda telah bereinkarnasi 26 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-21 Anda.', 'Anda telah menjalani 32 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-23 Anda.', 'Anda telah bereinkarnasi 28 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-24 Anda.', 'Anda telah membangun pengalaman memancing melalui 35 kehidupan.']
      }
    }
  },
  39: {
    reincarnation: {
      era: {
        en: ['You were an ancient Egyptian merchant.', 'In your past life, you were an ancient Chinese merchant.', 'You were a Roman merchant.', 'In your past life, you were a Greek merchant.', 'You were a Japanese merchant.', 'In your past life, you were an Indian merchant.', 'You were a Celtic merchant.', 'In your past life, you were a Persian merchant.', 'You were a Mayan merchant.', 'In your past life, you were a Korean merchant.'],
        ja: ['あなたは古代エジプトの商人でした。', '前世であなたは古代中国の商人でした。', 'あなたはローマの商人でした。', '前世であなたはギリシャの商人でした。', 'あなたは日本の商人でした。', '前世であなたはインドの商人でした。', 'あなたはケルトの商人でした。', '前世であなたはペルシャの商人でした。', 'あなたはマヤの商人でした。', '前世であなたは韓国の商人でした。'],
        'zh-CN': ['你是古埃及的商人。', '你的前世是古代中国的商人。', '你是罗马的商人。', '你的前世是希腊的商人。', '你是日本的商人。', '你的前世是印度的商人。', '你是凯尔特的商人。', '你的前世是波斯的商人。', '你是玛雅的商人。', '你的前世是韩国的商人。'],
        'zh-TW': ['你是古埃及的商人。', '你的前世是古代中國的商人。', '你是羅馬的商人。', '你的前世是希臘的商人。', '你是日本的商人。', '你的前世是印度的商人。', '你是凱爾特的商人。', '你的前世是波斯的商人。', '你是瑪雅的商人。', '你的前世是韓國的商人。'],
        vi: ['Bạn là một thương nhân Ai Cập cổ đại.', 'Ở kiếp trước, bạn là một thương nhân Trung Quốc cổ đại.', 'Bạn là một thương nhân La Mã.', 'Ở kiếp trước, bạn là một thương nhân Hy Lạp.', 'Bạn là một thương nhân Nhật Bản.', 'Ở kiếp trước, bạn là một thương nhân Ấn Độ.', 'Bạn là một thương nhân Celtic.', 'Ở kiếp trước, bạn là một thương nhân Ba Tư.', 'Bạn là một thương nhân Maya.', 'Ở kiếp trước, bạn là một thương nhân Hàn Quốc.'],
        id: ['Anda adalah pedagang Mesir kuno.', 'Di kehidupan lampau, Anda adalah pedagang Tiongkok kuno.', 'Anda adalah pedagang Romawi.', 'Di kehidupan lampau, Anda adalah pedagang Yunani.', 'Anda adalah pedagang Jepang.', 'Di kehidupan lampau, Anda adalah pedagang India.', 'Anda adalah pedagang Celtic.', 'Di kehidupan lampau, Anda adalah pedagang Persia.', 'Anda adalah pedagang Maya.', 'Di kehidupan lampau, Anda adalah pedagang Korea.']
      },
      occupation: {
        en: ['You were a spice merchant in your past life.', 'In your past life, you were a silk merchant.', 'You were a gold merchant in your past life.', 'In your past life, you were a salt merchant.', 'You were a wine merchant in your past life.', 'In your past life, you were a textile merchant.', 'You were a pottery merchant in your past life.', 'In your past life, you were a grain merchant.', 'You were a jewelry merchant in your past life.', 'In your past life, you were a trading teacher.'],
        ja: ['あなたは前世で香辛料商人でした。', '前世であなたは絹商人でした。', 'あなたは前世で金商人でした。', '前世であなたは塩商人でした。', 'あなたは前世でワイン商人でした。', '前世であなたは織物商人でした。', 'あなたは前世で陶器商人でした。', '前世であなたは穀物商人でした。', 'あなたは前世で宝石商人でした。', '前世であなたは貿易教師でした。'],
        'zh-CN': ['你的前世是香料商人。', '你的前世是丝绸商人。', '你的前世是黄金商人。', '你的前世是盐商。', '你的前世是酒商。', '你的前世是纺织品商人。', '你的前世是陶器商人。', '你的前世是谷物商人。', '你的前世是珠宝商人。', '你的前世是贸易教师。'],
        'zh-TW': ['你的前世是香料商人。', '你的前世是絲綢商人。', '你的前世是黃金商人。', '你的前世是鹽商。', '你的前世是酒商。', '你的前世是紡織品商人。', '你的前世是陶器商人。', '你的前世是穀物商人。', '你的前世是珠寶商人。', '你的前世是貿易教師。'],
        vi: ['Bạn từng là thương nhân gia vị ở kiếp trước.', 'Ở kiếp trước, bạn là thương nhân lụa.', 'Bạn từng là thương nhân vàng ở kiếp trước.', 'Ở kiếp trước, bạn là thương nhân muối.', 'Bạn từng là thương nhân rượu ở kiếp trước.', 'Ở kiếp trước, bạn là thương nhân dệt may.', 'Bạn từng là thương nhân gốm ở kiếp trước.', 'Ở kiếp trước, bạn là thương nhân ngũ cốc.', 'Bạn từng là thương nhân trang sức ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên thương mại.'],
        id: ['Di kehidupan lampau, Anda adalah pedagang rempah-rempah.', 'Di kehidupan lampau, Anda adalah pedagang sutra.', 'Di kehidupan lampau, Anda adalah pedagang emas.', 'Di kehidupan lampau, Anda adalah pedagang garam.', 'Di kehidupan lampau, Anda adalah pedagang anggur.', 'Di kehidupan lampau, Anda adalah pedagang tekstil.', 'Di kehidupan lampau, Anda adalah pedagang tembikar.', 'Di kehidupan lampau, Anda adalah pedagang biji-bijian.', 'Di kehidupan lampau, Anda adalah pedagang perhiasan.', 'Di kehidupan lampau, Anda adalah guru perdagangan.']
      },
      reason: {
        en: ['You came to use past trading skills in negotiation and communication.', 'You returned to apply business wisdom to relationship building.', 'You came to use trading patience for long-term deals.', 'You returned to use business knowledge for strategy.', 'You came to use trading precision for detailed work.', 'You returned to use business instincts for intuition.', 'You came to use trading responsibility for fair exchange.', 'You returned to use business teaching for guidance.', 'You came to use trading mastery for foundation building.', 'You returned to use business knowledge for innovation.'],
        ja: ['前世の貿易技術を今生の交渉とコミュニケーションに活かすために来ました。', '前世のビジネス知恵を今生の関係構築に用いるために来ました。', '前世の貿易忍耐を今生の長期取引に活かすために来ました。', '前世のビジネス知識を今生の戦略に用いるために来ました。', '前世の貿易精密さを今生の詳細作業に活かすために来ました。', '前世のビジネス本能を今生の直感に用いるために来ました。', '前世の貿易責任を今生の公正な交換に活かすために来ました。', '前世のビジネス教育を今生の指導に用いるために来ました。', '前世の貿易習得を今生の基盤構築に活かすために来ました。', '前世のビジネス知識を今生の革新に用いるために来ました。'],
        'zh-CN': ['你为了将前世的贸易技能用于今生的谈判和沟通而来。', '你为了将前世的商业智慧用于今生的关系建设而来。', '你为了将前世的贸易耐心用于今生的长期交易而来。', '你为了将前世的商业知识用于今生的战略而来。', '你为了将前世的贸易精度用于今生的细致工作而来。', '你为了将前世的商业本能用于今生的直觉而来。', '你为了将前世的贸易责任用于今生的公平交换而来。', '你为了将前世的商业教学用于今生的指导而来。', '你为了将前世的贸易掌握用于今生的基础建设而来。', '你为了将前世的商业知识用于今生的创新而来。'],
        'zh-TW': ['你為了將前世的貿易技能用於今生的談判和溝通而來。', '你為了將前世的商業智慧用於今生的關係建設而來。', '你為了將前世的貿易耐心用於今生的長期交易而來。', '你為了將前世的商業知識用於今生的戰略而來。', '你為了將前世的貿易精度用於今生的細緻工作而來。', '你為了將前世的商業本能用於今生的直覺而來。', '你為了將前世的貿易責任用於今生的公平交換而來。', '你為了將前世的商業教學用於今生的指導而來。', '你為了將前世的貿易掌握用於今生的基礎建設而來。', '你為了將前世的商業知識用於今生的創新而來。'],
        vi: ['Bạn đến để sử dụng kỹ năng thương mại từ kiếp trước trong đàm phán và giao tiếp.', 'Bạn trở lại để áp dụng trí tuệ kinh doanh vào xây dựng mối quan hệ.', 'Bạn đến để sử dụng sự kiên nhẫn thương mại cho các giao dịch dài hạn.', 'Bạn trở lại để sử dụng kiến thức kinh doanh cho chiến lược.', 'Bạn đến để sử dụng độ chính xác thương mại cho công việc chi tiết.', 'Bạn trở lại để sử dụng bản năng kinh doanh cho trực giác.', 'Bạn đến để sử dụng trách nhiệm thương mại cho trao đổi công bằng.', 'Bạn trở lại để sử dụng giảng dạy kinh doanh cho hướng dẫn.', 'Bạn đến để sử dụng sự thành thạo thương mại cho xây dựng nền tảng.', 'Bạn trở lại để sử dụng kiến thức kinh doanh cho đổi mới.'],
        id: ['Anda datang untuk menggunakan keterampilan perdagangan masa lalu dalam negosiasi dan komunikasi.', 'Anda kembali untuk menerapkan kebijaksanaan bisnis pada pembangunan hubungan.', 'Anda datang untuk menggunakan kesabaran perdagangan untuk kesepakatan jangka panjang.', 'Anda kembali untuk menggunakan pengetahuan bisnis untuk strategi.', 'Anda datang untuk menggunakan presisi perdagangan untuk pekerjaan detail.', 'Anda kembali untuk menggunakan insting bisnis untuk intuisi.', 'Anda datang untuk menggunakan tanggung jawab perdagangan untuk pertukaran yang adil.', 'Anda kembali untuk menggunakan pengajaran bisnis untuk bimbingan.', 'Anda datang untuk menggunakan penguasaan perdagangan untuk membangun fondasi.', 'Anda kembali untuk menggunakan pengetahuan bisnis untuk inovasi.']
      },
      lifeCount: {
        en: ['This is your 23rd reincarnation.', 'You have lived a total of 30 lives so far.', 'This life is your 21st experience.', 'You have reincarnated 27 times up to this life.', 'This life follows your 22nd past life.', 'You have lived 33 lives so far.', 'This is your 24th life.', 'You have reincarnated 29 times up to this life.', 'This life is a new beginning after your 25th past life.', 'You have built trading experience through 36 lives.'],
        ja: ['これはあなたの23回目の転生です。', 'これまでに合計30回の人生を生きました。', '今生は21回目の経験です。', '今生までに27回転生しました。', '今生は22番目の前世の後に続きます。', 'これまでに33回の人生を生きました。', '今生は24回目の人生です。', '今生までに29回転生しました。', '今生は25番目の前世を経た新たな始まりです。', 'これまでに36回の人生で貿易の経験を積みました。'],
        'zh-CN': ['这是你的第23次转生。', '截至目前你总共经历了30次人生。', '今生是你的第21次体验。', '到今生为止你已经转生了27次。', '今生延续自你的第22次前世。', '截至目前你已经经历了33次人生。', '今生是你的第24次人生。', '到今生为止你已经转生了29次。', '今生是你第25次前世后的新开始。', '通过36次人生你积累了贸易经验。'],
        'zh-TW': ['這是你的第23次轉生。', '截至目前你總共經歷了30次人生。', '今生是你的第21次體驗。', '到今生為止你已經轉生了27次。', '今生延續自你的第22次前世。', '截至目前你已經經歷了33次人生。', '今生是你的第24次人生。', '到今生為止你已經轉生了29次。', '今生是你第25次前世後的新開始。', '通過36次人生你積累了貿易經驗。'],
        vi: ['Đây là lần tái sinh thứ 23 của bạn.', 'Bạn đã sống tổng cộng 30 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 21 của bạn.', 'Bạn đã tái sinh 27 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 22 của bạn.', 'Bạn đã sống 33 kiếp cho đến nay.', 'Đây là kiếp thứ 24 của bạn.', 'Bạn đã tái sinh 29 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 25 của bạn.', 'Bạn đã tích lũy kinh nghiệm thương mại qua 36 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-23 Anda.', 'Anda telah menjalani total 30 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-21 Anda.', 'Anda telah bereinkarnasi 27 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-22 Anda.', 'Anda telah menjalani 33 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-24 Anda.', 'Anda telah bereinkarnasi 29 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-25 Anda.', 'Anda telah membangun pengalaman perdagangan melalui 36 kehidupan.']
      }
    }
  }
};