import { FaceReincarnationTranslations } from '../merge';

export const batch33: FaceReincarnationTranslations = {
  46: {
    reincarnation: {
      era: {
        en: ['You were an ancient Egyptian musician.', 'In your past life, you were an ancient Chinese musician.', 'You were a Roman musician.', 'In your past life, you were a Greek musician.', 'You were a Japanese musician.', 'In your past life, you were an Indian musician.', 'You were a Celtic musician.', 'In your past life, you were a Persian musician.', 'You were a Mayan musician.', 'In your past life, you were a Korean musician.'],
        ja: ['あなたは古代エジプトの音楽家でした。', '前世であなたは古代中国の音楽家でした。', 'あなたはローマの音楽家でした。', '前世であなたはギリシャの音楽家でした。', 'あなたは日本の音楽家でした。', '前世であなたはインドの音楽家でした。', 'あなたはケルトの音楽家でした。', '前世であなたはペルシャの音楽家でした。', 'あなたはマヤの音楽家でした。', '前世であなたは韓国の音楽家でした。'],
        'zh-CN': ['你是古埃及的音乐家。', '你的前世是古代中国的音乐家。', '你是罗马的音乐家。', '你的前世是希腊的音乐家。', '你是日本的音乐家。', '你的前世是印度的音乐家。', '你是凯尔特的音乐家。', '你的前世是波斯的音乐家。', '你是玛雅的音乐家。', '你的前世是韩国的音乐家。'],
        'zh-TW': ['你是古埃及的音樂家。', '你的前世是古代中國的音樂家。', '你是羅馬的音樂家。', '你的前世是希臘的音樂家。', '你是日本的音樂家。', '你的前世是印度的音樂家。', '你是凱爾特的音樂家。', '你的前世是波斯的音樂家。', '你是瑪雅的音樂家。', '你的前世是韓國的音樂家。'],
        vi: ['Bạn là một nhạc sĩ Ai Cập cổ đại.', 'Ở kiếp trước, bạn là một nhạc sĩ Trung Quốc cổ đại.', 'Bạn là một nhạc sĩ La Mã.', 'Ở kiếp trước, bạn là một nhạc sĩ Hy Lạp.', 'Bạn là một nhạc sĩ Nhật Bản.', 'Ở kiếp trước, bạn là một nhạc sĩ Ấn Độ.', 'Bạn là một nhạc sĩ Celtic.', 'Ở kiếp trước, bạn là một nhạc sĩ Ba Tư.', 'Bạn là một nhạc sĩ Maya.', 'Ở kiếp trước, bạn là một nhạc sĩ Hàn Quốc.'],
        id: ['Anda adalah musisi Mesir kuno.', 'Di kehidupan lampau, Anda adalah musisi Tiongkok kuno.', 'Anda adalah musisi Romawi.', 'Di kehidupan lampau, Anda adalah musisi Yunani.', 'Anda adalah musisi Jepang.', 'Di kehidupan lampau, Anda adalah musisi India.', 'Anda adalah musisi Celtic.', 'Di kehidupan lampau, Anda adalah musisi Persia.', 'Anda adalah musisi Maya.', 'Di kehidupan lampau, Anda adalah musisi Korea.']
      },
      occupation: {
        en: ['You were a royal musician in your past life.', 'In your past life, you were a temple musician.', 'You were a court musician in your past life.', 'In your past life, you were a street musician.', 'You were a ceremonial musician in your past life.', 'In your past life, you were a military musician.', 'You were a traveling musician in your past life.', 'In your past life, you were a village musician.', 'You were a merchant musician in your past life.', 'In your past life, you were a music teacher.'],
        ja: ['あなたは前世で王室音楽家でした。', '前世であなたは寺院音楽家でした。', 'あなたは前世で宮廷音楽家でした。', '前世であなたはストリート音楽家でした。', 'あなたは前世で儀式音楽家でした。', '前世であなたは軍音楽家でした。', 'あなたは前世で旅音楽家でした。', '前世であなたは村音楽家でした。', 'あなたは前世で商人音楽家でした。', '前世であなたは音楽教師でした。'],
        'zh-CN': ['你的前世是王室音乐家。', '你的前世是寺庙音乐家。', '你的前世是宫廷音乐家。', '你的前世是街头音乐家。', '你的前世是仪式音乐家。', '你的前世是军乐家。', '你的前世是游方音乐家。', '你的前世是乡村音乐家。', '你的前世是商人音乐家。', '你的前世是音乐教师。'],
        'zh-TW': ['你的前世是王室音樂家。', '你的前世是寺廟音樂家。', '你的前世是宮廷音樂家。', '你的前世是街頭音樂家。', '你的前世是儀式音樂家。', '你的前世是軍樂家。', '你的前世是遊方音樂家。', '你的前世是鄉村音樂家。', '你的前世是商人音樂家。', '你的前世是音樂教師。'],
        vi: ['Bạn từng là nhạc sĩ hoàng gia ở kiếp trước.', 'Ở kiếp trước, bạn là nhạc sĩ đền thờ.', 'Bạn từng là nhạc sĩ triều đình ở kiếp trước.', 'Ở kiếp trước, bạn là nhạc sĩ đường phố.', 'Bạn từng là nhạc sĩ nghi lễ ở kiếp trước.', 'Ở kiếp trước, bạn là nhạc sĩ quân đội.', 'Bạn từng là nhạc sĩ du hành ở kiếp trước.', 'Ở kiếp trước, bạn là nhạc sĩ làng.', 'Bạn từng là nhạc sĩ thương nhân ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên âm nhạc.'],
        id: ['Di kehidupan lampau, Anda adalah musisi kerajaan.', 'Di kehidupan lampau, Anda adalah musisi kuil.', 'Di kehidupan lampau, Anda adalah musisi istana.', 'Di kehidupan lampau, Anda adalah musisi jalanan.', 'Di kehidupan lampau, Anda adalah musisi upacara.', 'Di kehidupan lampau, Anda adalah musisi militer.', 'Di kehidupan lampau, Anda adalah musisi keliling.', 'Di kehidupan lampau, Anda adalah musisi desa.', 'Di kehidupan lampau, Anda adalah musisi pedagang.', 'Di kehidupan lampau, Anda adalah guru musik.']
      },
      reason: {
        en: ['You came to use past musical skills in creativity and expression.', 'You returned to apply musical wisdom to emotional healing.', 'You came to use musical patience for detailed composition.', 'You returned to use musical knowledge for inspiration.', 'You came to use musical precision for harmony.', 'You returned to use musical instincts for intuition.', 'You came to use musical responsibility for cultural preservation.', 'You returned to use musical teaching for guidance.', 'You came to use musical mastery for foundation building.', 'You returned to use musical knowledge for innovation.'],
        ja: ['前世の音楽技術を今生の創造性と表現に活かすために来ました。', '前世の音楽知恵を今生の感情的癒しに用いるために来ました。', '前世の音楽忍耐を今生の詳細作曲に活かすために来ました。', '前世の音楽知識を今生のインスピレーションに用いるために来ました。', '前世の音楽精密さを今生の調和に活かすために来ました。', '前世の音楽本能を今生の直感に用いるために来ました。', '前世の音楽責任を今生の文化保存に活かすために来ました。', '前世の音楽教育を今生の指導に用いるために来ました。', '前世の音楽習得を今生の基盤構築に活かすために来ました。', '前世の音楽知識を今生の革新に用いるために来ました。'],
        'zh-CN': ['你为了将前世的音乐技能用于今生的创造性和表达而来。', '你为了将前世的音乐智慧用于今生的情感治愈而来。', '你为了将前世的音乐耐心用于今生的详细作曲而来。', '你为了将前世的音乐知识用于今生的灵感而来。', '你为了将前世的音乐精度用于今生的和谐而来。', '你为了将前世的音乐本能用于今生的直觉而来。', '你为了将前世的音乐责任用于今生的文化保护而来。', '你为了将前世的音乐教学用于今生的指导而来。', '你为了将前世的音乐掌握用于今生的基础建设而来。', '你为了将前世的音乐知识用于今生的创新而来。'],
        'zh-TW': ['你為了將前世的音樂技能用於今生的創造性和表達而來。', '你為了將前世的音樂智慧用於今生的情感治愈而來。', '你為了將前世的音樂耐心用於今生的詳細作曲而來。', '你為了將前世的音樂知識用於今生的靈感而來。', '你為了將前世的音樂精度用於今生的和諧而來。', '你為了將前世的音樂本能用於今生的直覺而來。', '你為了將前世的音樂責任用於今生的文化保護而來。', '你為了將前世的音樂教學用於今生的指導而來。', '你為了將前世的音樂掌握用於今生的基礎建設而來。', '你為了將前世的音樂知識用於今生的創新而來。'],
        vi: ['Bạn đến để sử dụng kỹ năng âm nhạc từ kiếp trước trong sự sáng tạo và biểu đạt.', 'Bạn trở lại để áp dụng trí tuệ âm nhạc vào chữa lành cảm xúc.', 'Bạn đến để sử dụng sự kiên nhẫn âm nhạc cho sáng tác chi tiết.', 'Bạn trở lại để sử dụng kiến thức âm nhạc cho cảm hứng.', 'Bạn đến để sử dụng độ chính xác âm nhạc cho sự hài hòa.', 'Bạn trở lại để sử dụng bản năng âm nhạc cho trực giác.', 'Bạn đến để sử dụng trách nhiệm âm nhạc cho bảo tồn văn hóa.', 'Bạn trở lại để sử dụng giảng dạy âm nhạc cho hướng dẫn.', 'Bạn đến để sử dụng sự thành thạo âm nhạc cho xây dựng nền tảng.', 'Bạn trở lại để sử dụng kiến thức âm nhạc cho đổi mới.'],
        id: ['Anda datang untuk menggunakan keterampilan musik masa lalu dalam kreativitas dan ekspresi.', 'Anda kembali untuk menerapkan kebijaksanaan musik pada penyembuhan emosional.', 'Anda datang untuk menggunakan kesabaran musik untuk komposisi detail.', 'Anda kembali untuk menggunakan pengetahuan musik untuk inspirasi.', 'Anda datang untuk menggunakan presisi musik untuk harmoni.', 'Anda kembali untuk menggunakan insting musik untuk intuisi.', 'Anda datang untuk menggunakan tanggung jawab musik untuk pelestarian budaya.', 'Anda kembali untuk menggunakan pengajaran musik untuk bimbingan.', 'Anda datang untuk menggunakan penguasaan musik untuk membangun fondasi.', 'Anda kembali untuk menggunakan pengetahuan musik untuk inovasi.']
      },
      lifeCount: {
        en: ['This is your 30th reincarnation.', 'You have lived a total of 37 lives so far.', 'This life is your 28th experience.', 'You have reincarnated 34 times up to this life.', 'This life follows your 29th past life.', 'You have lived 40 lives so far.', 'This is your 31st life.', 'You have reincarnated 36 times up to this life.', 'This life is a new beginning after your 32nd past life.', 'You have built musical experience through 43 lives.'],
        ja: ['これはあなたの30回目の転生です。', 'これまでに合計37回の人生を生きました。', '今生は28回目の経験です。', '今生までに34回転生しました。', '今生は29番目の前世の後に続きます。', 'これまでに40回の人生を生きました。', '今生は31回目の人生です。', '今生までに36回転生しました。', '今生は32番目の前世を経た新たな始まりです。', 'これまでに43回の人生で音楽の経験を積みました。'],
        'zh-CN': ['这是你的第30次转生。', '截至目前你总共经历了37次人生。', '今生是你的第28次体验。', '到今生为止你已经转生了34次。', '今生延续自你的第29次前世。', '截至目前你已经经历了40次人生。', '今生是你的第31次人生。', '到今生为止你已经转生了36次。', '今生是你第32次前世后的新开始。', '通过43次人生你积累了音乐经验。'],
        'zh-TW': ['這是你的第30次轉生。', '截至目前你總共經歷了37次人生。', '今生是你的第28次體驗。', '到今生為止你已經轉生了34次。', '今生延續自你的第29次前世。', '截至目前你已經經歷了40次人生。', '今生是你的第31次人生。', '到今生為止你已經轉生了36次。', '今生是你第32次前世後的新開始。', '通過43次人生你積累了音樂經驗。'],
        vi: ['Đây là lần tái sinh thứ 30 của bạn.', 'Bạn đã sống tổng cộng 37 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 28 của bạn.', 'Bạn đã tái sinh 34 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 29 của bạn.', 'Bạn đã sống 40 kiếp cho đến nay.', 'Đây là kiếp thứ 31 của bạn.', 'Bạn đã tái sinh 36 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 32 của bạn.', 'Bạn đã tích lũy kinh nghiệm âm nhạc qua 43 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-30 Anda.', 'Anda telah menjalani total 37 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-28 Anda.', 'Anda telah bereinkarnasi 34 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-29 Anda.', 'Anda telah menjalani 40 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-31 Anda.', 'Anda telah bereinkarnasi 36 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-32 Anda.', 'Anda telah membangun pengalaman musik melalui 43 kehidupan.']
      }
    }
  },
  47: {
    reincarnation: {
      era: {
        en: ['You were an ancient Egyptian dancer.', 'In your past life, you were an ancient Chinese dancer.', 'You were a Roman dancer.', 'In your past life, you were a Greek dancer.', 'You were a Japanese dancer.', 'In your past life, you were an Indian dancer.', 'You were a Celtic dancer.', 'In your past life, you were a Persian dancer.', 'You were a Mayan dancer.', 'In your past life, you were a Korean dancer.'],
        ja: ['あなたは古代エジプトの踊り手でした。', '前世であなたは古代中国の踊り手でした。', 'あなたはローマの踊り手でした。', '前世であなたはギリシャの踊り手でした。', 'あなたは日本の踊り手でした。', '前世であなたはインドの踊り手でした。', 'あなたはケルトの踊り手でした。', '前世であなたはペルシャの踊り手でした。', 'あなたはマヤの踊り手でした。', '前世であなたは韓国の踊り手でした。'],
        'zh-CN': ['你是古埃及的舞者。', '你的前世是古代中国的舞者。', '你是罗马的舞者。', '你的前世是希腊的舞者。', '你是日本的舞者。', '你的前世是印度的舞者。', '你是凯尔特的舞者。', '你的前世是波斯的舞者。', '你是玛雅的舞者。', '你的前世是韩国的舞者。'],
        'zh-TW': ['你是古埃及的舞者。', '你的前世是古代中國的舞者。', '你是羅馬的舞者。', '你的前世是希臘的舞者。', '你是日本的舞者。', '你的前世是印度的舞者。', '你是凱爾特的舞者。', '你的前世是波斯的舞者。', '你是瑪雅的舞者。', '你的前世是韓國的舞者。'],
        vi: ['Bạn là một vũ công Ai Cập cổ đại.', 'Ở kiếp trước, bạn là một vũ công Trung Quốc cổ đại.', 'Bạn là một vũ công La Mã.', 'Ở kiếp trước, bạn là một vũ công Hy Lạp.', 'Bạn là một vũ công Nhật Bản.', 'Ở kiếp trước, bạn là một vũ công Ấn Độ.', 'Bạn là một vũ công Celtic.', 'Ở kiếp trước, bạn là một vũ công Ba Tư.', 'Bạn là một vũ công Maya.', 'Ở kiếp trước, bạn là một vũ công Hàn Quốc.'],
        id: ['Anda adalah penari Mesir kuno.', 'Di kehidupan lampau, Anda adalah penari Tiongkok kuno.', 'Anda adalah penari Romawi.', 'Di kehidupan lampau, Anda adalah penari Yunani.', 'Anda adalah penari Jepang.', 'Di kehidupan lampau, Anda adalah penari India.', 'Anda adalah penari Celtic.', 'Di kehidupan lampau, Anda adalah penari Persia.', 'Anda adalah penari Maya.', 'Di kehidupan lampau, Anda adalah penari Korea.']
      },
      occupation: {
        en: ['You were a royal dancer in your past life.', 'In your past life, you were a temple dancer.', 'You were a court dancer in your past life.', 'In your past life, you were a street dancer.', 'You were a ceremonial dancer in your past life.', 'In your past life, you were a ritual dancer.', 'You were a traveling dancer in your past life.', 'In your past life, you were a village dancer.', 'You were a merchant dancer in your past life.', 'In your past life, you were a dance teacher.'],
        ja: ['あなたは前世で王室踊り手でした。', '前世であなたは寺院踊り手でした。', 'あなたは前世で宮廷踊り手でした。', '前世であなたはストリート踊り手でした。', 'あなたは前世で儀式踊り手でした。', '前世であなたは儀式踊り手でした。', 'あなたは前世で旅踊り手でした。', '前世であなたは村踊り手でした。', 'あなたは前世で商人踊り手でした。', '前世であなたはダンス教師でした。'],
        'zh-CN': ['你的前世是王室舞者。', '你的前世是寺庙舞者。', '你的前世是宫廷舞者。', '你的前世是街头舞者。', '你的前世是仪式舞者。', '你的前世是仪式舞者。', '你的前世是游方舞者。', '你的前世是乡村舞者。', '你的前世是商人舞者。', '你的前世是舞蹈教师。'],
        'zh-TW': ['你的前世是王室舞者。', '你的前世是寺廟舞者。', '你的前世是宮廷舞者。', '你的前世是街頭舞者。', '你的前世是儀式舞者。', '你的前世是儀式舞者。', '你的前世是遊方舞者。', '你的前世是鄉村舞者。', '你的前世是商人舞者。', '你的前世是舞蹈教師。'],
        vi: ['Bạn từng là vũ công hoàng gia ở kiếp trước.', 'Ở kiếp trước, bạn là vũ công đền thờ.', 'Bạn từng là vũ công triều đình ở kiếp trước.', 'Ở kiếp trước, bạn là vũ công đường phố.', 'Bạn từng là vũ công nghi lễ ở kiếp trước.', 'Ở kiếp trước, bạn là vũ công nghi lễ.', 'Bạn từng là vũ công du hành ở kiếp trước.', 'Ở kiếp trước, bạn là vũ công làng.', 'Bạn từng là vũ công thương nhân ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên múa.'],
        id: ['Di kehidupan lampau, Anda adalah penari kerajaan.', 'Di kehidupan lampau, Anda adalah penari kuil.', 'Di kehidupan lampau, Anda adalah penari istana.', 'Di kehidupan lampau, Anda adalah penari jalanan.', 'Di kehidupan lampau, Anda adalah penari upacara.', 'Di kehidupan lampau, Anda adalah penari ritual.', 'Di kehidupan lampau, Anda adalah penari keliling.', 'Di kehidupan lampau, Anda adalah penari desa.', 'Di kehidupan lampau, Anda adalah penari pedagang.', 'Di kehidupan lampau, Anda adalah guru tari.']
      },
      reason: {
        en: ['You came to use past dancing skills in expression and movement.', 'You returned to apply dance wisdom to emotional release.', 'You came to use dancing patience for detailed choreography.', 'You returned to use dance knowledge for inspiration.', 'You came to use dancing precision for grace.', 'You returned to use dance instincts for intuition.', 'You came to use dancing responsibility for cultural preservation.', 'You returned to use dance teaching for guidance.', 'You came to use dancing mastery for foundation building.', 'You returned to use dance knowledge for innovation.'],
        ja: ['前世のダンス技術を今生の表現と動きに活かすために来ました。', '前世のダンス知恵を今生の感情解放に用いるために来ました。', '前世のダンス忍耐を今生の詳細振り付けに活かすために来ました。', '前世のダンス知識を今生のインスピレーションに用いるために来ました。', '前世のダンス精密さを今生の優雅さに活かすために来ました。', '前世のダンス本能を今生の直感に用いるために来ました。', '前世のダンス責任を今生の文化保存に活かすために来ました。', '前世のダンス教育を今生の指導に用いるために来ました。', '前世のダンス習得を今生の基盤構築に活かすために来ました。', '前世のダンス知識を今生の革新に用いるために来ました。'],
        'zh-CN': ['你为了将前世的舞蹈技能用于今生的表达和动作而来。', '你为了将前世的舞蹈智慧用于今生的情感释放而来。', '你为了将前世的舞蹈耐心用于今生的详细编舞而来。', '你为了将前世的舞蹈知识用于今生的灵感而来。', '你为了将前世的舞蹈精度用于今生的优雅而来。', '你为了将前世的舞蹈本能用于今生的直觉而来。', '你为了将前世的舞蹈责任用于今生的文化保护而来。', '你为了将前世的舞蹈教学用于今生的指导而来。', '你为了将前世的舞蹈掌握用于今生的基础建设而来。', '你为了将前世的舞蹈知识用于今生的创新而来。'],
        'zh-TW': ['你為了將前世的舞蹈技能用於今生的表達和動作而來。', '你為了將前世的舞蹈智慧用於今生的情感釋放而來。', '你為了將前世的舞蹈耐心用於今生的詳細編舞而來。', '你為了將前世的舞蹈知識用於今生的靈感而來。', '你為了將前世的舞蹈精度用於今生的優雅而來。', '你為了將前世的舞蹈本能用於今生的直覺而來。', '你為了將前世的舞蹈責任用於今生的文化保護而來。', '你為了將前世的舞蹈教學用於今生的指導而來。', '你為了將前世的舞蹈掌握用於今生的基礎建設而來。', '你為了將前世的舞蹈知識用於今生的創新而來。'],
        vi: ['Bạn đến để sử dụng kỹ năng múa từ kiếp trước trong biểu đạt và chuyển động.', 'Bạn trở lại để áp dụng trí tuệ múa vào giải phóng cảm xúc.', 'Bạn đến để sử dụng sự kiên nhẫn múa cho biên đạo chi tiết.', 'Bạn trở lại để sử dụng kiến thức múa cho cảm hứng.', 'Bạn đến để sử dụng độ chính xác múa cho sự duyên dáng.', 'Bạn trở lại để sử dụng bản năng múa cho trực giác.', 'Bạn đến để sử dụng trách nhiệm múa cho bảo tồn văn hóa.', 'Bạn trở lại để sử dụng giảng dạy múa cho hướng dẫn.', 'Bạn đến để sử dụng sự thành thạo múa cho xây dựng nền tảng.', 'Bạn trở lại để sử dụng kiến thức múa cho đổi mới.'],
        id: ['Anda datang untuk menggunakan keterampilan menari masa lalu dalam ekspresi dan gerakan.', 'Anda kembali untuk menerapkan kebijaksanaan tari pada pelepasan emosional.', 'Anda datang untuk menggunakan kesabaran menari untuk koreografi detail.', 'Anda kembali untuk menggunakan pengetahuan tari untuk inspirasi.', 'Anda datang untuk menggunakan presisi menari untuk keanggunan.', 'Anda kembali untuk menggunakan insting tari untuk intuisi.', 'Anda datang untuk menggunakan tanggung jawab menari untuk pelestarian budaya.', 'Anda kembali untuk menggunakan pengajaran tari untuk bimbingan.', 'Anda datang untuk menggunakan penguasaan menari untuk membangun fondasi.', 'Anda kembali untuk menggunakan pengetahuan tari untuk inovasi.']
      },
      lifeCount: {
        en: ['This is your 31st reincarnation.', 'You have lived a total of 38 lives so far.', 'This life is your 29th experience.', 'You have reincarnated 35 times up to this life.', 'This life follows your 30th past life.', 'You have lived 41 lives so far.', 'This is your 32nd life.', 'You have reincarnated 37 times up to this life.', 'This life is a new beginning after your 33rd past life.', 'You have built dancing experience through 44 lives.'],
        ja: ['これはあなたの31回目の転生です。', 'これまでに合計38回の人生を生きました。', '今生は29回目の経験です。', '今生までに35回転生しました。', '今生は30番目の前世の後に続きます。', 'これまでに41回の人生を生きました。', '今生は32回目の人生です。', '今生までに37回転生しました。', '今生は33番目の前世を経た新たな始まりです。', 'これまでに44回の人生でダンスの経験を積みました。'],
        'zh-CN': ['这是你的第31次转生。', '截至目前你总共经历了38次人生。', '今生是你的第29次体验。', '到今生为止你已经转生了35次。', '今生延续自你的第30次前世。', '截至目前你已经经历了41次人生。', '今生是你的第32次人生。', '到今生为止你已经转生了37次。', '今生是你第33次前世后的新开始。', '通过44次人生你积累了舞蹈经验。'],
        'zh-TW': ['這是你的第31次轉生。', '截至目前你總共經歷了38次人生。', '今生是你的第29次體驗。', '到今生為止你已經轉生了35次。', '今生延續自你的第30次前世。', '截至目前你已經經歷了41次人生。', '今生是你的第32次人生。', '到今生為止你已經轉生了37次。', '今生是你第33次前世後的新開始。', '通過44次人生你積累了舞蹈經驗。'],
        vi: ['Đây là lần tái sinh thứ 31 của bạn.', 'Bạn đã sống tổng cộng 38 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 29 của bạn.', 'Bạn đã tái sinh 35 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 30 của bạn.', 'Bạn đã sống 41 kiếp cho đến nay.', 'Đây là kiếp thứ 32 của bạn.', 'Bạn đã tái sinh 37 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 33 của bạn.', 'Bạn đã tích lũy kinh nghiệm múa qua 44 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-31 Anda.', 'Anda telah menjalani total 38 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-29 Anda.', 'Anda telah bereinkarnasi 35 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-30 Anda.', 'Anda telah menjalani 41 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-32 Anda.', 'Anda telah bereinkarnasi 37 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-33 Anda.', 'Anda telah membangun pengalaman menari melalui 44 kehidupan.']
      }
    }
  }
};