import { FaceReincarnationTranslations } from '../merge';

export const batch24: FaceReincarnationTranslations = {
  28: {
    reincarnation: {
      era: {
        en: ['You were an ancient Egyptian hunter.', 'In your past life, you were an ancient Chinese hunter.', 'You were a Roman hunter.', 'In your past life, you were a Greek hunter.', 'You were a Japanese hunter.', 'In your past life, you were an Indian hunter.', 'You were a Celtic hunter.', 'In your past life, you were a Persian hunter.', 'You were a Mayan hunter.', 'In your past life, you were a Korean hunter.'],
        ja: ['あなたは古代エジプトの狩人でした。', '前世であなたは古代中国の狩人でした。', 'あなたはローマの狩人でした。', '前世であなたはギリシャの狩人でした。', 'あなたは日本の狩人でした。', '前世であなたはインドの狩人でした。', 'あなたはケルトの狩人でした。', '前世であなたはペルシャの狩人でした。', 'あなたはマヤの狩人でした。', '前世であなたは韓国の狩人でした。'],
        'zh-CN': ['你是古埃及的猎人。', '你的前世是古代中国的猎人。', '你是罗马的猎人。', '你的前世是希腊的猎人。', '你是日本的猎人。', '你的前世是印度的猎人。', '你是凯尔特的猎人。', '你的前世是波斯的猎人。', '你是玛雅的猎人。', '你的前世是韩国的猎人。'],
        'zh-TW': ['你是古埃及的獵人。', '你的前世是古代中國的獵人。', '你是羅馬的獵人。', '你的前世是希臘的獵人。', '你是日本的獵人。', '你的前世是印度的獵人。', '你是凱爾特的獵人。', '你的前世是波斯的獵人。', '你是瑪雅的獵人。', '你的前世是韓國的獵人。'],
        vi: ['Bạn là một thợ săn Ai Cập cổ đại.', 'Ở kiếp trước, bạn là một thợ săn Trung Quốc cổ đại.', 'Bạn là một thợ săn La Mã.', 'Ở kiếp trước, bạn là một thợ săn Hy Lạp.', 'Bạn là một thợ săn Nhật Bản.', 'Ở kiếp trước, bạn là một thợ săn Ấn Độ.', 'Bạn là một thợ săn Celtic.', 'Ở kiếp trước, bạn là một thợ săn Ba Tư.', 'Bạn là một thợ săn Maya.', 'Ở kiếp trước, bạn là một thợ săn Hàn Quốc.'],
        id: ['Anda adalah pemburu Mesir kuno.', 'Di kehidupan lampau, Anda adalah pemburu Tiongkok kuno.', 'Anda adalah pemburu Romawi.', 'Di kehidupan lampau, Anda adalah pemburu Yunani.', 'Anda adalah pemburu Jepang.', 'Di kehidupan lampau, Anda adalah pemburu India.', 'Anda adalah pemburu Celtic.', 'Di kehidupan lampau, Anda adalah pemburu Persia.', 'Anda adalah pemburu Maya.', 'Di kehidupan lampau, Anda adalah pemburu Korea.']
      },
      occupation: {
        en: ['You were a big game hunter in your past life.', 'In your past life, you were a small game hunter.', 'You were a bird hunter in your past life.', 'In your past life, you were a ceremonial hunter.', 'You were a royal hunter in your past life.', 'In your past life, you were a subsistence hunter.', 'You were a fur hunter in your past life.', 'In your past life, you were a bow hunter.', 'You were a spear hunter in your past life.', 'In your past life, you were a hunting teacher.'],
        ja: ['あなたは前世で大型動物狩人でした。', '前世であなたは小型動物狩人でした。', 'あなたは前世で鳥狩人でした。', '前世であなたは儀式用狩人でした。', 'あなたは前世で王室狩人でした。', '前世であなたは自給狩人でした。', 'あなたは前世で毛皮狩人でした。', '前世であなたは弓狩人でした。', 'あなたは前世で槍狩人でした。', '前世であなたは狩猟教師でした。'],
        'zh-CN': ['你的前世是大型猎物猎人。', '你的前世是小型猎物猎人。', '你的前世是鸟类猎人。', '你的前世是仪式猎人。', '你的前世是王室猎人。', '你的前世是自给猎人。', '你的前世是毛皮猎人。', '你的前世是弓箭猎人。', '你的前世是长矛猎人。', '你的前世是狩猎教师。'],
        'zh-TW': ['你的前世是大型獵物獵人。', '你的前世是小型獵物獵人。', '你的前世是鳥類獵人。', '你的前世是儀式獵人。', '你的前世是王室獵人。', '你的前世是自給獵人。', '你的前世是毛皮獵人。', '你的前世是弓箭獵人。', '你的前世是長矛獵人。', '你的前世是狩獵教師。'],
        vi: ['Bạn từng là thợ săn thú lớn ở kiếp trước.', 'Ở kiếp trước, bạn là thợ săn thú nhỏ.', 'Bạn từng là thợ săn chim ở kiếp trước.', 'Ở kiếp trước, bạn là thợ săn nghi lễ.', 'Bạn từng là thợ săn hoàng gia ở kiếp trước.', 'Ở kiếp trước, bạn là thợ săn tự cung tự cấp.', 'Bạn từng là thợ săn lông thú ở kiếp trước.', 'Ở kiếp trước, bạn là thợ săn cung tên.', 'Bạn từng là thợ săn giáo ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên săn bắn.'],
        id: ['Di kehidupan lampau, Anda adalah pemburu hewan besar.', 'Di kehidupan lampau, Anda adalah pemburu hewan kecil.', 'Di kehidupan lampau, Anda adalah pemburu burung.', 'Di kehidupan lampau, Anda adalah pemburu upacara.', 'Di kehidupan lampau, Anda adalah pemburu kerajaan.', 'Di kehidupan lampau, Anda adalah pemburu subsisten.', 'Di kehidupan lampau, Anda adalah pemburu bulu.', 'Di kehidupan lampau, Anda adalah pemburu busur.', 'Di kehidupan lampau, Anda adalah pemburu tombak.', 'Di kehidupan lampau, Anda adalah guru berburu.']
      },
      reason: {
        en: ['You came to use past hunting skills in focus and determination.', 'You returned to apply tracking abilities to problem solving.', 'You came to use hunting patience for persistence.', 'You returned to use wilderness wisdom for survival.', 'You came to use hunting precision for accuracy.', 'You returned to use animal instincts for intuition.', 'You came to use hunting responsibility for provision.', 'You returned to use wilderness teaching for guidance.', 'You came to use hunting mastery for foundation building.', 'You returned to use wilderness knowledge for innovation.'],
        ja: ['前世の狩猟技術を今生の集中と決意に活かすために来ました。', '前世の追跡能力を今生の問題解決に用いるために来ました。', '前世の狩猟忍耐を今生の持続性に活かすために来ました。', '前世の荒野知恵を今生の生存に用いるために来ました。', '前世の狩猟精密さを今生の正確性に活かすために来ました。', '前世の動物本能を今生の直感に用いるために来ました。', '前世の狩猟責任を今生の供給に活かすために来ました。', '前世の荒野教育を今生の指導に用いるために来ました。', '前世の狩猟習得を今生の基盤構築に活かすために来ました。', '前世の荒野知識を今生の革新に用いるために来ました。'],
        'zh-CN': ['你为了将前世的狩猎技能用于今生的专注和决心而来。', '你为了将前世的追踪能力用于今生的问题解决而来。', '你为了将前世的狩猎耐心用于今生的坚持而来。', '你为了将前世的荒野智慧用于今生的生存而来。', '你为了将前世的狩猎精度用于今生的准确性而来。', '你为了将前世的动物本能用于今生的直觉而来。', '你为了将前世的狩猎责任用于今生的供给而来。', '你为了将前世的荒野教学用于今生的指导而来。', '你为了将前世的狩猎掌握用于今生的基础建设而来。', '你为了将前世的荒野知识用于今生的创新而来。'],
        'zh-TW': ['你為了將前世的狩獵技能用於今生的專注和決心而來。', '你為了將前世的追蹤能力用於今生的問題解決而來。', '你為了將前世的狩獵耐心用於今生的堅持而來。', '你為了將前世的荒野智慧用於今生的生存而來。', '你為了將前世的狩獵精度用於今生的準確性而來。', '你為了將前世的動物本能用於今生的直覺而來。', '你為了將前世的狩獵責任用於今生的供給而來。', '你為了將前世的荒野教學用於今生的指導而來。', '你為了將前世的狩獵掌握用於今生的基礎建設而來。', '你為了將前世的荒野知識用於今生的創新而來。'],
        vi: ['Bạn đến để sử dụng kỹ năng săn bắn từ kiếp trước trong sự tập trung và quyết tâm.', 'Bạn trở lại để áp dụng khả năng theo dõi vào giải quyết vấn đề.', 'Bạn đến để sử dụng sự kiên nhẫn săn bắn cho sự bền bỉ.', 'Bạn trở lại để sử dụng trí tuệ hoang dã cho sự sống còn.', 'Bạn đến để sử dụng độ chính xác săn bắn cho sự chính xác.', 'Bạn trở lại để sử dụng bản năng động vật cho trực giác.', 'Bạn đến để sử dụng trách nhiệm săn bắn cho cung cấp.', 'Bạn trở lại để sử dụng giảng dạy hoang dã cho hướng dẫn.', 'Bạn đến để sử dụng sự thành thạo săn bắn cho xây dựng nền tảng.', 'Bạn trở lại để sử dụng kiến thức hoang dã cho đổi mới.'],
        id: ['Anda datang untuk menggunakan keterampilan berburu masa lalu dalam fokus dan tekad.', 'Anda kembali untuk menerapkan kemampuan melacak pada pemecahan masalah.', 'Anda datang untuk menggunakan kesabaran berburu untuk ketekunan.', 'Anda kembali untuk menggunakan kebijaksanaan alam liar untuk bertahan hidup.', 'Anda datang untuk menggunakan presisi berburu untuk akurasi.', 'Anda kembali untuk menggunakan insting hewan untuk intuisi.', 'Anda datang untuk menggunakan tanggung jawab berburu untuk penyediaan.', 'Anda kembali untuk menggunakan pengajaran alam liar untuk bimbingan.', 'Anda datang untuk menggunakan penguasaan berburu untuk membangun fondasi.', 'Anda kembali untuk menggunakan pengetahuan alam liar untuk inovasi.']
      },
      lifeCount: {
        en: ['This is your 12th reincarnation.', 'You have lived a total of 19 lives so far.', 'This life is your 10th experience.', 'You have reincarnated 16 times up to this life.', 'This life follows your 11th past life.', 'You have lived 22 lives so far.', 'This is your 13th life.', 'You have reincarnated 18 times up to this life.', 'This life is a new beginning after your 14th past life.', 'You have built hunting experience through 25 lives.'],
        ja: ['これはあなたの12回目の転生です。', 'これまでに合計19回の人生を生きました。', '今生は10回目の経験です。', '今生までに16回転生しました。', '今生は11番目の前世の後に続きます。', 'これまでに22回の人生を生きました。', '今生は13回目の人生です。', '今生までに18回転生しました。', '今生は14番目の前世を経た新たな始まりです。', 'これまでに25回の人生で狩猟の経験を積みました。'],
        'zh-CN': ['这是你的第12次转生。', '截至目前你总共经历了19次人生。', '今生是你的第10次体验。', '到今生为止你已经转生了16次。', '今生延续自你的第11次前世。', '截至目前你已经经历了22次人生。', '今生是你的第13次人生。', '到今生为止你已经转生了18次。', '今生是你第14次前世后的新开始。', '通过25次人生你积累了狩猎经验。'],
        'zh-TW': ['這是你的第12次轉生。', '截至目前你總共經歷了19次人生。', '今生是你的第10次體驗。', '到今生為止你已經轉生了16次。', '今生延續自你的第11次前世。', '截至目前你已經經歷了22次人生。', '今生是你的第13次人生。', '到今生為止你已經轉生了18次。', '今生是你第14次前世後的新開始。', '通過25次人生你積累了狩獵經驗。'],
        vi: ['Đây là lần tái sinh thứ 12 của bạn.', 'Bạn đã sống tổng cộng 19 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 10 của bạn.', 'Bạn đã tái sinh 16 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 11 của bạn.', 'Bạn đã sống 22 kiếp cho đến nay.', 'Đây là kiếp thứ 13 của bạn.', 'Bạn đã tái sinh 18 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 14 của bạn.', 'Bạn đã tích lũy kinh nghiệm săn bắn qua 25 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-12 Anda.', 'Anda telah menjalani total 19 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-10 Anda.', 'Anda telah bereinkarnasi 16 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-11 Anda.', 'Anda telah menjalani 22 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-13 Anda.', 'Anda telah bereinkarnasi 18 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-14 Anda.', 'Anda telah membangun pengalaman berburu melalui 25 kehidupan.']
      }
    }
  },
  29: {
    reincarnation: {
      era: {
        en: ['You were an ancient Egyptian gatherer.', 'In your past life, you were an ancient Chinese gatherer.', 'You were a Roman gatherer.', 'In your past life, you were a Greek gatherer.', 'You were a Japanese gatherer.', 'In your past life, you were an Indian gatherer.', 'You were a Celtic gatherer.', 'In your past life, you were a Persian gatherer.', 'You were a Mayan gatherer.', 'In your past life, you were a Korean gatherer.'],
        ja: ['あなたは古代エジプトの採集者でした。', '前世であなたは古代中国の採集者でした。', 'あなたはローマの採集者でした。', '前世であなたはギリシャの採集者でした。', 'あなたは日本の採集者でした。', '前世であなたはインドの採集者でした。', 'あなたはケルトの採集者でした。', '前世であなたはペルシャの採集者でした。', 'あなたはマヤの採集者でした。', '前世であなたは韓国の採集者でした。'],
        'zh-CN': ['你是古埃及的采集者。', '你的前世是古代中国的采集者。', '你是罗马的采集者。', '你的前世是希腊的采集者。', '你是日本的采集者。', '你的前世是印度的采集者。', '你是凯尔特的采集者。', '你的前世是波斯的采集者。', '你是玛雅的采集者。', '你的前世是韩国的采集者。'],
        'zh-TW': ['你是古埃及的採集者。', '你的前世是古代中國的採集者。', '你是羅馬的採集者。', '你的前世是希臘的採集者。', '你是日本的採集者。', '你的前世是印度的採集者。', '你是凱爾特的採集者。', '你的前世是波斯的採集者。', '你是瑪雅的採集者。', '你的前世是韓國的採集者。'],
        vi: ['Bạn là một người thu thập Ai Cập cổ đại.', 'Ở kiếp trước, bạn là một người thu thập Trung Quốc cổ đại.', 'Bạn là một người thu thập La Mã.', 'Ở kiếp trước, bạn là một người thu thập Hy Lạp.', 'Bạn là một người thu thập Nhật Bản.', 'Ở kiếp trước, bạn là một người thu thập Ấn Độ.', 'Bạn là một người thu thập Celtic.', 'Ở kiếp trước, bạn là một người thu thập Ba Tư.', 'Bạn là một người thu thập Maya.', 'Ở kiếp trước, bạn là một người thu thập Hàn Quốc.'],
        id: ['Anda adalah pengumpul Mesir kuno.', 'Di kehidupan lampau, Anda adalah pengumpul Tiongkok kuno.', 'Anda adalah pengumpul Romawi.', 'Di kehidupan lampau, Anda adalah pengumpul Yunani.', 'Anda adalah pengumpul Jepang.', 'Di kehidupan lampau, Anda adalah pengumpul India.', 'Anda adalah pengumpul Celtic.', 'Di kehidupan lampau, Anda adalah pengumpul Persia.', 'Anda adalah pengumpul Maya.', 'Di kehidupan lampau, Anda adalah pengumpul Korea.']
      },
      occupation: {
        en: ['You were a berry gatherer in your past life.', 'In your past life, you were a mushroom gatherer.', 'You were a herb gatherer in your past life.', 'In your past life, you were a root gatherer.', 'You were a seed gatherer in your past life.', 'In your past life, you were a medicinal gatherer.', 'You were a ceremonial gatherer in your past life.', 'In your past life, you were a food gatherer.', 'You were a fiber gatherer in your past life.', 'In your past life, you were a gathering teacher.'],
        ja: ['あなたは前世でベリー採集者でした。', '前世であなたはキノコ採集者でした。', 'あなたは前世でハーブ採集者でした。', '前世であなたは根採集者でした。', 'あなたは前世で種子採集者でした。', '前世であなたは薬用採集者でした。', 'あなたは前世で儀式用採集者でした。', '前世であなたは食物採集者でした。', 'あなたは前世で繊維採集者でした。', '前世であなたは採集教師でした。'],
        'zh-CN': ['你的前世是浆果采集者。', '你的前世是蘑菇采集者。', '你的前世是草药采集者。', '你的前世是根茎采集者。', '你的前世是种子采集者。', '你的前世是药用采集者。', '你的前世是仪式采集者。', '你的前世是食物采集者。', '你的前世是纤维采集者。', '你的前世是采集教师。'],
        'zh-TW': ['你的前世是漿果採集者。', '你的前世是蘑菇採集者。', '你的前世是草藥採集者。', '你的前世是根莖採集者。', '你的前世是種子採集者。', '你的前世是藥用採集者。', '你的前世是儀式採集者。', '你的前世是食物採集者。', '你的前世是纖維採集者。', '你的前世是採集教師。'],
        vi: ['Bạn từng là người thu thập quả mọng ở kiếp trước.', 'Ở kiếp trước, bạn là người thu thập nấm.', 'Bạn từng là người thu thập thảo dược ở kiếp trước.', 'Ở kiếp trước, bạn là người thu thập rễ cây.', 'Bạn từng là người thu thập hạt giống ở kiếp trước.', 'Ở kiếp trước, bạn là người thu thập dược liệu.', 'Bạn từng là người thu thập nghi lễ ở kiếp trước.', 'Ở kiếp trước, bạn là người thu thập thực phẩm.', 'Bạn từng là người thu thập sợi ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên thu thập.'],
        id: ['Di kehidupan lampau, Anda adalah pengumpul beri.', 'Di kehidupan lampau, Anda adalah pengumpul jamur.', 'Di kehidupan lampau, Anda adalah pengumpul herbal.', 'Di kehidupan lampau, Anda adalah pengumpul akar.', 'Di kehidupan lampau, Anda adalah pengumpul benih.', 'Di kehidupan lampau, Anda adalah pengumpul obat.', 'Di kehidupan lampau, Anda adalah pengumpul upacara.', 'Di kehidupan lampau, Anda adalah pengumpul makanan.', 'Di kehidupan lampau, Anda adalah pengumpul serat.', 'Di kehidupan lampau, Anda adalah guru pengumpulan.']
      },
      reason: {
        en: ['You came to use past gathering skills in resourcefulness.', 'You returned to apply nature knowledge to sustainability.', 'You came to use gathering patience for persistence.', 'You returned to use natural wisdom for harmony.', 'You came to use gathering precision for detail work.', 'You returned to use nature instincts for intuition.', 'You came to use gathering responsibility for provision.', 'You returned to use nature teaching for guidance.', 'You came to use gathering mastery for foundation building.', 'You returned to use nature knowledge for innovation.'],
        ja: ['前世の採集技術を今生の創意工夫に活かすために来ました。', '前世の自然知識を今生の持続可能性に用いるために来ました。', '前世の採集忍耐を今生の持続性に活かすために来ました。', '前世の自然知恵を今生の調和に用いるために来ました。', '前世の採集精密さを今生の詳細作業に活かすために来ました。', '前世の自然本能を今生の直感に用いるために来ました。', '前世の採集責任を今生の供給に活かすために来ました。', '前世の自然教育を今生の指導に用いるために来ました。', '前世の採集習得を今生の基盤構築に活かすために来ました。', '前世の自然知識を今生の革新に用いるために来ました。'],
        'zh-CN': ['你为了将前世的采集技能用于今生的足智多谋而来。', '你为了将前世的自然知识用于今生的可持续性而来。', '你为了将前世的采集耐心用于今生的坚持而来。', '你为了将前世的自然智慧用于今生的和谐而来。', '你为了将前世的采集精度用于今生的细致工作而来。', '你为了将前世的自然本能用于今生的直觉而来。', '你为了将前世的采集责任用于今生的供给而来。', '你为了将前世的自然教学用于今生的指导而来。', '你为了将前世的采集掌握用于今生的基础建设而来。', '你为了将前世的自然知识用于今生的创新而来。'],
        'zh-TW': ['你為了將前世的採集技能用於今生的足智多謀而來。', '你為了將前世的自然知識用於今生的可持續性而來。', '你為了將前世的採集耐心用於今生的堅持而來。', '你為了將前世的自然智慧用於今生的和諧而來。', '你為了將前世的採集精度用於今生的細緻工作而來。', '你為了將前世的自然本能用於今生的直覺而來。', '你為了將前世的採集責任用於今生的供給而來。', '你為了將前世的自然教學用於今生的指導而來。', '你為了將前世的採集掌握用於今生的基礎建設而來。', '你為了將前世的自然知識用於今生的創新而來。'],
        vi: ['Bạn đến để sử dụng kỹ năng thu thập từ kiếp trước trong sự tháo vát.', 'Bạn trở lại để áp dụng kiến thức thiên nhiên vào tính bền vững.', 'Bạn đến để sử dụng sự kiên nhẫn thu thập cho sự bền bỉ.', 'Bạn trở lại để sử dụng trí tuệ thiên nhiên cho sự hài hòa.', 'Bạn đến để sử dụng độ chính xác thu thập cho công việc chi tiết.', 'Bạn trở lại để sử dụng bản năng thiên nhiên cho trực giác.', 'Bạn đến để sử dụng trách nhiệm thu thập cho cung cấp.', 'Bạn trở lại để sử dụng giảng dạy thiên nhiên cho hướng dẫn.', 'Bạn đến để sử dụng sự thành thạo thu thập cho xây dựng nền tảng.', 'Bạn trở lại để sử dụng kiến thức thiên nhiên cho đổi mới.'],
        id: ['Anda datang untuk menggunakan keterampilan pengumpulan masa lalu dalam kecerdikan.', 'Anda kembali untuk menerapkan pengetahuan alam pada keberlanjutan.', 'Anda datang untuk menggunakan kesabaran pengumpulan untuk ketekunan.', 'Anda kembali untuk menggunakan kebijaksanaan alam untuk harmoni.', 'Anda datang untuk menggunakan presisi pengumpulan untuk pekerjaan detail.', 'Anda kembali untuk menggunakan insting alam untuk intuisi.', 'Anda datang untuk menggunakan tanggung jawab pengumpulan untuk penyediaan.', 'Anda kembali untuk menggunakan pengajaran alam untuk bimbingan.', 'Anda datang untuk menggunakan penguasaan pengumpulan untuk membangun fondasi.', 'Anda kembali untuk menggunakan pengetahuan alam untuk inovasi.']
      },
      lifeCount: {
        en: ['This is your 13th reincarnation.', 'You have lived a total of 20 lives so far.', 'This life is your 11th experience.', 'You have reincarnated 17 times up to this life.', 'This life follows your 12th past life.', 'You have lived 23 lives so far.', 'This is your 14th life.', 'You have reincarnated 19 times up to this life.', 'This life is a new beginning after your 15th past life.', 'You have built gathering experience through 26 lives.'],
        ja: ['これはあなたの13回目の転生です。', 'これまでに合計20回の人生を生きました。', '今生は11回目の経験です。', '今生までに17回転生しました。', '今生は12番目の前世の後に続きます。', 'これまでに23回の人生を生きました。', '今生は14回目の人生です。', '今生までに19回転生しました。', '今生は15番目の前世を経た新たな始まりです。', 'これまでに26回の人生で採集の経験を積みました。'],
        'zh-CN': ['这是你的第13次转生。', '截至目前你总共经历了20次人生。', '今生是你的第11次体验。', '到今生为止你已经转生了17次。', '今生延续自你的第12次前世。', '截至目前你已经经历了23次人生。', '今生是你的第14次人生。', '到今生为止你已经转生了19次。', '今生是你第15次前世后的新开始。', '通过26次人生你积累了采集经验。'],
        'zh-TW': ['這是你的第13次轉生。', '截至目前你總共經歷了20次人生。', '今生是你的第11次體驗。', '到今生為止你已經轉生了17次。', '今生延續自你的第12次前世。', '截至目前你已經經歷了23次人生。', '今生是你的第14次人生。', '到今生為止你已經轉生了19次。', '今生是你第15次前世後的新開始。', '通過26次人生你積累了採集經驗。'],
        vi: ['Đây là lần tái sinh thứ 13 của bạn.', 'Bạn đã sống tổng cộng 20 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 11 của bạn.', 'Bạn đã tái sinh 17 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 12 của bạn.', 'Bạn đã sống 23 kiếp cho đến nay.', 'Đây là kiếp thứ 14 của bạn.', 'Bạn đã tái sinh 19 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 15 của bạn.', 'Bạn đã tích lũy kinh nghiệm thu thập qua 26 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-13 Anda.', 'Anda telah menjalani total 20 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-11 Anda.', 'Anda telah bereinkarnasi 17 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-12 Anda.', 'Anda telah menjalani 23 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-14 Anda.', 'Anda telah bereinkarnasi 19 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-15 Anda.', 'Anda telah membangun pengalaman pengumpulan melalui 26 kehidupan.']
      }
    }
  }
};