import { FaceReincarnationTranslations } from '../merge';

export const batch25: FaceReincarnationTranslations = {
  30: {
    reincarnation: {
      era: {
        en: ['You were an ancient Egyptian carpenter.', 'In your past life, you were an ancient Chinese carpenter.', 'You were a Roman carpenter.', 'In your past life, you were a Greek carpenter.', 'You were a Japanese carpenter.', 'In your past life, you were an Indian carpenter.', 'You were a Celtic carpenter.', 'In your past life, you were a Persian carpenter.', 'You were a Mayan carpenter.', 'In your past life, you were a Korean carpenter.'],
        ja: ['あなたは古代エジプトの大工でした。', '前世であなたは古代中国の大工でした。', 'あなたはローマの大工でした。', '前世であなたはギリシャの大工でした。', 'あなたは日本の大工でした。', '前世であなたはインドの大工でした。', 'あなたはケルトの大工でした。', '前世であなたはペルシャの大工でした。', 'あなたはマヤの大工でした。', '前世であなたは韓国の大工でした。'],
        'zh-CN': ['你是古埃及的木匠。', '你的前世是古代中国的木匠。', '你是罗马的木匠。', '你的前世是希腊的木匠。', '你是日本的木匠。', '你的前世是印度的木匠。', '你是凯尔特的木匠。', '你的前世是波斯的木匠。', '你是玛雅的木匠。', '你的前世是韩国的木匠。'],
        'zh-TW': ['你是古埃及的木匠。', '你的前世是古代中國的木匠。', '你是羅馬的木匠。', '你的前世是希臘的木匠。', '你是日本的木匠。', '你的前世是印度的木匠。', '你是凱爾特的木匠。', '你的前世是波斯的木匠。', '你是瑪雅的木匠。', '你的前世是韓國的木匠。'],
        vi: ['Bạn là một thợ mộc Ai Cập cổ đại.', 'Ở kiếp trước, bạn là một thợ mộc Trung Quốc cổ đại.', 'Bạn là một thợ mộc La Mã.', 'Ở kiếp trước, bạn là một thợ mộc Hy Lạp.', 'Bạn là một thợ mộc Nhật Bản.', 'Ở kiếp trước, bạn là một thợ mộc Ấn Độ.', 'Bạn là một thợ mộc Celtic.', 'Ở kiếp trước, bạn là một thợ mộc Ba Tư.', 'Bạn là một thợ mộc Maya.', 'Ở kiếp trước, bạn là một thợ mộc Hàn Quốc.'],
        id: ['Anda adalah tukang kayu Mesir kuno.', 'Di kehidupan lampau, Anda adalah tukang kayu Tiongkok kuno.', 'Anda adalah tukang kayu Romawi.', 'Di kehidupan lampau, Anda adalah tukang kayu Yunani.', 'Anda adalah tukang kayu Jepang.', 'Di kehidupan lampau, Anda adalah tukang kayu India.', 'Anda adalah tukang kayu Celtic.', 'Di kehidupan lampau, Anda adalah tukang kayu Persia.', 'Anda adalah tukang kayu Maya.', 'Di kehidupan lampau, Anda adalah tukang kayu Korea.']
      },
      occupation: {
        en: ['You were a furniture carpenter in your past life.', 'In your past life, you were a house carpenter.', 'You were a ship carpenter in your past life.', 'In your past life, you were a temple carpenter.', 'You were a tool carpenter in your past life.', 'In your past life, you were a decorative carpenter.', 'You were a musical instrument carpenter in your past life.', 'In your past life, you were a wheel carpenter.', 'You were a coffin carpenter in your past life.', 'In your past life, you were a carpentry teacher.'],
        ja: ['あなたは前世で家具大工でした。', '前世であなたは家屋大工でした。', 'あなたは前世で船大工でした。', '前世であなたは寺院大工でした。', 'あなたは前世で工具大工でした。', '前世であなたは装飾大工でした。', 'あなたは前世で楽器大工でした。', '前世であなたは車輪大工でした。', 'あなたは前世で棺大工でした。', '前世であなたは大工教師でした。'],
        'zh-CN': ['你的前世是家具木匠。', '你的前世是房屋木匠。', '你的前世是船舶木匠。', '你的前世是寺庙木匠。', '你的前世是工具木匠。', '你的前世是装饰木匠。', '你的前世是乐器木匠。', '你的前世是车轮木匠。', '你的前世是棺材木匠。', '你的前世是木工教师。'],
        'zh-TW': ['你的前世是家具木匠。', '你的前世是房屋木匠。', '你的前世是船舶木匠。', '你的前世是寺廟木匠。', '你的前世是工具木匠。', '你的前世是裝飾木匠。', '你的前世是樂器木匠。', '你的前世是車輪木匠。', '你的前世是棺材木匠。', '你的前世是木工教師。'],
        vi: ['Bạn từng là thợ mộc đồ nội thất ở kiếp trước.', 'Ở kiếp trước, bạn là thợ mộc nhà cửa.', 'Bạn từng là thợ mộc tàu thuyền ở kiếp trước.', 'Ở kiếp trước, bạn là thợ mộc đền thờ.', 'Bạn từng là thợ mộc dụng cụ ở kiếp trước.', 'Ở kiếp trước, bạn là thợ mộc trang trí.', 'Bạn từng là thợ mộc nhạc cụ ở kiếp trước.', 'Ở kiếp trước, bạn là thợ mộc bánh xe.', 'Bạn từng là thợ mộc quan tài ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên mộc.'],
        id: ['Di kehidupan lampau, Anda adalah tukang kayu furnitur.', 'Di kehidupan lampau, Anda adalah tukang kayu rumah.', 'Di kehidupan lampau, Anda adalah tukang kayu kapal.', 'Di kehidupan lampau, Anda adalah tukang kayu kuil.', 'Di kehidupan lampau, Anda adalah tukang kayu alat.', 'Di kehidupan lampau, Anda adalah tukang kayu dekoratif.', 'Di kehidupan lampau, Anda adalah tukang kayu alat musik.', 'Di kehidupan lampau, Anda adalah tukang kayu roda.', 'Di kehidupan lampau, Anda adalah tukang kayu peti mati.', 'Di kehidupan lampau, Anda adalah guru pertukangan.']
      },
      reason: {
        en: ['You came to use past carpentry skills in precision and craftsmanship.', 'You returned to apply wood wisdom to structure building.', 'You came to use carpentry patience for detailed work.', 'You returned to use wood knowledge for foundation building.', 'You came to use carpentry precision for accuracy.', 'You returned to use wood instincts for intuition.', 'You came to use carpentry responsibility for creation.', 'You returned to use wood teaching for guidance.', 'You came to use carpentry mastery for foundation building.', 'You returned to use wood knowledge for innovation.'],
        ja: ['前世の大工技術を今生の精密さと職人技に活かすために来ました。', '前世の木材知恵を今生の構造構築に用いるために来ました。', '前世の大工忍耐を今生の詳細作業に活かすために来ました。', '前世の木材知識を今生の基盤構築に用いるために来ました。', '前世の大工精密さを今生の正確性に活かすために来ました。', '前世の木材本能を今生の直感に用いるために来ました。', '前世の大工責任を今生の創造に活かすために来ました。', '前世の木材教育を今生の指導に用いるために来ました。', '前世の大工習得を今生の基盤構築に活かすために来ました。', '前世の木材知識を今生の革新に用いるために来ました。'],
        'zh-CN': ['你为了将前世的木工技能用于今生的精确和工艺而来。', '你为了将前世的木材智慧用于今生的结构建设而来。', '你为了将前世的木工耐心用于今生的细致工作而来。', '你为了将前世的木材知识用于今生的基础建设而来。', '你为了将前世的木工精度用于今生的准确性而来。', '你为了将前世的木材本能用于今生的直觉而来。', '你为了将前世的木工责任用于今生的创造而来。', '你为了将前世的木材教学用于今生的指导而来。', '你为了将前世的木工掌握用于今生的基础建设而来。', '你为了将前世的木材知识用于今生的创新而来。'],
        'zh-TW': ['你為了將前世的木工技能用於今生的精確和工藝而來。', '你為了將前世的木材智慧用於今生的結構建設而來。', '你為了將前世的木工耐心用於今生的細緻工作而來。', '你為了將前世的木材知識用於今生的基礎建設而來。', '你為了將前世的木工精度用於今生的準確性而來。', '你為了將前世的木材本能用於今生的直覺而來。', '你為了將前世的木工責任用於今生的創造而來。', '你為了將前世的木材教學用於今生的指導而來。', '你為了將前世的木工掌握用於今生的基礎建設而來。', '你為了將前世的木材知識用於今生的創新而來。'],
        vi: ['Bạn đến để sử dụng kỹ năng mộc từ kiếp trước trong sự chính xác và thủ công.', 'Bạn trở lại để áp dụng trí tuệ gỗ vào xây dựng cấu trúc.', 'Bạn đến để sử dụng sự kiên nhẫn mộc cho công việc chi tiết.', 'Bạn trở lại để sử dụng kiến thức gỗ cho xây dựng nền tảng.', 'Bạn đến để sử dụng độ chính xác mộc cho sự chính xác.', 'Bạn trở lại để sử dụng bản năng gỗ cho trực giác.', 'Bạn đến để sử dụng trách nhiệm mộc cho sáng tạo.', 'Bạn trở lại để sử dụng giảng dạy gỗ cho hướng dẫn.', 'Bạn đến để sử dụng sự thành thạo mộc cho xây dựng nền tảng.', 'Bạn trở lại để sử dụng kiến thức gỗ cho đổi mới.'],
        id: ['Anda datang untuk menggunakan keterampilan pertukangan masa lalu dalam presisi dan kerajinan.', 'Anda kembali untuk menerapkan kebijaksanaan kayu pada pembangunan struktur.', 'Anda datang untuk menggunakan kesabaran pertukangan untuk pekerjaan detail.', 'Anda kembali untuk menggunakan pengetahuan kayu untuk membangun fondasi.', 'Anda datang untuk menggunakan presisi pertukangan untuk akurasi.', 'Anda kembali untuk menggunakan insting kayu untuk intuisi.', 'Anda datang untuk menggunakan tanggung jawab pertukangan untuk kreasi.', 'Anda kembali untuk menggunakan pengajaran kayu untuk bimbingan.', 'Anda datang untuk menggunakan penguasaan pertukangan untuk membangun fondasi.', 'Anda kembali untuk menggunakan pengetahuan kayu untuk inovasi.']
      },
      lifeCount: {
        en: ['This is your 14th reincarnation.', 'You have lived a total of 21 lives so far.', 'This life is your 12th experience.', 'You have reincarnated 18 times up to this life.', 'This life follows your 13th past life.', 'You have lived 24 lives so far.', 'This is your 15th life.', 'You have reincarnated 20 times up to this life.', 'This life is a new beginning after your 16th past life.', 'You have built carpentry experience through 27 lives.'],
        ja: ['これはあなたの14回目の転生です。', 'これまでに合計21回の人生を生きました。', '今生は12回目の経験です。', '今生までに18回転生しました。', '今生は13番目の前世の後に続きます。', 'これまでに24回の人生を生きました。', '今生は15回目の人生です。', '今生までに20回転生しました。', '今生は16番目の前世を経た新たな始まりです。', 'これまでに27回の人生で大工の経験を積みました。'],
        'zh-CN': ['这是你的第14次转生。', '截至目前你总共经历了21次人生。', '今生是你的第12次体验。', '到今生为止你已经转生了18次。', '今生延续自你的第13次前世。', '截至目前你已经经历了24次人生。', '今生是你的第15次人生。', '到今生为止你已经转生了20次。', '今生是你第16次前世后的新开始。', '通过27次人生你积累了木工经验。'],
        'zh-TW': ['這是你的第14次轉生。', '截至目前你總共經歷了21次人生。', '今生是你的第12次體驗。', '到今生為止你已經轉生了18次。', '今生延續自你的第13次前世。', '截至目前你已經經歷了24次人生。', '今生是你的第15次人生。', '到今生為止你已經轉生了20次。', '今生是你第16次前世後的新開始。', '通過27次人生你積累了木工經驗。'],
        vi: ['Đây là lần tái sinh thứ 14 của bạn.', 'Bạn đã sống tổng cộng 21 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 12 của bạn.', 'Bạn đã tái sinh 18 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 13 của bạn.', 'Bạn đã sống 24 kiếp cho đến nay.', 'Đây là kiếp thứ 15 của bạn.', 'Bạn đã tái sinh 20 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 16 của bạn.', 'Bạn đã tích lũy kinh nghiệm mộc qua 27 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-14 Anda.', 'Anda telah menjalani total 21 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-12 Anda.', 'Anda telah bereinkarnasi 18 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-13 Anda.', 'Anda telah menjalani 24 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-15 Anda.', 'Anda telah bereinkarnasi 20 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-16 Anda.', 'Anda telah membangun pengalaman pertukangan melalui 27 kehidupan.']
      }
    }
  },
  31: {
    reincarnation: {
      era: {
        en: ['You were an ancient Egyptian stonemason.', 'In your past life, you were an ancient Chinese stonemason.', 'You were a Roman stonemason.', 'In your past life, you were a Greek stonemason.', 'You were a Japanese stonemason.', 'In your past life, you were an Indian stonemason.', 'You were a Celtic stonemason.', 'In your past life, you were a Persian stonemason.', 'You were a Mayan stonemason.', 'In your past life, you were a Korean stonemason.'],
        ja: ['あなたは古代エジプトの石工でした。', '前世であなたは古代中国の石工でした。', 'あなたはローマの石工でした。', '前世であなたはギリシャの石工でした。', 'あなたは日本の石工でした。', '前世であなたはインドの石工でした。', 'あなたはケルトの石工でした。', '前世であなたはペルシャの石工でした。', 'あなたはマヤの石工でした。', '前世であなたは韓国の石工でした。'],
        'zh-CN': ['你是古埃及的石匠。', '你的前世是古代中国的石匠。', '你是罗马的石匠。', '你的前世是希腊的石匠。', '你是日本的石匠。', '你的前世是印度的石匠。', '你是凯尔特的石匠。', '你的前世是波斯的石匠。', '你是玛雅的石匠。', '你的前世是韩国的石匠。'],
        'zh-TW': ['你是古埃及的石匠。', '你的前世是古代中國的石匠。', '你是羅馬的石匠。', '你的前世是希臘的石匠。', '你是日本的石匠。', '你的前世是印度的石匠。', '你是凱爾特的石匠。', '你的前世是波斯的石匠。', '你是瑪雅的石匠。', '你的前世是韓國的石匠。'],
        vi: ['Bạn là một thợ đá Ai Cập cổ đại.', 'Ở kiếp trước, bạn là một thợ đá Trung Quốc cổ đại.', 'Bạn là một thợ đá La Mã.', 'Ở kiếp trước, bạn là một thợ đá Hy Lạp.', 'Bạn là một thợ đá Nhật Bản.', 'Ở kiếp trước, bạn là một thợ đá Ấn Độ.', 'Bạn là một thợ đá Celtic.', 'Ở kiếp trước, bạn là một thợ đá Ba Tư.', 'Bạn là một thợ đá Maya.', 'Ở kiếp trước, bạn là một thợ đá Hàn Quốc.'],
        id: ['Anda adalah tukang batu Mesir kuno.', 'Di kehidupan lampau, Anda adalah tukang batu Tiongkok kuno.', 'Anda adalah tukang batu Romawi.', 'Di kehidupan lampau, Anda adalah tukang batu Yunani.', 'Anda adalah tukang batu Jepang.', 'Di kehidupan lampau, Anda adalah tukang batu India.', 'Anda adalah tukang batu Celtic.', 'Di kehidupan lampau, Anda adalah tukang batu Persia.', 'Anda adalah tukang batu Maya.', 'Di kehidupan lampau, Anda adalah tukang batu Korea.']
      },
      occupation: {
        en: ['You were a temple stonemason in your past life.', 'In your past life, you were a monument stonemason.', 'You were a bridge stonemason in your past life.', 'In your past life, you were a wall stonemason.', 'You were a decorative stonemason in your past life.', 'In your past life, you were a tomb stonemason.', 'You were a fortress stonemason in your past life.', 'In your past life, you were a road stonemason.', 'You were a sculpture stonemason in your past life.', 'In your past life, you were a stonemasonry teacher.'],
        ja: ['あなたは前世で寺院石工でした。', '前世であなたは記念碑石工でした。', 'あなたは前世で橋石工でした。', '前世であなたは壁石工でした。', 'あなたは前世で装飾石工でした。', '前世であなたは墓石工でした。', 'あなたは前世で要塞石工でした。', '前世であなたは道路石工でした。', 'あなたは前世で彫刻石工でした。', '前世であなたは石工教師でした。'],
        'zh-CN': ['你的前世是寺庙石匠。', '你的前世是纪念碑石匠。', '你的前世是桥梁石匠。', '你的前世是城墙石匠。', '你的前世是装饰石匠。', '你的前世是陵墓石匠。', '你的前世是堡垒石匠。', '你的前世是道路石匠。', '你的前世是雕塑石匠。', '你的前世是石工教师。'],
        'zh-TW': ['你的前世是寺廟石匠。', '你的前世是紀念碑石匠。', '你的前世是橋樑石匠。', '你的前世是城牆石匠。', '你的前世是裝飾石匠。', '你的前世是陵墓石匠。', '你的前世是堡壘石匠。', '你的前世是道路石匠。', '你的前世是雕塑石匠。', '你的前世是石工教師。'],
        vi: ['Bạn từng là thợ đá đền thờ ở kiếp trước.', 'Ở kiếp trước, bạn là thợ đá tượng đài.', 'Bạn từng là thợ đá cầu ở kiếp trước.', 'Ở kiếp trước, bạn là thợ đá tường.', 'Bạn từng là thợ đá trang trí ở kiếp trước.', 'Ở kiếp trước, bạn là thợ đá mộ.', 'Bạn từng là thợ đá pháo đài ở kiếp trước.', 'Ở kiếp trước, bạn là thợ đá đường.', 'Bạn từng là thợ đá điêu khắc ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên đá.'],
        id: ['Di kehidupan lampau, Anda adalah tukang batu kuil.', 'Di kehidupan lampau, Anda adalah tukang batu monumen.', 'Di kehidupan lampau, Anda adalah tukang batu jembatan.', 'Di kehidupan lampau, Anda adalah tukang batu tembok.', 'Di kehidupan lampau, Anda adalah tukang batu dekoratif.', 'Di kehidupan lampau, Anda adalah tukang batu makam.', 'Di kehidupan lampau, Anda adalah tukang batu benteng.', 'Di kehidupan lampau, Anda adalah tukang batu jalan.', 'Di kehidupan lampau, Anda adalah tukang batu patung.', 'Di kehidupan lampau, Anda adalah guru pertukangan batu.']
      },
      reason: {
        en: ['You came to use past stonemasonry skills in strength and endurance.', 'You returned to apply stone wisdom to foundation building.', 'You came to use stonemasonry patience for persistence.', 'You returned to use stone knowledge for structure building.', 'You came to use stonemasonry precision for accuracy.', 'You returned to use stone instincts for intuition.', 'You came to use stonemasonry responsibility for creation.', 'You returned to use stone teaching for guidance.', 'You came to use stonemasonry mastery for foundation building.', 'You returned to use stone knowledge for innovation.'],
        ja: ['前世の石工技術を今生の強さと持久力に活かすために来ました。', '前世の石の知恵を今生の基盤構築に用いるために来ました。', '前世の石工忍耐を今生の持続性に活かすために来ました。', '前世の石の知識を今生の構造構築に用いるために来ました。', '前世の石工精密さを今生の正確性に活かすために来ました。', '前世の石の本能を今生の直感に用いるために来ました。', '前世の石工責任を今生の創造に活かすために来ました。', '前世の石の教育を今生の指導に用いるために来ました。', '前世の石工習得を今生の基盤構築に活かすために来ました。', '前世の石の知識を今生の革新に用いるために来ました。'],
        'zh-CN': ['你为了将前世的石工技能用于今生的力量和耐力而来。', '你为了将前世的石头智慧用于今生的基础建设而来。', '你为了将前世的石工耐心用于今生的坚持而来。', '你为了将前世的石头知识用于今生的结构建设而来。', '你为了将前世的石工精度用于今生的准确性而来。', '你为了将前世的石头本能用于今生的直觉而来。', '你为了将前世的石工责任用于今生的创造而来。', '你为了将前世的石头教学用于今生的指导而来。', '你为了将前世的石工掌握用于今生的基础建设而来。', '你为了将前世的石头知识用于今生的创新而来。'],
        'zh-TW': ['你為了將前世的石工技能用於今生的力量和耐力而來。', '你為了將前世的石頭智慧用於今生的基礎建設而來。', '你為了將前世的石工耐心用於今生的堅持而來。', '你為了將前世的石頭知識用於今生的結構建設而來。', '你為了將前世的石工精度用於今生的準確性而來。', '你為了將前世的石頭本能用於今生的直覺而來。', '你為了將前世的石工責任用於今生的創造而來。', '你為了將前世的石頭教學用於今生的指導而來。', '你為了將前世的石工掌握用於今生的基礎建設而來。', '你為了將前世的石頭知識用於今生的創新而來。'],
        vi: ['Bạn đến để sử dụng kỹ năng đá từ kiếp trước trong sức mạnh và sức bền.', 'Bạn trở lại để áp dụng trí tuệ đá vào xây dựng nền tảng.', 'Bạn đến để sử dụng sự kiên nhẫn đá cho sự bền bỉ.', 'Bạn trở lại để sử dụng kiến thức đá cho xây dựng cấu trúc.', 'Bạn đến để sử dụng độ chính xác đá cho sự chính xác.', 'Bạn trở lại để sử dụng bản năng đá cho trực giác.', 'Bạn đến để sử dụng trách nhiệm đá cho sáng tạo.', 'Bạn trở lại để sử dụng giảng dạy đá cho hướng dẫn.', 'Bạn đến để sử dụng sự thành thạo đá cho xây dựng nền tảng.', 'Bạn trở lại để sử dụng kiến thức đá cho đổi mới.'],
        id: ['Anda datang untuk menggunakan keterampilan pertukangan batu masa lalu dalam kekuatan dan daya tahan.', 'Anda kembali untuk menerapkan kebijaksanaan batu pada pembangunan fondasi.', 'Anda datang untuk menggunakan kesabaran pertukangan batu untuk ketekunan.', 'Anda kembali untuk menggunakan pengetahuan batu untuk pembangunan struktur.', 'Anda datang untuk menggunakan presisi pertukangan batu untuk akurasi.', 'Anda kembali untuk menggunakan insting batu untuk intuisi.', 'Anda datang untuk menggunakan tanggung jawab pertukangan batu untuk kreasi.', 'Anda kembali untuk menggunakan pengajaran batu untuk bimbingan.', 'Anda datang untuk menggunakan penguasaan pertukangan batu untuk membangun fondasi.', 'Anda kembali untuk menggunakan pengetahuan batu untuk inovasi.']
      },
      lifeCount: {
        en: ['This is your 15th reincarnation.', 'You have lived a total of 22 lives so far.', 'This life is your 13th experience.', 'You have reincarnated 19 times up to this life.', 'This life follows your 14th past life.', 'You have lived 25 lives so far.', 'This is your 16th life.', 'You have reincarnated 21 times up to this life.', 'This life is a new beginning after your 17th past life.', 'You have built stonemasonry experience through 28 lives.'],
        ja: ['これはあなたの15回目の転生です。', 'これまでに合計22回の人生を生きました。', '今生は13回目の経験です。', '今生までに19回転生しました。', '今生は14番目の前世の後に続きます。', 'これまでに25回の人生を生きました。', '今生は16回目の人生です。', '今生までに21回転生しました。', '今生は17番目の前世を経た新たな始まりです。', 'これまでに28回の人生で石工の経験を積みました。'],
        'zh-CN': ['这是你的第15次转生。', '截至目前你总共经历了22次人生。', '今生是你的第13次体验。', '到今生为止你已经转生了19次。', '今生延续自你的第14次前世。', '截至目前你已经经历了25次人生。', '今生是你的第16次人生。', '到今生为止你已经转生了21次。', '今生是你第17次前世后的新开始。', '通过28次人生你积累了石工经验。'],
        'zh-TW': ['這是你的第15次轉生。', '截至目前你總共經歷了22次人生。', '今生是你的第13次體驗。', '到今生為止你已經轉生了19次。', '今生延續自你的第14次前世。', '截至目前你已經經歷了25次人生。', '今生是你的第16次人生。', '到今生為止你已經轉生了21次。', '今生是你第17次前世後的新開始。', '通過28次人生你積累了石工經驗。'],
        vi: ['Đây là lần tái sinh thứ 15 của bạn.', 'Bạn đã sống tổng cộng 22 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 13 của bạn.', 'Bạn đã tái sinh 19 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 14 của bạn.', 'Bạn đã sống 25 kiếp cho đến nay.', 'Đây là kiếp thứ 16 của bạn.', 'Bạn đã tái sinh 21 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 17 của bạn.', 'Bạn đã tích lũy kinh nghiệm đá qua 28 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-15 Anda.', 'Anda telah menjalani total 22 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-13 Anda.', 'Anda telah bereinkarnasi 19 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-14 Anda.', 'Anda telah menjalani 25 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-16 Anda.', 'Anda telah bereinkarnasi 21 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-17 Anda.', 'Anda telah membangun pengalaman pertukangan batu melalui 28 kehidupan.']
      }
    }
  }
};