import { FaceReincarnationTranslations } from '../merge';

export const batch27: FaceReincarnationTranslations = {
  34: {
    reincarnation: {
      era: {
        en: ['You were an ancient Egyptian metalworker.', 'In your past life, you were an ancient Chinese metalworker.', 'You were a Roman metalworker.', 'In your past life, you were a Greek metalworker.', 'You were a Japanese metalworker.', 'In your past life, you were an Indian metalworker.', 'You were a Celtic metalworker.', 'In your past life, you were a Persian metalworker.', 'You were a Mayan metalworker.', 'In your past life, you were a Korean metalworker.'],
        ja: ['あなたは古代エジプトの金属職人でした。', '前世であなたは古代中国の金属職人でした。', 'あなたはローマの金属職人でした。', '前世であなたはギリシャの金属職人でした。', 'あなたは日本の金属職人でした。', '前世であなたはインドの金属職人でした。', 'あなたはケルトの金属職人でした。', '前世であなたはペルシャの金属職人でした。', 'あなたはマヤの金属職人でした。', '前世であなたは韓国の金属職人でした。'],
        'zh-CN': ['你是古埃及的金属工匠。', '你的前世是古代中国的金属工匠。', '你是罗马的金属工匠。', '你的前世是希腊的金属工匠。', '你是日本的金属工匠。', '你的前世是印度的金属工匠。', '你是凯尔特的金属工匠。', '你的前世是波斯的金属工匠。', '你是玛雅的金属工匠。', '你的前世是韩国的金属工匠。'],
        'zh-TW': ['你是古埃及的金屬工匠。', '你的前世是古代中國的金屬工匠。', '你是羅馬的金屬工匠。', '你的前世是希臘的金屬工匠。', '你是日本的金屬工匠。', '你的前世是印度的金屬工匠。', '你是凱爾特的金屬工匠。', '你的前世是波斯的重屬工匠。', '你是瑪雅的金屬工匠。', '你的前世是韓國的金屬工匠。'],
        vi: ['Bạn là một thợ kim loại Ai Cập cổ đại.', 'Ở kiếp trước, bạn là một thợ kim loại Trung Quốc cổ đại.', 'Bạn là một thợ kim loại La Mã.', 'Ở kiếp trước, bạn là một thợ kim loại Hy Lạp.', 'Bạn là một thợ kim loại Nhật Bản.', 'Ở kiếp trước, bạn là một thợ kim loại Ấn Độ.', 'Bạn là một thợ kim loại Celtic.', 'Ở kiếp trước, bạn là một thợ kim loại Ba Tư.', 'Bạn là một thợ kim loại Maya.', 'Ở kiếp trước, bạn là một thợ kim loại Hàn Quốc.'],
        id: ['Anda adalah pekerja logam Mesir kuno.', 'Di kehidupan lampau, Anda adalah pekerja logam Tiongkok kuno.', 'Anda adalah pekerja logam Romawi.', 'Di kehidupan lampau, Anda adalah pekerja logam Yunani.', 'Anda adalah pekerja logam Jepang.', 'Di kehidupan lampau, Anda adalah pekerja logam India.', 'Anda adalah pekerja logam Celtic.', 'Di kehidupan lampau, Anda adalah pekerja logam Persia.', 'Anda adalah pekerja logam Maya.', 'Di kehidupan lampau, Anda adalah pekerja logam Korea.']
      },
      occupation: {
        en: ['You were a blacksmith in your past life.', 'In your past life, you were a goldsmith.', 'You were a silversmith in your past life.', 'In your past life, you were a coppersmith.', 'You were a weaponsmith in your past life.', 'In your past life, you were a toolsmith.', 'You were a armorsmith in your past life.', 'In your past life, you were a jeweler.', 'You were a bellmaker in your past life.', 'In your past life, you were a metalworking teacher.'],
        ja: ['あなたは前世で鍛冶屋でした。', '前世であなたは金細工師でした。', 'あなたは前世で銀細工師でした。', '前世であなたは銅細工師でした。', 'あなたは前世で武器鍛冶でした。', '前世であなたは工具鍛冶でした。', 'あなたは前世で防具鍛冶でした。', '前世であなたは宝石商でした。', 'あなたは前世で鐘職人でした。', '前世であなたは金属加工教師でした。'],
        'zh-CN': ['你的前世是铁匠。', '你的前世是金匠。', '你的前世是银匠。', '你的前世是铜匠。', '你的前世是武器匠。', '你的前世是工具匠。', '你的前世是盔甲匠。', '你的前世是珠宝商。', '你的前世是制钟匠。', '你的前世是金属加工教师。'],
        'zh-TW': ['你的前世是鐵匠。', '你的前世是金匠。', '你的前世是銀匠。', '你的前世是銅匠。', '你的前世是武器匠。', '你的前世是工具匠。', '你的前世是盔甲匠。', '你的前世是珠寶商。', '你的前世是製鐘匠。', '你的前世是金屬加工教師。'],
        vi: ['Bạn từng là thợ rèn ở kiếp trước.', 'Ở kiếp trước, bạn là thợ vàng.', 'Bạn từng là thợ bạc ở kiếp trước.', 'Ở kiếp trước, bạn là thợ đồng.', 'Bạn từng là thợ vũ khí ở kiếp trước.', 'Ở kiếp trước, bạn là thợ dụng cụ.', 'Bạn từng là thợ áo giáp ở kiếp trước.', 'Ở kiếp trước, bạn là thợ trang sức.', 'Bạn từng là thợ chuông ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên kim loại.'],
        id: ['Di kehidupan lampau, Anda adalah pandai besi.', 'Di kehidupan lampau, Anda adalah tukang emas.', 'Di kehidupan lampau, Anda adalah tukang perak.', 'Di kehidupan lampau, Anda adalah tukang tembaga.', 'Di kehidupan lampau, Anda adalah tukang senjata.', 'Di kehidupan lampau, Anda adalah tukang alat.', 'Di kehidupan lampau, Anda adalah tukang baju besi.', 'Di kehidupan lampau, Anda adalah tukang perhiasan.', 'Di kehidupan lampau, Anda adalah pembuat lonceng.', 'Di kehidupan lampau, Anda adalah guru pekerjaan logam.']
      },
      reason: {
        en: ['You came to use past metalworking skills in strength and precision.', 'You returned to apply fire wisdom to transformation.', 'You came to use metalworking patience for detailed work.', 'You returned to use fire knowledge for creation.', 'You came to use metalworking precision for craftsmanship.', 'You returned to use fire instincts for intuition.', 'You came to use metalworking responsibility for creation.', 'You returned to use fire teaching for guidance.', 'You came to use metalworking mastery for foundation building.', 'You returned to use fire knowledge for innovation.'],
        ja: ['前世の金属加工技術を今生の強さと精密さに活かすために来ました。', '前世の火の知恵を今生の変容に用いるために来ました。', '前世の金属加工忍耐を今生の詳細作業に活かすために来ました。', '前世の火の知識を今生の創造に用いるために来ました。', '前世の金属加工精密さを今生の職人技に活かすために来ました。', '前世の火の本能を今生の直感に用いるために来ました。', '前世の金属加工責任を今生の創造に活かすために来ました。', '前世の火の教育を今生の指導に用いるために来ました。', '前世の金属加工習得を今生の基盤構築に活かすために来ました。', '前世の火の知識を今生の革新に用いるために来ました。'],
        'zh-CN': ['你为了将前世的金属加工技能用于今生的力量和精确而来。', '你为了将前世的火智慧用于今生的转化而来。', '你为了将前世的金属加工耐心用于今生的细致工作而来。', '你为了将前世的火知识用于今生的创造而来。', '你为了将前世的金属加工精度用于今生的工艺而来。', '你为了将前世的火本能用于今生的直觉而来。', '你为了将前世的金属加工责任用于今生的创造而来。', '你为了将前世的火教学用于今生的指导而来。', '你为了将前世的金属加工掌握用于今生的基础建设而来。', '你为了将前世的火知识用于今生的创新而来。'],
        'zh-TW': ['你為了將前世的金屬加工技能用於今生的力量和精確而來。', '你為了將前世的火智慧用於今生的轉化而來。', '你為了將前世的金屬加工耐心用於今生的細緻工作而來。', '你為了將前世的火知識用於今生的創造而來。', '你為了將前世的金屬加工精度用於今生的工藝而來。', '你為了將前世的火本能用於今生的直覺而來。', '你為了將前世的金屬加工責任用於今生的創造而來。', '你為了將前世的火教學用於今生的指導而來。', '你為了將前世的金屬加工掌握用於今生的基礎建設而來。', '你為了將前世的火知識用於今生的創新而來。'],
        vi: ['Bạn đến để sử dụng kỹ năng kim loại từ kiếp trước trong sức mạnh và chính xác.', 'Bạn trở lại để áp dụng trí tuệ lửa vào sự biến đổi.', 'Bạn đến để sử dụng sự kiên nhẫn kim loại cho công việc chi tiết.', 'Bạn trở lại để sử dụng kiến thức lửa cho sáng tạo.', 'Bạn đến để sử dụng độ chính xác kim loại cho thủ công.', 'Bạn trở lại để sử dụng bản năng lửa cho trực giác.', 'Bạn đến để sử dụng trách nhiệm kim loại cho sáng tạo.', 'Bạn trở lại để sử dụng giảng dạy lửa cho hướng dẫn.', 'Bạn đến để sử dụng sự thành thạo kim loại cho xây dựng nền tảng.', 'Bạn trở lại để sử dụng kiến thức lửa cho đổi mới.'],
        id: ['Anda datang untuk menggunakan keterampilan pekerjaan logam masa lalu dalam kekuatan dan presisi.', 'Anda kembali untuk menerapkan kebijaksanaan api pada transformasi.', 'Anda datang untuk menggunakan kesabaran pekerjaan logam untuk pekerjaan detail.', 'Anda kembali untuk menggunakan pengetahuan api untuk kreasi.', 'Anda datang untuk menggunakan presisi pekerjaan logam untuk kerajinan.', 'Anda kembali untuk menggunakan insting api untuk intuisi.', 'Anda datang untuk menggunakan tanggung jawab pekerjaan logam untuk kreasi.', 'Anda kembali untuk menggunakan pengajaran api untuk bimbingan.', 'Anda datang untuk menggunakan penguasaan pekerjaan logam untuk membangun fondasi.', 'Anda kembali untuk menggunakan pengetahuan api untuk inovasi.']
      },
      lifeCount: {
        en: ['This is your 18th reincarnation.', 'You have lived a total of 25 lives so far.', 'This life is your 16th experience.', 'You have reincarnated 22 times up to this life.', 'This life follows your 17th past life.', 'You have lived 28 lives so far.', 'This is your 19th life.', 'You have reincarnated 24 times up to this life.', 'This life is a new beginning after your 20th past life.', 'You have built metalworking experience through 31 lives.'],
        ja: ['これはあなたの18回目の転生です。', 'これまでに合計25回の人生を生きました。', '今生は16回目の経験です。', '今生までに22回転生しました。', '今生は17番目の前世の後に続きます。', 'これまでに28回の人生を生きました。', '今生は19回目の人生です。', '今生までに24回転生しました。', '今生は20番目の前世を経た新たな始まりです。', 'これまでに31回の人生で金属加工の経験を積みました。'],
        'zh-CN': ['这是你的第18次转生。', '截至目前你总共经历了25次人生。', '今生是你的第16次体验。', '到今生为止你已经转生了22次。', '今生延续自你的第17次前世。', '截至目前你已经经历了28次人生。', '今生是你的第19次人生。', '到今生为止你已经转生了24次。', '今生是你第20次前世后的新开始。', '通过31次人生你积累了金属加工经验。'],
        'zh-TW': ['這是你的第18次轉生。', '截至目前你總共經歷了25次人生。', '今生是你的第16次體驗。', '到今生為止你已經轉生了22次。', '今生延續自你的第17次前世。', '截至目前你已經經歷了28次人生。', '今生是你的第19次人生。', '到今生為止你已經轉生了24次。', '今生是你第20次前世後的新開始。', '通過31次人生你積累了金屬加工經驗。'],
        vi: ['Đây là lần tái sinh thứ 18 của bạn.', 'Bạn đã sống tổng cộng 25 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 16 của bạn.', 'Bạn đã tái sinh 22 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 17 của bạn.', 'Bạn đã sống 28 kiếp cho đến nay.', 'Đây là kiếp thứ 19 của bạn.', 'Bạn đã tái sinh 24 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 20 của bạn.', 'Bạn đã tích lũy kinh nghiệm kim loại qua 31 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-18 Anda.', 'Anda telah menjalani total 25 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-16 Anda.', 'Anda telah bereinkarnasi 22 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-17 Anda.', 'Anda telah menjalani 28 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-19 Anda.', 'Anda telah bereinkarnasi 24 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-20 Anda.', 'Anda telah membangun pengalaman pekerjaan logam melalui 31 kehidupan.']
      }
    }
  },
  35: {
    reincarnation: {
      era: {
        en: ['You were an ancient Egyptian weaver.', 'In your past life, you were an ancient Chinese weaver.', 'You were a Roman weaver.', 'In your past life, you were a Greek weaver.', 'You were a Japanese weaver.', 'In your past life, you were an Indian weaver.', 'You were a Celtic weaver.', 'In your past life, you were a Persian weaver.', 'You were a Mayan weaver.', 'In your past life, you were a Korean weaver.'],
        ja: ['あなたは古代エジプトの織工でした。', '前世であなたは古代中国の織工でした。', 'あなたはローマの織工でした。', '前世であなたはギリシャの織工でした。', 'あなたは日本の織工でした。', '前世であなたはインドの織工でした。', 'あなたはケルトの織工でした。', '前世であなたはペルシャの織工でした。', 'あなたはマヤの織工でした。', '前世であなたは韓国の織工でした。'],
        'zh-CN': ['你是古埃及的织工。', '你的前世是古代中国的织工。', '你是罗马的织工。', '你的前世是希腊的织工。', '你是日本的织工。', '你的前世是印度的织工。', '你是凯尔特的织工。', '你的前世是波斯的织工。', '你是玛雅的织工。', '你的前世是韩国的织工。'],
        'zh-TW': ['你是古埃及的織工。', '你的前世是古代中國的織工。', '你是羅馬的織工。', '你的前世是希臘的織工。', '你是日本的織工。', '你的前世是印度的織工。', '你是凱爾特的織工。', '你的前世是波斯的織工。', '你是瑪雅的織工。', '你的前世是韓國的織工。'],
        vi: ['Bạn là một thợ dệt Ai Cập cổ đại.', 'Ở kiếp trước, bạn là một thợ dệt Trung Quốc cổ đại.', 'Bạn là một thợ dệt La Mã.', 'Ở kiếp trước, bạn là một thợ dệt Hy Lạp.', 'Bạn là một thợ dệt Nhật Bản.', 'Ở kiếp trước, bạn là một thợ dệt Ấn Độ.', 'Bạn là một thợ dệt Celtic.', 'Ở kiếp trước, bạn là một thợ dệt Ba Tư.', 'Bạn là một thợ dệt Maya.', 'Ở kiếp trước, bạn là một thợ dệt Hàn Quốc.'],
        id: ['Anda adalah penenun Mesir kuno.', 'Di kehidupan lampau, Anda adalah penenun Tiongkok kuno.', 'Anda adalah penenun Romawi.', 'Di kehidupan lampau, Anda adalah penenun Yunani.', 'Anda adalah penenun Jepang.', 'Di kehidupan lampau, Anda adalah penenun India.', 'Anda adalah penenun Celtic.', 'Di kehidupan lampau, Anda adalah penenun Persia.', 'Anda adalah penenun Maya.', 'Di kehidupan lampau, Anda adalah penenun Korea.']
      },
      occupation: {
        en: ['You were a textile weaver in your past life.', 'In your past life, you were a tapestry weaver.', 'You were a carpet weaver in your past life.', 'In your past life, you were a clothing weaver.', 'You were a ceremonial weaver in your past life.', 'In your past life, you were a decorative weaver.', 'You were a functional weaver in your past life.', 'In your past life, you were a ritual weaver.', 'You were a artistic weaver in your past life.', 'In your past life, you were a weaving teacher.'],
        ja: ['あなたは前世で織物織工でした。', '前世であなたはタペストリー織工でした。', 'あなたは前世で絨毯織工でした。', '前世であなたは衣類織工でした。', 'あなたは前世で儀式織工でした。', '前世であなたは装飾織工でした。', 'あなたは前世で機能織工でした。', '前世であなたは儀式用織工でした。', 'あなたは前世で芸術織工でした。', '前世であなたは織物教師でした。'],
        'zh-CN': ['你的前世是纺织品织工。', '你的前世是挂毯织工。', '你的前世是地毯织工。', '你的前世是服装织工。', '你的前世是仪式织工。', '你的前世是装饰织工。', '你的前世是功能织工。', '你的前世是仪式织工。', '你的前世是艺术织工。', '你的前世是织造教师。'],
        'zh-TW': ['你的前世是紡織品織工。', '你的前世是掛毯織工。', '你的前世是地毯織工。', '你的前世是服裝織工。', '你的前世是儀式織工。', '你的前世是裝飾織工。', '你的前世是功能織工。', '你的前世是儀式織工。', '你的前世是藝術織工。', '你的前世是織造教師。'],
        vi: ['Bạn từng là thợ dệt vải ở kiếp trước.', 'Ở kiếp trước, bạn là thợ dệt thảm treo tường.', 'Bạn từng là thợ dệt thảm ở kiếp trước.', 'Ở kiếp trước, bạn là thợ dệt quần áo.', 'Bạn từng là thợ dệt nghi lễ ở kiếp trước.', 'Ở kiếp trước, bạn là thợ dệt trang trí.', 'Bạn từng là thợ dệt chức năng ở kiếp trước.', 'Ở kiếp trước, bạn là thợ dệt nghi lễ.', 'Bạn từng là thợ dệt nghệ thuật ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên dệt.'],
        id: ['Di kehidupan lampau, Anda adalah penenun tekstil.', 'Di kehidupan lampau, Anda adalah penenun permadani.', 'Di kehidupan lampau, Anda adalah penenun karpet.', 'Di kehidupan lampau, Anda adalah penenun pakaian.', 'Di kehidupan lampau, Anda adalah penenun upacara.', 'Di kehidupan lampau, Anda adalah penenun dekoratif.', 'Di kehidupan lampau, Anda adalah penenun fungsional.', 'Di kehidupan lampau, Anda adalah penenun ritual.', 'Di kehidupan lampau, Anda adalah penenun artistik.', 'Di kehidupan lampau, Anda adalah guru menenun.']
      },
      reason: {
        en: ['You came to use past weaving skills in patience and creativity.', 'You returned to apply thread wisdom to connection building.', 'You came to use weaving patience for detailed work.', 'You returned to use thread knowledge for creation.', 'You came to use weaving precision for craftsmanship.', 'You returned to use thread instincts for intuition.', 'You came to use weaving responsibility for beauty.', 'You returned to use thread teaching for guidance.', 'You came to use weaving mastery for foundation building.', 'You returned to use thread knowledge for innovation.'],
        ja: ['前世の織物技術を今生の忍耐と創造性に活かすために来ました。', '前世の糸の知恵を今生の繋がり構築に用いるために来ました。', '前世の織物忍耐を今生の詳細作業に活かすために来ました。', '前世の糸の知識を今生の創造に用いるために来ました。', '前世の織物精密さを今生の職人技に活かすために来ました。', '前世の糸の本能を今生の直感に用いるために来ました。', '前世の織物責任を今生の美しさに活かすために来ました。', '前世の糸の教育を今生の指導に用いるために来ました。', '前世の織物習得を今生の基盤構築に活かすために来ました。', '前世の糸の知識を今生の革新に用いるために来ました。'],
        'zh-CN': ['你为了将前世的织造技能用于今生的耐心和创造性而来。', '你为了将前世的线智慧用于今生的连接建设而来。', '你为了将前世的织造耐心用于今生的细致工作而来。', '你为了将前世的线知识用于今生的创造而来。', '你为了将前世的织造精度用于今生的工艺而来。', '你为了将前世的线本能用于今生的直觉而来。', '你为了将前世的织造责任用于今生的美丽而来。', '你为了将前世的线教学用于今生的指导而来。', '你为了将前世的织造掌握用于今生的基础建设而来。', '你为了将前世的线知识用于今生的创新而来。'],
        'zh-TW': ['你為了將前世的織造技能用於今生的耐心和創造性而來。', '你為了將前世的線智慧用於今生的連接建設而來。', '你為了將前世的織造耐心用於今生的細緻工作而來。', '你為了將前世的線知識用於今生的創造而來。', '你為了將前世的織造精度用於今生的工藝而來。', '你為了將前世的線本能用於今生的直覺而來。', '你為了將前世的織造責任用於今生的美麗而來。', '你為了將前世的線教學用於今生的指導而來。', '你為了將前世的織造掌握用於今生的基礎建設而來。', '你為了將前世的線知識用於今生的創新而來。'],
        vi: ['Bạn đến để sử dụng kỹ năng dệt từ kiếp trước trong sự kiên nhẫn và sáng tạo.', 'Bạn trở lại để áp dụng trí tuệ sợi vào xây dựng kết nối.', 'Bạn đến để sử dụng sự kiên nhẫn dệt cho công việc chi tiết.', 'Bạn trở lại để sử dụng kiến thức sợi cho sáng tạo.', 'Bạn đến để sử dụng độ chính xác dệt cho thủ công.', 'Bạn trở lại để sử dụng bản năng sợi cho trực giác.', 'Bạn đến để sử dụng trách nhiệm dệt cho vẻ đẹp.', 'Bạn trở lại để sử dụng giảng dạy sợi cho hướng dẫn.', 'Bạn đến để sử dụng sự thành thạo dệt cho xây dựng nền tảng.', 'Bạn trở lại để sử dụng kiến thức sợi cho đổi mới.'],
        id: ['Anda datang untuk menggunakan keterampilan menenun masa lalu dalam kesabaran dan kreativitas.', 'Anda kembali untuk menerapkan kebijaksanaan benang pada pembangunan koneksi.', 'Anda datang untuk menggunakan kesabaran menenun untuk pekerjaan detail.', 'Anda kembali untuk menggunakan pengetahuan benang untuk kreasi.', 'Anda datang untuk menggunakan presisi menenun untuk kerajinan.', 'Anda kembali untuk menggunakan insting benang untuk intuisi.', 'Anda datang untuk menggunakan tanggung jawab menenun untuk keindahan.', 'Anda kembali untuk menggunakan pengajaran benang untuk bimbingan.', 'Anda datang untuk menggunakan penguasaan menenun untuk membangun fondasi.', 'Anda kembali untuk menggunakan pengetahuan benang untuk inovasi.']
      },
      lifeCount: {
        en: ['This is your 19th reincarnation.', 'You have lived a total of 26 lives so far.', 'This life is your 17th experience.', 'You have reincarnated 23 times up to this life.', 'This life follows your 18th past life.', 'You have lived 29 lives so far.', 'This is your 20th life.', 'You have reincarnated 25 times up to this life.', 'This life is a new beginning after your 21st past life.', 'You have built weaving experience through 32 lives.'],
        ja: ['これはあなたの19回目の転生です。', 'これまでに合計26回の人生を生きました。', '今生は17回目の経験です。', '今生までに23回転生しました。', '今生は18番目の前世の後に続きます。', 'これまでに29回の人生を生きました。', '今生は20回目の人生です。', '今生までに25回転生しました。', '今生は21番目の前世を経た新たな始まりです。', 'これまでに32回の人生で織物の経験を積みました。'],
        'zh-CN': ['这是你的第19次转生。', '截至目前你总共经历了26次人生。', '今生是你的第17次体验。', '到今生为止你已经转生了23次。', '今生延续自你的第18次前世。', '截至目前你已经经历了29次人生。', '今生是你的第20次人生。', '到今生为止你已经转生了25次。', '今生是你第21次前世后的新开始。', '通过32次人生你积累了织造经验。'],
        'zh-TW': ['這是你的第19次轉生。', '截至目前你總共經歷了26次人生。', '今生是你的第17次體驗。', '到今生為止你已經轉生了23次。', '今生延續自你的第18次前世。', '截至目前你已經經歷了29次人生。', '今生是你的第20次人生。', '到今生為止你已經轉生了25次。', '今生是你第21次前世後的新開始。', '通過32次人生你積累了織造經驗。'],
        vi: ['Đây là lần tái sinh thứ 19 của bạn.', 'Bạn đã sống tổng cộng 26 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 17 của bạn.', 'Bạn đã tái sinh 23 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 18 của bạn.', 'Bạn đã sống 29 kiếp cho đến nay.', 'Đây là kiếp thứ 20 của bạn.', 'Bạn đã tái sinh 25 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 21 của bạn.', 'Bạn đã tích lũy kinh nghiệm dệt qua 32 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-19 Anda.', 'Anda telah menjalani total 26 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-17 Anda.', 'Anda telah bereinkarnasi 23 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-18 Anda.', 'Anda telah menjalani 29 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-20 Anda.', 'Anda telah bereinkarnasi 25 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-21 Anda.', 'Anda telah membangun pengalaman menenun melalui 32 kehidupan.']
      }
    }
  }
};