import { FaceReincarnationTranslations } from '../merge';

export const batch23: FaceReincarnationTranslations = {
  26: {
    reincarnation: {
      era: {
        en: ['You were an ancient Egyptian herder.', 'In your past life, you were an ancient Chinese herder.', 'You were a Roman herder.', 'In your past life, you were a Greek herder.', 'You were a Japanese herder.', 'In your past life, you were an Indian herder.', 'You were a Celtic herder.', 'In your past life, you were a Persian herder.', 'You were a Mayan herder.', 'In your past life, you were a Korean herder.'],
        ja: ['あなたは古代エジプトの牧畜業者でした。', '前世であなたは古代中国の牧畜業者でした。', 'あなたはローマの牧畜業者でした。', '前世であなたはギリシャの牧畜業者でした。', 'あなたは日本の牧畜業者でした。', '前世であなたはインドの牧畜業者でした。', 'あなたはケルトの牧畜業者でした。', '前世であなたはペルシャの牧畜業者でした。', 'あなたはマヤの牧畜業者でした。', '前世であなたは韓国の牧畜業者でした。'],
        'zh-CN': ['你是古埃及的牧民。', '你的前世是古代中国的牧民。', '你是罗马的牧民。', '你的前世是希腊的牧民。', '你是日本的牧民。', '你的前世是印度的牧民。', '你是凯尔特的牧民。', '你的前世是波斯的牧民。', '你是玛雅的牧民。', '你的前世是韩国的牧民。'],
        'zh-TW': ['你是古埃及的牧民。', '你的前世是古代中國的牧民。', '你是羅馬的牧民。', '你的前世是希臘的牧民。', '你是日本的牧民。', '你的前世是印度的牧民。', '你是凱爾特的牧民。', '你的前世是波斯的牧民。', '你是瑪雅的牧民。', '你的前世是韓國的牧民。'],
        vi: ['Bạn là một người chăn nuôi Ai Cập cổ đại.', 'Ở kiếp trước, bạn là một người chăn nuôi Trung Quốc cổ đại.', 'Bạn là một người chăn nuôi La Mã.', 'Ở kiếp trước, bạn là một người chăn nuôi Hy Lạp.', 'Bạn là một người chăn nuôi Nhật Bản.', 'Ở kiếp trước, bạn là một người chăn nuôi Ấn Độ.', 'Bạn là một người chăn nuôi Celtic.', 'Ở kiếp trước, bạn là một người chăn nuôi Ba Tư.', 'Bạn là một người chăn nuôi Maya.', 'Ở kiếp trước, bạn là một người chăn nuôi Hàn Quốc.'],
        id: ['Anda adalah peternak Mesir kuno.', 'Di kehidupan lampau, Anda adalah peternak Tiongkok kuno.', 'Anda adalah peternak Romawi.', 'Di kehidupan lampau, Anda adalah peternak Yunani.', 'Anda adalah peternak Jepang.', 'Di kehidupan lampau, Anda adalah peternak India.', 'Anda adalah peternak Celtic.', 'Di kehidupan lampau, Anda adalah peternak Persia.', 'Anda adalah peternak Maya.', 'Di kehidupan lampau, Anda adalah peternak Korea.']
      },
      occupation: {
        en: ['You were a sheep herder in your past life.', 'In your past life, you were a cattle herder.', 'You were a goat herder in your past life.', 'In your past life, you were a horse herder.', 'You were a camel herder in your past life.', 'In your past life, you were a yak herder.', 'You were a reindeer herder in your past life.', 'In your past life, you were a buffalo herder.', 'You were a llama herder in your past life.', 'In your past life, you were a herding teacher.'],
        ja: ['あなたは前世で羊飼いでした。', '前世であなたは牛飼いでした。', 'あなたは前世で山羊飼いでした。', '前世であなたは馬飼いでした。', 'あなたは前世でラクダ飼いでした。', '前世であなたはヤク飼いでした。', 'あなたは前世でトナカイ飼いでした。', '前世であなたは水牛飼いでした。', 'あなたは前世でリャマ飼いでした。', '前世であなたは牧畜教師でした。'],
        'zh-CN': ['你的前世是牧羊人。', '你的前世是牧牛人。', '你的前世是牧羊人。', '你的前世是牧马人。', '你的前世是牧驼人。', '你的前世是牧牦牛人。', '你的前世是牧驯鹿人。', '你的前世是牧水牛人。', '你的前世是牧羊驼人。', '你的前世是畜牧教师。'],
        'zh-TW': ['你的前世是牧羊人。', '你的前世是牧牛人。', '你的前世是牧羊人。', '你的前世是牧馬人。', '你的前世是牧駝人。', '你的前世是牧犛牛人。', '你的前世是牧馴鹿人。', '你的前世是牧水牛人。', '你的前世是牧羊駝人。', '你的前世是畜牧教師。'],
        vi: ['Bạn từng là người chăn cừu ở kiếp trước.', 'Ở kiếp trước, bạn là người chăn bò.', 'Bạn từng là người chăn dê ở kiếp trước.', 'Ở kiếp trước, bạn là người chăn ngựa.', 'Bạn từng là người chăn lạc đà ở kiếp trước.', 'Ở kiếp trước, bạn là người chăn bò Tây Tạng.', 'Bạn từng là người chăn tuần lộc ở kiếp trước.', 'Ở kiếp trước, bạn là người chăn trâu.', 'Bạn từng là người chăn lạc đà không bướu ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên chăn nuôi.'],
        id: ['Di kehidupan lampau, Anda adalah penggembala domba.', 'Di kehidupan lampau, Anda adalah penggembala sapi.', 'Di kehidupan lampau, Anda adalah penggembala kambing.', 'Di kehidupan lampau, Anda adalah penggembala kuda.', 'Di kehidupan lampau, Anda adalah penggembala unta.', 'Di kehidupan lampau, Anda adalah penggembala yak.', 'Di kehidupan lampau, Anda adalah penggembala rusa kutub.', 'Di kehidupan lampau, Anda adalah penggembala kerbau.', 'Di kehidupan lampau, Anda adalah penggembala llama.', 'Di kehidupan lampau, Anda adalah guru peternakan.']
      },
      reason: {
        en: ['You came to use past herding skills in leadership.', 'You returned to apply animal care to nurturing others.', 'You came to use herding patience for persistence.', 'You returned to use animal wisdom for guidance.', 'You came to use herding knowledge for protection.', 'You returned to use animal instincts for intuition.', 'You came to use herding responsibility for duty.', 'You returned to use animal care for service.', 'You came to use herding mastery for foundation building.', 'You returned to use animal knowledge for innovation.'],
        ja: ['前世の牧畜技術を今生のリーダーシップに活かすために来ました。', '前世の動物ケアを今生の他者育成に用いるために来ました。', '前世の牧畜忍耐を今生の持続性に活かすために来ました。', '前世の動物知恵を今生の指導に用いるために来ました。', '前世の牧畜知識を今生の保護に活かすために来ました。', '前世の動物本能を今生の直感に用いるために来ました。', '前世の牧畜責任を今生の義務に活かすために来ました。', '前世の動物ケアを今生の奉仕に用いるために来ました。', '前世の牧畜習得を今生の基盤構築に活かすために来ました。', '前世の動物知識を今生の革新に用いるために来ました。'],
        'zh-CN': ['你为了将前世的畜牧技能用于今生的领导力而来。', '你为了将前世的动物护理用于今生的培育他人而来。', '你为了将前世的畜牧耐心用于今生的坚持而来。', '你为了将前世的动物智慧用于今生的指导而来。', '你为了将前世的畜牧知识用于今生的保护而来。', '你为了将前世的动物本能用于今生的直觉而来。', '你为了将前世的畜牧责任用于今生的义务而来。', '你为了将前世的动物护理用于今生的服务而来。', '你为了将前世的畜牧掌握用于今生的基础建设而来。', '你为了将前世的动物知识用于今生的创新而来。'],
        'zh-TW': ['你為了將前世的畜牧技能用於今生的領導力而來。', '你為了將前世的動物護理用於今生的培育他人而來。', '你為了將前世的畜牧耐心用於今生的堅持而來。', '你為了將前世的動物智慧用於今生的指導而來。', '你為了將前世的畜牧知識用於今生的保護而來。', '你為了將前世的動物本能用於今生的直覺而來。', '你為了將前世的畜牧責任用於今生的義務而來。', '你為了將前世的動物護理用於今生的服務而來。', '你為了將前世的畜牧掌握用於今生的基礎建設而來。', '你為了將前世的動物知識用於今生的創新而來。'],
        vi: ['Bạn đến để sử dụng kỹ năng chăn nuôi từ kiếp trước trong lãnh đạo.', 'Bạn trở lại để áp dụng chăm sóc động vật vào nuôi dưỡng người khác.', 'Bạn đến để sử dụng sự kiên nhẫn chăn nuôi cho sự bền bỉ.', 'Bạn trở lại để sử dụng trí tuệ động vật cho hướng dẫn.', 'Bạn đến để sử dụng kiến thức chăn nuôi cho bảo vệ.', 'Bạn trở lại để sử dụng bản năng động vật cho trực giác.', 'Bạn đến để sử dụng trách nhiệm chăn nuôi cho nghĩa vụ.', 'Bạn trở lại để sử dụng chăm sóc động vật cho phục vụ.', 'Bạn đến để sử dụng sự thành thạo chăn nuôi cho xây dựng nền tảng.', 'Bạn trở lại để sử dụng kiến thức động vật cho đổi mới.'],
        id: ['Anda datang untuk menggunakan keterampilan peternakan masa lalu dalam kepemimpinan.', 'Anda kembali untuk menerapkan perawatan hewan pada memelihara orang lain.', 'Anda datang untuk menggunakan kesabaran peternakan untuk ketekunan.', 'Anda kembali untuk menggunakan kebijaksanaan hewan untuk bimbingan.', 'Anda datang untuk menggunakan pengetahuan peternakan untuk perlindungan.', 'Anda kembali untuk menggunakan insting hewan untuk intuisi.', 'Anda datang untuk menggunakan tanggung jawab peternakan untuk kewajiban.', 'Anda kembali untuk menggunakan perawatan hewan untuk pelayanan.', 'Anda datang untuk menggunakan penguasaan peternakan untuk membangun fondasi.', 'Anda kembali untuk menggunakan pengetahuan hewan untuk inovasi.']
      },
      lifeCount: {
        en: ['This is your 10th reincarnation.', 'You have lived a total of 17 lives so far.', 'This life is your 8th experience.', 'You have reincarnated 14 times up to this life.', 'This life follows your 9th past life.', 'You have lived 20 lives so far.', 'This is your 11th life.', 'You have reincarnated 16 times up to this life.', 'This life is a new beginning after your 12th past life.', 'You have built herding experience through 23 lives.'],
        ja: ['これはあなたの10回目の転生です。', 'これまでに合計17回の人生を生きました。', '今生は8回目の経験です。', '今生までに14回転生しました。', '今生は9番目の前世の後に続きます。', 'これまでに20回の人生を生きました。', '今生は11回目の人生です。', '今生までに16回転生しました。', '今生は12番目の前世を経た新たな始まりです。', 'これまでに23回の人生で牧畜の経験を積みました。'],
        'zh-CN': ['这是你的第10次转生。', '截至目前你总共经历了17次人生。', '今生是你的第8次体验。', '到今生为止你已经转生了14次。', '今生延续自你的第9次前世。', '截至目前你已经经历了20次人生。', '今生是你的第11次人生。', '到今生为止你已经转生了16次。', '今生是你第12次前世后的新开始。', '通过23次人生你积累了畜牧经验。'],
        'zh-TW': ['這是你的第10次轉生。', '截至目前你總共經歷了17次人生。', '今生是你的第8次體驗。', '到今生為止你已經轉生了14次。', '今生延續自你的第9次前世。', '截至目前你已經經歷了20次人生。', '今生是你的第11次人生。', '到今生為止你已經轉生了16次。', '今生是你第12次前世後的新開始。', '通過23次人生你積累了畜牧經驗。'],
        vi: ['Đây là lần tái sinh thứ 10 của bạn.', 'Bạn đã sống tổng cộng 17 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 8 của bạn.', 'Bạn đã tái sinh 14 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 9 của bạn.', 'Bạn đã sống 20 kiếp cho đến nay.', 'Đây là kiếp thứ 11 của bạn.', 'Bạn đã tái sinh 16 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 12 của bạn.', 'Bạn đã tích lũy kinh nghiệm chăn nuôi qua 23 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-10 Anda.', 'Anda telah menjalani total 17 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-8 Anda.', 'Anda telah bereinkarnasi 14 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-9 Anda.', 'Anda telah menjalani 20 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-11 Anda.', 'Anda telah bereinkarnasi 16 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-12 Anda.', 'Anda telah membangun pengalaman peternakan melalui 23 kehidupan.']
      }
    }
  },
  27: {
    reincarnation: {
      era: {
        en: ['You were an ancient Egyptian fisherman.', 'In your past life, you were an ancient Chinese fisherman.', 'You were a Roman fisherman.', 'In your past life, you were a Greek fisherman.', 'You were a Japanese fisherman.', 'In your past life, you were an Indian fisherman.', 'You were a Celtic fisherman.', 'In your past life, you were a Persian fisherman.', 'You were a Mayan fisherman.', 'In your past life, you were a Korean fisherman.'],
        ja: ['あなたは古代エジプトの漁師でした。', '前世であなたは古代中国の漁師でした。', 'あなたはローマの漁師でした。', '前世であなたはギリシャの漁師でした。', 'あなたは日本の漁師でした。', '前世であなたはインドの漁師でした。', 'あなたはケルトの漁師でした。', '前世であなたはペルシャの漁師でした。', 'あなたはマヤの漁師でした。', '前世であなたは韓国の漁師でした。'],
        'zh-CN': ['你是古埃及的渔夫。', '你的前世是古代中国的渔夫。', '你是罗马的渔夫。', '你的前世是希腊的渔夫。', '你是日本的渔夫。', '你的前世是印度的渔夫。', '你是凯尔特的渔夫。', '你的前世是波斯的渔夫。', '你是玛雅的渔夫。', '你的前世是韩国的渔夫。'],
        'zh-TW': ['你是古埃及的漁夫。', '你的前世是古代中國的漁夫。', '你是羅馬的漁夫。', '你的前世是希臘的漁夫。', '你是日本的漁夫。', '你的前世是印度的漁夫。', '你是凱爾特的漁夫。', '你的前世是波斯的漁夫。', '你是瑪雅的漁夫。', '你的前世是韓國的漁夫。'],
        vi: ['Bạn là một ngư dân Ai Cập cổ đại.', 'Ở kiếp trước, bạn là một ngư dân Trung Quốc cổ đại.', 'Bạn là một ngư dân La Mã.', 'Ở kiếp trước, bạn là một ngư dân Hy Lạp.', 'Bạn là một ngư dân Nhật Bản.', 'Ở kiếp trước, bạn là một ngư dân Ấn Độ.', 'Bạn là một ngư dân Celtic.', 'Ở kiếp trước, bạn là một ngư dân Ba Tư.', 'Bạn là một ngư dân Maya.', 'Ở kiếp trước, bạn là một ngư dân Hàn Quốc.'],
        id: ['Anda adalah nelayan Mesir kuno.', 'Di kehidupan lampau, Anda adalah nelayan Tiongkok kuno.', 'Anda adalah nelayan Romawi.', 'Di kehidupan lampau, Anda adalah nelayan Yunani.', 'Anda adalah nelayan Jepang.', 'Di kehidupan lampau, Anda adalah nelayan India.', 'Anda adalah nelayan Celtic.', 'Di kehidupan lampau, Anda adalah nelayan Persia.', 'Anda adalah nelayan Maya.', 'Di kehidupan lampau, Anda adalah nelayan Korea.']
      },
      occupation: {
        en: ['You were a deep sea fisherman in your past life.', 'In your past life, you were a river fisherman.', 'You were a lake fisherman in your past life.', 'In your past life, you were a coastal fisherman.', 'You were a commercial fisherman in your past life.', 'In your past life, you were a subsistence fisherman.', 'You were a ceremonial fisherman in your past life.', 'In your past life, you were a fish trader.', 'You were a net maker in your past life.', 'In your past life, you were a fishing teacher.'],
        ja: ['あなたは前世で深海漁師でした。', '前世であなたは川漁師でした。', 'あなたは前世で湖漁師でした。', '前世であなたは沿岸漁師でした。', 'あなたは前世で商業漁師でした。', '前世であなたは自給漁師でした。', 'あなたは前世で儀式用漁師でした。', '前世であなたは魚商人でした。', 'あなたは前世で網職人でした。', '前世であなたは漁業教師でした。'],
        'zh-CN': ['你的前世是深海渔夫。', '你的前世是河渔夫。', '你的前世是湖渔夫。', '你的前世是沿海渔夫。', '你的前世是商业渔夫。', '你的前世是自给渔夫。', '你的前世是仪式渔夫。', '你的前世是鱼商。', '你的前世是制网师。', '你的前世是渔业教师。'],
        'zh-TW': ['你的前世是深海漁夫。', '你的前世是河漁夫。', '你的前世是湖漁夫。', '你的前世是沿海漁夫。', '你的前世是商業漁夫。', '你的前世是自給漁夫。', '你的前世是儀式漁夫。', '你的前世是魚商。', '你的前世是製網師。', '你的前世是漁業教師。'],
        vi: ['Bạn từng là ngư dân biển sâu ở kiếp trước.', 'Ở kiếp trước, bạn là ngư dân sông.', 'Bạn từng là ngư dân hồ ở kiếp trước.', 'Ở kiếp trước, bạn là ngư dân ven biển.', 'Bạn từng là ngư dân thương mại ở kiếp trước.', 'Ở kiếp trước, bạn là ngư dân tự cung tự cấp.', 'Bạn từng là ngư dân nghi lễ ở kiếp trước.', 'Ở kiếp trước, bạn là thương nhân cá.', 'Bạn từng là thợ làm lưới ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên đánh cá.'],
        id: ['Di kehidupan lampau, Anda adalah nelayan laut dalam.', 'Di kehidupan lampau, Anda adalah nelayan sungai.', 'Di kehidupan lampau, Anda adalah nelayan danau.', 'Di kehidupan lampau, Anda adalah nelayan pantai.', 'Di kehidupan lampau, Anda adalah nelayan komersial.', 'Di kehidupan lampau, Anda adalah nelayan subsisten.', 'Di kehidupan lampau, Anda adalah nelayan upacara.', 'Di kehidupan lampau, Anda adalah pedagang ikan.', 'Di kehidupan lampau, Anda adalah pembuat jaring.', 'Di kehidupan lampau, Anda adalah guru memancing.']
      },
      reason: {
        en: ['You came to use past fishing skills in patience and persistence.', 'You returned to apply water wisdom to emotional flow.', 'You came to use fishing patience for long-term goals.', 'You returned to use water knowledge for adaptability.', 'You came to use fishing precision for detailed work.', 'You returned to use water instincts for intuition.', 'You came to use fishing responsibility for provision.', 'You returned to use water teaching for guidance.', 'You came to use fishing mastery for foundation building.', 'You returned to use water knowledge for innovation.'],
        ja: ['前世の漁業技術を今生の忍耐と持続性に活かすために来ました。', '前世の水の知恵を今生の感情の流れに用いるために来ました。', '前世の漁業忍耐を今生の長期目標に活かすために来ました。', '前世の水の知識を今生の適応性に用いるために来ました。', '前世の漁業精密さを今生の詳細作業に活かすために来ました。', '前世の水の本能を今生の直感に用いるために来ました。', '前世の漁業責任を今生の供給に活かすために来ました。', '前世の水の教育を今生の指導に用いるために来ました。', '前世の漁業習得を今生の基盤構築に活かすために来ました。', '前世の水の知識を今生の革新に用いるために来ました。'],
        'zh-CN': ['你为了将前世的捕鱼技能用于今生的耐心和坚持而来。', '你为了将前世的水智慧用于今生的情感流动而来。', '你为了将前世的捕鱼耐心用于今生的长期目标而来。', '你为了将前世的水知识用于今生的适应性而来。', '你为了将前世的捕鱼精度用于今生的细致工作而来。', '你为了将前世的水本能用于今生的直觉而来。', '你为了将前世的捕鱼责任用于今生的供给而来。', '你为了将前世的水教学用于今生的指导而来。', '你为了将前世的捕鱼掌握用于今生的基础建设而来。', '你为了将前世的水知识用于今生的创新而来。'],
        'zh-TW': ['你為了將前世的捕魚技能用於今生的耐心和堅持而來。', '你為了將前世的水智慧用於今生的情感流動而來。', '你為了將前世的捕魚耐心用於今生的長期目標而來。', '你為了將前世的水知識用於今生的適應性而來。', '你為了將前世的捕魚精度用於今生的細緻工作而來。', '你為了將前世的水本能用於今生的直覺而來。', '你為了將前世的捕魚責任用於今生的供給而來。', '你為了將前世的水教學用於今生的指導而來。', '你為了將前世的捕魚掌握用於今生的基礎建設而來。', '你為了將前世的水知識用於今生的創新而來。'],
        vi: ['Bạn đến để sử dụng kỹ năng đánh cá từ kiếp trước trong sự kiên nhẫn và bền bỉ.', 'Bạn trở lại để áp dụng trí tuệ nước vào dòng chảy cảm xúc.', 'Bạn đến để sử dụng sự kiên nhẫn đánh cá cho mục tiêu dài hạn.', 'Bạn trở lại để sử dụng kiến thức nước cho khả năng thích ứng.', 'Bạn đến để sử dụng độ chính xác đánh cá cho công việc chi tiết.', 'Bạn trở lại để sử dụng bản năng nước cho trực giác.', 'Bạn đến để sử dụng trách nhiệm đánh cá cho cung cấp.', 'Bạn trở lại để sử dụng giảng dạy nước cho hướng dẫn.', 'Bạn đến để sử dụng sự thành thạo đánh cá cho xây dựng nền tảng.', 'Bạn trở lại để sử dụng kiến thức nước cho đổi mới.'],
        id: ['Anda datang untuk menggunakan keterampilan memancing masa lalu dalam kesabaran dan ketekunan.', 'Anda kembali untuk menerapkan kebijaksanaan air pada aliran emosional.', 'Anda datang untuk menggunakan kesabaran memancing untuk tujuan jangka panjang.', 'Anda kembali untuk menggunakan pengetahuan air untuk adaptabilitas.', 'Anda datang untuk menggunakan presisi memancing untuk pekerjaan detail.', 'Anda kembali untuk menggunakan insting air untuk intuisi.', 'Anda datang untuk menggunakan tanggung jawab memancing untuk penyediaan.', 'Anda kembali untuk menggunakan pengajaran air untuk bimbingan.', 'Anda datang untuk menggunakan penguasaan memancing untuk membangun fondasi.', 'Anda kembali untuk menggunakan pengetahuan air untuk inovasi.']
      },
      lifeCount: {
        en: ['This is your 11th reincarnation.', 'You have lived a total of 18 lives so far.', 'This life is your 9th experience.', 'You have reincarnated 15 times up to this life.', 'This life follows your 10th past life.', 'You have lived 21 lives so far.', 'This is your 12th life.', 'You have reincarnated 17 times up to this life.', 'This life is a new beginning after your 13th past life.', 'You have built fishing experience through 24 lives.'],
        ja: ['これはあなたの11回目の転生です。', 'これまでに合計18回の人生を生きました。', '今生は9回目の経験です。', '今生までに15回転生しました。', '今生は10番目の前世の後に続きます。', 'これまでに21回の人生を生きました。', '今生は12回目の人生です。', '今生までに17回転生しました。', '今生は13番目の前世を経た新たな始まりです。', 'これまでに24回の人生で漁業の経験を積みました。'],
        'zh-CN': ['这是你的第11次转生。', '截至目前你总共经历了18次人生。', '今生是你的第9次体验。', '到今生为止你已经转生了15次。', '今生延续自你的第10次前世。', '截至目前你已经经历了21次人生。', '今生是你的第12次人生。', '到今生为止你已经转生了17次。', '今生是你第13次前世后的新开始。', '通过24次人生你积累了捕鱼经验。'],
        'zh-TW': ['這是你的第11次轉生。', '截至目前你總共經歷了18次人生。', '今生是你的第9次體驗。', '到今生為止你已經轉生了15次。', '今生延續自你的第10次前世。', '截至目前你已經經歷了21次人生。', '今生是你的第12次人生。', '到今生為止你已經轉生了17次。', '今生是你第13次前世後的新開始。', '通過24次人生你積累了捕魚經驗。'],
        vi: ['Đây là lần tái sinh thứ 11 của bạn.', 'Bạn đã sống tổng cộng 18 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 9 của bạn.', 'Bạn đã tái sinh 15 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 10 của bạn.', 'Bạn đã sống 21 kiếp cho đến nay.', 'Đây là kiếp thứ 12 của bạn.', 'Bạn đã tái sinh 17 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 13 của bạn.', 'Bạn đã tích lũy kinh nghiệm đánh cá qua 24 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-11 Anda.', 'Anda telah menjalani total 18 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-9 Anda.', 'Anda telah bereinkarnasi 15 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-10 Anda.', 'Anda telah menjalani 21 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-12 Anda.', 'Anda telah bereinkarnasi 17 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-13 Anda.', 'Anda telah membangun pengalaman memancing melalui 24 kehidupan.']
      }
    }
  }
};