import { FaceReincarnationTranslations } from '../merge';

export const batch34: FaceReincarnationTranslations = {
  48: {
    reincarnation: {
      era: {
        en: ['You were an ancient Egyptian calligrapher.', 'In your past life, you were an ancient Chinese calligrapher.', 'You were a Roman calligrapher.', 'In your past life, you were a Greek calligrapher.', 'You were a Japanese calligrapher.', 'In your past life, you were an Indian calligrapher.', 'You were a Celtic calligrapher.', 'In your past life, you were a Persian calligrapher.', 'You were a Mayan calligrapher.', 'In your past life, you were a Korean calligrapher.'],
        ja: ['あなたは古代エジプトの書道家でした。', '前世であなたは古代中国の書道家でした。', 'あなたはローマの書道家でした。', '前世であなたはギリシャの書道家でした。', 'あなたは日本の書道家でした。', '前世であなたはインドの書道家でした。', 'あなたはケルトの書道家でした。', '前世であなたはペルシャの書道家でした。', 'あなたはマヤの書道家でした。', '前世であなたは韓国の書道家でした。'],
        'zh-CN': ['你是古埃及的书法家。', '你的前世是古代中国的书法家。', '你是罗马的书法家。', '你的前世是希腊的书法家。', '你是日本的书法家。', '你的前世是印度的书法家。', '你是凯尔特的书法家。', '你的前世是波斯的书法家。', '你是玛雅的书法家。', '你的前世是韩国的书法家。'],
        'zh-TW': ['你是古埃及的書法家。', '你的前世是古代中國的書法家。', '你是羅馬的書法家。', '你的前世是希臘的書法家。', '你是日本的書法家。', '你的前世是印度的書法家。', '你是凱爾特的書法家。', '你的前世是波斯的書法家。', '你是瑪雅的書法家。', '你的前世是韓國的書法家。'],
        vi: ['Bạn là một thư pháp gia Ai Cập cổ đại.', 'Ở kiếp trước, bạn là một thư pháp gia Trung Quốc cổ đại.', 'Bạn là một thư pháp gia La Mã.', 'Ở kiếp trước, bạn là một thư pháp gia Hy Lạp.', 'Bạn là một thư pháp gia Nhật Bản.', 'Ở kiếp trước, bạn là một thư pháp gia Ấn Độ.', 'Bạn là một thư pháp gia Celtic.', 'Ở kiếp trước, bạn là một thư pháp gia Ba Tư.', 'Bạn là một thư pháp gia Maya.', 'Ở kiếp trước, bạn là một thư pháp gia Hàn Quốc.'],
        id: ['Anda adalah kaligrafer Mesir kuno.', 'Di kehidupan lampau, Anda adalah kaligrafer Tiongkok kuno.', 'Anda adalah kaligrafer Romawi.', 'Di kehidupan lampau, Anda adalah kaligrafer Yunani.', 'Anda adalah kaligrafer Jepang.', 'Di kehidupan lampau, Anda adalah kaligrafer India.', 'Anda adalah kaligrafer Celtic.', 'Di kehidupan lampau, Anda adalah kaligrafer Persia.', 'Anda adalah kaligrafer Maya.', 'Di kehidupan lampau, Anda adalah kaligrafer Korea.']
      },
      occupation: {
        en: ['You were a royal calligrapher in your past life.', 'In your past life, you were a temple calligrapher.', 'You were a court calligrapher in your past life.', 'In your past life, you were a scribe calligrapher.', 'You were a ceremonial calligrapher in your past life.', 'In your past life, you were a religious calligrapher.', 'You were a traveling calligrapher in your past life.', 'In your past life, you were a village calligrapher.', 'You were a merchant calligrapher in your past life.', 'In your past life, you were a calligraphy teacher.'],
        ja: ['あなたは前世で王室書道家でした。', '前世であなたは寺院書道家でした。', 'あなたは前世で宮廷書道家でした。', '前世であなたは書記書道家でした。', 'あなたは前世で儀式書道家でした。', '前世であなたは宗教書道家でした。', 'あなたは前世で旅書道家でした。', '前世であなたは村書道家でした。', 'あなたは前世で商人書道家でした。', '前世であなたは書道教師でした。'],
        'zh-CN': ['你的前世是王室书法家。', '你的前世是寺庙书法家。', '你的前世是宫廷书法家。', '你的前世是抄写员书法家。', '你的前世是仪式书法家。', '你的前世是宗教书法家。', '你的前世是游方书法家。', '你的前世是乡村书法家。', '你的前世是商人书法家。', '你的前世是书法教师。'],
        'zh-TW': ['你的前世是王室書法家。', '你的前世是寺廟書法家。', '你的前世是宮廷書法家。', '你的前世是抄寫員書法家。', '你的前世是儀式書法家。', '你的前世是宗教書法家。', '你的前世是遊方書法家。', '你的前世是鄉村書法家。', '你的前世是商人書法家。', '你的前世是書法教師。'],
        vi: ['Bạn từng là thư pháp gia hoàng gia ở kiếp trước.', 'Ở kiếp trước, bạn là thư pháp gia đền thờ.', 'Bạn từng là thư pháp gia triều đình ở kiếp trước.', 'Ở kiếp trước, bạn là thư pháp gia thư ký.', 'Bạn từng là thư pháp gia nghi lễ ở kiếp trước.', 'Ở kiếp trước, bạn là thư pháp gia tôn giáo.', 'Bạn từng là thư pháp gia du hành ở kiếp trước.', 'Ở kiếp trước, bạn là thư pháp gia làng.', 'Bạn từng là thư pháp gia thương nhân ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên thư pháp.'],
        id: ['Di kehidupan lampau, Anda adalah kaligrafer kerajaan.', 'Di kehidupan lampau, Anda adalah kaligrafer kuil.', 'Di kehidupan lampau, Anda adalah kaligrafer istana.', 'Di kehidupan lampau, Anda adalah kaligrafer juru tulis.', 'Di kehidupan lampau, Anda adalah kaligrafer upacara.', 'Di kehidupan lampau, Anda adalah kaligrafer agama.', 'Di kehidupan lampau, Anda adalah kaligrafer keliling.', 'Di kehidupan lampau, Anda adalah kaligrafer desa.', 'Di kehidupan lampau, Anda adalah kaligrafer pedagang.', 'Di kehidupan lampau, Anda adalah guru kaligrafi.']
      },
      reason: {
        en: ['You came to use past calligraphy skills in precision and beauty.', 'You returned to apply writing wisdom to communication.', 'You came to use calligraphy patience for detailed work.', 'You returned to use writing knowledge for expression.', 'You came to use calligraphy precision for accuracy.', 'You returned to use writing instincts for intuition.', 'You came to use calligraphy responsibility for cultural preservation.', 'You returned to use writing teaching for guidance.', 'You came to use calligraphy mastery for foundation building.', 'You returned to use writing knowledge for innovation.'],
        ja: ['前世の書道技術を今生の精密さと美しさに活かすために来ました。', '前世の書字知恵を今生のコミュニケーションに用いるために来ました。', '前世の書道忍耐を今生の詳細作業に活かすために来ました。', '前世の書字知識を今生の表現に用いるために来ました。', '前世の書道精密さを今生の正確性に活かすために来ました。', '前世の書字本能を今生の直感に用いるために来ました。', '前世の書道責任を今生の文化保存に活かすために来ました。', '前世の書字教育を今生の指導に用いるために来ました。', '前世の書道習得を今生の基盤構築に活かすために来ました。', '前世の書字知識を今生の革新に用いるために来ました。'],
        'zh-CN': ['你为了将前世的书法技能用于今生的精确和美丽而来。', '你为了将前世的书写智慧用于今生的沟通而来。', '你为了将前世的书法耐心用于今生的细致工作而来。', '你为了将前世的书写知识用于今生的表达而来。', '你为了将前世的书法精度用于今生的准确性而来。', '你为了将前世的书写本能用于今生的直觉而来。', '你为了将前世的书法责任用于今生的文化保护而来。', '你为了将前世的书写教学用于今生的指导而来。', '你为了将前世的书法掌握用于今生的基础建设而来。', '你为了将前世的书写知识用于今生的创新而来。'],
        'zh-TW': ['你為了將前世的書法技能用於今生的精確和美麗而來。', '你為了將前世的書寫智慧用於今生的溝通而來。', '你為了將前世的書法耐心用於今生的細緻工作而來。', '你為了將前世的書寫知識用於今生的表達而來。', '你為了將前世的書法精度用於今生的準確性而來。', '你為了將前世的書寫本能用於今生的直覺而來。', '你為了將前世的書法責任用於今生的文化保護而來。', '你為了將前世的書寫教學用於今生的指導而來。', '你為了將前世的書法掌握用於今生的基礎建設而來。', '你為了將前世的書寫知識用於今生的創新而來。'],
        vi: ['Bạn đến để sử dụng kỹ năng thư pháp từ kiếp trước trong sự chính xác và vẻ đẹp.', 'Bạn trở lại để áp dụng trí tuệ viết vào giao tiếp.', 'Bạn đến để sử dụng sự kiên nhẫn thư pháp cho công việc chi tiết.', 'Bạn trở lại để sử dụng kiến thức viết cho biểu đạt.', 'Bạn đến để sử dụng độ chính xác thư pháp cho sự chính xác.', 'Bạn trở lại để sử dụng bản năng viết cho trực giác.', 'Bạn đến để sử dụng trách nhiệm thư pháp cho bảo tồn văn hóa.', 'Bạn trở lại để sử dụng giảng dạy viết cho hướng dẫn.', 'Bạn đến để sử dụng sự thành thạo thư pháp cho xây dựng nền tảng.', 'Bạn trở lại để sử dụng kiến thức viết cho đổi mới.'],
        id: ['Anda datang untuk menggunakan keterampilan kaligrafi masa lalu dalam presisi dan keindahan.', 'Anda kembali untuk menerapkan kebijaksanaan menulis pada komunikasi.', 'Anda datang untuk menggunakan kesabaran kaligrafi untuk pekerjaan detail.', 'Anda kembali untuk menggunakan pengetahuan menulis untuk ekspresi.', 'Anda datang untuk menggunakan presisi kaligrafi untuk akurasi.', 'Anda kembali untuk menggunakan insting menulis untuk intuisi.', 'Anda datang untuk menggunakan tanggung jawab kaligrafi untuk pelestarian budaya.', 'Anda kembali untuk menggunakan pengajaran menulis untuk bimbingan.', 'Anda datang untuk menggunakan penguasaan kaligrafi untuk membangun fondasi.', 'Anda kembali untuk menggunakan pengetahuan menulis untuk inovasi.']
      },
      lifeCount: {
        en: ['This is your 32nd reincarnation.', 'You have lived a total of 39 lives so far.', 'This life is your 30th experience.', 'You have reincarnated 36 times up to this life.', 'This life follows your 31st past life.', 'You have lived 42 lives so far.', 'This is your 33rd life.', 'You have reincarnated 38 times up to this life.', 'This life is a new beginning after your 34th past life.', 'You have built calligraphy experience through 45 lives.'],
        ja: ['これはあなたの32回目の転生です。', 'これまでに合計39回の人生を生きました。', '今生は30回目の経験です。', '今生までに36回転生しました。', '今生は31番目の前世の後に続きます。', 'これまでに42回の人生を生きました。', '今生は33回目の人生です。', '今生までに38回転生しました。', '今生は34番目の前世を経た新たな始まりです。', 'これまでに45回の人生で書道の経験を積みました。'],
        'zh-CN': ['这是你的第32次转生。', '截至目前你总共经历了39次人生。', '今生是你的第30次体验。', '到今生为止你已经转生了36次。', '今生延续自你的第31次前世。', '截至目前你已经经历了42次人生。', '今生是你的第33次人生。', '到今生为止你已经转生了38次。', '今生是你第34次前世后的新开始。', '通过45次人生你积累了书法经验。'],
        'zh-TW': ['這是你的第32次轉生。', '截至目前你總共經歷了39次人生。', '今生是你的第30次體驗。', '到今生為止你已經轉生了36次。', '今生延續自你的第31次前世。', '截至目前你已經經歷了42次人生。', '今生是你的第33次人生。', '到今生為止你已經轉生了38次。', '今生是你第34次前世後的新開始。', '通過45次人生你積累了書法經驗。'],
        vi: ['Đây là lần tái sinh thứ 32 của bạn.', 'Bạn đã sống tổng cộng 39 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 30 của bạn.', 'Bạn đã tái sinh 36 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 31 của bạn.', 'Bạn đã sống 42 kiếp cho đến nay.', 'Đây là kiếp thứ 33 của bạn.', 'Bạn đã tái sinh 38 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 34 của bạn.', 'Bạn đã tích lũy kinh nghiệm thư pháp qua 45 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-32 Anda.', 'Anda telah menjalani total 39 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-30 Anda.', 'Anda telah bereinkarnasi 36 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-31 Anda.', 'Anda telah menjalani 42 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-33 Anda.', 'Anda telah bereinkarnasi 38 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-34 Anda.', 'Anda telah membangun pengalaman kaligrafi melalui 45 kehidupan.']
      }
    }
  },
  49: {
    reincarnation: {
      era: {
        en: ['You were an ancient Egyptian poet.', 'In your past life, you were an ancient Chinese poet.', 'You were a Roman poet.', 'In your past life, you were a Greek poet.', 'You were a Japanese poet.', 'In your past life, you were an Indian poet.', 'You were a Celtic poet.', 'In your past life, you were a Persian poet.', 'You were a Mayan poet.', 'In your past life, you were a Korean poet.'],
        ja: ['あなたは古代エジプトの詩人でした。', '前世であなたは古代中国の詩人でした。', 'あなたはローマの詩人でした。', '前世であなたはギリシャの詩人でした。', 'あなたは日本の詩人でした。', '前世であなたはインドの詩人でした。', 'あなたはケルトの詩人でした。', '前世であなたはペルシャの詩人でした。', 'あなたはマヤの詩人でした。', '前世であなたは韓国の詩人でした。'],
        'zh-CN': ['你是古埃及的诗人。', '你的前世是古代中国的诗人。', '你是罗马的诗人。', '你的前世是希腊的诗人。', '你是日本的诗人。', '你的前世是印度的诗人。', '你是凯尔特的诗人。', '你的前世是波斯的诗人。', '你是玛雅的诗人。', '你的前世是韩国的诗人。'],
        'zh-TW': ['你是古埃及的詩人。', '你的前世是古代中國的詩人。', '你是羅馬的詩人。', '你的前世是希臘的詩人。', '你是日本的詩人。', '你的前世是印度的詩人。', '你是凱爾特的詩人。', '你的前世是波斯的詩人。', '你是瑪雅的詩人。', '你的前世是韓國的詩人。'],
        vi: ['Bạn là một nhà thơ Ai Cập cổ đại.', 'Ở kiếp trước, bạn là một nhà thơ Trung Quốc cổ đại.', 'Bạn là một nhà thơ La Mã.', 'Ở kiếp trước, bạn là một nhà thơ Hy Lạp.', 'Bạn là một nhà thơ Nhật Bản.', 'Ở kiếp trước, bạn là một nhà thơ Ấn Độ.', 'Bạn là một nhà thơ Celtic.', 'Ở kiếp trước, bạn là một nhà thơ Ba Tư.', 'Bạn là một nhà thơ Maya.', 'Ở kiếp trước, bạn là một nhà thơ Hàn Quốc.'],
        id: ['Anda adalah penyair Mesir kuno.', 'Di kehidupan lampau, Anda adalah penyair Tiongkok kuno.', 'Anda adalah penyair Romawi.', 'Di kehidupan lampau, Anda adalah penyair Yunani.', 'Anda adalah penyair Jepang.', 'Di kehidupan lampau, Anda adalah penyair India.', 'Anda adalah penyair Celtic.', 'Di kehidupan lampau, Anda adalah penyair Persia.', 'Anda adalah penyair Maya.', 'Di kehidupan lampau, Anda adalah penyair Korea.']
      },
      occupation: {
        en: ['You were a royal poet in your past life.', 'In your past life, you were a temple poet.', 'You were a court poet in your past life.', 'In your past life, you were a street poet.', 'You were a ceremonial poet in your past life.', 'In your past life, you were a religious poet.', 'You were a traveling poet in your past life.', 'In your past life, you were a village poet.', 'You were a merchant poet in your past life.', 'In your past life, you were a poetry teacher.'],
        ja: ['あなたは前世で王室詩人でした。', '前世であなたは寺院詩人でした。', 'あなたは前世で宮廷詩人でした。', '前世であなたはストリート詩人でした。', 'あなたは前世で儀式詩人でした。', '前世であなたは宗教詩人でした。', 'あなたは前世で旅詩人でした。', '前世であなたは村詩人でした。', 'あなたは前世で商人詩人でした。', '前世であなたは詩歌教師でした。'],
        'zh-CN': ['你的前世是王室诗人。', '你的前世是寺庙诗人。', '你的前世是宫廷诗人。', '你的前世是街头诗人。', '你的前世是仪式诗人。', '你的前世是宗教诗人。', '你的前世是游方诗人。', '你的前世是乡村诗人。', '你的前世是商人诗人。', '你的前世是诗歌教师。'],
        'zh-TW': ['你的前世是王室詩人。', '你的前世是寺廟詩人。', '你的前世是宮廷詩人。', '你的前世是街頭詩人。', '你的前世是儀式詩人。', '你的前世是宗教詩人。', '你的前世是遊方詩人。', '你的前世是鄉村詩人。', '你的前世是商人詩人。', '你的前世是詩歌教師。'],
        vi: ['Bạn từng là nhà thơ hoàng gia ở kiếp trước.', 'Ở kiếp trước, bạn là nhà thơ đền thờ.', 'Bạn từng là nhà thơ triều đình ở kiếp trước.', 'Ở kiếp trước, bạn là nhà thơ đường phố.', 'Bạn từng là nhà thơ nghi lễ ở kiếp trước.', 'Ở kiếp trước, bạn là nhà thơ tôn giáo.', 'Bạn từng là nhà thơ du hành ở kiếp trước.', 'Ở kiếp trước, bạn là nhà thơ làng.', 'Bạn từng là nhà thơ thương nhân ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên thơ ca.'],
        id: ['Di kehidupan lampau, Anda adalah penyair kerajaan.', 'Di kehidupan lampau, Anda adalah penyair kuil.', 'Di kehidupan lampau, Anda adalah penyair istana.', 'Di kehidupan lampau, Anda adalah penyair jalanan.', 'Di kehidupan lampau, Anda adalah penyair upacara.', 'Di kehidupan lampau, Anda adalah penyair agama.', 'Di kehidupan lampau, Anda adalah penyair keliling.', 'Di kehidupan lampau, Anda adalah penyair desa.', 'Di kehidupan lampau, Anda adalah penyair pedagang.', 'Di kehidupan lampau, Anda adalah guru puisi.']
      },
      reason: {
        en: ['You came to use past poetry skills in expression and creativity.', 'You returned to apply poetic wisdom to emotional healing.', 'You came to use poetry patience for detailed composition.', 'You returned to use poetic knowledge for inspiration.', 'You came to use poetry precision for beauty.', 'You returned to use poetic instincts for intuition.', 'You came to use poetry responsibility for cultural preservation.', 'You returned to use poetic teaching for guidance.', 'You came to use poetry mastery for foundation building.', 'You returned to use poetic knowledge for innovation.'],
        ja: ['前世の詩歌技術を今生の表現と創造性に活かすために来ました。', '前世の詩的知恵を今生の感情的癒しに用いるために来ました。', '前世の詩歌忍耐を今生の詳細創作に活かすために来ました。', '前世の詩的知識を今生のインスピレーションに用いるために来ました。', '前世の詩歌精密さを今生の美しさに活かすために来ました。', '前世の詩的本能を今生の直感に用いるために来ました。', '前世の詩歌責任を今生の文化保存に活かすために来ました。', '前世の詩的教育を今生の指導に用いるために来ました。', '前世の詩歌習得を今生の基盤構築に活かすために来ました。', '前世の詩的知識を今生の革新に用いるために来ました。'],
        'zh-CN': ['你为了将前世的诗歌技能用于今生的表达和创造性而来。', '你为了将前世的诗意智慧用于今生的情感治愈而来。', '你为了将前世的诗歌耐心用于今生的详细创作而来。', '你为了将前世的诗意知识用于今生的灵感而来。', '你为了将前世的诗歌精度用于今生的美丽而来。', '你为了将前世的诗意本能用于今生的直觉而来。', '你为了将前世的诗歌责任用于今生的文化保护而来。', '你为了将前世的诗意教学用于今生的指导而来。', '你为了将前世的诗歌掌握用于今生的基础建设而来。', '你为了将前世的诗意知识用于今生的创新而来。'],
        'zh-TW': ['你為了將前世的詩歌技能用於今生的表達和創造性而來。', '你為了將前世的詩意智慧用於今生的情感治愈而來。', '你為了將前世的詩歌耐心用於今生的詳細創作而來。', '你為了將前世的詩意知識用於今生的靈感而來。', '你為了將前世的詩歌精度用於今生的美麗而來。', '你為了將前世的詩意本能用於今生的直覺而來。', '你為了將前世的詩歌責任用於今生的文化保護而來。', '你為了將前世的詩意教學用於今生的指導而來。', '你為了將前世的詩歌掌握用於今生的基礎建設而來。', '你為了將前世的詩意知識用於今生的創新而來。'],
        vi: ['Bạn đến để sử dụng kỹ năng thơ ca từ kiếp trước trong biểu đạt và sáng tạo.', 'Bạn trở lại để áp dụng trí tuệ thơ ca vào chữa lành cảm xúc.', 'Bạn đến để sử dụng sự kiên nhẫn thơ ca cho sáng tác chi tiết.', 'Bạn trở lại để sử dụng kiến thức thơ ca cho cảm hứng.', 'Bạn đến để sử dụng độ chính xác thơ ca cho vẻ đẹp.', 'Bạn trở lại để sử dụng bản năng thơ ca cho trực giác.', 'Bạn đến để sử dụng trách nhiệm thơ ca cho bảo tồn văn hóa.', 'Bạn trở lại để sử dụng giảng dạy thơ ca cho hướng dẫn.', 'Bạn đến để sử dụng sự thành thạo thơ ca cho xây dựng nền tảng.', 'Bạn trở lại để sử dụng kiến thức thơ ca cho đổi mới.'],
        id: ['Anda datang untuk menggunakan keterampilan puisi masa lalu dalam ekspresi dan kreativitas.', 'Anda kembali untuk menerapkan kebijaksanaan puitis pada penyembuhan emosional.', 'Anda datang untuk menggunakan kesabaran puisi untuk komposisi detail.', 'Anda kembali untuk menggunakan pengetahuan puitis untuk inspirasi.', 'Anda datang untuk menggunakan presisi puisi untuk keindahan.', 'Anda kembali untuk menggunakan insting puitis untuk intuisi.', 'Anda datang untuk menggunakan tanggung jawab puisi untuk pelestarian budaya.', 'Anda kembali untuk menggunakan pengajaran puitis untuk bimbingan.', 'Anda datang untuk menggunakan penguasaan puisi untuk membangun fondasi.', 'Anda kembali untuk menggunakan pengetahuan puitis untuk inovasi.']
      },
      lifeCount: {
        en: ['This is your 33rd reincarnation.', 'You have lived a total of 40 lives so far.', 'This life is your 31st experience.', 'You have reincarnated 37 times up to this life.', 'This life follows your 32nd past life.', 'You have lived 43 lives so far.', 'This is your 34th life.', 'You have reincarnated 39 times up to this life.', 'This life is a new beginning after your 35th past life.', 'You have built poetry experience through 46 lives.'],
        ja: ['これはあなたの33回目の転生です。', 'これまでに合計40回の人生を生きました。', '今生は31回目の経験です。', '今生までに37回転生しました。', '今生は32番目の前世の後に続きます。', 'これまでに43回の人生を生きました。', '今生は34回目の人生です。', '今生までに39回転生しました。', '今生は35番目の前世を経た新たな始まりです。', 'これまでに46回の人生で詩歌の経験を積みました。'],
        'zh-CN': ['这是你的第33次转生。', '截至目前你总共经历了40次人生。', '今生是你的第31次体验。', '到今生为止你已经转生了37次。', '今生延续自你的第32次前世。', '截至目前你已经经历了43次人生。', '今生是你的第34次人生。', '到今生为止你已经转生了39次。', '今生是你第35次前世后的新开始。', '通过46次人生你积累了诗歌经验。'],
        'zh-TW': ['這是你的第33次轉生。', '截至目前你總共經歷了40次人生。', '今生是你的第31次體驗。', '到今生為止你已經轉生了37次。', '今生延續自你的第32次前世。', '截至目前你已經經歷了43次人生。', '今生是你的第34次人生。', '到今生為止你已經轉生了39次。', '今生是你第35次前世後的新開始。', '通過46次人生你積累了詩歌經驗。'],
        vi: ['Đây là lần tái sinh thứ 33 của bạn.', 'Bạn đã sống tổng cộng 40 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 31 của bạn.', 'Bạn đã tái sinh 37 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 32 của bạn.', 'Bạn đã sống 43 kiếp cho đến nay.', 'Đây là kiếp thứ 34 của bạn.', 'Bạn đã tái sinh 39 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 35 của bạn.', 'Bạn đã tích lũy kinh nghiệm thơ ca qua 46 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-33 Anda.', 'Anda telah menjalani total 40 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-31 Anda.', 'Anda telah bereinkarnasi 37 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-32 Anda.', 'Anda telah menjalani 43 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-34 Anda.', 'Anda telah bereinkarnasi 39 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-35 Anda.', 'Anda telah membangun pengalaman puisi melalui 46 kehidupan.']
      }
    }
  }
};