import { FaceReincarnationTranslations } from '../merge';

export const batch21: FaceReincarnationTranslations = {
  21: {
    reincarnation: {
      era: {
        en: ['You were an ancient Chinese potter.', 'In your past life, you were an ancient Greek potter.', 'You were a Roman potter.', 'In your past life, you were an Egyptian potter.', 'You were a Japanese potter.', 'In your past life, you were an Indian potter.', 'You were a Mayan potter.', 'In your past life, you were a Persian potter.', 'You were a Celtic potter.', 'In your past life, you were a Korean potter.'],
        ja: ['あなたは古代中国の陶工でした。', '前世であなたは古代ギリシャの陶工でした。', 'あなたはローマの陶工でした。', '前世であなたはエジプトの陶工でした。', 'あなたは日本の陶工でした。', '前世であなたはインドの陶工でした。', 'あなたはマヤの陶工でした。', '前世であなたはペルシャの陶工でした。', 'あなたはケルトの陶工でした。', '前世であなたは韓国の陶工でした。'],
        'zh-CN': ['你是古代中国的陶工。', '你的前世是古希腊的陶工。', '你是罗马的陶工。', '你的前世是埃及的陶工。', '你是日本的陶工。', '你的前世是印度的陶工。', '你是玛雅的陶工。', '你的前世是波斯的陶工。', '你是凯尔特的陶工。', '你的前世是韩国的陶工。'],
        'zh-TW': ['你是古代中國的陶工。', '你的前世是古希臘的陶工。', '你是羅馬的陶工。', '你的前世是埃及的陶工。', '你是日本的陶工。', '你的前世是印度的陶工。', '你是瑪雅的陶工。', '你的前世是波斯的陶工。', '你是凱爾特的陶工。', '你的前世是韓國的陶工。'],
        vi: ['Bạn là một thợ gốm Trung Quốc cổ đại.', 'Ở kiếp trước, bạn là một thợ gốm Hy Lạp cổ đại.', 'Bạn là một thợ gốm La Mã.', 'Ở kiếp trước, bạn là một thợ gốm Ai Cập.', 'Bạn là một thợ gốm Nhật Bản.', 'Ở kiếp trước, bạn là một thợ gốm Ấn Độ.', 'Bạn là một thợ gốm Maya.', 'Ở kiếp trước, bạn là một thợ gốm Ba Tư.', 'Bạn là một thợ gốm Celtic.', 'Ở kiếp trước, bạn là một thợ gốm Hàn Quốc.'],
        id: ['Anda adalah pengrajin tembikar Tiongkok kuno.', 'Di kehidupan lampau, Anda adalah pengrajin tembikar Yunani kuno.', 'Anda adalah pengrajin tembikar Romawi.', 'Di kehidupan lampau, Anda adalah pengrajin tembikar Mesir.', 'Anda adalah pengrajin tembikar Jepang.', 'Di kehidupan lampau, Anda adalah pengrajin tembikar India.', 'Anda adalah pengrajin tembikar Maya.', 'Di kehidupan lampau, Anda adalah pengrajin tembikar Persia.', 'Anda adalah pengrajin tembikar Celtic.', 'Di kehidupan lampau, Anda adalah pengrajin tembikar Korea.']
      },
      occupation: {
        en: ['You were a ceremonial potter in your past life.', 'In your past life, you were a household potter.', 'You were a temple potter in your past life.', 'In your past life, you were a royal potter.', 'You were a decorative potter in your past life.', 'In your past life, you were a functional potter.', 'You were a artistic potter in your past life.', 'In your past life, you were a kiln master.', 'You were a clay preparer in your past life.', 'In your past life, you were a pottery teacher.'],
        ja: ['あなたは前世で儀式用陶工でした。', '前世であなたは家庭用陶工でした。', 'あなたは前世で神殿陶工でした。', '前世であなたは王室陶工でした。', 'あなたは前世で装飾陶工でした。', '前世であなたは実用陶工でした。', 'あなたは前世で芸術陶工でした。', '前世であなたは窯の師匠でした。', 'あなたは前世で粘土準備者でした。', '前世であなたは陶芸教師でした。'],
        'zh-CN': ['你的前世是仪式用陶工。', '你的前世是家用陶工。', '你的前世是神庙陶工。', '你的前世是王室陶工。', '你的前世是装饰陶工。', '你的前世是实用陶工。', '你的前世是艺术陶工。', '你的前世是窑炉大师。', '你的前世是粘土准备者。', '你的前世是陶艺教师。'],
        'zh-TW': ['你的前世是儀式用陶工。', '你的前世是家用陶工。', '你的前世是神廟陶工。', '你的前世是王室陶工。', '你的前世是裝飾陶工。', '你的前世是實用陶工。', '你的前世是藝術陶工。', '你的前世是窯爐大師。', '你的前世是粘土準備者。', '你的前世是陶藝教師。'],
        vi: ['Bạn từng là thợ gốm nghi lễ ở kiếp trước.', 'Ở kiếp trước, bạn là thợ gốm gia đình.', 'Bạn từng là thợ gốm đền thờ ở kiếp trước.', 'Ở kiếp trước, bạn là thợ gốm hoàng gia.', 'Bạn từng là thợ gốm trang trí ở kiếp trước.', 'Ở kiếp trước, bạn là thợ gốm thực dụng.', 'Bạn từng là thợ gốm nghệ thuật ở kiếp trước.', 'Ở kiếp trước, bạn là bậc thầy lò nung.', 'Bạn từng là người chuẩn bị đất sét ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên gốm sứ.'],
        id: ['Di kehidupan lampau, Anda adalah pengrajin tembikar upacara.', 'Di kehidupan lampau, Anda adalah pengrajin tembikar rumah tangga.', 'Di kehidupan lampau, Anda adalah pengrajin tembikar kuil.', 'Di kehidupan lampau, Anda adalah pengrajin tembikar kerajaan.', 'Di kehidupan lampau, Anda adalah pengrajin tembikar dekoratif.', 'Di kehidupan lampau, Anda adalah pengrajin tembikar fungsional.', 'Di kehidupan lampau, Anda adalah pengrajin tembikar artistik.', 'Di kehidupan lampau, Anda adalah master tungku.', 'Di kehidupan lampau, Anda adalah penyiap tanah liat.', 'Di kehidupan lampau, Anda adalah guru keramik.']
      },
      reason: {
        en: ['You came to use past pottery skills in creative expression.', 'You returned to apply clay work to artistic projects.', 'You came to use ceramic precision in detailed work.', 'You returned to use kiln knowledge for transformation.', 'You came to use pottery patience for persistence.', 'You returned to use clay wisdom for adaptability.', 'You came to use ceramic artistry for beauty.', 'You returned to use pottery teaching for guidance.', 'You came to use clay mastery for foundation building.', 'You returned to use ceramic knowledge for innovation.'],
        ja: ['前世の陶芸技術を今生の創造的表現に活かすために来ました。', '前世の粘土作業を今生の芸術プロジェクトに用いるために来ました。', '前世の陶器精密さを今生の詳細作業に活かすために来ました。', '前世の窯知識を今生の変容に用いるために来ました。', '前世の陶芸忍耐を今生の持続性に活かすために来ました。', '前世の粘土知恵を今生の適応性に用いるために来ました。', '前世の陶器芸術性を今生の美しさに活かすために来ました。', '前世の陶芸教育を今生の指導に用いるために来ました。', '前世の粘土習得を今生の基盤構築に活かすために来ました。', '前世の陶器知識を今生の革新に用いるために来ました。'],
        'zh-CN': ['你为了将前世的陶艺技能用于今生的创意表达而来。', '你为了将前世的粘土工作用于今生的艺术项目而来。', '你为了将前世的陶瓷精度用于今生的细致工作而来。', '你为了将前世的窑炉知识用于今生的转变而来。', '你为了将前世的陶艺耐心用于今生的坚持而来。', '你为了将前世的粘土智慧用于今生的适应性而来。', '你为了将前世的陶瓷艺术用于今生的美感而来。', '你为了将前世的陶艺教学用于今生的指导而来。', '你为了将前世的粘土掌握用于今生的基础建设而来。', '你为了将前世的陶瓷知识用于今生的创新而来。'],
        'zh-TW': ['你為了將前世的陶藝技能用於今生的創意表達而來。', '你為了將前世的粘土工作用於今生的藝術項目而來。', '你為了將前世的陶瓷精度用於今生的細緻工作而來。', '你為了將前世的窯爐知識用於今生的轉變而來。', '你為了將前世的陶藝耐心用於今生的堅持而來。', '你為了將前世的粘土智慧用於今生的適應性而來。', '你為了將前世的陶瓷藝術用於今生的美感而來。', '你為了將前世的陶藝教學用於今生的指導而來。', '你為了將前世的粘土掌握用於今生的基礎建設而來。', '你為了將前世的陶瓷知識用於今生的創新而來。'],
        vi: ['Bạn đến để sử dụng kỹ năng gốm sứ từ kiếp trước trong biểu đạt sáng tạo.', 'Bạn trở lại để áp dụng công việc đất sét vào dự án nghệ thuật.', 'Bạn đến để sử dụng độ chính xác gốm sứ trong công việc chi tiết.', 'Bạn trở lại để sử dụng kiến thức lò nung cho sự biến đổi.', 'Bạn đến để sử dụng sự kiên nhẫn gốm sứ cho sự bền bỉ.', 'Bạn trở lại để sử dụng trí tuệ đất sét cho khả năng thích ứng.', 'Bạn đến để sử dụng nghệ thuật gốm sứ cho vẻ đẹp.', 'Bạn trở lại để sử dụng giảng dạy gốm sứ cho hướng dẫn.', 'Bạn đến để sử dụng sự thành thạo đất sét cho xây dựng nền tảng.', 'Bạn trở lại để sử dụng kiến thức gốm sứ cho đổi mới.'],
        id: ['Anda datang untuk menggunakan keterampilan keramik masa lalu dalam ekspresi kreatif.', 'Anda kembali untuk menerapkan pekerjaan tanah liat pada proyek artistik.', 'Anda datang untuk menggunakan presisi keramik dalam pekerjaan detail.', 'Anda kembali untuk menggunakan pengetahuan tungku untuk transformasi.', 'Anda datang untuk menggunakan kesabaran keramik untuk ketekunan.', 'Anda kembali untuk menggunakan kebijaksanaan tanah liat untuk adaptabilitas.', 'Anda datang untuk menggunakan seni keramik untuk keindahan.', 'Anda kembali untuk menggunakan pengajaran keramik untuk bimbingan.', 'Anda datang untuk menggunakan penguasaan tanah liat untuk membangun fondasi.', 'Anda kembali untuk menggunakan pengetahuan keramik untuk inovasi.']
      },
      lifeCount: {
        en: ['This is your 5th reincarnation.', 'You have lived a total of 12 lives so far.', 'This life is your 3rd experience.', 'You have reincarnated 9 times up to this life.', 'This life follows your 4th past life.', 'You have lived 15 lives so far.', 'This is your 6th life.', 'You have reincarnated 11 times up to this life.', 'This life is a new beginning after your 7th past life.', 'You have built pottery experience through 18 lives.'],
        ja: ['これはあなたの5回目の転生です。', 'これまでに合計12回の人生を生きました。', '今生は3回目の経験です。', '今生までに9回転生しました。', '今生は4番目の前世の後に続きます。', 'これまでに15回の人生を生きました。', '今生は6回目の人生です。', '今生までに11回転生しました。', '今生は7番目の前世を経た新たな始まりです。', 'これまでに18回の人生で陶芸の経験を積みました。'],
        'zh-CN': ['这是你的第5次转生。', '截至目前你总共经历了12次人生。', '今生是你的第3次体验。', '到今生为止你已经转生了9次。', '今生延续自你的第4次前世。', '截至目前你已经经历了15次人生。', '今生是你的第6次人生。', '到今生为止你已经转生了11次。', '今生是你第7次前世后的新开始。', '通过18次人生你积累了陶艺经验。'],
        'zh-TW': ['這是你的第5次轉生。', '截至目前你總共經歷了12次人生。', '今生是你的第3次體驗。', '到今生為止你已經轉生了9次。', '今生延續自你的第4次前世。', '截至目前你已經經歷了15次人生。', '今生是你的第6次人生。', '到今生為止你已經轉生了11次。', '今生是你第7次前世後的新開始。', '通過18次人生你積累了陶藝經驗。'],
        vi: ['Đây là lần tái sinh thứ 5 của bạn.', 'Bạn đã sống tổng cộng 12 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 3 của bạn.', 'Bạn đã tái sinh 9 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 4 của bạn.', 'Bạn đã sống 15 kiếp cho đến nay.', 'Đây là kiếp thứ 6 của bạn.', 'Bạn đã tái sinh 11 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 7 của bạn.', 'Bạn đã tích lũy kinh nghiệm gốm sứ qua 18 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-5 Anda.', 'Anda telah menjalani total 12 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-3 Anda.', 'Anda telah bereinkarnasi 9 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-4 Anda.', 'Anda telah menjalani 15 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-6 Anda.', 'Anda telah bereinkarnasi 11 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-7 Anda.', 'Anda telah membangun pengalaman keramik melalui 18 kehidupan.']
      }
    }
  },
  22: {
    reincarnation: {
      era: {
        en: ['You were an ancient Egyptian blacksmith.', 'In your past life, you were an ancient Chinese blacksmith.', 'You were a Roman blacksmith.', 'In your past life, you were a Greek blacksmith.', 'You were a Japanese blacksmith.', 'In your past life, you were an Indian blacksmith.', 'You were a Celtic blacksmith.', 'In your past life, you were a Persian blacksmith.', 'You were a Viking blacksmith.', 'In your past life, you were a Korean blacksmith.'],
        ja: ['あなたは古代エジプトの鍛冶屋でした。', '前世であなたは古代中国の鍛冶屋でした。', 'あなたはローマの鍛冶屋でした。', '前世であなたはギリシャの鍛冶屋でした。', 'あなたは日本の鍛冶屋でした。', '前世であなたはインドの鍛冶屋でした。', 'あなたはケルトの鍛冶屋でした。', '前世であなたはペルシャの鍛冶屋でした。', 'あなたはバイキングの鍛冶屋でした。', '前世であなたは韓国の鍛冶屋でした。'],
        'zh-CN': ['你是古埃及的铁匠。', '你的前世是古代中国的铁匠。', '你是罗马的铁匠。', '你的前世是希腊的铁匠。', '你是日本的铁匠。', '你的前世是印度的铁匠。', '你是凯尔特的铁匠。', '你的前世是波斯的铁匠。', '你是维京的铁匠。', '你的前世是韩国的铁匠。'],
        'zh-TW': ['你是古埃及的鐵匠。', '你的前世是古代中國的鐵匠。', '你是羅馬的鐵匠。', '你的前世是希臘的鐵匠。', '你是日本的鐵匠。', '你的前世是印度的鐵匠。', '你是凱爾特的鐵匠。', '你的前世是波斯的鐵匠。', '你是維京的鐵匠。', '你的前世是韓國的鐵匠。'],
        vi: ['Bạn là một thợ rèn Ai Cập cổ đại.', 'Ở kiếp trước, bạn là một thợ rèn Trung Quốc cổ đại.', 'Bạn là một thợ rèn La Mã.', 'Ở kiếp trước, bạn là một thợ rèn Hy Lạp.', 'Bạn là một thợ rèn Nhật Bản.', 'Ở kiếp trước, bạn là một thợ rèn Ấn Độ.', 'Bạn là một thợ rèn Celtic.', 'Ở kiếp trước, bạn là một thợ rèn Ba Tư.', 'Bạn là một thợ rèn Viking.', 'Ở kiếp trước, bạn là một thợ rèn Hàn Quốc.'],
        id: ['Anda adalah pandai besi Mesir kuno.', 'Di kehidupan lampau, Anda adalah pandai besi Tiongkok kuno.', 'Anda adalah pandai besi Romawi.', 'Di kehidupan lampau, Anda adalah pandai besi Yunani.', 'Anda adalah pandai besi Jepang.', 'Di kehidupan lampau, Anda adalah pandai besi India.', 'Anda adalah pandai besi Celtic.', 'Di kehidupan lampau, Anda adalah pandai besi Persia.', 'Anda adalah pandai besi Viking.', 'Di kehidupan lampau, Anda adalah pandai besi Korea.']
      },
      occupation: {
        en: ['You were a weapon smith in your past life.', 'In your past life, you were a tool smith.', 'You were a armor smith in your past life.', 'In your past life, you were a jewelry smith.', 'You were a horseshoe smith in your past life.', 'In your past life, you were a nail smith.', 'You were a decorative smith in your past life.', 'In your past life, you were a bell smith.', 'You were a chain smith in your past life.', 'In your past life, you were a smithing teacher.'],
        ja: ['あなたは前世で武器鍛冶でした。', '前世であなたは道具鍛冶でした。', 'あなたは前世で甲冑鍛冶でした。', '前世であなたは装飾品鍛冶でした。', 'あなたは前世で蹄鉄鍛冶でした。', '前世であなたは釘鍛冶でした。', 'あなたは前世で装飾鍛冶でした。', '前世であなたは鐘鍛冶でした。', 'あなたは前世で鎖鍛冶でした。', '前世であなたは鍛冶教師でした。'],
        'zh-CN': ['你的前世是武器铁匠。', '你的前世是工具铁匠。', '你的前世是盔甲铁匠。', '你的前世是珠宝铁匠。', '你的前世是马蹄铁铁匠。', '你的前世是钉子铁匠。', '你的前世是装饰铁匠。', '你的前世是钟铁匠。', '你的前世是链条铁匠。', '你的前世是铁匠教师。'],
        'zh-TW': ['你的前世是武器鐵匠。', '你的前世是工具鐵匠。', '你的前世是盔甲鐵匠。', '你的前世是珠寶鐵匠。', '你的前世是馬蹄鐵鐵匠。', '你的前世是釘子鐵匠。', '你的前世是裝飾鐵匠。', '你的前世是鐘鐵匠。', '你的前世是鏈條鐵匠。', '你的前世是鐵匠教師。'],
        vi: ['Bạn từng là thợ rèn vũ khí ở kiếp trước.', 'Ở kiếp trước, bạn là thợ rèn dụng cụ.', 'Bạn từng là thợ rèn áo giáp ở kiếp trước.', 'Ở kiếp trước, bạn là thợ rèn trang sức.', 'Bạn từng là thợ rèn móng ngựa ở kiếp trước.', 'Ở kiếp trước, bạn là thợ rèn đinh.', 'Bạn từng là thợ rèn trang trí ở kiếp trước.', 'Ở kiếp trước, bạn là thợ rèn chuông.', 'Bạn từng là thợ rèn xích ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên rèn.'],
        id: ['Di kehidupan lampau, Anda adalah pandai besi senjata.', 'Di kehidupan lampau, Anda adalah pandai besi alat.', 'Di kehidupan lampau, Anda adalah pandai besi baju besi.', 'Di kehidupan lampau, Anda adalah pandai besi perhiasan.', 'Di kehidupan lampau, Anda adalah pandai besi tapal kuda.', 'Di kehidupan lampau, Anda adalah pandai besi paku.', 'Di kehidupan lampau, Anda adalah pandai besi dekoratif.', 'Di kehidupan lampau, Anda adalah pandai besi lonceng.', 'Di kehidupan lampau, Anda adalah pandai besi rantai.', 'Di kehidupan lampau, Anda adalah guru pandai besi.']
      },
      reason: {
        en: ['You came to use past metalworking skills in modern craftsmanship.', 'You returned to apply forging techniques to personal strength.', 'You came to use smithing precision in detailed work.', 'You returned to use metal knowledge for durability.', 'You came to use forging patience for persistence.', 'You returned to use metal wisdom for transformation.', 'You came to use smithing artistry for beauty.', 'You returned to use metal teaching for guidance.', 'You came to use forging mastery for foundation building.', 'You returned to use metal knowledge for innovation.'],
        ja: ['前世の金属加工技術を今生の現代職人技に活かすために来ました。', '前世の鍛造技術を今生の個人的強さに用いるために来ました。', '前世の鍛冶精密さを今生の詳細作業に活かすために来ました。', '前世の金属知識を今生の耐久性に用いるために来ました。', '前世の鍛造忍耐を今生の持続性に活かすために来ました。', '前世の金属知恵を今生の変容に用いるために来ました。', '前世の鍛冶芸術性を今生の美しさに活かすために来ました。', '前世の金属教育を今生の指導に用いるために来ました。', '前世の鍛造習得を今生の基盤構築に活かすために来ました。', '前世の金属知識を今生の革新に用いるために来ました。'],
        'zh-CN': ['你为了将前世的金属加工技能用于今生的现代工艺而来。', '你为了将前世的锻造技术用于今生的个人力量而来。', '你为了将前世的铁匠精度用于今生的细致工作而来。', '你为了将前世的金属知识用于今生的耐久性而来。', '你为了将前世的锻造耐心用于今生的坚持而来。', '你为了将前世的金属智慧用于今生的转变而来。', '你为了将前世的铁匠艺术用于今生的美感而来。', '你为了将前世的金属教学用于今生的指导而来。', '你为了将前世的锻造掌握用于今生的基础建设而来。', '你为了将前世的金属知识用于今生的创新而来。'],
        'zh-TW': ['你為了將前世的金屬加工技能用於今生的現代工藝而來。', '你為了將前世的鍛造技術用於今生的個人力量而來。', '你為了將前世的鐵匠精度用於今生的細緻工作而來。', '你為了將前世的金屬知識用於今生的耐久性而來。', '你為了將前世的鍛造耐心用於今生的堅持而來。', '你為了將前世的金屬智慧用於今生的轉變而來。', '你為了將前世的鐵匠藝術用於今生的美感而來。', '你為了將前世的金屬教學用於今生的指導而來。', '你為了將前世的鍛造掌握用於今生的基礎建設而來。', '你為了將前世的金屬知識用於今生的創新而來。'],
        vi: ['Bạn đến để sử dụng kỹ năng gia công kim loại từ kiếp trước trong thủ công hiện đại.', 'Bạn trở lại để áp dụng kỹ thuật rèn vào sức mạnh cá nhân.', 'Bạn đến để sử dụng độ chính xác rèn trong công việc chi tiết.', 'Bạn trở lại để sử dụng kiến thức kim loại cho độ bền.', 'Bạn đến để sử dụng sự kiên nhẫn rèn cho sự bền bỉ.', 'Bạn trở lại để sử dụng trí tuệ kim loại cho sự biến đổi.', 'Bạn đến để sử dụng nghệ thuật rèn cho vẻ đẹp.', 'Bạn trở lại để sử dụng giảng dạy kim loại cho hướng dẫn.', 'Bạn đến để sử dụng sự thành thạo rèn cho xây dựng nền tảng.', 'Bạn trở lại để sử dụng kiến thức kim loại cho đổi mới.'],
        id: ['Anda datang untuk menggunakan keterampilan metalworking masa lalu dalam kerajinan modern.', 'Anda kembali untuk menerapkan teknik tempa pada kekuatan pribadi.', 'Anda datang untuk menggunakan presisi pandai besi dalam pekerjaan detail.', 'Anda kembali untuk menggunakan pengetahuan logam untuk daya tahan.', 'Anda datang untuk menggunakan kesabaran tempa untuk ketekunan.', 'Anda kembali untuk menggunakan kebijaksanaan logam untuk transformasi.', 'Anda datang untuk menggunakan seni pandai besi untuk keindahan.', 'Anda kembali untuk menggunakan pengajaran logam untuk bimbingan.', 'Anda datang untuk menggunakan penguasaan tempa untuk membangun fondasi.', 'Anda kembali untuk menggunakan pengetahuan logam untuk inovasi.']
      },
      lifeCount: {
        en: ['This is your 6th reincarnation.', 'You have lived a total of 13 lives so far.', 'This life is your 4th experience.', 'You have reincarnated 10 times up to this life.', 'This life follows your 5th past life.', 'You have lived 16 lives so far.', 'This is your 7th life.', 'You have reincarnated 12 times up to this life.', 'This life is a new beginning after your 8th past life.', 'You have built metalworking experience through 19 lives.'],
        ja: ['これはあなたの6回目の転生です。', 'これまでに合計13回の人生を生きました。', '今生は4回目の経験です。', '今生までに10回転生しました。', '今生は5番目の前世の後に続きます。', 'これまでに16回の人生を生きました。', '今生は7回目の人生です。', '今生までに12回転生しました。', '今生は8番目の前世を経た新たな始まりです。', 'これまでに19回の人生で金属加工の経験を積みました。'],
        'zh-CN': ['这是你的第6次转生。', '截至目前你总共经历了13次人生。', '今生是你的第4次体验。', '到今生为止你已经转生了10次。', '今生延续自你的第5次前世。', '截至目前你已经经历了16次人生。', '今生是你的第7次人生。', '到今生为止你已经转生了12次。', '今生是你第8次前世后的新开始。', '通过19次人生你积累了金属加工经验。'],
        'zh-TW': ['這是你的第6次轉生。', '截至目前你總共經歷了13次人生。', '今生是你的第4次體驗。', '到今生為止你已經轉生了10次。', '今生延續自你的第5次前世。', '截至目前你已經經歷了16次人生。', '今生是你的第7次人生。', '到今生為止你已經轉生了12次。', '今生是你第8次前世後的新開始。', '通過19次人生你積累了金屬加工經驗。'],
        vi: ['Đây là lần tái sinh thứ 6 của bạn.', 'Bạn đã sống tổng cộng 13 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 4 của bạn.', 'Bạn đã tái sinh 10 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 5 của bạn.', 'Bạn đã sống 16 kiếp cho đến nay.', 'Đây là kiếp thứ 7 của bạn.', 'Bạn đã tái sinh 12 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 8 của bạn.', 'Bạn đã tích lũy kinh nghiệm gia công kim loại qua 19 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-6 Anda.', 'Anda telah menjalani total 13 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-4 Anda.', 'Anda telah bereinkarnasi 10 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-5 Anda.', 'Anda telah menjalani 16 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-7 Anda.', 'Anda telah bereinkarnasi 12 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-8 Anda.', 'Anda telah membangun pengalaman metalworking melalui 19 kehidupan.']
      }
    }
  }
};