import { FaceReincarnationTranslations } from '../merge';

export const batch35: FaceReincarnationTranslations = {
  50: {
    reincarnation: {
      era: {
        en: ['You were an ancient Egyptian philosopher.', 'In your past life, you were an ancient Chinese philosopher.', 'You were a Roman philosopher.', 'In your past life, you were a Greek philosopher.', 'You were a Japanese philosopher.', 'In your past life, you were an Indian philosopher.', 'You were a Celtic philosopher.', 'In your past life, you were a Persian philosopher.', 'You were a Mayan philosopher.', 'In your past life, you were a Korean philosopher.'],
        ja: ['あなたは古代エジプトの哲学者でした。', '前世であなたは古代中国の哲学者でした。', 'あなたはローマの哲学者でした。', '前世であなたはギリシャの哲学者でした。', 'あなたは日本の哲学者でした。', '前世であなたはインドの哲学者でした。', 'あなたはケルトの哲学者でした。', '前世であなたはペルシャの哲学者でした。', 'あなたはマヤの哲学者でした。', '前世であなたは韓国の哲学者でした。'],
        'zh-CN': ['你是古埃及的哲学家。', '你的前世是古代中国的哲学家。', '你是罗马的哲学家。', '你的前世是希腊的哲学家。', '你是日本的哲学家。', '你的前世是印度的哲学家。', '你是凯尔特的哲学家。', '你的前世是波斯的哲学家。', '你是玛雅的哲学家。', '你的前世是韩国的哲学家。'],
        'zh-TW': ['你是古埃及的哲學家。', '你的前世是古代中國的哲學家。', '你是羅馬的哲學家。', '你的前世是希臘的哲學家。', '你是日本的哲學家。', '你的前世是印度的哲學家。', '你是凱爾特的哲學家。', '你的前世是波斯的哲學家。', '你是瑪雅的哲學家。', '你的前世是韓國的哲學家。'],
        vi: ['Bạn là một triết gia Ai Cập cổ đại.', 'Ở kiếp trước, bạn là một triết gia Trung Quốc cổ đại.', 'Bạn là một triết gia La Mã.', 'Ở kiếp trước, bạn là một triết gia Hy Lạp.', 'Bạn là một triết gia Nhật Bản.', 'Ở kiếp trước, bạn là một triết gia Ấn Độ.', 'Bạn là một triết gia Celtic.', 'Ở kiếp trước, bạn là một triết gia Ba Tư.', 'Bạn là một triết gia Maya.', 'Ở kiếp trước, bạn là một triết gia Hàn Quốc.'],
        id: ['Anda adalah filsuf Mesir kuno.', 'Di kehidupan lampau, Anda adalah filsuf Tiongkok kuno.', 'Anda adalah filsuf Romawi.', 'Di kehidupan lampau, Anda adalah filsuf Yunani.', 'Anda adalah filsuf Jepang.', 'Di kehidupan lampau, Anda adalah filsuf India.', 'Anda adalah filsuf Celtic.', 'Di kehidupan lampau, Anda adalah filsuf Persia.', 'Anda adalah filsuf Maya.', 'Di kehidupan lampau, Anda adalah filsuf Korea.']
      },
      occupation: {
        en: ['You were a royal philosopher in your past life.', 'In your past life, you were a temple philosopher.', 'You were a court philosopher in your past life.', 'In your past life, you were a street philosopher.', 'You were a ceremonial philosopher in your past life.', 'In your past life, you were a religious philosopher.', 'You were a traveling philosopher in your past life.', 'In your past life, you were a village philosopher.', 'You were a merchant philosopher in your past life.', 'In your past life, you were a philosophy teacher.'],
        ja: ['あなたは前世で王室哲学者でした。', '前世であなたは寺院哲学者でした。', 'あなたは前世で宮廷哲学者でした。', '前世であなたはストリート哲学者でした。', 'あなたは前世で儀式哲学者でした。', '前世であなたは宗教哲学者でした。', 'あなたは前世で旅哲学者でした。', '前世であなたは村哲学者でした。', 'あなたは前世で商人哲学者でした。', '前世であなたは哲学教師でした。'],
        'zh-CN': ['你的前世是王室哲学家。', '你的前世是寺庙哲学家。', '你的前世是宫廷哲学家。', '你的前世是街头哲学家。', '你的前世是仪式哲学家。', '你的前世是宗教哲学家。', '你的前世是游方哲学家。', '你的前世是乡村哲学家。', '你的前世是商人哲学家。', '你的前世是哲学教师。'],
        'zh-TW': ['你的前世是王室哲學家。', '你的前世是寺廟哲學家。', '你的前世是宮廷哲學家。', '你的前世是街頭哲學家。', '你的前世是儀式哲學家。', '你的前世是宗教哲學家。', '你的前世是遊方哲學家。', '你的前世是鄉村哲學家。', '你的前世是商人哲學家。', '你的前世是哲學教師。'],
        vi: ['Bạn từng là triết gia hoàng gia ở kiếp trước.', 'Ở kiếp trước, bạn là triết gia đền thờ.', 'Bạn từng là triết gia triều đình ở kiếp trước.', 'Ở kiếp trước, bạn là triết gia đường phố.', 'Bạn từng là triết gia nghi lễ ở kiếp trước.', 'Ở kiếp trước, bạn là triết gia tôn giáo.', 'Bạn từng là triết gia du hành ở kiếp trước.', 'Ở kiếp trước, bạn là triết gia làng.', 'Bạn từng là triết gia thương nhân ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên triết học.'],
        id: ['Di kehidupan lampau, Anda adalah filsuf kerajaan.', 'Di kehidupan lampau, Anda adalah filsuf kuil.', 'Di kehidupan lampau, Anda adalah filsuf istana.', 'Di kehidupan lampau, Anda adalah filsuf jalanan.', 'Di kehidupan lampau, Anda adalah filsuf upacara.', 'Di kehidupan lampau, Anda adalah filsuf agama.', 'Di kehidupan lampau, Anda adalah filsuf keliling.', 'Di kehidupan lampau, Anda adalah filsuf desa.', 'Di kehidupan lampau, Anda adalah filsuf pedagang.', 'Di kehidupan lampau, Anda adalah guru filsafat.']
      },
      reason: {
        en: ['You came to use past philosophical skills in wisdom and understanding.', 'You returned to apply philosophical wisdom to truth seeking.', 'You came to use philosophical patience for deep thinking.', 'You returned to use philosophical knowledge for guidance.', 'You came to use philosophical precision for clarity.', 'You returned to use philosophical instincts for intuition.', 'You came to use philosophical responsibility for enlightenment.', 'You returned to use philosophical teaching for guidance.', 'You came to use philosophical mastery for foundation building.', 'You returned to use philosophical knowledge for innovation.'],
        ja: ['前世の哲学技術を今生の知恵と理解に活かすために来ました。', '前世の哲学的知恵を今生の真理探求に用いるために来ました。', '前世の哲学忍耐を今生の深い思考に活かすために来ました。', '前世の哲学知識を今生の指導に用いるために来ました。', '前世の哲学精密さを今生の明確さに活かすために来ました。', '前世の哲学本能を今生の直感に用いるために来ました。', '前世の哲学責任を今生の悟りに活かすために来ました。', '前世の哲学教育を今生の指導に用いるために来ました。', '前世の哲学習得を今生の基盤構築に活かすために来ました。', '前世の哲学知識を今生の革新に用いるために来ました。'],
        'zh-CN': ['你为了将前世的哲学技能用于今生的智慧和理解而来。', '你为了将前世的哲学智慧用于今生的真理探索而来。', '你为了将前世的哲学耐心用于今生的深度思考而来。', '你为了将前世的哲学知识用于今生的指导而来。', '你为了将前世的哲学精度用于今生的清晰而来。', '你为了将前世的哲学本能用于今生的直觉而来。', '你为了将前世的哲学责任用于今生的启蒙而来。', '你为了将前世的哲学教学用于今生的指导而来。', '你为了将前世的哲学掌握用于今生的基础建设而来。', '你为了将前世的哲学知识用于今生的创新而来。'],
        'zh-TW': ['你為了將前世的哲學技能用於今生的智慧和理解而來。', '你為了將前世的哲學智慧用於今生的真理探索而來。', '你為了將前世的哲學耐心用於今生的深度思考而來。', '你為了將前世的哲學知識用於今生的指導而來。', '你為了將前世的哲學精度用於今生的清晰而來。', '你為了將前世的哲學本能用於今生的直覺而來。', '你為了將前世的哲學責任用於今生的啟蒙而來。', '你為了將前世的哲學教學用於今生的指導而來。', '你為了將前世的哲學掌握用於今生的基礎建設而來。', '你為了將前世的哲學知識用於今生的創新而來。'],
        vi: ['Bạn đến để sử dụng kỹ năng triết học từ kiếp trước trong trí tuệ và hiểu biết.', 'Bạn trở lại để áp dụng trí tuệ triết học vào tìm kiếm chân lý.', 'Bạn đến để sử dụng sự kiên nhẫn triết học cho suy nghĩ sâu sắc.', 'Bạn trở lại để sử dụng kiến thức triết học cho hướng dẫn.', 'Bạn đến để sử dụng độ chính xác triết học cho sự rõ ràng.', 'Bạn trở lại để sử dụng bản năng triết học cho trực giác.', 'Bạn đến để sử dụng trách nhiệm triết học cho giác ngộ.', 'Bạn trở lại để sử dụng giảng dạy triết học cho hướng dẫn.', 'Bạn đến để sử dụng sự thành thạo triết học cho xây dựng nền tảng.', 'Bạn trở lại để sử dụng kiến thức triết học cho đổi mới.'],
        id: ['Anda datang untuk menggunakan keterampilan filosofis masa lalu dalam kebijaksanaan dan pemahaman.', 'Anda kembali untuk menerapkan kebijaksanaan filosofis pada pencarian kebenaran.', 'Anda datang untuk menggunakan kesabaran filosofis untuk pemikiran mendalam.', 'Anda kembali untuk menggunakan pengetahuan filosofis untuk bimbingan.', 'Anda datang untuk menggunakan presisi filosofis untuk kejelasan.', 'Anda kembali untuk menggunakan insting filosofis untuk intuisi.', 'Anda datang untuk menggunakan tanggung jawab filosofis untuk pencerahan.', 'Anda kembali untuk menggunakan pengajaran filosofis untuk bimbingan.', 'Anda datang untuk menggunakan penguasaan filosofis untuk membangun fondasi.', 'Anda kembali untuk menggunakan pengetahuan filosofis untuk inovasi.']
      },
      lifeCount: {
        en: ['This is your 34th reincarnation.', 'You have lived a total of 41 lives so far.', 'This life is your 32nd experience.', 'You have reincarnated 38 times up to this life.', 'This life follows your 33rd past life.', 'You have lived 44 lives so far.', 'This is your 35th life.', 'You have reincarnated 40 times up to this life.', 'This life is a new beginning after your 36th past life.', 'You have built philosophical experience through 47 lives.'],
        ja: ['これはあなたの34回目の転生です。', 'これまでに合計41回の人生を生きました。', '今生は32回目の経験です。', '今生までに38回転生しました。', '今生は33番目の前世の後に続きます。', 'これまでに44回の人生を生きました。', '今生は35回目の人生です。', '今生までに40回転生しました。', '今生は36番目の前世を経た新たな始まりです。', 'これまでに47回の人生で哲学の経験を積みました。'],
        'zh-CN': ['这是你的第34次转生。', '截至目前你总共经历了41次人生。', '今生是你的第32次体验。', '到今生为止你已经转生了38次。', '今生延续自你的第33次前世。', '截至目前你已经经历了44次人生。', '今生是你的第35次人生。', '到今生为止你已经转生了40次。', '今生是你第36次前世后的新开始。', '通过47次人生你积累了哲学经验。'],
        'zh-TW': ['這是你的第34次轉生。', '截至目前你總共經歷了41次人生。', '今生是你的第32次體驗。', '到今生為止你已經轉生了38次。', '今生延續自你的第33次前世。', '截至目前你已經經歷了44次人生。', '今生是你的第35次人生。', '到今生為止你已經轉生了40次。', '今生是你第36次前世後的新開始。', '通過47次人生你積累了哲學經驗。'],
        vi: ['Đây là lần tái sinh thứ 34 của bạn.', 'Bạn đã sống tổng cộng 41 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 32 của bạn.', 'Bạn đã tái sinh 38 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 33 của bạn.', 'Bạn đã sống 44 kiếp cho đến nay.', 'Đây là kiếp thứ 35 của bạn.', 'Bạn đã tái sinh 40 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 36 của bạn.', 'Bạn đã tích lũy kinh nghiệm triết học qua 47 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-34 Anda.', 'Anda telah menjalani total 41 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-32 Anda.', 'Anda telah bereinkarnasi 38 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-33 Anda.', 'Anda telah menjalani 44 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-35 Anda.', 'Anda telah bereinkarnasi 40 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-36 Anda.', 'Anda telah membangun pengalaman filosofis melalui 47 kehidupan.']
      }
    }
  }
};