import { FaceReincarnationTranslations } from '../merge';

export const batch30: FaceReincarnationTranslations = {
  40: {
    reincarnation: {
      era: {
        en: ['You were an ancient Egyptian chef.', 'In your past life, you were an ancient Chinese chef.', 'You were a Roman chef.', 'In your past life, you were a Greek chef.', 'You were a Japanese chef.', 'In your past life, you were an Indian chef.', 'You were a Celtic chef.', 'In your past life, you were a Persian chef.', 'You were a Mayan chef.', 'In your past life, you were a Korean chef.'],
        ja: ['あなたは古代エジプトの料理人でした。', '前世であなたは古代中国の料理人でした。', 'あなたはローマの料理人でした。', '前世であなたはギリシャの料理人でした。', 'あなたは日本の料理人でした。', '前世であなたはインドの料理人でした。', 'あなたはケルトの料理人でした。', '前世であなたはペルシャの料理人でした。', 'あなたはマヤの料理人でした。', '前世であなたは韓国の料理人でした。'],
        'zh-CN': ['你是古埃及的厨师。', '你的前世是古代中国的厨师。', '你是罗马的厨师。', '你的前世是希腊的厨师。', '你是日本的厨师。', '你的前世是印度的厨师。', '你是凯尔特的厨师。', '你的前世是波斯的厨师。', '你是玛雅的厨师。', '你的前世是韩国的厨师。'],
        'zh-TW': ['你是古埃及的廚師。', '你的前世是古代中國的廚師。', '你是羅馬的廚師。', '你的前世是希臘的廚師。', '你是日本的廚師。', '你的前世是印度的廚師。', '你是凱爾特的廚師。', '你的前世是波斯的廚師。', '你是瑪雅的廚師。', '你的前世是韓國的廚師。'],
        vi: ['Bạn là một đầu bếp Ai Cập cổ đại.', 'Ở kiếp trước, bạn là một đầu bếp Trung Quốc cổ đại.', 'Bạn là một đầu bếp La Mã.', 'Ở kiếp trước, bạn là một đầu bếp Hy Lạp.', 'Bạn là một đầu bếp Nhật Bản.', 'Ở kiếp trước, bạn là một đầu bếp Ấn Độ.', 'Bạn là một đầu bếp Celtic.', 'Ở kiếp trước, bạn là một đầu bếp Ba Tư.', 'Bạn là một đầu bếp Maya.', 'Ở kiếp trước, bạn là một đầu bếp Hàn Quốc.'],
        id: ['Anda adalah koki Mesir kuno.', 'Di kehidupan lampau, Anda adalah koki Tiongkok kuno.', 'Anda adalah koki Romawi.', 'Di kehidupan lampau, Anda adalah koki Yunani.', 'Anda adalah koki Jepang.', 'Di kehidupan lampau, Anda adalah koki India.', 'Anda adalah koki Celtic.', 'Di kehidupan lampau, Anda adalah koki Persia.', 'Anda adalah koki Maya.', 'Di kehidupan lampau, Anda adalah koki Korea.']
      },
      occupation: {
        en: ['You were a royal chef in your past life.', 'In your past life, you were a temple chef.', 'You were a tavern chef in your past life.', 'In your past life, you were a street chef.', 'You were a banquet chef in your past life.', 'In your past life, you were a home chef.', 'You were a ceremonial chef in your past life.', 'In your past life, you were a military chef.', 'You were a merchant chef in your past life.', 'In your past life, you were a cooking teacher.'],
        ja: ['あなたは前世で王室料理人でした。', '前世であなたは寺院料理人でした。', 'あなたは前世で居酒屋料理人でした。', '前世であなたは屋台料理人でした。', 'あなたは前世で宴会料理人でした。', '前世であなたは家庭料理人でした。', 'あなたは前世で儀式料理人でした。', '前世であなたは軍料理人でした。', 'あなたは前世で商人料理人でした。', '前世であなたは料理教師でした。'],
        'zh-CN': ['你的前世是王室厨师。', '你的前世是寺庙厨师。', '你的前世是酒馆厨师。', '你的前世是街头厨师。', '你的前世是宴会厨师。', '你的前世是家庭厨师。', '你的前世是仪式厨师。', '你的前世是军队厨师。', '你的前世是商人厨师。', '你的前世是烹饪教师。'],
        'zh-TW': ['你的前世是王室廚師。', '你的前世是寺廟廚師。', '你的前世是酒館廚師。', '你的前世是街頭廚師。', '你的前世是宴會廚師。', '你的前世是家庭廚師。', '你的前世是儀式廚師。', '你的前世是軍隊廚師。', '你的前世是商人廚師。', '你的前世是烹飪教師。'],
        vi: ['Bạn từng là đầu bếp hoàng gia ở kiếp trước.', 'Ở kiếp trước, bạn là đầu bếp đền thờ.', 'Bạn từng là đầu bếp quán rượu ở kiếp trước.', 'Ở kiếp trước, bạn là đầu bếp đường phố.', 'Bạn từng là đầu bếp tiệc tùng ở kiếp trước.', 'Ở kiếp trước, bạn là đầu bếp gia đình.', 'Bạn từng là đầu bếp nghi lễ ở kiếp trước.', 'Ở kiếp trước, bạn là đầu bếp quân đội.', 'Bạn từng là đầu bếp thương nhân ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên nấu ăn.'],
        id: ['Di kehidupan lampau, Anda adalah koki kerajaan.', 'Di kehidupan lampau, Anda adalah koki kuil.', 'Di kehidupan lampau, Anda adalah koki kedai minuman.', 'Di kehidupan lampau, Anda adalah koki jalanan.', 'Di kehidupan lampau, Anda adalah koki pesta.', 'Di kehidupan lampau, Anda adalah koki rumah.', 'Di kehidupan lampau, Anda adalah koki upacara.', 'Di kehidupan lampau, Anda adalah koki militer.', 'Di kehidupan lampau, Anda adalah koki pedagang.', 'Di kehidupan lampau, Anda adalah guru memasak.']
      },
      reason: {
        en: ['You came to use past cooking skills in creativity and nurturing.', 'You returned to apply fire wisdom to transformation and healing.', 'You came to use cooking patience for detailed work.', 'You returned to use fire knowledge for creation.', 'You came to use cooking precision for craftsmanship.', 'You returned to use fire instincts for intuition.', 'You came to use cooking responsibility for nourishment.', 'You returned to use fire teaching for guidance.', 'You came to use cooking mastery for foundation building.', 'You returned to use fire knowledge for innovation.'],
        ja: ['前世の料理技術を今生の創造性と育成に活かすために来ました。', '前世の火の知恵を今生の変容と癒しに用いるために来ました。', '前世の料理忍耐を今生の詳細作業に活かすために来ました。', '前世の火の知識を今生の創造に用いるために来ました。', '前世の料理精密さを今生の職人技に活かすために来ました。', '前世の火の本能を今生の直感に用いるために来ました。', '前世の料理責任を今生の栄養に活かすために来ました。', '前世の火の教育を今生の指導に用いるために来ました。', '前世の料理習得を今生の基盤構築に活かすために来ました。', '前世の火の知識を今生の革新に用いるために来ました。'],
        'zh-CN': ['你为了将前世的烹饪技能用于今生的创造性和培育而来。', '你为了将前世的火智慧用于今生的转化和治愈而来。', '你为了将前世的烹饪耐心用于今生的细致工作而来。', '你为了将前世的火知识用于今生的创造而来。', '你为了将前世的烹饪精度用于今生的工艺而来。', '你为了将前世的火本能用于今生的直觉而来。', '你为了将前世的烹饪责任用于今生的营养而来。', '你为了将前世的火教学用于今生的指导而来。', '你为了将前世的烹饪掌握用于今生的基础建设而来。', '你为了将前世的火知识用于今生的创新而来。'],
        'zh-TW': ['你為了將前世的烹飪技能用於今生的創造性和培育而來。', '你為了將前世的火智慧用於今生的轉化和治愈而來。', '你為了將前世的烹飪耐心用於今生的細緻工作而來。', '你為了將前世的火知識用於今生的創造而來。', '你為了將前世的烹飪精度用於今生的工藝而來。', '你為了將前世的火本能用於今生的直覺而來。', '你為了將前世的烹飪責任用於今生的營養而來。', '你為了將前世的火教學用於今生的指導而來。', '你為了將前世的烹飪掌握用於今生的基礎建設而來。', '你為了將前世的火知識用於今生的創新而來。'],
        vi: ['Bạn đến để sử dụng kỹ năng nấu ăn từ kiếp trước trong sự sáng tạo và nuôi dưỡng.', 'Bạn trở lại để áp dụng trí tuệ lửa vào sự biến đổi và chữa lành.', 'Bạn đến để sử dụng sự kiên nhẫn nấu ăn cho công việc chi tiết.', 'Bạn trở lại để sử dụng kiến thức lửa cho sáng tạo.', 'Bạn đến để sử dụng độ chính xác nấu ăn cho thủ công.', 'Bạn trở lại để sử dụng bản năng lửa cho trực giác.', 'Bạn đến để sử dụng trách nhiệm nấu ăn cho dinh dưỡng.', 'Bạn trở lại để sử dụng giảng dạy lửa cho hướng dẫn.', 'Bạn đến để sử dụng sự thành thạo nấu ăn cho xây dựng nền tảng.', 'Bạn trở lại để sử dụng kiến thức lửa cho đổi mới.'],
        id: ['Anda datang untuk menggunakan keterampilan memasak masa lalu dalam kreativitas dan pemeliharaan.', 'Anda kembali untuk menerapkan kebijaksanaan api pada transformasi dan penyembuhan.', 'Anda datang untuk menggunakan kesabaran memasak untuk pekerjaan detail.', 'Anda kembali untuk menggunakan pengetahuan api untuk kreasi.', 'Anda datang untuk menggunakan presisi memasak untuk kerajinan.', 'Anda kembali untuk menggunakan insting api untuk intuisi.', 'Anda datang untuk menggunakan tanggung jawab memasak untuk nutrisi.', 'Anda kembali untuk menggunakan pengajaran api untuk bimbingan.', 'Anda datang untuk menggunakan penguasaan memasak untuk membangun fondasi.', 'Anda kembali untuk menggunakan pengetahuan api untuk inovasi.']
      },
      lifeCount: {
        en: ['This is your 24th reincarnation.', 'You have lived a total of 31 lives so far.', 'This life is your 22nd experience.', 'You have reincarnated 28 times up to this life.', 'This life follows your 23rd past life.', 'You have lived 34 lives so far.', 'This is your 25th life.', 'You have reincarnated 30 times up to this life.', 'This life is a new beginning after your 26th past life.', 'You have built cooking experience through 37 lives.'],
        ja: ['これはあなたの24回目の転生です。', 'これまでに合計31回の人生を生きました。', '今生は22回目の経験です。', '今生までに28回転生しました。', '今生は23番目の前世の後に続きます。', 'これまでに34回の人生を生きました。', '今生は25回目の人生です。', '今生までに30回転生しました。', '今生は26番目の前世を経た新たな始まりです。', 'これまでに37回の人生で料理の経験を積みました。'],
        'zh-CN': ['这是你的第24次转生。', '截至目前你总共经历了31次人生。', '今生是你的第22次体验。', '到今生为止你已经转生了28次。', '今生延续自你的第23次前世。', '截至目前你已经经历了34次人生。', '今生是你的第25次人生。', '到今生为止你已经转生了30次。', '今生是你第26次前世后的新开始。', '通过37次人生你积累了烹饪经验。'],
        'zh-TW': ['這是你的第24次轉生。', '截至目前你總共經歷了31次人生。', '今生是你的第22次體驗。', '到今生為止你已經轉生了28次。', '今生延續自你的第23次前世。', '截至目前你已經經歷了34次人生。', '今生是你的第25次人生。', '到今生為止你已經轉生了30次。', '今生是你第26次前世後的新開始。', '通過37次人生你積累了烹飪經驗。'],
        vi: ['Đây là lần tái sinh thứ 24 của bạn.', 'Bạn đã sống tổng cộng 31 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 22 của bạn.', 'Bạn đã tái sinh 28 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 23 của bạn.', 'Bạn đã sống 34 kiếp cho đến nay.', 'Đây là kiếp thứ 25 của bạn.', 'Bạn đã tái sinh 30 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 26 của bạn.', 'Bạn đã tích lũy kinh nghiệm nấu ăn qua 37 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-24 Anda.', 'Anda telah menjalani total 31 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-22 Anda.', 'Anda telah bereinkarnasi 28 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-23 Anda.', 'Anda telah menjalani 34 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-25 Anda.', 'Anda telah bereinkarnasi 30 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-26 Anda.', 'Anda telah membangun pengalaman memasak melalui 37 kehidupan.']
      }
    }
  },
  41: {
    reincarnation: {
      era: {
        en: ['You were an ancient Egyptian doctor.', 'In your past life, you were an ancient Chinese doctor.', 'You were a Roman doctor.', 'In your past life, you were a Greek doctor.', 'You were a Japanese doctor.', 'In your past life, you were an Indian doctor.', 'You were a Celtic doctor.', 'In your past life, you were a Persian doctor.', 'You were a Mayan doctor.', 'In your past life, you were a Korean doctor.'],
        ja: ['あなたは古代エジプトの医者でした。', '前世であなたは古代中国の医者でした。', 'あなたはローマの医者でした。', '前世であなたはギリシャの医者でした。', 'あなたは日本の医者でした。', '前世であなたはインドの医者でした。', 'あなたはケルトの医者でした。', '前世であなたはペルシャの医者でした。', 'あなたはマヤの医者でした。', '前世であなたは韓国の医者でした。'],
        'zh-CN': ['你是古埃及的医生。', '你的前世是古代中国的医生。', '你是罗马的医生。', '你的前世是希腊的医生。', '你是日本的医生。', '你的前世是印度的医生。', '你是凯尔特的医生。', '你的前世是波斯的医生。', '你是玛雅的医生。', '你的前世是韩国的医生。'],
        'zh-TW': ['你是古埃及的醫生。', '你的前世是古代中國的醫生。', '你是羅馬的醫生。', '你的前世是希臘的醫生。', '你是日本的醫生。', '你的前世是印度的醫生。', '你是凱爾特的醫生。', '你的前世是波斯的醫生。', '你是瑪雅的醫生。', '你的前世是韓國的醫生。'],
        vi: ['Bạn là một bác sĩ Ai Cập cổ đại.', 'Ở kiếp trước, bạn là một bác sĩ Trung Quốc cổ đại.', 'Bạn là một bác sĩ La Mã.', 'Ở kiếp trước, bạn là một bác sĩ Hy Lạp.', 'Bạn là một bác sĩ Nhật Bản.', 'Ở kiếp trước, bạn là một bác sĩ Ấn Độ.', 'Bạn là một bác sĩ Celtic.', 'Ở kiếp trước, bạn là một bác sĩ Ba Tư.', 'Bạn là một bác sĩ Maya.', 'Ở kiếp trước, bạn là một bác sĩ Hàn Quốc.'],
        id: ['Anda adalah dokter Mesir kuno.', 'Di kehidupan lampau, Anda adalah dokter Tiongkok kuno.', 'Anda adalah dokter Romawi.', 'Di kehidupan lampau, Anda adalah dokter Yunani.', 'Anda adalah dokter Jepang.', 'Di kehidupan lampau, Anda adalah dokter India.', 'Anda adalah dokter Celtic.', 'Di kehidupan lampau, Anda adalah dokter Persia.', 'Anda adalah dokter Maya.', 'Di kehidupan lampau, Anda adalah dokter Korea.']
      },
      occupation: {
        en: ['You were a royal doctor in your past life.', 'In your past life, you were a temple doctor.', 'You were a military doctor in your past life.', 'In your past life, you were a village doctor.', 'You were a court doctor in your past life.', 'In your past life, you were a traveling doctor.', 'You were a herbal doctor in your past life.', 'In your past life, you were a surgical doctor.', 'You were a spiritual doctor in your past life.', 'In your past life, you were a medical teacher.'],
        ja: ['あなたは前世で王室医者でした。', '前世であなたは寺院医者でした。', 'あなたは前世で軍医者でした。', '前世であなたは村医者でした。', 'あなたは前世で宮廷医者でした。', '前世であなたは旅医者でした。', 'あなたは前世で薬草医者でした。', '前世であなたは外科医者でした。', 'あなたは前世で霊的医者でした。', '前世であなたは医学教師でした。'],
        'zh-CN': ['你的前世是王室医生。', '你的前世是寺庙医生。', '你的前世是军医。', '你的前世是乡村医生。', '你的前世是宫廷医生。', '你的前世是游医。', '你的前世是草药医生。', '你的前世是外科医生。', '你的前世是精神医生。', '你的前世是医学教师。'],
        'zh-TW': ['你的前世是王室醫生。', '你的前世是寺廟醫生。', '你的前世是軍醫。', '你的前世是鄉村醫生。', '你的前世是宮廷醫生。', '你的前世是遊醫。', '你的前世是草藥醫生。', '你的前世是外科醫生。', '你的前世是精神醫生。', '你的前世是醫學教師。'],
        vi: ['Bạn từng là bác sĩ hoàng gia ở kiếp trước.', 'Ở kiếp trước, bạn là bác sĩ đền thờ.', 'Bạn từng là bác sĩ quân đội ở kiếp trước.', 'Ở kiếp trước, bạn là bác sĩ làng.', 'Bạn từng là bác sĩ triều đình ở kiếp trước.', 'Ở kiếp trước, bạn là bác sĩ du hành.', 'Bạn từng là bác sĩ thảo dược ở kiếp trước.', 'Ở kiếp trước, bạn là bác sĩ phẫu thuật.', 'Bạn từng là bác sĩ tâm linh ở kiếp trước.', 'Ở kiếp trước, bạn là giáo viên y học.'],
        id: ['Di kehidupan lampau, Anda adalah dokter kerajaan.', 'Di kehidupan lampau, Anda adalah dokter kuil.', 'Di kehidupan lampau, Anda adalah dokter militer.', 'Di kehidupan lampau, Anda adalah dokter desa.', 'Di kehidupan lampau, Anda adalah dokter istana.', 'Di kehidupan lampau, Anda adalah dokter keliling.', 'Di kehidupan lampau, Anda adalah dokter herbal.', 'Di kehidupan lampau, Anda adalah dokter bedah.', 'Di kehidupan lampau, Anda adalah dokter spiritual.', 'Di kehidupan lampau, Anda adalah guru medis.']
      },
      reason: {
        en: ['You came to use past medical skills in healing and compassion.', 'You returned to apply healing wisdom to service and care.', 'You came to use medical patience for detailed diagnosis.', 'You returned to use healing knowledge for treatment.', 'You came to use medical precision for accuracy.', 'You returned to use healing instincts for intuition.', 'You came to use medical responsibility for saving lives.', 'You returned to use healing teaching for guidance.', 'You came to use medical mastery for foundation building.', 'You returned to use healing knowledge for innovation.'],
        ja: ['前世の医学技術を今生の癒しと慈悲に活かすために来ました。', '前世の癒しの知恵を今生の奉仕とケアに用いるために来ました。', '前世の医学忍耐を今生の詳細診断に活かすために来ました。', '前世の癒しの知識を今生の治療に用いるために来ました。', '前世の医学精密さを今生の正確性に活かすために来ました。', '前世の癒しの本能を今生の直感に用いるために来ました。', '前世の医学責任を今生の命を救うことに活かすために来ました。', '前世の癒しの教育を今生の指導に用いるために来ました。', '前世の医学習得を今生の基盤構築に活かすために来ました。', '前世の癒しの知識を今生の革新に用いるために来ました。'],
        'zh-CN': ['你为了将前世的医学技能用于今生的治愈和慈悲而来。', '你为了将前世的治愈智慧用于今生的服务和关怀而来。', '你为了将前世的医学耐心用于今生的详细诊断而来。', '你为了将前世的治愈知识用于今生的治疗而来。', '你为了将前世的医学精度用于今生的准确性而来。', '你为了将前世的治愈本能用于今生的直觉而来。', '你为了将前世的医学责任用于今生的拯救生命而来。', '你为了将前世的治愈教学用于今生的指导而来。', '你为了将前世的医学掌握用于今生的基础建设而来。', '你为了将前世的治愈知识用于今生的创新而来。'],
        'zh-TW': ['你為了將前世的醫學技能用於今生的治愈和慈悲而來。', '你為了將前世的治愈智慧用於今生的服務和關懷而來。', '你為了將前世的醫學耐心用於今生的詳細診斷而來。', '你為了將前世的治愈知識用於今生的治療而來。', '你為了將前世的醫學精度用於今生的準確性而來。', '你為了將前世的治愈本能用於今生的直覺而來。', '你為了將前世的醫學責任用於今生的拯救生命而來。', '你為了將前世的治愈教學用於今生的指導而來。', '你為了將前世的醫學掌握用於今生的基礎建設而來。', '你為了將前世的治愈知識用於今生的創新而來。'],
        vi: ['Bạn đến để sử dụng kỹ năng y học từ kiếp trước trong chữa lành và lòng từ bi.', 'Bạn trở lại để áp dụng trí tuệ chữa lành vào phục vụ và chăm sóc.', 'Bạn đến để sử dụng sự kiên nhẫn y học cho chẩn đoán chi tiết.', 'Bạn trở lại để sử dụng kiến thức chữa lành cho điều trị.', 'Bạn đến để sử dụng độ chính xác y học cho sự chính xác.', 'Bạn trở lại để sử dụng bản năng chữa lành cho trực giác.', 'Bạn đến để sử dụng trách nhiệm y học cho cứu sống.', 'Bạn trở lại để sử dụng giảng dạy chữa lành cho hướng dẫn.', 'Bạn đến để sử dụng sự thành thạo y học cho xây dựng nền tảng.', 'Bạn trở lại để sử dụng kiến thức chữa lành cho đổi mới.'],
        id: ['Anda datang untuk menggunakan keterampilan medis masa lalu dalam penyembuhan dan belas kasihan.', 'Anda kembali untuk menerapkan kebijaksanaan penyembuhan pada pelayanan dan perawatan.', 'Anda datang untuk menggunakan kesabaran medis untuk diagnosis detail.', 'Anda kembali untuk menggunakan pengetahuan penyembuhan untuk pengobatan.', 'Anda datang untuk menggunakan presisi medis untuk akurasi.', 'Anda kembali untuk menggunakan insting penyembuhan untuk intuisi.', 'Anda datang untuk menggunakan tanggung jawab medis untuk menyelamatkan nyawa.', 'Anda kembali untuk menggunakan pengajaran penyembuhan untuk bimbingan.', 'Anda datang untuk menggunakan penguasaan medis untuk membangun fondasi.', 'Anda kembali untuk menggunakan pengetahuan penyembuhan untuk inovasi.']
      },
      lifeCount: {
        en: ['This is your 25th reincarnation.', 'You have lived a total of 32 lives so far.', 'This life is your 23rd experience.', 'You have reincarnated 29 times up to this life.', 'This life follows your 24th past life.', 'You have lived 35 lives so far.', 'This is your 26th life.', 'You have reincarnated 31 times up to this life.', 'This life is a new beginning after your 27th past life.', 'You have built medical experience through 38 lives.'],
        ja: ['これはあなたの25回目の転生です。', 'これまでに合計32回の人生を生きました。', '今生は23回目の経験です。', '今生までに29回転生しました。', '今生は24番目の前世の後に続きます。', 'これまでに35回の人生を生きました。', '今生は26回目の人生です。', '今生までに31回転生しました。', '今生は27番目の前世を経た新たな始まりです。', 'これまでに38回の人生で医学の経験を積みました。'],
        'zh-CN': ['这是你的第25次转生。', '截至目前你总共经历了32次人生。', '今生是你的第23次体验。', '到今生为止你已经转生了29次。', '今生延续自你的第24次前世。', '截至目前你已经经历了35次人生。', '今生是你的第26次人生。', '到今生为止你已经转生了31次。', '今生是你第27次前世后的新开始。', '通过38次人生你积累了医学经验。'],
        'zh-TW': ['這是你的第25次轉生。', '截至目前你總共經歷了32次人生。', '今生是你的第23次體驗。', '到今生為止你已經轉生了29次。', '今生延續自你的第24次前世。', '截至目前你已經經歷了35次人生。', '今生是你的第26次人生。', '到今生為止你已經轉生了31次。', '今生是你第27次前世後的新開始。', '通過38次人生你積累了醫學經驗。'],
        vi: ['Đây là lần tái sinh thứ 25 của bạn.', 'Bạn đã sống tổng cộng 32 kiếp cho đến nay.', 'Kiếp này là trải nghiệm thứ 23 của bạn.', 'Bạn đã tái sinh 29 lần đến kiếp này.', 'Kiếp này tiếp nối sau kiếp trước thứ 24 của bạn.', 'Bạn đã sống 35 kiếp cho đến nay.', 'Đây là kiếp thứ 26 của bạn.', 'Bạn đã tái sinh 31 lần đến kiếp này.', 'Kiếp này là khởi đầu mới sau kiếp trước thứ 27 của bạn.', 'Bạn đã tích lũy kinh nghiệm y học qua 38 kiếp.'],
        id: ['Ini adalah reinkarnasi ke-25 Anda.', 'Anda telah menjalani total 32 kehidupan sejauh ini.', 'Kehidupan ini adalah pengalaman ke-23 Anda.', 'Anda telah bereinkarnasi 29 kali hingga kehidupan ini.', 'Kehidupan ini mengikuti kehidupan lampau ke-24 Anda.', 'Anda telah menjalani 35 kehidupan sejauh ini.', 'Ini adalah kehidupan ke-26 Anda.', 'Anda telah bereinkarnasi 31 kali hingga kehidupan ini.', 'Kehidupan ini adalah awal baru setelah kehidupan lampau ke-27 Anda.', 'Anda telah membangun pengalaman medis melalui 38 kehidupan.']
      }
    }
  }
};