/**
 * 나의 '먹방' 스타일 진단 — 12문항 이미지 2지선다, A=0 B=1, 총점 0~12 → 6유형
 * 썸네일: p3_test_mukbang_style_diagnosis.webp
 * 답변 이미지: p3_test_mukbang_style_diagnosis_q{n}a~b.webp (12×2=24장)
 */

type Locale = 'ko' | 'en' | 'ja' | 'zh-CN' | 'zh-TW' | 'vi' | 'id';
type ML = Record<Locale, string>;

function L(m: ML): Record<string, string> {
  return m;
}

const IMG = (n: number, choice: 'a' | 'b') =>
  `p3_test_mukbang_style_diagnosis_q${n}${choice}.webp`;

export interface Phase3MukbangStyleDiagnosisQuestion {
  id: number;
  question: Record<string, string>;
  options: { image: string; label: Record<string, string>; score: number }[];
}

export interface Phase3MukbangStyleDiagnosisResult {
  type: string;
  emoji: string;
  title: Record<string, string>;
  shortDescription: Record<string, string>;
  description: Record<string, string>;
  mukbangStyle: Record<string, string>;
  mukbangKeywords: Record<string, string>;
  eatingTogether: Record<string, string>;
  foodStrength: Record<string, string>;
  avoidEatingWith?: Record<string, string>;
  communityStance: Record<string, string>;
  oneLiner?: Record<string, string>;
  shareMessage: Record<string, string>;
}

export function calculatePhase3MukbangStyleDiagnosisResult(scores: number[]): string {
  const total = scores.reduce((a, b) => a + (b ?? 0), 0);
  if (total <= 1) return 'Type1';
  if (total <= 3) return 'Type2';
  if (total <= 6) return 'Type3';
  if (total <= 9) return 'Type4';
  if (total <= 11) return 'Type5';
  return 'Type6';
}

export const phase3MukbangStyleDiagnosisQuestions: Phase3MukbangStyleDiagnosisQuestion[] = [
  {
    id: 1,
    question: L({
      ko: '탕수육이 나왔다. 나는?',
      en: 'Sweet and sour pork arrives. I...',
      ja: '酢豚が出てきた。私は？',
      'zh-CN': '糖醋肉端上来了。我是？',
      'zh-TW': '糖醋肉上桌了。我是？',
      vi: 'Thịt heo chua ngọt được mang ra. Mình là kiểu...?',
      id: 'Babi asam manis datang. Aku tipe yang...?',
    }),
    options: [
      {
        image: IMG(1, 'a'),
        label: L({
          ko: '소스를 따로 덜어서 먹기 직전에 찍어 먹는 장면',
          en: 'A scene of pouring the sauce into a separate dish and dipping each piece right before eating',
          ja: 'ソースを別の器に入れて、食べる直前につけて食べるシーン',
          'zh-CN': '把酱汁单独盛出来，吃之前才蘸一下的场景',
          'zh-TW': '把醬汁另外裝、快吃之前才沾一下的畫面',
          vi: 'Cảnh chấm nước sốt riêng ra bát, chấm ngay trước khi ăn',
          id: 'Scene menuang saus ke wadah terpisah dan mencelupkannya tepat sebelum makan',
        }),
        score: 0,
      },
      {
        image: IMG(1, 'b'),
        label: L({
          ko: '탕수육 위에 소스를 전부 부어버린 장면',
          en: 'A scene of pouring the entire sauce directly over the sweet and sour pork',
          ja: '酢豚の上にソースを全部かけてしまうシーン',
          'zh-CN': '把酱汁全部倒在糖醋肉上的场景',
          'zh-TW': '把醬汁整個倒在糖醋肉上的畫面',
          vi: 'Cảnh đổ hết nước sốt lên trên thịt heo chua ngọt',
          id: 'Scene menuang seluruh saus langsung ke atas babi asam manis',
        }),
        score: 1,
      },
    ],
  },
  {
    id: 2,
    question: L({
      ko: '라면을 끓인다. 스프는?',
      en: 'Cooking ramen. What about the soup base?',
      ja: 'ラーメンを作る。スープの素は？',
      'zh-CN': '煮泡面。汤料放多少？',
      'zh-TW': '煮泡麵。湯包放多少？',
      vi: 'Nấu mì gói. Còn gói súp thì sao?',
      id: 'Memasak mi instan. Bagaimana dengan bumbunya?',
    }),
    options: [
      {
        image: IMG(2, 'a'),
        label: L({
          ko: '스프를 절반만 넣고 순하게 끓인 맑은 빛깔 라면',
          en: 'A scene of a mild, clear-colored ramen made with only half the soup packet',
          ja: 'スープの素を半分だけ入れて、優しい味の透明なラーメン',
          'zh-CN': '只放一半汤料，煮出清淡颜色的泡面',
          'zh-TW': '只放一半湯包，煮出清淡色澤的泡麵',
          vi: 'Chỉ cho nửa gói súp, nấu ra tô mì màu trong nhạt, dịu vị',
          id: 'Scene mi instan berwarna bening lembut, hanya pakai separuh bumbu',
        }),
        score: 0,
      },
      {
        image: IMG(2, 'b'),
        label: L({
          ko: '스프에 고춧가루까지 추가해 새빨간 불닭 라면',
          en: 'A scene of a fiery red fire-noodle-style ramen with extra red pepper flakes added to the soup',
          ja: 'スープに唐辛子粉まで加えた真っ赤な激辛ラーメン',
          'zh-CN': '在汤料里再加辣椒粉，煮成火红的超辣泡面',
          'zh-TW': '湯包裡還加了辣椒粉，煮成火紅的超辣泡麵',
          vi: 'Cho thêm cả bột ớt vào gói súp, nấu ra tô mì đỏ rực siêu cay',
          id: 'Scene mi instan merah menyala super pedas, bumbu ditambah bubuk cabai',
        }),
        score: 1,
      },
    ],
  },
  {
    id: 3,
    question: L({
      ko: '삼겹살을 먹는다. 나의 방식은?',
      en: 'Eating pork belly (samgyeopsal). My style is...',
      ja: 'サムギョプサルを食べる。私の食べ方は？',
      'zh-CN': '吃烤五花肉。我的方式是？',
      'zh-TW': '吃烤五花肉。我的吃法是？',
      vi: 'Ăn thịt ba chỉ nướng. Cách ăn của mình là?',
      id: 'Makan samgyeopsal (perut babi panggang). Caraku makan adalah...?',
    }),
    options: [
      {
        image: IMG(3, 'a'),
        label: L({
          ko: '깻잎·마늘·쌈장에 정성껏 싸서 한 입에 쏙 넣는 쌈 장면',
          en: 'A scene of carefully wrapping the meat with perilla leaves, garlic, and ssamjang, then popping it into the mouth in one bite',
          ja: 'エゴマの葉・にんにく・サムジャンで丁寧に包んで、一口でぱくっと食べるシーン',
          'zh-CN': '用紫苏叶、蒜和大酱仔细包好，一口塞进嘴里的场景',
          'zh-TW': '用紫蘇葉、大蒜和味噌醬仔細包好，一口塞進嘴裡的畫面',
          vi: 'Cảnh cuốn kỹ với lá tía tô, tỏi, tương ssamjang rồi đưa cả miếng vào miệng',
          id: 'Scene membungkus dengan hati-hati menggunakan daun perilla, bawang putih, dan ssamjang, lalu memasukkannya sekaligus ke mulut',
        }),
        score: 0,
      },
      {
        image: IMG(3, 'b'),
        label: L({
          ko: '쌈 없이 구운 고기를 바로 입에 넣고 된장찌개에 밥 말아 함께 먹는 장면',
          en: 'A scene of eating the grilled meat straight, no wrap, alongside rice mixed into doenjang stew',
          ja: '包まずに焼いた肉をそのまま口に入れ、テンジャンチゲにご飯を入れて一緒に食べるシーン',
          'zh-CN': '不包生菜直接吃烤肉，配着大酱汤泡饭一起吃的场景',
          'zh-TW': '不包生菜直接吃烤肉，配大醬湯泡飯一起吃的畫面',
          vi: 'Cảnh ăn thịt nướng trực tiếp không cuốn, ăn kèm cơm chan canh tương đậu',
          id: 'Scene makan daging panggang langsung tanpa dibungkus, sambil menyantap nasi dicampur sup doenjang',
        }),
        score: 1,
      },
    ],
  },
  {
    id: 4,
    question: L({
      ko: '국과 밥이 나왔다. 나는?',
      en: 'Soup and rice arrive. I...',
      ja: 'スープとご飯が出てきた。私は？',
      'zh-CN': '汤和米饭端上来了。我是？',
      'zh-TW': '湯跟飯上桌了。我是？',
      vi: 'Canh và cơm được mang ra. Mình là?',
      id: 'Sup dan nasi datang. Aku tipe yang...?',
    }),
    options: [
      {
        image: IMG(4, 'a'),
        label: L({
          ko: '국과 밥을 따로 먹는 장면. 밥 한 숟가락, 국 한 숟가락 번갈아',
          en: 'A scene of eating soup and rice separately, alternating one spoonful of rice and one of soup',
          ja: 'スープとご飯を別々に食べるシーン。ご飯一口、スープ一口を交互に',
          'zh-CN': '汤和饭分开吃的场景。一勺饭一勺汤轮流吃',
          'zh-TW': '湯跟飯分開吃的畫面，一口飯一口湯輪流吃',
          vi: 'Cảnh ăn canh và cơm riêng, một muỗng cơm rồi một muỗng canh xen kẽ',
          id: 'Scene makan sup dan nasi secara terpisah, bergantian satu sendok nasi dan satu sendok sup',
        }),
        score: 0,
      },
      {
        image: IMG(4, 'b'),
        label: L({
          ko: '국에 밥을 말아버린 장면. 뚝배기에 밥이 퐁당 빠진 순간',
          en: 'A scene of pouring rice right into the soup, the moment rice plops into the earthenware pot',
          ja: 'スープにご飯を入れてしまうシーン。土鍋にご飯がぽとんと落ちる瞬間',
          'zh-CN': '把饭直接倒进汤里的场景。米饭扑通掉进砂锅的瞬间',
          'zh-TW': '把飯直接倒進湯裡的畫面，飯撲通掉進砂鍋的瞬間',
          vi: 'Cảnh đổ cơm luôn vào canh, khoảnh khắc cơm rơi ùm vào nồi đất',
          id: "Scene menuang nasi langsung ke dalam sup, momen nasi jatuh 'plup' ke dalam panci tanah",
        }),
        score: 1,
      },
    ],
  },
  {
    id: 5,
    question: L({
      ko: '치킨을 시켰다. 선택은?',
      en: 'Fried chicken is ordered. My choice is...',
      ja: 'チキンを注文した。選択は？',
      'zh-CN': '点了炸鸡。我的选择是？',
      'zh-TW': '點了炸雞。我的選擇是？',
      vi: 'Gọi món gà rán. Mình chọn?',
      id: 'Memesan ayam goreng. Pilihanku adalah...?',
    }),
    options: [
      {
        image: IMG(5, 'a'),
        label: L({
          ko: '바삭한 황금빛 후라이드 치킨 한 조각 클로즈업',
          en: 'A close-up of a crispy, golden piece of plain fried chicken',
          ja: 'カリッとした黄金色のフライドチキンのクローズアップ',
          'zh-CN': '香脆金黄的原味炸鸡特写',
          'zh-TW': '香脆金黃的原味炸雞特寫',
          vi: 'Cận cảnh miếng gà rán vàng giòn vị nguyên bản',
          id: 'Close-up ayam goreng original berwarna emas yang renyah',
        }),
        score: 0,
      },
      {
        image: IMG(5, 'b'),
        label: L({
          ko: '빨갛게 양념이 발린 양념치킨 클로즈업',
          en: 'A close-up of chicken coated in red, spicy-sweet seasoning sauce',
          ja: '赤いヤンニョムがたっぷりかかったヤンニョムチキンのクローズアップ',
          'zh-CN': '裹满红色调味酱的辣鸡特写',
          'zh-TW': '裹滿紅色調味醬的辣味炸雞特寫',
          vi: 'Cận cảnh miếng gà tẩm sốt cay đỏ rực',
          id: 'Close-up ayam berlumur saus pedas berwarna merah',
        }),
        score: 1,
      },
    ],
  },
  {
    id: 6,
    question: L({
      ko: '떡볶이를 먹는다. 나의 선택은?',
      en: 'Eating tteokbokki. My choice is...',
      ja: 'トッポギを食べる。私の選択は？',
      'zh-CN': '吃炒年糕。我的选择是？',
      'zh-TW': '吃辣炒年糕。我的選擇是？',
      vi: 'Ăn bánh gạo cay tteokbokki. Mình chọn?',
      id: 'Makan tteokbokki. Pilihanku adalah...?',
    }),
    options: [
      {
        image: IMG(6, 'a'),
        label: L({
          ko: '오리지널 빨간 떡볶이. 군더더기 없이 클래식하게',
          en: 'Classic red tteokbokki, no frills, done the traditional way',
          ja: 'オリジナルの赤いトッポギ。シンプルにクラシックに',
          'zh-CN': '原味红色炒年糕，简单又经典',
          'zh-TW': '原味紅色辣炒年糕，簡單又經典',
          vi: 'Tteokbokki đỏ nguyên bản, đơn giản và cổ điển',
          id: 'Tteokbokki merah original, sederhana dan klasik',
        }),
        score: 0,
      },
      {
        image: IMG(6, 'b'),
        label: L({
          ko: '치즈가 듬뿍 올라간 치즈 떡볶이. 늘어나는 치즈와 함께',
          en: 'Cheese tteokbokki piled high with melted cheese, stretching as you pull it',
          ja: 'チーズがたっぷり乗ったチーズトッポギ。伸びるチーズと一緒に',
          'zh-CN': '堆满起司的芝士炒年糕，拉丝十足',
          'zh-TW': '灑滿起司的起司辣炒年糕，牽絲十足',
          vi: 'Tteokbokki phô mai phủ đầy phô mai, kéo sợi khi ăn',
          id: 'Tteokbokki keju yang ditaburi keju berlimpah, molor saat ditarik',
        }),
        score: 1,
      },
    ],
  },
  {
    id: 7,
    question: L({
      ko: '여러 반찬이 나왔다. 나의 식사 방식은?',
      en: 'Several side dishes arrive. My eating style is...',
      ja: 'おかずがいくつも出てきた。私の食べ方は？',
      'zh-CN': '上了好几道小菜。我的吃法是？',
      'zh-TW': '上了好幾道小菜。我的吃法是？',
      vi: 'Nhiều món ăn kèm được mang ra. Cách ăn của mình là?',
      id: 'Beberapa lauk datang. Cara makanku adalah...?',
    }),
    options: [
      {
        image: IMG(7, 'a'),
        label: L({
          ko: '반찬을 하나씩 따로 먹는 장면. 밥과 각 반찬이 섞이지 않게',
          en: 'A scene of eating each side dish separately, keeping rice and each dish from mixing',
          ja: 'おかずを一つずつ別々に食べるシーン。ご飯と各おかずが混ざらないように',
          'zh-CN': '小菜一个一个分开吃的场景，不让米饭和各种小菜混在一起',
          'zh-TW': '小菜一個個分開吃的畫面，不讓飯跟各種小菜混在一起',
          vi: 'Cảnh ăn từng món ăn kèm riêng lẻ, không để cơm và các món trộn vào nhau',
          id: 'Scene makan setiap lauk secara terpisah, agar nasi dan tiap lauk tidak tercampur',
        }),
        score: 0,
      },
      {
        image: IMG(7, 'b'),
        label: L({
          ko: '비빔밥처럼 모든 반찬을 밥에 올려 한꺼번에 비벼 먹는 장면',
          en: 'A scene of piling all the side dishes onto rice like bibimbap and mixing everything together at once',
          ja: 'ビビンバのようにすべてのおかずをご飯に乗せて一気に混ぜて食べるシーン',
          'zh-CN': '像拌饭一样把所有小菜都倒在饭上一起拌着吃的场景',
          'zh-TW': '像拌飯一樣把所有小菜都倒在飯上一起拌著吃的畫面',
          vi: 'Cảnh trộn hết các món ăn kèm vào cơm rồi ăn chung một lần như bibimbap',
          id: 'Scene menuangkan semua lauk ke atas nasi dan mencampurnya sekaligus seperti bibimbap',
        }),
        score: 1,
      },
    ],
  },
  {
    id: 8,
    question: L({
      ko: '맛있는 음식 앞에서 나는?',
      en: 'In front of delicious food, I...',
      ja: '美味しい食べ物を前にして私は？',
      'zh-CN': '面对美味的食物，我是？',
      'zh-TW': '面對美味的食物，我是？',
      vi: 'Trước món ăn ngon, mình là?',
      id: 'Di depan makanan lezat, aku...?',
    }),
    options: [
      {
        image: IMG(8, 'a'),
        label: L({
          ko: '적당량을 예쁘게 담아 음식 사진을 찍는 장면',
          en: 'A scene of plating a modest portion nicely and taking a photo of the food',
          ja: '適量をきれいに盛って写真を撮るシーン',
          'zh-CN': '把适量食物摆得漂漂亮亮然后拍照的场景',
          'zh-TW': '把適量食物擺得漂漂亮亮再拍照的畫面',
          vi: 'Cảnh bày một lượng vừa phải cho đẹp rồi chụp ảnh món ăn',
          id: 'Scene menata makanan secukupnya dengan rapi lalu memotretnya',
        }),
        score: 0,
      },
      {
        image: IMG(8, 'b'),
        label: L({
          ko: '사진 없이 바로 크게 한 입 베어무는 장면',
          en: 'A scene of taking a big bite right away, no photo taken',
          ja: '写真も撮らずにすぐ大きく一口かじるシーン',
          'zh-CN': '不拍照直接大口咬下去的场景',
          'zh-TW': '沒拍照直接大口咬下去的畫面',
          vi: 'Cảnh cắn ngay một miếng to mà không chụp ảnh',
          id: 'Scene langsung menggigit besar tanpa memotret dulu',
        }),
        score: 1,
      },
    ],
  },
  {
    id: 9,
    question: L({
      ko: '외식 자리가 잡혔다. 메뉴 선택은?',
      en: 'A dine-out plan is set. How I choose the menu...',
      ja: '外食の約束が決まった。メニュー選びは？',
      'zh-CN': '外出聚餐定好了。选菜单的方式是？',
      'zh-TW': '外出聚餐定好了。選菜單的方式是？',
      vi: 'Đã hẹn đi ăn ngoài. Cách chọn quán là?',
      id: 'Rencana makan di luar sudah dibuat. Cara memilih menu?',
    }),
    options: [
      {
        image: IMG(9, 'a'),
        label: L({
          ko: '미리 맛집을 검색하고 메뉴를 정해온 장면. 리뷰 캡처본 들고',
          en: 'A scene of having already searched for a great restaurant and decided the menu in advance, holding screenshots of reviews',
          ja: '事前に人気店を調べてメニューを決めておくシーン。レビューのスクショを持って',
          'zh-CN': '提前搜好网红餐厅、定好菜单，还带着评论截图的场景',
          'zh-TW': '事先搜好人氣餐廳、決定好菜單，還帶著評論截圖的畫面',
          vi: 'Cảnh đã tìm quán ngon và chọn sẵn món từ trước, cầm cả ảnh chụp review',
          id: 'Scene sudah mencari restoran enak dan menentukan menu dari awal, sambil membawa screenshot ulasan',
        }),
        score: 0,
      },
      {
        image: IMG(9, 'b'),
        label: L({
          ko: '끌리는 간판 보이면 바로 들어가는 즉흥 외식 장면',
          en: 'A scene of spontaneously walking into whichever sign catches your eye',
          ja: '気になる看板を見つけたらすぐ入る、即興の外食シーン',
          'zh-CN': '看到顺眼的招牌就直接走进去的即兴聚餐场景',
          'zh-TW': '看到順眼的招牌就直接走進去的即興聚餐畫面',
          vi: 'Cảnh thấy tấm bảng hiệu nào bắt mắt là vào ăn ngay, ngẫu hứng',
          id: 'Scene langsung masuk begitu melihat plang toko yang menarik, spontan',
        }),
        score: 1,
      },
    ],
  },
  {
    id: 10,
    question: L({
      ko: '좋아하는 음식이 상에 올라왔다. 나는?',
      en: 'A favorite food is on the table. I...',
      ja: '好きな食べ物がテーブルに並んだ。私は？',
      'zh-CN': '喜欢的食物上桌了。我是？',
      'zh-TW': '喜歡的食物上桌了。我是？',
      vi: 'Món ăn yêu thích được bày lên bàn. Mình là?',
      id: 'Makanan favorit tersaji di meja. Aku...?',
    }),
    options: [
      {
        image: IMG(10, 'a'),
        label: L({
          ko: '덜 좋아하는 것부터 먹고 제일 좋아하는 것을 마지막에 남기는 장면',
          en: 'A scene of eating the less-favorite items first and saving the favorite for last',
          ja: 'あまり好きではないものから食べて、一番好きなものを最後に残すシーン',
          'zh-CN': '先吃不太喜欢的，把最喜欢的留到最后吃的场景',
          'zh-TW': '先吃不太喜歡的，把最喜歡的留到最後吃的畫面',
          vi: 'Cảnh ăn món ít thích trước, để món thích nhất lại ăn sau cùng',
          id: 'Scene makan yang kurang disukai dulu, menyisakan yang paling favorit untuk terakhir',
        }),
        score: 0,
      },
      {
        image: IMG(10, 'b'),
        label: L({
          ko: '제일 좋아하는 것을 가장 먼저 집어 먹는 장면',
          en: 'A scene of grabbing the favorite item first, right away',
          ja: '一番好きなものを最初に真っ先に食べるシーン',
          'zh-CN': '第一个就抢先吃最喜欢的那一口的场景',
          'zh-TW': '第一個就搶先吃最喜歡的那一口的畫面',
          vi: 'Cảnh gắp món yêu thích nhất ăn ngay đầu tiên',
          id: 'Scene langsung mengambil yang paling favorit lebih dulu',
        }),
        score: 1,
      },
    ],
  },
  {
    id: 11,
    question: L({
      ko: '식사 중 나는?',
      en: 'During a meal, I...',
      ja: '食事中、私は？',
      'zh-CN': '吃饭的时候我？',
      'zh-TW': '吃飯的時候我？',
      vi: 'Trong khi ăn, mình là?',
      id: 'Saat makan, aku...?',
    }),
    options: [
      {
        image: IMG(11, 'a'),
        label: L({
          ko: '함께 먹으며 대화가 끊이지 않는 장면. 음식보다 이야기가 더 많은 식사',
          en: 'A scene of eating together with nonstop conversation, a meal with more talking than eating',
          ja: '一緒に食べながら会話が絶えないシーン。食べ物よりも話のほうが多い食事',
          'zh-CN': '一边吃一边聊个不停的场景，一顿聊天比吃饭还多的饭局',
          'zh-TW': '一邊吃一邊聊不停的畫面，聊天比吃飯還多的一頓飯',
          vi: 'Cảnh vừa ăn vừa nói chuyện không ngớt, bữa ăn nói nhiều hơn ăn',
          id: 'Scene makan sambil terus mengobrol tanpa henti, obrolan lebih banyak daripada makanannya',
        }),
        score: 0,
      },
      {
        image: IMG(11, 'b'),
        label: L({
          ko: '말없이 음식에만 집중하는 장면. 대화 없이 먹는 것만 하는 식사',
          en: 'A scene of silently focusing only on the food, a meal with no conversation, just eating',
          ja: '何も言わずに食べることだけに集中するシーン。会話なしでただ食べるだけの食事',
          'zh-CN': '一言不发只专注吃饭的场景，没有对话只顾吃饭的饭局',
          'zh-TW': '一言不發只專心吃飯的畫面，沒有對話只顧吃飯的一頓飯',
          vi: 'Cảnh im lặng chỉ tập trung ăn, bữa ăn không nói chuyện, chỉ ăn',
          id: 'Scene diam dan hanya fokus pada makanan, tanpa obrolan, hanya makan',
        }),
        score: 1,
      },
    ],
  },
  {
    id: 12,
    question: L({
      ko: '식사가 거의 끝났다. 그릇 상태는?',
      en: 'The meal is almost over. What does the bowl look like?',
      ja: '食事がほぼ終わった。器の状態は？',
      'zh-CN': '饭快吃完了。碗的状态是？',
      'zh-TW': '飯快吃完了。碗的狀態是？',
      vi: 'Bữa ăn gần kết thúc. Tình trạng cái bát là?',
      id: 'Makan hampir selesai. Bagaimana kondisi mangkuknya?',
    }),
    options: [
      {
        image: IMG(12, 'a'),
        label: L({
          ko: '조금 남긴 깔끔한 그릇. 과식하지 않고 적당히 먹은 흔적',
          en: 'A neat bowl with a little left over, a sign of not overeating and eating just the right amount',
          ja: '少し残したきれいな器。食べ過ぎずに適量食べた跡',
          'zh-CN': '剩一点点的干净碗，是没有吃太多、刚好吃饱的痕迹',
          'zh-TW': '剩一點點的乾淨碗，是沒有吃太多、剛好吃飽的痕跡',
          vi: 'Bát sạch sẽ còn thừa lại một chút, dấu hiệu ăn vừa đủ không quá no',
          id: 'Mangkuk rapi dengan sedikit sisa, tanda tidak makan berlebihan dan makan secukupnya',
        }),
        score: 0,
      },
      {
        image: IMG(12, 'b'),
        label: L({
          ko: '국물까지 싹 비운 그릇. 숟가락으로 바닥을 긁어낸 흔적',
          en: 'A bowl licked clean down to the broth, scraped to the bottom with the spoon',
          ja: 'スープまで完全に空にした器。スプーンで底までこすり取った跡',
          'zh-CN': '连汤都喝得一干二净的碗，用勺子把碗底刮得干干净净的痕迹',
          'zh-TW': '連湯都喝得一乾二淨的碗，用湯匙把碗底刮得乾乾淨淨的痕跡',
          vi: 'Bát sạch bong cả nước canh, dấu vết muỗng cạo tận đáy',
          id: 'Mangkuk bersih licin sampai kuahnya, bekas dikerok sampai dasar dengan sendok',
        }),
        score: 1,
      },
    ],
  },
];

export const phase3MukbangStyleDiagnosisResults: Phase3MukbangStyleDiagnosisResult[] = [
  {
    type: 'Type1',
    emoji: '🍽️',
    title: L({
      ko: '음식도 예술이다, 정갈한 미식가형 🍽️',
      en: 'Food Is Art Too, the Refined Gourmet Type 🍽️',
      ja: '食事も芸術だ、上品な美食家タイプ 🍽️',
      'zh-CN': '吃饭也是艺术，精致美食家型 🍽️',
      'zh-TW': '吃飯也是藝術，精緻美食家型 🍽️',
      vi: 'Ăn cũng là nghệ thuật, kiểu Người sành ăn tinh tế 🍽️',
      id: 'Makan Juga Seni, Tipe Gourmet Elegan 🍽️',
    }),
    shortDescription: L({
      ko: '당신에게 음식은 경험입니다. 먹는 것만큼 먹는 방식도 중요합니다.',
      en: 'To you, food is an experience. How you eat matters as much as what you eat.',
      ja: 'あなたにとって食事は経験です。食べることと同じくらい、食べ方も大切です。',
      'zh-CN': '对你来说，吃饭是一种体验。怎么吃跟吃什么一样重要。',
      'zh-TW': '對你來說，吃飯是一種體驗。怎麼吃跟吃什麼一樣重要。',
      vi: 'Với bạn, ăn uống là một trải nghiệm. Cách ăn quan trọng không kém gì món ăn.',
      id: 'Bagimu, makan adalah sebuah pengalaman. Cara makan sama pentingnya dengan apa yang dimakan.',
    }),
    description: L({
      ko: '찍먹 고집하고, 음식 사진 먼저 찍고, 반찬 하나씩 따로 먹고, 맛집 미리 검색해서 갑니다. 음식의 본래 맛을 섬세하게 느끼는 타입입니다. 테이블 세팅이 중요하고 음식 비주얼에도 민감합니다.',
      en: "You insist on dipping sauce separately, take food photos first, eat each side dish separately, and search for great restaurants in advance. You're the type who delicately savors the true flavor of food. Table setting matters to you, and you're sensitive to how food looks.",
      ja: 'ソースは別につけて食べることにこだわり、まず写真を撮り、おかずは一つずつ別々に食べ、事前に人気店を調べてから行きます。食べ物本来の味を繊細に感じ取るタイプです。テーブルセッティングを大切にし、料理の見た目にも敏感です。',
      'zh-CN': '坚持酱汁单独蘸着吃，先拍照再吃，小菜一个个分开吃，出门前先搜好餐厅。你是能细细品味食物原味的类型，很在意餐桌摆设，对食物的视觉呈现也很敏感。',
      'zh-TW': '堅持醬汁另外沾著吃，先拍照才吃，小菜一個個分開吃，出門前先搜好餐廳。你是能細細品味食物原味的類型，很在意餐桌擺設，對食物的視覺呈現也很敏感。',
      vi: 'Bạn khăng khăng chấm sốt riêng, chụp ảnh món ăn trước tiên, ăn từng món ăn kèm riêng lẻ, và tìm quán ngon từ trước khi đi. Bạn là kiểu người cảm nhận tinh tế hương vị nguyên bản của món ăn. Bạn coi trọng cách bày bàn ăn và nhạy cảm với hình thức trình bày món ăn.',
      id: 'Kamu bersikeras mencelup saus secara terpisah, memotret makanan dulu, makan setiap lauk secara terpisah, dan mencari restoran enak sebelum pergi. Kamu adalah tipe yang menikmati rasa asli makanan secara mendalam. Penataan meja penting bagimu, dan kamu sensitif terhadap tampilan visual makanan.',
    }),
    mukbangStyle: L({
      ko: '정갈한 미식가형 🍽️',
      en: 'Refined Gourmet Type 🍽️',
      ja: '上品な美食家タイプ 🍽️',
      'zh-CN': '精致美食家型 🍽️',
      'zh-TW': '精緻美食家型 🍽️',
      vi: 'Người sành ăn tinh tế 🍽️',
      id: 'Gourmet Elegan 🍽️',
    }),
    mukbangKeywords: L({
      ko: '섬세함·계획성·본연의 맛·플레이팅',
      en: 'Delicacy, planning, true flavor, plating',
      ja: '繊細さ、計画性、素材の味、盛り付け',
      'zh-CN': '细腻、计划性、原汁原味、摆盘',
      'zh-TW': '細膩、計畫性、原汁原味、擺盤',
      vi: 'Tinh tế, có kế hoạch, hương vị nguyên bản, cách trình bày',
      id: 'Ketelitian, terencana, rasa asli, penataan',
    }),
    eatingTogether: L({
      ko: '메뉴 선택에 의견이 뚜렷하고 음식 순서가 있는 편',
      en: 'Has clear opinions on menu choices and tends to eat in a set order',
      ja: 'メニュー選びに明確な意見があり、食べる順番を大事にする方',
      'zh-CN': '对点菜有明确主见，喜欢按顺序吃饭的人',
      'zh-TW': '對點菜有明確主見，喜歡按順序吃飯的人',
      vi: 'Có ý kiến rõ ràng khi chọn món và thường ăn theo một trình tự nhất định',
      id: 'Punya pendapat jelas soal pilihan menu dan cenderung makan dengan urutan tertentu',
    }),
    foodStrength: L({
      ko: '음식 하나하나를 깊이 음미하는 능력',
      en: 'The ability to deeply savor and appreciate every single dish',
      ja: '一つひとつの料理を深く味わう能力',
      'zh-CN': '能细细品味每一道菜的能力',
      'zh-TW': '能細細品味每一道菜的能力',
      vi: 'Khả năng thưởng thức sâu sắc từng món ăn một',
      id: 'Kemampuan menikmati setiap hidangan secara mendalam',
    }),
    avoidEatingWith: L({
      ko: '무조건 부어버리고 다 섞어버리는 만렙 먹방왕 앞에서 멘붕',
      en: 'Panics in front of a max-level mukbang king who pours everything and mixes it all together without hesitation',
      ja: '何でもかけて全部混ぜてしまう豪快な大食い王を前にすると戸惑う',
      'zh-CN': '看到那种什么都往上一倒、全部搅在一起的满级大胃王会崩溃',
      'zh-TW': '看到那種什麼都往上倒、全部攪在一起的滿等大胃王會崩潰',
      vi: 'Hoảng loạn trước một cao thủ ăn uống chuyên đổ hết mọi thứ và trộn lẫn tất cả',
      id: 'Panik di depan raja makan level maksimal yang menuang semuanya dan mencampur semuanya tanpa ragu',
    }),
    communityStance: L({
      ko: '찍먹 진영 핵심 인원. 부먹러와 절대 타협 없음',
      en: "Core member of the dip-eating camp. Absolutely no compromise with pour-eaters",
      ja: 'つけ派の中心人物。かけ派とは絶対に譲らない',
      'zh-CN': '蘸酱派核心成员，绝不和倒酱派妥协',
      'zh-TW': '沾醬派核心成員，絕不跟倒醬派妥協',
      vi: 'Thành viên nòng cốt phe chấm sốt riêng. Không bao giờ nhượng bộ phe đổ sốt',
      id: 'Anggota inti kubu celup saus. Tidak pernah berkompromi dengan kubu tuang saus',
    }),
    shareMessage: L({
      ko: '먹방 스타일: 정갈한 미식가형 🍽️ 찍먹 고집하고 음식 사진 먼저 찍는 유형... 부먹러들 이해 불가 ㅋㅋ → 너는 어떤 먹방 스타일이야? 찍먹 vs 부먹 논쟁 시작해봐',
      en: "Mukbang style: Refined Gourmet Type 🍽️ The type who insists on dipping sauce separately and takes food photos first... pour-eaters just don't get it lol → What's your mukbang style? Start the dip vs pour debate",
      ja: '食べ方タイプ：上品な美食家タイプ 🍽️ ソースは別につけて、まず写真を撮るタイプ…かけ派には理解できないらしい(笑) → あなたはどんな食べ方タイプ？つけ派 vs かけ派、論争スタート',
      'zh-CN': '干饭风格：精致美食家型 🍽️ 坚持蘸酱吃、先拍照才吃的类型…倒酱派表示无法理解 → 你是什么干饭风格？蘸酱 vs 倒酱大战开始',
      'zh-TW': '吃飯風格：精緻美食家型 🍽️ 堅持沾醬吃、先拍照才吃的類型…倒醬派表示無法理解 → 你是什麼吃飯風格？沾醬 vs 倒醬大戰開始',
      vi: 'Kiểu ăn uống: Người sành ăn tinh tế 🍽️ Kiểu khăng khăng chấm sốt riêng và chụp ảnh trước khi ăn... phe đổ sốt chắc không hiểu được đâu 😆 → Bạn thuộc kiểu ăn uống nào? Bắt đầu tranh luận chấm sốt vs đổ sốt thôi',
      id: 'Gaya makan: Gourmet Elegan 🍽️ Tipe yang bersikeras mencelup saus dan memotret dulu... kubu tuang saus pasti nggak ngerti 😂 → Kamu tipe gaya makan apa? Yuk mulai debat celup vs tuang saus',
    }),
  },
  {
    type: 'Type2',
    emoji: '🌸',
    title: L({
      ko: '먹스타그램이 곧 나다, 감성 소식좌형 🌸',
      en: 'Foodstagram Is Who I Am, the Sentimental Light Eater Type 🌸',
      ja: 'フーディグラムこそ私、感性派の少食タイプ 🌸',
      'zh-CN': '美食博主本人，感性小鸟胃型 🌸',
      'zh-TW': '美食部落客本人，感性小鳥胃型 🌸',
      vi: 'Foodstagram chính là tôi, kiểu Ăn ít đầy cảm xúc 🌸',
      id: 'Foodstagram Adalah Diriku, Tipe Pemakan Sedikit Sentimental 🌸',
    }),
    shortDescription: L({
      ko: '먹는 것만큼 기록하는 것도 중요합니다. 음식 사진은 필수입니다.',
      en: 'Recording your meal matters as much as eating it. A food photo is a must.',
      ja: '食べることと同じくらい記録することも大切です。食べ物の写真は必須です。',
      'zh-CN': '记录跟吃饭一样重要，拍照是必须的。',
      'zh-TW': '記錄跟吃飯一樣重要，拍照是必須的。',
      vi: 'Ghi lại khoảnh khắc quan trọng không kém gì việc ăn. Chụp ảnh món ăn là điều bắt buộc.',
      id: 'Mendokumentasikan sama pentingnya dengan makan. Foto makanan itu wajib.',
    }),
    description: L({
      ko: '음식 사진 꼭 찍고, 적당히 먹고 남기고, 분위기 좋은 맛집을 미리 검색합니다. 음식의 맛보다 경험과 감성을 중요시하는 타입입니다. 먹스타그램 피드가 예쁜 편입니다.',
      en: "You always take a food photo, eat a moderate amount and leave some behind, and search in advance for restaurants with a nice atmosphere. You value the experience and mood over the taste itself. Your foodstagram feed tends to look pretty.",
      ja: '必ず写真を撮り、適量食べて少し残し、雰囲気の良いお店を事前に検索します。味そのものより経験や雰囲気を大切にするタイプです。フーディグラムのフィードがきれいな方です。',
      'zh-CN': '一定先拍照，吃适量后会留一些，会提前搜氛围好的餐厅。比起味道本身，更重视体验和氛围，美食博主的feed通常拍得很好看。',
      'zh-TW': '一定先拍照，吃適量後會留一些，會提前搜氛圍好的餐廳。比起味道本身，更重視體驗和氛圍，美食版面通常拍得很好看。',
      vi: 'Bạn luôn chụp ảnh món ăn, ăn một lượng vừa phải và để lại một ít, và tìm trước những quán có không gian đẹp. Bạn coi trọng trải nghiệm và cảm xúc hơn là vị món ăn. Feed foodstagram của bạn thường rất đẹp.',
      id: 'Kamu selalu memotret makanan dulu, makan secukupnya dan menyisakan sedikit, serta mencari restoran dengan suasana bagus sebelumnya. Kamu lebih mengutamakan pengalaman dan suasana dibanding rasa itu sendiri. Feed foodstagram-mu biasanya terlihat cantik.',
    }),
    mukbangStyle: L({
      ko: '감성 소식좌형 🌸',
      en: 'Sentimental Light Eater Type 🌸',
      ja: '感性派の少食タイプ 🌸',
      'zh-CN': '感性小鸟胃型 🌸',
      'zh-TW': '感性小鳥胃型 🌸',
      vi: 'Ăn ít đầy cảm xúc 🌸',
      id: 'Pemakan Sedikit Sentimental 🌸',
    }),
    mukbangKeywords: L({
      ko: '감성·기록·분위기·소식',
      en: 'Sentiment, recording, atmosphere, light eating',
      ja: '感性、記録、雰囲気、少食',
      'zh-CN': '感性、记录、氛围、小食量',
      'zh-TW': '感性、記錄、氛圍、小食量',
      vi: 'Cảm xúc, ghi lại, không gian, ăn ít',
      id: 'Sentimental, dokumentasi, suasana, porsi kecil',
    }),
    eatingTogether: L({
      ko: '음식 나오면 사진 먼저. "잠깐, 사진 찍고"',
      en: 'Photo first when the food arrives. "Wait, let me take a picture"',
      ja: '食べ物が来たら写真が先。「ちょっと待って、写真撮るから」',
      'zh-CN': '食物一上桌先拍照，「等一下，先拍张照」',
      'zh-TW': '食物一上桌先拍照，「等一下，先拍張照」',
      vi: 'Món ăn vừa lên bàn là chụp ảnh trước. "Khoan đã, để chụp ảnh cái"',
      id: 'Begitu makanan datang, foto dulu. "Tunggu, foto dulu ya"',
    }),
    foodStrength: L({
      ko: '맛집 발굴 능력과 음식 사진 감각',
      en: 'A knack for discovering great restaurants and an eye for food photography',
      ja: '人気店を見つける能力とフードフォトのセンス',
      'zh-CN': '发现网红餐厅的能力和拍美食的手感',
      'zh-TW': '發現人氣餐廳的能力和拍美食的手感',
      vi: 'Khả năng tìm ra quán ngon và cảm quan chụp ảnh món ăn',
      id: 'Kemampuan menemukan restoran enak dan naluri fotografi makanan',
    }),
    avoidEatingWith: L({
      ko: '사진 기다려주지 않고 바로 숟가락 드는 사람',
      en: "People who pick up their spoon right away without waiting for the photo",
      ja: '写真を待たずにすぐスプーンを持つ人',
      'zh-CN': '不等你拍照就直接动勺子的人',
      'zh-TW': '不等你拍照就直接動筷動湯匙的人',
      vi: 'Người không chờ chụp ảnh mà cầm muỗng ăn ngay',
      id: 'Orang yang langsung mengambil sendok tanpa menunggu difoto',
    }),
    communityStance: L({
      ko: '음식 비주얼 논쟁에서 가장 목소리가 큰 유형',
      en: 'The loudest voice in debates about how food should look',
      ja: '食べ物の見た目に関する議論で一番声が大きいタイプ',
      'zh-CN': '在食物摆盘颜值的争论里嗓门最大的类型',
      'zh-TW': '在食物擺盤顏值的爭論裡嗓門最大的類型',
      vi: 'Kiểu người có tiếng nói lớn nhất trong các cuộc tranh luận về hình thức món ăn',
      id: 'Tipe dengan suara paling lantang dalam debat soal tampilan makanan',
    }),
    shareMessage: L({
      ko: '먹방 스타일: 감성 소식좌형 🌸 음식 나오면 사진 먼저인 유형... 먹스타 피드 예쁜 거 인정 → 너는 어떤 먹방 스타일이야?',
      en: "Mukbang style: Sentimental Light Eater Type 🌸 The type who takes a photo first when food arrives... gotta admit that foodstagram feed is pretty → What's your mukbang style?",
      ja: '食べ方タイプ：感性派の少食タイプ 🌸 食べ物が来たら写真が先のタイプ…フーディグラムのフィードがきれいなのは認める → あなたはどんな食べ方タイプ？',
      'zh-CN': '干饭风格：感性小鸟胃型 🌸 食物一上桌就先拍照的类型…不得不承认这美食feed是真的好看 → 你是什么干饭风格？',
      'zh-TW': '吃飯風格：感性小鳥胃型 🌸 食物一上桌就先拍照的類型…不得不承認這美食版面是真的好看 → 你是什麼吃飯風格？',
      vi: 'Kiểu ăn uống: Ăn ít đầy cảm xúc 🌸 Kiểu chụp ảnh trước khi món ăn vừa lên bàn... phải công nhận feed foodstagram đẹp thật → Bạn thuộc kiểu ăn uống nào?',
      id: 'Gaya makan: Pemakan Sedikit Sentimental 🌸 Tipe yang memotret dulu begitu makanan datang... harus diakui feed foodstagram-nya cantik banget → Kamu tipe gaya makan apa?',
    }),
  },
  {
    type: 'Type3',
    emoji: '🥢',
    title: L({
      ko: '상황에 따라 다른, 균형잡힌 먹방러 🥢',
      en: 'It Depends on the Situation, the Balanced Eater Type 🥢',
      ja: '状況によって変わる、バランス派の食事タイプ 🥢',
      'zh-CN': '看情况而定，均衡干饭型 🥢',
      'zh-TW': '看情況而定，均衡吃飯型 🥢',
      vi: 'Tùy tình huống mà thay đổi, kiểu Ăn uống cân bằng 🥢',
      id: 'Tergantung Situasi, Tipe Pemakan Seimbang 🥢',
    }),
    shortDescription: L({
      ko: '찍먹도 되고 부먹도 됩니다. 그날 기분에 따라 다릅니다.',
      en: "Dip or pour, either works for you. It just depends on your mood that day.",
      ja: 'つけてもかけても大丈夫。その日の気分によって違います。',
      'zh-CN': '蘸酱倒酱都行，全看当天的心情。',
      'zh-TW': '沾醬倒醬都行，全看當天的心情。',
      vi: 'Chấm sốt hay đổ sốt đều được. Tùy tâm trạng hôm đó thôi.',
      id: 'Celup atau tuang saus, sama-sama boleh. Tergantung mood hari itu.',
    }),
    description: L({
      ko: '특정 스타일에 강하게 고집이 없고 같이 먹는 사람과 상황에 맞게 즐기는 타입입니다. 가장 같이 밥 먹기 편한 유형입니다. 음식 논쟁에서 중립을 지키려다 양쪽 모두에게 공격받을 수 있습니다.',
      en: "You don't strongly stick to one style and just enjoy the meal in a way that fits the people and situation. You're the easiest type to share a meal with. But trying to stay neutral in food debates can get you attacked from both sides.",
      ja: '特定のスタイルに強くこだわらず、一緒に食べる人や状況に合わせて楽しむタイプです。一緒に食事をするのが一番楽な相手です。食の論争で中立を守ろうとして両方から攻撃されることも。',
      'zh-CN': '对某种风格没有强烈坚持，会根据一起吃饭的人和场合来享受用餐。是最容易一起吃饭的类型，但如果在食物争论中想保持中立，可能会被两边一起怼。',
      'zh-TW': '對某種風格沒有強烈堅持，會依照一起吃飯的人和場合來享受用餐。是最容易一起吃飯的類型，但如果在食物爭論中想保持中立，可能會被兩邊一起罵。',
      vi: 'Bạn không cố chấp với một kiểu ăn cụ thể mà thoải mái tùy theo người ăn cùng và hoàn cảnh. Bạn là kiểu người dễ ăn cùng nhất. Nhưng nếu cố giữ trung lập trong các cuộc tranh luận về ăn uống, bạn có thể bị cả hai phe tấn công.',
      id: 'Kamu tidak terlalu kaku pada satu gaya tertentu dan menikmati makan sesuai orang yang menemani dan situasinya. Kamu adalah tipe paling nyaman untuk makan bersama. Namun, mencoba netral dalam debat soal makanan bisa membuatmu diserang dari kedua kubu.',
    }),
    mukbangStyle: L({
      ko: '균형잡힌 먹방러 🥢',
      en: 'Balanced Eater Type 🥢',
      ja: 'バランス派の食事タイプ 🥢',
      'zh-CN': '均衡干饭型 🥢',
      'zh-TW': '均衡吃飯型 🥢',
      vi: 'Ăn uống cân bằng 🥢',
      id: 'Pemakan Seimbang 🥢',
    }),
    mukbangKeywords: L({
      ko: '유연함·균형·상황적응·무난함',
      en: 'Flexibility, balance, adaptability, easygoing',
      ja: '柔軟さ、バランス、状況適応、無難さ',
      'zh-CN': '灵活、平衡、随机应变、随和',
      'zh-TW': '靈活、平衡、隨機應變、隨和',
      vi: 'Linh hoạt, cân bằng, thích ứng, dễ tính',
      id: 'Fleksibel, seimbang, mudah beradaptasi, santai',
    }),
    eatingTogether: L({
      ko: '"나는 상관없어. 뭐든 좋아"',
      en: '"I don\'t mind either way. Whatever\'s fine"',
      ja: '「私はどっちでもいいよ。何でも好き」',
      'zh-CN': '「我都行，什么都可以」',
      'zh-TW': '「我都可以，什麼都好」',
      vi: '"Tôi sao cũng được. Gì cũng thích"',
      id: '"Aku terserah aja. Apa aja oke"',
    }),
    foodStrength: L({
      ko: '어떤 식사 자리에도 잘 맞는 높은 적응력',
      en: 'High adaptability that fits well into any meal setting',
      ja: 'どんな食事の場にもよく合う高い適応力',
      'zh-CN': '适应任何饭局的超强适应力',
      'zh-TW': '適應任何飯局的超強適應力',
      vi: 'Khả năng thích ứng cao, hợp với mọi bữa ăn',
      id: 'Adaptasi tinggi yang cocok untuk situasi makan apa pun',
    }),
    communityStance: L({
      ko: '"찍먹도 부먹도 다 맛있어요"라고 했다가 둘 다에게 욕먹는 유형',
      en: 'The type who says "both dip and pour are delicious" and ends up getting scolded by both sides',
      ja: '「つけもかけもどっちも美味しい」と言って両方から怒られるタイプ',
      'zh-CN': '说了句「蘸酱倒酱都好吃」结果被两边都骂的类型',
      'zh-TW': '說了句「沾醬倒醬都好吃」結果被兩邊都罵的類型',
      vi: 'Kiểu người nói "chấm sốt hay đổ sốt đều ngon" rồi bị cả hai phe mắng',
      id: 'Tipe yang bilang "celup atau tuang saus sama-sama enak" lalu dimarahi dua kubu sekaligus',
    }),
    shareMessage: L({
      ko: '먹방 스타일: 균형잡힌 먹방러 🥢 찍먹도 부먹도 다 된다는 유형... 커뮤니티 논쟁에서 양쪽 다 공격받는 중립 포지션 ㅋㅋ → 너는 어떤 스타일이야?',
      en: "Mukbang style: Balanced Eater Type 🥢 The type who says both dip and pour are fine... the neutral position that gets attacked from both sides in community debates lol → What's your style?",
      ja: '食べ方タイプ：バランス派の食事タイプ 🥢 つけもかけもどっちもいいというタイプ…論争で両方から攻撃される中立ポジション(笑) → あなたはどんなタイプ？',
      'zh-CN': '干饭风格：均衡干饭型 🥢 蘸酱倒酱都可以的类型…在争论里两边不讨好的中立位置哈哈 → 你是什么风格？',
      'zh-TW': '吃飯風格：均衡吃飯型 🥢 沾醬倒醬都可以的類型…在爭論裡兩邊不討好的中立位置哈哈 → 你是什麼風格？',
      vi: 'Kiểu ăn uống: Ăn uống cân bằng 🥢 Kiểu chấm sốt hay đổ sốt đều được... vị trí trung lập bị cả hai phe tấn công trong tranh luận 😂 → Bạn thuộc kiểu nào?',
      id: 'Gaya makan: Pemakan Seimbang 🥢 Tipe yang bilang celup dan tuang saus sama-sama oke... posisi netral yang diserang dua kubu dalam debat 😆 → Kamu tipe apa?',
    }),
  },
  {
    type: 'Type4',
    emoji: '🔥',
    title: L({
      ko: '먹는 게 낙이다, 야무진 먹보형 🔥',
      en: 'Eating Is Joy, the Hearty Big Eater Type 🔥',
      ja: '食べることが楽しみ、しっかり者の大食いタイプ 🔥',
      'zh-CN': '吃饭是快乐，干脆利落大胃口型 🔥',
      'zh-TW': '吃飯是快樂，乾脆爽快大胃口型 🔥',
      vi: 'Ăn là niềm vui, kiểu Người ăn khỏe dứt khoát 🔥',
      id: 'Makan Adalah Kebahagiaan, Tipe Pemakan Lahap yang Tegas 🔥',
    }),
    shortDescription: L({
      ko: '음식 앞에서 주저함이 없습니다. 일단 먹고 봅니다.',
      en: "You don't hesitate in front of food. You eat first, think later.",
      ja: '食べ物を前にして躊躇しません。まずは食べてから考えます。',
      'zh-CN': '在食物面前从不犹豫，先吃了再说。',
      'zh-TW': '在食物面前從不猶豫，先吃了再說。',
      vi: 'Bạn không hề chần chừ trước món ăn. Cứ ăn trước rồi tính sau.',
      id: 'Kamu tidak pernah ragu di depan makanan. Makan dulu, pikir belakangan.',
    }),
    description: L({
      ko: '좋아하는 것 먼저 집고, 밥에 다 비비고, 매운 것도 잘 먹고, 그릇 싹 비웁니다. 먹는 것 자체를 즐기는 타입입니다. 같이 밥 먹으면 옆에서 보는 사람도 덩달아 맛있어집니다.',
      en: 'You grab your favorite first, mix everything into rice, handle spicy food well, and clean your bowl completely. You genuinely enjoy the act of eating itself. Eating alongside you makes everyone else hungrier too.',
      ja: '好きなものを先に取り、ご飯に全部混ぜ、辛い物もよく食べ、器をきれいに空にします。食べること自体を楽しむタイプです。一緒に食事をすると、隣の人までつられて美味しくなります。',
      'zh-CN': '先夹喜欢的菜，全都拌进饭里，辣的也吃得很香，碗吃得干干净净。真心享受吃饭这件事本身的类型，跟你一起吃饭旁边的人也会跟着觉得香。',
      'zh-TW': '先夾喜歡的菜，全部拌進飯裡，辣的也吃得很香，碗吃得乾乾淨淨。真心享受吃飯這件事本身的類型，跟你一起吃飯旁邊的人也會跟著覺得香。',
      vi: 'Bạn gắp món thích nhất trước, trộn hết vào cơm, ăn cay cũng ngon miệng, và ăn sạch bát. Bạn thật sự thích thú với việc ăn uống. Ăn cùng bạn, người bên cạnh cũng thấy ngon miệng lây.',
      id: 'Kamu mengambil favoritmu lebih dulu, mencampur semuanya dengan nasi, kuat makan pedas, dan menghabiskan mangkuk sampai bersih. Kamu benar-benar menikmati kegiatan makan itu sendiri. Makan bersamamu membuat orang di sebelahmu jadi lebih lahap juga.',
    }),
    mukbangStyle: L({
      ko: '야무진 먹보형 🔥',
      en: 'Hearty Big Eater Type 🔥',
      ja: 'しっかり者の大食いタイプ 🔥',
      'zh-CN': '干脆利落大胃口型 🔥',
      'zh-TW': '乾脆爽快大胃口型 🔥',
      vi: 'Người ăn khỏe dứt khoát 🔥',
      id: 'Pemakan Lahap yang Tegas 🔥',
    }),
    mukbangKeywords: L({
      ko: '맛있게 먹기·야무짐·즐거운 식사·비움',
      en: 'Eating well, hearty appetite, joyful meals, finishing clean',
      ja: '美味しく食べる、しっかり者、楽しい食事、完食',
      'zh-CN': '吃得香、干脆利落、愉快用餐、清盘',
      'zh-TW': '吃得香、乾脆爽快、愉快用餐、清盤',
      vi: 'Ăn ngon miệng, dứt khoát, bữa ăn vui vẻ, ăn sạch',
      id: 'Makan enak, tegas, makan menyenangkan, habis tak bersisa',
    }),
    eatingTogether: L({
      ko: '먼저 잘 먹으면서 "이거 진짜 맛있다"를 연발',
      en: 'Eats well from the start, constantly saying "this is seriously good"',
      ja: '先によく食べながら「これ本当に美味しい」を連発',
      'zh-CN': '先吃得香，还不停说「这个真的太好吃了」',
      'zh-TW': '先吃得香，還不停說「這個真的太好吃了」',
      vi: 'Ăn ngon miệng ngay từ đầu, liên tục nói "cái này ngon thật đấy"',
      id: 'Makan dengan lahap sejak awal sambil terus bilang "ini enak banget"',
    }),
    foodStrength: L({
      ko: '어디서나 맛있게 잘 먹는 능력. 같이 먹는 사람을 행복하게 함',
      en: 'The ability to eat well anywhere with gusto, making everyone around you happy',
      ja: 'どこでも美味しく食べる能力。一緒に食べる人を幸せにする',
      'zh-CN': '无论在哪都能吃得香的能力，能让一起吃饭的人也开心',
      'zh-TW': '無論在哪都能吃得香的能力，能讓一起吃飯的人也開心',
      vi: 'Khả năng ăn ngon miệng ở bất cứ đâu, khiến người ăn cùng cũng vui',
      id: 'Kemampuan makan dengan lahap di mana saja, membuat orang yang makan bersamamu ikut senang',
    }),
    communityStance: L({
      ko: '부먹 진영. 찍먹러 보면 "왜 굳이 번거롭게?"',
      en: 'Firmly in the pour-eating camp. Sees dip-eaters and thinks "why make it so complicated?"',
      ja: 'かけ派。つけ派を見ると「なんでそんな面倒なことを？」',
      'zh-CN': '倒酱派，看到蘸酱派会想「有必要这么麻烦吗？」',
      'zh-TW': '倒醬派，看到沾醬派會想「有必要這麼麻煩嗎？」',
      vi: 'Phe đổ sốt. Thấy phe chấm sốt thì nghĩ "sao phải cầu kỳ vậy?"',
      id: 'Kubu tuang saus. Melihat kubu celup saus dan berpikir "kenapa harus repot begitu?"',
    }),
    shareMessage: L({
      ko: '먹방 스타일: 야무진 먹보형 🔥 좋아하는 것 먼저 집고 그릇 싹 비우는 유형... 부먹파 맞고 불닭 잘 먹는 거 인정 → 너는 어떤 먹방 스타일이야?',
      en: "Mukbang style: Hearty Big Eater Type 🔥 The type who grabs the favorite first and cleans the bowl completely... confirmed pour-eater who can handle fire noodles → What's your mukbang style?",
      ja: '食べ方タイプ：しっかり者の大食いタイプ 🔥 好きなものを先に取って器をきれいに空にするタイプ…かけ派で激辛もよく食べるの認める → あなたはどんな食べ方タイプ？',
      'zh-CN': '干饭风格：干脆利落大胃口型 🔥 先夹喜欢的、碗吃得干干净净的类型…倒酱派还很能吃辣，认了 → 你是什么干饭风格？',
      'zh-TW': '吃飯風格：乾脆爽快大胃口型 🔥 先夾喜歡的、碗吃得乾乾淨淨的類型…倒醬派還很能吃辣，認了 → 你是什麼吃飯風格？',
      vi: 'Kiểu ăn uống: Người ăn khỏe dứt khoát 🔥 Kiểu gắp món thích trước và ăn sạch bát... đúng chuẩn phe đổ sốt lại ăn cay siêu ngon miệng → Bạn thuộc kiểu ăn uống nào?',
      id: 'Gaya makan: Pemakan Lahap yang Tegas 🔥 Tipe yang ambil favorit dulu dan habiskan mangkuk sampai bersih... kubu tuang saus yang jago makan pedas juga, diakui → Kamu tipe gaya makan apa?',
    }),
  },
  {
    type: 'Type5',
    emoji: '💪',
    title: L({
      ko: '먹방 유튜버 자질 있다, 호쾌한 대식가형 💪',
      en: 'Mukbang YouTuber Material, the Bold Big Eater Type 💪',
      ja: 'フードYouTuberの素質あり、豪快な大食いタイプ 💪',
      'zh-CN': '有当吃播博主的潜质，豪爽大食型 💪',
      'zh-TW': '有當吃播主的潛質，豪爽大食型 💪',
      vi: 'Có tố chất YouTuber ẩm thực, kiểu Người ăn khỏe hào sảng 💪',
      id: 'Punya Bakat Jadi YouTuber Makan, Tipe Pemakan Lahap yang Ceria 💪',
    }),
    shortDescription: L({
      ko: '먹는 것이 행복입니다. 많이 먹는 것도 실력입니다.',
      en: 'Eating is happiness. Eating a lot is a skill too.',
      ja: '食べることが幸せです。たくさん食べることも実力です。',
      'zh-CN': '吃饭就是幸福，能吃也是一种实力。',
      'zh-TW': '吃飯就是幸福，能吃也是一種實力。',
      vi: 'Ăn uống là hạnh phúc. Ăn nhiều cũng là một khả năng.',
      id: 'Makan adalah kebahagiaan. Makan banyak juga sebuah kemampuan.',
    }),
    description: L({
      ko: '국에 밥 말고, 다 비비고, 그릇 싹 비우고, 계획 없이 즉흥으로 맛집 들어갑니다. 먹방 유튜버 자질이 있는 타입입니다. 같이 먹으면 분위기가 살아납니다.',
      en: 'You pour rice into soup, mix everything together, clean your bowl completely, and walk into restaurants on a whim with no plan. You have the makings of a mukbang YouTuber. Meals are lively whenever you\'re around.',
      ja: 'スープにご飯を入れ、全部混ぜ、器をきれいに空にし、計画なしで即興に人気店に入ります。フードYouTuberの素質があるタイプです。一緒に食べると盛り上がります。',
      'zh-CN': '把饭倒进汤里，全都拌在一起，碗吃得干干净净，没有计划、说走就走进餐厅。有当吃播博主的潜质，跟你一起吃饭气氛都会被带动起来。',
      'zh-TW': '把飯倒進湯裡，全部拌在一起，碗吃得乾乾淨淨，沒計畫、說走就走進餐廳。有當吃播主的潛質，跟你一起吃飯氣氛都會被帶動起來。',
      vi: 'Bạn đổ cơm vào canh, trộn hết mọi thứ, ăn sạch bát, và bước vào quán ăn một cách ngẫu hứng không kế hoạch. Bạn có tố chất trở thành YouTuber ẩm thực. Ăn cùng bạn thì không khí luôn sôi động.',
      id: 'Kamu menuang nasi ke dalam sup, mencampur semuanya, menghabiskan mangkuk sampai bersih, dan masuk ke restoran secara spontan tanpa rencana. Kamu punya bakat jadi YouTuber makan. Suasana jadi hidup setiap kali makan bersamamu.',
    }),
    mukbangStyle: L({
      ko: '호쾌한 대식가형 💪',
      en: 'Bold Big Eater Type 💪',
      ja: '豪快な大食いタイプ 💪',
      'zh-CN': '豪爽大食型 💪',
      'zh-TW': '豪爽大食型 💪',
      vi: 'Người ăn khỏe hào sảng 💪',
      id: 'Pemakan Lahap yang Ceria 💪',
    }),
    mukbangKeywords: L({
      ko: '대식·호쾌함·즉흥·분위기 메이커',
      en: 'Big appetite, boldness, spontaneity, mood maker',
      ja: '大食い、豪快さ、即興、ムードメーカー',
      'zh-CN': '大胃口、豪爽、随性、气氛担当',
      'zh-TW': '大胃口、豪爽、隨性、氣氛擔當',
      vi: 'Ăn nhiều, hào sảng, ngẫu hứng, người tạo không khí',
      id: 'Porsi besar, ceria, spontan, pembawa suasana',
    }),
    eatingTogether: L({
      ko: '제일 먼저 메뉴 결정하고 제일 많이 먹고 제일 나중에 숟가락 놓음',
      en: 'Decides the menu first, eats the most, and puts the spoon down last',
      ja: '一番先にメニューを決め、一番多く食べ、一番最後にスプーンを置く',
      'zh-CN': '最先定好菜单，吃得最多，最后一个放下勺子',
      'zh-TW': '最先定好菜單，吃得最多，最後一個放下湯匙',
      vi: 'Quyết định món trước tiên, ăn nhiều nhất, và đặt muỗng xuống sau cùng',
      id: 'Menentukan menu lebih dulu, makan paling banyak, dan meletakkan sendok paling akhir',
    }),
    foodStrength: L({
      ko: '먹방 에너지로 식탁 분위기를 살리는 능력',
      en: 'The ability to liven up the table with mukbang energy',
      ja: '食べる勢いでテーブルの雰囲気を盛り上げる能力',
      'zh-CN': '用干饭的气场带动餐桌氛围的能力',
      'zh-TW': '用吃飯的氣場帶動餐桌氛圍的能力',
      vi: 'Khả năng làm sôi động không khí bàn ăn bằng năng lượng ăn uống',
      id: 'Kemampuan menghidupkan suasana meja dengan energi makan yang menggebu',
    }),
    communityStance: L({
      ko: '"부먹이 맞지, 왜 찍어 먹어?" 강경 부먹파',
      en: '"Pouring is obviously right, why would you dip?" A hardcore pour-eating advocate',
      ja: '「かけるのが正解でしょ、なんでつけるの？」強硬なかけ派',
      'zh-CN': '「当然是倒酱对啊，干嘛要蘸？」坚定的倒酱派',
      'zh-TW': '「當然是倒醬對啊，幹嘛要沾？」堅定的倒醬派',
      vi: '"Đổ sốt mới đúng chứ, sao lại phải chấm?" - Người ủng hộ mạnh mẽ phe đổ sốt',
      id: '"Tuang saus jelas lebih benar, kenapa harus dicelup?" - Pendukung berat kubu tuang saus',
    }),
    shareMessage: L({
      ko: '먹방 스타일: 호쾌한 대식가형 💪 밥에 다 비비고 국물까지 싹 비우는 유형... 먹방 유튜버 해야 하는 거 아닌가 ㅋㅋ → 너는 어떤 먹방 스타일이야?',
      en: "Mukbang style: Bold Big Eater Type 💪 The type who mixes everything into rice and cleans the broth completely... shouldn't you be a mukbang YouTuber lol → What's your mukbang style?",
      ja: '食べ方タイプ：豪快な大食いタイプ 💪 ご飯に全部混ぜてスープまで空にするタイプ…フードYouTuberになるべきでは(笑) → あなたはどんな食べ方タイプ？',
      'zh-CN': '干饭风格：豪爽大食型 💪 全都拌进饭里、连汤都喝干净的类型…是不是该去当吃播博主了哈哈 → 你是什么干饭风格？',
      'zh-TW': '吃飯風格：豪爽大食型 💪 全部拌進飯裡、連湯都喝乾淨的類型…是不是該去當吃播主了哈哈 → 你是什麼吃飯風格？',
      vi: 'Kiểu ăn uống: Người ăn khỏe hào sảng 💪 Kiểu trộn hết vào cơm và ăn sạch cả nước canh... chẳng phải nên làm YouTuber ẩm thực rồi sao 😆 → Bạn thuộc kiểu ăn uống nào?',
      id: 'Gaya makan: Pemakan Lahap yang Ceria 💪 Tipe yang mencampur semuanya dengan nasi dan menghabiskan kuahnya juga... bukannya harusnya jadi YouTuber makan ya 😂 → Kamu tipe gaya makan apa?',
    }),
  },
  {
    type: 'Type6',
    emoji: '👑',
    title: L({
      ko: '먹방의 신, 전설의 먹방왕형 👑',
      en: 'God of Mukbang, the Legendary Mukbang King Type 👑',
      ja: '食の神、伝説の大食い王タイプ 👑',
      'zh-CN': '干饭之神，传说中的大胃王型 👑',
      'zh-TW': '吃飯之神，傳說中的大胃王型 👑',
      vi: 'Vị thần ẩm thực, kiểu Vua ăn uống huyền thoại 👑',
      id: 'Dewa Makan, Tipe Raja Makan Legendaris 👑',
    }),
    shortDescription: L({
      ko: '12개 전부 호쾌하게 골랐습니다. 당신의 위장은 아마 무한대입니다.',
      en: 'You chose the bold option for all 12 questions. Your stomach must be infinite.',
      ja: '12問全部豪快に選びました。あなたの胃袋はきっと無限大です。',
      'zh-CN': '12道题全部豪爽地选了，你的胃容量大概是无限的。',
      'zh-TW': '12道題全部豪爽地選了，你的胃容量大概是無限的。',
      vi: 'Bạn đã chọn kiểu hào sảng cho cả 12 câu. Dạ dày của bạn chắc là vô hạn.',
      id: 'Kamu memilih opsi paling lahap untuk semua 12 pertanyaan. Perutmu sepertinya tak terbatas.',
    }),
    description: L({
      ko: '부먹 확신범, 불닭 도전자, 비빔밥 창조자, 그릇 싹 청소자. 모든 먹방 스타일에서 가장 호쾌하고 야무진 선택을 했습니다. 살면서 배가 남아서 남긴 경험보다 다 먹고 아쉬운 경험이 더 많은 타입입니다.',
      en: "A confirmed pour-eater, a fire noodle challenger, a bibimbap creator, a bowl-cleaning master. You made the boldest, heartiest choice in every single mukbang style category. In your life, you've had more moments of regretting finishing everything than moments of leaving food behind.",
      ja: 'かけ派を確信し、激辛にも挑戦し、ビビンバを創造し、器を完全に空にする人。すべての食べ方タイプの中で最も豪快でしっかりした選択をしました。食べ残して後悔するより、食べきって物足りなさを感じることの多いタイプです。',
      'zh-CN': '坚定的倒酱派、辣味挑战者、拌饭创造者、清盘达人。在所有干饭风格里都做出了最豪爽、最干脆的选择。人生中因为吃太饱而遗憾的次数，比因为没吃够而遗憾的次数更多的类型。',
      'zh-TW': '堅定的倒醬派、辣味挑戰者、拌飯創造者、清盤達人。在所有吃飯風格裡都做出了最豪爽、最乾脆的選擇。人生中因為吃太飽而遺憾的次數，比因為沒吃夠而遺憾的次數更多的類型。',
      vi: 'Một người kiên định phe đổ sốt, người thử thách vị siêu cay, người sáng tạo món trộn, người ăn sạch bát. Bạn đã đưa ra lựa chọn hào sảng và dứt khoát nhất trong mọi kiểu ăn uống. Bạn là kiểu người có nhiều trải nghiệm tiếc nuối vì đã ăn hết hơn là vì còn thừa đồ ăn.',
      id: 'Pendukung sejati kubu tuang saus, penantang rasa pedas ekstrem, pencipta bibimbap, dan penghabis mangkuk sejati. Kamu membuat pilihan paling lahap dan tegas di setiap kategori gaya makan. Kamu adalah tipe yang lebih sering menyesal karena kehabisan makanan daripada karena menyisakannya.',
    }),
    mukbangStyle: L({
      ko: '전설의 먹방왕형 👑',
      en: 'Legendary Mukbang King Type 👑',
      ja: '伝説の大食い王タイプ 👑',
      'zh-CN': '传说中的大胃王型 👑',
      'zh-TW': '傳說中的大胃王型 👑',
      vi: 'Vua ăn uống huyền thoại 👑',
      id: 'Raja Makan Legendaris 👑',
    }),
    mukbangKeywords: L({
      ko: '무한 식욕·호쾌함·먹방 마스터·그릇 청소',
      en: 'Infinite appetite, boldness, mukbang master, bowl cleaning',
      ja: '無限の食欲、豪快さ、食べ方マスター、完食',
      'zh-CN': '食欲无限、豪爽、干饭大师、清盘',
      'zh-TW': '食慾無限、豪爽、吃飯大師、清盤',
      vi: 'Thèm ăn vô hạn, hào sảng, cao thủ ăn uống, ăn sạch bát',
      id: 'Nafsu makan tak terbatas, lahap, master makan, habis tak bersisa',
    }),
    eatingTogether: L({
      ko: '옆에 있으면 나도 더 많이 먹게 됨. 최고의 먹방 동반자',
      en: "Being next to you makes everyone else eat more too. The ultimate meal companion",
      ja: '隣にいると自分もたくさん食べてしまう。最高の食事仲間',
      'zh-CN': '在旁边的话自己也会跟着多吃，最佳饭搭子',
      'zh-TW': '在旁邊的話自己也會跟著多吃，最佳飯友',
      vi: 'Có bạn bên cạnh là mình cũng ăn nhiều hơn. Người bạn đồng hành ăn uống tuyệt nhất',
      id: 'Berada di sampingmu membuat orang lain jadi makan lebih banyak juga. Teman makan terbaik',
    }),
    foodStrength: L({
      ko: '어떤 음식도 맛있게 먹는 능력. 식당 사장님이 제일 좋아하는 손님',
      en: 'The ability to enjoy any food deliciously. The customer every restaurant owner loves most',
      ja: 'どんな食べ物も美味しく食べる能力。お店の店主が一番好きな客',
      'zh-CN': '能把任何食物吃得香的能力，是老板最喜欢的客人',
      'zh-TW': '能把任何食物吃得香的能力，是老闆最喜歡的客人',
      vi: 'Khả năng ăn ngon miệng với bất kỳ món ăn nào. Vị khách được chủ quán yêu thích nhất',
      id: 'Kemampuan menikmati makanan apa pun dengan lahap. Pelanggan favorit pemilik restoran',
    }),
    communityStance: L({
      ko: '찍먹러 보면 이해가 안 되는 강경 부먹파 수장',
      en: "The hardcore pour-eating leader who can't understand dip-eaters at all",
      ja: 'つけ派を見ると理解できない強硬なかけ派の頭',
      'zh-CN': '看蘸酱派完全无法理解的坚定倒酱派头目',
      'zh-TW': '看沾醬派完全無法理解的堅定倒醬派頭目',
      vi: 'Thủ lĩnh phe đổ sốt kiên định, không thể hiểu được phe chấm sốt',
      id: 'Pemimpin kubu tuang saus yang keras dan tidak bisa memahami kubu celup saus sama sekali',
    }),
    oneLiner: L({
      ko: '당신과 함께하는 식사는 항상 행복합니다',
      en: 'A meal with you is always a happy one',
      ja: 'あなたと一緒の食事はいつも幸せです',
      'zh-CN': '和你一起吃饭总是很幸福',
      'zh-TW': '和你一起吃飯總是很幸福',
      vi: 'Bữa ăn cùng bạn luôn luôn là một bữa ăn hạnh phúc',
      id: 'Makan bersamamu selalu terasa menyenangkan',
    }),
    shareMessage: L({
      ko: '먹방 스타일: 전설의 먹방왕형 👑 12개 전부 호쾌하게 골랐음... 부먹 강경파 수장 등극 ㅋㅋㅋ → 찍먹러들 나와봐 논쟁 받아줌',
      en: "Mukbang style: Legendary Mukbang King Type 👑 Chose the bold option for all 12 questions... crowned leader of the hardcore pour-eating camp lol → Dip-eaters, come at me, let's debate",
      ja: '食べ方タイプ：伝説の大食い王タイプ 👑 12問全部豪快に選んだ…かけ派の強硬リーダーに登極(笑) → つけ派の人、出てきて論争しよう',
      'zh-CN': '干饭风格：传说中的大胃王型 👑 12道题全部豪爽地选了…荣登倒酱派头目哈哈哈 → 蘸酱派的都出来，接受挑战',
      'zh-TW': '吃飯風格：傳說中的大胃王型 👑 12道題全部豪爽地選了…榮登倒醬派頭目哈哈哈 → 沾醬派的都出來，接受挑戰',
      vi: 'Kiểu ăn uống: Vua ăn uống huyền thoại 👑 Đã chọn kiểu hào sảng cho cả 12 câu... lên ngôi thủ lĩnh phe đổ sốt kiên định 😂 → Phe chấm sốt đâu, ra đây tranh luận nào',
      id: 'Gaya makan: Raja Makan Legendaris 👑 Memilih opsi paling lahap untuk semua 12 pertanyaan... naik takhta jadi pemimpin kubu tuang saus 😂 → Kubu celup saus, ayo maju, debat yuk',
    }),
  },
];
