/** 7개 로케일: ko, en, ja, zh-CN, zh-TW, vi, id */
const T = (
  ko: string,
  en: string,
  ja: string,
  zhCN: string,
  zhTW: string,
  vi: string,
  id: string,
) => ({
  ko,
  en,
  ja,
  'zh-CN': zhCN,
  'zh-TW': zhTW,
  vi,
  id,
});

export interface Phase3YoloFireGodlifeTypeQuestion {
  id: number;
  question: Record<string, string>;
  options: { text: Record<string, string>; score: number }[];
}

export interface Phase3YoloFireGodlifeTypeResult {
  type: string;
  emoji: string;
  title: Record<string, string>;
  shortDescription: Record<string, string>;
  description: Record<string, string>;
  lifeFinanceType: Record<string, string>;
  keywords: Record<string, string>;
  strength: Record<string, string>;
  weakness: Record<string, string>;
  prescription: Record<string, string>;
  goodMatch: Record<string, string>;
  badMatch: Record<string, string>;
  shareTypeName: Record<string, string>;
}

export function calculatePhase3YoloFireGodlifeTypeResult(scores: number[]): string {
  const total = scores.reduce((a, b) => a + (b ?? 0), 0);
  if (total <= 1) return 'Type1';
  if (total <= 3) return 'Type2';
  if (total <= 6) return 'Type3';
  if (total <= 9) return 'Type4';
  if (total <= 11) return 'Type5';
  return 'Type6';
}

export const phase3YoloFireGodlifeTypeQuestions: Phase3YoloFireGodlifeTypeQuestion[] = [
  {
    id: 1,
    question: T(
      '월급이 들어왔을 때 가장 먼저 드는 생각은?',
      'When your paycheck lands, what is the first thought?',
      '給料が入ったとき、真っ先に思うのは？',
      '工资到账后，你最先想到什么？',
      '薪水入帳後，你最先想到的是？',
      'Lương về, ý nghĩ đầu tiên của bạn là gì?',
      'Saat gaji masuk, apa pikiran pertamamu?',
    ),
    options: [
      {
        text: T(
          '이번 달엔 뭘 해볼까. 여행이나 맛집 가고 싶었는데',
          'What should I do this month—travel or hit that restaurant I wanted.',
          '今月は何しよう。旅行や行きたかったお店、やりたいことがある。',
          '这个月做点什么——旅行或去一直想去的餐厅。',
          '這個月做點什麼——旅行或去一直想去的餐廳。',
          'Tháng này làm gì—đi du lịch hay ăn chỗ mình muốn.',
          'Bulan ini mau apa—travel atau restoran yang sudah lama ingin dicoba.',
        ),
        score: 0,
      },
      {
        text: T(
          '저축 먼저. 목표 금액까지 얼마나 남았는지 확인한다',
          'Save first. I check how far I am from my savings goal.',
          'まず貯金。目標額まであとどれくらいか確認する。',
          '先存钱。看看离目标金额还有多远。',
          '先存錢。看看離目標金額還有多遠。',
          'Tiết kiệm trước. Xem còn bao xa mới tới mục tiêu.',
          'Tabung dulu. Cek masih berapa lagi ke target tabungan.',
        ),
        score: 1,
      },
    ],
  },
  {
    id: 2,
    question: T(
      '10년 후 나의 이상적인 모습은?',
      'What does your ideal self look like in 10 years?',
      '10年後の理想の自分は？',
      '10年后你理想中的自己是什么样？',
      '10年後你理想中的自己是什麼樣？',
      '10 năm nữa, bạn muốn trông như thế nào?',
      'Dalam 10 tahun, versi ideal dirimu seperti apa?',
    ),
    options: [
      {
        text: T(
          '지금보다 더 자유롭게 하고 싶은 것을 하며 살고 있는 모습',
          'Living more freely, doing more of what I want.',
          '今より自由に、やりたいことをして生きている。',
          '比现在更自由，做更多自己想做的事。',
          '比現在更自由，做更多自己想做的事。',
          'Tự do hơn, làm nhiều điều mình muốn hơn.',
          'Lebih bebas, melakukan lebih banyak hal yang kuinginkan.',
        ),
        score: 0,
      },
      {
        text: T(
          '경제적으로 완전히 독립해서 일을 선택할 수 있는 상태',
          'Fully financially independent, able to choose whether and how I work.',
          '経済的に完全に独立し、働き方を選べる状態。',
          '经济完全独立，可以自由选择是否工作、如何工作。',
          '經濟完全獨立，可以自由選擇是否工作、如何工作。',
          'Độc lập tài chính hoàn toàn, tự chọn có làm việc hay không.',
          'Mandiri finansial penuh, bisa memilih kerja atau tidak.',
        ),
        score: 1,
      },
    ],
  },
  {
    id: 3,
    question: T(
      '친구가 "우리 다음 달에 해외여행 가자!"라고 했을 때?',
      'Your friend says: “Let’s go abroad next month!” You…',
      '友だちが「来月海外旅行行こう！」と言ったら？',
      '朋友说“我们下个月出国玩吧！”你会？',
      '朋友說「我們下個月出國玩吧！」你會？',
      'Bạn nói: “Tháng sau đi du lịch nước ngoài nhé!” Bạn…',
      'Teman bilang: “Bulan depan ke luar negeri yuk!” Kamu…',
    ),
    options: [
      {
        text: T(
          '"어디로? 나 갈게!" 일정 맞추고 바로 항공권 본다',
          '“Where? I’m in!” I align dates and look at flights.',
          '「どこ？行く！」日程を合わせてすぐ航空券を見る。',
          '“去哪？我去！”对行程、立刻看机票。',
          '「去哪？我去！」對行程、立刻看機票。',
          '“Đi đâu? Mình đi!” Ghép lịch và xem vé ngay.',
          '“Ke mana? Aku ikut!” Cocokkan jadwal, langsung cek tiket.',
        ),
        score: 0,
      },
      {
        text: T(
          '"이번 달 예산이 어떻게 되는지 보고." 여행 경비를 먼저 계산한다',
          '“Let me see this month’s budget.” I estimate the trip cost first.',
          '「今月の予算を見てから。」まず旅費を計算する。',
          '“先看这个月预算。”先算旅费。',
          '「先看這個月預算。」先算旅費。',
          '“Để xem ngân sách tháng này.” Tính chi phí chuyến đi trước.',
          '“Lihat dulu budget bulan ini.” Hitung biaya trip dulu.',
        ),
        score: 1,
      },
    ],
  },
  {
    id: 4,
    question: T(
      '지금 하는 일(직장/사업)에 대한 솔직한 생각은?',
      'Honestly, how do you feel about your job or business right now?',
      '今の仕事／事業について、本音は？',
      '对现在的工作/事业，你的真实想法是？',
      '對現在的工作／事業，你的真實想法是？',
      'Thật lòng, bạn nghĩ gì về công việc／kinh doanh hiện tại?',
      'Jujur, bagaimana perasaanmu tentang pekerjaan／bisnismu sekarang?',
    ),
    options: [
      {
        text: T(
          '좋아하는 일을 하고 싶다. 돈보다 의미가 중요하다',
          'I want work I love. Meaning matters more than money.',
          '好きな仕事がしたい。お金より意味が大事。',
          '想做喜欢的事。意义比钱重要。',
          '想做喜歡的事。意義比錢重要。',
          'Muốn làm việc mình thích. Ý nghĩa quan trọng hơn tiền.',
          'Ingin kerja yang disukai. Makna lebih penting dari uang.',
        ),
        score: 0,
      },
      {
        text: T(
          '지금은 수단이다. 목표 자산을 모을 때까지 최대한 버텨야 한다',
          'Right now it’s a means to an end. I hold on until I hit my asset goal.',
          '今は手段。目標資産が貯まるまで耐える。',
          '现在是手段。攒够目标资产前尽量撑住。',
          '現在是手段。存夠目標資產前盡量撐住。',
          'Giờ là phương tiện. Cố đến khi đủ tài sản mục tiêu.',
          'Ini sekadar jalan. Bertahan sampai aset target tercapai.',
        ),
        score: 1,
      },
    ],
  },
  {
    id: 5,
    question: T(
      '오늘 저녁 갑자기 여유가 생겼다. 무엇을 하나요?',
      'You suddenly have a free evening. What do you do?',
      '今夜ふと時間ができた。何をする？',
      '今晚突然有空。你会做什么？',
      '今晚突然有空。你會做什麼？',
      'Tối nay bỗng rảnh. Bạn làm gì?',
      'Malam ini tiba-tiba luang. Kamu ngapain?',
    ),
    options: [
      {
        text: T(
          '맛집 가거나 보고 싶던 공연·영화를 즐긴다',
          'Hit a great restaurant or a show or movie I wanted.',
          '行きたかったお店、ライブ、映画を楽しむ。',
          '去喜欢的餐厅，或看想看的演出、电影。',
          '去喜歡的餐廳，或看想看的演出、電影。',
          'Ăn chỗ ngon, xem show／phim mình muốn.',
          'Makan di tempat favorit atau nonton pertunjukan／film yang diinginkan.',
        ),
        score: 0,
      },
      {
        text: T(
          '재테크 공부를 하거나 재무 계획을 점검한다',
          'Study investing or review my money plan.',
          '投資の勉強や家計・資産計画を見直す。',
          '学理财或检查财务计划。',
          '學理財或檢查財務計畫。',
          'Học đầu tư hoặc rà soát kế hoạch tài chính.',
          'Belajar investasi atau cek rencana keuangan.',
        ),
        score: 1,
      },
    ],
  },
  {
    id: 6,
    question: T(
      '소비할 때 나를 멈추게 하는 생각은?',
      'What thought stops you before you spend?',
      'お金を使うとき、ブレーキになる考えは？',
      '花钱时，什么想法会让你停下来？',
      '花錢時，什麼想法會讓你停下來？',
      'Khi tiêu tiền, ý nghĩ nào khiến bạn dừng lại?',
      'Saat mau belanja, pemikiran apa yang menghentikanmu?',
    ),
    options: [
      {
        text: T(
          '"이게 나한테 진짜 의미 있는 소비인가?"',
          '“Is this spending actually meaningful for me?”',
          '「これって本当に自分にとって意味のある支出？」',
          '“这消费对我真的有意义吗？”',
          '「這消費對我真的有意義嗎？」',
          '“Chi tiêu này có thực sự có ý nghĩa với mình không?”',
          '“Pengeluaran ini benar-benar bermakna bagiku?”',
        ),
        score: 0,
      },
      {
        text: T(
          '"이 돈으로 주식이나 ETF를 샀으면 10년 후 얼마가 됐을까?"',
          '“If I put this into stocks or ETFs, what might it be in 10 years?”',
          '「このお金を株やETFに回したら、10年後いくらになる？」',
          '“如果拿这笔钱买股票或 ETF，十年后会是多少？”',
          '「如果拿這筆錢買股票或 ETF，十年後會是多少？」',
          '“Nếu góp vào cổ phiếu／ETF, 10 năm sau sẽ ra sao?”',
          '“Kalau uang ini untuk saham／ETF, 10 tahun lagi jadi berapa?”',
        ),
        score: 1,
      },
    ],
  },
  {
    id: 7,
    question: T(
      '은퇴 시점에 대한 나의 생각은?',
      'How do you think about retirement timing?',
      '退職／リタイアのタイミングについて、あなたの考えは？',
      '关于退休时间，你的想法是？',
      '關於退休時間，你的想法是？',
      'Bạn nghĩ thế nào về thời điểm nghỉ hưu?',
      'Bagaimana pandanganmu soal kapan pensiun?',
    ),
    options: [
      {
        text: T(
          '좋아하는 일을 하면서 살다가 자연스럽게 은퇴하면 된다',
          'Work on what I enjoy and retire naturally when the time comes.',
          '好きなことをしながら生き、自然にリタイアすればいい。',
          '做喜欢的事，到时候自然退休就好。',
          '做喜歡的事，到時候自然退休就好。',
          'Làm việc mình thích, đến lúc thì nghỉ hưu tự nhiên.',
          'Kerja yang disukai, pensiun natural saat tiba waktunya.',
        ),
        score: 0,
      },
      {
        text: T(
          '최대한 빨리 은퇴하고 싶다. 40대 이전이 목표다',
          'I want out ASAP—before 40 if I can.',
          'できるだけ早く退職したい。40代前が目標。',
          '想尽快退休，目标是40岁前。',
          '想盡快退休，目標是40歲前。',
          'Muốn nghỉ càng sớm càng tốt—mục tiêu trước 40.',
          'Ingin pensiun secepat mungkin—target sebelum 40.',
        ),
        score: 1,
      },
    ],
  },
  {
    id: 8,
    question: T(
      '내 삶에서 가장 중요하게 여기는 것은?',
      'What matters most in your life?',
      'あなたの人生でいちばん大事にしているのは？',
      '你人生中最看重什么？',
      '你人生中最看重什麼？',
      'Điều quan trọng nhất trong đời bạn là gì?',
      'Yang paling penting dalam hidupmu?',
    ),
    options: [
      {
        text: T(
          '지금 이 순간의 행복과 경험',
          'Happiness and experience in the here and now.',
          '今この瞬間の幸福と体験。',
          '当下的幸福与体验。',
          '當下的幸福與體驗。',
          'Hạnh phúc và trải nghiệm ở hiện tại.',
          'Kebahagiaan dan pengalaman di sini dan sekarang.',
        ),
        score: 0,
      },
      {
        text: T(
          '미래의 자유와 경제적 안정',
          'Future freedom and financial security.',
          '未来の自由と経済的な安定。',
          '未来的自由与经济稳定。',
          '未來的自由與經濟穩定。',
          'Tự do tương lai và an toàn tài chính.',
          'Kebebasan masa depan dan keamanan finansial.',
        ),
        score: 1,
      },
    ],
  },
  {
    id: 9,
    question: T(
      '주변에서 나를 보는 시각은?',
      'How do people around you tend to see you?',
      '周りの人はあなたをどう見ている？',
      '身边的人通常怎么看你？',
      '身邊的人通常怎麼看你？',
      'Mọi người xung quanh thường thấy bạn thế nào?',
      'Orang di sekitarmu biasanya melihatmu seperti apa?',
    ),
    options: [
      {
        text: T(
          '"저 친구는 잘 논다. 인생 즐길 줄 안다"',
          '“They really live it up—they know how to enjoy life.”',
          '「あの子、よく遊ぶね。人生を楽しむのがうまい」',
          '“这人挺会玩，懂享受生活。”',
          '「這人挺會玩，懂享受生活。」',
          '“Bạn ấy sống vui, biết tận hưởng cuộc sống.”',
          '“Dia jago menikmati hidup.”',
        ),
        score: 0,
      },
      {
        text: T(
          '"저 친구는 진짜 철저하다. 계획적이고 미래를 잘 준비한다"',
          '“They’re so disciplined—planned and ready for the future.”',
          '「あの子、本当にしっかりしてる。計画的で未来の準備ができてる」',
          '“这人很稳，有计划，为未来准备得好。”',
          '「這人很穩，有計畫，為未來準備得好。」',
          '“Người có kế hoạch, chuẩn bị tương lai tốt.”',
          '“Orangnya terencana, siap untuk masa depan.”',
        ),
        score: 1,
      },
    ],
  },
  {
    id: 10,
    question: T(
      '인생에서 가장 후회하고 싶지 않은 것은?',
      'What do you least want to regret in life?',
      '人生でいちばん後悔したくないことは？',
      '人生中最不想后悔的是什么？',
      '人生中最不想後悔的是什麼？',
      'Điều bạn ít muốn hối tiếc nhất trong đời?',
      'Hal apa yang paling tidak ingin kamu sesali?',
    ),
    options: [
      {
        text: T(
          '하고 싶은 것을 못 하고 기회를 놓치는 것',
          'Missing chances and not doing what I wanted.',
          'やりたいことをできず、チャンスを逃すこと。',
          '没做成想做的事，错过机会。',
          '沒做成想做的事，錯過機會。',
          'Bỏ lỡ cơ hội, không làm được điều mình muốn.',
          'Kehilangan kesempatan, tidak melakukan yang diinginkan.',
        ),
        score: 0,
      },
      {
        text: T(
          '아무 준비 없이 나이 들어서 경제적으로 힘들어지는 것',
          'Getting older with no plan and struggling financially.',
          '何の準備もなく歳を取り、経済的に苦しくなること。',
          '毫无准备地变老，经济上陷入困境。',
          '毫無準備地變老，經濟上陷入困境。',
          'Già đi mà không chuẩn bị, khó khăn về tiền.',
          'Menua tanpa persiapan, kesulitan finansial.',
        ),
        score: 1,
      },
    ],
  },
  {
    id: 11,
    question: T(
      '아침 루틴에 대한 나의 현실은?',
      'What is your morning routine really like?',
      '朝のルーティン、現実は？',
      '你的早晨routine现实是？',
      '你的早晨routine現實是？',
      'Thói quen buổi sáng thực tế của bạn ra sao?',
      'Rutin pagimu sebenarnya seperti apa?',
    ),
    options: [
      {
        text: T(
          '알람을 끄고 잠을 더 자는 게 낙이다. 아침은 여유롭게',
          'Snooze and sleep in—slow, relaxed mornings.',
          'アラームを止めて二度寝。朝はゆったり。',
          '关掉闹钟再睡——早晨慢慢来。',
          '關掉鬧鐘再睡——早晨慢慢來。',
          'Tắt báo thức, ngủ thêm—sáng thư thả.',
          'Matikan alarm, tidur lagi—pagi santai.',
        ),
        score: 0,
      },
      {
        text: T(
          '일찍 일어나서 운동이나 공부 등 자기계발로 하루를 시작한다',
          'Up early—workout, study, or self-improvement to start the day.',
          '早起きして運動や勉強など、自己投資で一日を始める。',
          '早起运动或学习，用自我提升开启一天。',
          '早起運動或學習，用自我提升開啟一天。',
          'Dậy sớm—tập, học, phát triển bản thân để bắt đầu ngày.',
          'Bangun pagi—olahraga, belajar, pengembangan diri.',
        ),
        score: 1,
      },
    ],
  },
  {
    id: 12,
    question: T(
      '지금 이 순간 내 인생의 우선순위는?',
      'Right now, what is your top priority in life?',
      '今、この瞬間の人生の優先順位は？',
      '此刻你人生的优先级是？',
      '此刻你人生的優先順序是？',
      'Lúc này ưu tiên số một trong đời bạn là gì?',
      'Saat ini prioritas utama hidupmu?',
    ),
    options: [
      {
        text: T(
          '현재의 나. 지금 행복하지 않으면 미래도 의미가 없다',
          'Present me—if I’m not happy now, the future feels hollow.',
          '今の自分。今幸せじゃないなら未来も意味がない。',
          '当下的我。现在不快乐，未来也没意义。',
          '當下的我。現在不快樂，未來也沒意義。',
          'Bản thân hiện tại—không vui bây giờ thì tương lai cũng vô nghĩa.',
          'Aku sekarang—kalau tidak bahagia sekarang, masa depan kosong.',
        ),
        score: 0,
      },
      {
        text: T(
          '미래의 나. 지금 조금 불편해도 나중에 더 자유로울 수 있다면 감수한다',
          'Future me—a little discomfort now is OK if it buys more freedom later.',
          '未来の自分。今ちょっと苦しくても、あとで自由になれるなら受け入れる。',
          '未来的我。现在略有不便，若能换来自由就值得。',
          '未來的我。現在略有不便，若能換來自由就值得。',
          'Bản thân tương lai—khó chút bây giờ nếu sau này tự do hơn.',
          'Aku masa depan—sedikit tidak nyaman sekarang demi kebebasan nanti.',
        ),
        score: 1,
      },
    ],
  },
];

export const phase3YoloFireGodlifeTypeResults: Phase3YoloFireGodlifeTypeResult[] = [
  {
    type: 'Type1',
    emoji: '🎉',
    title: T(
      '오늘이 전부인, 순수 욜로족',
      'Pure YOLO—today is everything',
      '今日がすべて、ピュアYOLO族',
      '活在当下的纯粹YOLO族',
      '活在當下的純粹YOLO族',
      'YOLO thuần—hôm nay là tất cả',
      'YOLO murni—hari ini adalah segalanya',
    ),
    shortDescription: T(
      'You Only Live Once. 딱 한 번뿐인 인생, 지금 즐겨야 합니다.',
      'You only live once—this one life is meant to be enjoyed now.',
      'You Only Live Once。一度きりの人生、今を楽しむ。',
      '人生只有一次，要趁现在享受。',
      '人生只有一次，要趁現在享受。',
      'Chỉ sống một lần—hãy tận hưởng hiện tại.',
      'Hidup sekali—nikmati sekarang.',
    ),
    description: T(
      '당신은 현재의 행복을 최우선으로 두는 순수한 욜로 철학의 소유자입니다. 여행, 맛집, 경험에 아낌없이 투자하고, 미래 걱정보다 지금 이 순간을 충만하게 사는 것이 가장 중요합니다. 돈은 쓰라고 있는 것이라는 신념이 확고합니다. 삶의 만족도가 높은 대신, 미래 대비라는 숙제는 언젠가 반드시 마주해야 합니다. 즐기는 것과 조금씩 준비하는 것을 병행하는 것이 현명합니다.',
      'You put present happiness first—a true YOLO mindset. You invest freely in travel, food, and experiences, and living fully in the moment matters more than worrying about the future. You firmly believe money is meant to be used. Life satisfaction runs high, but someday you will need to face the homework of preparing ahead. Balancing fun with a little steady saving is wise.',
      '今の幸福を最優先する、純粋なYOLO思考の持ち主。旅行、グルメ、体験にお金を惜しまず、未来より「今」を満たすことが何より大事。お金は使うためにある、という信念が強い。満足度は高い一方、いつかは「将来の備え」と向き合う課題があります。楽しみつつ、少しずつ準備するのが賢明です。',
      '你把当下的快乐放在第一位，是纯粹的YOLO派。你愿意为旅行、美食、体验花钱，比起担心未来，更重视把现在过得充实。你坚信钱就是用来花的。生活满意度很高，但“为未来做准备”这道题迟早要面对。在享受的同时稍微存一点，会更稳妥。',
      '你把當下的快樂放在第一位，是純粹的YOLO派。你願意為旅行、美食、體驗花錢，比起擔心未來，更重視把現在過得充實。你堅信錢就是用來花的。生活滿意度很高，但「為未來做準備」這道題遲早要面對。在享受的同時稍微存一點，會更穩妥。',
      'Bạn đặt hạnh phúc hiện tại lên hàng đầu—đúng tinh thần YOLO. Bạn sẵn sàng chi cho du lịch, ăn uống, trải nghiệm; sống trọn khoảnh khắc quan trọng hơn lo xa. Bạn tin tiền là để dùng. Đời sống thỏa mãn cao, nhưng chuyện dự phòng tương lai rồi cũng phải đối mặt. Cân bằng giữa vui và tích lũy nhẹ là khôn ngoan.',
      'Kamu mengutamakan kebahagiaan saat ini—jiwa YOLO murni. Kamu rela investasi pada travel, makan, pengalaman; hidup penuh momen kini lebih penting dari cemas masa depan. Kamu yakin uang untuk dipakai. Kepuasan hidup tinggi, tapi tugas menyiapkan masa depan pasti datang. Seimbangkan bersenang-senang dengan sedikit menabung.',
    ),
    lifeFinanceType: T(
      '인생 재무 유형: 순수 욜로족 (Pure YOLO)',
      'Life & money type: Pure YOLO',
      '人生×お金タイプ：ピュアYOLO',
      '人生财务类型：纯粹YOLO',
      '人生財務類型：純粹YOLO',
      'Kiểu đời sống & tiền: YOLO thuần',
      'Tipe hidup & uang: YOLO murni',
    ),
    keywords: T(
      '현재, 경험, 자유, 즐거움',
      'Present, experience, freedom, fun',
      '現在、体験、自由、楽しさ',
      '当下、体验、自由、快乐',
      '當下、體驗、自由、快樂',
      'Hiện tại, trải nghiệm, tự do, niềm vui',
      'Saat ini, pengalaman, kebebasan, kesenangan',
    ),
    strength: T(
      '삶의 만족도 최상위, 후회 없는 경험 추구',
      'Top-tier life satisfaction; chasing regret-free experiences',
      '生活満足度が高い、後悔しない体験を追う',
      '生活满意度高，追求少留遗憾的体验',
      '生活滿意度高，追求少留遺憾的體驗',
      'Mức hài lòng cao; theo đuổi trải nghiệm ít hối tiếc',
      'Kepuasan hidup tinggi; kejar pengalaman tanpa penyesalan',
    ),
    weakness: T(
      '미래 대비 부족, 갑작스러운 상황에 취약',
      'Light on future prep; fragile when surprises hit',
      '将来の備えが薄い、突発に弱い',
      '未来准备不足，突发状况时较脆弱',
      '未來準備不足，突發狀況時較脆弱',
      'Dự phòng tương lai mỏng; dễ lúng túng khi bất ngờ',
      'Persiapan masa depan tipis; rentan saat kejutan',
    ),
    prescription: T(
      '월급의 10%만 건드리지 않는 계좌에 넣어보세요. 나머지는 마음껏 욜로해도 됩니다.',
      'Try parking 10% of each paycheck in an account you do not touch—the rest can still be full YOLO.',
      '給与の10％だけは触らない口座に。残りは思う存分YOLOで。',
      '试试把工资的10%放进不动用的账户，其余仍可尽情YOLO。',
      '試試把薪水的10%放進不動用的帳戶，其餘仍可盡情YOLO。',
      'Thử gửi 10% lương vào tài khoản “không đụng”—phần còn lại vẫn YOLO thoải mái.',
      'Sisihkan 10% gaji ke rekening yang tidak disentuh—sisanya tetap bisa YOLO.',
    ),
    goodMatch: T(
      'Type 2 (서로의 철학을 이해하며 자극을 줌)',
      'Type 2 (you spur each other on while respecting different views)',
      'Type 2（お互いの考えを理解し合い刺激し合える）',
      'Type 2（互相理解彼此，又能互相激发）',
      'Type 2（互相理解彼此，又能互相激發）',
      'Type 2 (hiểu nhau và tiếp thêm động lực)',
      'Type 2 (saling mengerti dan memotivasi)',
    ),
    badMatch: T(
      'Type 6 (극단적인 절약파와는 대화가 안 맞음)',
      'Type 6 (hard to vibe with extreme savers)',
      'Type 6（極端な節約派とは話が合いにくい）',
      'Type 6（与极端节省派很难聊到一起）',
      'Type 6（與極端節省派很難聊到一起）',
      'Type 6 (khó hợp với kiểu tiết kiệm cực đoan)',
      'Type 6 (sulit selaras dengan penghemat ekstrem)',
    ),
    shareTypeName: T(
      '순수 욜로족',
      'Pure YOLO',
      'ピュアYOLO族',
      '纯粹YOLO族',
      '純粹YOLO族',
      'YOLO thuần',
      'YOLO murni',
    ),
  },
  {
    type: 'Type2',
    emoji: '🌈',
    title: T(
      '즐기면서도 신경 쓰는, 현실 균형 욜로파',
      'Balanced YOLO—fun first, but not blind to tomorrow',
      '楽しみつつも気にする、現実バランスYOLO派',
      '会享受也在意的现实平衡YOLO派',
      '會享受也在意的現實平衡YOLO派',
      'YOLO cân bằng—vui nhưng không mù quáng với ngày mai',
      'YOLO seimbang—seru tapi tetap sadar masa depan',
    ),
    shortDescription: T(
      '오늘도 즐기고 싶지만, 미래가 아예 없는 건 불안합니다.',
      'I want fun today—but zero future buffer feels scary.',
      '今日も楽しみたい。でも未来がゼロは不安。',
      '今天也想开心，但完全没有未来缓冲会不安。',
      '今天也想開心，但完全沒有未來緩衝會不安。',
      'Muốn vui hôm nay nhưng không có dự phòng tương lai thì lo.',
      'Ingin senang hari ini—tapi tanpa cadangan masa depan rasanya cemas.',
    ),
    description: T(
      '당신은 현재의 즐거움을 중요하게 여기지만 미래에 대한 최소한의 준비는 갖추고 싶은 현실적인 균형파입니다. 욜로 성향이 강하지만 완전한 무계획은 아닙니다. 여행도 가고, 맛집도 가되 통장에 최소한의 안전망은 두는 스타일입니다. 가장 많은 사람들이 속하는 현실적인 타입으로, 지금 이 균형을 조금만 더 미래 쪽으로 기울이면 훨씬 안정적인 재무 상태를 만들 수 있습니다.',
      'You value today’s fun but still want a minimum safety net for the future—a realistic balancer. YOLO-leaning, but not totally plan-free. You still travel and eat out, while keeping a little cushion in the bank. Many people land here; nudge that balance slightly toward the future and your finances get much steadier.',
      '今の楽しさは大事。でも未来への最低限の備えも欲しい、現実的なバランス派。YOLO寄りだが完全な無計画ではない。旅行もグルメも行くが、口座には最低限のセーフティネット。多くの人がここにいて、このバランスを少しだけ未来側に傾けると財務はぐっと安定します。',
      '你重视当下的快乐，也想为未来留一点最低保障——现实的平衡派。偏YOLO，但并非完全没计划。你会旅行、探店，同时账户里留一点安全垫。很多人属于这一类；把平衡稍微向未来倾斜，财务会稳很多。',
      '你重視當下的快樂，也想為未來留一點最低保障——現實的平衡派。偏YOLO，但並非完全沒計畫。你會旅行、探店，同時帳戶裡留一點安全墊。很多人屬於這一類；把平衡稍微向未來傾斜，財務會穩很多。',
      'Bạn trọng niềm vui hiện tại nhưng vẫn muốn tối thiểu an toàn cho tương lai—người cân bằng thực tế. Thiên YOLO nhưng không hoàn toàn vô kế hoạch. Vẫn đi du lịch, ăn uống, đồng thời giữ một chút đệm trong tài khoản. Nhiều người thuộc nhóm này; lệch nhẹ về phía tương lai, tài chính ổn hơn hẳn.',
      'Kamu menghargai kesenangan kini tapi tetap ingin jaring pengaman minimal—pembela seimbang. Condong YOLO tapi bukan tanpa rencana. Tetap traveling dan kuliner sambil menyisakan cadangan di rekening. Banyak orang di sini; geser sedikit ke masa depan, keuangan jauh lebih stabil.',
    ),
    lifeFinanceType: T(
      '인생 재무 유형: 현실 균형 욜로파 (Balanced YOLO)',
      'Life & money type: Balanced YOLO',
      '人生×お金タイプ：現実バランスYOLO',
      '人生财务类型：现实平衡YOLO',
      '人生財務類型：現實平衡YOLO',
      'Kiểu đời sống & tiền: YOLO cân bằng',
      'Tipe hidup & uang: YOLO seimbang',
    ),
    keywords: T(
      '균형, 현재 중심, 최소한의 안정',
      'Balance, present-focused, minimum stability',
      'バランス、今重視、最低限の安定',
      '平衡、偏重当下、最低限度稳定',
      '平衡、偏重當下、最低限度穩定',
      'Cân bằng, ưu tiên hiện tại, ổn định tối thiểu',
      'Keseimbangan, fokus kini, stabilitas minimal',
    ),
    strength: T(
      '삶의 질과 재정 안정의 중간 지점 유지',
      'You sit between quality of life and financial stability',
      '生活の質と財務安定の中間を保つ',
      '在生活品质与财务稳定之间找中间点',
      '在生活品質與財務穩定之間找中間點',
      'Giữ điểm giữa giữa chất lượng sống và ổn định tài chính',
      'Titik tengah antara kualitas hidup dan stabilitas finansial',
    ),
    weakness: T(
      '어느 쪽도 완벽하지 않아서 가끔 불안함',
      'Neither side feels perfect—occasional anxiety',
      'どちらも完璧ではなく、ときどき不安',
      '两边都不够完美，有时会焦虑',
      '兩邊都不夠完美，有時會焦慮',
      'Không bên nào hoàn hảo—thỉnh thoảng lo lắng',
      'Tak ada yang sempurna—kadang cemas',
    ),
    prescription: T(
      '자동이체 저축 금액을 지금보다 5만 원만 더 올려보세요. 생각보다 차이가 큽니다.',
      'Bump your auto-transfer savings by a small fixed amount—you may be surprised by the difference.',
      '自動振替の積立を、今より少しだけ上げてみて。思った以上に効きます。',
      '把自动转账储蓄比现在调高一点点，差别往往比想象大。',
      '把自動轉帳儲蓄比現在調高一點點，差別往往比想像大。',
      'Tăng nhẹ số tiền gửi tự động—chênh lệch có thể lớn hơn bạn nghĩ.',
      'Naikkan sedikit tabungan transfer otomatis—bedanya bisa mengejutkan.',
    ),
    goodMatch: T(
      'Type 3 (갓생 자극을 받으며 성장할 수 있음)',
      'Type 3 (their “god-life” energy helps you grow)',
      'Type 3（ゴッドライフの刺激で成長できる）',
      'Type 3（自律人生型能带动你成长）',
      'Type 3（自律人生型能帶動你成長）',
      'Type 3 (năng lượng “god-life” giúp bạn tiến bộ)',
      'Type 3 (semangat god-life membantumu berkembang)',
    ),
    badMatch: T(
      'Type 5 (극단적인 파이어족의 절약 수준에 함께하기 어려움)',
      'Type 5 (hard to keep up with hardcore FIRE-level saving)',
      'Type 5（極端なFIREレベルの節約にはついていきにくい）',
      'Type 5（很难跟上极端FIRE级别的节俭）',
      'Type 5（很難跟上極端FIRE級別的節儉）',
      'Type 5 (khó theo kịp mức tiết kiệm kiểu FIRE cực đoan)',
      'Type 5 (sulit mengikuti hemat level FIRE ekstrem)',
    ),
    shareTypeName: T(
      '현실 균형 욜로파',
      'Balanced YOLO',
      '現実バランスYOLO派',
      '现实平衡YOLO派',
      '現實平衡YOLO派',
      'YOLO cân bằng',
      'YOLO seimbang',
    ),
  },
  {
    type: 'Type3',
    emoji: '🌅',
    title: T(
      '오늘도 갓생, 자기계발 성장형',
      'God-life growth—today counts, so does tomorrow',
      '今日もゴッドライフ、自己投資成長型',
      '今天也在自律人生：自我投资成长型',
      '今天也在自律人生：自我投資成長型',
      'God-life tăng trưởng—hôm nay và mai đều quan trọng',
      'God-life growth—hari ini dan besok sama pentingnya',
    ),
    shortDescription: T(
      '현재도 챙기고 미래도 챙깁니다. 새벽 기상은 기본입니다.',
      'You care about now and later—early mornings are basically default.',
      '今も未来も両方大事。早起きはデフォ。',
      '现在和未来都要顾，早起几乎是标配。',
      '現在與未來都要顧，早起幾乎是標配。',
      'Lo cả hiện tại và tương lai—dậy sớm gần như mặc định.',
      'Urusi kini dan nanti—bangun pagi hampir default.',
    ),
    description: T(
      '당신은 현재의 즐거움과 미래의 안정을 동시에 추구하는 갓생 철학의 실천자입니다. 하고 싶은 것도 하되, 자기계발과 재무 관리도 게을리하지 않습니다. 루틴이 있고, 목표가 있고, 그 목표를 향해 꾸준히 나아가는 타입입니다. 욜로와 파이어의 장점을 모두 추구하지만 그만큼 스스로에게 높은 기준을 요구하기 때문에 번아웃을 주의해야 합니다.',
      'You chase both present joy and future stability—the “god-life” mindset in action. You still do what you want, but you do not slack on self-development or money habits. You have routines, goals, and steady progress. You want the best of YOLO and FIRE—which means high standards for yourself, so watch for burnout.',
      '今の楽しさと未来の安定、両方を追うゴッドライフ実践者。やりたいこともするが、自己投資とお金の管理も怠らない。ルーティンがあり、目標があり、着実に進むタイプ。YOLOとFIREのいいとこ取りを目指す分、自分へのハードルが高くなりがち。燃え尽きに注意。',
      '你同时追求当下的快乐与未来的稳定，是“自律人生”的践行者。想做的事会做，自我提升和理财也不松懈。有习惯、有目标、能持续推进。你想兼得YOLO与FIRE的优点，但也因此对自己要求很高，要注意倦怠。',
      '你同時追求當下的快樂與未來的穩定，是「自律人生」的實踐者。想做的事會做，自我提升與理財也不鬆懈。有習慣、有目標、能持續推進。你想兼得YOLO與FIRE的優點，但也因此對自己要求很高，要注意倦怠。',
      'Bạn theo đuổi cả niềm vui hiện tại và sự ổn định tương lai—tinh thần “god-life”. Vẫn làm điều mình muốn nhưng không lơ là phát triển bản thân và quản lý tiền. Có thói quen, có mục tiêu, tiến bộ đều. Muốn gói trọn YOLO và FIRE—chuẩn cao với bản thân nên cẩn thận kiệt sức.',
      'Kamu mengejar kesenangan kini dan stabilitas nanti—jiwa god-life. Tetap melakukan yang diinginkan tanpa mengabaikan pengembangan diri dan keuangan. Ada rutin, target, dan progres stabil. Menginginkan yang terbaik dari YOLO dan FIRE—standar tinggi pada diri sendiri, waspada burnout.',
    ),
    lifeFinanceType: T(
      '인생 재무 유형: 갓생 성장형 (God-Life Achiever)',
      'Life & money type: God-Life Achiever',
      '人生×お金タイプ：ゴッドライフ成長型',
      '人生财务类型：自律人生成长型',
      '人生財務類型：自律人生成長型',
      'Kiểu đời sống & tiền: God-life tăng trưởng',
      'Tipe hidup & uang: God-life achiever',
    ),
    keywords: T(
      '성장, 루틴, 균형, 자기계발',
      'Growth, routine, balance, self-investment',
      '成長、ルーティン、バランス、自己投資',
      '成长、习惯、平衡、自我投资',
      '成長、習慣、平衡、自我投資',
      'Tăng trưởng, thói quen, cân bằng, tự đầu tư',
      'Pertumbuhan, rutin, keseimbangan, pengembangan diri',
    ),
    strength: T(
      '저축과 소비를 균형 있게 관리, 장기적으로 가장 안정적',
      'Balanced saving and spending—often the steadiest long term',
      '貯金と支出のバランスが良く、長期的に安定しやすい',
      '储蓄与消费平衡，长期往往最稳',
      '儲蓄與消費平衡，長期往往最穩',
      'Tiết kiệm và chi tiêu cân bằng—ổn định dài hạn',
      'Menabung dan membelanjakan seimbang—stabil jangka panjang',
    ),
    weakness: T(
      '스스로에게 너무 높은 기준을 세워 번아웃 위험',
      'Sky-high self-standards raise burnout risk',
      '自分へのハードルが高く、燃え尽きリスク',
      '对自己标准过高，有倦怠风险',
      '對自己標準過高，有倦怠風險',
      'Chuẩn quá cao với bản thân—rủi ro kiệt sức',
      'Standar diri terlalu tinggi—risiko burnout',
    ),
    prescription: T(
      '완벽한 갓생 말고 오늘 하루 딱 하나만 잘해보는 것도 충분합니다. 쉬는 것도 갓생입니다.',
      'Skip perfect god-life—nailing just one thing today is enough. Rest counts as god-life too.',
      '完璧なゴッドライフより、今日は一つだけちゃんとやる。休むのもゴッドライフ。',
      '不必完美自律人生，今天做好一件事就够。休息也是自律人生。',
      '不必完美自律人生，今天做好一件事就夠。休息也是自律人生。',
      'Không cần god-life hoàn hảo—chỉ cần làm tốt một việc hôm nay. Nghỉ ngơi cũng là god-life.',
      'Tidak perlu god-life sempurna—cukup satu hal hari ini. Istirahat juga god-life.',
    ),
    goodMatch: T(
      'Type 4 (함께 성장의 방향을 공유할 수 있음)',
      'Type 4 (you align on the direction of growth)',
      'Type 4（成長の方向性を共有できる）',
      'Type 4（成长方向一致、能并肩前行）',
      'Type 4（成長方向一致、能並肩前行）',
      'Type 4 (cùng hướng phát triển)',
      'Type 4 (selaras arah pertumbuhan)',
    ),
    badMatch: T(
      'Type 1 (계획 없이 사는 모습이 답답하게 느껴질 수 있음)',
      'Type 1 (their no-plan lifestyle can feel suffocating)',
      'Type 1（無計画な生き方がもどかしく感じることがある）',
      'Type 1（无计划的生活可能让你憋闷）',
      'Type 1（無計畫的生活可能讓你憋悶）',
      'Type 1 (lối sống không kế hoạch có thể ngột ngạt)',
      'Type 1 (hidup tanpa rencana bisa terasa sesak)',
    ),
    shareTypeName: T(
      '갓생 성장형',
      'God-Life Achiever',
      'ゴッドライフ成長型',
      '自律人生成长型',
      '自律人生成長型',
      'God-life tăng trưởng',
      'God-life achiever',
    ),
  },
  {
    type: 'Type4',
    emoji: '📋',
    title: T(
      '목표 지향 갓생파, 미래 설계 실천형',
      'Goal-driven god-life—future-first, still human',
      '目標志向ゴッドライフ派、未来設計実践型',
      '目标导向的自律派：未来规划实践型',
      '目標導向的自律派：未來規劃實踐型',
      'God-life hướng mục tiêu—thực hành thiết kế tương lai',
      'God-life berorientasi tujuan—praktisi perencanaan masa depan',
    ),
    shortDescription: T(
      '지금 잘 살기 위해서가 아니라, 나중에 잘 살기 위해 지금을 관리합니다.',
      'You manage today so tomorrow can be better—not just for today’s comfort.',
      '今をよくするためではなく、あとでよくするために今を管理する。',
      '管理现在不是为了当下舒服，而是为了以后过得更好。',
      '管理現在不是為了當下舒服，而是為了以後過得更好。',
      'Quản lý hiện tại để mai tốt hơn—không chỉ để thoải mái hôm nay.',
      'Atur hari ini agar besok lebih baik—bukan cuma nyaman sekarang.',
    ),
    description: T(
      '당신은 갓생 철학을 기반으로 미래 설계에 방점을 찍는 타입입니다. 자기계발과 재무 관리를 병행하면서 장기적인 목표를 향해 꾸준히 나아갩니다. 충동적인 소비보다는 가치 있는 투자에 집중하고, 일상의 루틴을 중요하게 여깁니다. 파이어족에 가까워지고 싶지만 삶의 질도 포기하고 싶지 않은 현실적인 미래 지향형입니다.',
      'You anchor god-life values in future design. You pair self-development with money habits and move steadily toward long-term goals. You favor meaningful investments over impulse buys, and you take daily routines seriously. You lean toward FIRE but still refuse to trash quality of life—a pragmatic future-first type.',
      'ゴッドライフの考え方を土台に、未来設計を最重視するタイプ。自己投資と資産管理を両立し、長期目標に向かって着実に進む。衝動買いより価値ある投資、日々のルーティンを大切にする。FIREに近づきたいが生活の質は捨てたくない、現実的な未来志向型。',
      '你把自律人生的理念落在“未来设计”上。自我提升与理财并行，朝长期目标稳步推进。比起冲动消费，更重视有价值的投资与日常习惯。你向往FIRE但不肯牺牲生活品质——务实的未来导向型。',
      '你把自律人生的理念落在「未來設計」上。自我提升與理財並行，朝長期目標穩步推進。比起衝動消費，更重視有價值的投資與日常習慣。你嚮往FIRE但不肯犧牲生活品質——務實的未來導向型。',
      'Bạn đặt thiết kế tương lai vào nền tảng god-life. Kết hợp phát triển bản thân và quản lý tiền, tiến đều về mục tiêu dài hạn. Ưu tiên đầu tư có ý nghĩa hơn mua bốc đồng; coi trọng thói quen hàng ngày. Muốn gần FIRE nhưng không bỏ chất lượng sống—hướng tương lai thực tế.',
      'Kamu menancapkan god-life pada desain masa depan. Gabungkan pengembangan diri dan keuangan, melangkah ke target jangka panjang. Utamakan investasi bermakna dibanding belanja impulsif; rutinitas penting. Condong ke FIRE tanpa mengorbankan kualitas hidup—tipe masa depan pragmatis.',
    ),
    lifeFinanceType: T(
      '인생 재무 유형: 미래 설계 실천형 (Future Builder)',
      'Life & money type: Future Builder',
      '人生×お金タイプ：未来設計実践型',
      '人生财务类型：未来规划实践型',
      '人生財務類型：未來規劃實踐型',
      'Kiểu đời sống & tiền: Future Builder',
      'Tipe hidup & uang: Future Builder',
    ),
    keywords: T(
      '목표, 계획, 자기계발, 미래 지향',
      'Goals, planning, self-investment, future focus',
      '目標、計画、自己投資、未来志向',
      '目标、计划、自我投资、面向未来',
      '目標、計畫、自我投資、面向未來',
      'Mục tiêu, kế hoạch, tự đầu tư, hướng tương lai',
      'Tujuan, rencana, pengembangan diri, fokus masa depan',
    ),
    strength: T(
      '장기 목표 달성 가능성 높음, 꾸준한 자산 증식',
      'Strong odds on long-term goals; steady wealth building',
      '長期目標達成の可能性が高く、資産が着実に増えやすい',
      '长期目标达成概率高，资产稳步增长',
      '長期目標達成機率高，資產穩步增長',
      'Khả năng đạt mục tiêu dài hạn cao; tài sản tăng đều',
      'Peluang capai target jangka panjang tinggi; kekayaan tumbuh stabil',
    ),
    weakness: T(
      '현재의 즐거움을 지나치게 미루다 기회를 놓칠 수 있음',
      'Deferring today’s joy too long—you might miss moments',
      '今の楽しみを先送りしすぎて、チャンスを逃すことがある',
      '过度推迟当下的快乐，可能错过体验',
      '過度推遲當下的快樂，可能錯過體驗',
      'Hoãn niềm vui quá lâu—có thể lỡ khoảnh khắc',
      'Menunda kesenangan terlalu lama—bisa melewatkan momen',
    ),
    prescription: T(
      '목표를 향해 달려가면서도 한 달에 한 번은 의미 있는 경험에 돈을 써보세요. 번아웃을 막는 투자입니다.',
      'While chasing goals, budget one meaningful experience a month—it is an investment against burnout.',
      '目標に向かって走りながらも、月に一度は意味のある体験にお金を使う。燃え尽き防止の投資。',
      '冲刺目标的同时，每月留一次钱给有意义的体验，这是防倦怠的投资。',
      '衝刺目標的同時，每月留一次錢給有意義的體驗，這是防倦怠的投資。',
      'Khi theo đuổi mục tiêu, mỗi tháng một trải nghiệm có ý nghĩa—đầu tư chống kiệt sức.',
      'Sambil kejar target, sisihkan satu pengalaman bermakna per bulan—investasi anti burnout.',
    ),
    goodMatch: T(
      'Type 5 (재무 목표와 전략을 함께 나눌 수 있는 동반자)',
      'Type 5 (a partner to share money goals and tactics with)',
      'Type 5（資産目標と戦略を一緒に語れる相棒）',
      'Type 5（能一起聊财务目标与策略的同伴）',
      'Type 5（能一起聊財務目標與策略的同伴）',
      'Type 5 (bạn đồng hành chia sẻ mục tiêu & chiến lược tiền)',
      'Type 5 (partner bagi tujuan dan strategi keuangan)',
    ),
    badMatch: T(
      'Type 1 (삶의 방향이 너무 달라 대화가 평행선)',
      'Type 1 (life direction so different you talk in parallel lines)',
      'Type 1（生き方の方向が違いすぎて話が平行線）',
      'Type 1（人生方向差太多，对话像平行线）',
      'Type 1（人生方向差太多，對話像平行線）',
      'Type 1 (hướng sống khác quá—nói chuyện song song)',
      'Type 1 (arah hidup terlalu beda—ngobrol tak bertemu)',
    ),
    shareTypeName: T(
      '미래 설계 실천형',
      'Future Builder',
      '未来設計実践型',
      '未来规划实践型',
      '未來規劃實踐型',
      'Future Builder',
      'Future Builder',
    ),
  },
  {
    type: 'Type5',
    emoji: '🔥',
    title: T(
      '조기 은퇴를 꿈꾸는, 파이어 준비생',
      'FIRE-in-training—early retirement is the north star',
      '早期リタイアを夢見る、FIRE準備生',
      '梦想提前退休的FIRE预备生',
      '夢想提前退休的FIRE預備生',
      'Ứng viên FIRE—nghỉ hưu sớm là kim chỉ nam',
      'Kandidat FIRE—pensiun dini adalah utara',
    ),
    shortDescription: T(
      '일을 그만두는 날을 손꼽아 기다리고 있습니다. 지금은 모으는 중입니다.',
      'You count the days until you can quit. Right now you stack.',
      '辞める日を指折り数えている。今は貯める番。',
      '你掰着指头等辞职那天，现在在拼命攒。',
      '你掰著指頭等辭職那天，現在在拼命存。',
      'Đếm từng ngày đến lúc nghỉ. Giờ là giai đoạn tích lũy.',
      'Menghitung hari bisa berhenti. Sekarang fase menumpuk.',
    ),
    description: T(
      '당신은 경제적 자립과 조기 은퇴를 목표로 현재의 소비를 철저하게 통제하는 파이어 철학의 실천자입니다. 지금 당장의 욜로보다 미래의 자유가 훨씬 매력적으로 느껴집니다. 재테크 커뮤니티를 자주 들여다보고, 지출 기록과 자산 현황을 주기적으로 점검합니다. 목표가 명확하고 실행력이 강하지만, 지금 이 순간을 너무 희생하지 않도록 균형을 찾는 것도 중요합니다.',
      'You aim for financial independence and early retirement, tightly controlling spending in the FIRE spirit. Future freedom feels far more attractive than instant YOLO. You follow money communities, track expenses, and review assets on a schedule. Goals are sharp and execution is strong—just remember not to sacrifice the present entirely; balance matters.',
      '経済的自立と早期リタイアを目指し、支出を厳しく管理するFIRE実践者。今のYOLOより未来の自由が魅力的。投資コミュニティを見たり、支出と資産を定期的にチェック。目標は明確で実行力も強いが、今を全部犠牲にしないバランスも大事。',
      '以经济独立与提前退休为目标，严格控制当下消费，是FIRE理念的践行者。比起眼前的YOLO，未来的自由更吸引你。你会关注理财社群，记账并定期检视资产。目标清晰、执行力强，但也要注意别把“现在”全部牺牲，平衡很重要。',
      '以經濟獨立與提前退休為目標，嚴格控制當下消費，是FIRE理念的實踐者。比起眼前的YOLO，未來的自由更吸引你。你會關心理財社群，記帳並定期檢視資產。目標清晰、執行力強，但也要注意別把「現在」全部犧牲，平衡很重要。',
      'Bạn hướng tới độc lập tài chính và nghỉ hưu sớm, kiểm soát chi tiêu chặt theo tinh thần FIRE. Tự do tương lai hấp dẫn hơn YOLO tức thì. Theo cộng đồng đầu tư, ghi chép chi tiêu, xem tài sản định kỳ. Mục tiêu rõ, thực thi mạnh—nhưng đừng hy sinh hoàn toàn hiện tại; cần cân bằng.',
      'Kamu mengejar mandiri finansial dan pensiun dini, mengontrol pengeluaran ketat ala FIRE. Kebebasan masa depan lebih menarik dari YOLO instan. Ikut komunitas investasi, catat pengeluaran, tinjau aset berkala. Target jelas, eksekusi kuat—jangan korbankan sepenuhnya hari ini; perlu keseimbangan.',
    ),
    lifeFinanceType: T(
      '인생 재무 유형: 파이어 준비생 (FIRE Candidate)',
      'Life & money type: FIRE Candidate',
      '人生×お金タイプ：FIRE準備生',
      '人生财务类型：FIRE预备生',
      '人生財務類型：FIRE預備生',
      'Kiểu đời sống & tiền: Ứng viên FIRE',
      'Tipe hidup & uang: Kandidat FIRE',
    ),
    keywords: T(
      '경제적 자유, 조기 은퇴, 절약, 투자',
      'Financial freedom, early retirement, saving, investing',
      '経済的自由、早期リタイア、節約、投資',
      '经济自由、提前退休、节俭、投资',
      '經濟自由、提前退休、節儉、投資',
      'Tự do tài chính, nghỉ hưu sớm, tiết kiệm, đầu tư',
      'Kebebasan finansial, pensiun dini, hemat, investasi',
    ),
    strength: T(
      '자산 증식 속도 최상위, 목표 달성 가능성 높음',
      'Top-tier wealth compounding; high odds of hitting the goal',
      '資産増加速度はトップクラス、目標達成の可能性が高い',
      '资产增速顶尖，达成目标概率高',
      '資產增速頂尖，達成目標機率高',
      'Tốc độ tăng tài sản hàng đầu; khả năng đạt mục tiêu cao',
      'Pertumbuhan kekayaan teratas; peluang capai target tinggi',
    ),
    weakness: T(
      '현재 삶의 질 저하, 극도의 절약으로 인한 번아웃 위험',
      'Today’s quality of life can dip; extreme frugality risks burnout',
      '今のQOLが下がりがち、極度の節約で燃え尽きリスク',
      '当下生活质量易下降，极度节俭有倦怠风险',
      '當下生活品質易下降，極度節儉有倦怠風險',
      'Chất lượng sống hiện tại có thể giảm; tiết kiệm cực đoan dễ kiệt sức',
      'Kualitas hidup kini bisa turun; hemat ekstrem risiko burnout',
    ),
    prescription: T(
      '파이어를 향해 달려가는 것도 좋지만, 지금 이 과정 자체도 삶입니다. 작은 즐거움을 예산에 넣어두세요.',
      'Sprinting toward FIRE is fine—this journey is still your life. Budget small joys.',
      'FIREを目指すのはいい。でもこの過程も人生。小さな楽しみを予算に。',
      '冲向FIRE很好，但这段过程也是人生。把小小的快乐写进预算。',
      '衝向FIRE很好，但這段過程也是人生。把小小的快樂寫進預算。',
      'Lao vào FIRE được—nhưng hành trình này cũng là đời. Cho niềm vui nhỏ vào ngân sách.',
      'Kejar FIRE boleh—perjalanannya juga hidup. Sisihkan suka kecil di anggaran.',
    ),
    goodMatch: T(
      'Type 6 (재무 철학을 완벽하게 공유하는 동반자)',
      'Type 6 (a partner who fully shares the money philosophy)',
      'Type 6（お金の哲学をほぼ完全に共有できる相棒）',
      'Type 6（财务理念几乎完全同频的同伴）',
      'Type 6（財務理念幾乎完全同頻的同伴）',
      'Type 6 (đồng điệu gần như hoàn toàn về triết lý tiền)',
      'Type 6 (selaras penuh soal filosofi uang)',
    ),
    badMatch: T(
      'Type 1 (욜로족과 함께하면 서로 스트레스)',
      'Type 1 (pairing with a YOLO type stresses both sides)',
      'Type 1（YOLO族と組むとお互いストレス）',
      'Type 1（和YOLO族一起容易互相压力）',
      'Type 1（和YOLO族一起容易互相壓力）',
      'Type 1 (đi với kiểu YOLO—cả hai đều căng)',
      'Type 1 (dengan tipe YOLO—dua-duanya stres)',
    ),
    shareTypeName: T(
      '파이어 준비생',
      'FIRE Candidate',
      'FIRE準備生',
      'FIRE预备生',
      'FIRE預備生',
      'Ứng viên FIRE',
      'Kandidat FIRE',
    ),
  },
  {
    type: 'Type6',
    emoji: '🏖️',
    title: T(
      '이미 길을 정한, 진성 파이어족',
      'True FIRE—you already picked the path',
      'もう道を決めた、本物のFIRE族',
      '已选定路线的真·FIRE族',
      '已選定路線的真·FIRE族',
      'FIRE thật sự—đã chọn đường rồi',
      'FIRE sejati—jalur sudah dipilih',
    ),
    shortDescription: T(
      '경제적 자유. 그것이 제 인생의 단 하나의 목표입니다.',
      'Financial freedom—that is the single goal of my life.',
      '経済的自由。それが人生の唯一の目標。',
      '经济自由。这是我人生的唯一目标。',
      '經濟自由。這是我人生的唯一目標。',
      'Tự do tài chính—đó là mục tiêu duy nhất của đời tôi.',
      'Kebebasan finansial—itulah satu-satunya tujuan hidupku.',
    ),
    description: T(
      '당신은 파이어 철학의 가장 극단적인 형태를 추구하는 진성 파이어족입니다. 모든 소비 결정의 기준은 하나, 조기 은퇴 목표에 도움이 되는가 아닌가입니다. 현재의 즐거움은 목표 달성 이후로 미루고, 지금은 오직 자산 증식에 집중합니다. 명확한 목표 의식과 강철 같은 실행력을 가진 타입입니다. 다만 삶은 목표 달성 이후에만 있는 것이 아닙니다. 지금 이 여정 자체도 당신의 삶임을 잊지 마세요.',
      'You pursue the most extreme form of FIRE. Every spending decision asks one question: does this help early retirement? You defer present fun until after the goal; right now it is all about growing assets. Clear intent and iron discipline—but life is not only after the finish line. This journey is your life too.',
      'FIREの最も極端な形を目指す本物のFIRE族。支出の基準は一つ、早期リタイアに役立つかどうか。今の楽しみは達成後に先送り、今は資産形成に集中。目標意識は明確で実行力も強い。でも人生はゴールのあとだけじゃない。この道のりもあなたの人生だ。',
      '你追求最极端形态的FIRE。每笔消费只问一件事：是否有助于提前退休。当下的快乐推到目标之后，现在只专注资产增值。目标清晰、执行力如钢。但人生不只在终点之后，这段路程也是你的人生。',
      '你追求最極端形態的FIRE。每筆消費只問一件事：是否有助於提前退休。當下的快樂推到目標之後，現在只專注資產增值。目標清晰、執行力如鋼。但人生不只在終點之後，這段路程也是你的人生。',
      'Bạn theo đuổi FIRE ở mức cực đoan. Mọi quyết định chi chỉ hỏi: có giúp nghỉ hưu sớm không? Hoãn vui hiện tại đến sau mục tiêu; giờ chỉ tập trung tăng tài sản. Ý chí rõ, kỷ luật sắt—nhưng đời không chỉ sau vạch đích. Hành trình này cũng là đời bạn.',
      'Kamu mengejar FIRE paling ekstrem. Setiap belanja satu pertanyaan: membantu pensiun dini? Tunda kesenangan kini sampai target; sekarang fokus pertumbuhan aset. Tekad jelas, disiplin baja—tapi hidup tidak hanya setelah garis finis. Perjalanan ini juga hidupmu.',
    ),
    lifeFinanceType: T(
      '인생 재무 유형: 진성 파이어족 (True FIRE)',
      'Life & money type: True FIRE',
      '人生×お金タイプ：本物のFIRE族',
      '人生财务类型：真·FIRE族',
      '人生財務類型：真·FIRE族',
      'Kiểu đời sống & tiền: FIRE thật sự',
      'Tipe hidup & uang: FIRE sejati',
    ),
    keywords: T(
      '경제적 자유, 조기 은퇴, 극단적 절약, 투자 극대화',
      'Financial freedom, early retirement, extreme saving, max investing',
      '経済的自由、早期リタイア、極度の節約、投資最大化',
      '经济自由、提前退休、极度节俭、投资最大化',
      '經濟自由、提前退休、極度節儉、投資最大化',
      'Tự do tài chính, nghỉ hưu sớm, tiết kiệm cực đoan, tối đa hóa đầu tư',
      'Kebebasan finansial, pensiun dini, hemat ekstrem, investasi maksimal',
    ),
    strength: T(
      '목표 달성 시 완전한 재정 자유 가능, 자산 증식 속도 최고',
      'Hit the goal and full financial freedom is on the table; compounding at max speed',
      '達成すれば完全な経済的自由が見える。資産増加速度は最高水準',
      '达成目标后有望实现完全财务自由，资产增速顶尖',
      '達成目標後有望實現完全財務自由，資產增速頂尖',
      'Đạt mục tiêu là có thể tự do tài chính hoàn toàn; tốc độ tài sản tối đa',
      'Capai target—kebebasan finansial penuh mungkin; pertumbuhan aset puncak',
    ),
    weakness: T(
      '현재 삶의 질 최하위, 관계나 경험을 희생할 가능성',
      'Today’s quality of life can tank; relationships and experiences may be sacrificed',
      '今のQOLが下がりやすく、人間関係や体験を犠牲にしがち',
      '当下生活质量易触底，可能牺牲关系与体验',
      '當下生活品質易觸底，可能犧牲關係與體驗',
      'Chất lượng sống hiện tại có thể thấp; quan hệ & trải nghiệm bị hy sinh',
      'Kualitas hidup kini bisa terendah; relasi & pengalaman terkorban',
    ),
    prescription: T(
      '은퇴 후 하고 싶은 것을 지금 조금씩 미리 경험해보세요. 그래야 은퇴 후 삶도 풍요롭습니다.',
      'Sample the things you want after retirement now—in small doses—so post-FIRE life stays rich.',
      'リタイア後にやりたいことを、今ちょっとずつ先取りして。退職後の人生も豊かになる。',
      '把退休后想做的事，现在一点点预演，退休后的生活才会丰盛。',
      '把退休後想做的事，現在一點點預演，退休後的生活才會豐盛。',
      'Thử trước những điều muốn làm sau khi nghỉ hưu—từng chút—để đời sau FIRE vẫn đầy đặn.',
      'Cicipi hal yang ingin dilakukan setelah pensiun sedikit demi sedikit—agar hidup pasca-FIRE tetap kaya.',
    ),
    goodMatch: T(
      'Type 5 (재무 목표와 전략을 완벽하게 공유)',
      'Type 5 (perfect alignment on money goals and strategy)',
      'Type 5（資産目標と戦略をほぼ完全に共有）',
      'Type 5（财务目标与策略高度同频）',
      'Type 5（財務目標與策略高度同頻）',
      'Type 5 (đồng bộ mục tiêu & chiến lược tiền)',
      'Type 5 (selaras target & strategi keuangan)',
    ),
    badMatch: T(
      'Type 1 (삶의 방향이 정반대라 대화 자체가 안 맞음)',
      'Type 1 (opposite directions—you barely speak the same language)',
      'Type 1（生き方が正反対で話が通じにくい）',
      'Type 1（人生方向完全相反，很难说到一起）',
      'Type 1（人生方向完全相反，很難說到一起）',
      'Type 1 (hướng sống đối lập—khó nói chung ngôn ngữ)',
      'Type 1 (arah hidup berlawanan—sulit sepaham)',
    ),
    shareTypeName: T(
      '진성 파이어족',
      'True FIRE',
      '本物のFIRE族',
      '真·FIRE族',
      '真·FIRE族',
      'FIRE thật sự',
      'FIRE sejati',
    ),
  },
];
