/**
 * 나의 '첫인상' 컬러 스캐너 — 12문항 이미지 4지선다, A=0 B=1 C=2 D=3, 총점 0~36 → 6유형
 *
 * Supabase `tests-thumbnails` 업로드 파일명 규칙:
 * - 썸네일: p3_test_first_impression_color_scanner.webp
 * - 답변 이미지(1:1): p3_test_first_impression_color_scanner_q{n}a~d.webp (12문항 × 4 = 48장)
 */

export interface Phase3FirstImpressionColorScannerQuestion {
  id: number;
  question: Record<string, string>;
  options: { image: string; label: Record<string, string>; score: number }[];
}

export interface Phase3FirstImpressionColorScannerResult {
  type: string;
  emoji: string;
  title: Record<string, string>;
  shortDescription: Record<string, string>;
  description: Record<string, string>;
  firstImpressionColor: Record<string, string>;
  colorKeywords: Record<string, string>;
  firstFeeling: Record<string, string>;
  shiningMoment: Record<string, string>;
  reverseCharm: Record<string, string>;
  matchingColors: Record<string, string>;
  personalColorLink: Record<string, string>;
  shareSnippet: Record<string, string>;
}

export function calculatePhase3FirstImpressionColorScannerResult(scores: number[]): string {
  const total = scores.reduce((a, b) => a + (b ?? 0), 0);
  if (total <= 5) return 'Type1';
  if (total <= 11) return 'Type2';
  if (total <= 19) return 'Type3';
  if (total <= 27) return 'Type4';
  if (total <= 33) return 'Type5';
  return 'Type6';
}

const IMG = (n: number, choice: 'a' | 'b' | 'c' | 'd') =>
  `p3_test_first_impression_color_scanner_q${n}${choice}.webp`;

export const phase3FirstImpressionColorScannerQuestions: Phase3FirstImpressionColorScannerQuestion[] = [
  {
    id: 1,
    question: {
      ko: '지금 내 방에 처음 들어온 사람이 보게 될 장면은?',
      en: 'What would someone see the first time they walk into your room?',
      ja: '今、初めて自分の部屋に入った人が目にする光景は？',
      'zh-CN': '第一次走进你房间的人会看到什么画面？',
      'zh-TW': '第一次走進你房間的人會看到什麼畫面？',
      vi: 'Người lần đầu bước vào phòng bạn sẽ thấy cảnh gì?',
      id: 'Apa yang akan dilihat seseorang saat pertama kali masuk ke kamarmu?',
    },
    options: [
      {
        image: IMG(1, 'a'),
        label: {
          ko: '강렬한 포인트 컬러 소품과 선명한 아트웍이 걸린 개성 있는 공간',
          en: 'A bold space with vivid accent pieces and striking artwork on the walls',
          ja: '強いポイントカラーの小物と鮮やかなアートが飾られた個性的な空間',
          'zh-CN': '摆着强烈点缀色小物、挂着鲜明艺术画的个性空间',
          'zh-TW': '擺著強烈點綴色小物、掛著鮮明藝術畫的個性空間',
          vi: 'Không gian cá tính với đồ điểm màu nổi bật và tranh nghệ thuật rõ nét',
          id: 'Ruang berkarakter dengan aksen warna kuat dan artwork yang mencolok',
        },
        score: 0,
      },
      {
        image: IMG(1, 'b'),
        label: {
          ko: '따뜻한 조명과 식물이 있는 포근하고 생동감 있는 공간',
          en: 'A cozy, lively space with warm lighting and plants',
          ja: '暖かい照明と植物がある、ふんわり活気のある空間',
          'zh-CN': '有温暖灯光和绿植、温馨又有生气的空间',
          'zh-TW': '有溫暖燈光和綠植、溫馨又有生氣的空間',
          vi: 'Không gian ấm cúng, sống động với ánh sáng ấm và cây xanh',
          id: 'Ruang hangat dan hidup dengan pencahayaan lembut serta tanaman',
        },
        score: 1,
      },
      {
        image: IMG(1, 'c'),
        label: {
          ko: '깔끔하게 정돈된 화이트·우드 베이스의 미니멀 공간',
          en: 'A clean, minimal space with a white and wood base',
          ja: 'きちんと整えられたホワイト＆ウッドベースのミニマル空間',
          'zh-CN': '整洁有序的白木基调极简空间',
          'zh-TW': '整潔有序的白木基調極簡空間',
          vi: 'Không gian tối giản gọn gàng với nền trắng và gỗ',
          id: 'Ruang minimalis rapi dengan basis putih dan kayu',
        },
        score: 2,
      },
      {
        image: IMG(1, 'd'),
        label: {
          ko: '은은한 조명과 책·소품이 감성적으로 배치된 신비로운 공간',
          en: 'A mysterious space with soft lighting and books and objects arranged with mood',
          ja: 'やわらかい照明と本・小物が感性的に置かれた神秘的な空間',
          'zh-CN': '灯光柔和、书本与小物感性摆放的神秘空间',
          'zh-TW': '燈光柔和、書本與小物感性擺放的神秘空間',
          vi: 'Không gian huyền ảo với ánh sáng dịu và sách, đồ vật xếp đầy cảm xúc',
          id: 'Ruang misterius dengan lampu lembut serta buku dan barang yang ditata penuh rasa',
        },
        score: 3,
      },
    ],
  },
  {
    id: 2,
    question: {
      ko: '오늘 기분에 딱 맞는 옷을 고른다면?',
      en: 'If you picked an outfit that matches today’s mood, what would it be?',
      ja: '今日の気分にぴったりの服を選ぶなら？',
      'zh-CN': '如果选一件最贴合今天心情的衣服？',
      'zh-TW': '如果選一件最貼合今天心情的衣服？',
      vi: 'Nếu chọn trang phục khớp với tâm trạng hôm nay?',
      id: 'Kalau memilih baju yang paling pas dengan mood hari ini?',
    },
    options: [
      {
        image: IMG(2, 'a'),
        label: {
          ko: '선명하고 강렬한 컬러의 아이템. 눈에 확 들어오는 것',
          en: 'Something in a vivid, intense color that instantly catches the eye',
          ja: '鮮やかで強いカラーのアイテム。目に飛び込んでくるもの',
          'zh-CN': '鲜明强烈的颜色单品，一眼就能抓住目光',
          'zh-TW': '鮮明強烈的顏色單品，一眼就能抓住目光',
          vi: 'Món đồ màu sắc rõ nét, mạnh mẽ — nhìn là chú ý ngay',
          id: 'Item warna cerah dan kuat yang langsung menarik perhatian',
        },
        score: 0,
      },
      {
        image: IMG(2, 'b'),
        label: {
          ko: '따뜻하고 밝은 계열의 컬러. 보기만 해도 기분이 좋아지는 것',
          en: 'Warm, bright tones that lift your mood just by looking at them',
          ja: '暖かく明るい系統のカラー。見るだけで気分が上がるもの',
          'zh-CN': '温暖明亮的色系，光是看着就开心',
          'zh-TW': '溫暖明亮的色系，光是看著就開心',
          vi: 'Tông ấm sáng — chỉ nhìn cũng thấy vui hơn',
          id: 'Warna hangat dan cerah yang bikin mood naik hanya dengan melihatnya',
        },
        score: 1,
      },
      {
        image: IMG(2, 'c'),
        label: {
          ko: '차분하고 자연스러운 어스·그린 계열. 편안하고 세련된 것',
          en: 'Calm, natural earth and green tones — comfortable and polished',
          ja: '落ち着いた自然なアース＆グリーン系。心地よく洗練されたもの',
          'zh-CN': '沉稳自然的大地色与绿色系，舒适又有质感',
          'zh-TW': '沉穩自然的大地色與綠色系，舒適又有質感',
          vi: 'Tông đất và xanh dịu, tự nhiên — thoải mái mà tinh tế',
          id: 'Nuansa earth & green yang tenang dan natural — nyaman sekaligus stylish',
        },
        score: 2,
      },
      {
        image: IMG(2, 'd'),
        label: {
          ko: '파스텔이나 뮤트된 쿨톤 계열. 은은하고 감성적인 것',
          en: 'Pastels or muted cool tones — soft and emotional',
          ja: 'パステルやミュートされたクールトーン。控えめであたたかい感性のもの',
          'zh-CN': '粉彩或柔和冷色调，含蓄又有感性',
          'zh-TW': '粉彩或柔和冷色調，含蓄又有感性',
          vi: 'Pastel hoặc cool tone dịu — nhẹ nhàng và đầy cảm xúc',
          id: 'Pastel atau cool tone yang muted — lembut dan penuh rasa',
        },
        score: 3,
      },
    ],
  },
  {
    id: 3,
    question: {
      ko: '처음 보는 자리에서 인사를 건넬 때 내 분위기는?',
      en: 'When you greet someone for the first time, what’s your vibe?',
      ja: '初対面の場であいさつするときの自分の雰囲気は？',
      'zh-CN': '第一次见面打招呼时，你给人的氛围是？',
      'zh-TW': '第一次見面打招呼時，你給人的氛圍是？',
      vi: 'Khi chào người lần đầu gặp, khí chất của bạn thế nào?',
      id: 'Saat menyapa orang di pertemuan pertama, aura kamu seperti apa?',
    },
    options: [
      {
        image: IMG(3, 'a'),
        label: {
          ko: '눈빛이 강하고 확신에 찬 표정으로 먼저 손을 내미는 장면',
          en: 'Strong eye contact and a confident look as you reach out first',
          ja: '強い眼差しと確信のある表情で、先に手を差し出す場面',
          'zh-CN': '目光坚定、表情自信，主动先伸出手',
          'zh-TW': '目光堅定、表情自信，主動先伸出手',
          vi: 'Ánh mắt mạnh, vẻ tự tin, chủ động đưa tay trước',
          id: 'Tatapan kuat dan ekspresi yakin sambil mengulurkan tangan lebih dulu',
        },
        score: 0,
      },
      {
        image: IMG(3, 'b'),
        label: {
          ko: '환하게 웃으며 자연스럽게 말을 거는 밝고 따뜻한 장면',
          en: 'A bright, warm moment — smiling widely and starting the chat naturally',
          ja: '満面の笑みで自然に声をかける、明るく温かい場面',
          'zh-CN': '笑容灿烂、自然搭话的明亮温暖画面',
          'zh-TW': '笑容燦爛、自然搭話的明亮溫暖畫面',
          vi: 'Cười tươi, bắt chuyện tự nhiên — sáng và ấm áp',
          id: 'Tersenyum lebar dan menyapa dengan natural — cerah dan hangat',
        },
        score: 1,
      },
      {
        image: IMG(3, 'c'),
        label: {
          ko: '차분하게 미소 지으며 편안한 분위기를 만드는 장면',
          en: 'A calm smile that makes the atmosphere feel easy',
          ja: '落ち着いた微笑みで、居心地のよい空気をつくる場面',
          'zh-CN': '淡淡微笑，把气氛变得很自在',
          'zh-TW': '淡淡微笑，把氣氛變得很自在',
          vi: 'Mỉm cười điềm tĩnh, tạo không khí dễ chịu',
          id: 'Tersenyum tenang sambil menciptakan suasana yang nyaman',
        },
        score: 2,
      },
      {
        image: IMG(3, 'd'),
        label: {
          ko: '살짝 신비로운 미소를 띠며 조용히 인사하는 장면',
          en: 'A slightly mysterious smile as you quietly say hello',
          ja: '少し神秘的な笑みを浮かべ、静かにあいさつする場面',
          'zh-CN': '带着一点神秘的微笑，安静地打招呼',
          'zh-TW': '帶著一點神秘的微笑，安靜地打招呼',
          vi: 'Nụ cười hơi huyền bí, chào hỏi nhẹ nhàng',
          id: 'Senyum sedikit misterius sambil menyapa dengan tenang',
        },
        score: 3,
      },
    ],
  },
  {
    id: 4,
    question: {
      ko: '모임에서 내가 앉은 자리의 분위기는?',
      en: 'At a gathering, what’s the vibe around where you’re sitting?',
      ja: '集まりで自分が座っている席の雰囲気は？',
      'zh-CN': '在聚会上，你坐的那一桌气氛如何？',
      'zh-TW': '在聚會上，你坐的那一桌氣氛如何？',
      vi: 'Ở buổi tụ họp, không khí chỗ bạn ngồi thế nào?',
      id: 'Di sebuah kumpulan, suasana di tempat dudukmu seperti apa?',
    },
    options: [
      {
        image: IMG(4, 'a'),
        label: {
          ko: '사람들이 자연스럽게 몰리고 대화 에너지가 폭발하는 자리',
          en: 'People naturally gather and conversation energy explodes',
          ja: '人が自然と集まり、会話のエネルギーが爆発する席',
          'zh-CN': '人们自然聚拢过来，聊天能量爆棚',
          'zh-TW': '人們自然聚攏過來，聊天能量爆棚',
          vi: 'Mọi người tự kéo tới, năng lượng trò chuyện bùng nổ',
          id: 'Orang-orang naturally berkumpul dan energi obrolan meledak',
        },
        score: 0,
      },
      {
        image: IMG(4, 'b'),
        label: {
          ko: '웃음소리가 끊이지 않고 활기차게 떠들썩한 자리',
          en: 'Laughter never stops — a lively, buzzing table',
          ja: '笑い声が絶えず、活気にあふれてにぎやかな席',
          'zh-CN': '笑声不断、热闹又有活力的一桌',
          'zh-TW': '笑聲不斷、熱鬧又有活力的一桌',
          vi: 'Tiếng cười không ngớt, bàn vui nhộn nhịp',
          id: 'Tawa tak putus — meja yang ramai dan penuh semangat',
        },
        score: 1,
      },
      {
        image: IMG(4, 'c'),
        label: {
          ko: '편안하게 이야기가 오가며 안정적인 분위기의 자리',
          en: 'Easy conversation flowing in a steady, comfortable vibe',
          ja: '心地よく話が行き交い、安定した空気の席',
          'zh-CN': '轻松聊天、气氛安定舒服的一桌',
          'zh-TW': '輕鬆聊天、氣氛安定舒服的一桌',
          vi: 'Chuyện trò thoải mái trong không khí ổn định, dễ chịu',
          id: 'Obrolan mengalir nyaman dalam suasana yang stabil',
        },
        score: 2,
      },
      {
        image: IMG(4, 'd'),
        label: {
          ko: '조용하지만 깊은 대화가 오가는 감성적인 자리',
          en: 'Quiet but deep — an emotional space for meaningful talk',
          ja: '静かだけれど深い会話が交わされる、感性的な席',
          'zh-CN': '安静却聊得很深的感性一桌',
          'zh-TW': '安靜卻聊得很深的感性一桌',
          vi: 'Yên nhưng sâu — chỗ đầy cảm xúc với trò chuyện ý nghĩa',
          id: 'Tenang tapi dalam — tempat emosional untuk percakapan bermakna',
        },
        score: 3,
      },
    ],
  },
  {
    id: 5,
    question: {
      ko: '내가 기분 좋을 때 내뿜는 에너지 이미지는?',
      en: 'When you’re in a good mood, what energy image do you give off?',
      ja: '気分がいいときに自分が放つエネルギーのイメージは？',
      'zh-CN': '心情好时，你散发的能量画面是？',
      'zh-TW': '心情好時，你散發的能量畫面是？',
      vi: 'Khi vui, hình ảnh năng lượng bạn tỏa ra là gì?',
      id: 'Saat mood bagus, citra energi yang kamu pancarkan seperti apa?',
    },
    options: [
      {
        image: IMG(5, 'a'),
        label: {
          ko: '붉은 노을 속에 자신감 있게 서있는 실루엣',
          en: 'A confident silhouette standing against a red sunset',
          ja: '赤い夕焼けの中で自信たっぷりに立つシルエット',
          'zh-CN': '站在火红晚霞里、充满自信的剪影',
          'zh-TW': '站在火紅晚霞裡、充滿自信的剪影',
          vi: 'Bóng dáng tự tin đứng giữa hoàng hôn đỏ',
          id: 'Siluet percaya diri berdiri di tengah sunset merah',
        },
        score: 0,
      },
      {
        image: IMG(5, 'b'),
        label: {
          ko: '따뜻한 햇살 가득한 카페에서 환하게 웃는 장면',
          en: 'Smiling brightly in a café filled with warm sunlight',
          ja: 'あたたかい日差しがいっぱいのカフェで明るく笑う場面',
          'zh-CN': '在洒满暖阳的咖啡馆里开怀笑着',
          'zh-TW': '在灑滿暖陽的咖啡館裡開懷笑著',
          vi: 'Cười rạng rỡ trong quán cà phê ngập nắng ấm',
          id: 'Tersenyum cerah di kafe yang penuh sinar matahari hangat',
        },
        score: 1,
      },
      {
        image: IMG(5, 'c'),
        label: {
          ko: '싱그러운 공원에서 여유롭게 산책하는 장면',
          en: 'Strolling leisurely through a fresh, green park',
          ja: 'みずみずしい公園をゆったり散歩している場面',
          'zh-CN': '在清新公园里悠闲散步',
          'zh-TW': '在清新公園裡悠閒散步',
          vi: 'Dạo bước thảnh thơi trong công viên xanh mát',
          id: 'Berjalan santai di taman yang segar dan hijau',
        },
        score: 2,
      },
      {
        image: IMG(5, 'd'),
        label: {
          ko: '달빛 아래 감성적으로 혼자 빛나는 장면',
          en: 'Shining alone under the moonlight, full of mood',
          ja: '月明かりの下で、感性たっぷりにひとり輝く場面',
          'zh-CN': '在月光下独自散发感性光芒',
          'zh-TW': '在月光下獨自散發感性光芒',
          vi: 'Một mình tỏa sáng dưới ánh trăng đầy cảm xúc',
          id: 'Bersinar sendirian di bawah cahaya bulan dengan penuh mood',
        },
        score: 3,
      },
    ],
  },
  {
    id: 6,
    question: {
      ko: '내 목소리와 말투가 풍기는 색감은?',
      en: 'What color vibe does your voice and speaking style give off?',
      ja: '自分の声と話し方がまとっている色感は？',
      'zh-CN': '你的声音和说话方式散发出什么色感？',
      'zh-TW': '你的聲音和說話方式散發出什麼色感？',
      vi: 'Giọng nói và cách nói của bạn toát ra sắc màu nào?',
      id: 'Warna aura apa yang terasa dari suara dan gaya bicaramu?',
    },
    options: [
      {
        image: IMG(6, 'a'),
        label: {
          ko: '선명하고 강한 원색 계열의 색감',
          en: 'Vivid, strong primary-color vibes',
          ja: '鮮やかで強い原色系の色感',
          'zh-CN': '鲜明强烈的原色系色感',
          'zh-TW': '鮮明強烈的原色系色感',
          vi: 'Sắc màu nguyên bản rõ nét và mạnh mẽ',
          id: 'Nuansa warna primer yang tegas dan kuat',
        },
        score: 0,
      },
      {
        image: IMG(6, 'b'),
        label: {
          ko: '따뜻하고 밝은 오렌지·코랄 계열의 색감',
          en: 'Warm, bright orange and coral tones',
          ja: '暖かく明るいオレンジ・コーラル系の色感',
          'zh-CN': '温暖明亮的橙·珊瑚系色感',
          'zh-TW': '溫暖明亮的橙·珊瑚系色感',
          vi: 'Tông cam·coral ấm và sáng',
          id: 'Nuansa oranye·coral yang hangat dan cerah',
        },
        score: 1,
      },
      {
        image: IMG(6, 'c'),
        label: {
          ko: '차분하고 자연스러운 그린·민트 계열의 색감',
          en: 'Calm, natural green and mint tones',
          ja: '落ち着いた自然なグリーン・ミント系の色感',
          'zh-CN': '沉稳自然的绿·薄荷系色感',
          'zh-TW': '沉穩自然的綠·薄荷系色感',
          vi: 'Tông xanh·mint dịu và tự nhiên',
          id: 'Nuansa hijau·mint yang tenang dan natural',
        },
        score: 2,
      },
      {
        image: IMG(6, 'd'),
        label: {
          ko: '은은하고 부드러운 라벤더·블루 계열의 색감',
          en: 'Soft, subtle lavender and blue tones',
          ja: '控えめでやわらかいラベンダー・ブルー系の色感',
          'zh-CN': '柔和含蓄的薰衣草·蓝色系色感',
          'zh-TW': '柔和含蓄的薰衣草·藍色系色感',
          vi: 'Tông lavender·xanh dịu và mềm mại',
          id: 'Nuansa lavender·biru yang lembut dan subtle',
        },
        score: 3,
      },
    ],
  },
  {
    id: 7,
    question: {
      ko: '내 SNS 피드를 한 장으로 표현하면?',
      en: 'If your SNS feed were one image, what would it look like?',
      ja: '自分のSNSフィードを一枚で表すと？',
      'zh-CN': '如果用一张图概括你的社交动态？',
      'zh-TW': '如果用一張圖概括你的社交動態？',
      vi: 'Nếu gói feed mạng xã hội của bạn thành một ảnh?',
      id: 'Kalau feed SNS-mu digambarkan dalam satu gambar?',
    },
    options: [
      {
        image: IMG(7, 'a'),
        label: {
          ko: '강렬한 대비와 선명한 컬러의 눈에 띄는 피드',
          en: 'A standout feed with bold contrast and vivid colors',
          ja: '強いコントラストと鮮やかなカラーの目立つフィード',
          'zh-CN': '对比强烈、色彩鲜明的吸睛动态',
          'zh-TW': '對比強烈、色彩鮮明的吸睛動態',
          vi: 'Feed nổi bật với tương phản mạnh và màu sắc rõ nét',
          id: 'Feed mencolok dengan kontras kuat dan warna yang tajam',
        },
        score: 0,
      },
      {
        image: IMG(7, 'b'),
        label: {
          ko: '따뜻하고 밝은 계열의 생동감 있는 피드',
          en: 'A lively feed full of warm, bright tones',
          ja: '暖かく明るい系統の、生き生きしたフィード',
          'zh-CN': '温暖明亮、充满生气的动态',
          'zh-TW': '溫暖明亮、充滿生氣的動態',
          vi: 'Feed sống động với tông ấm và sáng',
          id: 'Feed yang hidup dengan nuansa hangat dan cerah',
        },
        score: 1,
      },
      {
        image: IMG(7, 'c'),
        label: {
          ko: '자연스럽고 차분한 그린·베이지 계열의 피드',
          en: 'A natural, calm feed in green and beige tones',
          ja: '自然で落ち着いたグリーン・ベージュ系のフィード',
          'zh-CN': '自然沉静的绿·米色系动态',
          'zh-TW': '自然沉靜的綠·米色系動態',
          vi: 'Feed dịu, tự nhiên với tông xanh·beige',
          id: 'Feed natural dan tenang dengan nuansa hijau·beige',
        },
        score: 2,
      },
      {
        image: IMG(7, 'd'),
        label: {
          ko: '파스텔·무드 있는 은은하고 감성적인 피드',
          en: 'A soft, moody pastel feed that’s quietly emotional',
          ja: 'パステルでムードのある、控えめに感性的なフィード',
          'zh-CN': '粉彩氛围感、含蓄又感性的动态',
          'zh-TW': '粉彩氛圍感、含蓄又感性的動態',
          vi: 'Feed pastel đầy mood — dịu dàng và cảm xúc',
          id: 'Feed pastel yang moody — lembut dan emosional',
        },
        score: 3,
      },
    ],
  },
  {
    id: 8,
    question: {
      ko: '처음 나를 만난 사람이 보게 되는 내 전체적인 이미지는?',
      en: 'What’s the overall first impression people get of you?',
      ja: '初めて会った人が見る自分の全体イメージは？',
      'zh-CN': '第一次见面的人对你的整体印象是？',
      'zh-TW': '第一次見面的人對你的整體印象是？',
      vi: 'Hình ảnh tổng thể người lần đầu gặp bạn thấy là gì?',
      id: 'Citra keseluruhan yang dilihat orang saat pertama bertemu denganmu?',
    },
    options: [
      {
        image: IMG(8, 'a'),
        label: {
          ko: '강렬하고 존재감이 확실한 사람',
          en: 'Someone intense with undeniable presence',
          ja: '強烈で存在感がはっきりした人',
          'zh-CN': '强烈、存在感很明确的人',
          'zh-TW': '強烈、存在感很明確的人',
          vi: 'Người mạnh mẽ, hiện diện rõ ràng',
          id: 'Orang yang kuat dengan presence yang jelas',
        },
        score: 0,
      },
      {
        image: IMG(8, 'b'),
        label: {
          ko: '따뜻하고 에너지가 넘치는 사람',
          en: 'Someone warm and full of energy',
          ja: '温かくてエネルギーにあふれた人',
          'zh-CN': '温暖、能量满满的人',
          'zh-TW': '溫暖、能量滿滿的人',
          vi: 'Người ấm áp, tràn đầy năng lượng',
          id: 'Orang yang hangat dan penuh energi',
        },
        score: 1,
      },
      {
        image: IMG(8, 'c'),
        label: {
          ko: '안정적이고 믿음직스러운 사람',
          en: 'Someone steady and trustworthy',
          ja: '安定感があって信頼できそうな人',
          'zh-CN': '安定、让人觉得可靠的人',
          'zh-TW': '安定、讓人覺得可靠的人',
          vi: 'Người ổn định, đáng tin cậy',
          id: 'Orang yang stabil dan bisa dipercaya',
        },
        score: 2,
      },
      {
        image: IMG(8, 'd'),
        label: {
          ko: '신비롭고 독특한 감성을 가진 사람',
          en: 'Someone mysterious with a unique sensibility',
          ja: '神秘的で独特な感性を持つ人',
          'zh-CN': '神秘、带着独特感性的人',
          'zh-TW': '神秘、帶著獨特感性的人',
          vi: 'Người huyền bí với cảm xúc độc đáo',
          id: 'Orang misterius dengan sensibilitas unik',
        },
        score: 3,
      },
    ],
  },
  {
    id: 9,
    question: {
      ko: '내가 가장 오래 머물고 싶은 공간의 분위기는?',
      en: 'What atmosphere makes you want to stay the longest?',
      ja: 'いちばん長くいたい空間の雰囲気は？',
      'zh-CN': '你最想久待的空间氛围是？',
      'zh-TW': '你最想久待的空間氛圍是？',
      vi: 'Không khí không gian bạn muốn ở lâu nhất là gì?',
      id: 'Suasana ruang mana yang paling ingin kamu tinggali lama?',
    },
    options: [
      {
        image: IMG(9, 'a'),
        label: {
          ko: '세련되고 강렬한 컬러의 힙한 루프탑 또는 바',
          en: 'A stylish rooftop or bar with bold, intense colors',
          ja: '洗練された強いカラーの、ヒップなルーフトップやバー',
          'zh-CN': '时髦的屋顶酒吧，色彩强烈又有质感',
          'zh-TW': '時髦的屋頂酒吧，色彩強烈又有質感',
          vi: 'Rooftop hoặc bar hip với màu sắc tinh tế, mạnh mẽ',
          id: 'Rooftop atau bar hip dengan warna yang stylish dan kuat',
        },
        score: 0,
      },
      {
        image: IMG(9, 'b'),
        label: {
          ko: '따뜻한 조명의 활기찬 브런치 카페',
          en: 'A lively brunch café with warm lighting',
          ja: '暖かい照明の、活気あるブランチカフェ',
          'zh-CN': '灯光温暖、热闹的早午餐咖啡馆',
          'zh-TW': '燈光溫暖、熱鬧的早午餐咖啡館',
          vi: 'Quán brunch nhộn nhịp với ánh sáng ấm',
          id: 'Kafe brunch yang ramai dengan pencahayaan hangat',
        },
        score: 1,
      },
      {
        image: IMG(9, 'c'),
        label: {
          ko: '싱그러운 식물이 가득한 조용한 정원 카페',
          en: 'A quiet garden café filled with fresh greenery',
          ja: 'みずみずしい植物がいっぱいの、静かな庭園カフェ',
          'zh-CN': '满是清新绿植的安静庭院咖啡馆',
          'zh-TW': '滿是清新綠植的安靜庭院咖啡館',
          vi: 'Quán cafe vườn yên tĩnh ngập cây xanh tươi',
          id: 'Kafe taman yang tenang penuh tanaman segar',
        },
        score: 2,
      },
      {
        image: IMG(9, 'd'),
        label: {
          ko: '달빛과 조용한 음악이 있는 야경 카페',
          en: 'A night-view café with moonlight and quiet music',
          ja: '月明かりと静かな音楽がある夜景カフェ',
          'zh-CN': '有月光和安静音乐的夜景咖啡馆',
          'zh-TW': '有月光和安靜音樂的夜景咖啡館',
          vi: 'Quán cafe ngắm đêm với ánh trăng và nhạc nhẹ',
          id: 'Kafe pemandangan malam dengan cahaya bulan dan musik tenang',
        },
        score: 3,
      },
    ],
  },
  {
    id: 10,
    question: {
      ko: '내 감정이 가장 솔직하게 드러나는 색깔 이미지는?',
      en: 'Which color image shows your emotions most honestly?',
      ja: '自分の感情がいちばん正直に出るカラーイメージは？',
      'zh-CN': '哪个颜色画面最能诚实展现你的情绪？',
      'zh-TW': '哪個顏色畫面最能誠實展現你的情緒？',
      vi: 'Hình ảnh màu nào lộ cảm xúc thật của bạn nhất?',
      id: 'Citra warna mana yang paling jujur menampilkan emosimu?',
    },
    options: [
      {
        image: IMG(10, 'a'),
        label: {
          ko: '강렬하게 타오르는 불꽃',
          en: 'A fiercely burning flame',
          ja: '激しく燃え上がる炎',
          'zh-CN': '熊熊燃烧的烈焰',
          'zh-TW': '熊熊燃燒的烈焰',
          vi: 'Ngọn lửa cháy dữ dội',
          id: 'Api yang menyala dengan intens',
        },
        score: 0,
      },
      {
        image: IMG(10, 'b'),
        label: {
          ko: '따뜻하게 빛나는 일출',
          en: 'A warmly glowing sunrise',
          ja: 'あたたかく輝く日の出',
          'zh-CN': '温暖发光的日出',
          'zh-TW': '溫暖發光的日出',
          vi: 'Bình minh ấm áp rực sáng',
          id: 'Matahari terbit yang bersinar hangat',
        },
        score: 1,
      },
      {
        image: IMG(10, 'c'),
        label: {
          ko: '싱그럽게 흔들리는 봄 숲',
          en: 'A fresh spring forest swaying gently',
          ja: 'みずみずしく揺れる春の森',
          'zh-CN': '轻轻摇曳的清新春日树林',
          'zh-TW': '輕輕搖曳的清新春日樹林',
          vi: 'Rừng xuân xanh mát đang đung đưa',
          id: 'Hutan musim semi yang segar dan bergoyang lembut',
        },
        score: 2,
      },
      {
        image: IMG(10, 'd'),
        label: {
          ko: '고요하게 빛나는 보름달',
          en: 'A quietly shining full moon',
          ja: '静かに輝く満月',
          'zh-CN': '静静发光的满月',
          'zh-TW': '靜靜發光的滿月',
          vi: 'Trăng tròn lặng lẽ tỏa sáng',
          id: 'Bulan purnama yang bersinar tenang',
        },
        score: 3,
      },
    ],
  },
  {
    id: 11,
    question: {
      ko: '친한 친구들이 나를 소개할 때 쓰는 표현과 가장 가까운 이미지는?',
      en: 'Which image is closest to how close friends introduce you?',
      ja: '親しい友だちが自分を紹介するときの表現にいちばん近いイメージは？',
      'zh-CN': '哪个画面最接近好友介绍你时用的说法？',
      'zh-TW': '哪個畫面最接近好友介紹你時用的說法？',
      vi: 'Hình ảnh nào gần với cách bạn thân giới thiệu bạn nhất?',
      id: 'Citra mana yang paling dekat dengan cara teman dekat memperkenalkanmu?',
    },
    options: [
      {
        image: IMG(11, 'a'),
        label: {
          ko: '선명하고 강한 원색 문자들 - "존재감·카리스마·강렬한"',
          en: 'Bold primary-color words — "presence · charisma · intense"',
          ja: '鮮やかで強い原色の文字 — 「存在感・カリスマ・強烈」',
          'zh-CN': '鲜明强烈的原色文字 — “存在感·魅力·强烈”',
          'zh-TW': '鮮明強烈的原色文字 — 「存在感·魅力·強烈」',
          vi: 'Chữ màu nguyên bản rõ nét — "hiện diện · khí chất · mạnh mẽ"',
          id: 'Kata warna primer yang tegas — "presence · karisma · intense"',
        },
        score: 0,
      },
      {
        image: IMG(11, 'b'),
        label: {
          ko: '따뜻한 컬러 문자들 - "밝음·활기·따뜻한"',
          en: 'Warm-colored words — "bright · lively · warm"',
          ja: '暖かいカラーの文字 — 「明るさ・活気・温かさ」',
          'zh-CN': '温暖色文字 — “明亮·活力·温暖”',
          'zh-TW': '溫暖色文字 — 「明亮·活力·溫暖」',
          vi: 'Chữ tông ấm — "sáng · sống động · ấm áp"',
          id: 'Kata warna hangat — "cerah · hidup · hangat"',
        },
        score: 1,
      },
      {
        image: IMG(11, 'c'),
        label: {
          ko: '자연스러운 그린 문자들 - "편안·안정·믿음직한"',
          en: 'Natural green words — "comfortable · steady · reliable"',
          ja: '自然なグリーンの文字 — 「心地よさ・安定・信頼」',
          'zh-CN': '自然绿色文字 — “舒适·安定·可靠”',
          'zh-TW': '自然綠色文字 — 「舒適·安定·可靠」',
          vi: 'Chữ xanh tự nhiên — "thoải mái · ổn định · đáng tin"',
          id: 'Kata hijau natural — "nyaman · stabil · bisa dipercaya"',
        },
        score: 2,
      },
      {
        image: IMG(11, 'd'),
        label: {
          ko: '감성적인 라벤더 문자들 - "신비·감성·독특한"',
          en: 'Emotional lavender words — "mysterious · sensitive · unique"',
          ja: '感性的なラベンダーの文字 — 「神秘・感性・ユニーク」',
          'zh-CN': '感性的薰衣草文字 — “神秘·感性·独特”',
          'zh-TW': '感性的薰衣草文字 — 「神秘·感性·獨特」',
          vi: 'Chữ lavender đầy cảm xúc — "huyền bí · nhạy cảm · độc đáo"',
          id: 'Kata lavender yang emosional — "misterius · sensitif · unik"',
        },
        score: 3,
      },
    ],
  },
  {
    id: 12,
    question: {
      ko: '지금 이 순간 내 컬러 정체성을 가장 잘 표현한 이미지는?',
      en: 'Which image best expresses your color identity right now?',
      ja: '今この瞬間の自分のカラーアイデンティティをいちばんよく表すイメージは？',
      'zh-CN': '此刻哪个画面最能表达你的色彩身份？',
      'zh-TW': '此刻哪個畫面最能表達你的色彩身份？',
      vi: 'Hình ảnh nào diễn tả bản sắc màu của bạn lúc này nhất?',
      id: 'Citra mana yang paling menggambarkan identitas warnamu saat ini?',
    },
    options: [
      {
        image: IMG(12, 'a'),
        label: {
          ko: '강렬한 레드 장미 한 송이',
          en: 'One intense red rose',
          ja: '強烈な赤いバラが一輪',
          'zh-CN': '一朵强烈的红玫瑰',
          'zh-TW': '一朵強烈的紅玫瑰',
          vi: 'Một đóa hồng đỏ mãnh liệt',
          id: 'Satu mawar merah yang intense',
        },
        score: 0,
      },
      {
        image: IMG(12, 'b'),
        label: {
          ko: '따뜻한 해바라기 꽃밭',
          en: 'A warm field of sunflowers',
          ja: 'あたたかいひまわり畑',
          'zh-CN': '温暖的向日葵花田',
          'zh-TW': '溫暖的向日葵花田',
          vi: 'Cánh đồng hướng dương ấm áp',
          id: 'Ladang bunga matahari yang hangat',
        },
        score: 1,
      },
      {
        image: IMG(12, 'c'),
        label: {
          ko: '싱그러운 민트 유칼립투스',
          en: 'Fresh mint eucalyptus',
          ja: 'みずみずしいミントのユーカリ',
          'zh-CN': '清新的薄荷尤加利',
          'zh-TW': '清新的薄荷尤加利',
          vi: 'Khuynh diệp mint tươi mát',
          id: 'Eucalyptus mint yang segar',
        },
        score: 2,
      },
      {
        image: IMG(12, 'd'),
        label: {
          ko: '신비로운 라벤더 들판',
          en: 'A mysterious lavender field',
          ja: '神秘的なラベンダー畑',
          'zh-CN': '神秘的薰衣草田野',
          'zh-TW': '神秘的薰衣草田野',
          vi: 'Cánh đồng lavender huyền bí',
          id: 'Ladang lavender yang misterius',
        },
        score: 3,
      },
    ],
  },
];

export const phase3FirstImpressionColorScannerResults: Phase3FirstImpressionColorScannerResult[] = [
  {
    type: 'Type1',
    emoji: '🔴',
    title: {
      ko: '처음 봐도 잊히지 않는, 레드 카리스마 컬러',
      en: 'Unforgettable at first sight — Red Charisma Color',
      ja: '一目で忘れられない、レッドカリスマカラー',
      'zh-CN': '一眼难忘的红色魅力色',
      'zh-TW': '一眼難忘的紅色魅力色',
      vi: 'Nhìn một lần khó quên — Màu Red Charisma',
      id: 'Tak terlupakan sejak pandangan pertama — Warna Red Charisma',
    },
    shortDescription: {
      ko: '당신은 방에 들어서는 순간 공기가 바뀌는 사람입니다',
      en: 'You’re the kind of person who changes the air the moment you walk in',
      ja: '部屋に入った瞬間、空気が変わる人です',
      'zh-CN': '你是那种一进门空气就变了的人',
      'zh-TW': '你是那種一進門空氣就變了的人',
      vi: 'Bạn là người khiến không khí đổi ngay khi bước vào phòng',
      id: 'Kamu tipe yang mengubah udara ruangan begitu masuk',
    },
    description: {
      ko: '처음 만난 사람들이 가장 먼저 느끼는 것은 존재감입니다. 화려하게 꾸미지 않아도, 먼저 말을 걸지 않아도 당신이 있는 공간의 온도가 달라집니다.\n\n강렬하고 선명한 레드 컬러처럼 한 번 보면 기억에 남습니다.',
      en: 'What people notice first is your presence. Even without dressing flashy or speaking first, the temperature of the room shifts when you’re there.\n\nLike a vivid, intense red — once seen, you’re hard to forget.',
      ja: '初対面の人が最初に感じるのは存在感です。派手に着飾らなくても、先に話しかけなくても、あなたがいる空間の温度は変わります。\n\n強烈で鮮やかなレッドのように、一度見たら記憶に残ります。',
      'zh-CN': '初次见面的人最先感受到的是你的存在感。不必打扮华丽，也不必先开口，你所在之处的温度就会不同。\n\n像鲜明强烈的红色一样，看过一次就会记住。',
      'zh-TW': '初次見面的人最先感受到的是你的存在感。不必打扮華麗，也不必先開口，你所在之處的溫度就會不同。\n\n像鮮明強烈的紅色一樣，看過一次就會記住。',
      vi: 'Điều người ta cảm nhận đầu tiên là sự hiện diện của bạn. Không cần ăn mặc nổi bật hay mở lời trước, nhiệt độ không gian vẫn đổi khi bạn ở đó.\n\nNhư màu đỏ rõ nét, mạnh mẽ — nhìn một lần là nhớ.',
      id: 'Yang pertama dirasakan orang adalah presence-mu. Tanpa berdandan mencolok atau bicara duluan, suhu ruangan berubah saat kamu ada.\n\nSeperti merah yang tajam dan kuat — sekali dilihat, sulit dilupakan.',
    },
    firstImpressionColor: {
      ko: '레드 🔴',
      en: 'Red 🔴',
      ja: 'レッド 🔴',
      'zh-CN': '红色 🔴',
      'zh-TW': '紅色 🔴',
      vi: 'Đỏ 🔴',
      id: 'Merah 🔴',
    },
    colorKeywords: {
      ko: '강렬함,카리스마,존재감,자신감,열정',
      en: 'intensity,charisma,presence,confidence,passion',
      ja: '強烈さ,カリスマ,存在感,自信,情熱',
      'zh-CN': '强烈,魅力,存在感,自信,热情',
      'zh-TW': '強烈,魅力,存在感,自信,熱情',
      vi: 'mãnh liệt,khí chất,hiện diện,tự tin,đam mê',
      id: 'intensitas,karisma,presence,percaya diri,gairah',
    },
    firstFeeling: {
      ko: '"왠지 저 사람 만만하지 않을 것 같아" · "저 사람 눈빛이 강하다"',
      en: '"They don’t seem like someone you can underestimate" · "Their eyes are intense"',
      ja: '「なんかあの人、なめてかかったら危険そう」 · 「あの人の眼差しが強い」',
      'zh-CN': '“感觉那个人不好惹” · “那个人的眼神好强”',
      'zh-TW': '「感覺那個人不好惹」 · 「那個人的眼神好強」',
      vi: '"Hình như người kia không dễ ăn đâu" · "Ánh mắt họ thật mạnh"',
      id: '"Kayaknya orang itu nggak bisa diremehkan" · "Tatapan matanya kuat banget"',
    },
    shiningMoment: {
      ko: '중요한 발표·협상·리더십이 필요한 순간',
      en: 'Big presentations, negotiations, or moments that need leadership',
      ja: '大事な発表・交渉・リーダーシップが必要な瞬間',
      'zh-CN': '重要发表、谈判、需要领导力的时刻',
      'zh-TW': '重要發表、談判、需要領導力的時刻',
      vi: 'Lúc thuyết trình lớn, đàm phán, hoặc cần lãnh đạo',
      id: 'Momen presentasi penting, negosiasi, atau saat kepemimpinan dibutuhkan',
    },
    reverseCharm: {
      ko: '알면 알수록 의외로 따뜻하고 의리 있는 사람이라는 걸 발견하게 됨',
      en: 'The closer people get, the more they discover how unexpectedly warm and loyal you are',
      ja: '知るほど意外と温かく、義理人情のある人だと気づかれる',
      'zh-CN': '越了解越发现你其实意外温暖、很讲义气',
      'zh-TW': '越了解越發現你其實意外溫暖、很講義氣',
      vi: 'Càng hiểu càng thấy bạn ấm áp và rất trọng tình ngoài mong đợi',
      id: 'Semakin dekat, orang semakin menemukan betapa hangat dan setianya kamu — di luar dugaan',
    },
    matchingColors: {
      ko: '화이트(깔끔한 균형) · 블랙(강렬함 극대화)',
      en: 'White (clean balance) · Black (maximizes intensity)',
      ja: 'ホワイト（きれいなバランス） · ブラック（強烈さを最大化）',
      'zh-CN': '白色（干净平衡） · 黑色（把强烈感拉满）',
      'zh-TW': '白色（乾淨平衡） · 黑色（把強烈感拉滿）',
      vi: 'Trắng (cân bằng sạch sẽ) · Đen (tăng cường độ mạnh)',
      id: 'Putih (keseimbangan bersih) · Hitam (memaksimalkan intensitas)',
    },
    personalColorLink: {
      ko: '겨울 쿨톤 또는 가을 웜톤 계열과 잘 어울리는 경향',
      en: 'Often suits Winter Cool or Autumn Warm personal color tones',
      ja: 'ウィンタークールまたはオータムウォーム系統と相性がよい傾向',
      'zh-CN': '往往与冬冷色或秋暖色系更搭',
      'zh-TW': '往往與冬冷色或秋暖色系更搭',
      vi: 'Thường hợp với tông Winter Cool hoặc Autumn Warm',
      id: 'Cenderung cocok dengan tone Winter Cool atau Autumn Warm',
    },
    shareSnippet: {
      ko: '내 첫인상 컬러: 레드 카리스마 🔴 처음 봐도 잊히지 않는 강렬한 인상이래... 존재감 인정 ㅋㅋ → 너는 어떤 컬러야? 퍼스널 컬러랑 비교해봐',
      en: 'My first-impression color: Red Charisma 🔴 They said I’m unforgettable and intense... presence unlocked lol → What’s yours? Compare it with your personal color!',
      ja: '私の第一印象カラー：レッドカリスマ 🔴 一目で忘れられない強烈な印象らしい…存在感認めますw → あなたは何色？パーソナルカラーと比べてみて',
      'zh-CN': '我的第一印象色：红色魅力 🔴 说是一眼难忘的强烈印象…存在感实锤哈哈 → 你是什么色？跟你的个人色彩比比看',
      'zh-TW': '我的第一印象色：紅色魅力 🔴 說是一眼難忘的強烈印象…存在感實錘哈哈 → 你是什麼色？跟你的個人色彩比比看',
      vi: 'Màu ấn tượng đầu của mình: Red Charisma 🔴 Nghe bảo nhìn một lần khó quên và rất mạnh... hiện diện đúng thật haha → Còn bạn màu gì? So với personal color đi!',
      id: 'Warna first impression-ku: Red Charisma 🔴 Katanya tak terlupakan dan intense... presence unlocked wkwk → Kamu warna apa? Bandingkan dengan personal color-mu!',
    },
  },
  {
    type: 'Type2',
    emoji: '🧡',
    title: {
      ko: '있으면 분위기가 살아나는, 코랄 에너지 컬러',
      en: 'The room comes alive with you — Coral Energy Color',
      ja: 'いるだけで場が盛り上がる、コーラルエネルギーカラー',
      'zh-CN': '一出现气氛就活起来的珊瑚能量色',
      'zh-TW': '一出現氣氛就活起來的珊瑚能量色',
      vi: 'Có bạn là không khí sống dậy — Màu Coral Energy',
      id: 'Ruangan jadi hidup saat kamu datang — Warna Coral Energy',
    },
    shortDescription: {
      ko: '당신이 오면 모임이 시작됩니다',
      en: 'The gathering really starts when you arrive',
      ja: 'あなたが来ると、集まりが始まります',
      'zh-CN': '你一到，聚会才算真正开始',
      'zh-TW': '你一到，聚會才算真正開始',
      vi: 'Buổi tụ họp bắt đầu khi bạn xuất hiện',
      id: 'Kumpulan baru benar-benar dimulai saat kamu datang',
    },
    description: {
      ko: '따뜻하고 생동감 있는 코랄 컬러처럼 당신이 있는 곳엔 활기가 생깁니다. 처음 보는 사람도 금방 편안해지게 만드는 에너지가 있고 분위기를 밝게 만드는 것이 자연스럽습니다.\n\n웃음이 많고 긍정적인 첫인상을 줍니다.',
      en: 'Like warm, lively coral, wherever you are, energy follows. You put first-timers at ease fast, and brightening the mood comes naturally.\n\nPeople leave with a cheerful, positive first impression of you.',
      ja: '暖かく生き生きしたコーラルのように、あなたがいる場所には活気が生まれます。初対面でもすぐ安心させるエネルギーがあり、場を明るくするのが自然です。\n\n笑顔が多く、ポジティブな第一印象を与えます。',
      'zh-CN': '像温暖有活力的珊瑚色一样，你在哪里，哪里就有生气。即使第一次见面也能很快让人放松，点亮气氛对你来说很自然。\n\n给人的第一印象是爱笑、正向。',
      'zh-TW': '像溫暖有活力的珊瑚色一樣，你在哪裡，哪裡就有生氣。即使第一次見面也能很快讓人放鬆，點亮氣氛對你來說很自然。\n\n給人的第一印象是愛笑、正向。',
      vi: 'Như màu coral ấm và sống động, nơi bạn ở luôn có sức sống. Bạn khiến người lạ nhanh thấy thoải mái, và làm sáng không khí là điều rất tự nhiên.\n\nẤn tượng đầu là nhiều tiếng cười và tích cực.',
      id: 'Seperti coral yang hangat dan hidup, di mana kamu ada, energi ikut muncul. Orang baru cepat merasa nyaman, dan mencerahkan suasana terasa natural bagimu.\n\nFirst impression-mu penuh tawa dan positif.',
    },
    firstImpressionColor: {
      ko: '코랄·오렌지 🧡',
      en: 'Coral · Orange 🧡',
      ja: 'コーラル・オレンジ 🧡',
      'zh-CN': '珊瑚·橙色 🧡',
      'zh-TW': '珊瑚·橙色 🧡',
      vi: 'Coral · Cam 🧡',
      id: 'Coral · Oranye 🧡',
    },
    colorKeywords: {
      ko: '활기,따뜻함,밝음,사교성,생동감',
      en: 'liveliness,warmth,brightness,sociability,vitality',
      ja: '活気,温かさ,明るさ,社交性,生命力',
      'zh-CN': '活力,温暖,明亮,社交,生气',
      'zh-TW': '活力,溫暖,明亮,社交,生氣',
      vi: 'sống động,ấm áp,tươi sáng,hòa đồng,sinh khí',
      id: 'semangat,kehangatan,kecerahan,sosialitas,vitalitas',
    },
    firstFeeling: {
      ko: '"왠지 저 사람이랑 친해질 수 있을 것 같아" · "에너지 넘친다"',
      en: '"I feel like I could get close to them" · "They’re full of energy"',
      ja: '「なんかあの人ともっと仲良くなれそう」 · 「エネルギーに満ちてる」',
      'zh-CN': '“感觉能和那个人变熟” · “能量好满”',
      'zh-TW': '「感覺能和那個人變熟」 · 「能量好滿」',
      vi: '"Hình như mình có thể thân với họ" · "Năng lượng tràn đầy"',
      id: '"Kayaknya aku bisa akrab sama orang itu" · "Energinya overflowing"',
    },
    shiningMoment: {
      ko: '새로운 만남·파티·팀 분위기를 살려야 할 때',
      en: 'New meetups, parties, or when the team needs a vibe boost',
      ja: '新しい出会い・パーティー・チームの空気を盛り上げたいとき',
      'zh-CN': '新认识、派对、需要带起团队气氛时',
      'zh-TW': '新認識、派對、需要帶起團隊氣氛時',
      vi: 'Gặp gỡ mới, tiệc, hoặc khi cần làm sống đội nhóm',
      id: 'Pertemuan baru, pesta, atau saat suasana tim perlu dihidupkan',
    },
    reverseCharm: {
      ko: '겉으로는 밝아 보이지만 사실 섬세하게 상대방을 챙기는 사람',
      en: 'You look bright on the outside, but you’re actually carefully looking after people',
      ja: '外見は明るいのに、実は細やかに相手を気遣う人',
      'zh-CN': '外表看起来开朗，其实会细心照顾对方',
      'zh-TW': '外表看起來開朗，其實會細心照顧對方',
      vi: 'Bề ngoài sáng nhưng thật ra rất tinh tế chăm người khác',
      id: 'Kelihatan cerah di luar, tapi sebenarnya sangat teliti menjaga orang lain',
    },
    matchingColors: {
      ko: '화이트(환함 강조) · 네이비(생동감과 안정의 균형)',
      en: 'White (boosts brightness) · Navy (balances vitality and calm)',
      ja: 'ホワイト（明るさ強調） · ネイビー（活気と安定のバランス）',
      'zh-CN': '白色（突出明亮） · 海军蓝（平衡活力与安定）',
      'zh-TW': '白色（突出明亮） · 海軍藍（平衡活力與安定）',
      vi: 'Trắng (làm sáng hơn) · Navy (cân bằng sống động và ổn định)',
      id: 'Putih (menonjolkan kecerahan) · Navy (keseimbangan vitalitas dan ketenangan)',
    },
    personalColorLink: {
      ko: '봄 웜톤 계열과 잘 어울리는 경향',
      en: 'Often suits Spring Warm personal color tones',
      ja: 'スプリングウォーム系統と相性がよい傾向',
      'zh-CN': '往往与春暖色系更搭',
      'zh-TW': '往往與春暖色系更搭',
      vi: 'Thường hợp với tông Spring Warm',
      id: 'Cenderung cocok dengan tone Spring Warm',
    },
    shareSnippet: {
      ko: '내 첫인상 컬러: 코랄 에너지 🧡 내가 오면 모임이 시작된다는 거... 분위기 메이커 맞긴 함 → 너는 어떤 컬러야?',
      en: 'My first-impression color: Coral Energy 🧡 Apparently the party starts when I walk in... mood maker confirmed → What’s your color?',
      ja: '私の第一印象カラー：コーラルエネルギー 🧡 私が来ると集まりが始まるらしい…ムードメーカー正解かも → あなたは何色？',
      'zh-CN': '我的第一印象色：珊瑚能量 🧡 说我一到聚会才开始…气氛担当实锤 → 你是什么色？',
      'zh-TW': '我的第一印象色：珊瑚能量 🧡 說我一到聚會才開始…氣氛擔當實錘 → 你是什麼色？',
      vi: 'Màu ấn tượng đầu của mình: Coral Energy 🧡 Nghe bảo mình tới là buổi tụ họp bắt đầu... mood maker đúng rồi → Bạn màu gì?',
      id: 'Warna first impression-ku: Coral Energy 🧡 Katanya kumpulan baru mulai saat aku datang... mood maker confirmed → Kamu warna apa?',
    },
  },
  {
    type: 'Type3',
    emoji: '💛',
    title: {
      ko: '보면 기분이 좋아지는, 골드 햇살 컬러',
      en: 'Just seeing you brightens the day — Gold Sunshine Color',
      ja: '見るだけで気分が上がる、ゴールドサンシャインカラー',
      'zh-CN': '一看就开心的金色阳光色',
      'zh-TW': '一看就開心的金色陽光色',
      vi: 'Nhìn là thấy vui — Màu Gold Sunshine',
      id: 'Hanya melihatmu sudah bikin mood naik — Warna Gold Sunshine',
    },
    shortDescription: {
      ko: '당신은 주변 사람들을 덩달아 밝게 만드는 사람입니다',
      en: 'You make everyone around you brighter too',
      ja: '周りの人もつられて明るくなる人です',
      'zh-CN': '你是那种能把身边人一起点亮的人',
      'zh-TW': '你是那種能把身邊人一起點亮的人',
      vi: 'Bạn khiến người quanh mình cũng sáng lên theo',
      id: 'Kamu membuat orang di sekitarmu ikut jadi lebih cerah',
    },
    description: {
      ko: '햇살 같은 골드 컬러처럼 당신 곁에 있으면 이유 없이 기분이 좋아집니다. 유쾌하고 긍정적인 에너지가 자연스럽게 흘러나오며 처음 보는 사람도 금방 마음이 열립니다.\n\n밝은 첫인상과 함께 의외의 깊이가 있는 사람입니다.',
      en: 'Like gold sunshine, people feel happier near you for no clear reason. Cheerful, positive energy flows out naturally, and even strangers open up quickly.\n\nYou give a bright first impression — with surprising depth underneath.',
      ja: '日差しのようなゴールドのように、あなたのそばにいると理由もなく気分がよくなります。陽気でポジティブなエネルギーが自然にあふれ、初対面でもすぐ心が開きます。\n\n明るい第一印象の裏に、意外な深さもある人です。',
      'zh-CN': '像阳光般的金色一样，待在你身边会无缘无故开心起来。愉快正向的能量自然流露，初次见面的人也很快敞开心扉。\n\n明亮的第一印象之外，还有意外的深度。',
      'zh-TW': '像陽光般的金色一樣，待在你身邊會無緣無故開心起來。愉快正向的能量自然流露，初次見面的人也很快敞開心扉。\n\n明亮的第一印象之外，還有意外的深度。',
      vi: 'Như vàng ánh nắng, bên cạnh bạn người ta vui lên chẳng cần lý do. Năng lượng vui vẻ, tích cực tự nhiên tràn ra, và người lạ cũng mau mở lòng.\n\nẤn tượng đầu tươi sáng — kèm chiều sâu bất ngờ bên trong.',
      id: 'Seperti emas matahari, di dekatmu orang jadi senang tanpa alasan jelas. Energi ceria dan positif mengalir natural, dan orang baru pun cepat terbuka.\n\nFirst impression-mu cerah — dengan kedalaman yang mengejutkan di baliknya.',
    },
    firstImpressionColor: {
      ko: '골드·옐로우 💛',
      en: 'Gold · Yellow 💛',
      ja: 'ゴールド・イエロー 💛',
      'zh-CN': '金色·黄色 💛',
      'zh-TW': '金色·黃色 💛',
      vi: 'Vàng · Yellow 💛',
      id: 'Emas · Kuning 💛',
    },
    colorKeywords: {
      ko: '밝음,유쾌함,긍정성,친근감,햇살 같은 에너지',
      en: 'brightness,cheerfulness,positivity,friendliness,sunshine energy',
      ja: '明るさ,陽気さ,ポジティブ,親しみやすさ,日差しのようなエネルギー',
      'zh-CN': '明亮,愉快,正向,亲切,阳光般的能量',
      'zh-TW': '明亮,愉快,正向,親切,陽光般的能量',
      vi: 'tươi sáng,vui vẻ,tích cực,thân thiện,năng lượng như nắng',
      id: 'kecerahan,keceriaan,positivitas,keramahan,energi seperti matahari',
    },
    firstFeeling: {
      ko: '"왠지 기분이 좋아지는 사람이야" · "같이 있으면 즐겁겠다"',
      en: '"Being around them somehow lifts my mood" · "It’d be fun to hang out with them"',
      ja: '「なんか気分が上がる人だな」 · 「一緒にいたら楽しそう」',
      'zh-CN': '“感觉跟这个人在一起心情会变好” · “一起玩一定很开心”',
      'zh-TW': '「感覺跟這個人在一起心情會變好」 · 「一起玩一定很開心」',
      vi: '"Ở gần họ tự nhiên vui hơn" · "Ở cùng chắc vui lắm"',
      id: '"Kayaknya mood naik kalau deket orang ini" · "Seru deh kalau bareng"',
    },
    shiningMoment: {
      ko: '힘든 사람을 위로할 때·어색한 분위기를 풀 때',
      en: 'When comforting someone who’s struggling or breaking an awkward silence',
      ja: 'つらい人を慰めるとき・気まずい空気をほぐすとき',
      'zh-CN': '安慰难受的人、化解尴尬气氛时',
      'zh-TW': '安慰難受的人、化解尷尬氣氛時',
      vi: 'Khi an ủi người khó khăn hoặc gỡ bầu không khí ngượng',
      id: 'Saat menghibur orang yang sedang berat atau mencairkan suasana canggung',
    },
    reverseCharm: {
      ko: '밝아 보여서 가볍게 느껴지지만 실제로는 신중하고 섬세한 사람',
      en: 'You seem light because you’re bright — but you’re actually careful and sensitive',
      ja: '明るいから軽く見られがちだけど、実は慎重で繊細な人',
      'zh-CN': '因为开朗显得轻巧，其实很慎重、很细腻',
      'zh-TW': '因為開朗顯得輕巧，其實很慎重、很細膩',
      vi: 'Trông sáng nên dễ bị nghĩ nhẹ — thật ra rất thận trọng và tinh tế',
      id: 'Terlihat ringan karena cerah — padahal sebenarnya hati-hati dan sensitif',
    },
    matchingColors: {
      ko: '화이트(환한 조화) · 딥그린(안정감 추가)',
      en: 'White (bright harmony) · Deep green (adds steadiness)',
      ja: 'ホワイト（明るい調和） · ディープグリーン（安定感をプラス）',
      'zh-CN': '白色（明亮和谐） · 深绿（增添安定感）',
      'zh-TW': '白色（明亮和諧） · 深綠（增添安定感）',
      vi: 'Trắng (hài hòa sáng) · Xanh đậm (thêm ổn định)',
      id: 'Putih (harmoni cerah) · Hijau dalam (menambah kestabilan)',
    },
    personalColorLink: {
      ko: '봄 웜톤 또는 가을 웜톤 계열과 잘 어울리는 경향',
      en: 'Often suits Spring Warm or Autumn Warm personal color tones',
      ja: 'スプリングウォームまたはオータムウォーム系統と相性がよい傾向',
      'zh-CN': '往往与春暖色或秋暖色系更搭',
      'zh-TW': '往往與春暖色或秋暖色系更搭',
      vi: 'Thường hợp với tông Spring Warm hoặc Autumn Warm',
      id: 'Cenderung cocok dengan tone Spring Warm atau Autumn Warm',
    },
    shareSnippet: {
      ko: '내 첫인상 컬러: 골드 햇살 💛 보면 기분 좋아지는 사람이래... 이거 칭찬 맞죠? ㅋㅋ → 너는 어떤 첫인상 컬러야?',
      en: 'My first-impression color: Gold Sunshine 💛 They said just seeing me lifts the mood... that’s a compliment, right? lol → What’s your first-impression color?',
      ja: '私の第一印象カラー：ゴールドサンシャイン 💛 見るだけで気分が上がる人らしい…これ褒め言葉だよね？w → あなたの第一印象カラーは？',
      'zh-CN': '我的第一印象色：金色阳光 💛 说一看就开心…这是夸奖吧？哈哈 → 你的第一印象色是什么？',
      'zh-TW': '我的第一印象色：金色陽光 💛 說一看就開心…這是誇獎吧？哈哈 → 你的第一印象色是什麼？',
      vi: 'Màu ấn tượng đầu của mình: Gold Sunshine 💛 Nghe bảo nhìn là thấy vui... đây là lời khen đúng không? haha → Màu ấn tượng đầu của bạn là gì?',
      id: 'Warna first impression-ku: Gold Sunshine 💛 Katanya melihatku bikin mood naik... ini pujian kan? wkwk → First-impression color-mu apa?',
    },
  },
  {
    type: 'Type4',
    emoji: '💚',
    title: {
      ko: '곁에 있으면 안심되는, 민트 안정 컬러',
      en: 'You feel safe beside them — Mint Calm Color',
      ja: 'そばにいると安心する、ミント安定カラー',
      'zh-CN': '待在身边就安心的薄荷安定色',
      'zh-TW': '待在身邊就安心的薄荷安定色',
      vi: 'Bên cạnh là thấy yên — Màu Mint Calm',
      id: 'Di sampingmu rasanya aman — Warna Mint Calm',
    },
    shortDescription: {
      ko: '당신 곁에 있으면 왠지 모르게 마음이 놓입니다',
      en: 'Being near you somehow puts people’s hearts at ease',
      ja: 'あなたのそばにいると、なぜか心が落ち着きます',
      'zh-CN': '待在你身边，莫名就安心了',
      'zh-TW': '待在你身邊，莫名就安心了',
      vi: 'Ở gần bạn, lòng người tự nhiên thấy nhẹ',
      id: 'Di dekatmu, hati orang entah kenapa jadi tenang',
    },
    description: {
      ko: '싱그럽고 안정적인 민트 컬러처럼 당신의 존재 자체가 주변을 편안하게 만듭니다. 강렬하진 않지만 오래 볼수록 좋고 처음 만난 사람도 금방 마음을 여는 신뢰감 있는 첫인상입니다.',
      en: 'Like fresh, steady mint, your presence alone makes people comfortable. You’re not flashy, but the longer people know you, the better you feel — a trustworthy first impression that opens hearts fast.',
      ja: 'みずみずしく安定したミントのように、あなたの存在そのものが周りをくつろがせます。強烈ではないけれど、長く見るほどよく、初対面でもすぐ心を開かせる信頼感のある第一印象です。',
      'zh-CN': '像清新安定的薄荷色一样，你的存在本身就让人放松。不张扬，但越看越喜欢，初次见面也能很快让人敞开心扉——是可信的第一印象。',
      'zh-TW': '像清新安定的薄荷色一樣，你的存在本身就讓人放鬆。不張揚，但越看越喜歡，初次見面也能很快讓人敞開心扉——是可信的第一印象。',
      vi: 'Như mint tươi và ổn định, sự hiện diện của bạn khiến người khác dễ chịu. Không mãnh liệt, nhưng càng quen càng thích — ấn tượng đầu đáng tin khiến lòng mau mở.',
      id: 'Seperti mint yang segar dan stabil, kehadiranmu saja sudah membuat orang nyaman. Tidak mencolok, tapi semakin lama semakin enak — first impression yang bisa dipercaya dan cepat membuka hati.',
    },
    firstImpressionColor: {
      ko: '민트·그린 💚',
      en: 'Mint · Green 💚',
      ja: 'ミント・グリーン 💚',
      'zh-CN': '薄荷·绿色 💚',
      'zh-TW': '薄荷·綠色 💚',
      vi: 'Mint · Xanh 💚',
      id: 'Mint · Hijau 💚',
    },
    colorKeywords: {
      ko: '편안함,신뢰,안정감,자연스러움,진정성',
      en: 'comfort,trust,stability,naturalness,authenticity',
      ja: '心地よさ,信頼,安定感,自然さ,誠実さ',
      'zh-CN': '舒适,信任,安定,自然,真诚',
      'zh-TW': '舒適,信任,安定,自然,真誠',
      vi: 'thoải mái,tin cậy,ổn định,tự nhiên,chân thành',
      id: 'kenyamanan,kepercayaan,kestabilan,naturalitas,keaslian',
    },
    firstFeeling: {
      ko: '"왠지 믿을 수 있는 사람 같아" · "같이 있으면 편하다"',
      en: '"They seem trustworthy somehow" · "Being with them feels easy"',
      ja: '「なんか信頼できそうな人だ」 · 「一緒にいると楽だ」',
      'zh-CN': '“感觉是个能信得过的人” · “跟他在一起很自在”',
      'zh-TW': '「感覺是個能信得過的人」 · 「跟他在一起很自在」',
      vi: '"Hình như đáng tin" · "Ở cùng thấy dễ chịu"',
      id: '"Kayaknya bisa dipercaya" · "Bareng dia rasanya nyaman"',
    },
    shiningMoment: {
      ko: '누군가를 도울 때·깊은 신뢰 관계를 만들 때',
      en: 'When helping someone or building deep trust',
      ja: '誰かを助けるとき・深い信頼関係をつくるとき',
      'zh-CN': '帮助别人、建立深厚信任时',
      'zh-TW': '幫助別人、建立深厚信任時',
      vi: 'Khi giúp ai đó hoặc xây dựng lòng tin sâu',
      id: 'Saat membantu seseorang atau membangun kepercayaan yang dalam',
    },
    reverseCharm: {
      ko: '조용해 보이지만 알면 알수록 단단하고 뚜렷한 가치관이 있는 사람',
      en: 'You seem quiet, but the more people know you, the clearer and firmer your values appear',
      ja: '静かそうに見えるけれど、知るほどしっかりした明確な価値観がある人',
      'zh-CN': '看起来安静，越了解越发现你有坚定清晰的价值观',
      'zh-TW': '看起來安靜，越了解越發現你有堅定清晰的價值觀',
      vi: 'Trông trầm nhưng càng hiểu càng thấy giá trị cứng cỏi, rõ ràng',
      id: 'Terlihat tenang, tapi semakin dikenal semakin jelas nilai-nilai yang teguh dan tegas',
    },
    matchingColors: {
      ko: '화이트(신선한 조화) · 코랄(생동감 추가)',
      en: 'White (fresh harmony) · Coral (adds vitality)',
      ja: 'ホワイト（新鮮な調和） · コーラル（活気をプラス）',
      'zh-CN': '白色（清新和谐） · 珊瑚色（增添生气）',
      'zh-TW': '白色（清新和諧） · 珊瑚色（增添生氣）',
      vi: 'Trắng (hài hòa tươi) · Coral (thêm sinh khí)',
      id: 'Putih (harmoni segar) · Coral (menambah vitalitas)',
    },
    personalColorLink: {
      ko: '여름 쿨톤 또는 봄 웜톤 계열과 잘 어울리는 경향',
      en: 'Often suits Summer Cool or Spring Warm personal color tones',
      ja: 'サマークールまたはスプリングウォーム系統と相性がよい傾向',
      'zh-CN': '往往与夏冷色或春暖色系更搭',
      'zh-TW': '往往與夏冷色或春暖色系更搭',
      vi: 'Thường hợp với tông Summer Cool hoặc Spring Warm',
      id: 'Cenderung cocok dengan tone Summer Cool atau Spring Warm',
    },
    shareSnippet: {
      ko: '내 첫인상 컬러: 민트 안정 💚 곁에 있으면 안심된다는 거... 믿음직스러운 거 맞음 → 너는 어떤 컬러야? 퍼스널 컬러랑 비교해봐',
      en: 'My first-impression color: Mint Calm 💚 They said being near me feels safe... reliable vibes unlocked → What’s yours? Compare it with your personal color!',
      ja: '私の第一印象カラー：ミント安定 💚 そばにいると安心するらしい…信頼感あるよね → あなたは何色？パーソナルカラーと比べてみて',
      'zh-CN': '我的第一印象色：薄荷安定 💚 说待在身边就安心…可靠实锤 → 你是什么色？跟个人色彩比比看',
      'zh-TW': '我的第一印象色：薄荷安定 💚 說待在身邊就安心…可靠實錘 → 你是什麼色？跟個人色彩比比看',
      vi: 'Màu ấn tượng đầu của mình: Mint Calm 💚 Nghe bảo bên cạnh là yên... đáng tin đúng rồi → Bạn màu gì? So với personal color đi!',
      id: 'Warna first impression-ku: Mint Calm 💚 Katanya di dekatku rasanya aman... reliable vibes unlocked → Kamu warna apa? Bandingkan dengan personal color-mu!',
    },
  },
  {
    type: 'Type5',
    emoji: '💙',
    title: {
      ko: '차분하고 깊이 있는, 블루 지성 컬러',
      en: 'Calm and deep — Blue Intellect Color',
      ja: '落ち着いて奥深い、ブルージセイカラー',
      'zh-CN': '沉稳有深度的蓝色知性色',
      'zh-TW': '沉穩有深度的藍色知性色',
      vi: 'Điềm tĩnh và sâu — Màu Blue Intellect',
      id: 'Tenang dan dalam — Warna Blue Intellect',
    },
    shortDescription: {
      ko: '당신은 말을 많이 하지 않아도 신뢰가 가는 사람입니다',
      en: 'Even without saying much, people trust you',
      ja: '多くを語らなくても、信頼される人です',
      'zh-CN': '你是那种话不多却让人信任的人',
      'zh-TW': '你是那種話不多卻讓人信任的人',
      vi: 'Bạn ít nói nhưng vẫn khiến người khác tin',
      id: 'Tanpa banyak bicara pun, orang tetap percaya padamu',
    },
    description: {
      ko: '깊고 차분한 블루 컬러처럼 처음 만나도 흔들리지 않는 안정감을 줍니다. 쉽게 흥분하지 않고 상황을 차분하게 바라보는 인상 덕분에 처음 만난 자리에서도 신뢰를 얻습니다.\n\n지적이고 성숙한 첫인상입니다.',
      en: 'Like deep, calm blue, you give steady composure even at first meeting. You don’t get rattled easily, and your cool way of reading a room earns trust right away.\n\nIt’s an intellectual, mature first impression.',
      ja: '深く落ち着いたブルーのように、初対面でも揺らがない安定感を与えます。簡単には興奮せず、状況を冷静に見る印象のおかげで、初めての場でも信頼を得ます。\n\n知的で成熟した第一印象です。',
      'zh-CN': '像深沉冷静的蓝色一样，初次见面也能给人不动摇的安定感。不易激动、能冷静看待情况的印象，让你在初见场合也能赢得信任。\n\n这是知性而成熟的第一印象。',
      'zh-TW': '像深沉冷靜的藍色一樣，初次見面也能給人不動搖的安定感。不易激動、能冷靜看待情況的印象，讓你在初見場合也能贏得信任。\n\n這是知性而成熟的第一印象。',
      vi: 'Như xanh sâu và điềm tĩnh, bạn mang sự ổn định ngay từ lần đầu. Không dễ nóng, nhìn tình huống bình tĩnh — nên được tin ngay cả khi mới gặp.\n\nẤn tượng đầu trí tuệ và trưởng thành.',
      id: 'Seperti biru yang dalam dan tenang, kamu memberi kestabilan sejak pertemuan pertama. Tidak mudah terbawa emosi, dan cara membacamu yang tenang membuat orang percaya cepat.\n\nIni first impression yang intelektual dan dewasa.',
    },
    firstImpressionColor: {
      ko: '블루·아쿠아 💙',
      en: 'Blue · Aqua 💙',
      ja: 'ブルー・アクア 💙',
      'zh-CN': '蓝色·水色 💙',
      'zh-TW': '藍色·水色 💙',
      vi: 'Xanh · Aqua 💙',
      id: 'Biru · Aqua 💙',
    },
    colorKeywords: {
      ko: '차분함,지성,깊이,신뢰,성숙함',
      en: 'calm,intellect,depth,trust,maturity',
      ja: '落ち着き,知性,深さ,信頼,成熟',
      'zh-CN': '沉稳,知性,深度,信任,成熟',
      'zh-TW': '沉穩,知性,深度,信任,成熟',
      vi: 'điềm tĩnh,trí tuệ,chiều sâu,tin cậy,trưởng thành',
      id: 'ketenangan,intelek,kedalaman,kepercayaan,kedewasaan',
    },
    firstFeeling: {
      ko: '"왠지 이 사람 믿어도 될 것 같아" · "생각이 깊어 보인다"',
      en: '"I feel like I can trust this person" · "They seem deep thinkers"',
      ja: '「なんかこの人、信じても大丈夫そう」 · 「考えが深そう」',
      'zh-CN': '“感觉这个人可以信” · “看起来想法很深”',
      'zh-TW': '「感覺這個人可以信」 · 「看起來想法很深」',
      vi: '"Hình như tin được người này" · "Trông suy nghĩ sâu"',
      id: '"Kayaknya orang ini bisa dipercaya" · "Kelihatannya berpikirnya dalam"',
    },
    shiningMoment: {
      ko: '중요한 대화·리더십이 필요한 상황·깊은 관계',
      en: 'Important talks, situations that need leadership, or deep relationships',
      ja: '大事な対話・リーダーシップが必要な場面・深い関係',
      'zh-CN': '重要对话、需要领导力的场合、深厚关系',
      'zh-TW': '重要對話、需要領導力的場合、深厚關係',
      vi: 'Trò chuyện quan trọng, lúc cần lãnh đạo, hoặc quan hệ sâu',
      id: 'Percakapan penting, situasi yang butuh kepemimpinan, atau hubungan yang dalam',
    },
    reverseCharm: {
      ko: '차가워 보이지만 친해지면 누구보다 따뜻하고 유머가 있는 사람',
      en: 'You may seem cool at first, but once close, you’re warmer and funnier than anyone',
      ja: '冷たく見えがちだけど、親しくなると誰より温かくてユーモアがある人',
      'zh-CN': '乍看偏冷，熟了以后比谁都温暖、有幽默感',
      'zh-TW': '乍看偏冷，熟了以後比誰都溫暖、有幽默感',
      vi: 'Trông lạnh nhưng thân rồi ấm và hài hước hơn ai hết',
      id: 'Terlihat dingin di awal, tapi begitu dekat justru paling hangat dan humoris',
    },
    matchingColors: {
      ko: '화이트(깔끔한 지성) · 실버(세련미 극대화)',
      en: 'White (clean intellect) · Silver (maximizes polish)',
      ja: 'ホワイト（きれいな知性） · シルバー（洗練を最大化）',
      'zh-CN': '白色（干净知性） · 银色（把精致感拉满）',
      'zh-TW': '白色（乾淨知性） · 銀色（把精緻感拉滿）',
      vi: 'Trắng (trí tuệ sạch sẽ) · Bạc (tăng độ tinh tế)',
      id: 'Putih (intelek yang bersih) · Silver (memaksimalkan kesan polished)',
    },
    personalColorLink: {
      ko: '겨울 쿨톤 또는 여름 쿨톤 계열과 잘 어울리는 경향',
      en: 'Often suits Winter Cool or Summer Cool personal color tones',
      ja: 'ウィンタークールまたはサマークール系統と相性がよい傾向',
      'zh-CN': '往往与冬冷色或夏冷色系更搭',
      'zh-TW': '往往與冬冷色或夏冷色系更搭',
      vi: 'Thường hợp với tông Winter Cool hoặc Summer Cool',
      id: 'Cenderung cocok dengan tone Winter Cool atau Summer Cool',
    },
    shareSnippet: {
      ko: '내 첫인상 컬러: 블루 지성 💙 차분하고 깊이 있는 인상이래... 차가워 보인다는 거 알고 있음 ㅋㅋ → 너는 어떤 첫인상 컬러야?',
      en: 'My first-impression color: Blue Intellect 💙 They said I’m calm and deep... I know I can look cold lol → What’s your first-impression color?',
      ja: '私の第一印象カラー：ブルージセイ 💙 落ち着いて奥深い印象らしい…冷たく見えるのは自覚ありw → あなたの第一印象カラーは？',
      'zh-CN': '我的第一印象色：蓝色知性 💙 说沉稳有深度…知道自己看起来偏冷哈哈 → 你的第一印象色是什么？',
      'zh-TW': '我的第一印象色：藍色知性 💙 說沉穩有深度…知道自己看起來偏冷哈哈 → 你的第一印象色是什麼？',
      vi: 'Màu ấn tượng đầu của mình: Blue Intellect 💙 Nghe bảo điềm tĩnh và sâu... biết là trông hơi lạnh haha → Màu ấn tượng đầu của bạn là gì?',
      id: 'Warna first impression-ku: Blue Intellect 💙 Katanya tenang dan dalam... aku tahu kadang kelihatan dingin wkwk → First-impression color-mu apa?',
    },
  },
  {
    type: 'Type6',
    emoji: '💜',
    title: {
      ko: '한 번 보면 잊히지 않는, 라벤더 신비 컬러',
      en: 'Once seen, never forgotten — Lavender Mystery Color',
      ja: '一度見たら忘れられない、ラベンダーミステリーカラー',
      'zh-CN': '看过一次就难忘的薰衣草神秘色',
      'zh-TW': '看過一次就難忘的薰衣草神秘色',
      vi: 'Nhìn một lần khó quên — Màu Lavender Mystery',
      id: 'Sekali dilihat, tak terlupakan — Warna Lavender Mystery',
    },
    shortDescription: {
      ko: '당신은 처음 봤는데 왠지 오래 기억에 남는 사람입니다',
      en: 'Even at first meeting, somehow you stay in people’s minds',
      ja: '初めて会ったのに、なぜか長く記憶に残る人です',
      'zh-CN': '你是那种初次见面却莫名让人记得很久的人',
      'zh-TW': '你是那種初次見面卻莫名讓人記得很久的人',
      vi: 'Mới gặp lần đầu nhưng lạ thay lại ở lại lâu trong trí nhớ',
      id: 'Baru pertama ketemu, tapi entah kenapa lama tersimpan di ingatan',
    },
    description: {
      ko: '감성적이고 신비로운 라벤더 컬러처럼 당신의 첫인상은 독특하고 오래 남습니다. 쉽게 파악되지 않는 깊이가 있고 알면 알수록 다른 면이 보이는 매력이 있습니다.\n\n개성 있는 취향과 감성이 자연스럽게 드러납니다.',
      en: 'Like emotional, mysterious lavender, your first impression is unique and lasting. There’s depth that’s hard to read at once, and the more people know you, the more new sides appear.\n\nYour distinctive taste and sensibility show up naturally.',
      ja: '感性的で神秘的なラベンダーのように、あなたの第一印象はユニークで長く残ります。すぐに読み切れない深さがあり、知るほど別の顔が見える魅力があります。\n\n個性的な好みと感性が自然とにじみ出ます。',
      'zh-CN': '像感性神秘的薰衣草紫一样，你的第一印象独特又持久。有一时读不透的深度，越了解越能看到不同的一面。\n\n独特的品味与感性会自然流露。',
      'zh-TW': '像感性神秘的薰衣草紫一樣，你的第一印象獨特又持久。有一時讀不透的深度，越了解越能看到不同的一面。\n\n獨特的品味與感性會自然流露。',
      vi: 'Như lavender đầy cảm xúc và huyền bí, ấn tượng đầu của bạn độc đáo và bền. Có chiều sâu khó đọc ngay, càng hiểu càng thấy mặt khác.\n\nGu và cảm xúc riêng lộ ra rất tự nhiên.',
      id: 'Seperti lavender yang emosional dan misterius, first impression-mu unik dan bertahan lama. Ada kedalaman yang tak mudah dibaca sekaligus, dan semakin dikenal semakin banyak sisi baru yang muncul.\n\nSelera dan sensibilitas khasmu muncul dengan natural.',
    },
    firstImpressionColor: {
      ko: '라벤더·퍼플 💜',
      en: 'Lavender · Purple 💜',
      ja: 'ラベンダー・パープル 💜',
      'zh-CN': '薰衣草·紫色 💜',
      'zh-TW': '薰衣草·紫色 💜',
      vi: 'Lavender · Tím 💜',
      id: 'Lavender · Ungu 💜',
    },
    colorKeywords: {
      ko: '신비,독특함,감성,깊이,개성',
      en: 'mystery,uniqueness,sensibility,depth,individuality',
      ja: '神秘,ユニークさ,感性,深さ,個性',
      'zh-CN': '神秘,独特,感性,深度,个性',
      'zh-TW': '神秘,獨特,感性,深度,個性',
      vi: 'huyền bí,độc đáo,cảm xúc,chiều sâu,cá tính',
      id: 'misteri,keunikan,sensibilitas,kedalaman,individualitas',
    },
    firstFeeling: {
      ko: '"저 사람 어떤 사람인지 더 알고 싶다" · "어딘가 독특한 분위기가 있어"',
      en: '"I want to know more about them" · "There’s something uniquely atmospheric about them"',
      ja: '「あの人、どんな人かもっと知りたい」 · 「どこか独特な空気がある」',
      'zh-CN': '“想再多了解那个人一点” · “有一种独特的氛围”',
      'zh-TW': '「想再多了解那個人一點」 · 「有一種獨特的氛圍」',
      vi: '"Muốn biết thêm về người kia" · "Có gì đó độc đáo trong không khí của họ"',
      id: '"Pengin lebih kenal orang itu" · "Ada aura unik yang susah dijelasin"',
    },
    shiningMoment: {
      ko: '창의적인 분야·예술·깊은 감성 대화',
      en: 'Creative fields, art, or deep emotional conversations',
      ja: 'クリエイティブな分野・芸術・深い感性の対話',
      'zh-CN': '创意领域、艺术、深入的感性对话',
      'zh-TW': '創意領域、藝術、深入的感性對話',
      vi: 'Lĩnh vực sáng tạo, nghệ thuật, hoặc trò chuyện cảm xúc sâu',
      id: 'Bidang kreatif, seni, atau percakapan emosional yang dalam',
    },
    reverseCharm: {
      ko: '신비롭고 조용해 보이지만 알고 보면 세상에서 가장 재밌는 이야기를 가진 사람',
      en: 'You seem mysterious and quiet — but once known, you hold some of the most interesting stories',
      ja: '神秘的で静かそうに見えるけれど、知ると世界一おもしろい話を持つ人',
      'zh-CN': '看起来神秘安静，熟了才发现你有世上最好玩的故事',
      'zh-TW': '看起來神秘安靜，熟了才發現你有世上最好玩的故事',
      vi: 'Trông huyền bí, trầm — nhưng biết rồi sẽ thấy bạn có chuyện thú vị nhất đời',
      id: 'Terlihat misterius dan tenang — tapi begitu dikenal, kamu punya cerita paling menarik di dunia',
    },
    matchingColors: {
      ko: '화이트(몽환적인 조화) · 골드(신비로운 화려함)',
      en: 'White (dreamy harmony) · Gold (mysterious sparkle)',
      ja: 'ホワイト（幻想的な調和） · ゴールド（神秘的な華やかさ）',
      'zh-CN': '白色（梦幻和谐） · 金色（神秘的华丽）',
      'zh-TW': '白色（夢幻和諧） · 金色（神秘的華麗）',
      vi: 'Trắng (hài hòa mộng mơ) · Vàng (lộng lẫy huyền bí)',
      id: 'Putih (harmoni dreamy) · Emas (kemilau misterius)',
    },
    personalColorLink: {
      ko: '여름 쿨톤 계열과 잘 어울리는 경향',
      en: 'Often suits Summer Cool personal color tones',
      ja: 'サマークール系統と相性がよい傾向',
      'zh-CN': '往往与夏冷色系更搭',
      'zh-TW': '往往與夏冷色系更搭',
      vi: 'Thường hợp với tông Summer Cool',
      id: 'Cenderung cocok dengan tone Summer Cool',
    },
    shareSnippet: {
      ko: '내 첫인상 컬러: 라벤더 신비 💜 처음 봤는데 오래 기억에 남는 사람이래... 독특하다는 거 인정 → 너는 어떤 컬러야? 퍼스널 컬러랑 비교해봐',
      en: 'My first-impression color: Lavender Mystery 💜 They said I’m hard to forget even at first sight... unique vibes unlocked → What’s yours? Compare it with your personal color!',
      ja: '私の第一印象カラー：ラベンダーミステリー 💜 初めて会ったのに長く記憶に残る人らしい…ユニーク認定 → あなたは何色？パーソナルカラーと比べてみて',
      'zh-CN': '我的第一印象色：薰衣草神秘 💜 说初次见面却记得很久…独特实锤 → 你是什么色？跟个人色彩比比看',
      'zh-TW': '我的第一印象色：薰衣草神秘 💜 說初次見面卻記得很久…獨特實錘 → 你是什麼色？跟個人色彩比比看',
      vi: 'Màu ấn tượng đầu của mình: Lavender Mystery 💜 Nghe bảo mới gặp mà nhớ lâu... độc đáo đúng rồi → Bạn màu gì? So với personal color đi!',
      id: 'Warna first impression-ku: Lavender Mystery 💜 Katanya baru ketemu tapi lama diingat... unique vibes unlocked → Kamu warna apa? Bandingkan dengan personal color-mu!',
    },
  },
];
