/** 줄줄 새는 돈! 나의 멍청비용 진단 — 12문항 4지선다, 총점 0~36 */

function T(t: {
  ko: string;
  en: string;
  ja: string;
  zhCN: string;
  zhTW: string;
  vi: string;
  id: string;
}): Record<string, string> {
  return {
    ko: t.ko,
    en: t.en,
    ja: t.ja,
    'zh-CN': t.zhCN,
    'zh-TW': t.zhTW,
    vi: t.vi,
    id: t.id,
  };
}

export interface Phase3DumbSpendingDiagnosisQuestion {
  id: number;
  question: Record<string, string>;
  options: { text: Record<string, string>; score: number }[];
}

export interface Phase3DumbSpendingDiagnosisResult {
  type: string;
  emoji: string;
  title: Record<string, string>;
  diagnosisGrade: Record<string, string>;
  hookLine: Record<string, string>;
  description: Record<string, string>;
  detailSectionTitle: Record<string, string>;
  detailBullets: Record<string, string>;
  prescriptionSteps: Record<string, string>;
  monthlyWasteRange: Record<string, string>;
  yearlySaveRange: Record<string, string>;
  todayTask: Record<string, string>;
  shareLine: Record<string, string>;
  shareTypeName: Record<string, string>;
}

export function calculatePhase3DumbSpendingDiagnosisResult(answers: number[]): string {
  const total = answers.reduce((sum, s) => sum + (s ?? 0), 0);
  if (total <= 5) return 'Type1';
  if (total <= 11) return 'Type2';
  if (total <= 19) return 'Type3';
  if (total <= 27) return 'Type4';
  if (total <= 33) return 'Type5';
  return 'Type6';
}

export const phase3DumbSpendingDiagnosisQuestions: Phase3DumbSpendingDiagnosisQuestion[] = [
  {
    id: 1,
    question: T({
      ko: '지금 결제 중인 구독 서비스를 생각해보면?',
      en: 'When you think about subscription services you are paying for right now?',
      ja: '今課金中のサブスクを思い返すと？',
      zhCN: '想到你正在付费的订阅服务时？',
      zhTW: '想到你正在付費的訂閱服務時？',
      vi: 'Khi nghĩ về các dịch vụ đăng ký bạn đang trả tiền?',
      id: 'Kalau memikirkan langganan yang sedang kamu bayar?',
    }),
    options: [
      {
        text: T({
          ko: '모두 파악하고 있고 실제로 다 활용하고 있다',
          en: 'I know them all and actually use every one',
          ja: '全部把握していて、実際に全部使っている',
          zhCN: '全都清楚，而且真的都有在用',
          zhTW: '全都清楚，而且真的都有在用',
          vi: 'Mình nắm hết và thực sự dùng hết',
          id: 'Aku tahu semua dan benar-benar memakai semuanya',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '대부분 쓰고 있지만 가끔 안 쓰는 달도 있다',
          en: 'I use most of them, but some months I barely touch a few',
          ja: 'だいたい使うが、使わない月もある',
          zhCN: '大部分会用，但偶尔有几个月几乎不用',
          zhTW: '大部分會用，但偶爾有幾個月幾乎不用',
          vi: 'Hầu hết có dùng nhưng đôi tháng gần như không đụng tới',
          id: 'Sebagian besar dipakai, tapi ada bulan yang hampir tidak',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '솔직히 몇 개는 언제 결제됐는지도 잘 모른다',
          en: 'Honestly I am not even sure when some of them bill',
          ja: '正直、いくつかはいつ引き落とされるかよく分からない',
          zhCN: '老实说，有几个连什么时候扣款都不太清楚',
          zhTW: '老實說，有幾個連什麼時候扣款都不太清楚',
          vi: 'Thật lòng thì vài cái mình cũng chẳng rõ khi nào trừ tiền',
          id: 'Sejujurnya beberapa aku tidak tahu kapan ditagih',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '확인해보면 아마 안 쓰는 것도 있을 것 같아서 무섭다',
          en: 'I am scared to check—I probably still pay for things I do not use',
          ja: '確認したら使っていないのもありそうで怖い',
          zhCN: '不敢查，怕发现还在付没用的',
          zhTW: '不敢查，怕發現還在付沒用的',
          vi: 'Sợ kiểm tra—chắc vẫn đang trả tiền cho thứ không dùng',
          id: 'Takut cek—mungkin masih bayar yang tidak dipakai',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 2,
    question: T({
      ko: '배달 앱을 열었을 때 나는?',
      en: 'When you open a food-delivery app, you…',
      ja: 'デリバリーアプリを開いたとき、あなたは？',
      zhCN: '打开外卖应用时，你会？',
      zhTW: '打開外送 App 時，你會？',
      vi: 'Khi mở app giao đồ ăn, bạn…',
      id: 'Saat buka aplikasi pesan-antar makanan, kamu…',
    }),
    options: [
      {
        text: T({
          ko: '딱 먹고 싶은 것만 시키고 배달비가 아까우면 직접 가져온다',
          en: 'Order only what I crave; if the fee stings, I pick it up myself',
          ja: '食べたいものだけ注文。配達料がもったいなければ自分で取りに行く',
          zhCN: '只点想吃的；配送费贵就自己去取',
          zhTW: '只點想吃的；運費貴就自己去取',
          vi: 'Chỉ gọi món thật sự thèm; phí cao thì tự đến lấy',
          id: 'Hanya pesan yang benar-benar ingin; ongkir mahal ambil sendiri',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '최소 주문 금액 때문에 필요 없는 메뉴를 추가하는 경우가 있다',
          en: 'Sometimes I add extra items just to hit the minimum order',
          ja: '最低注文額のために不要なメニューを足すことがある',
          zhCN: '为了凑最低起送会多加不需要的菜',
          zhTW: '為了湊最低起送會多加不需要的菜',
          vi: 'Đôi khi thêm món không cần để đủ đơn tối thiểu',
          id: 'Kadang menambah menu yang tidak perlu untuk minimum order',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '배달비 아끼려다 묶음 배달 선택했는데 오히려 시간이 오래 걸린다',
          en: 'I chose bundled delivery to save fees, but it took way longer',
          ja: '配達料をケチってまとめ配達にしたら、かえって時間がかかった',
          zhCN: '为省配送费选了拼单，结果反而等更久',
          zhTW: '為省運費選了併單，結果反而等更久',
          vi: 'Chọn giao gộp để tiết kiệm phí nhưng lại chờ lâu hơn',
          id: 'Pilih antar gabung untuk hemat ongkir malah lebih lama',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '쿠폰 받으려고 새로운 가게를 시켰다가 맛없어서 돈이 아까웠다',
          en: 'I ordered from a new place for a coupon—it tasted bad and felt like a waste',
          ja: 'クーポン目的で新しい店を頼んだら不味くてもったいなかった',
          zhCN: '为领券试了新店，难吃又浪费钱',
          zhTW: '為了優惠券試新店，難吃又浪費錢',
          vi: 'Vì coupon thử quán mới—dở và thấy phí tiền',
          id: 'Demi kupon coba restoran baru—tidak enak dan sayang uang',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 3,
    question: T({
      ko: '할인 행사나 세일 소식을 들으면 나는?',
      en: 'When you hear about a sale or discount, you…',
      ja: 'セールや割引の話を聞くと、あなたは？',
      zhCN: '听到打折或促销时，你会？',
      zhTW: '聽到打折或促銷時，你會？',
      vi: 'Khi nghe tin giảm giá hoặc khuyến mãi, bạn…',
      id: 'Saat dengar diskon atau sale, kamu…',
    }),
    options: [
      {
        text: T({
          ko: '필요한 것만 구매한다. 할인이 목적이 되지 않는다',
          en: 'I buy only what I need—the discount is not the goal',
          ja: '必要なものだけ買う。割引が目的にならない',
          zhCN: '只买需要的，不为折扣而买',
          zhTW: '只買需要的，不為折扣而買',
          vi: 'Chỉ mua thứ cần—giảm giá không phải mục tiêu',
          id: 'Hanya beli yang perlu—diskon bukan tujuan',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '필요한 것이 할인할 때 사는 편이지만 가끔 필요 없는 것도 산다',
          en: 'I usually buy needs on sale, but sometimes I grab extras I do not need',
          ja: '必要なものはセールで買うが、不要なものも買うことがある',
          zhCN: '需要的会等打折买，但偶尔也会买不需要的',
          zhTW: '需要的會等打折買，但偶爾也會買不需要的',
          vi: 'Đồ cần mua khi giảm giá, nhưng đôi khi mua thừa không cần',
          id: 'Yang perlu dibeli saat diskon, kadang juga beli yang tidak perlu',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '어차피 살 거니까 대량 구매했다가 다 못 쓰고 버린 적이 있다',
          en: 'I bulk-bought “because I would use it anyway,” then threw a lot away',
          ja: '「どうせ使うから」とまとめ買いして、結局捨てたことがある',
          zhCN: '想着反正会用而囤货，结果很多没用完就扔',
          zhTW: '想著反正會用而囤貨，結果很多沒用完就丟',
          vi: 'Mua số lượng vì “dù sao cũng dùng,” rồi vứt bớt',
          id: 'Beli banyak karena “nanti dipakai,” banyak yang dibuang',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '할인이라는 말만 보면 일단 장바구니에 담고 본다',
          en: 'If I see “sale,” I toss it in the cart first and think later',
          ja: '「セール」と見たらとりあえずカートに入れる',
          zhCN: '看到“打折”就先加购再说',
          zhTW: '看到「打折」就先加購再說',
          vi: 'Thấy “giảm giá” là cho vào giỏ trước đã',
          id: 'Lihat “diskon” langsung masukkan keranjang dulu',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 4,
    question: T({
      ko: '편의점이나 카페에 들렀을 때 나는?',
      en: 'When you stop by a convenience store or café, you…',
      ja: 'コンビニやカフェに寄ったとき、あなたは？',
      zhCN: '进便利店或咖啡店时，你会？',
      zhTW: '進便利商店或咖啡店時，你會？',
      vi: 'Khi ghé cửa hàng tiện lợi hoặc quán cà phê, bạn…',
      id: 'Saat mampir minimarket atau kafe, kamu…',
    }),
    options: [
      {
        text: T({
          ko: '딱 필요한 것만 사고 나온다',
          en: 'I buy only what I came for and leave',
          ja: '必要なものだけ買って出る',
          zhCN: '只买需要的就走',
          zhTW: '只買需要的就走',
          vi: 'Chỉ mua đúng thứ cần rồi đi',
          id: 'Hanya beli yang perlu lalu pergi',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '1+1이면 하나는 필요 없어도 집어 든다',
          en: 'BOGO? I grab the second even if I do not really need it',
          ja: '1+1なら、要らなくてももう一つ取る',
          zhCN: '买一送一会多拿一件，即使不太需要',
          zhTW: '買一送一會多拿一件，即使不太需要',
          vi: 'Mua một tặng một thì lấy thêm dù không cần',
          id: 'Beli satu gratis satu—ambil yang kedua walau tidak perlu',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '왠지 한 가지만 사면 이상한 것 같아서 더 사게 된다',
          en: 'Somehow buying just one feels wrong, so I buy more',
          ja: 'なぜか一つだけだと気持ち悪くて、つい増やす',
          zhCN: '总觉得只买一件怪怪的，就会多买',
          zhTW: '總覺得只買一件怪怪的，就會多買',
          vi: 'Cảm giác chỉ mua một thứ là lạ nên mua thêm',
          id: 'Terasa aneh kalau cuma beli satu jadi beli lebih banyak',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '들어가면 평균 두 배 이상 더 쓰고 나온다',
          en: 'I routinely spend at least double what I planned',
          ja: '入ると計画の倍以上使って出る',
          zhCN: '进去平均花掉计划的两倍以上',
          zhTW: '進去平均花掉計畫的兩倍以上',
          vi: 'Vào là tiêu gấp đôi dự định trở lên',
          id: 'Begitu masuk pengeluaran jadi minimal dua kali lipat rencana',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 5,
    question: T({
      ko: '멤버십이나 포인트 카드에 대해 나는?',
      en: 'When it comes to memberships or point cards, you…',
      ja: '会員やポイントカードについて、あなたは？',
      zhCN: '谈到会员或积分卡，你会？',
      zhTW: '談到會員或集點卡，你會？',
      vi: 'Với thẻ thành viên hoặc tích điểm, bạn…',
      id: 'Soal membership atau kartu poin, kamu…',
    }),
    options: [
      {
        text: T({
          ko: '실제로 자주 가는 곳만 가입하고 잘 활용한다',
          en: 'I only join places I actually go to and use the perks',
          ja: '本当によく行く店だけ入会して活用している',
          zhCN: '只办常去的店，而且会用到权益',
          zhTW: '只辦常去的店，而且會用到權益',
          vi: 'Chỉ đăng ký nơi thật sự hay đến và dùng hết ưu đãi',
          id: 'Hanya daftar tempat yang sering dikunjungi dan memakai benefit',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '몇 개 있긴 한데 포인트를 쌓아두고 쓰지 않는 경우가 있다',
          en: 'I have a few, but points pile up unused',
          ja: 'いくつか持っているが、ポイントを溜めて使わないことがある',
          zhCN: '有几张，但积分常常攒着不用',
          zhTW: '有幾張，但積分常常攢著不用',
          vi: 'Có vài cái nhưng điểm cứ tích mà không dùng',
          id: 'Ada beberapa tapi poin menumpuk tidak dipakai',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '포인트 쌓으려다 오히려 더 자주 가게 되는 패턴이 있다',
          en: 'Chasing points makes me visit—and spend—more often',
          ja: 'ポイント目的で、かえって通う回数が増える',
          zhCN: '为了攒积分反而更常去、花更多',
          zhTW: '為了攢積分反而更常去、花更多',
          vi: 'Vì tích điểm mà đi thường xuyên hơn—và tiêu nhiều hơn',
          id: 'Demi poin jadi lebih sering datang—dan belanja lebih banyak',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '가입하면 혜택 준다고 해서 가입했는데 혜택은 쓴 적이 없다',
          en: 'I signed up for “benefits” I have never actually used',
          ja: '特典目的で入会したが、特典を使ったことはない',
          zhCN: '为福利办了会员，但从来没用过那些福利',
          zhTW: '為福利辦了會員，但從來沒用過那些福利',
          vi: 'Đăng ký vì “ưu đãi” nhưng chưa bao giờ dùng',
          id: 'Daftar karena “benefit” tapi tidak pernah memakainya',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 6,
    question: T({
      ko: '운동이나 자기계발 관련 지출을 떠올리면?',
      en: 'When you think about fitness or self-development spending…',
      ja: '運動や自己投資の支出を思い出すと？',
      zhCN: '想到运动或自我提升方面的开销时？',
      zhTW: '想到運動或自我提升方面的開銷時？',
      vi: 'Khi nghĩ đến chi cho thể thao hoặc phát triển bản thân…',
      id: 'Saat memikirkan pengeluaran olahraga atau pengembangan diri…',
    }),
    options: [
      {
        text: T({
          ko: '꾸준히 활용하고 있고 가성비가 좋다고 생각한다',
          en: 'I use it consistently and feel it is worth the money',
          ja: '継続して活用していて、コスパが良いと思う',
          zhCN: '持续在用，觉得性价比高',
          zhTW: '持續在用，覺得性價比高',
          vi: 'Dùng đều và thấy đáng tiền',
          id: 'Tetap dipakai dan menurutku worth it',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '가끔 빠지긴 하지만 대체로 잘 다니고 있다',
          en: 'I miss days sometimes, but mostly I show up',
          ja: '時々サボるが、だいたい通っている',
          zhCN: '偶尔偷懒，但大体上还会去',
          zhTW: '偶爾偷懶，但大體上還會去',
          vi: 'Đôi khi lười nhưng nhìn chung vẫn đi',
          id: 'Kadang bolos tapi secara umum masih rutin',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '등록은 했는데 처음 한 달만 열심히 다니고 점점 뜸해졌다',
          en: 'I went hard the first month, then drifted away',
          ja: '登録したが、最初の一ヶ月だけ頑張ってだんだん行かなくなった',
          zhCN: '办了卡只有第一个月积极，后来越去越少',
          zhTW: '辦了卡只有第一個月積極，後來越去越少',
          vi: 'Tháng đầu chăm, sau đó ngày càng lười đi',
          id: 'Bulan pertama rajin, lama-lama jarang',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '헬스장 등록비가 몇 개월째 자동결제 중인데 사실 안 가고 있다',
          en: 'My gym fee auto-charges every month—I barely go',
          ja: 'ジム代が何ヶ月も自動課金されているが、実際は行っていない',
          zhCN: '健身房自动扣了好几个月，其实几乎没去',
          zhTW: '健身房自動扣了好幾個月，其實幾乎沒去',
          vi: 'Phí gym tự trừ mấy tháng nhưng thực tế không đi',
          id: 'Biaya gym terpotong otomatis berbulan-bulan padahal jarang pergi',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 7,
    question: T({
      ko: '인터넷 쇼핑을 할 때 나는?',
      en: 'When you shop online, you…',
      ja: 'ネットショッピングをするとき、あなたは？',
      zhCN: '网购时，你会？',
      zhTW: '網購時，你會？',
      vi: 'Khi mua sắm online, bạn…',
      id: 'Saat belanja online, kamu…',
    }),
    options: [
      {
        text: T({
          ko: '필요한 것을 검색해서 최저가로 딱 구매한다',
          en: 'I search for what I need and buy at the best price—nothing extra',
          ja: '必要なものを検索して最安で買うだけ',
          zhCN: '搜需要的，最低价买下，不多买',
          zhTW: '搜需要的，最低價買下，不多買',
          vi: 'Tìm đúng thứ cần và mua giá tốt nhất',
          id: 'Cari yang perlu dan beli harga terbaik—tanpa tambahan',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '무료 배송 조건 맞추려다 필요 없는 것을 추가한 적이 있다',
          en: 'I have added junk to the cart just to hit free shipping',
          ja: '送料無料条件のために不要なものを足したことがある',
          zhCN: '为凑包邮加过不需要的东西',
          zhTW: '為湊免運加過不需要的東西',
          vi: 'Đã thêm đồ không cần để đủ điều kiện freeship',
          id: 'Pernah menambah barang tidak perlu demi gratis ongkir',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '오늘만 할인이라는 말에 급하게 샀다가 후회한 적이 있다',
          en: '“Today only” made me rush-buy and regret it',
          ja: '「今日だけセール」に急いで買って後悔したことがある',
          zhCN: '被“仅限今日”催着买，买完后悔',
          zhTW: '被「限時」催著買，買完後悔',
          vi: 'Vì “chỉ hôm nay” mua vội rồi hối hận',
          id: 'Karena “hanya hari ini” beli buru-buru lalu menyesal',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '장바구니에 담아두면 할인 쿠폰 오는 거 노리다가 결국 다 사버린다',
          en: 'I leave items in the cart waiting for coupons—then buy everything',
          ja: 'カートに入れてクーポン待ちして、結局全部買ってしまう',
          zhCN: '购物车蹲券，结果最后全买了',
          zhTW: '購物車蹲券，結果最後全買了',
          vi: 'Để trong giỏ chờ coupon—cuối cùng mua hết',
          id: 'Dalam keranjang nunggu kupon—akhirnya beli semua',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 8,
    question: T({
      ko: '음식이나 식재료 관련 지출은?',
      en: 'How do you handle food and grocery spending?',
      ja: '食事や食材の支出は？',
      zhCN: '食物和食材开销方面？',
      zhTW: '食物和食材開銷方面？',
      vi: 'Chi cho đồ ăn và thực phẩm của bạn?',
      id: 'Pengeluaran makanan dan bahan makanan?',
    }),
    options: [
      {
        text: T({
          ko: '계획적으로 장을 보고 거의 다 먹는다',
          en: 'I shop with a plan and eat almost everything I buy',
          ja: '計画的に買い物して、ほぼ全部食べる',
          zhCN: '有计划采购，基本吃完',
          zhTW: '有計畫採購，基本吃完',
          vi: 'Mua có kế hoạch và ăn gần hết',
          id: 'Belanja terencana dan hampir habis dimakan',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '가끔 유통기한 지나서 버리는 것이 있다',
          en: 'Sometimes things expire before I use them',
          ja: '時々賞味期限切れで捨てることがある',
          zhCN: '偶尔会放过期扔掉',
          zhTW: '偶爾會放過期扔掉',
          vi: 'Đôi khi để quá hạn phải vứt',
          id: 'Kadang kedaluwarsa harus dibuang',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '대용량이 싸다고 샀다가 다 못 먹고 버린 적이 꽤 있다',
          en: 'I bought bulk “because it was cheap,” then threw a lot out',
          ja: '「安いから」と大容量を買って、食べきれず捨てたことがよくある',
          zhCN: '图便宜买大包装，很多吃不完就扔',
          zhTW: '圖便宜買大包裝，很多吃不完就丟',
          vi: 'Mua size lớn vì rẻ rồi không ăn hết phải vứt',
          id: 'Beli besar karena murah—banyak yang tidak habis',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '배달 쿠폰 때문에 굳이 배달 시켰다가 배달비가 더 나온 적이 있다',
          en: 'I ordered delivery for a coupon and paid more in fees than I saved',
          ja: 'クーポン目的でデリバリーしたら、配達料の方が高かったことがある',
          zhCN: '为用券点外卖，配送费反而比省的多',
          zhTW: '為用券叫外送，運費反而比省的多',
          vi: 'Vì coupon gọi giao—phí ship còn cao hơn tiền “tiết kiệm”',
          id: 'Demi kupon pesan antar—ongkir malah lebih besar dari hematnya',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 9,
    question: T({
      ko: '자동이체나 정기결제를 확인한다면?',
      en: 'If we talk about auto-debits and subscriptions…',
      ja: '自動引き落としや定期課金の確認について？',
      zhCN: '关于自动扣款和定期付费？',
      zhTW: '關於自動扣款和定期付費？',
      vi: 'Về giao dịch tự động và thanh toán định kỳ…',
      id: 'Soal debit otomatis dan pembayaran berulang…',
    }),
    options: [
      {
        text: T({
          ko: '정기적으로 확인하고 안 쓰는 것은 바로 해지한다',
          en: 'I review regularly and cancel what I do not use',
          ja: '定期的に確認して、使わないものはすぐ解約する',
          zhCN: '定期查看，不用的马上退订',
          zhTW: '定期查看，不用的馬上退訂',
          vi: 'Kiểm tra định kỳ và hủy cái không dùng',
          id: 'Cek rutin dan batalkan yang tidak dipakai',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '가끔 확인하는 편이지만 귀찮아서 해지를 미룬 적이 있다',
          en: 'I check sometimes, but I have put off canceling out of laziness',
          ja: 'たまに確認するが、面倒で解約を先延ばししたことがある',
          zhCN: '偶尔查，但嫌麻烦拖着没退订',
          zhTW: '偶爾查，但嫌麻煩拖著沒退訂',
          vi: 'Đôi khi kiểm tra nhưng lười nên chưa hủy',
          id: 'Kadang cek tapi malas jadi menunda berhenti',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '확인하면 놀랄 것 같아서 솔직히 잘 안 들여다본다',
          en: 'I avoid looking—I am afraid of what I will find',
          ja: '見たらビックリしそうで、正直あまり見ない',
          zhCN: '怕看了吓一跳，所以不太敢查',
          zhTW: '怕看了嚇一跳，所以不太敢查',
          vi: 'Sợ nhìn vào sẽ “choáng” nên ít khi mở',
          id: 'Takut lihat hasilnya mengejutkan jadi jarang buka',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '확인해본 적이 별로 없다. 어딘가에서 새고 있을 것 같다',
          en: 'I hardly ever check—money is probably leaking somewhere',
          ja: 'ほとんど確認したことがない。どこかで漏れている気がする',
          zhCN: '几乎没查过，感觉钱不知在哪漏',
          zhTW: '幾乎沒查過，感覺錢不知在哪漏',
          vi: 'Hầu như không kiểm tra—tiền chắc đang “rò” đâu đó',
          id: 'Hampir tidak pernah cek—uang pasti bocor entah di mana',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 10,
    question: T({
      ko: '프리미엄 또는 업그레이드 옵션에 대해 나는?',
      en: 'When apps offer premium or upgrade options, you…',
      ja: 'プレミアムやアップグレードのとき、あなたは？',
      zhCN: '面对付费升级或高级版时，你会？',
      zhTW: '面對付費升級或進階版時，你會？',
      vi: 'Khi có bản premium hoặc nâng cấp, bạn…',
      id: 'Saat ada opsi premium atau upgrade, kamu…',
    }),
    options: [
      {
        text: T({
          ko: '필요하지 않으면 기본 옵션을 선택한다',
          en: 'If I do not need it, I stick with the basic plan',
          ja: '必要なければ基本プランを選ぶ',
          zhCN: '不需要就选基础版',
          zhTW: '不需要就選基礎版',
          vi: 'Không cần thì dùng gói cơ bản',
          id: 'Kalau tidak perlu pilih paket dasar',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '가끔 귀찮아서 프리미엄 옵션을 선택하는 경우가 있다',
          en: 'Sometimes I pick premium just because it is easier',
          ja: '面倒くさくてプレミアムを選ぶことがある',
          zhCN: '有时图省事直接选高级版',
          zhTW: '有時圖省事直接選進階版',
          vi: 'Đôi khi chọn premium vì lười xử lý',
          id: 'Kadang pilih premium karena malas ribet',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '조금만 더 내면 훨씬 낫다는 말에 자주 업그레이드한다',
          en: '“Just a little more” gets me to upgrade all the time',
          ja: '「少し払えばずっと良い」に弱くてよくアップグレードする',
          zhCN: '一听“加一点就好很多”就常升级',
          zhTW: '一聽「加一點就好很多」就常升級',
          vi: 'Nghe “chỉ thêm một chút là tốt hơn nhiều” là nâng cấp',
          id: 'Dengar “bayar sedikit lebih enak” sering upgrade',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '기본이랑 차이가 거의 없는데 습관적으로 프리미엄을 선택한다',
          en: 'The upgrade barely helps, but I pick it out of habit',
          ja: '基本とほぼ変わらないのに、癖でプレミアムを選ぶ',
          zhCN: '和基础版差不多，但习惯点高级',
          zhTW: '和基礎版差不多，但習慣點進階',
          vi: 'Khác biệt ít nhưng vẫn quen chọn premium',
          id: 'Bedanya kecil tapi kebiasaan pilih premium',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 11,
    question: T({
      ko: '한 달 지출을 돌아보면 가장 많이 후회되는 소비는?',
      en: 'Looking back at a month of spending, your biggest regret is…',
      ja: '一ヶ月の支出を振り返ると、一番後悔するのは？',
      zhCN: '回顾一个月开销，最后悔的消费是？',
      zhTW: '回顧一個月開銷，最後悔的消費是？',
      vi: 'Nhìn lại chi tiêu cả tháng, điều hối nhất là…',
      id: 'Melihat pengeluaran sebulan, yang paling disesali…',
    }),
    options: [
      {
        text: T({
          ko: '딱히 후회되는 것이 없다. 대체로 계획적으로 썼다',
          en: 'Nothing major—I mostly spent on purpose',
          ja: '特に後悔はない。だいたい計画的',
          zhCN: '没什么后悔的，大体有计划',
          zhTW: '沒什麼後悔的，大體有計畫',
          vi: 'Không có gì đặc biệt hối—nhìn chung có kế hoạch',
          id: 'Tidak ada penyesalan besar—cukup terencana',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '한두 개 정도 아 이건 살 필요 없었는데 싶은 게 있다',
          en: 'One or two purchases where I think, “I did not need that”',
          ja: '一つ二つ、「これは要らなかった」と思うものがある',
          zhCN: '有一两样觉得“其实不必买”',
          zhTW: '有一兩樣覺得「其實不必買」',
          vi: 'Một hai món thấy “lẽ ra không cần mua”',
          id: 'Satu dua barang yang seharusnya tidak perlu dibeli',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '충동구매가 꽤 있다. 사고 나서 왜 샀지 싶은 게 여러 개다',
          en: 'Plenty of impulse buys—I ask myself “why?” more than once',
          ja: '衝動買いが多い。「なぜ買った？」がいくつもある',
          zhCN: '冲动买不少，好几笔买完想问为什么',
          zhTW: '衝動買不少，好幾筆買完想問為什麼',
          vi: 'Nhiều mua ngẫu hứng—tự hỏi “sao mua?” vài lần',
          id: 'Banyak beli impuls—beberapa kali bertanya “kenapa beli?”',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '영수증을 보면 내가 이걸 왜 샀는지 기억도 안 나는 항목이 있다',
          en: 'Receipts include items I do not even remember buying',
          ja: 'レシートを見て「なぜ買ったか覚えていない」項目がある',
          zhCN: '看小票有完全想不起来为什么买的东西',
          zhTW: '看收據有完全想不起來為什麼買的東西',
          vi: 'Trên hóa đơn có món không nhớ vì sao mua',
          id: 'Di struk ada barang yang tidak ingat kenapa dibeli',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 12,
    question: T({
      ko: '지금 내 소비 패턴에 대한 솔직한 생각은?',
      en: 'Honestly, how do you feel about your spending habits right now?',
      ja: '今の自分の消費パターンについて正直どう思う？',
      zhCN: '老实说，你如何看待自己现在的消费习惯？',
      zhTW: '老實說，你如何看待自己現在的消費習慣？',
      vi: 'Thật lòng bạn nghĩ gì về thói chi tiêu hiện tại?',
      id: 'Sejujurnya bagaimana pandanganmu pada pola belanjamu sekarang?',
    }),
    options: [
      {
        text: T({
          ko: '꽤 합리적으로 쓰고 있다고 생각한다',
          en: 'I think I spend pretty reasonably',
          ja: 'かなり合理的に使っていると思う',
          zhCN: '觉得自己花得还算理性',
          zhTW: '覺得自己花得還算理性',
          vi: 'Mình thấy chi tiêu khá hợp lý',
          id: 'Menurutku belanjaku cukup rasional',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '조금 줄일 수 있는 부분이 있을 것 같다',
          en: 'There is probably room to trim a bit',
          ja: '少しは減らせる部分がありそう',
          zhCN: '应该还有些能省的地方',
          zhTW: '應該還有些能省的地方',
          vi: 'Chắc vẫn có chỗ cắt bớt được',
          id: 'Sepertinya masih ada yang bisa dikurangi',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '솔직히 멍청하게 쓰는 부분이 있다는 걸 알고 있다',
          en: 'I know I waste money in dumb ways sometimes',
          ja: '正直、ムダ遣いしている自覚はある',
          zhCN: '知道自己有时在乱花钱',
          zhTW: '知道自己有時在亂花錢',
          vi: 'Biết đôi khi mình tiêu khá “ngu”',
          id: 'Sadar kadang belanjaku boros dengan cara bodoh',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '어디서 새는지 모르겠지만 항상 잔액이 부족하다',
          en: 'No idea where it goes—I am always short on balance',
          ja: 'どこで漏れているか分からないが、いつも残高が足りない',
          zhCN: '不知道钱漏哪了，余额总是不够',
          zhTW: '不知道錢漏哪了，餘額總是不夠',
          vi: 'Không rõ tiền đi đâu—số dư lúc nào cũng thiếu',
          id: 'Tidak tahu uang mengalir ke mana—saldo selalu kurang',
        }),
        score: 3,
      },
    ],
  },
];

export const phase3DumbSpendingDiagnosisResults: Phase3DumbSpendingDiagnosisResult[] = [
  {
    type: 'Type1',
    emoji: '💚',
    title: T({
      ko: '멍청비용 거의 없는, 합리적 소비 우등생 💚',
      en: 'Almost no dumb spending—honor-roll rational spender 💚',
      ja: 'ムダ遣いほぼなし、合理的な優等生 💚',
      zhCN: '冤枉钱几乎为零的理性消费优等生 💚',
      zhTW: '冤枉錢幾乎為零的理性消費優等生 💚',
      vi: 'Gần như không lãng phí—“học sinh giỏi” chi tiêu hợp lý 💚',
      id: 'Hampir tidak boros—pengeluaran rasional juara kelas 💚',
    }),
    diagnosisGrade: T({
      ko: '[진단] 멍청비용 발생량: 최저 등급',
      en: '[Diagnosis] Dumb spending level: lowest tier',
      ja: '【診断】ムダ遣い量：最低レベル',
      zhCN: '【诊断】冤枉钱程度：最低档',
      zhTW: '【診斷】冤枉錢程度：最低檔',
      vi: '[Chẩn đoán] Mức lãng phí: thấp nhất',
      id: '[Diagnosis] Level pemborosan bodoh: terendah',
    }),
    hookLine: T({
      ko: '"당신의 소비는 꽤 합리적입니다. 하지만 방심하면 언제든 새기 시작합니다."',
      en: '"Your spending is fairly rational—but the moment you relax, leaks can start."',
      ja: '「あなたの支出はかなり合理的。油断すればいつでも漏れが始まります。」',
      zhCN: '“你的消费相当理性，但一松懈随时可能开始漏钱。”',
      zhTW: '「你的消費相當理性，但一鬆懈隨時可能開始漏錢。」',
      vi: '“Chi tiêu của bạn khá hợp lý—nhưng chỉ cần lơ là là tiền có thể rò.”',
      id: '“Belanjamu cukup rasional—tapi kalau lengah, uang bisa mulai merembes.”',
    }),
    description: T({
      ko: '현재 당신의 소비 패턴은 비교적 건강한 상태입니다. 구독 서비스를 파악하고 있고, 충동구매보다 계획 구매 비율이 높으며, 할인에 쉽게 흔들리지 않는 편입니다. 다만 완벽한 사람은 없습니다. 지금의 좋은 습관을 유지하면서 혹시 모르게 새는 소액 정기결제가 없는지 한 번쯤 점검해보는 것을 권합니다.',
      en: 'Your spending pattern is relatively healthy. You track subscriptions, lean toward planned purchases over impulse, and do not get swayed by discounts easily. Nobody is perfect—keep your good habits, but scan once in a while for small recurring charges you might have forgotten.',
      ja: '今の消費パターンは比較的健全です。サブスクを把握し、衝動買いより計画買いが多く、セールに流されにくい傾向です。ただ完璧な人はいません。良い習慣を保ちつつ、小さな定期課金が漏れていないか一度チェックすることを勧めます。',
      zhCN: '你目前的消费习惯相对健康：掌握订阅、计划性购买多于冲动消费，也不太容易被折扣带着走。不过没有完美的人。建议在保持好习惯的同时，偶尔检查是否还有悄悄扣款的小额定期付费。',
      zhTW: '你目前的消費習慣相對健康：掌握訂閱、計畫性購買多於衝動消費，也不太容易被折扣帶著走。不過沒有完美的人。建議在保持好習慣的同時，偶爾檢查是否還有悄悄扣款的小額定期付費。',
      vi: 'Thói chi tiêu của bạn tương đối lành mạnh: nắm rõ gói đăng ký, mua có kế hoạch hơn mua ngẫu hứng, và ít bị khuyến mãi lay chuyển. Không ai hoàn hảo—hãy giữ thói quen tốt và thỉnh thoảng rà soát các khoản trừ tiền định kỳ nhỏ có thể bị quên.',
      id: 'Pola belanjamu relatif sehat: langganan terkontrol, belanja terencana lebih dominan dari impuls, dan tidak mudah tergoda diskon. Tidak ada yang sempurna—pertahankan kebiasaan baikmu dan sesekali periksa tagihan kecil berulang yang mungkin terlupakan.',
    }),
    detailSectionTitle: T({
      ko: '멍청비용 취약 포인트',
      en: 'Where dumb spending can still sneak in',
      ja: 'ムダ遣いが入り込みやすいポイント',
      zhCN: '冤枉钱仍可能渗入的弱点',
      zhTW: '冤枉錢仍可能滲入的弱點',
      vi: 'Điểm yếu có thể để lãng phí lọt vào',
      id: 'Titik rawan pemborosan bisa masuk',
    }),
    detailBullets: T({
      ko: '소액 구독료 방심: 월 1~2만 원짜리 서비스가 쌓이면 연간 20만 원 이상\n포인트 미사용: 쌓아두고 쓰지 않는 포인트가 의외로 큰 금액일 수 있음',
      en: 'Small subscriptions add up: a few 10–20K KRW/month services can exceed 200K KRW/year\nUnused points: points you never redeem can quietly be a large amount',
      ja: '小額サブスクの油断：月1〜2万ウォンが積み重なると年20万ウォン超\n未使用ポイント：溜めて使わないポイントは意外と大きい',
      zhCN: '小额订阅麻痹：每月一两万韩元的服务堆起来，一年可能超过20万韩元\n积分闲置：攒着不用的积分可能金额不小',
      zhTW: '小額訂閱麻痺：每月一兩萬韓元的服務堆起來，一年可能超過20萬韓元\n點數閒置：攢著不用的點數可能金額不小',
      vi: 'Gói nhỏ chồng chất: vài dịch vụ 10k–20k KRW/tháng có thể vượt 200k KRW/năm\nĐiểm không đổi: để tích mà không dùng có thể thành số tiền lớn',
      id: 'Langganan kecil menumpuk: beberapa layanan 10–20rb KRW/bulan bisa melebihi 200rb KRW/tahun\nPoin tidak dipakai: menumpuk tanpa ditukar bisa jumlahnya besar',
    }),
    prescriptionSteps: T({
      ko: '분기에 한 번 전체 구독 서비스 목록 점검하기\n미사용 포인트 확인하고 이달 안에 사용하기\n지금의 좋은 습관을 가계부로 기록해서 유지하기',
      en: 'Once a quarter, review your full subscription list\nCheck unused points and use them this month\nKeep your good habits by logging spending in a budget app',
      ja: '四半期に一度、サブスク一覧を全チェック\n未使用ポイントを確認し今月中に使う\n良い習慣を家計簿アプリに記録して維持',
      zhCN: '每季度检查一次全部订阅\n查看未用积分并本月内用掉\n用记账应用记录以维持好习惯',
      zhTW: '每季檢查一次全部訂閱\n查看未用點數並本月內用掉\n用記帳 App 記錄以維持好習慣',
      vi: 'Mỗi quý rà soát toàn bộ đăng ký\nKiểm tra điểm chưa dùng và tiêu trong tháng này\nGhi chi tiêu trong app ngân sách để duy trì thói quen tốt',
      id: 'Setiap kuartal tinjau semua langganan\nCek poin tak terpakai dan gunakan bulan ini\nCatat di app keuangan untuk menjaga kebiasaan baik',
    }),
    monthlyWasteRange: T({
      ko: '1~3만 원 수준',
      en: 'About ₩10k–30k/mo',
      ja: '月1〜3万ウォン程度',
      zhCN: '约每月1–3万韩元水平',
      zhTW: '約每月1–3萬韓元水準',
      vi: 'Khoảng 10k–30k KRW/tháng',
      id: 'Sekitar 10–30rb KRW/bulan',
    }),
    yearlySaveRange: T({
      ko: '12~36만 원',
      en: 'About ₩120k–360k/yr you could save',
      ja: '年12〜36万ウォン',
      zhCN: '每年约12–36万韩元可省',
      zhTW: '每年約12–36萬韓元可省',
      vi: 'Khoảng 120k–360k KRW/năm có thể tiết kiệm',
      id: 'Sekitar 120–360rb KRW/tahun bisa dihemat',
    }),
    todayTask: T({
      ko: '통신사 포인트와 카드 포인트 잔액 확인',
      en: 'Check your carrier points and card reward balances',
      ja: 'キャリアポイントとカードポイント残高を確認',
      zhCN: '查看运营商积分与信用卡积分余额',
      zhTW: '查看電信積分與信用卡積分餘額',
      vi: 'Kiểm tra điểm nhà mạng và điểm thẻ',
      id: 'Cek poin operator dan saldo reward kartu',
    }),
    shareLine: T({
      ko: '내 멍청비용 유형은 합리적 소비 우등생 💚 그래도 포인트는 안 쓰고 있다는 거 들켰다 ㅋㅋ',
      en: 'My dumb-spending type: rational spender 💚 Caught not using my points though lol',
      ja: '私のムダ遣いタイプは合理的優等生 💚でもポイント使ってないのバレたｗ',
      zhCN: '我的冤枉钱类型是理性优等生 💚但不怎么用积分被发现了哈哈',
      zhTW: '我的冤枉錢類型是理性優等生 💚但不怎麼用點數被發現了哈哈',
      vi: 'Kiểu “tiền ngu” của mình: chi hợp lý 💚 Nhưng lộ là không dùng điểm haha',
      id: 'Tipe borosku: pengeluaran rasional 💚 Ketahuan tidak pakai poin haha',
    }),
    shareTypeName: T({
      ko: '합리적 소비 우등생 💚',
      en: 'Rational spender 💚',
      ja: '合理的な優等生 💚',
      zhCN: '理性消费优等生 💚',
      zhTW: '理性消費優等生 💚',
      vi: 'Chi tiêu hợp lý 💚',
      id: 'Pengeluaran rasional 💚',
    }),
  },
  {
    type: 'Type2',
    emoji: '📱',
    title: T({
      ko: '구독료에 무감각한, 자동결제 좀비 📱',
      en: 'Subscription-numb auto-pay zombie 📱',
      ja: 'サブスク無感覚、自動課金ゾンビ 📱',
      zhCN: '对订阅麻木的自动扣款僵尸 📱',
      zhTW: '對訂閱麻木的自動扣款殭屍 📱',
      vi: 'Vô cảm với phí đăng ký—xác sống thanh toán tự động 📱',
      id: 'Kebal biaya langganan—zombie debit otomatis 📱',
    }),
    diagnosisGrade: T({
      ko: '[진단] 멍청비용 발생량: 경계 등급 — 구독 서비스 누수 주의',
      en: '[Diagnosis] Borderline dumb spending—watch subscription leaks',
      ja: '【診断】境界レベル—サブスク漏れ注意',
      zhCN: '【诊断】边界级——注意订阅渗漏',
      zhTW: '【診斷】邊界級——注意訂閱滲漏',
      vi: '[Chẩn đoán] Mức ngưỡng—cảnh báo rò rỉ gói đăng ký',
      id: '[Diagnosis] Level peringatan—waspada kebocoran langganan',
    }),
    hookLine: T({
      ko: '"지금 이 순간도 어딘가에서 결제가 되고 있을 수 있습니다."',
      en: '"Right now something could be charging you somewhere."',
      ja: '「今この瞬間もどこかで課金されているかもしれません。」',
      zhCN: '“此刻也许正有某处在扣你的钱。”',
      zhTW: '「此刻也許正有某處在扣你的錢。」',
      vi: '“Ngay lúc này có thể đang có khoản trừ tiền ở đâu đó.”',
      id: '“Saat ini juga mungkin ada yang sedang memotong uangmu di suatu tempat.”',
    }),
    description: T({
      ko: '당신의 주요 멍청비용은 잊고 있는 구독 서비스와 자동결제에서 발생하고 있습니다. 처음엔 필요해서 가입했는데 지금은 거의 안 쓰는 것들, 무료 체험 기간이 끝난 뒤 그냥 결제가 되고 있는 것들이 쌓여 있을 가능성이 높습니다. 월 몇 천 원짜리라서 대수롭지 않게 넘겼겠지만 모이면 매달 3~5만 원이 그냥 사라지고 있습니다.',
      en: 'Most of your dumb spending comes from forgotten subscriptions and autopay. Things you needed at first but barely use now, or trials that rolled into paid plans, may be stacking up. A few thousand KRW each feels small—together it can quietly drain 30–50K KRW every month.',
      ja: '主なムダ遣いは、忘れたサブスクと自動課金から出ています。最初は必要で入ったが今はほぼ使わないもの、無料期間後にそのまま課金が続いているものが積み重なっている可能性が高いです。月数千ウォンは小さく見えても、合わせると毎月3〜5万ウォンが消えます。',
      zhCN: '你的冤枉钱主要来自被遗忘的订阅和自动扣款。一开始需要而开通、现在几乎不用的服务，以及试用结束后仍在扣费的项目，很可能已经堆叠。每月几千韩元看似不多，加起来每月可能白白消失3–5万韩元。',
      zhTW: '你的冤枉錢主要來自被遺忘的訂閱與自動扣款。一開始需要而開通、現在幾乎不用的服務，以及試用結束後仍在扣費的項目，很可能已經堆疊。每月幾千韓元看似不多，加起來每月可能白白消失3–5萬韓元。',
      vi: 'Phần lớn tiền “ngu” đến từ gói đăng ký quên và thanh toán tự động. Những thứ lúc đầu cần nhưng giờ gần như không dùng, hoặc gói dùng thử chuyển sang trả phí, có thể đang chồng chất. Mỗi tháng vài nghìn KRW nghe nhỏ—cộng lại có thể mất 30–50k KRW/tháng.',
      id: 'Pemborosan utamamu dari langganan terlupakan dan pembayaran otomatis. Yang awalnya perlu kini jarang dipakai, atau masa percobaan yang lanjut berbayar, bisa menumpuk. Beberapa ribu KRW per bulan terasa kecil—bersama bisa menghilang 30–50rb KRW setiap bulan.',
    }),
    detailSectionTitle: T({
      ko: '대표 멍청비용 패턴',
      en: 'Signature dumb-spending patterns',
      ja: '代表的なムダ遣いパターン',
      zhCN: '典型冤枉钱模式',
      zhTW: '典型冤枉錢模式',
      vi: 'Mô hình lãng phí điển hình',
      id: 'Pola pemborosan khas',
    }),
    detailBullets: T({
      ko: 'OTT 구독 2개 이상 동시 유지 (실제로는 1개만 보는 중)\n앱 프리미엄 구독이 무료 체험 후 자동 전환\n헬스장·필라테스 등 운동 시설 안 가면서 결제 중\n클라우드 스토리지 용량 업그레이드 후 필요성 소멸',
      en: 'Multiple OTT subs at once (you only really watch one)\nApp premium rolled from a free trial into paid\nGym/pilates fees while you barely go\nCloud storage upgraded, then you stopped needing the space',
      ja: 'OTTを2つ以上同時維持（実際は1つだけ見ている）\nアプリ課金が無料トライアル後に自動継続\nジム・ピラティスに行かないのに課金\nクラウド容量を上げたが必要性が消えた',
      zhCN: '同时开多个流媒体（实际只看一个）\nApp 试用结束自动续费\n健身房/普拉提不去仍在扣费\n云空间升级后其实不再需要',
      zhTW: '同時開多個串流（實際只看一個）\nApp 試用結束自動續費\n健身房／皮拉提斯不去仍在扣費\n雲空間升級後其實不再需要',
      vi: 'Nhiều gói OTT cùng lúc (thực tế chỉ xem một)\nPremium app tự gia hạn sau dùng thử\nPhí gym/pilates trong khi không đến\nNâng cấp cloud rồi không còn cần',
      id: 'Beberapa OTT sekaligus (hanya satu yang dipakai)\nPremium app lanjut setelah trial\nBiaya gym/pilates padahal jarang datang\nUpgrade cloud lalu tidak perlu lagi',
    }),
    prescriptionSteps: T({
      ko: '지금 당장 은행 앱에서 정기결제 항목 전체 조회하기\n3개월 이상 안 쓴 구독 서비스는 오늘 해지하기\nOTT는 한 번에 하나씩 돌아가며 이용하는 로테이션 전략 적용',
      en: 'Open your banking app now and list every recurring charge\nCancel subscriptions you have not used in 3+ months—today\nRotate OTT: keep one active at a time and switch monthly',
      ja: '今すぐ銀行アプリで定期課金を全表示\n3ヶ月以上使っていないサブスクは今日解約\nOTTは1つずつローテーション',
      zhCN: '立刻在银行 App 查看全部定期扣款\n三个月没用的订阅今天就退\n流媒体一次只开一个，按月轮换',
      zhTW: '立刻在銀行 App 查看全部定期扣款\n三個月沒用的訂閱今天就退\n串流一次只開一個，按月輪換',
      vi: 'Mở app ngân hàng và liệt kê mọi khoản định kỳ\nHủy gói không dùng trên 3 tháng—hôm nay\nLuân phiên OTT: mỗi lúc một dịch vụ',
      id: 'Buka app bank dan daftar semua tagihan berulang\nBatalkan langganan tidak dipakai 3+ bulan—hari ini\nRotasi OTT: satu aktif lalu ganti bulanan',
    }),
    monthlyWasteRange: T({
      ko: '3~7만 원',
      en: 'About ₩30k–70k/mo',
      ja: '月3〜7万ウォン',
      zhCN: '每月约3–7万韩元',
      zhTW: '每月約3–7萬韓元',
      vi: 'Khoảng 30k–70k KRW/tháng',
      id: 'Sekitar 30–70rb KRW/bulan',
    }),
    yearlySaveRange: T({
      ko: '36~84만 원',
      en: 'About ₩360k–840k/yr',
      ja: '年36〜84万ウォン',
      zhCN: '每年约36–84万韩元可省',
      zhTW: '每年約36–84萬韓元可省',
      vi: 'Khoảng 360k–840k KRW/năm',
      id: 'Sekitar 360–840rb KRW/tahun',
    }),
    todayTask: T({
      ko: '핸드폰 앱스토어 → 구독 → 활성 구독 목록 전체 확인',
      en: 'Phone app store → Subscriptions → review every active sub',
      ja: 'スマホのストア→サブスク→有効な一覧を全部確認',
      zhCN: '手机应用商店 → 订阅 → 查看全部有效订阅',
      zhTW: '手機 App 商店 → 訂閱 → 查看全部有效訂閱',
      vi: 'Cửa hàng app điện thoại → Đăng ký → xem toàn bộ đang hoạt động',
      id: 'App store ponsel → Langganan → cek semua yang aktif',
    }),
    shareLine: T({
      ko: '내 멍청비용 유형은 자동결제 좀비 📱 지금도 어딘가서 결제 중이라는 거 진짜 공감 ㅋㅋ',
      en: 'My dumb-spending type: auto-pay zombie 📱 Still charging somewhere—too real lol',
      ja: '私のムダ遣いタイプは自動課金ゾンビ 📱今もどこかで課金中、わかるｗ',
      zhCN: '我的冤枉钱类型是自动扣款僵尸 📱还在某处扣费太真实了哈哈',
      zhTW: '我的冤枉錢類型是自動扣款殭屍 📱還在某處扣費太真實了哈哈',
      vi: 'Kiểu tiền ngu: zombie thanh toán tự động 📱 Vẫn đang trừ tiền đâu đó—đúng quá haha',
      id: 'Tipe boros: zombie debit otomatis 📱 Masih ada yang memotong—relatable haha',
    }),
    shareTypeName: T({
      ko: '자동결제 좀비 📱',
      en: 'Auto-pay zombie 📱',
      ja: '自動課金ゾンビ 📱',
      zhCN: '自动扣款僵尸 📱',
      zhTW: '自動扣款殭屍 📱',
      vi: 'Zombie thanh toán tự động 📱',
      id: 'Zombie debit otomatis 📱',
    }),
  },
  {
    type: 'Type3',
    emoji: '🏷️',
    title: T({
      ko: '할인에 역으로 당하는, 세일 역이용 피해자 🏷️',
      en: 'Sale-trap victim—“saving” that costs more 🏷️',
      ja: 'セールに逆にやられる、逆利用の被害者 🏷️',
      zhCN: '被折扣反噬的促销受害者 🏷️',
      zhTW: '被折扣反噬的促銷受害者 🏷️',
      vi: 'Nạn nhân khuyến mãi—tiết kiệm ngược 🏷️',
      id: 'Korban diskon—hemat yang malah rugi 🏷️',
    }),
    diagnosisGrade: T({
      ko: '[진단] 멍청비용 발생량: 주의 등급 — 할인 함정 반복 패턴',
      en: '[Diagnosis] Caution tier—repeating discount traps',
      ja: '【診断】注意レベル—セールの罠が繰り返し',
      zhCN: '【诊断】注意级——反复掉入折扣陷阱',
      zhTW: '【診斷】注意級——反覆掉入折扣陷阱',
      vi: '[Chẩn đoán] Mức cảnh báo—lặp lại bẫy giảm giá',
      id: '[Diagnosis] Peringatan—jebakan diskon berulang',
    }),
    hookLine: T({
      ko: '"더 아끼려다가 더 쓰고 있습니다. 이게 바로 할인의 역설입니다."',
      en: '"You spend more trying to save more—that is the discount paradox."',
      ja: '「節約しようとして余計に使っている。それがセールの逆説。」',
      zhCN: '“越想省反而花得越多——这就是折扣悖论。”',
      zhTW: '「越想省反而花得越多——這就是折扣悖論。」',
      vi: '“Càng cố tiết kiệm càng tiêu nhiều—đó là nghịch lý giảm giá.”',
      id: '“Semakin ingin hemat malah makin boros—paradoks diskon.”',
    }),
    description: T({
      ko: '당신의 주요 멍청비용은 아이러니하게도 절약하려다 발생하고 있습니다. 무료 배송 조건 맞추려다 필요 없는 것을 추가하고, 대용량이 싸다고 샀다가 다 못 쓰고 버리고, 오늘만 할인이라는 말에 급하게 구매하는 패턴이 반복되고 있습니다. 10% 할인받으려다 30%를 더 쓰는 구조입니다.',
      en: 'Ironically, your dumb spending happens while “saving.” You add filler to hit free shipping, buy bulk you throw away, or rush-buy on “today only” deals. It is the classic 10% off that makes you spend 30% more.',
      ja: '皮肉なことに、ムダ遣いは「節約」のつもりで起きています。送料無料のために不要品を足し、安いからと大量購入して捨てたり、「今日だけセール」に急いで買ったりが繰り返されます。10％オフのために30％多く使う構造です。',
      zhCN: '讽刺的是，冤枉钱往往发生在“省钱”时：为凑包邮加购不需要的东西、图便宜囤大包装却浪费、被“仅限今日”催着下单。常见结构是：为省10%却多花了30%。',
      zhTW: '諷刺的是，冤枉錢往往發生在「省錢」時：為湊免運加購不需要的東西、圖便宜囤大包裝卻浪費、被「限時」催著下單。常見結構是：為省10%卻多花了30%。',
      vi: 'Trớ trêu thay, tiền “ngu” lại đến khi đang “tiết kiệm”: thêm hàng để freeship, mua số lượng lớn rồi vứt, hoặc mua vội vì “chỉ hôm nay.” Cấu trúc kinh điển: để giảm 10% lại tiêu thêm 30%.',
      id: 'Ironisnya pemborosan terjadi saat “hemat”: tambah barang demi ongkir gratis, beli besar lalu buang, atau buru-buru karena “hanya hari ini.” Pola klasik: demi diskon 10% malah keluar 30% lebih banyak.',
    }),
    detailSectionTitle: T({
      ko: '대표 멍청비용 패턴',
      en: 'Signature dumb-spending patterns',
      ja: '代表的なムダ遣いパターン',
      zhCN: '典型冤枉钱模式',
      zhTW: '典型冤枉錢模式',
      vi: 'Mô hình lãng phí điển hình',
      id: 'Pola pemborosan khas',
    }),
    detailBullets: T({
      ko: '무료 배송 기준 3만 원 채우려다 2만 원어치 더 구매\n1+1 행사에 하나는 필요 없는데 두 개 구매\n쿠폰 마감 임박에 필요 없는 물건 급구매\n대용량 구매 후 유통기한 내 소진 실패',
      en: 'Spending extra to hit a free-shipping threshold\nBOGO when you only needed one\nPanic-buying junk before a coupon expires\nBulk buys you cannot finish before they expire',
      ja: '送料無料のために余計に購入\n1+1で要らないものまで2つ\nクーポン期限前に不要品を急購入\n大容量を買い切れず期限切れ',
      zhCN: '为凑包邮多买两万\n买一送一多拿不需要的那份\n券快过期乱买不需要的东西\n大包装没吃完就过期',
      zhTW: '為湊免運多買兩萬\n買一送一多拿不需要的那份\n券快過期亂買不需要的東西\n大包裝沒吃完就過期',
      vi: 'Mua thêm để đủ freeship\nMua 1 tặng 1 nhưng chỉ cần một\nMua vội trước khi coupon hết hạn\nMua số lớn không kịp dùng hết hạn',
      id: 'Belanja ekstra demi ongkir gratis\nBOGO padahal cuma perlu satu\nBeli panik sebelum kupon habis\nBeli besar tidak habis sebelum kedaluwarsa',
    }),
    prescriptionSteps: T({
      ko: '배달·쇼핑 전 살 것 목록 미리 적고 목록 외 구매 금지\n할인 전 "이게 없었다면 샀을까?" 질문 먼저 하기\n무료 배송 조건보다 유료 배송비가 더 저렴한지 계산하는 습관',
      en: 'Before delivery or shopping, write a list—no off-list buys\nBefore any “deal,” ask: “Would I buy this without the discount?”\nCompare paid shipping vs. buying extra to get free shipping',
      ja: 'デリバー・買い物前にリスト作成、リスト外は禁止\nセール前に「これがなくても買う？」と問う\n送料無料のために買い足すより、送料払いの方が安いか計算',
      zhCN: '外卖/购物前列清单，清单外不买\n打折前先问：“没有它我还会买吗？”\n算算付运费是否比为包邮凑单更便宜',
      zhTW: '外送／購物前列清單，清單外不買\n打折前先問：「沒有它我還會買嗎？」\n算算付運費是否比為免運湊單更便宜',
      vi: 'Trước khi giao/ mua sắm, viết danh sách—không mua ngoài danh sách\nTrước khi “deal,” hỏi: “Không có khuyến mãi thì còn mua không?”\nSo sánh phí ship trả thêm vs. mua thêm để freeship',
      id: 'Sebelum antar/belanja, buat daftar—tanpa beli di luar daftar\nSebelum diskon, tanya: “Tanpa diskon masih beli?”\nBandingkan ongkir berbayar vs. belanja ekstra demi gratis ongkir',
    }),
    monthlyWasteRange: T({
      ko: '4~10만 원',
      en: 'About ₩40k–100k/mo',
      ja: '月4〜10万ウォン',
      zhCN: '每月约4–10万韩元',
      zhTW: '每月約4–10萬韓元',
      vi: 'Khoảng 40k–100k KRW/tháng',
      id: 'Sekitar 40–100rb KRW/bulan',
    }),
    yearlySaveRange: T({
      ko: '48~120만 원',
      en: 'About ₩480k–1.2M/yr',
      ja: '年48〜120万ウォン',
      zhCN: '每年约48–120万韩元可省',
      zhTW: '每年約48–120萬韓元可省',
      vi: 'Khoảng 480k–1,2 triệu KRW/năm',
      id: 'Sekitar 480rb–1,2 juta KRW/tahun',
    }),
    todayTask: T({
      ko: '냉장고 정리하면서 못 먹고 버린 식재료 금액 계산해보기',
      en: 'Clean the fridge and estimate money lost on food you threw out',
      ja: '冷蔵庫整理で、捨てた食材の金額を計算',
      zhCN: '整理冰箱，估算扔掉食材值多少钱',
      zhTW: '整理冰箱，估算扔掉食材值多少錢',
      vi: 'Dọn tủ lạnh và ước tính tiền thực phẩm đã vứt',
      id: 'Bersihkan kulkas dan hitung uang makanan terbuang',
    }),
    shareLine: T({
      ko: '내 멍청비용 유형은 세일 역이용 피해자 🏷️ 아끼려다 더 쓰는 패턴 진짜 나 맞다 ㅋㅋ',
      en: 'My dumb-spending type: sale-trap victim 🏷️ “Saving” that spends more—so me lol',
      ja: '私のムダ遣いタイプはセール被害者 🏷️節約のつもりが出費増、わかるｗ',
      zhCN: '我的冤枉钱类型是促销受害者 🏷️越省越花太准了哈哈',
      zhTW: '我的冤枉錢類型是促銷受害者 🏷️越省越花太準了哈哈',
      vi: 'Kiểu tiền ngu: nạn nhân sale 🏷️ Càng “tiết kiệm” càng tiêu—đúng mình haha',
      id: 'Tipe boros: korban diskon 🏷️ Makin hemat makin boros—aku banget haha',
    }),
    shareTypeName: T({
      ko: '세일 역이용 피해자 🏷️',
      en: 'Sale-trap victim 🏷️',
      ja: 'セール被害者 🏷️',
      zhCN: '促销受害者 🏷️',
      zhTW: '促銷受害者 🏷️',
      vi: 'Nạn nhân khuyến mãi 🏷️',
      id: 'Korban diskon 🏷️',
    }),
  },
  {
    type: 'Type4',
    emoji: '⚡',
    title: T({
      ko: '귀찮음이 돈으로 나가는, 편의 프리미엄 낭비자 ⚡',
      en: 'Convenience spender—laziness priced in premium ⚡',
      ja: '面倒がお金に変わる、便利課金のムダ遣い ⚡',
      zhCN: '嫌麻烦换来的便利溢价浪费者 ⚡',
      zhTW: '嫌麻煩換來的便利溢價浪費者 ⚡',
      vi: 'Chi tiền cho sự tiện—lười biếng đắt đỏ ⚡',
      id: 'Pembayaran demi kemudahan—kemalasan jadi mahal ⚡',
    }),
    diagnosisGrade: T({
      ko: '[진단] 멍청비용 발생량: 위험 등급 — 편의성 추구 과금 누적',
      en: '[Diagnosis] High tier—convenience fees stacking up',
      ja: '【診断】危険レベル—便利追求の課金が積み上がり',
      zhCN: '【诊断】危险级——便利溢价不断累积',
      zhTW: '【診斷】危險級——便利溢價不斷累積',
      vi: '[Chẩn đoán] Mức nguy hiểm—phí tiện lợi chồng chất',
      id: '[Diagnosis] Level berbahaya—biaya kenyamanan menumpuk',
    }),
    hookLine: T({
      ko: '"귀찮다는 이유로 매달 몇 만 원이 사라지고 있습니다."',
      en: '"Every month, tens of thousands disappear just because you could not be bothered."',
      ja: '「面倒くさいという理由で、毎月何万ウォンが消えています。」',
      zhCN: '“每个月都有几万块，仅仅因为嫌麻烦就没了。”',
      zhTW: '「每個月都有好幾萬，僅僅因為嫌麻煩就沒了。」',
      vi: '“Hàng tháng vài chục nghìn biến mất chỉ vì ngại.”',
      id: '“Setiap bulan puluhan ribu hilang karena malas saja.”',
    }),
    description: T({
      ko: '당신의 주요 멍청비용은 귀찮음을 돈으로 해결하는 과정에서 발생하고 있습니다. 직접 하면 무료인데 귀찮아서 유료 서비스를 선택하고, 기본 옵션이면 충분한데 습관적으로 프리미엄을 선택하고, 조금 움직이면 해결되는데 배달을 시키는 패턴이 쌓이고 있습니다. 편의에 대한 비용 자체가 나쁜 것은 아닙니다. 하지만 그 편의가 실제로 필요한 것인지 확인이 필요합니다.',
      en: 'Your dumb spending piles up when you buy your way out of hassle. Free if you DIY—but you pay for services; basic would be enough—but you default to premium; short walk—but you order delivery. Paying for convenience is not evil—just check whether that convenience is worth the price.',
      ja: 'ムダ遣いは「面倒を金で解消」から積み上がります。自分でやれば無料なのに有料を選ぶ、基本で十分なのにプレミアムを選ぶ、少し動けば済むのにデリバリー。便利の対価が悪いわけではありませんが、その便利が本当に必要か確認が必要です。',
      zhCN: '你的冤枉钱常来自用钱换省事：本可自己做却选付费、基础够用却习惯性点高级、走几步能解决却叫外卖。为便利付费没错，但要确认这便利是否真的值得。',
      zhTW: '你的冤枉錢常來自用錢換省事：本可自己做卻選付費、基礎夠用卻習慣性點進階、走幾步能解決卻叫外送。為便利付費沒錯，但要確認這便利是否真的值得。',
      vi: 'Tiền “ngu” chồng lên khi bạn trả tiền để khỏi phiền. Tự làm thì miễn phí nhưng chọn dịch vụ trả phí; gói cơ bản đủ nhưng mặc định premium; đi bộ được nhưng giao đồ ăn. Trả tiền cho tiện không xấu—chỉ cần xem có đáng không.',
      id: 'Pemborosan menumpuk saat kamu bayar untuk hindari repot. Bisa gratis DIY tapi pilih berbayar; dasar cukup tapi default premium; jalan sebentar tapi pesan antar. Bayar kenyamanan tidak salah—cek apakah layak.',
    }),
    detailSectionTitle: T({
      ko: '대표 멍청비용 패턴',
      en: 'Signature dumb-spending patterns',
      ja: '代表的なムダ遣いパターン',
      zhCN: '典型冤枉钱模式',
      zhTW: '典型冤枉錢模式',
      vi: 'Mô hình lãng phí điển hình',
      id: 'Pola pemborosan khas',
    }),
    detailBullets: T({
      ko: '가까운 거리인데 배달 시키기\n기본 옵션이면 충분한데 습관적 프리미엄 선택\n집에 있는 재료로 해결될 것을 귀찮아서 사먹기\n직접 하면 무료인 일을 유료 서비스에 맡기기',
      en: 'Ordering delivery for a short distance\nDefaulting to premium when basic is enough\nBuying food because cooking at home feels annoying\nPaying for services you could do yourself for free',
      ja: '近いのにデリバリー\n基本で十分なのに癖でプレミアム\n家にあるのに面倒で外食・購入\n自分で無料のことを有料に任せる',
      zhCN: '很近还叫外卖\n基础够用却习惯性选高级\n家里有料却嫌麻烦外食/外买\n本可自己做却花钱请人',
      zhTW: '很近還叫外送\n基礎夠用卻習慣性選進階\n家裡有料卻嫌麻煩外食／外買\n本可自己做卻花錢請人',
      vi: 'Giao đồ ăn dù gần\nMặc định premium khi cơ bản đủ\nMua ngoài vì lười nấu dù có đồ ở nhà\nThuê dịch vụ cho việc tự làm miễn phí',
      id: 'Pesan antar padahal dekat\nPremium padahal dasar cukup\nBeli karena malas masak padahal ada bahan\nBayar jasa untuk hal yang gratis jika DIY',
    }),
    prescriptionSteps: T({
      ko: '한 달 동안 프리미엄 옵션 선택할 때마다 메모하고 월말에 합산하기\n배달비 아낄 금액으로 한 달에 한 번 특별한 외식하기\n편의 비용을 쓸 때 "이 귀찮음이 이 돈만큼의 가치가 있나?" 물어보기',
      en: 'For one month, note every premium tap and total it at month-end\nUse delivery savings for one nice meal out per month\nBefore paying for convenience, ask: “Is this annoyance worth this much?”',
      ja: '1ヶ月、プレミアムを選ぶたびメモして月末に合計\nデリバーで浮いた分で月1回は外食のご褒美\n便利にお金を払う前に「この面倒さはこの金額の価値？」と問う',
      zhCN: '一个月里每次选高级版都记下来，月底加总\n把省下的配送费换成每月一次像样的外食\n付便利费前问：“这点麻烦值这些钱吗？”',
      zhTW: '一個月裡每次選進階版都記下來，月底加總\n把省下的運費換成每月一次像樣的外食\n付便利費前問：「這點麻煩值這些錢嗎？」',
      vi: 'Một tháng, ghi mỗi lần chọn premium, cuối tháng cộng lại\nDùng tiền tiết kiệm ship cho một bữa ngoài “xứng đáng” mỗi tháng\nTrước khi trả tiện lợi, hỏi: “Sự phiền này có đáng bấy nhiêu tiền không?”',
      id: 'Sebulan, catat setiap pilih premium, total di akhir bulan\nGunakan hemat ongkir untuk satu makan enak per bulan\nSebelum bayar kenyamanan, tanya: “Seberapa repotnya dibanding uang ini?”',
    }),
    monthlyWasteRange: T({
      ko: '6~15만 원',
      en: 'About ₩60k–150k/mo',
      ja: '月6〜15万ウォン',
      zhCN: '每月约6–15万韩元',
      zhTW: '每月約6–15萬韓元',
      vi: 'Khoảng 60k–150k KRW/tháng',
      id: 'Sekitar 60–150rb KRW/bulan',
    }),
    yearlySaveRange: T({
      ko: '72~180만 원',
      en: 'About ₩720k–1.8M/yr',
      ja: '年72〜180万ウォン',
      zhCN: '每年约72–180万韩元可省',
      zhTW: '每年約72–180萬韓元可省',
      vi: 'Khoảng 720k–1,8 triệu KRW/năm',
      id: 'Sekitar 720rb–1,8 juta KRW/tahun',
    }),
    todayTask: T({
      ko: '이번 달 배달비 총액 카드 앱에서 확인하기. 숫자를 보면 동기부여가 됩니다',
      en: 'In your card app, check total delivery fees for this month—seeing the number motivates cuts',
      ja: '今月のデリバリー料金合計をカードアプリで確認（数字で動機づけ）',
      zhCN: '在银行卡 App 查看本月配送费总额，数字会推动你省钱',
      zhTW: '在銀行卡 App 查看本月配送費總額，數字會推動你省錢',
      vi: 'Trong app thẻ, xem tổng phí giao hàng tháng này—con số sẽ thúc đẩy',
      id: 'Di app kartu, cek total ongkir bulan ini—angkanya memotivasi',
    }),
    shareLine: T({
      ko: '내 멍청비용 유형은 편의 프리미엄 낭비자 ⚡ 귀찮음이 매달 몇 만 원이라는 거 진짜 현실이네 ㅋㅋ',
      en: 'My dumb-spending type: convenience premium ⚡ Laziness really costs every month lol',
      ja: '私のムダ遣いタイプは便利課金 ⚡面倒が毎月何万ウォン、現実ｗ',
      zhCN: '我的冤枉钱类型是便利溢价 ⚡每月几万块嫌麻烦费太真实哈哈',
      zhTW: '我的冤枉錢類型是便利溢價 ⚡每月好幾萬嫌麻煩費太真實哈哈',
      vi: 'Kiểu tiền ngu: phí tiện lợi ⚡ Lười mỗi tháng mất vài chục nghìn—đúng thật haha',
      id: 'Tipe boros: premium kenyamanan ⚡ Malas tiap bulan habis puluhan ribu—nyata haha',
    }),
    shareTypeName: T({
      ko: '편의 프리미엄 낭비자 ⚡',
      en: 'Convenience premium ⚡',
      ja: '便利課金ムダ遣い ⚡',
      zhCN: '便利溢价浪费者 ⚡',
      zhTW: '便利溢價浪費者 ⚡',
      vi: 'Phí tiện lợi ⚡',
      id: 'Premium kenyamanan ⚡',
    }),
  },
  {
    type: 'Type5',
    emoji: '🛒',
    title: T({
      ko: '충동이 지갑을 지배하는, 순간 충동 탕진러 🛒',
      en: 'Impulse spender—your cart runs the show 🛒',
      ja: '衝動が財布を支配、瞬間ドカン散財 🛒',
      zhCN: '冲动支配钱包的瞬间挥霍者 🛒',
      zhTW: '衝動支配錢包的瞬間揮霍者 🛒',
      vi: 'Mua ngẫu hứng—ví tiền theo cảm xúc 🛒',
      id: 'Belanja impuls—dompet ikut emosi 🛒',
    }),
    diagnosisGrade: T({
      ko: '[진단] 멍청비용 발생량: 심각 등급 — 충동 소비 패턴 즉시 교정 필요',
      en: '[Diagnosis] Severe—fix impulse spending now',
      ja: '【診断】深刻レベル—衝動買いは今すぐ改善',
      zhCN: '【诊断】严重级——请立即纠正冲动消费',
      zhTW: '【診斷】嚴重級——請立即糾正衝動消費',
      vi: '[Chẩn đoán] Nghiêm trọng—cần sửa mua ngay lập tức',
      id: '[Diagnosis] Parah—perbaiki belanja impuls sekarang',
    }),
    hookLine: T({
      ko: '"살 때는 행복한데 통장 잔액 볼 때는 왜 이렇게 무서울까요?"',
      en: '"Buying feels great—so why is the balance so scary?"',
      ja: '「買うときは幸せなのに、残高を見るとなぜ怖いの？」',
      zhCN: '“买的时候很开心，看余额为什么那么可怕？”',
      zhTW: '「買的時候很開心，看餘額為什麼那麼可怕？」',
      vi: '“Mua thì vui mà nhìn số dư lại sợ?”',
      id: '“Belanja senang, lihat saldo kok seram?”',
    }),
    description: T({
      ko: '당신의 주요 멍청비용은 충동구매에서 발생하고 있습니다. 오늘만 할인이라는 말, 쿠폰 마감 임박이라는 알림, 장바구니 할인 쿠폰 유혹에 자주 무너지는 패턴이 있습니다. 구매하는 순간의 도파민은 강렬하지만 결제 후 며칠이 지나면 왜 샀는지 기억도 안 나는 물건들이 쌓이고 있습니다. 이 패턴을 교정하지 않으면 월급이 늘어도 잔액은 늘지 않습니다.',
      en: 'Most dumb spending is impulse: “today only,” expiring coupons, cart-discount nags. The dopamine hit at checkout is real—but days later you forget why you bought half of it. Until you break this pattern, a higher salary will not mean a higher balance.',
      ja: '主なムダ遣いは衝動買い。「今日だけ」「クーポン終了間近」「カート割引」に弱い。決済の瞬間のドーパミンは強いが、数日後にはなぜ買ったか分からない物が積み上がる。このパターンを直さないと、給料が上がっても残高は増えません。',
      zhCN: '冤枉钱多来自冲动：“仅限今日”、券将过期、购物车优惠提醒。结账瞬间很爽，几天后却想不起为什么买。不打破这个模式，加薪也不会增加余额。',
      zhTW: '冤枉錢多來自衝動：「限時」、券將過期、購物車優惠提醒。結帳瞬間很爽，幾天後卻想不起為什麼買。不打破這個模式，加薪也不會增加餘額。',
      vi: 'Lãng phí chủ yếu từ mua ngẫu hứng: “chỉ hôm nay,” coupon sắp hết, thông báo giảm giá giỏ. Lúc thanh toán phấn khích—vài ngày sau không nhớ vì sao mua. Không phá vỡ vòng này, tăng lương cũng không tăng số dư.',
      id: 'Pemborosan utama dari impuls: “hanya hari ini,” kupon hampir habis, notifikasi diskon keranjang. Saat bayar seru—beberapa hari kemudian lupa kenapa beli. Tanpa memutus pola ini, gaji naik tidak membuat saldo naik.',
    }),
    detailSectionTitle: T({
      ko: '대표 멍청비용 패턴',
      en: 'Signature dumb-spending patterns',
      ja: '代表的なムダ遣いパターン',
      zhCN: '典型冤枉钱模式',
      zhTW: '典型冤枉錢模式',
      vi: 'Mô hình lãng phí điển hình',
      id: 'Pola pemborosan khas',
    }),
    detailBullets: T({
      ko: '쿠폰 유효기간 마감 전 필요 없는 구매\n장바구니 할인 알림에 클릭해서 결국 구매\n한정판·오늘만 문구에 반응하는 즉흥 구매\n기억도 안 나는 충동 소액 구매 누적',
      en: 'Buying junk before a coupon expires\nClicking cart-discount alerts and checking out\nLimited / “today only” impulse grabs\nTiny impulse buys you do not even remember',
      ja: 'クーポン期限前の不要買い\nカート割引通知をクリックして結局購入\n限定・今日だけに反応する即興買い\n覚えていない小さな衝動買いの積み重ね',
      zhCN: '券快过期乱买不需要的\n点购物车折扣通知最后下单\n限量/限时冲动下单\n小额冲动买到想不起来',
      zhTW: '券快過期亂買不需要的\n點購物車折扣通知最後下單\n限量／限時衝動下單\n小額衝動買到想不起來',
      vi: 'Mua rác trước khi coupon hết\nBấm thông báo giảm giá giỏ rồi thanh toán\nMua vội vì “giới hạn / chỉ hôm nay”\nMua nhỏ tích lũy không nhớ',
      id: 'Beli tidak perlu sebelum kupon habis\nKlik notifikasi diskon keranjang lalu checkout\nBeli impuls edisi terbatas / hanya hari ini\nBelanja kecil menumpuk tidak ingat',
    }),
    prescriptionSteps: T({
      ko: '구매 전 24시간 룰 적용하기. 하루 자고 나서도 갖고 싶으면 그때 사기\n쇼핑 앱 푸시 알림 전체 끄기. 알림이 없으면 충동도 없음\n월 충동구매 예산 따로 설정하기. 그 안에서만 충동 허용',
      en: 'Use a 24-hour rule: if you still want it after sleeping on it, buy\nTurn off all shopping push alerts—no pings, fewer urges\nSet a monthly “impulse budget” and only impulse inside that cap',
      ja: '24時間ルール：一晩寝ても欲しければ買う\nショッピングアプリのプッシュを全部オフ\n月の衝動買い予算を決め、その中だけ許可',
      zhCN: '24小时规则：睡一晚还想买再买\n关掉所有购物推送—没提醒就少冲动\n设每月冲动预算，只在该额度内允许冲动',
      zhTW: '24 小時規則：睡一晚還想買再買\n關掉所有購物推播—沒提醒就少衝動\n設每月衝動預算，只在該額度內允許衝動',
      vi: 'Quy tắc 24 giờ: ngủ một đêm vẫn muốn thì mua\nTắt hết thông báo app mua sắm\nĐặt ngân sách mua ngẫu hứng hàng tháng',
      id: 'Aturan 24 jam: besok masih mau baru beli\nMatikan semua push app belanja\nAnggaran khusus belanja impuls per bulan',
    }),
    monthlyWasteRange: T({
      ko: '8~20만 원',
      en: 'About ₩80k–200k/mo',
      ja: '月8〜20万ウォン',
      zhCN: '每月约8–20万韩元',
      zhTW: '每月約8–20萬韓元',
      vi: 'Khoảng 80k–200k KRW/tháng',
      id: 'Sekitar 80–200rb KRW/bulan',
    }),
    yearlySaveRange: T({
      ko: '96~240만 원',
      en: 'About ₩960k–2.4M/yr',
      ja: '年96〜240万ウォン',
      zhCN: '每年约96–240万韩元可省',
      zhTW: '每年約96–240萬韓元可省',
      vi: 'Khoảng 960k–2,4 triệu KRW/năm',
      id: 'Sekitar 960rb–2,4 juta KRW/tahun',
    }),
    todayTask: T({
      ko: '쇼핑 앱 알림 설정 끄기 + 장바구니 비우기',
      en: 'Turn off shopping-app alerts + empty your cart',
      ja: 'ショッピングアプリの通知オフ＋カートを空に',
      zhCN: '关闭购物 App 通知并清空购物车',
      zhTW: '關閉購物 App 通知並清空購物車',
      vi: 'Tắt thông báo app mua sắm + dọn giỏ hàng',
      id: 'Matikan notifikasi app belanja + kosongkan keranjang',
    }),
    shareLine: T({
      ko: '내 멍청비용 유형은 순간 충동 탕진러 🛒 쿠폰 알림이 적이었구나 진짜 맞아 ㅋㅋ',
      en: 'My dumb-spending type: impulse splurger 🛒 Coupon alerts were the enemy—too real lol',
      ja: '私のムダ遣いタイプは衝動散財 🛒クーポン通知が敵だったｗ',
      zhCN: '我的冤枉钱类型是冲动挥霍 🛒原来优惠券通知才是对手哈哈',
      zhTW: '我的冤枉錢類型是衝動揮霍 🛒原來優惠券通知才是對手哈哈',
      vi: 'Kiểu tiền ngu: mua ngẫu hứng 🛒 Thông báo coupon mới là kẻ thù haha',
      id: 'Tipe boros: impuls 🛒 Notifikasi kupon memang musuhnya haha',
    }),
    shareTypeName: T({
      ko: '순간 충동 탕진러 🛒',
      en: 'Impulse splurger 🛒',
      ja: '衝動散財 🛒',
      zhCN: '冲动挥霍者 🛒',
      zhTW: '衝動揮霍者 🛒',
      vi: 'Mua ngẫu hứng 🛒',
      id: 'Impuls boros 🛒',
    }),
  },
  {
    type: 'Type6',
    emoji: '🌀',
    title: T({
      ko: '어디서 새는지도 모르는, 머니 블랙홀 🌀',
      en: 'Money black hole—you cannot even spot the leak 🌀',
      ja: 'どこで漏れるか分からない、マネーブラックホール 🌀',
      zhCN: '钱从哪漏都不知道的钱洞 🌀',
      zhTW: '錢從哪漏都不知道的錢洞 🌀',
      vi: 'Hố đen tiền—chẳng biết rò ở đâu 🌀',
      id: 'Lubang hitam uang—tidak tahu bocor di mana 🌀',
    }),
    diagnosisGrade: T({
      ko: '[진단] 멍청비용 발생량: 최고 등급 — 전면 소비 패턴 재설계 필요',
      en: '[Diagnosis] Maximum tier—rebuild your spending system',
      ja: '【診断】最高レベル—消費パターンの全面再設計が必要',
      zhCN: '【诊断】最高级——需全面重塑消费习惯',
      zhTW: '【診斷】最高級——需全面重塑消費習慣',
      vi: '[Chẩn đoán] Mức tối đa—cần thiết kế lại toàn bộ chi tiêu',
      id: '[Diagnosis] Tingkat maksimal—perlu susun ulang pola belanja',
    }),
    hookLine: T({
      ko: '"돈이 어디 갔는지 모르겠다는 말, 매달 하고 있죠?"',
      en: '"Where did my money go?"—you say it every month, right?',
      ja: '「お金どこ行った？」って、毎月言っていません？',
      zhCN: '“钱去哪儿了？”——你每个月都在说吧？',
      zhTW: '「錢去哪兒了？」——你每個月都在說吧？',
      vi: '“Tiền đi đâu rồi?”—mỗi tháng bạn đều nói nhỉ?',
      id: '“Uangku kemana?”—setiap bulan kamu bilang kan?',
    }),
    description: T({
      ko: '당신의 멍청비용은 특정 패턴 하나가 아니라 전방위에서 동시에 발생하고 있습니다. 안 쓰는 구독료, 할인 함정, 충동구매, 편의 비용이 모두 겹쳐서 빠져나가고 있습니다. 월급이 들어오는 속도보다 나가는 속도가 빠른 구조입니다. 지금 당장 전체 소비를 재점검하지 않으면 수입이 늘어도 잔액은 늘지 않는 패턴이 계속됩니다.',
      en: 'Your dumb spending is not one habit—it is everything at once: idle subs, sale traps, impulse buys, convenience fees. Money outpaces money in. Until you audit the whole picture, higher income will not grow your balance.',
      ja: 'ムダ遣いは一つの癖ではなく、全方位で同時に起きています。未使用サブスク、セールの罠、衝動買い、便利課金が重なる。入るより出る方が速い構造です。全体を見直さない限り、収入が増えても残高は増えません。',
      zhCN: '你的冤枉钱不是单一习惯，而是全方位同时发生：闲置订阅、促销陷阱、冲动消费、便利费叠加。支出快于收入。若不全面审视，加薪也不会增加余额。',
      zhTW: '你的冤枉錢不是單一習慣，而是全方位同時發生：閒置訂閱、促銷陷阱、衝動消費、便利費疊加。支出快於收入。若不全面審視，加薪也不會增加餘額。',
      vi: 'Không phải một thói xấu—mà là tất cả cùng lúc: đăng ký không dùng, bẫy sale, mua ngẫu hứng, phí tiện. Ra nhanh hơn vào. Không rà toàn cảnh thì tăng thu nhập cũng không tăng số dư.',
      id: 'Bukan satu kebiasaan—semua sekaligus: langganan nganggur, jebakan diskon, impuls, biaya kenyamanan. Keluar lebih cepat dari masuk. Tanpa audit total, penghasilan naik tidak menambah saldo.',
    }),
    detailSectionTitle: T({
      ko: '대표 멍청비용 패턴',
      en: 'Signature dumb-spending patterns',
      ja: '代表的なムダ遣いパターン',
      zhCN: '典型冤枉钱模式',
      zhTW: '典型冤枉錢模式',
      vi: 'Mô hình lãng phí điển hình',
      id: 'Pola pemborosan khas',
    }),
    detailBullets: T({
      ko: '인지하지 못하는 정기결제 다수\n할인에 역이용당하는 과구매\n충동구매와 편의 과금 동시 발생\n가계부 없음으로 인한 소비 파악 불가',
      en: 'Many recurring charges you do not notice\nOverspending from “saving” tricks\nImpulse + convenience costs at the same time\nNo budget log, so spending is a blur',
      ja: '気づいていない定期課金が多数\nセールに振り回される買いすぎ\n衝動と便利課金が同時\n家計簿なしで把握不能',
      zhCN: '大量未察觉的定期扣款\n被“省钱”套路买太多\n冲动与便利费同时发生\n没有记账，消费一片模糊',
      zhTW: '大量未察覺的定期扣款\n被「省錢」套路買太多\n衝動與便利費同時發生\n沒有記帳，消費一片模糊',
      vi: 'Nhiều khoản định kỳ không để ý\nMua quá vì chiêu “tiết kiệm”\nImpuls + phí tiện cùng lúc\nKhông sổ sách—chi tiêu mù mờ',
      id: 'Banyak tagihan rutin tidak disadari\nBelanja berlebihan karena trik “hemat”\nImpuls + biaya kenyamanan bersamaan\nTanpa catatan—pengeluaran kabur',
    }),
    prescriptionSteps: T({
      ko: '이번 주 안에 정기결제 전체 목록 조회 후 불필요 항목 해지\n가계부 앱 설치하고 2주간 지출 기록 시작하기. 숫자를 보는 것만으로 소비가 줄어듦\n월급날 생활비 통장과 저축 통장 분리하기. 분리가 곧 절약의 시작',
      en: 'This week: list every recurring charge and cancel what you do not need\nInstall a budget app and log spending for two weeks—seeing numbers cuts spend\nOn payday, split living money from savings—separation is where saving starts',
      ja: '今週中に定期課金を全部洗い出し、不要は解約\n家計簿アプリで2週間記録（数字を見るだけで減る）\n給料日に生活費と貯金口座を分ける。分けることが節約の第一歩',
      zhCN: '本周内列出全部定期扣款并退订不需要的\n安装记账 App 连续记两周支出，只看数字就会少花\n发薪日把生活费与储蓄账户分开，分账就是省钱的开始',
      zhTW: '本週內列出全部定期扣款並退訂不需要的\n安裝記帳 App 連續記兩週支出，只看數字就會少花\n發薪日把生活費與儲蓄帳戶分開，分帳就是省錢的開始',
      vi: 'Trong tuần: liệt kê mọi khoản định kỳ và hủy phần không cần\nCài app ngân sách, ghi chi 2 tuần—chỉ nhìn số cũng giảm chi\nNgày lương: tách tiền sinh hoạt và tiết kiệm—tách là bắt đầu tiết kiệm',
      id: 'Minggu ini: daftar semua tagihan rutin, batalkan yang tidak perlu\nPasang app keuangan, catat 2 minggu—lihat angka saja sudah kurangi\nHari gaji: pisahkan hidup dan tabungan—pemisahan awal hemat',
    }),
    monthlyWasteRange: T({
      ko: '15~30만 원 이상',
      en: 'About ₩150k–300k+/mo',
      ja: '月15〜30万ウォン以上',
      zhCN: '每月约15–30万韩元以上',
      zhTW: '每月約15–30萬韓元以上',
      vi: 'Khoảng 150k–300k+ KRW/tháng',
      id: 'Sekitar 150–300rb+ KRW/bulan',
    }),
    yearlySaveRange: T({
      ko: '180~360만 원 이상',
      en: 'About ₩1.8M–3.6M+/yr',
      ja: '年180〜360万ウォン以上',
      zhCN: '每年约180–360万韩元以上可省',
      zhTW: '每年約180–360萬韓元以上可省',
      vi: 'Khoảng 1,8–3,6 triệu+ KRW/năm',
      id: 'Sekitar 1,8–3,6 juta+ KRW/tahun',
    }),
    todayTask: T({
      ko: '은행 앱 → 이번 달 지출 내역 전체 조회 → 가장 후회되는 항목 3개 찾기',
      en: 'Bank app → this month’s transactions → pick the 3 purchases you regret most',
      ja: '銀行アプリ→今月の支出一覧→後悔トップ3を探す',
      zhCN: '银行 App → 本月全部支出 → 找出最后悔的 3 笔',
      zhTW: '銀行 App → 本月全部支出 → 找出最後悔的 3 筆',
      vi: 'App ngân hàng → chi tháng này → chọn 3 giao dịch hối nhất',
      id: 'App bank → transaksi bulan ini → 3 pembelian paling menyesal',
    }),
    shareLine: T({
      ko: '내 멍청비용 유형은 머니 블랙홀 🌀 연간 360만 원 절약 가능하다고?? 지금 당장 가계부 앱 깔았다 ㅋㅋ',
      en: 'My dumb-spending type: money black hole 🌀 Save up to ~₩3.6M a year?! Installing a budget app NOW lol',
      ja: '私のムダ遣いタイプはマネーブラックホール 🌀年360万ウォン節約って？今すぐ家計簿アプリｗ',
      zhCN: '我的冤枉钱类型是钱洞 🌀一年能省 360 万韩元？？马上装记账 App 哈哈',
      zhTW: '我的冤枉錢類型是錢洞 🌀一年能省 360 萬韓元？？馬上裝記帳 App 哈哈',
      vi: 'Kiểu tiền ngu: hố đen 🌀 Tiết kiệm tới 3,6 triệu/năm?! Cài app ngân sách ngay haha',
      id: 'Tipe boros: lubang hitam 🌀 Hemat sampai 3,6 juta/tahun?! Langsung pasang app keuangan haha',
    }),
    shareTypeName: T({
      ko: '머니 블랙홀 🌀',
      en: 'Money black hole 🌀',
      ja: 'マネーブラックホール 🌀',
      zhCN: '钱洞 🌀',
      zhTW: '錢洞 🌀',
      vi: 'Hố đen tiền 🌀',
      id: 'Lubang hitam uang 🌀',
    }),
  },
];
