/** 나의 '플러팅' 스타일 — 12문항 4지선다, A=0 B=1 C=2 D=3, 총점 0~36 → Type1~6 */

type Locale = 'ko' | 'en' | 'ja' | 'zh-CN' | 'zh-TW' | 'vi' | 'id';
type ML = Record<Locale, string>;
function L(m: ML): Record<string, string> {
  return m;
}

export interface Phase3FlirtingStyleQuestion {
  id: number;
  question: Record<string, string>;
  options: { text: Record<string, string>; score: number }[];
}

export interface Phase3FlirtingStyleResult {
  type: string;
  emoji: string;
  title: Record<string, string>;
  shortDescription: Record<string, string>;
  description: Record<string, string>;
  flirtingSkill: Record<string, string>;
  flirtingKeywords: Record<string, string>;
  strength: Record<string, string>;
  weakness: Record<string, string>;
  goodMatch: Record<string, string>;
  friendTestimony: Record<string, string>;
  shareSnippet: Record<string, string>;
}

export function calculatePhase3FlirtingStyleResult(answers: number[]): string {
  const total = answers.reduce((sum, s) => sum + (s ?? 0), 0);
  if (total <= 5) return 'Type1';
  if (total <= 11) return 'Type2';
  if (total <= 19) return 'Type3';
  if (total <= 27) return 'Type4';
  if (total <= 33) return 'Type5';
  return 'Type6';
}

export function getPhase3FlirtingStyleResultByType(
  type: string
): Phase3FlirtingStyleResult | undefined {
  return phase3FlirtingStyleResults.find((r) => r.type === type);
}

export const phase3FlirtingStyleQuestions: Phase3FlirtingStyleQuestion[] = [
  {
    id: 1,
    question: L({
      ko: '상황: 관심 있는 사람과 처음 눈이 마주쳤다. 나는?',
      en: 'Situation: You make eye contact with someone you like for the first time. What do you do?',
      ja: '状況：気になる人と初めて目が合った。私は？',
      'zh-CN': '情境：和心仪的人第一次对视。你会？',
      'zh-TW': '情境：和心儀的人第一次對視。你會？',
      vi: 'Tình huống: Lần đầu chạm mắt với người bạn thích. Bạn sẽ?',
      id: 'Situasi: Pertama kali tatap mata dengan orang yang kamu suka. Kamu?',
    }),
    options: [
      {
        text: L({
          ko: '눈이 마주치는 순간 나도 모르게 웃어버렸다. 의도한 게 아니었다',
          en: 'I smiled without realizing it the moment our eyes met. I didn\'t mean to',
          ja: '目が合った瞬間、知らず知らず笑ってしまった。意図したわけではない',
          'zh-CN': '对视的瞬间不自觉地笑了。并不是故意的',
          'zh-TW': '對視的瞬間不自覺地笑了。並不是故意的',
          vi: 'Khoảnh khắc chạm mắt, tôi cười mà không hay biết. Không cố ý',
          id: 'Saat mata bertemu, aku tersenyum tanpa sadar. Bukan sengaja',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '재밌는 말을 바로 던졌다. "저 눈 마주치면 지는 거 아니에요?"',
          en: 'I threw out a funny line right away. "Doesn\'t the person who breaks eye contact lose?"',
          ja: 'すぐ面白い一言を投げた。「目が合ったら負けじゃないですか？」',
          'zh-CN': '立刻抛了一句有趣的话。"对视的人算输吧？"',
          'zh-TW': '立刻拋了一句有趣的話。「對視的人算輸吧？」',
          vi: 'Ngay lập tức nói một câu vui. "Nhìn nhau mà rời mắt trước là thua đúng không?"',
          id: 'Langsung lempar kalimat lucu. "Kalau tatap mata, yang lepas duluan kalah kan?"',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '2초 더 바라보다가 살짝 시선을 피했다. 다시 돌아봤을 때 상대방이 먼저 웃었다',
          en: 'I looked for two more seconds, then glanced away. When I looked back, they smiled first',
          ja: '2秒もう見てから、少し視線を外した。振り返ったら相手が先に笑っていた',
          'zh-CN': '多看了两秒，然后微微移开视线。再回头时对方先笑了',
          'zh-TW': '多看了兩秒，然後微微移開視線。再回頭時對方先笑了',
          vi: 'Nhìn thêm 2 giây rồi hơi lánh mắt. Quay lại thì đối phương cười trước',
          id: 'Menatap 2 detik lagi lalu sedikit mengalihkan pandangan. Saat menoleh lagi, dia tersenyum duluan',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '일부러 무표정으로 돌아봤다. 상대방이 먼저 웃게 만들었다',
          en: 'I deliberately looked back with a blank face. I made them smile first',
          ja: 'わざと無表情で見返した。相手を先に笑わせた',
          'zh-CN': '故意面无表情地看回去。让对方先笑了',
          'zh-TW': '故意面無表情地看回去。讓對方先笑了',
          vi: 'Cố tình nhìn lại với mặt không cảm xúc. Làm đối phương cười trước',
          id: 'Sengaja menatap balik dengan wajah datar. Membuat dia tersenyum duluan',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 2,
    question: L({
      ko: '상황: 같이 밥을 먹게 됐다. 메뉴를 고르는 상황이다. 나는?',
      en: 'Situation: You\'re having a meal together and choosing the menu. What do you do?',
      ja: '状況：一緒に食事することになった。メニューを選ぶ場面。私は？',
      'zh-CN': '情境：一起吃饭，正在选菜单。你会？',
      'zh-TW': '情境：一起吃飯，正在選菜單。你會？',
      vi: 'Tình huống: Cùng ăn và đang chọn món. Bạn sẽ?',
      id: 'Situasi: Makan bersama dan sedang memilih menu. Kamu?',
    }),
    options: [
      {
        text: L({
          ko: '"뭐든 좋아요"라고 했는데 상대방이 내가 좋아할 것 같은 걸 골라줬다',
          en: 'I said "Anything is fine," and they picked something they thought I\'d like',
          ja: '「何でもいいです」と言ったら、相手が私が好きそうなものを選んでくれた',
          'zh-CN': '说了"什么都行"，对方却选了我可能会喜欢的',
          'zh-TW': '說了「什麼都行」，對方卻選了我可能會喜歡的',
          vi: 'Nói "Gì cũng được" nhưng đối phương chọn món họ nghĩ tôi sẽ thích',
          id: 'Bilang "Apa saja boleh" tapi dia memilih sesuatu yang menurutnya aku suka',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '"저는 이거요. 혹시 못 드시는 거 있어요? 제가 잘 먹이는 편이거든요"',
          en: '"I\'ll have this. Anything you can\'t eat? I\'m pretty good at taking care of people"',
          ja: '「私はこれ。何か食べられないものありますか？私、よく食べさせる方なんです」',
          'zh-CN': '"我要这个。有什么不能吃的吗？我挺会照顾人的"',
          'zh-TW': '「我要這個。有什麼不能吃的嗎？我挺會照顧人的」',
          vi: '"Tôi lấy món này. Bạn có gì không ăn được không? Tôi hay chăm người khác lắm"',
          id: '"Aku ambil ini. Ada yang tidak bisa kamu makan? Aku cukup jago mengurus orang"',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '상대방이 망설이는 것 같아서 "이거 어때요? 제가 자주 오는 데서 제일 잘 하더라고요" 하며 추천했다',
          en: 'They seemed unsure, so I said, "How about this? It\'s the best at a place I come to often"',
          ja: '相手が迷っているようだったので「これどうですか？私がよく行く店で一番おいしいんです」と勧めた',
          'zh-CN': '看对方犹豫，就说"这个怎么样？我常来的店做得最好"',
          'zh-TW': '看對方猶豫，就說「這個怎麼樣？我常來的店做得最好」',
          vi: 'Thấy họ phân vân nên nói "Món này sao? Quán tôi hay đến làm ngon nhất đấy"',
          id: 'Dia keliatan ragu, jadi aku bilang "Yang ini gimana? Di tempat favoritku ini paling enak"',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '일부러 고민하는 척하다가 "같이 골라봐요"라고 했다. 자연스럽게 가까워졌다',
          en: 'I pretended to think it over, then said, "Let\'s pick together." We naturally got closer',
          ja: 'わざと悩むふりをしてから「一緒に選びましょう」と言った。自然と距離が縮まった',
          'zh-CN': '故意装作纠结，然后说"一起选吧"。自然地拉近了距离',
          'zh-TW': '故意裝作糾結，然後說「一起選吧」。自然地拉近了距離',
          vi: 'Cố tình giả vờ phân vân rồi nói "Cùng chọn nhé." Tự nhiên lại gần hơn',
          id: 'Pura-pura bingung lalu bilang "Yuk pilih bareng." Jarak kami natural makin dekat',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 3,
    question: L({
      ko: '상황: 대화 중 상대방이 재밌는 말을 했다. 나는?',
      en: 'Situation: During a conversation, they say something funny. What do you do?',
      ja: '状況：会話中、相手が面白いことを言った。私は？',
      'zh-CN': '情境：聊天时对方说了有趣的话。你会？',
      'zh-TW': '情境：聊天時對方說了有趣的話。你會？',
      vi: 'Tình huống: Trong lúc nói chuyện, đối phương nói điều gì đó thú vị. Bạn sẽ?',
      id: 'Situasi: Saat ngobrol, dia bilang sesuatu yang lucu. Kamu?',
    }),
    options: [
      {
        text: L({
          ko: '그냥 웃었다. 나도 모르게 눈이 초승달이 됐다고 나중에 들었다',
          en: 'I just laughed. Later I heard my eyes turned into crescent moons without me noticing',
          ja: 'ただ笑った。後で知らないうちに目が三日月になっていたと聞いた',
          'zh-CN': '只是笑了。后来听说自己不知不觉笑成了月牙眼',
          'zh-TW': '只是笑了。後來聽說自己不知不覺笑成了月牙眼',
          vi: 'Chỉ cười thôi. Sau này nghe nói mắt tôi cong như trăng lưỡi liềm mà không hay',
          id: 'Cuma tertawa. Nanti dengar mataku jadi seperti bulan sabit tanpa sadar',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '"와 진짜요? 그거 저도요!" 하며 자연스럽게 공통점으로 연결했다',
          en: '"Really? Me too!" and naturally connected it to something we had in common',
          ja: '「わあ本当？それ私も！」と言って、自然に共通点につなげた',
          'zh-CN': '"哇真的吗？我也是！"并自然连接到共同点',
          'zh-TW': '「哇真的嗎？我也是！」並自然連接到共同點',
          vi: '"Thật à? Tôi cũng vậy!" và tự nhiên nối sang điểm chung',
          id: '"Wah beneran? Aku juga!" lalu natural nyambung ke kesamaan',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '리액션을 잠깐 참았다가 살짝 미소 지었다. 상대방이 더 재밌는 말을 하려고 했다',
          en: 'I held back my reaction for a moment, then smiled slightly. They tried to say something even funnier',
          ja: 'リアクションを少し我慢してから、ほんの少し微笑んだ。相手がもっと面白いことを言おうとした',
          'zh-CN': '稍微忍住反应，然后淡淡一笑。对方想讲更有趣的话',
          'zh-TW': '稍微忍住反應，然後淡淡一笑。對方想講更有趣的話',
          vi: 'Giữ phản ứng một chút rồi mỉm cười nhẹ. Đối phương cố nói thêm điều vui hơn',
          id: 'Tahan reaksi sebentar lalu tersenyum tipis. Dia berusaha bilang sesuatu yang lebih lucu',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '"그거 되게 웃기네요. 그런 면이 있을 줄 몰랐어요"라며 관심을 표현했다',
          en: '"That\'s really funny. I didn\'t know you had that side" — I showed my interest',
          ja: '「それすごく面白い。そんな一面があるなんて知らなかった」と関心を示した',
          'zh-CN': '"好好笑，没想到你还有这一面"——表达了兴趣',
          'zh-TW': '「好好笑，沒想到你還有這一面」——表達了興趣',
          vi: '"Hay thật đấy. Không ngờ bạn có mặt như vậy" — thể hiện sự quan tâm',
          id: '"Itu lucu banget. Nggak nyangka kamu punya sisi kayak gitu" — menunjukkan ketertarikan',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 4,
    question: L({
      ko: '상황: 상대방이 힘들다고 했다. 나는?',
      en: 'Situation: They say they\'re going through a hard time. What do you do?',
      ja: '状況：相手がつらいと言った。私は？',
      'zh-CN': '情境：对方说最近很辛苦。你会？',
      'zh-TW': '情境：對方說最近很辛苦。你會？',
      vi: 'Tình huống: Đối phương nói đang khó khăn. Bạn sẽ?',
      id: 'Situasi: Dia bilang sedang susah. Kamu?',
    }),
    options: [
      {
        text: L({
          ko: '"어떻게 된 거예요?" 하며 자연스럽게 들어주기 시작했다. 나중에 상대방이 "처음 이야기한 사람"이라고 했다',
          en: '"What happened?" I naturally started listening. Later they said I was "the first person they told"',
          ja: '「どうしたんですか？」と自然に話を聞き始めた。後で相手は「初めて話した人」と言った',
          'zh-CN': '问"发生什么事了？"自然地开始倾听。后来对方说我是"第一个倾诉的人"',
          'zh-TW': '問「發生什麼事了？」自然地開始傾聽。後來對方說我是「第一個傾訴的人」',
          vi: '"Chuyện gì vậy?" và tự nhiên lắng nghe. Sau này họ nói tôi là "người đầu tiên họ kể"',
          id: '"Kenapa?" lalu natural mulai mendengarkan. Nanti dia bilang aku "orang pertama yang dia ceritakan"',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '힘든 거 들어주다가 "저한테 말해줘서 다행이에요"라고 했다',
          en: 'After listening to their troubles, I said, "I\'m glad you told me"',
          ja: 'つらいことを聞いたあと「私に話してくれてよかった」と言った',
          'zh-CN': '听完对方的烦恼后说"幸好你告诉了我"',
          'zh-TW': '聽完對方的煩惱後說「幸好你告訴了我」',
          vi: 'Nghe họ tâm sự rồi nói "May quá bạn kể cho tôi nghe"',
          id: 'Setelah dengar ceritanya, aku bilang "Syukurlah kamu cerita ke aku"',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '다 듣고 나서 "그거 많이 힘들었겠다" 딱 한 마디만 했다. 상대방이 더 울었다',
          en: 'After hearing everything, I said only one line: "That must have been really hard." They cried even more',
          ja: '全部聞いたあと「それ、かなり大変だったね」と一言だけ言った。相手はもっと泣いた',
          'zh-CN': '听完后只说一句"那一定很辛苦吧"。对方哭得更厉害了',
          'zh-TW': '聽完後只說一句「那一定很辛苦吧」。對方哭得更厲害了',
          vi: 'Nghe hết rồi chỉ nói một câu: "Chắc rất khó nhỉ." Họ khóc nhiều hơn',
          id: 'Setelah dengar semua, cuma bilang satu kalimat: "Pasti berat ya." Dia malah makin menangis',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '들어주다가 "이따 같이 밥 먹을래요? 기운 내야 하잖아요"라고 자연스럽게 다음 약속을 잡았다',
          en: 'While listening, I smoothly set up the next plan: "Want to grab a meal later? You need to cheer up"',
          ja: '話を聞きながら「後で一緒にご飯食べない？元気出さないと」と自然に次の約束を取った',
          'zh-CN': '边听边说"待会一起吃饭吧？得打起精神啊"，自然地约好了下次',
          'zh-TW': '邊聽邊說「待會一起吃飯吧？得打起精神啊」，自然地約好了下次',
          vi: 'Vừa lắng nghe vừa nói "Sau này ăn cùng nhé? Phải lấy lại tinh thần chứ" và hẹn luôn',
          id: 'Sambil mendengarkan, bilang "Nanti makan bareng yuk? Harus semangat dong" dan natural janjian lagi',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 5,
    question: L({
      ko: '상황: 연락하고 싶은데 핑계가 필요하다. 나는?',
      en: 'Situation: You want to reach out but feel you need an excuse. What do you do?',
      ja: '状況：連絡したいけど口実が欲しい。私は？',
      'zh-CN': '情境：想联系对方，却觉得需要一个理由。你会？',
      'zh-TW': '情境：想聯絡對方，卻覺得需要一個理由。你會？',
      vi: 'Tình huống: Muốn nhắn tin nhưng cần cớ. Bạn sẽ?',
      id: 'Situasi: Ingin hubungi tapi butuh alasan. Kamu?',
    }),
    options: [
      {
        text: L({
          ko: '핑계 없이 그냥 연락한다. "생각나서요"라고 한다. 이게 가장 잘 먹힌다는 걸 알고 있다',
          en: 'I reach out with no excuse. I just say, "You crossed my mind." I know this works best',
          ja: '口実なしで連絡する。「思い出して」と言う。これが一番効くと知っている',
          'zh-CN': '不找借口直接联系。说"突然想到你了"。我知道这招最有效',
          'zh-TW': '不找藉口直接聯絡。說「突然想到你了」。我知道這招最有效',
          vi: 'Nhắn luôn không cần cớ. Nói "Nghĩ đến bạn thôi." Biết cách này hiệu quả nhất',
          id: 'Hubungi tanpa alasan. Bilang "Keinget kamu." Aku tahu ini paling manjur',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '재밌는 밈이나 영상을 보내며 "이거 봤어요? 생각났어요"',
          en: 'I send a funny meme or video with "Did you see this? It made me think of you"',
          ja: '面白いミームや動画を送って「これ見た？思い出した」',
          'zh-CN': '发有趣的梗或视频，说"看到这个了吗？想到你了"',
          'zh-TW': '發有趣的梗或影片，說「看到這個了嗎？想到你了」',
          vi: 'Gửi meme hoặc video vui kèm "Bạn thấy cái này chưa? Nghĩ đến bạn"',
          id: 'Kirim meme atau video lucu sambil bilang "Liat ini? Jadi keinget kamu"',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '상대방이 예전에 말했던 것과 연결된 무언가를 발견하고 "이거 전에 말했던 거 아니에요?" 하며 연락한다',
          en: 'I find something linked to what they said before and text, "Didn\'t you mention this before?"',
          ja: '相手が以前言っていたことにつながるものを見つけて「これ前に言ってたやつじゃない？」と連絡する',
          'zh-CN': '发现和对方以前说过的事有关的东西，联系说"这不是你之前说过的吗？"',
          'zh-TW': '發現和對方以前說過的事有關的東西，聯絡說「這不是你之前說過的嗎？」',
          vi: 'Thấy thứ gì liên quan điều họ từng nói và nhắn "Không phải bạn từng nói cái này sao?"',
          id: 'Nemu sesuatu yang nyambung dengan yang dia pernah bilang, lalu chat "Bukannya kamu pernah bilang ini?"',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '바로 연락하지 않고 하루 정도 기다렸다가 연락한다. 기다리게 만든 다음 먼저 연락하면 효과가 다르다',
          en: 'I don\'t reach out right away — I wait about a day. Making them wait first changes the effect',
          ja: 'すぐ連絡せず、1日くらい待ってから連絡する。待たせてから先に連絡すると効果が違う',
          'zh-CN': '不马上联系，等一天左右再发。让对方等一等再主动联系，效果不一样',
          'zh-TW': '不馬上聯絡，等一天左右再發。讓對方等一等再主動聯絡，效果不一樣',
          vi: 'Không nhắn ngay mà đợi khoảng một ngày. Để họ chờ rồi mình chủ động thì hiệu quả khác',
          id: 'Nggak langsung chat, tunggu sekitar sehari. Kalau bikin nunggu dulu lalu aku yang hubungi, efeknya beda',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 6,
    question: L({
      ko: '상황: 같이 걷다가 상대방과 어깨가 스쳤다. 나는?',
      en: 'Situation: While walking together, your shoulders brush. What do you do?',
      ja: '状況：一緒に歩いているうちに肩が触れた。私は？',
      'zh-CN': '情境：一起走路时肩膀擦到了。你会？',
      'zh-TW': '情境：一起走路時肩膀擦到了。你會？',
      vi: 'Tình huống: Đi cùng nhau thì vai chạm vai. Bạn sẽ?',
      id: 'Situasi: Jalan bareng lalu bahu saling bersentuhan. Kamu?',
    }),
    options: [
      {
        text: L({
          ko: '그냥 아무렇지 않게 걸었는데 상대방이 의식했다',
          en: 'I kept walking like nothing happened, but they noticed',
          ja: '何でもないように歩いたが、相手は意識していた',
          'zh-CN': '像没事一样继续走，但对方注意到了',
          'zh-TW': '像沒事一樣繼續走，但對方注意到了',
          vi: 'Cứ đi bình thường như không có gì, nhưng đối phương để ý',
          id: 'Jalan biasa saja seolah nggak ada apa-apa, tapi dia sadar',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '"어 닿았다" 하며 웃어버렸다. 분위기가 가벼워졌다',
          en: 'I laughed and said, "Oh, we touched." The mood got lighter',
          ja: '「あ、触れた」と笑ってしまった。空気が軽くなった',
          'zh-CN': '笑着说"啊，碰到了"。气氛变轻松了',
          'zh-TW': '笑著說「啊，碰到了」。氣氛變輕鬆了',
          vi: 'Cười và nói "Ôi, chạm rồi." Không khí nhẹ hơn',
          id: 'Tertawa sambil bilang "Eh, kena." Suasananya jadi ringan',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '살짝 더 가까이 걸었다. 상대방이 피하지 않으면 그게 신호라는 걸 안다',
          en: 'I walked a little closer. I know that if they don\'t pull away, that\'s a sign',
          ja: '少し近づいて歩いた。相手が避けなければそれが合図だと知っている',
          'zh-CN': '稍微走得更近一点。知道对方不躲开就是信号',
          'zh-TW': '稍微走得更近一點。知道對方不躲開就是信號',
          vi: 'Đi sát hơn một chút. Biết nếu họ không tránh thì đó là tín hiệu',
          id: 'Jalan sedikit lebih dekat. Aku tahu kalau dia nggak minggir, itu sinyal',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '아무 말 안 하고 천천히 걷는 속도를 맞췄다. 상대방도 맞추기 시작했다',
          en: 'I said nothing and slowly matched their walking pace. They started matching mine too',
          ja: '何も言わず、ゆっくり歩く速度を合わせた。相手も合わせ始めた',
          'zh-CN': '什么都不说，慢慢对齐走路速度。对方也开始配合',
          'zh-TW': '什麼都不說，慢慢對齊走路速度。對方也開始配合',
          vi: 'Không nói gì, từ từ chỉnh tốc độ đi cho khớp. Đối phương cũng bắt đầu theo',
          id: 'Tanpa bilang apa-apa, pelan-pelan samain kecepatan jalan. Dia juga mulai menyesuaikan',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 7,
    question: L({
      ko: '상황: 상대방이 "요즘 바빠?"라고 먼저 물어왔다. 나는?',
      en: 'Situation: They ask first, "Have you been busy lately?" What do you do?',
      ja: '状況：相手から先に「最近忙しい？」と聞かれた。私は？',
      'zh-CN': '情境：对方先问"最近忙吗？"你会？',
      'zh-TW': '情境：對方先問「最近忙嗎？」你會？',
      vi: 'Tình huống: Đối phương hỏi trước "Dạo này bận không?" Bạn sẽ?',
      id: 'Situasi: Dia tanya duluan "Lagi sibuk?" Kamu?',
    }),
    options: [
      {
        text: L({
          ko: '"응, 근데 너 연락 오면 시간 나"라고 그냥 솔직하게 말해버렸다',
          en: 'I bluntly said, "Yeah, but I make time when you reach out"',
          ja: '「うん、でも君から連絡来たら時間作る」と正直に言ってしまった',
          'zh-CN': '直接老实说"嗯，但你联系我就有时间"',
          'zh-TW': '直接老實說「嗯，但你聯絡我就有時間」',
          vi: 'Thẳng thắn nói "Ừ, nhưng bạn nhắn thì tôi có thời gian"',
          id: 'Jujur bilang "Iya, tapi kalau kamu chat aku sempetin"',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '"왜요? 보고 싶었어요?"라고 되물었다. 분위기가 확 달라졌다',
          en: 'I asked back, "Why? Did you miss me?" The mood shifted instantly',
          ja: '「どうして？会いたかった？」と聞き返した。空気が一気に変わった',
          'zh-CN': '反问"怎么了？想我了？"气氛立刻变了',
          'zh-TW': '反問「怎麼了？想我了？」氣氛立刻變了',
          vi: 'Hỏi lại "Sao vậy? Nhớ tôi à?" Không khí đổi ngay',
          id: 'Balas tanya "Kenapa? Kangen ya?" Suasana langsung berubah',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '"바빠요. 근데 왜요?"라고 답하며 상대방이 먼저 말하게 만들었다',
          en: 'I answered, "Busy. Why?" and made them say the rest first',
          ja: '「忙しい。でもどうして？」と答えて、相手に先に話させた',
          'zh-CN': '回答"挺忙的。不过怎么了？"让对方先开口',
          'zh-TW': '回答「挺忙的。不過怎麼了？」讓對方先開口',
          vi: 'Trả lời "Bận. Sao vậy?" và để họ nói trước',
          id: 'Jawab "Sibuk. Tapi kenapa?" dan bikin dia yang ngomong duluan',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '"바쁜데 물어봐줘서 기분은 좋네요"라고 했다. 상대방이 당황했다가 웃었다',
          en: 'I said, "I\'m busy, but it feels nice that you asked." They looked flustered, then laughed',
          ja: '「忙しいけど、聞いてくれて嬉しい」と言った。相手は戸惑ってから笑った',
          'zh-CN': '说"虽然忙，但你来问我还是挺开心的"。对方先愣住然后笑了',
          'zh-TW': '說「雖然忙，但你來問我還是挺開心的」。對方先愣住然後笑了',
          vi: 'Nói "Bận nhưng hỏi thăm thì vui đấy." Họ bối rối rồi cười',
          id: 'Bilang "Sibuk sih, tapi senang kamu nanya." Dia kaget lalu tertawa',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 8,
    question: L({
      ko: '상황: 상대방이 칭찬을 해줬다. "오늘 되게 좋아 보여요"라고 했다. 나는?',
      en: 'Situation: They compliment you: "You look really good today." What do you do?',
      ja: '状況：相手が褒めてくれた。「今日すごく素敵に見える」と言われた。私は？',
      'zh-CN': '情境：对方夸你"今天看起来很好"。你会？',
      'zh-TW': '情境：對方誇你「今天看起來很好」。你會？',
      vi: 'Tình huống: Đối phương khen "Hôm nay bạn trông rất đẹp." Bạn sẽ?',
      id: 'Situasi: Dia puji "Hari ini kamu kelihatan bagus banget." Kamu?',
    }),
    options: [
      {
        text: L({
          ko: '"그래요? 고마워요" 하며 환하게 웃었다. 그 웃음이 더 칭찬받았다',
          en: '"Really? Thank you" — I smiled brightly. That smile got me another compliment',
          ja: '「そう？ありがとう」と明るく笑った。その笑顔でもう一度褒められた',
          'zh-CN': '说"是吗？谢谢"并灿烂一笑。那个笑容又换来一句夸奖',
          'zh-TW': '說「是嗎？謝謝」並燦爛一笑。那個笑容又換來一句誇獎',
          vi: '"Thật à? Cảm ơn" — cười rạng rỡ. Nụ cười đó lại được khen thêm',
          id: '"Beneran? Makasih" — tersenyum cerah. Senyum itu malah dapat pujian lagi',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '"진짜요? 저 오늘 뭔가 설레는 일이 있어서요"라고 했다. 상대방이 \'그게 뭔지\' 궁금해했다',
          en: '"Really? Something exciting happened today" — they got curious about what it was',
          ja: '「本当？今日なんだかドキドキする出来事があって」と言った。相手は「それ何？」と気になった',
          'zh-CN': '说"真的吗？今天有点让人心动的事"——对方好奇那是什么',
          'zh-TW': '說「真的嗎？今天有點讓人心動的事」——對方好奇那是什麼',
          vi: '"Thật à? Hôm nay có chuyện khiến tôi hơi rung động" — họ tò mò đó là gì',
          id: '"Beneran? Hari ini ada sesuatu yang bikin deg-degan" — dia jadi penasaran apa itu',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '"그건 지금 봐주는 사람이 좋아서 그런 거 아닐까요"라고 받아쳤다',
          en: 'I shot back, "Maybe I look good because of who\'s looking at me"',
          ja: '「今見てくれている人がいいからじゃないですか」と返した',
          'zh-CN': '接话说"也许是因为现在看着我的人太好了"',
          'zh-TW': '接話說「也許是因為現在看著我的人太好了」',
          vi: 'Đáp lại "Có lẽ vì người đang nhìn tôi quá tuyệt"',
          id: 'Balas "Mungkin karena yang lihat aku sekarang orangnya bagus"',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '"고마워요" 딱 두 글자만 하고 살짝 웃었다. 더 말하지 않았다',
          en: 'I said only two words — "Thank you" — smiled slightly, and said nothing more',
          ja: '「ありがとう」の二文字だけ言って、少し微笑んだ。それ以上は言わなかった',
          'zh-CN': '只说"谢谢"两个字，淡淡一笑。没有再多说',
          'zh-TW': '只說「謝謝」兩個字，淡淡一笑。沒有再多說',
          vi: 'Chỉ nói hai chữ "Cảm ơn", mỉm cười nhẹ. Không nói thêm',
          id: 'Cuma bilang dua kata "Makasih", tersenyum tipis. Nggak bilang apa-apa lagi',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 9,
    question: L({
      ko: '상황: 분위기가 어느 정도 무르익었다. 상대방이 내 눈치를 보는 게 느껴진다. 나는?',
      en: 'Situation: The mood has ripened a bit. You can feel them watching your reaction. What do you do?',
      ja: '状況：空気がだいぶ熟してきた。相手が私の様子をうかがっているのが感じられる。私は？',
      'zh-CN': '情境：气氛已经有点到位了。感觉对方在观察你的反应。你会？',
      'zh-TW': '情境：氣氛已經有點到位了。感覺對方在觀察你的反應。你會？',
      vi: 'Tình huống: Không khí đã khá chín. Cảm giác đối phương đang nhìn phản ứng của bạn. Bạn sẽ?',
      id: 'Situasi: Suasananya sudah cukup matang. Terasa dia memperhatikan reaksiku. Kamu?',
    }),
    options: [
      {
        text: L({
          ko: '나도 모르는 사이에 이미 분위기가 만들어져 있었다. 상대방이 먼저 말을 꺼냈다',
          en: 'Without realizing it, the mood was already there. They spoke first',
          ja: '気づかないうちに、すでに空気ができていた。相手が先に口を開いた',
          'zh-CN': '不知不觉间气氛已经形成了。对方先开了口',
          'zh-TW': '不知不覺間氣氛已經形成了。對方先開了口',
          vi: 'Không hay, không khí đã hình thành sẵn. Đối phương nói trước',
          id: 'Tanpa sadar, suasananya sudah kebentuk. Dia yang buka obrolan duluan',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '"분위기 이상한 거 저만 느끼는 건 아니죠?"라고 먼저 말해버렸다',
          en: 'I blurted out first, "It\'s not just me feeling this vibe, right?"',
          ja: '「この空気、私だけじゃないですよね？」と先に言ってしまった',
          'zh-CN': '先开口说"不是只有我觉得气氛有点怪吧？"',
          'zh-TW': '先開口說「不是只有我覺得氣氛有點怪吧？」',
          vi: 'Chủ động nói "Không phải chỉ mình tôi thấy không khí hơi lạ đâu nhỉ?"',
          id: 'Bilang duluan "Bukan cuma aku kan yang ngerasa suasananya aneh?"',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '말하지 않고 그 분위기를 유지했다. 상대방이 못 참고 먼저 말했다',
          en: 'I said nothing and kept the mood going. They couldn\'t hold back and spoke first',
          ja: '何も言わず、その空気を保った。相手が我慢できず先に話した',
          'zh-CN': '什么都不说，继续维持那种气氛。对方忍不住先开口了',
          'zh-TW': '什麼都不說，繼續維持那種氣氛。對方忍不住先開口了',
          vi: 'Không nói gì, giữ nguyên không khí đó. Đối phương không chịu nổi và nói trước',
          id: 'Nggak bilang apa-apa, pertahankan suasananya. Dia nggak tahan dan ngomong duluan',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '"오늘 되게 좋다"라고 짧게 말하고 눈을 마주쳤다. 그걸로 충분했다',
          en: 'I said briefly, "Today feels really nice," and met their eyes. That was enough',
          ja: '「今日、すごくいい」と短く言って目を合わせた。それで十分だった',
          'zh-CN': '简短地说"今天真好"，然后对视。这就够了',
          'zh-TW': '簡短地說「今天真好」，然後對視。這就夠了',
          vi: 'Nói ngắn gọn "Hôm nay thật tuyệt" rồi nhìn thẳng mắt. Vậy là đủ',
          id: 'Bilang singkat "Hari ini enak banget" lalu tatap mata. Itu sudah cukup',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 10,
    question: L({
      ko: '상황: 상대방에게 연락이 뜸해지고 있다. 나는?',
      en: 'Situation: They\'ve been replying less often. What do you do?',
      ja: '状況：相手からの連絡が少なくなってきた。私は？',
      'zh-CN': '情境：对方的联系变少了。你会？',
      'zh-TW': '情境：對方的聯絡變少了。你會？',
      vi: 'Tình huống: Đối phương liên lạc ít hơn. Bạn sẽ?',
      id: 'Situasi: Dia mulai jarang hubungi. Kamu?',
    }),
    options: [
      {
        text: L({
          ko: '모르고 있었다. 나중에 상대방이 "연락이 줄었을 때 더 생각났다"고 했다',
          en: 'I didn\'t even notice. Later they said, "I thought about you more when you reached out less"',
          ja: '気づいていなかった。後で相手は「連絡が減ったときの方が余計に思い出した」と言った',
          'zh-CN': '自己都没察觉。后来对方说"你联系少的时候反而更想你了"',
          'zh-TW': '自己都沒察覺。後來對方說「你聯絡少的時候反而更想你了」',
          vi: 'Không hề để ý. Sau này họ nói "Lúc bạn ít liên lạc, tôi lại nghĩ đến bạn nhiều hơn"',
          id: 'Nggak sadar sama sekali. Nanti dia bilang "Pas kamu jarang chat, aku malah makin kepikiran"',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '"요즘 왜 이렇게 조용해요? 섭섭하게"라고 가볍게 먼저 티를 냈다',
          en: 'I lightly showed it first: "Why so quiet lately? I miss hearing from you"',
          ja: '「最近どうしてこんなに静か？寂しいんだけど」と軽く先に出した',
          'zh-CN': '轻松先表态"最近怎么这么安静？有点失落"',
          'zh-TW': '輕鬆先表態「最近怎麼這麼安靜？有點失落」',
          vi: 'Nhẹ nhàng nói trước "Sao dạo này im lặng vậy? Hơi buồn đấy"',
          id: 'Santai bilang duluan "Kok akhir-akhir ini diem? Agak sedih nih"',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '더 뜸하게 연락했다. 상대방이 먼저 연락이 왔다',
          en: 'I reached out even less often. They contacted me first',
          ja: 'もっと連絡を控えた。相手から先に連絡が来た',
          'zh-CN': '联系得更少了。结果对方先找我了',
          'zh-TW': '聯絡得更少了。結果對方先找我了',
          vi: 'Liên lạc càng ít hơn. Rồi đối phương chủ động nhắn trước',
          id: 'Malah makin jarang chat. Akhirnya dia yang hubungi duluan',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '"바빠요?" 딱 두 글자 보냈다. 상대방이 해명하듯 길게 답장했다',
          en: 'I sent just two words: "Busy?" They replied at length like they were explaining themselves',
          ja: '「忙しい？」の二文字だけ送った。相手は弁解するように長文で返してきた',
          'zh-CN': '只发了两个字"忙吗？"对方像解释一样回了很长一段',
          'zh-TW': '只發了兩個字「忙嗎？」對方像解釋一樣回了很長一段',
          vi: 'Chỉ gửi hai chữ "Bận à?" Họ trả lời dài như đang giải thích',
          id: 'Kirim cuma dua kata "Sibuk?" Dia balas panjang seolah lagi jelasin',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 11,
    question: L({
      ko: '상황: 처음 만난 자리가 끝나간다. 다음을 기약하고 싶다. 나는?',
      en: 'Situation: Your first meet-up is ending. You want to hint at seeing them again. What do you do?',
      ja: '状況：初めて会った場が終わりに向かう。次を約束したい。私は？',
      'zh-CN': '情境：第一次见面快要结束了。你想约定下次。你会？',
      'zh-TW': '情境：第一次見面快要結束了。你想約定下次。你會？',
      vi: 'Tình huống: Buổi gặp đầu tiên sắp kết thúc. Bạn muốn hẹn lần sau. Bạn sẽ?',
      id: 'Situasi: Pertemuan pertama hampir selesai. Kamu ingin janji ketemu lagi. Kamu?',
    }),
    options: [
      {
        text: L({
          ko: '"오늘 재밌었어요" 하며 인사했는데 상대방이 "또 봐요"라고 먼저 말했다',
          en: 'I said goodbye with "Today was fun," and they said "Let\'s meet again" first',
          ja: '「今日楽しかったです」と挨拶したら、相手が先に「また会いましょう」と言った',
          'zh-CN': '告别时说"今天很开心"，结果对方先说"下次见"',
          'zh-TW': '告別時說「今天很開心」，結果對方先說「下次見」',
          vi: 'Chào tạm biệt với "Hôm nay vui lắm" rồi đối phương nói trước "Hẹn gặp lại"',
          id: 'Pamit bilang "Hari ini seru" lalu dia yang bilang duluan "Ketemu lagi ya"',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '"다음엔 제가 좋은 데 데려갈게요. 기대하세요"라고 했다',
          en: 'I said, "Next time I\'ll take you somewhere nice. Look forward to it"',
          ja: '「次はいいところ連れて行くね。楽しみにして」と言った',
          'zh-CN': '说"下次我带你去个好地方，期待吧"',
          'zh-TW': '說「下次我帶你去個好地方，期待吧」',
          vi: 'Nói "Lần sau tôi dẫn bạn đi chỗ hay nhé. Mong chờ đi"',
          id: 'Bilang "Next time aku ajak ke tempat bagus. Tunggu ya"',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '"혹시 다음 주 시간 어때요?"라고 바로 다음 약속을 잡았다',
          en: 'I immediately set the next plan: "How\'s your schedule next week?"',
          ja: '「来週、時間どう？」とすぐ次の約束を取った',
          'zh-CN': '直接约下次"下周有时间吗？"',
          'zh-TW': '直接約下次「下週有時間嗎？」',
          vi: 'Hẹn luôn "Tuần sau bạn rảnh không?"',
          id: 'Langsung janjian "Minggu depan waktumu gimana?"',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '아무 말 없이 "연락해요"라고만 했다. 상대방이 먼저 연락이 왔다',
          en: 'Without saying much, I only said, "Let\'s keep in touch." They reached out first',
          ja: '特に何も言わず「連絡してね」とだけ言った。相手から先に連絡が来た',
          'zh-CN': '什么都没多说，只说了句"联系我吧"。对方先找我了',
          'zh-TW': '什麼都沒多說，只說了句「聯絡我吧」。對方先找我了',
          vi: 'Không nói thêm gì, chỉ nói "Liên lạc nhé." Đối phương nhắn trước',
          id: 'Tanpa banyak omong, cuma bilang "Hubungi aku ya." Dia yang chat duluan',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 12,
    question: L({
      ko: '상황: 친구가 "너 플러팅 스타일이 뭐야?"라고 물어봤다. 나는?',
      en: 'Situation: A friend asks, "What\'s your flirting style?" What do you say?',
      ja: '状況：友達に「あなたのフリートスタイルは？」と聞かれた。私は？',
      'zh-CN': '情境：朋友问"你的撩人风格是什么？"你会？',
      'zh-TW': '情境：朋友問「你的撩人風格是什麼？」你會？',
      vi: 'Tình huống: Bạn hỏi "Phong cách tán tỉnh của bạn là gì?" Bạn sẽ?',
      id: 'Situasi: Teman tanya "Gaya flirting kamu apa?" Kamu?',
    }),
    options: [
      {
        text: L({
          ko: '"나 플러팅 해? 모르고 있었는데"라고 진심으로 답했다',
          en: 'I honestly answered, "I flirt? I didn\'t even know I was doing that"',
          ja: '「私、フリートしてる？知らなかった」と本気で答えた',
          'zh-CN': '真心回答"我在撩人吗？我自己都不知道"',
          'zh-TW': '真心回答「我在撩人嗎？我自己都不知道」',
          vi: 'Thật lòng trả lời "Tôi tán tỉnh à? Tôi không biết luôn"',
          id: 'Jujur jawab "Aku flirting? Nggak sadar sama sekali"',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '"재밌게 대화하다 보면 자연스럽게 되던데"라고 했다',
          en: 'I said, "It just happens naturally when we have fun conversations"',
          ja: '「楽しく話しているうちに自然にそうなる」と言った',
          'zh-CN': '说"聊得开心的话就会自然变成那样"',
          'zh-TW': '說「聊得開心的話就會自然變成那樣」',
          vi: 'Nói "Cứ nói chuyện vui là tự nhiên thành vậy thôi"',
          id: 'Bilang "Kalau ngobrol seru, natural aja jadi gitu"',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '"관심 있으면 관심받게 만드는 거지. 상대방이 먼저 하게 만드는 편이야"',
          en: '"If I\'m interested, I make them feel interested too. I usually make the other person move first"',
          ja: '「気になる相手には気にさせる。相手に先に動かせる方」',
          'zh-CN': '"有兴趣的话就让对方也感受到，我偏向让对方先行动"',
          'zh-TW': '「有興趣的話就讓對方也感受到，我偏向讓對方先行動」',
          vi: '"Có hứng thú thì làm họ cũng cảm thấy vậy. Tôi hay để đối phương chủ động trước"',
          id: '"Kalau tertarik, aku bikin dia juga ngerasa. Biasanya aku bikin lawan bicara yang duluan"',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '"그게 티 나면 플러팅이 아니지"라고 했다. 친구가 "맞는 말이네"라고 했다',
          en: 'I said, "If you can tell, it\'s not flirting." My friend replied, "True"',
          ja: '「バレたらフリートじゃないでしょ」と言った。友達は「その通り」と言った',
          'zh-CN': '说"被看出来了就不叫撩了"。朋友说"说得对"',
          'zh-TW': '說「被看出來就不叫撩了」。朋友說「說得對」',
          vi: 'Nói "Lộ ra thì không gọi là tán tỉnh nữa." Bạn nói "Đúng thật"',
          id: 'Bilang "Kalau ketauan, bukan flirting dong." Temanku bilang "Bener"',
        }),
        score: 3,
      },
    ],
  },
];

export const phase3FlirtingStyleResults: Phase3FlirtingStyleResult[] = [
  {
    type: 'Type1',
    emoji: '🌸',
    title: L({
      ko: '하는 줄도 모르고 유혹하는, 무의식 천연 플러팅형 🌸',
      en: 'Unconscious Natural Flirt — You Seduce Without Even Trying 🌸',
      ja: '気づかないうちに誘う、無意識天然フリート型 🌸',
      'zh-CN': '不知不觉就撩人，无意识天然撩型 🌸',
      'zh-TW': '不知不覺就撩人，無意識天然撩型 🌸',
      vi: 'Tán tỉnh mà không hay, kiểu tự nhiên vô thức 🌸',
      id: 'Flirting tanpa sadar, tipe alami bawaan 🌸',
    }),
    shortDescription: L({
      ko: '플러팅 필살기: 나도 모르는 자연스러운 반응',
      en: 'Signature move: Reactions so natural even you don\'t notice',
      ja: '必殺技：自分でも気づかない自然な反応',
      'zh-CN': '撩人绝招：连你自己都没意识到的自然反应',
      'zh-TW': '撩人絕招：連你自己都沒意識到的自然反應',
      vi: 'Chiêu đặc trưng: Phản ứng tự nhiên đến mức bạn cũng không hay',
      id: 'Jurus andalan: Reaksi natural yang bahkan kamu nggak sadar',
    }),
    description: L({
      ko: '당신의 가장 강력한 유혹은 전혀 유혹처럼 보이지 않는다는 것입니다. 웃을 때 눈이 초승달이 되거나, 공감할 때 완전히 몰입하거나, 그냥 있는데 분위기가 만들어지는 타입입니다. 본인은 플러팅을 했다고 생각하지 않는데 상대방은 이미 무너지고 있습니다. 가장 무서운 유혹은 의도하지 않은 것입니다.',
      en: 'Your strongest charm is that it never looks like flirting at all. Your eyes turn into crescent moons when you laugh, you fully immerse yourself when you empathize, and somehow the mood just builds around you. You don\'t think you\'re flirting — but the other person is already melting. The scariest kind of charm is the kind you never meant to use.',
      ja: 'あなたの最強の魅力は、まったく誘惑に見えないことです。笑うと目が三日月になり、共感すると完全に没入し、ただそこにいるだけで空気ができあがるタイプ。本人はフリートしたつもりがないのに、相手はすでに心を落としています。最も怖い魅力は、意図していないものです。',
      'zh-CN': '你最强的魅力，是看起来完全不像在撩人。一笑眼睛弯成月牙，共情时会完全投入，只是站在那里气氛就会自然形成。你自己不觉得在撩，对方却已经心动了。最可怕的魅力，往往是无意的。',
      'zh-TW': '你最強的魅力，是看起來完全不像在撩人。一笑眼睛彎成月牙，共情時會完全投入，只是站在那裡氣氛就會自然形成。你自己不覺得在撩，對方卻已經心動了。最可怕的魅力，往往是無意的。',
      vi: 'Sức hút mạnh nhất của bạn là nó không hề giống tán tỉnh. Cười thì mắt cong như trăng lưỡi liềm, đồng cảm thì chìm hẳn vào, chỉ cần ở đó là không khí tự nhiên hình thành. Bạn không nghĩ mình đang flirt, nhưng đối phương đã rung động. Sức hút đáng sợ nhất là thứ bạn không hề cố ý.',
      id: 'Daya tarik terkuatmu adalah kelihatannya sama sekali bukan flirting. Tertawa lalu mata jadi seperti bulan sabit, empati lalu benar-benar masuk, cuma ada di situ suasananya kebentuk sendiri. Kamu nggak merasa sedang flirt, tapi lawan bicara sudah jatuh hati. Daya tarik paling menakutkan adalah yang nggak disengaja.',
    }),
    flirtingSkill: L({
      ko: '무의식적 자연스러움 🌸',
      en: 'Unconscious natural charm 🌸',
      ja: '無意識の自然さ 🌸',
      'zh-CN': '无意识的天然感 🌸',
      'zh-TW': '無意識的天然感 🌸',
      vi: 'Tự nhiên vô thức 🌸',
      id: 'Kec natural tanpa sadar 🌸',
    }),
    flirtingKeywords: L({
      ko: '천연·무장해제·자연스러움·눈웃음·진정성',
      en: 'Natural · Disarming · Effortless · Smiling eyes · Authenticity',
      ja: '天然・無防備・自然さ・目元の笑み・本物感',
      'zh-CN': '天然·卸下防备·自然·笑眼·真诚',
      'zh-TW': '天然·卸下防備·自然·笑眼·真誠',
      vi: 'Tự nhiên · Hạ phòng thủ · Thoải mái · Mắt cười · Chân thành',
      id: 'Alami · Meluluhkan · Natural · Mata senyum · Tulus',
    }),
    strength: L({
      ko: '꾸민 것이 없어서 상대방이 방어할 수가 없음. 가장 빠르게 마음을 열게 만드는 유형',
      en: 'There\'s nothing calculated, so they can\'t guard against you. You open hearts faster than any other type',
      ja: '作り込みがないので相手は防御できない。最も早く心を開かせるタイプ',
      'zh-CN': '毫无刻意，对方根本防不住。最快让人打开心扉的类型',
      'zh-TW': '毫無刻意，對方根本防不住。最快讓人打開心扉的類型',
      vi: 'Không hề tính toán nên đối phương không phòng thủ được. Kiểu mở lòng người khác nhanh nhất',
      id: 'Nggak ada yang dibuat-buat, jadi lawan bicara nggak bisa waspada. Tipe yang paling cepat buka hati',
    }),
    weakness: L({
      ko: '본인이 모르니까 타이밍을 잡기가 어렵고 상대방이 좋아하는지 늦게 알아챔',
      en: 'Because you don\'t realize it yourself, it\'s hard to time things — and you notice their feelings late',
      ja: '本人が気づかないのでタイミングを取りにくく、相手の好意にも気づくのが遅い',
      'zh-CN': '因为自己没意识到，很难把握时机，也较晚才发现对方喜欢你',
      'zh-TW': '因為自己沒意識到，很難把握時機，也較晚才發現對方喜歡你',
      vi: 'Vì bản thân không hay nên khó bắt nhịp, và cũng nhận ra muộn khi đối phương thích mình',
      id: 'Karena kamu nggak sadar sendiri, susah baca timing dan telat sadar kalau dia suka',
    }),
    goodMatch: L({
      ko: '진정성에 감동받는 사람. 계산된 플러팅에 지친 사람',
      en: 'Someone moved by sincerity. Someone tired of calculated flirting',
      ja: '本物の誠実さに心を動かされる人。計算されたフリートに疲れた人',
      'zh-CN': '会被真诚打动的人。厌倦套路撩法的人',
      'zh-TW': '會被真誠打動的人。厭倦套路撩法的人',
      vi: 'Người dễ xúc động vì sự chân thành. Người mệt mỏi với kiểu tán tỉnh tính toán',
      id: 'Orang yang tersentuh oleh ketulusan. Orang yang capek sama flirting yang penuh kalkulasi',
    }),
    friendTestimony: L({
      ko: '얘 이거 맞음. 본인은 아무것도 안 했다고 하는데 사람들이 다 넘어감',
      en: 'This is so them. They swear they did nothing, but everyone falls for them anyway',
      ja: 'これ当たってる。本人は何もしてないと言うのに、みんな落ちてる',
      'zh-CN': '这太准了。本人说啥也没做，但大家都被撩到了',
      'zh-TW': '這太準了。本人說啥也沒做，但大家都被撩到了',
      vi: 'Đúng bạn luôn. Bạn ấy bảo chẳng làm gì, nhưng ai cũng đổ',
      id: 'Ini bener banget. Dia bilang nggak ngapa-ngapain, tapi semua orang jatuh hati',
    }),
    shareSnippet: L({
      ko: '내 플러팅 스타일: 무의식 천연형 🌸 플러팅 한다는 거 본인만 몰랐음 ㅋㅋ 아무것도 안 했다는데 사람들이 넘어간다는 거 인정 → 내 플러팅 필살기 뭐야? 친구한테 증언 받아봐',
      en: 'My flirting style: Unconscious Natural 🌸 I was the only one who didn\'t know I was flirting lol People fall for me even when I swear I did nothing → What\'s my signature move? Ask a friend to testify',
      ja: '私のフリートスタイル：無意識天然型 🌸 フリートしてたの本人だけ知らなかったｗ 何もしてないのに落とすの認める → 私の必殺技は？友達に証言してもらおう',
      'zh-CN': '我的撩人风格：无意识天然型 🌸 只有我自己不知道在撩人哈哈 明明啥也没做却总能让人心动 → 我的撩人绝招是什么？让朋友来作证',
      'zh-TW': '我的撩人風格：無意識天然型 🌸 只有我自己不知道在撩人哈哈 明明啥也沒做卻總能讓人心動 → 我的撩人絕招是什麼？讓朋友來作證',
      vi: 'Phong cách flirt của tôi: Tự nhiên vô thức 🌸 Chỉ mình tôi không biết là đang flirt haha Không làm gì mà mọi người vẫn đổ → Chiêu đặc trưng của tôi là gì? Nhờ bạn bè làm chứng',
      id: 'Gaya flirting-ku: Alami tanpa sadar 🌸 Cuma aku yang nggak tahu kalau lagi flirt wkwk Nggak ngapa-ngapain tapi orang-orang jatuh hati → Jurus andalanku apa? Minta teman jadi saksi',
    }),
  },
  {
    type: 'Type2',
    emoji: '😄',
    title: L({
      ko: '웃기면서 설레게 하는, 유머 설렘 플러팅형 😄',
      en: 'Humor & Heart Flutter Flirt — You Make Them Laugh and Blush 😄',
      ja: '笑わせながらドキッとさせる、ユーモアときめきフリート型 😄',
      'zh-CN': '笑着让人心动，幽默撩型 😄',
      'zh-TW': '笑著讓人心動，幽默撩型 😄',
      vi: 'Vừa làm cười vừa làm rung động, kiểu hài hước 😄',
      id: 'Bikin ketawa sekaligus deg-degan, tipe humor 😄',
    }),
    shortDescription: L({
      ko: '플러팅 필살기: 웃기면서 자연스럽게 가까워지기',
      en: 'Signature move: Getting closer through laughter',
      ja: '必殺技：笑わせながら自然に距離を縮める',
      'zh-CN': '撩人绝招：笑着自然拉近距离',
      'zh-TW': '撩人絕招：笑著自然拉近距離',
      vi: 'Chiêu đặc trưng: Vừa làm cười vừa tự nhiên lại gần',
      id: 'Jurus andalan: Dekat sambil bikin ketawa',
    }),
    description: L({
      ko: '당신은 웃음으로 분위기를 열고 그 안에서 설렘을 심어놓습니다. 재밌는 말 한마디로 어색한 분위기를 깨고 공통점으로 자연스럽게 연결하며 밈이나 영상으로 핑계 없이 연락하는 타입입니다. 상대방이 당신과 있을 때 편하고 즐겁다는 걸 느끼게 됩니다. 그러다 어느 순간 설레는 자신을 발견합니다.',
      en: 'You open the mood with laughter and plant little flutters inside it. One funny line breaks awkwardness, common ground connects you naturally, and memes or videos become your excuse-free way to reach out. They start feeling comfortable and happy around you — then suddenly realize they\'re catching feelings.',
      ja: 'あなたは笑いで空気を開き、その中にときめきを仕込みます。面白い一言でぎこちなさを崩し、共通点で自然につながり、ミームや動画で口実なしに連絡するタイプ。相手はあなたといると楽で心地よいと感じ始め、気づけばドキドキしている自分に気づきます。',
      'zh-CN': '你用笑声打开气氛，再在里头种下心动。一句有趣的话打破尴尬，用共同点自然连接，用梗或视频毫无借口地联系。对方和你相处时会感到轻松愉快，然后在某个瞬间发现自己已经心动了。',
      'zh-TW': '你用笑聲打開氣氛，再在裡頭種下心動。一句有趣的話打破尷尬，用共同點自然連接，用梗或影片毫無藉口地聯絡。對方和你相處時會感到輕鬆愉快，然後在某個瞬間發現自己已經心動了。',
      vi: 'Bạn mở không khí bằng tiếng cười rồi gieo cảm giác rung động bên trong. Một câu vui phá bỏ sự gượng gạo, điểm chung nối hai người tự nhiên, meme hoặc video là cách liên lạc không cần cớ. Đối phương cảm thấy thoải mái và vui khi ở bên bạn — rồi bất ngờ nhận ra mình đã thích.',
      id: 'Kamu buka suasana dengan tawa lalu tanam rasa deg-degan di dalamnya. Satu kalimat lucu pecahin awkwardness, kesamaan nyambungin natural, meme atau video jadi cara hubungi tanpa alasan. Mereka merasa nyaman dan senang bareng kamu — lalu tiba-tiba sadar kalau hati mulai goyah.',
    }),
    flirtingSkill: L({
      ko: '유머로 문 열고 진심으로 마무리 😄',
      en: 'Open the door with humor, finish with sincerity 😄',
      ja: 'ユーモアで扉を開き、本音で締める 😄',
      'zh-CN': '用幽默开门，用真心收尾 😄',
      'zh-TW': '用幽默開門，用真心收尾 😄',
      vi: 'Mở cửa bằng hài hước, kết bằng chân thành 😄',
      id: 'Buka pintu pakai humor, tutup pakai ketulusan 😄',
    }),
    flirtingKeywords: L({
      ko: '유머·공통점·가벼움·자연스러운 연결·웃음',
      en: 'Humor · Common ground · Lightness · Natural connection · Laughter',
      ja: 'ユーモア・共通点・軽さ・自然なつながり・笑い',
      'zh-CN': '幽默·共同点·轻松·自然连接·笑声',
      'zh-TW': '幽默·共同點·輕鬆·自然連接·笑聲',
      vi: 'Hài hước · Điểm chung · Nhẹ nhàng · Kết nối tự nhiên · Tiếng cười',
      id: 'Humor · Kesamaan · Ringan · Koneksi natural · Tawa',
    }),
    strength: L({
      ko: '어색함이 없어서 상대방의 경계가 낮아짐. 같이 있으면 즐거운 사람이 됨',
      en: 'There\'s no awkwardness, so their guard stays low. You become someone fun to be around',
      ja: 'ぎこちなさがないので相手の警戒心が下がる。一緒にいると楽しい人になる',
      'zh-CN': '没有尴尬感，对方防备心很低。会成为让人相处愉快的人',
      'zh-TW': '沒有尷尬感，對方防備心很低。會成為讓人相處愉快的人',
      vi: 'Không gượng gạo nên đối phương hạ phòng thủ. Trở thành người ở bên cùng thì vui',
      id: 'Nggak awkward jadi pertahanan lawan bicara rendah. Jadi orang yang asik diajak bareng',
    }),
    weakness: L({
      ko: '너무 친구 같아서 연애 감정으로 연결되는 타이밍이 늦어질 수 있음',
      en: 'You can feel too much like a friend, so the shift to romance may come late',
      ja: '友達すぎて恋愛感情につながるタイミングが遅れることがある',
      'zh-CN': '太像朋友，转向恋爱感情的时间可能会偏晚',
      'zh-TW': '太像朋友，轉向戀愛感情的時間可能會偏晚',
      vi: 'Quá giống bạn bè nên thời điểm chuyển sang tình cảm có thể muộn',
      id: 'Terlalu terasa kayak temen, jadi momen pindah ke perasaan romantis bisa telat',
    }),
    goodMatch: L({
      ko: '가벼운 분위기를 좋아하는 사람. 유머에 반응하는 사람',
      en: 'Someone who likes a light mood. Someone who responds to humor',
      ja: '軽い空気が好きな人。ユーモアに反応する人',
      'zh-CN': '喜欢轻松氛围的人。会对幽默有反应的人',
      'zh-TW': '喜歡輕鬆氛圍的人。會對幽默有反應的人',
      vi: 'Người thích không khí nhẹ nhàng. Người phản ứng tốt với sự hài hước',
      id: 'Orang yang suka suasana ringan. Orang yang responsif terhadap humor',
    }),
    friendTestimony: L({
      ko: '맞음 ㅋㅋ 얘가 재밌는 말 하면서 자연스럽게 파고드는 스타일',
      en: 'Spot on lol They naturally get closer while saying funny things',
      ja: '当たってるｗ 面白いことを言いながら自然に距離を詰めるタイプ',
      'zh-CN': '太准了哈哈 总是一边讲有趣的话一边自然靠近',
      'zh-TW': '太準了哈哈 總是一邊講有趣的話一邊自然靠近',
      vi: 'Đúng luôn haha Kiểu vừa nói chuyện vui vừa tự nhiên tiến lại gần',
      id: 'Bener wkww Tipe yang deketin sambil ngomong hal lucu',
    }),
    shareSnippet: L({
      ko: '내 플러팅 스타일: 유머 설렘형 😄 웃기면서 자연스럽게 파고드는 스타일이래... 밈 보내서 연락 시도한 거 들켰음 ㅋㅋ → 내 플러팅 필살기 뭐야? 친구 태그해봐',
      en: 'My flirting style: Humor & Heart Flutter 😄 They say I get closer naturally while being funny... Got caught texting memes as an excuse lol → What\'s my signature move? Tag a friend',
      ja: '私のフリートスタイル：ユーモアときめき型 😄 笑わせながら自然に距離を詰めるって…ミーム送って連絡したのバレたｗ → 私の必殺技は？友達タグして',
      'zh-CN': '我的撩人风格：幽默心动型 😄 据说是一边搞笑一边自然靠近…用梗联系被发现了哈哈 → 我的撩人绝招是什么？@朋友来作证',
      'zh-TW': '我的撩人風格：幽默心動型 😄 據說是一邊搞笑一邊自然靠近…用梗聯絡被發現了哈哈 → 我的撩人絕招是什麼？@朋友來作證',
      vi: 'Phong cách flirt của tôi: Hài hước & rung động 😄 Bảo là vừa làm cười vừa lại gần tự nhiên… Lộ gửi meme để nhắn rồi haha → Chiêu đặc trưng của tôi là gì? Tag bạn bè',
      id: 'Gaya flirting-ku: Humor & deg-degan 😄 Katanya aku deketin sambil lucu… Ketauan kirim meme buat chat wkwk → Jurus andalanku apa? Tag temen',
    }),
  },
  {
    type: 'Type3',
    emoji: '🎯',
    title: L({
      ko: '상대방을 세상의 중심으로 만드는, 관심 집중 플러팅형 🎯',
      en: 'Focused Attention Flirt — You Make Them Feel Like the Center of the World 🎯',
      ja: '相手を世界の中心にする、関心集中フリート型 🎯',
      'zh-CN': '让对方成为宇宙中心，专注关注撩型 🎯',
      'zh-TW': '讓對方成為宇宙中心，專注關注撩型 🎯',
      vi: 'Khiến đối phương như trung tâm vũ trụ, kiểu tập trung quan tâm 🎯',
      id: 'Bikin lawan bicara jadi pusat dunia, tipe fokus perhatian 🎯',
    }),
    shortDescription: L({
      ko: '플러팅 필살기: 상대방이 세상에서 제일 특별한 사람인 것처럼 만들기',
      en: 'Signature move: Making them feel like the most special person alive',
      ja: '必殺技：相手を世界で一番特別な人にさせる',
      'zh-CN': '撩人绝招：让对方觉得自己是世上最特别的人',
      'zh-TW': '撩人絕招：讓對方覺得自己是世上最特別的人',
      vi: 'Chiêu đặc trưng: Làm họ cảm thấy mình là người đặc biệt nhất',
      id: 'Jurus andalan: Bikin mereka merasa paling spesial di dunia',
    }),
    description: L({
      ko: '당신과 이야기할 때 상대방은 자신이 가장 흥미로운 사람처럼 느껴집니다. 상대방이 예전에 말했던 것을 기억해서 연결하고, 말할 때 완전히 집중하고, 힘들 때 "처음 이야기한 사람"이 되는 타입입니다. 가장 기억에 남는 사람이 되는 방식으로 유혹합니다.',
      en: 'When they talk to you, they feel like the most interesting person in the room. You remember what they said before and connect it later, listen with full focus, and become "the first person they told" when things get hard. You seduce by becoming unforgettable.',
      ja: 'あなたと話すとき、相手は自分が一番面白い人だと感じます。以前言ったことを覚えてつなげ、話すときは完全に集中し、つらいときは「初めて話した人」になるタイプ。最も記憶に残る存在になることで誘います。',
      'zh-CN': '和你聊天时，对方会觉得自己是全场最有趣的人。你会记住他们说过的话并串联起来，说话时完全专注，在他们难过时成为"第一个倾诉的人"。你用成为最难忘的人这种方式来撩。',
      'zh-TW': '和你聊天時，對方會覺得自己是全場最有趣的人。你會記住他們說過的話並串聯起來，說話時完全專注，在他們難過時成為「第一個傾訴的人」。你用成為最難忘的人這種方式來撩。',
      vi: 'Khi nói chuyện với bạn, họ cảm thấy mình là người thú vị nhất. Bạn nhớ điều họ từng nói và nối lại, lắng nghe hoàn toàn tập trung, và trở thành "người đầu tiên họ kể" khi họ khó khăn. Bạn quyến rũ bằng cách trở thành người khó quên nhất.',
      id: 'Saat ngobrol sama kamu, mereka merasa jadi orang paling menarik. Kamu ingat yang pernah mereka bilang lalu nyambungin lagi, dengerin dengan fokus penuh, dan jadi "orang pertama yang mereka ceritakan" saat susah. Kamu menggoda dengan cara jadi yang paling nggak bisa dilupakan.',
    }),
    flirtingSkill: L({
      ko: '상대방의 말을 완전히 기억하고 관심 집중 🎯',
      en: 'Remember everything they say and focus completely 🎯',
      ja: '相手の言葉を完全に覚えて集中する 🎯',
      'zh-CN': '完全记住对方的话并专注关注 🎯',
      'zh-TW': '完全記住對方的話並專注關注 🎯',
      vi: 'Nhớ hết lời họ nói và tập trung hoàn toàn 🎯',
      id: 'Ingat semua omongan mereka dan fokus penuh 🎯',
    }),
    flirtingKeywords: L({
      ko: '경청·기억·공감·집중·특별함',
      en: 'Listening · Memory · Empathy · Focus · Specialness',
      ja: '傾聴・記憶・共感・集中・特別感',
      'zh-CN': '倾听·记忆·共情·专注·特别感',
      'zh-TW': '傾聽·記憶·共情·專注·特別感',
      vi: 'Lắng nghe · Ghi nhớ · Đồng cảm · Tập trung · Cảm giác đặc biệt',
      id: 'Mendengarkan · Mengingat · Empati · Fokus · Spesial',
    }),
    strength: L({
      ko: '상대방이 "이 사람 나한테 관심 있나?"가 아니라 "나를 정말 잘 아는 사람"으로 인식함. 깊은 연결을 만들어냄',
      en: 'They don\'t think "Are they into me?" — they think "This person really gets me." You build deep connection',
      ja: '相手は「この人、私に気がある？」ではなく「本当に私をわかってくれる人」と感じる。深いつながりを作る',
      'zh-CN': '对方不会想"这人是不是喜欢我？"而是觉得"这人真的懂我"。能建立深层连接',
      'zh-TW': '對方不會想「這人是不是喜歡我？」而是覺得「這人真的懂我」。能建立深層連接',
      vi: 'Họ không nghĩ "Người này có thích mình không?" mà nghĩ "Người này thật sự hiểu mình." Tạo kết nối sâu',
      id: 'Mereka nggak mikir "Dia suka aku ya?" tapi "Orang ini beneran ngerti aku." Bikin koneksi yang dalam',
    }),
    weakness: L({
      ko: '너무 잘 들어줘서 상대방이 친구로 정의해버리는 경우가 생길 수 있음',
      en: 'You listen so well that they sometimes define you as just a friend',
      ja: '聞きすぎて、相手が友達枠に決めてしまうことがある',
      'zh-CN': '太会倾听，有时会被对方定义成朋友',
      'zh-TW': '太會傾聽，有時會被對方定義成朋友',
      vi: 'Nghe quá giỏi nên đôi khi bị xếp vào nhóm bạn bè',
      id: 'Terlalu jago dengerin sampai kadang dilabeli cuma temen',
    }),
    goodMatch: L({
      ko: '이해받고 싶은 사람. 깊은 대화를 원하는 사람',
      en: 'Someone who wants to feel understood. Someone who craves deep conversation',
      ja: '理解されたい人。深い会話を求める人',
      'zh-CN': '渴望被理解的人。想要深度对话的人',
      'zh-TW': '渴望被理解的人。想要深度對話的人',
      vi: 'Người muốn được thấu hiểu. Người thích trò chuyện sâu',
      id: 'Orang yang ingin dipahami. Orang yang suka obrolan dalam',
    }),
    friendTestimony: L({
      ko: '이거 딱 맞음. 얘가 내 말 다 기억하고 있어서 내가 먼저 빠진 적 있음',
      en: 'This is exactly them. They remember everything I say — I fell first more than once',
      ja: 'これピッタリ。全部覚えてるから、私が先に落ちたことある',
      'zh-CN': '太准了。Ta记得我说过的所有话，我因此先动心了',
      'zh-TW': '太準了。對方記得我說過的所有話，我因此先動心了',
      vi: 'Đúng bài luôn. Bạn ấy nhớ hết lời tôi nói nên tôi từng thích trước',
      id: 'Pas banget. Dia inget semua omonganku, jadi aku pernah jatuh duluan',
    }),
    shareSnippet: L({
      ko: '내 플러팅 스타일: 관심 집중형 🎯 상대방 말 다 기억하고 집중하는 스타일이래... 처음 이야기한 사람 되는 거 맞음 → 친구야 이거 맞아? 태그해봐',
      en: 'My flirting style: Focused Attention 🎯 They say I remember everything and listen like it matters... Being "the first person they told" is real → Friend, is this me? Tag them',
      ja: '私のフリートスタイル：関心集中型 🎯 相手の言葉全部覚えて集中するって…「初めて話した人」になるの本当 → 友達、これ当たってる？タグして',
      'zh-CN': '我的撩人风格：专注关注型 🎯 据说会记住对方说的所有话并专注倾听…成为"第一个倾诉的人"是真的 → 朋友，这准吗？@来作证',
      'zh-TW': '我的撩人風格：專注關注型 🎯 據說會記住對方說的所有話並專注傾聽…成為「第一個傾訴的人」是真的 → 朋友，這準嗎？@來作證',
      vi: 'Phong cách flirt của tôi: Tập trung quan tâm 🎯 Bảo là nhớ hết lời đối phương và lắng nghe rất tập trung… Là "người đầu tiên họ kể" là thật → Bạn ơi đúng không? Tag thử',
      id: 'Gaya flirting-ku: Fokus perhatian 🎯 Katanya aku inget semua omongan lawan bicara dan dengerin fokus… Jadi "orang pertama yang dia ceritakan" bener → Temen, ini bener? Tag dong',
    }),
  },
  {
    type: 'Type4',
    emoji: '🎭',
    title: L({
      ko: '당기고 밀면서 미치게 만드는, 장인 밀당 플러팅형 🎭',
      en: 'Master Push-Pull Flirt — You Drive Them Crazy with Tension 🎭',
      ja: '引いて押して狂わせる、達人の駆け引きフリート型 🎭',
      'zh-CN': '推拉之间让人抓狂，高手暧昧撩型 🎭',
      'zh-TW': '推拉之間讓人抓狂，高手曖昧撩型 🎭',
      vi: 'Kéo đẩy khiến người ta phát điên, kiểu push-pull bậc thầy 🎭',
      id: 'Tarik-dorong bikin gila, tipe push-pull master 🎭',
    }),
    shortDescription: L({
      ko: '플러팅 필살기: 밀었다 당겼다 상대방이 먼저 말하게 만들기',
      en: 'Signature move: Push and pull until they speak first',
      ja: '必殺技：引いて押して相手に先に言わせる',
      'zh-CN': '撩人绝招：推拉之间让对方先开口',
      'zh-TW': '撩人絕招：推拉之間讓對方先開口',
      vi: 'Chiêu đặc trưng: Kéo đẩy để họ nói trước',
      id: 'Jurus andalan: Push-pull sampai dia yang ngomong duluan',
    }),
    description: L({
      ko: '당신의 가장 강력한 유혹은 상대방이 먼저 하게 만드는 것입니다. 뜸하게 연락하다가 딱 한마디로 존재감을 남기고, 무표정으로 돌아보다가 살짝 웃고, 분위기가 무르익어도 먼저 말하지 않고 기다리는 타입입니다. 상대방이 먼저 카드를 꺼내도록 설계합니다.',
      en: 'Your strongest charm is making them move first. You reply less often, then leave your mark with one perfect line. You look back with a blank face, then smile slightly. Even when the mood is ripe, you wait instead of speaking first. You design the moment so they show their hand first.',
      ja: 'あなたの最強の魅力は、相手に先に動かせること。連絡を控えめにして、一言で存在感を残し、無表情で見返してから少し笑い、空気が熟しても先に言わないタイプ。相手が先にカードを出すように設計します。',
      'zh-CN': '你最强的魅力，是让对方先行动。联系时冷一点，再用一句话留下存在感；面无表情地看回去，再淡淡一笑；气氛到位了也不先开口。你会设计局面，让对方先亮底牌。',
      'zh-TW': '你最強的魅力，是讓對方先行動。聯絡時冷一點，再用一句話留下存在感；面無表情地看回去，再淡淡一笑；氣氛到位了也不先開口。你會設計局面，讓對方先亮底牌。',
      vi: 'Sức hút mạnh nhất của bạn là khiến đối phương chủ động trước. Liên lạc thưa hơn rồi để lại dấu ấn bằng một câu duy nhất; nhìn lại với mặt không cảm xúc rồi mỉm cười nhẹ; không khí đã chín vẫn không nói trước. Bạn thiết kế để họ lật bài trước.',
      id: 'Daya tarik terkuatmu adalah bikin lawan bicara yang gerak duluan. Chat lebih jarang, lalu ninggalin jejak dengan satu kalimat. Tatap balik datar, lalu tersenyum tipis. Suasana sudah matang pun nggak ngomong duluan. Kamu desain momen biar dia yang buka kartu duluan.',
    }),
    flirtingSkill: L({
      ko: '먼저 하지 않고 상대방이 먼저 하게 만들기 🎭',
      en: 'Never move first — make them move first 🎭',
      ja: '先に動かず、相手に先に動かせる 🎭',
      'zh-CN': '不先行动，让对方先行动 🎭',
      'zh-TW': '不先行動，讓對方先行動 🎭',
      vi: 'Không làm trước — để họ làm trước 🎭',
      id: 'Nggak gerak duluan — bikin dia yang gerak duluan 🎭',
    }),
    flirtingKeywords: L({
      ko: '밀당·긴장감·설계·여백·역전',
      en: 'Push-pull · Tension · Design · Space · Reversal',
      ja: '駆け引き・緊張感・設計・余白・逆転',
      'zh-CN': '推拉·紧张感·设计·留白·反转',
      'zh-TW': '推拉·緊張感·設計·留白·反轉',
      vi: 'Push-pull · Căng thẳng · Thiết kế · Khoảng trống · Đảo ngược',
      id: 'Push-pull · Tension · Desain · Ruang · Balik peran',
    }),
    strength: L({
      ko: '상대방이 능동적으로 다가오게 만들어서 관계 주도권을 자연스럽게 가짐',
      en: 'You make them come to you actively, so you naturally hold the upper hand',
      ja: '相手が能動的に近づくようにして、関係の主導権を自然に握る',
      'zh-CN': '让对方主动靠近，自然掌握关系主导权',
      'zh-TW': '讓對方主動靠近，自然掌握關係主導權',
      vi: 'Khiến đối phương chủ động lại gần, tự nhiên nắm quyền trong mối quan hệ',
      id: 'Bikin mereka mendekat sendiri, jadi natural pegang kendali hubungan',
    }),
    weakness: L({
      ko: '너무 길어지면 상대방이 지쳐서 포기할 수 있음. 타이밍이 중요',
      en: 'If it goes on too long, they may get tired and give up. Timing is everything',
      ja: '長引きすぎると相手が疲れて諦めることがある。タイミングが重要',
      'zh-CN': '拖太久对方可能会累而放弃。时机很重要',
      'zh-TW': '拖太久對方可能會累而放棄。時機很重要',
      vi: 'Kéo dài quá họ có thể mệt và bỏ cuộc. Timing rất quan trọng',
      id: 'Kalau kepanjangan, mereka bisa capek dan nyerah. Timing itu kunci',
    }),
    goodMatch: L({
      ko: '설레는 감정에 민감한 사람. 밀당에 반응하는 사람',
      en: 'Someone sensitive to butterflies. Someone who responds to push-pull',
      ja: 'ときめきに敏感な人。駆け引きに反応する人',
      'zh-CN': '对心动感敏感的人。会对推拉有反应的人',
      'zh-TW': '對心動感敏感的人。會對推拉有反應的人',
      vi: 'Người nhạy cảm với cảm giác rung động. Người phản ứng với push-pull',
      id: 'Orang yang sensitif sama perasaan deg-degan. Orang yang responsif ke push-pull',
    }),
    friendTestimony: L({
      ko: '맞음 ㅋㅋ 얘가 관심 있는 척 없는 척 하다가 사람 미치게 만드는 스타일',
      en: 'True lol They act like they don\'t care, then drive people crazy',
      ja: '当たってるｗ 気があるフリしないフリして、人を狂わせるタイプ',
      'zh-CN': '太准了哈哈 装作没兴趣，其实把人撩到发疯的类型',
      'zh-TW': '太準了哈哈 裝作沒興趣，其實把人撩到發瘋的類型',
      vi: 'Đúng luôn haha Kiểu giả vờ không quan tâm rồi làm người ta phát điên',
      id: 'Bener wkwk Tipe pura-pura nggak peduli tapi bikin orang gila',
    }),
    shareSnippet: L({
      ko: '내 플러팅 스타일: 장인 밀당형 🎭 상대방이 먼저 말하게 만드는 스타일이래... 밀었다 당겼다 미치게 만드는 거 인정 ㅋㅋ → 이거 맞지? 친구한테 증언 받아봐',
      en: 'My flirting style: Master Push-Pull 🎭 They say I make people speak first... Admit it, the push-pull drives people crazy lol → Is this me? Get a friend to testify',
      ja: '私のフリートスタイル：達人駆け引き型 🎭 相手に先に言わせるって…引いて押して狂わせるの認めるｗ → これ当たってる？友達に証言してもらおう',
      'zh-CN': '我的撩人风格：高手推拉型 🎭 据说会让对方先开口…推拉把人逼疯这点我认哈哈 → 这准吗？让朋友来作证',
      'zh-TW': '我的撩人風格：高手推拉型 🎭 據說會讓對方先開口…推拉把人逼瘋這點我認哈哈 → 這準嗎？讓朋友來作證',
      vi: 'Phong cách flirt của tôi: Push-pull bậc thầy 🎭 Bảo là để đối phương nói trước… Kéo đẩy làm người ta phát điên, tôi thừa nhận haha → Đúng không? Nhờ bạn bè làm chứng',
      id: 'Gaya flirting-ku: Push-pull master 🎭 Katanya aku bikin lawan bicara ngomong duluan… Push-pull bikin gila, aku akui wkwk → Ini bener? Minta temen jadi saksi',
    }),
  },
  {
    type: 'Type5',
    emoji: '🔥',
    title: L({
      ko: '직접 분위기를 만들어버리는, 직진 분위기 플러팅형 🔥',
      en: 'Direct Mood Maker Flirt — You Build the Vibe and Move Forward 🔥',
      ja: '直接ムードを作る、直進ムードフリート型 🔥',
      'zh-CN': '亲手制造气氛，直球氛围撩型 🔥',
      'zh-TW': '親手製造氣氛，直球氛圍撩型 🔥',
      vi: 'Tự tạo không khí, kiểu thẳng thắn dẫn dắt 🔥',
      id: 'Bikin suasana sendiri, tipe langsung dan memimpin 🔥',
    }),
    shortDescription: L({
      ko: '플러팅 필살기: 분위기 조성하고 직접 다음 약속 만들기',
      en: 'Signature move: Set the mood and make the next plan yourself',
      ja: '必殺技：ムードを作って次の約束を自分から取る',
      'zh-CN': '撩人绝招：营造气氛并直接约下次',
      'zh-TW': '撩人絕招：營造氣氛並直接約下次',
      vi: 'Chiêu đặc trưng: Tạo không khí và chủ động hẹn lần sau',
      id: 'Jurus andalan: Bikin suasana dan langsung janjian lagi',
    }),
    description: L({
      ko: '당신은 분위기를 만드는 데 가장 능숙한 사람입니다. 다음에 데려갈 좋은 곳을 미리 언급하고, 힘든 상대방에게 자연스럽게 밥 약속을 잡고, 헤어질 때 "다음 주 시간 어때요?"를 바로 꺼내는 타입입니다. 설레는 분위기를 조성한 다음 그 분위기 안에서 다음 단계로 넘어가는 것을 자연스럽게 만들어냅니다.',
      en: 'You\'re one of the best at creating mood. You mention a great place you\'ll take them next, naturally set up a meal when they\'re down, and say "How\'s next week?" as you part ways. You build a fluttery atmosphere, then smoothly move to the next step inside it.',
      ja: 'あなたはムード作りが最も上手い人です。次に連れて行く場所を先に出し、つらい相手に自然に食事の約束を取り、別れるときに「来週、時間どう？」をすぐ言うタイプ。ときめく空気を作ったあと、その中で次の段階へ自然につなげます。',
      'zh-CN': '你最擅长制造气氛。会提前提到下次要带去的好地方，在对方难过时自然约吃饭，分别时直接问"下周有时间吗？"。你会先营造心动氛围，再在那个氛围里自然推进到下一步。',
      'zh-TW': '你最擅長製造氣氛。會提前提到下次要帶去的好地方，在對方難過時自然約吃飯，分別時直接問「下週有時間嗎？」。你會先營造心動氛圍，再在那個氛圍裡自然推進到下一步。',
      vi: 'Bạn rất giỏi tạo không khí. Nói trước về nơi hay sẽ dẫn họ đi, tự nhiên hẹn ăn khi họ buồn, và khi chia tay hỏi luôn "Tuần sau rảnh không?" Bạn tạo không khí rung động rồi tự nhiên chuyển sang bước tiếp theo.',
      id: 'Kamu paling jago bikin suasana. Sebut tempat bagus yang bakal diajak next, natural janjian makan pas dia lagi down, dan pas pamit langsung tanya "Minggu depan waktumu gimana?" Kamu bikin vibe deg-degan lalu natural lanjut ke step berikutnya.',
    }),
    flirtingSkill: L({
      ko: '분위기 만들고 다음 단계 자연스럽게 연결 🔥',
      en: 'Build the mood and connect to the next step 🔥',
      ja: 'ムードを作り、次の段階へ自然につなぐ 🔥',
      'zh-CN': '制造气氛并自然连接下一步 🔥',
      'zh-TW': '製造氣氛並自然連接下一步 🔥',
      vi: 'Tạo không khí và nối sang bước tiếp theo 🔥',
      id: 'Bikin suasana dan nyambung ke step berikutnya 🔥',
    }),
    flirtingKeywords: L({
      ko: '리딩·분위기·적극성·다음 약속·추진력',
      en: 'Leading · Mood · Initiative · Next plan · Momentum',
      ja: 'リード・ムード・積極性・次の約束・推進力',
      'zh-CN': '主导·气氛·积极性·下次约定·推进力',
      'zh-TW': '主導·氣氛·積極性·下次約定·推進力',
      vi: 'Dẫn dắt · Không khí · Chủ động · Hẹn lần sau · Đà tiến',
      id: 'Memimpin · Suasana · Inisiatif · Janji berikutnya · Momentum',
    }),
    strength: L({
      ko: '분위기를 흐지부지 끝내지 않고 다음으로 연결하는 능력. 관계 속도가 빠름',
      en: 'You don\'t let the mood fade — you connect it to what\'s next. Relationships move fast with you',
      ja: 'ムードを流し切らず次につなげる力がある。関係のスピードが速い',
      'zh-CN': '不会让气氛白白结束，而是连接到下一步。关系推进很快',
      'zh-TW': '不會讓氣氛白白結束，而是連接到下一步。關係推進很快',
      vi: 'Không để không khí tan đi vô ích mà nối sang bước tiếp theo. Mối quan hệ tiến nhanh',
      id: 'Nggak biarin suasana cuma habis begitu — kamu sambungin ke langkah berikutnya. Hubungan maju cepat',
    }),
    weakness: L({
      ko: '상대방이 아직 준비가 안 됐을 때 속도 차이로 부담을 줄 수 있음',
      en: 'If they\'re not ready yet, your pace can feel like pressure',
      ja: '相手の準備がまだのとき、速度差でプレッシャーになることがある',
      'zh-CN': '对方还没准备好时，速度差可能带来压力',
      'zh-TW': '對方還沒準備好時，速度差可能帶來壓力',
      vi: 'Khi đối phương chưa sẵn sàng, chênh tốc độ có thể gây áp lực',
      id: 'Kalau mereka belum siap, beda tempo bisa terasa memberatkan',
    }),
    goodMatch: L({
      ko: '리드해주는 사람을 좋아하는 사람. 적극성에 반응하는 사람',
      en: 'Someone who likes being led. Someone who responds to initiative',
      ja: 'リードされるのが好きな人。積極性に反応する人',
      'zh-CN': '喜欢被带领的人。会对主动有反应的人',
      'zh-TW': '喜歡被帶領的人。會對主動有反應的人',
      vi: 'Người thích được dẫn dắt. Người phản ứng tốt với sự chủ động',
      id: 'Orang yang suka dipimpin. Orang yang responsif ke inisiatif',
    }),
    friendTestimony: L({
      ko: '이거 완전 맞음. 얘가 분위기 만들고 바로 약속 잡는 스타일. 나도 당한 적 있음',
      en: 'This is 100% them. They set the mood and lock in plans right away. I\'ve fallen for it too',
      ja: 'これ完全に当たってる。ムード作ってすぐ約束取るタイプ。私も落とされたことある',
      'zh-CN': '完全命中。Ta会制造气氛然后立刻约下次。我也中过招',
      'zh-TW': '完全命中。對方會製造氣氛然後立刻約下次。我也中過招',
      vi: 'Đúng 100%. Bạn ấy tạo không khí rồi hẹn luôn. Tôi cũng từng dính',
      id: 'Ini 100% bener. Dia bikin suasana terus langsung janjian. Aku juga pernah kena',
    }),
    shareSnippet: L({
      ko: '내 플러팅 스타일: 직진 분위기형 🔥 분위기 만들고 바로 약속 잡는 스타일이래... 리드하는 거 맞음 → 친구야 이거 맞다고 증언해줘 ㅋㅋ',
      en: 'My flirting style: Direct Mood Maker 🔥 They say I build the vibe and lock in plans right away... Leading is real → Friend, testify that this is me lol',
      ja: '私のフリートスタイル：直進ムード型 🔥 ムード作ってすぐ約束取るって…リードするの認める → 友達、これ当たってるって証言してｗ',
      'zh-CN': '我的撩人风格：直球氛围型 🔥 据说会制造气氛然后立刻约下次…主导这点我认 → 朋友来作证哈哈',
      'zh-TW': '我的撩人風格：直球氛圍型 🔥 據說會製造氣氛然後立刻約下次…主導這點我認 → 朋友來作證哈哈',
      vi: 'Phong cách flirt của tôi: Thẳng thắn dẫn dắt 🔥 Bảo là tạo không khí rồi hẹn luôn… Dẫn dắt là thật → Bạn ơi xác nhận giúp haha',
      id: 'Gaya flirting-ku: Langsung & pimpin 🔥 Katanya aku bikin suasana terus langsung janjian… Memimpin memang bener → Temen, saksiin dong wkwk',
    }),
  },
  {
    type: 'Type6',
    emoji: '💜',
    title: L({
      ko: '아무것도 안 해도 분위기인, 침묵 마스터 플러팅형 💜',
      en: 'Silence Master Flirt — The Mood Speaks for You 💜',
      ja: '何もしなくても空気になる、沈黙マスターフリート型 💜',
      'zh-CN': '什么都不做也有气氛，沉默大师撩型 💜',
      'zh-TW': '什麼都不做也有氣氛，沉默大師撩型 💜',
      vi: 'Không làm gì vẫn có không khí, kiểu bậc thầy im lặng 💜',
      id: 'Nggak ngapa-ngapain tapi suasananya ada, tipe master diam 💜',
    }),
    shortDescription: L({
      ko: '플러팅 필살기: 말하지 않아도 느껴지는 분위기',
      en: 'Signature move: A mood you feel without words',
      ja: '必殺技：言わなくても伝わる空気',
      'zh-CN': '撩人绝招：不说话也能感受到的气氛',
      'zh-TW': '撩人絕招：不說話也能感受到的氣氛',
      vi: 'Chiêu đặc trưng: Không khí cảm nhận được dù không nói',
      id: 'Jurus andalan: Suasana yang kerasa tanpa kata-kata',
    }),
    description: L({
      ko: '당신의 가장 강력한 유혹은 말하지 않는 것입니다. 짧은 한마디, 눈 마주침 하나, 침묵 속에서 만들어지는 분위기. 당신은 많이 말하지 않아도 상대방이 더 많이 생각하게 만드는 타입입니다. "저 사람 나한테 관심 있나?"라는 생각이 계속 들게 만드는 것. 그게 당신의 필살기입니다.',
      en: 'Your strongest charm is what you don\'t say. One short line. One look. A mood built in silence. You don\'t need many words to make them think about you more. You keep them wondering, "Are they into me?" That\'s your signature move.',
      ja: 'あなたの最強の魅力は、言わないことです。短い一言、目が合う瞬間、沈黙の中で生まれる空気。たくさん話さなくても、相手にもっと考えさせるタイプ。「あの人、私に気があるの？」と思わせ続ける。それがあなたの必殺技です。',
      'zh-CN': '你最强的魅力，是不说。简短的一句话、一次对视、沉默里形成的气氛。你不需要说很多，就能让对方想得更多。让人不断冒出"这人是不是对我有意思？"——这就是你的绝招。',
      'zh-TW': '你最強的魅力，是不說。簡短的一句話、一次對視、沉默裡形成的氣氛。你不需要說很多，就能讓對方想得更多。讓人不斷冒出「這人是不是對我有意思？」——這就是你的絕招。',
      vi: 'Sức hút mạnh nhất của bạn là im lặng. Một câu ngắn. Một lần chạm mắt. Không khí hình thành trong khoảng lặng. Bạn không cần nói nhiều mà vẫn khiến họ nghĩ về bạn nhiều hơn. Luôn khiến họ tự hỏi "Người này có thích mình không?" — đó là chiêu đặc trưng của bạn.',
      id: 'Daya tarik terkuatmu adalah diam. Satu kalimat pendek. Satu tatapan. Suasana yang kebentuk dalam hening. Kamu nggak perlu banyak omong tapi bikin mereka makin mikirin kamu. Terus bikin mereka bertanya, "Dia suka aku ya?" — itu jurus andalanmu.',
    }),
    flirtingSkill: L({
      ko: '말하지 않음으로 더 많이 말하기 💜',
      en: 'Say more by saying less 💜',
      ja: '言わないことで、もっと伝える 💜',
      'zh-CN': '用不说来传达更多 💜',
      'zh-TW': '用不說來傳達更多 💜',
      vi: 'Nói nhiều hơn bằng cách nói ít 💜',
      id: 'Bilang lebih banyak dengan bilang lebih sedikit 💜',
    }),
    flirtingKeywords: L({
      ko: '침묵·여운·미스터리·눈 마주침·한 마디',
      en: 'Silence · Afterglow · Mystery · Eye contact · One line',
      ja: '沈黙・余韻・ミステリー・目が合う・一言',
      'zh-CN': '沉默·余韵·神秘感·对视·一句话',
      'zh-TW': '沉默·餘韻·神秘感·對視·一句話',
      vi: 'Im lặng · Dư vị · Bí ẩn · Chạm mắt · Một câu',
      id: 'Diam · Bekas rasa · Misteri · Tatap mata · Satu kalimat',
    }),
    strength: L({
      ko: '상대방이 계속 생각하게 만드는 여운. 가장 기억에 남는 사람이 됨',
      en: 'You leave an afterglow that keeps them thinking. You become unforgettable',
      ja: '相手をずっと考えさせる余韻を残す。最も記憶に残る人になる',
      'zh-CN': '留下让人不断回味的余韵。会成为最难忘的人',
      'zh-TW': '留下讓人不斷回味的餘韻。會成為最難忘的人',
      vi: 'Để lại dư vị khiến họ cứ nghĩ mãi. Trở thành người khó quên nhất',
      id: 'Ninggalin bekas rasa yang bikin mereka terus kepikiran. Jadi yang paling nggak bisa dilupakan',
    }),
    weakness: L({
      ko: '너무 미스터리하면 상대방이 관심 없다고 오해하고 포기할 수 있음. 가끔 신호 하나는 줘야 함',
      en: 'Too much mystery and they may think you\'re not interested and give up. You need to send a signal sometimes',
      ja: 'ミステリーすぎると、関心がないと誤解して諦めることがある。たまには合図が必要',
      'zh-CN': '太神秘的话，对方可能误以为没兴趣而放弃。偶尔还是要给一个信号',
      'zh-TW': '太神秘的話，對方可能誤以為沒興趣而放棄。偶爾還是要給一個信號',
      vi: 'Quá bí ẩn thì họ có thể tưởng bạn không quan tâm và bỏ cuộc. Thỉnh thoảng vẫn cần một tín hiệu',
      id: 'Terlalu misterius, mereka bisa salah paham nggak tertarik lalu nyerah. Kadang perlu kasih sinyal',
    }),
    goodMatch: L({
      ko: '분위기에 민감한 사람. 말보다 눈빛에 반응하는 사람',
      en: 'Someone sensitive to mood. Someone who responds to looks more than words',
      ja: '空気に敏感な人。言葉より目線に反応する人',
      'zh-CN': '对气氛敏感的人。比起语言更会被眼神打动的人',
      'zh-TW': '對氣氛敏感的人。比起語言更會被眼神打動的人',
      vi: 'Người nhạy cảm với không khí. Người phản ứng với ánh mắt hơn lời nói',
      id: 'Orang yang sensitif sama suasana. Orang yang lebih responsif ke tatapan daripada kata-kata',
    }),
    friendTestimony: L({
      ko: '완전 맞음. 얘가 아무 말도 안 하는데 그게 더 설레는 이상한 스타일',
      en: 'Totally true. They barely say anything, and somehow that\'s even more exciting',
      ja: '完全に当たってる。ほとんど話さないのに、それがもっとドキドキする変なタイプ',
      'zh-CN': '完全命中。Ta几乎不说话，但那样反而更让人心动',
      'zh-TW': '完全命中。對方幾乎不說話，但那樣反而更讓人心動',
      vi: 'Đúng hoàn toàn. Bạn ấy gần như không nói gì mà càng làm người ta rung động hơn',
      id: 'Bener banget. Dia hampir nggak ngomong tapi malah makin bikin deg-degan',
    }),
    shareSnippet: L({
      ko: '내 플러팅 스타일: 침묵 마스터형 💜 아무 말 안 해도 분위기인 스타일이래... 그게 더 설렌다는 거 이해는 함 ㅋㅋ → 이거 맞지? 친구 태그해서 증언 받아봐',
      en: 'My flirting style: Silence Master 💜 They say the vibe is there even when I say nothing... I get why that\'s exciting lol → Is this me? Tag a friend to testify',
      ja: '私のフリートスタイル：沈黙マスター型 💜 何も言わなくても空気があるって…それがドキドキするのはわかるｗ → これ当たってる？友達タグして証言して',
      'zh-CN': '我的撩人风格：沉默大师型 💜 据说什么都不说也有气氛…我懂为什么那样更让人心动哈哈 → 这准吗？@朋友来作证',
      'zh-TW': '我的撩人風格：沉默大師型 💜 據說什麼都不說也有氣氛…我懂為什麼那樣更讓人心動哈哈 → 這準嗎？@朋友來作證',
      vi: 'Phong cách flirt của tôi: Bậc thầy im lặng 💜 Bảo là không nói gì vẫn có không khí… Tôi hiểu sao nó lại rung động haha → Đúng không? Tag bạn bè làm chứng',
      id: 'Gaya flirting-ku: Master diam 💜 Katanya nggak ngomong apa-apa tapi suasananya ada… Aku ngerti kenapa itu bikin deg-degan wkwk → Ini bener? Tag temen buat saksi',
    }),
  },
];
