/** 밸런스 게임 — 가족 극한편 · phase3-family-balance-game · 12라운드 2지선다 · A=0/B=1 · 7개 로케일 */

export type Phase3FamilyBalanceGameLocaleKey = 'ko' | 'en' | 'ja' | 'zh-CN' | 'zh-TW' | 'vi' | 'id';

function localeMap(t: Record<Phase3FamilyBalanceGameLocaleKey, string>): Record<Phase3FamilyBalanceGameLocaleKey, string> {
  return t;
}

function opt(m: Record<Phase3FamilyBalanceGameLocaleKey, string>, score: number): { text: Record<Phase3FamilyBalanceGameLocaleKey, string>; score: number } {
  return { text: localeMap(m), score };
}

export interface Phase3FamilyBalanceGameQuestion {
  id: number;
  question: Record<Phase3FamilyBalanceGameLocaleKey, string>;
  options: { text: Record<Phase3FamilyBalanceGameLocaleKey, string>; score: number }[];
}

export interface Phase3FamilyBalanceGameResult {
  type: string;
  emoji: string;
  title: Record<Phase3FamilyBalanceGameLocaleKey, string>;
  shortDescription: Record<Phase3FamilyBalanceGameLocaleKey, string>;
  description: Record<Phase3FamilyBalanceGameLocaleKey, string>;
  empathyLevel: Record<Phase3FamilyBalanceGameLocaleKey, string>;
  characteristics: Record<Phase3FamilyBalanceGameLocaleKey, string>;
  goodMatch: Record<Phase3FamilyBalanceGameLocaleKey, string>;
  badMatch: Record<Phase3FamilyBalanceGameLocaleKey, string>;
  certificationPhrase: Record<Phase3FamilyBalanceGameLocaleKey, string>;
  shareLine: Record<Phase3FamilyBalanceGameLocaleKey, string>;
}

export function calculatePhase3FamilyBalanceGameResult(answers: number[]): string {
  const total = answers.reduce((sum, s) => sum + (s ?? 0), 0);
  if (total <= 1) return 'Type1';
  if (total <= 3) return 'Type2';
  if (total <= 6) return 'Type3';
  if (total <= 9) return 'Type4';
  if (total <= 11) return 'Type5';
  return 'Type6';
}

export const phase3FamilyBalanceGameQuestions: Phase3FamilyBalanceGameQuestion[] = [

  {
    id: 1,
    question: localeMap({
      ko: "부모님이 급하게 빚보증을 서달라고 하신다. 잘못되면 내 전 재산이 날아갈 수 있다. 나는?",
      en: "Your parents urgently ask you to co-sign a loan. If things go wrong, you could lose everything you own. What do you do?",
      ja: "両親が急いで連帯保証人になってほしいと頼んできた。うまくいかなければ自分の全財産を失うかもしれない。あなたは？",
      'zh-CN': "父母急需你作贷款担保。一旦出事，你可能失去全部财产。你会？",
      'zh-TW': "父母急需你作貸款擔保。一旦出事，你可能失去全部財產。你會？",
      vi: "Bố mẹ đột ngột nhờ bạn bảo lãnh khoản vay. Nếu trót, bạn có thể mất toàn bộ tài sản. Bạn sẽ?",
      id: "Orang tua mendesak kamu menjadi penjamin pinjaman. Kalau salah, seluruh hartamu bisa hilang. Kamu?",
    }),
    options: [
      opt(localeMap({
        ko: "거절한다. 빚보증은 나도 같이 무너지는 길이다. 다른 방법을 찾아야 한다",
        en: "Refuse. Co-signing is a path to going down together. We need to find another way",
        ja: "断る。連帯保証は一緒に倒れる道だ。別の方法を探すべきだ",
        'zh-CN': "拒绝。担保等于一起垮掉，必须另找办法",
        'zh-TW': "拒絕。擔保等於一起垮掉，必須另找辦法",
        vi: "Từ chối. Bảo lãnh là con đường cùng sụp đổ. Phải tìm cách khác",
        id: "Menolak. Jadi penjamin berarti ikut jatuh. Harus cari cara lain",
    }), 0),
      opt(localeMap({
        ko: "선다. 부모님이 급하신데 거절할 수 없다. 최악의 상황도 감수한다",
        en: "Sign. They're in a crisis—I can't say no. I'll accept even the worst outcome",
        ja: "署名する。切羽詰まっているのに断れない。最悪の事態も受け入れる",
        'zh-CN': "签字。父母这么急，没法拒绝。最坏的情况也接受",
        'zh-TW': "簽字。父母這麼急，沒法拒絕。最壞的情況也接受",
        vi: "Ký. Bố mẹ đang gấp, không thể từ chối. Chấp nhận cả tình huống tệ nhất",
        id: "Tanda tangani. Mereka sedang genting, tidak bisa menolak. Siap terima skenario terburuk",
    }), 1),
    ],
  },
  {
    id: 2,
    question: localeMap({
      ko: "해외에서 인생 최고의 기회가 왔다. 하지만 부모님이 편찮으시고 곁에 있어달라고 하신다. 나는?",
      en: "The opportunity of a lifetime opens up abroad. But your parents are unwell and want you by their side. What do you do?",
      ja: "海外で人生最高のチャンスが来た。でも両親が体調を崩し、そばにいてほしいと言う。あなたは？",
      'zh-CN': "海外出现了人生最好的机会。但父母身体不好，希望你在身边。你会？",
      'zh-TW': "海外出現了人生最好的機會。但父母身體不好，希望你在身邊。你會？",
      vi: "Cơ hội đời đến từ nước ngoài. Nhưng bố mẹ ốm và muốn bạn ở bên. Bạn sẽ?",
      id: "Kesempatan hidup datang dari luar negeri. Tapi orang tua sakit dan minta kamu di samping mereka. Kamu?",
    }),
    options: [
      opt(localeMap({
        ko: "떠난다. 이 기회를 놓칠 수 없다. 정기적으로 방문하고 도움을 드리겠다",
        en: "Leave. I can't miss this chance. I'll visit regularly and help however I can",
        ja: "行く。このチャンスは逃せない。定期的に帰省して手伝う",
        'zh-CN': "离开。这个机会不能错过。会定期回去看望、尽力帮忙",
        'zh-TW': "離開。這個機會不能錯過。會定期回去看望、盡力幫忙",
        vi: "Đi. Không thể bỏ lỡ cơ hội này. Sẽ về thăm thường xuyên và hỗ trợ hết mình",
        id: "Pergi. Kesempatan ini tidak boleh dilewatkan. Akan pulang rutin dan membantu sebisa mungkin",
    }), 0),
      opt(localeMap({
        ko: "남는다. 부모님 곁을 지킨다. 기회는 다시 올 수 있지만 이 시간은 다시 없다",
        en: "Stay. I'll be by my parents' side. Opportunities may come again, but this time won't",
        ja: "残る。両親のそばを守る。チャンスはまた来るが、この時間は戻らない",
        'zh-CN': "留下。守在父母身边。机会还会再来，但这段时间不会重来",
        'zh-TW': "留下。守在父母身邊。機會還會再來，但這段時間不會重來",
        vi: "Ở lại. Ở bên bố mẹ. Cơ hội có thể quay lại, nhưng khoảng thời gian này thì không",
        id: "Tinggal. Menjaga orang tua. Kesempatan bisa datang lagi, tapi waktu ini tidak",
    }), 1),
    ],
  },
  {
    id: 3,
    question: localeMap({
      ko: "사랑하는 사람이 생겼는데 부모님이 절대 반대한다. 결혼하면 의절하겠다고 하신다. 나는?",
      en: "You've found someone you love, but your parents are dead set against it. They say they'll disown you if you marry. What do you do?",
      ja: "愛する人ができたが、両親は絶対反対。結婚したら縁を切ると言われた。あなたは？",
      'zh-CN': "你有了心爱的人，但父母坚决反对。他们说结婚就断绝关系。你会？",
      'zh-TW': "你有了心愛的人，但父母堅決反對。他們說結婚就斷絕關係。你會？",
      vi: "Bạn yêu ai đó nhưng bố mẹ phản đối tuyệt đối. Họ nói sẽ cắt đứt quan hệ nếu cưới. Bạn sẽ?",
      id: "Kamu jatuh cinta, tapi orang tua menolak keras. Mereka ancam putus hubungan kalau kamu menikah. Kamu?",
    }),
    options: [
      opt(localeMap({
        ko: "내 선택을 밀어붙인다. 내 인생은 내가 결정한다. 언젠간 이해하실 것이다",
        en: "Push ahead with my choice. My life is mine to decide. They'll understand someday",
        ja: "自分の選択を貫く。人生は自分で決める。いつか理解してくれる",
        'zh-CN': "坚持自己的选择。人生由我决定。他们总有一天会理解",
        'zh-TW': "堅持自己的選擇。人生由我決定。他們總有一天會理解",
        vi: "Theo quyết định của mình. Đời tôi do tôi quyết. Rồi họ sẽ hiểu",
        id: "Tetap pada pilihan sendiri. Hidupku, keputusanku. Suatu hari mereka akan mengerti",
    }), 0),
      opt(localeMap({
        ko: "포기한다. 가족과 평생 멀어지는 삶은 선택할 수 없다",
        en: "Give it up. I can't choose a life permanently estranged from my family",
        ja: "諦める。家族と一生離れた生活は選べない",
        'zh-CN': "放弃。无法选择与家人终生疏远的活法",
        'zh-TW': "放棄。無法選擇與家人終生疏遠的活法",
        vi: "Từ bỏ. Không thể chọn cuộc sống xa cách gia đình suốt đời",
        id: "Menyerah. Tidak bisa memilih hidup jauh dari keluarga selamanya",
    }), 1),
    ],
  },
  {
    id: 4,
    question: localeMap({
      ko: "형제자매가 큰돈을 빌려달라고 한다. 솔직히 못 받을 것 같다는 느낌이 강하다. 나는?",
      en: "A sibling asks to borrow a large sum. You strongly feel you won't get it back. What do you do?",
      ja: "兄弟姉妹が大金を借りたいと言う。正直、返ってこなさそうな予感が強い。あなたは？",
      'zh-CN': "兄弟姐妹要借一大笔钱。你强烈感觉很可能收不回来。你会？",
      'zh-TW': "兄弟姐妹要借一大筆錢。你強烈感覺很可能收不回來。你會？",
      vi: "Anh chị em muốn vay một khoản lớn. Bạn cảm thấy chắc là không đòi lại được. Bạn sẽ?",
      id: "Saudara minta pinjam uang besar. Kamu yakin sulit dikembalikan. Kamu?",
    }),
    options: [
      opt(localeMap({
        ko: "거절한다. 돈 문제로 가족 관계가 틀어지는 게 더 싫다. 못 받으면 상처만 남는다",
        en: "Refuse. I'd rather not ruin family ties over money. If it's not repaid, only hurt remains",
        ja: "断る。お金で家族関係が壊れる方が嫌だ。返せなければ傷だけが残る",
        'zh-CN': "拒绝。更不想因钱把家庭关系搞僵。收不回来只剩伤害",
        'zh-TW': "拒絕。更不想因錢把家庭關係搞僵。收不回來只剩傷害",
        vi: "Từ chối. Không muốn vì tiền mà hỏng quan hệ gia đình. Không đòi lại được thì chỉ còn tổn thương",
        id: "Menolak. Lebih baik tidak merusak hubungan keluarga karena uang. Kalau tidak kembali, yang tersisa hanya luka",
    }), 0),
      opt(localeMap({
        ko: "빌려준다. 가족이 힘들다는데 모른 척할 수 없다. 못 받아도 내가 감당한다",
        en: "Lend it. I can't ignore family in need. Even if I don't get it back, I'll bear it",
        ja: "貸す。家族が苦しいのに見て見ぬふりはできない。返ってこなくても自分で受け止める",
        'zh-CN': "借给他。家人有难不能装作不知道。就算收不回来我自己扛",
        'zh-TW': "借給他。家人有難不能裝作不知道。就算收不回來我自己扛",
        vi: "Cho vay. Không thể làm ngơ khi người thân khó khăn. Không đòi lại được thì tôi chịu",
        id: "Pinjamkan. Tidak bisa pura-pura tidak tahu saat keluarga susah. Kalau tidak kembali, aku yang tanggung",
    }), 1),
    ],
  },
  {
    id: 5,
    question: localeMap({
      ko: "가족 중 한 명이 충격적인 비밀을 내게만 털어놨다. 다른 가족들은 모른다. 혼자 짊어지기 너무 무겁다. 나는?",
      en: "A family member confided a shocking secret to you alone. No one else knows. It's too heavy to carry alone. What do you do?",
      ja: "家族の一人が衝撃的な秘密を自分だけに打ち明けた。他の家族は知らない。一人で背負うには重すぎる。あなたは？",
      'zh-CN': "一位家人只向你透露了惊人的秘密。其他家人都不知道。独自承担太重了。你会？",
      'zh-TW': "一位家人只向你透露了驚人的秘密。其他家人都不知道。獨自承擔太重了。你會？",
      vi: "Một người thân chỉ kể bí mật gây sốc với bạn. Người khác không biết. Gánh một mình quá nặng. Bạn sẽ?",
      id: "Seorang keluarga menceritakan rahasia mengejutkan hanya ke kamu. Yang lain tidak tahu. Terlalu berat dibawa sendiri. Kamu?",
    }),
    options: [
      opt(localeMap({
        ko: "다른 가족에게 알린다. 혼자 감당하는 건 한계가 있다. 같이 해결해야 한다",
        en: "Tell the rest of the family. There's a limit to handling it alone. We need to solve it together",
        ja: "他の家族にも伝える。一人で抱えるには限界がある。一緒に解決すべきだ",
        'zh-CN': "告诉其他家人。一个人扛有极限，必须一起解决",
        'zh-TW': "告訴其他家人。一個人扛有極限，必須一起解決",
        vi: "Nói với các thành viên khác. Một mình gánh có giới hạn. Phải cùng giải quyết",
        id: "Beritahu keluarga lain. Menanggung sendiri ada batasnya. Harus diselesaikan bersama",
    }), 0),
      opt(localeMap({
        ko: "혼자 끝까지 짊어진다. 나를 믿고 말해준 것이다. 가족을 지키는 게 먼저다",
        en: "Carry it to the end alone. They trusted me with it. Protecting the family comes first",
        ja: "最後まで一人で背負う。自分を信じて話してくれた。家族を守ることが先だ",
        'zh-CN': "独自扛到底。他们是因为信任我才说的。守护家人优先",
        'zh-TW': "獨自扛到底。他們是因為信任我才說的。守護家人優先",
        vi: "Gánh một mình đến cùng. Họ tin tưởng mới kể. Bảo vệ gia đình là trước hết",
        id: "Pikul sendiri sampai akhir. Mereka percaya padaku. Melindungi keluarga yang utama",
    }), 1),
    ],
  },
  {
    id: 6,
    question: localeMap({
      ko: "형제자매가 억울하게 공개적으로 비난받고 있다. 내가 나서면 나도 같이 공격받을 것이 뻔하다. 나는?",
      en: "Your sibling is being publicly blamed unfairly. If you step in, you'll likely be attacked too. What do you do?",
      ja: "兄弟姉妹が不当に公然と非難されている。出れば自分も攻撃されるのは明らかだ。あなたは？",
      'zh-CN': "兄弟姐妹正被公开冤枉指责。你出面的话，显然也会一起被攻击。你会？",
      'zh-TW': "兄弟姐妹正被公開冤枉指責。你出面的話，顯然也會一起被攻擊。你會？",
      vi: "Anh chị em đang bị oan công khai. Nếu bạn lên tiếng, chắc chắn cũng bị tấn công. Bạn sẽ?",
      id: "Saudara sedang diserang secara publik tanpa alasan. Kalau kamu ikut campur, kamu juga akan diserang. Kamu?",
    }),
    options: [
      opt(localeMap({
        ko: "직접 나서지 않는다. 개인 연락으로 위로한다. 공개 싸움에 끌려가는 건 다른 문제다",
        en: "Don't step in publicly. Comfort them privately. Getting dragged into a public fight is another matter",
        ja: "直接は出ない。個人的に連絡して慰める。公開の争いに巻き込まれるのは別問題だ",
        'zh-CN': "不公开出面。私下联系安慰。被卷进公开争吵是另一回事",
        'zh-TW': "不公開出面。私下聯繫安慰。被捲進公開爭吵是另一回事",
        vi: "Không lên tiếng công khai. An ủi riêng. Bị kéo vào cuộc cãi công khai là chuyện khác",
        id: "Tidak tampil di depan umum. Menghibur lewat kontak pribadi. Terseret pertengkaran publik itu urusan lain",
    }), 0),
      opt(localeMap({
        ko: "공개적으로 방어한다. 나도 같이 공격받더라도 혼자 두고 볼 수 없다",
        en: "Defend them publicly. Even if I'm attacked too, I can't leave them alone",
        ja: "公然と守る。自分も攻撃されても、一人にしておけない",
        'zh-CN': "公开辩护。就算一起被攻击，也不能袖手旁观",
        'zh-TW': "公開辯護。就算一起被攻擊，也不能袖手旁觀",
        vi: "Bảo vệ công khai. Dù cùng bị tấn công, không thể để họ một mình",
        id: "Membela secara publik. Meski ikut diserang, tidak bisa membiarkannya sendirian",
    }), 1),
    ],
  },
  {
    id: 7,
    question: localeMap({
      ko: "어릴 때부터 꿈꿔온 것이 있다. 부모님이 강하게 반대하시고 가족 중 아무도 응원하지 않는다. 나는?",
      en: "There's something you've dreamed of since childhood. Your parents strongly oppose it and no one in the family supports you. What do you do?",
      ja: "子どもの頃からの夢がある。両親は強く反対し、家族の誰も応援してくれない。あなたは？",
      'zh-CN': "你有从小到大的梦想。父母强烈反对，家里没人支持。你会？",
      'zh-TW': "你有從小到大的夢想。父母強烈反對，家裡沒人支持。你會？",
      vi: "Bạn có ước mơ từ nhỏ. Bố mẹ phản đối mạnh, không ai trong gia đình ủng hộ. Bạn sẽ?",
      id: "Ada impian sejak kecil. Orang tua menolak keras dan tidak ada keluarga yang mendukung. Kamu?",
    }),
    options: [
      opt(localeMap({
        ko: "한다. 후회하는 삶은 살 수 없다. 결과로 보여드리면 된다",
        en: "Do it. I can't live with regret. I'll prove it with results",
        ja: "やる。後悔する人生は生きられない。結果で示せばいい",
        'zh-CN': "去做。不能活在对后悔的人生里。用结果证明就好",
        'zh-TW': "去做。不能活在對後悔的人生裡。用結果證明就好",
        vi: "Làm. Không thể sống với hối tiếc. Chứng minh bằng kết quả",
        id: "Lakukan. Tidak bisa hidup penuh penyesalan. Buktikan lewat hasil",
    }), 0),
      opt(localeMap({
        ko: "포기한다. 온 가족이 반대하는 것을 혼자 밀어붙일 자신이 없다. 가족이 더 중요하다",
        en: "Give it up. I don't have the confidence to push through when the whole family is against me. Family matters more",
        ja: "諦める。家族全員に反対されながら一人で押し通す自信がない。家族の方が大切だ",
        'zh-CN': "放弃。全家都反对，我没信心独自硬撑。家人更重要",
        'zh-TW': "放棄。全家都反對，我沒信心獨自硬撐。家人更重要",
        vi: "Từ bỏ. Cả nhà phản đối, tôi không đủ tự tin để một mình cố. Gia đình quan trọng hơn",
        id: "Menyerah. Tidak punya keberanian melawan seluruh keluarga sendirian. Keluarga lebih penting",
    }), 1),
    ],
  },
  {
    id: 8,
    question: localeMap({
      ko: "부모님이 명백히 잘못된 결정을 내리고 계신다. 강하게 반대하면 크게 충돌할 것이다. 나는?",
      en: "Your parents are making a clearly wrong decision. Strong opposition will cause a major clash. What do you do?",
      ja: "両親が明らかに間違った決断をしている。強く反対すれば大きな衝突になる。あなたは？",
      'zh-CN': "父母正在做明显错误的决定。强烈反对会引发大冲突。你会？",
      'zh-TW': "父母正在做明顯錯誤的決定。強烈反對會引發大衝突。你會？",
      vi: "Bố mẹ đang đưa ra quyết định sai rõ ràng. Phản đối mạnh sẽ gây xung đột lớn. Bạn sẽ?",
      id: "Orang tua mengambil keputusan yang jelas salah. Menolak keras akan memicu bentrokan besar. Kamu?",
    }),
    options: [
      opt(localeMap({
        ko: "직접 반대 의사를 표현한다. 잘못된 결정은 막아야 한다. 충돌이 두렵지 않다",
        en: "Express opposition directly. Wrong decisions must be stopped. I'm not afraid of conflict",
        ja: "直接反対の意思を示す。間違った決断は止めるべきだ。衝突は恐れない",
        'zh-CN': "直接表达反对。错误的决定必须阻止。不怕冲突",
        'zh-TW': "直接表達反對。錯誤的決定必須阻止。不怕衝突",
        vi: "Nói thẳng sự phản đối. Quyết định sai phải ngăn lại. Không sợ xung đột",
        id: "Menyatakan penolakan langsung. Keputusan salah harus dihentikan. Tidak takut konflik",
    }), 0),
      opt(localeMap({
        ko: "따른다. 결국 부모님의 결정이다. 내가 할 일은 옆에서 지지하는 것이다",
        en: "Go along with it. It's ultimately their decision. My role is to support them from the side",
        ja: "従う。最終的には両親の決断だ。自分にできるのはそばで支えることだ",
        'zh-CN': "跟随。终究是父母的决定。我能做的是在旁边支持",
        'zh-TW': "跟隨。終究是父母的決定。我能做的是在旁邊支持",
        vi: "Theo theo. Cuối cùng vẫn là quyết định của bố mẹ. Việc của tôi là ở bên ủng hộ",
        id: "Ikuti saja. Pada akhirnya itu keputusan mereka. Tugasku mendukung dari samping",
    }), 1),
    ],
  },
  {
    id: 9,
    question: localeMap({
      ko: "형제자매가 모두 있는 가족 자리에서 분명히 틀린 말을 했다. 눈빛으로 편들어달라고 한다. 나는?",
      en: "At a family gathering, your sibling said something clearly wrong. They're giving you a look, asking you to take their side. What do you do?",
      ja: "家族が揃う場で兄弟姉妹が明らかに間違った発言をした。目配せで味方してほしいと言われている。あなたは？",
      'zh-CN': "全家都在的场合，兄弟姐妹说了明显错误的话。用眼神示意你帮腔。你会？",
      'zh-TW': "全家都在的場合，兄弟姐妹說了明顯錯誤的話。用眼神示意你幫腔。你會？",
      vi: "Trong buổi sum họp, anh chị em nói điều sai rõ ràng và nhìn bạn như muốn bạn ủng hộ. Bạn sẽ?",
      id: "Saat keluarga berkumpul, saudara bilang sesuatu yang jelas salah dan memintamu memihak lewat tatapan. Kamu?",
    }),
    options: [
      opt(localeMap({
        ko: "사실을 말한다. 가족 앞에서 틀린 건 바로잡아야 한다. 나중에 더 창피해질 수 있다",
        en: "State the facts. Wrong is wrong, even in front of family. It could get more embarrassing later",
        ja: "事実を言う。家族の前でも間違いは正すべきだ。後でより恥ずかしくなるかもしれない",
        'zh-CN': "说出事实。家人面前错了就要纠正。拖下去可能更丢脸",
        'zh-TW': "說出事實。家人面前錯了就要糾正。拖下去可能更丟臉",
        vi: "Nói sự thật. Sai thì phải sửa trước mặt gia đình. Để sau có thể càng xấu hổ",
        id: "Katakan faktanya. Di depan keluarga pun yang salah harus diperbaiki. Nanti bisa makin malu",
    }), 0),
      opt(localeMap({
        ko: "편을 든다. 가족 앞에서 망신 줄 수 없다. 나중에 따로 말하면 된다",
        en: "Take their side. I can't let them lose face in front of family. I'll talk to them privately later",
        ja: "味方する。家族の前で恥をかかせられない。後で個人的に話せばいい",
        'zh-CN': "帮腔。不能在家人面前让他丢脸。以后私下再说",
        'zh-TW': "幫腔。不能在家人面前讓他丟臉。以後私下再說",
        vi: "Ủng hộ. Không thể để họ mất mặt trước gia đình. Nói riêng sau cũng được",
        id: "Memihak. Tidak bisa membiarkannya malu di depan keluarga. Nanti bicara sendiri saja",
    }), 1),
    ],
  },
  {
    id: 10,
    question: localeMap({
      ko: "내 인생에서 가장 중요한 날(최종 면접·시험·발표)에 가족 응급상황이 생겼다. 나는?",
      en: "On the most important day of your life (final interview, exam, presentation), a family emergency happens. What do you do?",
      ja: "人生で最も重要な日（最終面接・試験・発表）に家族の緊急事態が起きた。あなたは？",
      'zh-CN': "在你人生最重要的日子（最终面试、考试、发表）时，家里出了紧急情况。你会？",
      'zh-TW': "在你人生最重要的日子（最終面試、考試、發表）時，家裡出了緊急情況。你會？",
      vi: "Vào ngày quan trọng nhất đời bạn (phỏng vấn cuối, thi, thuyết trình), gia đình có tình huống khẩn cấp. Bạn sẽ?",
      id: "Di hari terpenting hidupmu (wawancara final, ujian, presentasi), keluarga mengalami darurat. Kamu?",
    }),
    options: [
      opt(localeMap({
        ko: "내 일을 마치고 달려간다. 내가 살아야 가족도 더 잘 도울 수 있다",
        en: "Finish my commitment first, then rush over. I need to stand on my own feet to help my family better",
        ja: "自分の用事を終えてから駆けつける。自分が立たなければ家族をよりよく助けられない",
        'zh-CN': "先完成自己的事再赶过去。我得先站稳，才能更好地帮家人",
        'zh-TW': "先完成自己的事再趕過去。我得先站穩，才能更好地幫家人",
        vi: "Hoàn thành việc của mình rồi chạy đến. Phải ổn định bản thân mới giúp gia đình tốt hơn",
        id: "Selesaikan urusanku dulu, baru buru-buru datang. Aku harus kuat dulu agar bisa membantu keluarga lebih baik",
    }), 0),
      opt(localeMap({
        ko: "즉시 달려간다. 내 일보다 가족이 먼저다. 기회는 다시 온다",
        en: "Rush over immediately. Family comes before my work. Opportunities will come again",
        ja: "すぐに駆けつける。自分の用事より家族が先だ。チャンスはまた来る",
        'zh-CN': "立刻赶过去。家人比我的事优先。机会还会再来",
        'zh-TW': "立刻趕過去。家人比我的事優先。機會還會再來",
        vi: "Chạy ngay. Gia đình trước, việc của tôi sau. Cơ hội sẽ quay lại",
        id: "Langsung datang. Keluarga dulu, urusanku belakangan. Kesempatan akan datang lagi",
    }), 1),
    ],
  },
  {
    id: 11,
    question: localeMap({
      ko: "오랫동안 나를 이용해왔다는 걸 알게 된 가족이 있다. 다른 가족들은 아직 모른다. 나는?",
      en: "You realize a family member has been taking advantage of you for a long time. The others don't know yet. What do you do?",
      ja: "長い間自分を利用してきた家族がいると気づいた。他の家族はまだ知らない。あなたは？",
      'zh-CN': "你发现有位家人长期利用你。其他家人还不知道。你会？",
      'zh-TW': "你發現有位家人長期利用你。其他家人還不知道。你會？",
      vi: "Bạn phát hiện một người thân đã lợi dụng bạn lâu rồi. Người khác chưa biết. Bạn sẽ?",
      id: "Kamu sadar ada keluarga yang sudah lama memanfaatkanmu. Yang lain belum tahu. Kamu?",
    }),
    options: [
      opt(localeMap({
        ko: "관계를 정리하고 다른 가족들에게도 알린다. 가족이어도 이건 아니다",
        en: "Cut ties and tell the rest of the family. Even family can't get away with this",
        ja: "関係を整理し、他の家族にも伝える。家族だからといってこれは許せない",
        'zh-CN': "理清关系并告诉其他家人。就算是家人也不行",
        'zh-TW': "理清關係並告訴其他家人。就算是家人也不行",
        vi: "Chấm dứt quan hệ và nói với các thành viên khác. Dù là người thân cũng không được",
        id: "Akhiri hubungan dan beritahu keluarga lain. Meski keluarga, ini tidak bisa diterima",
    }), 0),
      opt(localeMap({
        ko: "가족들에겐 알리지 않고 그 사람과 조용히 거리를 둔다. 가족 전체가 흔들리는 건 막아야 한다",
        en: "Keep it from the others and quietly distance myself from that person. I must stop the whole family from being shaken",
        ja: "家族には伝えず、その人と静かに距離を置く。家族全体が揺らぐのは防がなければならない",
        'zh-CN': "不告诉其他家人，与那人悄悄保持距离。必须阻止整个家庭动摇",
        'zh-TW': "不告訴其他家人，與那人悄悄保持距離。必須阻止整個家庭動搖",
        vi: "Không nói với người khác, âm thầm giữ khoảng cách. Phải ngăn cả gia đình bị lay chuyển",
        id: "Jangan beritahu yang lain, jarakkan diri diam-diam. Jangan biarkan seluruh keluarga goyah",
    }), 1),
    ],
  },
  {
    id: 12,
    question: localeMap({
      ko: "평생 내 편이라 믿었던 가족이 나의 가장 큰 비밀을 다른 가족들에게 퍼뜨렸다. 진심으로 사과했다. 나는?",
      en: "A family member you trusted completely spread your biggest secret to others. They apologized sincerely. What do you do?",
      ja: "生涯自分の味方だと信じていた家族が、最大の秘密を他の家族に漏らした。心から謝ってきた。あなたは？",
      'zh-CN': "你一辈子都相信会站在你这边的家人，把你的最大秘密告诉了其他家人。他们真诚道歉了。你会？",
      'zh-TW': "你一輩子都相信會站在你這邊的家人，把你的最大秘密告訴了其他家人。他們真誠道歉了。你會？",
      vi: "Người thân bạn tin cả đời đã tiết lộ bí mật lớn nhất cho người khác. Họ đã xin lỗi chân thành. Bạn sẽ?",
      id: "Keluarga yang selama ini kamu percaya membocorkan rahasia terbesarmu ke yang lain. Mereka minta maaf tulus. Kamu?",
    }),
    options: [
      opt(localeMap({
        ko: "관계를 정리한다. 신뢰가 깨지면 끝이다. 가족이어도 마찬가지다",
        en: "End the relationship. Once trust is broken, it's over—even with family",
        ja: "関係を終える。信頼が壊れたら終わりだ。家族でも同じだ",
        'zh-CN': "结束关系。信任一旦破裂就完了，家人也一样",
        'zh-TW': "結束關係。信任一旦破裂就完了，家人也一樣",
        vi: "Chấm dứt quan hệ. Tin cậy vỡ là hết. Dù là người thân cũng vậy",
        id: "Akhiri hubungan. Kepercayaan rusak berarti selesai. Meski keluarga pun sama",
    }), 0),
      opt(localeMap({
        ko: "용서하고 이어간다. 가족이기 때문에 포기할 수 없다. 상처받았지만 관계를 지킨다",
        en: "Forgive and continue. I can't give up on them because they're family. It hurt, but I'll keep the relationship",
        ja: "許して続ける。家族だから諦められない。傷ついたが関係を守る",
        'zh-CN': "原谅并继续。因为是家人所以不能放弃。虽然受伤，但要守住关系",
        'zh-TW': "原諒並繼續。因為是家人所以不能放棄。雖然受傷，但要守住關係",
        vi: "Tha thứ và tiếp tục. Vì là gia đình nên không thể buông. Tổn thương nhưng vẫn giữ quan hệ",
        id: "Maafkan dan lanjutkan. Karena keluarga, tidak bisa menyerah. Terluka, tapi hubungan tetap dijaga",
    }), 1),
    ],
  },
];

export const phase3FamilyBalanceGameResults: Phase3FamilyBalanceGameResult[] = [
  {
    type: 'Type1',
    emoji: '🧊',
    title: localeMap({
      ko: "가족도 개인이고 나도 개인인 사람, 냉철 독립형",
      en: "Family Are Individuals and So Am I — Cool Independent Type",
      ja: "家族も個人、自分も個人 — 冷静な独立型",
      'zh-CN': "家人是独立的，我也是独立的——冷静独立型",
      'zh-TW': "家人是獨立的，我也是獨立的——冷靜獨立型",
      vi: "Gia đình là cá nhân, tôi cũng là cá nhân — Kiểu độc lập lạnh lùng",
      id: "Keluarga pun individu, aku pun individu — Tipe independen dingin",
    }),
    shortDescription: localeMap({
      ko: "당신은 가족이라는 이유만으로 무조건 희생하지 않습니다. 가족도 건강한 경계가 있어야 한다고 믿습니다.",
      en: "You don't sacrifice unconditionally just because they're family. You believe even family needs healthy boundaries.",
      ja: "家族だからといって無条件に犠牲にはならない。家族にも健全な境界線が必要だと信じている。",
      'zh-CN': "你不会只因为对方是家人就无条件牺牲。你相信家人之间也需要健康的边界。",
      'zh-TW': "你不會只因為對方是家人就無條件犧牲。你相信家人之間也需要健康的界線。",
      vi: "Bạn không hy sinh vô điều kiện chỉ vì họ là gia đình. Bạn tin rằng gia đình cũng cần ranh giới lành mạnh.",
      id: "Kamu tidak berkorban tanpa syarat hanya karena mereka keluarga. Kamu percaya keluarga pun butuh batas yang sehat.",
    }),
    description: localeMap({
      ko: "빚보증도 거절하고 꿈을 밀어붙이며 틀린 것은 틀리다고 말합니다. 이것이 냉정한 게 아닙니다. 가족 관계에서도 나 자신을 잃지 않는 것이 이 유형의 방식입니다.\n\n이 유형의 강점: 가족의 요구에 휩쓸리지 않아 자신을 지킬 수 있음. 쓴소리를 할 수 있는 가족 구성원\n\n한 줄 평: 가족이라는 이유로 모든 것을 감수해야 한다는 공식은 없습니다. 건강한 경계를 가진 당신이 결국 가족 관계를 더 오래 지속시킵니다",
      en: "You refuse co-signing, push for your dreams, and call out what's wrong. That isn't coldness—it's how you stay yourself even within family.\n\nStrengths of This Type: You don't get swept up by family demands and can protect yourself. You're the member who can speak hard truths.\n\nOne-liner: There's no rule that family means giving up everything. Your healthy boundaries are what keep family ties lasting longer.",
      ja: "連帯保証も断り、夢を押し通し、間違いは間違いだと言う。これは冷たさではない。家族関係の中でも自分を失わないのがこのタイプのやり方だ。\n\nこのタイプの強み: 家族の要求に流されず自分を守れる。厳しいことも言える家族の一員。\n\n一言評価: 家族だからすべてを受け入れなければならない公式はない。健全な境界線を持つあなたが、家族関係をより長く続けさせる。",
      'zh-CN': "你会拒绝担保、坚持梦想，错了就会直说。这不是冷漠，而是在家庭关系里也不失去自我的方式。\n\n这种类型的优势: 不会被家人的要求裹挟，能保护自己。也是家里敢说真话的人。\n\n一句话点评: 没有“因为是家人就必须承受一切”的公式。有健康边界的你，反而能让家庭关系走得更久。",
      'zh-TW': "你會拒絕擔保、堅持夢想，錯了就會直說。這不是冷漠，而是在家庭關係裡也不失去自我的方式。\n\n這種類型的優勢: 不會被家人的要求裹挾，能保護自己。也是家裡敢說真話的人。\n\n一句話點評: 沒有「因為是家人就必須承受一切」的公式。有健康界線的你，反而能讓家庭關係走得更久。",
      vi: "Bạn từ chối bảo lãnh, theo đuổi ước mơ, và nói thẳng khi sai. Đó không phải lạnh lùng — đó là cách bạn không đánh mất bản thân trong gia đình.\n\nĐiểm mạnh của kiểu này: Không bị cuốn theo yêu cầu gia đình và có thể bảo vệ bản thân. Là người dám nói lời thật trong nhà.\n\nNhận xét một câu: Không có công thức nào bắt bạn chấp nhận mọi thứ chỉ vì là gia đình. Ranh giới lành mạnh của bạn mới giúp quan hệ gia đình bền lâu.",
      id: "Kamu menolak jadi penjamin, mendorong impian, dan mengatakan yang salah memang salah. Ini bukan dingin — ini cara kamu tetap menjadi dirimu dalam keluarga.\n\nKelebihan tipe ini: Tidak tersapu tuntutan keluarga dan bisa melindungi diri. Anggota keluarga yang berani bicara jujur.\n\nSatu kalimat: Tidak ada rumus bahwa karena keluarga kamu harus menerima segalanya. Batas sehatmu justru membuat hubungan keluarga lebih tahan lama.",
    }),
    empathyLevel: localeMap({
      ko: "냉철 독립형 🧊",
      en: "Cool Independent Type 🧊",
      ja: "冷静な独立型 🧊",
      'zh-CN': "冷静独立型 🧊",
      'zh-TW': "冷靜獨立型 🧊",
      vi: "Kiểu độc lập lạnh lùng 🧊",
      id: "Tipe independen dingin 🧊",
    }),
    characteristics: localeMap({
      ko: "경계·독립·현실·이성·자기 보호",
      en: "Boundaries · Independence · Reality · Reason · Self-protection",
      ja: "境界 · 独立 · 現実 · 理性 · 自己防衛",
      'zh-CN': "边界·独立·现实·理性·自我保护",
      'zh-TW': "界線·獨立·現實·理性·自我保護",
      vi: "Ranh giới · Độc lập · Thực tế · Lý trí · Tự bảo vệ",
      id: "Batas · Independen · Realitas · Rasional · Perlindungan diri",
    }),
    goodMatch: localeMap({
      ko: "\"넌 왜 이렇게 냉정해\", \"근데 결국 네 말이 맞더라\"",
      en: "\"Why are you so cold?\" \"But in the end, you were right.\"",
      ja: "「なんでそんなに冷静なの」「でも結局、君の言う通りだった」",
      'zh-CN': "“你怎么这么冷静”“但最后还是你是对的”",
      'zh-TW': "「你怎麼這麼冷靜」「但到最後還是你說得對」",
      vi: "\"Sao mày lạnh lùng thế?\" \"Nhưng cuối cùng mày đúng.\"",
      id: "\"Kok kamu dingin banget?\" \"Tapi akhirnya kamu yang benar.\"",
    }),
    badMatch: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    certificationPhrase: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    shareLine: localeMap({
      ko: "가족 극한 밸런스 결과: 냉철 독립형 🧊 부모님 빚보증 거절... 가족이어도 선이 있다는 거 맞음 → 가족 단톡방에 공유해봐 반응 봐야함 ㅋㅋ",
      en: "Family Extreme Balance result: Cool Independent Type 🧊 Refused to co-sign for my parents... even family has limits → share in the family chat and watch the reactions lol",
      ja: "家族極限バランス結果：冷静な独立型 🧊 親の連帯保証を断った…家族でも線はある → 家族グループに共有して反応見よう 笑",
      'zh-CN': "家庭极限平衡结果：冷静独立型 🧊 拒绝给父母担保…家人也有底线 → 发到家庭群看反应 哈哈",
      'zh-TW': "家庭極限平衡結果：冷靜獨立型 🧊 拒絕給父母擔保…家人也有底線 → 發到家庭群看反應 哈哈",
      vi: "Kết quả cân bằng gia đình cực hạn: Kiểu độc lập lạnh lùng 🧊 Từ chối bảo lãnh cho bố mẹ... gia đình cũng có ranh giới → chia sẻ vào nhóm gia đình xem phản ứng nhé haha",
      id: "Hasil balance game keluarga ekstrem: Tipe independen dingin 🧊 Menolak jadi penjamin orang tua... keluarga pun punya batas → share di grup keluarga lihat reaksinya lol",
    }),
  },
  {
    type: 'Type2',
    emoji: '🔍',
    title: localeMap({
      ko: "대부분 현실적이지만 결정적 순간엔 움직이는 사람, 이성 우선형",
      en: "Mostly Practical, But Moves at Decisive Moments — Reason-First Type",
      ja: "大抵は現実的だが決定的な瞬間に動く人 — 理性優先型",
      'zh-CN': "大多现实，但在关键时刻会行动——理性优先型",
      'zh-TW': "大多現實，但在關鍵時刻會行動——理性優先型",
      vi: "Phần lớn thực tế, nhưng hành động ở khoảnh khắc then chốt — Kiểu ưu tiên lý trí",
      id: "Kebanyakan realistis, tapi bergerak di momen krusial — Tipe rasional dulu",
    }),
    shortDescription: localeMap({
      ko: "당신은 대부분의 상황에서 현명한 선택을 합니다. 하지만 특정 가족, 특정 상황 앞에서는 이성이 아닌 마음이 먼저 움직입니다.",
      en: "In most situations you choose wisely. But with certain family members and moments, your heart moves before your head.",
      ja: "大抵の状況では賢い選択をする。でも特定の家族、特定の場面では理性より心が先に動く。",
      'zh-CN': "你在大多数情况下会做出明智的选择。但在特定的家人和情境前，心会比理性先动。",
      'zh-TW': "你在大多數情況下會做出明智的選擇。但在特定的家人和情境前，心會比理性先動。",
      vi: "Hầu hết tình huống bạn chọn khôn ngoan. Nhưng trước một số người thân và hoàn cảnh, trái tim đi trước lý trí.",
      id: "Di kebanyakan situasi kamu memilih dengan bijak. Tapi di hadapan keluarga atau momen tertentu, hati bergerak lebih dulu dari rasio.",
    }),
    description: localeMap({
      ko: "대부분 나를 지키지만 가족이 정말 힘든 순간엔 예상 밖의 선택을 하기도 합니다. 의리가 없는 게 아니라 의리를 쓸 타이밍을 아는 타입입니다.\n\n이 유형의 강점: 무분별한 희생 없이 관계를 오래 유지함. 진짜 필요한 순간에 나타나는 헌신\n\n한 줄 평: 당신의 헌신은 조용하지만 필요한 순간 정확하게 나타납니다. 그래서 더 믿음직합니다",
      en: "Most of the time you protect yourself, but when family is truly in crisis you sometimes make unexpected choices. It's not a lack of loyalty—you know when to spend it.\n\nStrengths of This Type: You sustain relationships without reckless sacrifice. Your devotion shows up exactly when it's truly needed.\n\nOne-liner: Your devotion is quiet, but it appears precisely when needed. That's why it's more trustworthy.",
      ja: "大抵は自分を守るが、家族が本当に苦しい瞬間には予想外の選択をすることもある。義理がないのではなく、義理を使うタイミングを知っているタイプだ。\n\nこのタイプの強み: 無分別な犠牲なしに関係を長く保てる。本当に必要な瞬間に現れる献身。\n\n一言評価: あなたの献身は静かだが、必要な瞬間に正確に現れる。だからこそより信頼できる。",
      'zh-CN': "大多数时候你会保全自己，但家人真正艰难时也会做出出乎意料的选择。不是没有义气，而是知道什么时候该用。\n\n这种类型的优势: 能在不盲目牺牲的情况下长久维持关系。在真正需要的时刻出现。\n\n一句话点评: 你的付出很安静，但在需要的时刻会准确出现。所以更让人信赖。",
      'zh-TW': "大多數時候你會保全自己，但家人真正艱難時也會做出出乎意料的選擇。不是沒有義氣，而是知道什麼時候該用。\n\n這種類型的優勢: 能在不盲目犧牲的情況下長久維持關係。在真正需要的時刻出現。\n\n一句話點評: 你的付出很安靜，但在需要的時刻會準確出現。所以更讓人信賴。",
      vi: "Phần lớn bạn bảo vệ bản thân, nhưng khi gia đình thực sự khó khăn đôi khi bạn chọn bất ngờ. Không phải thiếu nghĩa khí — bạn biết khi nào nên dùng.\n\nĐiểm mạnh của kiểu này: Duy trì quan hệ lâu dài mà không hy sinh mù quáng. Sự hi sinh xuất hiện đúng lúc thật sự cần.\n\nNhận xét một câu: Sự hi sinh của bạn lặng lẽ, nhưng xuất hiện chính xác khi cần. Vì vậy đáng tin hơn.",
      id: "Kebanyakan kamu melindungi diri, tapi saat keluarga benar-benar susah kadang pilihanmu mengejutkan. Bukan kurang loyal — kamu tahu kapan harus menggunakannya.\n\nKelebihan tipe ini: Menjaga hubungan lama tanpa korban sembarangan. Pengabdian muncul tepat saat benar-benar dibutuhkan.\n\nSatu kalimat: Pengabdianmu tenang, tapi muncul tepat saat dibutuhkan. Makanya lebih dipercaya.",
    }),
    empathyLevel: localeMap({
      ko: "이성 우선형 🔍",
      en: "Reason-First Type 🔍",
      ja: "理性優先型 🔍",
      'zh-CN': "理性优先型 🔍",
      'zh-TW': "理性優先型 🔍",
      vi: "Kiểu ưu tiên lý trí 🔍",
      id: "Tipe rasional dulu 🔍",
    }),
    characteristics: localeMap({
      ko: "이성·선택적 헌신·상황 판단·가끔 충동",
      en: "Reason · Selective devotion · Situational judgment · Occasional impulse",
      ja: "理性 · 選択的献身 · 状況判断 · たまの衝動",
      'zh-CN': "理性·选择性付出·情境判断·偶尔冲动",
      'zh-TW': "理性·選擇性付出·情境判斷·偶爾衝動",
      vi: "Lý trí · Hi sinh có chọn lọc · Phán đoán tình huống · Đôi khi bốc đồng",
      id: "Rasional · Pengabdian selektif · Penilaian situasi · Kadang impulsif",
    }),
    goodMatch: localeMap({
      ko: "\"넌 냉정한 줄 알았는데 이런 면이 있었어?\"",
      en: "\"I thought you were cold—who knew you had this side?\"",
      ja: "「冷静な人だと思ってたけど、こんな一面があったの？」",
      'zh-CN': "“还以为你很冷静，原来还有这一面？”",
      'zh-TW': "「還以為你很冷靜，原來還有這一面？」",
      vi: "\"Tưởng mày lạnh lùng, ai ngờ lại có mặt này?\"",
      id: "\"Kukira kamu dingin—ternyata ada sisi seperti ini?\"",
    }),
    badMatch: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    certificationPhrase: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    shareLine: localeMap({
      ko: "가족 극한 밸런스 결과: 이성 우선형 🔍 대부분 현실 선택인데 몇 개는 튀어나옴... 가족 앞에서만 나오는 의리가 있는 것 같음 ㅋㅋ → 가족이랑 비교해봐",
      en: "Family Extreme Balance result: Reason-First Type 🔍 Mostly practical picks, but a few wild ones... seems like loyalty only shows up around family lol → compare with yours",
      ja: "家族極限バランス結果：理性優先型 🔍 だいたい現実的な選択なのにいくつか外れる…家族の前だけ出る義理があるっぽい 笑 → 家族と比べてみて",
      'zh-CN': "家庭极限平衡结果：理性优先型 🔍 大多现实选择，但有几个很跳…好像只在家人面前才讲义气 哈哈 → 和家人比比",
      'zh-TW': "家庭極限平衡結果：理性優先型 🔍 大多現實選擇，但有幾個很跳…好像只在家人面前才講義氣 哈哈 → 和家人比比",
      vi: "Kết quả cân bằng gia đình cực hạn: Kiểu ưu tiên lý trí 🔍 Phần lớn chọn thực tế nhưng vài cái lạ... hình như chỉ nghĩa khí với gia đình haha → so với gia đình đi",
      id: "Hasil balance game keluarga ekstrem: Tipe rasional dulu 🔍 Kebanyakan pilihan realistis, tapi ada yang aneh... kayanya loyalitas cuma keluar di depan keluarga lol → bandingkan dengan keluargamu",
    }),
  },
  {
    type: 'Type3',
    emoji: '⚖️',
    title: localeMap({
      ko: "상황 따라 판단하는 사람, 균형 가족형",
      en: "Judges by Situation — Balanced Family Type",
      ja: "状況で判断する人 — バランス家族型",
      'zh-CN': "看情况判断的人——平衡家庭型",
      'zh-TW': "看情況判斷的人——平衡家庭型",
      vi: "Người phán đoán theo tình huống — Kiểu gia đình cân bằng",
      id: "Orang yang menilai menurut situasi — Tipe keluarga seimbang",
    }),
    shortDescription: localeMap({
      ko: "당신은 모든 상황에 같은 답을 내놓지 않습니다. 어떤 가족인지, 어떤 상황인지에 따라 달라집니다.",
      en: "You don't give the same answer to every situation. It depends on which family member and what the context is.",
      ja: "すべての状況に同じ答えを出さない。どの家族か、どんな状況かで変わる。",
      'zh-CN': "你不会对所有情况给出同样的答案。会因是哪位家人、什么情境而不同。",
      'zh-TW': "你不會對所有情況給出同樣的答案。會因是哪位家人、什麼情境而不同。",
      vi: "Bạn không trả lời giống nhau cho mọi tình huống. Tùy người thân nào và hoàn cảnh ra sao.",
      id: "Kamu tidak memberi jawaban sama untuk setiap situasi. Bergantung siapa keluarganya dan konteksnya.",
    }),
    description: localeMap({
      ko: "어떤 상황에서는 나 편, 어떤 상황에서는 가족 편. 이것이 일관성이 없는 게 아닙니다. 모든 상황이 다르다는 걸 아는 사람의 방식입니다. 12라운드 내내 한쪽으로 치우치지 않았다는 것이 가장 균형 잡힌 가족 감각의 증거입니다.\n\n이 유형의 강점: 어떤 가족 구성원과도 잘 맞음. 극단적 선택보다 맥락을 보는 능력\n\n한 줄 평: 균형은 무관심이 아닙니다. 상황을 제대로 보는 사람만이 가족 안에서 균형을 유지할 수 있습니다",
      en: "Sometimes you're on your own side, sometimes on family's. That's not inconsistency—it's how someone who knows every situation is different operates. Not leaning one way through all 12 rounds is proof of your balanced family sense.\n\nStrengths of This Type: You get along with any family member. You read context rather than making extreme choices.\n\nOne-liner: Balance isn't indifference. Only those who truly read the situation can keep balance within family.",
      ja: "状況によっては自分側、状況によっては家族側。一貫性がないのではない。すべての状況が違うと知っている人のやり方だ。12ラウンドずっと一方に偏らなかったことが、最もバランスの取れた家族感覚の証拠だ。\n\nこのタイプの強み: どの家族ともうまくやれる。極端な選択より文脈を見る力がある。\n\n一言評価: バランスは無関心ではない。状況をきちんと見る人だけが家族の中でバランスを保てる。",
      'zh-CN': "有些情况站自己这边，有些站家人这边。这不是不一致，而是懂得每种情况都不同的人的做法。12轮都没有偏向一边，正是最平衡的家庭感证明。\n\n这种类型的优势: 和任何家人都处得来。比起极端选择，更擅长看情境。\n\n一句话点评: 平衡不是冷漠。只有真正看懂情境的人，才能在家庭中维持平衡。",
      'zh-TW': "有些情況站自己這邊，有些站家人這邊。這不是不一致，而是懂得每種情況都不同的人的做法。12輪都沒有偏向一邊，正是最平衡的家庭感證明。\n\n這種類型的優勢: 和任何家人都處得來。比起極端選擇，更擅長看情境。\n\n一句話點評: 平衡不是冷漠。只有真正看懂情境的人，才能在家庭中維持平衡。",
      vi: "Có lúc đứng về phía mình, có lúc về phía gia đình. Không phải thiếu nhất quán — đó là cách của người biết mỗi tình huống đều khác. 12 vòng không nghiêng về một phía là bằng chứng cho cảm giác gia đình cân bằng nhất.\n\nĐiểm mạnh của kiểu này: Hòa hợp với bất kỳ thành viên nào. Biết đọc bối cảnh hơn là chọn cực đoan.\n\nNhận xét một câu: Cân bằng không phải thờ ơ. Chỉ người nhìn đúng tình huống mới giữ được cân bằng trong gia đình.",
      id: "Kadang memihak diri sendiri, kadang keluarga. Bukan inkonsisten — ini cara orang yang tahu setiap situasi berbeda. Tidak condong ke satu sisi selama 12 ronde adalah bukti rasa keluarga paling seimbang.\n\nKelebihan tipe ini: Cocok dengan anggota keluarga mana pun. Lebih pandai membaca konteks daripada pilihan ekstrem.\n\nSatu kalimat: Keseimbangan bukan berarti acuh tak acuh. Hanya yang benar-benar membaca situasi bisa menjaga keseimbangan dalam keluarga.",
    }),
    empathyLevel: localeMap({
      ko: "균형 가족형 ⚖️",
      en: "Balanced Family Type ⚖️",
      ja: "バランス家族型 ⚖️",
      'zh-CN': "平衡家庭型 ⚖️",
      'zh-TW': "平衡家庭型 ⚖️",
      vi: "Kiểu gia đình cân bằng ⚖️",
      id: "Tipe keluarga seimbang ⚖️",
    }),
    characteristics: localeMap({
      ko: "균형·맥락·유연함·상황 판단",
      en: "Balance · Context · Flexibility · Situational judgment",
      ja: "バランス · 文脈 · 柔軟さ · 状況判断",
      'zh-CN': "平衡·情境·灵活·判断局势",
      'zh-TW': "平衡·情境·靈活·判斷局勢",
      vi: "Cân bằng · Bối cảnh · Linh hoạt · Phán đoán tình huống",
      id: "Keseimbangan · Konteks · Fleksibilitas · Penilaian situasi",
    }),
    goodMatch: localeMap({
      ko: "\"넌 어떻게 이렇게 상황을 잘 읽어?\"",
      en: "\"How do you read situations so well?\"",
      ja: "「どうしてそんなに状況を読めるの？」",
      'zh-CN': "“你怎么这么会看情况？”",
      'zh-TW': "「你怎麼這麼會看情況？」",
      vi: "\"Sao mày đọc tình huống giỏi thế?\"",
      id: "\"Kok kamu bisa baca situasi sebaik itu?\"",
    }),
    badMatch: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    certificationPhrase: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    shareLine: localeMap({
      ko: "가족 극한 밸런스 결과: 균형 가족형 ⚖️ 딱 반반 나옴... 상황마다 다르다는 거 이래서 맞는 말 → 어떻게 그걸 골랐어?! 가족 단톡방 공유해봐",
      en: "Family Extreme Balance result: Balanced Family Type ⚖️ Split right down the middle... 'it depends' really is true → how did you pick THAT?! share in the family chat",
      ja: "家族極限バランス結果：バランス家族型 ⚖️ ちょうど半分半分…状況で違うってこういうこと → なんでそれ選んだの?! 家族グループに共有して",
      'zh-CN': "家庭极限平衡结果：平衡家庭型 ⚖️ 刚好一半一半…“看情况”原来是真的 → 你怎么选那个的?! 发到家庭群",
      'zh-TW': "家庭極限平衡結果：平衡家庭型 ⚖️ 剛好一半一半…「看情況」原來是真的 → 你怎麼選那個的?! 發到家庭群",
      vi: "Kết quả cân bằng gia đình cực hạn: Kiểu gia đình cân bằng ⚖️ Đúng nửa nửa... 'tùy tình huống' là có thật → sao mày chọn cái đó?! chia sẻ vào nhóm gia đình",
      id: "Hasil balance game keluarga ekstrem: Tipe keluarga seimbang ⚖️ Persis setengah-setengah... 'tergantung situasi' memang bener → kok kamu pilih ITU?! share di grup keluarga",
    }),
  },
  {
    type: 'Type4',
    emoji: '🏠',
    title: localeMap({
      ko: "가족을 위해 기꺼이 손해 보는 사람, 가족 우선형",
      en: "Willing to Take the Loss for Family — Family-First Type",
      ja: "家族のために惜しまず損する人 — 家族優先型",
      'zh-CN': "愿意为家人吃亏的人——家庭优先型",
      'zh-TW': "願意為家人吃虧的人——家庭優先型",
      vi: "Người sẵn sàng chịu thiệt vì gia đình — Kiểu ưu tiên gia đình",
      id: "Orang yang rela rugi demi keluarga — Tipe keluarga dulu",
    }),
    shortDescription: localeMap({
      ko: "당신은 가족을 위한 선택이 내 것을 내려놓는 것이어도 감당합니다. 그게 당신의 가족 방식입니다.",
      en: "You can handle choices for family even when they mean giving up something of your own. That's your way with family.",
      ja: "家族のための選択が自分のものを手放すことでも受け止められる。それがあなたの家族のやり方だ。",
      'zh-CN': "你为家人做的选择，即使要放下自己的东西，你也承受得住。这就是你的家庭方式。",
      'zh-TW': "你為家人做的選擇，即使要放下自己的東西，你也承受得住。這就是你的家庭方式。",
      vi: "Bạn chấp nhận lựa chọn vì gia đình dù phải buông bỏ thứ của riêng mình. Đó là cách bạn với gia đình.",
      id: "Kamu sanggup pilihan demi keluarga meski harus melepaskan sesuatu milikmu. Itu cara keluargamu.",
    }),
    description: localeMap({
      ko: "해외 기회를 포기하고 빚보증을 서며 가족이 공격받으면 앞에 나섭니다. 이 선택들이 모여 가족 안에서 가장 믿음직한 존재가 되는 유형입니다.\n\n이 유형의 강점: 가족이 힘들 때 가장 먼저 생각나는 사람. 장기적으로 가족 안에서 중심 역할\n\n한 줄 평: 당신이 선택한 그 희생들이 가족을 단단하게 묶어줍니다. 당신이 있어서 이 가족이 버틴 순간들이 있습니다",
      en: "You pass up opportunities abroad, co-sign loans, and step forward when family is attacked. These choices make you the most dependable person in the family.\n\nStrengths of This Type: You're the first person family thinks of in hard times. Over the long run, you're the anchor at the center.\n\nOne-liner: The sacrifices you chose hold the family together. There are moments this family endured because you were there.",
      ja: "海外のチャンスを断り、連帯保証をし、家族が攻撃されれば前に出る。こうした選択が重なり、家族の中で最も頼れる存在になるタイプだ。\n\nこのタイプの強み: 家族が苦しいとき真っ先に思い浮かぶ人。長期的に家族の中心的存在。\n\n一言評価: あなたが選んだ犠牲が家族を強く結びつける。あなたがいたからこの家族が乗り越えた瞬間がある。",
      'zh-CN': "你会放弃海外机会、作担保，家人被攻击时也会站出来。这些选择让你成为家里最可靠的人。\n\n这种类型的优势: 家人困难时第一个被想到的人。长期里是家庭的核心。\n\n一句话点评: 你选择的那些牺牲把家人紧紧绑在一起。这个家庭能撑过来，是因为有你在。",
      'zh-TW': "你會放棄海外機會、作擔保，家人被攻擊時也會站出來。這些選擇讓你成為家裡最可靠的人。\n\n這種類型的優勢: 家人困難時第一個被想到的人。長期裡是家庭的核心。\n\n一句話點評: 你選擇的那些犧牲把家人緊緊綁在一起。這個家庭能撐過來，是因為有你在。",
      vi: "Bạn từ bỏ cơ hội nước ngoài, bảo lãnh, và đứng ra khi gia đình bị tấn công. Những lựa chọn này khiến bạn là người đáng tin nhất trong nhà.\n\nĐiểm mạnh của kiểu này: Người gia đình nghĩ đến đầu tiên khi khó khăn. Về lâu dài là trụ cột của gia đình.\n\nNhận xét một câu: Những hy sinh bạn chọn gắn chặt gia đình lại. Có những khoảnh khắc gia đình này vượt qua được vì có bạn.",
      id: "Kamu melewatkan kesempatan luar negeri, jadi penjamin, dan maju saat keluarga diserang. Pilihan-pilihan ini membuatmu yang paling diandalkan dalam keluarga.\n\nKelebihan tipe ini: Orang pertama yang dipikirkan keluarga saat susah. Jangka panjang, kamu pusat keluarga.\n\nSatu kalimat: Pengorbanan yang kamu pilih mengikat keluarga erat. Ada momen keluarga ini bertahan karena kamu ada.",
    }),
    empathyLevel: localeMap({
      ko: "가족 우선형 🏠",
      en: "Family-First Type 🏠",
      ja: "家族優先型 🏠",
      'zh-CN': "家庭优先型 🏠",
      'zh-TW': "家庭優先型 🏠",
      vi: "Kiểu ưu tiên gia đình 🏠",
      id: "Tipe keluarga dulu 🏠",
    }),
    characteristics: localeMap({
      ko: "헌신·희생·가족 우선·든든함·신뢰",
      en: "Devotion · Sacrifice · Family first · Reliability · Trust",
      ja: "献身 · 犠牲 · 家族優先 · 頼もしさ · 信頼",
      'zh-CN': "奉献·牺牲·家庭优先·可靠·信任",
      'zh-TW': "奉獻·犧牲·家庭優先·可靠·信任",
      vi: "Hi sinh · Tận tụy · Gia đình trước · Vững chắc · Tin cậy",
      id: "Pengabdian · Pengorbanan · Keluarga dulu · Tangguh · Kepercayaan",
    }),
    goodMatch: localeMap({
      ko: "\"우리한테 이렇게 해준 사람은 너뿐이야\"",
      en: "\"You're the only one who's done this much for us\"",
      ja: "「ここまでしてくれたのは君だけだよ」",
      'zh-CN': "“为我们做到这样的，只有你”",
      'zh-TW': "「為我們做到這樣的，只有你」",
      vi: "\"Chỉ có mày làm được nhiều thế này cho bọn tao\"",
      id: "\"Cuma kamu yang sudah segini buat kita\"",
    }),
    badMatch: localeMap({
      ko: "너무 많이 주다 보면 소진될 수 있음. 가족도 당신에게 줄 수 있어야 건강한 관계",
      en: "Giving too much can burn you out. For a healthy relationship, family must be able to give back to you too.",
      ja: "与えすぎると消耗する。家族もあなたに返せる関係でなければ健全ではない。",
      'zh-CN': "给得太多可能会耗尽自己。家人也要能回馈你，关系才健康。",
      'zh-TW': "給得太多可能會耗盡自己。家人也要能回饋你，關係才健康。",
      vi: "Cho quá nhiều có thể kiệt sức. Gia đình cũng phải biết cho lại thì quan hệ mới lành mạnh.",
      id: "Memberi terlalu banyak bisa membuatmu kehabisan tenaga. Keluarga juga harus bisa memberi balik agar hubungan sehat.",
    }),
    certificationPhrase: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    shareLine: localeMap({
      ko: "가족 극한 밸런스 결과: 가족 우선형 🏠 가족 위해 기회도 포기한다는 선택 다 함... 나 가족한테 이런 사람이었구나 ㅠ → 가족한테 보내서 반응 봐봐",
      en: "Family Extreme Balance result: Family-First Type 🏠 Chose to give up opportunities for family... so THIS is who I am to them ㅠ → send to family and see their reaction",
      ja: "家族極限バランス結果：家族優先型 🏠 家族のためにチャンスも断る選択を全部…家族にとってこんな人だったのか ㅠ → 家族に送って反応見て",
      'zh-CN': "家庭极限平衡结果：家庭优先型 🏠 为家人放弃机会的选择全做了…原来我在家人眼里是这样的人 ㅠ → 发给家人看反应",
      'zh-TW': "家庭極限平衡結果：家庭優先型 🏠 為家人放棄機會的選擇全做了…原來我在家人眼裡是這樣的人 ㅠ → 發給家人看反應",
      vi: "Kết quả cân bằng gia đình cực hạn: Kiểu ưu tiên gia đình 🏠 Chọn từ bỏ cơ hội vì gia đình hết... hóa ra tôi là kiểu người này với họ ㅠ → gửi cho gia đình xem phản ứng",
      id: "Hasil balance game keluarga ekstrem: Tipe keluarga dulu 🏠 Pilihan melepaskan kesempatan demi keluarga semua... ternyata aku begini buat mereka ㅠ → kirim ke keluarga lihat reaksinya",
    }),
  },
  {
    type: 'Type5',
    emoji: '💛',
    title: localeMap({
      ko: "거의 모든 상황에서 가족을 선택하는 사람, 극강 가족형",
      en: "Chooses Family in Almost Every Situation — Ultra Family Type",
      ja: "ほぼすべての場面で家族を選ぶ人 — 最強家族型",
      'zh-CN': "几乎在所有情况下都选家人的人——超强家庭型",
      'zh-TW': "幾乎在所有情況下都選家人的人——超強家庭型",
      vi: "Người chọn gia đình trong hầu hết mọi tình huống — Kiểu gia đình cực mạnh",
      id: "Orang yang hampir selalu memilih keluarga — Tipe keluarga ultra",
    }),
    shortDescription: localeMap({
      ko: "당신에게 대부분의 상황에서 답은 하나입니다. 가족.",
      en: "For you, in most situations there is one answer: family.",
      ja: "あなたにとって大抵の状況で答えは一つ。家族。",
      'zh-CN': "对你而言，大多数情况的答案只有一个：家人。",
      'zh-TW': "對你而言，大多數情況的答案只有一個：家人。",
      vi: "Với bạn, trong hầu hết tình huống câu trả lời chỉ có một: gia đình.",
      id: "Bagimu, di kebanyakan situasi jawabannya satu: keluarga.",
    }),
    description: localeMap({
      ko: "빚보증을 서고 꿈을 포기하고 비밀을 혼자 짊어집니다. 이 선택들이 쉬운 건 아닙니다. 그런데도 당신은 가족 쪽을 선택했습니다. 이 수준의 헌신은 가족에게 평생의 자산이 됩니다.\n\n이 유형의 강점: 어떤 상황에서도 가족 편이라는 강한 신뢰감. 이 수준의 가족 구성원이 있는 집은 다름\n\n한 줄 평: 당신의 헌신은 가족 안에서 레어템입니다. 그 가치를 아는 가족에게 쏟고 있는지 가끔 확인해보세요",
      en: "You co-sign, give up dreams, and carry secrets alone. These choices aren't easy. Yet you still chose family. Devotion at this level becomes a lifelong asset to them.\n\nStrengths of This Type: Strong trust that you're always on family's side. A home with someone like you is different.\n\nOne-liner: Your devotion is rare within family. Check sometimes whether you're pouring it into those who know its worth.",
      ja: "連帯保証をし、夢を諦め、秘密を一人で背負う。簡単な選択ではない。それでも家族側を選んだ。このレベルの献身は家族にとって一生の財産になる。\n\nこのタイプの強み: どんな状況でも家族側という強い信頼感。このレベルの家族がいる家は違う。\n\n一言評価: あなたの献身は家族の中ではレアアイテムだ。その価値を知る家族に注いでいるか、たまに確かめて。",
      'zh-CN': "你会作担保、放弃梦想、独自扛秘密。这些选择并不容易。但你还是选了家人。这种程度的付出，对家人是一辈子的财富。\n\n这种类型的优势: 无论什么情况都站家人这边，让人强烈信赖。有这种家人的家就是不一样。\n\n一句话点评: 你的付出在家人里是稀有品。偶尔确认一下，是否给到了懂得珍惜的人。",
      'zh-TW': "你會作擔保、放棄夢想、獨自扛秘密。這些選擇並不容易。但你還是選了家人。這種程度的付出，對家人是一輩子的財富。\n\n這種類型的優勢: 無論什麼情況都站家人這邊，讓人強烈信賴。有這種家人的家就是不一樣。\n\n一句話點評: 你的付出在家人裡是稀有品。偶爾確認一下，是否給到了懂得珍惜的人。",
      vi: "Bạn bảo lãnh, từ bỏ ước mơ, gánh bí mật một mình. Những lựa chọn này không dễ. Nhưng bạn vẫn chọn gia đình. Mức hi sinh này là tài sản cả đời với họ.\n\nĐiểm mạnh của kiểu này: Niềm tin mạnh rằng bạn luôn về phía gia đình. Nhà có người như bạn là khác biệt.\n\nNhận xét một câu: Sự hi sinh của bạn là hiếm trong gia đình. Thỉnh thoảng xem bạn có dành cho người biết giá trị đó không.",
      id: "Kamu jadi penjamin, menyerah impian, dan memikul rahasia sendiri. Pilihan ini tidak mudah. Tapi kamu tetap memilih keluarga. Pengabdian selevel ini jadi aset seumur hidup bagi mereka.\n\nKelebihan tipe ini: Kepercayaan kuat bahwa kamu selalu memihak keluarga. Rumah dengan anggota selevel ini memang beda.\n\nSatu kalimat: Pengabdianmu langka dalam keluarga. Sesekali cek apakah kamu menuangkannya ke yang tahu nilainya.",
    }),
    empathyLevel: localeMap({
      ko: "극강 가족형 💛",
      en: "Ultra Family Type 💛",
      ja: "最強家族型 💛",
      'zh-CN': "超强家庭型 💛",
      'zh-TW': "超強家庭型 💛",
      vi: "Kiểu gia đình cực mạnh 💛",
      id: "Tipe keluarga ultra 💛",
    }),
    characteristics: localeMap({
      ko: "무조건·헌신·가족이 전부·평생 지킴",
      en: "Unconditional · Devotion · Family is everything · Lifelong loyalty",
      ja: "無条件 · 献身 · 家族がすべて · 生涯守る",
      'zh-CN': "无条件·奉献·家人就是全部·一生守护",
      'zh-TW': "無條件·奉獻·家人就是全部·一生守護",
      vi: "Vô điều kiện · Hi sinh · Gia đình là tất cả · Giữ cả đời",
      id: "Tanpa syarat · Pengabdian · Keluarga segalanya · Jaga seumur hidup",
    }),
    goodMatch: localeMap({
      ko: "\"너 같은 가족은 두 번 다시 못 만날 것 같아\"",
      en: "\"I don't think I'll ever find another family member like you\"",
      ja: "「君みたいな家族、もう二度と出会えないと思う」",
      'zh-CN': "“像你这样的家人，可能再也遇不到了”",
      'zh-TW': "「像你這樣的家人，可能再也遇不到了」",
      vi: "\"Chắc không gặp lại được người thân như mày đâu\"",
      id: "\"Kayaknya nggak akan ketemu lagi keluarga sepertimu\"",
    }),
    badMatch: localeMap({
      ko: "모든 가족 구성원이 이 헌신을 당연하게 여기지 않는지 확인하기. 당신의 희생을 가볍게 보는 경우는 없는지 점검",
      en: "Check whether every family member takes this devotion for granted. Make sure no one treats your sacrifice lightly.",
      ja: "すべての家族がこの献身を当たり前にしていないか確かめて。あなたの犠牲を軽く見ていないか点検を。",
      'zh-CN': "确认是否每位家人都把这份付出当作理所当然。检查是否有人轻视你的牺牲。",
      'zh-TW': "確認是否每位家人都把這份付出當作理所當然。檢查是否有人輕視你的犧牲。",
      vi: "Xem mọi thành viên có coi sự hi sinh này là đương nhiên không. Kiểm tra xem có ai xem nhẹ hy sinh của bạn.",
      id: "Pastikan semua anggota keluarga tidak menganggap pengabdian ini wajar. Cek apakah ada yang meremehkan pengorbananmu.",
    }),
    certificationPhrase: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    shareLine: localeMap({
      ko: "가족 극한 밸런스 결과: 극강 가족형 💛 거의 다 가족 선택... 빚보증도 서겠다는 거 나 진짜 가족 바보인가 ㅋㅋ → 어떻게 그걸 골라?!",
      en: "Family Extreme Balance result: Ultra Family Type 💛 Almost all family picks... even co-signing?! am I really a family fool lol → how did you pick THAT?!",
      ja: "家族極限バランス結果：最強家族型 💛 ほぼ全部家族選択…連帯保証もするの？本当に家族バカか 笑 → なんでそれ選んだの?!",
      'zh-CN': "家庭极限平衡结果：超强家庭型 💛 几乎全选家人…连担保都愿意？我真是家庭傻瓜吗 哈哈 → 你怎么选那个的?!",
      'zh-TW': "家庭極限平衡結果：超強家庭型 💛 幾乎全選家人…連擔保都願意？我真是家庭傻瓜嗎 哈哈 → 你怎麼選那個的?!",
      vi: "Kết quả cân bằng gia đình cực hạn: Kiểu gia đình cực mạnh 💛 Gần như chọn gia đình hết... còn bảo lãnh nữa? tôi ngốc gia đình thật à haha → sao mày chọn cái đó?!",
      id: "Hasil balance game keluarga ekstrem: Tipe keluarga ultra 💛 Hampir semua pilih keluarga... bahkan jadi penjamin? aku beneran bodoh keluarga ya lol → kok kamu pilih ITU?!",
    }),
  },
  {
    type: 'Type6',
    emoji: '🌟',
    title: localeMap({
      ko: "가족이 곧 삶인 사람, 가족 레전드형",
      en: "Family Is Life Itself — Family Legend Type",
      ja: "家族こそが人生の人 — 家族レジェンド型",
      'zh-CN': "家人就是人生的人——家庭传奇型",
      'zh-TW': "家人就是人生的人——家庭傳奇型",
      vi: "Gia đình chính là cuộc đời — Kiểu huyền thoại gia đình",
      id: "Keluarga adalah hidup — Tipe legenda keluarga",
    }),
    shortDescription: localeMap({
      ko: "12개 전부 가족을 선택했습니다. 당신에게 가족은 타협 없는 절대값입니다.",
      en: "You chose family in all 12 rounds. For you, family is a non-negotiable absolute.",
      ja: "12問すべて家族を選びました。あなたにとって家族は妥協のない絶対値です。",
      'zh-CN': "12题全部选了家人。对你而言，家人是不容妥协的绝对值。",
      'zh-TW': "12題全部選了家人。對你而言，家人是不容妥協的絕對值。",
      vi: "Bạn chọn gia đình cả 12 vòng. Với bạn, gia đình là giá trị tuyệt đối không thỏa hiệp.",
      id: "Kamu memilih keluarga di semua 12 ronde. Bagimu, keluarga adalah nilai mutlak tanpa kompromi.",
    }),
    description: localeMap({
      ko: "빚보증·꿈 포기·비밀 혼자 짊어지기·공개 방어·용서까지 전부 선택했습니다. 현실적으로 손해인 것을 알면서도 선택했습니다. 이 수준의 가족관을 가진 사람은 드뭅니다. 그리고 이런 가족 구성원 하나 있으면 그 가족의 색이 달라집니다.\n\n이 유형의 강점: 가족이 흔들릴 때 중심을 잡는 사람. 가족에게 평생 기억되는 존재\n\n한 줄 평: 이 결과를 가족 단톡방에 올리세요. 당신 같은 가족이 있다는 것을 모두가 알아야 합니다",
      en: "Co-signing, giving up dreams, carrying secrets alone, public defense, forgiveness—you chose all of them. You knew they were costly in reality and still chose them. People with this level of family devotion are rare. One member like you changes the whole family's color.\n\nStrengths of This Type: You hold the center when family shakes. You're someone they'll remember for life.\n\nOne-liner: Post this result in the family chat. Everyone should know they have someone like you.",
      ja: "連帯保証・夢の放棄・秘密を一人で背負う・公然の防御・許しまで全部選んだ。現実的に損だと分かっていても選んだ。このレベルの家族観を持つ人は稀だ。こういう家族が一人いるだけで、その家族の色が変わる。\n\nこのタイプの強み: 家族が揺れるとき中心を保つ人。家族に一生記憶される存在。\n\n一言評価: この結果を家族グループに上げて。あなたのような家族がいることをみんなが知るべきだ。",
      'zh-CN': "担保、放弃梦想、独自扛秘密、公开辩护、原谅——你全都选了。明知现实上会吃亏还是选了。这种家庭观的人很少见。有这样一个家人，整个家的气质都会不同。\n\n这种类型的优势: 家人动摇时稳住中心的人。会被家人记住一辈子。\n\n一句话点评: 把这个结果发到家庭群。大家都该知道有你这样的家人。",
      'zh-TW': "擔保、放棄夢想、獨自扛秘密、公開辯護、原諒——你全都選了。明知現實上會吃虧還是選了。這種家庭觀的人很少見。有這樣一個家人，整個家的氣質都會不同。\n\n這種類型的優勢: 家人動搖時穩住中心的人。會被家人記住一輩子。\n\n一句話點評: 把這個結果發到家庭群。大家都該知道有你這樣的家人。",
      vi: "Bảo lãnh, bỏ ước mơ, gánh bí mật một mình, bảo vệ công khai, tha thứ — bạn chọn hết. Biết thực tế sẽ thiệt mà vẫn chọn. Người có quan niệm gia đình mức này rất hiếm. Có một người như bạn là cả nhà đã khác màu.\n\nĐiểm mạnh của kiểu này: Người giữ vững trung tâm khi gia đình lay chuyển. Là người gia đình nhớ cả đời.\n\nNhận xét một câu: Đăng kết quả này vào nhóm gia đình. Mọi người cần biết có người như bạn.",
      id: "Penjamin, menyerah impian, pikul rahasia sendiri, bela di depan umum, maafkan — semua kamu pilih. Tahu secara realistis rugi tapi tetap pilih. Orang dengan pandangan keluarga selevel ini jarang. Satu anggota seperti kamu mengubah warna seluruh keluarga.\n\nKelebihan tipe ini: Orang yang menjaga pusat saat keluarga goyah. Kehadiran yang akan diingat seumur hidup.\n\nSatu kalimat: Unggah hasil ini di grup keluarga. Semua harus tahu ada keluarga sepertimu.",
    }),
    empathyLevel: localeMap({
      ko: "가족 레전드 🌟",
      en: "Family Legend 🌟",
      ja: "家族レジェンド 🌟",
      'zh-CN': "家庭传奇 🌟",
      'zh-TW': "家庭傳奇 🌟",
      vi: "Huyền thoại gia đình 🌟",
      id: "Legenda keluarga 🌟",
    }),
    characteristics: localeMap({
      ko: "절대 헌신·가족이 전부·무한 의리·레전드",
      en: "Absolute devotion · Family is everything · Boundless loyalty · Legend",
      ja: "絶対献身 · 家族がすべて · 無限の義理 · レジェンド",
      'zh-CN': "绝对奉献·家人就是全部·无限义气·传奇",
      'zh-TW': "絕對奉獻·家人就是全部·無限義氣·傳奇",
      vi: "Hi sinh tuyệt đối · Gia đình là tất cả · Nghĩa khí vô hạn · Huyền thoại",
      id: "Pengabdian mutlak · Keluarga segalanya · Loyalitas tak terbatas · Legenda",
    }),
    goodMatch: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    badMatch: localeMap({
      ko: "헌신이 절대적일수록 가족에게 배신당했을 때 충격이 클 수 있음. 나 자신에게도 그 헌신의 일부를 돌려주기",
      en: "The more absolute your devotion, the harder betrayal by family can hit. Give some of that devotion back to yourself too.",
      ja: "献身が絶対的であるほど、家族に裏切られたときの衝撃は大きい。自分自身にもその献身の一部を返して。",
      'zh-CN': "奉献越绝对，被家人辜负时的冲击可能越大。也留一部分给自己。",
      'zh-TW': "奉獻越絕對，被家人辜負時的衝擊可能越大。也留一部分給自己。",
      vi: "Hi sinh càng tuyệt đối, cú sốc khi bị gia đình phản bội càng lớn. Hãy dành một phần cho chính mình.",
      id: "Semakin mutlak pengabdianmu, semakin besar dampak jika dikhianati keluarga. Kembalikan sebagian pengabdian itu untuk dirimu sendiri.",
    }),
    certificationPhrase: localeMap({
      ko: "가족 레전드 달성 🌟 12라운드 전부 가족을 선택했습니다",
      en: "Family Legend Achieved 🌟 You chose family in all 12 rounds",
      ja: "家族レジェンド達成 🌟 12ラウンドすべて家族を選択しました",
      'zh-CN': "达成家庭传奇 🌟 12轮全部选择了家人",
      'zh-TW': "達成家庭傳奇 🌟 12輪全部選擇了家人",
      vi: "Đạt Huyền thoại gia đình 🌟 Đã chọn gia đình cả 12 vòng",
      id: "Legenda Keluarga Tercapai 🌟 Memilih keluarga di semua 12 ronde",
    }),
    shareLine: localeMap({
      ko: "가족 극한 밸런스 결과: 가족 레전드 🌟 12개 전부 가족 선택... 가족 단톡방에 올렸더니 반응 폭발 → 너희 가족도 해봐 결과 다 다름 보장",
      en: "Family Extreme Balance result: Family Legend 🌟 Chose family all 12... posted in the family chat and reactions exploded → try with your family, guaranteed different results",
      ja: "家族極限バランス結果：家族レジェンド 🌟 12問全部家族選択…家族グループに上げたら反応爆発 → みんなの家族もやってみて、結果は絶対違う",
      'zh-CN': "家庭极限平衡结果：家庭传奇 🌟 12题全选家人…发到家庭群反应爆炸 → 你们家也试试，结果肯定不同",
      'zh-TW': "家庭極限平衡結果：家庭傳奇 🌟 12題全選家人…發到家庭群反應爆炸 → 你們家也試試，結果肯定不同",
      vi: "Kết quả cân bằng gia đình cực hạn: Huyền thoại gia đình 🌟 Chọn gia đình cả 12... đăng nhóm gia đình là nổ tung → thử với gia đình bạn, chắc chắn khác nhau",
      id: "Hasil balance game keluarga ekstrem: Legenda keluarga 🌟 Pilih keluarga semua 12... share di grup keluarga reaksinya meledak → coba dengan keluargamu, dijamin beda",
    }),
  },
];
