/** AI가 그린 나의 '10년 후' — 12문항 4지선다, A=0 B=1 C=2 D=3, 총점 0~36 → Type1~6 */

type Locale = 'ko' | 'en' | 'ja' | 'zh-CN' | 'zh-TW' | 'vi' | 'id';
type ML = Record<Locale, string>;

function L(m: ML): Record<string, string> {
  return m;
}

/** Korean source → 7-locale map (missing keys fall back to Korean) */
const TR: Record<string, Partial<Record<'en' | 'ja' | 'zh-CN' | 'zh-TW' | 'vi' | 'id', string>>> = {
  "10년 후 내가 살고 싶은 공간은?": {
    en: "Where do you want to live in 10 years?",
    ja: "10年後、住みたい空間は？",
    'zh-CN': "十年后你想住在怎样的空间？",
    'zh-TW': "十年後你想住在怎樣的空間？",
    vi: "Sau 10 năm bạn muốn sống ở không gian nào?",
    id: "Di mana kamu ingin tinggal 10 tahun lagi?",
  },
  "10년 후 월요일 아침을 상상한다면?": {
    en: "Imagine a Monday morning in 10 years — what's it like?",
    ja: "10年後の月曜の朝を想像すると？",
    'zh-CN': "想象十年后的周一早晨会是怎样？",
    'zh-TW': "想像十年後的週一早晨會是怎樣？",
    vi: "Hãy tưởng tượng sáng thứ Hai sau 10 năm?",
    id: "Bayangkan pagi Senin 10 tahun lagi?",
  },
  "10년 후 나의 일은 어떤 모습이길 원하나요?": {
    en: "What do you want your work to look like in 10 years?",
    ja: "10年後、仕事はどんな姿であってほしい？",
    'zh-CN': "十年后你希望工作是什么样子？",
    'zh-TW': "十年後你希望工作是什麼樣子？",
    vi: "Bạn muốn công việc sau 10 năm như thế nào?",
    id: "Seperti apa pekerjaan yang kamu inginkan 10 tahun lagi?",
  },
  "10년 후 주말 오후에 내가 있을 것 같은 장면은?": {
    en: "Where do you see yourself on a weekend afternoon in 10 years?",
    ja: "10年後の週末の午後、自分がいる場面は？",
    'zh-CN': "十年后周末下午你会在怎样的场景里？",
    'zh-TW': "十年後週末下午你會在怎樣的場景裡？",
    vi: "Cảnh nào bạn thấy mình vào chiều cuối tuần sau 10 năm?",
    id: "Di adegan mana kamu berada di sore akhir pekan 10 tahun lagi?",
  },
  "10년 후 나에게 가장 중요한 관계는?": {
    en: "What relationship matters most to you in 10 years?",
    ja: "10年後、いちばん大切な関係は？",
    'zh-CN': "十年后对你最重要的关系是？",
    'zh-TW': "十年後對你最重要的關係是？",
    vi: "Mối quan hệ quan trọng nhất với bạn sau 10 năm?",
    id: "Hubungan apa yang paling penting bagimu 10 tahun lagi?",
  },
  "10년 후 나의 하루에서 가장 많은 시간을 차지하는 것은?": {
    en: "What takes most of your day in 10 years?",
    ja: "10年後の一日でいちばん多くの時間を占めるものは？",
    'zh-CN': "十年后你一天里占用最多时间的是？",
    'zh-TW': "十年後你一天裡佔用最多時間的是？",
    vi: "Điều gì chiếm nhiều thời gian nhất trong ngày bạn sau 10 năm?",
    id: "Apa yang paling banyak mengisi harimu 10 tahun lagi?",
  },
  "10년 후 나에게 성공이란?": {
    en: "What does success mean to you in 10 years?",
    ja: "10年後、自分にとっての成功とは？",
    'zh-CN': "十年后对你而言成功是什么？",
    'zh-TW': "十年後對你而言成功是什麼？",
    vi: "Với bạn, thành công sau 10 năm là gì?",
    id: "Apa arti sukses bagimu 10 tahun lagi?",
  },
  "10년 후 내 삶에 반드시 있어야 하는 것은?": {
    en: "What must exist in your life in 10 years?",
    ja: "10年後の人生に必ず必要なものは？",
    'zh-CN': "十年后你的生活里必须有什么？",
    'zh-TW': "十年後你的生活裡必須有什麼？",
    vi: "Điều gì bắt buộc phải có trong đời bạn sau 10 năm?",
    id: "Apa yang wajib ada di hidupmu 10 tahun lagi?",
  },
  "10년 후 가장 갖고 싶은 능력은?": {
    en: "What ability do you most want in 10 years?",
    ja: "10年後、いちばん欲しい能力は？",
    'zh-CN': "十年后你最想拥有的能力是？",
    'zh-TW': "十年後你最想擁有的能力是？",
    vi: "Năng lực bạn muốn có nhất sau 10 năm?",
    id: "Kemampuan apa yang paling ingin kamu miliki 10 tahun lagi?",
  },
  "10년 후 저녁 시간을 보내는 나의 모습은?": {
    en: "How do you spend evenings in 10 years?",
    ja: "10年後、夕方の時間を過ごす自分の姿は？",
    'zh-CN': "十年后你如何度过晚间？",
    'zh-TW': "十年後你如何度過晚間？",
    vi: "Bạn dành buổi tối như thế nào sau 10 năm?",
    id: "Bagaimana kamu menghabiskan malam 10 tahun lagi?",
  },
  "10년 후 내가 두려워하지 않을 것은?": {
    en: "What won't you fear in 10 years?",
    ja: "10年後、恐れなくなるものは？",
    'zh-CN': "十年后你不会再害怕的是？",
    'zh-TW': "十年後你不會再害怕的是？",
    vi: "Điều gì bạn sẽ không còn sợ sau 10 năm?",
    id: "Apa yang tidak lagi kamu takuti 10 tahun lagi?",
  },
  "지금 이 순간 10년 후의 나에게 가장 바라는 것은?": {
    en: "Right now, what do you most hope for your future self in 10 years?",
    ja: "今この瞬間、10年後の自分にいちばん望むことは？",
    'zh-CN': "此刻你最希望十年后的自己怎样？",
    'zh-TW': "此刻你最希望十年後的自己怎樣？",
    vi: "Ngay lúc này, bạn mong bản thân 10 năm sau điều gì nhất?",
    id: "Saat ini, apa yang paling kamu harapkan dari diri 10 tahun lagi?",
  },
  "조용한 교외나 자연 근처의 작고 아늑한 집. 혼자만의 공간이 충분한 곳": {
    en: "A small cozy home near quiet suburbs or nature, with enough space just for me",
    ja: "静かな郊外や自然の近くの小さく居心地の良い家。ひとりの空間が十分な場所",
    'zh-CN': "安静郊区或自然附近的小而温馨的家，有足够的独处空间",
    'zh-TW': "安靜郊區或自然附近的小而溫馨的家，有足夠的獨處空間",
    vi: "Ngôi nhà nhỏ ấm cúng gần ngoại ô yên tĩnh hoặc thiên nhiên, đủ không gian riêng",
    id: "Rumah kecil nyaman dekat pinggiran tenang atau alam, dengan ruang pribadi cukup",
  },
  "가족이나 가까운 사람들과 함께할 수 있는 넓고 따뜻한 집": {
    en: "A spacious warm home where I can be with family or close people",
    ja: "家族や近い人たちと一緒にいられる広く温かい家",
    'zh-CN': "能和家人或亲近的人在一起的宽敞温暖的家",
    'zh-TW': "能和家人或親近的人在一起的寬敞溫暖的家",
    vi: "Ngôi nhà rộng ấm áp để ở cùng gia đình hoặc người thân",
    id: "Rumah luas dan hangat untuk bersama keluarga atau orang dekat",
  },
  "도심과 가까우면서도 작업실이나 서재가 있는 기능적인 공간": {
    en: "A functional space near the city with a studio or study",
    ja: "都心に近く、作業室や書斎がある機能的な空間",
    'zh-CN': "靠近市区又有工作室或书房的功能性空间",
    'zh-TW': "靠近市區又有工作室或書房的功能性空間",
    vi: "Không gian tiện ích gần trung tâm có phòng làm việc hoặc thư viện riêng",
    id: "Ruang fungsional dekat kota dengan studio atau ruang baca",
  },
  "어디에 있는지는 중요하지 않다. 필요하면 옮길 수 있는 유연한 공간": {
    en: "Location doesn't matter — a flexible space I can move when needed",
    ja: "どこにあるかは重要ではない。必要なら移れる柔軟な空間",
    'zh-CN': "在哪里不重要，需要时就能搬走的灵活空间",
    'zh-TW': "在哪裡不重要，需要時就能搬走的靈活空間",
    vi: "Ở đâu không quan trọng — không gian linh hoạt có thể chuyển khi cần",
    id: "Lokasi tidak penting — ruang fleksibel yang bisa dipindah jika perlu",
  },
  "알람 없이 일어나 조용히 커피를 내리고 책을 읽는 아침": {
    en: "Waking without an alarm, quietly brewing coffee and reading",
    ja: "アラームなしで起き、静かにコーヒーを淹れて本を読む朝",
    'zh-CN': "不靠闹钟起床，安静地冲咖啡、读书的早晨",
    'zh-TW': "不靠鬧鐘起床，安靜地沖咖啡、讀書的早晨",
    vi: "Thức dậy không báo thức, pha cà phê và đọc sách yên lặng",
    id: "Bangun tanpa alarm, menyeduh kopi dan membaca dengan tenang",
  },
  "가족이나 소중한 사람과 함께 아침 식사를 하는 따뜻한 시간": {
    en: "A warm breakfast with family or someone precious",
    ja: "家族や大切な人と一緒に朝ごはんを食べる温かい時間",
    'zh-CN': "和家人或珍爱的人一起吃早餐的温暖时光",
    'zh-TW': "和家人或珍愛的人一起吃早餐的溫暖時光",
    vi: "Bữa sáng ấm áp cùng gia đình hoặc người quý",
    id: "Sarapan hangat bersama keluarga atau orang tersayang",
  },
  "계획된 루틴대로 움직이며 하루를 준비하는 효율적인 아침": {
    en: "An efficient morning following a planned routine",
    ja: "計画したルーティンどおりに動き、一日を準備する効率的な朝",
    'zh-CN': "按既定例行高效准备一天的早晨",
    'zh-TW': "按既定例行高效準備一天的早晨",
    vi: "Buổi sáng hiệu quả theo lịch trình đã lên để chuẩn bị cả ngày",
    id: "Pagi efisien mengikuti rutinitas terencana",
  },
  "오늘 뭘 할지 그날 결정하는 즉흥적이고 자유로운 아침": {
    en: "A free, spontaneous morning deciding what to do that day",
    ja: "今日何をするかその日に決める即興で自由な朝",
    'zh-CN': "当天再决定做什么的即兴自由早晨",
    'zh-TW': "當天再決定做什麼的即興自由早晨",
    vi: "Buổi sáng tự do, ứng biến — quyết định hôm đó làm gì",
    id: "Pagi spontan dan bebas, memutuskan hari itu mau apa",
  },
  "조용히 혼자 집중할 수 있는 일. 깊이 있는 결과물이 쌓이는 것": {
    en: "Quiet focused solo work where deep output accumulates",
    ja: "静かにひとりで集中できる仕事。深い成果物が積み上がること",
    'zh-CN': "能安静独自专注的工作，深度成果不断累积",
    'zh-TW': "能安靜獨自專注的工作，深度成果不斷累積",
    vi: "Công việc yên tĩnh tập trung một mình, kết quả sâu dần tích lũy",
    id: "Pekerjaan fokus sendirian yang tenang, hasil mendalam menumpuk",
  },
  "사람들과 연결되고 누군가에게 도움이 되는 의미 있는 일": {
    en: "Meaningful work connecting with people and helping someone",
    ja: "人とつながり、誰かの役に立つ意味のある仕事",
    'zh-CN': "与人连接、能帮助他人的有意义的工作",
    'zh-TW': "與人連接、能幫助他人的有意義的工作",
    vi: "Công việc ý nghĩa kết nối với người khác và giúp ai đó",
    id: "Pekerjaan bermakna yang terhubung dengan orang dan membantu seseorang",
  },
  "전문성과 성과가 인정받는 일. 내 커리어에 자부심이 있는 것": {
    en: "Work where expertise and results are recognized — pride in my career",
    ja: "専門性と成果が認められる仕事。キャリアに誇りがあること",
    'zh-CN': "专业与成果被认可的工作，对自己的职业感到自豪",
    'zh-TW': "專業與成果被認可的工作，對自己的職業感到自豪",
    vi: "Công việc được công nhận chuyên môn và thành tích — tự hào sự nghiệp",
    id: "Pekerjaan yang keahlian dan hasilnya diakui — bangga dengan karier",
  },
  "자유롭게 내 방식으로 할 수 있는 일. 누가 정해준 틀이 없는 것": {
    en: "Work I can do my own way freely — no frame someone else set",
    ja: "自由に自分のやり方でできる仕事。誰かが決めた枠がないこと",
    'zh-CN': "能按自己方式自由做的工作，没有别人定的框框",
    'zh-TW': "能按自己方式自由做的工作，沒有別人定的框框",
    vi: "Công việc tự do theo cách của mình — không khuôn mẫu người khác đặt",
    id: "Pekerjaan bebas dengan caraku sendiri — tanpa kerangka orang lain",
  },
  "조용하고 충만한 나만의 세계, 내면 충만 생활형": {
    en: "A quiet, fulfilling world of my own — Inner Fulfillment Lifestyle",
    ja: "静かで充実した自分だけの世界、内面充実生活型",
    'zh-CN': "安静充实的自我世界，内在充盈生活型",
    'zh-TW': "安靜充實的自我世界，內在充盈生活型",
    vi: "Thế giới yên bình viên mãn của riêng mình — Kiểu sống sung mãn nội tâm",
    id: "Dunia tenang dan penuh milikku sendiri — Gaya Hidup Pemenuhan Batin",
  },
  "따뜻한 연결이 삶의 중심인, 관계 풍요 생활형": {
    en: "Warm connection at the center — Relationship Abundance Lifestyle",
    ja: "温かいつながりが人生の中心、関係豊かな生活型",
    'zh-CN': "以温暖连接为生活中心，关系丰盛生活型",
    'zh-TW': "以溫暖連接為生活中心，關係豐盛生活型",
    vi: "Kết nối ấm áp là trung tâm — Kiểu sống phong phú quan hệ",
    id: "Koneksi hangat di pusat hidup — Gaya Hidup Kelimpahan Relasi",
  },
  "일과 삶이 균형 잡힌, 꾸준한 성장 생활형": {
    en: "Work-life balance with steady growth — Steady Growth Lifestyle",
    ja: "仕事と人生のバランスが取れた、着実成長生活型",
    'zh-CN': "工作与生活平衡，稳健成长生活型",
    'zh-TW': "工作與生活平衡，穩健成長生活型",
    vi: "Cân bằng việc-đời, phát triển vững — Kiểu sống tăng trưởng đều",
    id: "Seimbang kerja-hidup, tumbuh konsisten — Gaya Hidup Pertumbuhan Stabil",
  },
  "목표와 성취가 살아있는, 전문 성취 생활형": {
    en: "Goals and achievement alive — Professional Achievement Lifestyle",
    ja: "目標と達成が生きている、専門達成生活型",
    'zh-CN': "目标与成就鲜活，专业成就生活型",
    'zh-TW': "目標與成就鮮活，專業成就生活型",
    vi: "Mục tiêu và thành tựu sống động — Kiểu sống thành tựu chuyên môn",
    id: "Tujuan dan capaian hidup — Gaya Hidup Prestasi Profesional",
  },
  "새로운 경험이 넘치는, 활동적 탐험 생활형": {
    en: "Overflowing with new experiences — Active Explorer Lifestyle",
    ja: "新しい経験にあふれる、活動的探検生活型",
    'zh-CN': "充满新体验，活力探索生活型",
    'zh-TW': "充滿新體驗，活力探索生活型",
    vi: "Tràn trải nghiệm mới — Kiểu sống thám hiểm năng động",
    id: "Penuh pengalaman baru — Gaya Hidup Penjelajah Aktif",
  },
  "자신만의 방식으로 사는, 자유 개척 생활형": {
    en: "Living my own way — Free Pioneer Lifestyle",
    ja: "自分だけのやり方で生きる、自由開拓生活型",
    'zh-CN': "按自己的方式生活，自由开拓生活型",
    'zh-TW': "按自己的方式生活，自由開拓生活型",
    vi: "Sống theo cách riêng — Kiểu sống khai phá tự do",
    id: "Hidup dengan caraku sendiri — Gaya Hidup Perintis Bebas",
  },
  "🔮 AI가 그린 당신의 10년 후": {
    en: "🔮 Your life in 10 years, painted by AI",
    ja: "🔮 AIが描くあなたの10年後",
    'zh-CN': "🔮 AI描绘的你的十年后",
    'zh-TW': "🔮 AI描繪的你的十年後",
    vi: "🔮 10 năm sau của bạn do AI vẽ",
    id: "🔮 10 tahun lagi-mu yang digambar AI",
  },
  "고요함,깊이,독립,충만,나다움": {
    en: "calm,depth,independence,fulfillment,authenticity",
    ja: "静けさ,深さ,独立,充実,自分らしさ",
    'zh-CN': "平静,深度,独立,充盈,本真",
    'zh-TW': "平靜,深度,獨立,充盈,本真",
    vi: "tĩnh lặng,chiều sâu,độc lập,viên mãn,đúng mình",
    id: "tenang,kedalaman,mandiri,pemenuhan,autentik",
  },
  "연결,따뜻함,돌봄,공감,함께함": {
    en: "connection,warmth,care,empathy,togetherness",
    ja: "つながり,温かさ,ケア,共感,共に",
    'zh-CN': "连接,温暖,照顾,共情,一起",
    'zh-TW': "連接,溫暖,照顧,共情,一起",
    vi: "kết nối,ấm áp,chăm sóc,đồng cảm,cùng nhau",
    id: "koneksi,kehangatan,peduli,empati,kebersamaan",
  },
  "균형,성장,꾸준함,전문성,방향성": {
    en: "balance,growth,consistency,expertise,direction",
    ja: "バランス,成長,着実さ,専門性,方向性",
    'zh-CN': "平衡,成长,稳健,专业,方向",
    'zh-TW': "平衡,成長,穩健,專業,方向",
    vi: "cân bằng,phát triển,vững vàng,chuyên môn,hướng đi",
    id: "keseimbangan,pertumbuhan,konsisten,keahlian,arah",
  },
  "성취,전문성,목표,인정,추진력": {
    en: "achievement,expertise,goals,recognition,drive",
    ja: "達成,専門性,目標,認め,推進力",
    'zh-CN': "成就,专业,目标,认可,推进力",
    'zh-TW': "成就,專業,目標,認可,推進力",
    vi: "thành tựu,chuyên môn,mục tiêu,công nhận,động lực",
    id: "capaian,keahlian,tujuan,pengakuan,dorongan",
  },
  "탐험,자유,새로움,이동,경험": {
    en: "exploration,freedom,novelty,mobility,experience",
    ja: "探検,自由,新しさ,移動,経験",
    'zh-CN': "探索,自由,新鲜,移动,体验",
    'zh-TW': "探索,自由,新鮮,移動,體驗",
    vi: "khám phá,tự do,mới mẻ,di chuyển,trải nghiệm",
    id: "eksplorasi,kebebasan,kebaruan,mobilitas,pengalaman",
  },
  "자유,개척,독창성,용기,나만의 길": {
    en: "freedom,pioneering,originality,courage,my own path",
    ja: "自由,開拓,独創性,勇気,自分の道",
    'zh-CN': "自由,开拓,独创,勇气,自己的路",
    'zh-TW': "自由,開拓,獨創,勇氣,自己的路",
    vi: "tự do,khai phá,độc đáo,dũng cảm,con đường riêng",
    id: "kebebasan,merintis,orisinalitas,keberanian,jalanku",
  },
  "🏠 10년 후 공간": {
    en: "🏠 Space in 10 years",
    ja: "🏠 10年後の空間",
    'zh-CN': "🏠 十年后的空间",
    'zh-TW': "🏠 十年後的空間",
    vi: "🏠 Không gian sau 10 năm",
    id: "🏠 Ruang 10 tahun lagi",
  },
  "💼 10년 후 일": {
    en: "💼 Work in 10 years",
    ja: "💼 10年後の仕事",
    'zh-CN': "💼 十年后的工作",
    'zh-TW': "💼 十年後的工作",
    vi: "💼 Công việc sau 10 năm",
    id: "💼 Pekerjaan 10 tahun lagi",
  },
  "💞 10년 후 관계": {
    en: "💞 Relationships in 10 years",
    ja: "💞 10年後の関係",
    'zh-CN': "💞 十年后的关系",
    'zh-TW': "💞 十年後的關係",
    vi: "💞 Quan hệ sau 10 năm",
    id: "💞 Hubungan 10 tahun lagi",
  },
  "☀️ 10년 후 하루의 핵심": {
    en: "☀️ Core of the day in 10 years",
    ja: "☀️ 10年後の一日の核心",
    'zh-CN': "☀️ 十年后一天的核心",
    'zh-TW': "☀️ 十年後一天的核心",
    vi: "☀️ Cốt lõi một ngày sau 10 năm",
    id: "☀️ Inti hari 10 tahun lagi",
  },
  "{year}년 어느 평일 아침입니다.\n알람 없이 눈을 뜹니다. 창문 너머로 빛이 조용히 들어오고 있고 당신은 서두르지 않습니다. 주방으로 나가 손수 커피를 내립니다. 드리퍼에 천천히 뜨거운 물을 붓는 동안 오늘 하고 싶은 것들이 머릿속을 지나갑니다.\n당신이 있는 곳은 도심에서 조금 벗어난 곳입니다. 작지만 당신의 취향이 곳곳에 배어있는 집입니다. 좋아하는 책들이 쌓인 선반, 오래 쓴 의자, 창가에 놓인 식물 한 두 개. 아무도 없어도 이 공간이 당신을 채웁니다.\n오늘 일은 오전에 집중해서 마칩니다. 당신이 하는 일은 깊이 있는 집중이 필요한 일입니다. 글을 쓰거나, 무언가를 만들거나, 오랫동안 쌓아온 전문성을 혼자 발휘하는 일입니다. 아무도 재촉하지 않고 당신의 페이스로 할 수 있습니다.\n오후엔 좋아하는 것을 합니다. 산책이거나 독서이거나 오래된 취미이거나. 많은 사람이 필요하지 않습니다. 당신 삶에는 진짜로 통하는 몇 명이 있고 그것으로 충분합니다.\n저녁이 되면 그 하루가 조용하게 쌓였다는 걸 느낍니다. 특별한 것은 없었지만 나답게 살았다는 느낌. 그것이 10년 후 당신의 성공입니다.": {
    en: "It's a weekday morning in {year}.\nYou wake without an alarm. Soft light comes through the window and you don't rush. In the kitchen you brew coffee by hand; as hot water pours slowly, the things you want today drift through your mind.\nYou live a little outside the city — a small home filled with your taste: shelves of books, a well-worn chair, a plant by the window. Even alone, the space fills you.\nWork finishes with deep focus in the morning — writing, making, or using expertise you've built alone, at your pace.\nAfternoons are for what you love: a walk, reading, an old hobby. You don't need many people; a few true connections are enough.\nAt evening you feel the quiet day stacked up. Nothing flashy — just living as yourself. That is your success in 10 years.",
    ja: "{year}年のある平日の朝です。\nアラームなしで目が覚めます。窓から静かな光が入り、あなたは急ぎません。キッチンで丁寧にコーヒーを淹れ、今日したいことが頭をよぎります。\n都心から少し離れた小さな家。本棚、使い込んだ椅子、窓辺の植物。誰もいなくてもこの空間があなたを満たします。\n午前中に深く集中して仕事を終え、午後は散歩や読書、古い趣味。本当に通じ合う数人で十分です。\n夕方、特別でなくても自分らしく生きた感覚。それが10年後の成功です。",
    'zh-CN': "{year}年的某个工作日早晨。\n你不靠闹钟醒来。窗外光线安静，你不着急。在厨房亲手冲咖啡，一边想着今天想做的事。\n你住在离市区稍远的地方——小家里处处是你的品味：书、旧椅子、窗边植物。即使一个人，这空间也能填满你。\n上午专注完成需要深度的工作；下午做喜欢的事。不需要很多人，几个真正相通的人就够了。\n晚上你会感到这一天安静地堆叠起来。没什么特别，却活成了自己——那就是十年后的成功。",
    'zh-TW': "{year}年的某個工作日早晨。\n你不靠鬧鐘醒來。窗外光線安靜，你不著急。在廚房親手沖咖啡，一邊想著今天想做的事。\n你住在離市區稍遠的地方——小家裡處處是你的品味。即使一個人，這空間也能填滿你。\n上午專注完成需要深度的工作；下午做喜歡的事。幾個真正相通的人就夠了。\n晚上你會感到這一天安靜地堆疊起來。沒什麼特別，卻活成了自己——那就是十年後的成功。",
    vi: "Một sáng ngày thường năm {year}.\nBạn thức dậy không báo thức. Ánh sáng dịu qua cửa sổ, bạn không vội. Pha cà phê chậm rãi, nghĩ về điều muốn làm hôm nay.\nBạn sống hơi xa trung tâm — ngôi nhà nhỏ đầy gu của bạn. Dù một mình, không gian ấy vẫn làm đầy bạn.\nBuổi sáng tập trung hoàn thành việc cần chiều sâu; chiều làm điều mình thích. Chỉ cần vài người thật sự thấu hiểu.\nBuổi tối bạn cảm nhận một ngày yên đã chồng lên. Không đặc biệt — nhưng sống đúng mình. Đó là thành công sau 10 năm.",
    id: "Suatu pagi hari kerja di tahun {year}.\nKamu bangun tanpa alarm. Cahaya lembut masuk, kamu tidak terburu-buru. Menyeduh kopi perlahan sambil memikirkan yang ingin dilakukan hari ini.\nKamu tinggal sedikit di luar kota — rumah kecil penuh selera. Meski sendirian, ruang itu mengisimu.\nPagi fokus menyelesaikan kerja yang butuh kedalaman; sore untuk yang kusukai. Cukup beberapa orang yang benar-benar nyambung.\nMalam hari kamu merasakan hari tenang yang menumpuk. Tidak spektakuler — tapi hidup sebagai dirimu. Itulah sukses 10 tahun lagi.",
  },
  "{year}년 어느 아침입니다.\n눈을 뜨면 주방에서 소리가 납니다. 혼자가 아닙니다. 당신의 삶에는 아침을 함께할 사람이 있습니다. 식탁에 앉아 커피를 마시며 오늘 이야기를 합니다. 아무 의미 없는 이야기도 괜찮습니다. 그냥 같은 시간을 공유하는 것 자체가 좋습니다.\n당신이 하는 일은 사람과 연결된 일입니다. 누군가를 돕거나, 가르치거나, 함께 만들어가는 일입니다. 일이 끝나면 에너지가 소진되는 게 아니라 오히려 충전되는 날이 많습니다. 내가 한 일이 누군가에게 실제로 도움이 됐을 때 느끼는 그 감각을 당신은 소중히 여깁니다.\n주말엔 자주 누군가와 함께합니다. 오래된 친구이거나 가족이거나 새로 알게 된 사람이거나. 밥을 같이 먹고 이야기를 나누고 웃습니다. 당신이 있는 자리는 항상 따뜻해집니다.\n저녁이 되면 오늘 만난 사람들이 생각납니다. 그리고 내일 또 누구를 만날지가 기대됩니다.\n10년 후 당신의 삶은 관계로 가득합니다. 그리고 그것이 당신에게 가장 풍요로운 삶입니다.": {
    en: "It's a morning in {year}.\nYou wake to sounds from the kitchen — you're not alone. Someone shares breakfast and small talk over coffee. Even meaningless chat feels good because you share the time.\nYour work connects people: helping, teaching, building together. Some days it charges you more than it drains. You treasure knowing you truly helped someone.\nWeekends often mean people — old friends, family, new faces — meals, talk, laughter. Wherever you are feels warm.\nAt night you think of who you met and look forward to who you'll meet tomorrow.\nIn 10 years your life is full of relationships — and that is your richest life.",
    ja: "{year}年のある朝です。\n厨房の音で目が覚めます。ひとりではありません。食卓でコーヒーを飲みながら今日の話をします。意味のない話でも、同じ時間を分かち合うこと自体が良いのです。\n仕事は人とつながるもの。助け、教え、共につくる。終わるときエネルギーが増える日も多い。誰かの役に立てた感覚を大切にします。\n週末はよく誰かと。ご飯と笑い。あなたのいる場所はいつも温かい。\n夜は今日会った人を思い、明日また誰に会えるかが楽しみです。\n10年後の人生は関係で満ち、それがいちばん豊かです。",
    'zh-CN': "{year}年的某个早晨。\n你醒来时厨房有声音——你不是一个人。一起喝咖啡聊今天，就算是琐碎闲聊也好，因为共享时间本身就好。\n你的工作与人相连：帮助、教导、一起创造。有些日子结束后反而更有能量。你珍惜真正帮到别人的感觉。\n周末常和人在一起——吃饭、聊天、笑。你在的地方总是温暖的。\n晚上会想起今天遇到的人，也期待明天再见谁。\n十年后你的生活充满关系——那对你就是最丰盛的生活。",
    'zh-TW': "{year}年的某個早晨。\n你醒來時廚房有聲音——你不是一個人。一起喝咖啡聊今天，瑣碎也沒關係，共享時間本身就好。\n你的工作與人相連。有些日子結束後反而更有能量。你珍惜真正幫到別人的感覺。\n週末常和人在一起。你在的地方總是溫暖的。\n十年後你的生活充滿關係——那對你就是最豐盛的生活。",
    vi: "Một buổi sáng năm {year}.\nBạn thức dậy nghe tiếng từ bếp — không một mình. Cùng uống cà phê, kể chuyện hôm nay; chuyện vụn vặt cũng ổn vì được chia sẻ thời gian.\nCông việc gắn với người: giúp, dạy, cùng tạo. Nhiều ngày kết thúc lại được nạp năng lượng. Bạn trân trọng cảm giác thật sự giúp được ai đó.\nCuối tuần thường có người — ăn, nói, cười. Chỗ bạn ở luôn ấm.\nTối nhớ người đã gặp và mong ngày mai gặp ai.\nSau 10 năm đời bạn đầy mối quan hệ — và đó là đời phong phú nhất.",
    id: "Suatu pagi di tahun {year}.\nKamu bangun mendengar suara dapur — tidak sendirian. Sarapan kopi dan obrolan hari ini; bahkan omong kosong pun enak karena berbagi waktu.\nPekerjaanmu terhubung dengan orang: membantu, mengajar, membangun bersama. Sering hari berakhir justru mengisi energi. Kamu menghargai rasa benar-benar membantu seseorang.\nAkhir pekan sering bersama orang — makan, bicara, tertawa. Tempatmu selalu hangat.\nMalam mengingat siapa yang ditemui dan menanti siapa besok.\n10 tahun lagi hidupmu penuh hubungan — itulah hidup terkaya bagimu.",
  },
  "집에서 좋아하는 것에 몰입하고 있는 장면. 조용하고 충만한 시간": {
    en: "Immersed at home in something I love — quiet and full",
    ja: "家で好きなことに没頭している場面。静かで充実した時間",
    'zh-CN': "在家沉浸于喜欢的事，安静而充实的时间",
    'zh-TW': "在家沉浸於喜歡的事，安靜而充實的時間",
    vi: "Ở nhà chìm vào điều mình thích — yên và đầy đủ",
    id: "Di rumah tenggelam dalam yang kusukai — tenang dan penuh",
  },
  "좋아하는 사람들과 함께 밥 먹거나 이야기하는 따뜻한 장면": {
    en: "A warm scene eating or talking with people I like",
    ja: "好きな人たちとご飯や話をする温かい場面",
    'zh-CN': "和喜欢的人一起吃饭或聊天的温暖场面",
    'zh-TW': "和喜歡的人一起吃飯或聊天的溫暖場面",
    vi: "Cảnh ấm ăn hoặc trò chuyện với người mình thích",
    id: "Adegan hangat makan atau ngobrol dengan orang yang kusukai",
  },
  "내가 좋아하는 카페나 작업 공간에서 개인 프로젝트를 하는 장면": {
    en: "Working on a personal project at a favorite café or workspace",
    ja: "好きなカフェや作業スペースで個人プロジェクトをする場面",
    'zh-CN': "在喜欢的咖啡馆或工作空间做个人项目",
    'zh-TW': "在喜歡的咖啡館或工作空間做個人項目",
    vi: "Làm dự án cá nhân ở quán cà phê hoặc không gian làm việc yêu thích",
    id: "Mengerjakan proyek pribadi di kafe atau ruang kerja favorit",
  },
  "여행 중이거나 새로운 곳을 탐험하고 있는 장면": {
    en: "Traveling or exploring somewhere new",
    ja: "旅行中か新しい場所を探検している場面",
    'zh-CN': "在旅行或探索新地方",
    'zh-TW': "在旅行或探索新地方",
    vi: "Đang du lịch hoặc khám phá nơi mới",
    id: "Sedang bepergian atau menjelajah tempat baru",
  },
  "소수의 깊은 관계. 많지 않아도 진짜로 통하는 사람들이면 충분하다": {
    en: "A few deep bonds — few is enough if we truly connect",
    ja: "少数の深い関係。本当に通じ合う人で十分",
    'zh-CN': "少数深厚的关系。真正相通的人就够了",
    'zh-TW': "少數深厚的關係。真正相通的人就夠了",
    vi: "Vài mối quan hệ sâu — không cần nhiều nếu thật sự thấu hiểu",
    id: "Sedikit hubungan mendalam — cukup jika benar-benar nyambung",
  },
  "가족과 가까운 친구들. 따뜻하고 안정적인 연결이 삶의 중심이다": {
    en: "Family and close friends — warm stable ties at life's center",
    ja: "家族と近い友達。温かく安定したつながりが中心",
    'zh-CN': "家人和亲近朋友。温暖稳定的连接是生活中心",
    'zh-TW': "家人和親近朋友。溫暖穩定的連接是生活中心",
    vi: "Gia đình và bạn thân — kết nối ấm ổn định là trung tâm",
    id: "Keluarga dan teman dekat — ikatan hangat stabil di pusat hidup",
  },
  "같은 방향을 바라보는 동료나 커뮤니티. 함께 성장하는 관계": {
    en: "Peers or community facing the same direction — growing together",
    ja: "同じ方向を見る同僚やコミュニティ。共に成長する関係",
    'zh-CN': "朝同一方向的同事或社群。一起成长",
    'zh-TW': "朝同一方向的同事或社群。一起成長",
    vi: "Đồng nghiệp hoặc cộng đồng cùng hướng — cùng phát triển",
    id: "Rekan atau komunitas searah — tumbuh bersama",
  },
  "다양한 사람들. 여러 분야의 사람들과 자유롭게 연결되는 것": {
    en: "Diverse people — freely connecting across many fields",
    ja: "さまざまな人と自由につながること",
    'zh-CN': "与各领域的人自由连接",
    'zh-TW': "與各領域的人自由連接",
    vi: "Kết nối tự do với nhiều lĩnh vực",
    id: "Terhubung bebas lintas bidang",
  },
  "나만의 시간. 좋아하는 것을 혼자 깊이 즐기는 시간": {
    en: "My own time — enjoying what I love alone, deeply",
    ja: "自分だけの時間。好きなことを深く楽しむ",
    'zh-CN': "属于自己的时间。独自深入享受喜欢的事",
    'zh-TW': "屬於自己的時間。獨自深入享受喜歡的事",
    vi: "Thời gian riêng — tận hưởng sâu điều mình thích một mình",
    id: "Waktu milikku — menikmati yang kusukai sendirian secara mendalam",
  },
  "사람들과 함께하는 시간. 대화하고 나누고 돌보는 시간": {
    en: "Time with people — talking, sharing, caring",
    ja: "人と一緒の時間。話し、分かち合い、支える",
    'zh-CN': "和人在一起的时间。交谈、分享、照顾",
    'zh-TW': "和人在一起的時間。交談、分享、照顧",
    vi: "Thời gian với người — trò chuyện, chia sẻ, chăm sóc",
    id: "Waktu bersama orang — bicara, berbagi, merawat",
  },
  "일과 성장에 투자하는 시간. 목표를 향해 나아가는 시간": {
    en: "Time invested in work and growth — moving toward goals",
    ja: "仕事と成長に投資する時間。目標へ進む",
    'zh-CN': "投入工作与成长的时间。朝目标前进",
    'zh-TW': "投入工作與成長的時間。朝目標前進",
    vi: "Thời gian cho việc và phát triển — tiến tới mục tiêu",
    id: "Waktu untuk kerja dan tumbuh — maju ke tujuan",
  },
  "새로운 경험을 만드는 시간. 여행·도전·탐험의 시간": {
    en: "Time making new experiences — travel, challenge, exploration",
    ja: "新しい経験をつくる時間。旅行・挑戦・探検",
    'zh-CN': "创造新体验的时间。旅行、挑战、探索",
    'zh-TW': "創造新體驗的時間。旅行、挑戰、探索",
    vi: "Thời gian tạo trải nghiệm mới — du lịch, thử thách, khám phá",
    id: "Waktu menciptakan pengalaman baru — perjalanan, tantangan, eksplorasi",
  },
  "목표·집중·성취·인정·발전": {
    en: "goals · focus · achievement · recognition · growth",
    ja: "目標・集中・達成・認め・発展",
    'zh-CN': "目标·专注·成就·认可·发展",
    'zh-TW': "目標·專注·成就·認可·發展",
    vi: "mục tiêu · tập trung · thành tựu · công nhận · phát triển",
    id: "tujuan · fokus · capaian · pengakuan · perkembangan",
  },
  "루틴·집중·균형·꾸준한 성장": {
    en: "routine · focus · balance · steady growth",
    ja: "ルーティン・集中・バランス・着実な成長",
    'zh-CN': "例行·专注·平衡·稳健成长",
    'zh-TW': "例行·專注·平衡·穩健成長",
    vi: "thói quen · tập trung · cân bằng · tăng trưởng vững",
    id: "rutinitas · fokus · keseimbangan · pertumbuhan stabil",
  },
  "지금보다 더 성장해 있을 것": {
    en: "Having grown more than now",
    ja: "今より成長していること",
    'zh-CN': "比现在更成长",
    'zh-TW': "比現在更成長",
    vi: "Đã phát triển hơn bây giờ",
    id: "Lebih tumbuh dibanding sekarang",
  },
  "사람과 연결되고 의미 있는 일": {
    en: "Meaningful work connected to people",
    ja: "人とつながり意味のある仕事",
    'zh-CN': "与人连接的有意义的工作",
    'zh-TW': "與人連接的有意義的工作",
    vi: "Công việc ý nghĩa gắn với người",
    id: "Pekerjaan bermakna terhubung dengan orang",
  },
  "함께 성장하는 동료·멘토·후배": {
    en: "Colleagues, mentors, juniors growing together",
    ja: "共に成長する同僚・メンター・後輩",
    'zh-CN': "一起成长的同事、导师、后辈",
    'zh-TW': "一起成長的同事、導師、後輩",
    vi: "Đồng nghiệp, mentor, đàn em cùng phát triển",
    id: "Rekan, mentor, junior yang tumbuh bersama",
  },
  "자유롭게 연결되는 다양한 사람들": {
    en: "Diverse people freely connecting",
    ja: "自由につながる多様な人たち",
    'zh-CN': "自由连接的各种各样的人",
    'zh-TW': "自由連接的各種各樣的人",
    vi: "Nhiều người đa dạng kết nối tự do",
    id: "Orang beragam yang terhubung bebas",
  },
  "지금보다 더 나답게 살고 있을 것": {
    en: "Living more as myself than now",
    ja: "今より自分らしく生きていること",
    'zh-CN': "比现在更活成自己",
    'zh-TW': "比現在更活成自己",
    vi: "Sống đúng mình hơn bây giờ",
    id: "Hidup lebih seperti diriku dibanding sekarang",
  },
  "나를 아껴주고 내가 아껴주는 사람들": {
    en: "People who cherish me and whom I cherish",
    ja: "自分を大切にし、私も大切にする人たち",
    'zh-CN': "珍惜我、也被我珍惜的人",
    'zh-TW': "珍惜我、也被我珍惜的人",
    vi: "Những người trân trọng tôi và tôi cũng trân trọng",
    id: "Orang yang menyayangiku dan kusayangi",
  },
  "지금보다 더 자유롭게 살고 있을 것": {
    en: "Living more freely than now",
    ja: "今より自由に生きていること",
    'zh-CN': "比现在更自由地生活",
    'zh-TW': "比現在更自由地生活",
    vi: "Sống tự do hơn bây giờ",
    id: "Hidup lebih bebas dibanding sekarang",
  },
  "함께할 수 있는 따뜻하고 넉넉한 집": {
    en: "A warm, generous home to share",
    ja: "一緒にいられる温かく広い家",
    'zh-CN': "能一起住的温暖宽敞的家",
    'zh-TW': "能一起住的溫暖寬敞的家",
    vi: "Ngôi nhà ấm rộng để cùng ở",
    id: "Rumah hangat dan lapang untuk bersama",
  },
  "같은 방향을 바라보는 동료와 커뮤니티": {
    en: "Colleagues and community facing the same direction",
    ja: "同じ方向を見る同僚とコミュニティ",
    'zh-CN': "朝同一方向的同事与社群",
    'zh-TW': "朝同一方向的同事與社群",
    vi: "Đồng nghiệp và cộng đồng cùng hướng",
    id: "Rekan dan komunitas searah",
  },
  "전문 분야에서 성과와 인정을 받는 일": {
    en: "Work with results and recognition in my field",
    ja: "専門分野で成果と認めを得る仕事",
    'zh-CN': "在专业领域获得成果与认可的工作",
    'zh-TW': "在專業領域獲得成果與認可的工作",
    vi: "Công việc có thành tích và được công nhận trong lĩnh vực",
    id: "Pekerjaan dengan hasil dan pengakuan di bidangku",
  },
  "나만의 루틴·나만의 공간·나만의 시간": {
    en: "My routine · my space · my time",
    ja: "自分のルーティン・空間・時間",
    'zh-CN': "我的例行·我的空间·我的时间",
    'zh-TW': "我的例行·我的空間·我的時間",
    vi: "Thói quen · không gian · thời gian của riêng tôi",
    id: "Rutinitasku · ruangku · waktuku",
  },
  "소수의 진짜 연결. 적지만 깊은 관계": {
    en: "A few real connections — few but deep",
    ja: "少数の本物のつながり。少なくても深い",
    'zh-CN': "少数真正的连接。少但深",
    'zh-TW': "少數真正的連接。少但深",
    vi: "Vài kết nối thật — ít nhưng sâu",
    id: "Sedikit koneksi nyata — sedikit tapi dalam",
  },
  "나만의 조용한 공간과 혼자 있는 시간": {
    en: "My quiet space and time alone",
    ja: "自分の静かな空間とひとりの時間",
    'zh-CN': "自己的安静空间和独处时间",
    'zh-TW': "自己的安靜空間和獨處時間",
    vi: "Không gian yên và thời gian một mình",
    id: "Ruang tenang dan waktu sendirian",
  },
  "새로운 공간·새로운 사람·새로운 경험": {
    en: "New spaces · new people · new experiences",
    ja: "新しい空間・人・経験",
    'zh-CN': "新空间·新人·新体验",
    'zh-TW': "新空間·新人·新體驗",
    vi: "Không gian mới · người mới · trải nghiệm mới",
    id: "Ruang baru · orang baru · pengalaman baru",
  },
  "원하는 목표를 효율적으로 달성하는 능력": {
    en: "Ability to efficiently achieve desired goals",
    ja: "望む目標を効率よく達成する能力",
    'zh-CN': "高效达成目标的能力",
    'zh-TW': "高效達成目標的能力",
    vi: "Khả năng đạt mục tiêu hiệu quả",
    id: "Kemampuan mencapai tujuan secara efisien",
  },
  "누군가와 나누는 식사·대화·소소한 연결": {
    en: "Meals, talk, and small connections with someone",
    ja: "誰かと分かち合う食事・会話・小さなつながり",
    'zh-CN': "与人分享的餐食、对话、小连接",
    'zh-TW': "與人分享的餐食、對話、小連接",
    vi: "Bữa ăn, trò chuyện, kết nối nhỏ với ai đó",
    id: "Makan, obrolan, dan koneksi kecil dengan seseorang",
  },
  "작업 공간이 있는 기능적이고 정돈된 집": {
    en: "A functional, tidy home with workspace",
    ja: "作業スペースがある機能的で整った家",
    'zh-CN': "有工作空间、功能性且整齐的家",
    'zh-TW': "有工作空間、功能性且整齊的家",
    vi: "Nhà tiện ích gọn gàng có chỗ làm việc",
    id: "Rumah fungsional rapi dengan ruang kerja",
  },
  "집중과 깊이가 필요한 독립적 전문 작업": {
    en: "Independent expert work needing focus and depth",
    ja: "集中と深さが必要な独立した専門作業",
    'zh-CN': "需要专注与深度的独立专业工作",
    'zh-TW': "需要專注與深度的獨立專業工作",
    vi: "Công việc chuyên môn độc lập cần tập trung và chiều sâu",
    id: "Kerja ahli mandiri yang butuh fokus dan kedalaman",
  },
  "사람들과 더 잘 연결되고 이해하는 능력": {
    en: "Ability to connect with and understand people better",
    ja: "人とよりよくつながり理解する能力",
    'zh-CN': "更好地与人连接并理解的能力",
    'zh-TW': "更好地與人連接並理解的能力",
    vi: "Khả năng kết nối và thấu hiểu người tốt hơn",
    id: "Kemampuan terhubung dan memahami orang lebih baik",
  },
  "가족·오랜 친구·새로 만난 따뜻한 사람들": {
    en: "Family, old friends, warmly met new people",
    ja: "家族・古い友達・新しく出会った温かい人たち",
    'zh-CN': "家人、老友、新认识的温暖的人",
    'zh-TW': "家人、老友、新認識的溫暖的人",
    vi: "Gia đình, bạn cũ, người mới ấm áp",
    id: "Keluarga, teman lama, orang baru yang hangat",
  },
  "성취감을 주는 일과 성장하고 있다는 느낌": {
    en: "Work that gives achievement and a sense of growing",
    ja: "達成感をくれる仕事と成長している感覚",
    'zh-CN': "带来成就感的工作与正在成长的感觉",
    'zh-TW': "帶來成就感的工作與正在成長的感覺",
    vi: "Công việc mang thành tựu và cảm giác đang lớn lên",
    id: "Pekerjaan yang memberi capaian dan rasa tumbuh",
  },
  "조용한 교외 또는 자연 가까운 아늑한 집": {
    en: "A cozy home in quiet suburbs or near nature",
    ja: "静かな郊外や自然に近い居心地の良い家",
    'zh-CN': "安静郊区或靠近自然的温馨之家",
    'zh-TW': "安靜郊區或靠近自然的溫馨之家",
    vi: "Nhà ấm gần ngoại ô yên hoặc thiên nhiên",
    id: "Rumah nyaman di pinggiran tenang atau dekat alam",
  },
  "자유·나만의 방식·예측 불가능한 설렘·개척": {
    en: "freedom · my way · unpredictable thrill · pioneering",
    ja: "自由・自分のやり方・予測不能なときめき・開拓",
    'zh-CN': "自由·自己的方式·不可预测的心动·开拓",
    'zh-TW': "自由·自己的方式·不可預測的心動·開拓",
    vi: "tự do · cách riêng · hồi hộp khó đoán · khai phá",
    id: "kebebasan · caraku · getaran tak terduga · merintis",
  },
  "어떤 환경에서도 적응하고 기회를 만드는 능력": {
    en: "Ability to adapt anywhere and create opportunities",
    ja: "どんな環境でも適応し機会をつくる能力",
    'zh-CN': "在任何环境适应并创造机会的能力",
    'zh-TW': "在任何環境適應並創造機會的能力",
    vi: "Khả năng thích nghi mọi nơi và tạo cơ hội",
    id: "Kemampuan beradaptasi di mana pun dan menciptakan peluang",
  },
  "전문성이 쌓인 분야에서 자부심 있게 하는 일": {
    en: "Work with pride in a field where expertise has grown",
    ja: "専門性が積み上がった分野で誇りを持ってする仕事",
    'zh-CN': "在已积累专业的领域自豪地工作",
    'zh-TW': "在已累積專業的領域自豪地工作",
    vi: "Công việc tự hào trong lĩnh vực đã dày chuyên môn",
    id: "Pekerjaan dengan bangga di bidang yang keahliannya menumpuk",
  },
  "지금보다 더 좋은 사람들과 둘러싸여 있을 것": {
    en: "Being surrounded by even better people than now",
    ja: "今より良い人たちに囲まれていること",
    'zh-CN': "被比现在更好的人环绕",
    'zh-TW': "被比現在更好的人環繞",
    vi: "Được bao quanh bởi người tốt hơn bây giờ",
    id: "Dikelilingi orang yang lebih baik dari sekarang",
  },
  "변화. 불확실성이 오히려 가능성이라는 걸 안다": {
    en: "Change — I know uncertainty is actually possibility",
    ja: "変化。不確かさこそ可能性だと知っている",
    'zh-CN': "变化。我知道不确定其实是可能",
    'zh-TW': "變化。我知道不確定其實是可能",
    vi: "Thay đổi — tôi biết sự không chắc chính là khả năng",
    id: "Perubahan — aku tahu ketidakpastian justru peluang",
  },
  "내가 좋아하는 분야를 깊이 있게 탐구하는 능력": {
    en: "Ability to deeply explore fields I love",
    ja: "好きな分野を深く探究する能力",
    'zh-CN': "深入探索喜欢领域的能力",
    'zh-TW': "深入探索喜歡領域的能力",
    vi: "Khả năng khám phá sâu lĩnh vực mình yêu",
    id: "Kemampuan mengeksplorasi mendalam bidang yang kusukai",
  },
  "실패. 과정이 나를 성장시킨다는 걸 경험으로 안다": {
    en: "Failure — I know from experience the process grows me",
    ja: "失敗。過程が成長させると経験で知っている",
    'zh-CN': "失败。我从经验知道过程让我成长",
    'zh-TW': "失敗。我從經驗知道過程讓我成長",
    vi: "Thất bại — tôi biết từ trải nghiệm rằng quá trình giúp tôi lớn",
    id: "Kegagalan — aku tahu dari pengalaman bahwa proses menumbuhkanku",
  },
  "지루하지 않은 삶. 새로운 것이 계속 생기는 일상": {
    en: "A life that isn't boring — new things keep appearing",
    ja: "退屈でない人生。新しいことが続く日常",
    'zh-CN': "不无聊的生活。不断有新事物的日常",
    'zh-TW': "不無聊的生活。不斷有新事物的日常",
    vi: "Cuộc sống không nhàm — luôn có điều mới",
    id: "Hidup yang tidak membosankan — selalu ada yang baru",
  },
  "나만의 방식으로 설계된 공간. 어디든 내 방식대로": {
    en: "A space designed my way — anywhere on my terms",
    ja: "自分のやり方で設計された空間。どこでも自分流",
    'zh-CN': "按自己方式设计的空间。何处都按我的方式",
    'zh-TW': "按自己方式設計的空間。何處都按我的方式",
    vi: "Không gian thiết kế theo cách tôi — đâu cũng theo tôi",
    id: "Ruang dirancang caraku — di mana pun dengan aturanku",
  },
  "자신의 커리어와 연결된 공간. 일과 삶이 가까운 곳": {
    en: "A space tied to my career — work and life close",
    ja: "キャリアとつながる空間。仕事と人生が近い場所",
    'zh-CN': "与职业相连的空间。工作与生活很近",
    'zh-TW': "與職業相連的空間。工作與生活很近",
    vi: "Không gian gắn sự nghiệp — việc và đời gần nhau",
    id: "Ruang terikat karier — kerja dan hidup berdekatan",
  },
  "장소에 자유로운 일. 이동이 일의 일부인 라이프스타일": {
    en: "Location-free work — mobility as part of the lifestyle",
    ja: "場所に自由な仕事。移動が仕事の一部のライフスタイル",
    'zh-CN': "不受地点限制的工作。移动即生活方式的一部分",
    'zh-TW': "不受地點限制的工作。移動即生活方式的一部分",
    vi: "Công việc không lệ thuộc nơi — di chuyển là một phần lối sống",
    id: "Kerja bebas lokasi — mobilitas bagian dari gaya hidup",
  },
  "다양한 배경의 넓은 연결 + 오래된 소수의 깊은 관계": {
    en: "Wide ties across backgrounds + a few deep old bonds",
    ja: "多様な背景の広いつながり＋古い少数の深い関係",
    'zh-CN': "跨背景的广泛连接 + 少数深厚的旧关系",
    'zh-TW': "跨背景的廣泛連接 + 少數深厚的舊關係",
    vi: "Kết nối rộng đa nền tảng + vài mối sâu lâu năm",
    id: "Jaringan luas lintas latar + sedikit ikatan lama yang dalam",
  },
  "전문 분야에서 인정받고 내 가능성을 최대한 실현하는 것": {
    en: "Being recognized in my field and fully realizing my potential",
    ja: "専門分野で認められ可能性を最大限に実現すること",
    'zh-CN': "在专业领域被认可并最大限度实现可能",
    'zh-TW': "在專業領域被認可並最大限度實現可能",
    vi: "Được công nhận trong lĩnh vực và phát huy tối đa tiềm năng",
    id: "Diakui di bidangku dan mewujudkan potensi sepenuhnya",
  },
  "고정되지 않은 공간. 어디서든 집처럼 살 수 있는 능력": {
    en: "Unfixed space — ability to live like home anywhere",
    ja: "固定されない空間。どこでも家のように暮らせる能力",
    'zh-CN': "不固定的空间。随处都能像家一样生活的能力",
    'zh-TW': "不固定的空間。隨處都能像家一樣生活的能力",
    vi: "Không gian không cố định — khả năng sống như ở nhà mọi nơi",
    id: "Ruang tak tetap — kemampuan hidup seperti di rumah di mana pun",
  },
  "기존 카테고리에 없는 나만의 일. 스스로 만들어낸 역할": {
    en: "My own work outside old categories — a role I made",
    ja: "既存カテゴリにない自分の仕事。自分でつくった役割",
    'zh-CN': "不在旧分类里的自己的工作。自己创造的角色",
    'zh-TW': "不在舊分類裡的自己的工作。自己創造的角色",
    vi: "Công việc ngoài danh mục cũ — vai trò tự tạo",
    id: "Pekerjaan di luar kategori lama — peran yang kuciptakan",
  },
  "소중한 사람들이 행복하고 함께하는 것. 관계의 풍요로움": {
    en: "Precious people happy together — richness of relationships",
    ja: "大切な人が幸せで一緒にいること。関係の豊かさ",
    'zh-CN': "珍爱的人幸福在一起。关系的丰盛",
    'zh-TW': "珍愛的人幸福在一起。關係的豐盛",
    vi: "Người quý hạnh phúc bên nhau — sự phong phú quan hệ",
    id: "Orang tersayang bahagia bersama — kekayaan hubungan",
  },
  "오늘의 성과를 점검하고 내일을 준비하며 마무리하는 모습": {
    en: "Reviewing today's results and preparing for tomorrow",
    ja: "今日の成果を点検し明日を準備して終える姿",
    'zh-CN': "检查今天成果并准备明天后收尾",
    'zh-TW': "檢查今天成果並準備明天後收尾",
    vi: "Rà soát thành quả hôm nay và chuẩn bị ngày mai",
    id: "Meninjau hasil hari ini dan bersiap untuk besok",
  },
  "혼자인 것. 나만의 시간이 나를 채운다는 걸 알게 됐다": {
    en: "Being alone — I've learned my own time fills me",
    ja: "ひとりであること。自分の時間が満たすと知った",
    'zh-CN': "独处。我已明白属于自己的时间能填满我",
    'zh-TW': "獨處。我已明白屬於自己的時間能填滿我",
    vi: "Ở một mình — tôi biết thời gian riêng làm đầy tôi",
    id: "Sendirian — aku tahu waktu milikku mengisiku",
  },
  "자유롭게 원하는 삶을 살아가는 것. 틀에 갇히지 않는 것": {
    en: "Living the life I want freely — not trapped in a frame",
    ja: "自由に望む人生を生きること。枠に囚われないこと",
    'zh-CN': "自由过想要的生活。不被框住",
    'zh-TW': "自由過想要的生活。不被框住",
    vi: "Sống đời mình muốn tự do — không bị giam khuôn",
    id: "Menjalani hidup yang kuinginkan bebas — tidak terjebak kerangka",
  },
  "즉흥적으로 저녁을 채우는 모습. 오늘의 끝도 예측 불가능하게": {
    en: "Filling the evening spontaneously — even day's end unpredictable",
    ja: "即興で夕方を埋める姿。終わりさえ予測不能に",
    'zh-CN': "即兴填满晚上。连一天的结束都不可预测",
    'zh-TW': "即興填滿晚上。連一天的結束都不可預測",
    vi: "Lấp đầy tối ứng biến — ngay cả kết thúc ngày cũng khó đoán",
    id: "Mengisi malam spontan — akhir hari pun tak terduga",
  },
  "좋아하는 책이나 콘텐츠를 즐기며 조용히 하루를 마무리하는 모습": {
    en: "Quietly ending the day with books or content I love",
    ja: "好きな本やコンテンツで静かに一日を終える姿",
    'zh-CN': "享受喜欢的书或内容，安静结束一天",
    'zh-TW': "享受喜歡的書或內容，安靜結束一天",
    vi: "Kết thúc ngày yên với sách hoặc nội dung yêu thích",
    id: "Mengakhiri hari dengan tenang menikmati buku atau konten kesukaan",
  },
  "소중한 사람과 오늘 하루 이야기를 나누며 따뜻하게 마무리하는 모습": {
    en: "Warmly wrapping up by sharing the day with someone precious",
    ja: "大切な人と今日を話し温かく終える姿",
    'zh-CN': "和珍爱的人聊今天，温暖收尾",
    'zh-TW': "和珍愛的人聊今天，溫暖收尾",
    vi: "Kết thúc ấm kể chuyện một ngày với người quý",
    id: "Menutup hari dengan hangat bercerita dengan orang tersayang",
  },
  "감정을 표현하는 것. 솔직한 연결이 삶을 풍요롭게 한다는 걸 안다": {
    en: "Expressing feelings — I know honest connection enriches life",
    ja: "感情を表現すること。正直なつながりが豊かにするのを知っている",
    'zh-CN': "表达情感。我知道真诚连接让生活丰盛",
    'zh-TW': "表達情感。我知道真誠連接讓生活豐盛",
    vi: "Bày tỏ cảm xúc — tôi biết kết nối chân thành làm đời phong phú",
    id: "Mengungkapkan perasaan — aku tahu koneksi jujur memperkaya hidup",
  },
  "내가 원하는 방식으로 조용히 살아갈 수 있는 것. 외부 기준이 아닌 나의 평화": {
    en: "Living quietly my own way — my peace, not outside standards",
    ja: "望むやり方で静かに生きられること。外の基準ではなく自分の平和",
    'zh-CN': "能按自己方式安静生活。不是外部标准，而是我的平静",
    'zh-TW': "能按自己方式安靜生活。不是外部標準，而是我的平靜",
    vi: "Sống yên theo cách mình — bình yên của tôi, không tiêu chuẩn ngoài",
    id: "Hidup tenang dengan caraku — damai milikku, bukan standar luar",
  },
  "AI가 그린 나의 10년 후: 내면 충만 생활형 🌿 알람 없이 일어나 커피 내리는 조용한 아침이 10년 후 내 일상이래... 이게 너무 나다 ㅋㅋ → 너의 10년 후는 어떤 모습이야?": {
    en: "AI paints my 10 years later: Inner Fulfillment 🌿 Quiet mornings without alarms brewing coffee — so me lol → What's yours?",
    ja: "AIが描く10年後：内面充実型🌿 アラームなしでコーヒーを淹れる静かな朝が日常らしい…まさに私→君の10年後は？",
    'zh-CN': "AI描绘我的十年后：内在充盈型🌿 不靠闹钟冲咖啡的安静早晨——太像我了→你的呢？",
    'zh-TW': "AI描繪我的十年後：內在充盈型🌿 不靠鬧鐘沖咖啡的安靜早晨——太像我了→你的呢？",
    vi: "AI vẽ 10 năm sau của tôi: Sung mãn nội tâm 🌿 Sáng yên không báo thức pha cà phê — đúng tôi quá → Còn bạn?",
    id: "AI menggambar 10 tahun lagi-ku: Pemenuhan Batin 🌿 Pagi tenang tanpa alarm menyeduh kopi — banget aku → Kalau kamu?",
  },
  "AI가 그린 나의 10년 후: 관계 풍요 생활형 🌸 따뜻한 사람들로 가득한 삶이 내 10년 후래... 식탁에서 함께 아침 먹는 장면 읽으면서 뭔가 찡했음 → 너의 10년 후는?": {
    en: "AI paints my 10 years later: Relationship Abundance 🌸 A life full of warm people — breakfast table scene hit me → Yours?",
    ja: "AIが描く10年後：関係豊か型🌸 温かい人で満ちた人生らしい…食卓の朝ごはんにグッときた→君は？",
    'zh-CN': "AI描绘我的十年后：关系丰盛型🌸 充满温暖的人的生活——餐桌早餐那幕好戳→你的呢？",
    'zh-TW': "AI描繪我的十年後：關係豐盛型🌸 充滿溫暖的人的生活——餐桌早餐那幕好戳→你的呢？",
    vi: "AI vẽ 10 năm sau: Phong phú quan hệ 🌸 Đời đầy người ấm — cảnh ăn sáng khiến tôi xúc động → Còn bạn?",
    id: "AI menggambar 10 tahun lagi: Kelimpahan Relasi 🌸 Hidup penuh orang hangat — adegan sarapan bikin terharu → Kalau kamu?",
  },
  "AI가 그린 나의 10년 후: 꾸준한 성장 생활형 📖 균형잡히고 꾸준한 삶이 내 10년 후래... 루틴대로 사는 거 맞음 ㅋㅋ → 너의 10년 후는 어떤 모습이야?": {
    en: "AI paints my 10 years later: Steady Growth 📖 Balanced steady life — yeah I live by routines lol → What's yours?",
    ja: "AIが描く10年後：着実成長型📖 バランスの取れた着実な人生らしい…ルーティン生活あるある→君は？",
    'zh-CN': "AI描绘我的十年后：稳健成长型📖 平衡稳健的生活——我就是例行控哈哈→你的呢？",
    'zh-TW': "AI描繪我的十年後：穩健成長型📖 平衡穩健的生活——我就是例行控哈哈→你的呢？",
    vi: "AI vẽ 10 năm sau: Tăng trưởng vững 📖 Đời cân bằng đều đặn — đúng tôi sống theo thói quen → Còn bạn?",
    id: "AI menggambar 10 tahun lagi: Pertumbuhan Stabil 📖 Hidup seimbang konsisten — iya aku hidup pakai rutinitas → Kalau kamu?",
  },
  "AI가 그린 나의 10년 후: 전문 성취 생활형 🏆 10년 후에 분야에서 인정받는 사람이 돼있대... 지금부터 열심히 해야겠다는 생각 듦 → 너의 10년 후는?": {
    en: "AI paints my 10 years later: Professional Achievement 🏆 Recognized in my field in 10 years — time to work hard → Yours?",
    ja: "AIが描く10年後：専門達成型🏆 分野で認められる人になってるらしい…今から頑張ろう→君は？",
    'zh-CN': "AI描绘我的十年后：专业成就型🏆 十年后在领域被认可——得开始努力了→你的呢？",
    'zh-TW': "AI描繪我的十年後：專業成就型🏆 十年後在領域被認可——得開始努力了→你的呢？",
    vi: "AI vẽ 10 năm sau: Thành tựu chuyên môn 🏆 Được công nhận trong lĩnh vực — phải cố từ giờ → Còn bạn?",
    id: "AI menggambar 10 tahun lagi: Prestasi Profesional 🏆 Diakui di bidangku — harus kerja keras dari sekarang → Kalau kamu?",
  },
  "AI가 그린 나의 10년 후: 활동적 탐험 생활형 🌍 10년 후에도 매주 다른 곳에 있는 삶이래... 맞음 나 그렇게 살고 싶음 ㅋㅋ → 너의 10년 후는 어떤 모습이야?": {
    en: "AI paints my 10 years later: Active Explorer 🌍 Still somewhere new each week — yes I want that lol → What's yours?",
    ja: "AIが描く10年後：活動的探検型🌍 毎週違う場所にいる生活らしい…それがいい→君は？",
    'zh-CN': "AI描绘我的十年后：活力探索型🌍 十年后每周还在不同地方——我想要这样→你的呢？",
    'zh-TW': "AI描繪我的十年後：活力探索型🌍 十年後每週還在不同地方——我想要這樣→你的呢？",
    vi: "AI vẽ 10 năm sau: Thám hiểm năng động 🌍 Vẫn mỗi tuần một nơi khác — đúng ý tôi → Còn bạn?",
    id: "AI menggambar 10 tahun lagi: Penjelajah Aktif 🌍 Masih tiap minggu di tempat beda — iya aku mau begitu → Kalau kamu?",
  },
  "AI가 그린 나의 10년 후: 자유 개척 생활형 🚀 아무도 예측 못 하는 나만의 삶이래... 이거 읽으면서 진짜 그렇게 살고 싶다는 생각 → 너의 10년 후는?": {
    en: "AI paints my 10 years later: Free Pioneer 🚀 A life nobody can predict — reading this made me want it → Yours?",
    ja: "AIが描く10年後：自由開拓型🚀 誰も予測できない自分の人生らしい…そう生きたい→君は？",
    'zh-CN': "AI描绘我的十年后：自由开拓型🚀 没人能预测的自己的生活——看完真想那样活→你的呢？",
    'zh-TW': "AI描繪我的十年後：自由開拓型🚀 沒人能預測的自己的生活——看完真想那樣活→你的呢？",
    vi: "AI vẽ 10 năm sau: Khai phá tự do 🚀 Đời không ai đoán được — đọc xong muốn sống vậy → Còn bạn?",
    id: "AI menggambar 10 tahun lagi: Perintis Bebas 🚀 Hidup yang tak terduga — baca ini bikin ingin hidup begitu → Kalau kamu?",
  },
  "{year}년 어느 평일입니다.\n오전 7시에 눈을 뜹니다. 준비된 루틴이 있습니다. 운동이거나 글쓰기이거나 공부이거나. 하루를 제대로 시작하는 자신만의 의식이 있고 그것이 오늘의 리듬을 만듭니다.\n일은 당신이 선택한 분야에서 꽤 깊은 전문성을 쌓아온 상태입니다. 10년 전 지금의 당신이 막연하게 원했던 것들이 꽤 많이 이뤄져 있습니다. 모든 것이 완벽하진 않지만 내가 가고 있는 방향에 대한 확신이 있습니다.\n오후엔 집중해서 일하고 퇴근 후엔 온전히 나를 위한 시간입니다. 좋아하는 것을 배우거나 취미에 투자하거나 그냥 쉬거나. 일과 삶의 경계가 분명하고 그것이 오히려 두 영역 모두를 더 잘하게 만들어줍니다.\n주변엔 함께 성장하는 사람들이 있습니다. 같은 관심사를 가진 동료, 서로 자극을 주는 커뮤니티. 혼자가 아니라 같은 방향을 바라보는 사람들과 함께 나아가고 있습니다.\n10년 후 당신의 하루는 균형 잡혀 있습니다. 치우치지 않고 꾸준히. 그것이 당신의 성장 방식입니다.": {
    en: "It's a weekday in {year}.\nYou wake at 7 with a routine — workout, writing, or study — a ritual that sets the day's rhythm.\nIn your field you've built real expertise; many vague wishes from 10 years ago are real now. Not perfect, but you trust your direction.\nAfternoons are focused work; after work is fully yours. Clear boundaries make both sides better.\nAround you are people growing the same way — colleagues and community facing forward together.\nYour day in 10 years is balanced — steady, not extreme. That is how you grow.",
    ja: "{year}年のある平日です。\n7時に起き、運動や執筆などのルーティンで一日のリズムをつくります。\n選んだ分野で専門性が積み上がり、10年前の漠然とした願いは多く叶っています。完璧ではなくても方向への確信があります。\n午後は集中して働き、退勤後は自分の時間。境界がはっきりしているから両方うまくいきます。\n同じ方向の仲間と共に。10年後の一日はバランスが取れ、着実です。それが成長の仕方です。",
    'zh-CN': "{year}年的某个工作日。\n七点起床，用运动或写作等例行开启节奏。\n在所选领域专业已深，十年前模糊的愿望很多已成真。不完美，但方向有把握。\n下午专注工作，下班后完全属于自己。边界清晰反而两边都更好。\n周围是同向成长的人。十年后的一天平衡、稳健——这就是你的成长方式。",
    'zh-TW': "{year}年的某個工作日。\n七點起床，用運動或寫作等例行開啟節奏。\n在所選領域專業已深，十年前模糊的願望很多已成真。不完美，但方向有把握。\n下午專注工作，下班後完全屬於自己。十年後的一天平衡、穩健——這就是你的成長方式。",
    vi: "Một ngày thường năm {year}.\nDậy lúc 7 với thói quen — tập, viết, học — tạo nhịp cho ngày.\nChuyên môn trong lĩnh vực đã dày; nhiều ước mơ mơ hồ 10 năm trước đã thành. Chưa hoàn hảo nhưng tin hướng đi.\nChiều tập trung làm; tan làm là thời gian của mình. Ranh giới rõ giúp cả hai phía tốt hơn.\nQuanh bạn là người cùng hướng. Ngày sau 10 năm cân bằng, vững vàng — đó là cách bạn lớn lên.",
    id: "Suatu hari kerja di tahun {year}.\nBangun jam 7 dengan rutinitas — olahraga, menulis, belajar — membentuk ritme hari.\nKeahlian di bidangmu sudah dalam; banyak keinginan kabur 10 tahun lalu sudah nyata. Belum sempurna, tapi yakin arah.\nSore fokus kerja; setelah itu sepenuhnya milikmu. Batas jelas membuat keduanya lebih baik.\nDi sekitarmu orang searah. Harimu 10 tahun lagi seimbang dan stabil — itulah cara kamu tumbuh.",
  },
  "{year}년 어느 아침입니다.\n이른 시간에 일어납니다. 오늘 해야 할 것들이 이미 머릿속에 정리돼 있습니다. 커피를 마시며 오늘의 가장 중요한 것 하나를 먼저 떠올립니다. 그것을 끝내면 오늘은 성공한 날입니다.\n당신이 하는 일은 10년 전 당신이 원했던 방향으로 뻗어있습니다. 분야에서 이름이 알려졌거나 팀을 이끌거나 어떤 방식으로든 성과가 눈에 보입니다. 당신의 전문성을 인정해주는 사람들이 생겼고 그 인정이 더 잘하고 싶다는 동력이 됩니다.\n물론 쉽지 않은 날도 있습니다. 목표가 있는 사람에게 압박은 친구처럼 따라다닙니다. 그러나 10년 후의 당신은 그 압박을 다루는 법을 배웠습니다. 밀고 나가야 할 때와 쉬어야 할 때를 압니다.\n저녁엔 오늘 한 것들을 돌아봅니다. 충분했는지, 더 잘할 수 있는 게 있는지. 자기 자신에게 엄격하지만 그만큼 결과도 따라옵니다.\n10년 후 당신의 삶에는 성취가 있습니다. 그리고 그것이 당신을 앞으로 나아가게 하는 힘입니다.": {
    en: "It's a morning in {year}.\nYou rise early with today's tasks already sorted. Over coffee you pick the one most important thing — finish that and the day succeeds.\nYour work stretches toward what you wanted 10 years ago. You're known in your field, leading, or showing clear results. Recognition fuels wanting to do better.\nHard days still come; pressure follows people with goals. But you've learned when to push and when to rest.\nAt night you review: enough? better next time? Strict with yourself — and results follow.\nIn 10 years your life has achievement — and that drives you forward.",
    ja: "{year}年のある朝です。\n早く起き、今日やることは整理済み。コーヒーを飲みながら最重要の一つを思い、それを終えたら成功の日。\n仕事は10年前の望んだ方向へ伸び、分野で名が知られ成果が見えます。認めが動力になります。\n厳しい日もありますが、押す時と休む時を知っています。\n夜は振り返り、自分に厳しく、結果がついてきます。\n10年後の人生には達成があり、それが前へ進む力です。",
    'zh-CN': "{year}年的某个早晨。\n你早起，今天的事已理清。喝着咖啡先抓住最重要的一件——做完就是成功的一天。\n工作朝十年前想要的方向延伸，领域里有名声或成果。认可成为想做得更好的动力。\n也有不容易的日子，但你学会了何时推进、何时休息。\n晚上复盘：够不够？还能更好吗？对自己严格，结果也跟着来。\n十年后你的生活里有成就——那就是推你向前的力量。",
    'zh-TW': "{year}年的某個早晨。\n你早起，今天的事已理清。喝著咖啡先抓住最重要的一件——做完就是成功的一天。\n工作朝十年前想要的方向延伸。認可成為想做得更好的動力。\n你學會了何時推進、何時休息。晚上複盤，對自己嚴格，結果也跟著來。\n十年後你的生活裡有成就——那就是推你向前的力量。",
    vi: "Một buổi sáng năm {year}.\nDậy sớm, việc hôm nay đã sắp sẵn. Uống cà phê, chọn một điều quan trọng nhất — xong là ngày thành công.\nCông việc vươn theo hướng bạn muốn từ 10 năm trước. Có tên tuổi hoặc thành tích rõ. Sự công nhận tiếp thêm động lực.\nNgày khó vẫn có, nhưng bạn biết lúc nào đẩy, lúc nào nghỉ.\nTối nhìn lại: đủ chưa? có thể tốt hơn? Nghiêm với mình — và kết quả theo sau.\nSau 10 năm đời bạn có thành tựu — đó là lực đẩy phía trước.",
    id: "Suatu pagi di tahun {year}.\nBangun pagi, tugas hari ini sudah tersusun. Sambil kopi, pilih satu yang paling penting — selesai itu, hari sukses.\nPekerjaanmu menjulur ke arah yang kauinginkan 10 tahun lalu. Ada nama atau hasil nyata. Pengakuan jadi bahan bakar.\nHari sulit tetap ada, tapi kamu tahu kapan mendorong dan kapan istirahat.\nMalam meninjau: cukup? bisa lebih baik? Tegas pada diri — dan hasil mengikuti.\n10 tahun lagi hidupmu punya capaian — itulah daya dorong maju.",
  },
  "{year}년 어느 날입니다.\n오늘 어느 도시에 있는지는 나중에 말씀드릴게요. 아마 지난주과는 다른 곳일 것입니다. 당신의 10년 후는 한 자리에 머물지 않습니다.\n아침을 낯선 카페에서 시작할 수도 있고 오랜 친구의 도시에서 깰 수도 있고 오래 전부터 가보고 싶었던 곳에서 눈을 뜰 수도 있습니다. 어디에 있든 당신은 그 공간을 금방 자신의 것으로 만듭니다.\n당신이 하는 일은 장소에 구애받지 않습니다. 어디서든 할 수 있거나 이동 자체가 일의 일부이거나. 10년 전 원했던 자유로운 방식으로 일하고 있습니다.\n새로운 사람을 만나는 것이 자연스럽습니다. 다양한 배경의 사람들과 연결되고 짧지만 진한 교류를 합니다. 물론 오래된 소중한 사람들도 있습니다. 거리가 멀어도 연결은 유지됩니다.\n저녁엔 오늘 새로 발견한 것들을 떠올립니다. 새로운 음식, 새로운 골목, 새로운 대화.\n10년 후 당신의 삶은 계속 새롭습니다. 그리고 그것이 당신을 살아있게 만드는 에너지입니다.": {
    en: "It's a day in {year}.\nWhich city? I'll tell you later — probably not last week's. Your 10 years later doesn't stay put.\nMorning might start in a new café, a friend's city, or a place you've long wanted. Anywhere, you make the space yours fast.\nWork isn't tied to place — remote or travel as part of the job — the free way you wanted 10 years ago.\nMeeting new people feels natural: short but vivid ties across backgrounds, plus old precious bonds kept across distance.\nAt night you recall today's finds: food, alleys, talk.\nYour life keeps renewing — and that energy keeps you alive.",
    ja: "{year}年のある日です。\n今日どの街かは後で。先週とは違うはず。10年後は一か所に留まりません。\n朝は知らないカフェ、友人の街、行きたかった場所かもしれません。どこでもすぐ自分の空間にします。\n仕事は場所に縛られず、10年前に望んだ自由な働き方です。\n新しい人との短い濃い交流も自然。古い大切な人とも距離を超えてつながります。\n夜は新しい発見を思い出し、人生は更新され続け、それが生きるエネルギーです。",
    'zh-CN': "{year}年的某一天。\n今天在哪座城市？稍后再说——大概和上周不同。你的十年后不会停在一处。\n早晨可能在陌生咖啡店、朋友的城市，或向往已久的地方。无论何处，你很快把空间变成自己的。\n工作不受地点束缚，正是十年前想要的自由方式。\n认识新人和短而浓的交流很自然；久违的重要关系也隔着距离保持。\n晚上回想今天的新发现。生活持续更新——那就是让你活着的能量。",
    'zh-TW': "{year}年的某一天。\n今天在哪座城市？稍後再說——大概和上週不同。你的十年後不會停在一處。\n無論何處，你很快把空間變成自己的。工作不受地點束縛。\n認識新人和短而濃的交流很自然。晚上回想今天的新發現。生活持續更新——那就是讓你活著的能量。",
    vi: "Một ngày năm {year}.\nHôm nay ở thành phố nào? Để sau — có lẽ khác tuần trước. 10 năm sau của bạn không đứng yên một chỗ.\nSáng có thể ở quán lạ, thành phố bạn cũ, hoặc nơi từng muốn đến. Ở đâu bạn cũng sớm biến thành của mình.\nCông việc không lệ thuộc nơi — đúng kiểu tự do từng muốn.\nGặp người mới rất tự nhiên; quan hệ cũ quý vẫn giữ dù xa.\nTối nhớ những điều mới hôm nay. Đời cứ mới — và đó là năng lượng khiến bạn sống.",
    id: "Suatu hari di tahun {year}.\nKota mana hari ini? Nanti saja — mungkin beda dari minggu lalu. 10 tahun lagi-mu tidak menetap.\nPagi bisa di kafe asing, kota teman, atau tempat yang lama diinginkan. Di mana pun, cepat jadi milikmu.\nKerja tidak terikat lokasi — cara bebas yang kauinginkan dulu.\nMenemukan orang baru terasa alami; ikatan lama tetap dijaga meski jauh.\nMalam mengingat temuan hari ini. Hidup terus baru — itulah energi yang membuatmu hidup.",
  },
  "{year}년 어느 날입니다.\n오늘 당신의 하루는 아무도 예측하지 못합니다. 당신 자신도 어젯밤까지는 몰랐을 것입니다.\n누군가 10년 전 당신에게 지금의 삶을 설명해줬다면 믿지 못했을 것입니다. 당신이 선택한 방향이 처음엔 비현실적으로 보였을지 모릅니다. 그러나 당신은 그 길을 갔습니다. 그리고 지금은 그것이 당신의 삶입니다.\n하는 일이 기존 카테고리에 딱 맞지 않을 수 있습니다. 여러 가지를 동시에 하고 있거나 스스로 만들어낸 역할을 하고 있거나. 남이 정해준 틀이 아닌 나만의 방식이 있습니다.\n오늘 당신은 자신이 선택한 일을 합니다. 자신이 선택한 사람들과 있습니다. 자신이 원하는 방식으로 시간을 씁니다.\n완벽하지 않습니다. 예측 불가능한 부분도 있습니다. 그러나 그것이 당신이 원하는 삶입니다. 틀 안에 갇히지 않은 삶. 스스로 설계한 삶.\n10년 후 당신의 하루는 자유입니다. 그리고 그 자유는 10년의 도전이 만들어낸 것입니다.": {
    en: "It's a day in {year}.\nNobody can predict today's shape — maybe not even you last night.\nIf someone described this life 10 years ago, you might not have believed it. The path looked unrealistic at first — but you took it, and now it is your life.\nYour work may not fit old labels: several things at once, or a role you invented. Your way, not someone else's frame.\nToday you do what you chose, with people you chose, on your terms.\nNot perfect. Unpredictable parts remain. But this is the life you wanted — unboxed, self-designed.\nYour day in 10 years is freedom — built by a decade of daring.",
    ja: "{year}年のある日です。\n今日の一日は誰も予測できません。昨夜の自分も知らなかったかもしれません。\n10年前に今の人生を説明されたら信じなかったかも。最初は非現実に見えた道を進み、今それが人生です。\n仕事は既存の枠に収まらないかもしれません。自分でつくった役割、自分のやり方。\n今日は選んだ仕事、選んだ人、望む時間の使い方。完璧ではなく予測不能でも、枠に囚われない自分設計の人生。\n10年後の一日は自由。10年の挑戦がつくりました。",
    'zh-CN': "{year}年的某一天。\n今天没人能预测——或许昨晚的你也不知道。\n若十年前有人描述现在的生活，你可能不信。路起初像不现实，但你走了，现在这就是你的人生。\n工作可能不在旧分类里：同时做几件事，或自己造出的角色。是你的方式，不是别人的框。\n今天做自己选的事，和自己选的人，按自己想要的方式用时间。不完美、有不可预测，却是你想要的——不被框住、自己设计。\n十年后的一天是自由——十年挑战铸成的。",
    'zh-TW': "{year}年的某一天。\n今天沒人能預測。若十年前有人描述現在的生活，你可能不信。你走了那條路，現在這就是你的人生。\n工作可能不在舊分類裡。今天做自己選的事，和自己選的人。不完美卻是你想要的——不被框住、自己設計。\n十年後的一天是自由——十年挑戰鑄成的。",
    vi: "Một ngày năm {year}.\nKhông ai đoán được hôm nay — có khi chính bạn đêm qua cũng không.\nNếu ai mô tả đời này từ 10 năm trước, bạn có thể không tin. Con đường từng như phi thực — nhưng bạn đã đi, và giờ đó là đời bạn.\nCông việc có thể không khớp danh mục cũ; vai trò tự tạo, cách của bạn.\nHôm nay làm việc đã chọn, với người đã chọn, theo cách muốn. Chưa hoàn hảo, khó đoán — nhưng đúng đời bạn muốn: không bị nhốt, tự thiết kế.\nNgày sau 10 năm là tự do — do một thập kỷ dám làm tạo nên.",
    id: "Suatu hari di tahun {year}.\nTak ada yang bisa menebak hari ini — mungkin kamu semalam juga tidak.\nJika seseorang menjelaskan hidup ini 10 tahun lalu, mungkin tak percaya. Jalannya tampak tidak realistis — tapi kamu menempuhnya, dan kini itulah hidupmu.\nPekerjaanmu mungkin tak pas kategori lama; peran yang kuciptakan, caraku.\nHari ini kerjakan yang kau pilih, dengan orang yang kau pilih, dengan caramu. Tidak sempurna, ada yang tak terduga — tapi itu hidup yang kauinginkan: tidak terkunci kerangka, dirancang sendiri.\nHarimu 10 tahun lagi adalah kebebasan — dibuat oleh satu dekade keberanian.",
  },
};

function tr(koText: string): Record<string, string> {
  const x = TR[koText] || {};
  return L({
    ko: koText,
    en: x.en ?? koText,
    ja: x.ja ?? koText,
    'zh-CN': x['zh-CN'] ?? koText,
    'zh-TW': x['zh-TW'] ?? koText,
    vi: x.vi ?? koText,
    id: x.id ?? koText,
  });
}

function ko(text: string): Record<string, string> {
  return tr(text);
}

function opt(text: string, score: number): { text: Record<string, string>; score: number } {
  return { text: tr(text), score };
}

function section(title: string, content: string): Phase3AiFuture10YearsResultSection {
  return { title: tr(title), content: tr(content) };
}

export interface Phase3AiFuture10YearsQuestion {
  id: number;
  question: Record<string, string>;
  options: { text: Record<string, string>; score: number }[];
}

export interface Phase3AiFuture10YearsResultSection {
  title: Record<string, string>;
  content: Record<string, string>;
}

export interface Phase3AiFuture10YearsResult {
  type: string;
  emoji: string;
  title: Record<string, string>;
  shortDescription: Record<string, string>;
  description: Record<string, string>;
  keywords: Record<string, string>;
  sections: Phase3AiFuture10YearsResultSection[];
  shareMessage: Record<string, string>;
}

export function getPhase3AiFuture10YearsTargetYear(baseYear?: number): number {
  const y = baseYear ?? new Date().getFullYear();
  return y + 10;
}

/** 결과 문구의 {year}를 (올해+10)으로 치환 */
export function formatPhase3AiFuture10YearsText(
  text: string,
  baseYear?: number
): string {
  return text.replace(/\{year\}/g, String(getPhase3AiFuture10YearsTargetYear(baseYear)));
}

export function calculatePhase3AiFuture10YearsResult(answers: number[]): string {
  const total = answers.reduce((sum, s) => sum + (s ?? 0), 0);
  if (total <= 5) return 'Type1';
  if (total <= 11) return 'Type2';
  if (total <= 19) return 'Type3';
  if (total <= 27) return 'Type4';
  if (total <= 33) return 'Type5';
  return 'Type6';
}

export const phase3AiFuture10YearsQuestions: Phase3AiFuture10YearsQuestion[] = [
  {
    id: 1,
    question: ko('10년 후 내가 살고 싶은 공간은?'),
    options: [
      opt('조용한 교외나 자연 근처의 작고 아늑한 집. 혼자만의 공간이 충분한 곳', 0),
      opt('가족이나 가까운 사람들과 함께할 수 있는 넓고 따뜻한 집', 1),
      opt('도심과 가까우면서도 작업실이나 서재가 있는 기능적인 공간', 2),
      opt('어디에 있는지는 중요하지 않다. 필요하면 옮길 수 있는 유연한 공간', 3),
    ],
  },
  {
    id: 2,
    question: ko('10년 후 월요일 아침을 상상한다면?'),
    options: [
      opt('알람 없이 일어나 조용히 커피를 내리고 책을 읽는 아침', 0),
      opt('가족이나 소중한 사람과 함께 아침 식사를 하는 따뜻한 시간', 1),
      opt('계획된 루틴대로 움직이며 하루를 준비하는 효율적인 아침', 2),
      opt('오늘 뭘 할지 그날 결정하는 즉흥적이고 자유로운 아침', 3),
    ],
  },
  {
    id: 3,
    question: ko('10년 후 나의 일은 어떤 모습이길 원하나요?'),
    options: [
      opt('조용히 혼자 집중할 수 있는 일. 깊이 있는 결과물이 쌓이는 것', 0),
      opt('사람들과 연결되고 누군가에게 도움이 되는 의미 있는 일', 1),
      opt('전문성과 성과가 인정받는 일. 내 커리어에 자부심이 있는 것', 2),
      opt('자유롭게 내 방식으로 할 수 있는 일. 누가 정해준 틀이 없는 것', 3),
    ],
  },
  {
    id: 4,
    question: ko('10년 후 주말 오후에 내가 있을 것 같은 장면은?'),
    options: [
      opt('집에서 좋아하는 것에 몰입하고 있는 장면. 조용하고 충만한 시간', 0),
      opt('좋아하는 사람들과 함께 밥 먹거나 이야기하는 따뜻한 장면', 1),
      opt('내가 좋아하는 카페나 작업 공간에서 개인 프로젝트를 하는 장면', 2),
      opt('여행 중이거나 새로운 곳을 탐험하고 있는 장면', 3),
    ],
  },
  {
    id: 5,
    question: ko('10년 후 나에게 가장 중요한 관계는?'),
    options: [
      opt('소수의 깊은 관계. 많지 않아도 진짜로 통하는 사람들이면 충분하다', 0),
      opt('가족과 가까운 친구들. 따뜻하고 안정적인 연결이 삶의 중심이다', 1),
      opt('같은 방향을 바라보는 동료나 커뮤니티. 함께 성장하는 관계', 2),
      opt('다양한 사람들. 여러 분야의 사람들과 자유롭게 연결되는 것', 3),
    ],
  },
  {
    id: 6,
    question: ko('10년 후 나의 하루에서 가장 많은 시간을 차지하는 것은?'),
    options: [
      opt('나만의 시간. 좋아하는 것을 혼자 깊이 즐기는 시간', 0),
      opt('사람들과 함께하는 시간. 대화하고 나누고 돌보는 시간', 1),
      opt('일과 성장에 투자하는 시간. 목표를 향해 나아가는 시간', 2),
      opt('새로운 경험을 만드는 시간. 여행·도전·탐험의 시간', 3),
    ],
  },
  {
    id: 7,
    question: ko('10년 후 나에게 성공이란?'),
    options: [
      opt('내가 원하는 방식으로 조용히 살아갈 수 있는 것. 외부 기준이 아닌 나의 평화', 0),
      opt('소중한 사람들이 행복하고 함께하는 것. 관계의 풍요로움', 1),
      opt('전문 분야에서 인정받고 내 가능성을 최대한 실현하는 것', 2),
      opt('자유롭게 원하는 삶을 살아가는 것. 틀에 갇히지 않는 것', 3),
    ],
  },
  {
    id: 8,
    question: ko('10년 후 내 삶에 반드시 있어야 하는 것은?'),
    options: [
      opt('나만의 조용한 공간과 혼자 있는 시간', 0),
      opt('나를 아껴주고 내가 아껴주는 사람들', 1),
      opt('성취감을 주는 일과 성장하고 있다는 느낌', 2),
      opt('지루하지 않은 삶. 새로운 것이 계속 생기는 일상', 3),
    ],
  },
  {
    id: 9,
    question: ko('10년 후 가장 갖고 싶은 능력은?'),
    options: [
      opt('내가 좋아하는 분야를 깊이 있게 탐구하는 능력', 0),
      opt('사람들과 더 잘 연결되고 이해하는 능력', 1),
      opt('원하는 목표를 효율적으로 달성하는 능력', 2),
      opt('어떤 환경에서도 적응하고 기회를 만드는 능력', 3),
    ],
  },
  {
    id: 10,
    question: ko('10년 후 저녁 시간을 보내는 나의 모습은?'),
    options: [
      opt('좋아하는 책이나 콘텐츠를 즐기며 조용히 하루를 마무리하는 모습', 0),
      opt('소중한 사람과 오늘 하루 이야기를 나누며 따뜻하게 마무리하는 모습', 1),
      opt('오늘의 성과를 점검하고 내일을 준비하며 마무리하는 모습', 2),
      opt('즉흥적으로 저녁을 채우는 모습. 오늘의 끝도 예측 불가능하게', 3),
    ],
  },
  {
    id: 11,
    question: ko('10년 후 내가 두려워하지 않을 것은?'),
    options: [
      opt('혼자인 것. 나만의 시간이 나를 채운다는 걸 알게 됐다', 0),
      opt('감정을 표현하는 것. 솔직한 연결이 삶을 풍요롭게 한다는 걸 안다', 1),
      opt('실패. 과정이 나를 성장시킨다는 걸 경험으로 안다', 2),
      opt('변화. 불확실성이 오히려 가능성이라는 걸 안다', 3),
    ],
  },
  {
    id: 12,
    question: ko('지금 이 순간 10년 후의 나에게 가장 바라는 것은?'),
    options: [
      opt('지금보다 더 나답게 살고 있을 것', 0),
      opt('지금보다 더 좋은 사람들과 둘러싸여 있을 것', 1),
      opt('지금보다 더 성장해 있을 것', 2),
      opt('지금보다 더 자유롭게 살고 있을 것', 3),
    ],
  },
];

export const phase3AiFuture10YearsResults: Phase3AiFuture10YearsResult[] = [
  {
    type: 'Type1',
    emoji: '🌿',
    title: ko('조용하고 충만한 나만의 세계, 내면 충만 생활형'),
    shortDescription: ko('🔮 AI가 그린 당신의 10년 후'),
    description: ko('{year}년 어느 평일 아침입니다.\n알람 없이 눈을 뜹니다. 창문 너머로 빛이 조용히 들어오고 있고 당신은 서두르지 않습니다. 주방으로 나가 손수 커피를 내립니다. 드리퍼에 천천히 뜨거운 물을 붓는 동안 오늘 하고 싶은 것들이 머릿속을 지나갑니다.\n당신이 있는 곳은 도심에서 조금 벗어난 곳입니다. 작지만 당신의 취향이 곳곳에 배어있는 집입니다. 좋아하는 책들이 쌓인 선반, 오래 쓴 의자, 창가에 놓인 식물 한 두 개. 아무도 없어도 이 공간이 당신을 채웁니다.\n오늘 일은 오전에 집중해서 마칩니다. 당신이 하는 일은 깊이 있는 집중이 필요한 일입니다. 글을 쓰거나, 무언가를 만들거나, 오랫동안 쌓아온 전문성을 혼자 발휘하는 일입니다. 아무도 재촉하지 않고 당신의 페이스로 할 수 있습니다.\n오후엔 좋아하는 것을 합니다. 산책이거나 독서이거나 오래된 취미이거나. 많은 사람이 필요하지 않습니다. 당신 삶에는 진짜로 통하는 몇 명이 있고 그것으로 충분합니다.\n저녁이 되면 그 하루가 조용하게 쌓였다는 걸 느낍니다. 특별한 것은 없었지만 나답게 살았다는 느낌. 그것이 10년 후 당신의 성공입니다.'),
    keywords: ko('고요함,깊이,독립,충만,나다움'),
    sections: [
      section('🏠 10년 후 공간', '조용한 교외 또는 자연 가까운 아늑한 집'),
      section('💼 10년 후 일', '집중과 깊이가 필요한 독립적 전문 작업'),
      section('💞 10년 후 관계', '소수의 진짜 연결. 적지만 깊은 관계'),
      section('☀️ 10년 후 하루의 핵심', '나만의 루틴·나만의 공간·나만의 시간'),
    ],
    shareMessage: ko('AI가 그린 나의 10년 후: 내면 충만 생활형 🌿 알람 없이 일어나 커피 내리는 조용한 아침이 10년 후 내 일상이래... 이게 너무 나다 ㅋㅋ → 너의 10년 후는 어떤 모습이야?'),
  },
  {
    type: 'Type2',
    emoji: '🌸',
    title: ko('따뜻한 연결이 삶의 중심인, 관계 풍요 생활형'),
    shortDescription: ko('🔮 AI가 그린 당신의 10년 후'),
    description: ko('{year}년 어느 아침입니다.\n눈을 뜨면 주방에서 소리가 납니다. 혼자가 아닙니다. 당신의 삶에는 아침을 함께할 사람이 있습니다. 식탁에 앉아 커피를 마시며 오늘 이야기를 합니다. 아무 의미 없는 이야기도 괜찮습니다. 그냥 같은 시간을 공유하는 것 자체가 좋습니다.\n당신이 하는 일은 사람과 연결된 일입니다. 누군가를 돕거나, 가르치거나, 함께 만들어가는 일입니다. 일이 끝나면 에너지가 소진되는 게 아니라 오히려 충전되는 날이 많습니다. 내가 한 일이 누군가에게 실제로 도움이 됐을 때 느끼는 그 감각을 당신은 소중히 여깁니다.\n주말엔 자주 누군가와 함께합니다. 오래된 친구이거나 가족이거나 새로 알게 된 사람이거나. 밥을 같이 먹고 이야기를 나누고 웃습니다. 당신이 있는 자리는 항상 따뜻해집니다.\n저녁이 되면 오늘 만난 사람들이 생각납니다. 그리고 내일 또 누구를 만날지가 기대됩니다.\n10년 후 당신의 삶은 관계로 가득합니다. 그리고 그것이 당신에게 가장 풍요로운 삶입니다.'),
    keywords: ko('연결,따뜻함,돌봄,공감,함께함'),
    sections: [
      section('🏠 10년 후 공간', '함께할 수 있는 따뜻하고 넉넉한 집'),
      section('💼 10년 후 일', '사람과 연결되고 의미 있는 일'),
      section('💞 10년 후 관계', '가족·오랜 친구·새로 만난 따뜻한 사람들'),
      section('☀️ 10년 후 하루의 핵심', '누군가와 나누는 식사·대화·소소한 연결'),
    ],
    shareMessage: ko('AI가 그린 나의 10년 후: 관계 풍요 생활형 🌸 따뜻한 사람들로 가득한 삶이 내 10년 후래... 식탁에서 함께 아침 먹는 장면 읽으면서 뭔가 찡했음 → 너의 10년 후는?'),
  },
  {
    type: 'Type3',
    emoji: '📖',
    title: ko('일과 삶이 균형 잡힌, 꾸준한 성장 생활형'),
    shortDescription: ko('🔮 AI가 그린 당신의 10년 후'),
    description: ko('{year}년 어느 평일입니다.\n오전 7시에 눈을 뜹니다. 준비된 루틴이 있습니다. 운동이거나 글쓰기이거나 공부이거나. 하루를 제대로 시작하는 자신만의 의식이 있고 그것이 오늘의 리듬을 만듭니다.\n일은 당신이 선택한 분야에서 꽤 깊은 전문성을 쌓아온 상태입니다. 10년 전 지금의 당신이 막연하게 원했던 것들이 꽤 많이 이뤄져 있습니다. 모든 것이 완벽하진 않지만 내가 가고 있는 방향에 대한 확신이 있습니다.\n오후엔 집중해서 일하고 퇴근 후엔 온전히 나를 위한 시간입니다. 좋아하는 것을 배우거나 취미에 투자하거나 그냥 쉬거나. 일과 삶의 경계가 분명하고 그것이 오히려 두 영역 모두를 더 잘하게 만들어줍니다.\n주변엔 함께 성장하는 사람들이 있습니다. 같은 관심사를 가진 동료, 서로 자극을 주는 커뮤니티. 혼자가 아니라 같은 방향을 바라보는 사람들과 함께 나아가고 있습니다.\n10년 후 당신의 하루는 균형 잡혀 있습니다. 치우치지 않고 꾸준히. 그것이 당신의 성장 방식입니다.'),
    keywords: ko('균형,성장,꾸준함,전문성,방향성'),
    sections: [
      section('🏠 10년 후 공간', '작업 공간이 있는 기능적이고 정돈된 집'),
      section('💼 10년 후 일', '전문성이 쌓인 분야에서 자부심 있게 하는 일'),
      section('💞 10년 후 관계', '같은 방향을 바라보는 동료와 커뮤니티'),
      section('☀️ 10년 후 하루의 핵심', '루틴·집중·균형·꾸준한 성장'),
    ],
    shareMessage: ko('AI가 그린 나의 10년 후: 꾸준한 성장 생활형 📖 균형잡히고 꾸준한 삶이 내 10년 후래... 루틴대로 사는 거 맞음 ㅋㅋ → 너의 10년 후는 어떤 모습이야?'),
  },
  {
    type: 'Type4',
    emoji: '🏆',
    title: ko('목표와 성취가 살아있는, 전문 성취 생활형'),
    shortDescription: ko('🔮 AI가 그린 당신의 10년 후'),
    description: ko('{year}년 어느 아침입니다.\n이른 시간에 일어납니다. 오늘 해야 할 것들이 이미 머릿속에 정리돼 있습니다. 커피를 마시며 오늘의 가장 중요한 것 하나를 먼저 떠올립니다. 그것을 끝내면 오늘은 성공한 날입니다.\n당신이 하는 일은 10년 전 당신이 원했던 방향으로 뻗어있습니다. 분야에서 이름이 알려졌거나 팀을 이끌거나 어떤 방식으로든 성과가 눈에 보입니다. 당신의 전문성을 인정해주는 사람들이 생겼고 그 인정이 더 잘하고 싶다는 동력이 됩니다.\n물론 쉽지 않은 날도 있습니다. 목표가 있는 사람에게 압박은 친구처럼 따라다닙니다. 그러나 10년 후의 당신은 그 압박을 다루는 법을 배웠습니다. 밀고 나가야 할 때와 쉬어야 할 때를 압니다.\n저녁엔 오늘 한 것들을 돌아봅니다. 충분했는지, 더 잘할 수 있는 게 있는지. 자기 자신에게 엄격하지만 그만큼 결과도 따라옵니다.\n10년 후 당신의 삶에는 성취가 있습니다. 그리고 그것이 당신을 앞으로 나아가게 하는 힘입니다.'),
    keywords: ko('성취,전문성,목표,인정,추진력'),
    sections: [
      section('🏠 10년 후 공간', '자신의 커리어와 연결된 공간. 일과 삶이 가까운 곳'),
      section('💼 10년 후 일', '전문 분야에서 성과와 인정을 받는 일'),
      section('💞 10년 후 관계', '함께 성장하는 동료·멘토·후배'),
      section('☀️ 10년 후 하루의 핵심', '목표·집중·성취·인정·발전'),
    ],
    shareMessage: ko('AI가 그린 나의 10년 후: 전문 성취 생활형 🏆 10년 후에 분야에서 인정받는 사람이 돼있대... 지금부터 열심히 해야겠다는 생각 듦 → 너의 10년 후는?'),
  },
  {
    type: 'Type5',
    emoji: '🌍',
    title: ko('새로운 경험이 넘치는, 활동적 탐험 생활형'),
    shortDescription: ko('🔮 AI가 그린 당신의 10년 후'),
    description: ko('{year}년 어느 날입니다.\n오늘 어느 도시에 있는지는 나중에 말씀드릴게요. 아마 지난주과는 다른 곳일 것입니다. 당신의 10년 후는 한 자리에 머물지 않습니다.\n아침을 낯선 카페에서 시작할 수도 있고 오랜 친구의 도시에서 깰 수도 있고 오래 전부터 가보고 싶었던 곳에서 눈을 뜰 수도 있습니다. 어디에 있든 당신은 그 공간을 금방 자신의 것으로 만듭니다.\n당신이 하는 일은 장소에 구애받지 않습니다. 어디서든 할 수 있거나 이동 자체가 일의 일부이거나. 10년 전 원했던 자유로운 방식으로 일하고 있습니다.\n새로운 사람을 만나는 것이 자연스럽습니다. 다양한 배경의 사람들과 연결되고 짧지만 진한 교류를 합니다. 물론 오래된 소중한 사람들도 있습니다. 거리가 멀어도 연결은 유지됩니다.\n저녁엔 오늘 새로 발견한 것들을 떠올립니다. 새로운 음식, 새로운 골목, 새로운 대화.\n10년 후 당신의 삶은 계속 새롭습니다. 그리고 그것이 당신을 살아있게 만드는 에너지입니다.'),
    keywords: ko('탐험,자유,새로움,이동,경험'),
    sections: [
      section('🏠 10년 후 공간', '고정되지 않은 공간. 어디서든 집처럼 살 수 있는 능력'),
      section('💼 10년 후 일', '장소에 자유로운 일. 이동이 일의 일부인 라이프스타일'),
      section('💞 10년 후 관계', '다양한 배경의 넓은 연결 + 오래된 소수의 깊은 관계'),
      section('☀️ 10년 후 하루의 핵심', '새로운 공간·새로운 사람·새로운 경험'),
    ],
    shareMessage: ko('AI가 그린 나의 10년 후: 활동적 탐험 생활형 🌍 10년 후에도 매주 다른 곳에 있는 삶이래... 맞음 나 그렇게 살고 싶음 ㅋㅋ → 너의 10년 후는 어떤 모습이야?'),
  },
  {
    type: 'Type6',
    emoji: '🚀',
    title: ko('자신만의 방식으로 사는, 자유 개척 생활형'),
    shortDescription: ko('🔮 AI가 그린 당신의 10년 후'),
    description: ko('{year}년 어느 날입니다.\n오늘 당신의 하루는 아무도 예측하지 못합니다. 당신 자신도 어젯밤까지는 몰랐을 것입니다.\n누군가 10년 전 당신에게 지금의 삶을 설명해줬다면 믿지 못했을 것입니다. 당신이 선택한 방향이 처음엔 비현실적으로 보였을지 모릅니다. 그러나 당신은 그 길을 갔습니다. 그리고 지금은 그것이 당신의 삶입니다.\n하는 일이 기존 카테고리에 딱 맞지 않을 수 있습니다. 여러 가지를 동시에 하고 있거나 스스로 만들어낸 역할을 하고 있거나. 남이 정해준 틀이 아닌 나만의 방식이 있습니다.\n오늘 당신은 자신이 선택한 일을 합니다. 자신이 선택한 사람들과 있습니다. 자신이 원하는 방식으로 시간을 씁니다.\n완벽하지 않습니다. 예측 불가능한 부분도 있습니다. 그러나 그것이 당신이 원하는 삶입니다. 틀 안에 갇히지 않은 삶. 스스로 설계한 삶.\n10년 후 당신의 하루는 자유입니다. 그리고 그 자유는 10년의 도전이 만들어낸 것입니다.'),
    keywords: ko('자유,개척,독창성,용기,나만의 길'),
    sections: [
      section('🏠 10년 후 공간', '나만의 방식으로 설계된 공간. 어디든 내 방식대로'),
      section('💼 10년 후 일', '기존 카테고리에 없는 나만의 일. 스스로 만들어낸 역할'),
      section('💞 10년 후 관계', '자유롭게 연결되는 다양한 사람들'),
      section('☀️ 10년 후 하루의 핵심', '자유·나만의 방식·예측 불가능한 설렘·개척'),
    ],
    shareMessage: ko('AI가 그린 나의 10년 후: 자유 개척 생활형 🚀 아무도 예측 못 하는 나만의 삶이래... 이거 읽으면서 진짜 그렇게 살고 싶다는 생각 → 너의 10년 후는?'),
  },
];
