/** '기억력' 한계 챌린지 — 12라운드 이미지 기억→선택, 정답 1점, 0~12점 → Type1~5 */

type Locale = 'ko' | 'en' | 'ja' | 'zh-CN' | 'zh-TW' | 'vi' | 'id';
type ML = Record<Locale, string>;
function L(m: ML): Record<string, string> {
  return m;
}

export const PHASE3_MEMORY_LIMIT_CHALLENGE_SLUG = 'phase3-memory-limit-challenge';
export const PHASE3_MEMORY_LIMIT_CHALLENGE_COUNT = 12;
export const MEMORY_COVER_MS = 300;
export const MEMORY_COUNTDOWN_STEP_MS = 1000;

export type MemoryZone = 'warmup' | 'mid' | 'extreme';

export interface Phase3MemoryLimitChallengeOption {
  text: Record<string, string>;
  isCorrect: boolean;
}

export interface Phase3MemoryLimitChallengeQuestion {
  id: number;
  imageFile: string;
  exposureMs: number;
  zone: MemoryZone;
  roundTitle: Record<string, string>;
  question: Record<string, string>;
  options: Phase3MemoryLimitChallengeOption[];
  correctExplanation: Record<string, string>;
}

export interface Phase3MemoryLimitChallengeResult {
  type: string;
  emoji: string;
  title: Record<string, string>;
  shortDescription: Record<string, string>;
  description: Record<string, string>;
  levelLabel: Record<string, string>;
  characteristics: Record<string, string>;
  strength: Record<string, string> | null;
  weakness: Record<string, string> | null;
  improvementTip: Record<string, string> | null;
  oneLiner: Record<string, string> | null;
  certify: Record<string, string> | null;
  shareLine: Record<string, string>;
}

export function getMemoryExposureMs(roundIndex: number): number {
  if (roundIndex < 4) return 2000;
  if (roundIndex < 8) return 1000;
  return 500;
}

export function calculatePhase3MemoryLimitChallengeResult(answers: number[]): string {
  const total = answers.reduce((sum, s) => sum + (s ?? 0), 0);
  if (total <= 2) return 'Type1';
  if (total <= 5) return 'Type2';
  if (total <= 8) return 'Type3';
  if (total <= 10) return 'Type4';
  return 'Type5';
}

export function getPhase3MemoryLimitChallengeResultByType(
  type: string
): Phase3MemoryLimitChallengeResult | undefined {
  return phase3MemoryLimitChallengeResults.find((r) => r.type === type);
}

export const phase3MemoryLimitChallengeQuestions: Phase3MemoryLimitChallengeQuestion[] = [
  {
    id: 1,
    imageFile: 'p3_test_memory_limit_challenge_q1.webp',
    exposureMs: 2000,
    zone: 'warmup',
    roundTitle: L({
      ko: '과일 기억하기 🍎',
      en: 'Remember the Fruits 🍎',
      ja: '果物を覚える 🍎',
      'zh-CN': '记住水果 🍎',
      'zh-TW': '記住水果 🍎',
      vi: 'Ghi nhớ trái cây 🍎',
      id: 'Ingat Buah-buahan 🍎',
    }),
    question: L({
      ko: '방금 본 과일에 없었던 것은?',
      en: 'Which fruit was NOT shown just now?',
      ja: 'さっき見た果物のうち、なかったものは？',
      'zh-CN': '刚才看到的水果中，没有的是？',
      'zh-TW': '剛才看到的水果中，沒有的是？',
      vi: 'Trái cây nào KHÔNG có trong hình vừa rồi?',
      id: 'Buah mana yang TIDAK ada tadi?',
    }),
    options: [
      {
        text: L({
          ko: '사과 🍎',
          en: 'Apple 🍎',
          ja: 'りんご 🍎',
          'zh-CN': '苹果 🍎',
          'zh-TW': '蘋果 🍎',
          vi: 'Táo 🍎',
          id: 'Apel 🍎',
        }),
        isCorrect: false,
      },
      {
        text: L({
          ko: '딸기 🍓',
          en: 'Strawberry 🍓',
          ja: 'いちご 🍓',
          'zh-CN': '草莓 🍓',
          'zh-TW': '草莓 🍓',
          vi: 'Dâu tây 🍓',
          id: 'Stroberi 🍓',
        }),
        isCorrect: true,
      },
      {
        text: L({
          ko: '바나나 🍌',
          en: 'Banana 🍌',
          ja: 'バナナ 🍌',
          'zh-CN': '香蕉 🍌',
          'zh-TW': '香蕉 🍌',
          vi: 'Chuối 🍌',
          id: 'Pisang 🍌',
        }),
        isCorrect: false,
      },
      {
        text: L({
          ko: '포도 🍇',
          en: 'Grapes 🍇',
          ja: 'ぶどう 🍇',
          'zh-CN': '葡萄 🍇',
          'zh-TW': '葡萄 🍇',
          vi: 'Nho 🍇',
          id: 'Anggur 🍇',
        }),
        isCorrect: false,
      },
    ],
    correctExplanation: L({
      ko: '사과·바나나·포도가 있었습니다. 딸기는 없었습니다.',
      en: 'Apple, banana, and grapes were shown. Strawberry was not.',
      ja: 'りんご・バナナ・ぶどうがありました。いちごはありませんでした。',
      'zh-CN': '有苹果、香蕉、葡萄。没有草莓。',
      'zh-TW': '有蘋果、香蕉、葡萄。沒有草莓。',
      vi: 'Có táo, chuối và nho. Không có dâu tây.',
      id: 'Ada apel, pisang, dan anggur. Stroberi tidak ada.',
    }),
  },
  {
    id: 2,
    imageFile: 'p3_test_memory_limit_challenge_q2.webp',
    exposureMs: 2000,
    zone: 'warmup',
    roundTitle: L({
      ko: '색깔 원 기억하기 🔴',
      en: 'Remember the Color Circles 🔴',
      ja: '色の丸を覚える 🔴',
      'zh-CN': '记住颜色圆点 🔴',
      'zh-TW': '記住顏色圓點 🔴',
      vi: 'Ghi nhớ vòng tròn màu 🔴',
      id: 'Ingat Lingkaran Warna 🔴',
    }),
    question: L({
      ko: '방금 본 색깔에 없었던 것은?',
      en: 'Which color was NOT shown just now?',
      ja: 'さっき見た色のうち、なかったものは？',
      'zh-CN': '刚才看到的颜色中，没有的是？',
      'zh-TW': '剛才看到的顏色中，沒有的是？',
      vi: 'Màu nào KHÔNG có trong hình vừa rồi?',
      id: 'Warna mana yang TIDAK ada tadi?',
    }),
    options: [
      {
        text: L({
          ko: '빨강 🔴',
          en: 'Red 🔴',
          ja: '赤 🔴',
          'zh-CN': '红色 🔴',
          'zh-TW': '紅色 🔴',
          vi: 'Đỏ 🔴',
          id: 'Merah 🔴',
        }),
        isCorrect: false,
      },
      {
        text: L({
          ko: '파랑 🔵',
          en: 'Blue 🔵',
          ja: '青 🔵',
          'zh-CN': '蓝色 🔵',
          'zh-TW': '藍色 🔵',
          vi: 'Xanh dương 🔵',
          id: 'Biru 🔵',
        }),
        isCorrect: false,
      },
      {
        text: L({
          ko: '노랑 🟡',
          en: 'Yellow 🟡',
          ja: '黄 🟡',
          'zh-CN': '黄色 🟡',
          'zh-TW': '黃色 🟡',
          vi: 'Vàng 🟡',
          id: 'Kuning 🟡',
        }),
        isCorrect: true,
      },
      {
        text: L({
          ko: '초록 🟢',
          en: 'Green 🟢',
          ja: '緑 🟢',
          'zh-CN': '绿色 🟢',
          'zh-TW': '綠色 🟢',
          vi: 'Xanh lá 🟢',
          id: 'Hijau 🟢',
        }),
        isCorrect: false,
      },
    ],
    correctExplanation: L({
      ko: '빨강·파랑·초록이 있었습니다. 노랑은 없었습니다.',
      en: 'Red, blue, and green were shown. Yellow was not.',
      ja: '赤・青・緑がありました。黄はありませんでした。',
      'zh-CN': '有红色、蓝色、绿色。没有黄色。',
      'zh-TW': '有紅色、藍色、綠色。沒有黃色。',
      vi: 'Có đỏ, xanh dương và xanh lá. Không có vàng.',
      id: 'Ada merah, biru, dan hijau. Kuning tidak ada.',
    }),
  },
  {
    id: 3,
    imageFile: 'p3_test_memory_limit_challenge_q3.webp',
    exposureMs: 2000,
    zone: 'warmup',
    roundTitle: L({
      ko: '동물 기억하기 🐶',
      en: 'Remember the Animals 🐶',
      ja: '動物を覚える 🐶',
      'zh-CN': '记住动物 🐶',
      'zh-TW': '記住動物 🐶',
      vi: 'Ghi nhớ động vật 🐶',
      id: 'Ingat Hewan 🐶',
    }),
    question: L({
      ko: '방금 본 동물에 있었던 것은?',
      en: 'Which animal WAS shown just now?',
      ja: 'さっき見た動物のうち、あったものは？',
      'zh-CN': '刚才看到的动物中，有的是？',
      'zh-TW': '剛才看到的動物中，有的是？',
      vi: 'Con vật nào CÓ trong hình vừa rồi?',
      id: 'Hewan mana yang ADA tadi?',
    }),
    options: [
      {
        text: L({
          ko: '여우 🦊',
          en: 'Fox 🦊',
          ja: 'きつね 🦊',
          'zh-CN': '狐狸 🦊',
          'zh-TW': '狐狸 🦊',
          vi: 'Cáo 🦊',
          id: 'Rubah 🦊',
        }),
        isCorrect: false,
      },
      {
        text: L({
          ko: '곰 🐻',
          en: 'Bear 🐻',
          ja: 'くま 🐻',
          'zh-CN': '熊 🐻',
          'zh-TW': '熊 🐻',
          vi: 'Gấu 🐻',
          id: 'Beruang 🐻',
        }),
        isCorrect: false,
      },
      {
        text: L({
          ko: '고양이 🐱',
          en: 'Cat 🐱',
          ja: 'ねこ 🐱',
          'zh-CN': '猫 🐱',
          'zh-TW': '貓 🐱',
          vi: 'Mèo 🐱',
          id: 'Kucing 🐱',
        }),
        isCorrect: true,
      },
      {
        text: L({
          ko: '늑대 🐺',
          en: 'Wolf 🐺',
          ja: 'おおかみ 🐺',
          'zh-CN': '狼 🐺',
          'zh-TW': '狼 🐺',
          vi: 'Sói 🐺',
          id: 'Serigala 🐺',
        }),
        isCorrect: false,
      },
    ],
    correctExplanation: L({
      ko: '강아지·고양이·토끼가 있었습니다.',
      en: 'Dog, cat, and rabbit were shown.',
      ja: 'いぬ・ねこ・うさぎがありました。',
      'zh-CN': '有狗、猫、兔子。',
      'zh-TW': '有狗、貓、兔子。',
      vi: 'Có chó, mèo và thỏ.',
      id: 'Ada anjing, kucing, dan kelinci.',
    }),
  },
  {
    id: 4,
    imageFile: 'p3_test_memory_limit_challenge_q4.webp',
    exposureMs: 2000,
    zone: 'warmup',
    roundTitle: L({
      ko: '물건 4개 기억하기 ⌚',
      en: 'Remember 4 Objects ⌚',
      ja: '物4つを覚える ⌚',
      'zh-CN': '记住4个物品 ⌚',
      'zh-TW': '記住4個物品 ⌚',
      vi: 'Ghi nhớ 4 đồ vật ⌚',
      id: 'Ingat 4 Benda ⌚',
    }),
    question: L({
      ko: '방금 본 물건에 없었던 것은?',
      en: 'Which object was NOT shown just now?',
      ja: 'さっき見た物のうち、なかったものは？',
      'zh-CN': '刚才看到的物品中，没有的是？',
      'zh-TW': '剛才看到的物品中，沒有的是？',
      vi: 'Đồ vật nào KHÔNG có trong hình vừa rồi?',
      id: 'Benda mana yang TIDAK ada tadi?',
    }),
    options: [
      {
        text: L({
          ko: '시계 ⌚',
          en: 'Watch ⌚',
          ja: '時計 ⌚',
          'zh-CN': '手表 ⌚',
          'zh-TW': '手錶 ⌚',
          vi: 'Đồng hồ ⌚',
          id: 'Jam tangan ⌚',
        }),
        isCorrect: false,
      },
      {
        text: L({
          ko: '신발 👟',
          en: 'Shoes 👟',
          ja: '靴 👟',
          'zh-CN': '鞋子 👟',
          'zh-TW': '鞋子 👟',
          vi: 'Giày 👟',
          id: 'Sepatu 👟',
        }),
        isCorrect: true,
      },
      {
        text: L({
          ko: '우산 ☂️',
          en: 'Umbrella ☂️',
          ja: '傘 ☂️',
          'zh-CN': '雨伞 ☂️',
          'zh-TW': '雨傘 ☂️',
          vi: 'Ô ☂️',
          id: 'Payung ☂️',
        }),
        isCorrect: false,
      },
      {
        text: L({
          ko: '가방 👜',
          en: 'Bag 👜',
          ja: 'かばん 👜',
          'zh-CN': '包 👜',
          'zh-TW': '包 👜',
          vi: 'Túi xách 👜',
          id: 'Tas 👜',
        }),
        isCorrect: false,
      },
    ],
    correctExplanation: L({
      ko: '시계·우산·가방·모자가 있었습니다. 신발은 없었습니다.',
      en: 'Watch, umbrella, bag, and hat were shown. Shoes were not.',
      ja: '時計・傘・かばん・帽子がありました。靴はありませんでした。',
      'zh-CN': '有手表、雨伞、包、帽子。没有鞋子。',
      'zh-TW': '有手錶、雨傘、包、帽子。沒有鞋子。',
      vi: 'Có đồng hồ, ô, túi xách và mũ. Không có giày.',
      id: 'Ada jam tangan, payung, tas, dan topi. Sepatu tidak ada.',
    }),
  },
  {
    id: 5,
    imageFile: 'p3_test_memory_limit_challenge_q5.webp',
    exposureMs: 1000,
    zone: 'mid',
    roundTitle: L({
      ko: '숫자 4개 기억하기 🔢',
      en: 'Remember 4 Numbers 🔢',
      ja: '数字4つを覚える 🔢',
      'zh-CN': '记住4个数字 🔢',
      'zh-TW': '記住4個數字 🔢',
      vi: 'Ghi nhớ 4 con số 🔢',
      id: 'Ingat 4 Angka 🔢',
    }),
    question: L({
      ko: '방금 본 숫자 중 없었던 것은?',
      en: 'Which number was NOT shown just now?',
      ja: 'さっき見た数字のうち、なかったものは？',
      'zh-CN': '刚才看到的数字中，没有的是？',
      'zh-TW': '剛才看到的數字中，沒有的是？',
      vi: 'Con số nào KHÔNG có trong hình vừa rồi?',
      id: 'Angka mana yang TIDAK ada tadi?',
    }),
    options: [
      { text: L({ ko: '3', en: '3', ja: '3', 'zh-CN': '3', 'zh-TW': '3', vi: '3', id: '3' }), isCorrect: false },
      { text: L({ ko: '7', en: '7', ja: '7', 'zh-CN': '7', 'zh-TW': '7', vi: '7', id: '7' }), isCorrect: false },
      { text: L({ ko: '5', en: '5', ja: '5', 'zh-CN': '5', 'zh-TW': '5', vi: '5', id: '5' }), isCorrect: true },
      { text: L({ ko: '9', en: '9', ja: '9', 'zh-CN': '9', 'zh-TW': '9', vi: '9', id: '9' }), isCorrect: false },
    ],
    correctExplanation: L({
      ko: '3·7·1·9가 있었습니다. 5는 없었습니다.',
      en: '3, 7, 1, and 9 were shown. 5 was not.',
      ja: '3・7・1・9がありました。5はありませんでした。',
      'zh-CN': '有3、7、1、9。没有5。',
      'zh-TW': '有3、7、1、9。沒有5。',
      vi: 'Có 3, 7, 1 và 9. Không có 5.',
      id: 'Ada 3, 7, 1, dan 9. Angka 5 tidak ada.',
    }),
  },
  {
    id: 6,
    imageFile: 'p3_test_memory_limit_challenge_q6.webp',
    exposureMs: 1000,
    zone: 'mid',
    roundTitle: L({
      ko: '위치 기억하기 🗺️',
      en: 'Remember the Positions 🗺️',
      ja: '位置を覚える 🗺️',
      'zh-CN': '记住位置 🗺️',
      'zh-TW': '記住位置 🗺️',
      vi: 'Ghi nhớ vị trí 🗺️',
      id: 'Ingat Posisi 🗺️',
    }),
    question: L({
      ko: '방금 표시됐던 위치가 아닌 것은?',
      en: 'Which position was NOT marked just now?',
      ja: 'さっき表示された位置ではないものは？',
      'zh-CN': '刚才没有标记的位置是？',
      'zh-TW': '剛才沒有標記的位置是？',
      vi: 'Vị trí nào KHÔNG được đánh dấu vừa rồi?',
      id: 'Posisi mana yang TIDAK ditandai tadi?',
    }),
    options: [
      {
        text: L({
          ko: '1행 1열 (왼쪽 상단)',
          en: 'Row 1 Col 1 (top left)',
          ja: '1行1列（左上）',
          'zh-CN': '第1行第1列（左上）',
          'zh-TW': '第1行第1列（左上）',
          vi: 'Hàng 1 Cột 1 (trên trái)',
          id: 'Baris 1 Kolom 1 (kiri atas)',
        }),
        isCorrect: false,
      },
      {
        text: L({
          ko: '2행 3열 (오른쪽 중간)',
          en: 'Row 2 Col 3 (middle right)',
          ja: '2行3列（右中央）',
          'zh-CN': '第2行第3列（右中）',
          'zh-TW': '第2行第3列（右中）',
          vi: 'Hàng 2 Cột 3 (giữa phải)',
          id: 'Baris 2 Kolom 3 (tengah kanan)',
        }),
        isCorrect: false,
      },
      {
        text: L({
          ko: '2행 2열 (정중앙)',
          en: 'Row 2 Col 2 (center)',
          ja: '2行2列（中央）',
          'zh-CN': '第2行第2列（正中央）',
          'zh-TW': '第2行第2列（正中央）',
          vi: 'Hàng 2 Cột 2 (chính giữa)',
          id: 'Baris 2 Kolom 2 (tengah)',
        }),
        isCorrect: true,
      },
      {
        text: L({
          ko: '3행 2열 (아래 가운데)',
          en: 'Row 3 Col 2 (bottom center)',
          ja: '3行2列（下中央）',
          'zh-CN': '第3行第2列（下中）',
          'zh-TW': '第3行第2列（下中）',
          vi: 'Hàng 3 Cột 2 (dưới giữa)',
          id: 'Baris 3 Kolom 2 (bawah tengah)',
        }),
        isCorrect: false,
      },
    ],
    correctExplanation: L({
      ko: '1행1열·2행3열·3행2열이 표시됐습니다. 정중앙(2행2열)은 비어있었습니다.',
      en: 'Row 1 Col 1, Row 2 Col 3, and Row 3 Col 2 were marked. The center (Row 2 Col 2) was empty.',
      ja: '1行1列・2行3列・3行2列が表示されました。中央（2行2列）は空でした。',
      'zh-CN': '标记了第1行第1列、第2行第3列、第3行第2列。正中央（第2行第2列）是空的。',
      'zh-TW': '標記了第1行第1列、第2行第3列、第3行第2列。正中央（第2行第2列）是空的。',
      vi: 'Hàng 1 Cột 1, Hàng 2 Cột 3 và Hàng 3 Cột 2 được đánh dấu. Chính giữa (Hàng 2 Cột 2) trống.',
      id: 'Baris 1 Kolom 1, Baris 2 Kolom 3, dan Baris 3 Kolom 2 ditandai. Tengah (Baris 2 Kolom 2) kosong.',
    }),
  },
  {
    id: 7,
    imageFile: 'p3_test_memory_limit_challenge_q7.webp',
    exposureMs: 1000,
    zone: 'mid',
    roundTitle: L({
      ko: '단어 5개 기억하기 📝',
      en: 'Remember 5 Words 📝',
      ja: '単語5つを覚える 📝',
      'zh-CN': '记住5个单词 📝',
      'zh-TW': '記住5個單字 📝',
      vi: 'Ghi nhớ 5 từ 📝',
      id: 'Ingat 5 Kata 📝',
    }),
    question: L({
      ko: '방금 본 단어에 없었던 것은?',
      en: 'Which word was NOT shown just now?',
      ja: 'さっき見た単語のうち、なかったものは？',
      'zh-CN': '刚才看到的单词中，没有的是？',
      'zh-TW': '剛才看到的單字中，沒有的是？',
      vi: 'Từ nào KHÔNG có trong hình vừa rồi?',
      id: 'Kata mana yang TIDAK ada tadi?',
    }),
    options: [
      {
        text: L({
          ko: '하늘',
          en: 'Sky',
          ja: '空',
          'zh-CN': '天空',
          'zh-TW': '天空',
          vi: 'Bầu trời',
          id: 'Langit',
        }),
        isCorrect: false,
      },
      {
        text: L({
          ko: '바람',
          en: 'Wind',
          ja: '風',
          'zh-CN': '风',
          'zh-TW': '風',
          vi: 'Gió',
          id: 'Angin',
        }),
        isCorrect: true,
      },
      {
        text: L({
          ko: '바다',
          en: 'Sea',
          ja: '海',
          'zh-CN': '大海',
          'zh-TW': '大海',
          vi: 'Biển',
          id: 'Laut',
        }),
        isCorrect: false,
      },
      {
        text: L({
          ko: '구름',
          en: 'Cloud',
          ja: '雲',
          'zh-CN': '云',
          'zh-TW': '雲',
          vi: 'Mây',
          id: 'Awan',
        }),
        isCorrect: false,
      },
    ],
    correctExplanation: L({
      ko: '하늘·바다·별·구름·달이 있었습니다. 바람은 없었습니다.',
      en: 'Sky, sea, star, cloud, and moon were shown. Wind was not.',
      ja: '空・海・星・雲・月がありました。風はありませんでした。',
      'zh-CN': '有天空、大海、星星、云、月亮。没有风。',
      'zh-TW': '有天空、大海、星星、雲、月亮。沒有風。',
      vi: 'Có bầu trời, biển, sao, mây và mặt trăng. Không có gió.',
      id: 'Ada langit, laut, bintang, awan, dan bulan. Angin tidak ada.',
    }),
  },
  {
    id: 8,
    imageFile: 'p3_test_memory_limit_challenge_q8.webp',
    exposureMs: 1000,
    zone: 'mid',
    roundTitle: L({
      ko: '색깔 순서 기억하기 🎨',
      en: 'Remember the Color Order 🎨',
      ja: '色の順番を覚える 🎨',
      'zh-CN': '记住颜色顺序 🎨',
      'zh-TW': '記住顏色順序 🎨',
      vi: 'Ghi nhớ thứ tự màu 🎨',
      id: 'Ingat Urutan Warna 🎨',
    }),
    question: L({
      ko: '3번째 색깔은 무엇이었나요?',
      en: 'What was the 3rd color?',
      ja: '3番目の色は何でしたか？',
      'zh-CN': '第3个颜色是什么？',
      'zh-TW': '第3個顏色是什麼？',
      vi: 'Màu thứ 3 là gì?',
      id: 'Apa warna ke-3?',
    }),
    options: [
      {
        text: L({
          ko: '빨강',
          en: 'Red',
          ja: '赤',
          'zh-CN': '红色',
          'zh-TW': '紅色',
          vi: 'Đỏ',
          id: 'Merah',
        }),
        isCorrect: false,
      },
      {
        text: L({
          ko: '파랑',
          en: 'Blue',
          ja: '青',
          'zh-CN': '蓝色',
          'zh-TW': '藍色',
          vi: 'Xanh dương',
          id: 'Biru',
        }),
        isCorrect: false,
      },
      {
        text: L({
          ko: '초록',
          en: 'Green',
          ja: '緑',
          'zh-CN': '绿色',
          'zh-TW': '綠色',
          vi: 'Xanh lá',
          id: 'Hijau',
        }),
        isCorrect: true,
      },
      {
        text: L({
          ko: '노랑',
          en: 'Yellow',
          ja: '黄',
          'zh-CN': '黄色',
          'zh-TW': '黃色',
          vi: 'Vàng',
          id: 'Kuning',
        }),
        isCorrect: false,
      },
    ],
    correctExplanation: L({
      ko: '순서는 빨강(1)→파랑(2)→초록(3)→노랑(4)이었습니다.',
      en: 'The order was red (1) → blue (2) → green (3) → yellow (4).',
      ja: '順番は赤(1)→青(2)→緑(3)→黄(4)でした。',
      'zh-CN': '顺序是红色(1)→蓝色(2)→绿色(3)→黄色(4)。',
      'zh-TW': '順序是紅色(1)→藍色(2)→綠色(3)→黃色(4)。',
      vi: 'Thứ tự là đỏ (1) → xanh dương (2) → xanh lá (3) → vàng (4).',
      id: 'Urutannya merah (1) → biru (2) → hijau (3) → kuning (4).',
    }),
  },
  {
    id: 9,
    imageFile: 'p3_test_memory_limit_challenge_q9.webp',
    exposureMs: 500,
    zone: 'extreme',
    roundTitle: L({
      ko: '위치 4개 기억하기 (극한) 🎯',
      en: 'Remember 4 Positions (Extreme) 🎯',
      ja: '位置4つを覚える（極限） 🎯',
      'zh-CN': '记住4个位置（极限） 🎯',
      'zh-TW': '記住4個位置（極限） 🎯',
      vi: 'Ghi nhớ 4 vị trí (Cực hạn) 🎯',
      id: 'Ingat 4 Posisi (Ekstrem) 🎯',
    }),
    question: L({
      ko: '방금 표시됐던 위치가 아닌 것은?',
      en: 'Which position was NOT marked just now?',
      ja: 'さっき表示された位置ではないものは？',
      'zh-CN': '刚才没有标记的位置是？',
      'zh-TW': '剛才沒有標記的位置是？',
      vi: 'Vị trí nào KHÔNG được đánh dấu vừa rồi?',
      id: 'Posisi mana yang TIDAK ditandai tadi?',
    }),
    options: [
      {
        text: L({
          ko: '1행 2열',
          en: 'Row 1 Col 2',
          ja: '1行2列',
          'zh-CN': '第1行第2列',
          'zh-TW': '第1行第2列',
          vi: 'Hàng 1 Cột 2',
          id: 'Baris 1 Kolom 2',
        }),
        isCorrect: false,
      },
      {
        text: L({
          ko: '2행 1열',
          en: 'Row 2 Col 1',
          ja: '2行1列',
          'zh-CN': '第2行第1列',
          'zh-TW': '第2行第1列',
          vi: 'Hàng 2 Cột 1',
          id: 'Baris 2 Kolom 1',
        }),
        isCorrect: false,
      },
      {
        text: L({
          ko: '2행 4열',
          en: 'Row 2 Col 4',
          ja: '2行4列',
          'zh-CN': '第2行第4列',
          'zh-TW': '第2行第4列',
          vi: 'Hàng 2 Cột 4',
          id: 'Baris 2 Kolom 4',
        }),
        isCorrect: true,
      },
      {
        text: L({
          ko: '3행 4열',
          en: 'Row 3 Col 4',
          ja: '3行4列',
          'zh-CN': '第3行第4列',
          'zh-TW': '第3行第4列',
          vi: 'Hàng 3 Cột 4',
          id: 'Baris 3 Kolom 4',
        }),
        isCorrect: false,
      },
    ],
    correctExplanation: L({
      ko: '1행2열·2행1열·3행4열·4행3열이 표시됐습니다.',
      en: 'Row 1 Col 2, Row 2 Col 1, Row 3 Col 4, and Row 4 Col 3 were marked.',
      ja: '1行2列・2行1列・3行4列・4行3列が表示されました。',
      'zh-CN': '标记了第1行第2列、第2行第1列、第3行第4列、第4行第3列。',
      'zh-TW': '標記了第1行第2列、第2行第1列、第3行第4列、第4行第3列。',
      vi: 'Hàng 1 Cột 2, Hàng 2 Cột 1, Hàng 3 Cột 4 và Hàng 4 Cột 3 được đánh dấu.',
      id: 'Baris 1 Kolom 2, Baris 2 Kolom 1, Baris 3 Kolom 4, dan Baris 4 Kolom 3 ditandai.',
    }),
  },
  {
    id: 10,
    imageFile: 'p3_test_memory_limit_challenge_q10.webp',
    exposureMs: 500,
    zone: 'extreme',
    roundTitle: L({
      ko: '숫자 5개 기억하기 (극한) 🔢',
      en: 'Remember 5 Numbers (Extreme) 🔢',
      ja: '数字5つを覚える（極限） 🔢',
      'zh-CN': '记住5个数字（极限） 🔢',
      'zh-TW': '記住5個數字（極限） 🔢',
      vi: 'Ghi nhớ 5 con số (Cực hạn) 🔢',
      id: 'Ingat 5 Angka (Ekstrem) 🔢',
    }),
    question: L({
      ko: '방금 본 숫자 중 없었던 것은?',
      en: 'Which number was NOT shown just now?',
      ja: 'さっき見た数字のうち、なかったものは？',
      'zh-CN': '刚才看到的数字中，没有的是？',
      'zh-TW': '剛才看到的數字中，沒有的是？',
      vi: 'Con số nào KHÔNG có trong hình vừa rồi?',
      id: 'Angka mana yang TIDAK ada tadi?',
    }),
    options: [
      { text: L({ ko: '2', en: '2', ja: '2', 'zh-CN': '2', 'zh-TW': '2', vi: '2', id: '2' }), isCorrect: false },
      { text: L({ ko: '5', en: '5', ja: '5', 'zh-CN': '5', 'zh-TW': '5', vi: '5', id: '5' }), isCorrect: true },
      { text: L({ ko: '8', en: '8', ja: '8', 'zh-CN': '8', 'zh-TW': '8', vi: '8', id: '8' }), isCorrect: false },
      { text: L({ ko: '4', en: '4', ja: '4', 'zh-CN': '4', 'zh-TW': '4', vi: '4', id: '4' }), isCorrect: false },
    ],
    correctExplanation: L({
      ko: '2·8·4·6·3이 있었습니다. 5는 없었습니다.',
      en: '2, 8, 4, 6, and 3 were shown. 5 was not.',
      ja: '2・8・4・6・3がありました。5はありませんでした。',
      'zh-CN': '有2、8、4、6、3。没有5。',
      'zh-TW': '有2、8、4、6、3。沒有5。',
      vi: 'Có 2, 8, 4, 6 và 3. Không có 5.',
      id: 'Ada 2, 8, 4, 6, dan 3. Angka 5 tidak ada.',
    }),
  },
  {
    id: 11,
    imageFile: 'p3_test_memory_limit_challenge_q11.webp',
    exposureMs: 500,
    zone: 'extreme',
    roundTitle: L({
      ko: '단어+색깔 조합 기억하기 🌈',
      en: 'Remember Word + Color Pairs 🌈',
      ja: '単語+色の組み合わせを覚える 🌈',
      'zh-CN': '记住单词+颜色组合 🌈',
      'zh-TW': '記住單字+顏色組合 🌈',
      vi: 'Ghi nhớ cặp từ + màu 🌈',
      id: 'Ingat Pasangan Kata + Warna 🌈',
    }),
    question: L({
      ko: "'사과'는 무슨 색과 짝지어져 있었나요?",
      en: "What color was paired with 'apple'?",
      ja: '「りんご」はどの色とペアになっていましたか？',
      'zh-CN': '「苹果」与什么颜色配对？',
      'zh-TW': '「蘋果」與什麼顏色配對？',
      vi: "Màu nào được ghép với 'táo'?",
      id: "Warna apa yang dipasangkan dengan 'apel'?",
    }),
    options: [
      {
        text: L({
          ko: '파랑',
          en: 'Blue',
          ja: '青',
          'zh-CN': '蓝色',
          'zh-TW': '藍色',
          vi: 'Xanh dương',
          id: 'Biru',
        }),
        isCorrect: false,
      },
      {
        text: L({
          ko: '초록',
          en: 'Green',
          ja: '緑',
          'zh-CN': '绿色',
          'zh-TW': '綠色',
          vi: 'Xanh lá',
          id: 'Hijau',
        }),
        isCorrect: false,
      },
      {
        text: L({
          ko: '빨강',
          en: 'Red',
          ja: '赤',
          'zh-CN': '红色',
          'zh-TW': '紅色',
          vi: 'Đỏ',
          id: 'Merah',
        }),
        isCorrect: true,
      },
      {
        text: L({
          ko: '노랑',
          en: 'Yellow',
          ja: '黄',
          'zh-CN': '黄色',
          'zh-TW': '黃色',
          vi: 'Vàng',
          id: 'Kuning',
        }),
        isCorrect: false,
      },
    ],
    correctExplanation: L({
      ko: '사과=빨강 / 하늘=파랑 / 풀=초록이었습니다.',
      en: 'Apple = red / sky = blue / grass = green.',
      ja: 'りんご=赤 / 空=青 / 草=緑でした。',
      'zh-CN': '苹果=红色 / 天空=蓝色 / 草=绿色。',
      'zh-TW': '蘋果=紅色 / 天空=藍色 / 草=綠色。',
      vi: 'Táo = đỏ / bầu trời = xanh dương / cỏ = xanh lá.',
      id: 'Apel = merah / langit = biru / rumput = hijau.',
    }),
  },
  {
    id: 12,
    imageFile: 'p3_test_memory_limit_challenge_q12.webp',
    exposureMs: 500,
    zone: 'extreme',
    roundTitle: L({
      ko: '아이콘 위치 기억하기 (최종 보스) 🏆',
      en: 'Remember Icon Position (Final Boss) 🏆',
      ja: 'アイコンの位置を覚える（最終ボス） 🏆',
      'zh-CN': '记住图标位置（最终Boss） 🏆',
      'zh-TW': '記住圖示位置（最終Boss） 🏆',
      vi: 'Ghi nhớ vị trí biểu tượng (Trùm cuối) 🏆',
      id: 'Ingat Posisi Ikon (Boss Final) 🏆',
    }),
    question: L({
      ko: '2행 2열(정중앙)에 있던 아이콘은?',
      en: 'Which icon was at Row 2 Col 2 (center)?',
      ja: '2行2列（中央）にあったアイコンは？',
      'zh-CN': '第2行第2列（正中央）的图标是？',
      'zh-TW': '第2行第2列（正中央）的圖示是？',
      vi: 'Biểu tượng nào ở Hàng 2 Cột 2 (chính giữa)?',
      id: 'Ikon apa yang ada di Baris 2 Kolom 2 (tengah)?',
    }),
    options: [
      {
        text: L({
          ko: '별 ⭐',
          en: 'Star ⭐',
          ja: '星 ⭐',
          'zh-CN': '星星 ⭐',
          'zh-TW': '星星 ⭐',
          vi: 'Sao ⭐',
          id: 'Bintang ⭐',
        }),
        isCorrect: false,
      },
      {
        text: L({
          ko: '달 🌙',
          en: 'Moon 🌙',
          ja: '月 🌙',
          'zh-CN': '月亮 🌙',
          'zh-TW': '月亮 🌙',
          vi: 'Mặt trăng 🌙',
          id: 'Bulan 🌙',
        }),
        isCorrect: false,
      },
      {
        text: L({
          ko: '해 ☀️',
          en: 'Sun ☀️',
          ja: '太陽 ☀️',
          'zh-CN': '太阳 ☀️',
          'zh-TW': '太陽 ☀️',
          vi: 'Mặt trời ☀️',
          id: 'Matahari ☀️',
        }),
        isCorrect: true,
      },
      {
        text: L({
          ko: '구름 ☁️',
          en: 'Cloud ☁️',
          ja: '雲 ☁️',
          'zh-CN': '云 ☁️',
          'zh-TW': '雲 ☁️',
          vi: 'Mây ☁️',
          id: 'Awan ☁️',
        }),
        isCorrect: false,
      },
    ],
    correctExplanation: L({
      ko: '정중앙(2행2열)에는 해(☀️)가 있었습니다. 마지막까지 기억했다면 당신의 뇌세포는 살아있습니다.',
      en: 'The center (Row 2 Col 2) had the sun (☀️). If you remembered until the end, your brain cells are still alive.',
      ja: '中央（2行2列）には太陽（☀️）がありました。最後まで覚えていたなら、あなたの脳細胞は生きています。',
      'zh-CN': '正中央（第2行第2列）是太阳（☀️）。如果记到最后，说明你的脑细胞还活着。',
      'zh-TW': '正中央（第2行第2列）是太陽（☀️）。如果記到最後，說明你的腦細胞還活著。',
      vi: 'Chính giữa (Hàng 2 Cột 2) có mặt trời (☀️). Nếu bạn nhớ đến cuối, tế bào não của bạn vẫn còn sống.',
      id: 'Di tengah (Baris 2 Kolom 2) ada matahari (☀️). Jika kamu ingat sampai akhir, sel otakmu masih hidup.',
    }),
  },
];

export const phase3MemoryLimitChallengeResults: Phase3MemoryLimitChallengeResult[] = [
  {
    type: 'Type1',
    emoji: '🆘',
    title: L({
      ko: '뇌세포 긴급 충전 필요, 기억력 SOS',
      en: 'Brain Cells Need Emergency Charge — Memory SOS',
      ja: '脳細胞緊急充電必要、記憶力SOS',
      'zh-CN': '脑细胞急需充电，记忆力SOS',
      'zh-TW': '腦細胞急需充電，記憶力SOS',
      vi: 'Tế bào não cần sạc khẩn cấp — SOS trí nhớ',
      id: 'Sel otak perlu isi daya darurat — SOS memori',
    }),
    shortDescription: L({
      ko: '워밍업 구간에서도 많이 힘드셨나요? 괜찮습니다. 뇌도 컨디션이 있습니다.',
      en: 'Struggled even in the warmup? That&apos;s okay. Brains have off days too.',
      ja: 'ウォームアップでも大変でしたか？大丈夫。脳にもコンディションがあります。',
      'zh-CN': '热身阶段就很吃力吗？没关系，大脑也有状态好坏。',
      'zh-TW': '熱身階段就很吃力嗎？沒關係，大腦也有狀態好壞。',
      vi: 'Ngay phần khởi động đã khó rồi? Không sao. Não cũng có ngày không ổn.',
      id: 'Kesulitan bahkan di pemanasan? Gapapa. Otak juga punya hari buruk.',
    }),
    description: L({
      ko: '12라운드 중 2개 이하를 맞혔습니다. 단기 기억력이 오늘 많이 지쳐있는 상태이거나 원래 시각 기억보다 청각·촉각 기억이 더 강한 유형일 수 있습니다. 잠을 충분히 자고 내일 다시 도전해보세요.',
      en: 'You got 2 or fewer out of 12 rounds correct. Your short-term memory may be tired today, or you may naturally be stronger with auditory/tactile memory than visual memory. Get enough sleep and try again tomorrow.',
      ja: '12ラウンド中2問以下でした。今日は短期記憶が疲れているか、もともと視覚記憶より聴覚・触覚記憶が強いタイプかもしれません。十分に眠って明日また挑戦してください。',
      'zh-CN': '12轮中答对2题及以下。短期记忆今天可能很疲惫，或者你天生听觉/触觉记忆比视觉记忆更强。睡足觉，明天再挑战吧。',
      'zh-TW': '12輪中答對2題及以下。短期記憶今天可能很疲憊，或者你天生聽覺/觸覺記憶比視覺記憶更強。睡足覺，明天再挑戰吧。',
      vi: 'Bạn trả lời đúng 2 câu trở xuống trong 12 vòng. Trí nhớ ngắn hạn hôm nay có thể đang mệt, hoặc bạn thuộc kiểu nhớ bằng tai/xúc giác mạnh hơn nhớ hình ảnh. Ngủ đủ giấc và thử lại ngày mai.',
      id: 'Kamu benar 2 atau kurang dari 12 ronde. Memori jangka pendekmu mungkin lelah hari ini, atau kamu memang lebih kuat ingat lewat suara/sentuhan daripada visual. Tidur cukup dan coba lagi besok.',
    }),
    levelLabel: L({
      ko: 'Lv.1 뇌세포 SOS 🆘',
      en: 'Lv.1 Brain Cell SOS 🆘',
      ja: 'Lv.1 脳細胞SOS 🆘',
      'zh-CN': 'Lv.1 脑细胞SOS 🆘',
      'zh-TW': 'Lv.1 腦細胞SOS 🆘',
      vi: 'Lv.1 SOS tế bào não 🆘',
      id: 'Lv.1 SOS sel otak 🆘',
    }),
    characteristics: L({
      ko: '정답 수 0~2개, 가장 취약한 구간: 전 구간',
      en: 'Correct: 0–2, weakest zone: all rounds',
      ja: '正解数0〜2、最も弱い区間：全区間',
      'zh-CN': '答对0~2题，最薄弱区间：全部',
      'zh-TW': '答對0~2題，最薄弱區間：全部',
      vi: 'Đúng 0–2 câu, khu vực yếu nhất: toàn bộ',
      id: 'Benar 0–2, zona terlemah: semua ronde',
    }),
    strength: null,
    weakness: L({
      ko: '전 구간',
      en: 'All rounds',
      ja: '全区間',
      'zh-CN': '全部区间',
      'zh-TW': '全部區間',
      vi: 'Toàn bộ các vòng',
      id: 'Semua ronde',
    }),
    improvementTip: L({
      ko: '물 마시기·수면 충분히 취하기·뇌 자극 게임 꾸준히 하기',
      en: 'Drink water, get enough sleep, and play brain-training games regularly',
      ja: '水分補給・十分な睡眠・脳トレゲームを継続する',
      'zh-CN': '多喝水、保证睡眠、坚持玩脑力游戏',
      'zh-TW': '多喝水、保證睡眠、堅持玩腦力遊戲',
      vi: 'Uống nước, ngủ đủ, chơi game rèn não thường xuyên',
      id: 'Minum air, tidur cukup, dan rutin main game latihan otak',
    }),
    oneLiner: L({
      ko: '오늘 뇌세포가 쉬고 싶다고 합니다. 내일 다시 도전하세요',
      en: 'Your brain cells want a day off today. Try again tomorrow',
      ja: '今日は脳細胞が休みたがっています。明日また挑戦してください',
      'zh-CN': '今天脑细胞想休息。明天再来挑战吧',
      'zh-TW': '今天腦細胞想休息。明天再來挑戰吧',
      vi: 'Hôm nay tế bào não muốn nghỉ. Thử lại ngày mai nhé',
      id: 'Hari ini sel otakmu ingin istirahat. Coba lagi besok',
    }),
    certify: null,
    shareLine: L({
      ko: '기억력 챌린지: 뇌세포 SOS 🆘 워밍업 구간에서부터 무너졌음... 오늘 뇌가 쉬고 싶다고 함 ㅋㅋ → 내 뇌세포 아직 살아있음? 너도 테스트해봐',
      en: 'Memory Challenge: Brain Cell SOS 🆘 Crashed during warmup... brain wants a day off lol → Are my brain cells still alive? Take the test too',
      ja: '記憶力チャレンジ：脳細胞SOS 🆘 ウォームアップから崩れた…今日は脳が休みたいらしい 笑 → 私の脳細胞まだ生きてる？ あなたもテストして',
      'zh-CN': '记忆力挑战：脑细胞SOS 🆘 热身阶段就崩了…今天大脑想休息 哈哈 → 我的脑细胞还活着吗？你也来测测',
      'zh-TW': '記憶力挑戰：腦細胞SOS 🆘 熱身階段就崩了…今天大腦想休息 哈哈 → 我的腦細胞還活著嗎？你也來測測',
      vi: 'Thử thách trí nhớ: SOS tế bào não 🆘 Gục ngay phần khởi động... não muốn nghỉ hôm nay haha → Tế bào não tôi còn sống không? Bạn cũng thử đi',
      id: 'Tantangan memori: SOS sel otak 🆘 Langsung collapse di pemanasan... otak mau libur hari ini wkwk → Sel otakku masih hidup? Kamu juga coba tesnya',
    }),
  },
  {
    type: 'Type2',
    emoji: '🧠',
    title: L({
      ko: '평균 기억력 보유자, 일반 뇌 작동 중',
      en: 'Average Memory Holder — Normal Brain Mode',
      ja: '平均記憶力保持者、通常脳作動中',
      'zh-CN': '平均记忆力持有者，普通大脑运转中',
      'zh-TW': '平均記憶力持有者，普通大腦運轉中',
      vi: 'Trí nhớ trung bình — não đang hoạt động bình thường',
      id: 'Pemilik memori rata-rata — otak mode normal',
    }),
    shortDescription: L({
      ko: '워밍업은 됐는데 속도가 빨라지면서 힘들어졌군요. 평균 수준입니다.',
      en: 'Warmup was fine, but it got harder as speed increased. That&apos;s average level.',
      ja: 'ウォームアップはできたけど、速度が上がると大変になった。平均レベルです。',
      'zh-CN': '热身还行，但速度加快后就吃力了。属于平均水平。',
      'zh-TW': '熱身還行，但速度加快後就吃力了。屬於平均水平。',
      vi: 'Phần khởi động ổn, nhưng tốc độ tăng lên thì khó hơn. Mức trung bình.',
      id: 'Pemanasan oke, tapi makin cepat makin susah. Level rata-rata.',
    }),
    description: L({
      ko: '워밍업 구간에선 어느 정도 맞혔는데 1초·0.5초 구간부터 급격히 어려워진 패턴입니다. 충분히 시간이 주어지면 잘 기억하지만 빠른 처리에서 손실이 많은 편입니다.',
      en: 'You did okay in warmup but struggled sharply from the 1-second and 0.5-second rounds. You remember well with enough time, but lose a lot under fast processing.',
      ja: 'ウォームアップではある程度正解したが、1秒・0.5秒区間から急に難しくなったパターンです。時間があればよく覚えるが、高速処理では損失が多いタイプです。',
      'zh-CN': '热身阶段还能答对一些，但从1秒、0.5秒区间开始明显变难。时间充足时记得不错，但快速处理时损失较多。',
      'zh-TW': '熱身階段還能答對一些，但從1秒、0.5秒區間開始明顯變難。時間充足時記得不錯，但快速處理時損失較多。',
      vi: 'Bạn làm khá ở phần khởi động nhưng khó đột ngột từ vòng 1 giây và 0,5 giây. Có đủ thời gian thì nhớ tốt, nhưng xử lý nhanh thì mất nhiều.',
      id: 'Kamu cukup baik di pemanasan tapi langsung sulit di ronde 1 detik dan 0,5 detik. Ingatannya bagus kalau waktu cukup, tapi banyak hilang saat proses cepat.',
    }),
    levelLabel: L({
      ko: 'Lv.2 일반 뇌 작동 🧠',
      en: 'Lv.2 Normal Brain Mode 🧠',
      ja: 'Lv.2 通常脳作動 🧠',
      'zh-CN': 'Lv.2 普通大脑运转 🧠',
      'zh-TW': 'Lv.2 普通大腦運轉 🧠',
      vi: 'Lv.2 Não hoạt động bình thường 🧠',
      id: 'Lv.2 Otak mode normal 🧠',
    }),
    characteristics: L({
      ko: '정답 수 3~5개, 강점: 워밍업(2초), 취약: 극한(0.5초)',
      en: 'Correct: 3–5, strength: warmup (2s), weakness: extreme (0.5s)',
      ja: '正解数3〜5、強み：ウォームアップ(2秒)、弱み：極限(0.5秒)',
      'zh-CN': '答对3~5题，优势：热身(2秒)，薄弱：极限(0.5秒)',
      'zh-TW': '答對3~5題，優勢：熱身(2秒)，薄弱：極限(0.5秒)',
      vi: 'Đúng 3–5 câu, mạnh: khởi động (2s), yếu: cực hạn (0,5s)',
      id: 'Benar 3–5, kuat: pemanasan (2d), lemah: ekstrem (0,5d)',
    }),
    strength: L({
      ko: '워밍업 (2초)',
      en: 'Warmup (2 seconds)',
      ja: 'ウォームアップ（2秒）',
      'zh-CN': '热身（2秒）',
      'zh-TW': '熱身（2秒）',
      vi: 'Khởi động (2 giây)',
      id: 'Pemanasan (2 detik)',
    }),
    weakness: L({
      ko: '극한 (0.5초)',
      en: 'Extreme (0.5 seconds)',
      ja: '極限（0.5秒）',
      'zh-CN': '极限（0.5秒）',
      'zh-TW': '極限（0.5秒）',
      vi: 'Cực hạn (0,5 giây)',
      id: 'Ekstrem (0,5 detik)',
    }),
    improvementTip: L({
      ko: '집중력 훈련·규칙적인 운동·뇌 영양소(오메가3) 섭취',
      en: 'Focus training, regular exercise, and brain nutrients (omega-3)',
      ja: '集中力トレーニング・定期的な運動・脳栄養素（オメガ3）摂取',
      'zh-CN': '专注力训练、规律运动、补充脑部营养（Omega-3）',
      'zh-TW': '專注力訓練、規律運動、補充腦部營養（Omega-3）',
      vi: 'Luyện tập tập trung, tập thể dục đều, bổ sung dinh dưỡng não (omega-3)',
      id: 'Latihan fokus, olahraga rutin, dan nutrisi otak (omega-3)',
    }),
    oneLiner: L({
      ko: '평균입니다. 연습하면 더 올릴 수 있습니다',
      en: 'Average level. Practice can improve your score',
      ja: '平均です。練習すればもっと上げられます',
      'zh-CN': '平均水平。多练习还能提高',
      'zh-TW': '平均水平。多練習還能提高',
      vi: 'Mức trung bình. Luyện tập sẽ cải thiện được',
      id: 'Level rata-rata. Latihan bisa meningkatkan skor',
    }),
    certify: null,
    shareLine: L({
      ko: '기억력 챌린지: 일반 뇌 🧠 2초는 됐는데 0.5초에서 완전 포기... 0.5초가 이렇게 짧은 줄 몰랐음 → 내 뇌세포 아직 살아있음? 챌린지해봐',
      en: 'Memory Challenge: Normal Brain 🧠 2 seconds was okay but gave up at 0.5s... didn&apos;t know 0.5s was this short → Are my brain cells still alive? Take the challenge',
      ja: '記憶力チャレンジ：通常脳 🧠 2秒はできたけど0.5秒で完全に諦めた…0.5秒ってこんなに短いとは → 私の脳細胞まだ生きてる？ チャレンジして',
      'zh-CN': '记忆力挑战：普通大脑 🧠 2秒还行但0.5秒完全放弃…原来0.5秒这么短 → 我的脑细胞还活着吗？来挑战吧',
      'zh-TW': '記憶力挑戰：普通大腦 🧠 2秒還行但0.5秒完全放棄…原來0.5秒這麼短 → 我的腦細胞還活著嗎？來挑戰吧',
      vi: 'Thử thách trí nhớ: Não bình thường 🧠 2 giây ổn nhưng 0,5 giây bỏ cuộc hoàn toàn... không biết 0,5 giây ngắn thế → Tế bào não tôi còn sống không? Thử thách đi',
      id: 'Tantangan memori: Otak normal 🧠 2 detik oke tapi menyerah total di 0,5 detik... nggak tahu 0,5 detik sesingkat itu → Sel otakku masih hidup? Coba tantangannya',
    }),
  },
  {
    type: 'Type3',
    emoji: '✅',
    title: L({
      ko: '기억력 우수형, 뇌세포 살아있음 인증',
      en: 'Strong Memory Type — Brain Cells Alive Certified',
      ja: '記憶力優秀型、脳細胞生きてる認証',
      'zh-CN': '记忆力优秀型，脑细胞存活认证',
      'zh-TW': '記憶力優秀型，腦細胞存活認證',
      vi: 'Kiểu trí nhớ tốt — xác nhận tế bào não còn sống',
      id: 'Tipe memori kuat — sel otak hidup tercertifikasi',
    }),
    shortDescription: L({
      ko: '절반 이상을 맞혔습니다. 당신의 뇌세포는 살아있습니다.',
      en: 'You got more than half correct. Your brain cells are alive.',
      ja: '半分以上正解しました。あなたの脳細胞は生きています。',
      'zh-CN': '答对了一半以上。你的脑细胞还活着。',
      'zh-TW': '答對了一半以上。你的腦細胞還活著。',
      vi: 'Bạn trả lời đúng hơn một nửa. Tế bào não bạn còn sống.',
      id: 'Kamu benar lebih dari setengah. Sel otakmu masih hidup.',
    }),
    description: L({
      ko: '1초 구간까지 꽤 잘 버텼고 0.5초 구간에서 일부를 맞혔습니다. 단기 기억력이 평균 이상이고 빠른 시각 처리 능력이 있습니다. 조금만 더 훈련하면 고수 단계에 도달할 수 있습니다.',
      en: 'You held up well through the 1-second rounds and got some right in the 0.5-second zone. Your short-term memory is above average with solid fast visual processing. A little more training could reach expert level.',
      ja: '1秒区間まではかなり耐え、0.5秒区間でも一部正解しました。短期記憶力は平均以上で、速い視覚処理能力があります。もう少し訓練すれば上級者レベルに到達できます。',
      'zh-CN': '1秒区间撑得不错，0.5秒区间也答对了一部分。短期记忆高于平均，具备快速视觉处理能力。再训练一下就能达到高手水平。',
      'zh-TW': '1秒區間撐得不錯，0.5秒區間也答對了一部分。短期記憶高於平均，具備快速視覺處理能力。再訓練一下就能達到高手水平。',
      vi: 'Bạn trụ tốt đến vòng 1 giây và trả lời đúng một phần ở vòng 0,5 giây. Trí nhớ ngắn hạn trên trung bình với khả năng xử lý hình ảnh nhanh. Luyện thêm chút nữa có thể lên cấp cao thủ.',
      id: 'Kamu bertahan baik sampai ronde 1 detik dan benar sebagian di zona 0,5 detik. Memori jangka pendek di atas rata-rata dengan pemrosesan visual cepat. Sedikit latihan lagi bisa capai level ahli.',
    }),
    levelLabel: L({
      ko: 'Lv.3 뇌세포 살아있음 ✅',
      en: 'Lv.3 Brain Cells Alive ✅',
      ja: 'Lv.3 脳細胞生きてる ✅',
      'zh-CN': 'Lv.3 脑细胞存活 ✅',
      'zh-TW': 'Lv.3 腦細胞存活 ✅',
      vi: 'Lv.3 Tế bào não còn sống ✅',
      id: 'Lv.3 Sel otak hidup ✅',
    }),
    characteristics: L({
      ko: '정답 수 6~8개, 강점: 워밍업+중급, 개선: 극한(0.5초)',
      en: 'Correct: 6–8, strength: warmup + mid, improve: extreme (0.5s)',
      ja: '正解数6〜8、強み：ウォームアップ+中級、改善：極限(0.5秒)',
      'zh-CN': '答对6~8题，优势：热身+中级，待提升：极限(0.5秒)',
      'zh-TW': '答對6~8題，優勢：熱身+中級，待提升：極限(0.5秒)',
      vi: 'Đúng 6–8 câu, mạnh: khởi động + trung cấp, cần cải thiện: cực hạn (0,5s)',
      id: 'Benar 6–8, kuat: pemanasan + menengah, perlu tingkatkan: ekstrem (0,5d)',
    }),
    strength: L({
      ko: '워밍업 + 중급 구간',
      en: 'Warmup + mid rounds',
      ja: 'ウォームアップ + 中級区間',
      'zh-CN': '热身 + 中级区间',
      'zh-TW': '熱身 + 中級區間',
      vi: 'Khởi động + vòng trung cấp',
      id: 'Pemanasan + ronde menengah',
    }),
    weakness: L({
      ko: '극한 (0.5초)',
      en: 'Extreme (0.5 seconds)',
      ja: '極限（0.5秒）',
      'zh-CN': '极限（0.5秒）',
      'zh-TW': '極限（0.5秒）',
      vi: 'Cực hạn (0,5 giây)',
      id: 'Ekstrem (0,5 detik)',
    }),
    improvementTip: L({
      ko: '처음 봤을 때 핵심 하나에 집중하는 연습',
      en: 'Practice focusing on one key detail when you first see the image',
      ja: '最初に見たとき、核心の1つに集中する練習',
      'zh-CN': '练习第一眼就聚焦一个关键信息',
      'zh-TW': '練習第一眼就聚焦一個關鍵資訊',
      vi: 'Luyện tập tập trung vào một điểm chính ngay khi nhìn thấy',
      id: 'Latihan fokus pada satu detail kunci saat pertama melihat',
    }),
    oneLiner: L({
      ko: '기억력 좋은 편입니다. 뇌세포 살아있음 공식 인증',
      en: 'Strong memory. Officially certified: brain cells alive',
      ja: '記憶力は良い方です。脳細胞生きてる公式認証',
      'zh-CN': '记忆力不错。官方认证：脑细胞存活',
      'zh-TW': '記憶力不錯。官方認證：腦細胞存活',
      vi: 'Trí nhớ khá tốt. Xác nhận chính thức: tế bào não còn sống',
      id: 'Memori cukup bagus. Sertifikasi resmi: sel otak hidup',
    }),
    certify: null,
    shareLine: L({
      ko: '기억력 챌린지: 뇌세포 살아있음 인증 ✅ 절반 이상 맞혔음... 0.5초 위치 기억 R12가 제일 어려웠음 → 너는 몇 개 맞혔어? 도전해봐',
      en: 'Memory Challenge: Brain Cells Alive Certified ✅ Got more than half... R12 position memory at 0.5s was hardest → How many did you get? Take the challenge',
      ja: '記憶力チャレンジ：脳細胞生きてる認証 ✅ 半分以上正解…0.5秒の位置記憶R12が一番難しかった → あなたは何問正解？ 挑戦して',
      'zh-CN': '记忆力挑战：脑细胞存活认证 ✅ 答对一半以上…0.5秒位置记忆R12最难 → 你答对几题？来挑战',
      'zh-TW': '記憶力挑戰：腦細胞存活認證 ✅ 答對一半以上…0.5秒位置記憶R12最難 → 你答對幾題？來挑戰',
      vi: 'Thử thách trí nhớ: Xác nhận tế bào não còn sống ✅ Đúng hơn một nửa... nhớ vị trí R12 ở 0,5s khó nhất → Bạn đúng mấy câu? Thử thách đi',
      id: 'Tantangan memori: Sel otak hidup tercertifikasi ✅ Benar lebih dari setengah... ingat posisi R12 di 0,5d paling susah → Kamu benar berapa? Coba tantangannya',
    }),
  },
  {
    type: 'Type4',
    emoji: '🔥',
    title: L({
      ko: '기억력 고수, 뇌 풀가동 상태',
      en: 'Memory Expert — Brain at Full Power',
      ja: '記憶力上級者、脳フル稼働状態',
      'zh-CN': '记忆力高手，大脑全速运转',
      'zh-TW': '記憶力高手，大腦全速運轉',
      vi: 'Cao thủ trí nhớ — não chạy hết công suất',
      id: 'Ahli memori — otak full power',
    }),
    shortDescription: L({
      ko: '0.5초 구간에서도 맞혔습니다. 상위 15%에 해당합니다.',
      en: 'You got some right even in the 0.5-second zone. Top 15%.',
      ja: '0.5秒区間でも正解しました。上位15%に該当します。',
      'zh-CN': '0.5秒区间也答对了。属于前15%。',
      'zh-TW': '0.5秒區間也答對了。屬於前15%。',
      vi: 'Bạn trả lời đúng cả ở vòng 0,5 giây. Thuộc top 15%.',
      id: 'Kamu benar bahkan di zona 0,5 detik. Top 15%.',
    }),
    description: L({
      ko: '극한 구간에서도 상당수를 맞혔다는 것이 이 점수의 포인트입니다. 시각 정보를 즉각적으로 부호화하고 단기 기억에 저장하는 능력이 뛰어납니다. 게임·악기·암기 과목에서 강점이 있는 유형입니다.',
      en: 'The key point of this score is getting many right even in extreme rounds. You excel at instantly encoding visual info into short-term memory. Strong in games, instruments, and memorization subjects.',
      ja: '極限区間でもかなり正解したことがこのスコアのポイントです。視覚情報を即座に符号化し短期記憶に保存する能力に優れています。ゲーム・楽器・暗記科目で強みがあるタイプです。',
      'zh-CN': '这个分数的关键是在极限区间也答对了很多。擅长即时编码视觉信息并存入短期记忆。在游戏、乐器、背诵科目方面有优势。',
      'zh-TW': '這個分數的關鍵是在極限區間也答對了很多。擅長即時編碼視覺資訊並存入短期記憶。在遊戲、樂器、背誦科目方面有優勢。',
      vi: 'Điểm mấu chốt là trả lời đúng nhiều câu cả ở vòng cực hạn. Bạn giỏi mã hóa thông tin hình ảnh ngay lập tức vào trí nhớ ngắn hạn. Mạnh về game, nhạc cụ và môn cần ghi nhớ.',
      id: 'Poin utamanya adalah benar banyak bahkan di ronde ekstrem. Kamu unggul mengodekan info visual langsung ke memori jangka pendek. Kuat di game, alat musik, dan mata pelajaran hafalan.',
    }),
    levelLabel: L({
      ko: 'Lv.4 뇌 풀가동 🔥',
      en: 'Lv.4 Brain Full Power 🔥',
      ja: 'Lv.4 脳フル稼働 🔥',
      'zh-CN': 'Lv.4 大脑全速运转 🔥',
      'zh-TW': 'Lv.4 大腦全速運轉 🔥',
      vi: 'Lv.4 Não full power 🔥',
      id: 'Lv.4 Otak full power 🔥',
    }),
    characteristics: L({
      ko: '정답 수 9~10개, 빠른 시각 정보 처리·단기 기억 용량 높음',
      en: 'Correct: 9–10, fast visual processing and high short-term memory capacity',
      ja: '正解数9〜10、速い視覚情報処理・短期記憶容量が高い',
      'zh-CN': '答对9~10题，快速视觉信息处理·短期记忆容量高',
      'zh-TW': '答對9~10題，快速視覺資訊處理·短期記憶容量高',
      vi: 'Đúng 9–10 câu, xử lý hình ảnh nhanh · dung lượng trí nhớ ngắn hạn cao',
      id: 'Benar 9–10, pemrosesan visual cepat · kapasitas memori jangka pendek tinggi',
    }),
    strength: L({
      ko: '빠른 시각 정보 처리·단기 기억 용량 높음',
      en: 'Fast visual processing and high short-term memory capacity',
      ja: '速い視覚情報処理・短期記憶容量が高い',
      'zh-CN': '快速视觉信息处理·短期记忆容量高',
      'zh-TW': '快速視覺資訊處理·短期記憶容量高',
      vi: 'Xử lý hình ảnh nhanh · dung lượng trí nhớ ngắn hạn cao',
      id: 'Pemrosesan visual cepat · kapasitas memori jangka pendek tinggi',
    }),
    weakness: L({
      ko: '12점 만점까지 2~3개 차이. 재도전하면 만점 가능',
      en: '2–3 away from a perfect 12. Retake for a perfect score',
      ja: '満点12点まで2〜3問差。再挑戦すれば満点可能',
      'zh-CN': '距离满分12分还差2~3题。再挑战可能满分',
      'zh-TW': '距離滿分12分還差2~3題。再挑戰可能滿分',
      vi: 'Cách điểm tối đa 12 còn 2–3 câu. Thử lại có thể đạt tuyệt đối',
      id: 'Tinggal 2–3 dari skor sempurna 12. Coba lagi bisa perfect',
    }),
    improvementTip: null,
    oneLiner: L({
      ko: '뇌가 거의 풀가동 중입니다. 만점 도전 가능합니다',
      en: 'Your brain is nearly at full power. A perfect score is within reach',
      ja: '脳はほぼフル稼働中です。満点挑戦可能です',
      'zh-CN': '大脑几乎全速运转中。可以挑战满分',
      'zh-TW': '大腦幾乎全速運轉中。可以挑戰滿分',
      vi: 'Não gần như chạy hết công suất. Có thể thử đạt điểm tuyệt đối',
      id: 'Otakmu hampir full power. Skor sempurna mungkin dicapai',
    }),
    certify: null,
    shareLine: L({
      ko: '기억력 챌린지: 뇌 풀가동 🔥 상위 15% 결과... 0.5초 극한 구간도 맞혔음 근데 만점은 아쉽게 놓침 → 내 뇌세포 아직 살아있음 인증 너도 해봐',
      en: 'Memory Challenge: Brain Full Power 🔥 Top 15% result... got extreme 0.5s rounds but missed perfect score → My brain cells alive certified — you try too',
      ja: '記憶力チャレンジ：脳フル稼働 🔥 上位15%結果…0.5秒極限区間も正解したけど満点は惜しく逃した → 私の脳細胞生きてる認証 あなたもやって',
      'zh-CN': '记忆力挑战：大脑全速运转 🔥 前15%结果…0.5秒极限也答对了但满分遗憾错过 → 我的脑细胞存活认证 你也试试',
      'zh-TW': '記憶力挑戰：大腦全速運轉 🔥 前15%結果…0.5秒極限也答對了但滿分遺憾錯過 → 我的腦細胞存活認證 你也試試',
      vi: 'Thử thách trí nhớ: Não full power 🔥 Top 15%... đúng cả vòng cực hạn 0,5s nhưng tiếc vì chưa tuyệt đối → Xác nhận tế bào não tôi còn sống, bạn cũng thử đi',
      id: 'Tantangan memori: Otak full power 🔥 Hasil top 15%... benar ronde ekstrem 0,5d tapi sayang belum perfect → Sel otakku hidup tercertifikasi, kamu juga coba',
    }),
  },
  {
    type: 'Type5',
    emoji: '🏆',
    title: L({
      ko: '기억력 끝판왕, 인간 블랙박스',
      en: 'Ultimate Memory Master — Human Black Box',
      ja: '記憶力最終ボス、人間ブラックボックス',
      'zh-CN': '记忆力终极王者，人类黑匣子',
      'zh-TW': '記憶力終極王者，人類黑匣子',
      vi: 'Vua trí nhớ tối thượng — hộp đen con người',
      id: 'Raja memori ultimat — black box manusia',
    }),
    shortDescription: L({
      ko: '0.5초짜리 극한 구간까지 대부분 맞혔습니다. 당신의 뇌는 블랙박스입니다.',
      en: 'You got most right even in the 0.5-second extreme zone. Your brain is a black box.',
      ja: '0.5秒の極限区間まで大部分正解しました。あなたの脳はブラックボックスです。',
      'zh-CN': '0.5秒的极限区间也大多答对了。你的大脑就是黑匣子。',
      'zh-TW': '0.5秒的極限區間也大多答對了。你的大腦就是黑匣子。',
      vi: 'Bạn trả lời đúng hầu hết cả ở vòng cực hạn 0,5 giây. Não bạn là hộp đen.',
      id: 'Kamu benar sebagian besar bahkan di zona ekstrem 0,5 detik. Otakmu adalah black box.',
    }),
    description: L({
      ko: '12문항 중 11~12개를 맞혔다는 것은 단기 기억 용량과 시각 정보 처리 속도 모두 상위권이라는 의미입니다. 이 테스트에서 이 결과가 나올 확률은 매우 낮습니다. 친구에게 공유하면 아무도 믿지 않을 것입니다.',
      en: 'Getting 11–12 out of 12 means top-tier short-term memory capacity and visual processing speed. This result is extremely rare in this test. Share with friends and nobody will believe you.',
      ja: '12問中11〜12問正解は、短期記憶容量と視覚情報処理速度の両方が上位圏であることを意味します。このテストでこの結果が出る確率は非常に低いです。友達にシェアしても誰も信じないでしょう。',
      'zh-CN': '12题中答对11~12题，说明短期记忆容量和视觉信息处理速度都在顶尖水平。在这个测试中得出此结果的概率极低。分享给朋友，没人会相信。',
      'zh-TW': '12題中答對11~12題，說明短期記憶容量和視覺資訊處理速度都在頂尖水準。在這個測試中得出此結果的機率極低。分享給朋友，沒人會相信。',
      vi: 'Trả lời đúng 11–12/12 nghĩa là dung lượng trí nhớ ngắn hạn và tốc độ xử lý hình ảnh đều thuộc hàng đầu. Kết quả này cực kỳ hiếm trong bài test. Chia sẻ với bạn bè, không ai tin.',
      id: 'Benar 11–12 dari 12 berarti kapasitas memori jangka pendek dan kecepatan pemrosesan visual top tier. Hasil ini sangat langka di tes ini. Bagikan ke teman, tidak ada yang percaya.',
    }),
    levelLabel: L({
      ko: 'Lv.5 인간 블랙박스 🏆',
      en: 'Lv.5 Human Black Box 🏆',
      ja: 'Lv.5 人間ブラックボックス 🏆',
      'zh-CN': 'Lv.5 人类黑匣子 🏆',
      'zh-TW': 'Lv.5 人類黑匣子 🏆',
      vi: 'Lv.5 Hộp đen con người 🏆',
      id: 'Lv.5 Black box manusia 🏆',
    }),
    characteristics: L({
      ko: '정답 수 11~12개, 0.5초 위치+아이콘 조합 R12까지 성공',
      en: 'Correct: 11–12, succeeded through R12 position + icon combo at 0.5s',
      ja: '正解数11〜12、0.5秒の位置+アイコン組み合わせR12まで成功',
      'zh-CN': '答对11~12题，0.5秒位置+图标组合R12也成功',
      'zh-TW': '答對11~12題，0.5秒位置+圖示組合R12也成功',
      vi: 'Đúng 11–12 câu, thành công đến R12 vị trí + biểu tượng ở 0,5s',
      id: 'Benar 11–12, sukses sampai R12 posisi + ikon combo di 0,5d',
    }),
    strength: L({
      ko: '바둑·체스·언어 학습·암기 시험',
      en: 'Go, chess, language learning, and memorization exams',
      ja: '囲碁・チェス・語学学習・暗記試験',
      'zh-CN': '围棋·国际象棋·语言学习·背诵考试',
      'zh-TW': '圍棋·國際象棋·語言學習·背誦考試',
      vi: 'Cờ vây · cờ vua · học ngoại ngữ · thi ghi nhớ',
      id: 'Go, catur, belajar bahasa, dan ujian hafalan',
    }),
    weakness: null,
    improvementTip: null,
    oneLiner: L({
      ko: '당신의 뇌는 블랙박스입니다. 이 결과를 친구에게 보내세요',
      en: 'Your brain is a black box. Send this result to your friends',
      ja: 'あなたの脳はブラックボックスです。この結果を友達に送ってください',
      'zh-CN': '你的大脑就是黑匣子。把这个结果发给朋友吧',
      'zh-TW': '你的大腦就是黑匣子。把這個結果發給朋友吧',
      vi: 'Não bạn là hộp đen. Gửi kết quả này cho bạn bè đi',
      id: 'Otakmu adalah black box. Kirim hasil ini ke teman-temanmu',
    }),
    certify: L({
      ko: '내 뇌세포 아직 살아있음 🏆 기억력 끝판왕 인증 완료',
      en: 'My brain cells are still alive 🏆 Ultimate memory master certified',
      ja: '私の脳細胞まだ生きてる 🏆 記憶力最終ボス認証完了',
      'zh-CN': '我的脑细胞还活着 🏆 记忆力终极王者认证完成',
      'zh-TW': '我的腦細胞還活著 🏆 記憶力終極王者認證完成',
      vi: 'Tế bào não tôi vẫn còn sống 🏆 Xác nhận vua trí nhớ tối thượng',
      id: 'Sel otakku masih hidup 🏆 Raja memori ultimat tercertifikasi',
    }),
    shareLine: L({
      ko: '기억력 챌린지: 인간 블랙박스 🏆 11~12개 맞힘... 0.5초짜리 아이콘 위치 조합도 맞혔음 ㅋㅋ → 내 뇌세포 아직 살아있음 인증 완료 너도 해봐서 이겨봐',
      en: 'Memory Challenge: Human Black Box 🏆 Got 11–12 right... nailed the 0.5s icon position combo lol → My brain cells alive certified — beat me if you can',
      ja: '記憶力チャレンジ：人間ブラックボックス 🏆 11〜12問正解…0.5秒のアイコン位置組み合わせも正解 笑 → 私の脳細胞生きてる認証完了 あなたもやって勝ってみて',
      'zh-CN': '记忆力挑战：人类黑匣子 🏆 答对11~12题…0.5秒图标位置组合也对了 哈哈 → 我的脑细胞存活认证完成 你也来比比看',
      'zh-TW': '記憶力挑戰：人類黑匣子 🏆 答對11~12題…0.5秒圖示位置組合也對了 哈哈 → 我的腦細胞存活認證完成 你也來比比看',
      vi: 'Thử thách trí nhớ: Hộp đen con người 🏆 Đúng 11–12 câu... combo vị trí biểu tượng 0,5s cũng đúng haha → Xác nhận tế bào não tôi còn sống — thử thách và thắng tôi đi',
      id: 'Tantangan memori: Black box manusia 🏆 Benar 11–12... combo posisi ikon 0,5d juga benar wkwk → Sel otakku hidup tercertifikasi — coba kalahkan aku',
    }),
  },
];
