/** 나의 그릿(Grit) 지수 측정 — phase3-grit-index · 12문항 4지선다 · A=0/B=1/C=2/D=3 · 7개 로케일 */

export type Phase3GritIndexLocaleKey = 'ko' | 'en' | 'ja' | 'zh-CN' | 'zh-TW' | 'vi' | 'id';

function localeMap(t: Record<Phase3GritIndexLocaleKey, string>): Record<Phase3GritIndexLocaleKey, string> {
  return t;
}

export interface Phase3GritIndexQuestion {
  id: number;
  question: Record<Phase3GritIndexLocaleKey, string>;
  options: { text: Record<Phase3GritIndexLocaleKey, string>; score: number }[];
}

export interface Phase3GritIndexResult {
  type: string;
  emoji: string;
  title: Record<Phase3GritIndexLocaleKey, string>;
  gritIndex: Record<Phase3GritIndexLocaleKey, string>;
  quote: Record<Phase3GritIndexLocaleKey, string>;
  description: Record<Phase3GritIndexLocaleKey, string>;
  perseveranceDiagnosis: Record<Phase3GritIndexLocaleKey, string>;
  passionDiagnosis: Record<Phase3GritIndexLocaleKey, string>;
  actionItems: Record<Phase3GritIndexLocaleKey, string>;
  duckworthQuote: Record<Phase3GritIndexLocaleKey, string>;
  commonTraits: Record<Phase3GritIndexLocaleKey, string>;
  caution: Record<Phase3GritIndexLocaleKey, string>;
  certificationPhrase: Record<Phase3GritIndexLocaleKey, string>;
  oneLiner: Record<Phase3GritIndexLocaleKey, string>;
  shareLine: Record<Phase3GritIndexLocaleKey, string>;
}

export function calculatePhase3GritIndexResult(answers: number[]): string {
  const total = answers.reduce((sum, s) => sum + (s ?? 0), 0);
  if (total <= 5) return 'Type1';
  if (total <= 11) return 'Type2';
  if (total <= 19) return 'Type3';
  if (total <= 27) return 'Type4';
  if (total <= 33) return 'Type5';
  return 'Type6';
}

export const phase3GritIndexQuestions: Phase3GritIndexQuestion[] = [
  {
    id: 1,
    question: localeMap({
      ko: "하고 있던 일이 생각보다 훨씬 어렵다는 걸 알게 됐을 때 나는?",
      en: "When I realize what I'm doing is much harder than expected, I...",
      ja: "やっていたことが思った以上に難しいと気づいたとき、私は？",
      'zh-CN': "当我发现正在做的事比想象中难得多时，我会？",
      'zh-TW': "當我發現正在做的事比想像中難得多時，我會？",
      vi: "Khi nhận ra việc đang làm khó hơn nhiều so với tưởng tượng, tôi...",
      id: "Ketika sadar apa yang kukerjakan jauh lebih sulit dari bayangan, aku...",
    }),
    options: [
      {
        text: localeMap({
      ko: "이 정도면 내 길이 아닌 것 같다는 생각이 들고 다른 방향을 찾아본다",
      en: "Think this probably isn't my path and start looking for another direction",
      ja: "これは自分の道ではないと感じ、他の方向を探す",
      'zh-CN': "觉得这可能不是我的路，开始找别的方向",
      'zh-TW': "覺得這可能不是我的路，開始找別的方向",
      vi: "Nghĩ đây có lẽ không phải con đường của mình và bắt đầu tìm hướng khác",
      id: "Merasa ini bukan jalanku dan mulai mencari arah lain",
    }),
        score: 0,
      },
      {
        text: localeMap({
      ko: "힘들지만 일단 조금 더 해보되 안 되면 방향을 바꿀 수도 있다고 생각한다",
      en: "It's tough, but I'll try a bit more—if it doesn't work, I might change direction",
      ja: "辛いが、もう少しやってみてダメなら方向転換もありだと思う",
      'zh-CN': "虽然辛苦但先再试一下，不行再换方向",
      'zh-TW': "雖然辛苦但先再試一下，不行再換方向",
      vi: "Khó khăn nhưng cứ thử thêm, không được thì đổi hướng",
      id: "Susah sih, tapi coba dulu lebih lama—kalau tidak berhasil baru pindah arah",
    }),
        score: 1,
      },
      {
        text: localeMap({
      ko: "어렵다는 것이 오히려 이게 의미 있는 일이라는 신호라고 생각하고 계속한다",
      en: "I see difficulty as a sign this is meaningful work, and keep going",
      ja: "難しいことはむしろこれが意味ある仕事だという合図だと思い続ける",
      'zh-CN': "越难反而觉得越有意义，继续坚持",
      'zh-TW': "越難反而覺得越有意義，繼續堅持",
      vi: "Thấy khó khăn là dấu hiệu việc này có ý nghĩa, và tiếp tục",
      id: "Melihat kesulitan sebagai tanda ini pekerjaan bermakna, dan terus lanjut",
    }),
        score: 2,
      },
      {
        text: localeMap({
      ko: "어려울수록 더 집중한다. 이 벽을 넘는 것 자체가 목표가 된다",
      en: "The harder it gets, the more I focus. Overcoming this wall becomes the goal itself",
      ja: "難しいほど集中する。この壁を越えること自体が目標になる",
      'zh-CN': "越困难越集中。翻过这面墙本身就成为目标",
      'zh-TW': "越困難越集中。翻過這面牆本身就成為目標",
      vi: "Càng khó càng tập trung. Vượt qua bức tường này trở thành mục tiêu",
      id: "Semakin sulit, semakin fokus. Melewati tembok ini sendiri jadi tujuannya",
    }),
        score: 3,
      },
    ],
  },
  {
    id: 2,
    question: localeMap({
      ko: "나는 몇 년째 지속적으로 관심을 갖고 있는 분야나 목표가 있는가?",
      en: "Do I have a field or goal I've been consistently interested in for years?",
      ja: "数年間ずっと関心を持ち続けている分野や目標はあるか？",
      'zh-CN': "我有持续关注多年的领域或目标吗？",
      'zh-TW': "我有持續關注多年的領域或目標嗎？",
      vi: "Tôi có lĩnh vực hoặc mục tiêu nào đã quan tâm liên tục nhiều năm không?",
      id: "Apakah aku punya bidang atau tujuan yang terus diminati selama bertahun-tahun?",
    }),
    options: [
      {
        text: localeMap({
      ko: "딱히 없다. 관심사가 자주 바뀌는 편이다",
      en: "Not really. My interests change often",
      ja: "特にない。興味がよく変わるほう",
      'zh-CN': "没什么，兴趣经常变",
      'zh-TW': "沒什麼，興趣經常變",
      vi: "Không có. Sở thích thay đổi khá thường xuyên",
      id: "Tidak juga. Minatku sering berubah",
    }),
        score: 0,
      },
      {
        text: localeMap({
      ko: "있긴 한데 중간에 흥미가 식거나 방향이 바뀐 적이 있다",
      en: "Yes, but my interest cooled or direction shifted along the way",
      ja: "あるが、途中で興味が冷めたり方向が変わったことがある",
      'zh-CN': "有，但中途兴趣变淡或方向变了",
      'zh-TW': "有，但中途興趣變淡或方向變了",
      vi: "Có, nhưng giữa chừng hứng thú giảm hoặc đổi hướng",
      id: "Ada, tapi di tengah jalan minat menurun atau arah berubah",
    }),
        score: 1,
      },
      {
        text: localeMap({
      ko: "3년 이상 같은 방향으로 나아가고 있는 목표나 관심사가 있다",
      en: "I have a goal or interest I've been pursuing in the same direction for 3+ years",
      ja: "3年以上同じ方向で進んでいる目標や関心事がある",
      'zh-CN': "有一个朝同一方向前进3年以上的目标或兴趣",
      'zh-TW': "有一個朝同一方向前進3年以上的目標或興趣",
      vi: "Có mục tiêu hoặc sở thích đã theo đuổi cùng hướng hơn 3 năm",
      id: "Ada tujuan atau minat yang sudah kujalani ke arah yang sama selama 3+ tahun",
    }),
        score: 2,
      },
      {
        text: localeMap({
      ko: "5년 이상 변함없이 집중해온 것이 있다. 그것이 내 정체성의 일부다",
      en: "I've focused on one thing consistently for 5+ years. It's part of my identity",
      ja: "5年以上変わらず集中してきたものがある。それが私のアイデンティティの一部",
      'zh-CN': "有坚持5年以上不变的事，它已是我身份的一部分",
      'zh-TW': "有堅持5年以上不變的事，它已是我身份的一部分",
      vi: "Có thứ đã tập trung hơn 5 năm. Nó là một phần bản sắc của tôi",
      id: "Ada yang sudah kufokuskan 5+ tahun. Itu bagian dari identitasku",
    }),
        score: 3,
      },
    ],
  },
  {
    id: 3,
    question: localeMap({
      ko: "크게 실패하거나 노력이 결과로 이어지지 않았을 때 나는?",
      en: "When I fail badly or my efforts don't lead to results, I...",
      ja: "大きく失敗したり努力が結果につながらなかったとき、私は？",
      'zh-CN': "当严重失败或努力没有结果时，我会？",
      'zh-TW': "當嚴重失敗或努力沒有結果時，我會？",
      vi: "Khi thất bại nặng hoặc nỗ lực không có kết quả, tôi...",
      id: "Ketika gagal besar atau usahaku tidak membuahkan hasil, aku...",
    }),
    options: [
      {
        text: localeMap({
      ko: "한동안 의욕이 크게 떨어지고 다시 시작하기까지 시간이 많이 걸린다",
      en: "My motivation drops significantly and it takes a long time to start again",
      ja: "しばらく意欲が大きく落ちて再開するまで時間がかかる",
      'zh-CN': "动力大幅下降，需要很久才能重新开始",
      'zh-TW': "動力大幅下降，需要很久才能重新開始",
      vi: "Động lực giảm mạnh và mất nhiều thời gian để bắt đầu lại",
      id: "Motivasiku turun drastis dan butuh waktu lama untuk mulai lagi",
    }),
        score: 0,
      },
      {
        text: localeMap({
      ko: "기운이 빠지지만 어느 정도 추스르고 다시 시도한다",
      en: "I feel drained but pull myself together and try again",
      ja: "気力は落ちるがある程度立て直してまた挑戦する",
      'zh-CN': "虽然很泄气但还是振作起来再试",
      'zh-TW': "雖然很洩氣但還是振作起來再試",
      vi: "Kiệt sức nhưng gượng lại và thử lại",
      id: "Merasa lemas tapi bangkit dan coba lagi",
    }),
        score: 1,
      },
      {
        text: localeMap({
      ko: "실패 원인을 분석하고 수정해서 다음에 더 잘하려고 한다",
      en: "I analyze the cause of failure, fix it, and try to do better next time",
      ja: "失敗の原因を分析して修正し、次に活かそうとする",
      'zh-CN': "分析失败原因并修正，争取下次做得更好",
      'zh-TW': "分析失敗原因並修正，爭取下次做得更好",
      vi: "Phân tích nguyên nhân thất bại, sửa chữa và cố gắng tốt hơn",
      id: "Menganalisis penyebab kegagalan, memperbaiki, dan berusaha lebih baik",
    }),
        score: 2,
      },
      {
        text: localeMap({
      ko: "실패가 쌓일수록 오히려 방법을 찾는 데 몰두한다. 안 되면 다른 방법을 찾을 뿐이다",
      en: "The more failures pile up, the more I dive into finding solutions. If one way fails, I just find another",
      ja: "失敗が重なるほどむしろ方法を探すことに没頭する。ダメなら別の方法を探すだけ",
      'zh-CN': "失败越多反而越专注于找方法。不行就换个方法",
      'zh-TW': "失敗越多反而越專注於找方法。不行就換個方法",
      vi: "Thất bại càng nhiều càng đắm chìm tìm giải pháp. Không được thì tìm cách khác",
      id: "Semakin banyak gagal, semakin fokus mencari cara. Tidak bisa ya cari cara lain",
    }),
        score: 3,
      },
    ],
  },
  {
    id: 4,
    question: localeMap({
      ko: "처음엔 정말 하고 싶었던 일이 시간이 지나면서 어떻게 되는가?",
      en: "What happens to something I really wanted to do as time passes?",
      ja: "最初は本当にやりたかったことが時間とともにどうなるか？",
      'zh-CN': "最初真心想做的事随着时间推移会怎样？",
      'zh-TW': "最初真心想做的事隨著時間推移會怎樣？",
      vi: "Điều ban đầu rất muốn làm sẽ ra sao theo thời gian?",
      id: "Apa yang terjadi pada hal yang awalnya sangat ingin kulakukan seiring waktu?",
    }),
    options: [
      {
        text: localeMap({
      ko: "어느 순간 식어있는 경우가 많다. 새로운 것이 생기면 관심이 옮겨간다",
      en: "Often it cools off. When something new appears, my interest shifts",
      ja: "いつの間にか冷めていることが多い。新しいものが出ると関心が移る",
      'zh-CN': "经常不知不觉就冷了，新东西出来兴趣就转移了",
      'zh-TW': "經常不知不覺就冷了，新東西出來興趣就轉移了",
      vi: "Thường nguội lạnh lúc nào không biết. Có thứ mới là chuyển hướng",
      id: "Sering mendingin tanpa sadar. Kalau ada hal baru, minat langsung pindah",
    }),
        score: 0,
      },
      {
        text: localeMap({
      ko: "가끔 의욕이 떨어지지만 환경이나 기분에 따라 다시 살아나기도 한다",
      en: "Sometimes motivation drops, but it revives depending on environment or mood",
      ja: "時々やる気が落ちるが、環境や気分で復活することもある",
      'zh-CN': "有时动力下降，但看环境和心情有时也会恢复",
      'zh-TW': "有時動力下降，但看環境和心情有時也會恢復",
      vi: "Đôi khi mất động lực nhưng tùy môi trường hay tâm trạng có thể hồi phục",
      id: "Kadang motivasi turun, tapi bisa bangkit lagi tergantung lingkungan atau mood",
    }),
        score: 1,
      },
      {
        text: localeMap({
      ko: "초반의 흥분은 줄지만 오래 할수록 더 깊은 흥미가 생기는 편이다",
      en: "Initial excitement fades, but deeper interest grows the longer I do it",
      ja: "最初の興奮は減るが、長く続けるほど深い興味が生まれる",
      'zh-CN': "初期的兴奋会减少，但越久越产生更深的兴趣",
      'zh-TW': "初期的興奮會減少，但越久越產生更深的興趣",
      vi: "Hào hứng ban đầu giảm nhưng càng lâu càng thấy hứng thú sâu hơn",
      id: "Kegembiraan awal berkurang tapi minat semakin dalam seiring waktu",
    }),
        score: 2,
      },
      {
        text: localeMap({
      ko: "시간이 지날수록 더 깊이 파고들고 싶어진다. 오래할수록 더 좋아진다",
      en: "The more time passes, the deeper I want to dig. The longer I do it, the more I like it",
      ja: "時間が経つほどもっと深く掘り下げたくなる。長くやるほど好きになる",
      'zh-CN': "时间越久越想深入钻研。越久越喜欢",
      'zh-TW': "時間越久越想深入鑽研。越久越喜歡",
      vi: "Càng lâu càng muốn đào sâu hơn. Làm càng lâu càng thích",
      id: "Semakin lama semakin ingin mendalami. Semakin lama semakin suka",
    }),
        score: 3,
      },
    ],
  },
  {
    id: 5,
    question: localeMap({
      ko: "목표를 이루기 위해 반드시 해야 하지만 지루하고 반복적인 과정을 해야 할 때 나는?",
      en: "When I must do boring, repetitive work to reach my goal, I...",
      ja: "目標のためにやらねばならない退屈で繰り返しの作業をするとき、私は？",
      'zh-CN': "为了目标必须做无聊重复的事时，我会？",
      'zh-TW': "為了目標必須做無聊重複的事時，我會？",
      vi: "Khi phải làm việc nhàm chán lặp đi lặp lại để đạt mục tiêu, tôi...",
      id: "Ketika harus melakukan pekerjaan membosankan dan berulang untuk mencapai tujuan, aku...",
    }),
    options: [
      {
        text: localeMap({
      ko: "지루한 과정을 피하는 방법을 먼저 찾게 된다. 효율적인 방법이 있을 것이라 생각한다",
      en: "I look for ways to skip the boring parts first. I think there must be a shortcut",
      ja: "まず退屈な過程を避ける方法を探す。効率的な方法があるはずだと思う",
      'zh-CN': "先想办法跳过无聊的部分，觉得肯定有效率更高的方法",
      'zh-TW': "先想辦法跳過無聊的部分，覺得肯定有效率更高的方法",
      vi: "Tìm cách bỏ qua phần nhàm chán trước. Nghĩ chắc có cách hiệu quả hơn",
      id: "Mencari cara menghindari bagian membosankan dulu. Pasti ada jalan pintas",
    }),
        score: 0,
      },
      {
        text: localeMap({
      ko: "어쩔 수 없이 하긴 하는데 그 시간이 길어지면 집중력이 흐트러진다",
      en: "I do it reluctantly, but lose focus if it drags on too long",
      ja: "仕方なくやるが、長く続くと集中力が乱れる",
      'zh-CN': "虽然勉强做但时间一长就分心了",
      'zh-TW': "雖然勉強做但時間一長就分心了",
      vi: "Miễn cưỡng làm nhưng kéo dài thì mất tập trung",
      id: "Terpaksa melakukan tapi kalau terlalu lama, fokus buyar",
    }),
        score: 1,
      },
      {
        text: localeMap({
      ko: "지루해도 이 과정이 필요하다는 걸 알기 때문에 의식적으로 버텨낸다",
      en: "Even when bored, I consciously push through because I know this process is necessary",
      ja: "退屈でもこの過程が必要だとわかっているから意識的に耐える",
      'zh-CN': "即使无聊也知道这过程必不可少，有意识地坚持",
      'zh-TW': "即使無聊也知道這過程必不可少，有意識地堅持",
      vi: "Dù chán vẫn biết quá trình này cần thiết nên cố ý kiên trì",
      id: "Meski bosan, aku sadar proses ini perlu dan bertahan secara sadar",
    }),
        score: 2,
      },
      {
        text: localeMap({
      ko: "반복 속에서 미세한 발전을 찾는 것이 습관이 됐다. 루틴 자체가 즐겁다",
      en: "Finding tiny improvements within repetition has become a habit. The routine itself is enjoyable",
      ja: "繰り返しの中で微細な進歩を見つけることが習慣になった。ルーティン自体が楽しい",
      'zh-CN': "在重复中发现微小进步已成习惯。routine本身就是享受",
      'zh-TW': "在重複中發現微小進步已成習慣。routine本身就是享受",
      vi: "Tìm tiến bộ nhỏ trong sự lặp lại đã thành thói quen. Bản thân routine đã vui",
      id: "Menemukan kemajuan kecil dalam pengulangan sudah jadi kebiasaan. Rutinnya sendiri menyenangkan",
    }),
        score: 3,
      },
    ],
  },
  {
    id: 6,
    question: localeMap({
      ko: "지금 하고 있는 일과 관계없는 새롭고 흥미로운 것이 생겼을 때 나는?",
      en: "When something new and interesting appears unrelated to what I'm doing now, I...",
      ja: "今やっていることと関係ない新しく興味深いものが出てきたとき、私は？",
      'zh-CN': "当出现与我正在做的事无关的新鲜有趣的东西时，我会？",
      'zh-TW': "當出現與我正在做的事無關的新鮮有趣的東西時，我會？",
      vi: "Khi xuất hiện thứ mới thú vị không liên quan đến việc đang làm, tôi...",
      id: "Ketika muncul hal baru menarik yang tidak terkait dengan apa yang sedang kukerjakan, aku...",
    }),
    options: [
      {
        text: localeMap({
      ko: "새로운 것에 자주 끌리고 이것저것 시도해보는 편이다. 다양한 경험이 중요하다고 생각한다",
      en: "I'm often drawn to new things and try various stuff. Diverse experience matters to me",
      ja: "新しいものによく惹かれて色々試すほう。多様な経験が大事だと思う",
      'zh-CN': "经常被新事物吸引，喜欢各种尝试。觉得多元体验很重要",
      'zh-TW': "經常被新事物吸引，喜歡各種嘗試。覺得多元體驗很重要",
      vi: "Thường bị thu hút bởi cái mới và thử nhiều thứ. Trải nghiệm đa dạng quan trọng",
      id: "Sering tertarik hal baru dan coba berbagai hal. Pengalaman beragam itu penting",
    }),
        score: 0,
      },
      {
        text: localeMap({
      ko: "관심은 가지만 지금 하는 것이 있으니 일단 메모해두고 나중에 보자는 식이다",
      en: "I'm interested but note it down for later since I'm busy with my current work",
      ja: "関心は持つが今やっていることがあるのでメモして後で見ようという感じ",
      'zh-CN': "有兴趣但现在有事，先记下以后再看",
      'zh-TW': "有興趣但現在有事，先記下以後再看",
      vi: "Quan tâm nhưng đang bận nên ghi lại xem sau",
      id: "Tertarik tapi karena lagi sibuk, dicatat dulu untuk nanti",
    }),
        score: 1,
      },
      {
        text: localeMap({
      ko: "호기심이 생겨도 지금 방향과 맞는지 먼저 따져보는 편이다",
      en: "Even when curious, I first check whether it aligns with my current direction",
      ja: "好奇心が生まれても今の方向に合うかまず考えるほう",
      'zh-CN': "即使好奇也会先看跟现在的方向是否一致",
      'zh-TW': "即使好奇也會先看跟現在的方向是否一致",
      vi: "Dù tò mò vẫn xem trước có phù hợp hướng hiện tại không",
      id: "Meski penasaran, aku cek dulu apakah sesuai dengan arah saat ini",
    }),
        score: 2,
      },
      {
        text: localeMap({
      ko: "새로운 것이 아무리 매력적으로 보여도 내 핵심 방향을 흔들지는 않는다",
      en: "No matter how attractive something new looks, it doesn't shake my core direction",
      ja: "新しいものがどんなに魅力的でも自分のコアな方向は揺らがない",
      'zh-CN': "新东西再诱人也不会动摇我的核心方向",
      'zh-TW': "新東西再誘人也不會動搖我的核心方向",
      vi: "Dù thứ mới hấp dẫn đến đâu cũng không lay chuyển hướng đi cốt lõi",
      id: "Sebermenarik apapun hal baru, arah intiku tidak goyah",
    }),
        score: 3,
      },
    ],
  },
  {
    id: 7,
    question: localeMap({
      ko: "몇 달 이상 걸리는 장기 프로젝트나 목표를 진행할 때 나는?",
      en: "When working on a long-term project or goal taking months or more, I...",
      ja: "数ヶ月以上かかる長期プロジェクトや目標を進めるとき、私は？",
      'zh-CN': "进行需要数月以上的长期项目或目标时，我会？",
      'zh-TW': "進行需要數月以上的長期專案或目標時，我會？",
      vi: "Khi thực hiện dự án hoặc mục tiêu dài hạn mất nhiều tháng, tôi...",
      id: "Saat mengerjakan proyek atau tujuan jangka panjang berbulan-bulan, aku...",
    }),
    options: [
      {
        text: localeMap({
      ko: "초반 의욕은 높지만 시간이 지나면서 흐지부지되는 경우가 많다",
      en: "Initial motivation is high but it often fizzles out over time",
      ja: "最初の意欲は高いが時間が経つと尻すぼみになることが多い",
      'zh-CN': "初期很有干劲但随着时间慢慢就不了了之",
      'zh-TW': "初期很有幹勁但隨著時間慢慢就不了了之",
      vi: "Đầu rất hăng nhưng dần dà thường bỏ dở",
      id: "Motivasi awal tinggi tapi sering meredup seiring waktu",
    }),
        score: 0,
      },
      {
        text: localeMap({
      ko: "마감이나 외부 동기가 있으면 유지되지만 없으면 흔들린다",
      en: "I stay on track with deadlines or external motivation, but waver without them",
      ja: "締め切りや外的動機があれば維持できるが、なければ揺らぐ",
      'zh-CN': "有deadline或外在动力时能坚持，没有就容易动摇",
      'zh-TW': "有deadline或外在動力時能堅持，沒有就容易動搖",
      vi: "Có deadline hoặc động lực bên ngoài thì duy trì được, không có thì lung lay",
      id: "Dengan deadline atau motivasi eksternal bisa bertahan, tanpa itu goyah",
    }),
        score: 1,
      },
      {
        text: localeMap({
      ko: "중간에 슬럼프가 와도 스스로 다시 궤도에 올려놓는 방법을 알고 있다",
      en: "Even when a slump hits mid-way, I know how to get myself back on track",
      ja: "途中でスランプが来ても自分で軌道に戻す方法を知っている",
      'zh-CN': "中途遇到低谷也知道怎么让自己重回正轨",
      'zh-TW': "中途遇到低谷也知道怎麼讓自己重回正軌",
      vi: "Dù gặp khủng hoảng giữa chừng vẫn biết cách quay lại đường ray",
      id: "Meski slump di tengah jalan, aku tahu cara kembali ke jalurnya",
    }),
        score: 2,
      },
      {
        text: localeMap({
      ko: "장기 프로젝트일수록 더 잘 유지된다. 단기보다 장기에 강한 편이다",
      en: "The longer the project, the better I maintain it. I'm stronger with long-term than short-term",
      ja: "長期プロジェクトほどうまく維持できる。短期より長期に強い",
      'zh-CN': "项目越长期反而越能坚持。比起短期我更擅长长期",
      'zh-TW': "專案越長期反而越能堅持。比起短期我更擅長長期",
      vi: "Dự án càng dài hạn càng duy trì tốt. Mạnh hơn ở dài hạn",
      id: "Semakin panjang proyeknya, semakin baik aku menjalankannya. Lebih kuat di jangka panjang",
    }),
        score: 3,
      },
    ],
  },
  {
    id: 8,
    question: localeMap({
      ko: "지금으로부터 5년 후 내가 어디에 있고 싶은지에 대해 나는?",
      en: "Regarding where I want to be 5 years from now, I...",
      ja: "今から5年後、自分がどこにいたいかについて、私は？",
      'zh-CN': "关于5年后我想在哪里，我会？",
      'zh-TW': "關於5年後我想在哪裡，我會？",
      vi: "Về nơi tôi muốn ở sau 5 năm nữa, tôi...",
      id: "Soal di mana aku ingin berada 5 tahun dari sekarang, aku...",
    }),
    options: [
      {
        text: localeMap({
      ko: "솔직히 잘 모르겠다. 그때 가봐야 알 것 같다",
      en: "Honestly, I'm not sure. I think I'll know when I get there",
      ja: "正直よくわからない。その時になってみないとわからない",
      'zh-CN': "说实话不太确定，到时候再说吧",
      'zh-TW': "說實話不太確定，到時候再說吧",
      vi: "Thành thật là không chắc. Đến lúc đó mới biết",
      id: "Jujur nggak tahu. Kayaknya baru tahu nanti",
    }),
        score: 0,
      },
      {
        text: localeMap({
      ko: "대략적인 방향은 있지만 구체적인 그림은 아직 흐릿하다",
      en: "I have a rough direction but the specific picture is still blurry",
      ja: "大まかな方向はあるが具体的なイメージはまだぼんやり",
      'zh-CN': "大致方向有但具体画面还很模糊",
      'zh-TW': "大致方向有但具體畫面還很模糊",
      vi: "Có hướng đại khái nhưng hình ảnh cụ thể còn mờ nhạt",
      id: "Ada arah kasar tapi gambarannya masih kabur",
    }),
        score: 1,
      },
      {
        text: localeMap({
      ko: "꽤 명확한 방향이 있고 지금 하는 것들이 거기에 연결되어 있다",
      en: "I have a fairly clear direction and what I'm doing now connects to it",
      ja: "かなり明確な方向があり、今やっていることはそこにつながっている",
      'zh-CN': "方向很明确，现在做的事都和它有关联",
      'zh-TW': "方向很明確，現在做的事都和它有關聯",
      vi: "Có hướng khá rõ ràng và những gì đang làm đều kết nối với nó",
      id: "Punya arah yang cukup jelas dan yang kulakukan sekarang terhubung ke sana",
    }),
        score: 2,
      },
      {
        text: localeMap({
      ko: "5년 후뿐만 아니라 10년 후 그림까지 어느 정도 그려져 있다. 지금 모든 것이 그 방향으로 정렬되어 있다",
      en: "I've sketched not just 5 years but 10 years ahead. Everything now is aligned to that direction",
      ja: "5年後だけでなく10年後の絵もある程度描けている。今のすべてがその方向に整列している",
      'zh-CN': "不止5年，10年后的蓝图也有了。现在一切都朝那个方向对齐",
      'zh-TW': "不止5年，10年後的藍圖也有了。現在一切都朝那個方向對齊",
      vi: "Không chỉ 5 năm mà bức tranh 10 năm cũng đã phác. Mọi thứ bây giờ đều hướng về đó",
      id: "Bukan hanya 5 tahun, gambaran 10 tahun pun sudah ada. Semua yang kulakukan sekarang selaras ke sana",
    }),
        score: 3,
      },
    ],
  },
  {
    id: 9,
    question: localeMap({
      ko: "\"이걸 왜 하고 있지? 그냥 그만둘까?\"라는 생각이 들 때 나는?",
      en: "When I think 'Why am I doing this? Should I just quit?', I...",
      ja: "「なんでこれやってるんだろう？やめようかな」と思ったとき、私は？",
      'zh-CN': "当我想'我为什么在做这个？干脆放弃吧'时，我会？",
      'zh-TW': "當我想'我為什麼在做這個？乾脆放棄吧'時，我會？",
      vi: "Khi nghĩ 'Sao mình lại làm cái này? Bỏ quách đi?', tôi...",
      id: "Saat berpikir 'Kenapa aku melakukan ini? Menyerah saja?', aku...",
    }),
    options: [
      {
        text: localeMap({
      ko: "그 생각이 한번 들면 실제로 그만두게 되는 경우가 많다",
      en: "Once that thought hits, I actually end up quitting most of the time",
      ja: "その考えが浮かんだら実際にやめてしまうことが多い",
      'zh-CN': "一旦有这想法就真的会放弃的情况很多",
      'zh-TW': "一旦有這想法就真的會放棄的情況很多",
      vi: "Khi ý nghĩ đó xuất hiện, thường thì thực sự bỏ luôn",
      id: "Begitu pikiran itu muncul, sering kali benar-benar berhenti",
    }),
        score: 0,
      },
      {
        text: localeMap({
      ko: "한동안 흔들리다가 이유를 다시 찾으면 계속하기도 하고 그만두기도 한다",
      en: "I waver for a while, and depending on whether I find a reason again, I continue or quit",
      ja: "しばらく揺れて、理由を再び見つければ続けることも、やめることもある",
      'zh-CN': "动摇一阵子，如果能重新找到理由就继续，找不到就放弃",
      'zh-TW': "動搖一陣子，如果能重新找到理由就繼續，找不到就放棄",
      vi: "Lung lay một thời gian, nếu tìm lại lý do thì tiếp, không thì bỏ",
      id: "Goyah sejenak, kalau menemukan alasan lagi lanjut, kalau tidak ya berhenti",
    }),
        score: 1,
      },
      {
        text: localeMap({
      ko: "그 생각이 들면 처음 시작했던 이유를 다시 상기시키는 루틴이 있다",
      en: "When that thought comes, I have a routine to remind myself why I started",
      ja: "その考えが浮かんだら最初始めた理由を思い出すルーティンがある",
      'zh-CN': "有这种想法时会用固定方式提醒自己为什么开始",
      'zh-TW': "有這種想法時會用固定方式提醒自己為什麼開始",
      vi: "Khi có ý nghĩ đó, tôi có thói quen nhắc lại lý do bắt đầu",
      id: "Saat pikiran itu muncul, aku punya rutinitas untuk mengingat alasan aku memulai",
    }),
        score: 2,
      },
      {
        text: localeMap({
      ko: "그만두고 싶다는 생각 자체가 잘 들지 않는다. 들어도 금방 지나간다",
      en: "The thought of quitting rarely comes. Even when it does, it passes quickly",
      ja: "やめたいという考え自体がほとんど浮かばない。浮かんでもすぐ過ぎ去る",
      'zh-CN': "想放弃的念头很少出现。即使出现也很快就过去",
      'zh-TW': "想放棄的念頭很少出現。即使出現也很快就過去",
      vi: "Ý nghĩ bỏ cuộc hiếm khi xuất hiện. Có xuất hiện cũng qua nhanh",
      id: "Pikiran menyerah jarang muncul. Kalau pun muncul, cepat berlalu",
    }),
        score: 3,
      },
    ],
  },
  {
    id: 10,
    question: localeMap({
      ko: "내가 관심 있는 분야에 대해 나는?",
      en: "Regarding the fields I'm interested in, I...",
      ja: "自分が関心のある分野について、私は？",
      'zh-CN': "关于我感兴趣的领域，我会？",
      'zh-TW': "關於我感興趣的領域，我會？",
      vi: "Về lĩnh vực tôi quan tâm, tôi...",
      id: "Soal bidang yang aku minati, aku...",
    }),
    options: [
      {
        text: localeMap({
      ko: "여러 가지를 넓게 알고 싶다. 한 가지에 너무 깊이 파는 것보다 다양한 경험이 좋다",
      en: "I want to know many things broadly. Diverse experience beats going too deep into one thing",
      ja: "色々広く知りたい。一つに深く掘るより多様な経験がいい",
      'zh-CN': "想广泛了解各种东西。比起深入一件事更喜欢多元体验",
      'zh-TW': "想廣泛了解各種東西。比起深入一件事更喜歡多元體驗",
      vi: "Muốn biết rộng nhiều thứ. Trải nghiệm đa dạng tốt hơn đào sâu một thứ",
      id: "Ingin tahu banyak hal secara luas. Pengalaman beragam lebih baik daripada mendalami satu hal",
    }),
        score: 0,
      },
      {
        text: localeMap({
      ko: "어느 정도 깊이 알고 싶지만 그 분야의 전문가 수준까지 가고 싶다는 생각은 아직 없다",
      en: "I want to know reasonably deep, but I'm not yet thinking of expert-level mastery",
      ja: "ある程度深く知りたいがその分野の専門家レベルまで行きたいとはまだ思わない",
      'zh-CN': "想了解得比较深但还没想到专家水平",
      'zh-TW': "想了解得比較深但還沒想到專家水平",
      vi: "Muốn biết khá sâu nhưng chưa nghĩ đến mức chuyên gia",
      id: "Ingin tahu cukup dalam tapi belum berpikir sampai level ahli",
    }),
        score: 1,
      },
      {
        text: localeMap({
      ko: "하나를 알면 더 알고 싶어진다. 깊이 파는 과정 자체가 즐겁다",
      en: "The more I learn, the more I want to know. The process of digging deep is enjoyable",
      ja: "一つ知るともっと知りたくなる。深く掘る過程自体が楽しい",
      'zh-CN': "知道一点就想知道更多。深入钻研的过程本身就很有趣",
      'zh-TW': "知道一點就想知道更多。深入鑽研的過程本身就很有趣",
      vi: "Biết một thì muốn biết thêm. Quá trình đào sâu bản thân đã vui",
      id: "Semakin tahu semakin ingin tahu lagi. Proses mendalami itu sendiri menyenangkan",
    }),
        score: 2,
      },
      {
        text: localeMap({
      ko: "이 분야의 끝까지 가보고 싶다는 욕구가 있다. 평생 해도 다 못 알 것 같은 것에 끌린다",
      en: "I have an urge to reach the very end of this field. I'm drawn to things I could study for a lifetime",
      ja: "この分野の果てまで行きたいという欲求がある。一生やっても全部わからないものに惹かれる",
      'zh-CN': "有走到这个领域尽头的欲望。被那种一辈子也学不完的东西吸引",
      'zh-TW': "有走到這個領域盡頭的慾望。被那種一輩子也學不完的東西吸引",
      vi: "Có khao khát đi đến tận cùng lĩnh vực này. Bị thu hút bởi thứ cả đời cũng không học hết",
      id: "Punya dorongan untuk mencapai ujung bidang ini. Tertarik pada hal yang seumur hidup pun tidak habis dipelajari",
    }),
        score: 3,
      },
    ],
  },
  {
    id: 11,
    question: localeMap({
      ko: "아무도 알아주지 않고 당장 결과가 안 나와도 계속할 수 있는가?",
      en: "Can I keep going even when no one notices and results don't show immediately?",
      ja: "誰にも認められず、すぐ結果が出なくても続けられるか？",
      'zh-CN': "没人认可、短期看不到结果也能坚持吗？",
      'zh-TW': "沒人認可、短期看不到結果也能堅持嗎？",
      vi: "Không ai ghi nhận, kết quả không thấy ngay, có tiếp tục được không?",
      id: "Bisakah aku terus maju meski tidak ada yang menghargai dan hasilnya belum terlihat?",
    }),
    options: [
      {
        text: localeMap({
      ko: "솔직히 피드백이나 인정이 없으면 계속하기 어렵다. 반응이 있어야 동력이 생긴다",
      en: "Honestly, without feedback or recognition it's hard to continue. I need reactions for motivation",
      ja: "正直、フィードバックや認知がなければ続けるのは難しい。反応があってこそ動力が生まれる",
      'zh-CN': "说实话没有反馈或认可就很难继续。有回应才有动力",
      'zh-TW': "說實話沒有反饋或認可就很難繼續。有回應才有動力",
      vi: "Thành thật là không có phản hồi hoặc ghi nhận thì rất khó tiếp tục",
      id: "Jujur, tanpa feedback atau pengakuan sulit melanjutkan. Butuh respons untuk motivasi",
    }),
        score: 0,
      },
      {
        text: localeMap({
      ko: "어느 정도까지는 가능하지만 오래 지속되면 외부 동기가 필요해진다",
      en: "I can manage for a while, but eventually I need external motivation",
      ja: "ある程度までは可能だが、長く続くと外的動機が必要になる",
      'zh-CN': "一定程度上可以，但持续太久就需要外在动力",
      'zh-TW': "一定程度上可以，但持續太久就需要外在動力",
      vi: "Có thể ở mức nào đó nhưng lâu dài thì cần động lực bên ngoài",
      id: "Bisa sampai titik tertentu, tapi kalau terlalu lama butuh motivasi eksternal",
    }),
        score: 1,
      },
      {
        text: localeMap({
      ko: "내가 방향이 맞다고 믿으면 당장 결과가 없어도 상당 기간 버틸 수 있다",
      en: "If I believe I'm on the right path, I can endure a long time without immediate results",
      ja: "方向が合っていると信じるなら、すぐ結果がなくてもかなりの期間耐えられる",
      'zh-CN': "如果相信方向没错，即使暂时没结果也能坚持很长时间",
      'zh-TW': "如果相信方向沒錯，即使暫時沒結果也能堅持很長時間",
      vi: "Nếu tin đúng hướng, không có kết quả ngay cũng chịu được khá lâu",
      id: "Kalau yakin arahnya benar, bisa bertahan lama meski belum ada hasil",
    }),
        score: 2,
      },
      {
        text: localeMap({
      ko: "외부 반응과 관계없이 할 수 있다. 오히려 아무도 모르는 과정이 더 집중이 잘 된다",
      en: "I can keep going regardless of external reactions. In fact, working unnoticed helps me focus more",
      ja: "外部の反応に関係なく続けられる。むしろ誰も知らない過程の方が集中できる",
      'zh-CN': "跟外界反应无关都能继续。反而没人知道的过程更能专注",
      'zh-TW': "跟外界反應無關都能繼續。反而沒人知道的過程更能專注",
      vi: "Có thể tiếp tục bất kể phản ứng bên ngoài. Thực tế, quá trình không ai biết lại tập trung hơn",
      id: "Bisa terus tanpa peduli reaksi luar. Justru proses tanpa diketahui siapapun lebih fokus",
    }),
        score: 3,
      },
    ],
  },
  {
    id: 12,
    question: localeMap({
      ko: "지금 내가 하고 있는 것들이 나의 더 큰 삶의 방향이나 목적과 연결되어 있다고 느끼는가?",
      en: "Do I feel what I'm doing now is connected to the bigger direction or purpose of my life?",
      ja: "今やっていることがより大きな人生の方向や目的につながっていると感じるか？",
      'zh-CN': "我觉得现在做的事和更大的人生方向或目的有关联吗？",
      'zh-TW': "我覺得現在做的事和更大的人生方向或目的有關聯嗎？",
      vi: "Tôi có cảm thấy những gì đang làm kết nối với hướng đi lớn hơn của cuộc đời không?",
      id: "Apakah aku merasa apa yang kulakukan sekarang terhubung ke arah atau tujuan hidup yang lebih besar?",
    }),
    options: [
      {
        text: localeMap({
      ko: "아직 나의 큰 방향이 뭔지 잘 모르겠다. 지금은 일단 하루하루가 먼저다",
      en: "I'm not sure what my big direction is yet. For now, I take it day by day",
      ja: "まだ自分の大きな方向が何かよくわからない。今はまず一日一日が先",
      'zh-CN': "还不太清楚自己的大方向是什么。现在先过好每一天",
      'zh-TW': "還不太清楚自己的大方向是什麼。現在先過好每一天",
      vi: "Chưa rõ hướng đi lớn là gì. Bây giờ cứ sống từng ngày đã",
      id: "Belum tahu arah besarku apa. Untuk sekarang jalani hari demi hari dulu",
    }),
        score: 0,
      },
      {
        text: localeMap({
      ko: "어렴풋이 연결된 것 같기도 하지만 확신이 없다",
      en: "It vaguely feels connected, but I'm not sure",
      ja: "なんとなくつながっている気もするが確信がない",
      'zh-CN': "隐约觉得有关联但不确定",
      'zh-TW': "隱約覺得有關聯但不確定",
      vi: "Lờ mờ thấy có liên kết nhưng không chắc",
      id: "Samar-samar terasa terhubung tapi tidak yakin",
    }),
        score: 1,
      },
      {
        text: localeMap({
      ko: "연결되어 있다는 느낌이 있다. 지금 하는 것이 큰 그림의 일부라는 감각이 있다",
      en: "I feel connected. There's a sense that what I do now is part of the bigger picture",
      ja: "つながっている感じがある。今やっていることが大きな絵の一部だという感覚がある",
      'zh-CN': "感觉有关联。觉得现在做的是大蓝图的一部分",
      'zh-TW': "感覺有關聯。覺得現在做的是大藍圖的一部分",
      vi: "Cảm thấy có kết nối. Có cảm giác những gì đang làm là một phần bức tranh lớn",
      id: "Merasa terhubung. Ada rasa bahwa yang kulakukan sekarang bagian dari gambaran besar",
    }),
        score: 2,
      },
      {
        text: localeMap({
      ko: "명확하게 연결되어 있다. 지금 하는 모든 것이 내가 살고 싶은 삶을 향한 과정이라는 확신이 있다",
      en: "Clearly connected. I'm certain everything I do now is part of the journey toward the life I want",
      ja: "明確につながっている。今していることすべてが自分の生きたい人生への過程だという確信がある",
      'zh-CN': "明确地有关联。确信现在做的一切都是通往理想人生的过程",
      'zh-TW': "明確地有關聯。確信現在做的一切都是通往理想人生的過程",
      vi: "Kết nối rõ ràng. Chắc chắn mọi thứ đang làm đều là hành trình tới cuộc sống mong muốn",
      id: "Jelas terhubung. Yakin semua yang kulakukan sekarang adalah proses menuju hidup yang kuinginkan",
    }),
        score: 3,
      },
    ],
  },
];

export const phase3GritIndexResults: Phase3GritIndexResult[] = [
  {
    type: "Type1",
    emoji: "🌱",
    title: localeMap({
      ko: "아직 그릿이 씨앗 상태인, 그릿 발아 준비형 🌱",
      en: "Grit Seedling — Still Preparing to Sprout 🌱",
      ja: "グリットがまだ種の状態、発芽準備型 🌱",
      'zh-CN': "坚毅力还在种子阶段的萌芽准备型 🌱",
      'zh-TW': "堅毅力還在種子階段的萌芽準備型 🌱",
      vi: "Grit còn ở dạng hạt giống, kiểu chuẩn bị nảy mầm 🌱",
      id: "Grit masih dalam benih, tipe persiapan berkecambah 🌱",
    }),
    gritIndex: localeMap({
      ko: "12% 이하 / 열정·끈기 모두 아직 형성 중\n🌱 씨앗형",
      en: "≤12% / Both passion & perseverance still forming\n🌱 Seedling",
      ja: "12%以下 / 情熱・粘り強さ共にまだ形成中\n🌱 種型",
      'zh-CN': "≤12% / 热情·毅力都在形成中\n🌱 种子型",
      'zh-TW': "≤12% / 熱情·毅力都在形成中\n🌱 種子型",
      vi: "≤12% / Đam mê·bền bỉ đều đang hình thành\n🌱 Kiểu hạt giống",
      id: "≤12% / Semangat & ketekunan masih dalam pembentukan\n🌱 Tipe Benih",
    }),
    quote: localeMap({
      ko: "당신의 그릿은 아직 씨앗 상태입니다. 땅 속에 있어서 보이지 않을 뿐, 가능성이 없다는 뜻이 아닙니다.",
      en: "Your grit is still a seed. Just because it's underground doesn't mean there's no potential.",
      ja: "あなたのグリットはまだ種の状態です。土の中にいて見えないだけで、可能性がないという意味ではありません。",
      'zh-CN': "你的坚毅力还是种子状态。只是在土里看不见，不代表没有可能性。",
      'zh-TW': "你的堅毅力還是種子狀態。只是在土裡看不見，不代表沒有可能性。",
      vi: "Grit của bạn vẫn là hạt giống. Chỉ vì nằm dưới đất không có nghĩa là không có tiềm năng.",
      id: "Grit-mu masih berupa benih. Hanya karena masih di dalam tanah bukan berarti tak ada potensi.",
    }),
    description: localeMap({
      ko: "아직 장기적으로 지속하고 싶은 뚜렷한 목표나 방향이 명확하지 않은 상태입니다. 관심사가 자주 바뀌거나 시작은 하는데 오래 지속하기가 어렵거나 포기 충동이 왔을 때 버티기 어려운 패턴이 있습니다. 이것은 능력의 문제가 아닙니다. 아직 열정이 불붙을 것을 못 만난 상태일 수 있습니다.",
      en: "You don't yet have a clear long-term goal or direction. Interests change often, things start but don't last, and resisting the urge to quit is hard. This isn't about ability—you may simply haven't found what ignites your passion yet.",
      ja: "長期的に続けたい明確な目標や方向がまだ定まっていません。興味がよく変わり、始めても長続きしにくく、諦めの衝動に耐えにくいパターンがあります。能力の問題ではなく、まだ情熱に火がつくものに出会えていない状態かもしれません。",
      'zh-CN': "目前还没有清晰的长期目标或方向。兴趣经常变化，开始了却难以持续，面对放弃冲动时很难坚持。这不是能力问题——可能只是还没遇到能点燃热情的事物。",
      'zh-TW': "目前還沒有清晰的長期目標或方向。興趣經常變化，開始了卻難以持續，面對放棄衝動時很難堅持。這不是能力問題——可能只是還沒遇到能點燃熱情的事物。",
      vi: "Bạn chưa có mục tiêu hoặc hướng đi dài hạn rõ ràng. Sở thích hay thay đổi, bắt đầu nhưng khó duy trì, và khó chống lại cảm giác muốn bỏ cuộc. Đây không phải vấn đề năng lực—có thể bạn chưa tìm được thứ thắp lên đam mê.",
      id: "Kamu belum punya tujuan atau arah jangka panjang yang jelas. Minat sering berubah, mulai tapi sulit bertahan, dan sulit melawan dorongan untuk menyerah. Ini bukan soal kemampuan—mungkin kamu belum menemukan apa yang menyalakan semangatmu.",
    }),
    perseveranceDiagnosis: localeMap({
      ko: "어려운 상황에서 버티는 내성이 아직 형성되지 않음",
      en: "Resilience to push through difficult situations hasn't formed yet",
      ja: "困難な状況で耐える免疫がまだ形成されていない",
      'zh-CN': "面对困难时的抗压能力尚未形成",
      'zh-TW': "面對困難時的抗壓能力尚未形成",
      vi: "Khả năng chịu đựng trong tình huống khó khăn chưa hình thành",
      id: "Ketahanan menghadapi situasi sulit belum terbentuk",
    }),
    passionDiagnosis: localeMap({
      ko: "오랫동안 지속되는 관심사 또는 방향이 아직 불명확",
      en: "A lasting interest or direction is still unclear",
      ja: "長期間持続する関心事や方向がまだ不明確",
      'zh-CN': "持久的兴趣或方向仍不明确",
      'zh-TW': "持久的興趣或方向仍不明確",
      vi: "Sở thích hoặc hướng đi lâu dài vẫn chưa rõ",
      id: "Minat atau arah yang bertahan lama masih belum jelas",
    }),
    actionItems: localeMap({
      ko: "지금까지 살면서 시간 가는 줄 몰랐던 순간이 언제였는지 떠올려보기\n완주 경험 하나 만들기. 작은 것도 좋음. 끝내는 경험 자체가 그릿의 근육을 만듦\n타인의 목표가 아닌 진짜 내가 원하는 게 뭔지 탐색하는 시간 가지기",
      en: "Recall moments when you lost track of time—what were you doing?\nCreate one completion experience. Even small ones count. Finishing itself builds grit muscle.\nSpend time exploring what YOU truly want, not other people's goals.",
      ja: "今まで時間を忘れた瞬間はいつだったか思い出す\n完走体験を一つ作る。小さくてもいい。終わらせる体験自体がグリットの筋肉を作る\n他人の目標ではなく本当に自分が望むことを探す時間を持つ",
      'zh-CN': "回想一下过去什么时候忘记了时间——那时你在做什么？\n创造一次完成体验。小事也可以。完成本身就锻炼坚毅力。\n花时间探索你真正想要的，而不是别人的目标。",
      'zh-TW': "回想一下過去什麼時候忘記了時間——那時你在做什麼？\n創造一次完成體驗。小事也可以。完成本身就鍛鍊堅毅力。\n花時間探索你真正想要的，而不是別人的目標。",
      vi: "Nhớ lại khoảnh khắc bạn quên mất thời gian—lúc đó bạn đang làm gì?\nTạo một trải nghiệm hoàn thành. Nhỏ cũng được. Việc hoàn thành bản thân nó tạo cơ bắp grit.\nDành thời gian khám phá điều BẠN thực sự muốn, không phải mục tiêu người khác.",
      id: "Ingat-ingat momen ketika kamu lupa waktu—sedang apa saat itu?\nCiptakan satu pengalaman menyelesaikan sesuatu. Yang kecil juga boleh. Menyelesaikan itu sendiri membentuk otot grit.\nLuangkan waktu menjelajahi apa yang KAMU benar-benar inginkan, bukan tujuan orang lain.",
    }),
    duckworthQuote: localeMap({
      ko: "\"그릿은 타고나는 것이 아닙니다. 올바른 것을 발견하고 그것을 오래 지속하는 과정에서 생깁니다\"",
      en: "\"Grit is not innate. It develops when you discover the right thing and sustain it over time.\"",
      ja: "\"グリットは生まれつきのものではありません。正しいものを見つけ、それを長く続ける過程で生まれます\"",
      'zh-CN': "\"坚毅力不是天生的。它在发现正确的事并长期坚持的过程中产生。\"",
      'zh-TW': "\"堅毅力不是天生的。它在發現正確的事並長期堅持的過程中產生。\"",
      vi: "\"Grit không phải bẩm sinh. Nó hình thành khi bạn tìm thấy đúng thứ và duy trì lâu dài.\"",
      id: "\"Grit bukan bawaan lahir. Ia berkembang saat kamu menemukan hal yang tepat dan mempertahankannya.\"",
    }),
    commonTraits: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    caution: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    certificationPhrase: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    oneLiner: localeMap({
      ko: "\"씨앗은 땅 속에서 가장 오래 머뭅니다. 지금 그 안에서 뭔가가 자라고 있을 수 있습니다\"",
      en: "\"Seeds stay underground the longest. Something may be growing inside right now.\"",
      ja: "\"種は土の中で最も長く留まります。今その中で何かが育っているかもしれません\"",
      'zh-CN': "\"种子在土里待得最久。也许此刻内心正在生长着什么。\"",
      'zh-TW': "\"種子在土裡待得最久。也許此刻內心正在生長著什麼。\"",
      vi: "\"Hạt giống nằm dưới đất lâu nhất. Có thể bên trong đang lớn lên điều gì đó.\"",
      id: "\"Benih tinggal paling lama di dalam tanah. Mungkin sesuatu sedang tumbuh di dalamnya sekarang.\"",
    }),
    shareLine: localeMap({
      ko: "내 그릿 지수: 씨앗형 🌱 아직 열정과 끈기 모두 형성 중이래... 그래도 씨앗이 있다는 거 아님? ㅋㅋ → 나 그릿 지수 이래 너는 몇 점이야?",
      en: "My Grit Index: Seedling 🌱 Both passion & perseverance still forming... but hey, at least there's a seed! → What's your score?",
      ja: "私のグリット指数：種型🌱 情熱も粘り強さもまだ形成中だって…でも種はあるってこと！→ あなたは何点？",
      'zh-CN': "我的坚毅指数：种子型🌱 热情和毅力都还在形成中…不过至少有颗种子不是吗？→ 你几分？",
      'zh-TW': "我的堅毅指數：種子型🌱 熱情和毅力都還在形成中…不過至少有顆種子不是嗎？→ 你幾分？",
      vi: "Chỉ số Grit của tôi: Hạt giống 🌱 Cả đam mê và bền bỉ đều đang hình thành... nhưng ít nhất có hạt giống rồi! → Bạn mấy điểm?",
      id: "Indeks Grit-ku: Benih 🌱 Semangat & ketekunan masih terbentuk... tapi setidaknya ada benih! → Kamu berapa poin?",
    }),
  },
  {
    type: "Type2",
    emoji: "🔥",
    title: localeMap({
      ko: "열정은 있는데 끈기가 아직 짧은, 그릿 점화형 🔥",
      en: "Passionate but Short on Perseverance — Grit Ignition 🔥",
      ja: "情熱はあるが粘り強さがまだ足りない、グリット着火型 🔥",
      'zh-CN': "有热情但毅力不足的点火型 🔥",
      'zh-TW': "有熱情但毅力不足的點火型 🔥",
      vi: "Có đam mê nhưng bền bỉ còn ngắn, kiểu khởi phát Grit 🔥",
      id: "Bersemangat tapi ketekunan masih pendek — Grit Penyalaan 🔥",
    }),
    gritIndex: localeMap({
      ko: "17~30% / 열정 있음 · 끈기 형성 중\n🔥 점화형",
      en: "17–30% / Passion present · Perseverance forming\n🔥 Ignition",
      ja: "17〜30% / 情熱あり・粘り強さ形成中\n🔥 着火型",
      'zh-CN': "17~30% / 有热情·毅力形成中\n🔥 点火型",
      'zh-TW': "17~30% / 有熱情·毅力形成中\n🔥 點火型",
      vi: "17–30% / Có đam mê · Bền bỉ đang hình thành\n🔥 Kiểu khởi phát",
      id: "17–30% / Semangat ada · Ketekunan dalam pembentukan\n🔥 Tipe Penyalaan",
    }),
    quote: localeMap({
      ko: "불은 켜졌는데 아직 장작이 부족합니다. 타오르다가 꺼지는 패턴이 반복되고 있을 가능성이 있습니다.",
      en: "The fire is lit, but there's not enough firewood yet. You may be cycling between flaring up and burning out.",
      ja: "火は灯ったがまだ薪が足りません。燃え上がっては消えるパターンが繰り返されている可能性があります。",
      'zh-CN': "火已经点着了，但柴火还不够。可能正在反复经历燃起又熄灭的循环。",
      'zh-TW': "火已經點著了，但柴火還不夠。可能正在反覆經歷燃起又熄滅的循環。",
      vi: "Lửa đã bật nhưng củi chưa đủ. Có thể bạn đang lặp lại chu kỳ bùng lên rồi tắt.",
      id: "Apinya sudah menyala, tapi kayu bakarnya masih kurang. Mungkin kamu sedang dalam siklus menyala-padam berulang.",
    }),
    description: localeMap({
      ko: "새로운 것을 시작할 때 에너지가 높고 흥미도 있지만 어려운 구간이 오거나 결과가 안 보이면 의욕이 빠지는 패턴입니다. 관심사는 다양하지만 하나에 오래 머무르기가 어렵습니다. 열정은 분명히 있지만 그것이 단기 흥분인지 장기 관심인지 아직 구분이 안 되는 단계입니다.",
      en: "You start with high energy and interest, but motivation drops when things get hard or results don't show. Your interests are diverse but it's hard to stick with one. You clearly have passion—the question is whether it's short-term excitement or long-term commitment.",
      ja: "新しいことを始めるときエネルギーが高く興味もあるが、難しい区間が来たり結果が見えないと意欲が下がるパターン。興味は多様だが一つに長く留まるのが難しい。情熱は確かにあるが、それが短期の興奮か長期の関心かまだ区別がつかない段階。",
      'zh-CN': "开始新事物时精力旺盛兴趣浓厚，但遇到困难或看不到结果时就丧失动力。兴趣广泛但难以长期坚持一个。热情确实有，但还分不清是短期兴奋还是长期兴趣。",
      'zh-TW': "開始新事物時精力旺盛興趣濃厚，但遇到困難或看不到結果時就喪失動力。興趣廣泛但難以長期堅持一個。熱情確實有，但還分不清是短期興奮還是長期興趣。",
      vi: "Bạn bắt đầu với năng lượng cao nhưng mất động lực khi gặp khó khăn hoặc không thấy kết quả. Sở thích đa dạng nhưng khó gắn bó lâu. Rõ ràng có đam mê—câu hỏi là đó là hào hứng ngắn hạn hay cam kết dài hạn.",
      id: "Kamu memulai dengan energi tinggi, tapi motivasi turun saat sulit atau tak ada hasil. Minatmu beragam tapi sulit bertahan di satu hal. Semangat jelas ada—pertanyaannya: ini kegembiraan sesaat atau komitmen jangka panjang?",
    }),
    perseveranceDiagnosis: localeMap({
      ko: "단기 집중력은 있지만 장기 지속력에서 에너지 손실이 큼",
      en: "Short-term focus exists but energy loss in long-term persistence is significant",
      ja: "短期の集中力はあるが長期の持続力でのエネルギー損失が大きい",
      'zh-CN': "短期集中力有但长期坚持中能量损耗大",
      'zh-TW': "短期集中力有但長期堅持中能量損耗大",
      vi: "Tập trung ngắn hạn có nhưng mất năng lượng nhiều khi bền bỉ dài hạn",
      id: "Fokus jangka pendek ada tapi kehilangan energi besar di ketekunan jangka panjang",
    }),
    passionDiagnosis: localeMap({
      ko: "다양한 관심사가 있지만 하나의 방향으로 수렴되지 않음",
      en: "Diverse interests exist but haven't converged into one direction",
      ja: "多様な関心事があるが一つの方向に収束していない",
      'zh-CN': "兴趣广泛但未收敛到一个方向",
      'zh-TW': "興趣廣泛但未收斂到一個方向",
      vi: "Có nhiều sở thích nhưng chưa hội tụ về một hướng",
      id: "Minat beragam tapi belum menyatu ke satu arah",
    }),
    actionItems: localeMap({
      ko: "지금 하고 있는 것 중 가장 오래된 것에 집중하기. 새 것보다 오래된 것에 투자\n의욕이 떨어지는 구간이 언제 오는지 패턴을 파악하고 그 시점에 루틴을 만들기\n시작할 때 '3개월 뒤 어떤 모습이 되고 싶은가'를 적어두고 보이는 곳에 두기",
      en: "Focus on the oldest thing you're still doing. Invest in the old over the new.\nIdentify when motivation dips happen and create a routine for those moments.\nWhen starting, write down 'Where do I want to be in 3 months?' and keep it visible.",
      ja: "今やっていることの中で最も古いものに集中する。新しいものより古いものに投資\n意欲が落ちる区間がいつ来るかパターンを把握し、その時点にルーティンを作る\n始めるとき「3ヶ月後どうなりたいか」を書いて見えるところに置く",
      'zh-CN': "把精力放在你坚持最久的事上。投资老的而不是新的。\n找出动力下降的规律，在那个节点建立routine。\n开始时写下'3个月后想变成什么样'，放在看得见的地方。",
      'zh-TW': "把精力放在你堅持最久的事上。投資老的而不是新的。\n找出動力下降的規律，在那個節點建立routine。\n開始時寫下「3個月後想變成什麼樣」，放在看得見的地方。",
      vi: "Tập trung vào thứ bạn đã làm lâu nhất. Đầu tư vào thứ cũ hơn thứ mới.\nNhận diện khi nào động lực giảm và tạo thói quen cho thời điểm đó.\nKhi bắt đầu, viết ra '3 tháng sau muốn thế nào?' và để nơi dễ thấy.",
      id: "Fokus pada hal yang paling lama kamu kerjakan. Investasi di yang lama, bukan yang baru.\nKenali pola kapan motivasi turun dan buat rutinitas untuk momen itu.\nSaat mulai, tulis 'Ingin jadi apa 3 bulan lagi?' dan taruh di tempat yang terlihat.",
    }),
    duckworthQuote: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    commonTraits: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    caution: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    certificationPhrase: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    oneLiner: localeMap({
      ko: "\"불꽃이 있다는 것은 이미 강점입니다. 이제 그 불이 꺼지지 않게 장작을 쌓는 법을 익힐 시간입니다\"",
      en: "\"Having a spark is already a strength. Now it's time to learn how to stack firewood so it doesn't go out.\"",
      ja: "\"火花があるということはすでに強みです。今はその火が消えないよう薪を積む方法を学ぶ時です\"",
      'zh-CN': "\"有火花本身就是优势。现在是学会堆柴让火不灭的时候了。\"",
      'zh-TW': "\"有火花本身就是優勢。現在是學會堆柴讓火不滅的時候了。\"",
      vi: "\"Có tia lửa đã là thế mạnh. Giờ là lúc học cách chất củi để lửa không tắt.\"",
      id: "\"Punya percikan api sudah jadi kekuatan. Sekarang saatnya belajar menumpuk kayu bakar agar api tak padam.\"",
    }),
    shareLine: localeMap({
      ko: "내 그릿 지수: 점화형 🔥 불은 켜졌는데 장작이 부족하다는 거... 시작은 잘 하는데 오래 못 한다는 거 맞음 ㅠ → 나 그릿 지수 이래 너는?",
      en: "My Grit Index: Ignition 🔥 The fire is lit but not enough firewood... I start well but can't last long 😅 → What's yours?",
      ja: "私のグリット指数：着火型🔥 火はついたけど薪不足…始めるのは得意だけど長く続かない😅→ あなたは？",
      'zh-CN': "我的坚毅指数：点火型🔥 火点着了但柴不够…开头很好但持续不了😅→ 你呢？",
      'zh-TW': "我的堅毅指數：點火型🔥 火點著了但柴不夠…開頭很好但持續不了😅→ 你呢？",
      vi: "Chỉ số Grit: Khởi phát 🔥 Lửa bật rồi nhưng thiếu củi... bắt đầu tốt nhưng không bền 😅 → Bạn thì sao?",
      id: "Indeks Grit-ku: Penyalaan 🔥 Api sudah menyala tapi kurang kayu bakar... mulai bagus tapi tak bertahan lama 😅 → Kamu gimana?",
    }),
  },
  {
    type: "Type3",
    emoji: "📈",
    title: localeMap({
      ko: "균형 잡히기 시작한, 그릿 성장형 📈",
      en: "Finding Balance — Grit Growth 📈",
      ja: "バランスが取れ始めた、グリット成長型 📈",
      'zh-CN': "开始趋于平衡的成长型 📈",
      'zh-TW': "開始趨於平衡的成長型 📈",
      vi: "Bắt đầu cân bằng, kiểu tăng trưởng Grit 📈",
      id: "Mulai Seimbang — Grit Pertumbuhan 📈",
    }),
    gritIndex: localeMap({
      ko: "33~53% / 열정·끈기 모두 평균 이상으로 형성 중\n📈 성장형",
      en: "33–53% / Both passion & perseverance forming above average\n📈 Growth",
      ja: "33〜53% / 情熱・粘り強さ共に平均以上に形成中\n📈 成長型",
      'zh-CN': "33~53% / 热情·毅力都在平均以上形成中\n📈 成长型",
      'zh-TW': "33~53% / 熱情·毅力都在平均以上形成中\n📈 成長型",
      vi: "33–53% / Đam mê·bền bỉ đều hình thành trên trung bình\n📈 Kiểu tăng trưởng",
      id: "33–53% / Semangat & ketekunan terbentuk di atas rata-rata\n📈 Tipe Pertumbuhan",
    }),
    quote: localeMap({
      ko: "당신의 그릿은 성장하고 있습니다. 방향이 잡히기 시작했고 어려운 구간도 버텨본 경험이 쌓이고 있습니다.",
      en: "Your grit is growing. Direction is forming and you're building experience pushing through tough spots.",
      ja: "あなたのグリットは成長しています。方向が定まり始め、難しい区間を乗り越えた経験が積み重なっています。",
      'zh-CN': "你的坚毅力正在成长。方向开始确立，挺过困难的经验也在积累。",
      'zh-TW': "你的堅毅力正在成長。方向開始確立，挺過困難的經驗也在積累。",
      vi: "Grit của bạn đang phát triển. Hướng đi đang hình thành và bạn đang tích lũy kinh nghiệm vượt qua khó khăn.",
      id: "Grit-mu sedang tumbuh. Arah mulai terbentuk dan kamu membangun pengalaman melewati masa sulit.",
    }),
    description: localeMap({
      ko: "어떤 일을 오래 해본 경험이 있고 포기 충동이 와도 어느 정도 버텨내는 근육이 생기기 시작했습니다. 다만 아직 외부 동기가 있을 때와 없을 때의 차이가 크거나 슬럼프 구간에서 손실이 발생하는 패턴이 있을 수 있습니다.",
      en: "You have experience sticking with things for a while and have started building the muscle to resist quitting. However, you may still see big gaps between having and not having external motivation, and lose ground during slumps.",
      ja: "何かを長く続けた経験があり、諦めの衝動が来ても耐える筋肉ができ始めています。ただ外的動機の有無で差が大きかったり、スランプ期間に損失が生じるパターンがあるかもしれません。",
      'zh-CN': "你有一些长期坚持的经验，面对放弃冲动也开始有了抵抗的肌肉。不过有外在动力和没有时差距可能还很大，低谷期容易掉队。",
      'zh-TW': "你有一些長期堅持的經驗，面對放棄衝動也開始有了抵抗的肌肉。不過有外在動力和沒有時差距可能還很大，低谷期容易掉隊。",
      vi: "Bạn có kinh nghiệm gắn bó lâu và đã bắt đầu xây dựng sức mạnh chống lại ý muốn bỏ cuộc. Tuy nhiên, khoảng cách giữa có và không có động lực bên ngoài có thể còn lớn, và dễ mất tiến độ trong giai đoạn khủng hoảng.",
      id: "Kamu punya pengalaman bertahan cukup lama dan mulai punya otot untuk melawan keinginan menyerah. Tapi mungkin masih ada gap besar antara punya/tidak punya motivasi eksternal, dan kehilangan progres saat slump.",
    }),
    perseveranceDiagnosis: localeMap({
      ko: "어려운 구간을 버텨본 경험이 있고 회복력이 형성되고 있음",
      en: "Experience pushing through hard spots exists; resilience is forming",
      ja: "難しい区間を耐えた経験があり回復力が形成されつつある",
      'zh-CN': "有挺过困难的经验，恢复力正在形成",
      'zh-TW': "有挺過困難的經驗，恢復力正在形成",
      vi: "Có kinh nghiệm vượt qua khó khăn; khả năng phục hồi đang hình thành",
      id: "Punya pengalaman melewati masa sulit; ketahanan sedang terbentuk",
    }),
    passionDiagnosis: localeMap({
      ko: "방향성이 잡히고 있지만 아직 확신이 흔들리는 순간이 있음",
      en: "Direction is forming but there are moments when conviction wavers",
      ja: "方向性が定まりつつあるがまだ確信が揺れる瞬間がある",
      'zh-CN': "方向正在确立但信念偶尔动摇",
      'zh-TW': "方向正在確立但信念偶爾動搖",
      vi: "Hướng đi đang hình thành nhưng vẫn có lúc niềm tin dao động",
      id: "Arah sedang terbentuk tapi ada momen keyakinan goyah",
    }),
    actionItems: localeMap({
      ko: "지금까지 버텨낸 경험 목록 만들어보기. 증거를 쌓으면 자기 확신이 강해짐\n슬럼프가 올 때를 대비한 회복 루틴 미리 만들기 (책·사람·장소·말 한마디)\n지금 하는 일이 더 큰 목적과 어떻게 연결되는지 언어로 정리해보기",
      en: "List all the experiences you've endured so far. Stacking evidence strengthens self-belief.\nPrepare a recovery routine in advance for slumps (books, people, places, one quote).\nArticulate in words how what you do now connects to a bigger purpose.",
      ja: "今まで耐えてきた経験リストを作る。証拠を積めば自信が強くなる\nスランプに備えた回復ルーティンを先に作る（本・人・場所・一言）\n今していることがより大きな目的とどうつながるか言葉で整理する",
      'zh-CN': "列出你至今坚持过的经历清单。积累证据会增强自信。\n提前为低谷期准备恢复routine（书·人·地方·一句话）。\n用语言整理现在做的事跟更大目标的关系。",
      'zh-TW': "列出你至今堅持過的經歷清單。積累證據會增強自信。\n提前為低谷期準備恢復routine（書·人·地方·一句話）。\n用語言整理現在做的事跟更大目標的關係。",
      vi: "Liệt kê các trải nghiệm bạn đã kiên trì. Tích lũy bằng chứng củng cố niềm tin.\nChuẩn bị sẵn thói quen phục hồi cho giai đoạn khủng hoảng (sách, người, nơi chốn, một câu nói).\nDiễn đạt bằng lời cách việc bạn làm kết nối với mục đích lớn hơn.",
      id: "Buat daftar pengalaman yang sudah kamu lewati. Menumpuk bukti memperkuat keyakinan diri.\nSiapkan rutinitas pemulihan untuk slump (buku, orang, tempat, satu kutipan).\nJelaskan dalam kata-kata bagaimana yang kamu kerjakan terhubung ke tujuan lebih besar.",
    }),
    duckworthQuote: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    commonTraits: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    caution: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    certificationPhrase: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    oneLiner: localeMap({
      ko: "\"이미 많이 왔습니다. 그리고 그 과정에서 생긴 근육은 다음 도전에서 더 크게 작동할 것입니다\"",
      en: "\"You've already come a long way. The muscle built along the way will work even harder in your next challenge.\"",
      ja: "\"すでにたくさん来ました。その過程で生まれた筋肉は次の挑戦でもっと大きく作動するでしょう\"",
      'zh-CN': "\"你已经走了很远了。路上积累的力量在下次挑战中会发挥更大作用。\"",
      'zh-TW': "\"你已經走了很遠了。路上積累的力量在下次挑戰中會發揮更大作用。\"",
      vi: "\"Bạn đã đi rất xa rồi. Sức mạnh tích lũy sẽ phát huy lớn hơn trong thử thách tiếp theo.\"",
      id: "\"Kamu sudah melangkah jauh. Otot yang terbentuk di perjalanan akan bekerja lebih besar di tantangan berikutnya.\"",
    }),
    shareLine: localeMap({
      ko: "내 그릿 지수: 성장형 📈 끈기와 열정이 균형 잡히기 시작했대... 어려운 구간 버텨본 경험 있다는 거 인정 → 나 그릿 지수 이래 너도 측정해봐",
      en: "My Grit Index: Growth 📈 Perseverance and passion are starting to balance... I admit I've pushed through tough times → Measure yours too!",
      ja: "私のグリット指数：成長型📈 粘り強さと情熱のバランスが取れ始めたって…難しい区間を耐えた経験ありは認める → あなたも測ってみて",
      'zh-CN': "我的坚毅指数：成长型📈 毅力和热情开始平衡了…承认我挺过了一些困难 → 你也来测测",
      'zh-TW': "我的堅毅指數：成長型📈 毅力和熱情開始平衡了…承認我挺過了一些困難 → 你也來測測",
      vi: "Chỉ số Grit: Tăng trưởng 📈 Bền bỉ và đam mê bắt đầu cân bằng... thừa nhận đã vượt qua khó khăn → Bạn cũng đo thử đi!",
      id: "Indeks Grit-ku: Pertumbuhan 📈 Ketekunan dan semangat mulai seimbang... memang sudah melewati masa sulit → Kamu juga ukur dong!",
    }),
  },
  {
    type: "Type4",
    emoji: "💪",
    title: localeMap({
      ko: "장기 목표에 강한 체력이 생긴, 그릿 강화형 💪",
      en: "Built for Long-Term Goals — Grit Strengthening 💪",
      ja: "長期目標に強い体力がついた、グリット強化型 💪",
      'zh-CN': "长期目标体力增强的强化型 💪",
      'zh-TW': "長期目標體力增強的強化型 💪",
      vi: "Có sức bền cho mục tiêu dài hạn, kiểu tăng cường Grit 💪",
      id: "Kuat untuk Tujuan Jangka Panjang — Grit Penguatan 💪",
    }),
    gritIndex: localeMap({
      ko: "56~75% / 열정·끈기 모두 평균 이상\n💪 강화형",
      en: "56–75% / Both passion & perseverance above average\n💪 Strengthening",
      ja: "56〜75% / 情熱・粘り強さ共に平均以上\n💪 強化型",
      'zh-CN': "56~75% / 热情·毅力都高于平均\n💪 强化型",
      'zh-TW': "56~75% / 熱情·毅力都高於平均\n💪 強化型",
      vi: "56–75% / Đam mê·bền bỉ đều trên trung bình\n💪 Kiểu tăng cường",
      id: "56–75% / Semangat & ketekunan di atas rata-rata\n💪 Tipe Penguatan",
    }),
    quote: localeMap({
      ko: "당신은 어지간한 어려움으로는 멈추지 않는 사람입니다. 장기 목표를 향해 가는 체력이 형성되어 있습니다.",
      en: "You're someone who doesn't stop at ordinary difficulties. You've built the stamina for long-term goals.",
      ja: "あなたはたいていの困難では止まらない人です。長期目標に向かう体力が形成されています。",
      'zh-CN': "你是那种一般困难拦不住的人。已经具备了追求长期目标的体力。",
      'zh-TW': "你是那種一般困難攔不住的人。已經具備了追求長期目標的體力。",
      vi: "Bạn là người không dừng lại trước khó khăn bình thường. Đã có sức bền cho mục tiêu dài hạn.",
      id: "Kamu orang yang tidak berhenti karena kesulitan biasa. Sudah punya stamina untuk tujuan jangka panjang.",
    }),
    description: localeMap({
      ko: "목표에 대한 방향이 비교적 일관되어 있고 포기 충동이 와도 버티는 패턴이 있습니다. 어려운 구간에서 원인을 분석하고 수정하는 능력이 있으며 외부 피드백이 없어도 어느 정도 혼자 유지할 수 있습니다. 이 수준의 그릿이면 대부분의 장기 목표에서 평균보다 훨씬 높은 완주 가능성을 가집니다.",
      en: "Your direction is relatively consistent, and you have a pattern of pushing through even when the urge to quit hits. You can analyze and fix problems in tough spots, and maintain progress on your own without external feedback. At this grit level, your completion rate for long-term goals is far above average.",
      ja: "目標に対する方向が比較的一貫しており、諦めの衝動が来ても耐えるパターンがある。難しい区間で原因を分析・修正する能力があり、外部フィードバックなしでもある程度維持できる。このレベルのグリットなら長期目標の完走率は平均よりずっと高い。",
      'zh-CN': "你的方向比较一致，即使想放弃也有坚持的模式。能在困难中分析原因并修正，没有外部反馈也能独自维持。这个水平的坚毅力意味着长期目标的完成率远高于平均。",
      'zh-TW': "你的方向比較一致，即使想放棄也有堅持的模式。能在困難中分析原因並修正，沒有外部反饋也能獨自維持。這個水平的堅毅力意味著長期目標的完成率遠高於平均。",
      vi: "Hướng đi của bạn khá nhất quán, và bạn có mô hình kiên trì ngay cả khi muốn bỏ cuộc. Có khả năng phân tích và sửa chữa trong khó khăn, duy trì tiến độ mà không cần phản hồi bên ngoài. Với mức grit này, tỷ lệ hoàn thành mục tiêu dài hạn cao hơn trung bình rất nhiều.",
      id: "Arahmu relatif konsisten, dan kamu punya pola bertahan meski ingin menyerah. Bisa menganalisis dan memperbaiki masalah saat sulit, serta menjaga progres tanpa feedback eksternal. Dengan level grit ini, tingkat penyelesaian tujuan jangka panjangmu jauh di atas rata-rata.",
    }),
    perseveranceDiagnosis: localeMap({
      ko: "실패 후 회복 속도가 빠르고 장기 프로젝트에서 강함",
      en: "Fast recovery after failure and strong in long-term projects",
      ja: "失敗後の回復が速く長期プロジェクトに強い",
      'zh-CN': "失败后恢复快，长期项目很强",
      'zh-TW': "失敗後恢復快，長期專案很強",
      vi: "Phục hồi nhanh sau thất bại và mạnh trong dự án dài hạn",
      id: "Cepat pulih setelah gagal dan kuat di proyek jangka panjang",
    }),
    passionDiagnosis: localeMap({
      ko: "하나의 방향으로 수년 이상 집중해온 경험이 있음",
      en: "Has experience focusing in one direction for years",
      ja: "一つの方向に数年以上集中してきた経験がある",
      'zh-CN': "有朝一个方向集中数年以上的经验",
      'zh-TW': "有朝一個方向集中數年以上的經驗",
      vi: "Có kinh nghiệm tập trung một hướng nhiều năm",
      id: "Punya pengalaman fokus ke satu arah selama bertahun-tahun",
    }),
    actionItems: localeMap({
      ko: "지금 목표의 의미를 더 크게 연결하기. 나를 위한 것에서 타인·사회·역사와 연결되면 그릿이 더 강해짐\n더 어려운 목표에 도전하기. 현재 수준에서 체력이 남는다면 더 큰 도전이 그릿을 계속 키움\n지금 이 그릿을 유지하게 해주는 사람·환경·루틴을 의식적으로 관리하기",
      en: "Connect your goal to something bigger—linking personal goals to others, society, or history strengthens grit.\nChallenge harder goals. If you have stamina left at this level, bigger challenges keep growing grit.\nConsciously manage the people, environment, and routines that sustain your grit.",
      ja: "今の目標の意味をもっと大きく結びつける。自分のためから他者・社会・歴史とつながるとグリットが強くなる\nもっと難しい目標に挑戦する。今のレベルで体力が余るならより大きな挑戦がグリットを育て続ける\n今のグリットを維持してくれる人・環境・ルーティンを意識的に管理する",
      'zh-CN': "把目标跟更大的意义连接。从自己延伸到他人·社会·历史会让坚毅力更强。\n挑战更难的目标。现有水平还有余力的话，更大挑战能继续培养坚毅力。\n有意识地管理维持坚毅力的人·环境·routine。",
      'zh-TW': "把目標跟更大的意義連接。從自己延伸到他人·社會·歷史會讓堅毅力更強。\n挑戰更難的目標。現有水平還有餘力的話，更大挑戰能繼續培養堅毅力。\n有意識地管理維持堅毅力的人·環境·routine。",
      vi: "Kết nối mục tiêu với ý nghĩa lớn hơn—liên kết mục tiêu cá nhân với người khác, xã hội, lịch sử sẽ tăng grit.\nThử thách mục tiêu khó hơn. Nếu còn sức bền ở mức này, thử thách lớn hơn tiếp tục nuôi grit.\nQuản lý có ý thức người, môi trường, thói quen duy trì grit.",
      id: "Hubungkan tujuanmu ke sesuatu yang lebih besar—menghubungkan ke orang lain, masyarakat, sejarah memperkuat grit.\nTantang tujuan yang lebih sulit. Jika masih ada stamina di level ini, tantangan besar terus menumbuhkan grit.\nKelola secara sadar orang, lingkungan, dan rutinitas yang menjaga grit-mu.",
    }),
    duckworthQuote: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    commonTraits: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    caution: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    certificationPhrase: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    oneLiner: localeMap({
      ko: "\"당신의 그릿은 이미 많은 사람보다 강합니다. 이제 이것을 가장 의미 있는 곳에 쏟는 것이 남은 과제입니다\"",
      en: "\"Your grit is already stronger than most. The remaining task is to pour it into the most meaningful place.\"",
      ja: "\"あなたのグリットはすでに多くの人より強いです。今後はそれを最も意味ある場所に注ぐことが課題です\"",
      'zh-CN': "\"你的坚毅力已经比大多数人强了。接下来的课题是把它倾注在最有意义的地方。\"",
      'zh-TW': "\"你的堅毅力已經比大多數人強了。接下來的課題是把它傾注在最有意義的地方。\"",
      vi: "\"Grit của bạn đã mạnh hơn đa số. Nhiệm vụ còn lại là đổ nó vào nơi có ý nghĩa nhất.\"",
      id: "\"Grit-mu sudah lebih kuat dari kebanyakan orang. Tugas selanjutnya adalah mencurahkannya ke tempat paling bermakna.\"",
    }),
    shareLine: localeMap({
      ko: "내 그릿 지수: 강화형 💪 어지간한 어려움으로 안 멈춘다는 거... 완주 체력 형성됐다는 거 맞음 → 나 그릿 지수 이래 자기계발 공유해봐",
      en: "My Grit Index: Strengthening 💪 Ordinary difficulties don't stop me... I've built the stamina to finish → Share your self-improvement score!",
      ja: "私のグリット指数：強化型💪 たいていの困難では止まらない…完走の体力ができた → あなたも測ってみて",
      'zh-CN': "我的坚毅指数：强化型💪 一般困难拦不住我…完成的体力已经有了 → 来测测你的",
      'zh-TW': "我的堅毅指數：強化型💪 一般困難攔不住我…完成的體力已經有了 → 來測測你的",
      vi: "Chỉ số Grit: Tăng cường 💪 Khó khăn thông thường không ngăn được tôi... đã có sức bền hoàn thành → Chia sẻ điểm của bạn!",
      id: "Indeks Grit-ku: Penguatan 💪 Kesulitan biasa tak menghentikanku... stamina penyelesaian sudah terbentuk → Bagikan skormu!",
    }),
  },
  {
    type: "Type5",
    emoji: "🏔️",
    title: localeMap({
      ko: "어지간한 걸로는 안 멈추는, 그릿 고수형 🏔️",
      en: "Unstoppable Under Pressure — Grit Pro 🏔️",
      ja: "簡単には止まらない、グリット上級者型 🏔️",
      'zh-CN': "轻易不会停下的高手型 🏔️",
      'zh-TW': "輕易不會停下的高手型 🏔️",
      vi: "Không dễ dừng lại, kiểu cao thủ Grit 🏔️",
      id: "Tak Mudah Berhenti — Grit Profesional 🏔️",
    }),
    gritIndex: localeMap({
      ko: "78~92% / 열정·끈기 모두 상위 수준\n🏔️ 고수형",
      en: "78–92% / Both passion & perseverance at top level\n🏔️ Pro",
      ja: "78〜92% / 情熱・粘り強さ共に上位レベル\n🏔️ 上級者型",
      'zh-CN': "78~92% / 热情·毅力都处于顶尖水平\n🏔️ 高手型",
      'zh-TW': "78~92% / 熱情·毅力都處於頂尖水平\n🏔️ 高手型",
      vi: "78–92% / Đam mê·bền bỉ đều ở mức cao\n🏔️ Kiểu cao thủ",
      id: "78–92% / Semangat & ketekunan di level atas\n🏔️ Tipe Profesional",
    }),
    quote: localeMap({
      ko: "당신은 산을 오르는 사람입니다. 어떤 날씨에도 발걸음을 멈추지 않는 사람입니다.",
      en: "You are a mountain climber. Someone who never stops walking, no matter the weather.",
      ja: "あなたは山を登る人です。どんな天気でも歩みを止めない人です。",
      'zh-CN': "你是爬山的人。无论什么天气都不会停下脚步。",
      'zh-TW': "你是爬山的人。無論什麼天氣都不會停下腳步。",
      vi: "Bạn là người leo núi. Người không bao giờ dừng bước dù thời tiết thế nào.",
      id: "Kamu adalah pendaki gunung. Seseorang yang tak pernah berhenti melangkah, apapun cuacanya.",
    }),
    description: localeMap({
      ko: "포기 충동이 와도 금방 지나가고 반복적이고 지루한 과정도 루틴으로 소화하며 장기 목표를 향해 수년 이상 일관된 방향으로 나아온 경험이 있습니다. 외부 인정 없이도 자기 기준으로 지속할 수 있고 실패가 오히려 방법을 찾는 에너지가 되는 타입입니다.",
      en: "The urge to quit passes quickly, boring repetition becomes routine, and you've moved consistently toward long-term goals for years. You can sustain yourself on your own standards without external recognition, and failure becomes fuel for finding new methods.",
      ja: "諦めの衝動もすぐ過ぎ、退屈な反復もルーティンとしてこなし、長期目標に向けて数年以上一貫した方向で進んできた経験がある。外部の認知なしでも自分の基準で続けられ、失敗がむしろ方法を探すエネルギーになるタイプ。",
      'zh-CN': "放弃的冲动很快就过去，重复枯燥的过程也能当routine消化，有朝长期目标持续数年的经验。不需要外部认可也能靠自己的标准坚持，失败反而成为寻找方法的动力。",
      'zh-TW': "放棄的衝動很快就過去，重複枯燥的過程也能當routine消化，有朝長期目標持續數年的經驗。不需要外部認可也能靠自己的標準堅持，失敗反而成為尋找方法的動力。",
      vi: "Cảm giác muốn bỏ cuộc qua nhanh, lặp lại nhàm chán cũng thành routine, và bạn đã tiến đều đặn hướng tới mục tiêu dài hạn nhiều năm. Có thể duy trì theo tiêu chuẩn riêng mà không cần ghi nhận bên ngoài, thất bại trở thành năng lượng tìm cách mới.",
      id: "Dorongan menyerah cepat berlalu, pengulangan membosankan jadi rutinitas, dan kamu sudah bergerak konsisten menuju tujuan jangka panjang bertahun-tahun. Bisa bertahan dengan standar sendiri tanpa pengakuan luar, dan kegagalan justru jadi energi mencari cara baru.",
    }),
    perseveranceDiagnosis: localeMap({
      ko: "장기 지속력이 높고 슬럼프 회복 능력이 탁월함",
      en: "High long-term persistence and excellent slump recovery",
      ja: "長期持続力が高くスランプからの回復力が優れている",
      'zh-CN': "长期坚持力强，低谷恢复能力出色",
      'zh-TW': "長期堅持力強，低谷恢復能力出色",
      vi: "Sức bền dài hạn cao và khả năng phục hồi khỏi khủng hoảng xuất sắc",
      id: "Ketekunan jangka panjang tinggi dan pemulihan dari slump sangat baik",
    }),
    passionDiagnosis: localeMap({
      ko: "하나의 방향에 오랫동안 일관된 관심을 유지해왔음",
      en: "Maintained consistent interest in one direction for a long time",
      ja: "一つの方向に長い間一貫した関心を維持してきた",
      'zh-CN': "长期保持对同一方向的持续兴趣",
      'zh-TW': "長期保持對同一方向的持續興趣",
      vi: "Duy trì sự quan tâm nhất quán theo một hướng trong thời gian dài",
      id: "Mempertahankan minat konsisten di satu arah untuk waktu lama",
    }),
    actionItems: localeMap({
      ko: "지금의 방향이 진짜 나에게 의미 있는 것인지 주기적으로 점검하기. 높은 그릿이 잘못된 방향에 쓰이지 않도록\n같은 그릿 수준의 사람들과 연결하기. 환경이 그릿을 더 키움\n다음 레벨의 목표를 미리 설정하기. 이 수준의 그릿은 더 큰 도전에서 진가를 발휘함",
      en: "Periodically check if your current direction truly matters to you. High grit shouldn't go toward the wrong path.\nConnect with people at a similar grit level. Environment grows grit further.\nSet next-level goals in advance. This level of grit shines in bigger challenges.",
      ja: "今の方向が本当に自分に意味あるか定期的に確認する。高いグリットが間違った方向に使われないように\n同じグリットレベルの人とつながる。環境がグリットをさらに育てる\n次のレベルの目標を先に設定する。このレベルのグリットはより大きな挑戦で真価を発揮する",
      'zh-CN': "定期检查现在的方向是否真的对你有意义。别让高坚毅力用错了方向。\n跟同等坚毅力水平的人交流。环境能进一步培养坚毅力。\n提前设定下一级目标。这个水平的坚毅力在更大挑战中才能充分发挥。",
      'zh-TW': "定期檢查現在的方向是否真的對你有意義。別讓高堅毅力用錯了方向。\n跟同等堅毅力水平的人交流。環境能進一步培養堅毅力。\n提前設定下一級目標。這個水平的堅毅力在更大挑戰中才能充分發揮。",
      vi: "Kiểm tra định kỳ hướng đi hiện tại có thực sự ý nghĩa với bạn không. Grit cao không nên dùng sai hướng.\nKết nối với người cùng mức grit. Môi trường nuôi dưỡng grit thêm.\nĐặt mục tiêu cấp tiếp theo từ trước. Mức grit này tỏa sáng trong thử thách lớn hơn.",
      id: "Periksa secara berkala apakah arahmu benar-benar bermakna. Grit tinggi jangan dipakai ke arah yang salah.\nTerhubung dengan orang-orang selevel grit. Lingkungan menumbuhkan grit lebih lanjut.\nTetapkan tujuan level berikutnya lebih awal. Level grit ini bersinar di tantangan lebih besar.",
    }),
    duckworthQuote: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    commonTraits: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    caution: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    certificationPhrase: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    oneLiner: localeMap({
      ko: "\"당신이 선택한 길에서 결국 남아있는 사람이 당신일 가능성이 매우 높습니다\"",
      en: "\"On the path you've chosen, the one still standing at the end is very likely you.\"",
      ja: "\"あなたが選んだ道で最後に残っている人はあなたである可能性が非常に高いです\"",
      'zh-CN': "\"在你选择的路上，最终留下来的人很可能就是你。\"",
      'zh-TW': "\"在你選擇的路上，最終留下來的人很可能就是你。\"",
      vi: "\"Trên con đường bạn chọn, người cuối cùng còn ở lại rất có thể là bạn.\"",
      id: "\"Di jalan yang kamu pilih, orang yang masih berdiri di akhir kemungkinan besar adalah kamu.\"",
    }),
    shareLine: localeMap({
      ko: "내 그릿 지수: 고수형 🏔️ 상위 수준... 포기 충동이 금방 지나간다는 거 맞음 ㅋㅋ → 나 그릿 지수 이래 너는 몇 점이야?",
      en: "My Grit Index: Pro 🏔️ Top level... the urge to quit passes fast, true story 😄 → What's your score?",
      ja: "私のグリット指数：上級者型🏔️ 上位レベル…諦めの衝動がすぐ過ぎるのは本当 → あなたは何点？",
      'zh-CN': "我的坚毅指数：高手型🏔️ 上位水平…想放弃的念头确实很快就过去了 → 你几分？",
      'zh-TW': "我的堅毅指數：高手型🏔️ 上位水平…想放棄的念頭確實很快就過去了 → 你幾分？",
      vi: "Chỉ số Grit: Cao thủ 🏔️ Mức cao... cảm giác muốn bỏ cuộc qua nhanh thật 😄 → Bạn mấy điểm?",
      id: "Indeks Grit-ku: Profesional 🏔️ Level atas... dorongan menyerah memang cepat berlalu 😄 → Berapa skormu?",
    }),
  },
  {
    type: "Type6",
    emoji: "👑",
    title: localeMap({
      ko: "열정과 끈기가 모두 최정상인, 그릿 마스터형 👑",
      en: "Peak Passion & Perseverance — Grit Master 👑",
      ja: "情熱と粘り強さが共に最頂点の、グリットマスター型 👑",
      'zh-CN': "热情和毅力都在巅峰的大师型 👑",
      'zh-TW': "熱情和毅力都在巔峰的大師型 👑",
      vi: "Đam mê và bền bỉ đều đỉnh cao, kiểu Bậc thầy Grit 👑",
      id: "Semangat & Ketekunan di Puncak — Grit Master 👑",
    }),
    gritIndex: localeMap({
      ko: "95~100% / 열정·끈기 모두 최상위\n👑 마스터형",
      en: "95–100% / Both passion & perseverance at the very top\n👑 Master",
      ja: "95〜100% / 情熱・粘り強さ共に最上位\n👑 マスター型",
      'zh-CN': "95~100% / 热情·毅力都在最顶端\n👑 大师型",
      'zh-TW': "95~100% / 熱情·毅力都在最頂端\n👑 大師型",
      vi: "95–100% / Đam mê·bền bỉ đều ở đỉnh cao nhất\n👑 Kiểu bậc thầy",
      id: "95–100% / Semangat & ketekunan di puncak tertinggi\n👑 Tipe Master",
    }),
    quote: localeMap({
      ko: "당신의 그릿은 재능을 이기는 수준에 도달해 있습니다.",
      en: "Your grit has reached a level that defeats talent.",
      ja: "あなたのグリットは才能を凌駕するレベルに達しています。",
      'zh-CN': "你的坚毅力已经达到了战胜天赋的水平。",
      'zh-TW': "你的堅毅力已經達到了戰勝天賦的水平。",
      vi: "Grit của bạn đã đạt đến mức đánh bại tài năng.",
      id: "Grit-mu sudah mencapai level yang mengalahkan bakat.",
    }),
    description: localeMap({
      ko: "10년 이상 같은 방향을 바라보거나 그에 준하는 일관성이 있고 외부 보상 없이도 혼자 수년 이상 지속해온 경험이 있으며 실패가 포기의 이유가 아니라 방법을 찾는 이유가 되는 타입입니다. 앤젤라 더크워스가 연구에서 발견한 상위 그릿 보유자의 패턴과 일치합니다.",
      en: "You've looked in the same direction for 10+ years (or equivalent consistency), sustained effort for years without external rewards, and treat failure not as a reason to quit but as a reason to find new methods. You match the pattern Duckworth found in top-grit individuals.",
      ja: "10年以上同じ方向を見続けるか同等の一貫性があり、外部報酬なしでも数年以上続けてきた経験があり、失敗が諦める理由ではなく方法を探す理由になるタイプ。ダックワースの研究で発見された上位グリット保有者のパターンと一致します。",
      'zh-CN': "你看同一个方向10年以上（或等同的一致性），无外部回报也能独自坚持数年，失败不是放弃的理由而是寻找方法的理由。你符合Duckworth在顶级坚毅力者中发现的模式。",
      'zh-TW': "你看同一個方向10年以上（或等同的一致性），無外部回報也能獨自堅持數年，失敗不是放棄的理由而是尋找方法的理由。你符合Duckworth在頂級堅毅力者中發現的模式。",
      vi: "Bạn đã nhìn cùng một hướng 10+ năm (hoặc sự nhất quán tương đương), duy trì nỗ lực nhiều năm không có phần thưởng bên ngoài, và xem thất bại không phải lý do bỏ cuộc mà là lý do tìm cách mới. Bạn khớp với mẫu Duckworth tìm thấy ở người có grit cao nhất.",
      id: "Kamu telah memandang ke arah yang sama 10+ tahun (atau konsistensi setara), mempertahankan usaha bertahun-tahun tanpa imbalan eksternal, dan menjadikan kegagalan bukan alasan berhenti tapi alasan mencari cara baru. Kamu cocok dengan pola yang Duckworth temukan pada individu dengan grit tertinggi.",
    }),
    perseveranceDiagnosis: localeMap({
      ko: "외부 동기 없이도 장기간 지속 가능. 어려울수록 집중도 증가",
      en: "Can sustain long-term without external motivation. Focus increases with difficulty",
      ja: "外的動機なしでも長期間持続可能。難しいほど集中度が増す",
      'zh-CN': "没有外在动力也能长期坚持。越难越集中",
      'zh-TW': "沒有外在動力也能長期堅持。越難越集中",
      vi: "Có thể duy trì dài hạn không cần động lực bên ngoài. Càng khó càng tập trung",
      id: "Bisa bertahan jangka panjang tanpa motivasi eksternal. Semakin sulit semakin fokus",
    }),
    passionDiagnosis: localeMap({
      ko: "하나의 방향에 삶의 목적 수준으로 연결된 관심이 있음",
      en: "Interest connected to one direction at life-purpose level",
      ja: "一つの方向に人生の目的レベルでつながった関心がある",
      'zh-CN': "对一个方向的兴趣已上升到人生目标的层面",
      'zh-TW': "對一個方向的興趣已上升到人生目標的層面",
      vi: "Sở thích kết nối với một hướng ở mức mục đích sống",
      id: "Minat terhubung ke satu arah di level tujuan hidup",
    }),
    actionItems: localeMap({
      ko: "지금의 방향이 진짜 나에게 의미 있는 것인지 주기적으로 점검하기. 높은 그릿이 잘못된 방향에 쓰이지 않도록\n같은 그릿 수준의 사람들과 연결하기. 환경이 그릿을 더 키움\n다음 레벨의 목표를 미리 설정하기. 이 수준의 그릿은 더 큰 도전에서 진가를 발휘함",
      en: "Periodically check if your current direction truly matters to you. High grit shouldn't go toward the wrong path.\nConnect with people at a similar grit level. Environment grows grit further.\nSet next-level goals in advance. This level of grit shines in bigger challenges.",
      ja: "今の方向が本当に自分に意味あるか定期的に確認する。高いグリットが間違った方向に使われないように\n同じグリットレベルの人とつながる。環境がグリットをさらに育てる\n次のレベルの目標を先に設定する。このレベルのグリットはより大きな挑戦で真価を発揮する",
      'zh-CN': "定期检查现在的方向是否真的对你有意义。别让高坚毅力用错了方向。\n跟同等坚毅力水平的人交流。环境能进一步培养坚毅力。\n提前设定下一级目标。这个水平的坚毅力在更大挑战中才能充分发挥。",
      'zh-TW': "定期檢查現在的方向是否真的對你有意義。別讓高堅毅力用錯了方向。\n跟同等堅毅力水平的人交流。環境能進一步培養堅毅力。\n提前設定下一級目標。這個水平的堅毅力在更大挑戰中才能充分發揮。",
      vi: "Kiểm tra định kỳ hướng đi hiện tại có thực sự ý nghĩa với bạn không. Grit cao không nên dùng sai hướng.\nKết nối với người cùng mức grit. Môi trường nuôi dưỡng grit thêm.\nĐặt mục tiêu cấp tiếp theo từ trước. Mức grit này tỏa sáng trong thử thách lớn hơn.",
      id: "Periksa secara berkala apakah arahmu benar-benar bermakna. Grit tinggi jangan dipakai ke arah yang salah.\nTerhubung dengan orang-orang selevel grit. Lingkungan menumbuhkan grit lebih lanjut.\nTetapkan tujuan level berikutnya lebih awal. Level grit ini bersinar di tantangan lebih besar.",
    }),
    duckworthQuote: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    commonTraits: localeMap({
      ko: "자신의 관심사와 더 큰 의미를 연결하고 있음. 남들이 포기하는 구간에서 오히려 집중력이 올라가는 패턴이 있음",
      en: "Connects personal interests to greater meaning. Focus actually increases in zones where others give up.",
      ja: "自分の関心事とより大きな意味を結びつけている。他の人が諦める区間でむしろ集中力が上がるパターンがある",
      'zh-CN': "把个人兴趣与更大意义联系在一起。在别人放弃的区间反而集中力上升。",
      'zh-TW': "把個人興趣與更大意義聯繫在一起。在別人放棄的區間反而集中力上升。",
      vi: "Kết nối sở thích cá nhân với ý nghĩa lớn hơn. Tập trung thực sự tăng ở vùng người khác bỏ cuộc.",
      id: "Menghubungkan minat pribadi dengan makna lebih besar. Fokus justru meningkat di zona di mana orang lain menyerah.",
    }),
    caution: localeMap({
      ko: "높은 그릿은 강력한 도구이지만 방향이 잘못됐을 때도 강하게 지속되는 특성이 있음. 주기적으로 방향이 맞는지 점검하는 것이 중요",
      en: "High grit is a powerful tool, but it also persists strongly even when the direction is wrong. Periodic direction checks are crucial.",
      ja: "高いグリットは強力な道具だが、方向が間違っている時も強く持続する特性がある。定期的に方向が合っているか点検することが重要",
      'zh-CN': "高坚毅力是强大工具，但方向错了也会顽强坚持。定期检查方向是否正确很重要。",
      'zh-TW': "高堅毅力是強大工具，但方向錯了也會頑強堅持。定期檢查方向是否正確很重要。",
      vi: "Grit cao là công cụ mạnh nhưng cũng kiên trì mạnh mẽ ngay cả khi sai hướng. Kiểm tra định kỳ hướng đi rất quan trọng.",
      id: "Grit tinggi adalah alat yang kuat, tapi juga bertahan kuat bahkan saat arahnya salah. Pengecekan arah secara berkala sangat penting.",
    }),
    certificationPhrase: localeMap({
      ko: "\"그릿 마스터 달성 👑 열정+끈기 최상위 5%\"",
      en: "\"Grit Master Achieved 👑 Top 5% in Passion + Perseverance\"",
      ja: "\"グリットマスター達成 👑 情熱＋粘り強さ上位5%\"",
      'zh-CN': "\"坚毅力大师达成 👑 热情+毅力最顶端5%\"",
      'zh-TW': "\"堅毅力大師達成 👑 熱情+毅力最頂端5%\"",
      vi: "\"Đạt Bậc thầy Grit 👑 Top 5% Đam mê + Bền bỉ\"",
      id: "\"Grit Master Tercapai 👑 Top 5% Semangat + Ketekunan\"",
    }),
    oneLiner: localeMap({
      ko: "\"당신이 선택한 것에 이 그릿을 쏟는다면 재능이 어지간히 뛰어난 사람도 따라오기 어렵습니다\"",
      en: "\"If you pour this grit into what you've chosen, even exceptionally talented people will struggle to keep up.\"",
      ja: "\"あなたが選んだものにこのグリットを注げば、才能がかなり優れた人でも追いつくのは難しいでしょう\"",
      'zh-CN': "\"如果你把这份坚毅力倾注到所选之事，即使才华横溢的人也难以追上。\"",
      'zh-TW': "\"如果你把這份堅毅力傾注到所選之事，即使才華橫溢的人也難以追上。\"",
      vi: "\"Nếu bạn đổ grit này vào thứ đã chọn, người tài năng xuất chúng cũng khó theo kịp.\"",
      id: "\"Jika kamu mencurahkan grit ini ke pilihanmu, bahkan orang berbakat luar biasa pun akan sulit mengikuti.\"",
    }),
    shareLine: localeMap({
      ko: "내 그릿 지수: 마스터형 👑 열정+끈기 최상위... 재능을 이기는 수준이래 ㅋㅋ → 나 그릿 지수 이래 앤젤라 더크워스 책 추천함",
      en: "My Grit Index: Master 👑 Top passion + perseverance... beats talent apparently 😄 → I recommend Angela Duckworth's book!",
      ja: "私のグリット指数：マスター型👑 情熱＋粘り強さ最上位…才能を凌駕するレベルらしい → ダックワースの本おすすめ",
      'zh-CN': "我的坚毅指数：大师型👑 热情+毅力最顶端…据说能战胜天赋 → 推荐Duckworth的书",
      'zh-TW': "我的堅毅指數：大師型👑 熱情+毅力最頂端…據說能戰勝天賦 → 推薦Duckworth的書",
      vi: "Chỉ số Grit: Bậc thầy 👑 Đam mê+bền bỉ đỉnh cao... nói là đánh bại tài năng 😄 → Gợi ý sách Angela Duckworth!",
      id: "Indeks Grit-ku: Master 👑 Semangat+ketekunan puncak... katanya mengalahkan bakat 😄 → Rekomendasikan buku Angela Duckworth!",
    }),
  },
];
