/** 무지출 챌린지 성공 가능성은? — 12문항 4지선다, 총점 0~36 → 6유형 */

function T(t: {
  ko: string;
  en: string;
  ja: string;
  zhCN: string;
  zhTW: string;
  vi: string;
  id: string;
}): Record<string, string> {
  return {
    ko: t.ko,
    en: t.en,
    ja: t.ja,
    'zh-CN': t.zhCN,
    'zh-TW': t.zhTW,
    vi: t.vi,
    id: t.id,
  };
}

export interface Phase3ZeroSpendingChallengeQuestion {
  id: number;
  question: Record<string, string>;
  options: { text: Record<string, string>; score: number }[];
}

export interface Phase3ZeroSpendingChallengeResult {
  type: string;
  emoji: string;
  title: Record<string, string>;
  successRateLine: Record<string, string>;
  hookLine: Record<string, string>;
  description: Record<string, string>;
  detailSectionTitle: Record<string, string>;
  detailBullets: Record<string, string>;
  prescriptionSteps: Record<string, string>;
  savingsEstimate: Record<string, string>;
  yearlyApply: Record<string, string>;
  todayTask: Record<string, string>;
  motivationLine: Record<string, string>;
  shareLine: Record<string, string>;
}

export function calculatePhase3ZeroSpendingChallengeResult(answers: number[]): string {
  const total = answers.reduce((sum, s) => sum + (s ?? 0), 0);
  if (total <= 5) return 'Type1';
  if (total <= 11) return 'Type2';
  if (total <= 19) return 'Type3';
  if (total <= 27) return 'Type4';
  if (total <= 33) return 'Type5';
  return 'Type6';
}

export const phase3ZeroSpendingChallengeQuestions: Phase3ZeroSpendingChallengeQuestion[] = [
  {
    id: 1,
    question: T({
      ko: '오늘 지갑과 페이 앱을 모두 잠근다고 선언했다. 30분 후 나는?',
      en: 'You declared your wallet and pay apps “locked for today.” 30 minutes later, you…',
      ja: '今日は財布もペイも封印と宣言した。30分後の自分は？',
      zhCN: '你宣布今天钱包和支付App都锁上。30分钟后你会？',
      zhTW: '你宣布今天錢包和支付App都鎖上。30分鐘後你會？',
      vi: 'Bạn tuyên bố khóa ví và app thanh toán cả ngày. 30 phút sau, bạn…',
      id: 'Kamu menyatakan dompet dan app pembayaran “terkunci hari ini.” 30 menit kemudian, kamu…',
    }),
    options: [
      {
        text: T({
          ko: '선언한 이상 지킨다. 다짐을 어기는 게 더 불편하다',
          en: 'I keep it—I hate breaking a promise to myself more.',
          ja: '宣言した以上は守る。自分との約束を破る方が不快だ。',
          zhCN: '既然说了就做到，违背自己的决心更难受。',
          zhTW: '既然說了就做到，違背自己的決心更難受。',
          vi: 'Đã nói là giữ—phá lời hứa với bản thân còn khó chịu hơn.',
          id: 'Kalau sudah menyatakan, aku pegang—mengingkari janji pada diri sendiri lebih tidak nyaman.',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '목적이 분명하면 버틸 수 있다. 단 이유가 명확해야 한다',
          en: 'I can hold if the “why” is clear—purpose has to be obvious.',
          ja: '目的がはっきりしていれば耐えられる。理由が明確なら。',
          zhCN: '目的清楚就能撑住，理由必须明确。',
          zhTW: '目的清楚就能撐住，理由必須明確。',
          vi: 'Nếu mục đích rõ thì nhịn được—phải có lý do rành mạch.',
          id: 'Kalau tujuannya jelas bisa bertahan—alasannya harus jelas.',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '버티긴 하는데 머릿속으로는 이미 내일 뭘 살지 계획 중이다',
          en: 'I resist, but I’m already planning what to buy tomorrow in my head.',
          ja: '耐えてはいるが、頭の中ではもう明日の買い物を計画中。',
          zhCN: '表面在忍，脑子里已经在计划明天买什么。',
          zhTW: '表面在忍，腦子裡已經在計畫明天買什麼。',
          vi: 'Cố nhịn nhưng trong đầu đã lên kế hoạch mai mua gì.',
          id: 'Menahan, tapi di kepala sudah merencanakan besok mau beli apa.',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '솔직히 30분 안에 "오늘만 예외"가 나올 것 같다',
          en: 'Honestly, “just today” exception would pop up within 30 minutes.',
          ja: '正直、30分以内に「今日だけ例外」が出そう。',
          zhCN: '老实说30分钟内就会出现“今天就例外”。',
          zhTW: '老實說30分鐘內就會出現「今天就例外」。',
          vi: 'Thật lòng thì trong 30 phút đã có “hôm nay ngoại lệ nhé”.',
          id: 'Jujur, dalam 30 menit sudah muncul “hari ini pengecualian”.',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 2,
    question: T({
      ko: '무지출 챌린지 날 아침, 커피가 없다. 나는?',
      en: 'Zero-spend challenge morning—no coffee at home. You…',
      ja: '無支出チャレンジの朝、コーヒーがない。あなたは？',
      zhCN: '零消费挑战日的早上，没有咖啡。你会？',
      zhTW: '零消費挑戰日的早上，沒有咖啡。你會？',
      vi: 'Sáng thử thách chi 0 đồng, không có cà phê. Bạn…',
      id: 'Pagi tantangan belanja nol, tidak ada kopi. Kamu…',
    }),
    options: [
      {
        text: T({
          ko: '집에 있는 재료로 해결한다. 없으면 그냥 안 마신다',
          en: 'I make do with what’s at home—or skip coffee.',
          ja: '家にあるもので代用。なければ飲まない。',
          zhCN: '用家里有的凑合，没有就不喝。',
          zhTW: '用家裡有的湊合，沒有就不喝。',
          vi: 'Dùng gì có ở nhà—không thì không uống.',
          id: 'Pakai yang ada di rumah—kalau tidak ada, tidak minum.',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '회사나 학교 탕비실·정수기 등 무료 대안을 찾는다',
          en: 'I hunt free coffee at the office/school pantry or water cooler hacks.',
          ja: '会社や学校の給湯室・ウォーターサーバーなど無料ルートを探す。',
          zhCN: '去公司或学校茶水间、饮水机等找免费替代。',
          zhTW: '去公司或學校茶水間、飲水機等找免費替代。',
          vi: 'Tìm cà phê miễn phí ở pantry công ty/trường hoặc nước lọc.',
          id: 'Cari alternatif gratis di pantry kantor/sekolah atau dispenser.',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '"커피는 생산성 투자잖아" 하고 합리화하며 산다',
          en: 'I rationalize: “Coffee is a productivity investment”—and buy it.',
          ja: '「コーヒーは生産性投資」と言い訳して買う。',
          zhCN: '合理化：“咖啡是生产力投资”然后买。',
          zhTW: '合理化：「咖啡是生產力投資」然後買。',
          vi: 'Biện minh “cà phê là đầu tư năng suất”—rồi mua.',
          id: 'Merasionalkan “kopi investasi produktivitas”—lalu beli.',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '커피 없이는 하루 시작이 안 된다. 이것만큼은 예외다',
          en: 'I can’t start the day without coffee—this one’s my exception.',
          ja: 'コーヒーなしでは一日が始まらない。これだけは例外。',
          zhCN: '没有咖啡一天无法开始，这项必须例外。',
          zhTW: '沒有咖啡一天無法開始，這項必須例外。',
          vi: 'Không cà phê là không bắt đầu được ngày—ngoại lệ này.',
          id: 'Tanpa kopi hari tidak mulai—ini pengecualian.',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 3,
    question: T({
      ko: '점심시간, 동료나 친구가 "오늘 같이 밥 먹으러 나가자"고 한다. 나는?',
      en: 'At lunch, a coworker/friend says, “Let’s go eat out together.” You…',
      ja: '昼休み、同僚や友人が「一緒に外食しよう」と誘う。あなたは？',
      zhCN: '午休时同事或朋友说“一起出去吃饭”。你会？',
      zhTW: '午休時同事或朋友說「一起出去吃飯」。你會？',
      vi: 'Giờ trưa, đồng nghiệp/bạn rủ “ra ngoài ăn cùng nhé”. Bạn…',
      id: 'Saat makan siang, rekan/teman ajak “makan di luar bareng”. Kamu…',
    }),
    options: [
      {
        text: T({
          ko: '"나 오늘 도시락·집밥이야" 하고 자연스럽게 거절한다',
          en: 'I naturally say I brought lunch / eating at home.',
          ja: '「今日は弁当・家飯」と自然に断る。',
          zhCN: '自然地说今天带便当/在家吃。',
          zhTW: '自然地說今天帶便當/在家吃。',
          vi: 'Tự nhiên nói hôm nay mang cơm/ăn ở nhà.',
          id: 'Dengan natural bilang bawa bekal/makan di rumah.',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '"무지출 챌린지 중이라" 솔직하게 말하고 대신 산책을 제안한다',
          en: 'I honestly say I’m on a zero-spend challenge and suggest a walk instead.',
          ja: '「無支出チャレンジ中」と正直に言い、代わりに散歩を提案。',
          zhCN: '坦白说在进行零消费挑战，改约散步。',
          zhTW: '坦白說在進行零消費挑戰，改約散步。',
          vi: 'Thật thà nói đang thử thách chi 0 đồng, đề xuất đi dạo.',
          id: 'Jujur bilang sedang tantangan belanja nol, ajak jalan-jalan.',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '같이 나가되 본인은 사먹지 않고 동행만 한다. 근데 빵 하나는 살 것 같다',
          en: 'I go along but don’t buy—though I’d probably grab bread.',
          ja: '一緒に行くが自分は買わず同行だけ。でもパン一つは買いそう。',
          zhCN: '跟着去但自己不点，只陪同；不过可能会买个面包。',
          zhTW: '跟著去但自己不點，只陪同；不過可能會買個麵包。',
          vi: 'Đi cùng nhưng không mua—nhưng có thể mua ổ bánh mì.',
          id: 'Ikut tapi tidak beli—tapi mungkin beli roti satu.',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '이건 어쩔 수 없다. 사회생활은 예외다',
          en: 'This is non-negotiable—social life is my exception.',
          ja: 'これは仕方ない。社会人としては例外。',
          zhCN: '这没办法，社交必须例外。',
          zhTW: '這沒辦法，社交必須例外。',
          vi: 'Không tránh được—đời sống xã hội là ngoại lệ.',
          id: 'Ini tak bisa dihindari—kehidupan sosial pengecualian.',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 4,
    question: T({
      ko: '배달 앱 알림이 "오늘만 50% 쿠폰"이라고 왔다. 나는?',
      en: 'Your delivery app pings: “50% off coupon—today only.” You…',
      ja: 'デリバリーアプリに「今日だけ50%クーポン」の通知。あなたは？',
      zhCN: '外卖App推送“仅限今天5折券”。你会？',
      zhTW: '外送App推播「限今天5折券」。你會？',
      vi: 'App giao đồ báo “coupon 50% chỉ hôm nay”. Bạn…',
      id: 'App pesan-antar notifikasi “kupon 50% hanya hari ini”. Kamu…',
    }),
    options: [
      {
        text: T({
          ko: '알림 자체를 무지출 챌린지 전날 꺼둔다',
          en: 'I turned notifications off the night before the challenge.',
          ja: 'チャレンジ前日に通知自体をオフにしてある。',
          zhCN: '挑战前夜就关掉了通知。',
          zhTW: '挑戰前夜就關掉了通知。',
          vi: 'Đã tắt thông báo từ hôm trước khi thử thách.',
          id: 'Sudah matikan notifikasi sejak malam sebelum tantangan.',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '알림을 보긴 했지만 무시한다. 쿠폰은 내일도 온다',
          en: 'I see it and ignore—coupons will come again tomorrow.',
          ja: '見たが無視。クーポンは明日も来る。',
          zhCN: '看到了但无视，券明天还会来。',
          zhTW: '看到了但無視，券明天還會來。',
          vi: 'Thấy nhưng bỏ qua—mai vẫn có coupon.',
          id: 'Lihat tapi abaikan—besok juga ada kupon.',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '"이건 진짜 아까운데..." 하며 저장해두고 내일 쓸지 고민한다',
          en: '“Such a waste…” I save it and debate using it tomorrow.',
          ja: '「もったいない…」と保存して明日使うか悩む。',
          zhCN: '“好可惜…”先存下来纠结明天用不用。',
          zhTW: '「好可惜…」先存下來糾結明天用不用。',
          vi: '“Phí quá…” lưu lại và phân vân mai dùng không.',
          id: '“Sayang…” simpan dan bimbang besok pakai atau tidak.',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '50% 쿠폰이면 사실 더 이득 아닌가. 쿠폰이 오면 못 버틴다',
          en: '50% off is basically profit—I can’t resist when coupons hit.',
          ja: '50%オフならむしろお得では？クーポンが来ると耐えられない。',
          zhCN: '五折等于赚到，券一来就扛不住。',
          zhTW: '五折等於賺到，券一來就扛不住。',
          vi: 'Giảm 50% là lời rồi—có coupon là không cưỡng được.',
          id: 'Diskon 50% kan untung—kalau ada kupon tidak tahan.',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 5,
    question: T({
      ko: '무지출 챌린지 날 편의점 앞을 지나가게 됐다. 나는?',
      en: 'On zero-spend day you pass a convenience store. You…',
      ja: '無支出チャレンジの日、コンビニの前を通る。あなたは？',
      zhCN: '零消费日路过便利店门口。你会？',
      zhTW: '零消費日路過便利商店門口。你會？',
      vi: 'Ngày chi 0 đồng, bạn đi ngang cửa hàng tiện lợi. Bạn…',
      id: 'Hari belanja nol, lewat depan minimarket. Kamu…',
    }),
    options: [
      {
        text: T({
          ko: '편의점을 그냥 지나친다. 들어가면 진다는 걸 알기 때문에',
          en: 'I walk past—I know entering means I lose.',
          ja: 'そのまま通り過ぎる。入ったら負けだと分かっているから。',
          zhCN: '直接走过，知道进去就输了。',
          zhTW: '直接走過，知道進去就輸了。',
          vi: 'Đi thẳng—biết vào là thua.',
          id: 'Lewat saja—tahu kalau masuk berarti kalah.',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '들어가더라도 구경만 하고 나온다. 의지력 테스트로 여긴다',
          en: 'If I go in, I only browse—treating it as a willpower test.',
          ja: '入っても見るだけで出る。意志力テストだと思う。',
          zhCN: '进去也只逛不买，当意志力测试。',
          zhTW: '進去也只逛不買，當意志力測試。',
          vi: 'Vào cũng chỉ xem không mua—coi như thử ý chí.',
          id: 'Kalau masuk cuma lihat—anggap tes tekad.',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '들어가면 무조건 뭔가 손에 들려 나오게 된다. 아는데 못 참는다',
          en: 'If I enter, something always ends up in my hands—I can’t help it.',
          ja: '入ると何か手に持って出てしまう。分かっているのに我慢できない。',
          zhCN: '进去就一定会拿点什么出来，知道但忍不住。',
          zhTW: '進去就一定會拿點什麼出來，知道但忍不住。',
          vi: 'Vào là chắc chắn cầm gì đó ra—biết mà không nhịn được.',
          id: 'Kalau masuk pasti bawa sesuatu keluar—tahu tapi tidak tahan.',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '편의점 앞에서 이미 결제 완료다. 이건 도전 불가 구역이다',
          en: 'I’ve basically paid before I reach the door—no-go zone for me.',
          ja: '店の前で既に決済完了みたいなもの。ここは挑戦不能エリア。',
          zhCN: '到门口前就已经算付过款了，禁区。',
          zhTW: '到門口前就已經算付過款了，禁區。',
          vi: 'Gần đến cửa là coi như đã thanh toán—vùng cấm.',
          id: 'Belum masuk sudah kayak bayar—zona mustahil.',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 6,
    question: T({
      ko: '무지출 챌린지 중 지인이 갑자기 생일이라는 걸 기억했다. 나는?',
      en: 'Mid-challenge you suddenly remember it’s someone’s birthday. You…',
      ja: 'チャレンジ中、急に知人の誕生日を思い出した。あなたは？',
      zhCN: '挑战中突然想起熟人生日。你会？',
      zhTW: '挑戰中突然想起熟人生日。你會？',
      vi: 'Giữa thử thách chợt nhớ hôm nay sinh nhật ai đó. Bạn…',
      id: 'Saat tantangan tiba-tiba ingat ulang tahun seseorang. Kamu…',
    }),
    options: [
      {
        text: T({
          ko: '카카오톡 선물하기 대신 직접 쓴 메시지로 진심을 전한다',
          en: 'I skip paid gifts—send a heartfelt handwritten-style message.',
          ja: 'ギフト送信ではなく、自分の言葉でメッセージを書いて伝える。',
          zhCN: '不用送礼功能，亲手写消息表达心意。',
          zhTW: '不用送禮功能，親手寫訊息表達心意。',
          vi: 'Không gửi quà trả phí—nhắn tin chân thành tự viết.',
          id: 'Tanpa kirim hadiah berbayar—pesan tulus yang kutulis sendiri.',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '무료로 할 수 있는 방식으로 진심 어린 생일 축하를 대신한다',
          en: 'I celebrate in a free way that still feels sincere.',
          ja: '無料でできる方法で、誠実なお祝いをする。',
          zhCN: '用免费但真诚的方式祝福。',
          zhTW: '用免費但真誠的方式祝福。',
          vi: 'Chúc mừng miễn phí nhưng chân thành.',
          id: 'Ucapan ulang tahun gratis tapi tulus.',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '소액이라도 마음을 전하고 싶다. 이건 인간 도리의 영역이다',
          en: 'I want to send something small—basic human decency wins.',
          ja: '少額でも気持ちを伝えたい。これは人情の範囲。',
          zhCN: '再少也想表示心意，这是人情。',
          zhTW: '再少也想表示心意，這是人情。',
          vi: 'Dù ít cũng muốn gửi gắm—đó là phần con người.',
          id: 'Sedikit pun ingin memberi—itu kewajaran sosial.',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '생일 선물은 관계 투자다. 챌린지보다 사람이 먼저다',
          en: 'Birthday gifts are relationship investments—people beat the challenge.',
          ja: '誕生日プレゼントは関係への投資。チャレンジより人が先。',
          zhCN: '生日礼物是关系投资，人比挑战重要。',
          zhTW: '生日禮物是關係投資，人比挑戰重要。',
          vi: 'Quà sinh nhật là đầu tư quan hệ—người quan trọng hơn thử thách.',
          id: 'Hadiah ulang tahun investasi hubungan—orang dulu baru tantangan.',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 7,
    question: T({
      ko: '하루 동안 쓰고 싶은 충동이 가장 강하게 오는 순간은?',
      en: 'When does the urge to spend hit you hardest in a day?',
      ja: '一日のうち、お金を使いたい衝動が一番強くなるのはいつ？',
      zhCN: '一天里最想花钱的冲动什么时候最强？',
      zhTW: '一天裡最想花錢的衝動什麼時候最強？',
      vi: 'Lúc nào trong ngày cơn thèm chi tiêu mạnh nhất?',
      id: 'Kapan dalam sehari dorongan belanja paling kuat?',
    }),
    options: [
      {
        text: T({
          ko: '딱히 없다. 쓰고 싶다는 충동 자체가 크지 않은 편이다',
          en: 'Not really—the urge to spend isn’t strong for me.',
          ja: '特にない。使いたい衝動自体が大きくない。',
          zhCN: '基本没有，花钱冲动不大。',
          zhTW: '基本沒有，花錢衝動不大。',
          vi: 'Không hẳn—xung chi không mạnh.',
          id: 'Tidak terlalu—dorongan belanja tidak besar.',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '스트레스 받을 때. 근데 다른 해소 방법을 찾을 수 있다',
          en: 'When I’m stressed—but I can find other outlets.',
          ja: 'ストレス時。ただ他の発散方法を見つけられる。',
          zhCN: '压力大时，但能找到别的发泄方式。',
          zhTW: '壓力大時，但能找到別的發洩方式。',
          vi: 'Khi căng thẳng—nhưng tìm được cách xả khác.',
          id: 'Saat stres—tapi bisa cari pelampiasan lain.',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '배고프거나 심심할 때. 먹는 것과 무료함이 최대 적이다',
          en: 'When I’m hungry or bored—food and boredom are my kryptonite.',
          ja: '空腹か退屈なとき。食べ物と暇さが最大の敵。',
          zhCN: '饿或无聊时，吃和无聊是最大敌人。',
          zhTW: '餓或無聊時，吃和無聊是最大敵人。',
          vi: 'Đói hoặc chán—ăn và buồn chán là kẻ thù lớn nhất.',
          id: 'Lapar atau bosan—makan dan kebosanan musuh terbesar.',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '하루 종일. 쓰고 싶다는 생각이 수시로 올라온다',
          en: 'All day long—I keep wanting to spend.',
          ja: '一日中。すぐにでも使いたくなる。',
          zhCN: '一整天，时不时想花钱。',
          zhTW: '一整天，時不時想花錢。',
          vi: 'Cả ngày—liên tục muốn tiêu.',
          id: 'Sepanjang hari—terus ingin belanja.',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 8,
    question: T({
      ko: '무지출 챌린지에 실패할 때 가장 큰 이유는?',
      en: 'What’s the biggest reason you fail a zero-spend challenge?',
      ja: '無支出チャレンジに失敗するとき、一番の理由は？',
      zhCN: '零消费挑战失败时最大的原因是？',
      zhTW: '零消費挑戰失敗時最大的原因是？',
      vi: 'Lý do lớn nhất khi thất bại thử thách chi 0 đồng?',
      id: 'Alasan terbesar gagal tantangan belanja nol?',
    }),
    options: [
      {
        text: T({
          ko: '실패 경험이 없거나 거의 없다. 한 번 정하면 지키는 편이다',
          en: 'I rarely fail—once I decide, I stick to it.',
          ja: '失敗経験はほぼない。一度決めたら守るタイプ。',
          zhCN: '几乎没失败过，定了就会守。',
          zhTW: '幾乎沒失敗過，定了就會守。',
          vi: 'Hiếm khi thất bại—đã quyết là giữ.',
          id: 'Jarang gagal—sudah putuskan pasti pegang.',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '예상치 못한 외부 상황이 생길 때. 내 의지보다 환경 요인',
          en: 'Unexpected outside situations—environment beats willpower.',
          ja: '予想外の外部要因。意志より環境。',
          zhCN: '意外外界情况，环境比意志大。',
          zhTW: '意外外界情況，環境比意志大。',
          vi: 'Tình huống bất ngờ—môi trường hơn ý chí.',
          id: 'Situasi luar tak terduga—lingkungan mengalahkan tekad.',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '사소한 지출이 쌓인다. 1000원, 2000원씩 조금씩 무너진다',
          en: 'Tiny spends add up—1,000 here, 2,000 there.',
          ja: '小さな出費が積み重なる。千ウォン二千ウォンで崩れる。',
          zhCN: '小钱堆起来，一千两千就崩了。',
          zhTW: '小錢堆起來，一千兩千就崩了。',
          vi: 'Chi nhỏ chồng chất—vài nghìn won là sập.',
          id: 'Pengeluaran kecil menumpuk—seribu dua ribu lalu runtuh.',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '오전에는 버티다가 오후가 되면 의지력이 바닥난다',
          en: 'I hold out in the morning—by afternoon my willpower is empty.',
          ja: '午前は耐えるが午後になると意志力が枯れる。',
          zhCN: '上午能撑，下午意志力见底。',
          zhTW: '上午能撐，下午意志力見底。',
          vi: 'Sáng còn nhịn—chiều ý chí cạn.',
          id: 'Pagi masih kuat—sore tekad habis.',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 9,
    question: T({
      ko: '평소 소비 패턴을 솔직하게 고른다면?',
      en: 'If you’re honest, your usual spending pattern is…',
      ja: '普段の消費パターンを正直に選ぶと？',
      zhCN: '平时消费习惯老实说？',
      zhTW: '平時消費習慣老實說？',
      vi: 'Thói chi tiêu thường ngày, thật lòng thì…',
      id: 'Pola belanja biasanya, jujur…',
    }),
    options: [
      {
        text: T({
          ko: '계획된 것만 산다. 충동구매가 거의 없다',
          en: 'I only buy planned items—almost no impulse buys.',
          ja: '計画したものだけ買う。衝動買いはほぼない。',
          zhCN: '只买计划内的，几乎不冲动消费。',
          zhTW: '只買計畫內的，幾乎不衝動消費。',
          vi: 'Chỉ mua theo kế hoạch—gần như không mua ngẫu hứng.',
          id: 'Hanya beli yang direncanakan—hampir tidak impulsif.',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '대체로 계획적이지만 가끔 소액 충동구매가 있다',
          en: 'Mostly planned, but sometimes small impulse purchases.',
          ja: 'だいたい計画的だが、たまに小さな衝動買いがある。',
          zhCN: '多半有计划，偶尔小额冲动。',
          zhTW: '多半有計畫，偶爾小額衝動。',
          vi: 'Đa phần có kế hoạch, thỉnh thoảng mua nhỏ bốc đồng.',
          id: 'Mayoritas terencana, kadang impuls kecil.',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '충동구매가 꽤 있다. 사고 나서 후회하는 경우도 있다',
          en: 'Quite a few impulse buys—I regret some after.',
          ja: '衝動買いが多い。買ってから後悔することもある。',
          zhCN: '冲动消费不少，买完会后悔。',
          zhTW: '衝動消費不少，買完會後悔。',
          vi: 'Khá nhiều mua ngẫu hứng—đôi khi hối sau đó.',
          id: 'Cukup banyak belanja impuls—kadang menyesal.',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '충동구매가 주를 이룬다. 계획보다 감정으로 소비하는 편이다',
          en: 'Impulse rules—I spend more on emotion than plans.',
          ja: '衝動買いが中心。計画より感情で使う。',
          zhCN: '冲动为主，情绪消费多于计划。',
          zhTW: '衝動為主，情緒消費多於計畫。',
          vi: 'Chủ yếu mua ngẫu hứng—cảm xúc hơn kế hoạch.',
          id: 'Impuls mendominasi—perasaan lebih dari rencana.',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 10,
    question: T({
      ko: '무지출 챌린지를 위해 나는 사전에 얼마나 준비하나?',
      en: 'How much do you prep the day before a zero-spend challenge?',
      ja: '無支出チャレンジのために、事前にどれだけ準備する？',
      zhCN: '为零消费挑战你会提前准备多少？',
      zhTW: '為零消費挑戰你會提前準備多少？',
      vi: 'Bạn chuẩn bị trước thế nào cho thử thách chi 0 đồng?',
      id: 'Seberapa banyak kamu persiapkan sebelum tantangan belanja nol?',
    }),
    options: [
      {
        text: T({
          ko: '전날 냉장고 정리, 알림 끄기, 동선 계획까지 꼼꼼히 준비한다',
          en: 'Full prep: fridge, notifications off, route planned.',
          ja: '前日に冷蔵庫整理・通知OFF・動線まで綿密に準備。',
          zhCN: '前夜整理冰箱、关通知、规划路线，细致准备。',
          zhTW: '前夜整理冰箱、關通知、規劃路線，細緻準備。',
          vi: 'Chuẩn bị kỹ: tủ lạnh, tắt thông báo, lên lộ trình.',
          id: 'Persiapan matang: kulkas, matikan notif, rute.',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '대략적인 계획을 세우고 당일 상황에 맞춰 대응한다',
          en: 'Rough plan—then I adapt on the day.',
          ja: 'だいたいの計画を立て、当日に合わせて対応。',
          zhCN: '大致计划，当天随机应变。',
          zhTW: '大致計畫，當天隨機應變。',
          vi: 'Kế hoạch sơ bộ—đến ngày linh hoạt.',
          id: 'Rencana kasar—hari H menyesuaikan.',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '마음만 먹고 별도 준비는 하지 않는다',
          en: 'I only decide in my head—no real prep.',
          ja: '気持ちだけ。特別な準備はしない。',
          zhCN: '只是下决心，没有特别准备。',
          zhTW: '只是下決心，沒有特別準備。',
          vi: 'Chỉ quyết tâm—không chuẩn bị gì thêm.',
          id: 'Hanya niat—tanpa persiapan khusus.',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '준비 없이 그냥 시작했다가 보통 중간에 포기한다',
          en: 'I start cold and usually quit halfway.',
          ja: '準備なしで始めて、だいたい途中で挫折。',
          zhCN: '没准备就开始，通常半途而废。',
          zhTW: '沒準備就開始，通常半途而廢。',
          vi: 'Bắt đầu không chuẩn bị—thường bỏ giữa chừng.',
          id: 'Mulai tanpa persiapan—biasanya nyerah di tengah.',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 11,
    question: T({
      ko: '무지출 챌린지 도중 친구가 "오늘 나 쏠게" 한다. 나는?',
      en: 'Mid-challenge a friend says, “My treat today.” You…',
      ja: 'チャレンジ中、友だちが「今日は俺おごる」と言う。あなたは？',
      zhCN: '挑战中朋友说“今天我请客”。你会？',
      zhTW: '挑戰中朋友說「今天我請客」。你會？',
      vi: 'Giữa thử thách bạn nói “hôm nay tôi khao”. Bạn…',
      id: 'Saat tantangan teman bilang “hari ini aku traktir”. Kamu…',
    }),
    options: [
      {
        text: T({
          ko: '고맙지만 정중히 사양한다. 내가 받으면 나중에 사줘야 해서 결국 지출이 된다',
          en: 'Thanks, but I decline—treats still become future spending for me.',
          ja: 'ありがたいが丁寧に断る。受けると後でおごり返しが必要になり結局出費になる。',
          zhCN: '感谢但婉拒，收了以后回请还是花钱。',
          zhTW: '感謝但婉拒，收了以後回請還是花錢。',
          vi: 'Cảm ơn nhưng từ chối—nhận rồi sau vẫn phải khao lại.',
          id: 'Terima kasih tapi tolak—nanti balas traktiran tetap keluar uang.',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '친구 호의는 받되 나중에 갚겠다고 말해두고 먹는다',
          en: 'I accept and say I’ll treat them back later.',
          ja: '好意は受け取り、後でおごり返すと言って食べる。',
          zhCN: '接受好意，说好以后回请再吃。',
          zhTW: '接受好意，說好以後回請再吃。',
          vi: 'Nhận và nói sau sẽ khao lại.',
          id: 'Terima dan bilang nanti traktir balik.',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '이건 내 돈이 나가는 게 아니니까 괜찮은 거 맞지? 하고 기꺼이 먹는다',
          en: 'It’s not my money leaving my wallet—sure, I’ll eat happily.',
          ja: '自分のお金が出ていないから大丈夫でしょ？と喜んで食べる。',
          zhCN: '反正不是从自己钱包出，应该没问题吧，开心吃。',
          zhTW: '反正不是從自己錢包出，應該沒問題吧，開心吃。',
          vi: 'Không phải tiền mình chi—ăn thôi.',
          id: 'Bukan uangku yang keluar—gas makan.',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '친구가 사준다는데 거절할 이유가 없다. 오히려 이날이 기회다',
          en: 'No reason to refuse a treat—this day is basically free.',
          ja: 'おごってもらえるなら断る理由がない。むしろチャンス。',
          zhCN: '请客没理由拒绝，这天等于白捡。',
          zhTW: '請客沒理由拒絕，這天等於白撿。',
          vi: 'Được khao thì không lý do từ—cơ hội luôn.',
          id: 'Ditraktir tidak ada alasan tolak—malah kesempatan.',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 12,
    question: T({
      ko: '무지출 챌린지 성공에 대한 나의 솔직한 자기 평가는?',
      en: 'Your honest self-rating for succeeding at a zero-spend challenge:',
      ja: '無支出チャレンジ成功について、正直な自己評価は？',
      zhCN: '对零消费挑战成功的诚实自评：',
      zhTW: '對零消費挑戰成功的誠實自評：',
      vi: 'Tự đánh giá thành thật về khả năng thành công thử thách chi 0 đồng:',
      id: 'Penilaian jujur atas keberhasilan tantangan belanja nol:',
    }),
    options: [
      {
        text: T({
          ko: '충분히 할 수 있다. 해본 적도 있고 의지력에 자신 있다',
          en: 'I can do it—I’ve done it before and I trust my willpower.',
          ja: '十分できる。経験もあり、意志力に自信がある。',
          zhCN: '完全能做到，有经验，对意志力有信心。',
          zhTW: '完全能做到，有經驗，對意志力有信心。',
          vi: 'Làm được—đã từng làm và tin vào ý chí.',
          id: 'Bisa—pernah dan percaya pada tekad.',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '준비만 잘 하면 가능하다. 환경 세팅이 핵심이다',
          en: 'Possible if I prep well—environment setup is everything.',
          ja: '準備さえすれば可能。環境セットアップが鍵。',
          zhCN: '准备到位就能成，环境设置是关键。',
          zhTW: '準備到位就能成，環境設置是關鍵。',
          vi: 'Chuẩn bị tốt là được—môi trường là chìa khóa.',
          id: 'Kalau persiapan bagus bisa—lingkungan kunci.',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '한 번쯤 실패할 것 같다. 그래도 거의 아깝게 버틸 것 같다',
          en: 'I might slip once—but I’d still almost make it.',
          ja: '一度は失敗しそう。でもギリギリで耐えそう。',
          zhCN: '可能会失手一次，但大概能险过。',
          zhTW: '可能會失手一次，但大概能險過。',
          vi: 'Có thể trượt một lần—nhưng gần như vẫn trụ được.',
          id: 'Mungkin gagal sekali—tapi hampir berhasil.',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '솔직히 하루도 버티기 어렵다. 나한테는 너무 가혹한 챌린지다',
          en: 'Honestly even one day is hard—this challenge is brutal for me.',
          ja: '正直一日も厳しい。自分には苛酷なチャレンジだ。',
          zhCN: '老实说一天都难，这挑战对我太狠。',
          zhTW: '老實說一天都難，這挑戰對我太狠。',
          vi: 'Thật lòng một ngày cũng khó—thử thách quá sức.',
          id: 'Jujur sehari saja sulit—tantangan ini kejam buatku.',
        }),
        score: 3,
      },
    ],
  },
];

export const phase3ZeroSpendingChallengeResults: Phase3ZeroSpendingChallengeResult[] = [
  {
    type: 'Type1',
    emoji: '💚',
    title: T({
      ko: '이미 무지출 마스터, 성공 확률 92~99%',
      en: 'Already a zero-spend master — 92–99% success odds',
      ja: 'すでに無支出マスター、成功率92〜99%',
      zhCN: '已是零消费大师，成功率 92~99%',
      zhTW: '已是零消費大師，成功率 92~99%',
      vi: 'Đã là bậc thầy chi 0 đồng — 92–99% cơ hội thành công',
      id: 'Sudah master belanja nol — peluang sukses 92–99%',
    }),
    successRateLine: T({
      ko: '무지출 챌린지 성공 확률: 92~99%',
      en: 'Zero-spend challenge success odds: 92–99%',
      ja: '無支出チャレンジ成功率：92〜99%',
      zhCN: '零消费挑战成功率：92~99%',
      zhTW: '零消費挑戰成功率：92~99%',
      vi: 'Xác suất thành công thử thách chi 0 đồng: 92–99%',
      id: 'Peluang sukses tantangan belanja nol: 92–99%',
    }),
    hookLine: T({
      ko: '"당신은 무지출 챌린지가 챌린지도 아닌 사람입니다."',
      en: '"For you, a zero-spend day barely feels like a challenge."',
      ja: '「あなたにとって無支出チャレンジはチャレンジですらない。」',
      zhCN: '“对你来说，零消费日几乎不算挑战。”',
      zhTW: '「對你來說，零消費日幾乎不算挑戰。」',
      vi: '“Với bạn, thử thách chi 0 đồng gần như không phải thử thách.”',
      id: '“Bagimu, tantangan belanja nol nyaris bukan tantangan.”',
    }),
    description: T({
      ko: '계획한 것은 지키고, 충동구매가 거의 없으며, 외부 유혹에도 흔들리지 않는 강철 의지의 소유자입니다. 무지출 챌린지는 당신에게 특별한 도전이 아니라 원래 생활 방식에 가깝습니다. 이미 해본 경험이 있거나 재정 관리가 체화된 수준입니다. 주변에서 의지력 좀 나눠달라는 소리를 들을 것입니다.',
      en: 'You keep plans, rarely impulse-buy, and barely sway to temptation—steel willpower. A zero-spend day isn’t a special feat; it’s close to how you already live. You’ve done it before or money habits are second nature. People may jokingly ask you to donate some willpower.',
      ja: '計画は守り、衝動買いはほぼなく、誘惑にも揺れない鋼の意志の持ち主。無支出は特別な挑戦というより、もともとの生活に近い。経験済みか、お金の管理が体に染みついているレベル。周りから意志力を分けてと言われるかも。',
      zhCN: '守计划、少冲动、不易受诱惑，意志如钢。零消费对你不是特别挑战，而接近日常。你已有经验或理财已成习惯。别人可能会开玩笑要你分点意志力。',
      zhTW: '守計畫、少衝動、不易受誘惑，意志如鋼。零消費對你不是特別挑戰，而接近日常。你已有經驗或理財已成習慣。別人可能會開玩笑要你分點意志力。',
      vi: 'Giữ kế hoạch, hiếm mua ngẫu hứng, khó bị cám dỗ—ý chí như thép. Ngày chi 0 đồng không phải kỳ tích mà gần với lối sống bạn. Bạn đã làm được hoặc quản tiền đã thành bản năng. Người khác có thể đùa xin “cho ít ý chí”.',
      id: 'Menepati rencana, jarang impuls, tahan godaan—tekad seperti baja. Hari belanja nol bukan pencapaian luar biasa, hampir seperti hidupmu sehari-hari. Pernah melakukan atau keuangan sudah jadi kebiasaan. Orang mungkin bercanda minta “sedikit tekad”.',
    }),
    detailSectionTitle: T({
      ko: '성공률 인사이트',
      en: 'Success-rate insights',
      ja: '成功率インサイト',
      zhCN: '成功率洞察',
      zhTW: '成功率洞察',
      vi: 'Góc nhìn tỷ lệ thành công',
      id: 'Wawasan tingkat keberhasilan',
    }),
    detailBullets: T({
      ko: '성공 확률: 92~99% 🟩🟩🟩🟩🟩\n실패 가능성: 1~8% (예측 불가능한 외부 상황만)\n가장 위험한 순간: 예상치 못한 경조사·긴급 상황 발생 시\n성공 비결: 이미 갖고 있음. 사전 준비 습관이 탁월\n오늘 할 일: 무지출 챌린지 1일이 아닌 3일 도전으로 업그레이드',
      en: 'Success odds: 92–99% 🟩🟩🟩🟩🟩\nFailure risk: 1–8% (only unpredictable external events)\nRiskiest moment: surprise life events or emergencies\nSecret: you already have it—prep habits are excellent\nToday: level up from 1 day to a 3-day streak',
      ja: '成功率：92〜99% 🟩🟩🟩🟩🟩\n失敗リスク：1〜8%（予測不能な外部要因のみ）\n最も危険な瞬間：想定外の慶弔・緊急時\n成功の秘訣：すでに持っている。事前準備の習慣が抜群\n今日：1日ではなく3日連続にアップグレード',
      zhCN: '成功概率：92~99% 🟩🟩🟩🟩🟩\n失败可能：1~8%（仅不可预测的外界情况）\n最危险时刻：突发人情或紧急情况\n成功秘诀：你已有——准备习惯极佳\n今日：从1天升级为连续3天挑战',
      zhTW: '成功機率：92~99% 🟩🟩🟩🟩🟩\n失敗可能：1~8%（僅不可預測的外界情況）\n最危險時刻：突發人情或緊急情況\n成功秘訣：你已有——準備習慣極佳\n今日：從1天升級為連續3天挑戰',
      vi: 'Tỷ lệ thành công: 92–99% 🟩🟩🟩🟩🟩\nRủi ro thất bại: 1–8% (chỉ tình huống ngoài dự đoán)\nKhoảnh khắc rủi ro nhất: việc hiếu hỉ/khẩn cấp bất ngờ\nBí quyết: bạn đã có—thói quen chuẩn bị xuất sắc\nHôm nay: nâng từ 1 ngày lên chuỗi 3 ngày',
      id: 'Peluang sukses: 92–99% 🟩🟩🟩🟩🟩\nRisiko gagal: 1–8% (hanya kejadian luar tak terduga)\nMomen paling berisiko: acara mendadak/darurat\nRahasia: sudah punya—kebiasaan persiapan kuat\nHari ini: naikkan dari 1 hari ke rangkaian 3 hari',
    }),
    prescriptionSteps: T({
      ko: '현재 수준: 무지출 마스터\n다음 목표: 주 1회 → 주 2회 무지출로 업그레이드\n월 8회 무지출 달성 시 연간 절약 예상: 100~200만 원',
      en: 'Current level: zero-spend master\nNext goal: 1 day/week → 2 days/week\nIf you hit 8 zero-spend days/month, yearly savings roughly ₩1M–2M',
      ja: '現状：無支出マスター\n次の目標：週1回→週2回へ\n月8回達成なら年間節約の目安：約100〜200万ウォン',
      zhCN: '当前：零消费大师\n下一步：每周1天→每周2天\n若每月8天零消费，年省约 100~200 万韩元',
      zhTW: '當前：零消費大師\n下一步：每週1天→每週2天\n若每月8天零消費，年省約 100~200 萬韓元',
      vi: 'Hiện tại: bậc thầy chi 0 đồng\nMục tiếp: 1 ngày/tuần → 2 ngày/tuần\nNếu 8 ngày/tháng, tiết kiệm năm ~₩1–2 triệu (ước lượng)',
      id: 'Level: master belanja nol\nBerikutnya: 1 hari/minggu → 2 hari/minggu\nJika 8 hari/bulan, hemat tahunan ~₩1–2 juta (perkiraan)',
    }),
    savingsEstimate: T({
      ko: '평소 하루 지출 전액 절약 가능',
      en: 'Can save roughly all of a typical day’s spending',
      ja: '普段の一日分の支出をほぼ全額節約可能',
      zhCN: '约等于省下平常一整天的花费',
      zhTW: '約等於省下平常一整天的花費',
      vi: 'Có thể tiết kiệm gần như toàn bộ chi tiêu một ngày bình thường',
      id: 'Bisa hemat mendekati seluruh pengeluaran harian biasa',
    }),
    yearlyApply: T({
      ko: '월 4회(주 1회) 무지출 챌린지 → 연간 50만~100만 원 절약 가능',
      en: '4 zero-spend days/month (1/week) → about ₩500k–1M saved/year',
      ja: '月4回（週1）無支出→年間約50〜100万ウォン節約の目安',
      zhCN: '每月4次（每周1天）零消费→年省约 50~100 万韩元',
      zhTW: '每月4次（每週1天）零消費→年省約 50~100 萬韓元',
      vi: '4 ngày chi 0/tháng (1/tuần) → tiết kiệm ~₩500k–1M/năm',
      id: '4 hari nol/bulan (1/minggu) → hemat ~₩500rb–1jt/tahun',
    }),
    todayTask: T({
      ko: '무지출 챌린지 1일이 아닌 3일 연속 도전 일정을 캘린더에 잡아보세요.',
      en: 'Schedule a 3-day zero-spend streak on your calendar—not just one day.',
      ja: '1日ではなく3日連続の無支出チャレンジをカレンダーに入れてみる。',
      zhCN: '在日历上安排连续3天零消费，而不只是一天。',
      zhTW: '在日曆上安排連續3天零消費，而不只是一天。',
      vi: 'Lên lịch chuỗi 3 ngày chi 0 trên lịch—không chỉ một ngày.',
      id: 'Jadwalkan rangkaian 3 hari belanja nol di kalender—bukan sehari saja.',
    }),
    motivationLine: T({
      ko: '"당신의 의지력은 이미 충분합니다. 이제 빈도를 높일 차례입니다"',
      en: '"Your willpower is already enough—now raise how often you use it."',
      ja: '「あなたの意志力はすでに十分。いまは頻度を上げる番。」',
      zhCN: '“你的意志力已经够用了，现在该提高频率。”',
      zhTW: '「你的意志力已經夠用了，現在該提高頻率。」',
      vi: '“Ý chí của bạn đã đủ—giờ hãy tăng tần suất.”',
      id: '“Tekadmu sudah cukup—sekarang tingkatkan frekuensinya.”',
    }),
    shareLine: T({
      ko: '무지출 챌린지 성공 확률 99% 💚 이미 마스터 수준이라는데 솔직히 맞는 것 같음 → 너는 몇 %야?',
      en: 'My zero-spend odds: 99% 💚 Basically master tier—sounds right → what’s your %?',
      ja: '無支出チャレンジ成功率99% 💚もうマスター級って言われてるけど、正直それっぽい → あなたは何%？',
      zhCN: '零消费成功率 99% 💚 说是大师级，老实说挺准 → 你多少 %？',
      zhTW: '零消費成功率 99% 💚 說是大師級，老實說挺準 → 你多少 %？',
      vi: 'Tỷ lệ chi 0 đồng của tôi: 99% 💚 Bảo là master—nghe cũng đúng → bạn bao nhiêu %?',
      id: 'Peluang belanja nol-ku: 99% 💚 Katanya level master—kebetulan pas → kamu berapa %?',
    }),
  },
  {
    type: 'Type2',
    emoji: '🔵',
    title: T({
      ko: '준비하면 반드시 된다, 성공 확률 75~85%',
      en: 'Prep well and you’ll make it — 75–85% odds',
      ja: '準備できれば必ず達成、成功率75〜85%',
      zhCN: '准备到位就能成，成功率 75~85%',
      zhTW: '準備到位就能成，成功率 75~85%',
      vi: 'Chuẩn bị tốt là qua — 75–85%',
      id: 'Kalau persiapan bagus pasti bisa — 75–85%',
    }),
    successRateLine: T({
      ko: '무지출 챌린지 성공 확률: 75~85%',
      en: 'Zero-spend challenge success odds: 75–85%',
      ja: '無支出チャレンジ成功率：75〜85%',
      zhCN: '零消费挑战成功率：75~85%',
      zhTW: '零消費挑戰成功率：75~85%',
      vi: 'Xác suất thành công: 75–85%',
      id: 'Peluang sukses: 75–85%',
    }),
    hookLine: T({
      ko: '"당신은 준비만 잘 하면 반드시 성공하는 타입입니다."',
      en: '"If you set up your environment, you can absolutely succeed."',
      ja: '「準備さえ整えば必ず成功できるタイプ。」',
      zhCN: '“只要环境备好，你一定能成功。”',
      zhTW: '「只要環境備好，你一定能成功。」',
      vi: '“Chỉ cần chuẩn bị môi trường là bạn chắc chắn làm được.”',
      id: '“Asal persiapan lingkungan, kamu pasti bisa.”',
    }),
    description: T({
      ko: '기본 의지력은 충분히 갖추고 있지만 환경 세팅이 성패를 가릅니다. 전날 냉장고 정리, 배달 앱 알림 끄기, 동선 계획처럼 유혹을 미리 차단해두면 높은 확률로 성공합니다. 반대로 준비 없이 덤벼들면 중간에 "오늘만 예외" 함정에 빠질 수 있습니다. 챌린지 전날의 10분이 성공을 결정합니다.',
      en: 'Your baseline willpower is solid—environment decides win or lose. Clear the fridge, silence delivery alerts, plan routes to dodge temptation and your odds jump. Charge in unprepared and you may fall into “just today” exceptions. Ten minutes the night before often decides success.',
      ja: '基礎の意志力は十分だが、環境設計が勝敗を分ける。前日に冷蔵庫整理・配達通知OFF・動線で誘惑を先に遮れば成功率は高い。準備なしだと「今日だけ例外」に落ちやすい。前夜の10分が成功を決める。',
      zhCN: '意志底子够，成败在环境。前夜整理冰箱、关外卖通知、规划绕路避开诱惑，成功率就高。没准备容易掉进“今天就例外”。挑战前夜10分钟常决定成败。',
      zhTW: '意志底子夠，成敗在環境。前夜整理冰箱、關外送通知、規劃繞路避開誘惑，成功率就高。沒準備容易掉進「今天就例外」。挑戰前夜10分鐘常決定成敗。',
      vi: 'Ý chí nền đủ—môi trường quyết thắng thua. Tối hôm trước: dọn tủ lạnh, tắt thông báo giao đồ, lên đường tránh cám dỗ thì tỷ lệ cao. Lao vào không chuẩn bị dễ rơi “hôm nay ngoại lệ”. 10 phút tối hôm trước thường quyết định.',
      id: 'Tekad dasar cukup—lingkungan menentukan. Malam sebelumnya: kulkas, matikan notif pesan-antar, rute hindari godaan—peluang naik. Tanpa persiapan mudah jebakan “hari ini saja”. 10 menit malam sebelumnya sering menentukan.',
    }),
    detailSectionTitle: T({
      ko: '성공률 인사이트',
      en: 'Success-rate insights',
      ja: '成功率インサイト',
      zhCN: '成功率洞察',
      zhTW: '成功率洞察',
      vi: 'Góc nhìn tỷ lệ thành công',
      id: 'Wawasan tingkat keberhasilan',
    }),
    detailBullets: T({
      ko: '성공 확률: 75~85% 🟦🟦🟦🟦□\n실패 가능성: 15~25% (준비 부족 또는 외부 유혹)\n가장 위험한 순간: 스트레스 받는 날 오후 3~6시 (의지력 방전 구간)\n성공 비결: 전날 밤 환경 세팅이 핵심\n오늘 할 일: ① 배달 앱 알림 OFF ② 편의점 동선 우회 계획 ③ 대체 간식 준비',
      en: 'Success odds: 75–85% 🟦🟦🟦🟦□\nFailure risk: 15–25% (weak prep or outside temptation)\nRiskiest window: 3–6 p.m. on stressful days (willpower dip)\nSecret: night-before environment setup\nToday: ① mute delivery alerts ② plan a detour around stores ③ pack snacks',
      ja: '成功率：75〜85% 🟦🟦🟦🟦□\n失敗リスク：15〜25%（準備不足か外部誘惑）\n最も危険：ストレスの日の15〜18時（意志力低下）\n秘訣：前夜の環境設計\n今日：①配達通知OFF ②コンビニ迂回 ③代替おやつ',
      zhCN: '成功概率：75~85% 🟦🟦🟦🟦□\n失败可能：15~25%（准备不足或外界诱惑）\n最危险：压力大那天的下午3~6点（意志力低谷）\n秘诀：前夜环境布置\n今日：①关外卖通知 ②绕开便利店 ③带替代零食',
      zhTW: '成功機率：75~85% 🟦🟦🟦🟦□\n失敗可能：15~25%（準備不足或外界誘惑）\n最危險：壓力大那天的下午3~6點（意志力低谷）\n秘訣：前夜環境布置\n今日：①關外送通知 ②繞開便利商店 ③帶替代零食',
      vi: 'Tỷ lệ thành công: 75–85% 🟦🟦🟦🟦□\nRủi ro thất bại: 15–25% (chuẩn bị kém hoặc cám dỗ)\nKhung giờ rủi ro: 15–18h ngày căng (ý chí yếu)\nBí quyết: dọn môi trường tối hôm trước\nHôm nay: ① tắt thông báo giao đồ ② đường vòng tránh cửa hàng ③ mang đồ ăn thay thế',
      id: 'Peluang: 75–85% 🟦🟦🟦🟦□\nRisiko gagal: 15–25% (persiapan lemah atau godaan)\nJam rawan: 15–18 saat stres (tekad turun)\nRahasia: setel lingkungan malam sebelumnya\nHari ini: ① matikan notif pesan-antar ② rute hindari minimarket ③ bawa camilan',
    }),
    prescriptionSteps: T({
      ko: '오늘 밤 10분 투자\n① 배달 앱 알림 전체 OFF\n② 편의점 동선 우회 루트 계획\n③ 내일 챙길 간식·커피 미리 준비\n④ 지루한 시간대 대체 활동 예약 — 이것만 해도 성공률 약 20% 상승',
      en: 'Invest 10 minutes tonight:\n① turn off all delivery alerts\n② plan a route that skips convenience stores\n③ prep snacks/coffee for tomorrow\n④ book a boredom backup activity—this alone can lift success odds ~20%',
      ja: '今夜10分投資\n①デリバリー通知を全部OFF\n②コンビニを避ける動線\n③明日のおやつ・コーヒーを用意\n④退屈な時間の代替予約—これだけで成功率約+20%',
      zhCN: '今晚投资10分钟\n①关闭所有外卖通知\n②规划绕开便利店的路线\n③备好明天零食/咖啡\n④给无聊时段预约替代活动—仅此成功率约+20%',
      zhTW: '今晚投資10分鐘\n①關閉所有外送通知\n②規劃繞開便利商店的路線\n③備好明天零食/咖啡\n④給無聊時段預約替代活動—僅此成功率約+20%',
      vi: 'Đầu tư 10 phút tối nay:\n① tắt hết thông báo giao đồ\n② lên đường tránh cửa tiện lợi\n③ chuẩn bị đồ ăn/cà phê mai\n④ đặt hoạt động dự phòng khi chán—có thể +~20% tỷ lệ thành công',
      id: 'Investasi 10 menit malam ini:\n① matikan semua notif pesan-antar\n② rute hindari minimarket\n③ siapkan camilan/kopi besok\n④ aktivitas cadangan saat bosan—bisa naikkan peluang ~20%',
    }),
    savingsEstimate: T({
      ko: '하루 지출의 80~90% 절약 가능',
      en: 'Can save ~80–90% of a typical day’s spending',
      ja: '普段の一日支出の80〜90%を節約できる目安',
      zhCN: '约能省下平日一天花费的 80~90%',
      zhTW: '約能省下平日一天花費的 80~90%',
      vi: 'Có thể tiết kiệm ~80–90% chi tiêu một ngày bình thường',
      id: 'Bisa hemat ~80–90% pengeluaran harian biasa',
    }),
    yearlyApply: T({
      ko: '월 2회 무지출 챌린지 → 연간 30~60만 원 절약 가능',
      en: '2 zero-spend days/month → roughly ₩300k–600k/year',
      ja: '月2回無支出→年間約30〜60万ウォン節約の目安',
      zhCN: '每月2天零消费→年省约 30~60 万韩元',
      zhTW: '每月2天零消費→年省約 30~60 萬韓元',
      vi: '2 ngày chi 0/tháng → ~₩300k–600k/năm',
      id: '2 hari nol/bulan → ~₩300rb–600rb/tahun',
    }),
    todayTask: T({
      ko: '배달 앱 알림 OFF, 편의점 우회 동선, 내일 간식·커피를 메모해 두세요.',
      en: 'Mute delivery alerts, sketch a store-detour route, note tomorrow’s snacks/coffee.',
      ja: '配達通知OFF、コンビニ迂回ルート、明日のおやつ・コーヒーをメモ。',
      zhCN: '关外卖通知、画绕开便利店的路线、记下明天零食/咖啡。',
      zhTW: '關外送通知、畫繞開便利商店的路線、記下明天零食/咖啡。',
      vi: 'Tắt thông báo giao đồ, phác đường tránh cửa hàng, ghi chú đồ ăn/cà phê mai.',
      id: 'Matikan notif pesan-antar, sketsa rute hindari minimarket, catat camilan/kopi besok.',
    }),
    motivationLine: T({
      ko: '"준비된 당신은 성공합니다. 오늘 밤 10분만 투자하세요"',
      en: '"Prepared you wins—invest just 10 minutes tonight."',
      ja: '「準備したあなたは成功する。今夜10分だけ投資を。」',
      zhCN: '“有准备的你就会成功，今晚只投10分钟。”',
      zhTW: '「有準備的你就會成功，今晚只投10分鐘。」',
      vi: '“Bạn đã chuẩn bị là sẽ thành công—chỉ 10 phút tối nay.”',
      id: '“Yang siap akan berhasil—investasi 10 menit malam ini saja.”',
    }),
    shareLine: T({
      ko: '무지출 챌린지 성공 확률 80% 🔵 준비만 하면 된다는 거 알고 있음 → 너는 몇 %야?',
      en: 'My zero-spend odds: 80% 🔵 I know prep is everything → what’s your %?',
      ja: '無支出成功率80% 🔵準備が大事なのは分かってる → あなたは何%？',
      zhCN: '零消费成功率 80% 🔵 知道要靠准备 → 你多少 %？',
      zhTW: '零消費成功率 80% 🔵 知道要靠準備 → 你多少 %？',
      vi: 'Tỷ lệ chi 0 của tôi: 80% 🔵 Biết là phải chuẩn bị → bạn bao nhiêu %?',
      id: 'Peluang belanja nol-ku: 80% 🔵 Tahu harus persiapan → kamu berapa %?',
    }),
  },
  {
    type: 'Type3',
    emoji: '🟡',
    title: T({
      ko: '아깝게 버티는 스타일, 성공 확률 55~65%',
      en: 'The "almost made it" type — 55–65%',
      ja: 'ギリギリで耐えるタイプ、成功率55〜65%',
      zhCN: '险撑型，成功率 55~65%',
      zhTW: '險撐型，成功率 55~65%',
      vi: 'Gần trụ rồi gãy — 55–65%',
      id: 'Hampir kuat lalu runtuh — 55–65%',
    }),
    successRateLine: T({
      ko: '무지출 챌린지 성공 확률: 55~65%',
      en: 'Zero-spend success odds: 55–65%',
      ja: '無支出成功率：55〜65%',
      zhCN: '零消费成功率：55~65%',
      zhTW: '零消費成功率：55~65%',
      vi: 'Xác suất thành công: 55–65%',
      id: 'Peluang sukses: 55–65%',
    }),
    hookLine: T({
      ko: '"당신은 거의 다 버티다가 마지막에 무너지는 타입입니다."',
      en: '"You almost make it—then break at the finish line."',
      ja: '「ほぼ耐えるが、最後に崩れるタイプ。」',
      zhCN: '“你几乎撑到最后才崩。”',
      zhTW: '「你幾乎撐到最後才崩。」',
      vi: '“Bạn gần như trụ được—rồi gãy ở cuối.”',
      id: '“Hampir bertahan—lalu runtuh di akhir.”',
    }),
    description: T({
      ko: '오전은 완벽합니다. 점심도 어떻게 버팁니다. 그런데 오후 2~4시쯤 심심함과 허기가 동시에 몰려오면 "이 정도면 거의 다 한 거잖아" 합리화가 시작됩니다. 결국 1000~3000원짜리 소액에 챌린지가 무너집니다. 의지력 자체보다 지루함과 배고픔 관리가 관건입니다.',
      en: 'Morning is perfect; lunch you survive. Around 2–4 p.m., boredom plus hunger hits and “I’ve basically done the challenge” rationalization starts. A ₩1,000–3,000 slip ends the streak. Managing boredom and hunger matters more than raw willpower.',
      ja: '午前は完璧、昼もなんとか。14〜16時ごろ退屈と空腹が重なると「もうほぼ達成でしょ」と言い訳が始まる。千〜三千ウォンの小額で崩れる。意志力より退屈と空腹の管理が鍵。',
      zhCN: '上午完美，午餐也撑住。下午2~4点无聊加饿一起来，就开始合理化“差不多算完成了”。最后栽在几千韩元小笔上。管理无聊和饥饿比意志力更关键。',
      zhTW: '上午完美，午餐也撐住。下午2~4點無聊加餓一起來，就開始合理化「差不多算完成了」。最後栽在幾千韓元小筆上。管理無聊和飢餓比意志力更關鍵。',
      vi: 'Sáng hoàn hảo, trưa còn trụ. Khoảng 14–16h chán + đói cùng lúc là bắt đầu biện minh “gần xong rồi”. Một khoản nhỏ vài nghìn won là hỏng. Quản lý chán và đói quan trọng hơn ý chí thuần túy.',
      id: 'Pagi sempurna, siang masih kuat. Sekitar 14–16 bosan + lapar bareng mulai rasionalisasi “hampir selesai”. Slip kecil beberapa ribu won sudah gagal. Mengatur bosan dan lapar lebih penting dari tekad mentah.',
    }),
    detailSectionTitle: T({
      ko: '성공률 인사이트',
      en: 'Success-rate insights',
      ja: '成功率インサイト',
      zhCN: '成功率洞察',
      zhTW: '成功率洞察',
      vi: 'Góc nhìn tỷ lệ thành công',
      id: 'Wawasan tingkat keberhasilan',
    }),
    detailBullets: T({
      ko: '성공 확률: 55~65% 🟨🟨🟨□□\n실패 가능성: 35~45% (오후 지루함·허기 구간이 최대 위기)\n가장 위험한 순간: 오후 2~4시 심심함 + 배고픔 동시 발생 시\n성공 비결: 그 시간대 미리 대안 활동 배치 (산책, 물 마시기, 유튜브 등)\n오늘 할 일: ① 오후 간식으로 집에서 챙겨온 것 준비 ② 지루함 해소 플랜 B 미리 준비',
      en: 'Odds: 55–65% 🟨🟨🟨□□\nFailure risk: 35–45% (afternoon boredom + hunger zone)\nRiskiest: 2–4 p.m. when bored and hungry together\nSecret: schedule alternate activities then (walk, water, short video)\nToday: ① pack home snacks for afternoon ② prep a “plan B” for boredom',
      ja: '成功率：55〜65% 🟨🟨🟨□□\n失敗リスク：35〜45%（午後の退屈・空腹帯）\n最危険：14〜16時 退屈+空腹が重なる時\n秘訣：その時間に代替行動（散歩・水・短い動画）\n今日：①午後用におやつを家から ②退屈用プランB',
      zhCN: '概率：55~65% 🟨🟨🟨□□\n失败可能：35~45%（下午无聊+饿）\n最险：下午2~4点又闲又饿\n秘诀：提前安排那段时间的替代活动\n今日：①带下午零食 ②准备解闷B计划',
      zhTW: '機率：55~65% 🟨🟨🟨□□\n失敗可能：35~45%（下午無聊+餓）\n最險：下午2~4點又閒又餓\n秘訣：提前安排那段時間的替代活動\n今日：①帶下午零食 ②準備解悶B計畫',
      vi: 'Tỷ lệ: 55–65% 🟨🟨🟨□□\nRủi ro: 35–45% (chiều chán + đói)\nNguy hiểm nhất: 14–16h vừa chán vừa đói\nBí quyết: lên lịch hoạt động thay thế (đi bộ, nước, video ngắn)\nHôm nay: ① mang đồ ăn nhẹ chiều ② kế hoạch B khi chán',
      id: 'Peluang: 55–65% 🟨🟨🟨□□\nRisiko: 35–45% (sore bosan + lapar)\nPaling riskan: 14–16 bosan + lapar bersamaan\nRahasia: jadwalkan aktivitas pengganti\nHari ini: ① camilan sore dari rumah ② rencana B saat bosan',
    }),
    prescriptionSteps: T({
      ko: '성공 확률 55~85% 구간: 환경 세팅 처방\n오늘 밤 10분 투자로 알림·동선·간식·대체 활동까지 정리\n이것만 해도 성공률이 눈에 띄게 오릅니다',
      en: '55–85% band: environment prescription\nSpend 10 minutes tonight locking alerts, routes, snacks, and backup activities\nThat alone can noticeably lift your odds',
      ja: '55〜85%帯：環境セットの処方\n今夜10分で通知・動線・おやつ・代替活動を整理\nこれだけでも成功率が上がる',
      zhCN: '55~85%区间：环境处方\n今晚10分钟整理通知、路线、零食、替代活动\n仅此就能明显提升成功率',
      zhTW: '55~85%區間：環境處方\n今晚10分鐘整理通知、路線、零食、替代活動\n僅此就能明顯提升成功率',
      vi: 'Nhóm 55–85%: đơn thuốc môi trường\n10 phút tối nay: thông báo, đường đi, đồ ăn, hoạt động dự phòng\nChỉ vậy đã tăng rõ tỷ lệ',
      id: 'Rentang 55–85%: resep lingkungan\n10 menit malam: notif, rute, camilan, aktivitas cadangan\nItu saja sudah naikkan peluang',
    }),
    savingsEstimate: T({
      ko: '성공 시 하루 지출의 70% 절약. 실패해도 소액 지출로 마무리 가능',
      en: 'If you succeed: ~70% of daily spend saved; if you slip, often just small amounts',
      ja: '成功なら一日支出の約70%節約。失敗しても小額で済むことが多い',
      zhCN: '成功可省约一天支出的70%；失手也常只是小额',
      zhTW: '成功可省約一天支出的70%；失手也常只是小額',
      vi: 'Thành công: tiết kiệm ~70% chi tiêu ngày; trượt thường chỉ số nhỏ',
      id: 'Sukses: hemat ~70% pengeluaran harian; gagal sering hanya nominal kecil',
    }),
    yearlyApply: T({
      ko: '월 2회 도전, 1.5회 성공 평균 → 연간 20~40만 원 절약 가능',
      en: '2 tries/month, ~1.5 wins on average → ~₩200k–400k/year',
      ja: '月2回挑戦・平均1.5回成功→年間約20〜40万ウォン',
      zhCN: '每月挑战2次、平均成功约1.5次→年省约 20~40 万韩元',
      zhTW: '每月挑戰2次、平均成功約1.5次→年省約 20~40 萬韓元',
      vi: '2 lần/tháng, trung bình ~1,5 thành công → ~₩200k–400k/năm',
      id: '2 kali/bulan, rata-rata ~1,5 sukses → ~₩200rb–400rb/tahun',
    }),
    todayTask: T({
      ko: '오후 3시 전후 알람을 맞춰 두고, 그때 마실 물·집 간식을 챙겨 두세요.',
      en: 'Set an alarm around 3 p.m. and prep water plus snacks from home for that window.',
      ja: '15時前後にアラームをセットし、その時間用に水と家のおやつを用意。',
      zhCN: '设下午3点左右的闹钟，并备好水和家里零食。',
      zhTW: '設下午3點左右的鬧鐘，並備好水和家裡零食。',
      vi: 'Báo thức khoảng 15h và chuẩn bị nước + đồ ăn nhẹ từ nhà.',
      id: 'Alarm sekitar jam 3 sore, siapkan air + camilan dari rumah.',
    }),
    motivationLine: T({
      ko: '"오후 3시만 버티면 됩니다. 그 한 시간이 챌린지의 전부입니다"',
      en: '"Just survive 3 p.m.—that hour is the whole challenge."',
      ja: '「午後3時さえ乗り越えればいい。その一時間がチャレンジのすべて。」',
      zhCN: '“只要扛过下午3点，那一小时就是全部。”',
      zhTW: '「只要扛過下午3點，那一小時就是全部。」',
      vi: '“Chỉ cần vượt qua 3 giờ chiều—một giờ đó là cả thử thách.”',
      id: '“Lewati jam 3 sore—satu jam itu seluruh tantangan.”',
    }),
    shareLine: T({
      ko: '무지출 챌린지 성공 확률 60% 🟡 오후 3시에 무너지는 타입 맞음... → 너는 몇 %야?',
      en: 'My zero-spend odds: 60% 🟡 I really do crash at 3 p.m.… what’s your %?',
      ja: '無支出成功率60% 🟡午後3時に崩れるタイプ、ドンピシャ…あなたは何%？',
      zhCN: '零消费成功率 60% 🟡 下午3点崩，太准…你多少 %？',
      zhTW: '零消費成功率 60% 🟡 下午3點崩，太準…你多少 %？',
      vi: 'Tỷ lệ chi 0: 60% 🟡 Đúng là gãy lúc 15h… bạn bao nhiêu %?',
      id: 'Peluang nol-ku: 60% 🟡 Memang runtuh jam 3… kamu berapa %?',
    }),
  },
  {
    type: 'Type4',
    emoji: '🟠',
    title: T({
      ko: '절반의 의지, 성공 확률 35~45%',
      en: 'Half the willpower — 35–45%',
      ja: '意志は半分、成功率35〜45%',
      zhCN: '意志一半，成功率 35~45%',
      zhTW: '意志一半，成功率 35~45%',
      vi: 'Nửa ý chí — 35–45%',
      id: 'Setengah tekad — 35–45%',
    }),
    successRateLine: T({
      ko: '무지출 챌린지 성공 확률: 35~45%',
      en: 'Zero-spend success odds: 35–45%',
      ja: '無支出成功率：35〜45%',
      zhCN: '零消费成功率：35~45%',
      zhTW: '零消費成功率：35~45%',
      vi: 'Xác suất chi 0 đồng: 35–45%',
      id: 'Peluang belanja nol: 35–45%',
    }),
    hookLine: T({
      ko: '"당신은 마음은 굴뚝같은데 현실이 따라주지 않는 타입입니다."',
      en: '"Your mindset is strong—reality doesn’t always cooperate."',
      ja: '「気持ちは強いが、現実がついてこないタイプ。」',
      zhCN: '“心气很硬，现实不太配合。”',
      zhTW: '「心氣很硬，現實不太配合。」',
      vi: '“Tinh thần cứng—thực tế không theo kịp.”',
      id: '“Niatan kuat—realita sering tidak mengikuti.”',
    }),
    description: T({
      ko: '챌린지 시작은 매번 합니다. 그런데 커피 한 잔, 편의점 껌 하나, 갑자기 온 50% 쿠폰에 연달아 무너지는 패턴이 있습니다. 의지력 자체보다 소비 습관이 이미 일상 깊숙이 들어와 있는 상태입니다. 하루 완전 무지출보다 "하루 지출 5000원 이하" 같은 현실적인 목표가 오히려 더 잘 맞는 타입입니다.',
      en: 'You always start strong—then coffee, a convenience-store snack, a 50% coupon, and the streak breaks. Spending habits run deeper than willpower. A strict zero-spend day may be too harsh; a “spend under ₩5,000 today” mini-challenge often fits better.',
      ja: '始めるのは毎回。でもコーヒー、コンビニおやつ、50%クーポンで連続で崩れる。意志力より消費習慣が深く根付いている。完全ゼロより「今日は5000ウォン以下」の方が合うタイプ。',
      zhCN: '每次开头都很猛，然后咖啡、便利店零食、五折券连环破功。消费习惯比意志更根深蒂固。完全零元可能太狠，“今天花费5000韩元以下”的小挑战往往更合适。',
      zhTW: '每次開頭都很猛，然後咖啡、便利商店零食、五折券連環破功。消費習慣比意志更根深蒂固。完全零元可能太狠，「今天花費5000韓元以下」的小挑戰往往更合適。',
      vi: 'Luôn khởi đầu mạnh—rồi cà phê, đồ tiện lợi, coupon 50% là gãy chuỗi. Thói chi tiêu ăn sâu hơn ý chí. Ngày 0 đồng có thể quá khắc; thử thách “dưới ₩5.000 hôm nay” thường hợp hơn.',
      id: 'Selalu mulai kuat—lalu kopi, jajan minimarket, kupon 50% bikin runtuh. Kebiasaan belanja lebih dalam dari tekad. Nol penuh mungkin kejam; mini-tantangan “di bawah ₩5.000 hari ini” sering lebih pas.',
    }),
    detailSectionTitle: T({
      ko: '성공률 인사이트',
      en: 'Success-rate insights',
      ja: '成功率インサイト',
      zhCN: '成功率洞察',
      zhTW: '成功率洞察',
      vi: 'Góc nhìn tỷ lệ thành công',
      id: 'Wawasan tingkat keberhasilan',
    }),
    detailBullets: T({
      ko: '성공 확률: 35~45% 🟧🟧□□□\n실패 가능성: 55~65% (소비 패턴 자체가 자동화된 상태)\n가장 위험한 순간: 편의점, 배달 앱 알림, 지인과의 약속 모두 위험\n성공 비결: 완전 무지출 대신 "필수 지출만 허용" 변형 챌린지 시도\n오늘 할 일: 무지출 대신 "오늘 지출 5000원 이하" 미니 챌린지로 시작하기',
      en: 'Odds: 35–45% 🟧🟧□□□\nFailure risk: 55–65% (spending on autopilot)\nRisk zones: convenience stores, delivery pings, social plans\nSecret: try a “essential spend only” variant instead of strict zero\nToday: start a mini “under ₩5,000 today” goal',
      ja: '成功率：35〜45% 🟧🟧□□□\n失敗リスク：55〜65%（消費が自動化）\n危険地帯：コンビニ・配達通知・予定\n秘訣：完全ゼロより「必要支出だけ」変形チャレンジ\n今日：「今日5000ウォン以下」ミニチャレンジ',
      zhCN: '概率：35~45% 🟧🟧□□□\n失败可能：55~65%（消费已自动化）\n危险区：便利店、外卖通知、社交约会\n秘诀：先试“仅允许必要支出”变体\n今日：从“今天花费5000韩元以下”迷你挑战开始',
      zhTW: '機率：35~45% 🟧🟧□□□\n失敗可能：55~65%（消費已自動化）\n危險區：便利商店、外送通知、社交約會\n秘訣：先試「僅允許必要支出」變體\n今日：從「今天花費5000韓元以下」迷你挑戰開始',
      vi: 'Tỷ lệ: 35–45% 🟧🟧□□□\nRủi ro: 55–65% (chi tiêu tự động)\nVùng rủi ro: cửa tiện lợi, thông báo giao đồ, hẹn xã hội\nBí quyết: thử biến thể “chỉ chi cần thiết”\nHôm nay: bắt đầu mini “dưới ₩5.000 hôm nay”',
      id: 'Peluang: 35–45% 🟧🟧□□□\nRisiko: 55–65% (belanja autopilot)\nZona rawan: minimarket, notif pesan-antar, janji sosial\nRahasia: coba varian “hanya pengeluaran penting”\nHari ini: mulai mini “di bawah ₩5.000 hari ini”',
    }),
    prescriptionSteps: T({
      ko: '1단계: 하루 지출 1만 원 이하 챌린지\n2단계: 하루 지출 5000원 이하 챌린지\n3단계: 완전 무지출 챌린지 — 단계별 성공 후 업그레이드',
      en: 'Step 1: cap spending under ₩10,000/day\nStep 2: cap under ₩5,000/day\nStep 3: full zero-spend—level up only after each step sticks',
      ja: '第1段階：1日1万ウォン以下\n第2段階：1日5000ウォン以下\n第3段階：完全無支出—段階ごとに成功してから',
      zhCN: '第1步：每天花费不超过1万韩元\n第2步：不超过5000韩元\n第3步：完全零消费—每步稳定再升级',
      zhTW: '第1步：每天花費不超過1萬韓元\n第2步：不超過5000韓元\n第3步：完全零消費—每步穩定再升級',
      vi: 'Bước 1: dưới ₩10.000/ngày\nBước 2: dưới ₩5.000/ngày\nBước 3: chi 0 đồng—chỉ lên cấp khi bước trước ổn',
      id: 'Langkah 1: di bawah ₩10.000/hari\nLangkah 2: di bawah ₩5.000/hari\nLangkah 3: nol penuh—naik level jika langkah sebelumnya mantap',
    }),
    savingsEstimate: T({
      ko: '평소 대비 50~60% 지출 감소 목표로 조정',
      en: 'Aim to cut typical daily spend by ~50–60%',
      ja: '普段比で支出を50〜60%減らす目標に調整',
      zhCN: '目标把平常日支出压低约50~60%',
      zhTW: '目標把平常日支出壓低約50~60%',
      vi: 'Mục tiêu giảm ~50–60% chi tiêu ngày thường',
      id: 'Target turunkan ~50–60% pengeluaran harian biasa',
    }),
    yearlyApply: T({
      ko: '미니 챌린지 월 4회 → 연간 15~30만 원 절약 가능',
      en: '4 mini-challenge days/month → ~₩150k–300k/year',
      ja: 'ミニチャレンジ月4回→年間約15〜30万ウォン',
      zhCN: '每月4次迷你挑战→年省约 15~30 万韩元',
      zhTW: '每月4次迷你挑戰→年省約 15~30 萬韓元',
      vi: '4 ngày mini/tháng → ~₩150k–300k/năm',
      id: '4 hari mini/bulan → ~₩150rb–300rb/tahun',
    }),
    todayTask: T({
      ko: '오늘은 "지출 5000원 이하"만 목표로 정하고 영수증·알림을 한 번 점검하세요.',
      en: 'Today’s only goal: spend under ₩5,000—quick-scan receipts and alerts once.',
      ja: '今日の目標は「5000ウォン以下」だけ。レシートと通知を一度チェック。',
      zhCN: '今天目标只有“花费5000韩元以下”，快速检查一次小票和通知。',
      zhTW: '今天目標只有「花費5000韓元以下」，快速檢查一次收據和通知。',
      vi: 'Hôm nay chỉ mục tiêu “dưới ₩5.000”—lướt nhanh biên lai và thông báo một lần.',
      id: 'Hari ini cuma target “di bawah ₩5.000”—cek sekali struk dan notifikasi.',
    }),
    motivationLine: T({
      ko: '"0원이 어렵다면 5000원부터 시작하세요. 작은 성공이 습관을 바꿉니다"',
      en: '"If zero is too hard, start at ₩5,000—small wins rewrite habits."',
      ja: '「ゼロが難しければ5000ウォンから。小さな成功が習慣を変える。」',
      zhCN: '“零太难就从5000韩元开始，小成功改习惯。”',
      zhTW: '「零太難就從5000韓元開始，小成功改習慣。」',
      vi: '“Nếu 0 đồng quá khó, bắt từ ₩5.000—chiến thắng nhỏ đổi thói quen.”',
      id: '“Kalau nol terlalu berat, mulai dari ₩5.000—kemenangan kecil mengubah kebiasaan.”',
    }),
    shareLine: T({
      ko: '무지출 챌린지 성공 확률 40% 🟠 마음은 굴뚝같은데 현실이... 공감하면 좋아요 → 너는 몇 %야?',
      en: 'My zero-spend odds: 40% 🟠 Mind says yes, coupons say no—relatable? What’s your %?',
      ja: '無支出成功率40% 🟠気持ちは強いのに現実が…共感したらいいね → あなたは何%？',
      zhCN: '零消费成功率 40% 🟠 心气很硬现实很软…有同感吗 → 你多少 %？',
      zhTW: '零消費成功率 40% 🟠 心氣很硬現實很軟…有同感嗎 → 你多少 %？',
      vi: 'Tỷ lệ chi 0: 40% 🟠 Lý trí mạnh, thực tế… — đồng cảm không? Bạn bao nhiêu %?',
      id: 'Peluang nol-ku: 40% 🟠 Niatan keras, kenyataan… relate? Kamu berapa %?',
    }),
  },
  {
    type: 'Type5',
    emoji: '🔴',
    title: T({
      ko: '도전은 했는데 결과는 글쎄, 성공 확률 15~25%',
      en: 'You try—but odds are shaky — 15–25%',
      ja: '挑戦はするが結果は微妙、成功率15〜25%',
      zhCN: '有挑战但结果难说，成功率 15~25%',
      zhTW: '有挑戰但結果難說，成功率 15~25%',
      vi: 'Có thử—nhưng kết quả hên xui — 15–25%',
      id: 'Ada usaha—tapi hasil ragu — 15–25%',
    }),
    successRateLine: T({
      ko: '무지출 챌린지 성공 확률: 15~25%',
      en: 'Zero-spend success odds: 15–25%',
      ja: '無支出成功率：15〜25%',
      zhCN: '零消费成功率：15~25%',
      zhTW: '零消費成功率：15~25%',
      vi: 'Xác suất chi 0 đồng: 15–25%',
      id: 'Peluang belanja nol: 15–25%',
    }),
    hookLine: T({
      ko: '"당신에게 무지출 챌린지는 가혹한 도전입니다. 하지만 불가능하지는 않습니다."',
      en: '"A zero-spend day is brutal for you—but not impossible."',
      ja: '「無支出はあなたには厳しい挑戦。でも不可能ではない。」',
      zhCN: '“零消费对你很残酷，但不是不可能。”',
      zhTW: '「零消費對你很殘酷，但不是不可能。」',
      vi: '“Ngày chi 0 đồng khắc nghiệt với bạn—nhưng không phải không thể.”',
      id: '“Hari belanja nol kejam untukmu—tapi bukan mustahil.”',
    }),
    description: T({
      ko: '소비가 일상의 스트레스 해소·감정 조절 수단으로 깊이 연결된 상태입니다. 무지출 챌린지를 시도할 때마다 오전에 무너지거나 예외를 자꾸 만드는 패턴이 반복됩니다. 단순히 의지력 문제가 아니라 소비 패턴 자체를 바꾸는 작업이 먼저 필요합니다. 지금 당장 무지출보다 소비 기록부터 시작하는 것을 추천합니다.',
      en: 'Spending is tightly wired to stress relief and mood. Each zero-spend attempt may collapse in the morning or sprout “exceptions.” It’s not just willpower—you need to reshape the habit loop. Before another zero-spend push, start by tracking every purchase for two weeks.',
      ja: '支出がストレス発散や感情調整と深く結びついている。無支出に挑むたび午前に崩れたり例外だらけになる。意志力だけの問題ではなく、習慣そのものを変える必要がある。まずは2週間の支出記録から。',
      zhCN: '消费与减压、调节情绪深度绑定。每次零消费容易上午就破或不断例外。不只是意志力，要先重塑消费习惯。建议先记两周账再谈零消费。',
      zhTW: '消費與減壓、調節情緒深度綁定。每次零消費容易上午就破或不斷例外。不只是意志力，要先重塑消費習慣。建議先記兩週帳再談零消費。',
      vi: 'Chi tiêu gắn chặt xả stress và cảm xúc. Mỗi lần thử chi 0 dễ gãy sáng hoặc đầy ngoại lệ. Không chỉ ý chí—cần đổi vòng thói quen. Trước khi thử lại, hãy ghi chép chi tiêu 2 tuần.',
      id: 'Belanja terikat erat dengan stres dan suasana hati. Tiap percobaan nol sering runtuh pagi atau penuh pengecualian. Bukan sekadar tekad—perlu ubah pola kebiasaan. Sebelum coba lagi, catat semua pengeluaran selama 2 minggu.',
    }),
    detailSectionTitle: T({
      ko: '성공률 인사이트',
      en: 'Success-rate insights',
      ja: '成功率インサイト',
      zhCN: '成功率洞察',
      zhTW: '成功率洞察',
      vi: 'Góc nhìn tỷ lệ thành công',
      id: 'Wawasan tingkat keberhasilan',
    }),
    detailBullets: T({
      ko: '성공 확률: 15~25% 🟥□□□□\n실패 가능성: 75~85% (소비가 감정·습관과 깊이 연결된 상태)\n가장 위험한 순간: 사실상 모든 순간. 특히 스트레스·지루함·배고픔 3가지 동시 발생 시\n성공 비결: 무지출 챌린지 전 2주간 지출 기록 → 패턴 파악이 먼저\n오늘 할 일: 가계부 앱 설치 → 오늘 지출 기록 시작하기 (무지출은 다음 단계)',
      en: 'Odds: 15–25% 🟥□□□□\nFailure risk: 75–85% (spending fused with emotion/habit)\nRiskiest: basically always—especially stress + boredom + hunger together\nSecret: log spending 2 weeks before another zero-spend attempt\nToday: install a budget app and log today’s spending (zero-spend comes later)',
      ja: '成功率：15〜25% 🟥□□□□\n失敗リスク：75〜85%（感情・習慣と結びついた支出）\n最危険：常に—特にストレス+退屈+空腹が重なる時\n秘訣：再挑戦前に2週間の記録\n今日：家計簿アプリを入れて今日から記録（無支出は次の段階）',
      zhCN: '概率：15~25% 🟥□□□□\n失败可能：75~85%（消费与情绪/习惯深度绑定）\n最险：几乎随时—尤其压力+无聊+饿同时\n秘诀：再挑战前先记两周账\n今日：装记账App，从记录今天开始（零消费下一步）',
      zhTW: '機率：15~25% 🟥□□□□\n失敗可能：75~85%（消費與情緒/習慣深度綁定）\n最險：幾乎隨時—尤其壓力+無聊+餓同時\n秘訣：再挑戰前先記兩週帳\n今日：裝記帳App，從記錄今天開始（零消費下一步）',
      vi: 'Tỷ lệ: 15–25% 🟥□□□□\nRủi ro: 75–85% (chi tiêu dính cảm xúc/thói quen)\nRủi ro nhất: gần như lúc nào—nhất là stress + chán + đói cùng lúc\nBí quyết: ghi chép 2 tuần trước khi thử lại\nHôm nay: cài app ngân sách, ghi chi tiêu hôm nay (chi 0 để sau)',
      id: 'Peluang: 15–25% 🟥□□□□\nRisiko: 75–85% (belanja melekat emosi/kebiasaan)\nPaling riskan: hampir kapan saja—terutama stres + bosan + lapar bareng\nRahasia: catat 2 minggu sebelum coba lagi\nHari ini: pasang app keuangan, catat hari ini (nol penuh belakangan)',
    }),
    prescriptionSteps: T({
      ko: '무지출 전에 기록이 먼저\n오늘 지출한 것 전부 기록하기 → 2주 후 패턴 파악 → 그때 무지출 챌린지 도전\n기록만으로 지출이 20~30% 줄어드는 경우가 많습니다',
      en: 'Tracking before zero-spend\nLog everything you spend today → read patterns after 2 weeks → then retry zero-spend\nMany people naturally cut 20–30% just by logging',
      ja: '無支出より先に記録\n今日の支出を全部記録→2週間で傾向把握→その後に無支出へ\n記録だけで20〜30%減ることも多い',
      zhCN: '先记录再零消费\n记录今天所有支出→两周后看清模式→再挑战零消费\n很多人只记账就能少花20~30%',
      zhTW: '先記錄再零消費\n記錄今天所有支出→兩週後看清模式→再挑戰零消費\n很多人只記帳就能少花20~30%',
      vi: 'Ghi chép trước, chi 0 sau\nGhi hết hôm nay → sau 2 tuần đọc mẫu → rồi thử lại chi 0\nNhiều người chỉ ghi đã giảm 20–30%',
      id: 'Catat dulu, nol belakangan\nCatat semua hari ini → setelah 2 minggu lihat pola → coba nol lagi\nBanyak orang cuma catat sudah turun 20–30%',
    }),
    savingsEstimate: T({
      ko: '지출 기록만으로 평소 대비 20~30% 자연 감소 효과',
      en: 'Logging alone often trims typical spending ~20–30%',
      ja: '記録だけで普段比20〜30%減ることが多い',
      zhCN: '仅记账也常能自然少花20~30%',
      zhTW: '僅記帳也常能自然少花20~30%',
      vi: 'Chỉ ghi chép cũng thường giảm ~20–30% chi tiêu',
      id: 'Sekadar mencatat sering memangkas ~20–30% pengeluaran',
    }),
    yearlyApply: T({
      ko: '지출 기록 습관화 → 연간 50~100만 원 절약 가능 (무지출보다 효과적일 수 있음)',
      en: 'Habitual tracking → ~₩500k–1M/year saved (sometimes beats strict zero-spend days)',
      ja: '記録の習慣化→年間約50〜100万ウォン（無支出より効くことも）',
      zhCN: '养成记账习惯→年省约 50~100 万韩元（有时比硬零消费更有效）',
      zhTW: '養成記帳習慣→年省約 50~100 萬韓元（有時比硬零消費更有效）',
      vi: 'Thói quen ghi chép → ~₩500k–1M/năm (đôi khi hiệu quả hơn ngày 0 đồng cứng)',
      id: 'Kebiasaan catat → ~₩500rb–1jt/tahun (kadang lebih jitu dari nol keras)',
    }),
    todayTask: T({
      ko: '가계부 앱 하나 설치하고 오늘 쓴 금액만이라도 모두 적어 보세요.',
      en: 'Install any budget app and write down every spend from today—even tiny ones.',
      ja: '家計簿アプリを入れて、今日使った金額を小さくても全部メモ。',
      zhCN: '装一个记账App，把今天花的哪怕再少也全记下。',
      zhTW: '裝一個記帳App，把今天花的哪怕再少也全記下。',
      vi: 'Cài một app ngân sách và ghi mọi khoản hôm nay—dù nhỏ.',
      id: 'Pasang app keuangan dan tulis semua pengeluaran hari ini—sekecil apa pun.',
    }),
    motivationLine: T({
      ko: '"기록이 먼저입니다. 자신의 소비 패턴을 아는 것이 챌린지 성공의 시작입니다"',
      en: '"Logging comes first—knowing your pattern is step one to winning the challenge."',
      ja: '「記録が先。自分のパターンを知ることが成功のスタート。」',
      zhCN: '“先记账。了解自己的模式才是挑战成功的起点。”',
      zhTW: '「先記帳。了解自己的模式才是挑戰成功的起點。」',
      vi: '“Ghi chép trước—hiểu mô hình chi tiêu của bạn là bước đầu để thắng.”',
      id: '“Catat dulu—mengenal pola belanjamu adalah langkah pertama menang.”',
    }),
    shareLine: T({
      ko: '무지출 챌린지 성공 확률 20% 🔴 솔직히 나한테 너무 가혹한 챌린지... 공감 폭발 → 너는 몇 %야?',
      en: 'My zero-spend odds: 20% 🔴 Way too brutal for me—who relates? What’s your %?',
      ja: '無支出成功率20% 🔴正直きつすぎ…共感したらいいね → あなたは何%？',
      zhCN: '零消费成功率 20% 🔴 对我太狠了…有同感的吗 → 你多少 %？',
      zhTW: '零消費成功率 20% 🔴 對我太狠了…有同感的嗎 → 你多少 %？',
      vi: 'Tỷ lệ chi 0: 20% 🔴 Quá khắc với mình… ai đồng cảm? Bạn bao nhiêu %?',
      id: 'Peluang nol-ku: 20% 🔴 Kejam banget buatku… relate? Kamu berapa %?',
    }),
  },
  {
    type: 'Type6',
    emoji: '⚫',
    title: T({
      ko: '무지출보다 먼저 할 게 있는, 성공 확률 5% 이하',
      en: 'Fix spending structure first — under ~5% odds',
      ja: '無支出より先にやることがある、成功率5%以下',
      zhCN: '有比零消费更该先做的，成功率 ≤5%',
      zhTW: '有比零消費更該先做的，成功率 ≤5%',
      vi: 'Còn việc quan trọng hơn chi 0 đồng — dưới ~5%',
      id: 'Ada yang lebih dulu dari nol—peluang di bawah ~5%',
    }),
    successRateLine: T({
      ko: '무지출 챌린지 성공 확률: 5% 이하',
      en: 'Zero-spend success odds: ~5% or less',
      ja: '無支出成功率：5%以下',
      zhCN: '零消费成功率：≤5%',
      zhTW: '零消費成功率：≤5%',
      vi: 'Xác suất chi 0 đồng: ~5% trở xuống',
      id: 'Peluang belanja nol: ~5% atau kurang',
    }),
    hookLine: T({
      ko: '"당신에게 지금 무지출 챌린지는 적절한 도전이 아닙니다."',
      en: '"A zero-spend challenge isn’t the right fight for you—yet."',
      ja: '「今のあなたには無支出チャレンジは適切な挑戦ではない。」',
      zhCN: '“现在的你还不适合把零消费当主战场。”',
      zhTW: '「現在的你還不適合把零消費當主戰場。」',
      vi: '“Thử thách chi 0 đồng chưa phải trận đánh đúng với bạn—chưa.”',
      id: '“Tantangan belanja nol belum pertarungan yang tepat untukmu—belum.”',
    }),
    description: T({
      ko: '현재 소비 패턴은 계획·의지와 거의 무관하게 자동화된 상태입니다. 무지출 챌린지를 시도해도 오전을 버티기 어렵고, 매번 같은 지점에서 무너지는 패턴이 반복되고 있을 가능성이 높습니다. 이 상태에서 무지출 챌린지는 오히려 실패 경험만 쌓아서 자존감을 떨어뜨릴 수 있습니다. 지금 당장 필요한 것은 무지출이 아니라 소비 구조 재설계입니다.',
      en: 'Spending runs on autopilot—barely connected to plans or willpower. Zero-spend attempts may fail before noon, repeating the same break point. Piling on “failed” zero days can hurt self-esteem. What you need now isn’t a harsh zero day—it’s redesigning where money leaks: cards, subscriptions, autopay.',
      ja: '支出はほぼ自動運転で、計画や意志と結びついていない。無支出は午前に崩れ、同じポイントで繰り返し失敗する可能性。失敗の積み重ねは自尊心を下げる。今必要なのはゼロ日より、カード・サブスク・自動引き落としの再設計。',
      zhCN: '消费几乎自动驾驶，与计划、意志脱节。零消费可能上午就破，总在同一处崩盘。硬扛零消费只会堆失败伤自尊。现在更需要重构支出：卡账、订阅、自动扣款。',
      zhTW: '消費幾乎自動駕駛，與計畫、意志脫節。零消費可能上午就破，總在同一處崩盤。硬扛零消費只會堆失敗傷自尊。現在更需要重構支出：卡帳、訂閱、自動扣款。',
      vi: 'Chi tiêu gần như tự động—không gắn kế hoạch hay ý chí. Thử chi 0 có thể gãy trước trưa, lặp lại cùng điểm vỡ. Chồng thất bại làm tổn thương lòng tự trọng. Giờ cần thiết kế lại tiền rò: thẻ, gói đăng ký, trừ tiền tự động.',
      id: 'Belanja hampir autopilot—jarang terhubung rencana/tekad. Percobaan nol bisa gagal sebelum siang, berulang di titik sama. Menumpuk kegagalan bisa merusak harga diri. Yang dibutuhkan sekarang merancang ulang kebocoran: kartu, langganan, debit otomatis.',
    }),
    detailSectionTitle: T({
      ko: '성공률 인사이트',
      en: 'Success-rate insights',
      ja: '成功率インサイト',
      zhCN: '成功率洞察',
      zhTW: '成功率洞察',
      vi: 'Góc nhìn tỷ lệ thành công',
      id: 'Wawasan tingkat keberhasilan',
    }),
    detailBullets: T({
      ko: '성공 확률: 5% 이하 ⬛□□□□\n실패 가능성: 95% 이상 (소비 패턴 자동화 + 의지력 소진 상태)\n가장 위험한 순간: 사실상 챌린지 시작 직후부터\n성공 비결: 지금은 무지출보다 지출 구조 파악이 먼저\n오늘 할 일: ① 이번 달 카드·페이 명세서 전체 확인 ② 쓸데없는 자동결제 하나만 해지하기',
      en: 'Odds: ~5% or less ⬛□□□□\nFailure risk: 95%+ (autopilot spending + depleted willpower)\nRiskiest: basically right after you start\nSecret: map spending structure before chasing zero\nToday: ① scan this month’s card/pay statements ② cancel one useless subscription/autopay',
      ja: '成功率：5%以下 ⬛□□□□\n失敗リスク：95%超（自動支出+枯れた意志）\n最危険：始めてすぐから\n秘訣：ゼロより支出構造の把握\n今日：①今月のカード・ペイ明細を見る ②不要な自動課金を1つ解約',
      zhCN: '概率：≤5% ⬛□□□□\n失败可能：95%+（消费自动驾驶+意志耗尽）\n最险：几乎一开始\n秘诀：先摸清支出结构再谈零消费\n今日：①查看本月卡/支付账单 ②取消一笔无用自动扣款/订阅',
      zhTW: '機率：≤5% ⬛□□□□\n失敗可能：95%+（消費自動駕駛+意志耗盡）\n最險：幾乎一開始\n秘訣：先摸清支出結構再談零消費\n今日：①查看本月卡/支付帳單 ②取消一筆無用自動扣款/訂閱',
      vi: 'Tỷ lệ: ~5% trở xuống ⬛□□□□\nRủi ro: 95%+ (chi tự động + ý chí cạn)\nNguy hiểm nhất: gần như ngay sau khi bắt đầu\nBí quyết: bản đồ cấu trúc chi trước khi săn số 0\nHôm nay: ① xem sao kê thẻ/pay tháng này ② hủy một gói tự động không cần',
      id: 'Peluang: ~5% atau kurang ⬛□□□□\nRisiko: 95%+ (belanja autopilot + tekad habis)\nPaling riskan: hampir segera setelah mulai\nRahasia: peta struktur pengeluaran sebelum kejar nol\nHari ini: ① cek rekening kartu/pay bulan ini ② batalkan satu langganan/autopay tidak perlu',
    }),
    prescriptionSteps: T({
      ko: '무지출 전에 기록이 먼저 (25% 이하 구간 권장)\n오늘 지출 전부 기록 → 2주 패턴 파악 후 무지출 재도전\n구독·자동결제 정리만으로도 월 수만~십만 원 절약이 흔합니다',
      en: 'Track before zero (recommended if odds ≤25%)\nLog all spending today → read patterns in 2 weeks → retry zero-spend\nTrimming subs/autopay alone often saves tens of thousands of KRW monthly',
      ja: '無支出より記録（25%以下帯は特に）\n今日を全部記録→2週間で傾向→再挑戦\nサブスク整理だけで月数万〜十万ウォンは珍しくない',
      zhCN: '先记录再零消费（概率≤25%者尤甚）\n记录今天全部→两周后看清模式→再挑战\n只整理订阅/自动扣款，每月常能省几万到十万韩元',
      zhTW: '先記錄再零消費（機率≤25%者尤甚）\n記錄今天全部→兩週後看清模式→再挑戰\n只整理訂閱/自動扣款，每月常能省幾萬到十萬韓元',
      vi: 'Ghi trước, chi 0 sau (khuyến nghị nếu tỷ lệ ≤25%)\nGhi hết hôm nay → sau 2 tuần đọc mẫu → thử lại\nChỉ gỡ gói/tự động trừ tiền đã thường tiết kiệm hàng chục nghìn won/tháng',
      id: 'Catat dulu (disarankan jika peluang ≤25%)\nCatat semua hari ini → pola 2 minggu → coba nol lagi\nHanya rapikan langganan/autopay sering hemat puluhan ribu won/bulan',
    }),
    savingsEstimate: T({
      ko: '자동결제 정리만으로 월 3~10만 원 절약 즉시 가능',
      en: 'Canceling stray autopays alone can free ~₩30k–100k/month',
      ja: '不要な自動課金整理だけで月3〜10万ウォンは珍しくない',
      zhCN: '只清理多余自动扣款，每月常能立刻省下约3~10万韩元',
      zhTW: '只清理多餘自動扣款，每月常能立刻省下約3~10萬韓元',
      vi: 'Gỡ thanh toán tự động thừa có thể tiết kiệm ~₩30k–100k/tháng',
      id: 'Bersihkan autopay ngawur bisa hemat ~₩30rb–100rb/bulan',
    }),
    yearlyApply: T({
      ko: '소비 구조 재설계 → 연간 100만 원 이상 절약 가능 (무지출보다 훨씬 효과적일 수 있음)',
      en: 'Restructuring spending → often ₩1M+/year saved (can beat rigid zero days)',
      ja: '支出構造の再設計→年100万ウォン超も（無支出より効くことも）',
      zhCN: '重构消费结构→年省常超100万韩元（有时比硬零消费更有效）',
      zhTW: '重構消費結構→年省常超100萬韓元（有時比硬零消費更有效）',
      vi: 'Tái cấu trúc chi tiêu → thường >₩1M/năm (đôi khi hơn ngày 0 cứng)',
      id: 'Restruktur belanja → sering >₩1jt/tahun (kadang lebih jitu dari nol keras)',
    }),
    todayTask: T({
      ko: '이번 달 명세서를 펼쳐 보고 자동결제·구독 한 개만 끊을 후보를 고르세요.',
      en: 'Open this month’s statements and pick one subscription or autopay to cancel.',
      ja: '今月の明細を開き、解約候補のサブスクか自動課金を1つ選ぶ。',
      zhCN: '打开本月对账单，挑一个订阅或自动扣款准备取消。',
      zhTW: '打開本月對帳單，挑一個訂閱或自動扣款準備取消。',
      vi: 'Mở sao kê tháng này và chọn một gói đăng ký hoặc autopay để hủy.',
      id: 'Buka mutasi bulan ini dan pilih satu langganan atau autopay untuk dibatalkan.',
    }),
    motivationLine: T({
      ko: '"무지출 챌린지보다 구독 서비스 하나 끊는 게 지금 당신에게 더 현실적인 재테크입니다"',
      en: '"Canceling one subscription is more realistic wealth-care for you right now than a zero day."',
      ja: '「無支出より、サブスクを一つ解約する方が今のあなたには現実的な家計改善。」',
      zhCN: '“现在对你来说，取消一个订阅比硬扛零消费更现实的理财。”',
      zhTW: '「現在對你來說，取消一個訂閱比硬扛零消費更現實的理財。」',
      vi: '“Hủy một gói đăng ký thực tế hơn với bạn lúc này so với ngày chi 0.”',
      id: '“Membatalkan satu langganan lebih realistis untukmu sekarang daripada hari nol.”',
    }),
    shareLine: T({
      ko: '무지출 챌린지 성공 확률 5% ⚫ 솔직해서 믿음이 가는 결과 ㅋㅋ 나 무지출보다 먼저 할 게 있대 → 너는 몇 %야?',
      en: 'My zero-spend odds: ~5% ⚫ Brutally honest—I’m told to fix subs before zero days → what’s your %?',
      ja: '無支出成功率5% ⚫正直すぎて笑える。先にサブスク整理しろって → あなたは何%？',
      zhCN: '零消费成功率 ~5% ⚫ 太诚实了…说要先搞订阅再谈零花 → 你多少 %？',
      zhTW: '零消費成功率 ~5% ⚫ 太誠實了…說要先搞訂閱再談零花 → 你多少 %？',
      vi: 'Tỷ lệ chi 0: ~5% ⚫ Thật quá—bảo sửa gói trước đã → bạn bao nhiêu %?',
      id: 'Peluang nol: ~5% ⚫ Jujur banget—suruh beresin langganan dulu → kamu berapa %?',
    }),
  },
];
