/**
 * 나의 '자아 성벽' 두께 — 12문항 이미지 2지선다, A=0 B=1, 총점 0~12 → 6유형
 * 썸네일: p3_test_ego_wall_thickness.webp
 * 답변 이미지: p3_test_ego_wall_thickness_q{n}a~b.webp (12×2=24장)
 */

type Locale = "ko" | "en" | "ja" | "zh-CN" | "zh-TW" | "vi" | "id";
type ML = Record<Locale, string>;

function L(m: ML): Record<string, string> {
  return m;
}

const IMG = (n: number, choice: "a" | "b") =>
  `p3_test_ego_wall_thickness_q${n}${choice}.webp`;

export interface Phase3EgoWallThicknessQuestion {
  id: number;
  question: Record<string, string>;
  options: { image: string; label: Record<string, string>; score: number }[];
}

export interface Phase3EgoWallThicknessResult {
  type: string;
  emoji: string;
  title: Record<string, string>;
  shortDescription: Record<string, string>;
  description: Record<string, string>;
  wallThickness: Record<string, string>;
  strength: Record<string, string>;
  shadow: Record<string, string>;
  needNow: Record<string, string>;
  shiningMoment: Record<string, string>;
  oneLiner?: Record<string, string>;
  shareMessage: Record<string, string>;
}

export function calculatePhase3EgoWallThicknessResult(scores: number[]): string {
  const total = scores.reduce((a, b) => a + (b ?? 0), 0);
  if (total <= 1) return "Type1";
  if (total <= 3) return "Type2";
  if (total <= 6) return "Type3";
  if (total <= 9) return "Type4";
  if (total <= 11) return "Type5";
  return "Type6";
}

export const phase3EgoWallThicknessQuestions: Phase3EgoWallThicknessQuestion[] = [
  {
    id: 1,
    question: L({
      ko: "두 가지 공간 중 지금 내가 있고 싶은 곳은?",
      en: "Which of these two spaces would you rather be in right now?",
      ja: "二つの空間のうち、今いたい場所はどっち？",
      "zh-CN": "两种空间中，你现在更想待在哪里？",
      "zh-TW": "兩種空間中，你現在更想待在哪裡？",
      vi: "Trong hai không gian này, bạn muốn ở đâu ngay bây giờ?",
      id: "Di antara dua ruang ini, di mana kamu ingin berada sekarang?",
    }),
    options: [
      {
        image: IMG(1, "a"),
        label: L({
          ko: "통유리 창이 열려있고 햇살이 가득 들어오는 탁 트인 공간",
          en: "An open space with floor-to-ceiling windows letting in plenty of sunlight",
          ja: "全面ガラス窓が開いていて、陽射しがたっぷり入る開放的な空間",
          "zh-CN": "落地玻璃窗敞开、阳光洒满的开阔空间",
          "zh-TW": "落地玻璃窗敞開、陽光灑滿的開闊空間",
          vi: "Không gian rộng mở với cửa sổ kính lớn và ánh nắng tràn ngập",
          id: "Ruang terbuka dengan jendela kaca besar yang membiarkan sinar matahari masuk",
        }),
        score: 0,
      },
      {
        image: IMG(1, "b"),
        label: L({
          ko: "두꺼운 커튼이 쳐진 아늑하고 외부와 단절된 아늑한 공간",
          en: "A cozy space with thick curtains drawn, cut off from the outside world",
          ja: "厚いカーテンが閉められた、外部から切り離された居心地の良い空間",
          "zh-CN": "拉着厚厚窗帘、与外界隔绝的舒适空间",
          "zh-TW": "拉著厚厚窗簾、與外界隔絕的舒適空間",
          vi: "Không gian ấm cúng với rèm cửa dày, tách biệt hoàn toàn với bên ngoài",
          id: "Ruang nyaman dengan gorden tebal yang tertutup, terpisah dari dunia luar",
        }),
        score: 1,
      },
    ],
  },
  {
    id: 2,
    question: L({
      ko: "두 가지 문 중 더 끌리는 것은?",
      en: "Which of these two doors appeals to you more?",
      ja: "二つのドアのうち、より惹かれるのはどっち？",
      "zh-CN": "两种门中，你更喜欢哪一种？",
      "zh-TW": "兩種門中，你更喜歡哪一種？",
      vi: "Trong hai loại cửa này, bạn thích cái nào hơn?",
      id: "Di antara dua pintu ini, mana yang lebih menarik bagimu?",
    }),
    options: [
      {
        image: IMG(2, "a"),
        label: L({
          ko: "유리로 만들어진 투명한 문. 안팎이 다 보이는 문",
          en: "A transparent glass door. You can see both inside and outside",
          ja: "ガラスで作られた透明なドア。内も外も丸見えのドア",
          "zh-CN": "由玻璃制成的透明门，里外都能看得一清二楚",
          "zh-TW": "由玻璃製成的透明門，裡外都能看得一清二楚",
          vi: "Cửa kính trong suốt, có thể nhìn thấy cả bên trong và bên ngoài",
          id: "Pintu kaca transparan. Bagian dalam dan luar bisa terlihat jelas",
        }),
        score: 0,
      },
      {
        image: IMG(2, "b"),
        label: L({
          ko: "두꺼운 나무로 만들어진 자물쇠가 달린 묵직한 문",
          en: "A heavy door made of thick wood with a lock attached",
          ja: "厚い木で作られた、鍵がついた重厚なドア",
          "zh-CN": "由厚重木材制成、装有锁的沉重大门",
          "zh-TW": "由厚重木材製成、裝有鎖的沉重大門",
          vi: "Cửa gỗ dày, nặng nề, có gắn khóa",
          id: "Pintu berat dari kayu tebal yang dilengkapi gembok",
        }),
        score: 1,
      },
    ],
  },
  {
    id: 3,
    question: L({
      ko: "두 가지 식물 중 나에게 더 가깝다고 느껴지는 것은?",
      en: "Which of these two plants feels closer to who you are?",
      ja: "二つの植物のうち、自分に近いと感じるのはどっち？",
      "zh-CN": "两种植物中，你觉得哪个更贴近自己？",
      "zh-TW": "兩種植物中，你覺得哪個更貼近自己？",
      vi: "Trong hai loại cây này, bạn cảm thấy cái nào giống mình hơn?",
      id: "Di antara dua tanaman ini, mana yang terasa lebih mirip denganmu?",
    }),
    options: [
      {
        image: IMG(3, "a"),
        label: L({
          ko: "활짝 꽃을 피운 해바라기. 태양을 향해 완전히 열린 꽃",
          en: "A sunflower in full bloom, completely open toward the sun",
          ja: "満開に咲いたひまわり。太陽に向かって完全に開いた花",
          "zh-CN": "盛开的向日葵，完全朝着太阳绽放的花",
          "zh-TW": "盛開的向日葵，完全朝著太陽綻放的花",
          vi: "Hoa hướng dương nở rộ, hoàn toàn hướng về phía mặt trời",
          id: "Bunga matahari yang mekar penuh, terbuka sepenuhnya menghadap matahari",
        }),
        score: 0,
      },
      {
        image: IMG(3, "b"),
        label: L({
          ko: "날카로운 가시로 덮인 선인장. 건드리면 아프지만 강한 식물",
          en: "A cactus covered in sharp thorns — painful to touch but strong",
          ja: "鋭いトゲに覆われたサボテン。触れると痛いが強い植物",
          "zh-CN": "布满尖刺的仙人掌，碰到会痛但很坚强的植物",
          "zh-TW": "布滿尖刺的仙人掌，碰到會痛但很堅強的植物",
          vi: "Cây xương rồng đầy gai nhọn, đụng vào sẽ đau nhưng rất mạnh mẽ",
          id: "Kaktus berduri tajam, menyakitkan jika disentuh tapi kuat",
        }),
        score: 1,
      },
    ],
  },
  {
    id: 4,
    question: L({
      ko: "두 가지 이미지 중 더 끌리는 것은?",
      en: "Which of these two images appeals to you more?",
      ja: "二つのイメージのうち、より惹かれるのはどっち？",
      "zh-CN": "两张图片中，你更喜欢哪一个？",
      "zh-TW": "兩張圖片中，你更喜歡哪一個？",
      vi: "Trong hai hình ảnh này, bạn thích cái nào hơn?",
      id: "Di antara dua gambar ini, mana yang lebih menarik bagimu?",
    }),
    options: [
      {
        image: IMG(4, "a"),
        label: L({
          ko: "맑고 투명한 호수. 바닥까지 다 보이는 잔잔한 물",
          en: "A clear, transparent lake — calm water you can see all the way to the bottom",
          ja: "澄んで透明な湖。底まで見える静かな水",
          "zh-CN": "清澈透明的湖泊，能看到湖底的平静水面",
          "zh-TW": "清澈透明的湖泊，能看到湖底的平靜水面",
          vi: "Hồ nước trong suốt, tĩnh lặng, có thể nhìn thấy đến tận đáy",
          id: "Danau yang jernih dan transparan, air tenang yang terlihat sampai ke dasar",
        }),
        score: 0,
      },
      {
        image: IMG(4, "b"),
        label: L({
          ko: "깊고 어두운 바다. 수면은 조용하지만 아래가 보이지 않는 물",
          en: "A deep, dark sea — calm on the surface but you can't see what's below",
          ja: "深く暗い海。水面は静かだが下は見えない水",
          "zh-CN": "深邃黑暗的海洋，表面平静但看不见水下的世界",
          "zh-TW": "深邃黑暗的海洋，表面平靜但看不見水下的世界",
          vi: "Biển sâu và tối, mặt nước yên tĩnh nhưng không thể thấy phía dưới",
          id: "Laut yang dalam dan gelap, permukaannya tenang tapi bagian bawahnya tak terlihat",
        }),
        score: 1,
      },
    ],
  },
  {
    id: 5,
    question: L({
      ko: "두 가지 집 중 더 살고 싶은 곳은?",
      en: "Which of these two houses would you rather live in?",
      ja: "二つの家のうち、より住みたいのはどっち？",
      "zh-CN": "两种房子中，你更想住在哪一种？",
      "zh-TW": "兩種房子中，你更想住在哪一種？",
      vi: "Trong hai căn nhà này, bạn muốn sống ở đâu hơn?",
      id: "Di antara dua rumah ini, di mana kamu lebih ingin tinggal?",
    }),
    options: [
      {
        image: IMG(5, "a"),
        label: L({
          ko: "사방이 통유리인 집. 풍경이 다 보이고 외부와 연결된 집",
          en: "A house with floor-to-ceiling windows on every side — full view of the scenery and connected to the outside",
          ja: "四方が全面ガラスの家。景色が全部見えて外とつながっている家",
          "zh-CN": "四面都是落地玻璃的房子，风景一览无遗，与外界相连",
          "zh-TW": "四面都是落地玻璃的房子，風景一覽無遺，與外界相連",
          vi: "Ngôi nhà có cửa kính lớn ở mọi phía, nhìn thấy toàn cảnh và kết nối với bên ngoài",
          id: "Rumah dengan jendela kaca besar di semua sisi, pemandangan terlihat penuh dan terhubung dengan luar",
        }),
        score: 0,
      },
      {
        image: IMG(5, "b"),
        label: L({
          ko: "높은 담장으로 둘러싸인 집. 외부에서 안이 전혀 보이지 않는 집",
          en: "A house surrounded by high walls — completely invisible from the outside",
          ja: "高い塀に囲まれた家。外から中が全く見えない家",
          "zh-CN": "被高墙环绕的房子，外面完全看不到里面",
          "zh-TW": "被高牆環繞的房子，外面完全看不到裡面",
          vi: "Ngôi nhà được bao quanh bởi tường cao, bên ngoài hoàn toàn không thấy được bên trong",
          id: "Rumah yang dikelilingi tembok tinggi, sama sekali tidak terlihat dari luar",
        }),
        score: 1,
      },
    ],
  },
  {
    id: 6,
    question: L({
      ko: "두 가지 날씨 중 지금 내 마음 상태에 더 가까운 것은?",
      en: "Which of these two kinds of weather feels closer to your current state of mind?",
      ja: "二つの天気のうち、今の自分の心の状態に近いのはどっち？",
      "zh-CN": "两种天气中，哪一种更接近你现在的心境？",
      "zh-TW": "兩種天氣中，哪一種更接近你現在的心境？",
      vi: "Trong hai kiểu thời tiết này, cái nào gần với trạng thái tâm lý hiện tại của bạn hơn?",
      id: "Di antara dua jenis cuaca ini, mana yang lebih dekat dengan kondisi hatimu sekarang?",
    }),
    options: [
      {
        image: IMG(6, "a"),
        label: L({
          ko: "구름 한 점 없이 맑은 파란 하늘",
          en: "A clear blue sky without a single cloud",
          ja: "雲一つない晴れた青空",
          "zh-CN": "万里无云的晴朗蓝天",
          "zh-TW": "萬里無雲的晴朗藍天",
          vi: "Bầu trời xanh trong không một gợn mây",
          id: "Langit biru cerah tanpa awan sedikit pun",
        }),
        score: 0,
      },
      {
        image: IMG(6, "b"),
        label: L({
          ko: "안개가 자욱하게 낀 회색 하늘",
          en: "A gray sky thick with fog",
          ja: "霧が濃く立ち込めた灰色の空",
          "zh-CN": "被浓雾笼罩的灰色天空",
          "zh-TW": "被濃霧籠罩的灰色天空",
          vi: "Bầu trời xám mù mịt sương",
          id: "Langit kelabu yang diselimuti kabut tebal",
        }),
        score: 1,
      },
    ],
  },
  {
    id: 7,
    question: L({
      ko: "두 가지 껍질 중 더 끌리는 것은?",
      en: "Which of these two shells appeals to you more?",
      ja: "二つの殻のうち、より惹かれるのはどっち？",
      "zh-CN": "两种外壳中，你更喜欢哪一种？",
      "zh-TW": "兩種外殼中，你更喜歡哪一種？",
      vi: "Trong hai loại vỏ này, bạn thích cái nào hơn?",
      id: "Di antara dua jenis cangkang ini, mana yang lebih menarik bagimu?",
    }),
    options: [
      {
        image: IMG(7, "a"),
        label: L({
          ko: "부드럽고 얇은 꽃잎. 살짝만 건드려도 열리는 꽃봉오리",
          en: "A soft, thin petal — a bud that opens at the slightest touch",
          ja: "柔らかく薄い花びら。ちょっと触れるだけで開くつぼみ",
          "zh-CN": "柔软纤薄的花瓣，轻轻一碰就绽放的花蕾",
          "zh-TW": "柔軟纖薄的花瓣，輕輕一碰就綻放的花蕾",
          vi: "Cánh hoa mềm mỏng, chỉ cần chạm nhẹ là nụ hoa đã bung nở",
          id: "Kelopak bunga yang lembut dan tipis, kuncup yang terbuka hanya dengan sentuhan ringan",
        }),
        score: 0,
      },
      {
        image: IMG(7, "b"),
        label: L({
          ko: "단단하고 두꺼운 조개껍데기. 열려면 상당한 힘이 필요한 껍질",
          en: "A hard, thick seashell — takes considerable force to open",
          ja: "硬くて厚い貝殻。開けるにはかなりの力が必要な殻",
          "zh-CN": "坚硬厚重的贝壳，需要相当大的力气才能打开",
          "zh-TW": "堅硬厚重的貝殼，需要相當大的力氣才能打開",
          vi: "Vỏ sò cứng và dày, cần một lực khá lớn để mở ra",
          id: "Cangkang kerang yang keras dan tebal, butuh tenaga besar untuk membukanya",
        }),
        score: 1,
      },
    ],
  },
  {
    id: 8,
    question: L({
      ko: "두 가지 빛 중 더 끌리는 것은?",
      en: "Which of these two lights appeals to you more?",
      ja: "二つの光のうち、より惹かれるのはどっち？",
      "zh-CN": "两种光中，你更喜欢哪一种？",
      "zh-TW": "兩種光中，你更喜歡哪一種？",
      vi: "Trong hai loại ánh sáng này, bạn thích cái nào hơn?",
      id: "Di antara dua jenis cahaya ini, mana yang lebih menarik bagimu?",
    }),
    options: [
      {
        image: IMG(8, "a"),
        label: L({
          ko: "대낮의 강한 햇살. 모든 것이 선명하게 드러나는 빛",
          en: "Strong midday sunlight — light that reveals everything clearly",
          ja: "真昼の強い日差し。すべてが鮮明に見える光",
          "zh-CN": "正午强烈的阳光，让一切都清晰显现的光",
          "zh-TW": "正午強烈的陽光，讓一切都清晰顯現的光",
          vi: "Ánh nắng gay gắt giữa trưa, ánh sáng làm mọi thứ hiện rõ",
          id: "Sinar matahari terik di siang bolong, cahaya yang menampakkan segalanya dengan jelas",
        }),
        score: 0,
      },
      {
        image: IMG(8, "b"),
        label: L({
          ko: "새벽의 은은한 달빛. 모든 것이 부드럽게 가려지는 빛",
          en: "Gentle moonlight before dawn — light that softly conceals everything",
          ja: "夜明けのほのかな月光。すべてが柔らかく隠される光",
          "zh-CN": "凌晨柔和的月光，将一切温柔遮掩的光",
          "zh-TW": "凌晨柔和的月光，將一切溫柔遮掩的光",
          vi: "Ánh trăng dịu nhẹ lúc rạng đông, ánh sáng che phủ mọi thứ một cách êm ái",
          id: "Cahaya bulan lembut menjelang subuh, cahaya yang menyamarkan segalanya dengan halus",
        }),
        score: 1,
      },
    ],
  },
  {
    id: 9,
    question: L({
      ko: "두 가지 소재 중 내 마음과 더 닮은 것은?",
      en: "Which of these two materials feels more like your heart?",
      ja: "二つの素材のうち、自分の心とより似ているのはどっち？",
      "zh-CN": "两种材质中，哪个更像你的内心？",
      "zh-TW": "兩種材質中，哪個更像你的內心？",
      vi: "Trong hai loại vật liệu này, cái nào giống với tâm hồn bạn hơn?",
      id: "Di antara dua bahan ini, mana yang lebih menyerupai hatimu?",
    }),
    options: [
      {
        image: IMG(9, "a"),
        label: L({
          ko: "투명한 유리. 내부가 다 보이지만 깨지기 쉬운 소재",
          en: "Transparent glass — you can see everything inside, but it's fragile",
          ja: "透明なガラス。内部は全部見えるが割れやすい素材",
          "zh-CN": "透明的玻璃，内部一览无遗但容易破碎的材质",
          "zh-TW": "透明的玻璃，內部一覽無遺但容易破碎的材質",
          vi: "Kính trong suốt, có thể nhìn thấy bên trong nhưng dễ vỡ",
          id: "Kaca transparan, bagian dalamnya terlihat jelas tapi mudah pecah",
        }),
        score: 0,
      },
      {
        image: IMG(9, "b"),
        label: L({
          ko: "단단한 강철. 잘 깨지지 않지만 차갑고 무거운 소재",
          en: "Solid steel — hard to break, but cold and heavy",
          ja: "硬い鋼鉄。壊れにくいが冷たく重い素材",
          "zh-CN": "坚硬的钢铁，不易破碎但冰冷沉重的材质",
          "zh-TW": "堅硬的鋼鐵，不易破碎但冰冷沉重的材質",
          vi: "Thép cứng, khó vỡ nhưng lạnh lẽo và nặng nề",
          id: "Baja yang keras, tidak mudah pecah tapi dingin dan berat",
        }),
        score: 1,
      },
    ],
  },
  {
    id: 10,
    question: L({
      ko: "두 가지 풍경 중 더 끌리는 것은?",
      en: "Which of these two landscapes appeals to you more?",
      ja: "二つの風景のうち、より惹かれるのはどっち？",
      "zh-CN": "两种风景中，你更喜欢哪一种？",
      "zh-TW": "兩種風景中，你更喜歡哪一種？",
      vi: "Trong hai khung cảnh này, bạn thích cái nào hơn?",
      id: "Di antara dua pemandangan ini, mana yang lebih menarik bagimu?",
    }),
    options: [
      {
        image: IMG(10, "a"),
        label: L({
          ko: "끝까지 탁 트인 광활한 초원",
          en: "A vast, open grassland stretching as far as the eye can see",
          ja: "どこまでも開けた広大な草原",
          "zh-CN": "一望无际的开阔草原",
          "zh-TW": "一望無際的開闊草原",
          vi: "Cánh đồng cỏ rộng lớn, thoáng đãng đến tận cuối chân trời",
          id: "Padang rumput luas yang terbuka sejauh mata memandang",
        }),
        score: 0,
      },
      {
        image: IMG(10, "b"),
        label: L({
          ko: "울창한 숲 속 깊은 곳의 작은 공터",
          en: "A small clearing deep within a dense forest",
          ja: "鬱蒼とした森の奥深くにある小さな空き地",
          "zh-CN": "茂密森林深处的一片小空地",
          "zh-TW": "茂密森林深處的一片小空地",
          vi: "Một khoảng đất trống nhỏ sâu trong rừng rậm",
          id: "Sebidang tanah kosong kecil di kedalaman hutan lebat",
        }),
        score: 1,
      },
    ],
  },
  {
    id: 11,
    question: L({
      ko: "두 가지 이미지 중 더 끌리는 것은?",
      en: "Which of these two images appeals to you more?",
      ja: "二つのイメージのうち、より惹かれるのはどっち？",
      "zh-CN": "两张图片中，你更喜欢哪一个？",
      "zh-TW": "兩張圖片中，你更喜歡哪一個？",
      vi: "Trong hai hình ảnh này, bạn thích cái nào hơn?",
      id: "Di antara dua gambar ini, mana yang lebih menarik bagimu?",
    }),
    options: [
      {
        image: IMG(11, "a"),
        label: L({
          ko: "완전히 녹아 흐르는 촛불 왁스. 형태를 잃을 만큼 부드러운 것",
          en: "Fully melted candle wax, flowing and so soft it loses its shape",
          ja: "完全に溶けて流れるキャンドルワックス。形を失うほど柔らかいもの",
          "zh-CN": "完全融化流动的蜡烛蜡，柔软到失去形状的东西",
          "zh-TW": "完全融化流動的蠟燭蠟，柔軟到失去形狀的東西",
          vi: "Sáp nến tan chảy hoàn toàn, mềm đến mức mất hết hình dạng",
          id: "Lilin yang mencair sepenuhnya, begitu lembut hingga kehilangan bentuknya",
        }),
        score: 0,
      },
      {
        image: IMG(11, "b"),
        label: L({
          ko: "용암이 식어서 굳은 현무암. 한번 굳으면 웬만해서는 변하지 않는 것",
          en: "Basalt formed from cooled, hardened lava — once set, it rarely changes",
          ja: "溶岩が冷えて固まった玄武岩。一度固まるとなかなか変わらないもの",
          "zh-CN": "熔岩冷却凝固的玄武岩，一旦凝固就很难再改变的东西",
          "zh-TW": "熔岩冷卻凝固的玄武岩，一旦凝固就很難再改變的東西",
          vi: "Đá bazan hình thành từ dung nham nguội và cứng lại, khi đã cứng thì khó mà thay đổi",
          id: "Batu basalt yang terbentuk dari lava yang mendingin dan mengeras, begitu mengeras jarang berubah",
        }),
        score: 1,
      },
    ],
  },
  {
    id: 12,
    question: L({
      ko: "두 가지 모습 중 지금 내가 더 닮아있는 것은?",
      en: "Which of these two figures do you resemble more right now?",
      ja: "二つの姿のうち、今の自分に近いのはどっち？",
      "zh-CN": "两种姿态中，你现在更像哪一种？",
      "zh-TW": "兩種姿態中，你現在更像哪一種？",
      vi: "Trong hai hình dáng này, bạn giống cái nào hơn vào lúc này?",
      id: "Di antara dua sosok ini, mana yang lebih menyerupai dirimu sekarang?",
    }),
    options: [
      {
        image: IMG(12, "a"),
        label: L({
          ko: "두 팔을 활짝 벌리고 하늘을 향해 서있는 사람",
          en: "A person standing with arms wide open, facing the sky",
          ja: "両手を大きく広げて空に向かって立っている人",
          "zh-CN": "张开双臂面向天空站立的人",
          "zh-TW": "張開雙臂面向天空站立的人",
          vi: "Một người đứng dang rộng hai tay, hướng về phía bầu trời",
          id: "Seseorang yang berdiri dengan kedua tangan terbuka lebar menghadap langit",
        }),
        score: 0,
      },
      {
        image: IMG(12, "b"),
        label: L({
          ko: "양팔로 자신을 감싸 안고 눈을 감고 있는 사람",
          en: "A person wrapping their own arms around themselves with eyes closed",
          ja: "両腕で自分を抱きしめ、目を閉じている人",
          "zh-CN": "双臂环抱自己、闭着眼睛的人",
          "zh-TW": "雙臂環抱自己、閉著眼睛的人",
          vi: "Một người tự ôm lấy mình bằng hai tay, nhắm mắt lại",
          id: "Seseorang yang memeluk dirinya sendiri dengan kedua tangan sambil memejamkan mata",
        }),
        score: 1,
      },
    ],
  },
];

export const phase3EgoWallThicknessResults: Phase3EgoWallThicknessResult[] = [
  {
    type: "Type1",
    emoji: "🌅",
    title: L({
      ko: "성벽이 없는 사람, 완전 개방형 🌅",
      en: "The Person With No Wall, The Fully Open Type 🌅",
      ja: "城壁のない人、完全開放型 🌅",
      "zh-CN": "没有城墙的人，完全开放型 🌅",
      "zh-TW": "沒有城牆的人，完全開放型 🌅",
      vi: "Người không có bức tường, Kiểu hoàn toàn cởi mở 🌅",
      id: "Orang Tanpa Tembok, Tipe Sepenuhnya Terbuka 🌅",
    }),
    shortDescription: L({
      ko: "당신의 마음은 통유리 집처럼 안팎이 훤히 보입니다. 감추는 것이 거의 없습니다.",
      en: "Your heart is like a glass house — inside and out are clearly visible. You hide almost nothing.",
      ja: "あなたの心は全面ガラスの家のように、内も外もよく見えます。隠すものがほとんどありません。",
      "zh-CN": "你的内心就像落地玻璃屋一样，里外都清晰可见。几乎没有隐藏的东西。",
      "zh-TW": "你的內心就像落地玻璃屋一樣，裡外都清晰可見。幾乎沒有隱藏的東西。",
      vi: "Tâm hồn bạn giống như một ngôi nhà kính, trong ngoài đều nhìn rõ. Bạn hầu như không giấu điều gì.",
      id: "Hatimu seperti rumah berdinding kaca — bagian dalam dan luar terlihat jelas. Kamu hampir tidak menyembunyikan apa pun.",
    }),
    description: L({
      ko: "감정을 그대로 드러내고 타인을 빠르게 받아들이며 상처받을 것을 알아도 열린 채로 있습니다. 이 개방성이 가장 큰 강점이지만 동시에 가장 큰 취약점이기도 합니다. 성벽이 없으면 안으로 들어오는 것을 가리지 못할 수 있습니다.",
      en: "You show your emotions exactly as they are, accept others quickly, and stay open even knowing you might get hurt. This openness is your greatest strength, but also your greatest vulnerability. Without a wall, you may not be able to filter what comes in.",
      ja: "感情をそのまま表し、他人を素早く受け入れ、傷つくとわかっていても開いたままでいます。この開放性は最大の強みですが、同時に最大の弱点でもあります。城壁がないと、入ってくるものを選別できないことがあります。",
      "zh-CN": "你会如实表达情感，很快接纳他人，即使知道会受伤也依然保持敞开。这种开放性是你最大的优点，但同时也是你最大的弱点。没有城墙，可能就无法筛选进入内心的一切。",
      "zh-TW": "你會如實表達情感，很快接納他人，即使知道會受傷也依然保持敞開。這種開放性是你最大的優點，但同時也是你最大的弱點。沒有城牆，可能就無法篩選進入內心的一切。",
      vi: "Bạn thể hiện cảm xúc một cách chân thật, nhanh chóng chấp nhận người khác, và vẫn giữ sự cởi mở dù biết có thể bị tổn thương. Sự cởi mở này là điểm mạnh lớn nhất của bạn, nhưng đồng thời cũng là điểm yếu lớn nhất. Không có bức tường, bạn có thể không lọc được những gì đi vào tâm hồn mình.",
      id: "Kamu menunjukkan emosi apa adanya, cepat menerima orang lain, dan tetap terbuka meski tahu bisa terluka. Keterbukaan ini adalah kekuatan terbesarmu, tapi sekaligus juga kerentanan terbesarmu. Tanpa tembok, kamu mungkin tidak bisa menyaring apa yang masuk.",
    }),
    wallThickness: L({
      ko: "Lv.1 완전 개방",
      en: "Lv.1 Fully Open",
      ja: "Lv.1 完全開放",
      "zh-CN": "Lv.1 完全开放",
      "zh-TW": "Lv.1 完全開放",
      vi: "Lv.1 Hoàn toàn cởi mở",
      id: "Lv.1 Sepenuhnya Terbuka",
    }),
    strength: L({
      ko: "진정성 있는 연결·빠른 친밀감 형성·감정 표현의 자유로움",
      en: "Authentic connection · Quick to build intimacy · Freedom of emotional expression",
      ja: "誠実なつながり·早い親密感の形成·感情表現の自由さ",
      "zh-CN": "真诚的连接·快速建立亲密感·情感表达的自由",
      "zh-TW": "真誠的連結·快速建立親密感·情感表達的自由",
      vi: "Kết nối chân thành · Nhanh chóng tạo sự thân thiết · Tự do bộc lộ cảm xúc",
      id: "Koneksi yang tulus · Cepat membangun kedekatan · Kebebasan mengekspresikan emosi",
    }),
    shadow: L({
      ko: "타인의 감정에 쉽게 영향받음·경계가 흐릿해질 수 있음·상처 회복이 느릴 수 있음",
      en: "Easily affected by others' emotions · Boundaries may blur · Recovery from hurt can be slow",
      ja: "他人の感情に影響されやすい·境界が曖昧になりやすい·傷の回復が遅いことがある",
      "zh-CN": "容易受他人情绪影响·界限可能变得模糊·伤痛恢复可能较慢",
      "zh-TW": "容易受他人情緒影響·界限可能變得模糊·傷痛恢復可能較慢",
      vi: "Dễ bị ảnh hưởng bởi cảm xúc của người khác · Ranh giới có thể trở nên mờ nhạt · Việc hồi phục sau tổn thương có thể chậm",
      id: "Mudah terpengaruh emosi orang lain · Batasan bisa menjadi kabur · Pemulihan dari luka bisa lambat",
    }),
    needNow: L({
      ko: "개방성을 유지하되 나를 지키는 최소한의 경계선 하나 만들기",
      en: "Keep your openness, but create at least one minimal boundary to protect yourself",
      ja: "開放性を保ちながら、自分を守る最小限の境界線を一つ作ること",
      "zh-CN": "保持开放性，但为自己设立一条最基本的保护界限",
      "zh-TW": "保持開放性，但為自己設立一條最基本的保護界線",
      vi: "Duy trì sự cởi mở nhưng hãy tạo ra ít nhất một ranh giới tối thiểu để bảo vệ bản thân",
      id: "Pertahankan keterbukaan, tapi buatlah setidaknya satu batasan minimal untuk melindungi dirimu",
    }),
    shiningMoment: L({
      ko: "처음 만나는 사람도 금방 마음을 여는 따뜻한 관계",
      en: "Warm relationships where even someone you just met quickly opens up to you",
      ja: "初めて会う人でもすぐに心を開く温かい関係",
      "zh-CN": "即使初次见面的人也能很快敞开心扉的温暖关系",
      "zh-TW": "即使初次見面的人也能很快敞開心扉的溫暖關係",
      vi: "Những mối quan hệ ấm áp nơi ngay cả người mới gặp lần đầu cũng nhanh chóng mở lòng",
      id: "Hubungan hangat di mana bahkan orang yang baru ditemui pun cepat membuka hatinya",
    }),
    shareMessage: L({
      ko: "자아 성벽 두께: 완전 개방형 🌅 성벽이 거의 없는 통유리 마음이래... 상처받기 쉽지만 진정성 있는 연결 잘 만드는 유형 → 너는 어떤 두께야?",
      en: "Ego Wall Thickness: Fully Open Type 🌅 Apparently I have a glass-house heart with barely any wall... easily hurt, but great at making authentic connections → What's your wall thickness?",
      ja: "自我の城壁の厚さ：完全開放型 🌅 城壁がほとんどない全面ガラスの心らしい…傷つきやすいけど誠実なつながりを作るのが得意なタイプ → あなたの厚さは？",
      "zh-CN": "自我城墙厚度：完全开放型 🌅 据说我的内心几乎没有城墙，像玻璃屋一样……容易受伤但很擅长建立真诚连接的类型 → 你是什么厚度？",
      "zh-TW": "自我城牆厚度：完全開放型 🌅 據說我的內心幾乎沒有城牆，像玻璃屋一樣……容易受傷但很擅長建立真誠連結的類型 → 你是什麼厚度？",
      vi: "Độ dày tường thành bản ngã: Kiểu hoàn toàn cởi mở 🌅 Nghe nói tim mình gần như không có tường, như nhà kính vậy... dễ bị tổn thương nhưng rất giỏi tạo kết nối chân thành → Bạn thì độ dày bao nhiêu?",
      id: "Ketebalan Tembok Ego: Tipe Sepenuhnya Terbuka 🌅 Katanya hatiku hampir tanpa tembok, seperti rumah kaca... mudah terluka tapi jago membangun koneksi yang tulus → Berapa ketebalan tembokmu?",
    }),
  },
  {
    type: "Type2",
    emoji: "🌸",
    title: L({
      ko: "성벽이 얇은 사람, 감성 개방형 🌸",
      en: "The Person With a Thin Wall, The Emotionally Open Type 🌸",
      ja: "城壁が薄い人、感性開放型 🌸",
      "zh-CN": "城墙薄的人，感性开放型 🌸",
      "zh-TW": "城牆薄的人，感性開放型 🌸",
      vi: "Người có bức tường mỏng, Kiểu cởi mở cảm xúc 🌸",
      id: "Orang dengan Tembok Tipis, Tipe Terbuka Secara Emosional 🌸",
    }),
    shortDescription: L({
      ko: "당신의 마음은 꽃잎처럼 섬세하고 열려있습니다. 건드리면 느껴지지만 쉽게 열립니다.",
      en: "Your heart is as delicate and open as a flower petal. You feel every touch, but you open easily.",
      ja: "あなたの心は花びらのように繊細で開いています。触れると感じますが、簡単に開きます。",
      "zh-CN": "你的内心像花瓣一样细腻而敞开。触碰会有感觉，但很容易打开。",
      "zh-TW": "你的內心像花瓣一樣細膩而敞開。觸碰會有感覺，但很容易打開。",
      vi: "Tâm hồn bạn tinh tế và cởi mở như cánh hoa. Bạn cảm nhận được khi bị đụng vào, nhưng dễ dàng mở lòng.",
      id: "Hatimu seperti kelopak bunga — halus dan terbuka. Terasa saat disentuh, tapi mudah terbuka.",
    }),
    description: L({
      ko: "대부분의 상황에서 자신을 드러내고 타인을 받아들이지만 깊은 상처를 받으면 잠깐 닫히는 패턴이 있습니다. 감수성이 풍부하고 공감 능력이 높으며 진심 어린 관계를 만들어냅니다. 성벽이 얇다는 것은 나약함이 아닙니다. 용기입니다.",
      en: "In most situations, you reveal yourself and accept others, but when deeply hurt, you tend to close off for a while. You're highly sensitive and empathetic, and you build heartfelt relationships. A thin wall isn't weakness — it's courage.",
      ja: "ほとんどの状況で自分を表し、他人を受け入れますが、深く傷つくと少し閉じるパターンがあります。感受性が豊かで共感力が高く、心からの関係を作り出します。城壁が薄いことは弱さではありません。勇気です。",
      "zh-CN": "在大多数情况下，你会展现真实的自己并接纳他人，但如果受到深深的伤害，会暂时封闭起来。你感受力丰富、共情能力强，能建立真心的关系。城墙薄并不是软弱，而是勇气。",
      "zh-TW": "在大多數情況下，你會展現真實的自己並接納他人，但如果受到深深的傷害，會暫時封閉起來。你感受力豐富、共情能力強，能建立真心的關係。城牆薄並不是軟弱，而是勇氣。",
      vi: "Trong hầu hết các tình huống, bạn thể hiện bản thân và chấp nhận người khác, nhưng khi bị tổn thương sâu sắc, bạn có xu hướng đóng lòng lại một thời gian. Bạn giàu cảm xúc, có khả năng đồng cảm cao và xây dựng những mối quan hệ chân thành. Bức tường mỏng không phải là yếu đuối, mà là can đảm.",
      id: "Dalam kebanyakan situasi, kamu menunjukkan dirimu dan menerima orang lain, tapi ketika terluka dalam, kamu cenderung menutup diri sejenak. Kamu sangat sensitif dan empatik, serta membangun hubungan yang tulus. Tembok yang tipis bukan kelemahan — itu adalah keberanian.",
    }),
    wallThickness: L({
      ko: "Lv.2 감성 개방",
      en: "Lv.2 Emotionally Open",
      ja: "Lv.2 感性開放",
      "zh-CN": "Lv.2 感性开放",
      "zh-TW": "Lv.2 感性開放",
      vi: "Lv.2 Cởi mở cảm xúc",
      id: "Lv.2 Terbuka Secara Emosional",
    }),
    strength: L({
      ko: "깊은 공감력·진정성·관계에서의 온기·감성적 표현 능력",
      en: "Deep empathy · Authenticity · Warmth in relationships · Emotional expressiveness",
      ja: "深い共感力·誠実さ·関係における温かさ·感性的な表現力",
      "zh-CN": "深厚的共情力·真诚·关系中的温暖·感性的表达能力",
      "zh-TW": "深厚的共情力·真誠·關係中的溫暖·感性的表達能力",
      vi: "Khả năng đồng cảm sâu sắc · Chân thành · Sự ấm áp trong quan hệ · Khả năng biểu đạt cảm xúc",
      id: "Empati yang dalam · Ketulusan · Kehangatan dalam hubungan · Kemampuan ekspresi emosional",
    }),
    shadow: L({
      ko: "예민함으로 인한 소진·타인 감정에 과도한 영향·경계 설정이 어려울 때 있음",
      en: "Burnout from sensitivity · Overly affected by others' emotions · Sometimes hard to set boundaries",
      ja: "敏感さによる消耗·他人の感情に過度に影響される·境界設定が難しいときがある",
      "zh-CN": "因敏感而消耗心力·过度受他人情绪影响·有时难以设立界限",
      "zh-TW": "因敏感而消耗心力·過度受他人情緒影響·有時難以設立界限",
      vi: "Kiệt sức vì quá nhạy cảm · Bị ảnh hưởng quá mức bởi cảm xúc người khác · Đôi khi khó thiết lập ranh giới",
      id: "Kelelahan akibat sensitivitas · Terlalu terpengaruh emosi orang lain · Terkadang sulit menetapkan batasan",
    }),
    needNow: L({
      ko: "감수성을 잃지 않되 자신을 충전하는 혼자만의 회복 루틴 만들기",
      en: "Keep your sensitivity, but create your own recovery routine to recharge alone",
      ja: "感受性を失わずに、自分を充電する一人だけの回復ルーティンを作ること",
      "zh-CN": "不失去感受力，但要为自己建立独处充电的恢复日常",
      "zh-TW": "不失去感受力，但要為自己建立獨處充電的恢復日常",
      vi: "Không đánh mất sự nhạy cảm nhưng hãy tạo cho mình một thói quen hồi phục riêng để nạp lại năng lượng",
      id: "Jangan kehilangan sensitivitasmu, tapi buatlah rutinitas pemulihan sendiri untuk mengisi ulang energimu",
    }),
    shiningMoment: L({
      ko: "누군가 힘들 때 제일 먼저 알아채고 다가가는 사람",
      en: "The first person to notice and reach out when someone is struggling",
      ja: "誰かが辛いとき、一番先に気づいて寄り添う人",
      "zh-CN": "别人难过时第一个察觉并靠近的人",
      "zh-TW": "別人難過時第一個察覺並靠近的人",
      vi: "Người đầu tiên nhận ra và đến bên cạnh khi ai đó đang gặp khó khăn",
      id: "Orang pertama yang menyadari dan mendekat saat seseorang sedang kesulitan",
    }),
    shareMessage: L({
      ko: "자아 성벽 두께: 감성 개방형 🌸 꽃잎처럼 섬세하게 열려있는 마음이래... 공감 능력 높다는 거 맞음 → 너는 어떤 두께야?",
      en: "Ego Wall Thickness: Emotionally Open Type 🌸 Apparently my heart is delicately open like a petal... yeah, my empathy really is high → What's your wall thickness?",
      ja: "自我の城壁の厚さ：感性開放型 🌸 花びらのように繊細に開いた心らしい…共感力が高いって当たってる → あなたの厚さは？",
      "zh-CN": "自我城墙厚度：感性开放型 🌸 据说我的心像花瓣一样细腻地敞开着……共情能力高这点真的没错 → 你是什么厚度？",
      "zh-TW": "自我城牆厚度：感性開放型 🌸 據說我的心像花瓣一樣細膩地敞開著……共情能力高這點真的沒錯 → 你是什麼厚度？",
      vi: "Độ dày tường thành bản ngã: Kiểu cởi mở cảm xúc 🌸 Nghe nói tim mình mở ra tinh tế như cánh hoa... đúng là khả năng đồng cảm cao thật → Bạn thì độ dày bao nhiêu?",
      id: "Ketebalan Tembok Ego: Tipe Terbuka Secara Emosional 🌸 Katanya hatiku terbuka dengan halus seperti kelopak bunga... memang benar empatiku tinggi → Berapa ketebalan tembokmu?",
    }),
  },
  {
    type: "Type3",
    emoji: "🌿",
    title: L({
      ko: "성벽이 적당한 사람, 균형 보호형 🌿",
      en: "The Person With a Moderate Wall, The Balanced Protector Type 🌿",
      ja: "城壁が適度な人、バランス保護型 🌿",
      "zh-CN": "城墙适中的人，平衡保护型 🌿",
      "zh-TW": "城牆適中的人，平衡保護型 🌿",
      vi: "Người có bức tường vừa phải, Kiểu bảo vệ cân bằng 🌿",
      id: "Orang dengan Tembok Sedang, Tipe Pelindung Seimbang 🌿",
    }),
    shortDescription: L({
      ko: "당신의 마음은 탁 트인 초원 안의 작은 울타리입니다. 열려있지만 경계는 있습니다.",
      en: "Your heart is a small fence within an open meadow. Open, but with boundaries.",
      ja: "あなたの心は開けた草原の中にある小さな囲いです。開いてはいますが境界があります。",
      "zh-CN": "你的内心是开阔草原中的一道小栅栏。敞开着，但有界限。",
      "zh-TW": "你的內心是開闊草原中的一道小柵欄。敞開著，但有界限。",
      vi: "Tâm hồn bạn là một hàng rào nhỏ trong đồng cỏ rộng mở. Cởi mở nhưng vẫn có ranh giới.",
      id: "Hatimu adalah pagar kecil di tengah padang rumput terbuka. Terbuka, tapi tetap memiliki batasan.",
    }),
    description: L({
      ko: "열린 마음과 자기 보호 사이에서 균형을 잡고 있는 단계입니다. 신뢰가 생기면 자연스럽게 열리고 신뢰가 깨지면 자연스럽게 닫힙니다. 가장 건강한 성벽 두께 구간입니다.",
      en: "You're at a stage of balancing an open heart with self-protection. You open naturally when trust forms, and close naturally when trust breaks. This is the healthiest range of wall thickness.",
      ja: "開いた心と自己防衛の間でバランスを取っている段階です。信頼が生まれれば自然に開き、信頼が崩れれば自然に閉じます。最も健康な城壁の厚さの区間です。",
      "zh-CN": "你正处于在敞开心扉与自我保护之间取得平衡的阶段。信任建立时自然敞开，信任破裂时自然关闭。这是最健康的城墙厚度区间。",
      "zh-TW": "你正處於在敞開心扉與自我保護之間取得平衡的階段。信任建立時自然敞開，信任破裂時自然關閉。這是最健康的城牆厚度區間。",
      vi: "Bạn đang ở giai đoạn cân bằng giữa một tâm hồn cởi mở và việc tự bảo vệ bản thân. Khi có niềm tin, bạn tự nhiên mở lòng, và khi niềm tin tan vỡ, bạn tự nhiên đóng lại. Đây là khoảng độ dày tường thành lành mạnh nhất.",
      id: "Kamu berada di tahap menyeimbangkan hati yang terbuka dengan perlindungan diri. Kamu terbuka secara alami saat kepercayaan terbentuk, dan menutup secara alami saat kepercayaan itu hancur. Ini adalah rentang ketebalan tembok yang paling sehat.",
    }),
    wallThickness: L({
      ko: "Lv.3 균형 보호",
      en: "Lv.3 Balanced Protection",
      ja: "Lv.3 バランス保護",
      "zh-CN": "Lv.3 平衡保护",
      "zh-TW": "Lv.3 平衡保護",
      vi: "Lv.3 Bảo vệ cân bằng",
      id: "Lv.3 Perlindungan Seimbang",
    }),
    strength: L({
      ko: "건강한 경계선·상황 판단력·관계의 깊이와 안전 균형",
      en: "Healthy boundaries · Good situational judgment · Balance between depth and safety in relationships",
      ja: "健康な境界線·状況判断力·関係の深さと安全のバランス",
      "zh-CN": "健康的界限·情境判断力·关系深度与安全的平衡",
      "zh-TW": "健康的界限·情境判斷力·關係深度與安全的平衡",
      vi: "Ranh giới lành mạnh · Khả năng đánh giá tình huống · Sự cân bằng giữa độ sâu và an toàn trong quan hệ",
      id: "Batasan yang sehat · Kemampuan menilai situasi · Keseimbangan antara kedalaman dan keamanan dalam hubungan",
    }),
    shadow: L({
      ko: "가끔 열지 말지를 너무 오래 고민하거나 판단이 느릴 수 있음",
      en: "Sometimes overthinks whether to open up, or judgment can be slow",
      ja: "時々開くかどうかを長く悩んだり、判断が遅くなることがある",
      "zh-CN": "有时会为要不要敞开心扉而纠结太久，判断可能较慢",
      "zh-TW": "有時會為要不要敞開心扉而糾結太久，判斷可能較慢",
      vi: "Đôi khi phân vân quá lâu về việc có nên mở lòng hay không, hoặc phán đoán chậm",
      id: "Terkadang terlalu lama menimbang apakah harus terbuka atau tidak, atau penilaiannya bisa lambat",
    }),
    needNow: L({
      ko: "지금의 균형을 유지하는 것만으로 충분. 경계를 죄책감 없이 설정하는 연습",
      en: "Just maintaining your current balance is enough. Practice setting boundaries without guilt.",
      ja: "今のバランスを維持するだけで十分。罪悪感なく境界を設定する練習。",
      "zh-CN": "维持现在的平衡就已经足够。练习在没有愧疚感的情况下设立界限。",
      "zh-TW": "維持現在的平衡就已經足夠。練習在沒有愧疚感的情況下設立界限。",
      vi: "Chỉ cần duy trì sự cân bằng hiện tại là đủ. Hãy luyện tập thiết lập ranh giới mà không cảm thấy tội lỗi.",
      id: "Menjaga keseimbangan saat ini saja sudah cukup. Latihlah menetapkan batasan tanpa rasa bersalah.",
    }),
    shiningMoment: L({
      ko: "누구에게나 편안하지만 아무에게나 다 열지 않는 사람",
      en: "Someone comfortable to be around for anyone, but who doesn't open up to just anyone",
      ja: "誰に対しても居心地良いが、誰にでも全部開くわけではない人",
      "zh-CN": "对谁都自在相处，但不会对任何人都毫无保留敞开心扉的人",
      "zh-TW": "對誰都自在相處，但不會對任何人都毫無保留敞開心扉的人",
      vi: "Người khiến ai cũng cảm thấy thoải mái, nhưng không mở lòng hoàn toàn với bất kỳ ai",
      id: "Orang yang nyaman bagi siapa saja, tapi tidak terbuka sepenuhnya kepada sembarang orang",
    }),
    shareMessage: L({
      ko: "자아 성벽 두께: 균형 보호형 🌿 열려있지만 경계는 있는 가장 건강한 두께래... 근데 나 이게 맞나 싶기도 함 ㅋㅋ → 너는 어떤 두께야?",
      en: "Ego Wall Thickness: Balanced Protector Type 🌿 Apparently this is the healthiest thickness — open but with boundaries... though I do wonder if that's really me lol → What's your wall thickness?",
      ja: "自我の城壁の厚さ：バランス保護型 🌿 開いているけど境界もある一番健康な厚さらしい…でも本当にそうかなって思うw → あなたの厚さは？",
      "zh-CN": "自我城墙厚度：平衡保护型 🌿 据说这是最健康的厚度，敞开但有界限……不过我也在想这样对不对哈哈 → 你是什么厚度？",
      "zh-TW": "自我城牆厚度：平衡保護型 🌿 據說這是最健康的厚度，敞開但有界限……不過我也在想這樣對不對哈哈 → 你是什麼厚度？",
      vi: "Độ dày tường thành bản ngã: Kiểu bảo vệ cân bằng 🌿 Nghe nói đây là độ dày lành mạnh nhất - cởi mở nhưng có ranh giới... nhưng mình cũng thấy hơi ngờ ngợ ha ha → Bạn thì độ dày bao nhiêu?",
      id: "Ketebalan Tembok Ego: Tipe Pelindung Seimbang 🌿 Katanya ini ketebalan paling sehat — terbuka tapi punya batasan... tapi aku juga jadi mikir apa benar gitu haha → Berapa ketebalan tembokmu?",
    }),
  },
  {
    type: "Type4",
    emoji: "🏛️",
    title: L({
      ko: "성벽이 두꺼운 사람, 신중 방어형 🏛️",
      en: "The Person With a Thick Wall, The Cautious Defender Type 🏛️",
      ja: "城壁が厚い人、慎重防御型 🏛️",
      "zh-CN": "城墙厚的人，谨慎防御型 🏛️",
      "zh-TW": "城牆厚的人，謹慎防禦型 🏛️",
      vi: "Người có bức tường dày, Kiểu phòng thủ cẩn trọng 🏛️",
      id: "Orang dengan Tembok Tebal, Tipe Pelindung Waspada 🏛️",
    }),
    shortDescription: L({
      ko: "당신의 마음은 단단한 조개껍데기처럼 쉽게 열리지 않습니다. 하지만 열리면 안에 진주가 있습니다.",
      en: "Your heart doesn't open easily, like a hard seashell. But once it opens, there's a pearl inside.",
      ja: "あなたの心は硬い貝殻のように簡単には開きません。でも開けば中に真珠があります。",
      "zh-CN": "你的内心像坚硬的贝壳一样不容易打开。但一旦打开，里面有珍珠。",
      "zh-TW": "你的內心像堅硬的貝殼一樣不容易打開。但一旦打開，裡面有珍珠。",
      vi: "Tâm hồn bạn giống như một chiếc vỏ sò cứng, không dễ mở ra. Nhưng khi đã mở, bên trong có một hòn ngọc trai.",
      id: "Hatimu tidak mudah terbuka, seperti cangkang kerang yang keras. Tapi begitu terbuka, di dalamnya ada mutiara.",
    }),
    description: L({
      ko: "낯선 상황과 사람 앞에서 자연스럽게 방어 기제가 작동합니다. 신중하고 쉽게 흔들리지 않으며 한번 신뢰하면 깊이 있는 관계를 만드는 타입입니다. 성벽이 두꺼운 데는 이유가 있습니다. 지금까지 지켜온 자신이 있습니다.",
      en: "In unfamiliar situations and around new people, your defense mechanisms kick in naturally. You're cautious, not easily shaken, and once you trust someone, you build deep relationships. There's a reason your wall is thick — there's a self you've been protecting all this time.",
      ja: "見知らぬ状況や人の前で自然に防御機制が働きます。慎重で簡単には揺らがず、一度信頼すれば深い関係を作るタイプです。城壁が厚いのには理由があります。今まで守ってきた自分があるのです。",
      "zh-CN": "在陌生的情况和人面前，防御机制会自然启动。你是谨慎、不易动摇的类型，一旦信任就会建立深厚的关系。城墙厚是有原因的，是因为有一个你一直守护到现在的自己。",
      "zh-TW": "在陌生的情況和人面前，防禦機制會自然啟動。你是謹慎、不易動搖的類型，一旦信任就會建立深厚的關係。城牆厚是有原因的，是因為有一個你一直守護到現在的自己。",
      vi: "Trước những tình huống và con người xa lạ, cơ chế phòng thủ của bạn tự động hoạt động. Bạn là người cẩn trọng, khó bị lung lay, và khi đã tin tưởng ai đó, bạn sẽ xây dựng mối quan hệ sâu sắc. Bức tường dày có lý do của nó — đó là một bản thân bạn đã bảo vệ đến tận bây giờ.",
      id: "Di hadapan situasi dan orang yang belum dikenal, mekanisme pertahananmu bekerja secara alami. Kamu berhati-hati, tidak mudah goyah, dan begitu kamu percaya pada seseorang, kamu membangun hubungan yang dalam. Ada alasan mengapa tembokmu tebal — ada dirimu yang selama ini kamu jaga.",
    }),
    wallThickness: L({
      ko: "Lv.4 신중 방어",
      en: "Lv.4 Cautious Defense",
      ja: "Lv.4 慎重防御",
      "zh-CN": "Lv.4 谨慎防御",
      "zh-TW": "Lv.4 謹慎防禦",
      vi: "Lv.4 Phòng thủ cẩn trọng",
      id: "Lv.4 Pertahanan Waspada",
    }),
    strength: L({
      ko: "단단한 자기 기준·쉽게 흔들리지 않음·한번 맺은 관계의 깊이",
      en: "Firm personal standards · Not easily shaken · Depth in relationships once formed",
      ja: "しっかりした自分の基準·簡単には揺るがない·一度結んだ関係の深さ",
      "zh-CN": "坚定的自我标准·不易动摇·一旦建立关系就有深度",
      "zh-TW": "堅定的自我標準·不易動搖·一旦建立關係就有深度",
      vi: "Tiêu chuẩn bản thân vững chắc · Khó bị lung lay · Chiều sâu trong mối quan hệ đã thiết lập",
      id: "Standar diri yang kuat · Tidak mudah goyah · Kedalaman hubungan yang sudah terjalin",
    }),
    shadow: L({
      ko: "새로운 관계 형성이 느림·마음을 여는 데 에너지가 많이 듦·오해받을 수 있음",
      en: "Slow to form new relationships · Opening up takes a lot of energy · Can be misunderstood",
      ja: "新しい関係を築くのが遅い·心を開くのに多くのエネルギーが必要·誤解されることがある",
      "zh-CN": "建立新关系较慢·敞开心扉需要耗费很多精力·可能被误解",
      "zh-TW": "建立新關係較慢·敞開心扉需要耗費很多精力·可能被誤解",
      vi: "Chậm trong việc hình thành mối quan hệ mới · Mở lòng cần nhiều năng lượng · Có thể bị hiểu lầm",
      id: "Lambat dalam membangun hubungan baru · Membuka diri membutuhkan banyak energi · Bisa disalahpahami",
    }),
    needNow: L({
      ko: "신뢰하는 사람에게 조금 더 먼저 다가가는 작은 시도. 성벽을 무너뜨리는 게 아니라 문을 하나 더 만드는 것",
      en: "A small attempt to reach out first to someone you trust. Not tearing down the wall, but adding one more door.",
      ja: "信頼する人にもう少し先に近づく小さな試み。城壁を崩すのではなく、ドアを一つ増やすこと。",
      "zh-CN": "对信任的人多迈出一小步、主动靠近的尝试。不是拆掉城墙，而是多开一扇门。",
      "zh-TW": "對信任的人多邁出一小步、主動靠近的嘗試。不是拆掉城牆，而是多開一扇門。",
      vi: "Một cố gắng nhỏ để chủ động tiến gần hơn với người bạn tin tưởng. Không phải phá bỏ bức tường, mà là tạo thêm một cánh cửa.",
      id: "Sebuah upaya kecil untuk lebih dulu mendekat kepada orang yang kamu percaya. Bukan merobohkan tembok, tapi menambahkan satu pintu lagi.",
    }),
    shiningMoment: L({
      ko: "오래 알면 알수록 새로운 면이 나오는 사람",
      en: "Someone who reveals new sides the longer you know them",
      ja: "長く知れば知るほど新しい面が出てくる人",
      "zh-CN": "认识越久越能发现新面貌的人",
      "zh-TW": "認識越久越能發現新面貌的人",
      vi: "Người mà càng biết lâu càng lộ ra những mặt mới",
      id: "Orang yang menunjukkan sisi baru semakin lama kamu mengenalnya",
    }),
    shareMessage: L({
      ko: "자아 성벽 두께: 신중 방어형 🏛️ 쉽게 열리지 않는 조개껍데기 마음이래... 열리면 진주가 있다는 표현 너무 마음에 듦 → 너는 어떤 두께야?",
      en: "Ego Wall Thickness: Cautious Defender Type 🏛️ Apparently my heart is a seashell that doesn't open easily... I love the part about there being a pearl inside once it opens → What's your wall thickness?",
      ja: "自我の城壁の厚さ：慎重防御型 🏛️ 簡単には開かない貝殻の心らしい…開けば真珠があるっていう表現が気に入った → あなたの厚さは？",
      "zh-CN": "自我城墙厚度：谨慎防御型 🏛️ 据说我的心是不容易打开的贝壳……但打开就有珍珠这个说法我太喜欢了 → 你是什么厚度？",
      "zh-TW": "自我城牆厚度：謹慎防禦型 🏛️ 據說我的心是不容易打開的貝殼……但打開就有珍珠這個說法我太喜歡了 → 你是什麼厚度？",
      vi: "Độ dày tường thành bản ngã: Kiểu phòng thủ cẩn trọng 🏛️ Nghe nói tim mình là vỏ sò khó mở... nhưng câu mở ra sẽ có ngọc trai thì mình cực thích → Bạn thì độ dày bao nhiêu?",
      id: "Ketebalan Tembok Ego: Tipe Pelindung Waspada 🏛️ Katanya hatiku adalah cangkang kerang yang tidak mudah terbuka... tapi ungkapan begitu terbuka ada mutiara di dalamnya benar-benar aku suka → Berapa ketebalan tembokmu?",
    }),
  },
  {
    type: "Type5",
    emoji: "🌊",
    title: L({
      ko: "성벽이 매우 두꺼운 사람, 깊이 보호형 🌊",
      en: "The Person With a Very Thick Wall, The Deep Protector Type 🌊",
      ja: "城壁が非常に厚い人、深層保護型 🌊",
      "zh-CN": "城墙非常厚的人，深度保护型 🌊",
      "zh-TW": "城牆非常厚的人，深度保護型 🌊",
      vi: "Người có bức tường rất dày, Kiểu bảo vệ sâu sắc 🌊",
      id: "Orang dengan Tembok Sangat Tebal, Tipe Pelindung Mendalam 🌊",
    }),
    shortDescription: L({
      ko: "당신의 마음은 깊고 어두운 바다처럼 수면은 조용하지만 아래가 보이지 않습니다.",
      en: "Your heart is like a deep, dark sea — calm on the surface, but you can't see what's below.",
      ja: "あなたの心は深く暗い海のように、水面は静かですが下は見えません。",
      "zh-CN": "你的内心像深邃黑暗的海洋，表面平静但看不见水下的世界。",
      "zh-TW": "你的內心像深邃黑暗的海洋，表面平靜但看不見水下的世界。",
      vi: "Tâm hồn bạn giống như biển sâu và tối, mặt nước yên tĩnh nhưng không thể thấy được phía dưới.",
      id: "Hatimu seperti laut yang dalam dan gelap — tenang di permukaan, tapi bagian bawahnya tak terlihat.",
    }),
    description: L({
      ko: "겉으로는 평온하고 차분해 보이지만 내면 깊이 들어가기 매우 어려운 상태입니다. 오랜 시간 동안 자신을 지키며 쌓아온 성벽입니다. 이것은 나약함이 아닙니다. 다만 이 성벽이 때로는 진짜 원하는 연결을 막고 있을 수 있습니다.",
      en: "On the outside you look calm and composed, but it's very hard to get deep into your inner world. This is a wall you've built over a long time to protect yourself. This isn't weakness. It's just that this wall may sometimes be blocking the connection you truly want.",
      ja: "外見は穏やかで落ち着いて見えますが、内面の奥深くに入るのは非常に難しい状態です。長い時間、自分を守りながら積み上げてきた城壁です。これは弱さではありません。ただ、この城壁が時に本当に望むつながりを妨げていることがあります。",
      "zh-CN": "表面看起来平静沉稳，但要深入内心却非常困难。这是长时间守护自己而筑起的城墙。这并不是软弱。只是这座城墙有时可能阻挡了你真正渴望的连接。",
      "zh-TW": "表面看起來平靜沉穩，但要深入內心卻非常困難。這是長時間守護自己而築起的城牆。這並不是軟弱。只是這座城牆有時可能阻擋了你真正渴望的連結。",
      vi: "Bên ngoài trông có vẻ điềm tĩnh và bình thản, nhưng để đi sâu vào nội tâm lại rất khó khăn. Đây là bức tường mà bạn đã xây dựng qua thời gian dài để bảo vệ bản thân. Đây không phải là sự yếu đuối. Chỉ là bức tường này đôi khi có thể đang ngăn cản sự kết nối mà bạn thực sự mong muốn.",
      id: "Dari luar terlihat tenang dan tenteram, tapi sangat sulit untuk masuk jauh ke dalam batinmu. Ini adalah tembok yang kamu bangun selama waktu yang lama untuk melindungi dirimu. Ini bukan kelemahan. Hanya saja tembok ini terkadang bisa menghalangi koneksi yang benar-benar kamu inginkan.",
    }),
    wallThickness: L({
      ko: "Lv.5 깊이 보호",
      en: "Lv.5 Deep Protection",
      ja: "Lv.5 深層保護",
      "zh-CN": "Lv.5 深度保护",
      "zh-TW": "Lv.5 深度保護",
      vi: "Lv.5 Bảo vệ sâu sắc",
      id: "Lv.5 Pelindung Mendalam",
    }),
    strength: L({
      ko: "강한 자기 독립성·쉽게 흔들리지 않는 내면·깊이 있는 사색",
      en: "Strong self-independence · An inner core that's hard to shake · Deep contemplation",
      ja: "強い自己独立性·簡単には揺らがない内面·深い思索",
      "zh-CN": "强大的自我独立性·不易动摇的内心·深刻的思考能力",
      "zh-TW": "強大的自我獨立性·不易動搖的內心·深刻的思考能力",
      vi: "Tính độc lập bản thân mạnh mẽ · Nội tâm khó bị lung lay · Khả năng suy ngẫm sâu sắc",
      id: "Kemandirian diri yang kuat · Batin yang tidak mudah goyah · Perenungan yang dalam",
    }),
    shadow: L({
      ko: "진짜 감정을 표현하기 어려움·친밀한 관계 형성이 느리고 힘듦·외로움을 혼자 감당하는 경향",
      en: "Hard to express true feelings · Slow and difficult to form intimate relationships · Tendency to carry loneliness alone",
      ja: "本当の感情を表現するのが難しい·親密な関係の形成が遅く困難·孤独を一人で抱え込む傾向",
      "zh-CN": "难以表达真实情感·建立亲密关系缓慢而困难·倾向于独自承受孤独",
      "zh-TW": "難以表達真實情感·建立親密關係緩慢而困難·傾向於獨自承受孤獨",
      vi: "Khó bộc lộ cảm xúc thật · Hình thành mối quan hệ thân thiết chậm và khó khăn · Có xu hướng tự mình chịu đựng sự cô đơn",
      id: "Sulit mengungkapkan perasaan yang sebenarnya · Lambat dan sulit membangun hubungan yang intim · Cenderung menanggung kesepian sendirian",
    }),
    needNow: L({
      ko: "성벽을 무너뜨릴 필요는 없습니다. 단 한 명에게 오늘 하루 어땠는지 솔직하게 말해보기",
      en: "There's no need to tear down the wall. Try honestly telling just one person how your day went.",
      ja: "城壁を崩す必要はありません。たった一人に今日一日どうだったか正直に話してみること。",
      "zh-CN": "不需要拆掉城墙。试着向一个人坦诚地说说今天过得怎样。",
      "zh-TW": "不需要拆掉城牆。試著向一個人坦誠地說說今天過得怎樣。",
      vi: "Không cần phải phá bỏ bức tường. Hãy thử nói thật lòng với một người về ngày hôm nay của bạn.",
      id: "Tidak perlu merobohkan tembok. Cobalah bercerita jujur pada satu orang tentang bagaimana harimu berjalan.",
    }),
    shiningMoment: L({
      ko: "알면 알수록 예상치 못한 깊이와 따뜻함이 나오는 사람",
      en: "Someone whose unexpected depth and warmth reveal themselves the more you know them",
      ja: "知れば知るほど予想外の深さと温かさが出てくる人",
      "zh-CN": "越了解越能发现意想不到的深度与温暖的人",
      "zh-TW": "越了解越能發現意想不到的深度與溫暖的人",
      vi: "Người mà càng hiểu càng thấy được chiều sâu và sự ấm áp bất ngờ",
      id: "Orang yang menunjukkan kedalaman dan kehangatan tak terduga semakin kamu mengenalnya",
    }),
    shareMessage: L({
      ko: "자아 성벽 두께: 깊이 보호형 🌊 수면은 조용하지만 아래가 보이지 않는 깊은 바다 마음이래... 알면 알수록 깊이 있는 사람 맞음 → 너는 어떤 두께야?",
      en: "Ego Wall Thickness: Deep Protector Type 🌊 Apparently my heart is a deep sea, calm on the surface but unseen below... yeah, I really do get deeper the more you know me → What's your wall thickness?",
      ja: "自我の城壁の厚さ：深層保護型 🌊 水面は静かだけど下が見えない深い海の心らしい…知れば知るほど深い人って当たってる → あなたの厚さは？",
      "zh-CN": "自我城墙厚度：深度保护型 🌊 据说我的心是表面平静但看不见水下的深海……越了解越有深度这点真的没错 → 你是什么厚度？",
      "zh-TW": "自我城牆厚度：深度保護型 🌊 據說我的心是表面平靜但看不見水下的深海……越了解越有深度這點真的沒錯 → 你是什麼厚度？",
      vi: "Độ dày tường thành bản ngã: Kiểu bảo vệ sâu sắc 🌊 Nghe nói tim mình là biển sâu, mặt nước yên tĩnh nhưng không thấy đáy... đúng là mình càng hiểu càng sâu sắc thật → Bạn thì độ dày bao nhiêu?",
      id: "Ketebalan Tembok Ego: Tipe Pelindung Mendalam 🌊 Katanya hatiku adalah laut dalam, tenang di permukaan tapi tak terlihat di bawah... memang benar aku semakin dalam semakin dikenal → Berapa ketebalan tembokmu?",
    }),
  },
  {
    type: "Type6",
    emoji: "🏰",
    title: L({
      ko: "철옹성 수준, 완전 방어형 🏰",
      en: "Fortress Level, The Fully Defended Type 🏰",
      ja: "鉄壁レベル、完全防御型 🏰",
      "zh-CN": "铁壁级别，完全防御型 🏰",
      "zh-TW": "鐵壁級別，完全防禦型 🏰",
      vi: "Cấp độ thành trì bất khả xâm phạm, Kiểu phòng thủ toàn diện 🏰",
      id: "Level Benteng, Tipe Pertahanan Total 🏰",
    }),
    shortDescription: L({
      ko: "당신의 성벽은 아무도 쉽게 들어올 수 없을 만큼 두껍습니다. 그 안에 무엇이 있는지는 당신만 압니다.",
      en: "Your wall is so thick that no one can easily get in. Only you know what's inside.",
      ja: "あなたの城壁は誰も簡単には入れないほど厚いです。その中に何があるかはあなただけが知っています。",
      "zh-CN": "你的城墙厚到没有人能轻易进入。里面有什么，只有你自己知道。",
      "zh-TW": "你的城牆厚到沒有人能輕易進入。裡面有什麼，只有你自己知道。",
      vi: "Bức tường của bạn dày đến mức không ai có thể dễ dàng bước vào. Bên trong có gì, chỉ có bạn mới biết.",
      id: "Tembokmu begitu tebal sehingga tidak ada yang bisa masuk dengan mudah. Hanya kamu yang tahu apa yang ada di dalamnya.",
    }),
    description: L({
      ko: "12개 이미지 모두에서 더 닫히고 더 보호받는 것을 선택했습니다. 이것은 지금까지 자신을 지켜온 방식입니다. 성벽이 두껍다는 것은 그 안에 지키고 싶은 것이 있다는 뜻입니다. 그리고 그것은 가치 있는 것입니다.",
      en: "In all 12 images, you chose the more closed and more protected option. This is the way you've protected yourself until now. A thick wall means there's something inside worth protecting. And that something is valuable.",
      ja: "12個の画像すべてで、より閉じてより保護されるものを選びました。これは今まで自分を守ってきた方法です。城壁が厚いということは、その中に守りたいものがあるという意味です。そしてそれは価値のあるものです。",
      "zh-CN": "在全部12张图片中，你都选择了更封闭、更受保护的一方。这是你至今守护自己的方式。城墙厚意味着里面有你想守护的东西。而那是有价值的东西。",
      "zh-TW": "在全部12張圖片中，你都選擇了更封閉、更受保護的一方。這是你至今守護自己的方式。城牆厚意味著裡面有你想守護的東西。而那是有價值的東西。",
      vi: "Trong cả 12 hình ảnh, bạn đều chọn phía đóng kín và được bảo vệ hơn. Đây là cách bạn đã bảo vệ bản thân đến bây giờ. Bức tường dày có nghĩa là bên trong có điều gì đó bạn muốn bảo vệ. Và điều đó là có giá trị.",
      id: "Dalam semua 12 gambar, kamu memilih pilihan yang lebih tertutup dan lebih terlindungi. Ini adalah cara kamu melindungi dirimu sampai sekarang. Tembok yang tebal berarti ada sesuatu di dalamnya yang ingin dijaga. Dan hal itu berharga.",
    }),
    wallThickness: L({
      ko: "Lv.6 철옹성",
      en: "Lv.6 Fortress",
      ja: "Lv.6 鉄壁",
      "zh-CN": "Lv.6 铁壁",
      "zh-TW": "Lv.6 鐵壁",
      vi: "Lv.6 Thành trì bất khả xâm phạm",
      id: "Lv.6 Benteng",
    }),
    strength: L({
      ko: "누구에게도 쉽게 흔들리지 않는 내면의 단단함·독립성·자기만의 세계",
      en: "Inner steadiness that's hard for anyone to shake · Independence · A world entirely your own",
      ja: "誰にも簡単には揺らがない内面の強さ·独立性·自分だけの世界",
      "zh-CN": "无人能轻易动摇的内心坚定·独立性·属于自己的世界",
      "zh-TW": "無人能輕易動搖的內心堅定·獨立性·屬於自己的世界",
      vi: "Sự vững chắc nội tâm mà không ai dễ làm lung lay · Tính độc lập · Thế giới riêng của bản thân",
      id: "Ketegaran batin yang tak mudah digoyahkan siapa pun · Kemandirian · Dunia yang sepenuhnya milikmu sendiri",
    }),
    shadow: L({
      ko: "진정한 연결이 어려울 수 있음·감정을 혼자 감당하는 부담·성벽이 외로움을 만들기도 함",
      en: "True connection can be difficult · The burden of handling emotions alone · The wall can also create loneliness",
      ja: "本当のつながりが難しいことがある·感情を一人で抱える負担·城壁が孤独を作ることもある",
      "zh-CN": "真正的连接可能很困难·独自承担情绪的负担·城墙有时也会造成孤独",
      "zh-TW": "真正的連結可能很困難·獨自承擔情緒的負擔·城牆有時也會造成孤獨",
      vi: "Kết nối thật sự có thể khó khăn · Gánh nặng tự mình gánh chịu cảm xúc · Bức tường cũng có thể tạo ra sự cô đơn",
      id: "Koneksi yang sejati bisa jadi sulit · Beban menanggung emosi sendirian · Tembok itu juga bisa menciptakan kesepian",
    }),
    needNow: L({
      ko: "성벽을 허물 필요는 없습니다. 다만 그 성벽에 작은 창문 하나를 내는 것. 전부를 보여줄 필요 없이 한 조각만 꺼내보기",
      en: "There's no need to tear down the wall. Just make one small window in it. You don't need to show everything — just try sharing one small piece.",
      ja: "城壁を壊す必要はありません。ただその城壁に小さな窓を一つ作ること。すべてを見せる必要はなく、一片だけ出してみること。",
      "zh-CN": "不需要拆掉城墙。只是在城墙上开一个小窗。不必展示全部，只拿出一小部分试试看。",
      "zh-TW": "不需要拆掉城牆。只是在城牆上開一個小窗。不必展示全部，只拿出一小部分試試看。",
      vi: "Không cần phải phá bỏ bức tường. Chỉ cần mở một ô cửa nhỏ trên bức tường đó. Không cần cho thấy tất cả, chỉ cần thử hé lộ một phần nhỏ.",
      id: "Tidak perlu merobohkan tembok itu. Cukup buat satu jendela kecil di tembok tersebut. Tidak perlu menunjukkan semuanya — coba tunjukkan satu bagian kecil saja.",
    }),
    shiningMoment: L({
      ko: "성벽 안으로 초대받은 사람이 가장 소중하게 느끼는 존재가 됩니다",
      en: "Whoever is invited inside the wall becomes the person you cherish most",
      ja: "城壁の中に招かれた人が最も大切に感じる存在になります",
      "zh-CN": "被邀请进入城墙内的人，会成为你最珍视的存在",
      "zh-TW": "被邀請進入城牆內的人，會成為你最珍視的存在",
      vi: "Người được mời vào trong bức tường sẽ trở thành người mà bạn coi trọng nhất",
      id: "Siapa pun yang diundang masuk ke dalam tembok akan menjadi sosok yang paling kamu hargai",
    }),
    oneLiner: L({
      ko: "성벽이 두꺼울수록 그 안이 더 궁금해집니다",
      en: "The thicker the wall, the more curious people become about what's inside",
      ja: "城壁が厚いほど、その中がもっと気になります",
      "zh-CN": "城墙越厚，越让人好奇里面是什么",
      "zh-TW": "城牆越厚，越讓人好奇裡面是什麼",
      vi: "Bức tường càng dày, người ta càng tò mò về những gì bên trong",
      id: "Semakin tebal temboknya, semakin membuat orang ingin tahu apa yang ada di dalamnya",
    }),
    shareMessage: L({
      ko: "자아 성벽 두께: 완전 방어형 🏰 철옹성 수준이래... 성벽 안으로 초대받은 사람이 가장 소중하게 느끼는 존재가 된다는 말이 울림 → 너는 어떤 두께야?",
      en: "Ego Wall Thickness: Fully Defended Type 🏰 Apparently I'm fortress level... the line about whoever's invited inside becoming the one I cherish most really hit me → What's your wall thickness?",
      ja: "自我の城壁の厚さ：完全防御型 🏰 鉄壁レベルらしい…城壁の中に招かれた人が一番大切な存在になるという言葉が心に響いた → あなたの厚さは？",
      "zh-CN": "自我城墙厚度：完全防御型 🏰 据说是铁壁级别……被邀请进城墙里的人会成为最珍视的存在这句话真的很触动我 → 你是什么厚度？",
      "zh-TW": "自我城牆厚度：完全防禦型 🏰 據說是鐵壁級別……被邀請進城牆裡的人會成為最珍視的存在這句話真的很觸動我 → 你是什麼厚度？",
      vi: "Độ dày tường thành bản ngã: Kiểu phòng thủ toàn diện 🏰 Nghe nói mình đạt cấp độ thành trì bất khả xâm phạm... câu nói người được mời vào trong tường sẽ trở thành người quý giá nhất khiến mình thực sự xúc động → Bạn thì độ dày bao nhiêu?",
      id: "Ketebalan Tembok Ego: Tipe Pertahanan Total 🏰 Katanya aku level benteng... kalimat tentang siapa pun yang diundang masuk akan menjadi sosok yang paling dihargai benar-benar menyentuh → Berapa ketebalan tembokmu?",
    }),
  },
];
