/** 나의 시험 공부 유형 — phase3-exam-study-type · 12문항 4지선다 · A=0/B=1/C=2/D=3 · 7개 로케일 */

export type Phase3ExamStudyTypeLocaleKey = 'ko' | 'en' | 'ja' | 'zh-CN' | 'zh-TW' | 'vi' | 'id';

function localeMap(t: Record<Phase3ExamStudyTypeLocaleKey, string>): Record<Phase3ExamStudyTypeLocaleKey, string> {
  return t;
}

function opt(m: Record<Phase3ExamStudyTypeLocaleKey, string>, score: number): { text: Record<Phase3ExamStudyTypeLocaleKey, string>; score: number } {
  return { text: localeMap(m), score };
}

export interface Phase3ExamStudyTypeQuestion {
  id: number;
  question: Record<Phase3ExamStudyTypeLocaleKey, string>;
  options: { text: Record<Phase3ExamStudyTypeLocaleKey, string>; score: number }[];
}

export interface Phase3ExamStudyTypeResult {
  type: string;
  emoji: string;
  title: Record<Phase3ExamStudyTypeLocaleKey, string>;
  studySummary: Record<Phase3ExamStudyTypeLocaleKey, string>;
  quote: Record<Phase3ExamStudyTypeLocaleKey, string>;
  description: Record<Phase3ExamStudyTypeLocaleKey, string>;
  studyType: Record<Phase3ExamStudyTypeLocaleKey, string>;
  studyKeywords: Record<Phase3ExamStudyTypeLocaleKey, string>;
  strengths: Record<Phase3ExamStudyTypeLocaleKey, string>;
  cautions: Record<Phase3ExamStudyTypeLocaleKey, string>;
  studyTip: Record<Phase3ExamStudyTypeLocaleKey, string>;
  typicalPhrase: Record<Phase3ExamStudyTypeLocaleKey, string>;
  certificationPhrase: Record<Phase3ExamStudyTypeLocaleKey, string>;
  oneLiner: Record<Phase3ExamStudyTypeLocaleKey, string>;
  shareLine: Record<Phase3ExamStudyTypeLocaleKey, string>;
}

export function calculatePhase3ExamStudyTypeResult(answers: number[]): string {
  const total = answers.reduce((sum, s) => sum + (s ?? 0), 0);
  if (total <= 5) return 'Type1';
  if (total <= 11) return 'Type2';
  if (total <= 19) return 'Type3';
  if (total <= 27) return 'Type4';
  if (total <= 33) return 'Type5';
  return 'Type6';
}

export function calculatePhase3ExamStudyTypeDomainScores(answers: number[]) {
  const startStyle = (answers[0] ?? 0) + (answers[1] ?? 0);
  const focusEnv = (answers[2] ?? 0) + (answers[3] ?? 0);
  const studyMethod = (answers[4] ?? 0) + (answers[5] ?? 0);
  const slumpCoping = (answers[6] ?? 0) + (answers[7] ?? 0);
  const examEvePattern = (answers[8] ?? 0) + (answers[9] ?? 0);
  const resultAcceptance = (answers[10] ?? 0) + (answers[11] ?? 0);
  return {
    startStyle,
    focusEnv,
    studyMethod,
    slumpCoping,
    examEvePattern,
    resultAcceptance,
    total: answers.reduce((sum, s) => sum + (s ?? 0), 0),
  };
}

export const phase3ExamStudyTypeQuestions: Phase3ExamStudyTypeQuestion[] = [
  {
    id: 1,
    question: localeMap({
      ko: '오늘 공부를 시작하려고 책상 앞에 앉았다. 가장 먼저 하는 것은?',
      en: 'You sit at your desk to study today. What do you do first?',
      ja: '今日勉強を始めようと机に座った。最初にすることは？',
      'zh-CN': '今天坐到书桌前准备学习。最先做什么？',
      'zh-TW': '今天坐到書桌前準備學習。最先做什麼？',
      vi: 'Ngồi vào bàn để học hôm nay, bạn làm gì đầu tiên?',
      id: 'Duduk di meja untuk belajar hari ini. Apa yang pertama dilakukan?',
    }),
    options: [
      opt(localeMap({
        ko: '일단 눕는다. 시작이 너무 어렵다. 조금 있다 하면 되지 싶은데 어느새 자고 있다',
        en: 'Lie down first. Starting is too hard, and I end up asleep.',
        ja: 'とりあえず横になる。始めるのが難しく、いつの間にか寝ている',
        'zh-CN': '先躺一下。开始太难了，不知不觉就睡着了',
        'zh-TW': '先躺一下。開始太難了，不知不覺就睡著了',
        vi: 'Nằm xuống trước. Bắt đầu quá khó và rồi tôi ngủ luôn.',
        id: 'Rebahan dulu. Memulai terlalu sulit dan tahu-tahu tertidur.',
    }), 0),
      opt(localeMap({
        ko: '공부 플레이리스트를 켜고 커피를 내린다. 분위기가 잡혀야 공부가 된다',
        en: 'Turn on a study playlist and make coffee. I need the mood.',
        ja: '勉強用プレイリストとコーヒー。雰囲気が必要',
        'zh-CN': '打开学习歌单、冲咖啡。需要氛围',
        'zh-TW': '打開學習歌單、沖咖啡。需要氛圍',
        vi: 'Bật playlist học và pha cà phê. Tôi cần không khí.',
        id: 'Nyalakan playlist belajar dan buat kopi. Aku butuh suasana.',
    }), 1),
      opt(localeMap({
        ko: '오늘 외울 것들을 나열하고 몇 번 반복할지 정한다. 일단 외우면 뭔가 된 것 같다',
        en: 'List what to memorize and how many repetitions to do.',
        ja: '覚えることと反復回数を決める',
        'zh-CN': '列出要背的内容和重复次数',
        'zh-TW': '列出要背的內容和重複次數',
        vi: 'Liệt kê điều cần thuộc và số lần lặp.',
        id: 'Daftar yang harus dihafal dan berapa kali mengulang.',
    }), 2),
      opt(localeMap({
        ko: '오늘 공부할 범위를 정하고 어떤 순서로 이해해나갈지 먼저 구조를 파악한다',
        en: 'Set the scope and understand the learning structure first.',
        ja: '範囲と理解する順序の構造を先に把握する',
        'zh-CN': '先确定范围和理解顺序的结构',
        'zh-TW': '先確定範圍和理解順序的結構',
        vi: 'Xác định phạm vi và cấu trúc cần hiểu trước.',
        id: 'Tentukan cakupan dan pahami struktur belajarnya dahulu.',
    }), 3),
    ],
  },
  {
    id: 2,
    question: localeMap({
      ko: '시험이 2주 남았다는 것을 방금 깨달았다. 나는?',
      en: 'You just realized the exam is two weeks away. What do you do?',
      ja: '試験まで2週間だと今気づいた。私は？',
      'zh-CN': '刚发现考试只剩两周。我会？',
      'zh-TW': '剛發現考試只剩兩週。我會？',
      vi: 'Bạn vừa nhận ra còn hai tuần nữa là thi. Bạn?',
      id: 'Baru sadar ujian tinggal dua minggu. Aku?',
    }),
    options: [
      opt(localeMap({
        ko: '아직 2주나 있다. 다음 주에 시작해도 충분하다. 일단 오늘은 쉰다',
        en: 'Two weeks is plenty. I will start next week; today I rest.',
        ja: 'まだ2週間ある。来週始めれば十分、今日は休む',
        'zh-CN': '还有两周呢。下周开始就够，今天先休息',
        'zh-TW': '還有兩週呢。下週開始就夠，今天先休息',
        vi: 'Còn tận hai tuần. Tuần sau học, hôm nay nghỉ.',
        id: 'Masih dua minggu. Minggu depan mulai saja, hari ini istirahat.',
    }), 0),
      opt(localeMap({
        ko: '일단 예쁜 공부 스케줄 양식을 찾아보기 시작한다. 계획표가 멋있어야 의욕이 생긴다',
        en: 'Look for a beautiful study schedule template first.',
        ja: 'まずおしゃれな勉強スケジュール表を探す',
        'zh-CN': '先找一张漂亮的学习计划表',
        'zh-TW': '先找一張漂亮的學習計畫表',
        vi: 'Tìm mẫu lịch học đẹp trước.',
        id: 'Cari template jadwal belajar yang cantik dulu.',
    }), 1),
      opt(localeMap({
        ko: '외워야 할 것들 목록을 작성한다. 시험은 결국 얼마나 많이 외웠느냐의 싸움이다',
        en: 'Make a list of things to memorize.',
        ja: '覚えるもののリストを作る',
        'zh-CN': '列出要背的内容',
        'zh-TW': '列出要背的內容',
        vi: 'Lập danh sách những thứ phải thuộc.',
        id: 'Buat daftar hal yang harus dihafal.',
    }), 2),
      opt(localeMap({
        ko: '시험 범위를 파악하고 이해해야 할 개념과 암기해야 할 것을 분류해서 계획을 세운다',
        en: 'Classify concepts to understand and things to memorize, then plan.',
        ja: '理解と暗記を分類して計画を立てる',
        'zh-CN': '区分要理解的概念与要背的内容后计划',
        'zh-TW': '區分要理解的概念與要背的內容後計畫',
        vi: 'Phân loại phần cần hiểu và cần thuộc rồi lập kế hoạch.',
        id: 'Klasifikasikan konsep yang dipahami dan yang dihafal, lalu rencanakan.',
    }), 3),
    ],
  },
  {
    id: 3,
    question: localeMap({
      ko: '공부하기 가장 좋은 나만의 환경은?',
      en: 'What is your best study environment?',
      ja: '自分にとって最も勉強しやすい環境は？',
      'zh-CN': '最适合我的学习环境是？',
      'zh-TW': '最適合我的學習環境是？',
      vi: 'Môi trường học tốt nhất của bạn là?',
      id: 'Lingkungan belajar terbaik bagiku adalah?',
    }),
    options: [
      opt(localeMap({
        ko: '사실 어디서든 집중이 안 된다. 환경보다 의지의 문제인 것 같은데 의지가 없다',
        en: 'I cannot focus anywhere. It seems like a willpower problem.',
        ja: 'どこでも集中できない。意志力の問題だと思う',
        'zh-CN': '其实哪里都无法专注，像是意志力问题',
        'zh-TW': '其實哪裡都無法專注，像是意志力問題',
        vi: 'Thật ra tôi không tập trung được ở đâu cả.',
        id: 'Sebenarnya aku tidak bisa fokus di mana pun.',
    }), 0),
      opt(localeMap({
        ko: '카페 배경음이 있어야 한다. 조용하면 오히려 집중이 안 된다. 분위기가 핵심이다',
        en: 'A café soundtrack; silence makes focus harder. Mood is key.',
        ja: 'カフェ音が必要。静かだと集中できず、雰囲気が鍵',
        'zh-CN': '需要咖啡馆背景音；氛围是关键',
        'zh-TW': '需要咖啡館背景音；氛圍是關鍵',
        vi: 'Cần tiếng nền quán cà phê; không khí là then chốt.',
        id: 'Butuh suara kafe; suasana adalah kuncinya.',
    }), 1),
      opt(localeMap({
        ko: '혼자 조용한 방에서 입으로 소리 내가며 반복 암기하는 게 가장 잘 된다',
        en: 'A quiet room alone, repeating aloud.',
        ja: '一人の静かな部屋で声に出して反復する',
        'zh-CN': '独自在安静房间里出声重复',
        'zh-TW': '獨自在安靜房間裡出聲重複',
        vi: 'Một mình trong phòng yên tĩnh, đọc lặp thành tiếng.',
        id: 'Sendiri di kamar tenang sambil mengulang dengan suara.',
    }), 2),
      opt(localeMap({
        ko: '집중을 방해하는 것이 없는 환경. 책상 위는 공부 도구만 있어야 한다',
        en: 'No distractions, with only study tools on my desk.',
        ja: '邪魔がなく、机には勉強道具だけの環境',
        'zh-CN': '没有干扰，桌上只放学习工具',
        'zh-TW': '沒有干擾，桌上只放學習工具',
        vi: 'Không có thứ gây xao nhãng, bàn chỉ có dụng cụ học.',
        id: 'Tanpa gangguan, meja hanya berisi alat belajar.',
    }), 3),
    ],
  },
  {
    id: 4,
    question: localeMap({
      ko: '공부 중 핸드폰 알림이 왔다. 나는?',
      en: 'A phone notification arrives while studying. You?',
      ja: '勉強中にスマホ通知が来た。私は？',
      'zh-CN': '学习时手机来了通知。我会？',
      'zh-TW': '學習時手機來了通知。我會？',
      vi: 'Đang học thì điện thoại báo tin. Bạn?',
      id: 'Saat belajar ada notifikasi ponsel. Aku?',
    }),
    options: [
      opt(localeMap({
        ko: '당연히 본다. 어차피 집중 안 되고 있었다. 그냥 잠깐 보다가 한 시간이 된다',
        en: 'Of course I check. I was not focused anyway, then an hour passes.',
        ja: 'もちろん見る。どうせ集中しておらず、1時間が過ぎる',
        'zh-CN': '当然看，反正没专注，结果一小时过去了',
        'zh-TW': '當然看，反正沒專注，結果一小時過去了',
        vi: 'Dĩ nhiên xem. Vốn không tập trung, rồi một giờ trôi qua.',
        id: 'Tentu lihat. Memang tidak fokus, tahu-tahu satu jam lewat.',
    }), 0),
      opt(localeMap({
        ko: '공부용 플레이리스트 앱을 끄지 않으려고 조심스럽게 확인하고 다시 분위기를 잡는다',
        en: 'Check carefully without closing my playlist, then rebuild the mood.',
        ja: 'プレイリストを消さないよう確認して、雰囲気を作り直す',
        'zh-CN': '小心查看不关掉歌单，再找回氛围',
        'zh-TW': '小心查看不關掉歌單，再找回氛圍',
        vi: 'Kiểm tra cẩn thận để không tắt playlist rồi lấy lại cảm hứng.',
        id: 'Cek hati-hati agar playlist tidak tertutup, lalu bangun suasana lagi.',
    }), 1),
      opt(localeMap({
        ko: '지금 반복하던 것을 끝까지 마친 다음에 확인한다. 흐름이 끊기면 다시 시작하기 어렵다',
        en: 'Finish the current repetition first; restarting the flow is hard.',
        ja: '今の反復を終えてから見る。流れを切りたくない',
        'zh-CN': '先完成正在重复的内容，流程断了很难重来',
        'zh-TW': '先完成正在重複的內容，流程斷了很難重來',
        vi: 'Xong lượt lặp hiện tại mới xem; khó bắt lại nhịp.',
        id: 'Selesaikan pengulangan dulu; sulit memulai alur lagi.',
    }), 2),
      opt(localeMap({
        ko: '무음 모드로 뒤집어놓고 정해진 쉬는 시간에만 확인한다. 집중 구간엔 아무것도 보지 않는다',
        en: 'Put it face down on silent mode and check only during breaks.',
        ja: '無音で伏せ、決めた休憩時間だけ確認する',
        'zh-CN': '静音扣放，只在休息时间查看',
        'zh-TW': '靜音扣放，只在休息時間查看',
        vi: 'Úp máy ở chế độ im lặng, chỉ xem lúc nghỉ.',
        id: 'Balikkan dalam mode senyap dan cek hanya saat istirahat.',
    }), 3),
    ],
  },
  {
    id: 5,
    question: localeMap({
      ko: '새로운 개념이나 내용을 처음 공부할 때 나는?',
      en: 'When first learning a new concept, you?',
      ja: '新しい概念を初めて学ぶとき、私は？',
      'zh-CN': '第一次学新概念时，我会？',
      'zh-TW': '第一次學新概念時，我會？',
      vi: 'Khi học khái niệm mới lần đầu, bạn?',
      id: 'Saat pertama belajar konsep baru, aku?',
    }),
    options: [
      opt(localeMap({
        ko: '일단 빠르게 훑는다. 나중에 시험 전날 다시 보면 어떻게든 된다',
        en: 'Skim quickly. I can somehow manage the night before.',
        ja: '素早く流し見する。前日に何とかなる',
        'zh-CN': '快速浏览，考前一天总会有办法',
        'zh-TW': '快速瀏覽，考前一天總會有辦法',
        vi: 'Lướt nhanh. Đêm trước thi rồi cũng xoay xở được.',
        id: 'Baca cepat. Malam sebelum ujian pasti bisa diakali.',
    }), 0),
      opt(localeMap({
        ko: '예쁘게 노트 필기를 한다. 정리된 노트를 보면 뿌듯하고 기억에도 잘 남는 것 같다',
        en: 'Make pretty notes. Organized notes feel memorable.',
        ja: 'きれいにノートを取る。整理されたノートは覚えやすい',
        'zh-CN': '做漂亮笔记，整理好的笔记似乎更好记',
        'zh-TW': '做漂亮筆記，整理好的筆記似乎更好記',
        vi: 'Ghi chép đẹp; vở gọn gàng có vẻ dễ nhớ.',
        id: 'Membuat catatan cantik; catatan rapi terasa mudah diingat.',
    }), 1),
      opt(localeMap({
        ko: '중요한 것에 형광펜을 치고 반복해서 읽으며 눈에 익힌다. 여러 번 보면 외워진다',
        en: 'Highlight key parts and reread them until familiar.',
        ja: '重要箇所に線を引き、慣れるまで繰り返し読む',
        'zh-CN': '标出重点并反复阅读直到熟悉',
        'zh-TW': '標出重點並反覆閱讀直到熟悉',
        vi: 'Tô phần quan trọng và đọc lại đến khi quen.',
        id: 'Menyorot bagian penting dan membaca berulang sampai akrab.',
    }), 2),
      opt(localeMap({
        ko: '이 개념이 왜 이렇게 성립하는지 원리부터 이해한다. 이해 없이 외운 것은 금방 잊어버린다',
        en: 'Understand why the concept works before memorizing it.',
        ja: 'なぜ成り立つか原理から理解する',
        'zh-CN': '先理解概念为何成立的原理',
        'zh-TW': '先理解概念為何成立的原理',
        vi: 'Hiểu nguyên lý vì sao khái niệm này đúng trước.',
        id: 'Pahami dulu mengapa konsep ini berlaku.',
    }), 3),
    ],
  },
  {
    id: 6,
    question: localeMap({
      ko: '공부하다가 이해가 안 되는 부분이 나왔다. 나는?',
      en: 'You encounter something you do not understand while studying. You?',
      ja: '勉強中に理解できない部分が出た。私は？',
      'zh-CN': '学习中遇到不懂的部分。我会？',
      'zh-TW': '學習中遇到不懂的部分。我會？',
      vi: 'Gặp phần không hiểu khi học, bạn?',
      id: 'Saat belajar ada bagian yang tidak dipahami. Aku?',
    }),
    options: [
      opt(localeMap({
        ko: '일단 넘어간다. 시험에 안 나올 수도 있다. 어쩌면 감으로 맞힐 수도 있다',
        en: 'Skip it. It may not be on the exam; perhaps I can guess.',
        ja: '飛ばす。試験に出ないかもしれないし、勘で当たるかも',
        'zh-CN': '先跳过，可能不考，也许能蒙对',
        'zh-TW': '先跳過，可能不考，也許能蒙對',
        vi: 'Bỏ qua. Có thể không thi, biết đâu đoán đúng.',
        id: 'Lewati saja. Mungkin tidak keluar ujian, bisa saja menebak benar.',
    }), 0),
      opt(localeMap({
        ko: '유튜브에서 관련 영상을 찾아본다. 영상 보다가 다른 영상으로 넘어가는 경우도 있다',
        en: 'Find a related YouTube video, sometimes drifting to another video.',
        ja: 'YouTubeで動画を探すが、別動画に移ることもある',
        'zh-CN': '在YouTube找相关视频，有时又看了别的视频',
        'zh-TW': '在YouTube找相關影片，有時又看了別的影片',
        vi: 'Tìm video YouTube liên quan, đôi khi lại xem video khác.',
        id: 'Cari video terkait di YouTube, kadang pindah ke video lain.',
    }), 1),
      opt(localeMap({
        ko: '일단 통째로 외운다. 이해는 못 해도 답을 아는 것이 중요하다',
        en: 'Memorize it whole. Knowing the answer matters more.',
        ja: '丸ごと暗記する。理解より答えを知る方が重要',
        'zh-CN': '整段背下来，知道答案更重要',
        'zh-TW': '整段背下來，知道答案更重要',
        vi: 'Học thuộc nguyên phần đó. Biết đáp án quan trọng hơn.',
        id: 'Hafalkan saja. Mengetahui jawaban lebih penting.',
    }), 2),
      opt(localeMap({
        ko: '이해될 때까지 자료를 찾고 선생님이나 친구에게 물어보고 넘어간다. 모르는 채로 넘기면 불안하다',
        en: 'Research and ask until I understand; I cannot move on unsure.',
        ja: '理解できるまで調べて聞く。知らないまま進めない',
        'zh-CN': '查资料、问人直到理解，不能带着疑问过去',
        'zh-TW': '查資料、問人直到理解，不能帶著疑問過去',
        vi: 'Tìm tài liệu và hỏi đến khi hiểu; không thể bỏ qua.',
        id: 'Cari bahan dan bertanya sampai paham; tidak bisa lanjut tanpa tahu.',
    }), 3),
    ],
  },
  {
    id: 7,
    question: localeMap({
      ko: '공부를 시작한 지 20분 만에 집중이 완전히 흐트러졌다. 나는?',
      en: 'After only 20 minutes, your focus has completely slipped. You?',
      ja: '勉強開始20分で集中が完全に切れた。私は？',
      'zh-CN': '刚学20分钟就完全走神了。我会？',
      'zh-TW': '剛學20分鐘就完全走神了。我會？',
      vi: 'Mới học 20 phút đã mất tập trung hoàn toàn. Bạn?',
      id: 'Baru 20 menit belajar, fokus sudah buyar. Aku?',
    }),
    options: [
      opt(localeMap({
        ko: '그냥 쉬기로 한다. 안 되는 공부 억지로 해봐야 소용없다. 내일 다시 하면 된다',
        en: 'Decide to rest. Forcing it is useless; tomorrow is another day.',
        ja: '休むことにする。無理しても無駄、明日またやる',
        'zh-CN': '决定休息，勉强学习也没用，明天再来',
        'zh-TW': '決定休息，勉強學習也沒用，明天再來',
        vi: 'Nghỉ thôi. Ép học cũng vô ích, mai học lại.',
        id: 'Memutuskan istirahat. Memaksa belajar percuma, besok lagi.',
    }), 0),
      opt(localeMap({
        ko: '공부 브이로그를 튼다. 같이 공부하는 느낌이 들어야 다시 집중이 된다',
        en: 'Play a study vlog; feeling like I study with someone restores focus.',
        ja: '勉強Vlogをつける。一緒に勉強する感覚で戻る',
        'zh-CN': '放学习Vlog，有人陪学的感觉才能重拾专注',
        'zh-TW': '放學習Vlog，有人陪學的感覺才能重拾專注',
        vi: 'Mở vlog học tập; cảm giác học cùng ai đó giúp tập trung lại.',
        id: 'Nyalakan vlog belajar; rasa belajar bersama mengembalikan fokus.',
    }), 1),
      opt(localeMap({
        ko: '외울 것을 처음부터 다시 반복한다. 반복하다 보면 집중이 다시 잡힌다',
        en: 'Repeat the material from the beginning until focus returns.',
        ja: '最初から反復する。繰り返すと集中が戻る',
        'zh-CN': '从头再重复，重复中专注会回来',
        'zh-TW': '從頭再重複，重複中專注會回來',
        vi: 'Lặp lại từ đầu; cứ lặp thì tập trung sẽ trở lại.',
        id: 'Ulangi dari awal; fokus kembali saat mengulang.',
    }), 2),
      opt(localeMap({
        ko: '5분 휴식을 취한 다음 다시 타이머를 맞추고 시작한다. 뽀모도로 기법이나 집중 루틴으로 복구한다',
        en: 'Take five minutes, reset a timer, and use a focus routine.',
        ja: '5分休み、タイマーと集中ルーティンで再開する',
        'zh-CN': '休息五分钟，重新设定计时器和专注流程',
        'zh-TW': '休息五分鐘，重新設定計時器和專注流程',
        vi: 'Nghỉ năm phút, đặt lại hẹn giờ và quy trình tập trung.',
        id: 'Istirahat lima menit, atur ulang timer dan rutinitas fokus.',
    }), 3),
    ],
  },
  {
    id: 8,
    question: localeMap({
      ko: '시험 공부를 하다가 슬럼프가 왔다. 아무것도 머릿속에 들어오지 않는다. 나는?',
      en: 'You hit a study slump and nothing goes into your head. You?',
      ja: '試験勉強中にスランプ。何も頭に入らない。私は？',
      'zh-CN': '备考时陷入低潮，什么都记不进去。我会？',
      'zh-TW': '備考時陷入低潮，什麼都記不進去。我會？',
      vi: 'Bạn sa sút khi ôn thi, không gì vào đầu. Bạn?',
      id: 'Saat belajar ujian kamu slump dan tidak ada yang masuk kepala. Aku?',
    }),
    options: [
      opt(localeMap({
        ko: '이미 슬럼프가 아니라 원래 안 하고 있었다. 이 상태가 일상이다',
        en: 'It is not a slump; I was not studying in the first place.',
        ja: 'スランプではなく、もともとやっていない',
        'zh-CN': '不是低潮，本来就没在学',
        'zh-TW': '不是低潮，本來就沒在學',
        vi: 'Không phải slump, vốn dĩ tôi đã không học.',
        id: 'Bukan slump; memang dari awal tidak belajar.',
    }), 0),
      opt(localeMap({
        ko: '공부 감성 유튜브를 틀어놓고 노트를 예쁘게 다시 정리해본다. 뭐든 하는 것 같은 느낌이 든다',
        en: 'Play aesthetic study videos and rewrite my notes nicely.',
        ja: '勉強感性動画を流し、ノートをきれいに書き直す',
        'zh-CN': '放学习氛围视频，把笔记重新整理漂亮',
        'zh-TW': '放學習氛圍影片，把筆記重新整理漂亮',
        vi: 'Mở video học cảm hứng và chép lại vở cho đẹp.',
        id: 'Nyalakan video belajar estetik dan tulis ulang catatan dengan rapi.',
    }), 1),
      opt(localeMap({
        ko: '암기 카드를 꺼내서 이미 외운 것들을 다시 훑는다. 아는 것들을 확인하면 다시 의지가 생긴다',
        en: 'Review flashcards I already know to regain motivation.',
        ja: '知っている暗記カードを見直して意欲を戻す',
        'zh-CN': '翻看已背会的卡片来重获动力',
        'zh-TW': '翻看已背會的卡片來重獲動力',
        vi: 'Xem lại thẻ đã thuộc để lấy lại động lực.',
        id: 'Tinjau kartu hafalan yang sudah dikuasai untuk mengembalikan motivasi.',
    }), 2),
      opt(localeMap({
        ko: '공부 범위를 다시 점검하고 어느 부분이 부족한지 파악해서 우선순위를 재정비한다',
        en: 'Check the scope and reprioritize what is lacking.',
        ja: '範囲を見直し、不足部分の優先順位を立て直す',
        'zh-CN': '重新检查范围，调整薄弱部分的优先级',
        'zh-TW': '重新檢查範圍，調整薄弱部分的優先級',
        vi: 'Kiểm tra lại phạm vi và sắp xếp lại ưu tiên phần thiếu.',
        id: 'Periksa cakupan lagi dan atur ulang prioritas yang kurang.',
    }), 3),
    ],
  },
  {
    id: 9,
    question: localeMap({
      ko: '시험 전날 밤, 나는?',
      en: 'On the night before the exam, you?',
      ja: '試験前日の夜、私は？',
      'zh-CN': '考试前一晚，我会？',
      'zh-TW': '考試前一晚，我會？',
      vi: 'Tối trước ngày thi, bạn?',
      id: 'Malam sebelum ujian, aku?',
    }),
    options: [
      opt(localeMap({
        ko: '그날 처음으로 제대로 공부를 시작한다. 밤을 새우면 어떻게든 된다는 걸 경험으로 안다',
        en: 'Start studying properly for the first time and pull an all-nighter.',
        ja: 'その日初めて本格的に勉強し、徹夜する',
        'zh-CN': '那天才第一次认真学习，熬夜',
        'zh-TW': '那天才第一次認真學習，熬夜',
        vi: 'Lần đầu học nghiêm túc và thức trắng.',
        id: 'Baru mulai belajar sungguh-sungguh dan begadang.',
    }), 0),
      opt(localeMap({
        ko: '감성 조명을 켜고 좋아하는 음악을 틀면서 벼락치기를 시작한다. 분위기만큼은 최고다',
        en: 'Turn on mood lighting and music while cramming.',
        ja: '感性照明と音楽で徹夜勉強を始める',
        'zh-CN': '开氛围灯和音乐开始突击',
        'zh-TW': '開氛圍燈和音樂開始突擊',
        vi: 'Bật đèn và nhạc cảm hứng khi học nước rút.',
        id: 'Nyalakan lampu suasana dan musik sambil kebut belajar.',
    }), 1),
      opt(localeMap({
        ko: '외워야 할 것들을 마지막으로 빠르게 반복한다. 자고 일어나면 잊어버릴까봐 최대한 여러 번 본다',
        en: 'Rapidly repeat everything I must memorize one last time.',
        ja: '覚えるものを最後に高速で反復する',
        'zh-CN': '最后快速重复所有要背的内容',
        'zh-TW': '最後快速重複所有要背的內容',
        vi: 'Lặp nhanh những thứ phải thuộc lần cuối.',
        id: 'Mengulang cepat semua yang harus dihafal untuk terakhir kali.',
    }), 2),
      opt(localeMap({
        ko: '이미 복습을 끝낸 상태다. 전날 밤엔 가볍게 정리하고 일찍 잔다. 컨디션 관리가 마지막 공부다',
        en: 'I already reviewed; I lightly organize and sleep early.',
        ja: '復習済み。軽く整理して早く寝る',
        'zh-CN': '早已复习完，简单整理后早睡',
        'zh-TW': '早已複習完，簡單整理後早睡',
        vi: 'Đã ôn xong, chỉ sắp xếp nhẹ rồi ngủ sớm.',
        id: 'Sudah mengulang; merapikan sedikit lalu tidur awal.',
    }), 3),
    ],
  },
  {
    id: 10,
    question: localeMap({
      ko: '시험 당일 아침, 나는?',
      en: 'On the morning of the exam, you?',
      ja: '試験当日の朝、私は？',
      'zh-CN': '考试当天早上，我会？',
      'zh-TW': '考試當天早上，我會？',
      vi: 'Sáng ngày thi, bạn?',
      id: 'Pagi hari ujian, aku?',
    }),
    options: [
      opt(localeMap({
        ko: '전날 밤샘으로 피폐한 상태다. 시험지를 보는 순간 어제 외운 것들이 사라지는 경험을 한다',
        en: 'I am exhausted from staying up, and what I learned disappears.',
        ja: '徹夜で疲弊し、見た瞬間に昨日覚えたことが消える',
        'zh-CN': '熬夜后很疲惫，看到试卷昨天背的全消失',
        'zh-TW': '熬夜後很疲憊，看到試卷昨天背的全消失',
        vi: 'Kiệt sức vì thức đêm, kiến thức hôm qua biến mất.',
        id: 'Lelah karena begadang, hafalan kemarin menghilang.',
    }), 0),
      opt(localeMap({
        ko: '오늘 입을 옷과 들고 갈 음료를 먼저 결정한다. 시험장 분위기가 중요하다',
        en: 'Choose my outfit and drink first; exam venue mood matters.',
        ja: '服と飲み物を先に決める。会場の雰囲気が大切',
        'zh-CN': '先决定穿什么、带什么喝的，考场氛围很重要',
        'zh-TW': '先決定穿什麼、帶什麼喝的，考場氛圍很重要',
        vi: 'Chọn đồ mặc và nước uống trước; không khí phòng thi quan trọng.',
        id: 'Pilih pakaian dan minuman dulu; suasana ruang ujian penting.',
    }), 1),
      opt(localeMap({
        ko: '등교하는 동안 암기 카드를 본다. 이동 중에도 반복하면 기억에 남는다',
        en: 'Read flashcards on the way to school.',
        ja: '登校中も暗記カードを見る',
        'zh-CN': '上学路上也看记忆卡',
        'zh-TW': '上學路上也看記憶卡',
        vi: 'Xem thẻ ghi nhớ trên đường đến trường.',
        id: 'Melihat kartu hafalan dalam perjalanan ke sekolah.',
    }), 2),
      opt(localeMap({
        ko: '전날 정리한 요약 노트를 마지막으로 한 번 훑는다. 핵심 개념을 눈에 담고 시험장에 들어간다',
        en: 'Skim my summary notes once more and enter with core concepts.',
        ja: '要約ノートを最後に見て、核心概念を頭に入れて行く',
        'zh-CN': '最后扫一遍总结笔记，带着核心概念进考场',
        'zh-TW': '最後掃一遍總結筆記，帶著核心概念進考場',
        vi: 'Lướt ghi chú tóm tắt lần cuối rồi vào phòng thi.',
        id: 'Meninjau catatan ringkasan sekali lagi lalu masuk.',
    }), 3),
    ],
  },
  {
    id: 11,
    question: localeMap({
      ko: '시험이 끝났다. 생각보다 못 봤다. 나는?',
      en: 'The exam is over and you did worse than expected. You?',
      ja: '試験が終わり、思ったよりできなかった。私は？',
      'zh-CN': '考完比预想差。我会？',
      'zh-TW': '考完比預想差。我會？',
      vi: 'Thi xong, bạn làm kém hơn mong đợi. Bạn?',
      id: 'Ujian selesai dan hasilku lebih buruk dari dugaan. Aku?',
    }),
    options: [
      opt(localeMap({
        ko: '예상했다. 원래 이렇게 본다. 다음엔 진짜 열심히 해야지(를 매번 반복한다)',
        en: 'As expected. I promise to work hard next time, again.',
        ja: '予想通り。次こそ頑張るを毎回繰り返す',
        'zh-CN': '不意外。又一次说下次一定努力',
        'zh-TW': '不意外。又一次說下次一定努力',
        vi: 'Đúng như dự đoán. Lại hứa lần sau sẽ chăm chỉ.',
        id: 'Sudah diduga. Lagi-lagi janji akan rajin lain kali.',
    }), 0),
      opt(localeMap({
        ko: '시험 끝 기념 카페를 가면서 잊어버린다. 어차피 지난 일이다. 오늘은 쉬자',
        en: 'Forget it at a celebratory café. Today is for resting.',
        ja: '記念にカフェへ行って忘れる。今日は休む',
        'zh-CN': '去咖啡馆庆祝并忘掉它，今天休息',
        'zh-TW': '去咖啡館慶祝並忘掉它，今天休息',
        vi: 'Đi quán cà phê ăn mừng rồi quên đi. Hôm nay nghỉ.',
        id: 'Pergi ke kafe merayakan lalu melupakannya. Hari ini istirahat.',
    }), 1),
      opt(localeMap({
        ko: '어떤 걸 못 외웠는지 확인한다. 다음엔 더 많이 반복하면 된다',
        en: 'Check what I failed to memorize; next time I will repeat more.',
        ja: '覚えられなかったものを確認し、次はもっと反復する',
        'zh-CN': '确认哪些没背住，下次多重复',
        'zh-TW': '確認哪些沒背住，下次多重複',
        vi: 'Kiểm tra phần chưa thuộc; lần sau lặp nhiều hơn.',
        id: 'Cek yang belum hafal; lain kali mengulang lebih banyak.',
    }), 2),
      opt(localeMap({
        ko: '어떤 개념이 부족했는지 분석한다. 틀린 이유를 파악해야 다음에 같은 실수를 안 한다',
        en: 'Analyze missing concepts so I do not repeat the same mistake.',
        ja: '不足した概念を分析し、同じミスを防ぐ',
        'zh-CN': '分析缺少的概念，避免下次犯同样错误',
        'zh-TW': '分析缺少的概念，避免下次犯同樣錯誤',
        vi: 'Phân tích thiếu khái niệm nào để không lặp lỗi.',
        id: 'Analisis konsep yang kurang agar tidak mengulangi kesalahan.',
    }), 3),
    ],
  },
  {
    id: 12,
    question: localeMap({
      ko: '시험 공부에 대한 나의 솔직한 평가는?',
      en: 'Your honest assessment of exam study is?',
      ja: '試験勉強についての正直な評価は？',
      'zh-CN': '你对备考的真实评价是？',
      'zh-TW': '你對備考的真實評價是？',
      vi: 'Đánh giá thật lòng của bạn về việc ôn thi?',
      id: 'Penilaian jujurku tentang belajar ujian?',
    }),
    options: [
      opt(localeMap({
        ko: '매번 후회하면서 매번 똑같이 한다. 이게 나다. 어쩔 수 없다',
        en: 'I regret it every time yet do the same thing. This is me.',
        ja: '毎回後悔しながら同じことをする。これが私',
        'zh-CN': '每次后悔却每次一样，这就是我',
        'zh-TW': '每次後悔卻每次一樣，這就是我',
        vi: 'Lần nào cũng hối hận nhưng vẫn như cũ. Đó là tôi.',
        id: 'Selalu menyesal tapi tetap melakukan hal sama. Itulah aku.',
    }), 0),
      opt(localeMap({
        ko: '공부하는 환경과 분위기를 만드는 데는 자신 있다. 내용이 얼마나 들어가는지는 별개다',
        en: 'I can create a great study environment; learning content is separate.',
        ja: '勉強環境づくりには自信がある。内容は別問題',
        'zh-CN': '很会营造学习环境，学进去多少是另一回事',
        'zh-TW': '很會營造學習環境，學進去多少是另一回事',
        vi: 'Tôi giỏi tạo môi trường học; học được bao nhiêu là chuyện khác.',
        id: 'Aku jago menciptakan lingkungan belajar; isi yang masuk soal lain.',
    }), 1),
      opt(localeMap({
        ko: '성실하게 반복하는 편이다. 이해는 못 해도 외우면 어떻게든 된다고 생각한다',
        en: 'I repeat diligently. Even without understanding, memorizing works.',
        ja: '真面目に反復する。理解できなくても覚えれば何とかなる',
        'zh-CN': '我会认真重复，不懂也能靠背下来',
        'zh-TW': '我會認真重複，不懂也能靠背下來',
        vi: 'Tôi lặp lại chăm chỉ; không hiểu vẫn có thể học thuộc.',
        id: 'Aku tekun mengulang. Meski tidak paham, hafalan bisa membantu.',
    }), 2),
      opt(localeMap({
        ko: '체계적으로 공부한다. 시간이 걸려도 제대로 이해하고 정리하는 것이 결국 더 효율적이라고 믿는다',
        en: 'I study systematically. Proper understanding and organization are efficient.',
        ja: '体系的に学ぶ。時間がかかっても理解と整理が効率的',
        'zh-CN': '我系统学习，真正理解和整理最终更有效率',
        'zh-TW': '我系統學習，真正理解和整理最終更有效率',
        vi: 'Tôi học có hệ thống; hiểu và sắp xếp đúng mới hiệu quả.',
        id: 'Aku belajar sistematis; memahami dan merapikan dengan benar lebih efisien.',
    }), 3),
    ],
  },
];

export const phase3ExamStudyTypeResults: Phase3ExamStudyTypeResult[] = [
  {
    type: "Type1",
    emoji: "⚡",
    title: localeMap({
      ko: '전날 밤이 진짜 공부 시간인 사람, 벼락치기 레전드형',
      en: 'The Real Study Time Is the Night Before, Cram Legend Type',
      ja: '前日の夜が本当の勉強時間の人、徹夜レジェンド型',
      'zh-CN': '前一晚才是真正学习时间的人，突击传奇型',
      'zh-TW': '前一晚才是真正學習時間的人，突擊傳奇型',
      vi: 'Người có thời gian học thật sự là đêm trước, Kiểu huyền thoại nước rút',
      id: 'Orang yang waktu belajarnya sebenarnya malam sebelum ujian, Tipe Legenda Kebut',
    }),
    studySummary: localeMap({
      ko: '시험 전날 밤이 황금 집중 타임인 타입',
      en: 'Golden focus time is the night before the exam',
      ja: '試験前日の夜が黄金の集中時間',
      'zh-CN': '考试前一晚是黄金专注时间',
      'zh-TW': '考試前一晚是黃金專注時間',
      vi: 'Đêm trước thi là giờ tập trung vàng',
      id: 'Malam sebelum ujian adalah waktu fokus emas',
    }),
    quote: localeMap({
      ko: '당신에게 D-1은 위기가 아닙니다. 이때부터가 진짜입니다. 아드레날린이 공부 동력입니다.',
      en: 'D-1 is not a crisis for you. This is when it really begins. Adrenaline fuels your studying.',
      ja: 'あなたにとってD-1は危機ではありません。ここからが本番。アドレナリンが学習の燃料です。',
      'zh-CN': '对你而言D-1不是危机，这才是真正开始。肾上腺素是学习动力。',
      'zh-TW': '對你而言D-1不是危機，這才是真正開始。腎上腺素是學習動力。',
      vi: 'Với bạn, D-1 không phải khủng hoảng. Đây mới là lúc thật sự bắt đầu.',
      id: 'Bagi kamu, H-1 bukan krisis. Inilah saat yang sebenarnya dimulai.',
    }),
    description: localeMap({
      ko: '2주 전에는 아무것도 안 하다가 전날 밤 처음으로 책을 폅니다. 그리고 어떻게든 살아서 나옵니다. 이게 반복되면서 하나의 루틴이 됐습니다.',
      en: 'You open the book for the first time the night before, somehow survive, and repeat the routine.',
      ja: '前日の夜に初めて本を開き、何とか生還し、このルーティンを繰り返します。',
      'zh-CN': '前一晚才第一次打开书，然后不知怎么熬过来，反复如此。',
      'zh-TW': '前一晚才第一次打開書，然後不知怎麼撐過來，反覆如此。',
      vi: 'Bạn mở sách lần đầu vào đêm trước, xoay xở vượt qua rồi lặp lại.',
      id: 'Kamu baru membuka buku malam sebelumnya, entah bagaimana selamat, lalu mengulanginya.',
    }),
    studyType: localeMap({
      ko: '벼락치기 레전드형 ⚡',
      en: 'Cram Legend Type ⚡',
      ja: '徹夜レジェンド型 ⚡',
      'zh-CN': '突击传奇型 ⚡',
      'zh-TW': '突擊傳奇型 ⚡',
      vi: 'Kiểu huyền thoại nước rút ⚡',
      id: 'Tipe Legenda Kebut ⚡',
    }),
    studyKeywords: localeMap({
      ko: 'D-1·밤샘·아드레날린·기적·매번 후회',
      en: 'D-1 · All-nighter · Adrenaline · Miracle · Regret',
      ja: 'D-1・徹夜・アドレナリン・奇跡・毎回後悔',
      'zh-CN': 'D-1·熬夜·肾上腺素·奇迹·每次后悔',
      'zh-TW': 'D-1·熬夜·腎上腺素·奇蹟·每次後悔',
      vi: 'D-1 · Thức trắng · Adrenaline · Kỳ tích · Hối hận',
      id: 'H-1 · Begadang · Adrenalin · Keajaiban · Menyesal',
    }),
    strengths: localeMap({
      ko: '극한 압박 상황에서 집중력이 폭발. 시험 직전 정보 밀도가 높아짐',
      en: 'Focus explodes under extreme pressure; information density rises right before the exam.',
      ja: '極限の圧力で集中力が爆発し、直前の情報密度が高い。',
      'zh-CN': '极端压力下专注力爆发，考前信息密度高。',
      'zh-TW': '極端壓力下專注力爆發，考前資訊密度高。',
      vi: 'Tập trung bùng nổ dưới áp lực cao; hấp thụ dày đặc trước thi.',
      id: 'Fokus meledak di bawah tekanan ekstrem; informasi padat jelang ujian.',
    }),
    cautions: localeMap({
      ko: '장기 기억으로 남지 않음. 시험 일주일 후 다 잊어버림',
      en: 'It does not stay in long-term memory; a week later, it is all gone.',
      ja: '長期記憶に残らず、一週間後には忘れがち。',
      'zh-CN': '难进长期记忆，一周后全忘。',
      'zh-TW': '難進長期記憶，一週後全忘。',
      vi: 'Không vào trí nhớ dài hạn; một tuần sau đã quên.',
      id: 'Tidak masuk memori jangka panjang; seminggu kemudian hilang.',
    }),
    studyTip: localeMap({
      ko: '포기하지 말고 벼락치기를 최적화하기. 전날 밤엔 요약본만 보기. 빈출 문제 우선 공략',
      en: 'Optimize cramming: use only summaries and prioritize frequent questions.',
      ja: '徹夜を最適化。要約だけを見て頻出問題を優先。',
      'zh-CN': '优化突击：只看总结，优先高频题。',
      'zh-TW': '優化突擊：只看總結，優先高頻題。',
      vi: 'Tối ưu nước rút: chỉ xem tóm tắt, ưu tiên câu hay gặp.',
      id: 'Optimalkan kebut: lihat ringkasan dan dahulukan soal sering keluar.',
    }),
    typicalPhrase: localeMap({
      ko: '"이번엔 진짜 미리 할 거야"(를 매번 안 함)',
      en: '“This time I will start early.” (Then never does.)',
      ja: '「今回は本当に早く始める」（毎回やらない）',
      'zh-CN': '“这次真的会早点开始。”（但每次都没做）',
      'zh-TW': '「這次真的會早點開始。」（但每次都沒做）',
      vi: '“Lần này tôi sẽ bắt đầu sớm.” (Rồi lại không.)',
      id: '“Kali ini aku akan mulai awal.” (Tapi tidak pernah.)',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '매번 후회하면서 매번 살아남는 당신은 사실 위기 대처 능력이 뛰어난 사람입니다. 그 능력을 좀 더 일찍 써봐요',
      en: 'You survive every time you regret it; your crisis-response skill is real. Use it a little earlier.',
      ja: '毎回後悔しながら生還するあなたは危機対応が得意。その力を少し早く使おう。',
      'zh-CN': '每次后悔却都活下来，说明你很会应对危机。早点用这能力吧。',
      'zh-TW': '每次後悔卻都活下來，說明你很會應對危機。早點用這能力吧。',
      vi: 'Bạn luôn sống sót dù hối hận; hãy dùng khả năng ứng phó sớm hơn.',
      id: 'Kamu selalu selamat meski menyesal; pakai kemampuan krisismu lebih awal.',
    }),
    shareLine: localeMap({
      ko: '내 공부 유형: 벼락치기 레전드형 ⚡ 전날 밤이 진짜 공부 시간이래... \'이번엔 진짜 미리 할 거야\'를 매번 안 하는 거 맞음 ㅋㅋ → 나 이 유형이라 망함 ㅋㅋ 너는 어떤 유형이야?',
      en: 'My study type: Cram Legend ⚡ D-1 is my real study time… what is yours?',
      ja: '私の勉強タイプ：徹夜レジェンド型 ⚡ D-1が本番…あなたは？',
      'zh-CN': '我的学习类型：突击传奇型 ⚡ D-1才是正片…你呢？',
      'zh-TW': '我的學習類型：突擊傳奇型 ⚡ D-1才是正片…你呢？',
      vi: 'Kiểu học của tôi: Huyền thoại nước rút ⚡ Còn bạn?',
      id: 'Tipe belajarku: Legenda Kebut ⚡ Kalau kamu?',
    }),
  },
  {
    type: "Type2",
    emoji: "☕",
    title: localeMap({
      ko: '공부 분위기가 반은 먹고 들어가는 사람, 감성 공부형',
      en: 'Someone Whose Study Mood Does Half the Work, Aesthetic Study Type',
      ja: '勉強の雰囲気が半分を決める人、感性勉強型',
      'zh-CN': '学习氛围决定一半的人，氛围学习型',
      'zh-TW': '學習氛圍決定一半的人，氛圍學習型',
      vi: 'Người mà không khí học làm nên một nửa, Kiểu học cảm hứng',
      id: 'Orang yang suasana belajarnya menentukan setengah hasil, Tipe Belajar Estetis',
    }),
    studySummary: localeMap({
      ko: '환경·분위기·감성이 갖춰져야 공부가 되는 타입',
      en: 'Needs environment, mood, and feeling to study',
      ja: '環境・雰囲気・感性がそろうと勉強できるタイプ',
      'zh-CN': '环境、氛围和感觉齐备才能学习的类型',
      'zh-TW': '環境、氛圍和感覺齊備才能學習的類型',
      vi: 'Cần môi trường và cảm hứng để học',
      id: 'Butuh lingkungan dan suasana untuk belajar',
    }),
    quote: localeMap({
      ko: '당신에게 공부는 준비 과정이 50%입니다. 카페 자리, 플레이리스트, 커피 한 잔. 이게 갖춰져야 진짜 시작입니다.',
      en: 'Study prep is 50% of the work. Café seat, playlist, a cup of coffee — only then does real studying begin.',
      ja: 'あなたにとって勉強の準備が50%です。カフェの席、プレイリスト、コーヒー一杯。これが整って初めて本番です。',
      'zh-CN': '对你来说，学习准备占50%。咖啡馆座位、歌单、一杯咖啡——齐备了才真正开始。',
      'zh-TW': '對你來說，學習準備占50%。咖啡館座位、歌單、一杯咖啡——齊備了才真正開始。',
      vi: 'Chuẩn bị học chiếm 50%. Ghế quán cà phê, playlist, một ly cà phê — đủ rồi mới bắt đầu thật.',
      id: 'Persiapan belajar 50%. Kursi kafe, playlist, secangkir kopi — baru setelah itu belajar sungguh dimulai.',
    }),
    description: localeMap({
      ko: '공부 감성 유튜브를 틀고 예쁜 노트에 정리하고 조명을 맞추는 데 시간을 씁니다. 공부 준비가 너무 완벽해서 정작 내용에 쏟을 시간이 부족한 경우도 있습니다.',
      en: 'You spend time on study-aesthetic YouTube, pretty notes, and lighting. Prep can be so perfect there is little time left for the actual content.',
      ja: '勉強感性YouTubeをつけ、きれいなノート整理、照明調整に時間を使います。準備が完璧すぎて内容に使う時間が足りないことも。',
      'zh-CN': '你会花时间看学习氛围视频、整理漂亮笔记、调整灯光。准备太完美，反而没多少时间学内容。',
      'zh-TW': '你會花時間看學習氛圍影片、整理漂亮筆記、調整燈光。準備太完美，反而沒多少時間學內容。',
      vi: 'Bạn dành thời gian cho video cảm hứng học, ghi chép đẹp và ánh sáng. Chuẩn bị quá hoàn hảo nên ít thời gian cho nội dung.',
      id: 'Kamu habiskan waktu untuk video estetik belajar, catatan cantik, dan pencahayaan. Persiapan terlalu sempurna sehingga waktu untuk isi kurang.',
    }),
    studyType: localeMap({
      ko: '감성 공부형 ☕',
      en: 'Aesthetic Study Type ☕',
      ja: '感性勉強型 ☕',
      'zh-CN': '氛围学习型 ☕',
      'zh-TW': '氛圍學習型 ☕',
      vi: 'Kiểu học cảm hứng ☕',
      id: 'Tipe Belajar Estetis ☕',
    }),
    studyKeywords: localeMap({
      ko: '카페·플레이리스트·노트 정리·분위기·감성',
      en: 'Café · Playlist · Notes · Mood · Aesthetics',
      ja: 'カフェ・プレイリスト・ノート・雰囲気・感性',
      'zh-CN': '咖啡馆·歌单·笔记·氛围·感觉',
      'zh-TW': '咖啡館·歌單·筆記·氛圍·感覺',
      vi: 'Cà phê · Playlist · Ghi chép · Không khí · Cảm hứng',
      id: 'Kafe · Playlist · Catatan · Suasana · Estetika',
    }),
    strengths: localeMap({
      ko: '공부 환경을 잘 만들어서 진입 장벽이 낮음. 노트 정리 능력이 뛰어남',
      en: 'Creates a low barrier to starting and organizes notes beautifully.',
      ja: '始めるハードルを下げ、ノート整理が得意。',
      'zh-CN': '善于营造低门槛的开始环境，笔记整理出色。',
      'zh-TW': '善於營造低門檻的開始環境，筆記整理出色。',
      vi: 'Giỏi tạo điều kiện dễ bắt đầu và ghi chép đẹp.',
      id: 'Menciptakan awal yang mudah dan jago merapikan catatan.',
    }),
    cautions: localeMap({
      ko: '분위기에 의존하다 보면 환경이 안 좋으면 공부가 아예 안 됨',
      en: 'Depending on mood can make studying difficult in an imperfect environment.',
      ja: '雰囲気に依存すると、環境が整わない日は勉強しにくい。',
      'zh-CN': '太依赖氛围时，环境不好就很难学习。',
      'zh-TW': '太依賴氛圍時，環境不好就很難學習。',
      vi: 'Phụ thuộc vào không khí khiến việc học khó khi môi trường không hoàn hảo.',
      id: 'Terlalu bergantung suasana membuat belajar sulit saat lingkungan kurang baik.',
    }),
    studyTip: localeMap({
      ko: '분위기 만들기 시간을 15분으로 제한하기. 노트 정리는 내용을 이해한 후에 하기. 카페보다 도서관도 시도해보기',
      en: 'Limit setup to 15 minutes, then focus on understanding the content.',
      ja: '準備は15分に制限し、その後は内容理解に集中。',
      'zh-CN': '把准备限制在15分钟，然后专注理解内容。',
      'zh-TW': '把準備限制在15分鐘，然後專注理解內容。',
      vi: 'Giới hạn chuẩn bị 15 phút rồi tập trung vào nội dung.',
      id: 'Batasi persiapan 15 menit, lalu fokus memahami isi.',
    }),
    typicalPhrase: localeMap({
      ko: '공부 브이로그 촬영·예쁜 필기·카페 자리 잡기',
      en: 'Study vlog filming · Pretty notes · Finding a café seat',
      ja: '勉強Vlog撮影・きれいな筆記・カフェ席探し',
      'zh-CN': '拍学习Vlog·漂亮笔记·找咖啡馆座位',
      'zh-TW': '拍學習Vlog·漂亮筆記·找咖啡館座位',
      vi: 'Quay vlog học · Ghi chép đẹp · Tìm chỗ quán cà phê',
      id: 'Merekam vlog belajar · Catatan cantik · Cari kursi kafe',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '공부를 즐길 줄 아는 것은 강점입니다. 분위기를 만드는 에너지의 절반을 내용에 쏟으면 더 강해집니다',
      en: 'Enjoying study is a strength. Put half the energy you spend on mood into the content and you will grow stronger.',
      ja: '勉強を楽しめるのは強みです。雰囲気づくりのエネルギーの半分を内容に注げば、さらに強くなります。',
      'zh-CN': '会享受学习是优势。把营造氛围的能量一半用在内容上，会更强。',
      'zh-TW': '會享受學習是優勢。把營造氛圍的能量一半用在內容上，會更強。',
      vi: 'Biết tận hưởng việc học là thế mạnh. Dành một nửa năng lượng tạo không khí cho nội dung sẽ mạnh hơn.',
      id: 'Menikmati belajar adalah kekuatan. Setengah energi untuk suasana dialihkan ke isi akan membuatmu lebih kuat.',
    }),
    shareLine: localeMap({
      ko: '내 공부 유형: 감성 공부형 ☕ 공부 준비가 50%래... 카페 자리 잡는 데 30분 쓰는 거 맞음 ㅋㅋ → 나 이 유형이라 망함 ㅋㅋ 너는 어떤 유형이야?',
      en: 'My study type: Aesthetic Study ☕ Prep is 50% of studying… spending 30 minutes finding a café seat — so true lol → What is yours?',
      ja: '私の勉強タイプ：感性勉強型 ☕ 準備が50%…カフェ席探しに30分、当たり ㅋㅋ → あなたは？',
      'zh-CN': '我的学习类型：氛围学习型 ☕ 说准备占50%…找咖啡馆座位30分钟太准哈哈 → 你呢？',
      'zh-TW': '我的學習類型：氛圍學習型 ☕ 說準備占50%…找咖啡館座位30分鐘太準哈哈 → 你呢？',
      vi: 'Kiểu học của tôi: Cảm hứng ☕ Chuẩn bị chiếm 50%… tìm ghế quán cà phê 30 phút — đúng quá haha → Bạn loại nào?',
      id: 'Tipe belajarku: Estetis ☕ Persiapan 50%… cari kursi kafe 30 menit — bener wkwk → Kamu tipe apa?',
    }),
  },
  {
    type: "Type3",
    emoji: "📖",
    title: localeMap({
      ko: '반복이 곧 공부인 사람, 반복 암기형',
      en: 'Someone for Whom Repetition Is Studying, Repetition Memorization Type',
      ja: '反復こそ勉強の人、反復暗記型',
      'zh-CN': '重复就是学习的人，重复记忆型',
      'zh-TW': '重複就是學習的人，重複記憶型',
      vi: 'Người coi lặp lại là học, Kiểu ghi nhớ lặp lại',
      id: 'Orang yang menganggap pengulangan adalah belajar, Tipe Hafalan Berulang',
    }),
    studySummary: localeMap({
      ko: '이해보다 반복으로 머릿속에 새기는 타입',
      en: 'Engraves information through repetition rather than understanding',
      ja: '理解より反復で頭に刻むタイプ',
      'zh-CN': '比起理解更靠重复刻进脑海的类型',
      'zh-TW': '比起理解更靠重複刻進腦海的類型',
      vi: 'Khắc kiến thức bằng lặp lại hơn là hiểu',
      id: 'Menanamkan informasi lewat pengulangan',
    }),
    quote: localeMap({
      ko: '당신에게 공부의 핵심은 횟수입니다. 한 번 이해하는 것보다 열 번 반복하는 것이 더 믿음직합니다.',
      en: 'For you, study is about repetition count. Ten repetitions are more reliable than one understanding.',
      ja: 'あなたにとって勉強の核心は回数です。一度理解するより十回反復する方が信頼できます。',
      'zh-CN': '对你来说，学习的核心是次数。重复十次比理解一次更可靠。',
      'zh-TW': '對你來說，學習的核心是次數。重複十次比理解一次更可靠。',
      vi: 'Với bạn, cốt lõi học là số lần lặp. Mười lần lặp đáng tin hơn một lần hiểu.',
      id: 'Bagimu, inti belajar adalah jumlah pengulangan. Sepuluh kali mengulang lebih andal daripada sekali paham.',
    }),
    description: localeMap({
      ko: '형광펜을 치고 소리 내어 읽고 암기 카드를 만들고 반복합니다. 성실하고 꾸준한 방식입니다. 시험 범위 안의 것들은 확실하게 알고 들어갑니다.',
      en: 'You highlight, read aloud, make flashcards, and repeat. It is diligent and steady. You enter exams knowing the material in the defined range.',
      ja: '蛍光ペン、声に出して読む、暗記カード、反復。誠実で着実な方式です。試験範囲内のものは確実に知って臨みます。',
      'zh-CN': '你会用荧光笔、出声朗读、做记忆卡并反复练习。方式勤奋踏实，对考试范围内的内容很有把握。',
      'zh-TW': '你會用螢光筆、出聲朗讀、做記憶卡並反覆練習。方式勤奮踏實，對考試範圍內的內容很有把握。',
      vi: 'Bạn tô điểm, đọc to, làm thẻ nhớ và lặp lại. Cách học chăm chỉ và bền bỉ. Bạn vào thi với phần trong phạm vi đã chắc.',
      id: 'Kamu menandai, membaca keras, membuat kartu hafalan, dan mengulang. Cara belajar tekun dan konsisten. Kamu masuk ujian dengan materi dalam cakupan yang sudah dikuasai.',
    }),
    studyType: localeMap({
      ko: '반복 암기형 📖',
      en: 'Repetition Memorization Type 📖',
      ja: '反復暗記型 📖',
      'zh-CN': '重复记忆型 📖',
      'zh-TW': '重複記憶型 📖',
      vi: 'Kiểu ghi nhớ lặp lại 📖',
      id: 'Tipe Hafalan Berulang 📖',
    }),
    studyKeywords: localeMap({
      ko: '반복·암기 카드·형광펜·성실·횟수',
      en: 'Repetition · Flashcards · Highlighter · Diligence · Count',
      ja: '反復・暗記カード・蛍光ペン・誠実・回数',
      'zh-CN': '重复·记忆卡·荧光笔·勤奋·次数',
      'zh-TW': '重複·記憶卡·螢光筆·勤奮·次數',
      vi: 'Lặp lại · Thẻ nhớ · Bút dạ quang · Chăm chỉ · Số lần',
      id: 'Pengulangan · Kartu hafalan · Stabilo · Tekun · Jumlah',
    }),
    strengths: localeMap({
      ko: '외운 것은 확실함. 시험 범위가 정해진 과목에서 강함. 꾸준한 공부 습관',
      en: 'What is memorized is secure; you are steady and strong with defined exam ranges.',
      ja: '覚えたことは確実で、範囲が決まった試験に強く、着実に続けられる。',
      'zh-CN': '背过的内容很牢，擅长范围明确的考试且能坚持。',
      'zh-TW': '背過的內容很牢，擅長範圍明確的考試且能堅持。',
      vi: 'Đã thuộc là chắc; bạn bền bỉ và mạnh với phạm vi rõ ràng.',
      id: 'Yang dihafal kuat; kamu tekun dan kuat pada materi yang jelas.',
    }),
    cautions: localeMap({
      ko: '이해 없이 외운 것은 응용 문제에서 막힘. 처음 본 유형 문제에 취약',
      en: 'Memorizing without understanding can make unfamiliar application problems hard.',
      ja: '理解なしの暗記は、初見の応用問題で止まりやすい。',
      'zh-CN': '不理解地背诵容易在陌生应用题卡住。',
      'zh-TW': '不理解地背誦容易在陌生應用題卡住。',
      vi: 'Học thuộc không hiểu dễ mắc ở bài vận dụng mới.',
      id: 'Menghafal tanpa paham menyulitkan soal aplikasi baru.',
    }),
    studyTip: localeMap({
      ko: '외우기 전에 한 번만 "왜 그런지"를 확인하기. 이해하고 외우면 기억 지속 시간이 3배 늘어남. 암기 카드에 이유도 한 줄 추가하기',
      en: 'Before memorizing, ask once why it works; add one reason to every flashcard.',
      ja: '暗記前に一度「なぜ」を確認し、カードに理由を一行加える。',
      'zh-CN': '背前先问一次为什么，每张卡加一行理由。',
      'zh-TW': '背前先問一次為什麼，每張卡加一行理由。',
      vi: 'Trước khi thuộc, hỏi một lần “vì sao” và thêm lý do vào thẻ.',
      id: 'Sebelum menghafal, tanya sekali mengapa dan tambah alasan di kartu.',
    }),
    typicalPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '반복하는 성실함은 공부의 가장 기본 덕목입니다. 거기에 이해 한 겹만 더하면 훨씬 강해집니다',
      en: 'Diligent repetition is the most basic virtue of studying. Add one layer of understanding and you will become much stronger.',
      ja: '反復する誠実さは勉強の最も基本的な美徳です。理解を一層加えれば、はるかに強くなります。',
      'zh-CN': '重复中的勤奋是学习最基本的美德。再加一层理解就会强很多。',
      'zh-TW': '重複中的勤奮是學習最基本的美德。再加一層理解就會強很多。',
      vi: 'Sự chăm chỉ lặp lại là đức tính cơ bản nhất của học tập. Thêm một lớp hiểu biết sẽ mạnh hơn nhiều.',
      id: 'Ketekunan mengulang adalah kebajikan dasar belajar. Tambahkan satu lapisan pemahaman dan kamu jauh lebih kuat.',
    }),
    shareLine: localeMap({
      ko: '내 공부 유형: 반복 암기형 📖 이해보다 반복이 먼저래... 열 번 읽으면 외워진다는 거 맞음 → 나 이 유형이라 망함 ㅋㅋ 너도 해봐',
      en: 'My study type: Repetition Memorization 📖 Repetition before understanding… ten reads and it sticks — so true → Try it too',
      ja: '私の勉強タイプ：反復暗記型 📖 理解より反復が先…十回読めば覚える、当たり → あなたもやってみて',
      'zh-CN': '我的学习类型：重复记忆型 📖 说理解不如重复…读十遍就记住太准 → 你也试试',
      'zh-TW': '我的學習類型：重複記憶型 📖 說理解不如重複…讀十遍就記住太準 → 你也試試',
      vi: 'Kiểu học của tôi: Ghi nhớ lặp lại 📖 Lặp trước hiểu… đọc mười lần là nhớ — đúng quá → Bạn thử nhé',
      id: 'Tipe belajarku: Hafalan Berulang 📖 Mengulang dulu baru paham… baca sepuluh kali langsung hafal — bener → Kamu coba juga',
    }),
  },
  {
    type: "Type4",
    emoji: "🔍",
    title: localeMap({
      ko: '이해 안 되면 못 넘어가는 사람, 이해 탐구형',
      en: 'Someone Who Cannot Move On Without Understanding, Deep Understanding Type',
      ja: '理解できないと進めない人、理解探究型',
      'zh-CN': '不理解就无法继续的人，理解探究型',
      'zh-TW': '不理解就無法繼續的人，理解探究型',
      vi: 'Người không thể tiếp nếu chưa hiểu, Kiểu khám phá hiểu biết',
      id: 'Orang yang tidak bisa lanjut tanpa paham, Tipe Pemahaman Mendalam',
    }),
    studySummary: localeMap({
      ko: '원리와 개념을 이해해야만 다음으로 넘어갈 수 있는 타입',
      en: 'Must understand principles and concepts before moving on',
      ja: '原理と概念を理解してから次へ進むタイプ',
      'zh-CN': '必须理解原理和概念才继续的类型',
      'zh-TW': '必須理解原理和概念才繼續的類型',
      vi: 'Phải hiểu nguyên lý và khái niệm mới đi tiếp',
      id: 'Harus memahami prinsip dan konsep sebelum lanjut',
    }),
    quote: localeMap({
      ko: '당신에게 모르는 채로 넘어가는 것은 선택지에 없습니다. 한 페이지를 이해하는 데 한 시간이 걸려도 반드시 해결하고 갑니다.',
      en: 'Moving on without understanding is not an option. Even if one page takes an hour, you must solve it before continuing.',
      ja: '知らないまま進む選択肢はありません。1ページに1時間かかっても必ず解決してから進みます。',
      'zh-CN': '带着疑问继续不是选项。一页花一小时也要先搞懂。',
      'zh-TW': '帶著疑問繼續不是選項。一頁花一小時也要先搞懂。',
      vi: 'Tiếp tục khi chưa hiểu không phải lựa chọn. Dù một trang mất một giờ cũng phải giải quyết trước.',
      id: 'Melanjutkan tanpa paham bukan pilihan. Meski satu halaman butuh satu jam, harus diselesaikan dulu.',
    }),
    description: localeMap({
      ko: '이 개념이 왜 이렇게 성립하는지 물어보고 찾아보고 이해해야 다음 단계로 갑니다. 깊이 아는 것들은 절대 잊어버리지 않습니다.',
      en: 'You ask why a concept works, look it up, and understand before the next step. What you know deeply, you never forget.',
      ja: '概念がなぜ成り立つか調べ、理解してから次へ進みます。深く知ったものは絶対に忘れません。',
      'zh-CN': '你会追问概念为何成立、查资料、理解后再继续。真正理解的东西不会忘。',
      'zh-TW': '你會追問概念為何成立、查資料、理解後再繼續。真正理解的東西不會忘。',
      vi: 'Bạn hỏi vì sao khái niệm đúng, tra cứu và hiểu rồi mới sang bước sau. Điều hiểu sâu không bao giờ quên.',
      id: 'Kamu bertanya mengapa konsep berlaku, mencari bahan, dan paham dulu sebelum lanjut. Yang dipahami mendalam tidak pernah terlupa.',
    }),
    studyType: localeMap({
      ko: '이해 탐구형 🔍',
      en: 'Deep Understanding Type 🔍',
      ja: '理解探究型 🔍',
      'zh-CN': '理解探究型 🔍',
      'zh-TW': '理解探究型 🔍',
      vi: 'Kiểu khám phá hiểu biết 🔍',
      id: 'Tipe Pemahaman Mendalam 🔍',
    }),
    studyKeywords: localeMap({
      ko: '원리·이해·구조·왜·정확함',
      en: 'Principles · Understanding · Structure · Why · Accuracy',
      ja: '原理・理解・構造・なぜ・正確さ',
      'zh-CN': '原理·理解·结构·为什么·准确',
      'zh-TW': '原理·理解·結構·為什麼·準確',
      vi: 'Nguyên lý · Hiểu · Cấu trúc · Tại sao · Chính xác',
      id: 'Prinsip · Pemahaman · Struktur · Mengapa · Akurat',
    }),
    strengths: localeMap({
      ko: '이해한 것은 오래 기억됨. 응용 문제·서술형에서 강함. 실력이 진짜로 쌓임',
      en: 'What you understand lasts long, and you excel at application and written problems.',
      ja: '理解したことは長く残り、応用・記述問題に強い。',
      'zh-CN': '理解过的会记很久，擅长应用题和论述题。',
      'zh-TW': '理解過的會記很久，擅長應用題和論述題。',
      vi: 'Điều hiểu được nhớ lâu; bạn mạnh ở bài vận dụng và tự luận.',
      id: 'Yang dipahami bertahan lama; kamu kuat di soal aplikasi dan uraian.',
    }),
    cautions: localeMap({
      ko: '이해에 시간이 오래 걸려 시험 범위를 다 못 보는 경우가 생김. 시간 배분 실패 리스크',
      en: 'Going deep can take too long to cover the entire exam range.',
      ja: '深く理解する時間が長く、全範囲を終えられないことがある。',
      'zh-CN': '理解太深入会耗时，可能看不完全部范围。',
      'zh-TW': '理解太深入會耗時，可能看不完全部範圍。',
      vi: 'Hiểu sâu có thể tốn quá lâu, không kịp hết phạm vi.',
      id: 'Memahami terlalu dalam bisa memakan waktu dan tidak selesai semua materi.',
    }),
    studyTip: localeMap({
      ko: '이해의 깊이를 조절하기. 모든 개념을 100% 이해할 필요는 없음. 시험 비중에 따라 70% 이해로 넘길 수 있는 것과 100% 이해해야 하는 것을 구분하기',
      en: 'Adjust depth: decide what needs 100% understanding and what can move on at 70%.',
      ja: '理解の深さを調整し、100%必要なものと70%で進めるものを分ける。',
      'zh-CN': '调节理解深度，区分必须100%理解和70%即可的内容。',
      'zh-TW': '調節理解深度，區分必須100%理解和70%即可的內容。',
      vi: 'Điều chỉnh độ sâu: phân biệt phần cần 100% và 70% là đủ.',
      id: 'Atur kedalaman: bedakan yang perlu 100% dan yang bisa lanjut di 70%.',
    }),
    typicalPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '제대로 이해하는 사람이 결국 가장 오래 살아남습니다. 시간 배분만 더하면 완성입니다',
      en: 'People who truly understand survive the longest. Add better time allocation and you are complete.',
      ja: 'きちんと理解する人が最後まで残ります。時間配分だけ加えれば完成です。',
      'zh-CN': '真正理解的人最后会留下来。补上时间分配就完美了。',
      'zh-TW': '真正理解的人最後會留下來。補上時間分配就完美了。',
      vi: 'Người hiểu thật sự sẽ trụ lâu nhất. Thêm phân bổ thời gian là hoàn thiện.',
      id: 'Orang yang benar-benar paham bertahan paling lama. Tambahkan alokasi waktu dan kamu sudah lengkap.',
    }),
    shareLine: localeMap({
      ko: '내 공부 유형: 이해 탐구형 🔍 이해 안 되면 못 넘어가는 유형이래... 한 페이지에 한 시간 쓰는 거 맞음 ㅠ → 나 이 유형이라 망함 ㅋㅋ 너는 어떤 유형이야?',
      en: 'My study type: Deep Understanding 🔍 Cannot move on without understanding… one hour on one page — so true → What is yours?',
      ja: '私の勉強タイプ：理解探究型 🔍 理解できないと進めない…1ページ1時間、当たり ㅠ → あなたは？',
      'zh-CN': '我的学习类型：理解探究型 🔍 说不理解就过不去…一页一小时太准 → 你呢？',
      'zh-TW': '我的學習類型：理解探究型 🔍 說不理解就過不去…一頁一小時太準 → 你呢？',
      vi: 'Kiểu học của tôi: Hiểu sâu 🔍 Không hiểu là không qua… một trang một giờ — đúng quá → Bạn loại nào?',
      id: 'Tipe belajarku: Pemahaman Mendalam 🔍 Nggak paham nggak lanjut… satu halaman satu jam — bener → Kamu tipe apa?',
    }),
  },
  {
    type: "Type5",
    emoji: "📅",
    title: localeMap({
      ko: '계획표대로 착실히 하는 사람, 계획 실천형',
      en: 'Someone Who Follows the Plan Steadily, Plan Executor Type',
      ja: '計画表どおり着実に進める人、計画実践型',
      'zh-CN': '按计划踏实执行的人，计划实践型',
      'zh-TW': '按計畫踏實執行的人，計畫實踐型',
      vi: 'Người thực hiện kế hoạch đều đặn, Kiểu thực thi kế hoạch',
      id: 'Orang yang tekun mengikuti rencana, Tipe Pelaksana Rencana',
    }),
    studySummary: localeMap({
      ko: '계획을 세우고 그것을 실천하는 것으로 시험을 준비하는 타입',
      en: 'Prepares for exams by making and executing plans',
      ja: '計画を立てて実行し、試験に備えるタイプ',
      'zh-CN': '通过制定并执行计划备考的类型',
      'zh-TW': '通過制定並執行計畫備考的類型',
      vi: 'Chuẩn bị thi bằng cách lập và thực hiện kế hoạch',
      id: 'Menyiapkan ujian dengan membuat dan menjalankan rencana',
    }),
    quote: localeMap({
      ko: '당신에게 공부는 계획에서 시작합니다. 무엇을 언제 얼마나 할지가 정해져야 실행이 됩니다.',
      en: 'Study begins with a plan. You need to know what, when, and how much before you can execute.',
      ja: 'あなたにとって勉強は計画から始まります。何をいつどれだけやるかが決まって初めて実行できます。',
      'zh-CN': '对你来说，学习从计划开始。必须定好做什么、何时做、做多少才能执行。',
      'zh-TW': '對你來說，學習從計畫開始。必須定好做什麼、何時做、做多少才能執行。',
      vi: 'Học bắt đầu bằng kế hoạch. Phải biết làm gì, khi nào, bao nhiêu mới thực hiện được.',
      id: 'Belajar dimulai dari rencana. Harus tahu apa, kapan, dan berapa banyak baru bisa dieksekusi.',
    }),
    description: localeMap({
      ko: '2주 전부터 범위를 나누고 날마다 할 것을 정하고 착실히 진행합니다. 전날 밤엔 가볍게 복습하고 일찍 잡니다. 컨디션 관리까지 공부의 일부입니다.',
      en: 'Two weeks out you divide the scope, set daily tasks, and proceed steadily. The night before you lightly review and sleep early. Condition management is part of studying.',
      ja: '2週間前から範囲を分け、毎日のタスクを決め、着実に進めます。前日は軽く復習して早く寝ます。体調管理も勉強の一部です。',
      'zh-CN': '两周前划分范围、定每日任务并踏实推进。前一晚轻复习早睡，状态管理也是学习的一部分。',
      'zh-TW': '兩週前劃分範圍、定每日任務並踏實推進。前一晚輕複習早睡，狀態管理也是學習的一部分。',
      vi: 'Hai tuần trước bạn chia phạm vi, đặt việc hàng ngày và tiến đều. Đêm trước ôn nhẹ và ngủ sớm. Quản lý thể trạng cũng là học.',
      id: 'Dua minggu sebelumnya kamu bagi cakupan, tentukan tugas harian, dan lanjut konsisten. Malam sebelumnya ulasan ringan dan tidur awal. Mengelola kondisi juga bagian belajar.',
    }),
    studyType: localeMap({
      ko: '계획 실천형 📅',
      en: 'Plan Executor Type 📅',
      ja: '計画実践型 📅',
      'zh-CN': '计划实践型 📅',
      'zh-TW': '計畫實踐型 📅',
      vi: 'Kiểu thực thi kế hoạch 📅',
      id: 'Tipe Pelaksana Rencana 📅',
    }),
    studyKeywords: localeMap({
      ko: '계획표·분배·실천·컨디션·체계',
      en: 'Schedule · Allocation · Execution · Condition · System',
      ja: '計画表・配分・実行・体調・体系',
      'zh-CN': '计划表·分配·执行·状态·体系',
      'zh-TW': '計畫表·分配·執行·狀態·體系',
      vi: 'Lịch · Phân bổ · Thực hiện · Thể trạng · Hệ thống',
      id: 'Jadwal · Pembagian · Pelaksanaan · Kondisi · Sistem',
    }),
    strengths: localeMap({
      ko: '시험 전날 여유가 있음. 시험 범위 전체를 커버할 수 있음. 스트레스가 상대적으로 낮음',
      en: 'You cover the full range with less stress and have room to breathe before the exam.',
      ja: '全範囲をカバーしやすく、前日に余裕がありストレスも比較的低い。',
      'zh-CN': '能覆盖全部范围，考前有余裕，压力相对低。',
      'zh-TW': '能覆蓋全部範圍，考前有餘裕，壓力相對低。',
      vi: 'Bạn bao quát toàn bộ phạm vi, ít căng thẳng và có dư thời gian.',
      id: 'Kamu bisa mencakup seluruh materi, stres lebih rendah, dan punya waktu luang.',
    }),
    cautions: localeMap({
      ko: '계획이 틀어지면 당황하는 경우가 있음. 유연성이 부족할 수 있음',
      en: 'When the plan changes, you may feel flustered or lose flexibility.',
      ja: '計画が崩れると慌てやすく、柔軟性を失うことがある。',
      'zh-CN': '计划被打乱时容易慌张，灵活性可能不足。',
      'zh-TW': '計畫被打亂時容易慌張，靈活性可能不足。',
      vi: 'Khi kế hoạch lệch, bạn có thể hoảng và thiếu linh hoạt.',
      id: 'Saat rencana berubah, kamu bisa panik dan kurang fleksibel.',
    }),
    studyTip: localeMap({
      ko: '계획에 버퍼 시간 포함하기. 예상보다 오래 걸리는 날을 대비한 여유분 20% 추가. 계획 수정도 계획의 일부임을 인식하기',
      en: 'Add a 20% buffer and treat revising the plan as part of planning.',
      ja: '20%の予備時間を入れ、計画修正も計画の一部と考える。',
      'zh-CN': '加入20%缓冲时间，把修改计划也当作计划的一部分。',
      'zh-TW': '加入20%緩衝時間，把修改計畫也當作計畫的一部分。',
      vi: 'Thêm 20% thời gian đệm; xem việc sửa kế hoạch là một phần của kế hoạch.',
      id: 'Tambahkan buffer 20% dan anggap revisi rencana sebagai bagian dari rencana.',
    }),
    typicalPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '계획대로 한다는 것은 이미 공부의 절반을 한 것입니다. 그 실행력이 가장 강한 무기입니다',
      en: 'Following the plan means you have already done half the studying. That execution is your strongest weapon.',
      ja: '計画どおりに進むことは、すでに勉強の半分を終えたことです。その実行力が最強の武器です。',
      'zh-CN': '按计划执行，等于已经完成一半学习。那份执行力是最强武器。',
      'zh-TW': '按計畫執行，等於已經完成一半學習。那份執行力是最強武器。',
      vi: 'Làm đúng kế hoạch nghĩa là đã học được một nửa. Khả năng thực thi đó là vũ khí mạnh nhất.',
      id: 'Mengikuti rencana berarti setengah belajar sudah selesai. Eksekusi itu senjata terkuatmu.',
    }),
    shareLine: localeMap({
      ko: '내 공부 유형: 계획 실천형 📅 계획표대로 착실히 하는 유형이래... 2주 전부터 준비하는 거 맞음 → 나 이 유형이라 살았음 ㅋㅋ 너는 어떤 유형이야?',
      en: 'My study type: Plan Executor 📅 They say I prepare steadily from two weeks out — so true lol → What is yours?',
      ja: '私の勉強タイプ：計画実践型 📅 2週間前から着実に準備…当たり ㅋㅋ → あなたは？',
      'zh-CN': '我的学习类型：计划实践型 📅 说两周前就开始准备太准哈哈 → 你呢？',
      'zh-TW': '我的學習類型：計畫實踐型 📅 說兩週前就開始準備太準哈哈 → 你呢？',
      vi: 'Kiểu học của tôi: Thực thi kế hoạch 📅 Chuẩn bị từ hai tuần trước — đúng quá haha → Bạn loại nào?',
      id: 'Tipe belajarku: Pelaksana Rencana 📅 Persiapan dari dua minggu sebelumnya — bener wkwk → Kamu tipe apa?',
    }),
  },
  {
    type: "Type6",
    emoji: "🎯",
    title: localeMap({
      ko: '시험이 끝나도 복습하는 사람, 자기주도 완성형',
      en: 'Someone Who Reviews Even After the Exam, Self-Directed Master Type',
      ja: '試験後も復習する人、自己主導完成型',
      'zh-CN': '考完还复习的人，自主完成型',
      'zh-TW': '考完還複習的人，自主完成型',
      vi: 'Người vẫn ôn sau kỳ thi, Kiểu tự chủ hoàn thiện',
      id: 'Orang yang tetap mengulas setelah ujian, Tipe Mandiri Tuntas',
    }),
    studySummary: localeMap({
      ko: '모든 것이 체계적이고 이해와 암기가 균형 잡힌 완성형 학습자 타입',
      en: 'A complete learner with balanced understanding and memorization',
      ja: '理解と暗記のバランスが取れた完成型学習者',
      'zh-CN': '理解与记忆平衡的完整型学习者',
      'zh-TW': '理解與記憶平衡的完整型學習者',
      vi: 'Người học hoàn thiện, cân bằng hiểu và nhớ',
      id: 'Pembelajar lengkap dengan pemahaman dan hafalan seimbang',
    }),
    quote: localeMap({
      ko: '당신에게 공부는 시험을 위한 것이 아닙니다. 진짜로 아는 것이 목표입니다.',
      en: 'Study is not for the exam. Truly knowing is the goal.',
      ja: 'あなたにとって勉強は試験のためではありません。本当に知ることが目標です。',
      'zh-CN': '对你来说，学习不是为了考试。真正知道才是目标。',
      'zh-TW': '對你來說，學習不是為了考試。真正知道才是目標。',
      vi: 'Học không phải vì kỳ thi. Biết thật sự mới là mục tiêu.',
      id: 'Belajar bukan untuk ujian. Benar-benar tahu itulah tujuannya.',
    }),
    description: localeMap({
      ko: '범위 파악·개념 구조화·이해·암기·복습·컨디션 관리까지 모든 과정이 체계적입니다. 시험 전날은 가볍게 마무리하고 일찍 잡니다. 틀린 문제는 왜 틀렸는지 분석합니다.',
      en: 'Scope mapping, concept structuring, understanding, memorization, review, and condition management — every step is systematic. The night before you wrap up lightly and sleep early. You analyze why you got problems wrong.',
      ja: '範囲把握・概念構造化・理解・暗記・復習・体調管理まで体系的です。前日は軽く仕上げて早く寝、間違えた問題は理由を分析します。',
      'zh-CN': '范围把握、概念结构化、理解、记忆、复习、状态管理全都系统化。前一晚轻收尾早睡，错题会分析原因。',
      'zh-TW': '範圍把握、概念結構化、理解、記憶、複習、狀態管理全都系統化。前一晚輕收尾早睡，錯題會分析原因。',
      vi: 'Nắm phạm vi, cấu trúc khái niệm, hiểu, nhớ, ôn và quản lý thể trạng — mọi bước đều có hệ thống. Đêm trước kết thúc nhẹ và ngủ sớm. Phân tích vì sao sai.',
      id: 'Pemetaan cakupan, struktur konsep, paham, hafal, ulasan, dan kondisi — semua langkah sistematis. Malam sebelumnya ringan dan tidur awal. Menganalisis mengapa salah.',
    }),
    studyType: localeMap({
      ko: '자기주도 완성형 🎯',
      en: 'Self-Directed Master Type 🎯',
      ja: '自己主導完成型 🎯',
      'zh-CN': '自主完成型 🎯',
      'zh-TW': '自主完成型 🎯',
      vi: 'Kiểu tự chủ hoàn thiện 🎯',
      id: 'Tipe Mandiri Tuntas 🎯',
    }),
    studyKeywords: localeMap({
      ko: '체계·이해+암기 균형·복습·분석·완성',
      en: 'System · Understanding + memorization · Review · Analysis · Completion',
      ja: '体系・理解と暗記のバランス・復習・分析・完成',
      'zh-CN': '体系·理解+记忆平衡·复习·分析·完成',
      'zh-TW': '體系·理解+記憶平衡·複習·分析·完成',
      vi: 'Hệ thống · Hiểu + nhớ · Ôn tập · Phân tích · Hoàn thiện',
      id: 'Sistem · Pemahaman + hafalan · Ulasan · Analisis · Tuntas',
    }),
    strengths: localeMap({
      ko: '실력이 진짜로 쌓임. 시험 결과와 실력이 일치함. 장기 기억 능력 탁월',
      en: 'Your real ability accumulates, aligns with exam results, and stays in long-term memory.',
      ja: '実力が本当に積み上がり、試験結果と一致し、長期記憶にも残る。',
      'zh-CN': '实力真正积累，与成绩一致，长期记忆出色。',
      'zh-TW': '實力真正積累，與成績一致，長期記憶出色。',
      vi: 'Năng lực thật sự tích lũy, khớp kết quả thi và nhớ lâu.',
      id: 'Kemampuan nyata terkumpul, selaras dengan hasil ujian, dan bertahan lama.',
    }),
    cautions: localeMap({
      ko: '완벽주의가 지나치면 소진될 수 있음. 80%의 완성도로도 충분한 경우를 구분하기\n이 유형이 하는 말: "이 개념 정확히 알고 싶어서요"',
      en: 'Excessive perfectionism can lead to burnout; learn when 80% is enough.',
      ja: '完璧主義が強すぎると燃え尽きることも。80%で十分な場合を見分ける。',
      'zh-CN': '过度完美主义会耗尽自己，要分辨80%已足够的时候。',
      'zh-TW': '過度完美主義會耗盡自己，要分辨80%已足夠的時候。',
      vi: 'Cầu toàn quá mức có thể kiệt sức; hãy biết khi nào 80% là đủ.',
      id: 'Perfeksionisme berlebihan bisa membuat lelah; ketahui kapan 80% cukup.',
    }),
    studyTip: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    typicalPhrase: localeMap({
      ko: '"이 개념 정확히 알고 싶어서요"',
      en: '“I want to know this concept exactly.”',
      ja: '「この概念を正確に知りたいんです」',
      'zh-CN': '“我想准确了解这个概念。”',
      'zh-TW': '「我想準確了解這個概念。」',
      vi: '“Tôi muốn biết chính xác khái niệm này.”',
      id: '“Aku ingin mengetahui konsep ini dengan tepat.”',
    }),
    certificationPhrase: localeMap({
      ko: '자기주도 완성형 달성 🎯 공부의 모든 단계를 갖춘 학습자',
      en: 'Self-Directed Master Achieved 🎯 A learner equipped for every stage of studying',
      ja: '自己主導完成型達成 🎯 学習のすべての段階を備えた学習者',
      'zh-CN': '达成自主完成型 🎯 具备学习全部阶段的学习者',
      'zh-TW': '達成自主完成型 🎯 具備學習全部階段的學習者',
      vi: 'Đạt kiểu tự chủ hoàn thiện 🎯 Người học có đủ mọi giai đoạn',
      id: 'Tercapai Mandiri Tuntas 🎯 Pembelajar dengan semua tahap belajar',
    }),
    oneLiner: localeMap({
      ko: '당신이 쌓은 것은 시험이 끝나도 남습니다. 그것이 이 유형이 가장 멀리 가는 이유입니다',
      en: 'What you build stays even after the exam ends. That is why this type goes the furthest.',
      ja: '積み上げたものは試験が終わっても残ります。それがこのタイプが最も遠くへ行ける理由です。',
      'zh-CN': '你积累的东西考试结束后也会留下。这就是此类型能走最远的原因。',
      'zh-TW': '你累積的東西考試結束後也會留下。這就是此類型能走最遠的原因。',
      vi: 'Những gì bạn xây dựng vẫn còn sau khi thi xong. Đó là lý do kiểu này đi xa nhất.',
      id: 'Yang kamu bangun tetap ada setelah ujian selesai. Itulah mengapa tipe ini melangkah paling jauh.',
    }),
    shareLine: localeMap({
      ko: '내 공부 유형: 자기주도 완성형 🎯 시험 끝나도 복습한다는 유형이래... 이해+암기+컨디션 관리까지 하는 거 맞음 → 너는 어떤 유형이야?',
      en: 'My study type: Self-Directed Master 🎯 They say I review even after exams… understanding + memorization + condition management — so true → What is yours?',
      ja: '私の勉強タイプ：自己主導完成型 🎯 試験後も復習…理解・暗記・体調管理まで、当たり → あなたは？',
      'zh-CN': '我的学习类型：自主完成型 🎯 说考完还复习…理解+记忆+状态管理都有太准 → 你呢？',
      'zh-TW': '我的學習類型：自主完成型 🎯 說考完還複習…理解+記憶+狀態管理都有太準 → 你呢？',
      vi: 'Kiểu học của tôi: Tự chủ hoàn thiện 🎯 Vẫn ôn sau thi… hiểu + nhớ + quản lý thể trạng — đúng quá → Bạn loại nào?',
      id: 'Tipe belajarku: Mandiri Tuntas 🎯 Masih ulang setelah ujian… paham + hafal + kondisi — bener → Kamu tipe apa?',
    }),
  },
];
