/** 나의 수면 유형과 숙면 처방전 — 12문항 4지선다, A=0 B=1 C=2 D=3, 총점 0~36 → Type1~6 */

function T(t: {
  ko: string;
  en: string;
  ja: string;
  zhCN: string;
  zhTW: string;
  vi: string;
  id: string;
}): Record<string, string> {
  return {
    ko: t.ko,
    en: t.en,
    ja: t.ja,
    'zh-CN': t.zhCN,
    'zh-TW': t.zhTW,
    vi: t.vi,
    id: t.id,
  };
}

export interface Phase3SleepTypePrescriptionQuestion {
  id: number;
  question: Record<string, string>;
  options: { text: Record<string, string>; score: number }[];
}

export interface Phase3SleepTypePrescriptionResult {
  type: string;
  emoji: string;
  title: Record<string, string>;
  scoreBand: Record<string, string>;
  sleepTypeLine: Record<string, string>;
  hookLine: Record<string, string>;
  description: Record<string, string>;
  strengthLine: Record<string, string>;
  problemLine: Record<string, string>;
  prescriptionText: Record<string, string>;
  todayTask: Record<string, string>;
  warningLine?: Record<string, string>;
  shareLine: Record<string, string>;
}

export function calculatePhase3SleepTypePrescriptionResult(answers: number[]): string {
  const total = answers.reduce((sum, s) => sum + (s ?? 0), 0);
  if (total <= 5) return 'Type1';
  if (total <= 11) return 'Type2';
  if (total <= 19) return 'Type3';
  if (total <= 27) return 'Type4';
  if (total <= 33) return 'Type5';
  return 'Type6';
}

export const phase3SleepTypePrescriptionQuestions: Phase3SleepTypePrescriptionQuestion[] = [
  {
    id: 1,
    question: T({
      ko: '평소 자려고 누웠을 때 잠드는 데 걸리는 시간은?',
      en: 'When you lie down to sleep, how long does it usually take you to fall asleep?',
      ja: '寝ようと横になってから眠りにつくまで、どのくらいかかりますか？',
      zhCN: '平时躺下准备睡觉后，你入睡通常需要多久？',
      zhTW: '平時躺下準備睡覺後，你入睡通常需要多久？',
      vi: 'Khi nằm xuống để ngủ, thường bạn mất bao lâu để ngủ thiếp đi?',
      id: 'Saat berbaring untuk tidur, biasanya butuh waktu berapa lama sampai kamu tertidur?',
    }),
    options: [
      {
        text: T({
          ko: '10분 이내. 눕자마자 잠든다',
          en: 'Within 10 minutes. I fall asleep almost instantly.',
          ja: '10分以内。横になるとすぐ眠れる。',
          zhCN: '10分钟以内。躺下就睡着。',
          zhTW: '10分鐘以內。躺下就睡著。',
          vi: 'Trong 10 phút. Nằm xuống là ngủ ngay.',
          id: 'Dalam 10 menit. Begitu rebahan langsung tidur.',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '10~30분. 조금 뒤척이다 잠든다',
          en: '10–30 minutes. I toss a bit and then fall asleep.',
          ja: '10〜30分。少し寝返りしてから眠る。',
          zhCN: '10~30分钟。稍微翻来覆去后睡着。',
          zhTW: '10~30分鐘。稍微翻來覆去後睡著。',
          vi: '10–30 phút. Trằn trọc chút rồi ngủ.',
          id: '10–30 menit. Sedikit gelisah lalu tertidur.',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '30분~1시간. 잠이 잘 오지 않아서 폰을 보거나 다른 것을 한다',
          en: '30 minutes to 1 hour. Sleep doesn’t come, so I use my phone or do something else.',
          ja: '30分〜1時間。眠れなくてスマホを見たり別のことをする。',
          zhCN: '30分钟到1小时。睡不着就刷手机或做别的事。',
          zhTW: '30分鐘到1小時。睡不著就滑手機或做別的事。',
          vi: '30 phút–1 giờ. Khó ngủ nên mình xem điện thoại hoặc làm việc khác.',
          id: '30 menit–1 jam. Susah tidur jadi main HP atau melakukan hal lain.',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '1시간 이상 또는 아예 잠을 못 자는 날이 종종 있다',
          en: 'Over 1 hour, or there are nights I can’t sleep at all.',
          ja: '1時間以上、または全然眠れない日が時々ある。',
          zhCN: '1小时以上，甚至有时整晚睡不着。',
          zhTW: '1小時以上，甚至有時整晚睡不著。',
          vi: 'Hơn 1 giờ, hoặc có đêm gần như không ngủ được.',
          id: 'Lebih dari 1 jam, atau kadang sama sekali tidak bisa tidur.',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 2,
    question: T({
      ko: '자려고 누운 뒤 하는 행동은?',
      en: 'What do you usually do after you lie down to sleep?',
      ja: '寝るために横になってから、よくする行動は？',
      zhCN: '躺下准备睡觉后，你通常会做什么？',
      zhTW: '躺下準備睡覺後，你通常會做什麼？',
      vi: 'Sau khi nằm xuống để ngủ, bạn thường làm gì?',
      id: 'Setelah berbaring untuk tidur, biasanya kamu ngapain?',
    }),
    options: [
      {
        text: T({
          ko: '그냥 눈을 감으면 잠든다. 별다른 행동을 하지 않는다',
          en: 'I just close my eyes and fall asleep—no special routine.',
          ja: '目を閉じれば眠れる。特に何もしない。',
          zhCN: '闭上眼就能睡着，不做特别的事。',
          zhTW: '閉上眼就能睡著，不做特別的事。',
          vi: 'Mình nhắm mắt là ngủ, không làm gì đặc biệt.',
          id: 'Tinggal merem dan tidur, tidak ada kebiasaan khusus.',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '잠깐 음악을 듣거나 책을 읽다가 잠든다',
          en: 'I listen to some music or read a bit, then sleep.',
          ja: '少し音楽を聴いたり本を読んでから寝る。',
          zhCN: '听会儿音乐或看会儿书再睡。',
          zhTW: '聽會兒音樂或看會兒書再睡。',
          vi: 'Nghe nhạc hoặc đọc sách một chút rồi ngủ.',
          id: 'Dengerin musik atau baca sebentar lalu tidur.',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '스마트폰을 보다가 잠드는 경우가 많다',
          en: 'I often fall asleep while scrolling on my phone.',
          ja: 'スマホを見ながら寝落ちすることが多い。',
          zhCN: '经常刷手机刷着刷着就睡着。',
          zhTW: '經常滑手機滑著滑著就睡著。',
          vi: 'Thường mình lướt điện thoại rồi ngủ quên.',
          id: 'Sering ketiduran sambil main HP.',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '생각이 너무 많아서 쉽게 잠들지 못한다',
          en: 'My mind is too busy, so I can’t fall asleep easily.',
          ja: '考えが多すぎてなかなか眠れない。',
          zhCN: '想太多，难以入睡。',
          zhTW: '想太多，難以入睡。',
          vi: 'Suy nghĩ nhiều quá nên khó ngủ.',
          id: 'Kepikiran terus jadi susah tidur.',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 3,
    question: T({
      ko: '수면 중 자주 깨는 편인가요?',
      en: 'Do you wake up often during sleep?',
      ja: '睡眠中に目が覚めることは多いですか？',
      zhCN: '你睡觉时会经常醒来吗？',
      zhTW: '你睡覺時會經常醒來嗎？',
      vi: 'Bạn có hay tỉnh giấc giữa đêm không?',
      id: 'Kamu sering terbangun saat tidur?',
    }),
    options: [
      { text: T({ ko: '거의 깨지 않는다. 한번 자면 아침까지 잔다', en: 'Rarely. Once I sleep, I stay asleep until morning.', ja: 'ほとんどない。一度寝たら朝まで眠る。', zhCN: '几乎不会。一觉到天亮。', zhTW: '幾乎不會。一覺到天亮。', vi: 'Hầu như không. Ngủ một mạch tới sáng.', id: 'Hampir tidak. Sekali tidur sampai pagi.' }), score: 0 },
      { text: T({ ko: '가끔 깨는 편이지만 금방 다시 잠든다', en: 'Sometimes, but I fall back asleep quickly.', ja: 'たまにあるが、すぐまた眠れる。', zhCN: '偶尔醒，但很快能再睡。', zhTW: '偶爾醒，但很快能再睡。', vi: 'Thỉnh thoảng nhưng ngủ lại nhanh.', id: 'Kadang, tapi cepat tidur lagi.' }), score: 1 },
      { text: T({ ko: '자주 깬다. 화장실을 가거나 이유 없이 깨는 경우가 많다', en: 'Often. I wake to use the bathroom or for no reason.', ja: 'よくある。トイレに起きたり理由なく起きる。', zhCN: '经常醒。上厕所或莫名醒来。', zhTW: '經常醒。上廁所或莫名醒來。', vi: 'Hay tỉnh. Đi vệ sinh hoặc tự nhiên tỉnh.', id: 'Sering. Bangun ke toilet atau tanpa alasan.' }), score: 2 },
      { text: T({ ko: '자주 깨고 다시 잠들기 어렵다. 새벽에 깨면 그게 끝인 경우도 있다', en: 'Often, and it’s hard to fall back asleep. Sometimes waking at dawn is the end.', ja: 'よく起きて、また寝るのが難しい。明け方に起きたら終わることも。', zhCN: '经常醒且难再入睡。有时凌晨醒来就再也睡不着。', zhTW: '經常醒且難再入睡。有時凌晨醒來就再也睡不著。', vi: 'Hay tỉnh và khó ngủ lại. Có khi gần sáng tỉnh là hết ngủ.', id: 'Sering bangun dan susah tidur lagi. Kadang bangun subuh jadi tidak bisa tidur.' }), score: 3 },
    ],
  },
  {
    id: 4,
    question: T({
      ko: '아침에 일어날 때 나의 상태는?',
      en: 'How do you feel when you wake up in the morning?',
      ja: '朝起きたときの状態は？',
      zhCN: '早上起床时你的状态是？',
      zhTW: '早上起床時你的狀態是？',
      vi: 'Khi thức dậy buổi sáng, bạn thường thấy thế nào?',
      id: 'Saat bangun pagi, kondisi kamu biasanya bagaimana?',
    }),
    options: [
      { text: T({ ko: '개운하게 일어난다. 기상이 크게 힘들지 않다', en: 'Refreshed. Getting up isn’t too hard.', ja: 'スッキリ。起きるのがそれほど辛くない。', zhCN: '很清醒，起床不算痛苦。', zhTW: '很清醒，起床不算痛苦。', vi: 'Tỉnh táo, dậy không quá khó.', id: 'Segar. Bangun tidak terlalu susah.' }), score: 0 },
      { text: T({ ko: '조금 무겁지만 움직이면 괜찮아진다', en: 'A bit heavy, but I’m fine once I get moving.', ja: '少し重いが、動けば大丈夫。', zhCN: '有点沉，但动一动就好。', zhTW: '有點沉，但動一動就好。', vi: 'Hơi nặng người nhưng vận động là ổn.', id: 'Agak berat, tapi begitu bergerak jadi mendingan.' }), score: 1 },
      { text: T({ ko: '몸이 무겁고 더 자고 싶다. 알람을 2~3번 끄는 편이다', en: 'Heavy and want more sleep. I snooze the alarm 2–3 times.', ja: '体が重くもっと寝たい。アラームを2〜3回止める。', zhCN: '身体很沉还想睡，会按两三次贪睡。', zhTW: '身體很沉還想睡，會按兩三次貪睡。', vi: 'Nặng người và muốn ngủ thêm, thường bấm báo lại 2–3 lần.', id: 'Berat dan ingin tidur lagi; biasanya snooze 2–3 kali.' }), score: 2 },
      { text: T({ ko: '아무리 자도 피곤하다. 일어나기가 매우 힘들다', en: 'Tired no matter how much I sleep. Getting up is extremely hard.', ja: 'どれだけ寝ても疲れていて、起きるのがとても辛い。', zhCN: '怎么睡都累，起床非常困难。', zhTW: '怎麼睡都累，起床非常困難。', vi: 'Ngủ bao nhiêu cũng mệt, dậy cực khó.', id: 'Seberapa pun tidur tetap capek; bangun sangat sulit.' }), score: 3 },
    ],
  },
  {
    id: 5,
    question: T({
      ko: '평소 취침 시간은?',
      en: 'What is your usual bedtime?',
      ja: '普段の就寝時間は？',
      zhCN: '你平时一般几点睡？',
      zhTW: '你平時一般幾點睡？',
      vi: 'Giờ đi ngủ thường ngày của bạn là?',
      id: 'Jam tidur biasanya kamu?',
    }),
    options: [
      { text: T({ ko: '밤 10시~11시 사이. 일정하게 이른 편이다', en: '10–11 PM. Fairly early and consistent.', ja: '22〜23時。早めで安定。', zhCN: '晚上10~11点，比较早且规律。', zhTW: '晚上10~11點，比較早且規律。', vi: '10–11 giờ tối, khá sớm và đều.', id: 'Jam 10–11 malam, cukup awal dan konsisten.' }), score: 0 },
      { text: T({ ko: '밤 11시~12시 사이. 어느 정도 규칙적이다', en: '11 PM–12 AM. Somewhat regular.', ja: '23〜24時。ある程度規則的。', zhCN: '晚上11点到12点，算比较规律。', zhTW: '晚上11點到12點，算比較規律。', vi: '11–12 giờ đêm, khá đều.', id: 'Jam 11–12 malam, cukup teratur.' }), score: 1 },
      { text: T({ ko: '자정~새벽 1시 사이. 늦은 편이지만 대체로 일정하다', en: '12–1 AM. Late, but mostly consistent.', ja: '0〜1時。遅いがだいたい一定。', zhCN: '0点到1点，偏晚但大多固定。', zhTW: '0點到1點，偏晚但大多固定。', vi: '0–1 giờ sáng, muộn nhưng khá cố định.', id: 'Jam 12–1 dini hari, terlambat tapi cukup konsisten.' }), score: 2 },
      { text: T({ ko: '들쑥날쑥하다. 어떤 날은 10시에 자고 어떤 날은 새벽 3시에 잔다', en: 'All over the place—some nights 10 PM, other nights 3 AM.', ja: 'バラバラ。10時の日もあれば3時の日もある。', zhCN: '很不固定，有时10点睡有时凌晨3点睡。', zhTW: '很不固定，有時10點睡有時凌晨3點睡。', vi: 'Rất thất thường: có hôm 10 giờ, có hôm 3 giờ sáng.', id: 'Berantakan: kadang jam 10, kadang jam 3 pagi.' }), score: 3 },
    ],
  },
  {
    id: 6,
    question: T({
      ko: '잠들기 전 1~2시간 동안 주로 하는 것은?',
      en: 'In the 1–2 hours before sleep, what do you mostly do?',
      ja: '寝る前の1〜2時間は主に何をしていますか？',
      zhCN: '睡前1~2小时你主要在做什么？',
      zhTW: '睡前1~2小時你主要在做什麼？',
      vi: 'Trong 1–2 giờ trước khi ngủ, bạn chủ yếu làm gì?',
      id: 'Dalam 1–2 jam sebelum tidur, kamu biasanya ngapain?',
    }),
    options: [
      { text: T({ ko: '스트레칭·독서·명상 등 이완 활동을 한다', en: 'Relaxing activities like stretching, reading, or meditation.', ja: 'ストレッチ・読書・瞑想などリラックス。', zhCN: '拉伸/阅读/冥想等放松活动。', zhTW: '伸展/閱讀/冥想等放鬆活動。', vi: 'Thư giãn như giãn cơ, đọc sách, thiền.', id: 'Aktivitas relaks seperti stretching, membaca, meditasi.' }), score: 0 },
      { text: T({ ko: 'TV나 유튜브를 보다가 잠자리에 든다', en: 'Watch TV or YouTube, then go to bed.', ja: 'TVやYouTubeを見てから寝る。', zhCN: '看电视/YouTube再睡。', zhTW: '看電視/YouTube再睡。', vi: 'Xem TV/YouTube rồi mới ngủ.', id: 'Nonton TV/YouTube lalu tidur.' }), score: 1 },
      { text: T({ ko: '스마트폰으로 SNS·쇼핑·영상을 보다가 잠든다', en: 'Scroll SNS/shopping/videos on my phone until I fall asleep.', ja: 'スマホでSNS・買い物・動画を見て寝落ち。', zhCN: '手机刷社媒/购物/视频刷到睡着。', zhTW: '手機滑社群/購物/影片滑到睡著。', vi: 'Lướt mạng/xem video/mua sắm trên điện thoại đến khi ngủ.', id: 'Scroll medsos/belanja/video di HP sampai ketiduran.' }), score: 2 },
      { text: T({ ko: '업무·공부·걱정 등 머리가 계속 돌아가는 상태에서 잠자리에 든다', en: 'My head keeps running—work/study/worries—when I get into bed.', ja: '仕事・勉強・不安で頭が回り続けたまま寝る。', zhCN: '工作/学习/担心让大脑停不下来就上床。', zhTW: '工作/學習/擔心讓大腦停不下來就上床。', vi: 'Đầu óc vẫn chạy: công việc/học hành/lo lắng khi lên giường.', id: 'Pikiran masih penuh urusan: kerja/belajar/khawatir saat rebahan.' }), score: 3 },
    ],
  },
  {
    id: 7,
    question: T({
      ko: '낮 동안 졸음이 오는 빈도는?',
      en: 'How often do you feel sleepy during the day?',
      ja: '日中の眠気はどのくらいありますか？',
      zhCN: '白天你有多常犯困？',
      zhTW: '白天你有多常犯睏？',
      vi: 'Ban ngày bạn buồn ngủ thường xuyên thế nào?',
      id: 'Seberapa sering kamu ngantuk di siang hari?',
    }),
    options: [
      { text: T({ ko: '거의 없다. 낮에 졸리지 않고 활기차다', en: 'Rarely. I’m alert and energetic.', ja: 'ほぼない。日中は元気。', zhCN: '几乎没有，白天很精神。', zhTW: '幾乎沒有，白天很精神。', vi: 'Hầu như không, ban ngày tỉnh táo.', id: 'Hampir tidak. Siang hari segar.' }), score: 0 },
      { text: T({ ko: '점심 식사 후 가끔 졸리지만 크게 방해되지 않는다', en: 'Sometimes after lunch, but it doesn’t bother me much.', ja: '昼食後に少しあるが大きな支障はない。', zhCN: '午饭后偶尔困，但不太影响。', zhTW: '午飯後偶爾睏，但不太影響。', vi: 'Thỉnh thoảng sau bữa trưa nhưng không ảnh hưởng nhiều.', id: 'Kadang setelah makan siang, tapi tidak terlalu mengganggu.' }), score: 1 },
      { text: T({ ko: '오후에 자주 졸리다. 낮잠을 자고 싶은 날이 많다', en: 'Often in the afternoon. I frequently want to nap.', ja: '午後によく眠くなる。昼寝したい日が多い。', zhCN: '下午经常困，经常想午睡。', zhTW: '下午經常睏，常想午睡。', vi: 'Hay buồn ngủ buổi chiều, thường muốn chợp mắt.', id: 'Sering ngantuk sore; sering ingin tidur siang.' }), score: 2 },
      { text: T({ ko: '하루 종일 졸리다. 집중하기 어렵고 에너지가 없다', en: 'All day. It’s hard to focus and I have no energy.', ja: '一日中眠い。集中できずエネルギーがない。', zhCN: '整天都困，难集中、没精力。', zhTW: '整天都睏，難集中、沒精力。', vi: 'Cả ngày buồn ngủ, khó tập trung và thiếu năng lượng.', id: 'Seharian ngantuk; susah fokus dan tidak bertenaga.' }), score: 3 },
    ],
  },
  {
    id: 8,
    question: T({
      ko: '주말 수면 패턴은?',
      en: 'What is your weekend sleep pattern like?',
      ja: '週末の睡眠パターンは？',
      zhCN: '周末你的睡眠模式是？',
      zhTW: '週末你的睡眠模式是？',
      vi: 'Giấc ngủ cuối tuần của bạn thường như thế nào?',
      id: 'Pola tidur akhir pekan kamu bagaimana?',
    }),
    options: [
      { text: T({ ko: '평일과 비슷하게 잔다. 수면 시간이 규칙적이다', en: 'Similar to weekdays. Pretty regular.', ja: '平日と同じくらい。規則的。', zhCN: '和工作日差不多，比较规律。', zhTW: '和工作日差不多，比較規律。', vi: 'Gần giống ngày thường, khá đều.', id: 'Mirip hari kerja. Cukup teratur.' }), score: 0 },
      { text: T({ ko: '1~2시간 정도 더 자는 편이다', en: 'I sleep 1–2 hours more.', ja: '1〜2時間くらい多く寝る。', zhCN: '会多睡1~2小时。', zhTW: '會多睡1~2小時。', vi: 'Ngủ thêm khoảng 1–2 giờ.', id: 'Tidur 1–2 jam lebih lama.' }), score: 1 },
      { text: T({ ko: '평일 부족분을 몰아서 잔다. 2~3시간 이상 더 잔다', en: 'I catch up a lot—2–3+ hours more.', ja: '平日の不足分をまとめて寝る。2〜3時間以上。', zhCN: '会补觉很多，多睡2~3小时以上。', zhTW: '會補覺很多，多睡2~3小時以上。', vi: 'Bù ngủ nhiều: hơn 2–3 giờ.', id: 'Balas dendam tidur: 2–3 jam atau lebih.' }), score: 2 },
      { text: T({ ko: '아침 늦게까지 자거나 낮잠까지 자서 밤에 또 잠을 못 자는 패턴이 반복된다', en: 'I sleep in and even nap, then can’t sleep at night again—this repeats.', ja: '寝坊＋昼寝で夜また眠れない…が繰り返される。', zhCN: '睡懒觉还午睡，导致晚上又睡不着，循环反复。', zhTW: '睡懶覺還午睡，導致晚上又睡不著，循環反覆。', vi: 'Ngủ nướng và còn ngủ ngày, rồi tối lại khó ngủ, cứ lặp lại.', id: 'Tidur sampai siang dan masih tidur siang, malamnya susah tidur lagi; berulang.' }), score: 3 },
    ],
  },
  {
    id: 9,
    question: T({
      ko: '카페인 섭취 습관은?',
      en: 'What is your caffeine habit like?',
      ja: 'カフェインの摂取習慣は？',
      zhCN: '你摄入咖啡因的习惯是？',
      zhTW: '你攝取咖啡因的習慣是？',
      vi: 'Thói quen dùng caffeine của bạn là?',
      id: 'Kebiasaan konsumsi kafein kamu?',
    }),
    options: [
      { text: T({ ko: '오전에만 마시고 오후에는 마시지 않는다', en: 'Only in the morning, none in the afternoon.', ja: '午前だけ。午後は飲まない。', zhCN: '只在上午，下午不喝。', zhTW: '只在上午，下午不喝。', vi: 'Chỉ uống buổi sáng, không uống chiều.', id: 'Hanya pagi, tidak minum sore.' }), score: 0 },
      { text: T({ ko: '오후 2시 이전까지만 마신다', en: 'Only before 2 PM.', ja: '14時まで。', zhCN: '只喝到下午2点前。', zhTW: '只喝到下午2點前。', vi: 'Chỉ trước 14:00.', id: 'Hanya sebelum jam 2 siang.' }), score: 1 },
      { text: T({ ko: '오후 늦게 또는 저녁에도 커피를 마신다', en: 'Late afternoon or even in the evening.', ja: '夕方遅くや夜にも飲む。', zhCN: '下午晚些或晚上也喝。', zhTW: '下午晚些或晚上也喝。', vi: 'Chiều muộn hoặc tối vẫn uống.', id: 'Sore agak malam atau bahkan malam.' }), score: 2 },
      { text: T({ ko: '잠들기 직전까지 에너지 드링크나 커피를 마시는 경우가 있다', en: 'Sometimes right up until bedtime (coffee/energy drinks).', ja: '寝る直前まで飲むこともある（コーヒー/エナドリ）。', zhCN: '有时睡前还在喝（咖啡/能量饮料）。', zhTW: '有時睡前還在喝（咖啡/能量飲料）。', vi: 'Có khi sát giờ ngủ vẫn uống (cà phê/nước tăng lực).', id: 'Kadang sampai menjelang tidur masih minum (kopi/energy drink).' }), score: 3 },
    ],
  },
  {
    id: 10,
    question: T({
      ko: '수면의 질에 대한 나의 주관적인 평가는?',
      en: 'How would you rate your sleep quality?',
      ja: '自分の睡眠の質はどう評価しますか？',
      zhCN: '你主观评价自己的睡眠质量是？',
      zhTW: '你主觀評價自己的睡眠品質是？',
      vi: 'Bạn tự đánh giá chất lượng giấc ngủ của mình thế nào?',
      id: 'Menurutmu kualitas tidurmu bagaimana?',
    }),
    options: [
      { text: T({ ko: '대체로 잘 자는 편이다. 수면에 크게 불만이 없다', en: 'Mostly good. No major complaints.', ja: '概ね良い。不満は少ない。', zhCN: '总体不错，没什么大不满。', zhTW: '總體不錯，沒什麼大不滿。', vi: 'Khá tốt, không có phàn nàn lớn.', id: 'Sebagian besar baik, tidak ada keluhan besar.' }), score: 0 },
      { text: T({ ko: '가끔 아쉬운 날이 있지만 대체로 괜찮다', en: 'Sometimes not great, but generally okay.', ja: 'たまに微妙だが概ね大丈夫。', zhCN: '偶尔不太好，但总体还行。', zhTW: '偶爾不太好，但總體還行。', vi: 'Thỉnh thoảng chưa tốt nhưng nhìn chung ổn.', id: 'Kadang kurang, tapi umumnya oke.' }), score: 1 },
      { text: T({ ko: '수면의 질이 좋지 않다고 느낀다. 잔 것 같지 않을 때가 많다', en: 'Not good. Often I don’t feel like I slept.', ja: '良くない。寝た気がしないことが多い。', zhCN: '不太好，经常感觉没睡够。', zhTW: '不太好，常覺得沒睡到。', vi: 'Không tốt, hay cảm giác như chưa ngủ.', id: 'Kurang bagus; sering merasa seperti tidak tidur.' }), score: 2 },
      { text: T({ ko: '수면 때문에 일상이 힘들 정도로 피로가 쌓여있다', en: 'So bad it affects daily life—fatigue is piling up.', ja: '睡眠のせいで日常がしんどいほど疲労が溜まっている。', zhCN: '差到影响日常，疲劳堆积。', zhTW: '差到影響日常，疲勞堆積。', vi: 'Tệ đến mức ảnh hưởng sinh hoạt, mệt mỏi tích tụ.', id: 'Sampai mengganggu aktivitas harian; lelah menumpuk.' }), score: 3 },
    ],
  },
  {
    id: 11,
    question: T({
      ko: '잠들기 전 걱정이나 생각이 많아지는 편인가요?',
      en: 'Do worries or thoughts increase before you fall asleep?',
      ja: '寝る前に不安や考え事が増えますか？',
      zhCN: '睡前会变得很焦虑/想很多吗？',
      zhTW: '睡前會變得很焦慮/想很多嗎？',
      vi: 'Trước khi ngủ bạn có hay lo lắng/ nghĩ nhiều không?',
      id: 'Sebelum tidur kamu sering overthinking atau cemas?',
    }),
    options: [
      { text: T({ ko: '거의 없다. 눕으면 생각이 차단된다', en: 'Rarely. Lying down shuts my thoughts off.', ja: 'ほぼない。横になると考えが止まる。', zhCN: '几乎没有，躺下就不怎么想了。', zhTW: '幾乎沒有，躺下就不怎麼想了。', vi: 'Hầu như không. Nằm xuống là đầu óc tắt.', id: 'Hampir tidak. Rebahan langsung tenang.' }), score: 0 },
      { text: T({ ko: '가끔 있지만 크게 수면을 방해하지는 않는다', en: 'Sometimes, but it doesn’t interfere much.', ja: 'たまにあるが、あまり邪魔しない。', zhCN: '偶尔有，但不太影响。', zhTW: '偶爾有，但不太影響。', vi: 'Thỉnh thoảng nhưng không ảnh hưởng nhiều.', id: 'Kadang, tapi tidak terlalu mengganggu.' }), score: 1 },
      { text: T({ ko: '자주 있다. 잠들기 전 생각이 많아지는 패턴이 있다', en: 'Often. I tend to think a lot before sleeping.', ja: 'よくある。寝る前に考えが増える。', zhCN: '经常，会在睡前想很多。', zhTW: '經常，會在睡前想很多。', vi: 'Hay có, thường nghĩ nhiều trước khi ngủ.', id: 'Sering. Biasanya overthinking sebelum tidur.' }), score: 2 },
      { text: T({ ko: '매일 있다. 누우면 오히려 머릿속이 바빠지고 불안이 올라온다', en: 'Every day. My mind gets busier and anxiety rises when I lie down.', ja: '毎日。横になると頭が忙しくなり不安が上がる。', zhCN: '每天都是，躺下反而更焦虑更忙。', zhTW: '每天都是，躺下反而更焦慮更忙。', vi: 'Mỗi ngày. Nằm xuống là đầu óc chạy và lo lắng tăng.', id: 'Setiap hari. Rebahan malah makin ramai dan cemas naik.' }), score: 3 },
    ],
  },
  {
    id: 12,
    question: T({
      ko: '지금 나의 수면에 대한 솔직한 평가는?',
      en: 'What is your honest evaluation of your sleep right now?',
      ja: '今の睡眠について正直な評価は？',
      zhCN: '你对现在睡眠的真实评价是？',
      zhTW: '你對現在睡眠的真實評價是？',
      vi: 'Đánh giá thật lòng của bạn về giấc ngủ hiện tại?',
      id: 'Penilaian jujur kamu tentang tidurmu sekarang?',
    }),
    options: [
      { text: T({ ko: '잘 자고 있다. 수면 루틴이 안정돼 있다', en: 'I sleep well. My routine is stable.', ja: 'よく眠れている。ルーティンが安定。', zhCN: '睡得不错，作息很稳定。', zhTW: '睡得不錯，作息很穩定。', vi: 'Ngủ ổn, routine ổn định.', id: 'Tidurku baik, rutinitas stabil.' }), score: 0 },
      { text: T({ ko: '나쁘지 않은데 조금 더 좋아졌으면 한다', en: 'Not bad, but I want it to be better.', ja: '悪くないが、もう少し良くしたい。', zhCN: '不算差，但想更好。', zhTW: '不算差，但想更好。', vi: 'Không tệ nhưng muốn tốt hơn.', id: 'Tidak buruk, tapi ingin lebih baik.' }), score: 1 },
      { text: T({ ko: '수면이 고민이다. 개선이 필요하다는 걸 알고 있다', en: 'Sleep is a concern. I know I need to improve it.', ja: '睡眠が悩み。改善が必要だと分かっている。', zhCN: '睡眠是烦恼，我知道需要改善。', zhTW: '睡眠是煩惱，我知道需要改善。', vi: 'Giấc ngủ là vấn đề, mình biết cần cải thiện.', id: 'Tidur jadi masalah; aku tahu perlu diperbaiki.' }), score: 2 },
      { text: T({ ko: '수면 때문에 많이 힘들다. 뭔가 바꿔야 할 것 같다', en: 'Sleep is really hard. I feel I must change something.', ja: '睡眠でかなり辛い。何か変えないといけない。', zhCN: '因为睡眠很辛苦，必须做些改变。', zhTW: '因為睡眠很辛苦，必須做些改變。', vi: 'Khá mệt vì giấc ngủ, mình phải thay đổi gì đó.', id: 'Aku sangat kesulitan karena tidur; harus ada yang diubah.' }), score: 3 },
    ],
  },
];

export const phase3SleepTypePrescriptionResults: Phase3SleepTypePrescriptionResult[] = [
  {
    type: 'Type1',
    emoji: '🌙',
    title: T({
      ko: '수면 루틴이 안정된, 숙면 마스터형',
      en: 'Good Sleep Master (Stable Routine)',
      ja: '睡眠ルーティン安定・熟睡マスター型',
      zhCN: '作息稳定的「优质睡眠大师」型',
      zhTW: '作息穩定的「優質睡眠大師」型',
      vi: 'Bậc thầy ngủ ngon (Routine ổn định)',
      id: 'Master Tidur Nyenyak (Rutinitas Stabil)',
    }),
    scoreBand: T({
      ko: '총점 0~5점 구간',
      en: 'Total score: 0–5',
      ja: '合計0〜5点',
      zhCN: '总分 0–5 分区间',
      zhTW: '總分 0–5 分區間',
      vi: 'Tổng điểm: 0–5',
      id: 'Skor total: 0–5',
    }),
    sleepTypeLine: T({
      ko: '수면 유형: 건강하고 안정적인 수면 패턴',
      en: 'Sleep type: Healthy, stable sleep pattern',
      ja: '睡眠タイプ：健康で安定したパターン',
      zhCN: '睡眠类型：健康且稳定的睡眠模式',
      zhTW: '睡眠類型：健康且穩定的睡眠模式',
      vi: 'Kiểu ngủ: Nhịp ngủ khỏe mạnh và ổn định',
      id: 'Tipe tidur: Pola tidur sehat dan stabil',
    }),
    hookLine: T({
      ko: '"당신의 수면은 이미 꽤 건강한 상태입니다. 지금의 루틴을 유지하는 것이 가장 중요합니다."',
      en: '"Your sleep is already in a pretty healthy place. The key is keeping your current routine."',
      ja: '「あなたの睡眠はすでにかなり健康。大事なのは今のルーティンを守ること。」',
      zhCN: '“你的睡眠其实已经很健康。最重要的是把现在的作息守住。”',
      zhTW: '「你的睡眠其實已經很健康。最重要的是把現在的作息守住。」',
      vi: '"Giấc ngủ của bạn khá khỏe mạnh rồi. Quan trọng nhất là duy trì routine hiện tại."',
      id: '"Tidurmu sudah cukup sehat. Kuncinya adalah mempertahankan rutinitas yang sekarang."',
    }),
    description: T({
      ko: '취침·기상 시간이 규칙적이고 수면의 질이 높은 편입니다. 잠들기까지 시간이 짧고 중간에 깨는 일이 적으며 아침에 개운하게 일어나는 패턴을 유지하고 있습니다. 수면에 관해 가장 부러운 유형이지만 방심하면 무너질 수 있습니다.',
      en: 'Your bedtime and wake time are consistent, and your sleep quality is high. You fall asleep quickly, rarely wake up, and wake up refreshed. It’s an enviable pattern—but it can slip if you stop paying attention.',
      ja: '就寝・起床が安定し、睡眠の質も高め。入眠が早く中途覚醒も少なく、朝スッキリ起きられています。ただし油断すると崩れやすいのも事実です。',
      zhCN: '你的入睡与起床时间较规律，睡眠质量也偏高：入睡快、夜间醒得少、早上更清爽。这是很令人羡慕的状态，但一放松就可能被打乱。',
      zhTW: '你的入睡與起床時間較規律，睡眠品質也偏高：入睡快、夜間醒得少、早上更清爽。這是很令人羨慕的狀態，但一放鬆就可能被打亂。',
      vi: 'Giờ ngủ–giờ dậy của bạn khá đều và chất lượng ngủ tốt. Bạn dễ vào giấc, ít thức giấc giữa đêm và sáng dậy khá tỉnh. Tuy vậy, nếu chủ quan thì nhịp này cũng có thể bị phá vỡ.',
      id: 'Jam tidur–bangunmu konsisten dan kualitas tidurmu tinggi. Kamu cepat tertidur, jarang terbangun, dan bangun pagi lebih segar. Tapi kalau lengah, ritme ini bisa mudah berantakan.',
    }),
    strengthLine: T({
      ko: '규칙적 리듬·빠른 입면·높은 수면의 질',
      en: 'Stable rhythm · Fast sleep onset · High sleep quality',
      ja: '安定リズム・早い入眠・高い睡眠の質',
      zhCN: '节律稳定 · 入睡快 · 睡眠质量高',
      zhTW: '節律穩定 · 入睡快 · 睡眠品質高',
      vi: 'Nhịp đều · Dễ vào giấc · Chất lượng ngủ cao',
      id: 'Ritme stabil · Cepat tidur · Kualitas tidur tinggi',
    }),
    problemLine: T({
      ko: '스트레스·야근·여행 같은 변수로 루틴이 깨지면 회복에 시간이 걸릴 수 있음',
      en: 'If stress, overtime, or travel breaks your routine, it may take time to recover.',
      ja: 'ストレス・残業・旅行などで崩れると立て直しに時間がかかる。',
      zhCN: '一旦被压力、加班、旅行打乱，恢复节律可能需要时间。',
      zhTW: '一旦被壓力、加班、旅行打亂，恢復節律可能需要時間。',
      vi: 'Khi bị stress/tăng ca/du lịch phá nhịp, bạn có thể mất thời gian để hồi lại.',
      id: 'Kalau ritme rusak karena stres/lembur/perjalanan, pemulihan bisa butuh waktu.',
    }),
    prescriptionText: T({
      ko: ['지금 취침 시간을 ±30분 이내로 주말에도 유지하기', '분기에 한 번 수면 패턴 점검하기', '스트레스가 높은 시기에 수면 루틴을 더 의식적으로 지키기'].join('\n'),
      en: ['Keep your bedtime within ±30 minutes even on weekends.', 'Review your sleep pattern once per quarter.', 'During high-stress periods, protect your sleep routine more intentionally.'].join('\n'),
      ja: ['週末も就寝時間を±30分以内に保つ', '四半期に一度、睡眠パターンを点検する', 'ストレスが高い時期ほど睡眠ルーティンを意識して守る'].join('\n'),
      zhCN: ['周末也把就寝时间控制在±30分钟内', '每季度复盘一次睡眠模式', '压力高的时期，更要有意识地保护睡眠作息'].join('\n'),
      zhTW: ['週末也把就寢時間控制在±30分鐘內', '每季回顧一次睡眠模式', '壓力高的時期，更要有意識地保護睡眠作息'].join('\n'),
      vi: ['Cuối tuần cũng giữ giờ ngủ trong ±30 phút', 'Mỗi quý kiểm tra lại mô hình giấc ngủ một lần', 'Khi stress cao, hãy bảo vệ routine ngủ một cách chủ động hơn'].join('\n'),
      id: ['Akhir pekan pun jaga jam tidur dalam ±30 menit', 'Tinjau pola tidur setiap 3 bulan sekali', 'Saat stres tinggi, lindungi rutinitas tidur dengan lebih sadar'].join('\n'),
    }),
    todayTask: T({
      ko: '지금 수면 루틴을 기록해두기. 무너졌을 때 복구 기준점이 됩니다',
      en: 'Write down your current sleep routine. It becomes your reset baseline when things slip.',
      ja: '今の睡眠ルーティンを記録。崩れた時の復旧基準になります。',
      zhCN: '把你现在的作息记录下来，作为“节律崩掉时”的复位基准。',
      zhTW: '把你現在的作息記錄下來，作為「節律崩掉時」的復位基準。',
      vi: 'Ghi lại routine ngủ hiện tại. Nó là mốc để phục hồi khi bị lệch nhịp.',
      id: 'Catat rutinitas tidurmu sekarang. Ini jadi patokan saat perlu balik lagi.',
    }),
    shareLine: T({
      ko: '수면 유형 분석: 숙면 마스터형 🌙 수면 루틴 안정됐다는 결과... 주변에 부러운 사람 있으면 이거 해보라고 해봐 → 너는 어떤 수면 유형이야?',
      en: 'Sleep type result: Good Sleep Master 🌙 My routine is stable… If you know someone jealous, tell them to try this. What’s your sleep type?',
      ja: '睡眠タイプ結果：熟睡マスター型 🌙 ルーティン安定って出た…気になる人はやってみて。あなたはどのタイプ？',
      zhCN: '睡眠类型结果：优质睡眠大师型 🌙 作息稳定认证…你是什么睡眠类型？',
      zhTW: '睡眠類型結果：優質睡眠大師型 🌙 作息穩定認證…你是什麼睡眠類型？',
      vi: 'Kết quả: Bậc thầy ngủ ngon 🌙 Routine ngủ ổn định… Bạn thuộc kiểu ngủ nào?',
      id: 'Hasil tipe tidur: Master Tidur Nyenyak 🌙 Rutinitas stabil… Kamu tipe tidur yang mana?',
    }),
  },
  {
    type: 'Type2',
    emoji: '😪',
    title: T({
      ko: '잠은 자는데 개운하지 않은, 얕은 수면 피로형',
      en: 'Light Sleep Fatigue Type (Not Refreshed)',
      ja: '寝ているのにスッキリしない・浅い睡眠疲労型',
      zhCN: '睡了也不清爽的「浅睡疲劳」型',
      zhTW: '睡了也不清爽的「淺睡疲勞」型',
      vi: 'Ngủ nhưng không tỉnh: kiểu ngủ nông mệt mỏi',
      id: 'Tidur Tapi Tak Segar: Tipe Tidur Dangkal',
    }),
    scoreBand: T({
      ko: '총점 6~11점 구간',
      en: 'Total score: 6–11',
      ja: '合計6〜11点',
      zhCN: '总分 6–11 分区间',
      zhTW: '總分 6–11 分區間',
      vi: 'Tổng điểm: 6–11',
      id: 'Skor total: 6–11',
    }),
    sleepTypeLine: T({
      ko: '수면 유형: 수면 시간은 충분하지만 질이 낮은 패턴',
      en: 'Sleep type: Enough hours, but low quality',
      ja: '睡眠タイプ：時間は足りているが質が低い',
      zhCN: '睡眠类型：时长够，但质量偏低',
      zhTW: '睡眠類型：時長夠，但品質偏低',
      vi: 'Kiểu ngủ: Ngủ đủ giờ nhưng chất lượng thấp',
      id: 'Tipe tidur: Jam cukup, tapi kualitas rendah',
    }),
    hookLine: T({
      ko: '"충분히 잤는데도 피곤한 이유는 수면의 양이 아닌 질에 있습니다."',
      en: '"If you’re tired after “enough” sleep, the issue is quality—not quantity."',
      ja: '「十分寝たのに疲れるのは“量”ではなく“質”が原因。」',
      zhCN: '“睡够了还累，问题多半在质量，不在时长。”',
      zhTW: '「睡夠了還累，問題多半在品質，不在時長。」',
      vi: '"Ngủ đủ mà vẫn mệt: vấn đề nằm ở chất lượng, không phải số giờ."',
      id: '"Kalau sudah tidur cukup tapi tetap capek, masalahnya kualitas—bukan jumlah jam."',
    }),
    description: T({
      ko: '잠드는 것 자체는 어렵지 않지만 수면 중 자주 깨거나 깊은 수면에 들지 못해서 아침에 개운하지 않은 패턴입니다. 자도 잔 것 같지 않고 낮에 졸음이 자주 오는 것이 특징입니다. 잠의 양보다 질을 개선하는 것이 핵심입니다.',
      en: 'Falling asleep isn’t the main issue, but you wake up easily or don’t reach deep sleep—so mornings feel unrefreshed. You often feel like you didn’t truly sleep and get sleepy during the day. Improving depth and continuity is the key.',
      ja: '入眠は難しくないのに、中途覚醒が多い・深い睡眠に入りにくく、朝スッキリしないタイプ。寝た気がせず日中も眠くなりがち。量より質の改善がポイントです。',
      zhCN: '你并不难入睡，但容易醒来或难以进入深睡，所以早上不清爽。常有“睡了也像没睡”的感觉，白天也更易犯困。关键是提升睡眠深度与连续性。',
      zhTW: '你並不難入睡，但容易醒來或難以進入深睡，所以早上不清爽。常有「睡了也像沒睡」的感覺，白天也更易犯睏。關鍵是提升睡眠深度與連續性。',
      vi: 'Bạn không quá khó vào giấc, nhưng hay tỉnh hoặc ngủ không đủ sâu nên sáng dậy không tỉnh táo. Thường có cảm giác “ngủ mà như chưa ngủ” và hay buồn ngủ ban ngày. Mấu chốt là tăng độ sâu và tính liên tục của giấc ngủ.',
      id: 'Kamu tidak terlalu susah tertidur, tapi mudah terbangun atau sulit masuk tidur nyenyak sehingga pagi tidak segar. Sering terasa seperti “tidur tapi tidak tidur” dan mudah ngantuk siang hari. Kuncinya meningkatkan kedalaman dan kontinuitas tidur.',
    }),
    strengthLine: T({
      ko: '입면은 비교적 쉬운 편',
      en: 'Relatively easy to fall asleep',
      ja: '入眠は比較的スムーズ',
      zhCN: '相对容易入睡',
      zhTW: '相對容易入睡',
      vi: 'Tương đối dễ vào giấc',
      id: 'Relatif mudah tertidur',
    }),
    problemLine: T({
      ko: '수면 깊이 부족·잦은 각성·낮 피로 누적',
      en: 'Not enough deep sleep · Frequent awakenings · Daytime fatigue',
      ja: '睡眠が浅い・中途覚醒・日中の疲労蓄積',
      zhCN: '深睡不足 · 易醒 · 白天疲劳累积',
      zhTW: '深睡不足 · 易醒 · 白天疲勞累積',
      vi: 'Thiếu ngủ sâu · Hay tỉnh · Mệt mỏi ban ngày',
      id: 'Kurang tidur nyenyak · Sering terbangun · Lelah di siang hari',
    }),
    prescriptionText: T({
      ko: [
        '취침 전 실내 온도를 18~20도로 낮추기. 체온이 내려가야 깊은 수면에 들어갈 수 있음',
        '자기 전 스마트폰 블루라이트 차단. 수면 1시간 전 화면 끄기',
        '알코올 섭취 줄이기. 술은 잠들게 하지만 수면의 질을 크게 떨어뜨림',
        '수면 추적 앱이나 웨어러블로 수면 단계 모니터링해보기',
        '취침 전 10분 복식 호흡이나 스트레칭으로 부교감 신경 활성화',
      ].join('\n'),
      en: [
        'Lower your room temperature to 18–20°C before bed—cooling helps you reach deeper sleep.',
        'Cut blue light: put screens away 1 hour before sleep.',
        'Reduce alcohol—it may make you drowsy but significantly worsens sleep quality.',
        'Try a sleep-tracking app or wearable to monitor sleep stages.',
        'Do 10 minutes of slow breathing or gentle stretching to activate your parasympathetic system.',
      ].join('\n'),
      ja: [
        '就寝前に室温を18〜20℃へ。体温が下がると深い睡眠に入りやすい',
        'ブルーライト対策：寝る1時間前は画面オフ',
        'アルコールを減らす。寝付きは良くても睡眠の質は下がりやすい',
        '睡眠計測アプリ/ウェアラブルで睡眠段階を可視化',
        '就寝前10分の腹式呼吸や軽いストレッチで副交感神経を優位に',
      ].join('\n'),
      zhCN: [
        '睡前把室温降到 18–20℃：体温下降更容易进入深睡',
        '减少蓝光：睡前 1 小时停止看屏幕',
        '减少酒精：可能更易入睡，但会明显拉低睡眠质量',
        '用睡眠追踪 App/可穿戴设备观察睡眠阶段',
        '睡前 10 分钟腹式呼吸或轻柔拉伸，启动副交感神经',
      ].join('\n'),
      zhTW: [
        '睡前把室溫降到 18–20℃：體溫下降更容易進入深睡',
        '減少藍光：睡前 1 小時停止看螢幕',
        '減少酒精：可能更易入睡，但會明顯拉低睡眠品質',
        '用睡眠追蹤 App/穿戴裝置觀察睡眠階段',
        '睡前 10 分鐘腹式呼吸或輕柔伸展，啟動副交感神經',
      ].join('\n'),
      vi: [
        'Hạ nhiệt độ phòng xuống 18–20°C trước khi ngủ: cơ thể mát hơn giúp ngủ sâu.',
        'Giảm ánh sáng xanh: tắt màn hình 1 giờ trước khi ngủ.',
        'Giảm rượu: dễ buồn ngủ nhưng làm giảm chất lượng giấc ngủ.',
        'Dùng app/thiết bị theo dõi giấc ngủ để xem các giai đoạn ngủ.',
        '10 phút thở chậm hoặc giãn cơ nhẹ để kích hoạt hệ phó giao cảm.',
      ].join('\n'),
      id: [
        'Turunkan suhu kamar ke 18–20°C sebelum tidur—lebih sejuk membantu tidur lebih nyenyak.',
        'Kurangi blue light: berhenti layar 1 jam sebelum tidur.',
        'Kurangi alkohol—bisa bikin ngantuk tapi menurunkan kualitas tidur.',
        'Coba aplikasi/ wearable pelacak tidur untuk memantau tahap tidur.',
        '10 menit napas pelan atau peregangan ringan untuk mengaktifkan sistem parasimpatik.',
      ].join('\n'),
    }),
    todayTask: T({
      ko: '오늘 밤 자기 전 30분 일찍 스마트폰 내려놓기. 작은 변화가 수면 질을 바꿉니다',
      en: 'Tonight, put your phone down 30 minutes earlier. Small changes shift sleep quality.',
      ja: '今夜は30分早くスマホを置く。小さな変化が睡眠の質を変えます。',
      zhCN: '今晚睡前提前 30 分钟放下手机，小改变会带来大提升。',
      zhTW: '今晚睡前提前 30 分鐘放下手機，小改變會帶來大提升。',
      vi: 'Tối nay đặt điện thoại xuống sớm hơn 30 phút. Thay đổi nhỏ tạo khác biệt lớn.',
      id: 'Malam ini, taruh HP 30 menit lebih awal. Perubahan kecil bisa meningkatkan kualitas tidur.',
    }),
    shareLine: T({
      ko: '수면 유형 분석: 얕은 수면 피로형 😪 자도 피곤한 이유가 수면 질 문제였구나... 처방전 저장함 → 너는 어떤 수면 유형이야?',
      en: 'Sleep type result: Light Sleep Fatigue 😪 So that’s why I’m tired even after sleeping… saving this prescription. What’s your sleep type?',
      ja: '睡眠タイプ結果：浅い睡眠疲労型 😪 寝ても疲れる理由が分かった…処方箋保存。あなたはどのタイプ？',
      zhCN: '睡眠类型结果：浅睡疲劳型 😪 原来睡了还累是质量问题…处方先存。你是什么类型？',
      zhTW: '睡眠類型結果：淺睡疲勞型 😪 原來睡了還累是品質問題…處方先存。你是什麼類型？',
      vi: 'Kết quả: Ngủ nông mệt mỏi 😪 Hóa ra ngủ vẫn mệt là do chất lượng… lưu “đơn” luôn. Bạn thuộc kiểu nào?',
      id: 'Hasil: Tidur Dangkal 😪 Pantas saja tidur tetap capek… simpan resepnya. Kamu tipe yang mana?',
    }),
  },
  {
    type: 'Type3',
    emoji: '📱',
    title: T({
      ko: '폰 때문에 늦게 자는, 블루라이트 수면 방해형',
      en: 'Blue-Light Sleep Disruptor (Phone at Bedtime)',
      ja: 'スマホで寝るのが遅くなる・ブルーライト妨害型',
      zhCN: '手机蓝光干扰的「睡眠破坏」型',
      zhTW: '手機藍光干擾的「睡眠破壞」型',
      vi: 'Kiểu bị điện thoại/ánh sáng xanh phá giấc',
      id: 'Tipe Gangguan Tidur karena Blue Light (HP)',
    }),
    scoreBand: T({
      ko: '총점 12~19점 구간',
      en: 'Total score: 12–19',
      ja: '合計12〜19点',
      zhCN: '总分 12–19 分区间',
      zhTW: '總分 12–19 分區間',
      vi: 'Tổng điểm: 12–19',
      id: 'Skor total: 12–19',
    }),
    sleepTypeLine: T({
      ko: '수면 유형: 스마트폰·전자기기가 수면을 방해하는 패턴',
      en: 'Sleep type: Screens and devices disrupt your sleep',
      ja: '睡眠タイプ：スマホ/電子機器が睡眠を妨げる',
      zhCN: '睡眠类型：屏幕与设备在干扰你的睡眠',
      zhTW: '睡眠類型：螢幕與裝置在干擾你的睡眠',
      vi: 'Kiểu ngủ: Màn hình/thiết bị điện tử làm rối giấc ngủ',
      id: 'Tipe tidur: Layar & perangkat mengganggu tidur',
    }),
    hookLine: T({
      ko: '"잠들기 전 스마트폰 사용이 당신의 수면을 조용히 망가뜨리고 있습니다."',
      en: '"Using your phone before sleep is quietly sabotaging your rest."',
      ja: '「寝る前のスマホが、あなたの睡眠を静かに壊しています。」',
      zhCN: '“睡前刷手机，正在悄悄毁掉你的睡眠。”',
      zhTW: '「睡前滑手機，正在悄悄毀掉你的睡眠。」',
      vi: '"Dùng điện thoại trước khi ngủ đang âm thầm phá giấc ngủ của bạn."',
      id: '"Main HP sebelum tidur diam-diam merusak kualitas istirahatmu."',
    }),
    description: T({
      ko: '자려고 누웠지만 스마트폰을 보다가 결국 늦게 자는 패턴이 반복됩니다. 블루라이트는 뇌에 아직 낮이라는 신호를 보내서 멜라토닌 분비를 방해합니다. 의지력의 문제가 아닙니다. 환경을 바꾸는 것이 핵심입니다.',
      en: 'You lie down to sleep, but end up on your phone and go to bed late—again and again. Blue light signals “it’s still daytime” to your brain and suppresses melatonin. This isn’t about willpower; changing your environment works best.',
      ja: '寝ようとしてもスマホを見てしまい、結局寝るのが遅くなる…が繰り返し。ブルーライトは脳に「まだ昼」と誤認させ、メラトニン分泌を妨げます。意志の問題ではなく、環境設計がカギ。',
      zhCN: '你本来要睡，却刷着手机就越睡越晚。蓝光会让大脑误以为“还是白天”，抑制褪黑素分泌。这不是意志力的问题，关键是改变环境。',
      zhTW: '你本來要睡，卻滑著手機就越睡越晚。藍光會讓大腦誤以為「還是白天」，抑制褪黑素分泌。這不是意志力的問題，關鍵是改變環境。',
      vi: 'Bạn nằm xuống định ngủ nhưng rồi lướt điện thoại và ngủ muộn lặp đi lặp lại. Ánh sáng xanh gửi tín hiệu “vẫn là ban ngày” lên não và ức chế melatonin. Đây không phải vấn đề ý chí—thiết kế lại môi trường mới là chìa khóa.',
      id: 'Kamu sudah rebahan, tapi akhirnya main HP dan jadi tidur larut—berulang. Blue light memberi sinyal “masih siang” ke otak dan menekan melatonin. Ini bukan soal tekad; kuncinya mengubah lingkungan.',
    }),
    strengthLine: T({
      ko: '수면에 대한 인식은 있음. 고치고 싶다는 의지가 있음',
      en: 'You’re aware of the issue and want to fix it',
      ja: '問題意識があり、直したい意欲がある',
      zhCN: '你意识到问题，也愿意改善',
      zhTW: '你意識到問題，也願意改善',
      vi: 'Bạn có nhận thức và muốn thay đổi',
      id: 'Kamu sadar masalahnya dan ingin memperbaiki',
    }),
    problemLine: T({
      ko: '취침 시간 지연·멜라토닌 분비 방해·입면 어려움',
      en: 'Delayed bedtime · Melatonin suppression · Harder to fall asleep',
      ja: '就寝の遅れ・メラトニン抑制・入眠困難',
      zhCN: '睡得更晚 · 抑制褪黑素 · 更难入睡',
      zhTW: '睡得更晚 · 抑制褪黑素 · 更難入睡',
      vi: 'Ngủ muộn · Ức chế melatonin · Khó vào giấc',
      id: 'Tidur makin larut · Melatonin tertekan · Susah tertidur',
    }),
    prescriptionText: T({
      ko: [
        '침실에서 스마트폰 충전하지 않기. 충전기를 방 밖으로 꺼내는 것이 가장 효과적',
        '취침 1시간 전 스마트폰 대신 종이책·팟캐스트·조용한 음악으로 대체',
        '스마트폰 수면 모드 또는 다운타임 기능 설정하기. 설정하면 의지력 없이도 작동됨',
        '아침 알람을 위한 전용 알람 시계 구매 고려. 폰을 방 밖에 둘 수 있음',
        '자기 전 15분 저널링(일기 쓰기)으로 머릿속 정리하기',
      ].join('\n'),
      en: [
        'Don’t charge your phone in the bedroom—put the charger outside. It’s the most effective move.',
        'Replace the last hour with paper books, podcasts, or calm music.',
        'Enable Sleep/Do Not Disturb/Downtime—let settings do the work for you.',
        'Consider a dedicated alarm clock so your phone can stay out of the room.',
        'Journal for 15 minutes before bed to unload thoughts.',
      ].join('\n'),
      ja: [
        '寝室でスマホを充電しない。充電器を部屋の外へ（最強）',
        '就寝1時間前は紙の本・ポッドキャスト・静かな音楽に置き換え',
        'おやすみモード/ダウンタイム設定で意志に頼らずブロック',
        '目覚まし専用時計を検討。スマホを部屋の外に置ける',
        '寝る前15分のジャーナリングで頭の中を吐き出す',
      ].join('\n'),
      zhCN: [
        '卧室里不要给手机充电：把充电器放到房间外，这是最有效的一步',
        '睡前 1 小时用纸质书/播客/轻音乐替代手机',
        '开启睡眠模式/专注模式/停用时间，让设置替你执行',
        '考虑用独立闹钟，这样手机可以放到房外',
        '睡前 15 分钟写日记，把思绪“倒出来”',
      ].join('\n'),
      zhTW: [
        '臥室裡不要給手機充電：把充電器放到房間外，這是最有效的一步',
        '睡前 1 小時用紙本書/播客/輕音樂替代手機',
        '開啟睡眠模式/專注模式/停用時間，讓設定替你執行',
        '考慮用獨立鬧鐘，讓手機可以放到房外',
        '睡前 15 分鐘寫日記，把思緒「倒出來」',
      ].join('\n'),
      vi: [
        'Đừng sạc điện thoại trong phòng ngủ—để bộ sạc ra ngoài (hiệu quả nhất).',
        'Thay 1 giờ cuối bằng sách giấy/podcast/nhạc nhẹ.',
        'Bật chế độ ngủ/Không làm phiền/Downtime để “cài đặt” làm thay bạn.',
        'Cân nhắc đồng hồ báo thức riêng để điện thoại ở ngoài phòng.',
        'Viết nhật ký 15 phút trước khi ngủ để “xả” suy nghĩ.',
      ].join('\n'),
      id: [
        'Jangan cas HP di kamar tidur—taruh chargernya di luar (paling efektif).',
        'Ganti 1 jam terakhir dengan buku fisik/podcast/musik tenang.',
        'Aktifkan mode tidur/DND/Downtime biar setting yang bekerja.',
        'Pertimbangkan jam alarm terpisah supaya HP bisa di luar kamar.',
        'Jurnal 15 menit sebelum tidur untuk mengosongkan pikiran.',
      ].join('\n'),
    }),
    todayTask: T({
      ko: '오늘 밤 충전기를 방 밖으로 꺼내보기. 딱 하루만. 내일 아침이 달라집니다',
      en: 'Tonight, move your charger outside the bedroom—just for one night. Tomorrow morning will feel different.',
      ja: '今夜は充전器を部屋の外へ。まず1日だけ。明日の朝が変わります。',
      zhCN: '今晚把充电器移到卧室外，就一晚。明天早上你会感觉不一样。',
      zhTW: '今晚把充電器移到臥室外，就一晚。明天早上你會感覺不一樣。',
      vi: 'Tối nay hãy để bộ sạc ra ngoài phòng ngủ—chỉ 1 đêm thôi. Sáng mai sẽ khác.',
      id: 'Malam ini pindahkan charger ke luar kamar—cuma 1 malam. Besok pagi akan terasa beda.',
    }),
    shareLine: T({
      ko: '수면 유형 분석: 블루라이트 수면 방해형 📱 폰이 수면 망치고 있다는 거 알고 있었는데 확인됨... 오늘 밤 충전기 방 밖으로 꺼냄 → 너는 어떤 수면 유형이야?',
      en: 'Sleep type result: Blue-Light Sleep Disruptor 📱 Confirmed… my phone is ruining my sleep. Charger goes outside tonight. What’s your sleep type?',
      ja: '睡眠タイプ結果：ブルーライト妨害型 📱 やっぱりスマホが原因だった…今夜は充電器を外へ。あなたはどのタイプ？',
      zhCN: '睡眠类型结果：蓝光干扰型 📱 证实了：手机真的在毁睡眠…今晚充电器放房外。你是什么类型？',
      zhTW: '睡眠類型結果：藍光干擾型 📱 證實了：手機真的在毀睡眠…今晚充電器放房外。你是什麼類型？',
      vi: 'Kết quả: Bị ánh sáng xanh phá giấc 📱 Xác nhận luôn… tối nay để sạc ra ngoài. Bạn thuộc kiểu nào?',
      id: 'Hasil: Gangguan Blue Light 📱 Fix… HP memang merusak tidur. Malam ini charger di luar. Kamu tipe apa?',
    }),
  },
  {
    type: 'Type4',
    emoji: '🔀',
    title: T({
      ko: '불규칙한 패턴이 몸을 혼란시키는, 수면 리듬 붕괴형',
      en: 'Sleep Rhythm Collapse Type (Irregular Pattern)',
      ja: '不規則で体内時計が混乱・睡眠リズム崩壊型',
      zhCN: '作息不规律导致的「睡眠节律崩坏」型',
      zhTW: '作息不規律導致的「睡眠節律崩壞」型',
      vi: 'Kiểu vỡ nhịp ngủ (thất thường)',
      id: 'Tipe Ritme Tidur Berantakan (Tidak Teratur)',
    }),
    scoreBand: T({
      ko: '총점 20~27점 구간',
      en: 'Total score: 20–27',
      ja: '合計20〜27点',
      zhCN: '总分 20–27 分区间',
      zhTW: '總分 20–27 分區間',
      vi: 'Tổng điểm: 20–27',
      id: 'Skor total: 20–27',
    }),
    sleepTypeLine: T({
      ko: '수면 유형: 불규칙한 취침·기상 패턴으로 생체 리듬이 흔들린 상태',
      en: 'Sleep type: Your body clock is shaken by irregular sleep/wake times',
      ja: '睡眠タイプ：不規則な就寝・起床で体内時計が揺れている',
      zhCN: '睡眠类型：不规律的睡/起时间让生物钟被摇乱',
      zhTW: '睡眠類型：不規律的睡/起時間讓生理時鐘被搖亂',
      vi: 'Kiểu ngủ: Đồng hồ sinh học bị lệch do giờ ngủ–giờ dậy thất thường',
      id: 'Tipe tidur: Jam biologis terguncang karena jam tidur–bangun tidak konsisten',
    }),
    hookLine: T({
      ko: '"매일 다른 시간에 자고 일어나는 것이 당신의 몸시계를 완전히 망가뜨리고 있습니다."',
      en: '"Going to bed and waking up at different times is wrecking your internal clock."',
      ja: '「毎日バラバラの就寝・起床が体内時計を壊しています。」',
      zhCN: '“每天不同时间睡和起，正在把你的生物钟彻底弄乱。”',
      zhTW: '「每天不同時間睡和起，正在把你的生理時鐘徹底弄亂。」',
      vi: '"Ngủ–dậy mỗi ngày một giờ đang phá đồng hồ sinh học của bạn."',
      id: '"Jam tidur-bangun yang berubah-ubah tiap hari sedang merusak jam tubuhmu."',
    }),
    description: T({
      ko: '평일과 주말 수면 패턴이 크게 다르고, 취침 시간이 매일 달라지는 것이 특징입니다. 이것을 사회적 시차증(Social Jetlag)이라고 합니다. 몸이 오늘 몇 시에 자야 하는지 예측할 수 없어서 항상 준비되지 않은 상태가 됩니다. 리듬을 다시 잡는 것이 모든 처방보다 먼저입니다.',
      en: 'Your weekday and weekend sleep schedules differ a lot, and your bedtime shifts day to day. This is often called “social jetlag.” Your body can’t predict when to sleep, so it’s never truly ready. Restoring rhythm comes before any other fix.',
      ja: '平日と週末で睡眠が大きくズレ、就寝時間も日によって変わりがち。これは「ソーシャル・ジェットラグ」と呼ばれ、体が“今日は何時に寝るのか”を予測できません。まずリズムの再構築が最優先です。',
      zhCN: '你的工作日与周末作息差异很大，入睡时间也天天变。这常被称为“社会时差”。身体无法预测今晚几点该睡，所以总处在没准备好的状态。先把节律拉回来，比任何处方都重要。',
      zhTW: '你的工作日與週末作息差異很大，入睡時間也天天變。這常被稱為「社會時差」。身體無法預測今晚幾點該睡，所以總處在沒準備好的狀態。先把節律拉回來，比任何處方都重要。',
      vi: 'Giờ ngủ ngày thường và cuối tuần lệch nhau nhiều, và giờ đi ngủ thay đổi theo ngày. Đây thường được gọi là “social jetlag”. Cơ thể không đoán được khi nào nên ngủ nên luôn ở trạng thái chưa sẵn sàng. Việc kéo nhịp về lại là ưu tiên số 1.',
      id: 'Pola tidur hari kerja dan akhir pekanmu sangat berbeda, dan jam tidur berubah-ubah. Ini sering disebut “social jetlag”. Tubuhmu tidak bisa memprediksi kapan harus tidur, jadi tidak pernah benar-benar siap. Memperbaiki ritme adalah langkah pertama sebelum apa pun.',
    }),
    strengthLine: T({
      ko: '피로가 쌓이면 어디서든 잘 수 있는 적응력',
      en: 'Adaptability—you can sleep anywhere when exhausted',
      ja: '疲れればどこでも寝られる適応力',
      zhCN: '适应力强：累到极点时在哪都能睡',
      zhTW: '適應力強：累到極點時在哪都能睡',
      vi: 'Khả năng thích nghi: mệt là ngủ được ở đâu cũng được',
      id: 'Adaptif: kalau capek bisa tidur di mana saja',
    }),
    problemLine: T({
      ko: '불규칙한 리듬·주말 몰아자기·만성 피로',
      en: 'Irregular rhythm · Weekend catch-up sleep · Chronic fatigue',
      ja: '不規則なリズム・週末の寝だめ・慢性的疲労',
      zhCN: '节律不稳 · 周末补觉 · 慢性疲劳',
      zhTW: '節律不穩 · 週末補覺 · 慢性疲勞',
      vi: 'Nhịp thất thường · Ngủ bù cuối tuần · Mệt mỏi mạn tính',
      id: 'Ritme tidak teratur · Balas dendam tidur · Lelah kronis',
    }),
    prescriptionText: T({
      ko: [
        '기상 시간부터 먼저 고정하기. 취침 시간보다 기상 시간 고정이 더 효과적',
        '주말 기상 시간을 평일과 1시간 이내로 맞추기. 2시간 이상 차이나면 몸시계가 흔들림',
        '주말 몰아자기 대신 낮잠 20분으로 대체하기',
        '기상 후 햇빛 받기. 커튼을 열거나 5분만 밖에 나가도 생체 리듬 재설정 가능',
        '4주 동안 같은 시간에 자고 일어나기 챌린지 시도',
      ].join('\n'),
      en: [
        'Fix your wake-up time first—this works better than forcing bedtime.',
        'Keep weekend wake time within 1 hour of weekdays (2+ hours destabilizes your clock).',
        'Replace “sleeping in” with a 20-minute nap if needed.',
        'Get morning light: open curtains or go outside for 5 minutes to reset rhythm.',
        'Try a 4-week “same sleep-wake time” challenge.',
      ].join('\n'),
      ja: [
        'まず起床時間を固定（就寝より効果的）',
        '週末の起床も平日±1時間以内（2時間以上ズレると乱れやすい）',
        '寝だめの代わりに20分の昼寝で調整',
        '起床後の光：カーテンを開ける/5分外に出るだけでもリセット',
        '4週間、同じ時間に寝起きするチャレンジ',
      ].join('\n'),
      zhCN: [
        '先固定起床时间：比强行固定入睡更有效',
        '周末起床时间尽量控制在工作日±1小时内（差2小时以上就会乱）',
        '用 20 分钟小睡替代“睡到中午”',
        '起床后晒光：拉开窗帘或出门 5 分钟即可重置节律',
        '尝试 4 周“同一时间睡/起”的挑战',
      ].join('\n'),
      zhTW: [
        '先固定起床時間：比強行固定入睡更有效',
        '週末起床時間盡量控制在平日±1小時內（差2小時以上就會亂）',
        '用 20 分鐘小睡替代「睡到中午」',
        '起床後曬光：拉開窗簾或出門 5 分鐘即可重置節律',
        '嘗試 4 週「同一時間睡/起」的挑戰',
      ].join('\n'),
      vi: [
        'Cố định giờ dậy trước—hiệu quả hơn ép giờ đi ngủ.',
        'Cuối tuần dậy lệch tối đa 1 giờ so với ngày thường (lệch 2+ giờ dễ rối nhịp).',
        'Thay “ngủ nướng” bằng ngủ trưa 20 phút khi cần.',
        'Đón ánh sáng buổi sáng: mở rèm hoặc ra ngoài 5 phút để reset nhịp.',
        'Thử thách 4 tuần ngủ–dậy cùng giờ.',
      ].join('\n'),
      id: [
        'Kunci jam bangun dulu—lebih efektif daripada memaksa jam tidur.',
        'Akhir pekan bangun maksimal selisih 1 jam dari hari kerja (selisih 2+ jam bikin kacau).',
        'Ganti “tidur siang sampai siang” dengan power nap 20 menit bila perlu.',
        'Dapatkan cahaya pagi: buka tirai atau keluar 5 menit untuk reset ritme.',
        'Coba tantangan 4 minggu tidur-bangun di jam yang sama.',
      ].join('\n'),
    }),
    todayTask: T({
      ko: '내일 기상 알람을 설정하고 그 시간보다 늦게 자지 않도록 목표 설정하기',
      en: 'Set a wake-up alarm for tomorrow and plan your bedtime to hit it.',
      ja: '明日の起床アラームを決め、その時間に間に合う就寝目標を立てる',
      zhCN: '设置明天的起床闹钟，并倒推一个能做到的就寝目标',
      zhTW: '設定明天的起床鬧鐘，並倒推一個能做到的就寢目標',
      vi: 'Đặt báo thức giờ dậy cho ngày mai và đặt mục tiêu giờ ngủ để kịp dậy.',
      id: 'Pasang alarm bangun besok dan tentukan target jam tidur agar bisa bangun sesuai.',
    }),
    shareLine: T({
      ko: '수면 유형 분석: 수면 리듬 붕괴형 🔀 주말에 몰아자는 거 오히려 독이라는 거... 뼈 때리는 결과 ㅠ 처방전 저장해둠 → 너는 어떤 수면 유형이야?',
      en: 'Sleep type result: Sleep Rhythm Collapse 🔀 Turns out weekend “catch-up sleep” can backfire… saving this prescription. What’s your sleep type?',
      ja: '睡眠タイプ結果：睡眠リズム崩壊型 🔀 週末の寝だめが逆効果って…刺さる…。処方箋保存。あなたはどのタイプ？',
      zhCN: '睡眠类型结果：节律崩坏型 🔀 原来周末疯狂补觉反而伤…先把处方存了。你是什么类型？',
      zhTW: '睡眠類型結果：節律崩壞型 🔀 原來週末瘋狂補覺反而傷…先把處方存了。你是什麼類型？',
      vi: 'Kết quả: Vỡ nhịp ngủ 🔀 Hóa ra ngủ bù cuối tuần còn phản tác dụng… lưu đơn lại. Bạn thuộc kiểu nào?',
      id: 'Hasil: Ritme Tidur Berantakan 🔀 Ternyata balas dendam tidur akhir pekan bisa jadi racun… simpan resepnya. Kamu tipe apa?',
    }),
  },
  {
    type: 'Type5',
    emoji: '💭',
    title: T({
      ko: '생각이 수면을 방해하는, 과각성 불면형',
      en: 'Hyperarousal Insomnia Type (Overthinking)',
      ja: '考えが止まらない・過覚醒不眠型',
      zhCN: '思绪停不下来的「过度觉醒失眠」型',
      zhTW: '思緒停不下來的「過度覺醒失眠」型',
      vi: 'Kiểu mất ngủ do quá căng não (quá thức)',
      id: 'Tipe Insomnia Hiperarousal (Overthinking)',
    }),
    scoreBand: T({
      ko: '총점 28~33점 구간',
      en: 'Total score: 28–33',
      ja: '合計28〜33点',
      zhCN: '总分 28–33 分区间',
      zhTW: '總分 28–33 分區間',
      vi: 'Tổng điểm: 28–33',
      id: 'Skor total: 28–33',
    }),
    sleepTypeLine: T({
      ko: '수면 유형: 잠들기 전 과도한 생각과 걱정으로 잠을 이루지 못하는 패턴',
      en: 'Sleep type: Too many thoughts and worries before sleep',
      ja: '睡眠タイプ：寝る前の考えすぎ・不安で眠れない',
      zhCN: '睡眠类型：睡前想太多、担心太多导致难入睡',
      zhTW: '睡眠類型：睡前想太多、擔心太多導致難入睡',
      vi: 'Kiểu ngủ: Nghĩ và lo quá nhiều trước khi ngủ',
      id: 'Tipe tidur: Kebanyakan pikiran & cemas sebelum tidur',
    }),
    hookLine: T({
      ko: '"몸은 피곤한데 머릿속은 쉬지 않습니다. 이것이 당신의 불면의 본질입니다."',
      en: '"Your body is tired, but your mind won’t rest. That’s the core of your insomnia."',
      ja: '「体は疲れているのに、頭が休まない。それが不眠の本質です。」',
      zhCN: '“身体很累，但大脑停不下来——这就是失眠的本质。”',
      zhTW: '「身體很累，但大腦停不下來——這就是失眠的本質。」',
      vi: '"Cơ thể mệt nhưng đầu óc không chịu nghỉ—đó là cốt lõi của mất ngủ."',
      id: '"Badan capek, tapi pikiran tidak mau berhenti—itulah inti insomnianya."',
    }),
    description: T({
      ko: '누우면 오히려 생각이 많아지고 걱정이 올라오는 과각성 상태가 수면을 방해하고 있습니다. 잠을 자야 한다는 강박 자체가 각성을 높이는 악순환이 반복됩니다. 수면을 억지로 만들려는 노력을 멈추고 뇌의 긴장을 풀어주는 것이 핵심입니다.',
      en: 'When you lie down, your brain becomes even more active—thoughts and worries rise, keeping you in a hyperaroused state. The pressure to “must sleep” increases alertness and creates a vicious cycle. The key is reducing mental tension, not forcing sleep.',
      ja: '横になると考えや不安が増えて過覚醒になり、睡眠を妨げています。「寝なきゃ」という焦りが覚醒をさらに高める悪循環。無理に眠ろうとせず、脳の緊張を下げるのがポイントです。',
      zhCN: '你一躺下思绪反而更活跃，担心也上来，进入“过度觉醒”状态从而难以入睡。“必须睡着”的压力会让大脑更清醒，形成恶性循环。关键是降低大脑紧张，而不是硬逼自己睡。',
      zhTW: '你一躺下思緒反而更活躍，擔心也上來，進入「過度覺醒」狀態從而難以入睡。「必須睡著」的壓力會讓大腦更清醒，形成惡性循環。關鍵是降低大腦緊張，而不是硬逼自己睡。',
      vi: 'Khi nằm xuống, đầu óc bạn lại hoạt động mạnh hơn: suy nghĩ và lo lắng trỗi lên khiến cơ thể ở trạng thái “quá thức”. Áp lực “phải ngủ” làm bạn càng tỉnh và tạo vòng lặp tiêu cực. Chìa khóa là hạ căng thẳng cho não, không phải ép ngủ.',
      id: 'Saat rebahan, otakmu malah makin aktif—pikiran dan kekhawatiran naik, membuatmu berada dalam kondisi “terlalu siaga”. Tekanan “harus tidur” justru meningkatkan kewaspadaan dan jadi siklus buruk. Kuncinya menurunkan ketegangan mental, bukan memaksa tidur.',
    }),
    strengthLine: T({
      ko: '문제의 원인을 인식하고 있음',
      en: 'You can recognize what’s happening',
      ja: '原因に気づけている',
      zhCN: '你能意识到问题所在',
      zhTW: '你能意識到問題所在',
      vi: 'Bạn nhận ra nguyên nhân',
      id: 'Kamu sadar akar masalahnya',
    }),
    problemLine: T({
      ko: '입면 어려움·취침 전 과각성·수면 강박·만성 피로',
      en: 'Hard to fall asleep · Hyperarousal at bedtime · Sleep pressure · Chronic fatigue',
      ja: '入眠困難・就寝前の過覚醒・睡眠への焦り・慢性疲労',
      zhCN: '难入睡 · 睡前过度觉醒 · 睡眠焦虑 · 慢性疲劳',
      zhTW: '難入睡 · 睡前過度覺醒 · 睡眠焦慮 · 慢性疲勞',
      vi: 'Khó vào giấc · Quá thức trước ngủ · Áp lực phải ngủ · Mệt mỏi kéo dài',
      id: 'Susah tertidur · Terlalu siaga sebelum tidur · Tekanan harus tidur · Lelah kronis',
    }),
    prescriptionText: T({
      ko: [
        '걱정 시간 분리하기. 자기 전이 아닌 저녁 6~7시에 걱정 목록을 노트에 적고 닫기',
        '4-7-8 호흡법: 4초 들숨·7초 참기·8초 날숨을 3회 반복. 부교감 신경을 빠르게 활성화',
        '잠이 안 올 때 억지로 자려 하지 않기. 오히려 일어나서 조용한 활동 후 다시 눕기',
        '취침 전 하루 걱정 목록 적고 \"내일의 나에게 맡긴다\"고 선언하기',
        '필요하다면 수면 인지행동치료(CBT-I) 앱 또는 전문가 상담 고려',
      ].join('\n'),
      en: [
        'Separate “worry time”: write your worries at 6–7 PM, not in bed, then close the notebook.',
        '4-7-8 breathing: inhale 4s, hold 7s, exhale 8s × 3 rounds to activate the parasympathetic system.',
        'If you can’t sleep, don’t force it—get up, do something quiet, then return to bed.',
        'Before bed, list today’s worries and say: “I’ll hand this to tomorrow me.”',
        'If needed, consider CBT-I apps or professional support.',
      ].join('\n'),
      ja: [
        '「心配タイム」を分離：寝る前ではなく18〜19時に心配を書き出して閉じる',
        '4-7-8呼吸：4秒吸う→7秒止める→8秒吐く×3回で副交感神経を活性化',
        '眠れない時に無理に寝ない。起きて静かな活動→眠気が来たら戻る',
        '就寝前に心配を書き出し「明日の自分に預ける」と宣言',
        '必要ならCBT-Iアプリ/専門家相談も検討',
      ].join('\n'),
      zhCN: [
        '把“担心时间”移出床：在傍晚 6–7 点写下担心清单，然后合上本子',
        '4-7-8 呼吸：吸 4 秒、憋 7 秒、呼 8 秒 ×3 轮，快速启动副交感神经',
        '睡不着别硬躺：起身做安静活动，困了再回床上',
        '睡前写下今天的担心，并对自己说：交给明天的我处理',
        '必要时考虑 CBT-I（失眠认知行为疗法）App 或专业咨询',
      ].join('\n'),
      zhTW: [
        '把「擔心時間」移出床：在傍晚 6–7 點寫下擔心清單，然後合上本子',
        '4-7-8 呼吸：吸 4 秒、憋 7 秒、呼 8 秒 ×3 輪，快速啟動副交感神經',
        '睡不著別硬躺：起身做安靜活動，困了再回床上',
        '睡前寫下今天的擔心，並對自己說：交給明天的我處理',
        '必要時考慮 CBT-I（失眠認知行為療法）App 或專業諮詢',
      ].join('\n'),
      vi: [
        'Tách “giờ lo lắng”: viết danh sách lo lắng lúc 18–19h (không phải trên giường) rồi gấp sổ lại.',
        'Thở 4-7-8: hít 4s, giữ 7s, thở ra 8s ×3 vòng để kích hoạt hệ phó giao cảm.',
        'Nếu không ngủ được, đừng ép: hãy đứng dậy làm việc yên tĩnh rồi quay lại khi buồn ngủ.',
        'Trước khi ngủ, ghi lo lắng của hôm nay và nói: “Giao cho mình của ngày mai.”',
        'Nếu cần, cân nhắc CBT-I (liệu pháp nhận thức hành vi cho mất ngủ) hoặc tư vấn chuyên môn.',
      ].join('\n'),
      id: [
        'Pisahkan “worry time”: tulis daftar kekhawatiran jam 6–7 malam (bukan di kasur), lalu tutup bukunya.',
        'Napas 4-7-8: tarik 4 detik, tahan 7 detik, hembus 8 detik ×3 putaran untuk mengaktifkan sistem parasimpatik.',
        'Kalau tidak bisa tidur, jangan dipaksa—bangun, lakukan aktivitas tenang, lalu kembali saat mengantuk.',
        'Sebelum tidur, tulis kekhawatiran hari ini dan bilang: “Aku serahkan ke aku besok.”',
        'Jika perlu, pertimbangkan CBT-I atau bantuan profesional.',
      ].join('\n'),
    }),
    todayTask: T({
      ko: '자기 전에 걱정되는 것 3가지를 노트에 적고 덮어두기. 머릿속에서 꺼내면 생각이 줄어듭니다',
      en: 'Before bed, write down 3 worries and close the notebook. Taking them out of your head reduces them.',
      ja: '寝る前に心配を3つ書いて閉じる。頭の外に出すと考えが減ります。',
      zhCN: '睡前写下 3 件让你担心的事，然后合上本子。把它们从脑袋里拿出来，思绪会少很多。',
      zhTW: '睡前寫下 3 件讓你擔心的事，然後合上本子。把它們從腦袋裡拿出來，思緒會少很多。',
      vi: 'Trước khi ngủ, viết 3 điều đang lo rồi gấp sổ lại. Đưa ra khỏi đầu là nhẹ hơn.',
      id: 'Sebelum tidur, tulis 3 hal yang kamu khawatirkan lalu tutup bukunya. Keluar dari kepala = pikiran berkurang.',
    }),
    shareLine: T({
      ko: '수면 유형 분석: 과각성 불면형 💭 몸은 피곤한데 머릿속이 쉬질 않는 거 공감 폭발... 걱정 노트 시작해봄 → 너는 어떤 수면 유형이야?',
      en: 'Sleep type result: Hyperarousal Insomnia 💭 Body tired, mind won’t stop… starting a worry notebook tonight. What’s your sleep type?',
      ja: '睡眠タイプ結果：過覚醒不眠型 💭 体は疲れてるのに頭が止まらない…心配ノート始める。あなたはどのタイプ？',
      zhCN: '睡眠类型结果：过度觉醒失眠型 💭 身体累但大脑停不下…今晚开始“担心笔记”。你是什么类型？',
      zhTW: '睡眠類型結果：過度覺醒失眠型 💭 身體累但大腦停不下…今晚開始「擔心筆記」。你是什麼類型？',
      vi: 'Kết quả: Mất ngủ do quá thức 💭 Người mệt mà đầu không nghỉ… tối nay bắt đầu sổ lo lắng. Bạn kiểu nào?',
      id: 'Hasil: Insomnia Hiperarousal 💭 Badan capek tapi pikiran tidak berhenti… mulai “worry notebook” malam ini. Kamu tipe apa?',
    }),
  },
  {
    type: 'Type6',
    emoji: '🌑',
    title: T({
      ko: '수면이 일상을 무너뜨리는, 만성 수면 장애형',
      en: 'Chronic Sleep Disorder Type (Daily Life Impact)',
      ja: '日常が崩れる・慢性睡眠障害型',
      zhCN: '影响日常的「慢性睡眠障碍」型',
      zhTW: '影響日常的「慢性睡眠障礙」型',
      vi: 'Rối loạn giấc ngủ mạn tính (ảnh hưởng sinh hoạt)',
      id: 'Gangguan Tidur Kronis (Mengganggu Aktivitas)',
    }),
    scoreBand: T({
      ko: '총점 34~36점 구간',
      en: 'Total score: 34–36',
      ja: '合計34〜36点',
      zhCN: '总分 34–36 分区间',
      zhTW: '總分 34–36 分區間',
      vi: 'Tổng điểm: 34–36',
      id: 'Skor total: 34–36',
    }),
    sleepTypeLine: T({
      ko: '수면 유형: 수면 문제가 일상 전반에 영향을 미치는 심각한 수면 곤란 상태',
      en: 'Sleep type: Severe sleep difficulty impacting daily functioning',
      ja: '睡眠タイプ：睡眠問題が日常機能に影響する深刻な状態',
      zhCN: '睡眠类型：睡眠问题已明显影响日常功能',
      zhTW: '睡眠類型：睡眠問題已明顯影響日常功能',
      vi: 'Kiểu ngủ: Vấn đề ngủ nghiêm trọng ảnh hưởng sinh hoạt hằng ngày',
      id: 'Tipe tidur: Masalah tidur berat yang memengaruhi fungsi harian',
    }),
    hookLine: T({
      ko: '"수면 문제가 단순한 습관의 문제를 넘어섰을 수 있습니다. 혼자 해결하려 하지 않아도 됩니다."',
      en: '"Your sleep issue may have gone beyond habits. You don’t have to solve it alone."',
      ja: '「睡眠は単なる習慣の問題を超えているかもしれません。ひとりで抱えなくて大丈夫。」',
      zhCN: '“这可能已经不只是习惯问题了。你不需要一个人硬扛。”',
      zhTW: '「這可能已經不只是習慣問題了。你不需要一個人硬扛。」',
      vi: '"Vấn đề ngủ có thể đã vượt qua mức “thói quen”. Bạn không cần tự giải quyết một mình."',
      id: '"Masalah tidurmu mungkin sudah lebih dari sekadar kebiasaan. Kamu tidak harus mengatasinya sendirian."',
    }),
    description: T({
      ko: '잠들기 어려움·잦은 각성·아무리 자도 피곤함·낮의 극심한 졸음이 복합적으로 나타나고 있으며 이것이 일상 기능을 방해하는 수준입니다. 생활 습관 교정만으로는 충분하지 않을 수 있으며 전문적인 평가와 도움이 필요한 시기일 수 있습니다.',
      en: 'Difficulty falling asleep, frequent awakenings, unrefreshing sleep, and severe daytime sleepiness are all showing up—and they’re disrupting your daily life. Habit tweaks alone may not be enough. This may be the right time for professional evaluation and support.',
      ja: '入眠困難・中途覚醒・寝ても疲れる・日中の強い眠気が複合的に出ており、日常機能に支障が出ているレベル。生活習慣の改善だけでは足りない可能性があり、専門的な評価とサポートが必要な時期かもしれません。',
      zhCN: '入睡困难、频繁醒来、睡再久也累、白天极度嗜睡等多种问题同时出现，并已影响到日常生活。仅靠习惯调整可能不够，建议尽快进行专业评估与获得支持。',
      zhTW: '入睡困難、頻繁醒來、睡再久也累、白天極度嗜睡等多種問題同時出現，並已影響到日常生活。僅靠習慣調整可能不夠，建議儘快進行專業評估與獲得支持。',
      vi: 'Bạn có nhiều vấn đề cùng lúc: khó ngủ, hay tỉnh, ngủ bao nhiêu cũng mệt, buồn ngủ dữ dội ban ngày—và nó đã ảnh hưởng rõ đến sinh hoạt. Chỉ chỉnh thói quen có thể chưa đủ; đây có thể là lúc cần đánh giá và hỗ trợ chuyên môn.',
      id: 'Beberapa masalah muncul bersamaan: susah tidur, sering terbangun, tidur tetap lelah, dan sangat mengantuk di siang hari—hingga mengganggu aktivitas. Perbaikan kebiasaan saja mungkin tidak cukup; ini bisa jadi saat yang tepat untuk evaluasi dan bantuan profesional.',
    }),
    strengthLine: T({
      ko: '수면 문제를 인식하고 개선하려는 의지가 있음',
      en: 'You recognize the problem and want to improve',
      ja: '問題を認識し、改善したい意志がある',
      zhCN: '你能意识到问题并愿意改善',
      zhTW: '你能意識到問題並願意改善',
      vi: 'Bạn nhận thức vấn đề và muốn cải thiện',
      id: 'Kamu sadar masalahnya dan ingin membaik',
    }),
    problemLine: T({
      ko: '입면 곤란·잦은 각성·수면 유지 어려움·낮 기능 저하 복합 발생',
      en: 'Sleep onset/maintenance issues · Frequent awakenings · Daytime impairment',
      ja: '入眠/維持の困難・中途覚醒・日中機能の低下',
      zhCN: '难入睡/难维持 · 易醒 · 白天功能下降',
      zhTW: '難入睡/難維持 · 易醒 · 白天功能下降',
      vi: 'Khó vào giấc/duy trì · Hay tỉnh · Giảm chức năng ban ngày',
      id: 'Susah mulai/menjaga tidur · Sering terbangun · Fungsi siang menurun',
    }),
    prescriptionText: T({
      ko: [
        '수면 일지 2주 작성하기. 취침·기상 시간·중간에 깬 횟수·낮 피로도를 기록. 전문가 상담 시 중요한 자료가 됩니다',
        '오늘부터 카페인 오후 2시 이후 완전 차단하기',
        '침실은 수면과 성생활 외에는 사용하지 않기. 뇌가 침대=수면으로 연결하도록 훈련',
        '낮잠은 20분 이내로 제한. 낮잠이 밤 수면을 방해하지 않도록',
        '수면 클리닉 또는 정신건강의학과 수면 전문 상담을 강력히 권합니다',
      ].join('\n'),
      en: [
        'Keep a sleep diary for 2 weeks (bedtime, wake time, awakenings, daytime fatigue). It’s valuable for clinicians.',
        'From today, cut caffeine completely after 2 PM.',
        'Use your bedroom only for sleep and intimacy—train your brain: bed = sleep.',
        'Limit naps to 20 minutes so they don’t disrupt nighttime sleep.',
        'Strongly consider a sleep clinic or a mental health professional specializing in sleep.',
      ].join('\n'),
      ja: [
        '2週間の睡眠日誌（就寝/起床、覚醒回数、日中の疲労）をつける。受診時の重要資料',
        '今日から14時以降のカフェインを完全カット',
        '寝室は睡眠と性生活以外に使わない（ベッド＝睡眠を学習）',
        '昼寝は20分以内。夜の睡眠を妨げないため',
        '睡眠外来/睡眠に詳しい精神科・心療内科での相談を強く推奨',
      ].join('\n'),
      zhCN: [
        '坚持记录 2 周睡眠日记（睡/起时间、醒来次数、白天疲劳程度），就诊时很关键',
        '从今天起，下午 2 点后彻底停用咖啡因',
        '卧室只用于睡眠与亲密：训练大脑“床=睡觉”',
        '午睡控制在 20 分钟内，避免影响夜间睡眠',
        '强烈建议咨询睡眠门诊/睡眠专科或相关精神心理专业',
      ].join('\n'),
      zhTW: [
        '堅持記錄 2 週睡眠日記（睡/起時間、醒來次數、白天疲勞程度），就診時很關鍵',
        '從今天起，下午 2 點後徹底停用咖啡因',
        '臥室只用於睡眠與親密：訓練大腦「床=睡覺」',
        '午睡控制在 20 分鐘內，避免影響夜間睡眠',
        '強烈建議諮詢睡眠門診/睡眠專科或相關精神心理專業',
      ].join('\n'),
      vi: [
        'Ghi nhật ký giấc ngủ 2 tuần (giờ ngủ–giờ dậy, số lần tỉnh, mức mệt ban ngày). Rất hữu ích khi đi khám.',
        'Từ hôm nay, cắt caffeine hoàn toàn sau 14:00.',
        'Chỉ dùng phòng ngủ cho ngủ và thân mật: tập cho não “giường = ngủ”.',
        'Giới hạn ngủ trưa trong 20 phút để không phá giấc ngủ đêm.',
        'Cân nhắc mạnh mẽ khám/ tư vấn chuyên khoa giấc ngủ.',
      ].join('\n'),
      id: [
        'Buat sleep diary 2 minggu (jam tidur-bangun, berapa kali terbangun, lelah siang). Ini penting saat konsultasi.',
        'Mulai hari ini, stop kafein total setelah jam 2 siang.',
        'Gunakan kamar tidur hanya untuk tidur & intim: latih otak bahwa kasur = tidur.',
        'Batasi tidur siang maksimal 20 menit agar tidak mengganggu tidur malam.',
        'Sangat disarankan konsultasi ke klinik tidur atau profesional kesehatan mental yang fokus tidur.',
      ].join('\n'),
    }),
    warningLine: T({
      ko: '⚠️ 전문 상담 안내: 만성적 수면 문제는 혼자 해결하기 어렵습니다. 수면 클리닉이나 정신건강의학과 수면 전문 진료를 받아보세요. 수면 장애는 치료가 가능합니다',
      en: '⚠️ Professional help: Chronic sleep problems are hard to fix alone. Consider a sleep clinic or a sleep-focused medical evaluation—sleep disorders are treatable.',
      ja: '⚠️ 専門相談：慢性的な睡眠問題は一人で解決しにくいです。睡眠外来や睡眠に詳しい医療機関へ。睡眠障害は治療可能です。',
      zhCN: '⚠️ 专业咨询：长期睡眠问题很难靠自己解决。建议就诊睡眠门诊/相关专业评估——睡眠障碍是可以治疗的。',
      zhTW: '⚠️ 專業諮詢：長期睡眠問題很難靠自己解決。建議就診睡眠門診/相關專業評估——睡眠障礙是可以治療的。',
      vi: '⚠️ Tư vấn chuyên môn: Vấn đề ngủ mạn tính rất khó tự xử lý. Hãy cân nhắc khám/tư vấn chuyên khoa—rối loạn giấc ngủ có thể điều trị.',
      id: '⚠️ Bantuan profesional: Masalah tidur kronis sulit diselesaikan sendiri. Pertimbangkan klinik tidur/evaluasi medis—gangguan tidur bisa ditangani.',
    }),
    todayTask: T({
      ko: '오늘 밤 수면 일지 첫 페이지 시작하기. 취침 시간·기상 시간·중간에 깬 횟수·아침 피로도 1~10점으로 기록하기',
      en: 'Start a sleep diary tonight: bedtime, wake time, awakenings, and morning fatigue (1–10).',
      ja: '今夜から睡眠日誌の1ページ目。就寝/起床、覚醒回数、朝の疲労度(1〜10)を記録。',
      zhCN: '今晚开始睡眠日记：睡/起时间、醒来次数、早晨疲劳度（1–10）。',
      zhTW: '今晚開始睡眠日記：睡/起時間、醒來次數、早晨疲勞度（1–10）。',
      vi: 'Tối nay bắt đầu nhật ký giấc ngủ: giờ ngủ–giờ dậy, số lần tỉnh, mức mệt buổi sáng (1–10).',
      id: 'Mulai sleep diary malam ini: jam tidur-bangun, berapa kali terbangun, dan lelah pagi (1–10).',
    }),
    shareLine: T({
      ko: '수면 유형 분석: 만성 수면 장애형 🌑 수면 일지 오늘부터 시작... 이 결과 보고 뭔가 해야겠다는 생각 들었음 → 너는 어떤 수면 유형이야?',
      en: 'Sleep type result: Chronic Sleep Disorder 🌑 Starting a sleep diary today… this result made me realize I need to act. What’s your sleep type?',
      ja: '睡眠タイプ結果：慢性睡眠障害型 🌑 今日から睡眠日誌…この結果でちゃんと動こうと思った。あなたはどのタイプ？',
      zhCN: '睡眠类型结果：慢性睡眠障碍型 🌑 今天开始写睡眠日记…看到结果觉得真的该行动了。你是什么类型？',
      zhTW: '睡眠類型結果：慢性睡眠障礙型 🌑 今天開始寫睡眠日記…看到結果覺得真的該行動了。你是什麼類型？',
      vi: 'Kết quả: Rối loạn giấc ngủ mạn tính 🌑 Bắt đầu nhật ký ngủ từ hôm nay… kết quả này khiến mình muốn hành động. Bạn thuộc kiểu nào?',
      id: 'Hasil: Gangguan Tidur Kronis 🌑 Mulai sleep diary hari ini… hasil ini bikin aku sadar harus bertindak. Kamu tipe apa?',
    }),
  },
];

