/** 나의 호기심 유형 진단 — phase3-curiosity-type · 12문항 4지선다 · A=0/B=1/C=2/D=3 · 7개 로케일 */

export type Phase3CuriosityTypeLocaleKey = 'ko' | 'en' | 'ja' | 'zh-CN' | 'zh-TW' | 'vi' | 'id';

function localeMap(t: Record<Phase3CuriosityTypeLocaleKey, string>): Record<Phase3CuriosityTypeLocaleKey, string> {
  return t;
}

function opt(m: Record<Phase3CuriosityTypeLocaleKey, string>, score: number): { text: Record<Phase3CuriosityTypeLocaleKey, string>; score: number } {
  return { text: localeMap(m), score };
}

export interface Phase3CuriosityTypeQuestion {
  id: number;
  question: Record<Phase3CuriosityTypeLocaleKey, string>;
  options: { text: Record<Phase3CuriosityTypeLocaleKey, string>; score: number }[];
}

export interface Phase3CuriosityTypeResult {
  type: string;
  emoji: string;
  title: Record<Phase3CuriosityTypeLocaleKey, string>;
  curiositySummary: Record<Phase3CuriosityTypeLocaleKey, string>;
  quote: Record<Phase3CuriosityTypeLocaleKey, string>;
  description: Record<Phase3CuriosityTypeLocaleKey, string>;
  curiosityType: Record<Phase3CuriosityTypeLocaleKey, string>;
  exploreKeywords: Record<Phase3CuriosityTypeLocaleKey, string>;
  strengths: Record<Phase3CuriosityTypeLocaleKey, string>;
  cautions: Record<Phase3CuriosityTypeLocaleKey, string>;
  contentRecommend: Record<Phase3CuriosityTypeLocaleKey, string>;
  growCuriosity: Record<Phase3CuriosityTypeLocaleKey, string>;
  certificationPhrase: Record<Phase3CuriosityTypeLocaleKey, string>;
  oneLiner: Record<Phase3CuriosityTypeLocaleKey, string>;
  shareLine: Record<Phase3CuriosityTypeLocaleKey, string>;
}

export function calculatePhase3CuriosityTypeResult(answers: number[]): string {
  const total = answers.reduce((sum, s) => sum + (s ?? 0), 0);
  if (total <= 5) return 'Type1';
  if (total <= 11) return 'Type2';
  if (total <= 19) return 'Type3';
  if (total <= 27) return 'Type4';
  if (total <= 33) return 'Type5';
  return 'Type6';
}

export function calculatePhase3CuriosityTypeDomainScores(answers: number[]) {
  const interestScope = (answers[0] ?? 0) + (answers[1] ?? 0);
  const exploreMethod = (answers[2] ?? 0) + (answers[3] ?? 0);
  const questionTendency = (answers[4] ?? 0) + (answers[5] ?? 0);
  const learningPattern = (answers[6] ?? 0) + (answers[7] ?? 0);
  const interestTrigger = (answers[8] ?? 0) + (answers[9] ?? 0);
  const curiosityPersistence = (answers[10] ?? 0) + (answers[11] ?? 0);
  return {
    interestScope,
    exploreMethod,
    questionTendency,
    learningPattern,
    interestTrigger,
    curiosityPersistence,
    total: answers.reduce((sum, s) => sum + (s ?? 0), 0),
  };
}

export const phase3CuriosityTypeQuestions: Phase3CuriosityTypeQuestion[] = [
  {
    id: 1,
    question: localeMap({
      ko: '새로운 것을 접할 때 나는?',
      en: 'When I encounter something new, I:',
      ja: '新しいものに出会ったとき、私は？',
      'zh-CN': '接触新事物时，我会？',
      'zh-TW': '接觸新事物時，我會？',
      vi: 'Khi gặp điều mới, tôi:',
      id: 'Saat menemukan hal baru, aku:',
    }),
    options: [
      opt(localeMap({
        ko: '지금 당장 필요하거나 유용한 것에만 관심이 생긴다. 필요 없는 것을 굳이 알려 하지 않는다',
        en: 'Only get interested in what I need or find useful right now. I do not bother learning what I do not need',
        ja: '今すぐ必要または役立つものにだけ関心が湧く。不要なものをわざわざ知ろうとしない',
        'zh-CN': '只对当下需要或有用的东西感兴趣，没必要的东西不会特意去了解',
        'zh-TW': '只對當下需要或有用的東西感興趣，沒必要的東西不會特意去了解',
        vi: 'Chỉ quan tâm thứ cần ngay hoặc hữu ích. Không cố tìm hiểu thứ không cần',
        id: 'Hanya tertarik pada yang dibutuhkan atau berguna sekarang. Tidak repot tahu yang tidak perlu',
    }), 0),
      opt(localeMap({
        ko: '관심 분야가 정해져 있고 그 안에서 새로운 것을 발견하는 것을 좋아한다',
        en: 'Have set interest areas and enjoy discovering new things within them',
        ja: '関心分野が決まっていて、その中で新しい発見を楽しむ',
        'zh-CN': '有固定的兴趣领域，喜欢在其中发现新东西',
        'zh-TW': '有固定的興趣領域，喜歡在其中發現新東西',
        vi: 'Có lĩnh vực quan tâm cố định và thích khám phá điều mới trong đó',
        id: 'Punya bidang minat tertentu dan suka menemukan hal baru di dalamnya',
    }), 1),
      opt(localeMap({
        ko: '여러 분야에 걸쳐 흥미로운 것들을 수집하다가 뜻밖의 연결을 발견할 때 즐겁다',
        en: 'Collect interesting things across fields and enjoy unexpected connections',
        ja: '複数分野の面白いものを集め、思いがけないつながりを見つけると楽しい',
        'zh-CN': '跨领域收集有趣的东西，发现意外连接时很开心',
        'zh-TW': '跨領域收集有趣的東西，發現意外連結時很開心',
        vi: 'Thu thập điều thú vị ở nhiều lĩnh vực và vui khi phát hiện kết nối bất ngờ',
        id: 'Mengumpulkan hal menarik lintas bidang dan senang saat menemukan koneksi tak terduga',
    }), 2),
      opt(localeMap({
        ko: '뭐든 새로운 것이면 일단 흥미롭다. 관심 분야 경계가 거의 없다',
        en: 'Find almost anything new interesting. My interest boundaries are barely defined',
        ja: '新しいものなら何でも面白い。関心分野の境界がほとんどない',
        'zh-CN': '只要是新的几乎都有趣，兴趣边界几乎不存在',
        'zh-TW': '只要是新的幾乎都有趣，興趣邊界幾乎不存在',
        vi: 'Gần như mọi thứ mới đều thú vị. Ranh giới quan tâm gần như không có',
        id: 'Hampir semua yang baru menarik. Batas minat hampir tidak ada',
    }), 3),
    ],
  },
  {
    id: 2,
    question: localeMap({
      ko: '관심사가 생겼을 때 나는 얼마나 넓게 파는가?',
      en: 'When interest arises, how broadly do I dig?',
      ja: '関心が生まれたとき、どれだけ広く掘るか？',
      'zh-CN': '产生兴趣时，我会挖多广？',
      'zh-TW': '產生興趣時，我會挖多廣？',
      vi: 'Khi có hứng thú, tôi đào sâu rộng đến đâu?',
      id: 'Saat minat muncul, seberapa luas aku gali?',
    }),
    options: [
      opt(localeMap({
        ko: '꼭 필요한 부분만 파악하면 충분하다. 실용적인 범위 안에서 알고 싶다',
        en: 'Grasping only what I need is enough. I want to know within a practical range',
        ja: '必要な部分だけ把握すれば十分。実用的な範囲内で知りたい',
        'zh-CN': '掌握必要部分就够了，想在实用范围内了解',
        'zh-TW': '掌握必要部分就夠了，想在實用範圍內了解',
        vi: 'Nắm phần cần thiết là đủ. Muốn biết trong phạm vi thực tế',
        id: 'Memahami bagian yang perlu sudah cukup. Ingin tahu dalam ruang praktis',
    }), 0),
      opt(localeMap({
        ko: '그 분야 안에서 깊이 파고드는 편이다. 넓이보다 깊이가 더 중요하다',
        en: 'I tend to go deep within that field. Depth matters more than breadth',
        ja: 'その分野の中で深く掘る方。広さより深さが重要',
        'zh-CN': '倾向在该领域内深挖，深度比广度更重要',
        'zh-TW': '傾向在該領域內深挖，深度比廣度更重要',
        vi: 'Thường đi sâu trong lĩnh vực đó. Chiều sâu quan trọng hơn chiều rộng',
        id: 'Cenderung mendalami di bidang itu. Kedalaman lebih penting dari keluasan',
    }), 1),
      opt(localeMap({
        ko: '본래 관심사에서 시작해 연결된 분야들까지 자연스럽게 탐색하게 된다',
        en: 'Starting from the original interest, I naturally explore connected fields',
        ja: 'もともとの関心から始まり、つながった分野まで自然に探索する',
        'zh-CN': '从原本兴趣出发，自然延伸到相关领域探索',
        'zh-TW': '從原本興趣出發，自然延伸到相關領域探索',
        vi: 'Từ quan tâm ban đầu, tự nhiên khám phá các lĩnh vực liên quan',
        id: 'Dari minat awal, secara alami mengeksplorasi bidang terkait',
    }), 2),
      opt(localeMap({
        ko: '한 가지를 알면 그것과 관련된 모든 것이 궁금해진다. 끝을 정하기 어렵다',
        en: 'Learning one thing makes me curious about everything related. Hard to set an end point',
        ja: '一つ知ると関連するすべてが気になる。終わりを決めにくい',
        'zh-CN': '知道一样就会好奇所有相关的东西，很难设定终点',
        'zh-TW': '知道一樣就會好奇所有相關的東西，很難設定終點',
        vi: 'Biết một thứ thì mọi thứ liên quan đều tò mò. Khó đặt điểm dừng',
        id: 'Tahu satu hal, semua yang terkait jadi penasaran. Sulit tentukan titik akhir',
    }), 3),
    ],
  },
  {
    id: 3,
    question: localeMap({
      ko: '무언가를 이해하고 싶을 때 나는 어떻게 탐구하는가?',
      en: 'When I want to understand something, how do I explore?',
      ja: '何かを理解したいとき、どう探索するか？',
      'zh-CN': '想理解某事时，我如何探索？',
      'zh-TW': '想理解某事時，我如何探索？',
      vi: 'Khi muốn hiểu điều gì đó, tôi khám phá thế nào?',
      id: 'Saat ingin memahami sesuatu, bagaimana aku mengeksplorasi?',
    }),
    options: [
      opt(localeMap({
        ko: '핵심 개념만 빠르게 파악하는 편이다. 구체적인 활용 방법 위주로 알고 싶다',
        en: 'I quickly grasp core concepts. I want to know mainly how to apply it',
        ja: '核心概念を素早く把握する方。具体的な活用方法中心で知りたい',
        'zh-CN': '倾向快速掌握核心概念，主要想知道具体怎么用',
        'zh-TW': '傾向快速掌握核心概念，主要想知道具體怎麼用',
        vi: 'Nhanh nắm khái niệm cốt lõi. Muốn biết chủ yếu cách áp dụng',
        id: 'Cepat pahami konsep inti. Ingin tahu terutama cara menerapkannya',
    }), 0),
      opt(localeMap({
        ko: '관련 책·강의·자료를 체계적으로 찾아서 깊이 공부한다. 정확하게 이해해야 넘어갈 수 있다',
        en: 'I systematically find books, lectures, and materials and study deeply. I must understand accurately before moving on',
        ja: '関連書籍・講義・資料を体系的に探して深く学ぶ。正確に理解してから次へ',
        'zh-CN': '系统找书、课程、资料深入学习，准确理解后才能继续',
        'zh-TW': '系統找書、課程、資料深入學習，準確理解後才能繼續',
        vi: 'Tìm sách, bài giảng, tài liệu có hệ thống và học sâu. Phải hiểu chính xác mới sang bước sau',
        id: 'Mencari buku, kuliah, materi secara sistematis dan belajar mendalam. Harus paham akurat dulu',
    }), 1),
      opt(localeMap({
        ko: '여러 자료를 넓게 훑다가 흥미로운 연결 고리나 패턴을 발견하면 그곳을 더 파고든다',
        en: 'I skim many sources broadly, then dig deeper where I find interesting links or patterns',
        ja: '複数資料を広く読み、面白いつながりやパターンを見つけたところを深掘りする',
        'zh-CN': '广泛浏览多种资料，发现有趣连接或模式的地方再深挖',
        'zh-TW': '廣泛瀏覽多種資料，發現有趣連結或模式的地方再深挖',
        vi: 'Lướt nhiều nguồn rộng rồi đào sâu nơi thấy liên kết hoặc mẫu thú vị',
        id: 'Menelusuri banyak sumber secara luas, lalu gali lebih dalam di titik koneksi atau pola menarik',
    }), 2),
      opt(localeMap({
        ko: '직접 경험해보거나 다양한 사람의 시각을 듣거나 이것저것 시도해보면서 파악한다',
        en: 'I learn by trying it myself, hearing diverse views, and experimenting',
        ja: '直接体験したり多様な視点を聞いたり試しながら把握する',
        'zh-CN': '通过亲身体验、听不同观点、各种尝试来理解',
        'zh-TW': '透過親身體驗、聽不同觀點、各種嘗試來理解',
        vi: 'Học bằng trải nghiệm trực tiếp, nghe nhiều góc nhìn và thử nghiệm',
        id: 'Belajar dengan mencoba sendiri, mendengar berbagai sudut pandang, dan bereksperimen',
    }), 3),
    ],
  },
  {
    id: 4,
    question: localeMap({
      ko: '잘 모르는 것을 발견했을 때 나는?',
      en: 'When I discover something I do not know well, I:',
      ja: 'よく分からないものを発見したとき、私は？',
      'zh-CN': '发现不太了解的东西时，我会？',
      'zh-TW': '發現不太了解的東西時，我會？',
      vi: 'Khi phát hiện điều mình chưa hiểu rõ, tôi:',
      id: 'Saat menemukan sesuatu yang belum aku pahami, aku:',
    }),
    options: [
      opt(localeMap({
        ko: '지금 당장 알 필요가 없으면 그냥 넘어간다. 모르는 것이 있어도 크게 불편하지 않다',
        en: 'Move on if I do not need to know right now. Not knowing does not bother me much',
        ja: '今知る必要がなければそのまま進む。知らなくても大きく不快ではない',
        'zh-CN': '当下不需要知道就跳过，不知道也不太困扰',
        'zh-TW': '當下不需要知道就跳過，不知道也不太困擾',
        vi: 'Bỏ qua nếu chưa cần biết ngay. Không biết cũng không quá khó chịu',
        id: 'Lanjutkan jika belum perlu tahu sekarang. Tidak tahu tidak terlalu mengganggu',
    }), 0),
      opt(localeMap({
        ko: '그 분야의 전문적인 자료를 찾아서 제대로 이해하고 넘어가야 마음이 편하다',
        en: 'I must find expert materials and understand properly before I feel at ease',
        ja: '専門的な資料を見つけてきちんと理解してからでないと落ち着かない',
        'zh-CN': '必须找专业资料好好理解才能安心',
        'zh-TW': '必須找專業資料好好理解才能安心',
        vi: 'Phải tìm tài liệu chuyên môn và hiểu đúng mới yên tâm',
        id: 'Harus temukan materi ahli dan pahami dengan benar baru tenang',
    }), 1),
      opt(localeMap({
        ko: '일단 개요를 파악하고 나중에 더 깊이 알아볼 것들을 저장해둔다',
        en: 'I grasp the overview first and save topics to explore deeper later',
        ja: 'まず概要を把握し、後で深く調べるものを保存する',
        'zh-CN': '先掌握概貌，把以后要深入了解的存起来',
        'zh-TW': '先掌握概貌，把以後要深入了解的存起來',
        vi: 'Nắm tổng quan trước và lưu chủ đề để tìm hiểu sâu sau',
        id: 'Pahami gambaran dulu dan simpan topik untuk pelajari lebih dalam nanti',
    }), 2),
      opt(localeMap({
        ko: '당장 알고 싶어서 검색이 시작된다. 모르는 상태로 있는 것이 불편하다',
        en: 'I want to know immediately and start searching. Being in the unknown feels uncomfortable',
        ja: 'すぐ知りたくなり検索が始まる。知らない状態が居心地悪い',
        'zh-CN': '立刻想知道并开始搜索，处于未知状态会不自在',
        'zh-TW': '立刻想知道並開始搜尋，處於未知狀態會不自在',
        vi: 'Muốn biết ngay và bắt đầu tìm kiếm. Ở trạng thái không biết khó chịu',
        id: 'Langsung ingin tahu dan mulai mencari. Berada dalam ketidaktahuan tidak nyaman',
    }), 3),
    ],
  },
  {
    id: 5,
    question: localeMap({
      ko: '어떤 사실을 알게 됐을 때 나는?',
      en: 'When I learn a fact, I:',
      ja: 'ある事実を知ったとき、私は？',
      'zh-CN': '得知某个事实时，我会？',
      'zh-TW': '得知某個事實時，我會？',
      vi: 'Khi biết một sự thật, tôi:',
      id: 'Saat mengetahui suatu fakta, aku:',
    }),
    options: [
      opt(localeMap({
        ko: '그렇구나, 하고 받아들인다. 굳이 그 이면까지 알고 싶지 않은 경우가 많다',
        en: 'Accept it with "I see." I often do not want to know what lies beneath',
        ja: '「そうか」と受け止める。その裏まで知りたくないことが多い',
        'zh-CN': '「原来如此」就接受了，往往不想知道背后',
        'zh-TW': '「原來如此」就接受了，往往不想知道背後',
        vi: 'Nhận với "Ra vậy." Thường không muốn biết phía sau',
        id: 'Terima dengan "Oh begitu." Sering tidak ingin tahu di baliknya',
    }), 0),
      opt(localeMap({
        ko: '그게 왜 그런지, 어떤 원리인지 더 알고 싶어진다. 사실보다 원리가 더 궁금하다',
        en: 'Want to know why and what principle it follows. Principles interest me more than facts',
        ja: 'なぜそうなのか、どんな原理かもっと知りたくなる。事実より原理が気になる',
        'zh-CN': '想知道为什么、什么原理，对原理比对事实更感兴趣',
        'zh-TW': '想知道為什麼、什麼原理，對原理比對事實更感興趣',
        vi: 'Muốn biết vì sao và nguyên lý gì. Nguyên lý hấp dẫn hơn sự thật',
        id: 'Ingin tahu kenapa dan prinsip apa. Prinsip lebih menarik dari fakta',
    }), 1),
      opt(localeMap({
        ko: '그것이 다른 분야와 어떻게 연결되는지가 궁금해진다. 이 사실이 가진 더 큰 의미를 찾고 싶다',
        en: 'Wonder how it connects to other fields and look for its bigger meaning',
        ja: '他分野とどうつながるかが気になる。より大きな意味を探したい',
        'zh-CN': '好奇它如何与其他领域连接，想找更大的意义',
        'zh-TW': '好奇它如何與其他領域連結，想找更大的意義',
        vi: 'Tò mò nó liên kết lĩnh vực khác thế nào và tìm ý nghĩa lớn hơn',
        id: 'Penasaran bagaimana terhubung ke bidang lain dan mencari makna lebih besar',
    }), 2),
      opt(localeMap({
        ko: '이건 사실인가, 다른 관점은 없는가, 반례는 무엇인가 같은 질문이 연속으로 생긴다',
        en: 'Questions chain up: Is this true? Any other views? What are counterexamples?',
        ja: '「本当か」「別の視点は」「反例は何か」など質問が連鎖する',
        'zh-CN': '「这是真的吗」「有其他观点吗」「反例是什么」等问题接连出现',
        'zh-TW': '「這是真的嗎」「有其他觀點嗎」「反例是什麼」等問題接連出現',
        vi: 'Câu hỏi nối tiếp: Có đúng không? Góc nhìn khác? Phản ví dụ là gì?',
        id: 'Pertanyaan berantai: Benarkah? Ada sudut pandang lain? Apa contoh kontra?',
    }), 3),
    ],
  },
  {
    id: 6,
    question: localeMap({
      ko: '대화 중 모르는 개념이 나왔다. 나는?',
      en: 'An unknown concept comes up in conversation. I:',
      ja: '会話中に知らない概念が出た。私は？',
      'zh-CN': '对话中出现不懂的概念。我会？',
      'zh-TW': '對話中出現不懂的概念。我會？',
      vi: 'Trong hội thoại xuất hiện khái niệm không biết. Tôi:',
      id: 'Konsep yang tidak dikenal muncul dalam percakapan. Aku:',
    }),
    options: [
      opt(localeMap({
        ko: '대화 흐름상 필요하면 물어보고 아니면 그냥 넘어간다',
        en: 'Ask if needed for the flow; otherwise I let it pass',
        ja: '会話の流れ上必要なら聞き、そうでなければそのまま進む',
        'zh-CN': '对话需要就问，否则就略过',
        'zh-TW': '對話需要就問，否則就略過',
        vi: 'Hỏi nếu cần cho luồng hội thoại; không thì bỏ qua',
        id: 'Tanya jika perlu untuk alur; kalau tidak, biarkan lewat',
    }), 0),
      opt(localeMap({
        ko: '나중에 찾아보겠다고 메모한다. 제대로 알기 전까지 어정쩡하게 아는 게 싫다',
        en: 'Note to look it up later. I dislike half-knowing before I understand properly',
        ja: '後で調べようとメモする。きちんと知る前の曖昧な理解が嫌',
        'zh-CN': '记下以后查，没真正搞懂前不喜欢似懂非懂',
        'zh-TW': '記上以後查，沒真正搞懂前不喜歡似懂非懂',
        vi: 'Ghi chú để tra sau. Không thích biết nửa vời trước khi hiểu đúng',
        id: 'Catat untuk cari nanti. Tidak suka setengah paham sebelum benar-benar mengerti',
    }), 1),
      opt(localeMap({
        ko: '그 개념이 다른 것들과 어떻게 연결되는지가 궁금해서 대화 후 탐색을 시작한다',
        en: 'Wonder how the concept connects to other things and explore after the talk',
        ja: 'その概念が他とどうつながるか気になり、会話後に探索を始める',
        'zh-CN': '好奇概念如何与其他事物连接，对话后开始探索',
        'zh-TW': '好奇概念如何與其他事物連結，對話後開始探索',
        vi: 'Tò mò khái niệm liên kết thế nào và khám phá sau cuộc trò chuyện',
        id: 'Penasaran bagaimana konsep terhubung ke hal lain dan eksplorasi setelah obrolan',
    }), 2),
      opt(localeMap({
        ko: '그 자리에서 바로 물어보거나 검색한다. 모르는 채로 대화를 이어가기가 어렵다',
        en: 'Ask on the spot or search immediately. Hard to continue while not knowing',
        ja: 'その場で聞くかすぐ検索する。知らないまま続けるのが難しい',
        'zh-CN': '当场问或立刻搜索，不知道的情况下很难继续',
        'zh-TW': '當場問或立刻搜尋，不知道的情況下很難繼續',
        vi: 'Hỏi ngay hoặc tìm kiếm lập tức. Khó tiếp tục khi chưa biết',
        id: 'Tanya langsung atau cari segera. Sulit lanjut tanpa tahu',
    }), 3),
    ],
  },
  {
    id: 7,
    question: localeMap({
      ko: '무언가를 배울 때 가장 즐거운 순간은?',
      en: 'The most enjoyable moment when learning is:',
      ja: '何かを学ぶとき最も楽しい瞬間は？',
      'zh-CN': '学习时最享受的时刻是？',
      'zh-TW': '學習時最享受的時刻是？',
      vi: 'Khoảnh khắc thú vị nhất khi học là:',
      id: 'Momen paling menyenangkan saat belajar:',
    }),
    options: [
      opt(localeMap({
        ko: '배운 것을 실제로 써먹을 수 있다는 걸 확인할 때. 쓸 수 있어야 의미가 있다',
        en: 'When I confirm I can actually use what I learned. It must be usable to matter',
        ja: '学んだことを実際に使えると確認できたとき。使えることが意味がある',
        'zh-CN': '确认学到的东西能实际使用时，能用才有意义',
        'zh-TW': '確認學到的東西能實際使用時，能用才有意義',
        vi: 'Khi xác nhận có thể dùng được điều đã học. Phải dùng được mới có ý nghĩa',
        id: 'Saat memastikan bisa memakai apa yang dipelajari. Harus bisa dipakai baru berarti',
    }), 0),
      opt(localeMap({
        ko: '한 분야를 깊이 파다가 전에는 보이지 않던 것들이 보이기 시작할 때. 전문성이 쌓이는 느낌',
        en: 'When diving deep in one field and things I could not see before start appearing. The feeling of building expertise',
        ja: '一分野を深く掘り、以前見えなかったものが見え始めるとき。専門性が積み上がる感覚',
        'zh-CN': '深入一个领域，以前看不到的东西开始出现，专业感累积',
        'zh-TW': '深入一個領域，以前看不到的東西開始出現，專業感累積',
        vi: 'Khi đi sâu một lĩnh vực và thứ trước không thấy bắt đầu hiện ra. Cảm giác tích lũy chuyên môn',
        id: 'Saat mendalami satu bidang dan hal yang dulu tak terlihat mulai muncul. Rasa membangun keahlian',
    }), 1),
      opt(localeMap({
        ko: '전혀 다른 두 가지가 연결되는 순간. "이게 저것과 같은 원리였구나"를 발견할 때',
        en: 'When two completely different things connect. Discovering "this works on the same principle as that"',
        ja: '全く異なる二つがつながる瞬間。「これとあれが同じ原理だった」と発見するとき',
        'zh-CN': '完全不同的两样东西连接时，发现「这和那个是同一原理」',
        'zh-TW': '完全不同的兩樣東西連結時，發現「這和那個是同一原理」',
        vi: 'Khi hai thứ hoàn toàn khác nhau kết nối. Phát hiện "cái này cùng nguyên lý với cái kia"',
        id: 'Saat dua hal yang benar-benar berbeda terhubung. Menemukan "ini prinsipnya sama dengan itu"',
    }), 2),
      opt(localeMap({
        ko: '예상치 못한 것을 발견했을 때. 알면 알수록 모르는 게 더 많아진다는 걸 느낄 때',
        en: 'When I discover something unexpected. Feeling that the more I know, the more I do not know',
        ja: '予想外のものを発見したとき。知れば知るほど分からないことが増えると感じるとき',
        'zh-CN': '发现意料之外的东西，越知道越感到不懂很多',
        'zh-TW': '發現意料之外的東西，越知道越感到不懂很多',
        vi: 'Khi phát hiện điều bất ngờ. Cảm giác càng biết càng thấy còn nhiều điều chưa biết',
        id: 'Saat menemukan hal tak terduga. Merasa semakin tahu, semakin banyak yang belum tahu',
    }), 3),
    ],
  },
  {
    id: 8,
    question: localeMap({
      ko: '관심이 생긴 분야에 얼마나 오래 머무는가?',
      en: 'How long do I stay in a field of interest?',
      ja: '関心が生じた分野にどれだけ長く留まるか？',
      'zh-CN': '在感兴趣的领域会待多久？',
      'zh-TW': '在感興趣的領域會待多久？',
      vi: 'Tôi ở lại lĩnh vực quan tâm bao lâu?',
      id: 'Berapa lama aku tinggal di bidang yang menarik minat?',
    }),
    options: [
      opt(localeMap({
        ko: '필요한 것을 익히면 넘어간다. 한 곳에 오래 머물기보다 필요할 때 돌아오는 편이다',
        en: 'Move on once I learn what I need. I return when needed rather than staying long',
        ja: '必要なことを身につけたら次へ。長く留まるより必要なとき戻る方',
        'zh-CN': '掌握需要的就离开，需要时再回来，不太久留',
        'zh-TW': '掌握需要的就離開，需要時再回來，不太久留',
        vi: 'Chuyển đi khi học đủ phần cần. Quay lại khi cần hơn là ở lâu',
        id: 'Pindah setelah pelajari yang perlu. Kembali saat perlu daripada tinggal lama',
    }), 0),
      opt(localeMap({
        ko: '한번 빠지면 오래 머문다. 이 분야의 깊은 곳까지 가보고 싶다는 욕구가 생긴다',
        en: 'Once hooked, I stay long. I want to reach the deep end of the field',
        ja: '一度ハマると長く留まる。その分野の深いところまで行きたい',
        'zh-CN': '一旦入迷会待很久，想去该领域的深处',
        'zh-TW': '一旦入迷會待很久，想去該領域的深處',
        vi: 'Một khi mê thì ở lâu. Muốn đến tận chiều sâu của lĩnh vực',
        id: 'Sekali terpikat, tinggal lama. Ingin sampai ke ujung kedalaman bidang',
    }), 1),
      opt(localeMap({
        ko: '본래 관심사에서 파생된 것들로 이동하면서 계속 이어지는 편이다. 끝이 없다',
        en: 'I keep going through things derived from the original interest. It never really ends',
        ja: 'もとの関心から派生したものへ移りながら続く。終わりがない',
        'zh-CN': '从原本兴趣衍生到其他方向持续下去，没有尽头',
        'zh-TW': '從原本興趣衍生到其他方向持續下去，沒有盡頭',
        vi: 'Tiếp tục qua những thứ phát sinh từ quan tâm ban đầu. Không có hồi kết',
        id: 'Terus melalui hal turunan dari minat awal. Tidak pernah benar-benar berakhir',
    }), 2),
      opt(localeMap({
        ko: '새로운 것을 계속 발견하기 때문에 자연스럽게 오래 머물게 된다. 흥미가 식는 속도가 느리다',
        en: 'I naturally stay long because I keep finding new things. Interest fades slowly',
        ja: '新しい発見が続くので自然に長く留まる。興味が冷める速度が遅い',
        'zh-CN': '不断发现新东西所以自然待很久，兴趣消退慢',
        'zh-TW': '不斷發現新東西所以自然待很久，興趣消退慢',
        vi: 'Tự nhiên ở lâu vì liên tục phát hiện điều mới. Hứng thú giảm chậm',
        id: 'Secara alami tinggal lama karena terus menemukan hal baru. Minat reda lambat',
    }), 3),
    ],
  },
  {
    id: 9,
    question: localeMap({
      ko: '나의 호기심이 가장 강하게 발화하는 순간은?',
      en: 'When does my curiosity fire strongest?',
      ja: '私の好奇心が最も強く燃える瞬間は？',
      'zh-CN': '我的好奇心最强被点燃的时刻是？',
      'zh-TW': '我的好奇心最強被點燃的時刻是？',
      vi: 'Khi nào sự tò mò của tôi bùng mạnh nhất?',
      id: 'Kapan rasa penasaran-ku paling kuat menyala?',
    }),
    options: [
      opt(localeMap({
        ko: '당장 해결해야 할 문제가 생겼을 때. 필요가 호기심을 만든다',
        en: 'When a problem I must solve right now appears. Need creates curiosity',
        ja: '今すぐ解決すべき問題が生じたとき。必要が好奇心を生む',
        'zh-CN': '出现必须立刻解决的问题时，需要产生好奇心',
        'zh-TW': '出現必須立刻解決的問題時，需要產生好奇心',
        vi: 'Khi có vấn đề phải giải quyết ngay. Nhu cầu tạo ra tò mò',
        id: 'Saat masalah yang harus segera diselesaikan muncul. Kebutuhan menciptakan rasa penasaran',
    }), 0),
      opt(localeMap({
        ko: '내가 몰랐던 사실이나 개념을 발견했을 때. 지식의 빈칸이 채워지는 느낌',
        en: 'When I discover a fact or concept I did not know. The feeling of filling a knowledge gap',
        ja: '知らなかった事実や概念を発見したとき。知識の空白が埋まる感覚',
        'zh-CN': '发现不知道的事实或概念时，知识空白被填补的感觉',
        'zh-TW': '發現不知道的事實或概念時，知識空白被填補的感覺',
        vi: 'Khi phát hiện sự thật hoặc khái niệm chưa biết. Cảm giác lấp khoảng trống kiến thức',
        id: 'Saat menemukan fakta atau konsep yang belum tahu. Rasa mengisi celah pengetahuan',
    }), 1),
      opt(localeMap({
        ko: '서로 관계없어 보이는 두 가지 사이에서 공통점이 보일 때. 연결의 순간',
        en: 'When I see common ground between two things that seemed unrelated. The moment of connection',
        ja: '無関係に見える二つの間に共通点が見えるとき。つながりの瞬間',
        'zh-CN': '看似无关的两件事出现共同点时，连接的瞬间',
        'zh-TW': '看似無關的兩件事出現共同點時，連結的瞬間',
        vi: 'Khi thấy điểm chung giữa hai thứ tưởng không liên quan. Khoảnh khắc kết nối',
        id: 'Saat melihat titik temu antara dua hal yang tampak tidak terkait. Momen koneksi',
    }), 2),
      opt(localeMap({
        ko: '당연하다고 생각했던 것이 사실이 아닐 수 있다는 걸 알게 됐을 때. 세상이 다시 보이는 느낌',
        en: 'When I learn something I took for granted might not be true. The world looks different again',
        ja: '当たり前だと思っていたことが違うかもしれないと分かったとき。世界が再び見える感覚',
        'zh-CN': '发现以为理所当然的事可能不对时，世界重新被看见',
        'zh-TW': '發現以為理所當然的事可能不對時，世界重新被看見',
        vi: 'Khi biết điều tưởng hiển nhiên có thể không đúng. Thế giới lại được nhìn khác đi',
        id: 'Saat tahu hal yang dianggap wajar mungkin tidak benar. Dunia terlihat berbeda lagi',
    }), 3),
    ],
  },
  {
    id: 10,
    question: localeMap({
      ko: '다큐멘터리나 강연, 책을 볼 때 나는?',
      en: 'When watching documentaries, talks, or reading books, I:',
      ja: 'ドキュメンタリー・講演・本を見るとき、私は？',
      'zh-CN': '看纪录片、演讲、读书时，我会？',
      'zh-TW': '看紀錄片、演講、讀書時，我會？',
      vi: 'Khi xem phim tài liệu, bài nói chuyện hoặc đọc sách, tôi:',
      id: 'Saat menonton dokumenter, ceramah, atau membaca buku, aku:',
    }),
    options: [
      opt(localeMap({
        ko: '내 삶이나 일에 직접 적용할 수 있는 내용 위주로 본다. 실용적 정보가 핵심이다',
        en: 'Focus on content I can apply directly to my life or work. Practical information is key',
        ja: '生活や仕事に直接応用できる内容中心。実用的情報が核心',
        'zh-CN': '主要看能直接用于生活或工作的内容，实用信息是核心',
        'zh-TW': '主要看能直接用於生活或工作的內容，實用資訊是核心',
        vi: 'Tập trung nội dung áp dụng trực tiếp vào đời sống hoặc công việc. Thông tin thực tế là cốt lõi',
        id: 'Fokus pada konten yang bisa langsung diterapkan ke hidup atau pekerjaan. Info praktis adalah kunci',
    }), 0),
      opt(localeMap({
        ko: '한 주제를 깊이 다루는 콘텐츠를 선호한다. 얕은 것보다 깊은 것이 좋다',
        en: 'Prefer content that goes deep on one topic. Depth over shallow coverage',
        ja: '一テーマを深く扱うコンテンツを好む。浅いより深い方が良い',
        'zh-CN': '偏好深入一个主题的内容，深度胜过浅尝',
        'zh-TW': '偏好深入一個主題的內容，深度勝過淺嚐',
        vi: 'Thích nội dung đi sâu một chủ đề. Chiều sâu hơn nội dung nông',
        id: 'Lebih suka konten yang mendalami satu topik. Kedalaman lebih dari yang dangkal',
    }), 1),
      opt(localeMap({
        ko: '여러 분야를 넘나들며 연결하는 콘텐츠가 가장 재밌다. 분야를 초월한 통찰이 좋다',
        en: 'Most enjoy content connecting multiple fields. Cross-domain insight is best',
        ja: '複数分野をまたぐつながりコンテンツが最も面白い。分野を超えた洞察が好き',
        'zh-CN': '最喜欢跨领域连接的内容，超越领域的洞察最好',
        'zh-TW': '最喜歡跨領域連結的內容，超越領域的洞察最好',
        vi: 'Thích nhất nội dung kết nối nhiều lĩnh vực. Thấu hiểu vượt lĩnh vực là hay nhất',
        id: 'Paling suka konten yang menghubungkan banyak bidang. Wawasan lintas bidang paling menarik',
    }), 2),
      opt(localeMap({
        ko: '장르를 가리지 않는다. 무엇이든 흥미로운 것이 나타나면 시작된다. 추천 알고리즘이 무섭다',
        en: 'No genre limits. I start whatever looks interesting. Recommendation algorithms scare me',
        ja: 'ジャンル不問。面白そうなら何でも始まる。おすすめアルゴリズムが怖い',
        'zh-CN': '不限类型，有趣就开始，推荐算法很可怕',
        'zh-TW': '不限類型，有趣就開始，推薦演算法很可怕',
        vi: 'Không giới hạn thể loại. Cái gì thú vị là bắt đầu. Thuật toán gợi ý đáng sợ',
        id: 'Tidak peduli genre. Apa pun yang menarik langsung mulai. Algoritme rekomendasi menakutkan',
    }), 3),
    ],
  },
  {
    id: 11,
    question: localeMap({
      ko: '한 번 발동한 호기심이 얼마나 지속되는가?',
      en: 'Once curiosity is triggered, how long does it last?',
      ja: '一度発動した好奇心はどれくらい続くか？',
      'zh-CN': '好奇心一旦被点燃，能持续多久？',
      'zh-TW': '好奇心一旦被點燃，能持續多久？',
      vi: 'Một khi tò mò được kích hoạt, nó kéo dài bao lâu?',
      id: 'Setelah rasa penasaran menyala, berapa lama bertahan?',
    }),
    options: [
      opt(localeMap({
        ko: '필요한 것을 해결하면 금방 식는다. 호기심이 오래 지속되지 않는 편이다',
        en: 'It fades quickly once I solve what I needed. Curiosity does not last long for me',
        ja: '必要なことを解決するとすぐ冷める。好奇心は長く続かない方',
        'zh-CN': '解决需要的就很快消退，好奇心不太持久',
        'zh-TW': '解決需要的就很快消退，好奇心不太持久',
        vi: 'Nguội nhanh khi giải quyết xong phần cần. Tò mò không kéo dài lâu',
        id: 'Reda cepat setelah kebutuhan terpenuhi. Rasa penasaran tidak bertahan lama',
    }), 0),
      opt(localeMap({
        ko: '한 분야에 한번 꽂히면 매우 오래 간다. 수년 이상 같은 분야를 탐구하는 경우도 있다',
        en: 'Once hooked on a field, it lasts very long. I may explore the same field for years',
        ja: '一分野にハマると非常に長い。数年同じ分野を探索することもある',
        'zh-CN': '迷上一个领域会非常久，可能多年探索同一领域',
        'zh-TW': '迷上一個領域會非常久，可能多年探索同一領域',
        vi: 'Một khi mê một lĩnh vực thì rất lâu. Có thể khám phá cùng lĩnh vực nhiều năm',
        id: 'Sekali terpikat bidang, sangat lama. Bisa mengeksplorasi bidang sama selama bertahun-tahun',
    }), 1),
      opt(localeMap({
        ko: '하나에서 다른 하나로 이어지면서 계속 이어진다. 형태는 바뀌지만 탐구 자체는 멈추지 않는다',
        en: 'It continues from one thing to another. Form changes but exploration never stops',
        ja: '一つから別の一つへつながり続く。形は変わるが探索自体は止まらない',
        'zh-CN': '从一个连到另一个持续下去，形式变但探索不停',
        'zh-TW': '從一個連到另一個持續下去，形式變但探索不停',
        vi: 'Tiếp tục từ cái này sang cái khác. Hình thức đổi nhưng khám phá không dừng',
        id: 'Terus dari satu ke yang lain. Bentuk berubah tapi eksplorasi tidak berhenti',
    }), 2),
      opt(localeMap({
        ko: '알면 알수록 더 모르는 게 많아진다는 걸 느껴서 호기심이 줄어들지 않는다',
        en: 'It never fades because the more I know, the more I feel I do not know',
        ja: '知れば知るほど分からないことが多いと感じるので好奇心が減らない',
        'zh-CN': '越知道越觉得不懂很多，好奇心不会减少',
        'zh-TW': '越知道越覺得不懂很多，好奇心不會減少',
        vi: 'Càng biết càng thấy còn nhiều điều chưa biết nên tò mò không giảm',
        id: 'Tidak pernah reda karena semakin tahu, semakin merasa belum tahu banyak',
    }), 3),
    ],
  },
  {
    id: 12,
    question: localeMap({
      ko: '호기심이 내 삶에서 어떤 역할을 하는가?',
      en: 'What role does curiosity play in my life?',
      ja: '好奇心は私の人生でどんな役割をするか？',
      'zh-CN': '好奇心在我的生活中扮演什么角色？',
      'zh-TW': '好奇心在我的生活中扮演什麼角色？',
      vi: 'Sự tò mò đóng vai trò gì trong cuộc sống của tôi?',
      id: 'Peran apa rasa penasaran dalam hidupku?',
    }),
    options: [
      opt(localeMap({
        ko: '필요한 것을 배우고 문제를 해결하는 도구다. 실용적인 역할이 크다',
        en: 'A tool to learn what I need and solve problems. Mostly a practical role',
        ja: '必要なことを学び問題を解く道具。実用的な役割が大きい',
        'zh-CN': '学习所需、解决问题的工具，实用角色很大',
        'zh-TW': '學習所需、解決問題的工具，實用角色很大',
        vi: 'Công cụ học điều cần và giải quyết vấn đề. Vai trò thực tế lớn',
        id: 'Alat belajar yang dibutuhkan dan menyelesaikan masalah. Peran praktis besar',
    }), 0),
      opt(localeMap({
        ko: '내가 선택한 분야를 깊이 알아가는 것이 삶의 큰 기쁨이다. 전문성이 정체성과 연결된다',
        en: 'Deeply knowing my chosen field is a major joy in life. Expertise connects to identity',
        ja: '選んだ分野を深く知ることが人生の大きな喜び。専門性がアイデンティティとつながる',
        'zh-CN': '深入了解所选领域是生活的大乐趣，专业性与身份相连',
        'zh-TW': '深入了解所選領域是生活的大樂趣，專業性與身份相連',
        vi: 'Hiểu sâu lĩnh vực mình chọn là niềm vui lớn. Chuyên môn gắn với bản sắc',
        id: 'Mengenal bidang pilihan secara mendalam adalah kegembiraan besar. Keahlian terhubung identitas',
    }), 1),
      opt(localeMap({
        ko: '전혀 다른 세계들이 사실 하나로 연결되어 있다는 걸 발견하는 과정 자체가 즐겁다',
        en: 'The joy of discovering that entirely different worlds are actually one connected whole',
        ja: 'まったく異なる世界が実は一つにつながっていると発見する過程自体が楽しい',
        'zh-CN': '发现完全不同的世界其实连成一体的过程本身就很快乐',
        'zh-TW': '發現完全不同的世界其實連成一體的過程本身就很快樂',
        vi: 'Niềm vui khi phát hiện các thế giới khác nhau thực ra là một thể liên kết',
        id: 'Kegembiraan menemukan dunia yang berbeda sebenarnya satu kesatuan terhubung',
    }), 2),
      opt(localeMap({
        ko: '세상이 얼마나 넓고 신기한지를 계속 발견하게 해주는 것이다. 살아있다는 느낌을 준다',
        en: 'It keeps showing me how wide and wondrous the world is. It makes me feel alive',
        ja: '世界がいかに広く不思議かを見せ続ける。生きている感覚を与える',
        'zh-CN': '不断让我发现世界有多广阔神奇，带来活着的感觉',
        'zh-TW': '不斷讓我發現世界有多廣闊神奇，帶來活著的感覺',
        vi: 'Liên tục cho thấy thế giới rộng và kỳ diệu thế nào. Mang cảm giác đang sống',
        id: 'Terus menunjukkan betapa luas dan menakjubkannya dunia. Memberi rasa hidup',
    }), 3),
    ],
  },
];

export const phase3CuriosityTypeResults: Phase3CuriosityTypeResult[] = [
  {
    type: "Type1",
    emoji: "🔧",
    title: localeMap({
      ko: '필요한 것만 정확하게 아는 사람, 실용 탐구형',
      en: 'Someone Who Knows Only What\'s Needed, Practical Explorer Type',
      ja: '必要なものだけ正確に知る人、実用探究型',
      'zh-CN': '只精确了解所需之人，实用探究型',
      'zh-TW': '只精確了解所需之人，實用探究型',
      vi: 'Người chỉ biết chính xác điều cần thiết, Loại khám phá thực dụng',
      id: 'Orang yang Hanya Tahu yang Diperlukan, Tipe Eksplorasi Praktis',
    }),
    curiositySummary: localeMap({
      ko: '목적과 필요에 따라 탐구를 시작하고 충족되면 멈추는 타입',
      en: 'Starts exploring based on purpose and need, and stops once satisfied',
      ja: '目的と必要に応じて探究を始め、満たされれば止まるタイプ',
      'zh-CN': '依目的与需要开始探索，满足后便停止的类型',
      'zh-TW': '依目的與需要開始探索，滿足後便停止的類型',
      vi: 'Bắt đầu khám phá theo mục đích và nhu cầu, dừng lại khi đã đủ',
      id: 'Memulai eksplorasi sesuai tujuan dan kebutuhan, berhenti setelah terpenuhi',
    }),
    quote: localeMap({
      ko: '당신의 호기심은 효율적입니다. 필요한 것을 빠르게 찾아내고 쓸 수 있게 만드는 데 탁월합니다.',
      en: 'Your curiosity is efficient. You excel at quickly finding what you need and making it usable.',
      ja: 'あなたの好奇心は効率的です。必要なものを素早く見つけ、使える形にするのが得意です。',
      'zh-CN': '你的好奇心很高效，擅长快速找到所需并让它可用。',
      'zh-TW': '你的好奇心很高效，擅長快速找到所需並讓它可用。',
      vi: 'Sự tò mò của bạn hiệu quả. Bạn giỏi nhanh chóng tìm ra điều cần và biến nó thành hữu dụng.',
      id: 'Rasa ingin tahumu efisien. Kamu unggul menemukan cepat yang dibutuhkan dan membuatnya bisa dipakai.',
    }),
    description: localeMap({
      ko: '모르는 것이 생겼을 때 그것이 지금 필요한 것인지를 먼저 판단하고 필요하다면 핵심을 빠르게 파악하는 타입입니다. 지식을 수집하는 것보다 활용하는 것에 더 큰 가치를 둡니다. 이것은 호기심이 부족한 게 아닙니다. 방향이 실용에 맞춰진 것입니다.',
      en: 'When something unknown appears, you first judge whether you need it now; if yes, you quickly grasp the core. You value applying knowledge more than collecting it. This is not a lack of curiosity — your direction is tuned to practicality.',
      ja: '知らないことが生じたとき、今必要かどうかをまず判断し、必要なら核心を素早く把握するタイプです。知識を集めるより活用することに大きな価値を置きます。好奇心が足りないのではなく、方向が実用に合わせられているのです。',
      'zh-CN': '遇到未知时，你先判断现在是否需要；需要的话便快速掌握核心。你更看重运用知识而非收集知识。这不是缺乏好奇心，而是方向对准了实用。',
      'zh-TW': '遇到未知時，你先判斷現在是否需要；需要的話便快速掌握核心。你更看重運用知識而非收集知識。這不是缺乏好奇心，而是方向對準了實用。',
      vi: 'Khi gặp điều chưa biết, bạn trước hết đánh giá có cần ngay không; nếu cần thì nắm nhanh phần cốt lõi. Bạn coi trọng ứng dụng hơn tích lũy kiến thức. Đây không phải thiếu tò mò — hướng đi của bạn hướng về thực dụng.',
      id: 'Saat ada hal yang belum diketahui, kamu dulu menilai apakah dibutuhkan sekarang; jika ya, cepat pahami intinya. Kamu lebih menghargai penerapan daripada mengumpulkan pengetahuan. Ini bukan kurang rasa ingin tahu — arahmu disetel ke praktis.',
    }),
    curiosityType: localeMap({
      ko: '실용 탐구형 🔧',
      en: 'Practical Explorer Type 🔧',
      ja: '実用探究型 🔧',
      'zh-CN': '实用探究型 🔧',
      'zh-TW': '實用探究型 🔧',
      vi: 'Loại khám phá thực dụng 🔧',
      id: 'Tipe Eksplorasi Praktis 🔧',
    }),
    exploreKeywords: localeMap({
      ko: '목적·효율·실용·활용·빠른 습득',
      en: 'Purpose · Efficiency · Practicality · Application · Quick learning',
      ja: '目的・効率・実用・活用・素早い習得',
      'zh-CN': '目的·效率·实用·运用·快速习得',
      'zh-TW': '目的·效率·實用·運用·快速習得',
      vi: 'Mục đích · Hiệu quả · Thực dụng · Ứng dụng · Học nhanh',
      id: 'Tujuan · Efisiensi · Praktis · Penerapan · Belajar cepat',
    }),
    strengths: localeMap({
      ko: '불필요한 탐색 없이 핵심을 빠르게 파악함. 정보 처리 효율이 높음\n배운 것을 실제로 써먹는 능력이 뛰어남. 앎과 행동의 간격이 짧음\n깊이 있는 전문성을 한 분야에 집중해서 쌓는 데 강함',
      en: 'Grasps essentials quickly without unnecessary exploration. High information-processing efficiency\nExcellent at putting what you learn into action. Short gap between knowing and doing\nStrong at building deep expertise by focusing on one field',
      ja: '不要な探索なしで核心を素早く把握。情報処理効率が高い\n学んだことを実際に使う能力に優れる。知識と行動の間隔が短い\n一つの分野に集中して深い専門性を積み上げるのが得意',
      'zh-CN': '不做多余探索，快速掌握核心，信息处理效率高\n擅长把所学付诸行动，知与行的间隔很短\n专注一个领域，善于积累深度专业',
      'zh-TW': '不做多餘探索，快速掌握核心，資訊處理效率高\n擅長把所學付諸行動，知與行的間隔很短\n專注一個領域，善於累積深度專業',
      vi: 'Nắm cốt lõi nhanh không cần khám phá thừa. Xử lý thông tin hiệu quả\nGiỏi đưa kiến thức vào hành động. Khoảng cách giữa biết và làm ngắn\nMạnh khi tập trung một lĩnh vực để xây chuyên môn sâu',
      id: 'Memahami inti cepat tanpa eksplorasi berlebihan. Efisiensi pemrosesan informasi tinggi\nUnggul menerapkan apa yang dipelajari. Jarak antara tahu dan bertindak pendek\nKuat membangun keahlian mendalam dengan fokus pada satu bidang',
    }),
    cautions: localeMap({
      ko: '직접적 필요가 없는 탐구를 건너뛰다 보면 예상치 못한 연결이나 창의적 인사이트를 놓칠 수 있음\n가끔은 쓸모없어 보이는 것을 탐구하는 것이 장기적으로 가장 큰 가치를 만들기도 함',
      en: 'Skipping exploration without direct need can mean missing unexpected connections or creative insights\nSometimes exploring what seems useless creates the greatest long-term value',
      ja: '直接的な必要がない探究を飛ばすと、予想外のつながりや創造的インサイトを逃すことがある\n時には役に立たなそうなものを探究することが、長期的に最大の価値を生む',
      'zh-CN': '跳过没有直接需要的探索，可能错过意外连接或创意洞见\n有时探索看似无用的东西，反而创造最大的长期价值',
      'zh-TW': '跳過沒有直接需要的探索，可能錯過意外連結或創意洞見\n有時探索看似無用的東西，反而創造最大的長期價值',
      vi: 'Bỏ qua khám phá không cần trực tiếp có thể lỡ kết nối bất ngờ hoặc góc nhìn sáng tạo\nĐôi khi khám phá thứ có vẻ vô dụng lại tạo giá trị dài hạn lớn nhất',
      id: 'Melewati eksplorasi tanpa kebutuhan langsung bisa kehilangan koneksi tak terduga atau wawasan kreatif\nTerkadang mengeksplorasi hal yang tampak tidak berguna justru menciptakan nilai jangka panjang terbesar',
    }),
    contentRecommend: localeMap({
      ko: '실용 노하우 중심 강의·직무 관련 자격증·문제 해결 중심 튜토리얼',
      en: 'Practical how-to courses · Job-related certifications · Problem-solving tutorials',
      ja: '実用ノウハウ中心の講座・職務関連資格・問題解決型チュートリアル',
      'zh-CN': '实用技巧课程·职涯相关证照·以解决问题为主的教程',
      'zh-TW': '實用技巧課程·職涯相關證照·以解決問題為主的教程',
      vi: 'Khóa học kỹ năng thực tế · Chứng chỉ liên quan công việc · Hướng dẫn giải quyết vấn đề',
      id: 'Kursus tips praktis · Sertifikasi terkait pekerjaan · Tutorial berbasis pemecahan masalah',
    }),
    growCuriosity: localeMap({
      ko: '한 달에 하나씩 "지금 당장 쓸모없지만 재미있어 보이는 것"을 탐구해보기. 쓸모없어 보이는 호기심이 가장 창의적인 연결을 만들어냄',
      en: 'Once a month, explore something "useless right now but looks fun." Curiosity that seems pointless often creates the most creative connections',
      ja: '月に一つ、「今すぐ役に立たなそうだが面白そうなもの」を探究してみる。役に立たなそうな好奇心が最も創造的なつながりを生む',
      'zh-CN': '每月探索一项「现在没用但看起来有趣的东西」。看似无用的好奇心往往创造最有创意的连接',
      'zh-TW': '每月探索一項「現在沒用但看起來有趣的東西」。看似無用的好奇心往往創造最有創意的連結',
      vi: 'Mỗi tháng khám phá một thứ "vô dụng ngay bây giờ nhưng trông thú vị." Tò mò có vẻ vô ích thường tạo kết nối sáng tạo nhất',
      id: 'Sekali sebulan, eksplorasi sesuatu "tidak berguna sekarang tapi terlihat menarik." Rasa ingin tahu yang tampak sia-sia sering menciptakan koneksi paling kreatif',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '필요한 것을 빠르게 아는 능력은 강점입니다. 가끔 필요 없는 것을 탐구하는 여유도 그 강점을 더 풍부하게 만들어줍니다',
      en: 'Knowing quickly what you need is a strength. Occasionally exploring what you do not need makes that strength even richer',
      ja: '必要なものを素早く知る能力は強みです。時には不要なものを探究する余裕も、その強みをより豊かにします',
      'zh-CN': '快速知道所需是优势。偶尔探索不需要的东西，会让这份优势更丰富',
      'zh-TW': '快速知道所需是優勢。偶爾探索不需要的東西，會讓這份優勢更豐富',
      vi: 'Biết nhanh điều cần thiết là thế mạnh. Thỉnh thoảng khám phá điều không cần cũng làm thế mạnh ấy phong phú hơn',
      id: 'Tahu cepat yang dibutuhkan adalah kekuatan. Sesekali mengeksplorasi yang tidak perlu membuat kekuatan itu lebih kaya',
    }),
    shareLine: localeMap({
      ko: '내 호기심 유형: 실용 탐구형 🔧 필요한 것만 정확하게 아는 유형이래... 쓸 수 있어야 의미 있다는 거 맞음 ㅋㅋ → 호기심 결과 너는 어떤 유형이야? 학습 취미 추천도 나옴',
      en: 'My curiosity type: Practical Explorer 🔧 They say I only know exactly what I need... "It has to be usable to matter" — so true lol → What\'s your curiosity type? You get learning hobby picks too',
      ja: '私の好奇心タイプ: 実用探究型 🔧 必要なものだけ正確に知るタイプ…使えることが意味だって当たり ㅋㅋ → 好奇心結果 あなたはどのタイプ？学習・趣味のおすすめも出る',
      'zh-CN': '我的好奇心类型：实用探究型 🔧 说我只精确了解所需…「能用才有意义」太准哈哈 → 你的好奇心类型是？还有学习爱好推荐',
      'zh-TW': '我的好奇心類型：實用探究型 🔧 說我只精確了解所需…「能用才有意義」太準哈哈 → 你的好奇心類型是？還有學習愛好推薦',
      vi: 'Loại tò mò của tôi: Khám phá thực dụng 🔧 Bảo tôi chỉ biết chính xác điều cần... "Dùng được mới có nghĩa" — đúng quá haha → Bạn loại tò mò nào? Có cả gợi ý học tập và sở thích',
      id: 'Tipe rasa ingin tahu-ku: Eksplorasi Praktis 🔧 Katanya aku cuma tahu persis yang dibutuhkan... "Harus bisa dipakai baru berarti" — bener banget wkwk → Kamu tipe apa? Rekomendasi belajar dan hobi juga keluar',
    }),
  },
  {
    type: "Type2",
    emoji: "📚",
    title: localeMap({
      ko: '하나를 끝까지 파는 사람, 전문 심화형',
      en: 'Someone Who Digs to the End, Deep Specialist Type',
      ja: '一つを最後まで掘り下げる人、専門深化型',
      'zh-CN': '把一个领域挖到底的人，专业深化型',
      'zh-TW': '把一個領域挖到底的人，專業深化型',
      vi: 'Người đào sâu đến tận cùng, Loại chuyên sâu',
      id: 'Orang yang Menggali Sampai Tuntas, Tipe Spesialis Mendalam',
    }),
    curiositySummary: localeMap({
      ko: '관심 분야가 정해지면 그 끝까지 깊이 파고드는 타입',
      en: 'Once an interest area is set, digs deep all the way to the bottom',
      ja: '関心分野が決まると、その底まで深く掘り下げるタイプ',
      'zh-CN': '兴趣领域一旦确定，就会一路深挖到底的类型',
      'zh-TW': '興趣領域一旦確定，就會一路深挖到底的類型',
      vi: 'Khi đã chọn lĩnh vực quan tâm, đào sâu đến tận cùng',
      id: 'Setelah bidang minat ditetapkan, menggali dalam sampai ke dasar',
    }),
    quote: localeMap({
      ko: '당신의 호기심은 수직으로 내려갑니다. 한번 꽂히면 그 분야의 깊은 곳까지 닿으려 합니다.',
      en: 'Your curiosity goes vertical. Once hooked, you reach for the deepest parts of a field.',
      ja: 'あなたの好奇心は垂直に下へ向かいます。一度はまると、その分野の深いところまで届こうとします。',
      'zh-CN': '你的好奇心是垂直向下的。一旦入迷，就会触达该领域最深的地方。',
      'zh-TW': '你的好奇心是垂直向下的。一旦入迷，就會觸及該領域最深的地方。',
      vi: 'Sự tò mò của bạn đi theo chiều sâu. Một khi cuốn vào, bạn chạm tới tận cùng lĩnh vực đó.',
      id: 'Rasa ingin tahumu vertikal. Sekali terpikat, kamu meraih bagian paling dalam suatu bidang.',
    }),
    description: localeMap({
      ko: '특정 분야에 관심이 생기면 그 분야의 원리·역사·세부 논쟁까지 알고 싶어하고 얕은 지식보다 깊은 이해를 선호하며 수년 이상 같은 분야를 탐구하는 것이 자연스러운 타입입니다. 이 탐구 방식이 전문성의 가장 빠른 경로입니다.',
      en: 'When a field catches your interest, you want to know its principles, history, and fine debates; you prefer deep understanding over shallow knowledge, and exploring the same field for years feels natural. This path is the fastest route to expertise.',
      ja: '特定の分野に関心が生じると、その原理・歴史・細かな論争まで知りたくなり、浅い知識より深い理解を好み、数年同じ分野を探究するのが自然なタイプです。この探究の仕方が専門性への最も速い道です。',
      'zh-CN': '对某领域产生兴趣后，你想了解其原理、历史与细节争论；比起浅层知识，你更偏好深度理解，长年探究同一领域很自然。这是通往专业最快的路径。',
      'zh-TW': '對某領域產生興趣後，你想了解其原理、歷史與細節爭論；比起淺層知識，你更偏好深度理解，長年探究同一領域很自然。這是通往專業最快的路徑。',
      vi: 'Khi một lĩnh vực thu hút, bạn muốn biết nguyên lý, lịch sử và các tranh luận chi tiết; thích hiểu sâu hơn biết nông, và nghiên cứu cùng một lĩnh vực nhiều năm là điều tự nhiên. Đây là con đường nhanh nhất tới chuyên môn.',
      id: 'Saat suatu bidang menarik minat, kamu ingin tahu prinsip, sejarah, dan perdebatan detailnya; lebih suka pemahaman mendalam daripada pengetahuan dangkal, dan mengeksplorasi bidang yang sama selama bertahun-tahun terasa alami. Ini jalur tercepat menuju keahlian.',
    }),
    curiosityType: localeMap({
      ko: '전문 심화형 📚',
      en: 'Deep Specialist Type 📚',
      ja: '専門深化型 📚',
      'zh-CN': '专业深化型 📚',
      'zh-TW': '專業深化型 📚',
      vi: 'Loại chuyên sâu 📚',
      id: 'Tipe Spesialis Mendalam 📚',
    }),
    exploreKeywords: localeMap({
      ko: '깊이·전문성·원리·체계·완전한 이해',
      en: 'Depth · Expertise · Principles · System · Complete understanding',
      ja: '深さ・専門性・原理・体系・完全な理解',
      'zh-CN': '深度·专业·原理·体系·完全理解',
      'zh-TW': '深度·專業·原理·體系·完全理解',
      vi: 'Chiều sâu · Chuyên môn · Nguyên lý · Hệ thống · Hiểu trọn vẹn',
      id: 'Kedalaman · Keahlian · Prinsip · Sistem · Pemahaman utuh',
    }),
    strengths: localeMap({
      ko: '한 분야의 깊은 전문성을 쌓는 속도가 빠름\n표면 아래를 보는 능력. 같은 정보를 봐도 더 많은 것을 읽어냄\n지식이 쌓일수록 새로운 것을 빠르게 흡수하는 능력(망각 방지 효과)',
      en: 'Builds deep expertise in one field quickly\nSees beneath the surface — reads more from the same information\nAbsorbs new knowledge faster as knowledge accumulates (anti-forgetting effect)',
      ja: '一つの分野の深い専門性を素早く積み上げる\n表面の下を見る能力。同じ情報からより多くを読み取る\n知識が増えるほど新しいものを素早く吸収する能力（忘却防止効果）',
      'zh-CN': '快速在一个领域积累深度专业\n能看见表面之下——从同样信息中读出更多\n知识越多，吸收新知越快（防遗忘效应）',
      'zh-TW': '快速在一個領域累積深度專業\n能看見表面之下——從同樣資訊中讀出更多\n知識越多，吸收新知越快（防遺忘效應）',
      vi: 'Xây chuyên môn sâu trong một lĩnh vực nhanh\nNhìn xuống dưới bề mặt — đọc được nhiều hơn từ cùng thông tin\nHấp thụ kiến thức mới nhanh hơn khi kiến thức tích lũy (hiệu ứng chống quên)',
      id: 'Membangun keahlian mendalam di satu bidang dengan cepat\nMelihat di bawah permukaan — membaca lebih banyak dari informasi yang sama\nMenyerap pengetahuan baru lebih cepat seiring pengetahuan terkumpul (efek anti-lupa)',
    }),
    cautions: localeMap({
      ko: '하나에 너무 깊이 파다 보면 분야 밖의 새로운 자극에 상대적으로 덜 노출됨\n깊은 지식을 가지고 있지만 다른 분야와 연결하는 것이 어색할 수 있음',
      en: 'Digging too deep in one area can mean less exposure to fresh stimuli outside the field\nDeep knowledge may make connecting to other fields feel awkward',
      ja: '一つに深く入りすぎると、分野外の新しい刺激に相対的に触れにくくなる\n深い知識を持っていても、他分野とのつながりがぎこちなく感じることがある',
      'zh-CN': '在一个领域挖太深，可能较少接触领域外的新刺激\n拥有深厚知识，却可能不太擅长与其他领域连接',
      'zh-TW': '在一個領域挖太深，可能較少接觸領域外的新刺激\n擁有深厚知識，卻可能不太擅長與其他領域連接',
      vi: 'Đào quá sâu một lĩnh vực có thể ít tiếp xúc kích thích mới bên ngoài\nCó kiến thức sâu nhưng kết nối với lĩnh vực khác đôi khi vụng về',
      id: 'Menggali terlalu dalam di satu bidang bisa kurang terpapar rangsangan baru di luar bidang\nPunya pengetahuan mendalam tapi menghubungkan ke bidang lain bisa terasa canggung',
    }),
    contentRecommend: localeMap({
      ko: '전문 서적·심화 강의·논문·해당 분야 커뮤니티·마스터클래스',
      en: 'Specialist books · Advanced courses · Papers · Field communities · Masterclasses',
      ja: '専門書・深化講座・論文・該当分野コミュニティ・マスタークラス',
      'zh-CN': '专业书籍·进阶课程·论文·该领域社群·大师班',
      'zh-TW': '專業書籍·進階課程·論文·該領域社群·大師班',
      vi: 'Sách chuyên môn · Khóa học nâng cao · Bài báo khoa học · Cộng đồng lĩnh vực · Lớp học chuyên sâu',
      id: 'Buku spesialis · Kursus lanjutan · Makalah · Komunitas bidang · Kelas master',
    }),
    growCuriosity: localeMap({
      ko: '자신의 전문 분야와 전혀 다른 분야를 하나씩 탐색하기. 깊은 전문성과 다양한 분야 지식이 결합될 때 독보적인 통찰이 나옴',
      en: 'Explore one field completely different from your specialty. When deep expertise meets diverse knowledge, unique insight emerges',
      ja: '自分の専門分野とまったく異なる分野を一つずつ探究する。深い専門性と多様な分野の知識が結合すると、独自の洞察が生まれる',
      'zh-CN': '逐一探索与专业完全不同的领域。深度专业与多元知识结合时，会产生独到洞见',
      'zh-TW': '逐一探索與專業完全不同的領域。深度專業與多元知識結合時，會產生獨到洞見',
      vi: 'Khám phá từng lĩnh vực hoàn toàn khác chuyên môn của bạn. Khi chuyên sâu gặp kiến thức đa dạng, góc nhìn độc đáo xuất hiện',
      id: 'Eksplorasi satu bidang yang sama sekali berbeda dari spesialisasimu. Saat keahlian mendalam bertemu pengetahuan beragam, wawasan unik muncul',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '깊이 아는 것은 희귀한 능력입니다. 그 깊이가 다른 세계와 만날 때 아무도 흉내 낼 수 없는 관점이 생깁니다',
      en: 'Knowing deeply is a rare ability. When that depth meets other worlds, a perspective no one can copy appears',
      ja: '深く知ることは希少な能力です。その深さが他の世界と出会うとき、誰も真似できない視点が生まれます',
      'zh-CN': '深度了解是罕见能力。当这份深度遇见其他世界，会产生无人能复制的视角',
      'zh-TW': '深度了解是罕見能力。當這份深度遇見其他世界，會產生無人能複製的視角',
      vi: 'Biết sâu là năng lực hiếm. Khi chiều sâu ấy gặp thế giới khác, góc nhìn không ai sao chép được xuất hiện',
      id: 'Tahu secara mendalam adalah kemampuan langka. Saat kedalaman itu bertemu dunia lain, perspektif yang tak bisa ditiru muncul',
    }),
    shareLine: localeMap({
      ko: '내 호기심 유형: 전문 심화형 📚 하나를 끝까지 파는 유형이래... 한번 꽂히면 그 분야 다 알아야 직성 풀리는 거 맞음 → 호기심 결과 너는 어떤 유형이야?',
      en: 'My curiosity type: Deep Specialist 📚 They say I dig one thing to the end... once hooked I have to know it all — so true → What\'s your curiosity type?',
      ja: '私の好奇心タイプ: 専門深化型 📚 一つを最後まで掘るタイプ…一度はまると分野全部知らないと気が済まない、当たり → 好奇心結果 あなたはどのタイプ？',
      'zh-CN': '我的好奇心类型：专业深化型 📚 说我把一个挖到底…一旦入迷不全会浑身难受太准 → 你的好奇心类型是？',
      'zh-TW': '我的好奇心類型：專業深化型 📚 說我把一個挖到底…一旦入迷不全會渾身難受太準 → 你的好奇心類型是？',
      vi: 'Loại tò mò của tôi: Chuyên sâu 📚 Bảo tôi đào một thứ đến cùng... cuốn vào là phải biết hết mới yên — đúng quá → Bạn loại tò mò nào?',
      id: 'Tipe rasa ingin tahu-ku: Spesialis Mendalam 📚 Katanya aku gali satu hal sampai tuntas... sekali kecanduan harus tahu semuanya — bener → Kamu tipe apa?',
    }),
  },
  {
    type: "Type3",
    emoji: "🕸️",
    title: localeMap({
      ko: '다른 세계의 연결 고리를 찾는 사람, 연결 탐색형',
      en: 'Someone Who Finds Links Between Worlds, Connection Explorer Type',
      ja: '異なる世界のつながりを見つける人、連結探索型',
      'zh-CN': '寻找不同世界连接的人，连接探索型',
      'zh-TW': '尋找不同世界連結的人，連結探索型',
      vi: 'Người tìm mắt xích giữa các thế giới, Loại khám phá kết nối',
      id: 'Orang yang Menemukan Tautan Antar Dunia, Tipe Eksplorasi Koneksi',
    }),
    curiositySummary: localeMap({
      ko: '서로 다른 분야 사이의 연결과 패턴을 발견하는 것을 즐기는 타입',
      en: 'Enjoys discovering connections and patterns between different fields',
      ja: '異なる分野間のつながりとパターンを発見することを楽しむタイプ',
      'zh-CN': '享受发现不同领域之间连接与模式的类型',
      'zh-TW': '享受發現不同領域之間連結與模式的類型',
      vi: 'Thích khám phá kết nối và mẫu hình giữa các lĩnh vực khác nhau',
      id: 'Menikmati menemukan koneksi dan pola antar bidang yang berbeda',
    }),
    quote: localeMap({
      ko: '당신의 호기심은 점들을 연결합니다. 전혀 다른 두 세계가 사실 같은 원리로 작동하고 있다는 것을 발견할 때 가장 살아있는 느낌이 납니다.',
      en: 'Your curiosity connects dots. You feel most alive when you discover that two utterly different worlds run on the same principle.',
      ja: 'あなたの好奇心は点と点をつなぎます。まったく異なる二つの世界が同じ原理で動いていると発見するとき、最も生きている感覚が得られます。',
      'zh-CN': '你的好奇心连接点与点。当发现两个完全不同的世界遵循同一原理时，你感到最鲜活。',
      'zh-TW': '你的好奇心連結點與點。當發現兩個完全不同的世界遵循同一原理時，你感到最鮮活。',
      vi: 'Sự tò mò của bạn nối các điểm lại với nhau. Bạn cảm thấy sống động nhất khi phát hiện hai thế giới hoàn toàn khác nhau vận hành theo cùng một nguyên lý.',
      id: 'Rasa ingin tahumu menghubungkan titik-titik. Kamu paling hidup saat menemukan dua dunia yang sangat berbeda berjalan dengan prinsip yang sama.',
    }),
    description: localeMap({
      ko: '생물학과 경제학이 같은 패턴을 가진다는 것, 음악 이론과 수학이 닮아있다는 것, 역사의 어떤 사건이 현재와 반복된다는 것을 발견하는 순간이 가장 짜릿한 타입입니다. 분야를 초월한 연결이 창의적 인사이트의 원천입니다.',
      en: 'The thrill comes when you find that biology and economics share a pattern, music theory resembles math, or a historical event echoes the present. Cross-field connections are the source of creative insight.',
      ja: '生物学と経済学が同じパターンを持つ、音楽理論と数学が似ている、歴史の出来事が現在と繰り返される——そういう発見の瞬間が最もゾクゾクするタイプです。分野を超えたつながりが創造的インサイトの源です。',
      'zh-CN': '发现生物学与经济学有相同模式、音乐理论与数学相似、历史事件与当下呼应的瞬间最让你兴奋。跨领域连接是创意洞见的源泉。',
      'zh-TW': '發現生物學與經濟學有相同模式、音樂理論與數學相似、歷史事件與當下呼應的瞬間最讓你興奮。跨領域連結是創意洞見的源泉。',
      vi: 'Khoảnh khắc phấn khích nhất là khi thấy sinh học và kinh tế cùng một mẫu, lý thuyết âm nhạc giống toán học, hay sự kiện lịch sử lặp lại ở hiện tại. Kết nối liên ngành là nguồn góc nhìn sáng tạo.',
      id: 'Momen paling seru saat menemukan biologi dan ekonomi punya pola sama, teori musik mirip matematika, atau peristiwa sejarah bergema di masa kini. Koneksi lintas bidang adalah sumber wawasan kreatif.',
    }),
    curiosityType: localeMap({
      ko: '연결 탐색형 🕸️',
      en: 'Connection Explorer Type 🕸️',
      ja: '連結探索型 🕸️',
      'zh-CN': '连接探索型 🕸️',
      'zh-TW': '連結探索型 🕸️',
      vi: 'Loại khám phá kết nối 🕸️',
      id: 'Tipe Eksplorasi Koneksi 🕸️',
    }),
    exploreKeywords: localeMap({
      ko: '연결·패턴·통합·초월·메타 인사이트',
      en: 'Connection · Pattern · Integration · Transcendence · Meta insight',
      ja: '連結・パターン・統合・超越・メタインサイト',
      'zh-CN': '连接·模式·整合·超越·元洞察',
      'zh-TW': '連結·模式·整合·超越·元洞察',
      vi: 'Kết nối · Mẫu hình · Tích hợp · Vượt giới hạn · Góc nhìn siêu cấp',
      id: 'Koneksi · Pola · Integrasi · Transendensi · Wawasan meta',
    }),
    strengths: localeMap({
      ko: '타 분야의 개념을 자신의 분야에 적용하는 창의적 문제 해결 능력\n전문가들이 각자의 영역에 갇혀 보지 못하는 연결을 발견함\n독창적인 아이디어와 발상의 원천이 됨',
      en: 'Creative problem-solving by applying concepts from other fields\nDiscovers links experts trapped in their own domains miss\nSource of original ideas and fresh thinking',
      ja: '他分野の概念を自分の分野に応用する創造的問題解決能力\n専門家が各分野に閉じ込められて見逃すつながりを発見\n独創的なアイデアと発想の源になる',
      'zh-CN': '将其他领域概念应用到自身领域，具备创意解题能力\n发现各领域的专家看不到的连接\n是原创想法与新思维的源泉',
      'zh-TW': '將其他領域概念應用到自身領域，具備創意解題能力\n發現各領域的專家看不到的連結\n是原創想法與新思維的源泉',
      vi: 'Giải quyết vấn đề sáng tạo bằng cách áp dụng khái niệm từ lĩnh vực khác\nPhát hiện liên kết mà chuyên gia mắc kẹt trong lĩnh vực riêng bỏ lỡ\nNguồn ý tưởng độc đáo và tư duy mới',
      id: 'Pemecahan masalah kreatif dengan menerapkan konsep dari bidang lain\nMenemukan tautan yang terlewat oleh ahli terkurung di domain masing-masing\nSumber ide orisinal dan pemikiran segar',
    }),
    cautions: localeMap({
      ko: '연결을 찾다 보면 하나를 깊이 파는 것이 어려울 수 있음. 깊이와 연결의 균형 필요\n연결이 흥미롭게 보여도 실제로 유효한지 검증하는 과정이 필요함',
      en: 'Searching for connections can make it hard to go deep in one area — balance depth and connection\nEven exciting links need validation to confirm they are truly valid',
      ja: 'つながりを探すうちに一つを深く掘るのが難しくなることがある。深さと連結のバランスが必要\nつながりが面白く見えても、実際に有効か検証する過程が必要',
      'zh-CN': '寻找连接时可能难以在一个领域深挖——需要平衡深度与连接\n即使连接看起来有趣，也需要验证其是否真正有效',
      'zh-TW': '尋找連結時可能難以在一個領域深挖——需要平衡深度與連結\n即使連結看起來有趣，也需要驗證其是否真正有效',
      vi: 'Tìm kết nối có thể khiến khó đào sâu một lĩnh vực — cần cân bằng chiều sâu và kết nối\nDù liên kết hấp dẫn cũng cần kiểm chứng xem có thực sự hợp lệ',
      id: 'Mencari koneksi bisa membuat sulit menggali dalam satu bidang — perlu keseimbangan kedalaman dan koneksi\nMeski tautan terlihat menarik, perlu validasi apakah benar-benar valid',
    }),
    contentRecommend: localeMap({
      ko: '분야를 초월하는 TED 강연·교양서·복잡계·시스템 이론·다학제 콘텐츠',
      en: 'Cross-field TED talks · General education books · Complexity · Systems theory · Interdisciplinary content',
      ja: '分野横断TED・教養書・複雑系・システム理論・学際的コンテンツ',
      'zh-CN': '跨领域TED演讲·通识读物·复杂系统·系统理论·跨学科内容',
      'zh-TW': '跨領域TED演講·通識讀物·複雜系統·系統理論·跨學科內容',
      vi: 'TED liên ngành · Sách giáo dục phổ thông · Hệ phức tạp · Lý thuyết hệ thống · Nội dung đa ngành',
      id: 'TED lintas bidang · Buku pendidikan umum · Kompleksitas · Teori sistem · Konten interdisipliner',
    }),
    growCuriosity: localeMap({
      ko: '하나의 개념을 발견하면 "이것과 같은 원리가 작동하는 전혀 다른 분야는 무엇일까?"를 질문해보기',
      en: 'When you discover a concept, ask: "What completely different field runs on the same principle?"',
      ja: '一つの概念を発見したら「同じ原理が働く、まったく異なる分野は何か？」と問いかけてみる',
      'zh-CN': '发现一个概念后，问：「有哪些完全不同的领域遵循同一原理？」',
      'zh-TW': '發現一個概念後，問：「有哪些完全不同的領域遵循同一原理？」',
      vi: 'Khi phát hiện một khái niệm, hỏi: "Lĩnh vực hoàn toàn khác nào vận hành theo cùng nguyên lý?"',
      id: 'Saat menemukan suatu konsep, tanyakan: "Bidang yang sama sekali berbeda apa yang berjalan dengan prinsip yang sama?"',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '당신은 세상이 생각보다 훨씬 연결되어 있다는 것을 보는 사람입니다. 그 시각은 어떤 분야에서든 독보적인 관점이 됩니다',
      en: 'You see that the world is far more connected than people think. That view becomes a unique perspective in any field',
      ja: '世界は思っているよりずっとつながっていることを見る人です。その視点はどんな分野でも独自の視野になります',
      'zh-CN': '你能看见世界比人们想象的更紧密相连。这种视角在任何领域都是独到观点',
      'zh-TW': '你能看見世界比人們想像的更緊密相連。這種視角在任何領域都是獨到觀點',
      vi: 'Bạn thấy thế giới liên kết hơn nhiều so với mọi người nghĩ. Góc nhìn ấy trở thành quan điểm độc đáo ở mọi lĩnh vực',
      id: 'Kamu melihat dunia jauh lebih terhubung dari yang dibayangkan. Pandangan itu jadi perspektif unik di bidang apa pun',
    }),
    shareLine: localeMap({
      ko: '내 호기심 유형: 연결 탐색형 🕸️ 다른 분야의 연결 고리 찾는 유형이래... 전혀 다른 두 가지가 같은 원리라는 거 발견할 때 소름 돋는 거 맞음 → 너는 어떤 호기심 유형이야?',
      en: 'My curiosity type: Connection Explorer 🕸️ They say I find links between fields... chills when two totally different things share the same principle — so true → What\'s your curiosity type?',
      ja: '私の好奇心タイプ: 連結探索型 🕸️ 異なる分野のつながりを見つけるタイプ…まったく違う二つが同じ原理、ゾクゾクするの当たり → あなたはどの好奇心タイプ？',
      'zh-CN': '我的好奇心类型：连接探索型 🕸️ 说我会找不同领域的连接…两个完全不同的东西竟是同一原理，起鸡皮疙瘩太准 → 你是什么好奇心类型？',
      'zh-TW': '我的好奇心類型：連結探索型 🕸️ 說我會找不同領域的連結…兩個完全不同的東西竟是同一原理，起雞皮疙瘩太準 → 你是什麼好奇心類型？',
      vi: 'Loại tò mò của tôi: Khám phá kết nối 🕸️ Bảo tôi tìm mắt xích giữa các lĩnh vực... hai thứ hoàn toàn khác cùng nguyên lý, sởn gai ốc — đúng quá → Bạn loại tò mò nào?',
      id: 'Tipe rasa ingin tahu-ku: Eksplorasi Koneksi 🕸️ Katanya aku cari tautan antar bidang... dua hal yang sangat berbeda prinsipnya sama, merinding — bener → Kamu tipe apa?',
    }),
  },
  {
    type: "Type4",
    emoji: "🗺️",
    title: localeMap({
      ko: '경계 없이 탐험하는 사람, 확산 탐험형',
      en: 'Someone Who Explores Without Boundaries, Broad Explorer Type',
      ja: '境界なく探索する人、拡散探検型',
      'zh-CN': '无边界探索的人，扩散探险型',
      'zh-TW': '無邊界探索的人，擴散探險型',
      vi: 'Người khám phá không ranh giới, Loại thám hiểm lan rộng',
      id: 'Orang yang Mengeksplorasi Tanpa Batas, Tipe Penjelajah Luas',
    }),
    curiositySummary: localeMap({
      ko: '분야·장르·경계 없이 다양한 것을 넓게 탐험하는 타입',
      en: 'Explores widely across fields, genres, and boundaries without limits',
      ja: '分野・ジャンル・境界なく多様なものを広く探検するタイプ',
      'zh-CN': '跨越领域、类型与边界，广泛探索的类型',
      'zh-TW': '跨越領域、類型與邊界，廣泛探索的類型',
      vi: 'Khám phá rộng khắp qua lĩnh vực, thể loại và ranh giới không giới hạn',
      id: 'Mengeksplorasi luas lintas bidang, genre, dan batas tanpa batas',
    }),
    quote: localeMap({
      ko: '당신의 호기심에는 지도가 없습니다. 흥미로운 것이 나타나면 어느 방향이든 달려갑니다.',
      en: 'Your curiosity has no map. When something interesting appears, you run in any direction.',
      ja: 'あなたの好奇心には地図がありません。面白いものが現れれば、どの方向へでも走り出します。',
      'zh-CN': '你的好奇心没有地图。有趣的东西一出现，你就朝任何方向奔去。',
      'zh-TW': '你的好奇心沒有地圖。有趣的東西一出現，你就朝任何方向奔去。',
      vi: 'Sự tò mò của bạn không có bản đồ. Điều thú vị xuất hiện là bạn chạy theo bất kỳ hướng nào.',
      id: 'Rasa ingin tahumu tidak punya peta. Saat sesuatu menarik muncul, kamu berlari ke arah mana pun.',
    }),
    description: localeMap({
      ko: '관심 분야의 경계가 모호하고 무엇이든 새로운 것이면 일단 흥미롭고 여러 분야를 넓게 탐험하면서 뜻밖의 발견을 수집하는 타입입니다. 폭넓은 관심사가 다양한 관점과 풍부한 연상의 원천이 됩니다.',
      en: 'Your interest boundaries are fuzzy — almost anything new catches your eye. You explore many fields widely and collect unexpected discoveries. Broad interests become a source of diverse perspectives and rich associations.',
      ja: '関心分野の境界が曖昧で、新しいものなら何でも面白い。複数分野を広く探検し、思いがけない発見を集めるタイプです。幅広い関心が多様な視点と豊かな連想の源になります。',
      'zh-CN': '兴趣边界模糊，几乎任何新事物都有趣。你广泛探索多个领域，收集意外发现。广泛的兴趣成为多元视角与丰富联想的源泉。',
      'zh-TW': '興趣邊界模糊，幾乎任何新事物都有趣。你廣泛探索多個領域，收集意外發現。廣泛的興趣成為多元視角與豐富聯想的源泉。',
      vi: 'Ranh giới quan tâm mơ hồ — gần như mọi thứ mới đều hấp dẫn. Bạn khám phá rộng nhiều lĩnh vực và thu thập phát hiện bất ngờ. Sở thích rộng trở thành nguồn góc nhìn đa dạng và liên tưởng phong phú.',
      id: 'Batas minatmu kabur — hampir semua yang baru menarik perhatian. Kamu mengeksplorasi banyak bidang secara luas dan mengumpulkan temuan tak terduga. Minat luas jadi sumber perspektif beragam dan asosiasi kaya.',
    }),
    curiosityType: localeMap({
      ko: '확산 탐험형 🗺️',
      en: 'Broad Explorer Type 🗺️',
      ja: '拡散探検型 🗺️',
      'zh-CN': '扩散探险型 🗺️',
      'zh-TW': '擴散探險型 🗺️',
      vi: 'Loại thám hiểm lan rộng 🗺️',
      id: 'Tipe Penjelajah Luas 🗺️',
    }),
    exploreKeywords: localeMap({
      ko: '다양성·탐험·넓이·발견·경계 없음',
      en: 'Diversity · Exploration · Breadth · Discovery · No boundaries',
      ja: '多様性・探検・広さ・発見・境界なし',
      'zh-CN': '多样性·探险·广度·发现·无边界',
      'zh-TW': '多樣性·探險·廣度·發現·無邊界',
      vi: 'Đa dạng · Thám hiểm · Chiều rộng · Khám phá · Không ranh giới',
      id: 'Keragaman · Eksplorasi · Keluasan · Penemuan · Tanpa batas',
    }),
    strengths: localeMap({
      ko: '다양한 분야의 지식이 쌓여 어떤 대화에서도 연결 고리를 찾아냄\n새로운 환경이나 분야에 빠르게 적응하는 능력\n전혀 다른 배경의 사람들과 소통하는 능력이 높음',
      en: 'Knowledge across fields lets you find connections in any conversation\nQuick to adapt to new environments or fields\nStrong at communicating with people from very different backgrounds',
      ja: '多様な分野の知識が積み重なり、どんな会話でもつながりを見つけられる\n新しい環境や分野に素早く適応する能力\nまったく異なる背景の人々とコミュニケーションする能力が高い',
      'zh-CN': '跨领域知识积累，让你在任何对话中都能找到连接\n快速适应新环境或新领域\n与背景完全不同的人沟通能力很强',
      'zh-TW': '跨領域知識累積，讓你在任何對話中都能找到連結\n快速適應新環境或新領域\n與背景完全不同的人溝通能力很強',
      vi: 'Kiến thức đa lĩnh vực giúp bạn tìm kết nối trong mọi cuộc trò chuyện\nThích nghi nhanh với môi trường hoặc lĩnh vực mới\nGiỏi giao tiếp với người có nền tảng hoàn toàn khác',
      id: 'Pengetahuan lintas bidang membuatmu menemukan koneksi di percakapan apa pun\nCepat beradaptasi ke lingkungan atau bidang baru\nKuat berkomunikasi dengan orang dari latar belakang sangat berbeda',
    }),
    cautions: localeMap({
      ko: '넓게 알지만 특정 분야의 깊은 전문성이 부족할 수 있음. 의도적인 깊이 투자가 도움이 됨\n흥미가 분산되다 보면 하나를 끝까지 완수하기 어려운 경우가 생김',
      en: 'You may know widely but lack deep expertise in one field — intentional depth helps\nScattered interest can make it hard to finish one thing completely',
      ja: '広く知っているが特定分野の深い専門性が不足することがある。意図的な深さへの投資が助けになる\n興味が分散すると一つを最後まで完遂するのが難しくなる場合がある',
      'zh-CN': '可能知道很广，但某一领域的深度专业不足——刻意投入深度会有帮助\n兴趣分散时，可能难以把一件事完整做完',
      'zh-TW': '可能知道很廣，但某一領域的深度專業不足——刻意投入深度會有幫助\n興趣分散時，可能難以把一件事完整做完',
      vi: 'Biết rộng nhưng có thể thiếu chuyên sâu một lĩnh vực — đầu tư chiều sâu có chủ ý sẽ giúp\nQuan tâm phân tán có thể khiến khó hoàn thành trọn vẹn một việc',
      id: 'Mungkin tahu luas tapi kurang keahlian mendalam di satu bidang — investasi kedalaman sengaja membantu\nMinat terpecah bisa membuat sulit menyelesaikan satu hal sepenuhnya',
    }),
    contentRecommend: localeMap({
      ko: '교양 팟캐스트·다큐멘터리·크로스오버 주제 책·뉴스레터·유튜브 알고리즘',
      en: 'General-interest podcasts · Documentaries · Crossover topic books · Newsletters · YouTube recommendations',
      ja: '教養ポッドキャスト・ドキュメンタリー・クロスオーバー書籍・ニュースレター・YouTubeおすすめ',
      'zh-CN': '通识播客·纪录片·跨界主题书籍·电子报·YouTube推荐',
      'zh-TW': '通識播客·紀錄片·跨界主題書籍·電子報·YouTube推薦',
      vi: 'Podcast giáo dục phổ thông · Phim tài liệu · Sách chủ đề xuyên lĩnh vực · Bản tin · Gợi ý YouTube',
      id: 'Podcast minat umum · Dokumenter · Buku topik crossover · Newsletter · Rekomendasi YouTube',
    }),
    growCuriosity: localeMap({
      ko: '넓게 탐험하다 가장 자주 돌아오는 주제 하나를 찾기. 그것이 당신의 핵심 관심사. 그곳에 의도적으로 깊이 투자해보기',
      en: 'While exploring widely, find the one topic you keep returning to. That is your core interest — invest depth there intentionally',
      ja: '広く探検しながら、最もよく戻ってくるテーマを一つ見つける。それがあなたの核心関心。そこに意図的に深さを投資してみる',
      'zh-CN': '广泛探索的同时，找出你最常回到的主题。那就是你的核心兴趣——刻意在那里投入深度',
      'zh-TW': '廣泛探索的同時，找出你最常回到的主題。那就是你的核心興趣——刻意在那裡投入深度',
      vi: 'Trong khi khám phá rộng, tìm chủ đề bạn hay quay lại nhất. Đó là quan tâm cốt lõi — đầu tư chiều sâu ở đó một cách có chủ ý',
      id: 'Saat mengeksplorasi luas, temukan topik yang paling sering kamu kembali. Itu minat intimu — investasi kedalaman di sana secara sengaja',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '당신의 넓은 탐험은 어느 날 갑자기 독보적인 관점의 원천이 됩니다. 탐험 중 가장 자주 돌아오는 곳에 당신의 핵심이 있습니다',
      en: 'Your wide exploration will someday become the source of a unique perspective. Your core lies where you return most often',
      ja: 'あなたの広い探検は、ある日突然、独自の視点の源になります。最もよく戻る場所にあなたの核心があります',
      'zh-CN': '你广泛的探索，某天会成为独到视角的源泉。你最常回到的地方，就是你的核心',
      'zh-TW': '你廣泛的探索，某天會成為獨到視角的源泉。你最常回到的地方，就是你的核心',
      vi: 'Cuộc khám phá rộng của bạn sẽ một ngày trở thành nguồn góc nhìn độc đáo. Cốt lõi nằm ở nơi bạn hay quay lại nhất',
      id: 'Eksplorasimu yang luas suatu hari jadi sumber perspektif unik. Intimu ada di tempat yang paling sering kamu kembali',
    }),
    shareLine: localeMap({
      ko: '내 호기심 유형: 확산 탐험형 🗺️ 분야 경계 없이 다 탐험하는 유형이래... 흥미로운 거 나타나면 어디든 달려가는 거 맞음 ㅋㅋ → 호기심 결과 너는?',
      en: 'My curiosity type: Broad Explorer 🗺️ They say I explore everything with no field limits... run anywhere when something interesting shows up — so true lol → What\'s your curiosity result?',
      ja: '私の好奇心タイプ: 拡散探検型 🗺️ 分野の境界なく全部探検するタイプ…面白いものが出たらどこへでも走る、当たり ㅋㅋ → 好奇心結果 あなたは？',
      'zh-CN': '我的好奇心类型：扩散探险型 🗺️ 说我没有领域边界到处探索…有趣的东西出现就冲太准哈哈 → 你的好奇心结果是？',
      'zh-TW': '我的好奇心類型：擴散探險型 🗺️ 說我沒有領域邊界到處探索…有趣的東西出現就衝太準哈哈 → 你的好奇心結果是？',
      vi: 'Loại tò mò của tôi: Thám hiểm lan rộng 🗺️ Bảo tôi khám phá mọi thứ không ranh giới lĩnh vực... thú vị là lao đi — đúng quá haha → Kết quả tò mò của bạn?',
      id: 'Tipe rasa ingin tahu-ku: Penjelajah Luas 🗺️ Katanya aku jelajahi semua tanpa batas bidang... ada yang menarik langsung lari — bener wkwk → Hasil rasa ingin tahu kamu?',
    }),
  },
  {
    type: "Type5",
    emoji: "❓",
    title: localeMap({
      ko: '왜를 멈추지 않는 사람, 질문 탐구형',
      en: 'Someone Who Never Stops Asking Why, Question Explorer Type',
      ja: 'なぜを止めない人、質問探究型',
      'zh-CN': '不停追问为什么的人，提问探究型',
      'zh-TW': '不停追問為什麼的人，提問探究型',
      vi: 'Người không ngừng hỏi tại sao, Loại khám phá qua câu hỏi',
      id: 'Orang yang Tidak Berhenti Bertanya Mengapa, Tipe Eksplorasi Pertanyaan',
    }),
    curiositySummary: localeMap({
      ko: '사실보다 원리, 원리보다 이유를 끝없이 물어보는 타입',
      en: 'Endlessly asks why beyond facts, and why beyond principles',
      ja: '事実より原理、原理より理由を終わりなく問い続けるタイプ',
      'zh-CN': '不停追问事实背后的原理，以及原理背后的理由',
      'zh-TW': '不停追問事實背後的原理，以及原理背後的理由',
      vi: 'Liên tục hỏi tại sao vượt xa sự thật, và tại sao vượt xa nguyên lý',
      id: 'Terus bertanya mengapa melampaui fakta, dan mengapa melampaui prinsip',
    }),
    quote: localeMap({
      ko: '당신의 탐구는 하나의 질문이 열 개의 질문을 낳습니다. 왜?는 항상 다음 왜?를 부릅니다.',
      en: 'Your inquiry turns one question into ten. Why? always calls the next why?',
      ja: 'あなたの探究は一つの質問が十の質問を生みます。なぜ？は常に次のなぜ？を呼びます。',
      'zh-CN': '你的探究让一个问号生出十个。为什么？总会引出下一个为什么？',
      'zh-TW': '你的探究讓一個問號生出十個。為什麼？總會引出下一個為什麼？',
      vi: 'Cuộc khám phá của bạn biến một câu hỏi thành mười câu. Tại sao? luôn gọi tiếp tại sao?',
      id: 'Eksplorasimu mengubah satu pertanyaan jadi sepuluh. Mengapa? selalu memanggil mengapa berikutnya?',
    }),
    description: localeMap({
      ko: '어떤 사실을 알게 되면 그것이 왜 그런지, 그 이면에는 무엇이 있는지, 반례는 없는지를 연속으로 물어보고 당연하게 받아들여지는 것들을 의심하고 다시 보는 것이 자연스러운 타입입니다. 이 패턴이 가장 깊은 이해와 창의적 발견을 만들어냅니다.',
      en: 'When you learn a fact, you ask why it is so, what lies beneath, and whether counterexamples exist. Questioning what others take for granted and seeing again feels natural. This pattern creates the deepest understanding and the most creative discoveries.',
      ja: 'ある事実を知ると、なぜそうなのか、その奥には何があるのか、反例はないのかを連続で問い、当たり前とされるものを疑い再び見るのが自然なタイプです。このパターンが最も深い理解と創造的発見を生み出します。',
      'zh-CN': '得知某个事实后，你会连续追问为何如此、背后是什么、有无反例。质疑被视为理所当然的事物并重新观看，对你很自然。这种模式创造最深的理解与最有创意的发现。',
      'zh-TW': '得知某個事實後，你會連續追問為何如此、背後是什麼、有無反例。質疑被視為理所當然的事物並重新觀看，對你很自然。這種模式創造最深的理解與最有創意的發現。',
      vi: 'Khi biết một sự thật, bạn hỏi liên tiếp vì sao như vậy, bên trong là gì, có phản ví không. Nghi ngờ điều được coi là hiển nhiên và nhìn lại là điều tự nhiên. Mẫu này tạo hiểu biết sâu nhất và khám phá sáng tạo nhất.',
      id: 'Saat mengetahui suatu fakta, kamu bertanya beruntun mengapa demikian, apa di baliknya, apakah ada contoh penyangkal. Mempertanyakan hal yang dianggap wajar dan melihat ulang terasa alami. Pola ini menciptakan pemahaman paling dalam dan penemuan paling kreatif.',
    }),
    curiosityType: localeMap({
      ko: '질문 탐구형 ❓',
      en: 'Question Explorer Type ❓',
      ja: '質問探究型 ❓',
      'zh-CN': '提问探究型 ❓',
      'zh-TW': '提問探究型 ❓',
      vi: 'Loại khám phá qua câu hỏi ❓',
      id: 'Tipe Eksplorasi Pertanyaan ❓',
    }),
    exploreKeywords: localeMap({
      ko: '왜·원리·비판적 사고·의심·깊이 있는 이해',
      en: 'Why · Principles · Critical thinking · Doubt · Deep understanding',
      ja: 'なぜ・原理・批判的思考・疑い・深い理解',
      'zh-CN': '为什么·原理·批判性思维·质疑·深度理解',
      'zh-TW': '為什麼·原理·批判性思維·質疑·深度理解',
      vi: 'Tại sao · Nguyên lý · Tư duy phản biện · Nghi ngờ · Hiểu biết sâu',
      id: 'Mengapa · Prinsip · Berpikir kritis · Keraguan · Pemahaman mendalam',
    }),
    strengths: localeMap({
      ko: '표면 아래 원리를 꿰뚫는 능력. 같은 정보를 봐도 더 깊이 이해함\n당연한 것을 다시 보는 능력. 새로운 발견과 혁신의 원천\n복잡한 문제를 근본부터 분석하는 능력',
      en: 'Penetrates principles beneath the surface — understands the same information more deeply\nAbility to see the taken-for-granted again — source of new discovery and innovation\nAnalyzes complex problems from the root up',
      ja: '表面の下の原理を見抜く能力。同じ情報をより深く理解する\n当たり前を再び見る能力。新しい発見と革新の源\n複雑な問題を根本から分析する能力',
      'zh-CN': '穿透表面下的原理，从同样信息中理解得更深\n重新看见被视为理所当然的事物——新发现与创新的源泉\n从根本分析复杂问题的能力',
      'zh-TW': '穿透表面下的原理，從同樣資訊中理解得更深\n重新看見被視為理所當然的事物——新發現與創新的源泉\n從根本分析複雜問題的能力',
      vi: 'Nhìn thấu nguyên lý dưới bề mặt — hiểu cùng thông tin sâu hơn\nKhả năng nhìn lại điều được coi là hiển nhiên — nguồn khám phá mới và đổi mới\nPhân tích vấn đề phức tạp từ gốc rễ',
      id: 'Menembus prinsip di bawah permukaan — memahami informasi yang sama lebih dalam\nKemampuan melihat ulang hal yang dianggap wajar — sumber penemuan baru dan inovasi\nMenganalisis masalah kompleks dari akar',
    }),
    cautions: localeMap({
      ko: '질문이 너무 많아지면 결론에 도달하기 전에 에너지를 소모하는 경우가 있음\n모든 것에 의문을 품다 보면 행동으로 넘어가는 것이 늦어질 수 있음\n답이 없는 질문 앞에서 불편함을 느낄 수 있음. 불확실성을 즐기는 연습도 필요',
      en: 'Too many questions can drain energy before reaching a conclusion\nDoubting everything can delay moving into action\nYou may feel uncomfortable before questions with no answer — practice enjoying uncertainty too',
      ja: '質問が多すぎると結論に至る前にエネルギーを消耗することがある\nすべてに疑問を持つうちに行動へ移るのが遅れることがある\n答えのない質問の前で不快感を感じることがある。不確実性を楽しむ練習も必要',
      'zh-CN': '问题太多可能在得出结论前就耗尽能量\n对一切都质疑可能延迟行动\n面对没有答案的问题可能感到不适——也需要练习享受不确定',
      'zh-TW': '問題太多可能在得出結論前就耗盡能量\n對一切都質疑可能延遲行動\n面對沒有答案的問題可能感到不適——也需要練習享受不確定',
      vi: 'Quá nhiều câu hỏi có thể tiêu hao năng lượng trước khi có kết luận\nNghi ngờ mọi thứ có thể trì hoãn hành động\nCó thể khó chịu trước câu hỏi không có đáp án — cần luyện tận hưởng sự không chắc chắn',
      id: 'Terlalu banyak pertanyaan bisa habiskan energi sebelum sampai kesimpulan\nMeragukan semuanya bisa menunda bertindak\nBisa merasa tidak nyaman di hadapan pertanyaan tanpa jawaban — latih menikmati ketidakpastian juga',
    }),
    contentRecommend: localeMap({
      ko: '철학·과학 원리 탐구·비판적 사고 책·논쟁이 있는 분야의 깊은 토론',
      en: 'Philosophy · Exploring scientific principles · Critical thinking books · Deep debates in contested fields',
      ja: '哲学・科学原理の探究・批判的思考の書・論争のある分野の深い討論',
      'zh-CN': '哲学·科学原理探索·批判性思维书籍·有争议领域的深度讨论',
      'zh-TW': '哲學·科學原理探索·批判性思維書籍·有爭議領域的深度討論',
      vi: 'Triết học · Khám phá nguyên lý khoa học · Sách tư duy phản biện · Thảo luận sâu ở lĩnh vực còn tranh cãi',
      id: 'Filosofi · Eksplorasi prinsip ilmiah · Buku berpikir kritis · Debate mendalam di bidang kontroversial',
    }),
    growCuriosity: localeMap({
      ko: '하나의 질문을 오래 붙잡고 있어보기. 빠른 답보다 좋은 질문이 더 중요한 경우가 많음. "이 질문을 더 정밀하게 만들 수 있는가?"를 물어보기',
      en: 'Hold onto one question for a long time. A good question often matters more than a quick answer. Ask: "Can I make this question more precise?"',
      ja: '一つの質問を長く握り続けてみる。速い答えより良い質問の方が重要な場合が多い。「この質問をもっと精密にできるか？」と問いかける',
      'zh-CN': '长时间抓住一个问题。好问题往往比快答案更重要。问：「我能否让这个问题更精确？」',
      'zh-TW': '長時間抓住一個問題。好問題往往比快答案更重要。問：「我能否讓這個問題更精確？」',
      vi: 'Giữ một câu hỏi lâu. Câu hỏi hay thường quan trọng hơn câu trả lời nhanh. Hỏi: "Tôi có thể làm câu hỏi này chính xác hơn không?"',
      id: 'Pegang satu pertanyaan lama. Pertanyaan bagus sering lebih penting dari jawaban cepat. Tanyakan: "Bisakah aku membuat pertanyaan ini lebih presisi?"',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '왜를 멈추지 않는 사람이 세상을 바꿉니다. 다만 좋은 질문은 답을 찾는 것이 아니라 더 나은 질문으로 이어지는 것임을 기억하세요',
      en: 'People who never stop asking why change the world. Remember: a good question leads not to an answer but to a better question',
      ja: 'なぜを止めない人が世界を変えます。ただし良い質問は答えを見つけるのではなく、より良い質問へと続くことを忘れないで',
      'zh-CN': '不停问为什么的人改变世界。但请记住：好问题不是找到答案，而是引向更好的问题',
      'zh-TW': '不停問為什麼的人改變世界。但請記住：好問題不是找到答案，而是引向更好的問題',
      vi: 'Người không ngừng hỏi tại sao thay đổi thế giới. Nhớ rằng: câu hỏi hay không dẫn tới đáp án mà tới câu hỏi tốt hơn',
      id: 'Orang yang tidak berhenti bertanya mengapa mengubah dunia. Ingat: pertanyaan bagus tidak menuju jawaban melainkan pertanyaan yang lebih baik',
    }),
    shareLine: localeMap({
      ko: '내 호기심 유형: 질문 탐구형 ❓ 왜를 멈추지 않는 유형이래... 하나 알면 열 개 질문이 생기는 거 맞음 ㅠ → 호기심 결과 너는 어떤 유형이야?',
      en: 'My curiosity type: Question Explorer ❓ They say I never stop asking why... one fact spawns ten questions — so true → What\'s your curiosity type?',
      ja: '私の好奇心タイプ: 質問探究型 ❓ なぜを止めないタイプ…一つ知ると十の質問が生まれる、当たり → 好奇心結果 あなたはどのタイプ？',
      'zh-CN': '我的好奇心类型：提问探究型 ❓ 说我不停问为什么…知道一个就生出十个问题太准 → 你的好奇心类型是？',
      'zh-TW': '我的好奇心類型：提問探究型 ❓ 說我不停問為什麼…知道一個就生出十個問題太準 → 你的好奇心類型是？',
      vi: 'Loại tò mò của tôi: Khám phá qua câu hỏi ❓ Bảo tôi không ngừng hỏi tại sao... biết một cái sinh ra mười câu hỏi — đúng quá → Bạn loại tò mò nào?',
      id: 'Tipe rasa ingin tahu-ku: Eksplorasi Pertanyaan ❓ Katanya aku nggak berhenti nanya kenapa... satu fakta jadi sepuluh pertanyaan — bener → Kamu tipe apa?',
    }),
  },
  {
    type: "Type6",
    emoji: "🌟",
    title: localeMap({
      ko: '세상 모든 것이 신기한 사람, 경이로움 탐험형',
      en: 'Someone Who Finds Everything Wonderous, Wonder Explorer Type',
      ja: '世界のすべてが不思議な人、驚異探検型',
      'zh-CN': '觉得世间万物都神奇的人，惊奇探险型',
      'zh-TW': '覺得世間萬物都神奇的人，驚奇探險型',
      vi: 'Người thấy mọi thứ trên đời đều kỳ diệu, Loại khám phá kinh ngạc',
      id: 'Orang yang Merasa Segalanya Ajaib, Tipe Penjelajah Keajaiban',
    }),
    curiositySummary: localeMap({
      ko: '삶의 모든 것에서 신기함과 경이로움을 발견하는 극강 호기심 타입',
      en: 'Extreme curiosity type that finds wonder and awe in everything in life',
      ja: '人生のすべてから不思議さと驚異を見出す、極強の好奇心タイプ',
      'zh-CN': '从生活中一切事物发现神奇与惊奇的极强好奇心类型',
      'zh-TW': '從生活中一切事物發現神奇與驚奇的極強好奇心類型',
      vi: 'Loại tò mò cực mạnh khám phá sự kỳ diệu và kinh ngạc trong mọi thứ của cuộc sống',
      id: 'Tipe rasa ingin tahu ekstrem yang menemukan keajaiban dan kekaguman di segala hal hidup',
    }),
    quote: localeMap({
      ko: '당신에게 세상은 탐구가 끝나지 않는 거대한 신비입니다. 알면 알수록 모르는 게 많아진다는 것이 두려움이 아니라 기쁨입니다.',
      en: 'To you, the world is a vast mystery that never stops inviting inquiry. The more you know, the more you do not know — and that is joy, not fear.',
      ja: 'あなたにとって世界は探究が終わらない巨大な神秘です。知れば知るほど知らないことが増えるのは恐れではなく喜びです。',
      'zh-CN': '对你而言，世界是永远探究不完的巨大神秘。知道越多，未知越多——那不是恐惧，而是喜悦。',
      'zh-TW': '對你而言，世界是永遠探究不完的巨大神秘。知道越多，未知越多——那不是恐懼，而是喜悅。',
      vi: 'Với bạn, thế giới là bí ẩn bao la không bao giờ hết mời gọi khám phá. Biết càng nhiều, không biết càng nhiều — đó là niềm vui, không phải sợ hãi.',
      id: 'Bagimu, dunia adalah misteri besar yang tak pernah berhenti mengundang eksplorasi. Semakin tahu, semakin banyak yang belum tahu — itu kegembiraan, bukan ketakutan.',
    }),
    description: localeMap({
      ko: '분야·장르·주제 경계 없이 무엇이든 흥미롭고 모르는 것을 발견하면 즉각 탐구가 시작되며 탐구할수록 세상이 더 넓어지는 것을 즐기는 타입입니다. 어린아이가 세상을 처음 보는 것 같은 경이로움이 성인이 돼서도 유지되는 가장 희귀한 유형입니다.',
      en: 'Without boundaries of field, genre, or topic, almost anything interests you. Discovery triggers inquiry instantly, and the more you explore, the wider the world feels. Childlike wonder that persists into adulthood is the rarest type of all.',
      ja: '分野・ジャンル・テーマの境界なく何でも面白く、知らないものを発見すれば即座に探究が始まり、探究すればするほど世界が広がるのを楽しむタイプです。子どもの頃のような驚異の感覚が大人になっても保たれる、最も希少なタイプです。',
      'zh-CN': '没有领域、类型、主题的边界，几乎什么都有趣；发现未知立刻开始探究，越探究越觉得世界更广阔。成年后仍保持孩童般惊奇感，是最罕见的类型。',
      'zh-TW': '沒有領域、類型、主題的邊界，幾乎什麼都有趣；發現未知立刻開始探究，越探究越覺得世界更廣闊。成年後仍保持孩童般驚奇感，是最罕見的類型。',
      vi: 'Không ranh giới lĩnh vực, thể loại hay chủ đề — gần như mọi thứ đều thú vị. Phát hiện điều chưa biết là khám phá bắt đầu ngay, càng khám phá càng thấy thế giới rộng hơn. Cảm giác kinh ngạc như trẻ em kéo dài đến tuổi trưởng thành là loại hiếm nhất.',
      id: 'Tanpa batas bidang, genre, atau topik, hampir semuanya menarik. Penemuan memicu eksplorasi seketika, dan semakin eksplorasi, dunia terasa semakin luas. Keajaiban seperti anak kecil yang bertahan hingga dewasa adalah tipe paling langka.',
    }),
    curiosityType: localeMap({
      ko: '경이로움 탐험형 🌟',
      en: 'Wonder Explorer Type 🌟',
      ja: '驚異探検型 🌟',
      'zh-CN': '惊奇探险型 🌟',
      'zh-TW': '驚奇探險型 🌟',
      vi: 'Loại khám phá kinh ngạc 🌟',
      id: 'Tipe Penjelajah Keajaiban 🌟',
    }),
    exploreKeywords: localeMap({
      ko: '경이로움·무한 탐구·열린 마음·발견의 기쁨·살아있음',
      en: 'Wonder · Infinite inquiry · Open mind · Joy of discovery · Aliveness',
      ja: '驚異・無限の探究・開かれた心・発見の喜び・生きている感覚',
      'zh-CN': '惊奇·无限探究·开放心态·发现的喜悦·活着的感觉',
      'zh-TW': '驚奇·無限探究·開放心態·發現的喜悅·活著的感覺',
      vi: 'Kinh ngạc · Khám phá vô hạn · Tâm hồn cởi mở · Niềm vui khám phá · Cảm giác sống',
      id: 'Keajaiban · Eksplorasi tak terbatas · Pikiran terbuka · Kegembiraan penemuan · Rasa hidup',
    }),
    strengths: localeMap({
      ko: '어떤 분야에서도 새로운 것을 발견하는 능력. 전문가들이 익숙하게 지나치는 것을 신기하게 봄\n탐구 자체에서 에너지를 얻기 때문에 학습 지속력이 매우 높음\n다양한 사람들과 연결되는 능력. 어떤 주제로도 대화를 이어갈 수 있음',
      en: 'Finds something new in any field — sees as wondrous what experts pass by\nDraws energy from inquiry itself, so learning stamina is very high\nConnects easily with many people — can continue conversation on any topic',
      ja: 'どんな分野でも新しいものを発見する能力。専門家が当たり前で見過ごすものを不思議に見る\n探究自体からエネルギーを得るため、学習の持続力が非常に高い\n多様な人々とつながる能力。どんなテーマでも会話を続けられる',
      'zh-CN': '在任何领域都能发现新事物——把专家习以为常的东西看成神奇\n从探究本身获得能量，学习持续力非常高\n与各种人轻松连接——任何话题都能继续聊下去',
      'zh-TW': '在任何領域都能發現新事物——把專家習以為常的東西看成神奇\n從探究本身獲得能量，學習持續力非常高\n與各種人輕鬆連接——任何話題都能繼續聊下去',
      vi: 'Phát hiện điều mới ở mọi lĩnh vực — thấy kỳ diệu ở thứ chuyên gia bỏ qua\nLấy năng lượng từ chính việc khám phá nên sức bền học tập rất cao\nKết nối dễ với nhiều người — mọi chủ đề đều tiếp tục trò chuyện được',
      id: 'Menemukan hal baru di bidang apa pun — melihat ajaib apa yang dilewati ahli\nMendapat energi dari eksplorasi itu sendiri, jadi stamina belajar sangat tinggi\nMudah terhubung dengan banyak orang — topik apa pun bisa dilanjutkan',
    }),
    cautions: localeMap({
      ko: '모든 것이 흥미롭다 보면 에너지가 분산되어 하나를 완성하기 어려울 수 있음\n탐구의 기쁨에 집중하다 보면 결과물을 만들어내는 것이 뒷전이 될 수 있음\n가끔은 하나에 깊이 투자하는 것이 이 호기심을 더욱 풍부하게 만들어줌',
      en: 'When everything is interesting, energy can scatter and finishing one thing becomes hard\nFocus on the joy of inquiry can push creating tangible results to the back\nSometimes investing depth in one area makes this curiosity even richer',
      ja: 'すべてが面白いとエネルギーが分散し、一つを完遂するのが難しくなることがある\n探究の喜びに集中すると、結果物を作ることが後回しになることがある\n時には一つに深く投資することが、この好奇心をより豊かにする',
      'zh-CN': '当一切都很有趣，能量可能分散，难以完成一件事\n专注探究的喜悦可能把产出成果推到后面\n有时在一个领域深度投入，会让这份好奇心更丰富',
      'zh-TW': '當一切都很有趣，能量可能分散，難以完成一件事\n專注探究的喜悅可能把產出成果推到後面\n有時在一個領域深度投入，會讓這份好奇心更豐富',
      vi: 'Khi mọi thứ đều thú vị, năng lượng có thể phân tán và khó hoàn thành một việc\nTập trung niềm vui khám phá có thể đẩy việc tạo kết quả cụ thể ra sau\nĐôi khi đầu tư chiều sâu một lĩnh vực làm tò mò này phong phú hơn',
      id: 'Saat semuanya menarik, energi bisa terpecah dan sulit menyelesaikan satu hal\nFokus pada kegembiraan eksplorasi bisa menunda membuat hasil nyata\nTerkadang investasi kedalaman di satu bidang membuat rasa ingin tahu ini lebih kaya',
    }),
    contentRecommend: localeMap({
      ko: '장르 무관·알고리즘 추천·우연한 발견·전시·여행·사람과의 대화',
      en: 'Any genre · Algorithm recommendations · Serendipitous discovery · Exhibitions · Travel · Conversations with people',
      ja: 'ジャンル不問・アルゴリズムおすすめ・偶然の発見・展示・旅行・人との対話',
      'zh-CN': '不限类型·算法推荐·偶然发现·展览·旅行·与人对话',
      'zh-TW': '不限類型·演算法推薦·偶然發現·展覽·旅行·與人對話',
      vi: 'Không giới hạn thể loại · Gợi ý thuật toán · Khám phá tình cờ · Triển lãm · Du lịch · Trò chuyện với mọi người',
      id: 'Genre bebas · Rekomendasi algoritme · Penemuan kebetulan · Pameran · Perjalanan · Percakapan dengan orang',
    }),
    growCuriosity: localeMap({
      ko: '탐구한 것들을 기록해두기. 어느 날 그 기록들이 독보적인 관점의 지도가 됨. 탐구에서 하나를 골라 끝까지 완성해보는 경험도 쌓기',
      en: 'Keep records of what you explore. One day those notes become a map of a unique perspective. Also try finishing one exploration all the way through',
      ja: '探究したものを記録しておく。ある日その記録が独自の視点の地図になる。探究の中から一つ選んで最後まで完成させる経験も積む',
      'zh-CN': '记录你探究过的东西。某天那些记录会成为独到视角的地图。也试着选一项探究做到底',
      'zh-TW': '記錄你探究過的東西。某天那些記錄會成為獨到視角的地圖。也試著選一項探究做到底',
      vi: 'Ghi lại những gì bạn khám phá. Một ngày những ghi chép ấy trở thành bản đồ góc nhìn độc đáo. Cũng thử hoàn thành trọn vẹn một cuộc khám phá',
      id: 'Catat apa yang kamu eksplorasi. Suatu hari catatan itu jadi peta perspektif unik. Coba juga menyelesaikan satu eksplorasi sampai tuntas',
    }),
    certificationPhrase: localeMap({
      ko: '경이로움 탐험형 달성 🌟 세상 모든 것이 신기한 극강 호기심 타입',
      en: 'Wonder Explorer Achieved 🌟 Extreme curiosity — everything in the world feels wonderous',
      ja: '驚異探検型達成 🌟 世界のすべてが不思議な、極強の好奇心タイプ',
      'zh-CN': '惊奇探险型达成 🌟 觉得世间万物都神奇的极强好奇心类型',
      'zh-TW': '驚奇探險型達成 🌟 覺得世間萬物都神奇的極強好奇心類型',
      vi: 'Đạt Loại Khám phá Kinh ngạc 🌟 Tò mò cực mạnh — mọi thứ trên đời đều kỳ diệu',
      id: 'Penjelajah Keajaiban tercapai 🌟 Rasa ingin tahu ekstrem — segalanya terasa ajaib',
    }),
    oneLiner: localeMap({
      ko: '당신에게 세상은 결코 지루해지지 않습니다. 그것이 가장 강력한 삶의 에너지 원천입니다',
      en: 'The world will never become boring to you. That is the most powerful source of life energy',
      ja: 'あなたにとって世界は決して退屈にはなりません。それが最も強力な人生のエネルギー源です',
      'zh-CN': '对你而言，世界永远不会无聊。那是最强大的人生能量来源',
      'zh-TW': '對你而言，世界永遠不會無聊。那是最強大的人生能量來源',
      vi: 'Với bạn, thế giới không bao giờ nhàm chán. Đó là nguồn năng lượng sống mạnh nhất',
      id: 'Bagimu, dunia tak pernah membosankan. Itu sumber energi hidup paling kuat',
    }),
    shareLine: localeMap({
      ko: '내 호기심 유형: 경이로움 탐험형 🌟 세상 모든 게 신기한 극강 호기심 유형이래... 알면 알수록 모르는 게 많아진다는 게 기쁘다는 거 맞음 ㅋㅋ → 너는 어떤 호기심 유형이야?',
      en: 'My curiosity type: Wonder Explorer 🌟 Extreme curiosity — everything feels wonderous... joy that the more you know, the more you don\'t know — so true lol → What\'s your curiosity type?',
      ja: '私の好奇心タイプ: 驚異探検型 🌟 世界のすべてが不思議な極強タイプ…知れば知るほど知らないことが増えるのが喜び、当たり ㅋㅋ → あなたはどの好奇心タイプ？',
      'zh-CN': '我的好奇心类型：惊奇探险型 🌟 说我对世间万物都神奇…知道越多未知越多反而开心太准哈哈 → 你是什么好奇心类型？',
      'zh-TW': '我的好奇心類型：驚奇探險型 🌟 說我對世間萬物都神奇…知道越多未知越多反而開心太準哈哈 → 你是什麼好奇心類型？',
      vi: 'Loại tò mò của tôi: Khám phá kinh ngạc 🌟 Tò mò cực mạnh — mọi thứ đều kỳ diệu... biết càng nhiều không biết càng nhiều mà vui — đúng quá haha → Bạn loại tò mò nào?',
      id: 'Tipe rasa ingin tahu-ku: Penjelajah Keajaiban 🌟 Rasa ingin tahu ekstrem — segalanya ajaib... semakin tahu semakin banyak yang belum tahu justru senang — bener wkwk → Kamu tipe apa?',
    }),
  },
];
