/** 나라별 인사말 맞추기 챌린지 — phase3-world-greeting-challenge · 12문항 4지선다 · 정답 +1 오답 0 · 7개 로케일 */

export type Phase3WorldGreetingChallengeLocaleKey = 'ko' | 'en' | 'ja' | 'zh-CN' | 'zh-TW' | 'vi' | 'id';

function localeMap(t: Record<Phase3WorldGreetingChallengeLocaleKey, string>): Record<Phase3WorldGreetingChallengeLocaleKey, string> {
  return t;
}

function quizOpt(m: Record<Phase3WorldGreetingChallengeLocaleKey, string>, isCorrect: boolean): { text: Record<Phase3WorldGreetingChallengeLocaleKey, string>; isCorrect: boolean } {
  return { text: localeMap(m), isCorrect };
}

export interface Phase3WorldGreetingChallengeOption {
  text: Record<Phase3WorldGreetingChallengeLocaleKey, string>;
  isCorrect: boolean;
}

export interface Phase3WorldGreetingChallengeQuestion {
  id: number;
  imageFile: string;
  question: Record<Phase3WorldGreetingChallengeLocaleKey, string>;
  options: Phase3WorldGreetingChallengeOption[];
  correctExplanation: Record<Phase3WorldGreetingChallengeLocaleKey, string>;
  wrongTraps: Record<Phase3WorldGreetingChallengeLocaleKey, string>;
}

export interface Phase3WorldGreetingChallengeResult {
  type: string;
  emoji: string;
  title: Record<Phase3WorldGreetingChallengeLocaleKey, string>;
  shortDescription: Record<Phase3WorldGreetingChallengeLocaleKey, string>;
  description: Record<Phase3WorldGreetingChallengeLocaleKey, string>;
  languageGrade: Record<Phase3WorldGreetingChallengeLocaleKey, string>;
  scoreRange: Record<Phase3WorldGreetingChallengeLocaleKey, string>;
  strengthZone: Record<Phase3WorldGreetingChallengeLocaleKey, string>;
  weakZone: Record<Phase3WorldGreetingChallengeLocaleKey, string>;
  retakeTip: Record<Phase3WorldGreetingChallengeLocaleKey, string>;
  characteristic: Record<Phase3WorldGreetingChallengeLocaleKey, string>;
  regretPoint: Record<Phase3WorldGreetingChallengeLocaleKey, string>;
  certificationPhrase: Record<Phase3WorldGreetingChallengeLocaleKey, string>;
  oneLiner: Record<Phase3WorldGreetingChallengeLocaleKey, string>;
  shareLine: Record<Phase3WorldGreetingChallengeLocaleKey, string>;
}

export function calculatePhase3WorldGreetingChallengeResult(answers: number[]): string {
  const total = answers.reduce((sum, s) => sum + (s ?? 0), 0);
  if (total <= 2) return 'Level1';
  if (total <= 5) return 'Level2';
  if (total <= 8) return 'Level3';
  if (total <= 10) return 'Level4';
  return 'Level5';
}

export const phase3WorldGreetingChallengeQuestions: Phase3WorldGreetingChallengeQuestion[] = [
  {
    id: 1,
    imageFile: 'p3_quiz_world_greeting_challenge_q1.webp',
    question: localeMap({
      ko: '이 인사말은 어느 나라의 언어인가요?',
      en: 'Which country\'s language is this greeting?',
      ja: 'この挨拶はどの国の言語ですか？',
      'zh-CN': '这个问候语是哪个国家的语言？',
      'zh-TW': '這個問候語是哪個國家的語言？',
      vi: 'Lời chào này là ngôn ngữ của nước nào?',
      id: 'Salam ini berasal dari bahasa negara mana?',
    }),
    options: [
      quizOpt(localeMap({
        ko: '이탈리아',
        en: 'Italy',
        ja: 'イタリア',
        'zh-CN': '意大利',
        'zh-TW': '義大利',
        vi: 'Ý',
        id: 'Italia',
    }), false),
      quizOpt(localeMap({
        ko: '포르투갈',
        en: 'Portugal',
        ja: 'ポルトガル',
        'zh-CN': '葡萄牙',
        'zh-TW': '葡萄牙',
        vi: 'Bồ Đào Nha',
        id: 'Portugal',
    }), false),
      quizOpt(localeMap({
        ko: '프랑스',
        en: 'France',
        ja: 'フランス',
        'zh-CN': '法国',
        'zh-TW': '法國',
        vi: 'Pháp',
        id: 'Prancis',
    }), true),
      quizOpt(localeMap({
        ko: '루마니아',
        en: 'Romania',
        ja: 'ルーマニア',
        'zh-CN': '罗马尼亚',
        'zh-TW': '羅馬尼亞',
        vi: 'Romania',
        id: 'Rumania',
    }), false),
    ],
    correctExplanation: localeMap({
      ko: '프랑스어 인사말 "Bonjour(봉주르)"입니다. "Bon(좋은) + Jour(낮)"의 합성어로 "좋은 하루"라는 의미입니다. 프랑스어는 전 세계 약 30개국에서 공식 언어로 사용되며 약 3억 명이 사용합니다. 비슷하게 들리는 이탈리아어 인사말은 "Buongiorno(부온조르노)"입니다.',
      en: 'This is the French greeting "Bonjour." It combines "Bon (good) + Jour (day)" meaning "good day." French is an official language in about 30 countries worldwide and is spoken by roughly 300 million people. A similar-sounding Italian greeting is "Buongiorno."',
      ja: 'フランス語の挨拶「Bonjour（ボンジュール）」です。「Bon（良い）＋ Jour（昼）」の合成語で「良い一日を」という意味です。フランス語は世界約30か国で公用語となり、約3億人が使用します。似た響きのイタリア語の挨拶は「Buongiorno（ブオンジョルノ）」です。',
      'zh-CN': '这是法语问候语 "Bonjour（你好）"。由 "Bon（好）+ Jour（白天）" 组成，意为"美好的一天"。法语在全球约30国为官方语言，约3亿人使用。发音相近的意大利语问候是 "Buongiorno"。',
      'zh-TW': '這是法語問候語 "Bonjour（你好）"。由 "Bon（好）+ Jour（白天）" 組成，意為「美好的一天」。法語在全球約30國為官方語言，約3億人使用。發音相近的義大利語問候是 "Buongiorno"。',
      vi: 'Đây là lời chào tiếng Pháp "Bonjour." Ghép từ "Bon (tốt) + Jour (ngày)" nghĩa là "chúc một ngày tốt lành." Tiếng Pháp là ngôn ngữ chính thức ở khoảng 30 quốc gia, khoảng 300 triệu người dùng. Lời chào tiếng Ý nghe tương tự là "Buongiorno."',
      id: 'Ini salam bahasa Prancis "Bonjour." Gabungan "Bon (baik) + Jour (siang)" berarti "semoga hari baik." Prancis adalah bahasa resmi di sekitar 30 negara dan dipakai sekitar 300 juta orang. Salam Italia yang terdengar mirip adalah "Buongiorno."',
    }),
    wrongTraps: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
  },
  {
    id: 2,
    imageFile: 'p3_quiz_world_greeting_challenge_q2.webp',
    question: localeMap({
      ko: '이 인사말은 어느 나라의 언어인가요?',
      en: 'Which country\'s language is this greeting?',
      ja: 'この挨拶はどの国の言語ですか？',
      'zh-CN': '这个问候语是哪个国家的语言？',
      'zh-TW': '這個問候語是哪個國家的語言？',
      vi: 'Lời chào này là ngôn ngữ của nước nào?',
      id: 'Salam ini berasal dari bahasa negara mana?',
    }),
    options: [
      quizOpt(localeMap({
        ko: '중국',
        en: 'China',
        ja: '中国',
        'zh-CN': '中国',
        'zh-TW': '中國',
        vi: 'Trung Quốc',
        id: 'Tiongkok',
    }), false),
      quizOpt(localeMap({
        ko: '대만',
        en: 'Taiwan',
        ja: '台湾',
        'zh-CN': '台湾',
        'zh-TW': '台灣',
        vi: 'Đài Loan',
        id: 'Taiwan',
    }), false),
      quizOpt(localeMap({
        ko: '일본',
        en: 'Japan',
        ja: '日本',
        'zh-CN': '日本',
        'zh-TW': '日本',
        vi: 'Nhật Bản',
        id: 'Jepang',
    }), true),
      quizOpt(localeMap({
        ko: '베트남',
        en: 'Vietnam',
        ja: 'ベトナム',
        'zh-CN': '越南',
        'zh-TW': '越南',
        vi: 'Việt Nam',
        id: 'Vietnam',
    }), false),
    ],
    correctExplanation: localeMap({
      ko: '일본어 인사말 "こんにちは(곤니치와)"입니다. "今日は(오늘은)"에서 유래한 표현으로 낮 인사로 사용됩니다. 아침엔 "おはようございます(오하요우 고자이마스)", 밤엔 "こんばんは(곤반와)"를 씁니다. 한자를 쓰는 중국·대만과 달리 일본어는 히라가나·카타카나·한자를 혼합 사용하는 것이 특징입니다.',
      en: 'This is the Japanese greeting "こんにちは (Konnichiwa)." It comes from "今日は (today)" and is used as a daytime greeting. Morning uses "おはようございます (Ohayou gozaimasu)" and evening uses "こんばんは (Konbanwa)." Unlike Chinese-speaking regions that use kanji heavily, Japanese mixes hiragana, katakana, and kanji.',
      ja: '日本語の挨拶「こんにちは」です。「今日は」から派生した表現で、昼の挨拶として使います。朝は「おはようございます」、夜は「こんばんは」を使います。漢字を使う中国・台湾と異なり、日本語はひらがな・カタカナ・漢字を混ぜて使うのが特徴です。',
      'zh-CN': '这是日语问候语 "こんにちは（你好）"。源自 "今日は（今天）"，用作白天问候。早晨说 "おはようございます"，晚上说 "こんばんは"。与使用汉字的中港台不同，日语混合使用平假名、片假名和汉字。',
      'zh-TW': '這是日語問候語 "こんにちは（你好）"。源自 "今日は（今天）"，用作白天問候。早晨說 "おはようございます"，晚上說 "こんばんは"。與使用漢字的中港台不同，日語混合使用平假名、片假名和漢字。',
      vi: 'Đây là lời chào tiếng Nhật "こんにちは (Konnichiwa)." Xuất phát từ "今日は (hôm nay)" và dùng để chào ban ngày. Buổi sáng dùng "おはようございます", buổi tối dùng "こんばんは". Khác với vùng dùng chữ Hán, tiếng Nhật trộn hiragana, katakana và kanji.',
      id: 'Ini salam Jepang "こんにちは (Konnichiwa)." Berasal dari "今日は (hari ini)" dan dipakai sebagai salam siang. Pagi pakai "おはようございます", malam pakai "こんばんは". Berbeda dari wilayah berbahasa Tionghoa, Jepang mencampur hiragana, katakana, dan kanji.',
    }),
    wrongTraps: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
  },
  {
    id: 3,
    imageFile: 'p3_quiz_world_greeting_challenge_q3.webp',
    question: localeMap({
      ko: '이 인사말은 어느 나라의 언어인가요?',
      en: 'Which country\'s language is this greeting?',
      ja: 'この挨拶はどの国の言語ですか？',
      'zh-CN': '这个问候语是哪个国家的语言？',
      'zh-TW': '這個問候語是哪個國家的語言？',
      vi: 'Lời chào này là ngôn ngữ của nước nào?',
      id: 'Salam ini berasal dari bahasa negara mana?',
    }),
    options: [
      quizOpt(localeMap({
        ko: '스페인',
        en: 'Spain',
        ja: 'スペイン',
        'zh-CN': '西班牙',
        'zh-TW': '西班牙',
        vi: 'Tây Ban Nha',
        id: 'Spanyol',
    }), false),
      quizOpt(localeMap({
        ko: '프랑스',
        en: 'France',
        ja: 'フランス',
        'zh-CN': '法国',
        'zh-TW': '法國',
        vi: 'Pháp',
        id: 'Prancis',
    }), false),
      quizOpt(localeMap({
        ko: '그리스',
        en: 'Greece',
        ja: 'ギリシャ',
        'zh-CN': '希腊',
        'zh-TW': '希臘',
        vi: 'Hy Lạp',
        id: 'Yunani',
    }), false),
      quizOpt(localeMap({
        ko: '이탈리아',
        en: 'Italy',
        ja: 'イタリア',
        'zh-CN': '意大利',
        'zh-TW': '義大利',
        vi: 'Ý',
        id: 'Italia',
    }), true),
    ],
    correctExplanation: localeMap({
      ko: '이탈리아어 인사말 "Ciao(차오)"입니다. 만날 때와 헤어질 때 모두 사용하는 인사말로 "안녕"과 "잘 가" 두 가지 의미를 가집니다. 이탈리아어에서 유래했지만 현재는 유럽 여러 나라에서 비공식 인사말로 사용될 만큼 전 세계로 퍼진 단어입니다.',
      en: 'This is the Italian greeting "Ciao." It is used both when meeting and parting, meaning both "hello" and "goodbye." Though it originated in Italian, it has spread worldwide as an informal greeting across much of Europe.',
      ja: 'イタリア語の挨拶「Ciao（チャオ）」です。出会いと別れの両方で使う挨拶で、「こんにちは」と「さようなら」の二つの意味を持ちます。イタリア語由来ですが、現在はヨーロッパの多くの国で非公式な挨拶として世界中に広がった言葉です。',
      'zh-CN': '这是意大利语问候语 "Ciao"。见面和告别时都能用，兼具"你好"和"再见"两种含义。源自意大利语，如今已在欧洲多国作为非正式问候语传遍世界。',
      'zh-TW': '這是義大利語問候語 "Ciao"。見面和告別時都能用，兼具「你好」和「再見」兩種含義。源自義大利語，如今已在歐洲多國作為非正式問候語傳遍世界。',
      vi: 'Đây là lời chào tiếng Ý "Ciao." Dùng cả khi gặp và chia tay, mang nghĩa "xin chào" và "tạm biệt." Xuất phát từ tiếng Ý nhưng hiện lan rộng khắp châu Âu như lời chào thân mật.',
      id: 'Ini salam Italia "Ciao." Dipakai saat bertemu dan berpisah, berarti "halo" sekaligus "selamat tinggal." Berasal dari Italia, kini menyebar sebagai salam informal di banyak negara Eropa.',
    }),
    wrongTraps: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
  },
  {
    id: 4,
    imageFile: 'p3_quiz_world_greeting_challenge_q4.webp',
    question: localeMap({
      ko: '이 인사말은 어느 나라의 언어인가요?',
      en: 'Which country\'s language is this greeting?',
      ja: 'この挨拶はどの国の言語ですか？',
      'zh-CN': '这个问候语是哪个国家的语言？',
      'zh-TW': '這個問候語是哪個國家的語言？',
      vi: 'Lời chào này là ngôn ngữ của nước nào?',
      id: 'Salam ini berasal dari bahasa negara mana?',
    }),
    options: [
      quizOpt(localeMap({
        ko: '일본',
        en: 'Japan',
        ja: '日本',
        'zh-CN': '日本',
        'zh-TW': '日本',
        vi: 'Nhật Bản',
        id: 'Jepang',
    }), false),
      quizOpt(localeMap({
        ko: '한국',
        en: 'Korea',
        ja: '韓国',
        'zh-CN': '韩国',
        'zh-TW': '韓國',
        vi: 'Hàn Quốc',
        id: 'Korea',
    }), false),
      quizOpt(localeMap({
        ko: '베트남',
        en: 'Vietnam',
        ja: 'ベトナム',
        'zh-CN': '越南',
        'zh-TW': '越南',
        vi: 'Việt Nam',
        id: 'Vietnam',
    }), false),
      quizOpt(localeMap({
        ko: '중국',
        en: 'China',
        ja: '中国',
        'zh-CN': '中国',
        'zh-TW': '中國',
        vi: 'Trung Quốc',
        id: 'Tiongkok',
    }), true),
    ],
    correctExplanation: localeMap({
      ko: '중국어(보통화/만다린) 인사말 "你好(니하오)"입니다. "你(당신) + 好(좋다)"의 합성어로 세계에서 가장 많은 사람이 사용하는 언어의 인사말입니다. 더 공손하게는 "您好(닌하오)"를 사용합니다. 일본어 한자(漢字)와 형태가 비슷하지만 발음 체계가 완전히 다릅니다.',
      en: 'This is the Mandarin Chinese greeting "你好 (Nǐ hǎo)." It combines "你 (you) + 好 (good)" and is the greeting of the world\'s most widely spoken language. A more polite form is "您好 (Nín hǎo)." It looks similar to Japanese kanji but uses a completely different pronunciation system.',
      ja: '中国語（普通話/マンダリン）の挨拶「你好（ニーハオ）」です。「你（あなた）＋ 好（良い）」の合成語で、世界で最も多くの人が使う言語の挨拶です。より丁寧には「您好（ニンハオ）」を使います。日本語の漢字と形が似ていますが、発音体系はまったく異なります。',
      'zh-CN': '这是中文（普通话）问候语 "你好"。由 "你 + 好" 组成，是世界上使用人数最多的语言的问候语。更礼貌的说法是 "您好"。字形与日语汉字相似，但发音体系完全不同。',
      'zh-TW': '這是中文（普通話）問候語 "你好"。由 "你 + 好" 組成，是世界上使用人數最多的語言的問候語。更禮貌的說法是 "您好"。字形與日語漢字相似，但發音體系完全不同。',
      vi: 'Đây là lời chào tiếng Trung (Quan thoại) "你好 (Nǐ hǎo)." Ghép "你 (bạn) + 好 (tốt)" — lời chào của ngôn ngữ được dùng nhiều nhất thế giới. Cách lịch sự hơn là "您好 (Nín hǎo)." Hình dạng chữ giống kanji Nhật nhưng hệ thống phát âm hoàn toàn khác.',
      id: 'Ini salam Mandarin "你好 (Nǐ hǎo)." Gabungan "你 (kamu) + 好 (baik)" — salam bahasa yang paling banyak dipakai di dunia. Bentuk lebih sopan: "您好 (Nín hǎo)." Bentuk huruf mirip kanji Jepang tapi sistem pelafalan berbeda total.',
    }),
    wrongTraps: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
  },
  {
    id: 5,
    imageFile: 'p3_quiz_world_greeting_challenge_q5.webp',
    question: localeMap({
      ko: '이 인사말은 어느 나라(언어)의 인사말인가요?',
      en: 'Which country (language) is this greeting from?',
      ja: 'この挨拶はどの国（言語）の挨拶ですか？',
      'zh-CN': '这个问候语是哪个国家（语言）的问候？',
      'zh-TW': '這個問候語是哪個國家（語言）的問候？',
      vi: 'Lời chào này thuộc quốc gia (ngôn ngữ) nào?',
      id: 'Salam ini dari negara (bahasa) mana?',
    }),
    options: [
      quizOpt(localeMap({
        ko: '네팔',
        en: 'Nepal',
        ja: 'ネパール',
        'zh-CN': '尼泊尔',
        'zh-TW': '尼泊爾',
        vi: 'Nepal',
        id: 'Nepal',
    }), false),
      quizOpt(localeMap({
        ko: '태국',
        en: 'Thailand',
        ja: 'タイ',
        'zh-CN': '泰国',
        'zh-TW': '泰國',
        vi: 'Thái Lan',
        id: 'Thailand',
    }), false),
      quizOpt(localeMap({
        ko: '스리랑카',
        en: 'Sri Lanka',
        ja: 'スリランカ',
        'zh-CN': '斯里兰卡',
        'zh-TW': '斯里蘭卡',
        vi: 'Sri Lanka',
        id: 'Sri Lanka',
    }), false),
      quizOpt(localeMap({
        ko: '인도 (힌디어)',
        en: 'India (Hindi)',
        ja: 'インド（ヒンディー語）',
        'zh-CN': '印度（印地语）',
        'zh-TW': '印度（印地語）',
        vi: 'Ấn Độ (tiếng Hindi)',
        id: 'India (Hindi)',
    }), true),
    ],
    correctExplanation: localeMap({
      ko: '힌디어 인사말 "नमस्ते(나마스테)"입니다. 산스크리트어에서 유래한 단어로 "당신 안에 있는 신성함에 경의를 표합니다"라는 깊은 의미를 담고 있습니다. 두 손을 모아 합장하며 인사하는 것이 전통 방식입니다. 힌디어는 인도의 공용어 중 하나로 약 6억 명이 사용합니다. 네팔에서도 같은 인사말을 씁니다.',
      en: 'This is the Hindi greeting "नमस्ते (Namaste)." From Sanskrit, it means "I bow to the divine in you." The traditional way is to greet with palms pressed together. Hindi is one of India\'s official languages, spoken by about 600 million people. The same greeting is also used in Nepal.',
      ja: 'ヒンディー語の挨拶「नमस्ते（ナマステ）」です。サンスクリット語由来で「あなたの中の神聖さに敬意を表します」という深い意味を持ちます。両手を合わせて挨拶するのが伝統的な方法です。ヒンディー語はインドの公用語の一つで約6億人が使用します。ネパールでも同じ挨拶を使います。',
      'zh-CN': '这是印地语问候语 "नमस्ते（Namaste）"。源自梵语，意为"向你内在的神圣致敬"。传统方式是双手合十问候。印地语是印度官方语言之一，约6亿人使用。尼泊尔也使用同样的问候语。',
      'zh-TW': '這是印地語問候語 "नमस्ते（Namaste）"。源自梵語，意為「向你內在的神聖致敬」。傳統方式是雙手合十問候。印地語是印度官方語言之一，約6億人使用。尼泊爾也使用同樣的問候語。',
      vi: 'Đây là lời chào tiếng Hindi "नमस्ते (Namaste)." Từ Sanskrit, nghĩa là "tôi cúi chào thiêng liêng trong bạn." Cách truyền thống là chắp tay chào. Hindi là một trong các ngôn ngữ chính thức của Ấn Độ, khoảng 600 triệu người dùng. Nepal cũng dùng cùng lời chào này.',
      id: 'Ini salam Hindi "नमस्ते (Namaste)." Dari Sanskrit, berarti "saya menghormati keilahan dalam dirimu." Cara tradisional adalah salam dengan telapak tangan berpadu. Hindi adalah salah satu bahasa resmi India, dipakai sekitar 600 juta orang. Nepal juga memakai salam yang sama.',
    }),
    wrongTraps: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
  },
  {
    id: 6,
    imageFile: 'p3_quiz_world_greeting_challenge_q6.webp',
    question: localeMap({
      ko: '이 인사말은 어느 나라의 언어인가요?',
      en: 'Which country\'s language is this greeting?',
      ja: 'この挨拶はどの国の言語ですか？',
      'zh-CN': '这个问候语是哪个国家的语言？',
      'zh-TW': '這個問候語是哪個國家的語言？',
      vi: 'Lời chào này là ngôn ngữ của nước nào?',
      id: 'Salam ini berasal dari bahasa negara mana?',
    }),
    options: [
      quizOpt(localeMap({
        ko: '아랍에미리트',
        en: 'United Arab Emirates',
        ja: 'アラブ首長国連邦',
        'zh-CN': '阿联酋',
        'zh-TW': '阿聯酋',
        vi: 'Các Tiểu vương quốc Ả Rập Thống nhất',
        id: 'Uni Emirat Arab',
    }), false),
      quizOpt(localeMap({
        ko: '이란',
        en: 'Iran',
        ja: 'イラン',
        'zh-CN': '伊朗',
        'zh-TW': '伊朗',
        vi: 'Iran',
        id: 'Iran',
    }), false),
      quizOpt(localeMap({
        ko: '그리스',
        en: 'Greece',
        ja: 'ギリシャ',
        'zh-CN': '希腊',
        'zh-TW': '希臘',
        vi: 'Hy Lạp',
        id: 'Yunani',
    }), false),
      quizOpt(localeMap({
        ko: '터키',
        en: 'Turkey',
        ja: 'トルコ',
        'zh-CN': '土耳其',
        'zh-TW': '土耳其',
        vi: 'Thổ Nhĩ Kỳ',
        id: 'Turki',
    }), true),
    ],
    correctExplanation: localeMap({
      ko: '터키어 인사말 "Merhaba(메르하바)"입니다. 아랍어 "مرحبا(Marhaba)"에서 유래한 단어로 터키를 비롯해 중동·발칸 지역의 여러 언어에서도 비슷한 형태로 사용됩니다. 더 격식 있는 인사말로는 "Günaydın(귀나이든, 좋은 아침)"이 있습니다.',
      en: 'This is the Turkish greeting "Merhaba." It comes from Arabic "مرحبا (Marhaba)" and similar forms appear across the Middle East and Balkans. A more formal morning greeting is "Günaydın (good morning)."',
      ja: 'トルコ語の挨拶「Merhaba（メルハバ）」です。アラビア語「مرحبا（Marhaba）」に由来し、トルコをはじめ中東・バルカン地域の複数言語でも似た形で使われます。より格式ある朝の挨拶は「Günaydın（ギュナイディン、おはよう）」です。',
      'zh-CN': '这是土耳其语问候语 "Merhaba"。源自阿拉伯语 "مرحبا (Marhaba)"，土耳其及中东、巴尔干多种语言也有类似形式。更正式的早晨问候是 "Günaydın（早安）"。',
      'zh-TW': '這是土耳其語問候語 "Merhaba"。源自阿拉伯語 "مرحبا (Marhaba)"，土耳其及中東、巴爾幹多種語言也有類似形式。更正式的早晨問候是 "Günaydın（早安）"。',
      vi: 'Đây là lời chào tiếng Thổ Nhĩ Kỳ "Merhaba." Xuất phát từ tiếng Ả Rập "مرحبا (Marhaba)" và hình thức tương tự xuất hiện ở Trung Đông và Balkan. Lời chào buổi sáng trang trọng hơn là "Günaydın (chào buổi sáng)."',
      id: 'Ini salam Turki "Merhaba." Berasal dari Arab "مرحبا (Marhaba)" dan bentuk serupa dipakai di Timur Tengah dan Balkan. Salam pagi lebih formal: "Günaydın (selamat pagi)."',
    }),
    wrongTraps: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
  },
  {
    id: 7,
    imageFile: 'p3_quiz_world_greeting_challenge_q7.webp',
    question: localeMap({
      ko: '이 인사말은 어느 나라의 언어인가요?',
      en: 'Which country\'s language is this greeting?',
      ja: 'この挨拶はどの国の言語ですか？',
      'zh-CN': '这个问候语是哪个国家的语言？',
      'zh-TW': '這個問候語是哪個國家的語言？',
      vi: 'Lời chào này là ngôn ngữ của nước nào?',
      id: 'Salam ini berasal dari bahasa negara mana?',
    }),
    options: [
      quizOpt(localeMap({
        ko: '아랍에미리트',
        en: 'United Arab Emirates',
        ja: 'アラブ首長国連邦',
        'zh-CN': '阿联酋',
        'zh-TW': '阿聯酋',
        vi: 'Các Tiểu vương quốc Ả Rập Thống nhất',
        id: 'Uni Emirat Arab',
    }), false),
      quizOpt(localeMap({
        ko: '요르단',
        en: 'Jordan',
        ja: 'ヨルダン',
        'zh-CN': '约旦',
        'zh-TW': '約旦',
        vi: 'Jordan',
        id: 'Yordania',
    }), false),
      quizOpt(localeMap({
        ko: '레바논',
        en: 'Lebanon',
        ja: 'レバノン',
        'zh-CN': '黎巴嫩',
        'zh-TW': '黎巴嫩',
        vi: 'Liban',
        id: 'Lebanon',
    }), false),
      quizOpt(localeMap({
        ko: '이스라엘 (히브리어)',
        en: 'Israel (Hebrew)',
        ja: 'イスラエル（ヘブライ語）',
        'zh-CN': '以色列（希伯来语）',
        'zh-TW': '以色列（希伯來語）',
        vi: 'Israel (tiếng Hebrew)',
        id: 'Israel (Ibrani)',
    }), true),
    ],
    correctExplanation: localeMap({
      ko: '히브리어 인사말 "שָׁלוֹם(샬롬)"입니다. "평화"를 의미하는 단어로 만날 때와 헤어질 때 모두 사용합니다. 히브리어는 약 2,000년간 사용되지 않다가 19세기 말 이스라엘 건국 운동과 함께 부활한 세계 유일의 \'되살아난 언어\'입니다. 아랍어 인사말 "السَّلَامُ عَلَيْكُمْ(앗살라무 알라이쿰)"도 같은 어원의 "살람(السلام)"에서 유래했습니다.',
      en: 'This is the Hebrew greeting "שָׁלוֹם (Shalom)," meaning "peace," used both when meeting and parting. Hebrew went unused for about 2,000 years before being revived in the late 19th century with the Zionist movement—it is the world\'s only "revived language." Arabic "السَّلَامُ عَلَيْكُمْ (As-salamu alaykum)" shares the same root "salam (السلام)."',
      ja: 'ヘブライ語の挨拶「שָׁלוֹם（シャローム）」です。「平和」を意味し、出会いと別れの両方で使います。約2,000年間使われなかったヘブライ語は19世紀末のシオニズム運動とともに復活した世界唯一の「蘇生言語」です。アラビア語の「السَّلَامُ عَلَيْكُمْ（アッサラーム・アライクム）」も同じ語源の「salam（السلام）」に由来します。',
      'zh-CN': '这是希伯来语问候语 "שָׁלוֹם（Shalom）"，意为"和平"，见面和告别时都能用。希伯来语曾停用约2000年，19世纪末随犹太复国运动复活，是世界上唯一的"复活语言"。阿拉伯语 "السَّلَامُ عَلَيْكُمْ" 也源自同一词根 "salam（السلام）"。',
      'zh-TW': '這是希伯來語問候語 "שָׁלוֹם（Shalom）"，意為「和平」，見面和告別時都能用。希伯來語曾停用約2000年，19世紀末隨猶太復國運動復活，是世界上唯一的「復活語言」。阿拉伯語 "السَّلَامُ عَلَيْكُمْ" 也源自同一詞根 "salam（السلام）"。',
      vi: 'Đây là lời chào tiếng Hebrew "שָׁלוֹם (Shalom)" nghĩa là "bình an," dùng cả khi gặp và chia tay. Hebrew không dùng khoảng 2.000 năm rồi được hồi sinh cuối thế kỷ 19 — ngôn ngữ "hồi sinh" duy nhất trên thế giới. Tiếng Ả Rập "السَّلَامُ عَلَيْكُمْ" cùng gốc "salam (السلام)."',
      id: 'Ini salam Ibrani "שָׁלוֹם (Shalom)" berarti "damai," dipakai saat bertemu dan berpisah. Ibrani tidak dipakai sekitar 2.000 tahun lalu hidup kembali akhir abad ke-19 — satu-satunya "bahasa yang bangkit." Arab "السَّلَامُ عَلَيْكُمْ" berakar sama "salam (السلام)."',
    }),
    wrongTraps: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
  },
  {
    id: 8,
    imageFile: 'p3_quiz_world_greeting_challenge_q8.webp',
    question: localeMap({
      ko: '이 인사말은 어느 나라의 언어인가요?',
      en: 'Which country\'s language is this greeting?',
      ja: 'この挨拶はどの国の言語ですか？',
      'zh-CN': '这个问候语是哪个国家的语言？',
      'zh-TW': '這個問候語是哪個國家的語言？',
      vi: 'Lời chào này là ngôn ngữ của nước nào?',
      id: 'Salam ini berasal dari bahasa negara mana?',
    }),
    options: [
      quizOpt(localeMap({
        ko: '우크라이나',
        en: 'Ukraine',
        ja: 'ウクライナ',
        'zh-CN': '乌克兰',
        'zh-TW': '烏克蘭',
        vi: 'Ukraina',
        id: 'Ukraina',
    }), false),
      quizOpt(localeMap({
        ko: '불가리아',
        en: 'Bulgaria',
        ja: 'ブルガリア',
        'zh-CN': '保加利亚',
        'zh-TW': '保加利亞',
        vi: 'Bulgaria',
        id: 'Bulgaria',
    }), false),
      quizOpt(localeMap({
        ko: '세르비아',
        en: 'Serbia',
        ja: 'セルビア',
        'zh-CN': '塞尔维亚',
        'zh-TW': '塞爾維亞',
        vi: 'Serbia',
        id: 'Serbia',
    }), false),
      quizOpt(localeMap({
        ko: '러시아',
        en: 'Russia',
        ja: 'ロシア',
        'zh-CN': '俄罗斯',
        'zh-TW': '俄羅斯',
        vi: 'Nga',
        id: 'Rusia',
    }), true),
    ],
    correctExplanation: localeMap({
      ko: '러시아어 비격식 인사말 "Привет(프리빗)"입니다. 친한 사이에 쓰는 "안녕/하이"에 해당하는 말로 격식 있는 인사말은 "Здравствуйте(즈드라스트부이쩨)"입니다. 러시아어는 키릴 문자를 사용하며 약 2억 6천만 명이 모국어 또는 제2언어로 사용합니다. 우크라이나·불가리아·세르비아 등도 키릴 문자를 쓰지만 각각 다른 언어입니다.',
      en: 'This is the informal Russian greeting "Привет (Privet)," like "hi" among friends. The formal form is "Здравствуйте (Zdravstvuyte)." Russian uses the Cyrillic alphabet and is spoken by about 260 million people as a first or second language. Ukraine, Bulgaria, and Serbia also use Cyrillic but speak different languages.',
      ja: 'ロシア語の非公式な挨拶「Привет（プリヴェット）」です。親しい間柄で使う「こんにちは/ハイ」に相当し、格式ある挨拶は「Здравствуйте（ズドラーストヴイチェ）」です。ロシア語はキリル文字を使い、約2億6千万人が母語または第二言語として使用します。ウクライナ・ブルガリア・セルビアもキリル文字を使いますが、それぞれ異なる言語です。',
      'zh-CN': '这是俄语非正式问候 "Привет（你好）"，相当于朋友间的"嗨"。正式说法是 "Здравствуйте"。俄语使用西里尔字母，约2.6亿人作为母语或第二语言使用。乌克兰、保加利亚、塞尔维亚也用西里尔字母，但是不同语言。',
      'zh-TW': '這是俄語非正式問候 "Привет（你好）"，相當於朋友間的「嗨」。正式說法是 "Здравствуйте"。俄語使用西里爾字母，約2.6億人作為母語或第二語言使用。烏克蘭、保加利亞、塞爾維亞也用西里爾字母，但是不同語言。',
      vi: 'Đây là lời chào thân mật tiếng Nga "Привет (Privet)" như "hi" giữa bạn bè. Cách trang trọng là "Здравствуйте (Zdravstvuyte)." Tiếng Nga dùng chữ Cyrillic, khoảng 260 triệu người dùng làm tiếng mẹ đẻ hoặc thứ hai. Ukraine, Bulgaria, Serbia cũng dùng Cyrillic nhưng là ngôn ngữ khác.',
      id: 'Ini salam informal Rusia "Привет (Privet)" seperti "hi" antar teman. Bentuk formal: "Здравствуйте (Zdravstvuyte)." Rusia memakai alfabet Cyrillic, dipakai sekitar 260 juta orang sebagai bahasa pertama atau kedua. Ukraina, Bulgaria, Serbia juga pakai Cyrillic tapi bahasa berbeda.',
    }),
    wrongTraps: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
  },
  {
    id: 9,
    imageFile: 'p3_quiz_world_greeting_challenge_q9.webp',
    question: localeMap({
      ko: '이 인사말은 어느 나라(언어)에서 사용하나요?',
      en: 'In which country (language) is this greeting used?',
      ja: 'この挨拶はどの国（言語）で使われますか？',
      'zh-CN': '这个问候语在哪个国家（语言）使用？',
      'zh-TW': '這個問候語在哪個國家（語言）使用？',
      vi: 'Lời chào này được dùng ở quốc gia (ngôn ngữ) nào?',
      id: 'Salam ini digunakan di negara (bahasa) mana?',
    }),
    options: [
      quizOpt(localeMap({
        ko: '나이지리아',
        en: 'Nigeria',
        ja: 'ナイジェリア',
        'zh-CN': '尼日利亚',
        'zh-TW': '奈及利亞',
        vi: 'Nigeria',
        id: 'Nigeria',
    }), false),
      quizOpt(localeMap({
        ko: '에티오피아',
        en: 'Ethiopia',
        ja: 'エチオピア',
        'zh-CN': '埃塞俄比亚',
        'zh-TW': '衣索比亞',
        vi: 'Ethiopia',
        id: 'Ethiopia',
    }), false),
      quizOpt(localeMap({
        ko: '가나',
        en: 'Ghana',
        ja: 'ガーナ',
        'zh-CN': '加纳',
        'zh-TW': '加納',
        vi: 'Ghana',
        id: 'Ghana',
    }), false),
      quizOpt(localeMap({
        ko: '케냐·탄자니아 (스와힐리어)',
        en: 'Kenya · Tanzania (Swahili)',
        ja: 'ケニア・タンザニア（スワヒリ語）',
        'zh-CN': '肯尼亚·坦桑尼亚（斯瓦希里语）',
        'zh-TW': '肯亞·坦尚尼亞（斯瓦希里語）',
        vi: 'Kenya · Tanzania (tiếng Swahili)',
        id: 'Kenya · Tanzania (Swahili)',
    }), true),
    ],
    correctExplanation: localeMap({
      ko: '스와힐리어 인사말 "Jambo(잠보)"입니다. 스와힐리어는 아프리카 동부 지역에서 약 2억 명이 사용하는 언어로 케냐·탄자니아·우간다·르완다 등의 공용어입니다. "Jambo"는 주로 외국인에게 친근하게 인사할 때 사용하며 현지인끼리는 "Habari(하바리, 어떻게 지내세요?)"를 더 많이 씁니다. 스와힐리어의 "Hakuna Matata(하쿠나 마타타)"는 "아무 문제 없어"라는 뜻으로도 유명합니다.',
      en: 'This is the Swahili greeting "Jambo." Swahili is used by about 200 million people in East Africa and is an official language in Kenya, Tanzania, Uganda, Rwanda, and more. "Jambo" is often used to greet foreigners warmly; locals more often say "Habari (how are you?)." The famous "Hakuna Matata" means "no worries."',
      ja: 'スワヒリ語の挨拶「Jambo（ジャンボ）」です。スワヒリ語はアフリカ東部で約2億人が使う言語で、ケニア・タンザニア・ウガンダ・ルワンダなどの公用語です。「Jambo」は主に外国人に親しみを込めて使い、現地人同士は「Habari（ハバリ、お元気ですか？）」をより多く使います。有名な「Hakuna Matata（ハクナ・マタタ）」は「問題ない」という意味です。',
      'zh-CN': '这是斯瓦希里语问候 "Jambo"。斯瓦希里语在非洲东部约2亿人使用，是肯尼亚、坦桑尼亚、乌干达、卢旺达等国的官方语言。"Jambo" 常用来热情问候外国人；当地人之间更常说 "Habari（你好吗？）"。著名的 "Hakuna Matata" 意为"没问题"。',
      'zh-TW': '這是斯瓦希里語問候 "Jambo"。斯瓦希里語在非洲東部約2億人使用，是肯亞、坦尚尼亞、烏干達、盧安達等國的官方語言。"Jambo" 常用來熱情問候外國人；當地人之間更常說 "Habari（你好嗎？）"。著名的 "Hakuna Matata" 意為「沒問題」。',
      vi: 'Đây là lời chào tiếng Swahili "Jambo." Swahili được khoảng 200 triệu người ở Đông Phi dùng, là ngôn ngữ chính thức ở Kenya, Tanzania, Uganda, Rwanda... "Jambo" thường chào du khách thân thiện; người địa phương hay nói "Habari (bạn khỏe không?)." "Hakuna Matata" nổi tiếng nghĩa là "không lo gì."',
      id: 'Ini salam Swahili "Jambo." Swahili dipakai sekitar 200 juta orang di Afrika Timur, bahasa resmi Kenya, Tanzania, Uganda, Rwanda, dll. "Jambo" sering dipakai menyapa turis; penduduk lokal lebih sering bilang "Habari (apa kabar?)." "Hakuna Matata" terkenal berarti "tidak masalah."',
    }),
    wrongTraps: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
  },
  {
    id: 10,
    imageFile: 'p3_quiz_world_greeting_challenge_q10.webp',
    question: localeMap({
      ko: '이 인사말은 어느 나라의 언어인가요?',
      en: 'Which country\'s language is this greeting?',
      ja: 'この挨拶はどの国の言語ですか？',
      'zh-CN': '这个问候语是哪个国家的语言？',
      'zh-TW': '這個問候語是哪個國家的語言？',
      vi: 'Lời chào này là ngôn ngữ của nước nào?',
      id: 'Salam ini berasal dari bahasa negara mana?',
    }),
    options: [
      quizOpt(localeMap({
        ko: '태국',
        en: 'Thailand',
        ja: 'タイ',
        'zh-CN': '泰国',
        'zh-TW': '泰國',
        vi: 'Thái Lan',
        id: 'Thailand',
    }), false),
      quizOpt(localeMap({
        ko: '캄보디아',
        en: 'Cambodia',
        ja: 'カンボジア',
        'zh-CN': '柬埔寨',
        'zh-TW': '柬埔寨',
        vi: 'Campuchia',
        id: 'Kamboja',
    }), false),
      quizOpt(localeMap({
        ko: '미얀마',
        en: 'Myanmar',
        ja: 'ミャンマー',
        'zh-CN': '缅甸',
        'zh-TW': '緬甸',
        vi: 'Myanmar',
        id: 'Myanmar',
    }), false),
      quizOpt(localeMap({
        ko: '베트남',
        en: 'Vietnam',
        ja: 'ベトナム',
        'zh-CN': '越南',
        'zh-TW': '越南',
        vi: 'Việt Nam',
        id: 'Vietnam',
    }), true),
    ],
    correctExplanation: localeMap({
      ko: '베트남어 인사말 "Xin chào(신짜오)"입니다. "Xin(정중히) + chào(인사하다)"의 합성어로 베트남어는 성조 언어로 같은 글자라도 성조에 따라 뜻이 완전히 달라집니다. 현재 베트남어는 라틴 문자를 변형한 꾸옥응으(Quốc ngữ)를 사용하는데 이는 17세기 프랑스 선교사들이 베트남어를 로마자로 표기하면서 정착된 것입니다.',
      en: 'This is the Vietnamese greeting "Xin chào." It combines "Xin (politely) + chào (to greet)." Vietnamese is a tonal language where the same spelling can mean entirely different things depending on tone. Today it uses the Latin-based Quốc ngữ script, standardized in the 17th century when French missionaries romanized Vietnamese.',
      ja: 'ベトナム語の挨拶「Xin chào（シンチャオ）」です。「Xin（丁寧に）＋ chào（挨拶する）」の合成語です。ベトナム語は声調言語で、同じ文字でも声調によって意味がまったく変わります。現在はラテン文字を変形したクォック・グー（Quốc ngữ）を使い、17世紀にフランスの宣教師がローマ字表記を定着させました。',
      'zh-CN': '这是越南语问候 "Xin chào（你好）"。由 "Xin（敬语）+ chào（问候）" 组成。越南语是声调语言，同一拼写因声调不同意思完全不同。如今使用拉丁化的国语（Quốc ngữ），17世纪法国传教士将其罗马化后定型。',
      'zh-TW': '這是越南語問候 "Xin chào（你好）"。由 "Xin（敬語）+ chào（問候）" 組成。越南語是聲調語言，同一拼寫因聲調不同意思完全不同。如今使用拉丁化的國語（Quốc ngữ），17世紀法國傳教士將其羅馬化後定型。',
      vi: 'Đây là lời chào tiếng Việt "Xin chào." Ghép "Xin (lịch sự) + chào (chào hỏi)." Tiếng Việt là ngôn ngữ thanh điệu — cùng chữ viết nhưng khác thanh là khác nghĩa hoàn toàn. Hiện dùng chữ Quốc ngữ theo Latin, được các giáo sĩ Pháp thế kỷ 17 chuẩn hóa.',
      id: 'Ini salam Vietnam "Xin chào." Gabungan "Xin (dengan sopan) + chào (menyapa)." Vietnam adalah bahasa nada — ejaan sama bisa artinya beda total. Kini memakai aksara Quốc ngữ berbasis Latin, distandardisasi abad ke-17 oleh misionaris Prancis.',
    }),
    wrongTraps: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
  },
  {
    id: 11,
    imageFile: 'p3_quiz_world_greeting_challenge_q11.webp',
    question: localeMap({
      ko: '이 인사말은 어느 나라의 언어에서 사용하나요?',
      en: 'In which country\'s language is this greeting used?',
      ja: 'この挨拶はどの国の言語で使われますか？',
      'zh-CN': '这个问候语在哪个国家的语言中使用？',
      'zh-TW': '這個問候語在哪個國家的語言中使用？',
      vi: 'Lời chào này được dùng trong ngôn ngữ của nước nào?',
      id: 'Salam ini digunakan dalam bahasa negara mana?',
    }),
    options: [
      quizOpt(localeMap({
        ko: '나이지리아 (요루바어)',
        en: 'Nigeria (Yoruba)',
        ja: 'ナイジェリア（ヨルバ語）',
        'zh-CN': '尼日利亚（约鲁巴语）',
        'zh-TW': '奈及利亞（約魯巴語）',
        vi: 'Nigeria (tiếng Yoruba)',
        id: 'Nigeria (Yoruba)',
    }), false),
      quizOpt(localeMap({
        ko: '에티오피아 (암하라어)',
        en: 'Ethiopia (Amharic)',
        ja: 'エチオピア（アムハラ語）',
        'zh-CN': '埃塞俄比亚（阿姆哈拉语）',
        'zh-TW': '衣索比亞（阿姆哈拉語）',
        vi: 'Ethiopia (tiếng Amharic)',
        id: 'Ethiopia (Amharic)',
    }), false),
      quizOpt(localeMap({
        ko: '이집트 (아랍어)',
        en: 'Egypt (Arabic)',
        ja: 'エジプト（アラビア語）',
        'zh-CN': '埃及（阿拉伯语）',
        'zh-TW': '埃及（阿拉伯語）',
        vi: 'Ai Cập (tiếng Ả Rập)',
        id: 'Mesir (Arab)',
    }), false),
      quizOpt(localeMap({
        ko: '남아프리카공화국 (줄루어)',
        en: 'South Africa (Zulu)',
        ja: '南アフリカ（ズールー語）',
        'zh-CN': '南非（祖鲁语）',
        'zh-TW': '南非（祖魯語）',
        vi: 'Nam Phi (tiếng Zulu)',
        id: 'Afrika Selatan (Zulu)',
    }), true),
    ],
    correctExplanation: localeMap({
      ko: '줄루어 인사말 "Sawubona(사우보나)"입니다. 직역하면 "나는 당신을 봅니다(I see you)"라는 의미로 단순한 인사를 넘어 "당신의 존재를 인정하고 존중합니다"라는 깊은 뜻을 담고 있습니다. 영화 아바타의 "I see you"가 이 인사말에서 영감을 받은 것으로 알려져 있습니다. 줄루어는 남아프리카공화국에서 약 1,200만 명이 사용하며 11개 공용어 중 하나입니다.',
      en: 'This is the Zulu greeting "Sawubona," literally meaning "I see you"—more than a hello, it acknowledges and respects your presence. Avatar\'s "I see you" is said to be inspired by this greeting. Zulu is spoken by about 12 million people in South Africa and is one of 11 official languages.',
      ja: 'ズールー語の挨拶「Sawubona（サウボナ）」です。直訳すると「私はあなたを見ています（I see you）」で、単なる挨拶を超え「あなたの存在を認め尊重します」という深い意味を持ちます。映画アバターの「I see you」はこの挨拶に触発されたと言われています。ズールー語は南アフリカで約1,200万人が使う11の公用語の一つです。',
      'zh-CN': '这是祖鲁语问候 "Sawubona"，字面意为"我看见你（I see you）"——不仅是打招呼，更表示"承认并尊重你的存在"。电影《阿凡达》的 "I see you" 据说受此启发。祖鲁语在南非约1200万人使用，是11种官方语言之一。',
      'zh-TW': '這是祖魯語問候 "Sawubona"，字面意為「我看見你（I see you）」——不僅是打招呼，更表示「承認並尊重你的存在」。電影《阿凡達》的 "I see you" 據說受此啟發。祖魯語在南非約1200萬人使用，是11種官方語言之一。',
      vi: 'Đây là lời chào tiếng Zulu "Sawubona," nghĩa đen là "Tôi thấy bạn (I see you)" — không chỉ chào mà còn thừa nhận và tôn trọng sự hiện diện của bạn. "I see you" trong phim Avatar được cho là lấy cảm hứng từ đây. Zulu được khoảng 12 triệu người ở Nam Phi dùng, một trong 11 ngôn ngữ chính thức.',
      id: 'Ini salam Zulu "Sawubona," harfiahnya "Saya melihatmu (I see you)" — lebih dari sekadar halo, mengakui dan menghormati kehadiranmu. "I see you" di film Avatar dikatakan terinspirasi salam ini. Zulu dipakai sekitar 12 juta orang di Afrika Selatan, salah satu dari 11 bahasa resmi.',
    }),
    wrongTraps: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
  },
  {
    id: 12,
    imageFile: 'p3_quiz_world_greeting_challenge_q12.webp',
    question: localeMap({
      ko: '이 인사말은 어느 나라의 언어인가요?',
      en: 'Which country\'s language is this greeting?',
      ja: 'この挨拶はどの国の言語ですか？',
      'zh-CN': '这个问候语是哪个国家的语言？',
      'zh-TW': '這個問候語是哪個國家的語言？',
      vi: 'Lời chào này là ngôn ngữ của nước nào?',
      id: 'Salam ini berasal dari bahasa negara mana?',
    }),
    options: [
      quizOpt(localeMap({
        ko: '피지',
        en: 'Fiji',
        ja: 'フィジー',
        'zh-CN': '斐济',
        'zh-TW': '斐濟',
        vi: 'Fiji',
        id: 'Fiji',
    }), false),
      quizOpt(localeMap({
        ko: '통가',
        en: 'Tonga',
        ja: 'トンガ',
        'zh-CN': '汤加',
        'zh-TW': '東加',
        vi: 'Tonga',
        id: 'Tonga',
    }), false),
      quizOpt(localeMap({
        ko: '하와이 (미국)',
        en: 'Hawaii (USA)',
        ja: 'ハワイ（米国）',
        'zh-CN': '夏威夷（美国）',
        'zh-TW': '夏威夷（美國）',
        vi: 'Hawaii (Mỹ)',
        id: 'Hawaii (AS)',
    }), false),
      quizOpt(localeMap({
        ko: '사모아',
        en: 'Samoa',
        ja: 'サモア',
        'zh-CN': '萨摩亚',
        'zh-TW': '薩摩亞',
        vi: 'Samoa',
        id: 'Samoa',
    }), true),
    ],
    correctExplanation: localeMap({
      ko: '사모아어 인사말 "Talofa(탈로파)"입니다. "Talo(사랑) + fa(줍니다)"의 합성어로 "사랑을 드립니다"라는 아름다운 의미를 담고 있습니다. 사모아는 남태평양의 섬나라로 인구 약 22만 명이 살며 사모아어와 영어를 공용어로 사용합니다. 비슷한 폴리네시아어 계통의 하와이어 인사말 "Aloha"와 헷갈리기 쉽지만 다른 언어입니다. 여기까지 맞히셨다면 진정한 세계 언어 마스터입니다.',
      en: 'This is the Samoan greeting "Talofa," combining "Talo (love) + fa (to give)" meaning "I give you love." Samoa is a South Pacific island nation of about 220,000 people where Samoan and English are official languages. It is easily confused with Polynesian cousin "Aloha" from Hawaiian, but they are different languages. If you got this far, you are a true world language master.',
      ja: 'サモア語の挨拶「Talofa（タロファ）」です。「Talo（愛）＋ fa（与える）」の合成語で「愛を差し上げます」という美しい意味を持ちます。サモアは南太平洋の島国で人口約22万人、サモア語と英語が公用語です。ポリネシア語系のハワイ語「Aloha」と混同しやすいですが別の言語です。ここまで当てたなら真の世界言語マスターです。',
      'zh-CN': '这是萨摩亚语问候 "Talofa"，由 "Talo（爱）+ fa（给予）" 组成，意为"我把爱送给你"。萨摩亚是南太平洋岛国，人口约22万，萨摩亚语和英语为官方语言。容易与波利尼西亚语系的夏威夷语 "Aloha" 混淆，但是不同语言。连这题都对，你就是真正的世界语言大师。',
      'zh-TW': '這是薩摩亞語問候 "Talofa"，由 "Talo（愛）+ fa（給予）" 組成，意為「我把愛送給你」。薩摩亞是南太平洋島國，人口約22萬，薩摩亞語和英語為官方語言。容易與波利尼西亞語系的夏威夷語 "Aloha" 混淆，但是不同語言。連這題都對，你就是真正的世界語言大師。',
      vi: 'Đây là lời chào tiếng Samoa "Talofa," ghép "Talo (yêu thương) + fa (trao tặng)" nghĩa là "Tôi trao tình yêu cho bạn." Samoa là quốc đảo Nam Thái Bình Dương, khoảng 220.000 dân, Samoa và tiếng Anh là ngôn ngữ chính thức. Dễ nhầm với "Aloha" của Hawaii cùng hệ Polynesia nhưng là ngôn ngữ khác. Đúng đến đây là bậc thầy ngôn ngữ thế giới thật sự.',
      id: 'Ini salam Samoa "Talofa," gabungan "Talo (cinta) + fa (memberi)" berarti "Saya memberimu cinta." Samoa adalah negara kepulauan Pasifik Selatan, sekitar 220 ribu penduduk, Samoa dan Inggris bahasa resmi. Sering tertukar dengan "Aloha" Hawaii dalam rumpun Polynesia, tapi bahasa berbeda. Benar sampai sini berarti kamu master bahasa dunia sejati.',
    }),
    wrongTraps: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
  },
];

export const phase3WorldGreetingChallengeResults: Phase3WorldGreetingChallengeResult[] = [
  {
    type: 'Level1',
    emoji: '🌱',
    title: localeMap({
      ko: '오늘 세계를 처음 만난 날, 언어 탐험 새싹 🌱',
      en: 'First day meeting the world—Language Explorer Sprout 🌱',
      ja: '今日世界と初めて出会った日、言語探検の新芽 🌱',
      'zh-CN': '今天初次遇见世界，语言探险新芽 🌱',
      'zh-TW': '今天初次遇見世界，語言探險新芽 🌱',
      vi: 'Hôm nay lần đầu gặp thế giới—Mầm thám hiểm ngôn ngữ 🌱',
      id: 'Hari pertama bertemu dunia—Benih penjelajah bahasa 🌱',
    }),
    shortDescription: localeMap({
      ko: '12개 중 2개 이하를 맞혔습니다. 쉬운 구간에서도 많이 막혔군요. 사실 당연합니다. 세계 언어는 7,000개가 넘으니까요.',
      en: 'You got 2 or fewer correct and struggled even in the easy section. That is completely normal—there are more than 7,000 languages in the world.',
      ja: '12問中2問以下正解。簡単な区間でも多くつまずきましたね。当然です。世界の言語は7,000以上あります。',
      'zh-CN': '12题中答对2题及以下，简单题也卡了不少。这很正常——世界语言超过7000种。',
      'zh-TW': '12題中答對2題及以下，簡單題也卡了不少。這很正常——世界語言超過7000種。',
      vi: 'Đúng 2 câu trở xuống, phần dễ cũng vấp nhiều. Hoàn toàn bình thường — thế giới có hơn 7.000 ngôn ngữ.',
      id: 'Benar 2 atau kurang, mentok di bagian mudah. Wajar — ada lebih dari 7.000 bahasa di dunia.',
    }),
    description: localeMap({
      ko: '오늘 이 테스트로 "Sawubona"가 I see you라는 뜻이고 "Talofa"가 사랑을 드립니다는 뜻이라는 걸 처음 알게 됐을 것입니다. 그것만으로도 충분합니다.',
      en: 'Through this test you probably learned for the first time that "Sawubona" means I see you and "Talofa" means I give you love. That alone is enough.',
      ja: 'このテストで「Sawubona」がI see you、「Talofa」が愛を差し上げますという意味だと初めて知ったはずです。それだけで十分です。',
      'zh-CN': '通过这次测试，你可能第一次知道 "Sawubona" 意为 I see you，"Talofa" 意为我把爱送给你。这就够了。',
      'zh-TW': '透過這次測試，你可能第一次知道 "Sawubona" 意為 I see you，"Talofa" 意為我把愛送給你。這就夠了。',
      vi: 'Qua bài test này bạn có lẽ lần đầu biết "Sawubona" nghĩa là I see you và "Talofa" nghĩa là tôi trao tình yêu. Chỉ vậy thôi cũng đủ rồi.',
      id: 'Lewat tes ini kamu mungkin baru tahu "Sawubona" berarti I see you dan "Talofa" berarti aku memberimu cinta. Itu saja sudah cukup.',
    }),
    languageGrade: localeMap({
      ko: '언어 고수 등급: Lv.1 탐험 새싹 🌱',
      en: 'Language Master Grade: Lv.1 Explorer Sprout 🌱',
      ja: '言語マスター等級: Lv.1 探検新芽 🌱',
      'zh-CN': '语言高手等级：Lv.1 探险新芽 🌱',
      'zh-TW': '語言高手等級：Lv.1 探險新芽 🌱',
      vi: 'Cấp cao thủ ngôn ngữ: Lv.1 Mầm thám hiểm 🌱',
      id: 'Grade master bahasa: Lv.1 Benih penjelajah 🌱',
    }),
    scoreRange: localeMap({
      ko: '정답 수: 0~2개',
      en: 'Correct answers: 0~2',
      ja: '正解数: 0~2問',
      'zh-CN': '答对数：0~2题',
      'zh-TW': '答對數：0~2題',
      vi: 'Số câu đúng: 0~2',
      id: 'Jawaban benar: 0~2',
    }),
    strengthZone: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    weakZone: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    retakeTip: localeMap({
      ko: '재도전 팁: 오늘 틀린 인사말 해설을 다시 읽고 각 나라 위치를 지도에서 확인하기',
      en: 'Retake tip: Re-read explanations for today\'s wrong greetings and find each country on a map',
      ja: '再挑戦のコツ: 今日間違えた挨拶の解説を読み直し、各国の位置を地図で確認する',
      'zh-CN': '重试提示：重读今天错题的解析，在地图上确认各国位置',
      'zh-TW': '重試提示：重讀今天錯題的解析，在地圖上確認各國位置',
      vi: 'Mẹo thử lại: Đọc lại giải thích các lời chào sai hôm nay và xem vị trí từng nước trên bản đồ',
      id: 'Tips ulang: Baca ulang penjelasan salam yang salah hari ini dan cek lokasi tiap negara di peta',
    }),
    characteristic: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    regretPoint: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '세계에는 아직 당신이 모르는 인사말이 7,000개 더 있습니다. 오늘 12개를 배웠습니다',
      en: 'There are 7,000 more greetings in the world you do not know yet. Today you learned 12',
      ja: '世界にはまだあなたが知らない挨拶が7,000個以上あります。今日12個を学びました',
      'zh-CN': '世界上还有7000多种你没听过的问候语。今天学了12个',
      'zh-TW': '世界上還有7000多種你沒聽過的問候語。今天學了12個',
      vi: 'Trên thế giới còn hơn 7.000 lời chào bạn chưa biết. Hôm nay bạn học được 12 cái',
      id: 'Di dunia masih ada 7.000 salam lagi yang belum kamu tahu. Hari ini kamu belajar 12',
    }),
    shareLine: localeMap({
      ko: '세계 인사말 퀴즈: Lv.1 새싹 🌱 Sawubona가 \'나는 당신을 봅니다\'라는 뜻인 거 오늘 처음 알았음... 세계에 이런 인사말이 있었구나 → 이 인사말 어느 나라 말인지 알아?',
      en: 'World Greeting Quiz: Lv.1 Sprout 🌱 Just learned today Sawubona means \'I see you\'... there are greetings like this in the world → Do you know which country this greeting is from?',
      ja: '世界の挨拶クイズ: Lv.1 新芽 🌱 Sawubonaが「I see you」の意味だと今日初めて知った…世界にこんな挨拶が → この挨拶どの国の言葉か分かる？',
      'zh-CN': '世界问候Quiz：Lv.1 新芽 🌱 今天才知道 Sawubona 是\'我看见你\'的意思…世界还有这种问候 → 这问候是哪个国家的语言？',
      'zh-TW': '世界問候Quiz：Lv.1 新芽 🌱 今天才知道 Sawubona 是「我看見你」的意思…世界還有這種問候 → 這問候是哪個國家的語言？',
      vi: 'World Greeting Quiz: Lv.1 Mầm 🌱 Hôm nay mới biết Sawubona nghĩa là \'I see you\'... thế giới có lời chào thế này → Biết lời chào này của nước nào không?',
      id: 'World Greeting Quiz: Lv.1 Benih 🌱 Baru tahu hari ini Sawubona berarti \'I see you\'... ada salam seperti ini di dunia → Tahu salam ini dari negara mana?',
    }),
  },
  {
    type: 'Level2',
    emoji: '🗺️',
    title: localeMap({
      ko: '익숙한 건 알고 낯선 건 모르는, 언어 견습생 🗺️',
      en: 'Know the familiar, not the unfamiliar—Language Apprentice 🗺️',
      ja: '馴染みのあるものは知っていて、馴染みのないものは知らない、言語見習い 🗺️',
      'zh-CN': '熟悉的知道，陌生的不会，语言学徒 🗺️',
      'zh-TW': '熟悉的知道，陌生的不會，語言學徒 🗺️',
      vi: 'Biết cái quen, không biết cái lạ — Học việc ngôn ngữ 🗺️',
      id: 'Tahu yang familiar, bingung yang asing — Magang bahasa 🗺️',
    }),
    shortDescription: localeMap({
      ko: '잘 알려진 인사말은 어느 정도 맞혔는데 중간 이후부터 막히기 시작했군요. 평균 수준입니다.',
      en: 'You got some well-known greetings right but started stumbling after the middle. Average level.',
      ja: 'よく知られた挨拶はある程度当てましたが、中盤以降でつまずき始めました。平均レベルです。',
      'zh-CN': '常见问候答对了一些，但中段之后开始卡住。平均水平。',
      'zh-TW': '常見問候答對了一些，但中段之後開始卡住。平均水平。',
      vi: 'Lời chào nổi tiếng đúng khá nhưng từ giữa bài bắt đầu vấp. Mức trung bình.',
      id: 'Salam terkenal cukup benar tapi mulai mentok setelah tengah. Level rata-rata.',
    }),
    description: localeMap({
      ko: '프랑스어·일본어는 맞혔지만 스와힐리어·줄루어에서 막혔을 것입니다. 오늘 배운 "Jambo"와 "Sawubona"를 내일 대화에서 한번 써보세요. 분위기가 달라집니다.',
      en: 'You probably got French and Japanese right but stumbled on Swahili and Zulu. Try using "Jambo" and "Sawubona" in conversation tomorrow—the vibe will change.',
      ja: 'フランス語・日本語は当てたが、スワヒリ語・ズールー語でつまずいたはずです。明日の会話で「Jambo」と「Sawubona」を一度使ってみてください。雰囲気が変わります。',
      'zh-CN': '法语、日语可能对了，但在斯瓦希里语、祖鲁语上卡住了。明天对话里试试 "Jambo" 和 "Sawubona"，气氛会不一样。',
      'zh-TW': '法語、日語可能對了，但在斯瓦希里語、祖魯語上卡住了。明天對話裡試試 "Jambo" 和 "Sawubona"，氣氛會不一樣。',
      vi: 'Có lẽ đúng tiếng Pháp, Nhật nhưng vấp ở Swahili, Zulu. Ngày mai thử dùng "Jambo" và "Sawubona" trong hội thoại — không khí sẽ khác.',
      id: 'Mungkin benar Prancis dan Jepang tapi mentok di Swahili dan Zulu. Besok coba pakai "Jambo" dan "Sawubona" dalam obrolan — suasana akan beda.',
    }),
    languageGrade: localeMap({
      ko: '언어 고수 등급: Lv.2 견습생 🗺️',
      en: 'Language Master Grade: Lv.2 Apprentice 🗺️',
      ja: '言語マスター等級: Lv.2 見習い 🗺️',
      'zh-CN': '语言高手等级：Lv.2 学徒 🗺️',
      'zh-TW': '語言高手等級：Lv.2 學徒 🗺️',
      vi: 'Cấp cao thủ ngôn ngữ: Lv.2 Học việc 🗺️',
      id: 'Grade master bahasa: Lv.2 Magang 🗺️',
    }),
    scoreRange: localeMap({
      ko: '정답 수: 3~5개',
      en: 'Correct answers: 3~5',
      ja: '正解数: 3~5問',
      'zh-CN': '答对数：3~5题',
      'zh-TW': '答對數：3~5題',
      vi: 'Số câu đúng: 3~5',
      id: 'Jawaban benar: 3~5',
    }),
    strengthZone: localeMap({
      ko: '강점 구간: 쉬운 Q1~Q4',
      en: 'Strength zone: Easy Q1~Q4',
      ja: '得意区間: 易しい Q1~Q4',
      'zh-CN': '强项区间：简单题 Q1~Q4',
      'zh-TW': '強項區間：簡單題 Q1~Q4',
      vi: 'Điểm mạnh: Câu dễ Q1~Q4',
      id: 'Zona kuat: Soal mudah Q1~Q4',
    }),
    weakZone: localeMap({
      ko: '취약 구간: 어려운 Q9~Q12',
      en: 'Weak zone: Hard Q9~Q12',
      ja: '弱点区間: 難しい Q9~Q12',
      'zh-CN': '弱项区间：难题 Q9~Q12',
      'zh-TW': '弱項區間：難題 Q9~Q12',
      vi: 'Điểm yếu: Câu khó Q9~Q12',
      id: 'Zona lemah: Soal sulit Q9~Q12',
    }),
    retakeTip: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    characteristic: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    regretPoint: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '유명한 언어는 알고 있습니다. 이제 그 바깥이 궁금해질 것입니다',
      en: 'You know the famous languages. Now you will be curious about what lies beyond',
      ja: '有名な言語は知っています。これからその外側が気になるはずです',
      'zh-CN': '有名的语言你知道。接下来会对圈外产生好奇',
      'zh-TW': '有名的語言你知道。接下來會對圈外產生好奇',
      vi: 'Bạn biết các ngôn ngữ nổi tiếng. Giờ bạn sẽ tò mò về những gì ở bên ngoài',
      id: 'Kamu tahu bahasa-bahasa terkenal. Sekarang kamu akan penasaran dengan yang di luarnya',
    }),
    shareLine: localeMap({
      ko: '세계 인사말 퀴즈: Lv.2 견습생 🗺️ Bonjour·Ciao는 맞혔는데 Jambo에서 막힘... 스와힐리어인 줄 몰랐음 → 이 인사말 어느 나라 말인지 알아? 도전해봐',
      en: 'World Greeting Quiz: Lv.2 Apprentice 🗺️ Got Bonjour and Ciao but stuck on Jambo... didn\'t know it was Swahili → Do you know which country this greeting is from? Try it!',
      ja: '世界の挨拶クイズ: Lv.2 見習い 🗺️ Bonjour・Ciaoは当てたのにJamboで止まった…スワヒリ語だと知らなかった → この挨拶どの国？挑戦して',
      'zh-CN': '世界问候Quiz：Lv.2 学徒 🗺️ Bonjour·Ciao对了但Jambo卡住了…不知道那是斯瓦希里语 → 这问候哪个国家的？来挑战！',
      'zh-TW': '世界問候Quiz：Lv.2 學徒 🗺️ Bonjour·Ciao對了但Jambo卡住了…不知道那是斯瓦希里語 → 這問候哪個國家的？來挑戰！',
      vi: 'World Greeting Quiz: Lv.2 Học việc 🗺️ Đúng Bonjour·Ciao nhưng vấp Jambo... không biết là Swahili → Biết lời chào này của nước nào? Thử đi!',
      id: 'World Greeting Quiz: Lv.2 Magang 🗺️ Benar Bonjour·Ciao tapi mentok di Jambo... tidak tahu itu Swahili → Tahu salam ini dari negara mana? Coba!',
    }),
  },
  {
    type: 'Level3',
    emoji: '🧭',
    title: localeMap({
      ko: '여행 좀 해봤거나 언어에 관심 있는, 언어 탐험가 🧭',
      en: 'Traveled a bit or interested in languages—Language Explorer 🧭',
      ja: '少し旅行したか言語に関心がある、言語探検家 🧭',
      'zh-CN': '旅行过或对语言有兴趣，语言探险家 🧭',
      'zh-TW': '旅行過或對語言有興趣，語言探險家 🧭',
      vi: 'Đã đi du lịch hoặc quan tâm ngôn ngữ — Nhà thám hiểm ngôn ngữ 🧭',
      id: 'Pernah traveling atau suka bahasa — Penjelajah bahasa 🧭',
    }),
    shortDescription: localeMap({
      ko: '절반 이상을 맞혔습니다. 평균 이상의 세계 언어 상식입니다.',
      en: 'You got more than half correct. Above-average world language knowledge.',
      ja: '半分以上正解しました。平均以上の世界言語常識です。',
      'zh-CN': '答对一半以上。高于平均的世界语言常识。',
      'zh-TW': '答對一半以上。高於平均的世界語言常識。',
      vi: 'Đúng hơn một nửa. Kiến thức ngôn ngữ thế giới trên mức trung bình.',
      id: 'Benar lebih dari setengah. Pengetahuan bahasa dunia di atas rata-rata.',
    }),
    description: localeMap({
      ko: '힌디어 나마스테, 터키어 메르하바, 히브리어 샬롬 정도는 알고 있는 수준입니다. 스와힐리어·줄루어·사모아어에서 막혔을 것입니다. 이 정도면 해외여행에서 현지인이 기뻐하는 인사 한마디를 건넬 수 있는 사람입니다.',
      en: 'You know Hindi Namaste, Turkish Merhaba, and Hebrew Shalom. You probably stumbled on Swahili, Zulu, and Samoan. At this level you can offer a local greeting abroad that makes people smile.',
      ja: 'ヒンディー語のナマステ、トルコ語のメルハバ、ヘブライ語のシャローム程度は知っているレベルです。スワヒリ語・ズールー語・サモア語でつまずいたはずです。この程度なら海外旅行で現地人が喜ぶ挨拶を一つ言える人です。',
      'zh-CN': '印地语 Namaste、土耳其语 Merhaba、希伯来语 Shalom 这个水平你知道。斯瓦希里语、祖鲁语、萨摩亚语可能卡住了。这个程度出国旅行能说一句让当地人开心的问候。',
      'zh-TW': '印地語 Namaste、土耳其語 Merhaba、希伯來語 Shalom 這個水平你知道。斯瓦希里語、祖魯語、薩摩亞語可能卡住了。這個程度出國旅行能說一句讓當地人開心的問候。',
      vi: 'Bạn biết Namaste Hindi, Merhaba Thổ, Shalom Hebrew. Có lẽ vấp Swahili, Zulu, Samoa. Mức này đủ nói một lời chào khiến người địa phương vui khi du lịch.',
      id: 'Kamu tahu Namaste Hindi, Merhaba Turki, Shalom Ibrani. Mungkin mentok di Swahili, Zulu, Samoa. Level ini cukup untuk salam lokal yang bikin penduduk setempat senang saat traveling.',
    }),
    languageGrade: localeMap({
      ko: '언어 고수 등급: Lv.3 탐험가 🧭',
      en: 'Language Master Grade: Lv.3 Explorer 🧭',
      ja: '言語マスター等級: Lv.3 探検家 🧭',
      'zh-CN': '语言高手等级：Lv.3 探险家 🧭',
      'zh-TW': '語言高手等級：Lv.3 探險家 🧭',
      vi: 'Cấp cao thủ ngôn ngữ: Lv.3 Nhà thám hiểm 🧭',
      id: 'Grade master bahasa: Lv.3 Penjelajah 🧭',
    }),
    scoreRange: localeMap({
      ko: '정답 수: 6~8개',
      en: 'Correct answers: 6~8',
      ja: '正解数: 6~8問',
      'zh-CN': '答对数：6~8题',
      'zh-TW': '答對數：6~8題',
      vi: 'Số câu đúng: 6~8',
      id: 'Jawaban benar: 6~8',
    }),
    strengthZone: localeMap({
      ko: '강점 구간: 쉬운 + 중간 구간',
      en: 'Strength zone: Easy + medium sections',
      ja: '得意区間: 易しい＋中間区間',
      'zh-CN': '强项区间：简单+中等区间',
      'zh-TW': '強項區間：簡單+中等區間',
      vi: 'Điểm mạnh: Phần dễ + trung bình',
      id: 'Zona kuat: Bagian mudah + menengah',
    }),
    weakZone: localeMap({
      ko: '취약 구간: 어려운 Q9~Q12 (아프리카·오세아니아 언어군)',
      en: 'Weak zone: Hard Q9~Q12 (Africa · Oceania language groups)',
      ja: '弱点区間: 難しい Q9~Q12（アフリカ・オセアニア言語群）',
      'zh-CN': '弱项区间：难题 Q9~Q12（非洲·大洋洲语系）',
      'zh-TW': '弱項區間：難題 Q9~Q12（非洲·大洋洲語系）',
      vi: 'Điểm yếu: Câu khó Q9~Q12 (nhóm ngôn ngữ châu Phi · Châu Đại Dương)',
      id: 'Zona lemah: Soal sulit Q9~Q12 (grup bahasa Afrika · Oseania)',
    }),
    retakeTip: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    characteristic: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    regretPoint: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '세계가 이미 어느 정도 보이는 사람입니다. 조금만 더 가면 고수입니다',
      en: 'The world is already somewhat visible to you. A little more and you are a master',
      ja: '世界がすでにある程度見えている人です。もう少しで達人です',
      'zh-CN': '世界在你眼中已经有点轮廓了。再进一步就是高手',
      'zh-TW': '世界在你眼中已經有點輪廓了。再進一步就是高手',
      vi: 'Thế giới đã hiện ra phần nào với bạn. Thêm chút nữa là cao thủ',
      id: 'Dunia sudah terlihat sebagian bagimu. Sedikit lagi jadi master',
    }),
    shareLine: localeMap({
      ko: '세계 인사말 퀴즈: Lv.3 탐험가 🧭 Namaste·Shalom까지는 맞혔는데 Talofa에서 멘붕... 사모아어인 줄 누가 알겠어 ㅋㅋ → 이 나라 말 알아? 친구한테 도전장 보내봐',
      en: 'World Greeting Quiz: Lv.3 Explorer 🧭 Got Namaste and Shalom but melted at Talofa... who knew it was Samoan lol → Know this country? Challenge a friend!',
      ja: '世界の挨拶クイズ: Lv.3 探検家 🧭 Namaste・Shalomまでは当てたのにTalofaでメンタル崩壊…サモア語だと誰が知る ㅋㅋ → この国分かる？友達に挑戦状',
      'zh-CN': '世界问候Quiz：Lv.3 探险家 🧭 Namaste·Shalom对了但Talofa崩了…谁知道是萨摩亚语 哈哈 → 这国家知道吗？发给朋友挑战！',
      'zh-TW': '世界問候Quiz：Lv.3 探險家 🧭 Namaste·Shalom對了但Talofa崩了…誰知道是薩摩亞語 哈哈 → 這國家知道嗎？發給朋友挑戰！',
      vi: 'World Greeting Quiz: Lv.3 Thám hiểm 🧭 Đúng Namaste·Shalom nhưng sập ở Talofa... ai biết là Samoa ㅋㅋ → Biết nước này không? Thách bạn!',
      id: 'World Greeting Quiz: Lv.3 Penjelajah 🧭 Benar Namaste·Shalom tapi k.o. di Talofa... siapa tahu itu Samoa ㅋㅋ → Tahu negara ini? Tantang teman!',
    }),
  },
  {
    type: 'Level4',
    emoji: '🌐',
    title: localeMap({
      ko: '세계 언어 지식이 상당한, 언어 고수 🌐',
      en: 'Strong world language knowledge—Language Expert 🌐',
      ja: '世界言語の知識がかなりある、言語上級者 🌐',
      'zh-CN': '世界语言知识相当丰富，语言高手 🌐',
      'zh-TW': '世界語言知識相當豐富，語言高手 🌐',
      vi: 'Kiến thức ngôn ngữ thế giới đáng kể — Cao thủ ngôn ngữ 🌐',
      id: 'Pengetahuan bahasa dunia kuat — Ahli bahasa 🌐',
    }),
    shortDescription: localeMap({
      ko: '어려운 구간까지 대부분 맞혔습니다. 상위 15%에 해당하는 세계 언어 지식입니다.',
      en: 'You got most of the hard section right. Top 15% world language knowledge.',
      ja: '難しい区間までほとんど正解しました。上位15%の世界言語知識です。',
      'zh-CN': '难题也大多答对。世界语言知识前15%。',
      'zh-TW': '難題也大多答對。世界語言知識前15%。',
      vi: 'Phần khó cũng đúng hầu hết. Top 15% kiến thức ngôn ngữ thế giới.',
      id: 'Bagian sulit kebanyakan benar. Top 15% pengetahuan bahasa dunia.',
    }),
    description: localeMap({
      ko: '스와힐리어 잠보, 베트남어 신짜오까지 알고 있다면 평소에 언어·문화·여행에 깊은 관심이 있는 사람일 가능성이 높습니다. "Sawubona"가 \'나는 당신을 봅니다\'라는 의미를 담고 있다는 것도 알고 있었다면 진짜 고수입니다.',
      en: 'If you know Swahili Jambo and Vietnamese Xin chào, you likely have deep interest in languages, culture, and travel. If you also knew Sawubona means "I see you," you are a true expert.',
      ja: 'スワヒリ語のJambo、ベトナム語のXin chàoまで知っているなら、普段から言語・文化・旅行に深い関心がある人の可能性が高いです。「Sawubona」がI see youという意味を知っていたなら本当の達人です。',
      'zh-CN': '若知道斯瓦希里语 Jambo、越南语 Xin chào，说明你平时对语言、文化、旅行有深厚兴趣。若还知道 Sawubona 意为 I see you，那就是真高手。',
      'zh-TW': '若知道斯瓦希里語 Jambo、越南語 Xin chào，說明你平時對語言、文化、旅行有深厚興趣。若還知道 Sawubona 意為 I see you，那就是真高手。',
      vi: 'Biết Jambo Swahili và Xin chào Việt Nam thì bạn có lẽ rất quan tâm ngôn ngữ, văn hóa, du lịch. Biết thêm Sawubona nghĩa "I see you" thì đúng là cao thủ.',
      id: 'Kalau tahu Jambo Swahili dan Xin chào Vietnam, kamu mungkin sangat suka bahasa, budaya, traveling. Kalau juga tahu Sawubona berarti "I see you," kamu ahli sejati.',
    }),
    languageGrade: localeMap({
      ko: '언어 고수 등급: Lv.4 고수 🌐',
      en: 'Language Master Grade: Lv.4 Expert 🌐',
      ja: '言語マスター等級: Lv.4 上級者 🌐',
      'zh-CN': '语言高手等级：Lv.4 高手 🌐',
      'zh-TW': '語言高手等級：Lv.4 高手 🌐',
      vi: 'Cấp cao thủ ngôn ngữ: Lv.4 Cao thủ 🌐',
      id: 'Grade master bahasa: Lv.4 Ahli 🌐',
    }),
    scoreRange: localeMap({
      ko: '정답 수: 9~10개',
      en: 'Correct answers: 9~10',
      ja: '正解数: 9~10問',
      'zh-CN': '答对数：9~10题',
      'zh-TW': '答對數：9~10題',
      vi: 'Số câu đúng: 9~10',
      id: 'Jawaban benar: 9~10',
    }),
    strengthZone: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    weakZone: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    retakeTip: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    characteristic: localeMap({
      ko: '이 결과를 가진 사람의 특징: 여행을 좋아하거나 언어·문화 콘텐츠를 즐겨 봄',
      en: 'Traits of this result: loves travel or enjoys language and culture content',
      ja: 'この結果を持つ人の特徴: 旅行が好き、または言語・文化コンテンツを楽しむ',
      'zh-CN': '此结果特征：喜欢旅行，或爱看语言·文化内容',
      'zh-TW': '此結果特徵：喜歡旅行，或愛看語言·文化內容',
      vi: 'Đặc điểm: thích du lịch hoặc hay xem nội dung ngôn ngữ · văn hóa',
      id: 'Ciri hasil ini: suka traveling atau menikmati konten bahasa & budaya',
    }),
    regretPoint: localeMap({
      ko: '아쉬운 포인트: 만점까지 2~3개 차이. 틀린 인사말의 해설을 다시 읽어보기',
      en: 'Almost there: 2~3 away from a perfect score. Re-read explanations for missed greetings',
      ja: '惜しいポイント: 満点まで2~3問差。間違えた挨拶の解説をもう一度読む',
      'zh-CN': '遗憾点：离满分差2~3题。重读错题解析',
      'zh-TW': '遺憾點：離滿分差2~3題。重讀錯題解析',
      vi: 'Tiếc nuối: cách điểm tuyệt đối 2~3 câu. Đọc lại giải thích các lời chào sai',
      id: 'Sayangnya: tinggal 2~3 lagi sempurna. Baca ulang penjelasan salam yang salah',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '이 결과면 세계 어느 나라에서든 현지 인사 한마디는 건넬 수 있는 사람입니다',
      en: 'With this result you can offer a local greeting almost anywhere in the world',
      ja: 'この結果なら世界のどこでも現地の挨拶を一つは言える人です',
      'zh-CN': '这个水平，世界任何地方都能来一句当地问候',
      'zh-TW': '這個水平，世界任何地方都能來一句當地問候',
      vi: 'Với kết quả này bạn có thể chào một câu địa phương ở hầu hết mọi nơi trên thế giới',
      id: 'Dengan hasil ini kamu bisa menyapa setempat hampir di mana saja di dunia',
    }),
    shareLine: localeMap({
      ko: '세계 인사말 퀴즈: Lv.4 고수 🌐 상위 15%... Xin chào·Sawubona까지 맞혔음 → 이 나라 말 알아? 이거 다 맞히면 언어 고수 인정',
      en: 'World Greeting Quiz: Lv.4 Expert 🌐 Top 15%... got Xin chào and Sawubona → Know this country? Get them all and you are a language master',
      ja: '世界の挨拶クイズ: Lv.4 上級者 🌐 上位15%…Xin chào・Sawubonaまで当てた → この国分かる？全部当てたら言語マスター認定',
      'zh-CN': '世界问候Quiz：Lv.4 高手 🌐 前15%…Xin chào·Sawubona都对了 → 这国家知道吗？全对算语言高手',
      'zh-TW': '世界問候Quiz：Lv.4 高手 🌐 前15%…Xin chào·Sawubona都對了 → 這國家知道嗎？全對算語言高手',
      vi: 'World Greeting Quiz: Lv.4 Cao thủ 🌐 Top 15%... đúng Xin chào·Sawubona → Biết nước này không? Full điểm = master ngôn ngữ',
      id: 'World Greeting Quiz: Lv.4 Ahli 🌐 Top 15%... benar Xin chào·Sawubona → Tahu negara ini? Full score = master bahasa',
    }),
  },
  {
    type: 'Level5',
    emoji: '🏆',
    title: localeMap({
      ko: '세계 모든 곳이 반가운 사람, 언어 마스터 🏆',
      en: 'Everywhere in the world feels welcoming—Language Master 🏆',
      ja: '世界のどこでも歓迎される人、言語マスター 🏆',
      'zh-CN': '世界各处都欢迎的人，语言大师 🏆',
      'zh-TW': '世界各處都歡迎的人，語言大師 🏆',
      vi: 'Mọi nơi trên thế giới đều chào đón — Bậc thầy ngôn ngữ 🏆',
      id: 'Di mana pun di dunia terasa welcome — Master bahasa 🏆',
    }),
    shortDescription: localeMap({
      ko: '11개 또는 12개를 모두 맞혔습니다. 사모아어 탈로파까지 맞혔다면 진정한 세계 언어 마스터입니다.',
      en: 'You got 11 or 12 correct. If you got Samoan Talofa too, you are a true world language master.',
      ja: '11問または12問全問正解。サモア語のTalofaまで当てたなら真の世界言語マスターです。',
      'zh-CN': '答对11或12题。连萨摩亚语 Talofa 也对了，就是真正的世界语言大师。',
      'zh-TW': '答對11或12題。連薩摩亞語 Talofa 也對了，就是真正的世界語言大師。',
      vi: 'Đúng 11 hoặc 12 câu. Đúng cả Talofa Samoa thì bạn là master ngôn ngữ thế giới thật sự.',
      id: 'Benar 11 atau 12. Kalau Talofa Samoa juga benar, kamu master bahasa dunia sejati.',
    }),
    description: localeMap({
      ko: '줄루어 Sawubona가 \'나는 당신을 봅니다\'를 의미하고, 사모아어 Talofa가 \'사랑을 드립니다\'를 의미하는 것까지 알고 있다는 것은 세계 언어에 깊은 관심과 지식을 가진 사람임을 증명합니다.',
      en: 'Knowing that Zulu Sawubona means I see you and Samoan Talofa means I give you love proves deep interest and knowledge in world languages.',
      ja: 'ズールー語のSawubonaがI see youを意味し、サモア語のTalofaが愛を差し上げますを意味することまで知っているのは、世界言語への深い関心と知識を持つ人であることを証明します。',
      'zh-CN': '知道祖鲁语 Sawubona 意为 I see you、萨摩亚语 Talofa 意为我把爱送给你，说明你拥有对世界语言的深厚兴趣与知识。',
      'zh-TW': '知道祖魯語 Sawubona 意為 I see you、薩摩亞語 Talofa 意為我把愛送給你，說明你擁有對世界語言的深厚興趣與知識。',
      vi: 'Biết Sawubona Zulu nghĩa I see you và Talofa Samoa nghĩa trao tình yêu chứng minh bạn có kiến thức và đam mê sâu với ngôn ngữ thế giới.',
      id: 'Tahu Sawubona Zulu berarti I see you dan Talofa Samoa berarti memberimu cinta membuktikan minat dan pengetahuan mendalam tentang bahasa dunia.',
    }),
    languageGrade: localeMap({
      ko: '언어 고수 등급: Lv.5 마스터 🏆',
      en: 'Language Master Grade: Lv.5 Master 🏆',
      ja: '言語マスター等級: Lv.5 マスター 🏆',
      'zh-CN': '语言高手等级：Lv.5 大师 🏆',
      'zh-TW': '語言高手等級：Lv.5 大師 🏆',
      vi: 'Cấp cao thủ ngôn ngữ: Lv.5 Bậc thầy 🏆',
      id: 'Grade master bahasa: Lv.5 Master 🏆',
    }),
    scoreRange: localeMap({
      ko: '정답 수: 11~12개',
      en: 'Correct answers: 11~12',
      ja: '正解数: 11~12問',
      'zh-CN': '答对数：11~12题',
      'zh-TW': '答對數：11~12題',
      vi: 'Số câu đúng: 11~12',
      id: 'Jawaban benar: 11~12',
    }),
    strengthZone: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    weakZone: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    retakeTip: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    characteristic: localeMap({
      ko: '이 결과가 가능한 경우: 언어학 전공·다국어 구사자·세계 여행 경험자·문화 콘텐츠 애청자',
      en: 'How this result is possible: linguistics major, polyglot, world traveler, or culture content enthusiast',
      ja: 'この結果が可能な場合: 言語学専攻・多言語話者・世界旅行経験者・文化コンテンツ愛好者',
      'zh-CN': '可能情况：语言学专业、多语者、环球旅行者、文化内容爱好者',
      'zh-TW': '可能情況：語言學專業、多語者、環球旅行者、文化內容愛好者',
      vi: 'Khả năng đạt kết quả này: chuyên ngành ngôn ngữ học, đa ngôn ngữ, đi khắp thế giới, hoặc mê nội dung văn hóa',
      id: 'Kemungkinan hasil ini: jurusan linguistik, poliglot, traveler dunia, atau penggemar konten budaya',
    }),
    regretPoint: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    certificationPhrase: localeMap({
      ko: '세계 언어 마스터 달성 🏆 사모아어까지 맞혔습니다',
      en: 'World Language Master achieved 🏆 You even got Samoan right',
      ja: '世界言語マスター達成 🏆 サモア語まで当てました',
      'zh-CN': '世界语言大师达成 🏆 连萨摩亚语也对了',
      'zh-TW': '世界語言大師達成 🏆 連薩摩亞語也對了',
      vi: 'Đạt World Language Master 🏆 Đúng cả tiếng Samoa',
      id: 'World Language Master tercapai 🏆 Bahkan Samoa benar',
    }),
    oneLiner: localeMap({
      ko: '당신은 세계 어디에서나 \'반갑습니다\'를 알아듣는 사람입니다',
      en: 'You understand \'nice to meet you\' anywhere in the world',
      ja: '世界のどこでも「はじめまして」を理解できる人です',
      'zh-CN': '世界任何地方都能听懂「很高兴见到你」',
      'zh-TW': '世界任何地方都能聽懂「很高興見到你」',
      vi: 'Bạn hiểu \'rất vui được gặp bạn\' ở bất cứ đâu trên thế giới',
      id: 'Kamu mengerti \'senang bertemu\' di mana pun di dunia',
    }),
    shareLine: localeMap({
      ko: '세계 인사말 퀴즈: Lv.5 마스터 🏆 사모아어 Talofa까지 맞혔음... 이거 12개 다 아는 사람 있으면 나와봐 → 이 나라 말 알아? 도전해봐',
      en: 'World Greeting Quiz: Lv.5 Master 🏆 Got Samoan Talofa too... anyone who got all 12, show yourself → Know this country? Challenge a friend!',
      ja: '世界の挨拶クイズ: Lv.5 マスター 🏆 サモア語Talofaまで当てた…12問全部知ってる人出てこい → この国分かる？挑戦して',
      'zh-CN': '世界问候Quiz：Lv.5 大师 🏆 萨摩亚语 Talofa 也对了…12题全会的人出来 → 这国家知道吗？来挑战！',
      'zh-TW': '世界問候Quiz：Lv.5 大師 🏆 薩摩亞語 Talofa 也對了…12題全會的人出來 → 這國家知道嗎？來挑戰！',
      vi: 'World Greeting Quiz: Lv.5 Master 🏆 Đúng cả Talofa Samoa... ai full 12 câu ra đây → Biết nước này không? Thách bạn!',
      id: 'World Greeting Quiz: Lv.5 Master 🏆 Benar Talofa Samoa juga... ada yang 12/12? Keluar → Tahu negara ini? Tantang teman!',
    }),
  },
];
