/** 밸런스 게임 — 음식 극한편 · phase3-food-balance-game · 12라운드 2지선다 · A=0(순) B=1(매) · 7개 로케일 */

export type Phase3FoodBalanceGameLocaleKey = 'ko' | 'en' | 'ja' | 'zh-CN' | 'zh-TW' | 'vi' | 'id';

function localeMap(t: Record<Phase3FoodBalanceGameLocaleKey, string>): Record<Phase3FoodBalanceGameLocaleKey, string> {
  return t;
}

export interface Phase3FoodBalanceGameQuestion {
  id: number;
  question: Record<Phase3FoodBalanceGameLocaleKey, string>;
  options: { image: string; label: Record<Phase3FoodBalanceGameLocaleKey, string>; score: number }[];
}

export interface Phase3FoodBalanceGameResult {
  type: string;
  emoji: string;
  title: Record<Phase3FoodBalanceGameLocaleKey, string>;
  shortDescription: Record<Phase3FoodBalanceGameLocaleKey, string>;
  description: Record<Phase3FoodBalanceGameLocaleKey, string>;
  temperatureCelsius: number;
  accentColor: string;
  emotionTemperature: Record<Phase3FoodBalanceGameLocaleKey, string>;
  emotionColor: Record<Phase3FoodBalanceGameLocaleKey, string>;
  emotionKeywords: Record<Phase3FoodBalanceGameLocaleKey, string>;
  strengthAtTemp: Record<Phase3FoodBalanceGameLocaleKey, string>;
  charmAtTemp: Record<Phase3FoodBalanceGameLocaleKey, string>;
  comfortableSpace: Record<Phase3FoodBalanceGameLocaleKey, string>;
  colorCodes: Record<Phase3FoodBalanceGameLocaleKey, string>;
  certificationPhrase: Record<Phase3FoodBalanceGameLocaleKey, string>;
  oneLiner: Record<Phase3FoodBalanceGameLocaleKey, string>;
  shareLine: Record<Phase3FoodBalanceGameLocaleKey, string>;
}

export function calculatePhase3FoodBalanceGameResult(answers: number[]): string {
  const total = answers.reduce((sum, s) => sum + (s ?? 0), 0);
  if (total <= 1) return 'Type1';
  if (total <= 3) return 'Type2';
  if (total <= 6) return 'Type3';
  if (total <= 9) return 'Type4';
  if (total <= 11) return 'Type5';
  return 'Type6';
}

const IMG = (n: number, choice: 'a' | 'b') => 'p3_game_food_balance_q' + String(n) + choice + '.webp';

export const phase3FoodBalanceGameQuestions: Phase3FoodBalanceGameQuestion[] = [

  {
    id: 1,
    question: localeMap({
      ko: "Round 1. 위로의 국물 vs 지옥의 국물",
      en: "Round 1. Comfort broth vs hell broth",
      ja: "ラウンド1. 癒しのスープ vs 地獄のスープ",
      'zh-CN': "第1轮 治愈系汤 vs 地狱级汤",
      'zh-TW': "第1輪 治癒系湯 vs 地獄級湯",
      vi: "Vòng 1. Nước dùng an ủi vs nước dùng địa ngục",
      id: "Ronde 1. Kuah penghibur vs kuah neraka",
    }),
    options: [
      { image: IMG(1, 'a'), label: localeMap({
        ko: "순두부찌개",
        en: "Soft tofu stew",
        ja: "スンドゥブチゲ",
        'zh-CN': "嫩豆腐锅",
        'zh-TW': "嫩豆腐鍋",
        vi: "Canh đậu phụ mềm",
        id: "Sup tahu lembut",
    }), score: 0 },
      { image: IMG(1, 'b'), label: localeMap({
        ko: "마라탕",
        en: "Mala hot pot",
        ja: "マーラータン",
        'zh-CN': "麻辣烫",
        'zh-TW': "麻辣燙",
        vi: "Lẩu mala",
        id: "Mala hot pot",
    }), score: 1 },
    ],
  },
  {
    id: 2,
    question: localeMap({
      ko: "Round 2. 국민 보양 vs 매운 맛의 끝",
      en: "Round 2. National tonic vs peak spice",
      ja: "ラウンド2. 国民滋養 vs 辛さの極み",
      'zh-CN': "第2轮 国民滋补 vs 辣味巅峰",
      'zh-TW': "第2輪 國民滋補 vs 辣味巔峰",
      vi: "Vòng 2. Món bồi bổ quốc dân vs đỉnh cay",
      id: "Ronde 2. Suplemen rakyat vs puncak pedas",
    }),
    options: [
      { image: IMG(2, 'a'), label: localeMap({
        ko: "삼계탕",
        en: "Samgyetang",
        ja: "サムゲタン",
        'zh-CN': "参鸡汤",
        'zh-TW': "參雞湯",
        vi: "Samgyetang",
        id: "Samgyetang",
    }), score: 0 },
      { image: IMG(2, 'b'), label: localeMap({
        ko: "불닭 닭발",
        en: "Spicy chicken feet",
        ja: "激辛チキンフィート",
        'zh-CN': "超辣鸡爪",
        'zh-TW': "超辣雞爪",
        vi: "Chân gà cay cực",
        id: "Kaki ayam pedas ekstrem",
    }), score: 1 },
    ],
  },
  {
    id: 3,
    question: localeMap({
      ko: "Round 3. 여름 대표 vs 매운 여름",
      en: "Round 3. Summer classic vs spicy summer",
      ja: "ラウンド3. 夏の定番 vs 辛い夏",
      'zh-CN': "第3轮 夏日代表 vs 火辣夏日",
      'zh-TW': "第3輪 夏日代表 vs 火辣夏日",
      vi: "Vòng 3. Món hè kinh điển vs mùa hè cay",
      id: "Ronde 3. Klasik musim panas vs musim panas pedas",
    }),
    options: [
      { image: IMG(3, 'a'), label: localeMap({
        ko: "물냉면",
        en: "Cold noodles in broth",
        ja: "水冷麺",
        'zh-CN': "水冷面",
        'zh-TW': "水冷麵",
        vi: "Naengmyeon nước",
        id: "Naengmyeon kuah",
    }), score: 0 },
      { image: IMG(3, 'b'), label: localeMap({
        ko: "불냉면",
        en: "Spicy cold noodles",
        ja: "激辛冷麺",
        'zh-CN': "辣冷面",
        'zh-TW': "辣冷麵",
        vi: "Naengmyeon cay",
        id: "Naengmyeon pedas",
    }), score: 1 },
    ],
  },
  {
    id: 4,
    question: localeMap({
      ko: "Round 4. 분식 클래식 vs 분식 극한",
      en: "Round 4. Snack bar classic vs extreme",
      ja: "ラウンド4. 軽食クラシック vs 軽食極限",
      'zh-CN': "第4轮 小吃经典 vs 小吃极限",
      'zh-TW': "第4輪 小吃經典 vs 小吃極限",
      vi: "Vòng 4. Đồ ăn vặt kinh điển vs cực hạn",
      id: "Ronde 4. Klasik jajanan vs ekstrem",
    }),
    options: [
      { image: IMG(4, 'a'), label: localeMap({
        ko: "일반 떡볶이",
        en: "Regular tteokbokki",
        ja: "普通のトッポッキ",
        'zh-CN': "普通炒年糕",
        'zh-TW': "普通炒年糕",
        vi: "Tteokbokki thường",
        id: "Tteokbokki biasa",
    }), score: 0 },
      { image: IMG(4, 'b'), label: localeMap({
        ko: "엽기 떡볶이",
        en: "Extreme tteokbokki",
        ja: "激辛トッポッキ",
        'zh-CN': "变态辣炒年糕",
        'zh-TW': "變態辣炒年糕",
        vi: "Tteokbokki siêu cay",
        id: "Tteokbokki ekstrem pedas",
    }), score: 1 },
    ],
  },
  {
    id: 5,
    question: localeMap({
      ko: "Round 5. 국물 전쟁 1라운드",
      en: "Round 5. Broth battle round 1",
      ja: "ラウンド5. スープバトル第1ラウンド",
      'zh-CN': "第5轮 汤面大战第1轮",
      'zh-TW': "第5輪 湯麵大戰第1輪",
      vi: "Vòng 5. Cuộc chiến nước dùng vòng 1",
      id: "Ronde 5. Pertarungan kuah ronde 1",
    }),
    options: [
      { image: IMG(5, 'a'), label: localeMap({
        ko: "우동",
        en: "Udon",
        ja: "うどん",
        'zh-CN': "乌冬面",
        'zh-TW': "烏龍麵",
        vi: "Udon",
        id: "Udon",
    }), score: 0 },
      { image: IMG(5, 'b'), label: localeMap({
        ko: "짬뽕",
        en: "Jjamppong",
        ja: "チャンポン",
        'zh-CN': "海鲜辣汤面",
        'zh-TW': "海鮮辣湯麵",
        vi: "Jjamppong",
        id: "Jjamppong",
    }), score: 1 },
    ],
  },
  {
    id: 6,
    question: localeMap({
      ko: "Round 6. 치킨 대전",
      en: "Round 6. Chicken showdown",
      ja: "ラウンド6. チキン対決",
      'zh-CN': "第6轮 炸鸡大战",
      'zh-TW': "第6輪 炸雞大戰",
      vi: "Vòng 6. Đại chiến gà rán",
      id: "Ronde 6. Pertarungan ayam goreng",
    }),
    options: [
      { image: IMG(6, 'a'), label: localeMap({
        ko: "후라이드 치킨",
        en: "Fried chicken",
        ja: "フライドチキン",
        'zh-CN': "原味炸鸡",
        'zh-TW': "原味炸雞",
        vi: "Gà rán giòn",
        id: "Ayam goreng",
    }), score: 0 },
      { image: IMG(6, 'b'), label: localeMap({
        ko: "핵불닭 치킨",
        en: "Nuclear spicy chicken",
        ja: "核激辛チキン",
        'zh-CN': "核弹级辣炸鸡",
        'zh-TW': "核彈級辣炸雞",
        vi: "Gà rán siêu cay",
        id: "Ayam goreng pedas nuklir",
    }), score: 1 },
    ],
  },
  {
    id: 7,
    question: localeMap({
      ko: "Round 7. 면 대전 클래식",
      en: "Round 7. Noodle showdown classic",
      ja: "ラウンド7. 麺対決クラシック",
      'zh-CN': "第7轮 面条大战经典篇",
      'zh-TW': "第7輪 麵條大戰經典篇",
      vi: "Vòng 7. Đại chiến mì kinh điển",
      id: "Ronde 7. Pertarungan mi klasik",
    }),
    options: [
      { image: IMG(7, 'a'), label: localeMap({
        ko: "짜장면",
        en: "Jajangmyeon",
        ja: "ジャージャー麺",
        'zh-CN': "炸酱面",
        'zh-TW': "炸醬麵",
        vi: "Jajangmyeon",
        id: "Jajangmyeon",
    }), score: 0 },
      { image: IMG(7, 'b'), label: localeMap({
        ko: "짬뽕라면",
        en: "Spicy seafood ramen",
        ja: "チャンポンラーメン",
        'zh-CN': "海鲜辣汤方便面",
        'zh-TW': "海鮮辣湯泡麵",
        vi: "Mì jjamppong",
        id: "Ramen jjamppong",
    }), score: 1 },
    ],
  },
  {
    id: 8,
    question: localeMap({
      ko: "Round 8. 고기 양자택일",
      en: "Round 8. Meat either-or",
      ja: "ラウンド8. 肉の二者択一",
      'zh-CN': "第8轮 肉类二选一",
      'zh-TW': "第8輪 肉類二選一",
      vi: "Vòng 8. Thịt chọn một trong hai",
      id: "Ronde 8. Daging pilih salah satu",
    }),
    options: [
      { image: IMG(8, 'a'), label: localeMap({
        ko: "삼겹살",
        en: "Pork belly BBQ",
        ja: "サムギョプサル",
        'zh-CN': "五花肉",
        'zh-TW': "五花肉",
        vi: "Ba chỉ nướng",
        id: "Samgyeopsal",
    }), score: 0 },
      { image: IMG(8, 'b'), label: localeMap({
        ko: "불곱창",
        en: "Spicy grilled intestines",
        ja: "激辛ホットプ",
        'zh-CN': "辣烤牛肠",
        'zh-TW': "辣烤牛腸",
        vi: "Lòng bò nướng cay",
        id: "Usus sapi pedas panggang",
    }), score: 1 },
    ],
  },
  {
    id: 9,
    question: localeMap({
      ko: "Round 9. 초밥 전쟁",
      en: "Round 9. Sushi battle",
      ja: "ラウンド9. 寿司バトル",
      'zh-CN': "第9轮 寿司大战",
      'zh-TW': "第9輪 壽司大戰",
      vi: "Vòng 9. Cuộc chiến sushi",
      id: "Ronde 9. Pertarungan sushi",
    }),
    options: [
      { image: IMG(9, 'a'), label: localeMap({
        ko: "일반 초밥",
        en: "Regular sushi",
        ja: "普通の寿司",
        'zh-CN': "普通寿司",
        'zh-TW': "普通壽司",
        vi: "Sushi thường",
        id: "Sushi biasa",
    }), score: 0 },
      { image: IMG(9, 'b'), label: localeMap({
        ko: "와사비 폭탄 초밥",
        en: "Wasabi bomb sushi",
        ja: "わさび爆弾寿司",
        'zh-CN': "芥末炸弹寿司",
        'zh-TW': "芥末炸彈壽司",
        vi: "Sushi bom wasabi",
        id: "Sushi bom wasabi",
    }), score: 1 },
    ],
  },
  {
    id: 10,
    question: localeMap({
      ko: "Round 10. 라면 대전",
      en: "Round 10. Ramen showdown",
      ja: "ラウンド10. ラーメン対決",
      'zh-CN': "第10轮 方便面大战",
      'zh-TW': "第10輪 泡麵大戰",
      vi: "Vòng 10. Đại chiến mì gói",
      id: "Ronde 10. Pertarungan ramen instan",
    }),
    options: [
      { image: IMG(10, 'a'), label: localeMap({
        ko: "신라면",
        en: "Shin Ramyun",
        ja: "辛ラーメン",
        'zh-CN': "辛拉面",
        'zh-TW': "辛拉麵",
        vi: "Shin Ramyun",
        id: "Shin Ramyun",
    }), score: 0 },
      { image: IMG(10, 'b'), label: localeMap({
        ko: "불닭볶음면",
        en: "Buldak stir-fry noodles",
        ja: "プルダックポックンミョン",
        'zh-CN': "火鸡面",
        'zh-TW': "火雞麵",
        vi: "Mì buldak",
        id: "Mie buldak",
    }), score: 1 },
    ],
  },
  {
    id: 11,
    question: localeMap({
      ko: "Round 11. 디저트 이변",
      en: "Round 11. Dessert upset",
      ja: "ラウンド11. デザートの異変",
      'zh-CN': "第11轮 甜点异变",
      'zh-TW': "第11輪 甜點異變",
      vi: "Vòng 11. Biến động tráng miệng",
      id: "Ronde 11. Kejutan dessert",
    }),
    options: [
      { image: IMG(11, 'a'), label: localeMap({
        ko: "바닐라 아이스크림",
        en: "Vanilla ice cream",
        ja: "バニラアイス",
        'zh-CN': "香草冰淇淋",
        'zh-TW': "香草冰淇淋",
        vi: "Kem vani",
        id: "Es krim vanila",
    }), score: 0 },
      { image: IMG(11, 'b'), label: localeMap({
        ko: "마라맛 아이스크림",
        en: "Mala-flavor ice cream",
        ja: "マーラー味アイス",
        'zh-CN': "麻辣味冰淇淋",
        'zh-TW': "麻辣味冰淇淋",
        vi: "Kem vị mala",
        id: "Es krim rasa mala",
    }), score: 1 },
    ],
  },
  {
    id: 12,
    question: localeMap({
      ko: "Round 12. 국물 전쟁 최종 라운드",
      en: "Round 12. Broth battle final round",
      ja: "ラウンド12. スープバトル最終ラウンド",
      'zh-CN': "第12轮 汤面大战最终轮",
      'zh-TW': "第12輪 湯麵大戰最終輪",
      vi: "Vòng 12. Cuộc chiến nước dùng vòng cuối",
      id: "Ronde 12. Pertarungan kuah ronde final",
    }),
    options: [
      { image: IMG(12, 'a'), label: localeMap({
        ko: "된장찌개",
        en: "Doenjang stew",
        ja: "テンジャンチゲ",
        'zh-CN': "大酱汤",
        'zh-TW': "大醬湯",
        vi: "Canh doenjang",
        id: "Sup doenjang",
    }), score: 0 },
      { image: IMG(12, 'b'), label: localeMap({
        ko: "마라샹궈",
        en: "Mala xiang guo",
        ja: "マーラーシャングオ",
        'zh-CN': "麻辣香锅",
        'zh-TW': "麻辣香鍋",
        vi: "Mala xiang guo",
        id: "Mala xiang guo",
    }), score: 1 },
    ],
  },
];

export const phase3FoodBalanceGameResults: Phase3FoodBalanceGameResult[] = [
  {
    type: 'Type1',
    emoji: '🌸',
    temperatureCelsius: 0,
    accentColor: '#6B9080',
    title: localeMap({
      ko: "배 걱정이 최우선인 사람, 소화기 천사형",
      en: "Stomach First — Digestive Angel Type",
      ja: "お腹優先の人 — 消化器天使型",
      'zh-CN': "胃优先的人——消化天使型",
      'zh-TW': "胃優先的人——消化天使型",
      vi: "Lo lắng dạ dày trước — Kiểu thiên thần tiêu hóa",
      id: "Perut dulu — Tipe malaikat pencernaan",
    }),
    shortDescription: localeMap({
      ko: "당신에게 음식은 자극이 아니라 위로입니다. 배가 편해야 행복한 사람입니다.",
      en: "Food is comfort, not stimulation. You're happy when your stomach is at ease.",
      ja: "あなたにとって食べ物は刺激ではなく癒し。お腹が楽なら幸せな人です。",
      'zh-CN': "对你而言，食物是安慰而非刺激。胃舒服才幸福。",
      'zh-TW': "對你而言，食物是安慰而非刺激。胃舒服才幸福。",
      vi: "Với bạn, đồ ăn là an ủi chứ không phải kích thích. Dạ dày thoải mái mới hạnh phúc.",
      id: "Bagimu, makanan itu penghibur bukan rangsangan. Perut nyaman baru bahagia.",
    }),
    description: localeMap({
      ko: "마라탕 대신 순두부, 불냉면 대신 물냉면, 불곱창 대신 삼겹살. 이 선택들에 이유가 있습니다. 자극적인 것이 싫은 게 아니라 몸이 먼저인 사람입니다. 12라운드 내내 순한 것을 선택한 평화주의 미각 타입입니다.",
      en: "Soft tofu over mala hot pot, cold noodles in broth over spicy cold noodles, pork belly over spicy intestines — these choices have a reason. It's not that you dislike spice; your body comes first. A peaceful palate type who picked mild options through all 12 rounds.",
      ja: "マーラータンよりスンドゥブ、激辛冷麺より水冷麺、激辛ホットプよりサムギョプサル。この選択には理由がある。刺激が嫌いなのではなく、体が先の人。12ラウンドずっとマイルドを選んだ平和主義の味覚タイプ。",
      'zh-CN': "麻辣烫换嫩豆腐锅、辣冷面换水冷面、辣烤牛肠换五花肉——这些选择都有理由。不是讨厌刺激，而是身体优先。12轮都选温和款的和平主义味觉型。",
      'zh-TW': "麻辣燙換嫩豆腐鍋、辣冷麵換水冷麵、辣烤牛腸換五花肉——這些選擇都有理由。不是討厭刺激，而是身體優先。12輪都選溫和款的和平主義味覺型。",
      vi: "Lẩu mala thay bằng canh đậu phụ, naengmyeon cay thay bằng naengmyeon nước, lòng bò cay thay bằng ba chỉ — mỗi lựa chọn đều có lý do. Không phải ghét cay mà cơ thể lên trước. Kiểu vị giác chủ nghĩa hòa bình, chọn món nhẹ cả 12 vòng.",
      id: "Mala hot pot diganti sup tahu, naengmyeon pedas diganti naengmyeon kuah, usus pedas diganti samgyeopsal — setiap pilihan punya alasan. Bukan benci pedas, tapi tubuh dulu. Tipe lidah damai yang pilih yang mild sepanjang 12 ronde.",
    }),
    emotionTemperature: localeMap({
      ko: "0~1점",
      en: "0–1 pts",
      ja: "0~1点",
      'zh-CN': "0~1分",
      'zh-TW': "0~1分",
      vi: "0~1 điểm",
      id: "0–1 poin",
    }),
    emotionColor: localeMap({
      ko: "소화기 천사형",
      en: "Digestive Angel",
      ja: "消化器天使型",
      'zh-CN': "消化天使型",
      'zh-TW': "消化天使型",
      vi: "Thiên thần tiêu hóa",
      id: "Malaikat pencernaan",
    }),
    emotionKeywords: localeMap({
      ko: "순한맛·국물·보양·담백·배 걱정",
      en: "Mild · Broth · Tonic · Light · Stomach care",
      ja: "マイルド · スープ · 滋養 · あっさり · お腹心配",
      'zh-CN': "清淡·汤·滋补·朴素·护胃",
      'zh-TW': "清淡·湯·滋補·樸素·護胃",
      vi: "Nhẹ · Nước dùng · Bồi bổ · Thanh · Lo dạ dày",
      id: "Ringan · Kuah · Suplemen · Gurih · Jaga perut",
    }),
    strengthAtTemp: localeMap({
      ko: "\"나중에 속 안 쓰릴까?\", \"이거 맵지 않지?\"",
      en: "\"Will my stomach hurt later?\", \"This isn't too spicy, right?\"",
      ja: "「後でお腹痛くならないかな」「これ辛くないよね？」",
      'zh-CN': "“等会儿胃会不会难受？”“这个不辣吧？”",
      'zh-TW': "「等會兒胃會不會難受？」「這個不辣吧？」",
      vi: "\"Sau này dạ dày có đau không nhỉ?\", \"Cái này không cay lắm đúng không?\"",
      id: "\"Nanti perut sakit nggak ya?\", \"Ini nggak terlalu pedas kan?\"",
    }),
    charmAtTemp: localeMap({
      ko: "빈속에 마라탕. 자기 전에 불닭. 숙취 상태에서 짬뽕",
      en: "Mala hot pot on an empty stomach. Buldak before bed. Jjamppong with a hangover",
      ja: "空腹でマーラータン。寝る前にプルダック。二日酔いでチャンポン",
      'zh-CN': "空腹吃麻辣烫。睡前吃火鸡面。宿醉喝海鲜辣汤",
      'zh-TW': "空腹吃麻辣燙。睡前吃火雞麵。宿醉喝海鮮辣湯",
      vi: "Lẩu mala lúc đói. Buldak trước khi ngủ. Jjamppong khi say xỉn",
      id: "Mala hot pot perut kosong. Buldak sebelum tidur. Jjamppong saat mabuk",
    }),
    comfortableSpace: localeMap({
      ko: "순두부집·삼계탕집·일본 우동집·순한 국물 전문점",
      en: "Soft tofu spots · Samgyetang houses · Udon shops · Mild broth specialists",
      ja: "スンドゥブ店 · サムゲタン店 · うどん店 · あっさりスープ専門店",
      'zh-CN': "嫩豆腐锅店·参鸡汤店·乌冬面店·清淡汤专门店",
      'zh-TW': "嫩豆腐鍋店·參雞湯店·烏龍麵店·清淡湯專門店",
      vi: "Quán canh đậu phụ · Quán samgyetang · Quán udon · Quán nước dùng nhẹ",
      id: "Restoran sup tahu · Samgyetang · Udon · Kuah ringan",
    }),
    colorCodes: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    certificationPhrase: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    oneLiner: localeMap({
      ko: "속 편한 음식이 최고라는 것을 아는 사람은 나이가 들수록 현명해집니다. 당신은 이미 현명합니다",
      en: "People who know gentle food is best grow wiser with age. You're already wise.",
      ja: "お腹に優しい食べ物が最高だと知る人は年を取るほど賢くなる。あなたはもう賢い。",
      'zh-CN': "知道温和食物最好的人越活越明智。你已经很明智了。",
      'zh-TW': "知道溫和食物最好的人越活越明智。你已經很明智了。",
      vi: "Biết đồ ăn dịu dạ dày là nhất thì càng lớn càng khôn. Bạn đã khôn rồi.",
      id: "Yang tahu makanan lembut itu terbaik makin tua makin bijak. Kamu sudah bijak.",
    }),
    shareLine: localeMap({
      ko: "음식 극한 밸런스 결과: 소화기 천사형 🌸 마라탕 대신 순두부 다 골랐음... 배 걱정이 먼저인 거 맞음 ㅋㅋ → 어떻게 그걸 골라?! 친구랑 비교해봐",
      en: "Food Extreme Balance result: Digestive Angel 🌸 Picked soft tofu over mala every time... stomach worry first, right? lol → how did you pick THAT?! compare with a friend",
      ja: "食べ物極限バランス結果：消化器天使型 🌸 マーラーよりスンドゥブ全部選んだ…お腹心配が先でしょ 笑 → なんでそれ選んだの?! 友達と比べて",
      'zh-CN': "食物极限平衡结果：消化天使型 🌸 麻辣烫全换嫩豆腐锅…胃优先没错吧 哈哈 → 你怎么选那个?! 和好友比比",
      'zh-TW': "食物極限平衡結果：消化天使型 🌸 麻辣燙全換嫩豆腐鍋…胃優先沒錯吧 哈哈 → 你怎麼選那個?! 和好友比比",
      vi: "Kết quả cân bằng thực phẩm cực hạn: Thiên thần tiêu hóa 🌸 Chọn canh đậu phụ thay mala hết... lo dạ dày trước đúng không haha → sao mày chọn cái đó?! so với bạn bè",
      id: "Hasil balance game makanan ekstrem: Malaikat pencernaan 🌸 Pilih sup tahu bukan mala terus... perut dulu kan lol → kok pilih ITU?! bandingkan dengan teman",
    }),
  },
  {
    type: 'Type2',
    emoji: '🍚',
    temperatureCelsius: 2,
    accentColor: '#A67B5B',
    title: localeMap({
      ko: "건강과 맛을 함께 생각하는 사람, 담백 미식가형",
      en: "Health and Taste Together — Light Gourmet Type",
      ja: "健康と味を一緒に考える人 — あっさりグルメ型",
      'zh-CN': "兼顾健康与味道的人——清淡美食家型",
      'zh-TW': "兼顧健康與味道的人——清淡美食家型",
      vi: "Cân bằng sức khỏe và hương vị — Kiểu sành ăn thanh nhẹ",
      id: "Pikir kesehatan dan rasa — Tipe gourmet ringan",
    }),
    shortDescription: localeMap({
      ko: "당신은 매운 것의 유혹을 알면서도 결국 담백한 쪽으로 손이 갑니다. 입은 매운 것을 원해도 몸이 먼저입니다.",
      en: "You know spicy temptation but usually reach for something light. Your mouth wants heat; your body comes first.",
      ja: "辛さの誘惑は分かっていても、結局あっさり側に手が伸びる。口は辛いものを欲しても体が先だ。",
      'zh-CN': "你知道辣的诱惑，但手最终还是伸向清淡。嘴想要辣，身体优先。",
      'zh-TW': "你知道辣的誘惑，但手最終還是伸向清淡。嘴想要辣，身體優先。",
      vi: "Biết cám dỗ của đồ cay nhưng tay vẫn chọn món thanh. Miệng muốn cay, cơ thể lên trước.",
      id: "Tahu godaan pedas tapi tangan pilih yang ringan. Mulut mau pedas, tubuh dulu.",
    }),
    description: localeMap({
      ko: "몇 가지 자극적인 선택을 했지만 결국 대부분은 순한 쪽입니다. 매운 것도 먹지만 기준이 있고 몸 상태에 따라 선택이 달라지는 균형 감각이 있는 식성입니다.",
      en: "You picked a few bold options, but mostly mild ones. You eat spicy food too — with standards, depending on how you feel. A balanced appetite.",
      ja: "いくつか刺激を選んだが、結局ほとんどはマイルド。辛いものも食べるが基準があり、体調で選び方が変わるバランス感覚のある食性。",
      'zh-CN': "选过几次刺激款，但大多还是温和。也会吃辣，但有标准，随身体状态而变。平衡的食性。",
      'zh-TW': "選過幾次刺激款，但大多還是溫和。也會吃辣，但有標準，隨身體狀態而變。平衡的食性。",
      vi: "Chọn vài món mạnh nhưng phần lớn vẫn nhẹ. Vẫn ăn cay nhưng có tiêu chuẩn, tùy cơ thể. Kiểu ăn cân bằng.",
      id: "Pilih beberapa yang berani tapi kebanyakan mild. Tetap makan pedas dengan standar, sesuai kondisi tubuh. Selera seimbang.",
    }),
    emotionTemperature: localeMap({
      ko: "2~3점",
      en: "2–3 pts",
      ja: "2~3点",
      'zh-CN': "2~3分",
      'zh-TW': "2~3分",
      vi: "2~3 điểm",
      id: "2–3 poin",
    }),
    emotionColor: localeMap({
      ko: "담백 미식가형",
      en: "Light Gourmet",
      ja: "あっさりグルメ型",
      'zh-CN': "清淡美食家型",
      'zh-TW': "清淡美食家型",
      vi: "Sành ăn thanh nhẹ",
      id: "Gourmet ringan",
    }),
    emotionKeywords: localeMap({
      ko: "담백·균형·건강·선택적 자극·맛집 탐방",
      en: "Light · Balance · Health · Selective spice · Foodie tours",
      ja: "あっさり · バランス · 健康 · 選択的刺激 · グルメ巡り",
      'zh-CN': "清淡·平衡·健康·选择性刺激·探店",
      'zh-TW': "清淡·平衡·健康·選擇性刺激·探店",
      vi: "Thanh · Cân bằng · Sức khỏe · Cay có chọn lọc · Săn quán",
      id: "Ringan · Seimbang · Sehat · Pedas selektif · Jelajah kuliner",
    }),
    strengthAtTemp: localeMap({
      ko: "\"오늘은 담백하게 먹어야겠다\", \"다음엔 매운 거 먹어야지\"",
      en: "\"Let's eat light today\", \"Next time I'll get something spicy\"",
      ja: "「今日はあっさり食べよう」「次は辛いの食べなきゃ」",
      'zh-CN': "“今天得清淡点”“下次要吃辣的”",
      'zh-TW': "「今天得清淡點」「下次要吃辣的」",
      vi: "\"Hôm nay ăn thanh thôi\", \"Lần sau phải ăn cay\"",
      id: "\"Hari ini makan ringan aja\", \"Besok harus pedas\"",
    }),
    charmAtTemp: localeMap({
      ko: "재료의 질, 국물의 깊이, 과하지 않은 간",
      en: "Ingredient quality, broth depth, seasoning that isn't overdone",
      ja: "素材の質、スープの深み、控えめな味付け",
      'zh-CN': "食材品质、汤的深度、不过度的调味",
      'zh-TW': "食材品質、湯的深度、不過度的調味",
      vi: "Chất nguyên liệu, độ sâu nước dùng, nêm vừa phải",
      id: "Kualitas bahan, kedalaman kuah, bumbu tidak berlebihan",
    }),
    comfortableSpace: localeMap({
      ko: "전통 한식·일식 코스·깔끔한 국물 전문점",
      en: "Traditional Korean · Japanese course · Clean broth spots",
      ja: "伝統韓国料理 · 日本コース · あっさりスープ専門店",
      'zh-CN': "传统韩餐·日料套餐·清爽汤专门店",
      'zh-TW': "傳統韓餐·日料套餐·清爽湯專門店",
      vi: "Hàn truyền thống · Omakase Nhật · Quán nước dùng thanh",
      id: "Korea tradisional · Kursus Jepang · Kuah bersih",
    }),
    colorCodes: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    certificationPhrase: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    oneLiner: localeMap({
      ko: "담백한 것의 맛을 아는 사람은 음식을 진짜로 먹을 줄 아는 사람입니다",
      en: "Those who know the taste of light food truly know how to eat.",
      ja: "あっさりの味を知る人は、本当に食べ物を食べられる人だ。",
      'zh-CN': "懂得清淡之味的人，才真正会吃。",
      'zh-TW': "懂得清淡之味的人，才真正會吃。",
      vi: "Biết vị thanh mới thật sự biết ăn.",
      id: "Yang tahu rasa ringan benar-benar tahu makan.",
    }),
    shareLine: localeMap({
      ko: "음식 극한 밸런스 결과: 담백 미식가형 🍚 대부분 순한 거 골랐는데 마라탕 하나는 못 참음 ㅋㅋ → 어떻게 그걸 골라?! 음식 취향 비교해봐",
      en: "Food Extreme Balance result: Light Gourmet 🍚 Mostly mild picks but couldn't skip mala lol → how did you pick THAT?! compare food tastes",
      ja: "食べ物極限バランス結果：あっさりグルメ型 🍚 だいたいマイルドだけどマーラー一つは我慢できない 笑 → なんでそれ?! 食の好み比べて",
      'zh-CN': "食物极限平衡结果：清淡美食家 🍚 大多选清淡但麻辣烫忍不住 哈哈 → 你怎么选那个?! 比比口味",
      'zh-TW': "食物極限平衡結果：清淡美食家 🍚 大多選清淡但麻辣燙忍不住 哈哈 → 你怎麼選那個?! 比比口味",
      vi: "Kết quả cân bằng thực phẩm: Sành ăn thanh 🍚 Phần lớn chọn nhẹ nhưng mala một cái không cưỡng được haha → sao chọn cái đó?! so khẩu vị",
      id: "Hasil balance game makanan: Gourmet ringan 🍚 Kebanyakan mild tapi mala satu nggak tahan lol → kok pilih ITU?! bandingkan selera",
    }),
  },
  {
    type: 'Type3',
    emoji: '⚖️',
    temperatureCelsius: 5,
    accentColor: '#D97706',
    title: localeMap({
      ko: "뭐든 잘 먹는 사람, 균형 미각형",
      en: "Eats Everything Well — Balanced Palate Type",
      ja: "何でもよく食べる人 — バランス味覚型",
      'zh-CN': "什么都吃的人——平衡味觉型",
      'zh-TW': "什麼都吃的人——平衡味覺型",
      vi: "Ăn gì cũng được — Kiểu vị giác cân bằng",
      id: "Makan apa saja — Tipe lidah seimbang",
    }),
    shortDescription: localeMap({
      ko: "당신의 입맛에는 경계가 없습니다. 순두부도 마라탕도, 물냉면도 불냉면도 다 좋습니다.",
      en: "Your palate has no borders. Soft tofu or mala, mild or spicy cold noodles — all good.",
      ja: "あなたの口には境界がない。スンドゥブもマーラーも、水冷麺も激辛冷麺も全部いい。",
      'zh-CN': "你的口味没有边界。嫩豆腐锅和麻辣烫、水冷面和辣冷面都好。",
      'zh-TW': "你的口味沒有邊界。嫩豆腐鍋和麻辣燙、水冷麵和辣冷麵都好。",
      vi: "Khẩu vị không ranh giới. Canh đậu phụ hay mala, naengmyeon nước hay cay — đều ngon.",
      id: "Lidah tanpa batas. Sup tahu atau mala, naengmyeon kuah atau pedas — semua enak.",
    }),
    description: localeMap({
      ko: "어떤 식당에 가도 불평이 없고 어떤 음식을 먹어도 만족할 수 있는 타입입니다. 가장 함께 밥 먹기 좋은 사람이기도 합니다.",
      en: "You don't complain at any restaurant and can enjoy any dish. The best person to eat with.",
      ja: "どんな店でも文句がなく、どんな料理でも満足できるタイプ。一緒に食べるのが一番楽しい人でもある。",
      'zh-CN': "去什么店都不抱怨，吃什么都能满足。最适合一起吃饭的人。",
      'zh-TW': "去什麼店都不抱怨，吃什麼都能滿足。最適合一起吃飯的人。",
      vi: "Đi quán nào cũng không phàn nàn, ăn gì cũng hài lòng. Người ăn cùng tuyệt nhất.",
      id: "Ke restoran mana pun nggak komplain, makan apa pun puas. Teman makan terbaik.",
    }),
    emotionTemperature: localeMap({
      ko: "4~6점",
      en: "4–6 pts",
      ja: "4~6点",
      'zh-CN': "4~6分",
      'zh-TW': "4~6分",
      vi: "4~6 điểm",
      id: "4–6 poin",
    }),
    emotionColor: localeMap({
      ko: "균형 미각형",
      en: "Balanced Palate",
      ja: "バランス味覚型",
      'zh-CN': "平衡味觉型",
      'zh-TW': "平衡味覺型",
      vi: "Vị giác cân bằng",
      id: "Lidah seimbang",
    }),
    emotionKeywords: localeMap({
      ko: "다 좋음·올라운더·적응력·배 안 가림",
      en: "All good · All-rounder · Adaptable · Strong stomach",
      ja: "全部OK · オールラウンダー · 適応力 · 鉄の胃",
      'zh-CN': "都好·全能·适应力·铁胃",
      'zh-TW': "都好·全能·適應力·鐵胃",
      vi: "Gì cũng được · Đa năng · Thích nghi · Dạ dày khỏe",
      id: "Semua OK · All-rounder · Adaptif · Perut kuat",
    }),
    strengthAtTemp: localeMap({
      ko: "\"저는 다 잘 먹어요\", \"아무데나 좋아요\"",
      en: "\"I eat everything\", \"Any place is fine\"",
      ja: "「何でも食べられます」「どこでもいいです」",
      'zh-CN': "“我什么都吃”“去哪都行”",
      'zh-TW': "「我什麼都吃」「去哪都行」",
      vi: "\"Tôi ăn gì cũng được\", \"Quán nào cũng OK\"",
      id: "\"Aku makan apa aja\", \"Ke mana aja oke\"",
    }),
    charmAtTemp: localeMap({
      ko: "분위기와 함께하는 사람",
      en: "Someone who values the vibe and company",
      ja: "雰囲気と一緒にいる人を大切にする",
      'zh-CN': "重视氛围和同行的人",
      'zh-TW': "重視氛圍和同行的人",
      vi: "Coi trọng không khí và người đi cùng",
      id: "Menghargai suasana dan teman makan",
    }),
    comfortableSpace: localeMap({
      ko: "어디든. 진짜로",
      en: "Anywhere. Seriously.",
      ja: "どこでも。マジで。",
      'zh-CN': "哪里都行。真的。",
      'zh-TW': "哪裡都行。真的。",
      vi: "Ở đâu cũng được. Thật đấy.",
      id: "Di mana saja. Serius.",
    }),
    colorCodes: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    certificationPhrase: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    oneLiner: localeMap({
      ko: "뭐든 잘 먹는 사람이 가장 행복한 사람입니다. 그리고 함께 밥 먹기 가장 좋은 사람입니다",
      en: "People who eat everything well are the happiest — and the best to dine with.",
      ja: "何でもよく食べる人が一番幸せな人。そして一緒に食べるのが一番いい人。",
      'zh-CN': "什么都吃的人最幸福，也最适合一起吃饭。",
      'zh-TW': "什麼都吃的人最幸福，也最適合一起吃飯。",
      vi: "Ai ăn gì cũng ngon là người hạnh phúc nhất — và ăn cùng tuyệt nhất.",
      id: "Yang makan apa saja enak paling bahagia — dan paling enak diajak makan.",
    }),
    shareLine: localeMap({
      ko: "음식 극한 밸런스 결과: 균형 미각형 ⚖️ 딱 반반 나옴... 뭐든 잘 먹는 거 맞음 → 어떻게 그걸 골라?! 음식 취향 충돌 보장",
      en: "Food Extreme Balance result: Balanced Palate ⚖️ Pretty much 50/50... eats everything, right? → how did you pick THAT?! taste clash guaranteed",
      ja: "食べ物極限バランス結果：バランス味覚型 ⚖️ 半々…何でも食べるでしょ → なんでそれ?! 食の衝突保証",
      'zh-CN': "食物极限平衡结果：平衡味觉 ⚖️ 刚好一半一半…什么都吃对吧 → 你怎么选那个?! 口味冲突保证",
      'zh-TW': "食物極限平衡結果：平衡味覺 ⚖️ 剛好一半一半…什麼都吃對吧 → 你怎麼選那個?! 口味衝突保證",
      vi: "Kết quả cân bằng thực phẩm: Vị giác cân bằng ⚖️ Gần 50/50... ăn gì cũng được đúng không → sao chọn cái đó?! đụng khẩu vị chắc chắn",
      id: "Hasil balance game makanan: Lidah seimbang ⚖️ Hampir 50/50... makan apa aja kan → kok pilih ITU?! bentrokan selera dijamin",
    }),
  },
  {
    type: 'Type4',
    emoji: '🌶️',
    temperatureCelsius: 8,
    accentColor: '#E63946',
    title: localeMap({
      ko: "매운 것을 즐기는 사람, 자극 추구 먹방 러버형",
      en: "Loves Spice — Thrill-Seeking Foodie Type",
      ja: "辛いものを楽しむ人 — 刺激追求グルメ型",
      'zh-CN': "享受辣味的人——刺激追求吃播爱好者型",
      'zh-TW': "享受辣味的人——刺激追求吃播愛好者型",
      vi: "Thích đồ cay — Kiểu foodie săn kích thích",
      id: "Suka pedas — Tipe foodie pencari sensasi",
    }),
    shortDescription: localeMap({
      ko: "당신에게 음식의 재미는 자극입니다. 맵고 강렬한 것 앞에서 눈이 빛납니다.",
      en: "The fun of food is stimulation for you. Your eyes light up at bold, spicy flavors.",
      ja: "あなたにとって食べ物の楽しさは刺激。辛くて強烈なものの前で目が輝く。",
      'zh-CN': "对你而言，食物的乐趣在于刺激。面对又辣又猛的，眼睛会发光。",
      'zh-TW': "對你而言，食物的樂趣在於刺激。面對又辣又猛的，眼睛會發光。",
      vi: "Với bạn, vui ăn uống là kích thích. Gặp đồ cay mạnh là mắt sáng lên.",
      id: "Bagimu, seru makan itu sensasi. Lihat pedas kuat, mata langsung berbinar.",
    }),
    description: localeMap({
      ko: "마라탕·불냉면·짬뽕을 고른 라운드가 더 많은 타입입니다. 매운 것이 힘들어도 참고 먹는 게 아니라 진짜로 좋아해서 먹는 사람입니다.",
      en: "You picked mala, spicy cold noodles, and jjamppong more often. You don't endure spice — you genuinely love it.",
      ja: "マーラー・激辛冷麺・チャンポンを選んだラウンドが多いタイプ。辛さに我慢しているのではなく、本当に好きで食べる人。",
      'zh-CN': "选麻辣烫、辣冷面、海鲜辣汤面的轮次更多。不是硬撑辣，而是真的喜欢。",
      'zh-TW': "選麻辣燙、辣冷麵、海鮮辣湯麵的輪次更多。不是硬撐辣，而是真的喜歡。",
      vi: "Chọn mala, naengmyeon cay, jjamppong nhiều hơn. Không chịu đựng cay mà thật sự thích.",
      id: "Lebih sering pilih mala, naengmyeon pedas, jjamppong. Bukan tahan pedas — memang suka.",
    }),
    emotionTemperature: localeMap({
      ko: "7~9점",
      en: "7–9 pts",
      ja: "7~9点",
      'zh-CN': "7~9分",
      'zh-TW': "7~9分",
      vi: "7~9 điểm",
      id: "7–9 poin",
    }),
    emotionColor: localeMap({
      ko: "자극 추구형",
      en: "Thrill-Seeker",
      ja: "刺激追求型",
      'zh-CN': "刺激追求型",
      'zh-TW': "刺激追求型",
      vi: "Săn kích thích",
      id: "Pencari sensasi",
    }),
    emotionKeywords: localeMap({
      ko: "매운맛·자극·먹방·도전·화끈함",
      en: "Spicy · Thrill · Mukbang · Challenge · Heat",
      ja: "辛さ · 刺激 · モッパン · 挑戦 · 火照り",
      'zh-CN': "辣味·刺激·吃播·挑战·火辣",
      'zh-TW': "辣味·刺激·吃播·挑戰·火辣",
      vi: "Cay · Kích thích · Mukbang · Thử thách · Nóng rực",
      id: "Pedas · Sensasi · Mukbang · Tantangan · Panas",
    }),
    strengthAtTemp: localeMap({
      ko: "\"여기 제일 매운 거 주세요\", \"이거 진짜 맵지 않네?\"",
      en: "\"Give me the spiciest thing here\", \"This isn't even that spicy?\"",
      ja: "「ここで一番辛いのください」「これ本当に辛くないね？」",
      'zh-CN': "“给我最辣的”“这真的不辣吧？”",
      'zh-TW': "「給我最辣的」「這真的不辣吧？」",
      vi: "\"Cho món cay nhất đi\", \"Cái này có cay đâu?\"",
      id: "\"Yang paling pedas dong\", \"Ini nggak pedas banget?\"",
    }),
    charmAtTemp: localeMap({
      ko: "매운맛 단계 표시",
      en: "Spice level labels on the menu",
      ja: "辛さレベル表示",
      'zh-CN': "辣度等级标注",
      'zh-TW': "辣度等級標註",
      vi: "Bảng cấp độ cay",
      id: "Label tingkat pedas",
    }),
    comfortableSpace: localeMap({
      ko: "마라탕·불닭 전문점·매운 짬뽕집·엽기 음식 전문점",
      en: "Mala hot pot · Buldak spots · Spicy jjamppong · Extreme food shops",
      ja: "マーラータン · プルダック専門店 · 激辛チャンポン · 過激グルメ店",
      'zh-CN': "麻辣烫·火鸡面专门店·辣海鲜面·变态美食店",
      'zh-TW': "麻辣燙·火雞麵專門店·辣海鮮麵·變態美食店",
      vi: "Lẩu mala · Quán buldak · Jjamppong cay · Quán đồ cực hạn",
      id: "Mala · Buldak · Jjamppong pedas · Toko makanan ekstrem",
    }),
    colorCodes: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    certificationPhrase: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    oneLiner: localeMap({
      ko: "매운 것을 즐긴다는 것은 삶의 자극을 즐긴다는 것과 비슷합니다. 당신은 강한 것을 두려워하지 않는 사람입니다",
      en: "Enjoying spice is like enjoying life's thrills. You don't fear intensity.",
      ja: "辛いものを楽しむことは、人生の刺激を楽しむことに似ている。あなたは強いものを恐れない人だ。",
      'zh-CN': "享受辣味就像享受生活的刺激。你不害怕强烈的东西。",
      'zh-TW': "享受辣味就像享受生活的刺激。你不害怕強烈的東西。",
      vi: "Thích cay giống thích kích thích cuộc sống. Bạn không sợ mạnh mẽ.",
      id: "Nikmati pedas seperti nikmati sensasi hidup. Kamu tidak takut intensitas.",
    }),
    shareLine: localeMap({
      ko: "음식 극한 밸런스 결과: 자극 추구형 🌶️ 불냉면·마라탕·짬뽕 다 골랐음... 매운 것 없으면 밥 먹은 것 같지 않은 거 맞음 → 어떻게 그걸 골랐어?!",
      en: "Food Extreme Balance result: Thrill-Seeker 🌶️ Picked spicy cold noodles, mala, jjamppong... no spice = didn't really eat, right? → how did you pick THAT?!",
      ja: "食べ物極限バランス結果：刺激追求型 🌶️ 激辛冷麺・マーラー・チャンポン全部…辛くないと食べた気しないでしょ → なんでそれ?!",
      'zh-CN': "食物极限平衡结果：刺激追求 🌶️ 辣冷面·麻辣烫·辣汤面全选…不辣像没吃饭对吧 → 你怎么选那个?!",
      'zh-TW': "食物極限平衡結果：刺激追求 🌶️ 辣冷麵·麻辣燙·辣湯麵全選…不辣像沒吃飯對吧 → 你怎麼選那個?!",
      vi: "Kết quả cân bằng thực phẩm: Săn kích thích 🌶️ Chọn naengmyeon cay, mala, jjamppong... không cay như chưa ăn đúng không → sao chọn cái đó?!",
      id: "Hasil balance game makanan: Pencari sensasi 🌶️ Pilih naengmyeon pedas, mala, jjamppong... nggak pedas kayak belum makan kan → kok pilih ITU?!",
    }),
  },
  {
    type: 'Type5',
    emoji: '🔥',
    temperatureCelsius: 10,
    accentColor: '#FF4500',
    title: localeMap({
      ko: "매운 것 없이는 밥을 못 먹는 사람, 극강 매운맛파",
      en: "Can't Eat Without Spice — Ultra Spicy Type",
      ja: "辛くないとご飯が食べられない人 — 最強辛党",
      'zh-CN': "无辣不下饭的人——超强辣党",
      'zh-TW': "無辣不下飯的人——超強辣黨",
      vi: "Không cay không ăn được — Kiểu cực cay",
      id: "Nggak pedas nggak bisa makan — Tipe ultra pedas",
    }),
    shortDescription: localeMap({
      ko: "당신에게 순한 음식은 밋밋합니다. 매운 것이 없으면 밥을 먹은 것 같지 않습니다.",
      en: "Mild food feels bland to you. Without spice, it doesn't feel like you ate.",
      ja: "あなたにとってマイルドは物足りない。辛くないと食べた気がしない。",
      'zh-CN': "清淡对你来说太寡淡。不辣就像没吃饭。",
      'zh-TW': "清淡對你來說太寡淡。不辣就像沒吃飯。",
      vi: "Món nhẹ với bạn là nhạt. Không cay như chưa ăn cơm.",
      id: "Makanan ringan terasa hambar. Tanpa pedas kayak belum makan.",
    }),
    description: localeMap({
      ko: "거의 모든 라운드에서 자극적인 쪽을 선택했습니다. 마라탕·불닭 닭발·불냉면·엽기 떡볶이·불곱창·불닭볶음면이 일상인 사람입니다. 이 정도면 매운맛 내성이 특급입니다.",
      en: "You picked the bold side in almost every round. Mala, spicy chicken feet, spicy cold noodles, extreme tteokbokki, spicy intestines, buldak — your daily menu. Elite spice tolerance.",
      ja: "ほぼ全ラウンドで刺激側を選択。マーラー・激辛チキンフィート・激辛冷麺・過激トッポッキ・激辛ホットプ・プルダックが日常。このレベルなら辛さ耐性は特級。",
      'zh-CN': "几乎每轮都选刺激款。麻辣烫、超辣鸡爪、辣冷面、变态辣炒年糕、辣烤牛肠、火鸡面是日常。这级别算特辣耐受。",
      'zh-TW': "幾乎每輪都選刺激款。麻辣燙、超辣雞爪、辣冷麵、變態辣炒年糕、辣烤牛腸、火雞麵是日常。這級別算特辣耐受。",
      vi: "Gần như mọi vòng chọn món mạnh. Mala, chân gà cay, naengmyeon cay, tteokbokki siêu cay, lòng bò cay, buldak — thường ngày. Chịu cay cấp đặc.",
      id: "Hampir semua ronde pilih yang berani. Mala, kaki ayam pedas, naengmyeon pedas, tteokbokki ekstrem, usus pedas, buldak — sehari-hari. Toleransi pedas elite.",
    }),
    emotionTemperature: localeMap({
      ko: "10~11점",
      en: "10–11 pts",
      ja: "10~11点",
      'zh-CN': "10~11分",
      'zh-TW': "10~11分",
      vi: "10~11 điểm",
      id: "10–11 poin",
    }),
    emotionColor: localeMap({
      ko: "극강 매운맛파",
      en: "Ultra Spicy",
      ja: "最強辛党",
      'zh-CN': "超强辣党",
      'zh-TW': "超強辣黨",
      vi: "Cực cay",
      id: "Ultra pedas",
    }),
    emotionKeywords: localeMap({
      ko: "매운맛 의존·자극 중독·불닭·마라·극한",
      en: "Spice dependency · Stimulation addiction · Buldak · Mala · Extreme",
      ja: "辛さ依存 · 刺激中毒 · プルダック · マーラー · 極限",
      'zh-CN': "辣依赖·刺激成瘾·火鸡面·麻辣·极限",
      'zh-TW': "辣依賴·刺激成癮·火雞麵·麻辣·極限",
      vi: "Phụ thuộc cay · Nghiện kích thích · Buldak · Mala · Cực hạn",
      id: "Ketergantungan pedas · Kecanduan sensasi · Buldak · Mala · Ekstrem",
    }),
    strengthAtTemp: localeMap({
      ko: "\"이게 맵다고?\", \"청양고추 더 주세요\"",
      en: "\"This is spicy?\", \"More chili peppers, please\"",
      ja: "「これが辛いの？」「唐辛子もっとください」",
      'zh-CN': "“这算辣？”“再加青阳辣椒”",
      'zh-TW': "「這算辣？」「再加青陽辣椒」",
      vi: "\"Cái này cay à?\", \"Cho thêm ớt đi\"",
      id: "\"Ini pedas?\", \"Tambah cabe rawit dong\"",
    }),
    charmAtTemp: localeMap({
      ko: "순한 음식만 파는 식당, 배 아플 때도 매운 것이 당김",
      en: "Restaurants that only serve mild food; craving spice even with a stomachache",
      ja: "マイルドだけの店、お腹痛い時でも辛いものが欲しくなる",
      'zh-CN': "只卖清淡菜的店；胃疼时也想来点辣的",
      'zh-TW': "只賣清淡菜的店；胃疼時也想来点辣的",
      vi: "Quán chỉ bán món nhẹ; đau bụng vẫn thèm cay",
      id: "Restoran cuma jual ringan; perut sakit tetap pengen pedas",
    }),
    comfortableSpace: localeMap({
      ko: "마라탕·마라샹궈·불닭 전문점·엽기 떡볶이 전문점",
      en: "Mala hot pot · Mala xiang guo · Buldak · Extreme tteokbokki spots",
      ja: "マーラータン · マーラーシャングオ · プルダック · 過激トッポッキ専門店",
      'zh-CN': "麻辣烫·麻辣香锅·火鸡面专门店·变态辣炒年糕店",
      'zh-TW': "麻辣燙·麻辣香鍋·火雞麵專門店·變態辣炒年糕店",
      vi: "Lẩu mala · Mala xiang guo · Buldak · Tteokbokki siêu cay",
      id: "Mala hot pot · Mala xiang guo · Buldak · Tteokbokki ekstrem",
    }),
    colorCodes: localeMap({
      ko: "음식점에서 매운맛 추가 요청, 집에 항상 청양고추 구비",
      en: "Ask for extra spice at restaurants; always keep chili peppers at home",
      ja: "店で辛さ追加を頼む、家に常に唐辛子をストック",
      'zh-CN': "在餐厅要求加辣，家里常备青阳辣椒",
      'zh-TW': "在餐廳要求加辣，家裡常備青陽辣椒",
      vi: "Nhờ thêm cay ở quán, nhà luôn có ớt",
      id: "Minta tambah pedas di restoran, stok cabe di rumah",
    }),
    certificationPhrase: localeMap({
      ko: "",
      en: "",
      ja: "",
      'zh-CN': "",
      'zh-TW': "",
      vi: "",
      id: "",
    }),
    oneLiner: localeMap({
      ko: "당신은 일반인이 감당 못 하는 맛의 세계에 살고 있습니다. 그 세계에 오신 것을 환영합니다",
      en: "You live in a flavor world most people can't handle. Welcome.",
      ja: "あなたは一般人が耐えられない味の世界に住んでいる。その世界へようこそ。",
      'zh-CN': "你活在一般人受不了的味觉世界。欢迎到来。",
      'zh-TW': "你活在一般人受不了的味覺世界。歡迎到來。",
      vi: "Bạn sống trong thế giới vị mà người thường không chịu nổi. Chào mừng.",
      id: "Kamu hidup di dunia rasa yang kebanyakan orang nggak kuat. Selamat datang.",
    }),
    shareLine: localeMap({
      ko: "음식 극한 밸런스 결과: 극강 매운맛파 🔥 거의 다 자극적인 거 골랐음... 이게 안 맵다고?가 일상인 거 맞음 ㅋㅋ → 어떻게 그걸 골라?!",
      en: "Food Extreme Balance result: Ultra Spicy 🔥 Picked almost all bold options... \"not spicy?\" is daily life lol → how did you pick THAT?!",
      ja: "食べ物極限バランス結果：最強辛党 🔥 ほぼ全部刺激…「辛くない」が日常でしょ 笑 → なんでそれ?!",
      'zh-CN': "食物极限平衡结果：超强辣党 🔥 几乎全选刺激…“这不算辣？”是日常 哈哈 → 你怎么选那个?!",
      'zh-TW': "食物極限平衡結果：超強辣黨 🔥 幾乎全選刺激…「這不算辣？」是日常 哈哈 → 你怎麼選那個?!",
      vi: "Kết quả cân bằng thực phẩm: Cực cay 🔥 Gần như chọn mạnh hết... \"có cay đâu?\" là thường ngày haha → sao chọn cái đó?!",
      id: "Hasil balance game makanan: Ultra pedas 🔥 Hampir semua pilih berani... \"nggak pedas?\" sehari-hari lol → kok pilih ITU?!",
    }),
  },
  {
    type: 'Type6',
    emoji: '🌋',
    temperatureCelsius: 12,
    accentColor: '#8B0000',
    title: localeMap({
      ko: "자극 없인 살 수 없는 사람, 먹방 레전드 마스터형",
      en: "Can't Live Without Stimulation — Mukbang Legend Master",
      ja: "刺激なしでは生きられない人 — モッパンレジェンドマスター型",
      'zh-CN': "无刺激不能活的人——吃播传奇大师型",
      'zh-TW': "無刺激不能活的人——吃播傳奇大師型",
      vi: "Không kích thích không sống nổi — Kiểu huyền thoại mukbang",
      id: "Tanpa sensasi nggak hidup — Tipe legenda mukbang master",
    }),
    shortDescription: localeMap({
      ko: "12개 전부 자극적인 쪽을 선택했습니다. 당신의 위장은 철갑입니다.",
      en: "You picked the bold side in all 12 rounds. Your stomach is armor-plated.",
      ja: "12問すべて刺激側を選択。あなたの胃は鉄壁だ。",
      'zh-CN': "12题全部选了刺激款。你的胃是铁甲。",
      'zh-TW': "12題全部選了刺激款。你的胃是鐵甲。",
      vi: "Chọn món mạnh cả 12 vòng. Dạ dày bạn là thép.",
      id: "Pilih yang berani semua 12 ronde. Perutmu baja.",
    }),
    description: localeMap({
      ko: "순두부 대신 마라탕, 삼계탕 대신 불닭 닭발, 물냉면 대신 불냉면, 바닐라 아이스크림 대신 마라맛 아이스크림, 된장찌개 대신 마라샹궈까지 전부 선택했습니다. 이 결과를 보고 놀라지 않는 자신을 보며 확신이 생겼을 것입니다.",
      en: "Soft tofu → mala, samgyetang → spicy chicken feet, mild cold noodles → spicy cold noodles, vanilla ice cream → mala ice cream, doenjang stew → mala xiang guo — all of them. Seeing this result probably didn't surprise you at all.",
      ja: "スンドゥブよりマーラー、サムゲタンより激辛チキンフィート、水冷麺より激辛冷麺、バニラアイスよりマーラー味アイス、テンジャンチゲよりマーラーシャングオまで全部。この結果を見て驚かない自分に確信が湧いたはず。",
      'zh-CN': "嫩豆腐换麻辣烫、参鸡汤换超辣鸡爪、水冷面换辣冷面、香草冰淇淋换麻辣味冰淇淋、大酱汤换麻辣香锅——全选了。看到这个结果你不惊讶，反而更确信了。",
      'zh-TW': "嫩豆腐換麻辣燙、參雞湯換超辣雞爪、水冷麵換辣冷麵、香草冰淇淋換麻辣味冰淇淋、大醬湯換麻辣香鍋——全選了。看到這個結果不驚訝，反而更確信了。",
      vi: "Canh đậu phụ → mala, samgyetang → chân gà cay, naengmyeon nước → cay, kem vani → kem mala, doenjang → mala xiang guo — hết. Nhìn kết quả chắc bạn không ngạc nhiên mà càng tin.",
      id: "Sup tahu → mala, samgyetang → kaki ayam pedas, naengmyeon kuah → pedas, es vanila → es mala, doenjang → mala xiang guo — semua. Lihat hasil ini mungkin nggak kaget, malah yakin.",
    }),
    emotionTemperature: localeMap({
      ko: "12점",
      en: "12 pts",
      ja: "12点",
      'zh-CN': "12分",
      'zh-TW': "12分",
      vi: "12 điểm",
      id: "12 poin",
    }),
    emotionColor: localeMap({
      ko: "먹방 레전드 마스터",
      en: "Mukbang Legend Master",
      ja: "モッパンレジェンドマスター",
      'zh-CN': "吃播传奇大师",
      'zh-TW': "吃播傳奇大師",
      vi: "Huyền thoại mukbang",
      id: "Legenda mukbang master",
    }),
    emotionKeywords: localeMap({
      ko: "자극 그 자체·마라 전도사·불닭 마스터·먹방 레전드",
      en: "Stimulation itself · Mala evangelist · Buldak master · Mukbang legend",
      ja: "刺激そのもの · マーラー伝道師 · プルダックマスター · モッパンレジェンド",
      'zh-CN': "刺激本身·麻辣传教士·火鸡面大师·吃播传奇",
      'zh-TW': "刺激本身·麻辣傳教士·火雞麵大師·吃播傳奇",
      vi: "Kích thích thuần · Truyền giáo mala · Buldak master · Huyền thoại mukbang",
      id: "Sensasi murni · Penginjil mala · Buldak master · Legenda mukbang",
    }),
    strengthAtTemp: localeMap({
      ko: "\"이거 왜 이렇게 안 매워?\", \"마라 추가요\"",
      en: "\"Why isn't this spicier?\", \"Extra mala, please\"",
      ja: "「なんでこんなに辛くないの？」「マーラー追加で」",
      'zh-CN': "“怎么这么不辣？”“加麻辣”",
      'zh-TW': "「怎麼這麼不辣？」「加麻辣」",
      vi: "\"Sao không cay thế?\", \"Thêm mala đi\"",
      id: "\"Kok nggak pedas?\", \"Tambah mala dong\"",
    }),
    charmAtTemp: localeMap({
      ko: "마라탕·마라샹궈·불닭 세트를 한 자리에서 먹을 때",
      en: "Eating mala hot pot, mala xiang guo, and buldak in one sitting",
      ja: "マーラータン・マーラーシャングオ・プルダックセットを一気に食べる時",
      'zh-CN': "在一处吃完麻辣烫、麻辣香锅、火鸡面套餐时",
      'zh-TW': "在一處吃完麻辣燙、麻辣香鍋、火雞麵套餐時",
      vi: "Ăn một lúc cả mala, mala xiang guo và buldak",
      id: "Makan mala hot pot, mala xiang guo, dan buldak sekaligus",
    }),
    comfortableSpace: localeMap({
      ko: "마라탕·마라샹궈·불닭 전문점·엽기 음식 전문점",
      en: "Mala hot pot · Mala xiang guo · Buldak · Extreme food shops",
      ja: "マーラータン · マーラーシャングオ · プルダック · 過激グルメ店",
      'zh-CN': "麻辣烫·麻辣香锅·火鸡面专门店·变态美食店",
      'zh-TW': "麻辣燙·麻辣香鍋·火雞麵專門店·變態美食店",
      vi: "Lẩu mala · Mala xiang guo · Buldak · Quán đồ cực hạn",
      id: "Mala hot pot · Mala xiang guo · Buldak · Toko makanan ekstrem",
    }),
    colorCodes: localeMap({
      ko: "철갑. 일반인의 3배 매운맛 내성 추정",
      en: "Armor-plated. Estimated 3× normal spice tolerance",
      ja: "鉄壁。一般人の3倍の辛さ耐性と推定",
      'zh-CN': "铁甲。推测辣耐受为常人3倍",
      'zh-TW': "鐵甲。推測辣耐受為常人3倍",
      vi: "Thép. Chịu cay gấp 3 lần người thường (ước tính)",
      id: "Baja. Toleransi pedas 3× orang biasa (perkiraan)",
    }),
    certificationPhrase: localeMap({
      ko: "먹방 레전드 마스터 달성 🌋 12라운드 전부 자극 선택. 위장이 철갑입니다",
      en: "Mukbang Legend Master Achieved 🌋 Bold picks in all 12 rounds. Stomach is armor-plated",
      ja: "モッパンレジェンドマスター達成 🌋 12ラウンド全部刺激選択。胃は鉄壁",
      'zh-CN': "达成吃播传奇大师 🌋 12轮全选刺激。胃是铁甲",
      'zh-TW': "達成吃播傳奇大師 🌋 12輪全選刺激。胃是鐵甲",
      vi: "Đạt Huyền thoại mukbang 🌋 Chọn mạnh cả 12 vòng. Dạ dày là thép",
      id: "Legenda Mukbang Master Tercapai 🌋 Pilih berani semua 12 ronde. Perut baja",
    }),
    oneLiner: localeMap({
      ko: "당신의 위장은 이미 레전드입니다. 이 결과를 친구에게 보내세요. 경악하는 반응이 보장됩니다",
      en: "Your stomach is already legendary. Send this result to a friend — shock guaranteed.",
      ja: "あなたの胃はすでにレジェンド。この結果を友人に送って。驚愕の反応が保証される。",
      'zh-CN': "你的胃已是传奇。把这个结果发给好友——震惊反应保证。",
      'zh-TW': "你的胃已是傳奇。把這個結果發給好友——震驚反應保證。",
      vi: "Dạ dày bạn đã là huyền thoại. Gửi kết quả này cho bạn — phản ứng sốc chắc chắn.",
      id: "Perutmu sudah legenda. Kirim hasil ini ke teman — reaksi shock dijamin.",
    }),
    shareLine: localeMap({
      ko: "음식 극한 밸런스 결과: 먹방 레전드 마스터 🌋 12개 전부 자극 선택... 마라맛 아이스크림도 골랐음 → 어떻게 그걸 골라?! 충격 보장",
      en: "Food Extreme Balance result: Mukbang Legend Master 🌋 Bold picks all 12... even mala ice cream → how did you pick THAT?! shock guaranteed",
      ja: "食べ物極限バランス結果：モッパンレジェンドマスター 🌋 12問全部刺激…マーラー味アイスも → なんでそれ?! 衝撃保証",
      'zh-CN': "食物极限平衡结果：吃播传奇大师 🌋 12题全选刺激…麻辣味冰淇淋也选了 → 你怎么选那个?! 震惊保证",
      'zh-TW': "食物極限平衡結果：吃播傳奇大師 🌋 12題全選刺激…麻辣味冰淇淋也選了 → 你怎麼選那個?! 震驚保證",
      vi: "Kết quả cân bằng thực phẩm: Huyền thoại mukbang 🌋 Chọn mạnh cả 12... cả kem mala → sao chọn cái đó?! sốc chắc chắn",
      id: "Hasil balance game makanan: Legenda mukbang 🌋 Pilih berani semua 12... es krim mala juga → kok pilih ITU?! shock dijamin",
    }),
  },
];
