/** 나의 '외로움' 농도 테스트 — 12문항 4지선다, A=0 B=1 C=2 D=3, 총점 0~36 → Type1~6 */

type Locale = 'ko' | 'en' | 'ja' | 'zh-CN' | 'zh-TW' | 'vi' | 'id';
type ML = Record<Locale, string>;
function L(m: ML): Record<string, string> {
  return m;
}

export interface Phase3LonelinessConcentrationQuestion {
  id: number;
  question: Record<string, string>;
  options: { text: Record<string, string>; score: number }[];
}

export interface Phase3LonelinessConcentrationResult {
  type: string;
  emoji: string;
  title: Record<string, string>;
  shortDescription: Record<string, string>;
  description: Record<string, string>;
  concentration: Record<string, string>;
  currentState: Record<string, string>;
  strength: Record<string, string> | null;
  actions: Record<string, string>;
  community: Record<string, string>;
  crisisNote: Record<string, string> | null;
  oneLiner: Record<string, string> | null;
  shareSnippet: Record<string, string>;
}

export function calculatePhase3LonelinessConcentrationResult(answers: number[]): string {
  const total = answers.reduce((sum, s) => sum + (s ?? 0), 0);
  if (total <= 5) return 'Type1';
  if (total <= 11) return 'Type2';
  if (total <= 19) return 'Type3';
  if (total <= 27) return 'Type4';
  if (total <= 33) return 'Type5';
  return 'Type6';
}

export function getPhase3LonelinessConcentrationResultByType(
  type: string
): Phase3LonelinessConcentrationResult | undefined {
  return phase3LonelinessConcentrationResults.find((r) => r.type === type);
}

export const phase3LonelinessConcentrationQuestions: Phase3LonelinessConcentrationQuestion[] = [
  {
    id: 1,
    question: L({
      ko: '오늘 하루 중 \'이걸 누군가에게 말하고 싶다\'는 생각이 드는 빈도는?',
      en: 'How often today do you think, "I want to tell someone about this"?',
      ja: '今日一日で「これ、誰かに話したい」と思う頻度は？',
      'zh-CN': '今天一天里，你有多常冒出「好想把这件事告诉别人」的念头？',
      'zh-TW': '今天一天裡，你有多常冒出「好想把這件事告訴別人」的念頭？',
      vi: 'Trong ngày hôm nay, bạn nghĩ "Mình muốn kể điều này với ai đó" thường xuyên thế nào?',
      id: 'Seberapa sering hari ini kamu berpikir, "Aku ingin cerita ini ke seseorang"?',
    }),
    options: [
      {
        text: L({
          ko: '거의 없다. 나눌 것이 생기면 자연스럽게 나눈다',
          en: 'Almost never. When something\'s worth sharing, I share it naturally',
          ja: 'ほとんどない。分かち合いたいことがあれば自然に話す',
          'zh-CN': '几乎没有。有想分享的事就会自然地说出来',
          'zh-TW': '幾乎沒有。有想分享的事就會自然地說出來',
          vi: 'Hầu như không. Có gì muốn chia sẻ thì mình nói tự nhiên',
          id: 'Hampir tidak pernah. Kalau ada yang ingin dibagikan, aku bagikan secara alami',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '가끔 있다. 말할 사람이 있지만 바로 연락하진 않는다',
          en: 'Sometimes. I have people to talk to, but I don\'t reach out right away',
          ja: 'たまにある。話せる人はいるけどすぐには連絡しない',
          'zh-CN': '偶尔有。有能说的人，但不会马上联系',
          'zh-TW': '偶爾有。有能說的人，但不會馬上聯繫',
          vi: 'Thỉnh thoảng. Có người để nói nhưng mình không liên lạc ngay',
          id: 'Kadang-kadang. Ada orang untuk diajak bicara, tapi tidak langsung menghubungi',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '자주 있다. 말하고 싶은데 연락하기가 망설여진다',
          en: 'Often. I want to talk, but I hesitate to reach out',
          ja: 'よくある。話したいのに連絡するのがためらわれる',
          'zh-CN': '经常有。想说，但犹豫着不敢联系',
          'zh-TW': '經常有。想說，但猶豫著不敢聯繫',
          vi: 'Khá thường xuyên. Muốn nói nhưng ngại liên lạc',
          id: 'Sering. Ingin cerita tapi ragu untuk menghubungi',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '항상 있다. 말하고 싶은데 딱히 연락할 사람이 떠오르지 않는다',
          en: 'Always. I want to talk, but no one really comes to mind',
          ja: 'いつもそう。話したいのに連絡する人が思い浮かばない',
          'zh-CN': '总是这样。想说，但想不到能联系谁',
          'zh-TW': '總是這樣。想說，但想不到能聯繫誰',
          vi: 'Luôn luôn. Muốn nói nhưng chẳng nghĩ ra ai để liên lạc',
          id: 'Selalu. Ingin cerita tapi tidak ada orang yang terlintas di pikiran',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 2,
    question: L({
      ko: '좋은 일이 생겼을 때 나는?',
      en: 'When something good happens, I…',
      ja: 'いいことがあったとき、私は？',
      'zh-CN': '有好事发生时，我会？',
      'zh-TW': '有好事發生時，我會？',
      vi: 'Khi có chuyện vui xảy ra, mình sẽ?',
      id: 'Saat ada kabar baik, aku…',
    }),
    options: [
      {
        text: L({
          ko: '바로 연락할 사람이 떠오른다. 같이 기뻐할 사람이 있다',
          en: 'Someone to call comes to mind right away. I have people to celebrate with',
          ja: 'すぐ連絡する人が思い浮かぶ。一緒に喜んでくれる人がいる',
          'zh-CN': '马上就想到能联系的人。有人能一起开心',
          'zh-TW': '馬上就想到能聯繫的人。有人能一起開心',
          vi: 'Ngay lập tức nghĩ ra người để gọi. Có người cùng vui với mình',
          id: 'Langsung terlintas orang untuk dihubungi. Ada yang bisa merayakan bersamaku',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '연락할 사람이 있긴 한데 조금 고민하고 연락한다',
          en: 'I have people to contact, but I think a bit before reaching out',
          ja: '連絡する人はいるけど、少し迷ってから連絡する',
          'zh-CN': '有能联系的人，但会犹豫一下才联系',
          'zh-TW': '有能聯繫的人，但會猶豫一下才聯繫',
          vi: 'Có người để liên lạc, nhưng nghĩ một chút rồi mới nhắn',
          id: 'Ada orang untuk dihubungi, tapi sempat mikir dulu baru menghubungi',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '나눌 사람이 있을 것 같은데 막상 연락하기 애매하다',
          en: 'I feel like I should have someone to share with, but reaching out feels awkward',
          ja: '分かち合える人はいるはずなのに、いざ連絡するとなると微妙',
          'zh-CN': '感觉应该有能分享的人，但真要联系又很尴尬',
          'zh-TW': '感覺應該有能分享的人，但真要聯繫又很尷尬',
          vi: 'Hình như có người để chia sẻ, nhưng liên lạc thì lại ngại',
          id: 'Seharusnya ada orang untuk berbagi, tapi rasanya awkward untuk menghubungi',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '혼자 기뻐하고 만다. 딱히 바로 연락할 사람이 없다',
          en: 'I just celebrate alone. There\'s no one to contact right away',
          ja: '一人で喜んで終わる。すぐ連絡する人が特にいない',
          'zh-CN': '自己一个人高兴就完了。没什么能马上联系的人',
          'zh-TW': '自己一個人高興就完了。沒什麼能馬上聯繫的人',
          vi: 'Chỉ vui một mình. Không có ai để liên lạc ngay',
          id: 'Cuma senang sendiri. Tidak ada orang yang bisa langsung dihubungi',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 3,
    question: L({
      ko: '힘든 일이 생겼을 때 나는?',
      en: 'When something hard happens, I…',
      ja: 'つらいことがあったとき、私は？',
      'zh-CN': '遇到难事时，我会？',
      'zh-TW': '遇到難事時，我會？',
      vi: 'Khi gặp chuyện khó khăn, mình sẽ?',
      id: 'Saat ada masalah berat, aku…',
    }),
    options: [
      {
        text: L({
          ko: '믿을 수 있는 사람에게 털어놓는다. 들어주는 사람이 있다',
          en: 'I open up to someone I trust. There\'s someone who listens',
          ja: '信頼できる人に打ち明ける。聞いてくれる人がいる',
          'zh-CN': '向信任的人倾诉。有人愿意听',
          'zh-TW': '向信任的人傾訴。有人願意聽',
          vi: 'Tâm sự với người mình tin. Có người lắng nghe',
          id: 'Curhat ke orang yang dipercaya. Ada yang mau mendengarkan',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '이야기할 사람이 있긴 한데 부담 줄까봐 혼자 삭이는 경우가 많다',
          en: 'I have people to talk to, but I often bottle it up so I won\'t burden them',
          ja: '話せる人はいるけど、負担になるのが怖くて一人で飲み込むことが多い',
          'zh-CN': '有能说的人，但怕给人添麻烦，经常自己闷着',
          'zh-TW': '有能說的人，但怕給人添麻煩，經常自己悶著',
          vi: 'Có người để nói, nhưng hay tự nuốt vì sợ làm phiền họ',
          id: 'Ada orang untuk diajak bicara, tapi sering dipendam sendiri biar tidak merepotkan',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '누군가에게 말하고 싶지만 결국 대부분 혼자 감당한다',
          en: 'I want to tell someone, but I usually end up handling it alone',
          ja: '誰かに話したいけど、結局ほとんど一人で抱え込む',
          'zh-CN': '想跟谁说说，但最后大多还是自己扛',
          'zh-TW': '想跟誰說說，但最後大多還是自己扛',
          vi: 'Muốn nói với ai đó, nhưng cuối cùng hầu như tự gánh một mình',
          id: 'Ingin cerita ke seseorang, tapi akhirnya hampir selalu ditanggung sendiri',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '힘들어도 말할 곳이 없어서 항상 혼자 해결한다',
          en: 'Even when it\'s hard, I have nowhere to turn, so I always deal with it alone',
          ja: 'つらくても話す場所がなく、いつも一人で解決する',
          'zh-CN': '再难也没有地方说，总是自己解决',
          'zh-TW': '再難也沒有地方說，總是自己解決',
          vi: 'Dù khó cũng không có chỗ để nói, nên lúc nào cũng tự giải quyết',
          id: 'Meski berat, tidak ada tempat cerita, jadi selalu diselesaikan sendiri',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 4,
    question: L({
      ko: '단톡방이나 SNS 알림이 왔을 때 나는?',
      en: 'When group chat or SNS notifications come in, I…',
      ja: 'グループチャットやSNSの通知が来たとき、私は？',
      'zh-CN': '群聊或社交软件来通知时，我会？',
      'zh-TW': '群聊或社群通知來的時候，我會？',
      vi: 'Khi có thông báo group chat hoặc mạng xã hội, mình sẽ?',
      id: 'Saat ada notifikasi grup chat atau media sosial, aku…',
    }),
    options: [
      {
        text: L({
          ko: '자주 온다. 활발하게 주고받는 편이다',
          en: 'They come often. I chat back and forth pretty actively',
          ja: 'よく来る。活発にやり取りしている方',
          'zh-CN': '经常来。交流挺活跃的',
          'zh-TW': '經常來。交流挺活躍的',
          vi: 'Đến khá thường xuyên. Mình chat qua lại khá năng động',
          id: 'Sering datang. Aku cukup aktif balas-membalas',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '가끔 온다. 필요할 때 연락이 오는 정도다',
          en: 'Sometimes. Mostly when there\'s something needed',
          ja: 'たまに来る。必要なときに連絡が来る程度',
          'zh-CN': '偶尔来。基本是有事才会联系',
          'zh-TW': '偶爾來。基本是有事才會聯繫',
          vi: 'Thỉnh thoảng. Chủ yếu khi có việc mới liên lạc',
          id: 'Kadang-kadang. Biasanya hanya saat ada keperluan',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '별로 없다. 있어도 단체 알림이 대부분이다',
          en: 'Not many. And most are just group blasts',
          ja: 'あまりない。あってもほとんどが団体通知',
          'zh-CN': '不太有。有的话也大多是群发通知',
          'zh-TW': '不太有。有的話也大多是群發通知',
          vi: 'Ít thôi. Có thì cũng phần lớn là thông báo nhóm',
          id: 'Jarang. Kalau ada, kebanyakan notifikasi grup massal',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '거의 없다. 내가 먼저 보내지 않으면 잘 오지 않는다',
          en: 'Almost none. If I don\'t message first, they rarely come',
          ja: 'ほとんどない。自分から送らないとあまり来ない',
          'zh-CN': '几乎没有。我不先发，就很少会来',
          'zh-TW': '幾乎沒有。我不先發，就很少會來',
          vi: 'Hầu như không. Không nhắn trước thì ít khi có tin đến',
          id: 'Hampir tidak ada. Kalau aku tidak chat dulu, jarang datang',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 5,
    question: L({
      ko: '밥을 먹을 때 주로 어떻게 먹나요?',
      en: 'How do you usually eat your meals?',
      ja: '食事のとき、主にどう食べていますか？',
      'zh-CN': '吃饭时你通常怎么吃？',
      'zh-TW': '吃飯時你通常怎麼吃？',
      vi: 'Khi ăn cơm, bạn thường ăn như thế nào?',
      id: 'Saat makan, biasanya kamu makan bagaimana?',
    }),
    options: [
      {
        text: L({
          ko: '함께 먹는 경우가 많다. 같이 먹을 사람이 자연스럽게 있다',
          en: 'Often with others. Someone to eat with comes naturally',
          ja: '一緒に食べることが多い。自然と一緒に食べる人がいる',
          'zh-CN': '经常一起吃。自然就有一起吃饭的人',
          'zh-TW': '經常一起吃。自然就有一起吃飯的人',
          vi: 'Thường ăn cùng người khác. Tự nhiên có người để ăn cùng',
          id: 'Sering makan bersama. Secara alami ada orang untuk makan bareng',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '혼자도 있고 같이도 있다. 반반 정도',
          en: 'Sometimes alone, sometimes with others. About fifty-fifty',
          ja: '一人のこともあれば一緒のこともある。半々くらい',
          'zh-CN': '有时一个人，有时一起。大概一半一半',
          'zh-TW': '有時一個人，有時一起。大概一半一半',
          vi: 'Có lúc một mình, có lúc cùng người. Khoảng nửa nửa',
          id: 'Kadang sendiri, kadang bareng. Kira-kira setengah-setengah',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '혼자 먹는 경우가 많다. 함께 먹고 싶을 때도 혼자 먹는다',
          en: 'Often alone. Even when I want company, I still eat by myself',
          ja: '一人で食べることが多い。一緒に食べたいときも一人で食べる',
          'zh-CN': '经常一个人吃。就算想一起吃，也还是自己吃',
          'zh-TW': '經常一個人吃。就算想一起吃，也還是自己吃',
          vi: 'Thường ăn một mình. Dù muốn ăn cùng người cũng vẫn ăn một mình',
          id: 'Sering makan sendiri. Meski ingin makan bareng, tetap makan sendiri',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '거의 항상 혼자 먹는다. 함께 먹는 것이 오히려 낯설다',
          en: 'Almost always alone. Eating with others actually feels unfamiliar',
          ja: 'ほぼいつも一人で食べる。一緒に食べる方がむしろ慣れない',
          'zh-CN': '几乎总是一个人吃。一起吃反而觉得陌生',
          'zh-TW': '幾乎總是一個人吃。一起吃反而覺得陌生',
          vi: 'Hầu như lúc nào cũng một mình. Ăn cùng người còn thấy lạ',
          id: 'Hampir selalu sendiri. Makan bareng justru terasa asing',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 6,
    question: L({
      ko: '주말이나 쉬는 날을 보내고 나면 드는 느낌은?',
      en: 'After a weekend or day off, how do you usually feel?',
      ja: '週末や休みを過ごしたあと、どんな気持ちになりますか？',
      'zh-CN': '过完周末或休息日，你通常有什么感觉？',
      'zh-TW': '過完週末或休息日，你通常有什麼感覺？',
      vi: 'Sau cuối tuần hoặc ngày nghỉ, bạn thường cảm thấy thế nào?',
      id: 'Setelah akhir pekan atau hari libur, biasanya perasaanmu bagaimana?',
    }),
    options: [
      {
        text: L({
          ko: '충전됐다. 사람들과 보내거나 혼자여도 만족스럽다',
          en: 'Recharged. Whether with people or alone, I feel satisfied',
          ja: '充電できた。人と過ごしても一人でも満足',
          'zh-CN': '充好电了。跟人一起或自己待着都挺满足',
          'zh-TW': '充好電了。跟人一起或自己待著都挺滿足',
          vi: 'Được nạp lại năng lượng. Ở với người hay một mình cũng thấy ổn',
          id: 'Terisi ulang. Entah bareng orang atau sendiri, tetap puas',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '무난하다. 특별히 충전되거나 허전하지도 않다',
          en: 'Fine. Not especially recharged, but not empty either',
          ja: '普通。特に充電できたわけでも虚しいわけでもない',
          'zh-CN': '还行。没什么特别充电，也不觉得空',
          'zh-TW': '還行。沒什麼特別充電，也不覺得空',
          vi: 'Bình thường. Không nạp lại gì nhiều, cũng chẳng trống trải',
          id: 'Biasa saja. Tidak terlalu terisi, tapi juga tidak kosong',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '약간 허전하다. 뭔가 부족한 느낌이 든다',
          en: 'A bit empty. Something feels missing',
          ja: '少し虚しい。何か足りない感じがする',
          'zh-CN': '有点空落落的。总觉得少了点什么',
          'zh-TW': '有點空落落的。總覺得少了點什麼',
          vi: 'Hơi trống trải. Cảm giác như thiếu gì đó',
          id: 'Agak kosong. Rasanya ada yang kurang',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '많이 허전하다. 길게 혼자였다는 느낌이 남는다',
          en: 'Really empty. A sense of having been alone for a long stretch lingers',
          ja: 'かなり虚しい。長く一人だった感覚が残る',
          'zh-CN': '很空虚。会留下「好久都一个人」的感觉',
          'zh-TW': '很空虛。會留下「好久都一個人」的感覺',
          vi: 'Rất trống trải. Cảm giác đã ở một mình lâu còn đọng lại',
          id: 'Sangat kosong. Tinggal rasa sudah sendirian terlalu lama',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 7,
    question: L({
      ko: '"나를 진심으로 아는 사람"이 몇 명이나 된다고 느끼나요?',
      en: 'How many people do you feel truly know you?',
      ja: '「自分を本気で知っている人」は何人くらいいると感じますか？',
      'zh-CN': '你觉得「真正了解你的人」有几个？',
      'zh-TW': '你覺得「真正瞭解你的人」有幾個？',
      vi: 'Bạn cảm thấy có bao nhiêu người "thật sự hiểu mình"?',
      id: 'Menurutmu, berapa orang yang benar-benar mengenalmu?',
    }),
    options: [
      {
        text: L({
          ko: '여러 명이다. 나를 깊이 아는 사람들이 곁에 있다',
          en: 'Several. People who know me deeply are by my side',
          ja: '何人かいる。自分を深く知っている人がそばにいる',
          'zh-CN': '好几个。身边有真正了解我的人',
          'zh-TW': '好幾個。身邊有真正瞭解我的人',
          vi: 'Vài người. Có những người hiểu sâu về mình ở bên',
          id: 'Beberapa orang. Ada yang mengenaliku secara mendalam di sisiku',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '한두 명 정도 있다. 많지는 않지만 있다',
          en: 'One or two. Not many, but they\'re there',
          ja: '一人か二人くらい。多くはないけどいる',
          'zh-CN': '一两个。不多，但有',
          'zh-TW': '一兩個。不多，但有',
          vi: 'Một hai người. Không nhiều nhưng có',
          id: 'Satu atau dua orang. Tidak banyak, tapi ada',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '있긴 한데 정말 아는지 확신이 없다',
          en: 'There might be someone, but I\'m not sure they really know me',
          ja: 'いるにはいるけど、本当に知っているか確信がない',
          'zh-CN': '好像有，但不确定他们是否真的了解我',
          'zh-TW': '好像有，但不確定他們是否真的瞭解我',
          vi: 'Có thì có, nhưng không chắc họ thật sự hiểu mình',
          id: 'Ada sih, tapi tidak yakin mereka benar-benar mengenaliku',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '솔직히 없는 것 같다. 나를 진짜 아는 사람이 떠오르지 않는다',
          en: 'Honestly, probably none. No one who truly knows me comes to mind',
          ja: '正直、いない気がする。自分を本当に知っている人が思い浮かばない',
          'zh-CN': '说实话好像没有。想不到真正了解我的人',
          'zh-TW': '說實話好像沒有。想不到真正瞭解我的人',
          vi: 'Thành thật thì hình như không có. Chẳng nghĩ ra ai thật sự hiểu mình',
          id: 'Jujur, kayaknya tidak ada. Tidak ada yang terlintas benar-benar mengenaliku',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 8,
    question: L({
      ko: '누군가와 대화를 나눈 후 드는 느낌은?',
      en: 'After talking with someone, how do you usually feel?',
      ja: '誰かと話したあと、どんな気持ちになりますか？',
      'zh-CN': '和别人聊完之后，你通常有什么感觉？',
      'zh-TW': '和別人聊完之後，你通常有什麼感覺？',
      vi: 'Sau khi trò chuyện với ai đó, bạn thường cảm thấy thế nào?',
      id: 'Setelah ngobrol dengan seseorang, biasanya perasaanmu bagaimana?',
    }),
    options: [
      {
        text: L({
          ko: '대체로 충전된다. 이야기 나누는 것이 좋다',
          en: 'Usually recharged. I enjoy talking with people',
          ja: 'だいたい充電される。話すのが好き',
          'zh-CN': '大多会感到充电。喜欢跟人聊天',
          'zh-TW': '大多會感到充電。喜歡跟人聊天',
          vi: 'Thường được nạp lại năng lượng. Thích trò chuyện',
          id: 'Biasanya terisi ulang. Senang ngobrol',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '가벼운 대화는 괜찮고 깊은 대화는 가끔 아쉬움이 남는다',
          en: 'Light chats are fine; deeper talks sometimes leave me wanting more',
          ja: '軽い会話は大丈夫。深い話はたまに物足りなさが残る',
          'zh-CN': '闲聊还好，深聊有时会觉得不够过瘾',
          'zh-TW': '閒聊還好，深聊有時會覺得不夠過癮',
          vi: 'Nói chuyện nhẹ nhàng thì ổn; chuyện sâu đôi khi còn thấy thiếu',
          id: 'Obrolan ringan oke; ngobrol dalam kadang masih kurang',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '대화를 나눠도 뭔가 연결된 느낌이 잘 안 든다',
          en: 'Even after talking, I rarely feel truly connected',
          ja: '話しても、つながっている感じがあまりしない',
          'zh-CN': '就算聊了，也很难有真正连上的感觉',
          'zh-TW': '就算聊了，也很難有真正連上的感覺',
          vi: 'Dù đã nói chuyện, vẫn khó cảm thấy kết nối thật sự',
          id: 'Meski sudah ngobrol, jarang merasa benar-benar terhubung',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '대화 자체가 피상적으로 느껴진다. 진짜로 통한다는 느낌이 거의 없다',
          en: 'Conversation itself feels surface-level. I almost never feel like we really click',
          ja: '会話そのものが表面的に感じる。本当に通じ合う感じがほとんどない',
          'zh-CN': '对话本身就感觉很表面。几乎没有真正对上的感觉',
          'zh-TW': '對話本身就感覺很表面。幾乎沒有真正對上的感覺',
          vi: 'Bản thân cuộc trò chuyện cũng thấy hời hợt. Hầu như không thấy thật sự ăn ý',
          id: 'Obrolannya sendiri terasa dangkal. Hampir tidak pernah merasa benar-benar nyambung',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 9,
    question: L({
      ko: '요즘 나의 연락 패턴은?',
      en: 'What\'s your contact pattern like these days?',
      ja: '最近の自分の連絡パターンは？',
      'zh-CN': '最近你的联系模式是？',
      'zh-TW': '最近你的聯繫模式是？',
      vi: 'Gần đây kiểu liên lạc của bạn thế nào?',
      id: 'Pola kontakmu belakangan ini seperti apa?',
    }),
    options: [
      {
        text: L({
          ko: '자연스럽게 주고받는다. 먼저 연락하기도 하고 받기도 한다',
          en: 'It flows naturally. I initiate and receive messages both',
          ja: '自然にやり取りしている。先に連絡することも受け取ることもある',
          'zh-CN': '自然地来来往往。会主动联系，也会收到消息',
          'zh-TW': '自然地來來往往。會主動聯繫，也會收到訊息',
          vi: 'Qua lại tự nhiên. Vừa chủ động nhắn vừa nhận tin',
          id: 'Alami saja. Kadang chat dulu, kadang menerima',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '주로 받는 편이거나 필요할 때만 연락한다',
          en: 'Mostly I receive, or I only reach out when needed',
          ja: '主に受け取るか、必要なときだけ連絡する',
          'zh-CN': '主要是收消息，或者只在需要时才联系',
          'zh-TW': '主要是收訊息，或者只在需要時才聯繫',
          vi: 'Chủ yếu nhận tin, hoặc chỉ liên lạc khi cần',
          id: 'Lebih sering menerima, atau hanya menghubungi saat perlu',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '먼저 연락하기 망설여진다. 부담이 될까봐 잘 안 한다',
          en: 'I hesitate to message first. I worry I\'ll be a burden',
          ja: '先に連絡するのがためらわれる。負担になるのが怖くてあまりしない',
          'zh-CN': '犹豫着不敢先联系。怕给人添麻烦，所以很少主动',
          'zh-TW': '猶豫著不敢先聯繫。怕給人添麻煩，所以很少主動',
          vi: 'Ngại nhắn trước. Sợ làm phiền nên ít khi chủ động',
          id: 'Ragu chat duluan. Takut merepotkan jadi jarang mulai',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '연락 자체를 잘 하지 않는다. 먼저 연락이 오는 것도 뜸하다',
          en: 'I barely contact anyone. Incoming messages are rare too',
          ja: '連絡そのものをあまりしない。先に来る連絡も少ない',
          'zh-CN': '基本不怎么联系。别人先找我也很少',
          'zh-TW': '基本不怎麼聯繫。別人先找我也很少',
          vi: 'Hầu như không liên lạc. Tin nhắn đến trước cũng thưa thớt',
          id: 'Jarang sekali menghubungi. Chat yang datang duluan juga jarang',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 10,
    question: L({
      ko: '"나는 혼자다"라는 생각이 드는 빈도는?',
      en: 'How often do you think, "I\'m alone"?',
      ja: '「自分は一人だ」と思う頻度は？',
      'zh-CN': '你有多常冒出「我是一个人」的念头？',
      'zh-TW': '你有多常冒出「我是一個人」的念頭？',
      vi: 'Bạn nghĩ "Mình đang một mình" thường xuyên thế nào?',
      id: 'Seberapa sering kamu berpikir, "Aku sendirian"?',
    }),
    options: [
      {
        text: L({
          ko: '거의 없다. 혼자여도 외롭다는 느낌이 들지 않는다',
          en: 'Almost never. Even alone, I don\'t feel lonely',
          ja: 'ほとんどない。一人でも寂しいとは感じない',
          'zh-CN': '几乎没有。就算一个人也不觉得孤独',
          'zh-TW': '幾乎沒有。就算一個人也不覺得孤獨',
          vi: 'Hầu như không. Dù một mình cũng không thấy cô đơn',
          id: 'Hampir tidak pernah. Meski sendiri, tidak merasa kesepian',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '가끔 있다. 특정 순간에 문득 드는 정도다',
          en: 'Sometimes. It hits me in certain moments',
          ja: 'たまに。特定の瞬間にふっと浮かぶ程度',
          'zh-CN': '偶尔有。只是某些瞬间会突然冒出来',
          'zh-TW': '偶爾有。只是某些瞬間會突然冒出來',
          vi: 'Thỉnh thoảng. Chỉ vụt đến ở vài khoảnh khắc',
          id: 'Kadang-kadang. Muncul di momen tertentu saja',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '꽤 자주 있다. 사람들 속에서도 그런 생각이 들 때가 있다',
          en: 'Pretty often. Even in a crowd, that thought can show up',
          ja: 'かなりよくある。人の中にいてもそう思うことがある',
          'zh-CN': '挺经常的。就算在人群里有时也会这么想',
          'zh-TW': '挺經常的。就算在人群裡有時也會這麼想',
          vi: 'Khá thường xuyên. Ngay cả giữa đám đông đôi khi vẫn nghĩ vậy',
          id: 'Cukup sering. Bahkan di keramaian, pikiran itu bisa muncul',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '자주 있다. 이 생각이 기본 설정처럼 깔려있다',
          en: 'Often. That thought feels like the default setting',
          ja: 'よくある。この考えがデフォルト設定のようにある',
          'zh-CN': '经常有。这个念头像默认设置一样一直在',
          'zh-TW': '經常有。這個念頭像預設設定一樣一直在',
          vi: 'Thường xuyên. Ý nghĩ này như cài đặt mặc định vậy',
          id: 'Sering. Pikiran itu seperti pengaturan bawaan',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 11,
    question: L({
      ko: '지금 나의 소통 니즈는?',
      en: 'Right now, how are your connection needs?',
      ja: '今の自分のコミュニケーションのニーズは？',
      'zh-CN': '现在你的沟通需求是？',
      'zh-TW': '現在你的溝通需求是？',
      vi: 'Nhu cầu kết nối của bạn lúc này thế nào?',
      id: 'Kebutuhan koneksimu saat ini bagaimana?',
    }),
    options: [
      {
        text: L({
          ko: '충족되고 있다. 원하는 만큼 연결되어 있다',
          en: 'Being met. I\'m connected as much as I want',
          ja: '満たされている。望む分だけつながっている',
          'zh-CN': '被满足了。连接程度正是我想要的',
          'zh-TW': '被滿足了。連結程度正是我想要的',
          vi: 'Đang được đáp ứng. Kết nối đủ như mình muốn',
          id: 'Terpenuhi. Sudah terhubung sebanyak yang aku mau',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '조금 더 있으면 좋겠다. 아주 부족하진 않다',
          en: 'Could use a bit more. Not severely lacking though',
          ja: 'もう少しあるといい。すごく足りないわけではない',
          'zh-CN': '再多一点会更好。倒也不是特别缺',
          'zh-TW': '再多一點會更好。倒也不是特別缺',
          vi: 'Thêm một chút thì tốt. Không thiếu quá nhiều',
          id: 'Sedikit lebih banyak akan lebih baik. Tidak terlalu kekurangan',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '꽤 부족하다. 더 깊은 연결이 필요하다는 느낌이 있다',
          en: 'Pretty lacking. I feel I need deeper connection',
          ja: 'かなり足りない。もっと深いつながりが必要だと感じる',
          'zh-CN': '挺缺的。感觉需要更深的连接',
          'zh-TW': '挺缺的。感覺需要更深的連結',
          vi: 'Khá thiếu. Cảm giác cần kết nối sâu hơn',
          id: 'Cukup kurang. Rasanya butuh koneksi yang lebih dalam',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '많이 부족하다. 진짜로 연결되고 싶다는 갈증이 크다',
          en: 'Really lacking. There\'s a strong thirst to truly connect',
          ja: 'とても足りない。本当につながりたいという渇きが大きい',
          'zh-CN': '非常缺。真的很渴望真正连上',
          'zh-TW': '非常缺。真的很渴望真正連上',
          vi: 'Thiếu rất nhiều. Khát khao kết nối thật sự rất lớn',
          id: 'Sangat kurang. Haus ingin benar-benar terhubung itu besar',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 12,
    question: L({
      ko: '이 테스트를 하면서 솔직하게 드는 생각은?',
      en: 'Being honest, what\'s coming up as you take this test?',
      ja: 'このテストを受けていて、正直どう感じますか？',
      'zh-CN': '做这个测试时，你老实说心里是什么感觉？',
      'zh-TW': '做這個測驗時，你老實說心裡是什麼感覺？',
      vi: 'Thành thật thì, khi làm bài test này bạn nghĩ gì?',
      id: 'Jujur saja, apa yang terasa saat mengerjakan tes ini?',
    }),
    options: [
      {
        text: L({
          ko: '나는 충분히 연결되어 있다. 크게 공감되지 않는 항목들이었다',
          en: 'I\'m connected enough. Most items didn\'t really resonate',
          ja: '自分は十分につながっている。あまり共感しない項目が多かった',
          'zh-CN': '我连接得够了。好多题目不太有共鸣',
          'zh-TW': '我連結得夠了。好多題目不太有共鳴',
          vi: 'Mình đã kết nối đủ. Nhiều câu không đồng cảm lắm',
          id: 'Aku sudah cukup terhubung. Banyak item yang kurang resonan',
        }),
        score: 0,
      },
      {
        text: L({
          ko: '몇 가지는 공감됐다. 조금 더 연결을 늘려도 좋겠다',
          en: 'A few hit home. It might be nice to grow connection a bit more',
          ja: 'いくつかは共感した。もう少しつながりを増やしてもいい',
          'zh-CN': '有几条挺有共鸣。再多一点连接会更好',
          'zh-TW': '有幾條挺有共鳴。再多一點連結會更好',
          vi: 'Vài câu khá đúng. Thêm một chút kết nối thì tốt',
          id: 'Beberapa cocok. Sedikit menambah koneksi mungkin bagus',
        }),
        score: 1,
      },
      {
        text: L({
          ko: '꽤 공감됐다. 외로움이 생각보다 가까이 있었다',
          en: 'A lot resonated. Loneliness was closer than I thought',
          ja: 'かなり共感した。孤独が思ったより近くにあった',
          'zh-CN': '挺有共鸣的。孤独比想象中更近',
          'zh-TW': '挺有共鳴的。孤獨比想像中更近',
          vi: 'Khá đồng cảm. Cô đơn gần hơn mình nghĩ',
          id: 'Cukup resonan. Kesepian lebih dekat dari yang kuduga',
        }),
        score: 2,
      },
      {
        text: L({
          ko: '많이 공감됐다. 이 감정을 누군가에게 말하고 싶다는 생각이 든다',
          en: 'A lot hit hard. I feel like I want to tell someone about this feeling',
          ja: 'すごく共感した。この気持ちを誰かに話したいと思った',
          'zh-CN': '很有共鸣。想把这种感觉告诉谁',
          'zh-TW': '很有共鳴。想把這種感覺告訴誰',
          vi: 'Rất đồng cảm. Muốn nói cảm xúc này với ai đó',
          id: 'Sangat cocok. Ingin cerita perasaan ini ke seseorang',
        }),
        score: 3,
      },
    ],
  },
];

export const phase3LonelinessConcentrationResults: Phase3LonelinessConcentrationResult[] = [
  {
    type: 'Type1',
    emoji: '☀️',
    title: L({
      ko: '외로움 농도 0%, 연결 충만형 ☀️',
      en: 'Loneliness Level 0%, Fully Connected Type ☀️',
      ja: '孤独濃度0%、つながり充実型 ☀️',
      'zh-CN': '孤独浓度 0%，连接充盈型 ☀️',
      'zh-TW': '孤獨濃度 0%，連結充盈型 ☀️',
      vi: 'Nồng độ cô đơn 0%, kiểu kết nối đầy đủ ☀️',
      id: 'Kadar Kesepian 0%, Tipe Penuh Koneksi ☀️',
    }),
    shortDescription: L({
      ko: '지금 당신의 삶에는 진짜 연결이 있습니다.',
      en: 'Right now, your life has real connection.',
      ja: '今のあなたの人生には、本物のつながりがあります。',
      'zh-CN': '此刻，你的生活里有真正的连接。',
      'zh-TW': '此刻，你的生活裡有真正的連結。',
      vi: 'Lúc này cuộc sống của bạn có kết nối thật sự.',
      id: 'Sekarang hidupmu punya koneksi yang nyata.',
    }),
    description: L({
      ko: '말하고 싶을 때 말할 사람이 있고 힘들 때 기댈 수 있으며 기쁠 때 함께 기뻐할 사람이 곁에 있습니다. 이 연결이 자연스럽게 느껴지지만 사실 쉽게 만들어지는 것이 아닙니다. 지금의 관계를 소중히 여기세요.',
      en: 'When you want to talk, there\'s someone. When it\'s hard, you can lean on someone. When you\'re happy, there\'s someone to celebrate with. This connection may feel natural, but it isn\'t easy to build. Treasure what you have right now.',
      ja: '話したいときに話せる人がいて、つらいときに頼れ、嬉しいときに一緒に喜んでくれる人がそばにいます。このつながりは自然に感じられるかもしれませんが、簡単にできるものではありません。今の関係を大切にしてください。',
      'zh-CN': '想说时有人可说，难过时有人可靠，开心时有人一起高兴。这份连接或许感觉很自然，其实并不容易建立。请珍惜现在的关系。',
      'zh-TW': '想說時有人可說，難過時有人可靠，開心時有人一起高興。這份連結或許感覺很自然，其實並不容易建立。請珍惜現在的關係。',
      vi: 'Khi muốn nói có người để nói, khi khó khăn có chỗ dựa, khi vui có người cùng vui. Kết nối này có vẻ tự nhiên, nhưng không dễ tạo được. Hãy trân trọng mối quan hệ hiện tại.',
      id: 'Saat ingin bicara ada orangnya, saat susah bisa bersandar, saat senang ada yang merayakan bersamamu. Koneksi ini terasa alami, tapi tidak mudah dibangun. Hargai hubunganmu sekarang.',
    }),
    concentration: L({
      ko: '0~10% ☀️',
      en: '0~10% ☀️',
      ja: '0~10% ☀️',
      'zh-CN': '0~10% ☀️',
      'zh-TW': '0~10% ☀️',
      vi: '0~10% ☀️',
      id: '0~10% ☀️',
    }),
    currentState: L({
      ko: '소통 니즈 충족·진짜 연결 보유',
      en: 'Connection needs met · Real bonds in place',
      ja: 'コミュニケーション欲求が満たされている・本物のつながりあり',
      'zh-CN': '沟通需求被满足 · 拥有真正连接',
      'zh-TW': '溝通需求被滿足 · 擁有真正連結',
      vi: 'Nhu cầu giao tiếp được đáp ứng · Có kết nối thật',
      id: 'Kebutuhan koneksi terpenuhi · Punya ikatan nyata',
    }),
    strength: L({
      ko: '건강한 관계망·자연스러운 연결',
      en: 'Healthy network · Natural connection',
      ja: '健全な人間関係網・自然なつながり',
      'zh-CN': '健康的关系网 · 自然的连接',
      'zh-TW': '健康的關係網 · 自然的連結',
      vi: 'Mạng quan hệ lành mạnh · Kết nối tự nhiên',
      id: 'Jaringan sehat · Koneksi alami',
    }),
    actions: L({
      ko: '지금 이 연결을 더 깊게 만들기. 가까운 사람에게 오늘 먼저 연락해보기',
      en: 'Deepen the connection you already have. Reach out first today to someone close',
      ja: '今のつながりをもっと深くする。近い人に今日、先に連絡してみる',
      'zh-CN': '把现有的连接再加深一点。今天先主动联系一位亲近的人',
      'zh-TW': '把現有的連結再加深一點。今天先主動聯繫一位親近的人',
      vi: 'Làm sâu hơn kết nối hiện có. Hôm nay chủ động nhắn một người thân gần',
      id: 'Perdalam koneksi yang sudah ada. Hari ini chat duluan ke orang terdekat',
    }),
    community: L({
      ko: '지금의 연결 에너지로 새로운 사람에게도 먼저 다가가보세요. 당신의 연결 능력이 누군가에게 큰 힘이 됩니다',
      en: 'Use that connection energy to reach out to someone new too. Your ability to connect can mean a lot to someone else',
      ja: '今のつながりのエネルギーで、新しい人にも先に近づいてみてください。あなたのつながる力が、誰かの大きな支えになります',
      'zh-CN': '用这份连接的能量，也主动靠近新的人吧。你的连接能力，对别人可能是很大的力量',
      'zh-TW': '用這份連結的能量，也主動靠近新的人吧。你的連結能力，對別人可能是很大的力量',
      vi: 'Dùng năng lượng kết nối ấy để chủ động tiếp cận người mới. Khả năng kết nối của bạn có thể là sức mạnh lớn với ai đó',
      id: 'Pakai energi koneksi itu untuk mendekati orang baru juga. Kemampuanmu terhubung bisa jadi kekuatan besar bagi seseorang',
    }),
    crisisNote: null,
    oneLiner: null,
    shareSnippet: L({
      ko: '외로움 농도: 0% ☀️ 진짜 연결이 충분한 상태래... 곁에 있어줘서 고마운 사람들한테 오늘 먼저 연락해야겠다 → 너는 외로움 농도 몇 %야?',
      en: 'Loneliness level: 0% ☀️ Apparently I\'m fully connected... gonna text the people I\'m grateful for first today → What\'s your loneliness %?',
      ja: '孤独濃度：0% ☀️ 本物のつながりが足りてるらしい…そばにいてくれてありがとうな人に今日先に連絡しよ → 君の孤独濃度は何%？',
      'zh-CN': '孤独浓度：0% ☀️ 说是真正连接够了…今天得先跟那些让我心怀感激的人联系一下 → 你的孤独浓度是几%？',
      'zh-TW': '孤獨濃度：0% ☀️ 說是真正連結夠了…今天得先跟那些讓我心懷感激的人聯繫一下 → 你的孤獨濃度是幾%？',
      vi: 'Nồng độ cô đơn: 0% ☀️ Bảo là kết nối thật đủ rồi… hôm nay phải nhắn trước những người mình biết ơn → Bạn bao nhiêu %?',
      id: 'Kadar kesepian: 0% ☀️ Katanya koneksi benerannya cukup… hari ini mau chat duluan ke orang yang aku syukuri → Kadar kesepianmu berapa %?',
    }),
  },
  {
    type: 'Type2',
    emoji: '🌤️',
    title: L({
      ko: '외로움 농도 20%, 가벼운 연결 갈증형 🌤️',
      en: 'Loneliness Level 20%, Mild Connection Thirst Type 🌤️',
      ja: '孤独濃度20%、軽いつながり渇望型 🌤️',
      'zh-CN': '孤独浓度 20%，轻度连接渴求型 🌤️',
      'zh-TW': '孤獨濃度 20%，輕度連結渴求型 🌤️',
      vi: 'Nồng độ cô đơn 20%, kiểu khát kết nối nhẹ 🌤️',
      id: 'Kadar Kesepian 20%, Tipe Haus Koneksi Ringan 🌤️',
    }),
    shortDescription: L({
      ko: '대체로 괜찮지만 가끔 연결이 더 필요하다는 느낌이 옵니다.',
      en: 'You\'re mostly fine, but sometimes you feel you need more connection.',
      ja: 'だいたい大丈夫だけど、ときどきもっとつながりが必要だと感じます。',
      'zh-CN': '大体还好，但偶尔会觉得需要更多连接。',
      'zh-TW': '大體還好，但偶爾會覺得需要更多連結。',
      vi: 'Nhìn chung ổn, nhưng đôi khi cảm thấy cần kết nối hơn.',
      id: 'Sebagian besar oke, tapi kadang merasa butuh lebih banyak koneksi.',
    }),
    description: L({
      ko: '관계가 없는 건 아닌데 가끔 더 깊은 대화가 필요하거나 먼저 연락하기 망설여지는 순간이 있습니다. 연결의 양보다 깊이를 원하고 있는 상태일 수 있습니다.',
      en: 'It\'s not that you have no relationships—sometimes you just need a deeper talk, or hesitate to message first. You may be craving depth more than quantity.',
      ja: '関係がないわけではないのに、もっと深い会話が必要だったり、先に連絡するのがためらわれる瞬間があります。つながりの量より深さを求めている状態かもしれません。',
      'zh-CN': '不是没有关系，只是偶尔需要更深的对话，或犹豫着不敢先联系。你可能更想要深度，而不是数量。',
      'zh-TW': '不是沒有關係，只是偶爾需要更深的對話，或猶豫著不敢先聯繫。你可能更想要深度，而不是數量。',
      vi: 'Không phải không có quan hệ—đôi khi chỉ cần trò chuyện sâu hơn, hoặc ngại nhắn trước. Có thể bạn đang muốn chiều sâu hơn là số lượng.',
      id: 'Bukan tidak punya hubungan—kadang hanya butuh obrolan lebih dalam, atau ragu chat duluan. Bisa jadi kamu lebih haus kedalaman daripada jumlah.',
    }),
    concentration: L({
      ko: '20~30% 🌤️',
      en: '20~30% 🌤️',
      ja: '20~30% 🌤️',
      'zh-CN': '20~30% 🌤️',
      'zh-TW': '20~30% 🌤️',
      vi: '20~30% 🌤️',
      id: '20~30% 🌤️',
    }),
    currentState: L({
      ko: '관계 있음·깊이 아쉬움',
      en: 'Has relationships · Craving more depth',
      ja: '関係はある・深さに物足りなさ',
      'zh-CN': '有关系 · 深度略显不足',
      'zh-TW': '有關係 · 深度略顯不足',
      vi: 'Có quan hệ · Thiếu chiều sâu',
      id: 'Punya hubungan · Kurang kedalaman',
    }),
    strength: null,
    actions: L({
      ko: '오래 연락 못 한 사람 한 명에게 먼저 연락해보기\n가볍게 만나던 사람과 조금 더 깊은 이야기를 나눠보기\n관심 있는 커뮤니티나 모임에 참여해보기',
      en: 'Reach out first to one person you haven\'t talked to in a while\nTry a slightly deeper conversation with someone you usually keep light\nJoin a community or meetup you\'re interested in',
      ja: '久しく連絡していない人一人に、先に連絡してみる\n軽い付き合いの人と、もう少し深い話をしてみる\n興味のあるコミュニティや集まりに参加してみる',
      'zh-CN': '先联系一位很久没聊的人\n和平时只是浅交的人，试着聊深一点\n参加一个你感兴趣的社群或聚会',
      'zh-TW': '先聯繫一位很久沒聊的人\n和平時只是淺交的人，試著聊深一點\n參加一個你感興趣的社群或聚會',
      vi: 'Chủ động nhắn một người lâu rồi chưa liên lạc\nThử trò chuyện sâu hơn với người vốn chỉ nói chuyện nhẹ\nTham gia một cộng đồng hoặc buổi gặp gỡ mình quan tâm',
      id: 'Chat duluan ke satu orang yang lama tidak dihubungi\nCoba obrolan sedikit lebih dalam dengan orang yang biasanya cuma ringan\nIkut komunitas atau meetup yang kamu minati',
    }),
    community: L({
      ko: '비슷한 관심사를 가진 사람들이 모인 공간에서 새로운 연결을 시작해보세요',
      en: 'Start a new connection in a space where people share your interests',
      ja: '似た興味を持つ人が集まる場所で、新しいつながりを始めてみてください',
      'zh-CN': '在志同道合的人聚集的地方，开始一段新的连接吧',
      'zh-TW': '在志同道合的人聚集的地方，開始一段新的連結吧',
      vi: 'Bắt đầu kết nối mới ở nơi có người cùng sở thích',
      id: 'Mulai koneksi baru di ruang di mana orang punya minat yang sama',
    }),
    crisisNote: null,
    oneLiner: null,
    shareSnippet: L({
      ko: '외로움 농도: 20% 🌤️ 가끔 연결 더 필요하다는 느낌 있는 상태래... 오래 연락 못 한 사람 한 명한테 먼저 연락해봐야겠다 → 너는 몇 %야?',
      en: 'Loneliness level: 20% 🌤️ Sometimes I need more connection apparently... gonna text that one person I\'ve been ghosting → What\'s yours?',
      ja: '孤独濃度：20% 🌤️ ときどきもっとつながりが欲しい状態らしい…久しく連絡してない人に先に連絡してみよ → 君は何%？',
      'zh-CN': '孤独浓度：20% 🌤️ 说是偶尔会想要更多连接…该先联系那个好久没聊的人了 → 你是几%？',
      'zh-TW': '孤獨濃度：20% 🌤️ 說是偶爾會想要更多連結…該先聯繫那個好久沒聊的人了 → 你是幾%？',
      vi: 'Nồng độ cô đơn: 20% 🌤️ Bảo là đôi khi cần kết nối hơn… phải nhắn trước người lâu rồi chưa liên lạc → Bạn bao nhiêu %?',
      id: 'Kadar kesepian: 20% 🌤️ Katanya kadang butuh lebih banyak koneksi… mau chat duluan ke orang yang lama tak dihubungi → Kamu berapa %?',
    }),
  },
  {
    type: 'Type3',
    emoji: '⛅',
    title: L({
      ko: '외로움 농도 40%, 연결 갈망형 ⛅',
      en: 'Loneliness Level 40%, Connection Longing Type ⛅',
      ja: '孤独濃度40%、つながり渇望型 ⛅',
      'zh-CN': '孤独浓度 40%，连接渴望型 ⛅',
      'zh-TW': '孤獨濃度 40%，連結渴望型 ⛅',
      vi: 'Nồng độ cô đơn 40%, kiểu khao khát kết nối ⛅',
      id: 'Kadar Kesepian 40%, Tipe Haus Koneksi ⛅',
    }),
    shortDescription: L({
      ko: '말하고 싶은데 망설이고, 연락하고 싶은데 부담될까봐 참는 패턴이 반복됩니다.',
      en: 'You want to talk but hesitate; you want to reach out but hold back so you won\'t be a burden—and the pattern repeats.',
      ja: '話したいのにためらい、連絡したいのに負担になるのが怖くて我慢するパターンが繰り返されます。',
      'zh-CN': '想说却犹豫，想联系又怕添麻烦而忍着——这个模式在反复。',
      'zh-TW': '想說卻猶豫，想聯繫又怕添麻煩而忍著——這個模式在反覆。',
      vi: 'Muốn nói thì ngại, muốn liên lạc lại nhịn vì sợ làm phiền—và kiểu đó lặp lại.',
      id: 'Ingin cerita tapi ragu; ingin chat tapi ditahan karena takut merepotkan—polanya berulang.',
    }),
    description: L({
      ko: '관계가 없는 것이 아닌데 진짜로 연결된 느낌이 잘 들지 않는 상태입니다. 표면적인 연결은 있지만 내면 깊은 곳에서는 더 진짜 같은 연결을 원하고 있습니다.',
      en: 'It\'s not that you have no relationships—you just rarely feel truly connected. Surface links exist, but deep down you want something more real.',
      ja: '関係がないわけではないのに、本当につながっている感じがしにくい状態です。表面的なつながりはあるけれど、心の奥ではもっと本物のつながりを求めています。',
      'zh-CN': '不是没有关系，只是很难感到真正连上。表面有连接，内心深处却想要更真实的连接。',
      'zh-TW': '不是沒有關係，只是很難感到真正連上。表面有連結，內心深處卻想要更真實的連結。',
      vi: 'Không phải không có quan hệ—chỉ là khó cảm thấy kết nối thật. Kết nối bề mặt có đó, nhưng sâu bên trong bạn muốn thứ thật hơn.',
      id: 'Bukan tidak punya hubungan—hanya jarang merasa benar-benar terhubung. Koneksi permukaan ada, tapi di dalam kamu ingin yang lebih nyata.',
    }),
    concentration: L({
      ko: '40~55% ⛅',
      en: '40~55% ⛅',
      ja: '40~55% ⛅',
      'zh-CN': '40~55% ⛅',
      'zh-TW': '40~55% ⛅',
      vi: '40~55% ⛅',
      id: '40~55% ⛅',
    }),
    currentState: L({
      ko: '피상적 연결·깊은 연결 갈망·먼저 다가가기 어려움',
      en: 'Surface connection · Longing for depth · Hard to reach out first',
      ja: '表面的なつながり・深いつながりの渇望・先に近づきにくい',
      'zh-CN': '表面连接 · 渴望深度 · 难以主动靠近',
      'zh-TW': '表面連結 · 渴望深度 · 難以主動靠近',
      vi: 'Kết nối hời hợt · Khao khát chiều sâu · Khó chủ động tiếp cận',
      id: 'Koneksi dangkal · Haus kedalaman · Sulit mendekat duluan',
    }),
    strength: null,
    actions: L({
      ko: '"나 요즘 좀 외롭다"고 솔직하게 말할 수 있는 사람 한 명 찾기\n부담 없이 들어오고 나갈 수 있는 커뮤니티 하나 시작해보기\n먼저 연락하는 것에 대한 부담을 줄이기. 짧은 메시지 하나면 충분합니다',
      en: 'Find one person you can honestly say "I\'ve been a bit lonely lately" to\nTry a community you can join and leave without pressure\nEase the pressure of messaging first—one short note is enough',
      ja: '「最近ちょっと寂しい」と正直に言える人を一人見つける\n気軽に出入りできるコミュニティを一つ始めてみる\n先に連絡する負担を減らす。短いメッセージ一つで十分です',
      'zh-CN': '找一个能坦率说「我最近有点孤独」的人\n开始一个进出都没有压力的社群\n减轻「先联系」的负担——一条短消息就够了',
      'zh-TW': '找一個能坦率說「我最近有點孤獨」的人\n開始一個進出都沒有壓力的社群\n減輕「先聯繫」的負擔——一則短訊就夠了',
      vi: 'Tìm một người để thật lòng nói "Dạo này mình hơi cô đơn"\nThử một cộng đồng vào ra không áp lực\nGiảm áp lực khi nhắn trước—một tin ngắn là đủ',
      id: 'Cari satu orang yang bisa kau bilang jujur, "Akhir-akhir ini aku agak kesepian"\nCoba komunitas yang bisa masuk-keluar tanpa tekanan\nKurangi beban chat duluan—satu pesan pendek sudah cukup',
    }),
    community: L({
      ko: '익명으로 참여할 수 있는 온라인 커뮤니티에서 먼저 작게 시작해보세요',
      en: 'Start small in an online community where you can join anonymously',
      ja: '匿名で参加できるオンラインコミュニティで、まずは小さく始めてみてください',
      'zh-CN': '先从可以匿名参与的线上社群小小开始吧',
      'zh-TW': '先從可以匿名參與的線上社群小小開始吧',
      vi: 'Bắt đầu nhỏ trong cộng đồng online có thể tham gia ẩn danh',
      id: 'Mulai kecil di komunitas online yang bisa diikuti secara anonim',
    }),
    crisisNote: null,
    oneLiner: null,
    shareSnippet: L({
      ko: '외로움 농도: 40% ⛅ 말하고 싶은데 망설이는 패턴이 있다는 거... 이 결과 공유하는 게 오늘의 용기 → 너는 몇 %야?',
      en: 'Loneliness level: 40% ⛅ Turns out I hesitate when I want to talk... sharing this is today\'s courage → What\'s yours?',
      ja: '孤独濃度：40% ⛅ 話したいのにためらうパターンがあるらしい…この結果をシェアするのが今日の勇気 → 君は何%？',
      'zh-CN': '孤独浓度：40% ⛅ 原来有「想说却犹豫」的模式…分享这个结果就是今天的勇气 → 你是几%？',
      'zh-TW': '孤獨濃度：40% ⛅ 原來有「想說卻猶豫」的模式…分享這個結果就是今天的勇氣 → 你是幾%？',
      vi: 'Nồng độ cô đơn: 40% ⛅ Bảo là có kiểu muốn nói mà ngại… chia sẻ kết quả này là can đảm của hôm nay → Bạn bao nhiêu %?',
      id: 'Kadar kesepian: 40% ⛅ Katanya ada pola ingin cerita tapi ragu… share hasil ini adalah keberanian hari ini → Kamu berapa %?',
    }),
  },
  {
    type: 'Type4',
    emoji: '🌥️',
    title: L({
      ko: '외로움 농도 60%, 만성 고립 시작형 🌥️',
      en: 'Loneliness Level 60%, Chronic Isolation Starting Type 🌥️',
      ja: '孤独濃度60%、慢性的孤立スタート型 🌥️',
      'zh-CN': '孤独浓度 60%，慢性孤立萌芽型 🌥️',
      'zh-TW': '孤獨濃度 60%，慢性孤立萌芽型 🌥️',
      vi: 'Nồng độ cô đơn 60%, kiểu cô lập mãn tính bắt đầu 🌥️',
      id: 'Kadar Kesepian 60%, Tipe Isolasi Kronis Mulai 🌥️',
    }),
    shortDescription: L({
      ko: '사람들 속에서도 혼자라는 느낌이 듭니다. 진짜로 통하는 느낌이 오래됐습니다.',
      en: 'Even among people, you feel alone. It\'s been a while since you felt truly understood.',
      ja: '人の中にいても一人だと感じます。本当に通じ合う感覚が久しぶりです。',
      'zh-CN': '就算在人群里，也感觉自己是一个人。真正对上的感觉，已经很久了。',
      'zh-TW': '就算在人群裡，也感覺自己是一個人。真正對上的感覺，已經很久了。',
      vi: 'Ngay cả giữa mọi người cũng thấy một mình. Đã lâu rồi không cảm thấy thật sự ăn ý.',
      id: 'Bahkan di keramaian, kamu merasa sendirian. Sudah lama tidak merasa benar-benar nyambung.',
    }),
    description: L({
      ko: '관계 자체가 없는 건 아닌데 진짜 연결의 느낌이 없거나 연결이 점점 줄어드는 상태입니다. 외로움이 기본 감정처럼 깔려있기 시작한 단계입니다. 이 외로움은 혼자 해결하는 것보다 연결을 만들어가는 것이 더 효과적입니다.',
      en: 'It\'s not that you have no relationships—you just lack the feeling of real connection, or it\'s fading. Loneliness is starting to feel like a baseline emotion. Building connection works better than solving this alone.',
      ja: '関係そのものがないわけではないのに、本物のつながりの感覚がないか、つながりが減りつつある状態です。孤独がベースの感情のようになり始めている段階です。この孤独は一人で解決するより、つながりを作っていく方が効果的です。',
      'zh-CN': '不是完全没有关系，只是缺少真正连接的感觉，或者连接正在变少。孤独开始像底色情绪一样铺开。比起独自硬扛，去建立连接会更有效。',
      'zh-TW': '不是完全沒有關係，只是缺少真正連結的感覺，或者連結正在變少。孤獨開始像底色情緒一樣鋪開。比起獨自硬扛，去建立連結會更有效。',
      vi: 'Không phải không có quan hệ—chỉ là thiếu cảm giác kết nối thật, hoặc kết nối đang mỏng dần. Cô đơn bắt đầu như cảm xúc nền. Xây kết nối hiệu quả hơn là tự giải một mình.',
      id: 'Bukan tidak punya hubungan—hanya rasa koneksi nyata yang hilang, atau koneksinya semakin menipis. Kesepian mulai jadi emosi default. Membangun koneksi lebih efektif daripada menyelesaikannya sendirian.',
    }),
    concentration: L({
      ko: '60~70% 🌥️',
      en: '60~70% 🌥️',
      ja: '60~70% 🌥️',
      'zh-CN': '60~70% 🌥️',
      'zh-TW': '60~70% 🌥️',
      vi: '60~70% 🌥️',
      id: '60~70% 🌥️',
    }),
    currentState: L({
      ko: '만성적 외로움 시작·피상적 연결·진짜 연결 부재',
      en: 'Chronic loneliness starting · Surface links · Missing real connection',
      ja: '慢性的な孤独の始まり・表面的なつながり・本物のつながり不在',
      'zh-CN': '慢性孤独开始 · 表面连接 · 真正连接缺失',
      'zh-TW': '慢性孤獨開始 · 表面連結 · 真正連結缺失',
      vi: 'Cô đơn mãn tính bắt đầu · Kết nối hời hợt · Thiếu kết nối thật',
      id: 'Kesepian kronis mulai · Koneksi dangkal · Koneksi nyata absen',
    }),
    strength: null,
    actions: L({
      ko: '매일 한 명에게 짧은 메시지 보내기 챌린지 7일 시도\n오프라인 모임이나 커뮤니티 활동 하나 시작하기\n"나는 외롭다"는 것을 스스로 인정하기. 인정이 연결의 시작',
      en: 'Try a 7-day challenge: send one short message to someone each day\nStart one offline meetup or community activity\nAdmit to yourself "I\'m lonely"—naming it is where connection starts',
      ja: '毎日一人に短いメッセージを送るチャレンジを7日間やってみる\nオフラインの集まりやコミュニティ活動を一つ始める\n「自分は寂しい」と自分で認める。認めることがつながりの始まり',
      'zh-CN': '试试连续7天、每天给一个人发一条短消息的挑战\n开始一个线下聚会或社群活动\n对自己承认「我孤独」——承认，是连接的开始',
      'zh-TW': '試試連續7天、每天給一個人發一則短訊的挑戰\n開始一個線下聚會或社群活動\n對自己承認「我孤獨」——承認，是連結的開始',
      vi: 'Thử thử thách 7 ngày: mỗi ngày gửi một tin ngắn cho một người\nBắt đầu một buổi gặp offline hoặc hoạt động cộng đồng\nTự thừa nhận "Mình cô đơn"—thừa nhận chính là khởi đầu của kết nối',
      id: 'Coba tantangan 7 hari: kirim satu pesan pendek ke seseorang setiap hari\nMulai satu meetup offline atau aktivitas komunitas\nAkui pada diri sendiri "Aku kesepian"—mengakuinya adalah awal koneksi',
    }),
    community: L({
      ko: '혼자 해결하려 하지 않아도 됩니다. 같은 감정을 가진 사람들이 있는 공간으로 먼저 들어와보세요',
      en: 'You don\'t have to fix this alone. Step into a space where others feel the same',
      ja: '一人で解決しなくても大丈夫。同じ気持ちの人がいる場所に、まず入ってみてください',
      'zh-CN': '不必一个人硬扛。先走进有同感的人在的空间吧',
      'zh-TW': '不必一個人硬扛。先走進有同感的人在的空間吧',
      vi: 'Không cần tự giải một mình. Hãy bước vào không gian có người cùng cảm xúc',
      id: 'Tidak harus diselesaikan sendirian. Masuk dulu ke ruang di mana orang merasakan hal yang sama',
    }),
    crisisNote: null,
    oneLiner: null,
    shareSnippet: L({
      ko: '외로움 농도: 60% 🌥️ 사람들 속에서도 혼자라는 느낌 든다는 거... 공감되는 사람 있으면 댓글 남겨줘 → 너는 몇 %야?',
      en: 'Loneliness level: 60% 🌥️ Feeling alone even in a crowd... if you get it, drop a comment → What\'s yours?',
      ja: '孤独濃度：60% 🌥️ 人の中にいても一人って感じるらしい…わかる人いたらコメントして → 君は何%？',
      'zh-CN': '孤独浓度：60% 🌥️ 说是人群里也会觉得自己一个人…有共鸣的留言一下 → 你是几%？',
      'zh-TW': '孤獨濃度：60% 🌥️ 說是人群裡也會覺得自己一個人…有共鳴的留言一下 → 你是幾%？',
      vi: 'Nồng độ cô đơn: 60% 🌥️ Bảo là giữa đám đông vẫn thấy một mình… ai đồng cảm thì comment nhé → Bạn bao nhiêu %?',
      id: 'Kadar kesepian: 60% 🌥️ Katanya merasa sendirian meski di keramaian… kalau resonate, tinggalkan komentar → Kamu berapa %?',
    }),
  },
  {
    type: 'Type5',
    emoji: '🌧️',
    title: L({
      ko: '외로움 농도 80%, 깊은 고립감형 🌧️',
      en: 'Loneliness Level 80%, Deep Isolation Type 🌧️',
      ja: '孤独濃度80%、深い孤立感型 🌧️',
      'zh-CN': '孤独浓度 80%，深度孤立感型 🌧️',
      'zh-TW': '孤獨濃度 80%，深度孤立感型 🌧️',
      vi: 'Nồng độ cô đơn 80%, kiểu cô lập sâu 🌧️',
      id: 'Kadar Kesepian 80%, Tipe Isolasi Dalam 🌧️',
    }),
    shortDescription: L({
      ko: '연결이 많이 부족합니다. 이 감정을 혼자 감당하고 있는 상태입니다.',
      en: 'Connection is seriously lacking. You\'re carrying this feeling alone.',
      ja: 'つながりが大きく足りていません。この気持ちを一人で抱えている状態です。',
      'zh-CN': '连接严重不足。这份情绪，你在一个人扛。',
      'zh-TW': '連結嚴重不足。這份情緒，你在一個人扛。',
      vi: 'Kết nối thiếu rất nhiều. Bạn đang tự gánh cảm xúc này một mình.',
      id: 'Koneksi sangat kurang. Kamu menanggung perasaan ini sendirian.',
    }),
    description: L({
      ko: '말할 사람이 없거나 있어도 진짜 말을 꺼내기 어렵고 연락도 잘 오지 않으며 혼자라는 생각이 자주 드는 상태입니다. 이 외로움은 결함이 아닙니다. 그러나 이 상태가 오래되면 힘들어집니다. 연결을 만들어가는 것이 지금 가장 중요합니다.',
      en: 'You may have no one to talk to—or someone exists but it\'s hard to open up, messages barely come, and "I\'m alone" shows up often. This loneliness isn\'t a flaw. But if it lasts, it gets heavy. Building connection matters most right now.',
      ja: '話せる人がいないか、いても本音を出せず、連絡もあまり来ず、「一人だ」という思いがよく浮かぶ状態です。この孤独は欠点ではありません。でも長く続くとつらくなります。つながりを作っていくことが今いちばん大切です。',
      'zh-CN': '可能没有可说的人，或者有人却很难说出口；消息也很少来，「我是一个人」常冒出来。这份孤独不是缺陷。但拖太久会很难受。此刻最重要的是去建立连接。',
      'zh-TW': '可能沒有可說的人，或者有人卻很難說出口；訊息也很少來，「我是一個人」常冒出來。這份孤獨不是缺陷。但拖太久會很難受。此刻最重要的是去建立連結。',
      vi: 'Có thể không có ai để nói—hoặc có người nhưng khó mở lời, tin nhắn cũng ít đến, và ý nghĩ "mình một mình" xuất hiện thường xuyên. Cô đơn này không phải lỗi. Nhưng kéo dài sẽ nặng. Xây kết nối là điều quan trọng nhất lúc này.',
      id: 'Bisa jadi tidak ada orang untuk diajak bicara—atau ada tapi sulit membuka diri, chat jarang datang, dan "aku sendirian" sering muncul. Kesepian ini bukan cacat. Tapi kalau lama, akan berat. Membangun koneksi adalah yang paling penting sekarang.',
    }),
    concentration: L({
      ko: '80~90% 🌧️',
      en: '80~90% 🌧️',
      ja: '80~90% 🌧️',
      'zh-CN': '80~90% 🌧️',
      'zh-TW': '80~90% 🌧️',
      vi: '80~90% 🌧️',
      id: '80~90% 🌧️',
    }),
    currentState: L({
      ko: '깊은 고립감·소통 니즈 심각하게 부족·연결 갈증 큼',
      en: 'Deep isolation · Connection needs severely unmet · Strong thirst to connect',
      ja: '深い孤立感・コミュニケーション欲求が深刻に不足・つながりの渇きが大きい',
      'zh-CN': '深度孤立感 · 沟通需求严重不足 · 连接渴望强烈',
      'zh-TW': '深度孤立感 · 溝通需求嚴重不足 · 連結渴望強烈',
      vi: 'Cô lập sâu · Nhu cầu giao tiếp thiếu nghiêm trọng · Khát kết nối lớn',
      id: 'Isolasi dalam · Kebutuhan koneksi sangat kurang · Haus koneksi besar',
    }),
    strength: null,
    actions: L({
      ko: '오늘 딱 한 사람에게 "요즘 어때?"라고 먼저 연락해보기\n온라인이든 오프라인이든 관심 있는 커뮤니티 하나 찾아보기\n이 감정을 글로 써보기. 아무도 안 봐도 됩니다. 꺼내는 것 자체가 중요합니다',
      en: 'Today, message just one person: "How\'ve you been?"\nFind one community you care about—online or offline\nWrite this feeling down. No one has to see it. Getting it out matters',
      ja: '今日、たった一人に「最近どう？」と先に連絡してみる\nオンラインでもオフラインでも、興味のあるコミュニティを一つ探す\nこの気持ちを書いてみる。誰も見なくてもいい。出すこと自体が大切です',
      'zh-CN': '今天只给一个人先发一句「最近怎么样？」\n找一个你感兴趣的社群——线上或线下都行\n把这种感觉写下来。不用给人看。说出来本身就重要',
      'zh-TW': '今天只給一個人先發一句「最近怎麼樣？」\n找一個你感興趣的社群——線上或線下都行\n把這種感覺寫下來。不用給人看。說出來本身就重要',
      vi: 'Hôm nay chỉ nhắn trước một người: "Dạo này thế nào?"\nTìm một cộng đồng mình quan tâm—online hay offline đều được\nViết cảm xúc này ra. Không ai cần xem. Việc nói ra mới quan trọng',
      id: 'Hari ini chat duluan ke satu orang saja: "Gimana kabarnya?"\nCari satu komunitas yang kamu minati—online atau offline\nTulis perasaan ini. Tidak perlu ada yang baca. Mengeluarkannya saja sudah penting',
    }),
    community: L({
      ko: '지금 당장 연결이 어렵다면 온라인 커뮤니티에서 가볍게 시작해도 됩니다. 댓글 하나가 연결의 시작이 됩니다',
      en: 'If connecting face-to-face feels hard right now, start lightly in an online community. One comment can be the start',
      ja: '今すぐつながるのが難しければ、オンラインコミュニティで軽く始めても大丈夫。コメント一つがつながりの始まりになります',
      'zh-CN': '如果现在当面连接很难，也可以从线上社群轻松开始。一条评论，就是连接的起点',
      'zh-TW': '如果現在當面連結很難，也可以從線上社群輕鬆開始。一則留言，就是連結的起點',
      vi: 'Nếu kết nối trực tiếp lúc này khó, có thể bắt đầu nhẹ trong cộng đồng online. Một comment có thể là khởi đầu',
      id: 'Kalau terhubung langsung terasa sulit sekarang, mulai ringan di komunitas online saja. Satu komentar bisa jadi awal koneksi',
    }),
    crisisNote: L({
      ko: '💙 오늘 많이 힘들다면: 가까운 사람에게 솔직하게 "나 요즘 많이 외로워"라고 말해보세요. 혼자 감당하지 않아도 됩니다',
      en: '💙 If today feels really heavy: tell someone close, honestly, "I\'ve been really lonely lately." You don\'t have to carry this alone',
      ja: '💙 今日とてもつらいなら：近い人に正直に「最近すごく寂しい」と伝えてみてください。一人で抱えなくても大丈夫です',
      'zh-CN': '💙 如果今天特别难受：对亲近的人诚实说一句「我最近真的很孤独」。不必一个人扛',
      'zh-TW': '💙 如果今天特別難受：對親近的人誠實說一句「我最近真的很孤獨」。不必一個人扛',
      vi: '💙 Nếu hôm nay thật nặng nề: hãy thật lòng nói với người thân gần "Dạo này mình rất cô đơn." Bạn không cần tự gánh một mình',
      id: '💙 Kalau hari ini terasa sangat berat: bilang jujur ke orang dekat, "Akhir-akhir ini aku sangat kesepian." Tidak harus ditanggung sendirian',
    }),
    oneLiner: null,
    shareSnippet: L({
      ko: '외로움 농도: 80% 🌧️ 진짜로 통하는 느낌이 오래됐다는 거... 이거 공감되면 같이 커뮤니티 들어와봐 → 너는 몇 %야?',
      en: 'Loneliness level: 80% 🌧️ It\'s been forever since I felt truly understood... if you get this, come join the community → What\'s yours?',
      ja: '孤独濃度：80% 🌧️ 本当に通じ合う感じが久しぶりらしい…わかる人はコミュニティに入ってきて → 君は何%？',
      'zh-CN': '孤独浓度：80% 🌧️ 说是真正对上的感觉已经很久了…有共鸣就一起进社群吧 → 你是几%？',
      'zh-TW': '孤獨濃度：80% 🌧️ 說是真正對上的感覺已經很久了…有共鳴就一起進社群吧 → 你是幾%？',
      vi: 'Nồng độ cô đơn: 80% 🌧️ Bảo là đã lâu rồi không cảm thấy thật sự ăn ý… đồng cảm thì vào cộng đồng cùng nhé → Bạn bao nhiêu %?',
      id: 'Kadar kesepian: 80% 🌧️ Katanya sudah lama tidak merasa benar-benar nyambung… kalau resonate, masuk komunitas bareng → Kamu berapa %?',
    }),
  },
  {
    type: 'Type6',
    emoji: '💙',
    title: L({
      ko: '외로움 농도 100%, 완전 고립감형 💙',
      en: 'Loneliness Level 100%, Complete Isolation Type 💙',
      ja: '孤独濃度100%、完全孤立感型 💙',
      'zh-CN': '孤独浓度 100%，完全孤立感型 💙',
      'zh-TW': '孤獨濃度 100%，完全孤立感型 💙',
      vi: 'Nồng độ cô đơn 100%, kiểu cô lập hoàn toàn 💙',
      id: 'Kadar Kesepian 100%, Tipe Isolasi Total 💙',
    }),
    shortDescription: L({
      ko: '지금 많이 외롭습니다. 이 감정이 오래됐을 수 있습니다.',
      en: 'You\'re really lonely right now. This feeling may have been around for a while.',
      ja: '今、とても寂しいです。この気持ちが長く続いてきたのかもしれません。',
      'zh-CN': '此刻你真的很孤独。这种感觉可能已经很久了。',
      'zh-TW': '此刻你真的很孤獨。這種感覺可能已經很久了。',
      vi: 'Lúc này bạn rất cô đơn. Cảm xúc này có thể đã kéo dài khá lâu.',
      id: 'Sekarang kamu sangat kesepian. Perasaan ini mungkin sudah lama ada.',
    }),
    description: L({
      ko: '말할 사람이 없고 연결이 거의 없으며 혼자라는 생각이 기본값처럼 깔려있는 상태입니다. 이것은 당신이 부족한 사람이어서가 아닙니다. 이 상태가 만들어진 데는 이유가 있고 달라질 수 있습니다. 지금 이 결과를 보고 있다는 것이 이미 변화의 시작입니다.',
      en: 'There\'s no one to talk to, almost no connection, and "I\'m alone" feels like the default. That doesn\'t mean you\'re lacking as a person. This state formed for reasons—and it can change. Just looking at this result is already the start of change.',
      ja: '話せる人がなく、つながりがほとんどなく、「一人だ」という思いがデフォルトのようにある状態です。これはあなたが足りない人だからではありません。この状態には理由があり、変われます。今この結果を見ていること自体が、もう変化の始まりです。',
      'zh-CN': '没有可说的人，连接几乎没有，「我是一个人」像默认值一样。这不代表你是不够好的人。这个状态有它形成的原因，也可以改变。此刻看着这个结果，本身就是变化的开始。',
      'zh-TW': '沒有可說的人，連結幾乎沒有，「我是一個人」像預設值一樣。這不代表你是不夠好的人。這個狀態有它形成的原因，也可以改變。此刻看著這個結果，本身就是變化的開始。',
      vi: 'Không có ai để nói, kết nối gần như không có, và ý nghĩ "mình một mình" như mặc định. Điều đó không có nghĩa bạn thiếu sót. Trạng thái này có lý do—và có thể đổi. Việc đang xem kết quả này đã là khởi đầu của thay đổi.',
      id: 'Tidak ada orang untuk diajak bicara, koneksi hampir tidak ada, dan "aku sendirian" terasa seperti default. Itu bukan berarti kamu orang yang kurang. Keadaan ini terbentuk karena suatu alasan—dan bisa berubah. Melihat hasil ini saja sudah jadi awal perubahan.',
    }),
    concentration: L({
      ko: '100% 💙',
      en: '100% 💙',
      ja: '100% 💙',
      'zh-CN': '100% 💙',
      'zh-TW': '100% 💙',
      vi: '100% 💙',
      id: '100% 💙',
    }),
    currentState: L({
      ko: '완전 고립감·소통 니즈 심각 부족·연결 단절',
      en: 'Complete isolation · Connection needs critically unmet · Disconnected',
      ja: '完全な孤立感・コミュニケーション欲求が深刻に不足・つながり断絶',
      'zh-CN': '完全孤立感 · 沟通需求严重不足 · 连接断裂',
      'zh-TW': '完全孤立感 · 溝通需求嚴重不足 · 連結斷裂',
      vi: 'Cô lập hoàn toàn · Nhu cầu giao tiếp thiếu nghiêm trọng · Đứt kết nối',
      id: 'Isolasi total · Kebutuhan koneksi kritis · Terputus',
    }),
    strength: null,
    actions: L({
      ko: '이 결과를 캡처해서 누군가에게 보내며 "나 이런 상태야"라고 말해보기\n퀴즈오아시스 커뮤니티에 이 결과를 공유해보기. 같은 감정을 가진 사람들이 있습니다\n지금 당장 연결이 어렵다면 그냥 이 결과를 보면서 "내가 연결을 원한다"는 것을 인정해주기',
      en: 'Screenshot this result and send it to someone with "This is where I\'m at"\nShare it in the QuizOasis community—others feel this too\nIf connecting right now feels impossible, just look at this result and admit "I want connection"',
      ja: 'この結果をスクショして誰かに送り、「今こんな状態だよ」と伝えてみる\nQuizOasisコミュニティにこの結果をシェアしてみる。同じ気持ちの人がいます\n今すぐつながるのが難しければ、この結果を見ながら「つながりたい」と認めてあげる',
      'zh-CN': '截图这个结果发给某人，说一声「我现在是这样」\n在 QuizOasis 社群分享这个结果。有同感的人在\n如果现在连接很难，就看着这个结果，承认「我想要连接」',
      'zh-TW': '截圖這個結果發給某人，說一聲「我現在是這樣」\n在 QuizOasis 社群分享這個結果。有同感的人在\n如果現在連結很難，就看著這個結果，承認「我想要連結」',
      vi: 'Chụp kết quả này gửi cho ai đó và nói "Mình đang thế này"\nChia sẻ trong cộng đồng QuizOasis—có người cùng cảm xúc\nNếu kết nối ngay lúc này khó, hãy nhìn kết quả và thừa nhận "Mình muốn kết nối"',
      id: 'Screenshot hasil ini dan kirim ke seseorang dengan "Aku lagi di kondisi ini"\nShare di komunitas QuizOasis—ada yang merasakan hal yang sama\nKalau terhubung sekarang terasa mustahil, lihat saja hasil ini dan akui "Aku ingin koneksi"',
    }),
    community: L({
      ko: '외로움을 느끼는 사람은 혼자가 아닙니다. 이 결과를 보고 있는 사람들이 지금 함께 있습니다',
      en: 'People who feel lonely are not alone. Everyone looking at this result is here with you',
      ja: '孤独を感じる人は一人ではありません。この結果を見ている人たちが、いま一緒にいます',
      'zh-CN': '感到孤独的人不孤单。正在看这个结果的人，此刻和你在一起',
      'zh-TW': '感到孤獨的人不孤單。正在看這個結果的人，此刻和你在一起',
      vi: 'Người cảm thấy cô đơn không đơn độc. Những người đang xem kết quả này đang ở đây cùng bạn',
      id: 'Orang yang merasa kesepian tidak sendirian. Orang-orang yang melihat hasil ini sedang bersamamu sekarang',
    }),
    crisisNote: L({
      ko: '💙 오늘 많이 힘들다면: 정신건강 위기상담전화 1577-0199 (24시간)에 연락하는 것도 방법입니다. 말할 수 있는 곳이 있습니다',
      en: '💙 If today feels really heavy: reaching out to a mental health crisis line in your area is an option. There is somewhere you can talk',
      ja: '💙 今日とてもつらいなら：お住まいの地域のメンタルヘルス相談窓口に連絡するのも一つの方法です。話せる場所があります',
      'zh-CN': '💙 如果今天特别难受：也可以联系当地的心理健康危机热线。有地方可以说话',
      'zh-TW': '💙 如果今天特別難受：也可以聯繫當地的心理健康危機專線。有地方可以說話',
      vi: '💙 Nếu hôm nay thật nặng nề: gọi đường dây hỗ trợ sức khỏe tâm thần tại nơi bạn ở cũng là một cách. Có chỗ để nói chuyện',
      id: '💙 Kalau hari ini terasa sangat berat: menghubungi hotline kesehatan mental di daerahmu juga bisa jadi pilihan. Ada tempat untuk berbicara',
    }),
    oneLiner: L({
      ko: '외로움을 느끼는 사람은 혼자가 아닙니다. 이 결과를 보고 있는 사람들이 지금 함께 있습니다',
      en: 'People who feel lonely are not alone. Everyone looking at this result is here with you',
      ja: '孤独を感じる人は一人ではありません。この結果を見ている人たちが、いま一緒にいます',
      'zh-CN': '感到孤独的人不孤单。正在看这个结果的人，此刻和你在一起',
      'zh-TW': '感到孤獨的人不孤單。正在看這個結果的人，此刻和你在一起',
      vi: 'Người cảm thấy cô đơn không đơn độc. Những người đang xem kết quả này đang ở đây cùng bạn',
      id: 'Orang yang merasa kesepian tidak sendirian. Orang-orang yang melihat hasil ini sedang bersamamu sekarang',
    }),
    shareSnippet: L({
      ko: '외로움 농도: 100% 💙 지금 많이 외롭다는 거 인정함... 이 결과 보고 있는 사람들 다 같이 외로운 거 아닌가 ㅠ → 너는 몇 %야? 같이 얘기해봐',
      en: 'Loneliness level: 100% 💙 Yeah I\'m really lonely rn... maybe everyone looking at this is lonely too ㅠ → What\'s yours? Talk to me',
      ja: '孤独濃度：100% 💙 今めっちゃ寂しいの認める…これ見てる人たちみんな寂しいんじゃない ㅠ → 君は何%？一緒に話そ',
      'zh-CN': '孤独浓度：100% 💙 承认，现在真的很孤独…看这个结果的人是不是都挺孤独的 ㅠ → 你是几%？一起聊聊',
      'zh-TW': '孤獨濃度：100% 💙 承認，現在真的很孤獨…看這個結果的人是不是都挺孤獨的 ㅠ → 你是幾%？一起聊聊',
      vi: 'Nồng độ cô đơn: 100% 💙 Thừa nhận lúc này mình rất cô đơn… những người đang xem kết quả này chắc cũng cô đơn ㅠ → Bạn bao nhiêu %? Nói chuyện với mình đi',
      id: 'Kadar kesepian: 100% 💙 Iya aku lagi sangat kesepian… orang yang lihat hasil ini kayaknya juga kesepian ㅠ → Kamu berapa %? Yuk ngobrol',
    }),
  },
];
