/** 나의 '자존감 방패' 강도 — 12문항 4지선다, A=0 B=1 C=2 D=3, 총점 0~36 → Type1~6 */

type Locale = 'ko' | 'en' | 'ja' | 'zh-CN' | 'zh-TW' | 'vi' | 'id';
type ML = Record<Locale, string>;
function L(m: ML): Record<string, string> {
  return m;
}

export interface Phase3SelfEsteemShieldStrengthQuestion {
  id: number;
  question: Record<string, string>;
  options: { text: Record<string, string>; score: number }[];
}

export interface Phase3SelfEsteemShieldStrengthResult {
  type: string;
  emoji: string;
  title: Record<string, string>;
  shortDescription: Record<string, string>;
  description: Record<string, string>;
  shieldStrength: Record<string, string>;
  pattern: Record<string, string> | null;
  strength: Record<string, string> | null;
  needNow: Record<string, string> | null;
  actions: Record<string, string> | null;
  remainingTask: Record<string, string> | null;
  canDo: Record<string, string> | null;
  caution: Record<string, string> | null;
  toOthers: Record<string, string> | null;
  affirmation: Record<string, string> | null;
  shareSnippet: Record<string, string>;
}

export function calculatePhase3SelfEsteemShieldStrengthResult(answers: number[]): string {
  const total = answers.reduce((sum, s) => sum + (s ?? 0), 0);
  if (total <= 5) return 'Type1';
  if (total <= 11) return 'Type2';
  if (total <= 19) return 'Type3';
  if (total <= 27) return 'Type4';
  if (total <= 33) return 'Type5';
  return 'Type6';
}

export function getPhase3SelfEsteemShieldStrengthResultByType(
  type: string
): Phase3SelfEsteemShieldStrengthResult | undefined {
  return phase3SelfEsteemShieldStrengthResults.find((r) => r.type === type);
}

export const phase3SelfEsteemShieldStrengthQuestions: Phase3SelfEsteemShieldStrengthQuestion[] = [
  {
    id: 1,
    question: L({
      ko: '누군가 나를 공개적으로 비판했을 때 나는?',
      en: 'When someone publicly criticizes me, I...',
      ja: '誰かが公の場で私を批判したとき、私は？',
      'zh-CN': '当有人在公开场合批评我时，我会？',
      'zh-TW': '當有人在公開場合批評我時，我會？',
      vi: 'Khi ai đó chỉ trích công khai, tôi...',
      id: 'Ketika seseorang mengkritikku di depan umum, aku...',
    }),
    options: [
      {
        text: L({
      ko: '그 자리에서 얼굴이 빨개지고 그 말이 며칠 동안 머릿속을 떠나지 않는다',
      en: 'My face turns red on the spot and the words stay in my head for days',
      ja: 'その場で顔が赤くなり、その言葉が数日頭から離れない',
      'zh-CN': '当场脸红，那句话好几天都忘不掉',
      'zh-TW': '當場臉紅，那句話好幾天都忘不掉',
      vi: 'Đỏ mặt ngay tại chỗ và câu đó cứ ám ảnh vài ngày',
      id: 'Langsung merah muka dan kata itu terngiang berhari-hari',
    }),
        score: 0,
      },
      {
        text: L({
      ko: '상처받지만 시간이 지나면 조금씩 잊힌다. 다만 그 사람이 신경 쓰인다',
      en: 'It hurts, but I slowly forget over time—though that person stays on my mind',
      ja: '傷つくが時間が経てば少しずつ忘れる。ただその人が気になる',
      'zh-CN': '会受伤，但时间久了会慢慢淡忘，只是还会在意那个人',
      'zh-TW': '會受傷，但時間久了會慢慢淡忘，只是還會在意那個人',
      vi: 'Bị tổn thương nhưng theo thời gian dần quên—dù vẫn để ý người đó',
      id: 'Terluka, tapi lama-kelamaan perlahan terlupa—meski orang itu tetap menggangguku',
    }),
        score: 1,
      },
      {
        text: L({
      ko: '일단 그 비판이 맞는 말인지 생각해본다. 맞으면 받아들이고 아니면 흘린다',
      en: 'I first consider if the criticism is valid. If yes, I accept it; if not, I let it go',
      ja: 'まずその批判が正しいか考える。正しければ受け入れ、違えば流す',
      'zh-CN': '先想想批评对不对，对就接受，不对就放过',
      'zh-TW': '先想想批評對不對，對就接受，不對就放過',
      vi: 'Trước hết nghĩ xem lời chỉ trích có đúng không. Đúng thì nhận, sai thì buông',
      id: 'Pertama-tama aku pikir apakah kritik itu benar. Kalau benar aku terima, kalau tidak aku lepaskan',
    }),
        score: 2,
      },
      {
        text: L({
      ko: '비판의 내용을 듣되 그것이 나의 전부를 정의하지 않는다는 것을 안다',
      en: 'I listen to the criticism but know it doesn\'t define all of me',
      ja: '批判の内容は聞くが、それが私のすべてを定義しないとわかっている',
      'zh-CN': '会听批评的内容，但知道那不能定义全部的我',
      'zh-TW': '會聽批評的內容，但知道那不能定義全部的我',
      vi: 'Tôi lắng nghe nhưng biết nó không định nghĩa toàn bộ con người tôi',
      id: 'Aku mendengarkan kritiknya, tapi tahu itu tidak mendefinisikan seluruh diriku',
    }),
        score: 3,
      },
    ],
  },
  {
    id: 2,
    question: L({
      ko: '친구가 나보다 더 좋은 결과를 냈을 때 나는?',
      en: 'When a friend gets a better result than me, I...',
      ja: '友達が自分より良い結果を出したとき、私は？',
      'zh-CN': '当朋友取得比我更好的结果时，我会？',
      'zh-TW': '當朋友取得比我更好的結果時，我會？',
      vi: 'Khi bạn bè đạt kết quả tốt hơn tôi, tôi...',
      id: 'Ketika teman mendapat hasil lebih baik dariku, aku...',
    }),
    options: [
      {
        text: L({
      ko: '나 자신이 부족하다는 생각이 강하게 든다. 비교가 오래 남는다',
      en: 'I strongly feel I\'m not enough. The comparison lingers',
      ja: '自分が足りないと強く感じる。比較が長く残る',
      'zh-CN': '强烈觉得自己不够好，比较感会持续很久',
      'zh-TW': '強烈覺得自己不夠好，比較感會持續很久',
      vi: 'Cảm giác mình không đủ rất mạnh. So sánh cứ ám ảnh',
      id: 'Sangat merasa diriku kurang. Perbandingan itu lama tertinggal',
    }),
        score: 0,
      },
      {
        text: L({
      ko: '부럽기도 하고 나 자신이 초라하게 느껴지기도 한다',
      en: 'I feel envious and sometimes small compared to myself',
      ja: '羨ましくもなり、自分が情けなく感じることもある',
      'zh-CN': '会羡慕，也会觉得自己很渺小',
      'zh-TW': '會羨慕，也會覺得自己很渺小',
      vi: 'Vừa ghen tị vừa thấy bản thân nhỏ bé',
      id: 'Iri sekaligus merasa diriku terlihat kecil',
    }),
        score: 1,
      },
      {
        text: L({
      ko: '축하해주면서 나도 더 잘하고 싶다는 자극을 받는다',
      en: 'I congratulate them and feel motivated to do better myself',
      ja: '祝福しつつ、自分ももっと頑張りたいと刺激を受ける',
      'zh-CN': '会祝贺对方，也激励自己想做得更好',
      'zh-TW': '會祝賀對方，也激勵自己想做得更好',
      vi: 'Chúc mừng họ và cảm thấy được thúc đẩy để cố gắng hơn',
      id: 'Aku memberi selamat dan merasa termotivasi untuk lebih baik',
    }),
        score: 2,
      },
      {
        text: L({
      ko: '진심으로 기뻐해준다. 친구의 결과가 나의 가치와 무관하다는 걸 안다',
      en: 'I\'m genuinely happy for them. I know their result has nothing to do with my worth',
      ja: '心から喜ぶ。友達の結果が自分の価値と無関係だとわかっている',
      'zh-CN': '真心为对方高兴，知道朋友的结果与我的价值无关',
      'zh-TW': '真心為對方高興，知道朋友的結果與我的價值無關',
      vi: 'Vui thật lòng. Biết kết quả của bạn không liên quan đến giá trị của tôi',
      id: 'Aku ikut bahagia tulus. Hasil temanku tidak ada kaitannya dengan nilai diriku',
    }),
        score: 3,
      },
    ],
  },
  {
    id: 3,
    question: L({
      ko: '열심히 한 일이 실패로 끝났을 때 나는?',
      en: 'When something I worked hard on ends in failure, I...',
      ja: '一生懸命取り組んだことが失敗に終わったとき、私は？',
      'zh-CN': '当努力的事情以失败收场时，我会？',
      'zh-TW': '當努力的事情以失敗收場時，我會？',
      vi: 'Khi việc mình cố gắng kết thúc bằng thất bại, tôi...',
      id: 'Ketika hal yang kukerjakan keras berakhir gagal, aku...',
    }),
    options: [
      {
        text: L({
      ko: '내가 능력 없는 사람이라는 생각이 든다. 한동안 새로운 도전이 어렵다',
      en: 'I think I\'m incapable. New challenges feel hard for a while',
      ja: '自分は能力がないと思う。しばらく新しい挑戦が難しい',
      'zh-CN': '觉得自己没能力，一段时间不敢再挑战',
      'zh-TW': '覺得自己沒能力，一段時間不敢再挑戰',
      vi: 'Nghĩ mình không có năng lực. Một thời gian khó thử thách mới',
      id: 'Aku pikir aku tidak mampu. Cukup lama sulit mencoba hal baru',
    }),
        score: 0,
      },
      {
        text: L({
      ko: '많이 속상하고 자책하다가 시간이 지나면 회복된다',
      en: 'I\'m very upset and blame myself, but recover over time',
      ja: 'とても落ち込み自責するが、時間が経てば回復する',
      'zh-CN': '很失落也会自责，但时间久了会恢复',
      'zh-TW': '很失落也會自責，但時間久了會恢復',
      vi: 'Rất buồn và tự trách, nhưng theo thời gian hồi phục',
      id: 'Sangat sedih dan menyalahkan diri, tapi lama-kelamaan pulih',
    }),
        score: 1,
      },
      {
        text: L({
      ko: '실망스럽지만 무엇이 문제였는지 파악하려 한다',
      en: 'I\'m disappointed but try to figure out what went wrong',
      ja: 'がっかりするが、何が問題だったか把握しようとする',
      'zh-CN': '会失望，但会试着找出问题所在',
      'zh-TW': '會失望，但會試著找出問題所在',
      vi: 'Thất vọng nhưng cố tìm hiểu vấn đề là gì',
      id: 'Kecewa, tapi mencoba memahami apa yang salah',
    }),
        score: 2,
      },
      {
        text: L({
      ko: '실패를 나의 가치와 분리한다. 이번 일이 안 됐을 뿐 내가 실패한 게 아니다',
      en: 'I separate failure from my worth. This attempt failed—I didn\'t',
      ja: '失敗を自分の価値と切り離す。今回うまくいかなかっただけで、自分が失敗したわけではない',
      'zh-CN': '把失败和价值分开。只是这次没成，不是整个人失败',
      'zh-TW': '把失敗和價值分開。只是這次沒成，不是整個人失敗',
      vi: 'Tách thất bại khỏi giá trị bản thân. Chỉ là lần này không được, không phải tôi thất bại',
      id: 'Aku pisahkan kegagalan dari nilai diri. Hanya upaya ini yang gagal, bukan aku',
    }),
        score: 3,
      },
    ],
  },
  {
    id: 4,
    question: L({
      ko: '내 외모·능력·성격에 대한 부정적인 말을 들었을 때 나는?',
      en: 'When I hear negative comments about my appearance, ability, or personality, I...',
      ja: '外見・能力・性格について否定的な言葉を聞いたとき、私は？',
      'zh-CN': '听到关于外貌、能力或性格的负面评价时，我会？',
      'zh-TW': '聽到關於外貌、能力或性格的負面評價時，我會？',
      vi: 'Khi nghe lời tiêu cực về ngoại hình, năng lực hoặc tính cách, tôi...',
      id: 'Ketika mendengar komentar negatif tentang penampilan, kemampuan, atau kepribadianku, aku...',
    }),
    options: [
      {
        text: L({
      ko: '그 말이 맞는 것 같아서 더 위축된다. 스스로도 그렇게 생각하게 된다',
      en: 'It feels true, so I shrink even more and start believing it myself',
      ja: 'その言葉が正しいように感じ、さらに萎縮する。自分もそう思い始める',
      'zh-CN': '觉得说得对，更加退缩，也开始那样看自己',
      'zh-TW': '覺得說得對，更加退縮，也開始那樣看自己',
      vi: 'Cảm giác đúng nên càng chùn lại và bắt đầu nghĩ vậy về mình',
      id: 'Terasa benar, jadi makin mengecil dan mulai percaya sendiri',
    }),
        score: 0,
      },
      {
        text: L({
      ko: '상처받고 기분이 나쁘지만 억지로 괜찮은 척한다',
      en: 'It hurts and I feel bad, but I pretend I\'m fine',
      ja: '傷つき気分も悪いが、無理に平気なふりをする',
      'zh-CN': '会受伤、心情很差，但强装没事',
      'zh-TW': '會受傷、心情很差，但強裝沒事',
      vi: 'Bị tổn thương, khó chịu nhưng giả vờ ổn',
      id: 'Terluka dan jelek perasaanku, tapi pura-pura baik-baik saja',
    }),
        score: 1,
      },
      {
        text: L({
      ko: '순간 상처받지만 내 실제 모습을 떠올리며 그 말을 다시 생각해본다',
      en: 'It stings at first, but I recall who I really am and reconsider the comment',
      ja: '一瞬傷つくが、本当の自分を思い出し、その言葉を再考する',
      'zh-CN': '瞬间会受伤，但会想起真实的我，再重新思考那句话',
      'zh-TW': '瞬間會受傷，但會想起真實的我，再重新思考那句話',
      vi: 'Ban đầu đau, nhưng nhớ lại con người thật của mình rồi suy nghĩ lại',
      id: 'Sekilas terluka, tapi aku ingat diriku yang sebenarnya lalu meninjau ulang',
    }),
        score: 2,
      },
      {
        text: L({
      ko: '그 말이 상대방의 시각일 뿐이라는 걸 안다. 내 자신에 대한 기준은 내가 갖고 있다',
      en: 'I know it\'s just their perspective. I hold my own standard for myself',
      ja: 'それは相手の視点に過ぎないとわかる。自分への基準は自分が持っている',
      'zh-CN': '知道那只是对方的视角，评价自己的标准由我自己掌握',
      'zh-TW': '知道那只是對方的視角，評價自己的標準由我自己掌握',
      vi: 'Biết đó chỉ là góc nhìn của họ. Tiêu chuẩn về bản thân do tôi nắm giữ',
      id: 'Aku tahu itu hanya sudut pandang mereka. Standar tentang diriku ada pada diriku sendiri',
    }),
        score: 3,
      },
    ],
  },
  {
    id: 5,
    question: L({
      ko: '아무 이유 없이 누군가 나를 싫어한다는 것을 알게 됐을 때 나는?',
      en: 'When I learn someone dislikes me for no clear reason, I...',
      ja: '理由もなく誰かに嫌われていると知ったとき、私は？',
      'zh-CN': '当知道有人无缘无故不喜欢我时，我会？',
      'zh-TW': '當知道有人無緣無故不喜歡我時，我會？',
      vi: 'Khi biết ai đó ghét mình không rõ lý do, tôi...',
      id: 'Ketika tahu seseorang tidak suka padaku tanpa alasan jelas, aku...',
    }),
    options: [
      {
        text: L({
      ko: '내가 뭔가 잘못한 게 있나 계속 생각하게 된다. 그 사람에게 맞추려 한다',
      en: 'I keep wondering if I did something wrong and try to adjust for them',
      ja: '自分が何か間違ったのではと考え続け、その人に合わせようとする',
      'zh-CN': '不断想是不是自己做错了，试图迎合对方',
      'zh-TW': '不斷想是不是自己做錯了，試圖迎合對方',
      vi: 'Cứ nghĩ mình có làm sai không và cố chiều theo họ',
      id: 'Terus berpikir apakah aku salah dan mencoba menyesuaikan diri',
    }),
        score: 0,
      },
      {
        text: L({
      ko: '신경 쓰이고 이유가 궁금해서 불편하다',
      en: 'It bothers me and I feel uneasy wondering why',
      ja: '気になり、理由が知りたくて居心地が悪い',
      'zh-CN': '会在意，好奇原因，感到不自在',
      'zh-TW': '會在意，好奇原因，感到不自在',
      vi: 'Bận tâm, tò mò lý do và cảm thấy khó chịu',
      id: 'Menggangguku dan aku penasaran alasannya',
    }),
        score: 1,
      },
      {
        text: L({
      ko: '이유를 파악하려 하지만 모든 사람이 나를 좋아할 필요는 없다는 것도 안다',
      en: 'I try to understand why, but also know not everyone has to like me',
      ja: '理由を把握しようとするが、全員に好かれる必要はないともわかっている',
      'zh-CN': '会试着弄清原因，但也知道不是所有人都必须喜欢我',
      'zh-TW': '會試著弄清原因，但也知道不是所有人都必須喜歡我',
      vi: 'Cố hiểu lý do, nhưng cũng biết không phải ai cũng phải thích mình',
      id: 'Aku coba pahami alasannya, tapi juga tahu tidak semua orang harus menyukaiku',
    }),
        score: 2,
      },
      {
        text: L({
      ko: '모든 사람에게 좋은 사람일 수 없다는 것을 안다. 크게 흔들리지 않는다',
      en: 'I know I can\'t be liked by everyone and don\'t get shaken much',
      ja: '全員に好かれる人にはなれないとわかり、大きく揺れない',
      'zh-CN': '知道不可能让所有人都喜欢，不会大幅动摇',
      'zh-TW': '知道不可能讓所有人都喜歡，不會大幅動搖',
      vi: 'Biết không thể được mọi người yêu thích và không lay chuyển nhiều',
      id: 'Aku tahu tidak bisa disukai semua orang dan tidak terlalu goyah',
    }),
        score: 3,
      },
    ],
  },
  {
    id: 6,
    question: L({
      ko: '내가 한 선택에 대해 주변에서 "왜 그걸 선택했어?" 하고 의문을 제기할 때 나는?',
      en: 'When people question my choice saying "Why did you choose that?", I...',
      ja: '自分の選択について周りが「なぜそれを選んだの？」と疑問を呈するとき、私は？',
      'zh-CN': '当周围人对我的选择问「为什么选那个？」时，我会？',
      'zh-TW': '當周圍人對我的選擇問「為什麼選那個？」時，我會？',
      vi: 'Khi mọi người hỏi "Sao bạn chọn cái đó?" về lựa chọn của tôi, tôi...',
      id: 'Ketika orang mempertanyakan pilihanku dengan "Kenapa memilih itu?", aku...',
    }),
    options: [
      {
        text: L({
      ko: '내 선택이 잘못된 건지 불안해지고 상대방 의견으로 쉽게 바뀐다',
      en: 'I worry my choice was wrong and easily change based on their opinion',
      ja: '自分の選択が間違いではと不安になり、相手の意見ですぐ変える',
      'zh-CN': '会担心选错了，容易因对方意见而改变',
      'zh-TW': '會擔心選錯了，容易因對方意見而改變',
      vi: 'Lo lắng mình chọn sai và dễ đổi theo ý kiến họ',
      id: 'Khawatir pilihanku salah dan mudah berubah mengikuti pendapat mereka',
    }),
        score: 0,
      },
      {
        text: L({
      ko: '흔들리긴 하지만 결국 내 선택을 유지하려 한다',
      en: 'I waver, but try to stick with my choice in the end',
      ja: '揺れるが、最終的には自分の選択を維持しようとする',
      'zh-CN': '会动摇，但最终还是想坚持自己的选择',
      'zh-TW': '會動搖，但最終還是想堅持自己的選擇',
      vi: 'Có lay chuyển nhưng cuối cùng vẫn cố giữ lựa chọn của mình',
      id: 'Goyah, tapi akhirnya berusaha tetap pada pilihanku',
    }),
        score: 1,
      },
      {
        text: L({
      ko: '상대방 의견을 듣고 판단한다. 납득되면 수정하고 아니면 내 선택을 유지한다',
      en: 'I listen and judge. If it makes sense I adjust; if not, I keep my choice',
      ja: '相手の意見を聞いて判断する。納得できれば修正し、そうでなければ維持する',
      'zh-CN': '听对方意见再判断，说得通就改，不通就维持',
      'zh-TW': '聽對方意見再判斷，說得通就改，不通就維持',
      vi: 'Nghe ý kiến rồi phán đoán. Hợp lý thì sửa, không thì giữ',
      id: 'Aku dengar pendapat mereka lalu menilai. Masuk akal aku ubah, kalau tidak aku pertahankan',
    }),
        score: 2,
      },
      {
        text: L({
      ko: '나의 선택에 충분한 이유가 있다는 것을 안다. 설명은 하되 흔들리지 않는다',
      en: 'I know I have good reasons for my choice. I explain but don\'t waver',
      ja: '自分の選択には十分な理由があるとわかる。説明はするが揺れない',
      'zh-CN': '知道自己的选择有足够理由，会解释但不被动摇',
      'zh-TW': '知道自己的選擇有足夠理由，會解釋但不動搖',
      vi: 'Biết lựa chọn của mình có lý do đủ. Giải thích nhưng không lay chuyển',
      id: 'Aku tahu pilihanku punya alasan cukup. Aku jelaskan tapi tidak goyah',
    }),
        score: 3,
      },
    ],
  },
  {
    id: 7,
    question: L({
      ko: '오랫동안 노력했는데 아무도 알아주지 않을 때 나는?',
      en: 'When no one recognizes my long efforts, I...',
      ja: '長い間努力したのに誰も認めてくれないとき、私は？',
      'zh-CN': '长期努力却没人认可时，我会？',
      'zh-TW': '長期努力卻沒人認可時，我會？',
      vi: 'Khi không ai công nhận nỗ lực lâu dài của tôi, tôi...',
      id: 'Ketika tidak ada yang mengakui usahaku yang panjang, aku...',
    }),
    options: [
      {
        text: L({
      ko: '내가 하는 일이 의미 없는 것 같아서 그만두고 싶어진다',
      en: 'I feel what I do is meaningless and want to quit',
      ja: '自分の努力が意味がないように感じ、やめたくなる',
      'zh-CN': '觉得做的事没意义，想放弃',
      'zh-TW': '覺得做的事沒意義，想放棄',
      vi: 'Cảm thấy việc mình làm vô nghĩa và muốn bỏ cuộc',
      id: 'Merasa usahaku tidak berarti dan ingin berhenti',
    }),
        score: 0,
      },
      {
        text: L({
      ko: '서운하고 인정받고 싶은 마음이 크다. 기운이 빠진다',
      en: 'I feel hurt and strongly want recognition. My energy drains',
      ja: '寂しく認められたい気持ちが強い。元気が抜ける',
      'zh-CN': '会觉得委屈，很想被认可，精力被抽走',
      'zh-TW': '會覺得委屈，很想被認可，精力被抽走',
      vi: 'Buồn và rất muốn được công nhận. Năng lượng tuột dần',
      id: 'Kecewa dan sangat ingin diakui. Energiku habis',
    }),
        score: 1,
      },
      {
        text: L({
      ko: '서운하지만 내가 이걸 왜 하고 있는지 다시 생각해본다',
      en: 'It stings, but I revisit why I\'m doing this',
      ja: '寂しいが、なぜこれをしているのか改めて考える',
      'zh-CN': '会委屈，但会重新想想为什么要做',
      'zh-TW': '會委屈，但會重新想想為什麼要做',
      vi: 'Buồn, nhưng suy nghĩ lại vì sao mình làm việc này',
      id: 'Sedih, tapi aku tinjau ulang mengapa aku melakukan ini',
    }),
        score: 2,
      },
      {
        text: L({
      ko: '타인의 인정은 보너스다. 나 자신이 이 노력의 가치를 알고 있으면 된다',
      en: 'Others\' recognition is a bonus. Knowing the value myself is enough',
      ja: '他人の認めはボーナス。自分がこの努力の価値を知っていれば十分',
      'zh-CN': '别人的认可是加分，我自己知道努力的价值就够了',
      'zh-TW': '別人的認可是加分，我自己知道努力的價值就夠了',
      vi: 'Sự công nhận của người khác chỉ là bonus. Tôi biết giá trị nỗ lực là đủ',
      id: 'Pengakuan orang lain bonus. Cukup aku sendiri tahu nilai usahaku',
    }),
        score: 3,
      },
    ],
  },
  {
    id: 8,
    question: L({
      ko: '실수를 했을 때 나는?',
      en: 'When I make a mistake, I...',
      ja: 'ミスをしたとき、私は？',
      'zh-CN': '当犯了错误时，我会？',
      'zh-TW': '當犯了錯誤時，我會？',
      vi: 'Khi mắc sai lầm, tôi...',
      id: 'Ketika aku membuat kesalahan, aku...',
    }),
    options: [
      {
        text: L({
      ko: '오랫동안 자책한다. "역시 나는 안 된다"는 생각이 든다',
      en: 'I blame myself for a long time. I think "I knew I wasn\'t good enough"',
      ja: '長い間自責する。「やっぱり自分はダメだ」と思う',
      'zh-CN': '会自责很久，觉得「果然我不行」',
      'zh-TW': '會自責很久，覺得「果然我不行」',
      vi: 'Tự trách lâu. Nghĩ "Đúng là mình không được"',
      id: 'Menyalahkan diri lama. Berpikir "Memang aku tidak cukup"',
    }),
        score: 0,
      },
      {
        text: L({
      ko: '한동안 기분이 안 좋지만 시간이 지나면 나아진다',
      en: 'I feel bad for a while, but improve over time',
      ja: 'しばらく気分が悪いが、時間が経てば良くなる',
      'zh-CN': '会心情不好一阵，但时间久了会好转',
      'zh-TW': '會心情不好一陣，但時間久了會好轉',
      vi: 'Một thời gian tâm trạng tệ, nhưng dần khá hơn',
      id: 'Perasaanku buruk sebentar, tapi lama-kelamaan membaik',
    }),
        score: 1,
      },
      {
        text: L({
      ko: '실수를 인정하고 같은 실수를 반복하지 않으려 한다',
      en: 'I admit the mistake and try not to repeat it',
      ja: 'ミスを認め、同じミスを繰り返さないよう努める',
      'zh-CN': '承认错误，努力不再犯同样的错',
      'zh-TW': '承認錯誤，努力不再犯同樣的錯',
      vi: 'Thừa nhận sai lầm và cố không lặp lại',
      id: 'Aku akui kesalahan dan berusaha tidak mengulanginya',
    }),
        score: 2,
      },
      {
        text: L({
      ko: '실수를 했다는 사실과 내가 형편없는 사람이라는 것은 다른 이야기라는 걸 안다',
      en: 'I know making a mistake and being a worthless person are different things',
      ja: 'ミスをした事実と、自分がダメな人間だということは別の話だとわかる',
      'zh-CN': '知道犯错和是糟糕的人，是两回事',
      'zh-TW': '知道犯錯和是糟糕的人，是兩回事',
      vi: 'Biết mắc lỗi và là người vô dụng là hai chuyện khác nhau',
      id: 'Aku tahu salah dan menjadi orang yang tidak berguna adalah hal berbeda',
    }),
        score: 3,
      },
    ],
  },
  {
    id: 9,
    question: L({
      ko: '칭찬을 받았을 때 나는?',
      en: 'When I receive praise, I...',
      ja: '褒められたとき、私は？',
      'zh-CN': '当受到表扬时，我会？',
      'zh-TW': '當受到表揚時，我會？',
      vi: 'Khi được khen, tôi...',
      id: 'Ketika aku dipuji, aku...',
    }),
    options: [
      {
        text: L({
      ko: '믿기 어렵다. "진심일까?" "빈말이겠지"라는 생각이 먼저 든다',
      en: 'It\'s hard to believe. I first think "Are they sincere?" or "Just empty words"',
      ja: '信じにくい。「本気？」「社交辞令？」と最初に思う',
      'zh-CN': '很难相信，先想「是真心吗？」「只是客套吧？」',
      'zh-TW': '很難相信，先想「是真心嗎？」「只是客套吧？」',
      vi: 'Khó tin. Trước hết nghĩ "Thật lòng không?" hay "Xã giao thôi"',
      id: 'Sulit percaya. Pertama-tama berpikir "Sungguhan?" atau "Bas-basi saja"',
    }),
        score: 0,
      },
      {
        text: L({
      ko: '기분은 좋지만 어딘가 쑥스럽고 "이 정도로 칭찬받아도 되나" 싶다',
      en: 'It feels good but awkward—"Do I really deserve this much praise?"',
      ja: '気分は良いがどこか照れくさく「この程度で褒められていいの？」と思う',
      'zh-CN': '心情不错但有点不好意思，「这样被夸合适吗？」',
      'zh-TW': '心情不錯但有點不好意思，「這樣被誇合適嗎？」',
      vi: 'Vui nhưng hơi ngại: "Mình có xứng được khen thế này không?"',
      id: 'Senang tapi agak malu: "Apakah aku pantas dipuji sebanyak ini?"',
    }),
        score: 1,
      },
      {
        text: L({
      ko: '감사하게 받아들인다. 노력한 것이 인정받는 것이 뿌듯하다',
      en: 'I accept it gratefully. It feels good when effort is recognized',
      ja: '感謝して受け取る。努力が認められるのが誇らしい',
      'zh-CN': '心怀感激地接受，努力被认可是件骄傲的事',
      'zh-TW': '心懷感激地接受，努力被認可是件驕傲的事',
      vi: 'Biết ơn mà nhận. Thấy tự hào khi nỗ lực được công nhận',
      id: 'Aku menerimanya dengan syukur. Bangga saat usaha diakui',
    }),
        score: 2,
      },
      {
        text: L({
      ko: '기쁘게 받아들인다. 칭찬이 나의 가치를 만들지 않지만 좋은 피드백으로 삼는다',
      en: 'I accept it happily. Praise doesn\'t create my worth, but I use it as good feedback',
      ja: '喜んで受け取る。褒め言葉が自分の価値を作らないが、良いフィードバックとして活かす',
      'zh-CN': '开心接受，赞美不决定我的价值，但会当作好反馈',
      'zh-TW': '開心接受，讚美不決定我的價值，但會當作好回饋',
      vi: 'Vui vẻ nhận. Lời khen không tạo giá trị, nhưng là phản hồi tốt',
      id: 'Aku terima dengan senang. Pujian tidak menciptakan nilai diriku, tapi jadi umpan balik bagus',
    }),
        score: 3,
      },
    ],
  },
  {
    id: 10,
    question: L({
      ko: '"너는 왜 항상 그 모양이야?" 라는 말을 들었을 때 나는?',
      en: 'When I hear "Why are you always like that?", I...',
      ja: '「なんでいつもそんななの？」と言われたとき、私は？',
      'zh-CN': '听到「你怎么总是那样？」时，我会？',
      'zh-TW': '聽到「你怎麼總是那樣？」時，我會？',
      vi: 'Khi nghe "Sao bạn lúc nào cũng thế?", tôi...',
      id: 'Ketika mendengar "Kenapa kamu selalu begitu?", aku...',
    }),
    options: [
      {
        text: L({
      ko: '그 말이 맞다는 생각이 든다. 스스로도 나를 그렇게 보게 된다',
      en: 'I think they\'re right and start seeing myself that way too',
      ja: 'その言葉が正しいと思い、自分もそう見るようになる',
      'zh-CN': '觉得说得对，也开始那样看自己',
      'zh-TW': '覺得說得對，也開始那樣看自己',
      vi: 'Nghĩ họ nói đúng và bắt đầu nhìn mình như vậy',
      id: 'Aku pikir mereka benar dan mulai melihat diriku begitu juga',
    }),
        score: 0,
      },
      {
        text: L({
      ko: '크게 상처받고 오랫동안 그 말이 머릿속에 남는다',
      en: 'I\'m deeply hurt and the words stay in my head for a long time',
      ja: '大きく傷つき、その言葉が長く頭に残る',
      'zh-CN': '深受伤害，那句话会在心里留很久',
      'zh-TW': '深受傷害，那句話會在心裡留很久',
      vi: 'Tổn thương sâu và câu đó ở lại đầu rất lâu',
      id: 'Sangat terluka dan kata itu lama tertinggal di kepala',
    }),
        score: 1,
      },
      {
        text: L({
      ko: '화가 나지만 그 말이 나의 전부를 표현한 것은 아니라고 생각한다',
      en: 'I\'m angry, but I think those words don\'t represent all of me',
      ja: '怒るが、その言葉が私のすべてを表していないと思う',
      'zh-CN': '会生气，但觉得那句话不能代表全部的我',
      'zh-TW': '會生氣，但覺得那句話不能代表全部的我',
      vi: 'Tức nhưng nghĩ câu đó không nói hết con người tôi',
      id: 'Marah, tapi aku pikir kata itu tidak mewakili seluruh diriku',
    }),
        score: 2,
      },
      {
        text: L({
      ko: '상대방의 말이 나의 정체성을 정의하지 않는다는 것을 안다. 그 말을 그 사람에게 돌려보낸다',
      en: 'I know their words don\'t define my identity. I send those words back to them',
      ja: '相手の言葉が自分のアイデンティティを定義しないとわかる。その言葉を相手に返す',
      'zh-CN': '知道对方的话不能定义我是谁，把那句话还回去',
      'zh-TW': '知道對方的話不能定義我是誰，把那句話還回去',
      vi: 'Biết lời họ không định nghĩa bản sắc tôi. Trả lại câu đó cho họ',
      id: 'Aku tahu kata mereka tidak mendefinisikan identitasku. Aku kembalikan kata itu',
    }),
        score: 3,
      },
    ],
  },
  {
    id: 11,
    question: L({
      ko: '나에 대해 스스로 가장 솔직하게 평가한다면?',
      en: 'If I evaluate myself most honestly, I...',
      ja: '自分について最も正直に評価すると？',
      'zh-CN': '如果最诚实地评价自己，我会？',
      'zh-TW': '如果最誠實地評價自己，我會？',
      vi: 'Nếu tự đánh giá bản thân thật nhất, tôi...',
      id: 'Jika menilai diriku dengan paling jujur, aku...',
    }),
    options: [
      {
        text: L({
      ko: '나는 많이 부족한 사람이다. 자랑스러운 점이 잘 생각나지 않는다',
      en: 'I\'m very lacking. I can\'t think of much to be proud of',
      ja: '自分はかなり足りない人だ。誇れる点が思い浮かばない',
      'zh-CN': '我有很多不足，想不起什么值得骄傲的事',
      'zh-TW': '我有很多不足，想不起什麼值得驕傲的事',
      vi: 'Tôi thiếu sót nhiều. Khó nghĩ ra điều gì đáng tự hào',
      id: 'Aku banyak kekurangan. Sulit memikirkan hal yang membanggakan',
    }),
        score: 0,
      },
      {
        text: L({
      ko: '장단점이 있는데 단점이 더 먼저 보인다',
      en: 'I have pros and cons, but cons stand out first',
      ja: '長所も短所もあるが、短所の方が先に目に入る',
      'zh-CN': '有优缺点，但缺点先被看到',
      'zh-TW': '有優缺點，但缺點先被看到',
      vi: 'Có ưu nhược, nhưng nhược điểm nổi bật trước',
      id: 'Ada kelebihan dan kekurangan, tapi kekurangan lebih dulu terlihat',
    }),
        score: 1,
      },
      {
        text: L({
      ko: '부족한 점도 있지만 잘하는 것도 있다. 성장하고 있다고 생각한다',
      en: 'I have weaknesses, but strengths too. I think I\'m growing',
      ja: '足りない点もあるが、得意なこともある。成長していると思う',
      'zh-CN': '有不足，也有擅长的事，觉得自己在成长',
      'zh-TW': '有不足，也有擅長的事，覺得自己在成長',
      vi: 'Có thiếu sót nhưng cũng có điểm giỏi. Tôi nghĩ mình đang lớn lên',
      id: 'Ada kekurangan, tapi ada hal yang kubisa. Aku pikir aku sedang tumbuh',
    }),
        score: 2,
      },
      {
        text: L({
      ko: '완벽하지 않지만 나는 충분히 가치 있는 사람이다. 그것을 진심으로 믿는다',
      en: 'I\'m not perfect, but I\'m valuable enough. I truly believe that',
      ja: '完璧ではないが、十分に価値のある人だ。それを心から信じている',
      'zh-CN': '不完美，但我是足够有价值的人，我真心相信',
      'zh-TW': '不完美，但我是足夠有價值的人，我真心相信',
      vi: 'Không hoàn hảo, nhưng tôi đủ giá trị. Tôi thật sự tin điều đó',
      id: 'Tidak sempurna, tapi aku cukup berharga. Aku benar-benar percaya itu',
    }),
        score: 3,
      },
    ],
  },
  {
    id: 12,
    question: L({
      ko: '이 테스트를 하면서 드는 솔직한 생각은?',
      en: 'My honest thought while taking this test is...',
      ja: 'このテストをしながら素直に思うことは？',
      'zh-CN': '做这份测试时，我真实的想法是？',
      'zh-TW': '做這份測試時，我真實的想法是？',
      vi: 'Suy nghĩ thật lòng khi làm bài test này là...',
      id: 'Pikiran jujurku saat mengerjakan tes ini adalah...',
    }),
    options: [
      {
        text: L({
      ko: '나의 방패가 정말 얇다는 걸 느꼈다. 남의 말에 너무 많이 흔들려왔다',
      en: 'I feel my shield is really thin. I\'ve been shaken too much by others\' words',
      ja: '自分のシールドが本当に薄いと感じた。他人の言葉に揺れすぎてきた',
      'zh-CN': '感觉我的盾牌真的很薄，太容易被别人的话动摇',
      'zh-TW': '感覺我的盾牌真的很薄，太容易被別人的話動搖',
      vi: 'Cảm thấy lá chắn mình thật sự mỏng. Bị lời người khác lay quá nhiều',
      id: 'Perisaiku memang tipis. Terlalu sering goyah oleh kata orang',
    }),
        score: 0,
      },
      {
        text: L({
      ko: '생각보다 흔들릴 때가 많았구나 싶다. 조금 더 단단해지고 싶다',
      en: 'I shake more than I thought. I want to become a bit stronger',
      ja: '思ったより揺れることが多かった。もう少し強くなりたい',
      'zh-CN': '原来比想象中更容易动摇，想变得更坚固一点',
      'zh-TW': '原來比想像中更容易動搖，想變得更堅固一點',
      vi: 'Lay chuyển nhiều hơn tưởng. Muốn cứng cáp hơn một chút',
      id: 'Ternyata lebih sering goyah dari kira. Ingin sedikit lebih kuat',
    }),
        score: 1,
      },
      {
        text: L({
      ko: '어느 정도 방패가 있다는 것을 확인했다. 더 강화할 수 있을 것 같다',
      en: 'I confirmed I have some shield. I think I can strengthen it more',
      ja: 'ある程度シールドがあると確認した。さらに強化できそう',
      'zh-CN': '确认自己有一定盾牌，应该还能再加强',
      'zh-TW': '確認自己有一定盾牌，應該還能再加強',
      vi: 'Xác nhận mình có lá chắn nhất định. Có thể củng cố thêm',
      id: 'Aku konfirmasi punya perisai cukup. Sepertinya bisa diperkuat lagi',
    }),
        score: 2,
      },
      {
        text: L({
      ko: '꽤 단단한 방패가 있다고 느꼈다. 앞으로도 나를 믿을 것이다',
      en: 'I feel I have a fairly solid shield. I\'ll keep believing in myself',
      ja: 'かなりしっかりしたシールドがあると感じた。これからも自分を信じる',
      'zh-CN': '感觉盾牌相当坚固，以后也会继续相信自己',
      'zh-TW': '感覺盾牌相當堅固，以後也會繼續相信自己',
      vi: 'Cảm thấy lá chắn khá vững. Tôi sẽ tiếp tục tin vào bản thân',
      id: 'Perisaiku cukup kokoh. Aku akan terus percaya pada diriku',
    }),
        score: 3,
      },
    ],
  },
];

export const phase3SelfEsteemShieldStrengthResults: Phase3SelfEsteemShieldStrengthResult[] = [
  {
    type: 'Type1',
    emoji: '🔴',
    title: L({
      ko: '방패가 없는 상태, 지금 당장 보호가 필요합니다 🔴',
      en: 'No shield—you need protection right now 🔴',
      ja: 'シールドなし、今すぐ保護が必要 🔴',
      'zh-CN': '没有盾牌，现在就需要保护 🔴',
      'zh-TW': '沒有盾牌，現在就需要保護 🔴',
      vi: 'Không có lá chắn—cần được bảo vệ ngay 🔴',
      id: 'Tanpa perisai—butuh perlindungan sekarang 🔴',
    }),
    shortDescription: L({
      ko: '지금 당신의 마음은 비가 오는데 우산이 없는 상태입니다.',
      en: 'Right now your heart is in the rain without an umbrella.',
      ja: '今あなたの心は雨が降っているのに傘がない状態です。',
      'zh-CN': '现在你的心像在下雨，却没有伞。',
      'zh-TW': '現在你的心像在下雨，卻沒有傘。',
      vi: 'Lúc này trái tim bạn như đang mưa mà không có ô.',
      id: 'Saat ini hatimu seperti hujan tanpa payung.',
    }),
    description: L({
      ko: '남의 말 한마디가 하루를 결정하고 비판을 들으면 그것이 나의 전부처럼 느껴지며 칭찬도 믿기 어려운 상태입니다. 이것은 약해서가 아닙니다. 오랜 시간 방패를 빼앗기는 경험이 쌓인 결과일 수 있습니다.',
      en: 'One comment can decide your whole day. Criticism feels like all of you, and praise is hard to believe. This isn\'t weakness—it may be the result of long experiences that took your shield away.',
      ja: '他人の一言が一日を決め、批判を受けるとそれが自分のすべてのように感じ、褒め言葉も信じにくい状態です。弱いからではありません。長い間シールドを奪われる経験が積み重なった結果かもしれません。',
      'zh-CN': '别人的一句话能决定你一整天，被批评时觉得那就是全部的你，也很难相信赞美。这不是因为你弱，可能是长期被夺走盾牌的经历累积的结果。',
      'zh-TW': '別人的一句話能決定你一整天，被批評時覺得那就是全部的你，也很難相信讚美。這不是因為你弱，可能是長期被奪走盾牌的經歷累積的結果。',
      vi: 'Một câu nói có thể quyết định cả ngày. Chỉ trích cảm giác như là toàn bộ bạn, và lời khen khó tin. Không phải vì yếu—có thể là kết quả của trải nghiệm lâu dài lấy mất lá chắn.',
      id: 'Satu komentar bisa menentukan seharianmu. Kritik terasa seperti seluruh dirimu, dan pujian sulit dipercaya. Bukan karena lemah—mungkin akumulasi pengalaman yang merampas perisaimu.',
    }),
    shieldStrength: L({
      ko: 'Lv.1 보호 필요',
      en: 'Lv.1 Protection needed',
      ja: 'Lv.1 保護必要',
      'zh-CN': 'Lv.1 需要保护',
      'zh-TW': 'Lv.1 需要保護',
      vi: 'Lv.1 Cần bảo vệ',
      id: 'Lv.1 Butuh perlindungan',
    }),
    pattern: L({
      ko: '비판→자기 전체로 확장·칭찬 불신·비교에 취약·자기 비난',
      en: 'Criticism→whole-self expansion·distrust of praise·vulnerable to comparison·self-blame',
      ja: '批判→自分全体へ拡大・褒め言葉不信・比較に弱い・自責',
      'zh-CN': '批评→扩展到整个自我·不信赞美·易受比较·自我责备',
      'zh-TW': '批評→擴展到整個自我·不信讚美·易受比較·自我責備',
      vi: 'Chỉ trích→mở rộng thành cả bản thân·không tin lời khen·dễ so sánh·tự trách',
      id: 'Kritik→meluas ke seluruh diri·tidak percaya pujian·rentan dibandingkan·menyalahkan diri',
    }),
    strength: null,
    needNow: L({
      ko: '방패를 세우기 전에 지금의 나를 인정하는 것',
      en: 'Before building a shield, acknowledging who you are right now',
      ja: 'シールドを立てる前に、今の自分を認めること',
      'zh-CN': '在建立盾牌之前，先承认现在的自己',
      'zh-TW': '在建立盾牌之前，先承認現在的自己',
      vi: 'Trước khi dựng lá chắn, hãy công nhận bản thân hiện tại',
      id: 'Sebelum membangun perisai, akui dirimu yang sekarang',
    }),
    actions: L({
      ko: '오늘 내가 잘한 것 한 가지를 저녁에 적어보기. 작아도 됩니다\n나에게 친절한 사람 한 명과 시간 보내기\n"나는 충분하다"를 하루 한 번 소리 내어 말해보기. 믿기지 않아도 괜찮습니다',
      en: 'Write down one thing you did well today tonight—even something small\nSpend time with one person who is kind to you\nSay "I am enough" out loud once a day. It\'s okay if you don\'t believe it yet',
      ja: '今夜、今日うまくできたことを一つ書く。小さくてもOK\n自分に優しい人と時間を過ごす\n「私は十分だ」を一日一回声に出す。信じられなくても大丈夫',
      'zh-CN': '今晚写下今天做得好的事一件，再小也可以\n和一位对你温柔的人相处\n每天大声说一次「我已经足够」，暂时不信也没关系',
      'zh-TW': '今晚寫下今天做得好的事一件，再小也可以\n和一位對你溫柔的人相處\n每天大聲說一次「我已經足夠」，暫時不信也沒關係',
      vi: 'Tối nay ghi một việc bạn làm tốt hôm nay—nhỏ cũng được\nDành thời gian với một người tử tế với bạn\nNói to "Tôi đủ rồi" mỗi ngày một lần. Chưa tin cũng được',
      id: 'Malam ini tulis satu hal yang kamu lakukan dengan baik hari ini—kecil pun boleh\nLuangkan waktu dengan satu orang yang baik padamu\nUcapkan "Aku cukup" keras sekali sehari. Tidak percaya dulu juga boleh',
    }),
    remainingTask: null,
    canDo: null,
    caution: null,
    toOthers: null,
    affirmation: null,
    shareSnippet: L({
      ko: '자존감 방패 강도: 보호 필요 🔴 방패가 많이 얇다는 거 알았음... 오늘부터 나를 좀 더 아껴주기로 함 → 너는 어떤 방패 강도야?',
      en: 'Self-esteem shield: Protection needed 🔴 Realized my shield is very thin... Starting to take better care of myself → What\'s your shield strength?',
      ja: '自尊心シールド強度: 保護必要 🔴 シールドがかなり薄いとわかった... 今日からもっと自分を大切にする → あなたはどんなシールド？',
      'zh-CN': '自尊盾牌强度：需要保护 🔴 发现盾牌很薄... 从今天起更善待自己 → 你是什么盾牌？',
      'zh-TW': '自尊盾牌強度：需要保護 🔴 發現盾牌很薄... 從今天起更善待自己 → 你是什麼盾牌？',
      vi: 'Lá chắn tự trọng: Cần bảo vệ 🔴 Nhận ra lá chắn mỏng lắm... Từ hôm nay chăm mình hơn → Bạn có lá chắn gì?',
      id: 'Perisai harga diri: Butuh perlindungan 🔴 Ternyata perisaiku tipis... Mulai hari ini lebih sayang diri → Perisimu yang mana?',
    }),
  },
  {
    type: 'Type2',
    emoji: '🟠',
    title: L({
      ko: '방패가 얇은 상태, 조금씩 세워가는 중 🟠',
      en: 'Thin shield—building it bit by bit 🟠',
      ja: '薄いシールド、少しずつ立てている 🟠',
      'zh-CN': '盾牌很薄，正在一点点建立 🟠',
      'zh-TW': '盾牌很薄，正在一點點建立 🟠',
      vi: 'Lá chắn mỏng—đang dựng dần 🟠',
      id: 'Perisai tipis—sedang dibangun perlahan 🟠',
    }),
    shortDescription: L({
      ko: '방패가 있긴 한데 자꾸 구멍이 생깁니다. 세우려다 또 흔들리는 상태입니다.',
      en: 'You have a shield, but holes keep appearing. You try to hold it up, then waver again.',
      ja: 'シールドはあるが穴が空きやすい。立てようとしてまた揺れる状態です。',
      'zh-CN': '有盾牌，但总有漏洞，刚立起来又动摇。',
      'zh-TW': '有盾牌，但總有漏洞，剛立起來又動搖。',
      vi: 'Có lá chắn nhưng hay thủng. Vừa dựng lên lại lay.',
      id: 'Ada perisai, tapi sering bolong. Baru tegak sudah goyah lagi.',
    }),
    description: L({
      ko: '비판에 상처받고 비교에 흔들리지만 시간이 지나면 조금씩 회복됩니다. 완전히 무너지지는 않는다는 것이 지금의 강점입니다. 방패는 이미 있습니다. 두껍게 만들어가는 중입니다.',
      en: 'Criticism hurts and comparison shakes you, but you recover over time. Not collapsing completely is your strength now. You already have a shield—you\'re making it thicker.',
      ja: '批判に傷つき比較に揺れるが、時間が経てば少しずつ回復します。完全に崩れないことが今の強みです。シールドはすでにあります。厚くしている最中です。',
      'zh-CN': '会被批评伤害、被比较动摇，但时间久了会慢慢恢复。没有完全崩溃是现在的优势。盾牌已经有了，正在加厚。',
      'zh-TW': '會被批評傷害、被比較動搖，但時間久了會慢慢恢復。沒有完全崩潰是現在的優勢。盾牌已經有了，正在加厚。',
      vi: 'Bị chỉ trích tổn thương, bị so sánh lay chuyển, nhưng theo thời gian hồi phục dần. Không sụp hoàn toàn là điểm mạnh hiện tại. Lá chắn đã có—đang làm dày hơn.',
      id: 'Kritik menyakitkan dan perbandingan menggoyahkanmu, tapi lama-kelamaan pulih. Tidak runtuh total adalah kekuatanmu sekarang. Perisai sudah ada—sedang menebalkannya.',
    }),
    shieldStrength: L({
      ko: 'Lv.2 얇은 방패 보유',
      en: 'Lv.2 Thin shield held',
      ja: 'Lv.2 薄いシールド保有',
      'zh-CN': 'Lv.2 持有薄盾牌',
      'zh-TW': 'Lv.2 持有薄盾牌',
      vi: 'Lv.2 Có lá chắn mỏng',
      id: 'Lv.2 Memegang perisai tipis',
    }),
    pattern: L({
      ko: '흔들렸다가 회복·비판에 예민·칭찬 수용 어려움',
      en: 'Waver then recover·sensitive to criticism·hard to accept praise',
      ja: '揺れて回復・批判に敏感・褒め言葉を受け取りにくい',
      'zh-CN': '动摇后恢复·对批评敏感·难接受赞美',
      'zh-TW': '動搖後恢復·對批評敏感·難接受讚美',
      vi: 'Lay rồi hồi·nhạy với chỉ trích·khó nhận lời khen',
      id: 'Goyah lalu pulih·peka terhadap kritik·sulit menerima pujian',
    }),
    strength: L({
      ko: '회복력이 있음. 완전히 무너지지 않음',
      en: 'You have resilience. You don\'t fully collapse',
      ja: '回復力がある。完全には崩れない',
      'zh-CN': '有恢复力，不会完全崩溃',
      'zh-TW': '有恢復力，不會完全崩潰',
      vi: 'Có khả năng hồi phục. Không sụp hoàn toàn',
      id: 'Punya daya pulih. Tidak runtuh total',
    }),
    needNow: null,
    actions: L({
      ko: '비판을 들었을 때 "그것이 나의 전부는 아니다"를 머릿속에서 한 번 말하기\n나에 대한 긍정적인 증거 모으기. 잘했던 순간들을 메모해두기\n나를 있는 그대로 봐주는 사람과의 시간을 늘리기',
      en: 'When criticized, say once in your mind: "That isn\'t all of me"\nCollect positive evidence about yourself—note moments you did well\nSpend more time with people who accept you as you are',
      ja: '批判を聞いたら心の中で「それが私のすべてではない」と一度言う\n自分への肯定的な証拠を集める。うまくいった瞬間をメモ\nありのままの自分を見てくれる人との時間を増やす',
      'zh-CN': '听到批评时，在心里说一次「那不能定义全部的我」\n收集关于自己的正面证据，记下做得好的时刻\n多和接纳真实的你的人相处',
      'zh-TW': '聽到批評時，在心裡說一次「那不能定義全部的我」\n收集關於自己的正面證據，記下做得好的時刻\n多和接納真實的你的人相處',
      vi: 'Khi bị chỉ trích, nói trong đầu một lần: "Đó không phải toàn bộ tôi"\nThu thập bằng chứng tích cực về bản thân—ghi lại khoảnh khắc làm tốt\nDành nhiều thời gian hơn với người chấp nhận bạn như bạn là',
      id: 'Saat dikritik, katakan sekali dalam hati: "Itu bukan seluruh diriku"\nKumpulkan bukti positif tentang dirimu—catat momen-momen sukses\nLuangkan lebih banyak waktu dengan orang yang menerima dirimu apa adanya',
    }),
    remainingTask: null,
    canDo: null,
    caution: null,
    toOthers: null,
    affirmation: null,
    shareSnippet: L({
      ko: '자존감 방패 강도: 얇은 방패 🟠 흔들리지만 회복은 하는 유형... 더 단단해지고 싶다는 거 확인함 → 너는 어떤 방패 강도야?',
      en: 'Self-esteem shield: Thin shield 🟠 I waver but recover... Confirmed I want to get stronger → What\'s your shield strength?',
      ja: '自尊心シールド: 薄いシールド 🟠 揺れるが回復するタイプ... もっと強くなりたいと確認 → あなたは？',
      'zh-CN': '自尊盾牌：薄盾牌 🟠 会动摇但能恢复... 确认想更坚固 → 你是什么盾牌？',
      'zh-TW': '自尊盾牌：薄盾牌 🟠 會動搖但能恢復... 確認想更堅固 → 你是什麼盾牌？',
      vi: 'Lá chắn tự trọng: Mỏng 🟠 Lay nhưng hồi được... Muốn cứng hơn → Bạn có lá chắn gì?',
      id: 'Perisai harga diri: Tipis 🟠 Goyah tapi pulih... Ingin lebih kuat → Perisimu yang mana?',
    }),
  },
  {
    type: 'Type3',
    emoji: '🟡',
    title: L({
      ko: '방패가 있지만 가끔 흔들리는, 방패 강화 중 🟡',
      en: 'Shield present but sometimes wavers—strengthening 🟡',
      ja: 'シールドはあるが時々揺れる、強化中 🟡',
      'zh-CN': '有盾牌但偶尔动摇，正在强化 🟡',
      'zh-TW': '有盾牌但偶爾動搖，正在強化 🟡',
      vi: 'Có lá chắn nhưng đôi khi lay—đang củng cố 🟡',
      id: 'Ada perisai tapi kadang goyah—sedang diperkuat 🟡',
    }),
    shortDescription: L({
      ko: '방패가 있습니다. 하지만 강한 바람이 불면 조금씩 흔들립니다.',
      en: 'You have a shield. But strong winds make it sway a little.',
      ja: 'シールドはあります。ただ強い風が吹くと少し揺れます。',
      'zh-CN': '你有盾牌，但强风来时仍会微微动摇。',
      'zh-TW': '你有盾牌，但強風來時仍會微微動搖。',
      vi: 'Bạn có lá chắn. Nhưng gió mạnh vẫn làm nó lay nhẹ.',
      id: 'Kamu punya perisai. Tapi angin kencang masih menggoyahkannya sedikit.',
    }),
    description: L({
      ko: '대부분의 상황에서 자신을 유지하지만 특정 상황이나 특정 사람 앞에서는 방패가 얇아지는 패턴이 있습니다. 평소엔 괜찮은데 가끔 예상치 못하게 무너지는 경험을 합니다.',
      en: 'You mostly hold yourself steady, but your shield thins in certain situations or around certain people. Usually fine, but sometimes you collapse unexpectedly.',
      ja: 'ほとんどの状況で自分を保てますが、特定の状況や特定の人の前ではシールドが薄くなるパターンがあります。普段は大丈夫でも、時々予想外に崩れる経験をします。',
      'zh-CN': '大多数情况能稳住，但在特定情境或特定人面前盾牌会变薄。平时还好，偶尔会意外崩溃。',
      'zh-TW': '大多數情況能穩住，但在特定情境或特定人面前盾牌會變薄。平時還好，偶爾會意外崩潰。',
      vi: 'Phần lớn bạn giữ vững, nhưng lá chắn mỏng đi trong một số tình huống hoặc trước một số người. Bình thường ổn, đôi khi sụp bất ngờ.',
      id: 'Sebagian besar kamu stabil, tapi perisai menipis di situasi atau di depan orang tertentu. Biasanya baik-baik saja, kadang runtuh tanpa diduga.',
    }),
    shieldStrength: L({
      ko: 'Lv.3 방패 강화 중',
      en: 'Lv.3 Shield strengthening',
      ja: 'Lv.3 シールド強化中',
      'zh-CN': 'Lv.3 盾牌强化中',
      'zh-TW': 'Lv.3 盾牌強化中',
      vi: 'Lv.3 Đang củng cố lá chắn',
      id: 'Lv.3 Perisai diperkuat',
    }),
    pattern: L({
      ko: '대체로 안정·특정 상황에서 취약·비판 선별 능력 있음',
      en: 'Mostly stable·vulnerable in specific situations·can filter criticism',
      ja: 'おおむね安定・特定状況で脆弱・批判を選別できる',
      'zh-CN': '大体稳定·特定情境脆弱·能筛选批评',
      'zh-TW': '大體穩定·特定情境脆弱·能篩選批評',
      vi: 'Phần lớn ổn định·dễ tổn thương trong tình huống cụ thể·lọc được chỉ trích',
      id: 'Sebagian besar stabil·rentan di situasi tertentu·bisa menyaring kritik',
    }),
    strength: L({
      ko: '현실 인식과 자기 보호가 공존하고 있음',
      en: 'Realistic awareness and self-protection coexist',
      ja: '現実認識と自己保護が共存している',
      'zh-CN': '现实认知与自我保护并存',
      'zh-TW': '現實認知與自我保護並存',
      vi: 'Nhận thức thực tế và tự bảo vệ cùng tồn tại',
      id: 'Kesadaran realistis dan perlindungan diri hidup berdampingan',
    }),
    needNow: null,
    actions: L({
      ko: '어떤 상황에서 방패가 얇아지는지 파악하기. 패턴을 아는 것이 강화의 시작\n비판과 사실을 구분하는 연습. "이것이 사실인가, 상대방의 판단인가?"\n나를 응원하는 나만의 문장 하나 만들기. 흔들릴 때 꺼내 쓰기',
      en: 'Identify when your shield gets thin—knowing the pattern is the start of strengthening\nPractice separating criticism from fact: "Is this true, or their judgment?"\nCreate one personal cheer phrase to use when you waver',
      ja: 'どんな状況でシールドが薄くなるか把握する。パターンを知ることが強化の始まり\n批判と事実を分ける練習。「これは事実か、相手の判断か？」\n自分を励ます一言を作る。揺れるときに使う',
      'zh-CN': '找出盾牌变薄的情境，认识模式是强化的开始\n练习区分批评与事实：「这是事实，还是对方的判断？」\n写一句只属于自己的鼓励语，动摇时拿出来用',
      'zh-TW': '找出盾牌變薄的情境，認識模式是強化的開始\n練習區分批評與事實：「這是事實，還是對方的判斷？」\n寫一句只屬於自己的鼓勵語，動搖時拿出來用',
      vi: 'Xác định khi nào lá chắn mỏng—biết mô hình là bước đầu củng cố\nLuyện phân biệt chỉ trích và sự thật: "Đây là sự thật hay phán xét của họ?"\nTạo một câu cổ vũ riêng—dùng khi lay chuyển',
      id: 'Kenali kapan perisai menipis—mengetahui polanya adalah awal penguatan\nLatih membedakan kritik dan fakta: "Ini fakta atau penilaian mereka?"\nBuat satu kalimat dukungan pribadi—pakai saat goyah',
    }),
    remainingTask: null,
    canDo: null,
    caution: null,
    toOthers: null,
    affirmation: null,
    shareSnippet: L({
      ko: '자존감 방패 강도: 방패 강화 중 🟡 가끔 예상치 못하게 흔들리는 유형... 어떤 상황에서 얇아지는지 파악 중 → 너는 어떤 방패 강도야?',
      en: 'Self-esteem shield: Strengthening 🟡 Sometimes shaken unexpectedly... Figuring out when it gets thin → What\'s your shield?',
      ja: '自尊心シールド: 強化中 🟡 時々予想外に揺れる... どこで薄くなるか把握中 → あなたは？',
      'zh-CN': '自尊盾牌：强化中 🟡 偶尔意外动摇... 正在找出何时变薄 → 你是什么盾牌？',
      'zh-TW': '自尊盾牌：強化中 🟡 偶爾意外動搖... 正在找出何時變薄 → 你是什麼盾牌？',
      vi: 'Lá chắn tự trọng: Đang củng cố 🟡 Đôi khi lay bất ngờ... Đang tìm khi nào mỏng → Bạn có lá chắn gì?',
      id: 'Perisai harga diri: Diperkuat 🟡 Kadang goyah tanpa diduga... Mencari kapan menipis → Perisimu?',
    }),
  },
  {
    type: 'Type4',
    emoji: '🟢',
    title: L({
      ko: '대체로 단단한 방패, 방패 작동형 🟢',
      en: 'Mostly solid shield—shield active 🟢',
      ja: 'おおむねしっかりしたシールド、作動型 🟢',
      'zh-CN': '大体坚固的盾牌，运作型 🟢',
      'zh-TW': '大體堅固的盾牌，運作型 🟢',
      vi: 'Lá chắn khá vững—đang hoạt động 🟢',
      id: 'Perisai cukup kokoh—aktif 🟢',
    }),
    shortDescription: L({
      ko: '방패가 작동하고 있습니다. 비판이 와도 튕겨낼 수 있는 힘이 있습니다.',
      en: 'Your shield is working. You have the strength to deflect criticism.',
      ja: 'シールドが機能しています。批判が来ても跳ね返す力があります。',
      'zh-CN': '盾牌正在运作，有力量把批评挡回去。',
      'zh-TW': '盾牌正在運作，有力量把批評擋回去。',
      vi: 'Lá chắn đang hoạt động. Bạn có sức để đỡ lời chỉ trích.',
      id: 'Perisaimu bekerja. Kamu punya kekuatan menangkis kritik.',
    }),
    description: L({
      ko: '외부의 비난과 비교에서 대체로 나 자신을 지킬 수 있습니다. 칭찬도 어느 정도 받아들이고 실패가 나의 전부가 아니라는 것도 압니다. 방패가 있습니다. 지금보다 더 빛나게 만들 수 있습니다.',
      en: 'You can mostly protect yourself from external blame and comparison. You accept praise to some degree and know failure isn\'t all of you. You have a shield—and can make it shine even more.',
      ja: '外部の非難や比較からおおむね自分を守れます。褒め言葉もある程度受け入れ、失敗が自分のすべてではないこともわかっています。シールドがあります。今よりもっと輝かせられます。',
      'zh-CN': '大体上能抵御外部指责和比较，也能一定程度接受赞美，知道失败不能定义全部的你。盾牌已经有了，还能让它更亮。',
      'zh-TW': '大體上能抵禦外部指責和比較，也能一定程度接受讚美，知道失敗不能定義全部的你。盾牌已經有了，還能讓它更亮。',
      vi: 'Phần lớn bạn bảo vệ được bản thân khỏi lời đổ lỗi và so sánh. Chấp nhận lời khen ở mức nào đó và biết thất bại không phải toàn bộ bạn. Lá chắn đã có—có thể làm sáng hơn.',
      id: 'Sebagian besar kamu melindungi diri dari blame dan perbandingan. Menerima pujian sejauh ini dan tahu kegagalan bukan seluruh dirimu. Perisai sudah ada—bisa lebih bersinar.',
    }),
    shieldStrength: L({
      ko: 'Lv.4 방패 작동',
      en: 'Lv.4 Shield active',
      ja: 'Lv.4 シールド作動',
      'zh-CN': 'Lv.4 盾牌运作',
      'zh-TW': 'Lv.4 盾牌運作',
      vi: 'Lv.4 Lá chắn hoạt động',
      id: 'Lv.4 Perisai aktif',
    }),
    pattern: null,
    strength: L({
      ko: '현실적 자기 평가·비판 선별 능력·회복력',
      en: 'Realistic self-assessment·criticism filtering·resilience',
      ja: '現実的な自己評価・批判選別・回復力',
      'zh-CN': '现实自我评价·筛选批评·恢复力',
      'zh-TW': '現實自我評價·篩選批評·恢復力',
      vi: 'Tự đánh giá thực tế·lọc chỉ trích·khả năng hồi phục',
      id: 'Penilaian diri realistis·penyaringan kritik·daya pulih',
    }),
    needNow: null,
    actions: L({
      ko: '방패가 가장 얇아지는 순간이 언제인지 점검하기\n나에게 좋은 말을 먼저 해주는 사람이 되기. 자기 내면의 언어를 점검하기\n한 달에 한 번 나 자신에게 잘한 것을 공식적으로 인정해주기',
      en: 'Check when your shield is thinnest\nBe someone who speaks kindly to yourself first—review your inner language\nOnce a month, officially acknowledge something you did well',
      ja: 'シールドが最も薄くなる瞬間を点検する\n自分に優しい言葉を先にかける人になる。内なる言語を点検\n月に一度、自分のできたことを正式に認める',
      'zh-CN': '检查盾牌最薄的时刻\n先做会对自说好话的人，审视内心语言\n每月正式认可自己一次做得好的事',
      'zh-TW': '檢查盾牌最薄的時刻\n先做會對自己說好話的人，審視內心語言\n每月正式認可自己一次做得好的事',
      vi: 'Kiểm tra khi nào lá chắn mỏng nhất\nTrở thành người nói lời tử tế với bản thân trước—rà soát ngôn ngữ nội tâm\nMỗi tháng một lần công nhận chính thức điều mình làm tốt',
      id: 'Periksa kapan perisai paling tipis\nJadilah orang yang berbicara baik padamu dulu—tinjau bahasa batin\nSekali sebulan, akui resmi hal yang kamu lakukan dengan baik',
    }),
    remainingTask: L({
      ko: '특정 취약 포인트 파악 및 강화',
      en: 'Identify and strengthen specific weak points',
      ja: '特定の弱点を把握し強化する',
      'zh-CN': '找出并强化特定弱点',
      'zh-TW': '找出並強化特定弱點',
      vi: 'Xác định và củng cố điểm yếu cụ thể',
      id: 'Identifikasi dan perkuat titik rentan tertentu',
    }),
    canDo: null,
    caution: null,
    toOthers: null,
    affirmation: null,
    shareSnippet: L({
      ko: '자존감 방패 강도: 방패 작동형 🟢 대체로 단단한 방패 있다는 거 확인함... 비판이 와도 튕겨낼 수 있는 수준 → 너는 어떤 방패 강도야?',
      en: 'Self-esteem shield: Active 🟢 Confirmed I have a mostly solid shield... Can deflect criticism → What\'s yours?',
      ja: '自尊心シールド: 作動型 🟢 おおむねしっかりしたシールドを確認... 批判も跳ね返せる → あなたは？',
      'zh-CN': '自尊盾牌：运作型 🟢 确认大体坚固... 能挡回批评 → 你是什么盾牌？',
      'zh-TW': '自尊盾牌：運作型 🟢 確認大體堅固... 能擋回批評 → 你是什麼盾牌？',
      vi: 'Lá chắn tự trọng: Hoạt động 🟢 Xác nhận khá vững... Đỡ được chỉ trích → Bạn có lá chắn gì?',
      id: 'Perisai harga diri: Aktif 🟢 Konfirmasi cukup kokoh... Bisa menangkis kritik → Perisimu?',
    }),
  },
  {
    type: 'Type5',
    emoji: '🔵',
    title: L({
      ko: '단단하고 빛나는 방패, 방패 고도화형 🔵',
      en: 'Solid, shining shield—advanced type 🔵',
      ja: 'しっかり輝くシールド、高度化型 🔵',
      'zh-CN': '坚固闪亮的盾牌，高阶型 🔵',
      'zh-TW': '堅固閃亮的盾牌，高階型 🔵',
      vi: 'Lá chắn vững và sáng—nâng cao 🔵',
      id: 'Perisai kokoh dan bersinar—tingkat lanjut 🔵',
    }),
    shortDescription: L({
      ko: '방패가 단단합니다. 강한 비난도 대부분 튕겨낼 수 있습니다.',
      en: 'Your shield is solid. You can deflect even strong blame.',
      ja: 'シールドはしっかりしています。強い非難もおおむね跳ね返せます。',
      'zh-CN': '盾牌很坚固，大多能挡回强烈指责。',
      'zh-TW': '盾牌很堅固，大多能擋回強烈指責。',
      vi: 'Lá chắn vững. Phần lớn lời chỉ trích mạnh cũng đỡ được.',
      id: 'Perisaimu kokoh. Sebagian besar blame keras bisa ditangkis.',
    }),
    description: L({
      ko: '외부의 평가가 나의 가치를 결정하지 않는다는 것을 압니다. 칭찬도 자연스럽게 받아들이고 실패와 나 자신을 분리하며 비판에서 배울 것만 취하는 능력이 있습니다.',
      en: 'You know external judgment doesn\'t define your worth. You accept praise naturally, separate failure from yourself, and take only what\'s useful from criticism.',
      ja: '外部の評価が自分の価値を決めないことを知っています。褒め言葉も自然に受け取り、失敗と自分を分離し、批判から学ぶべきことだけを取る能力があります。',
      'zh-CN': '你知道外部评价不能决定你的价值，能自然接受赞美，把失败与自我分开，从批评中只取可学之处。',
      'zh-TW': '你知道外部評價不能決定你的價值，能自然接受讚美，把失敗與自我分開，從批評中只取可學之處。',
      vi: 'Bạn biết đánh giá bên ngoài không quyết định giá trị. Nhận lời khen tự nhiên, tách thất bại khỏi bản thân, chỉ lấy điều hữu ích từ chỉ trích.',
      id: 'Kamu tahu penilaian luar tidak menentukan nilaimu. Menerima pujian alami, memisahkan kegagalan dari diri, hanya mengambil yang berguna dari kritik.',
    }),
    shieldStrength: L({
      ko: 'Lv.5 방패 고도화',
      en: 'Lv.5 Shield advanced',
      ja: 'Lv.5 シールド高度化',
      'zh-CN': 'Lv.5 盾牌高阶',
      'zh-TW': 'Lv.5 盾牌高階',
      vi: 'Lv.5 Lá chắn nâng cao',
      id: 'Lv.5 Perisai lanjutan',
    }),
    pattern: null,
    strength: L({
      ko: '자기 신뢰·현실적 자기 인식·비판 선별·칭찬 수용',
      en: 'Self-trust·realistic self-awareness·criticism filtering·praise acceptance',
      ja: '自己信頼・現実的な自己認識・批判選別・褒め言葉受容',
      'zh-CN': '自我信任·现实自我认知·筛选批评·接受赞美',
      'zh-TW': '自我信任·現實自我認知·篩選批評·接受讚美',
      vi: 'Tự tin·nhận thức bản thân thực tế·lọc chỉ trích·nhận lời khen',
      id: 'Kepercayaan diri·kesadaran diri realistis·penyaringan kritik·penerimaan pujian',
    }),
    needNow: null,
    actions: null,
    remainingTask: L({
      ko: '가장 가까운 관계에서도 방패가 유지되는지 점검하기',
      en: 'Check if your shield holds even in your closest relationships',
      ja: '最も近い関係でもシールドが維持されているか点検する',
      'zh-CN': '检查在最亲近的关系里盾牌是否仍然有效',
      'zh-TW': '檢查在最親近的關係裡盾牌是否仍然有效',
      vi: 'Kiểm tra lá chắn có giữ vững cả trong các mối quan hệ gần nhất',
      id: 'Periksa apakah perisai tetap kuat di relasi paling dekat',
    }),
    canDo: L({
      ko: '자존감 방패가 얇은 주변 사람에게 지지자가 되어줄 수 있는 위치',
      en: 'You\'re in a position to support people around you with thin shields',
      ja: '自尊心シールドが薄い周りの人の支えになれる位置にいる',
      'zh-CN': '你能成为周围自尊盾牌较薄之人的支持者',
      'zh-TW': '你能成為周圍自尊盾牌較薄之人的支持者',
      vi: 'Bạn ở vị trí có thể ủng hộ người xung quanh có lá chắn mỏng',
      id: 'Kamu bisa jadi pendukung bagi orang sekitar dengan perisai tipis',
    }),
    caution: null,
    toOthers: null,
    affirmation: null,
    shareSnippet: L({
      ko: '자존감 방패 강도: 방패 고도화형 🔵 외부 평가가 나의 가치를 결정 안 한다는 거 아는 유형... 방패 단단한 거 인정 → 너는 어떤 방패 강도야?',
      en: 'Self-esteem shield: Advanced 🔵 I know outside judgment doesn\'t define my worth... Solid shield confirmed → What\'s yours?',
      ja: '自尊心シールド: 高度化型 🔵 外部評価が価値を決めないとわかっている... シールドしっかり → あなたは？',
      'zh-CN': '自尊盾牌：高阶型 🔵 知道外部评价不能决定价值... 盾牌很坚固 → 你是什么盾牌？',
      'zh-TW': '自尊盾牌：高階型 🔵 知道外部評價不能決定價值... 盾牌很堅固 → 你是什麼盾牌？',
      vi: 'Lá chắn tự trọng: Nâng cao 🔵 Biết đánh giá ngoài không quyết định giá trị... Lá chắn vững → Bạn có lá chắn gì?',
      id: 'Perisai harga diri: Lanjutan 🔵 Tahu penilaian luar tidak menentukan nilai... Perisai kokoh → Perisimu?',
    }),
  },
  {
    type: 'Type6',
    emoji: '🏆',
    title: L({
      ko: '황금 방패, 자존감 금강불괴 🏆',
      en: 'Golden shield—unbreakable self-esteem 🏆',
      ja: '黄金シールド、自尊心金剛不壊 🏆',
      'zh-CN': '黄金盾牌，自尊金刚不坏 🏆',
      'zh-TW': '黃金盾牌，自尊金剛不壞 🏆',
      vi: 'Lá chắn vàng—tự trọng bất khả phá 🏆',
      id: 'Perisai emas—harga diri tak tergoyahkan 🏆',
    }),
    shortDescription: L({
      ko: '당신의 방패는 황금으로 만들어져 있습니다. 비난이 와도 빛을 잃지 않습니다.',
      en: 'Your shield is made of gold. Blame can\'t dim its light.',
      ja: 'あなたのシールドは黄金でできています。非難が来ても輝きを失いません。',
      'zh-CN': '你的盾牌由黄金打造，指责也无法让它失去光芒。',
      'zh-TW': '你的盾牌由黃金打造，指責也無法讓它失去光芒。',
      vi: 'Lá chắn của bạn bằng vàng. Lời chỉ trích không làm mất ánh sáng.',
      id: 'Perisaimu terbuat emas. Blame tidak bisa meredupkan cahayanya.',
    }),
    description: L({
      ko: '외부의 비판·비교·부정적 평가에서 자신을 완벽하게 지키는 단계입니다. 칭찬은 기쁘게 받아들이되 그것이 나의 가치를 결정하지 않는다는 것도 압니다. 실패와 자신을 분리하고 타인의 시선이 나의 기준이 되지 않습니다.',
      en: 'You fully protect yourself from external criticism, comparison, and negative judgment. You happily accept praise while knowing it doesn\'t define your worth. You separate failure from yourself, and others\' views don\'t become your standard.',
      ja: '外部の批判・比較・否定的評価から自分を完全に守る段階です。褒め言葉は喜んで受け取りつつ、それが自分の価値を決めないこともわかっています。失敗と自分を分離し、他人の視線が自分の基準になりません。',
      'zh-CN': '你能从外部批评、比较和负面评价中完整保护自己。开心接受赞美，也知道它不能决定价值。把失败与自我分开，别人的眼光不会成为你的标准。',
      'zh-TW': '你能從外部批評、比較和負面評價中完整保護自己。開心接受讚美，也知道它不能決定價值。把失敗與自我分開，別人的眼光不會成為你的標準。',
      vi: 'Bạn bảo vệ hoàn toàn bản thân khỏi chỉ trích, so sánh và đánh giá tiêu cực. Vui nhận lời khen nhưng biết nó không quyết định giá trị. Tách thất bại khỏi bản thân, ánh mắt người khác không thành tiêu chuẩn của bạn.',
      id: 'Kamu melindungi diri sepenuhnya dari kritik, perbandingan, dan penilaian negatif. Menerima pujian dengan senang sambil tahu itu tidak menentukan nilai. Memisahkan kegagalan dari diri, pandangan orang lain bukan standarmu.',
    }),
    shieldStrength: L({
      ko: 'Lv.6 황금 방패',
      en: 'Lv.6 Golden shield',
      ja: 'Lv.6 黄金シールド',
      'zh-CN': 'Lv.6 黄金盾牌',
      'zh-TW': 'Lv.6 黃金盾牌',
      vi: 'Lv.6 Lá chắn vàng',
      id: 'Lv.6 Perisai emas',
    }),
    pattern: null,
    strength: L({
      ko: '완전한 자기 신뢰·비판 선별 능력·칭찬 자연 수용·실패 분리 능력',
      en: 'Complete self-trust·criticism filtering·natural praise acceptance·failure separation',
      ja: '完全な自己信頼・批判選別・褒め言葉自然受容・失敗分離能力',
      'zh-CN': '完全自我信任·筛选批评·自然接受赞美·分离失败',
      'zh-TW': '完全自我信任·篩選批評·自然接受讚美·分離失敗',
      vi: 'Tự tin hoàn toàn·lọc chỉ trích·nhận khen tự nhiên·tách thất bại',
      id: 'Kepercayaan diri penuh·penyaringan kritik·penerimaan pujian alami·pemisahan kegagalan',
    }),
    needNow: null,
    actions: null,
    remainingTask: null,
    canDo: null,
    caution: L({
      ko: '방패가 두꺼워도 진심 어린 피드백을 놓치지 않는 유연성도 중요합니다',
      en: 'Even with a thick shield, flexibility to receive sincere feedback matters',
      ja: 'シールドが厚くても、真心のあるフィードバックを見逃さない柔軟性も大切です',
      'zh-CN': '即使盾牌很厚，也要保持接收真诚反馈的灵活',
      'zh-TW': '即使盾牌很厚，也要保持接收真誠回饋的靈活',
      vi: 'Dù lá chắn dày, sự linh hoạt để nhận phản hồi chân thành vẫn quan trọng',
      id: 'Meski perisai tebal, fleksibilitas menerima umpan balik tulus tetap penting',
    }),
    toOthers: L({
      ko: '이 사람과 함께 있으면 덩달아 자신감이 생깁니다',
      en: 'Being around this person naturally boosts confidence',
      ja: 'この人と一緒にいると自然と自信が湧きます',
      'zh-CN': '和这个人在一起会自然更有自信',
      'zh-TW': '和這個人在一起會自然更有自信',
      vi: 'Ở bên người này, tự tin cũng tăng theo',
      id: 'Bersama orang ini, percaya diri ikut tumbuh',
    }),
    affirmation: L({
      ko: '나는 외부의 비난에 흔들리지 않을 만큼 충분히 가치 있는 사람입니다 🏆',
      en: 'I am valuable enough not to be shaken by external blame 🏆',
      ja: '私は外部の非難に揺れないほど十分に価値のある人です 🏆',
      'zh-CN': '我足够有价值，不会因外部指责而动摇 🏆',
      'zh-TW': '我足夠有價值，不會因外部指責而動搖 🏆',
      vi: 'Tôi đủ giá trị để không bị lay bởi lời chỉ trích bên ngoài 🏆',
      id: 'Aku cukup berharga untuk tidak goyah oleh blame dari luar 🏆',
    }),
    shareSnippet: L({
      ko: '자존감 방패 강도: 황금 방패 🏆 자존감 금강불괴 달성... 나는 외부의 비난에 흔들리지 않을 만큼 충분히 가치 있는 사람 ✅ → 너는 어떤 방패 강도야?',
      en: 'Self-esteem shield: Golden 🏆 Unbreakable self-esteem achieved... I am valuable enough not to be shaken by blame ✅ → What\'s your shield?',
      ja: '自尊心シールド: 黄金 🏆 金剛不壊達成... 外部の非難に揺れないほど価値ある人 ✅ → あなたは？',
      'zh-CN': '自尊盾牌：黄金 🏆 金刚不坏达成... 我足够有价值 ✅ → 你是什么盾牌？',
      'zh-TW': '自尊盾牌：黃金 🏆 金剛不壞達成... 我足夠有價值 ✅ → 你是什麼盾牌？',
      vi: 'Lá chắn tự trọng: Vàng 🏆 Bất khả phá... Tôi đủ giá trị ✅ → Bạn có lá chắn gì?',
      id: 'Perisai harga diri: Emas 🏆 Tak tergoyahkan... Aku cukup berharga ✅ → Perisimu?',
    }),
  },
];
