/** 나의 스트레스 해소 유형 — 12문항 4지선다, A=0 B=1 C=2 D=3, 총점 0~36 → Type1~6 */

function T(t: {
  ko: string;
  en: string;
  ja: string;
  zhCN: string;
  zhTW: string;
  vi: string;
  id: string;
}): Record<string, string> {
  return {
    ko: t.ko,
    en: t.en,
    ja: t.ja,
    'zh-CN': t.zhCN,
    'zh-TW': t.zhTW,
    vi: t.vi,
    id: t.id,
  };
}

export interface Phase3StressReliefTypeQuestion {
  id: number;
  question: Record<string, string>;
  options: { text: Record<string, string>; score: number }[];
}

export interface Phase3StressReliefTypeResult {
  type: string;
  emoji: string;
  title: Record<string, string>;
  scoreBand: Record<string, string>;
  tagLine: Record<string, string>;
  hookLine: Record<string, string>;
  description: Record<string, string>;
  mechanism: Record<string, string>;
  strength: Record<string, string>;
  caution: Record<string, string>;
  routineText: Record<string, string>;
  actionNow: Record<string, string>;
  shareLine: Record<string, string>;
}

export function calculatePhase3StressReliefTypeResult(answers: number[]): string {
  const total = answers.reduce((sum, s) => sum + (s ?? 0), 0);
  if (total <= 5) return 'Type1';
  if (total <= 11) return 'Type2';
  if (total <= 19) return 'Type3';
  if (total <= 27) return 'Type4';
  if (total <= 33) return 'Type5';
  return 'Type6';
}

export const phase3StressReliefTypeQuestions: Phase3StressReliefTypeQuestion[] = [
  {
    id: 1,
    question: T({
      ko: '정말 힘든 날, 퇴근 후 가장 먼저 하고 싶은 것은?',
      en: 'After an exhausting day, what do you want to do first after work?',
      ja: '本当にしんどい日、退勤後にまずしたいことは？',
      zhCN: '特别累的一天，下班后你最想先做什么？',
      zhTW: '特別累的一天，下班後你最想先做什麼？',
      vi: 'Sau một ngày kiệt sức, bạn muốn làm gì đầu tiên sau khi tan làm?',
      id: 'Setelah hari yang melelahkan, apa yang paling ingin kamu lakukan pertama kali setelah pulang?',
    }),
    options: [
      {
        text: T({
          ko: '운동하거나 산책한다. 몸을 움직여야 머릿속이 비워진다',
          en: 'Work out or take a walk. Moving my body clears my head.',
          ja: '運動か散歩。体を動かすと頭が空になる。',
          zhCN: '运动或散步。动起来脑子才会清空。',
          zhTW: '運動或散步。動起來腦子才會清空。',
          vi: 'Tập luyện hoặc đi dạo. Phải vận động thì đầu óc mới “trống” ra.',
          id: 'Olahraga atau jalan santai. Aku harus bergerak dulu biar kepala kosong.',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '혼자 조용한 공간에서 아무것도 안 한다. 완전한 고독이 필요하다',
          en: 'Do nothing in a quiet place alone. I need complete solitude.',
          ja: '静かな場所で一人で何もしない。完全な孤独が必要。',
          zhCN: '在安静的空间里一个人什么都不做。我需要彻底的独处。',
          zhTW: '在安靜的空間裡一個人什麼都不做。我需要徹底的獨處。',
          vi: 'Ở một nơi yên tĩnh một mình và không làm gì cả. Mình cần sự cô độc hoàn toàn.',
          id: 'Diam sendiri di tempat tenang dan tidak melakukan apa-apa. Aku butuh benar-benar sendirian.',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '친구에게 연락해서 만나거나 통화한다. 말을 해야 풀린다',
          en: 'Call or meet a friend. I need to talk it out.',
          ja: '友達に連絡して会う／通話する。話さないとスッキリしない。',
          zhCN: '联系朋友见面或通话。不说出来就憋得慌。',
          zhTW: '聯絡朋友見面或通話。不說出來就憋得慌。',
          vi: 'Gọi hoặc gặp bạn. Phải nói ra thì mới nhẹ người.',
          id: 'Menghubungi teman untuk ketemu/telepon. Harus ngomong dulu baru lega.',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '맛있는 걸 먹거나 좋아하는 콘텐츠를 본다. 작은 즐거움이 최고다',
          en: 'Eat something good or watch what I like. Small pleasures are the best.',
          ja: '美味しいものを食べる／好きなコンテンツを見る。小さな楽しみが最高。',
          zhCN: '吃点好吃的或看喜欢的内容。小确幸最管用。',
          zhTW: '吃點好吃的或看喜歡的內容。小確幸最管用。',
          vi: 'Ăn món ngon hoặc xem nội dung mình thích. Niềm vui nhỏ là nhất.',
          id: 'Makan enak atau nonton konten favorit. Kebahagiaan kecil itu paling ampuh.',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 2,
    question: T({
      ko: '스트레스가 쌓였을 때 몸에서 가장 먼저 나타나는 신호는?',
      en: 'When stress builds up, what signal shows up first in your body?',
      ja: 'ストレスが溜まったとき、体に最初に出るサインは？',
      zhCN: '压力累积时，你身体最先出现的信号是？',
      zhTW: '壓力累積時，你身體最先出現的訊號是？',
      vi: 'Khi stress tích lại, tín hiệu đầu tiên xuất hiện trên cơ thể bạn là gì?',
      id: 'Saat stres menumpuk, sinyal pertama yang muncul di tubuhmu apa?',
    }),
    options: [
      {
        text: T({
          ko: '몸이 무겁거나 긴장된다. 어깨·목이 뭉치거나 두통이 온다',
          en: 'My body feels heavy/tense—tight shoulders/neck or headaches.',
          ja: '体が重い／緊張する。肩・首が凝ったり頭痛がする。',
          zhCN: '身体变沉或紧绷。肩颈僵硬，甚至头痛。',
          zhTW: '身體變沉或緊繃。肩頸僵硬，甚至頭痛。',
          vi: 'Cơ thể nặng và căng. Vai–cổ cứng hoặc đau đầu.',
          id: 'Badan terasa berat/tegang. Bahu-leher kaku atau sakit kepala.',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '말수가 줄고 혼자 있고 싶어진다. 사람이 피곤하게 느껴진다',
          en: 'I talk less and want to be alone. People feel exhausting.',
          ja: '口数が減って一人になりたくなる。人といるのが疲れる。',
          zhCN: '话变少，想一个人待着。跟人相处很累。',
          zhTW: '話變少，想一個人待著。跟人相處很累。',
          vi: 'Mình ít nói lại và muốn ở một mình. Gặp người khác thấy mệt.',
          id: 'Aku jadi lebih pendiam dan ingin sendiri. Berinteraksi terasa melelahkan.',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '자꾸 말하고 싶어진다. 누군가에게 털어놓지 않으면 답답하다',
          en: 'I want to talk nonstop. If I don’t vent to someone, I feel suffocated.',
          ja: 'とにかく話したくなる。誰かに吐き出さないと苦しい。',
          zhCN: '总想说话。不找人倾诉就憋得难受。',
          zhTW: '總想說話。不找人傾訴就憋得難受。',
          vi: 'Mình cứ muốn nói. Không kể ra với ai là bí bách.',
          id: 'Aku jadi pengin terus ngomong. Kalau nggak curhat, rasanya sesak.',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '뭔가 먹고 싶거나 쇼핑하고 싶어진다. 소비 욕구가 올라온다',
          en: 'I crave food or shopping. The urge to spend rises.',
          ja: '何か食べたい／買い物したい。消費欲が上がる。',
          zhCN: '想吃东西或想购物。消费冲动上来。',
          zhTW: '想吃東西或想購物。消費衝動上來。',
          vi: 'Mình thèm ăn hoặc muốn mua sắm. Ham muốn tiêu tiền tăng lên.',
          id: 'Aku jadi ingin makan atau belanja. Dorongan konsumsi naik.',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 3,
    question: T({
      ko: '스트레스가 해소됐다는 것을 알아차리는 순간은?',
      en: 'When do you realize your stress has been relieved?',
      ja: 'ストレスが解消されたと感じる瞬間は？',
      zhCN: '你在什么时候意识到压力被释放了？',
      zhTW: '你在什麼時候意識到壓力被釋放了？',
      vi: 'Khi nào bạn nhận ra mình đã “xả” được stress?',
      id: 'Kapan kamu sadar stresmu sudah reda?',
    }),
    options: [
      {
        text: T({
          ko: '땀을 흘리고 샤워한 뒤 몸이 가벼워질 때',
          en: 'After sweating and taking a shower—my body feels lighter.',
          ja: '汗をかいてシャワーした後、体が軽くなるとき。',
          zhCN: '流完汗洗完澡，身体变轻松的时候。',
          zhTW: '流完汗洗完澡，身體變輕鬆的時候。',
          vi: 'Sau khi ra mồ hôi và tắm xong, cơ thể nhẹ hẳn.',
          id: 'Setelah berkeringat dan mandi, badan terasa ringan.',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '혼자만의 시간을 충분히 보낸 뒤 마음이 차분해질 때',
          en: 'After enough alone time—my mind becomes calm.',
          ja: '一人の時間を十分に過ごして、心が落ち着いたとき。',
          zhCN: '独处时间够了之后，心里变得安稳的时候。',
          zhTW: '獨處時間夠了之後，心裡變得安穩的時候。',
          vi: 'Sau khi ở một mình đủ lâu, tâm trí trở nên bình tĩnh.',
          id: 'Setelah cukup waktu sendiri, hati jadi tenang.',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '친한 사람과 실컷 웃고 나서 기분이 가벼워질 때',
          en: 'After laughing a lot with someone close—my mood feels lighter.',
          ja: '親しい人とたくさん笑った後、気分が軽くなるとき。',
          zhCN: '和亲近的人笑到尽兴后，心情变轻的时候。',
          zhTW: '和親近的人笑到盡興後，心情變輕的時候。',
          vi: 'Sau khi cười thả ga với người thân, cảm xúc nhẹ đi.',
          id: 'Setelah ketawa puas dengan orang dekat, perasaan jadi ringan.',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '맛있는 것을 먹거나 좋아하는 것을 하고 나서 기분이 좋아질 때',
          en: 'After eating something good or doing what I like—I feel better.',
          ja: '美味しいものを食べたり好きなことをして、気分が良くなるとき。',
          zhCN: '吃到好吃的或做喜欢的事后，心情变好时。',
          zhTW: '吃到好吃的或做喜歡的事後，心情變好時。',
          vi: 'Sau khi ăn ngon hoặc làm điều mình thích, tâm trạng tốt lên.',
          id: 'Setelah makan enak atau melakukan hal yang disuka, mood jadi bagus.',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 4,
    question: T({
      ko: '주말에 완전히 쉰다고 했을 때 이상적인 하루는?',
      en: 'If you could fully rest on the weekend, what’s your ideal day?',
      ja: '週末に完全に休むなら理想の一日は？',
      zhCN: '如果周末能彻底休息，你理想的一天是？',
      zhTW: '如果週末能徹底休息，你理想的一天是？',
      vi: 'Nếu cuối tuần được nghỉ trọn vẹn, một ngày lý tưởng của bạn là gì?',
      id: 'Kalau akhir pekan bisa istirahat total, hari idealmu seperti apa?',
    }),
    options: [
      {
        text: T({
          ko: '아침 운동 후 건강한 브런치. 오후엔 가벼운 산책이나 스포츠 활동',
          en: 'Morning workout + healthy brunch. A light walk or sports in the afternoon.',
          ja: '朝運動してヘルシーブランチ。午後は散歩や軽いスポーツ。',
          zhCN: '早上运动+健康早午餐，下午散步或运动一下。',
          zhTW: '早上運動+健康早午餐，下午散步或運動一下。',
          vi: 'Sáng tập luyện + brunch lành mạnh, chiều đi dạo nhẹ hoặc chơi thể thao.',
          id: 'Olahraga pagi + brunch sehat, sore jalan santai atau aktivitas olahraga ringan.',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '늦게 일어나서 혼자 커피 마시며 책 읽기. 아무도 만나지 않는 날',
          en: 'Sleep in, sip coffee alone, read a book—meet nobody.',
          ja: '遅く起きて一人でコーヒーと読書。誰にも会わない日。',
          zhCN: '睡到自然醒，一个人喝咖啡看书，不见任何人。',
          zhTW: '睡到自然醒，一個人喝咖啡看書，不見任何人。',
          vi: 'Ngủ nướng, uống cà phê một mình và đọc sách—không gặp ai.',
          id: 'Bangun siang, ngopi sendirian sambil baca—tidak ketemu siapa pun.',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '친한 친구들과 밥 먹고 카페 가서 수다. 저녁엔 같이 술 한 잔',
          en: 'Eat with close friends, chat at a café, then drinks together at night.',
          ja: '仲の良い友達とご飯→カフェでおしゃべり→夜は一杯。',
          zhCN: '和好友吃饭去咖啡馆聊天，晚上再小酌。',
          zhTW: '和好友吃飯去咖啡館聊天，晚上再小酌。',
          vi: 'Ăn với bạn thân, cà phê tám chuyện, tối uống một ly cùng nhau.',
          id: 'Makan bareng teman dekat, ngobrol di kafe, malamnya minum sedikit bareng.',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '좋아하는 음식 배달 시키고 넷플릭스 정주행. 아무것도 안 하는 날',
          en: 'Order my favorite food and binge Netflix—do absolutely nothing.',
          ja: '好きなものをデリバリーしてNetflix一気見。何もしない日。',
          zhCN: '点喜欢的外卖、刷剧，一整天啥也不干。',
          zhTW: '點喜歡的外賣、刷劇，一整天啥也不幹。',
          vi: 'Gọi đồ ăn mình thích và cày Netflix—không làm gì cả.',
          id: 'Pesan makanan favorit dan marathon Netflix—nggak ngapa-ngapain.',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 5,
    question: T({
      ko: '회사나 학교에서 힘든 일이 생겼을 때 나는?',
      en: 'When something stressful happens at work or school, I…',
      ja: '職場や学校でつらいことが起きたとき、私は？',
      zhCN: '在公司/学校遇到糟心事时，我会？',
      zhTW: '在公司/學校遇到糟心事時，我會？',
      vi: 'Khi có chuyện mệt ở công ty/trường học, mình…',
      id: 'Saat ada hal berat di kantor/sekolah, aku…',
    }),
    options: [
      {
        text: T({
          ko: '점심에 빠르게 산책하거나 계단 오르기로 즉시 해소한다',
          en: 'Take a quick walk or climb stairs at lunch to release it immediately.',
          ja: '昼休みに散歩や階段で即リセットする。',
          zhCN: '午休快走/爬楼，立刻发散掉。',
          zhTW: '午休快走/爬樓，立刻發散掉。',
          vi: 'Đi bộ nhanh hoặc leo cầu thang giờ trưa để xả ngay.',
          id: 'Jalan cepat atau naik tangga saat makan siang untuk langsung lega.',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '잠깐 화장실에 가거나 조용한 공간에서 혼자 있는 시간을 만든다',
          en: 'Step away to the restroom or a quiet spot for a short alone break.',
          ja: 'トイレや静かな場所に行って一人時間を作る。',
          zhCN: '去趟洗手间或安静角落，给自己一点独处。',
          zhTW: '去趟洗手間或安靜角落，給自己一點獨處。',
          vi: 'Ra nhà vệ sinh hoặc chỗ yên tĩnh để có vài phút một mình.',
          id: 'Ke toilet atau tempat tenang sebentar untuk punya waktu sendiri.',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '친한 동료에게 바로 털어놓는다. 듣는 사람이 있어야 버틸 수 있다',
          en: 'Tell a close coworker right away. I need someone to listen to endure it.',
          ja: '仲の良い同僚にすぐ話す。聞いてくれる人が必要。',
          zhCN: '立刻跟熟人同事吐槽。有人听我说才扛得住。',
          zhTW: '立刻跟熟人同事吐槽。有人聽我說才扛得住。',
          vi: 'Kể ngay với đồng nghiệp thân. Có người nghe mình mới chịu nổi.',
          id: 'Langsung curhat ke rekan dekat. Aku butuh yang dengerin biar kuat.',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '맛있는 점심이나 간식으로 기분 전환한다. 먹으면 일단 나아진다',
          en: 'Switch my mood with a tasty lunch/snack. Eating helps first.',
          ja: '美味しいランチやおやつで気分転換。食べるとまず楽になる。',
          zhCN: '吃顿好午饭/小零食转换心情。先吃了再说。',
          zhTW: '吃頓好午飯/小零食轉換心情。先吃了再說。',
          vi: 'Đổi mood bằng bữa trưa/đồ ăn vặt ngon. Ăn vào là đỡ trước.',
          id: 'Ganti mood dengan makan siang/camilan enak. Kalau makan biasanya mendingan.',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 6,
    question: T({
      ko: '스트레스 상황에서 나를 가장 힘들게 하는 것은?',
      en: 'In stressful situations, what’s the hardest part for you?',
      ja: 'ストレス状況で一番つらいのは？',
      zhCN: '压力情境里，最让你难受的是？',
      zhTW: '壓力情境裡，最讓你難受的是？',
      vi: 'Trong tình huống stress, điều khiến bạn mệt nhất là gì?',
      id: 'Dalam situasi stres, hal yang paling bikin kamu berat adalah?',
    }),
    options: [
      {
        text: T({
          ko: '몸을 못 움직이는 상황. 앉아서 참기만 해야 할 때',
          en: 'Not being able to move—having to sit still and endure.',
          ja: '体を動かせない状況。座って耐えるしかないとき。',
          zhCN: '不能动，只能坐着硬扛的情况。',
          zhTW: '不能動，只能坐著硬扛的情況。',
          vi: 'Không thể vận động, chỉ ngồi đó chịu đựng.',
          id: 'Tidak bisa bergerak—harus duduk diam dan menahan.',
        }),
        score: 0,
      },
      {
        text: T({
          ko: '혼자 있는 시간이 없는 상황. 계속 사람들과 있어야 할 때',
          en: 'Having no alone time—being around people nonstop.',
          ja: '一人の時間がない状況。ずっと人と一緒にいなきゃいけないとき。',
          zhCN: '没有独处时间，一直要跟人待在一起。',
          zhTW: '沒有獨處時間，一直要跟人待在一起。',
          vi: 'Không có thời gian một mình, phải ở cạnh người khác liên tục.',
          id: 'Tidak punya waktu sendiri—harus terus bersama orang.',
        }),
        score: 1,
      },
      {
        text: T({
          ko: '혼자 삭여야 하는 상황. 말할 사람이 없거나 들어줄 사람이 없을 때',
          en: 'Having to swallow it alone—no one to talk to or who will listen.',
          ja: '一人で抱え込む状況。話す相手や聞いてくれる人がいないとき。',
          zhCN: '只能自己憋着，没有人可说、也没人愿意听。',
          zhTW: '只能自己憋著，沒有人可說、也沒人願意聽。',
          vi: 'Phải tự nuốt một mình—không có ai để nói hoặc lắng nghe.',
          id: 'Harus dipendam sendiri—nggak ada tempat cerita atau yang mau dengerin.',
        }),
        score: 2,
      },
      {
        text: T({
          ko: '아무것도 할 수 없는 상황. 즐거운 것도 없고 기댈 것도 없을 때',
          en: 'When I can’t do anything—no fun, no comfort, nothing to lean on.',
          ja: '何もできない状況。楽しみも拠り所もないとき。',
          zhCN: '什么都做不了，没乐趣也没依靠的时候。',
          zhTW: '什麼都做不了，沒樂趣也沒依靠的時候。',
          vi: 'Khi không làm được gì—không niềm vui, không chỗ dựa.',
          id: 'Saat tidak bisa melakukan apa-apa—tidak ada hiburan dan tidak ada pegangan.',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 7,
    question: T({
      ko: '나에게 가장 잘 맞는 혼자만의 회복 방법은?',
      en: 'Which solo recovery method fits you best?',
      ja: '自分に一番合う一人回復法は？',
      zhCN: '最适合你的独自恢复方式是？',
      zhTW: '最適合你的獨自恢復方式是？',
      vi: 'Cách hồi phục một mình hợp với bạn nhất là gì?',
      id: 'Cara pemulihan sendiri yang paling cocok untukmu adalah?',
    }),
    options: [
      { text: T({ ko: '러닝·헬스·요가·등산 등 신체 활동', en: 'Physical activity: running, gym, yoga, hiking', ja: 'ランニング・ジム・ヨガ・登山などの運動', zhCN: '身体活动：跑步/健身/瑜伽/登山', zhTW: '身體活動：跑步/健身/瑜伽/登山', vi: 'Vận động: chạy bộ, gym, yoga, leo núi', id: 'Aktivitas fisik: lari, gym, yoga, hiking' }), score: 0 },
      { text: T({ ko: '독서·명상·일기 쓰기·조용한 음악 감상', en: 'Reading, meditation, journaling, calm music', ja: '読書・瞑想・日記・静かな音楽', zhCN: '读书/冥想/写日记/听安静的音乐', zhTW: '讀書/冥想/寫日記/聽安靜的音樂', vi: 'Đọc sách, thiền, viết nhật ký, nghe nhạc nhẹ', id: 'Membaca, meditasi, journaling, musik yang tenang' }), score: 1 },
      { text: T({ ko: '좋아하는 유튜버 보기·드라마·예능 등 가벼운 콘텐츠', en: 'Light content: YouTube, dramas, variety shows', ja: 'YouTube・ドラマ・バラエティなど軽いコンテンツ', zhCN: '轻松内容：YouTube/剧/综艺', zhTW: '輕鬆內容：YouTube/劇/綜藝', vi: 'Nội dung nhẹ: YouTube, drama, show giải trí', id: 'Konten ringan: YouTube, drama, variety show' }), score: 2 },
      { text: T({ ko: '맛있는 음식·향기로운 목욕·쇼핑·취미 활동', en: 'Treats: good food, scented baths, shopping, hobbies', ja: '美味しい物・香りの良い入浴・買い物・趣味', zhCN: '奖励：美食/香氛泡澡/购物/爱好', zhTW: '獎勵：美食/香氛泡澡/購物/愛好', vi: 'Tự thưởng: đồ ăn ngon, tắm thơm, mua sắm, sở thích', id: 'Self-reward: makanan enak, mandi wangi, belanja, hobi' }), score: 3 },
    ],
  },
  {
    id: 8,
    question: T({
      ko: '스트레스 해소 후 다음 날 느끼는 감정은?',
      en: 'How do you feel the next day after relieving stress?',
      ja: 'ストレス解消後、翌日に感じるのは？',
      zhCN: '解压后第二天你的感觉是？',
      zhTW: '解壓後第二天你的感覺是？',
      vi: 'Hôm sau khi xả stress, bạn cảm thấy thế nào?',
      id: 'Keesokan harinya setelah melepas stres, kamu merasa bagaimana?',
    }),
    options: [
      { text: T({ ko: '몸이 가볍고 에너지가 올라온 느낌이다', en: 'My body feels lighter and my energy rises.', ja: '体が軽く、エネルギーが上がる感じ。', zhCN: '身体更轻，能量上来了。', zhTW: '身體更輕，能量上來了。', vi: 'Cơ thể nhẹ và năng lượng tăng lên.', id: 'Badan terasa ringan dan energiku naik.' }), score: 0 },
      { text: T({ ko: '머릿속이 정리된 느낌. 생각이 차분해진다', en: 'My head feels organized; my thoughts become calm.', ja: '頭が整理され、考えが落ち着く。', zhCN: '脑子理顺了，想法更平静。', zhTW: '腦子理順了，想法更平靜。', vi: 'Đầu óc gọn lại, suy nghĩ bình tĩnh hơn.', id: 'Kepalaku terasa tertata; pikiranku lebih tenang.' }), score: 1 },
      { text: T({ ko: '기분이 좋고 연결된 느낌. 혼자가 아니라는 안도감이 있다', en: 'I feel good and connected—relieved that I’m not alone.', ja: '気分がよくつながりを感じる。孤独じゃない安心感。', zhCN: '心情变好、有连接感，觉得自己不是一个人。', zhTW: '心情變好、有連結感，覺得自己不是一個人。', vi: 'Vui hơn và thấy được kết nối—yên tâm vì không cô đơn.', id: 'Aku merasa lebih baik dan terhubung—lega karena tidak sendirian.' }), score: 2 },
      { text: T({ ko: '충전된 느낌. 작은 행복을 경험했다는 만족감이 있다', en: 'I feel recharged—satisfied from a small happiness.', ja: '充電された感じ。小さな幸せを得た満足感。', zhCN: '像被充电一样，因小幸福而满足。', zhTW: '像被充電一樣，因小幸福而滿足。', vi: 'Như được sạc lại, hài lòng vì có một niềm vui nhỏ.', id: 'Rasanya terisi ulang, puas karena mengalami kebahagiaan kecil.' }), score: 3 },
    ],
  },
  {
    id: 9,
    question: T({
      ko: '휴가가 주어진다면 가장 하고 싶은 것은?',
      en: 'If you had a vacation, what would you want to do most?',
      ja: '休暇がもらえたら一番したいことは？',
      zhCN: '如果给你假期，你最想做的是？',
      zhTW: '如果給你假期，你最想做的是？',
      vi: 'Nếu có kỳ nghỉ, bạn muốn làm gì nhất?',
      id: 'Kalau dapat liburan, kamu paling ingin ngapain?',
    }),
    options: [
      { text: T({ ko: '하이킹·서핑·자전거 여행 등 액티비티 위주의 활동적인 휴가', en: 'An activity-heavy trip: hiking, surfing, cycling', ja: 'ハイキング・サーフィン・自転車旅などアクティブな休暇', zhCN: '以活动为主：徒步/冲浪/骑行旅行', zhTW: '以活動為主：徒步/衝浪/騎行旅行', vi: 'Kỳ nghỉ năng động: hiking, lướt sóng, đạp xe', id: 'Liburan aktif: hiking, surfing, bersepeda' }), score: 0 },
      { text: T({ ko: '아무 계획 없이 혼자 조용한 숙소에서 쉬는 1인 휴가', en: 'A quiet solo getaway with no plan', ja: '予定なしで静かな宿で一人休む休暇', zhCN: '不做计划，一个人安静住着休息', zhTW: '不做計畫，一個人安靜住著休息', vi: 'Nghỉ một mình ở chỗ yên tĩnh, không kế hoạch', id: 'Liburan sendiri di tempat tenang tanpa rencana' }), score: 1 },
      { text: T({ ko: '친한 친구나 연인과 함께하는 여행. 추억 만들기가 목적', en: 'Travel with close friends/partner to make memories', ja: '親しい友達や恋人と旅して思い出作り', zhCN: '和好友/伴侣旅行，主打“制造回忆”', zhTW: '和好友/伴侶旅行，主打「製造回憶」', vi: 'Du lịch với bạn thân/người yêu để tạo kỷ niệm', id: 'Liburan dengan teman dekat/pasangan untuk bikin kenangan' }), score: 2 },
      { text: T({ ko: '맛집 탐방·호캉스·좋아하는 것 실컷 하는 자기 보상 휴가', en: 'Food tour, hotel staycation, and pure self-reward', ja: 'グルメ巡り・ホカンス・好きなこと尽くしのご褒美休暇', zhCN: '美食探店/酒店度假，把喜欢的都安排上', zhTW: '美食探店/飯店度假，把喜歡的都安排上', vi: 'Ăn ngon, nghỉ khách sạn, tự thưởng hết mình', id: 'Wisata kuliner, staycation hotel, self-reward sepuasnya' }), score: 3 },
    ],
  },
  {
    id: 10,
    question: T({
      ko: '스트레스를 받을 때 주변 사람들에게 주로 하는 행동은?',
      en: 'When you’re stressed, what do you usually do with people around you?',
      ja: 'ストレスを感じるとき、周りの人に対してよくする行動は？',
      zhCN: '你压力大时，对周围人通常会？',
      zhTW: '你壓力大時，對周圍人通常會？',
      vi: 'Khi bị stress, bạn thường làm gì với những người xung quanh?',
      id: 'Saat stres, kamu biasanya bersikap bagaimana ke orang sekitar?',
    }),
    options: [
      { text: T({ ko: '평소보다 더 활동적으로 움직인다. 바쁘게 있어야 잊힌다', en: 'I move even more and stay busy—it helps me forget.', ja: 'いつも以上に動く。忙しくしていると忘れられる。', zhCN: '变得更忙、更爱动，忙起来就能忘。', zhTW: '變得更忙、更愛動，忙起來就能忘。', vi: 'Mình hoạt động nhiều hơn, phải bận rộn mới quên được.', id: 'Aku jadi lebih aktif dan sibuk—biar lupa.' }), score: 0 },
      { text: T({ ko: '연락을 줄이고 혼자만의 공간으로 들어간다', en: 'I reduce contact and retreat into my own space.', ja: '連絡を減らして自分の空間にこもる。', zhCN: '减少联系，躲回自己的空间。', zhTW: '減少聯繫，躲回自己的空間。', vi: 'Mình ít liên lạc hơn và rút vào không gian riêng.', id: 'Aku mengurangi kontak dan masuk ke ruang sendiri.' }), score: 1 },
      { text: T({ ko: '오히려 더 많이 연락한다. 주변에 사람이 있어야 버텨진다', en: 'I reach out more. I need people around to hold up.', ja: 'むしろ連絡が増える。周りに人がいないと耐えられない。', zhCN: '反而更爱联系别人。身边得有人我才撑得住。', zhTW: '反而更愛聯繫別人。身邊得有人我才撐得住。', vi: 'Mình liên lạc nhiều hơn. Có người xung quanh mới chịu được.', id: 'Aku jadi lebih sering menghubungi orang. Harus ada orang di sekitar agar kuat.' }), score: 2 },
      { text: T({ ko: '평소보다 더 먹거나 소비한다. 나를 위한 보상을 한다', en: 'I eat/spend more than usual—self-reward mode.', ja: '普段より食べたり使ったりする。自分へのご褒美。', zhCN: '吃得更多/花得更多，进入“犒赏自己”模式。', zhTW: '吃得更多/花得更多，進入「犒賞自己」模式。', vi: 'Mình ăn/tiêu nhiều hơn bình thường—tự thưởng.', id: 'Aku makan/belanja lebih dari biasanya—mode self-reward.' }), score: 3 },
    ],
  },
  {
    id: 11,
    question: T({
      ko: '스트레스 해소에 실패했을 때의 패턴은?',
      en: 'What’s your pattern when you fail to relieve stress?',
      ja: 'ストレス解消に失敗したときのパターンは？',
      zhCN: '当你解压失败时的模式是？',
      zhTW: '當你解壓失敗時的模式是？',
      vi: 'Khi xả stress không thành, “pattern” của bạn là gì?',
      id: 'Kalau gagal melepas stres, pola yang muncul biasanya apa?',
    }),
    options: [
      { text: T({ ko: '운동을 못 한 날은 몸이 더 무겁고 피로가 남는다', en: 'On days I can’t exercise, my body feels heavier and fatigue stays.', ja: '運動できない日は体が重く、疲れが残る。', zhCN: '没运动的日子身体更沉，疲劳残留。', zhTW: '沒運動的日子身體更沉，疲勞殘留。', vi: 'Ngày không vận động thì cơ thể nặng và mệt dai dẳng.', id: 'Hari tanpa olahraga, badan terasa lebih berat dan lelahnya menetap.' }), score: 0 },
      { text: T({ ko: '혼자 있는 시간이 없으면 과민해지거나 예민해진다', en: 'If I don’t get alone time, I become irritable and sensitive.', ja: '一人時間がないと過敏・神経質になる。', zhCN: '没有独处时间就会变得敏感/易怒。', zhTW: '沒有獨處時間就會變得敏感/易怒。', vi: 'Không có thời gian một mình là mình dễ cáu và nhạy cảm.', id: 'Kalau tidak ada waktu sendiri, aku jadi mudah tersinggung dan sensitif.' }), score: 1 },
      { text: T({ ko: '혼자 삭이다 보면 속이 답답하고 더 오래 힘들다', en: 'If I bottle it up alone, I feel suffocated and it drags on longer.', ja: '一人で抱え込むと苦しくて長引く。', zhCN: '自己憋着会更闷、更久都缓不过来。', zhTW: '自己憋著會更悶、更久都緩不過來。', vi: 'Tự nuốt một mình khiến mình bí bách và khó nguôi lâu hơn.', id: 'Kalau dipendam sendiri, rasanya sesak dan jadi lebih lama sulitnya.' }), score: 2 },
      { text: T({ ko: '즐거운 것 없이 버티다 보면 의욕이 사라진다', en: 'If I just endure without anything enjoyable, I lose motivation.', ja: '楽しみなく耐えるとやる気が消える。', zhCN: '没有一点快乐只能硬撑的话，动力会消失。', zhTW: '沒有一點快樂只能硬撐的話，動力會消失。', vi: 'Cứ gồng mà không có niềm vui thì mình mất động lực.', id: 'Kalau bertahan tanpa hal menyenangkan, motivasiku hilang.' }), score: 3 },
    ],
  },
  {
    id: 12,
    question: T({
      ko: '지금 나에게 가장 필요한 회복 방식을 고른다면?',
      en: 'If you had to pick what you need most right now, what would it be?',
      ja: '今一番必要な回復法を選ぶなら？',
      zhCN: '此刻你最需要的恢复方式是？',
      zhTW: '此刻你最需要的恢復方式是？',
      vi: 'Nếu chọn cách hồi phục bạn cần nhất lúc này, đó là gì?',
      id: 'Kalau harus memilih pemulihan yang paling kamu butuhkan sekarang, itu apa?',
    }),
    options: [
      { text: T({ ko: '땀 흘리는 운동 한 번. 몸을 쓰면 머리가 비워진다', en: 'One sweaty workout. Use my body, clear my head.', ja: '汗をかく運動を一回。体を使うと頭が空になる。', zhCN: '狠狠干一次运动。身体动起来，脑子就清空。', zhTW: '狠狠幹一次運動。身體動起來，腦子就清空。', vi: 'Một lần tập ra mồ hôi. Vận động là đầu óc trống ra.', id: 'Sekali olahraga sampai berkeringat. Kalau tubuh bergerak, kepala jadi kosong.' }), score: 0 },
      { text: T({ ko: '혼자서 조용히 보내는 반나절. 아무것도 안 해도 되는 시간', en: 'A quiet half-day alone—time where I’m allowed to do nothing.', ja: '静かに一人で過ごす半日。何もしなくていい時間。', zhCN: '安静独处半天。可以什么都不做的时间。', zhTW: '安靜獨處半天。可以什麼都不做的時間。', vi: 'Nửa ngày yên tĩnh một mình—thời gian được phép không làm gì.', id: 'Setengah hari tenang sendirian—waktu di mana aku boleh tidak melakukan apa-apa.' }), score: 1 },
      { text: T({ ko: '친한 사람과의 따뜻한 대화 한 번. 들어주는 사람이 있으면 된다', en: 'One warm conversation with someone close—just having a listener is enough.', ja: '親しい人との温かい会話を一回。聞いてくれる人がいればいい。', zhCN: '和亲近的人来一次温暖的对话。有个愿意听的人就够了。', zhTW: '和親近的人來一次溫暖的對話。有個願意聽的人就夠了。', vi: 'Một cuộc trò chuyện ấm áp với người thân—chỉ cần có người lắng nghe.', id: 'Satu obrolan hangat dengan orang dekat—cukup ada yang mau mendengarkan.' }), score: 2 },
      { text: T({ ko: '나만의 작은 즐거움 하나. 맛있는 것이든 좋아하는 것이든', en: 'One small pleasure—something delicious or something I love.', ja: '自分だけの小さな楽しみ一つ。美味しいものでも好きなことでも。', zhCN: '给自己一个小快乐：好吃的也好，喜欢的也好。', zhTW: '給自己一個小快樂：好吃的也好，喜歡的也好。', vi: 'Một niềm vui nhỏ cho riêng mình—món ngon hay điều mình thích đều được.', id: 'Satu kebahagiaan kecil untuk diri sendiri—makanan enak atau hal yang kusuka.' }), score: 3 },
    ],
  },
];

export const phase3StressReliefTypeResults: Phase3StressReliefTypeResult[] = [
  {
    type: 'Type1',
    emoji: '🏃',
    title: T({
      ko: '땀으로 리셋하는, 신체 활동 해소형',
      en: 'Sweat-to-Reset: Active Relief Type',
      ja: '汗でリセットする、身体活動リリーフタイプ',
      zhCN: '用流汗重启：运动释放型',
      zhTW: '用流汗重啟：運動釋放型',
      vi: 'Reset bằng mồ hôi: Kiểu giải tỏa bằng vận động',
      id: 'Reset dengan keringat: Tipe pelepas stres lewat aktivitas',
    }),
    scoreBand: T({
      ko: '총점 0~5점 구간',
      en: 'Total score: 0–5',
      ja: '合計 0〜5点',
      zhCN: '总分 0–5',
      zhTW: '總分 0–5',
      vi: 'Tổng điểm: 0–5',
      id: 'Skor total: 0–5',
    }),
    tagLine: T({
      ko: '스트레스 해소 유형: 몸을 움직여야 머릿속이 비워지는 사람',
      en: 'Relief type: Your head clears when you move your body.',
      ja: '解消タイプ：体を動かすと頭が空になる人。',
      zhCN: '解压类型：动起来，脑子才会清空。',
      zhTW: '解壓類型：動起來，腦子才會清空。',
      vi: 'Kiểu giải tỏa: Vận động là đầu óc nhẹ hẳn.',
      id: 'Tipe: Kepala jadi lega saat tubuh bergerak.',
    }),
    hookLine: T({
      ko: '"당신의 스트레스 해소 버튼은 운동입니다. 땀 한 번이 말 열 마디보다 효과적입니다."',
      en: '"Your stress-relief button is exercise. One good sweat beats ten conversations."',
      ja: '「あなたの解消ボタンは運動。汗ひとつで言葉十個分。」',
      zhCN: '“你的解压按钮是运动。出一次汗，比说十句话都管用。”',
      zhTW: '「你的解壓按鈕是運動。出一次汗，比說十句話都管用。」',
      vi: '“Nút xả stress của bạn là vận động. Ra mồ hôi một lần hiệu quả hơn mười câu nói.”',
      id: '"Tombol pelepas stresmu adalah olahraga. Sekali berkeringat lebih manjur daripada sepuluh kalimat."',
    }),
    description: T({
      ko: '스트레스가 쌓이면 몸이 먼저 반응하고, 몸을 움직이지 않으면 긴장이 빠져나가지 않습니다. 러닝·헬스·요가·등산 어떤 것이든 신체를 활성화하면 머릿속이 자연스럽게 비워지는 타입입니다. 운동을 못 한 날은 유독 피로가 쌓이고 예민해지는 경향이 있습니다.',
      en: 'When stress builds up, your body reacts first. If you can’t move, tension doesn’t release. Running, gym, yoga, hiking—any activation clears your mind naturally. On days you skip movement, fatigue lingers and you get more sensitive.',
      ja: 'ストレスが溜まると体が先に反応し、動けないと緊張が抜けません。ランニング・ジム・ヨガ・登山など、体を起こすほど頭が自然に空になるタイプ。運動できない日は疲れが残り、イライラしやすい傾向も。',
      zhCN: '压力一上来，你先是身体反应；不动就很难把紧张排出去。跑步、健身、瑜伽、登山都行，只要身体被激活，脑子就会自然清空。缺少运动的日子更容易疲惫和敏感。',
      zhTW: '壓力一上來，你先是身體反應；不動就很難把緊張排出去。跑步、健身、瑜伽、登山都行，只要身體被激活，腦子就會自然清空。缺少運動的日子更容易疲憊和敏感。',
      vi: 'Khi stress tích lại, cơ thể bạn phản ứng trước; không vận động thì căng thẳng khó thoát ra. Dù chạy bộ, gym, yoga hay leo núi, chỉ cần kích hoạt cơ thể là đầu óc tự nhẹ đi. Ngày không vận động thường mệt và dễ cáu hơn.',
      id: 'Saat stres menumpuk, tubuhmu bereaksi dulu; kalau tidak bergerak, tegangnya tidak keluar. Lari, gym, yoga, hiking—apa pun yang mengaktifkan tubuh akan mengosongkan kepala secara alami. Hari tanpa olahraga cenderung lebih lelah dan sensitif.',
    }),
    mechanism: T({
      ko: '운동 → 엔도르핀·세로토닌 분비 → 스트레스 호르몬 코르티솔 감소',
      en: 'Exercise → endorphins/serotonin → lower cortisol',
      ja: '運動 → エンドルフィン・セロトニン → コルチゾール低下',
      zhCN: '运动 → 内啡肽/血清素 → 降低皮质醇',
      zhTW: '運動 → 內啡肽/血清素 → 降低皮質醇',
      vi: 'Vận động → endorphin/serotonin → giảm cortisol',
      id: 'Olahraga → endorfin/serotonin → menurunkan kortisol',
    }),
    strength: T({
      ko: '가장 과학적으로 검증된 스트레스 해소법. 신체 건강과 동시에 해결됨',
      en: 'The most evidence-backed stress relief—plus physical health benefits.',
      ja: '科学的に裏付けの強い解消法。健康も同時に得られる。',
      zhCN: '科学证据最扎实的解压法，同时改善身体健康。',
      zhTW: '科學證據最紮實的解壓法，同時改善身體健康。',
      vi: 'Cách xả stress được kiểm chứng mạnh nhất, lại tốt cho sức khỏe.',
      id: 'Cara paling terbukti secara ilmiah, sekaligus menyehatkan tubuh.',
    }),
    caution: T({
      ko: '운동을 못 하는 상황에서 다른 해소 수단이 없으면 스트레스가 쌓임',
      en: 'If you can’t exercise and have no backup method, stress accumulates fast.',
      ja: '運動できない状況で代替手段がないとストレスが溜まりやすい。',
      zhCN: '运动受限又没有替代方案时，压力会越堆越多。',
      zhTW: '運動受限又沒有替代方案時，壓力會越堆越多。',
      vi: 'Khi không thể vận động mà không có phương án thay thế, stress dễ tích tụ.',
      id: 'Saat tidak bisa olahraga tanpa alternatif, stres mudah menumpuk.',
    }),
    routineText: T({
      ko: ['아침 20분 러닝 또는 저녁 30분 헬스를 루틴으로 고정', '회사에서 힘든 날은 점심 산책 10분으로 즉시 해소', '운동 불가 상황에서는 계단 오르기·스트레칭으로 대체', '주 1회 이상 야외 활동으로 자연 노출 시간 확보', '운동 후 충분한 단백질 섭취로 회복력 극대화'].join('\n'),
      en: ['Lock in 20 min morning run or 30 min evening workout', 'On rough days, take a 10 min lunch walk to reset fast', 'If you can’t work out, substitute stairs or stretching', 'Get nature exposure at least once a week', 'Support recovery with enough protein after exercise'].join('\n'),
      ja: ['朝20分ラン or 夜30分ジムを固定ルーティンに', 'しんどい日は昼に10分散歩で即リセット', '運動不可なら階段・ストレッチで代替', '週1回以上は屋外で自然に触れる', '運動後はタンパク質で回復力を底上げ'].join('\n'),
      zhCN: ['固定：早上20分钟跑步或晚上30分钟训练', '难熬的日子：午休散步10分钟快速卸压', '运动受限：用爬楼/拉伸替代', '每周至少一次户外自然暴露', '运动后补充足量蛋白提升恢复'].join('\n'),
      zhTW: ['固定：早上20分鐘跑步或晚上30分鐘訓練', '難熬的日子：午休散步10分鐘快速卸壓', '運動受限：用爬樓/拉伸替代', '每週至少一次戶外自然暴露', '運動後補充足量蛋白提升恢復'].join('\n'),
      vi: ['Cố định: chạy 20 phút buổi sáng hoặc tập 30 phút buổi tối', 'Ngày căng: đi bộ 10 phút giờ trưa để xả ngay', 'Không tập được: thay bằng leo cầu thang/giãn cơ', 'Ít nhất 1 lần/tuần ra ngoài tiếp xúc thiên nhiên', 'Sau tập bổ sung đủ protein để hồi phục tốt hơn'].join('\n'),
      id: ['Kunci rutinitas: lari 20 menit pagi atau gym 30 menit malam', 'Hari berat: jalan 10 menit saat makan siang untuk reset cepat', 'Tidak bisa olahraga: ganti dengan naik tangga/peregangan', 'Minimal 1x/minggu terpapar alam di luar ruangan', 'Setelah olahraga, cukup protein untuk memaksimalkan pemulihan'].join('\n'),
    }),
    actionNow: T({
      ko: '지금 자리에서 일어나 5분 스트레칭. 몸을 깨우면 생각이 바뀝니다',
      en: 'Stand up and stretch for 5 minutes. Wake the body, and the mind follows.',
      ja: '今立ち上がって5分ストレッチ。体が目覚めると考えも変わる。',
      zhCN: '现在就起身拉伸5分钟。身体醒了，思路也会变。',
      zhTW: '現在就起身拉伸5分鐘。身體醒了，思路也會變。',
      vi: 'Đứng dậy và giãn cơ 5 phút ngay bây giờ. Đánh thức cơ thể thì tâm trí cũng đổi khác.',
      id: 'Bangun dan stretching 5 menit sekarang. Saat tubuh bangun, pikiran ikut berubah.',
    }),
    shareLine: T({
      ko: '스트레스 해소 유형: 신체 활동 해소형 🏃 운동 못 한 날 유독 힘들었던 이유 알았음... 처방전 저장함 → 너는 어떤 해소 유형이야?',
      en: 'Stress relief type: Active relief 🏃 Now I get why days without exercise hit harder… saving this routine. What’s your type?',
      ja: 'ストレス解消タイプ：身体活動型 🏃 運動できない日がしんどい理由わかった…処方箋保存。あなたはどのタイプ？',
      zhCN: '解压类型：运动释放型 🏃 终于懂了为什么不运动的日子更难熬…先把处方存了。你是哪一型？',
      zhTW: '解壓類型：運動釋放型 🏃 終於懂了為什麼不運動的日子更難熬…先把處方存了。你是哪一型？',
      vi: 'Kiểu xả stress: Vận động 🏃 Giờ thì hiểu vì sao ngày không tập lại mệt hơn… lưu “đơn thuốc” này. Bạn thuộc kiểu nào?',
      id: 'Tipe pelegaan stres: Aktivitas 🏃 Pantas hari tanpa olahraga terasa lebih berat… simpan resepnya dulu. Kamu tipe yang mana?',
    }),
  },
  {
    type: 'Type2',
    emoji: '🌿',
    title: T({
      ko: '고요함으로 충전하는, 독립 충전 내향형',
      en: 'Recharge in Silence: Solo Recharge Introvert',
      ja: '静けさで充電する、独立チャージ内向型',
      zhCN: '用安静充电：独处充能内向型',
      zhTW: '用安靜充電：獨處充能內向型',
      vi: 'Nạp lại bằng tĩnh lặng: Kiểu hướng nội tự sạc',
      id: 'Isi ulang lewat hening: Introvert pengisi daya mandiri',
    }),
    scoreBand: T({
      ko: '총점 6~11점 구간',
      en: 'Total score: 6–11',
      ja: '合計 6〜11点',
      zhCN: '总分 6–11',
      zhTW: '總分 6–11',
      vi: 'Tổng điểm: 6–11',
      id: 'Skor total: 6–11',
    }),
    tagLine: T({
      ko: '스트레스 해소 유형: 혼자 있어야 진짜 회복이 되는 사람',
      en: 'Relief type: You truly recover only when you’re alone.',
      ja: '解消タイプ：一人でこそ本当に回復できる人。',
      zhCN: '解压类型：必须独处，才算真正恢复。',
      zhTW: '解壓類型：必須獨處，才算真正恢復。',
      vi: 'Kiểu giải tỏa: Phải ở một mình thì mới hồi phục thật sự.',
      id: 'Tipe: Harus sendirian agar benar-benar pulih.',
    }),
    hookLine: T({
      ko: '"당신에게 회복은 혼자만의 시간입니다. 아무것도 하지 않아도 되는 공간이 있어야 살아납니다."',
      en: '"Recovery for you is alone time. You come back to life when you have space to do nothing."',
      ja: '「あなたの回復は一人時間。何もしなくていい空間があると生き返る。」',
      zhCN: '“你的恢复是独处时间。有一个可以什么都不做的空间，你才会活过来。”',
      zhTW: '「你的恢復是獨處時間。有一個可以什麼都不做的空間，你才會活過來。」',
      vi: '“Hồi phục với bạn là thời gian một mình. Có không gian được phép không làm gì, bạn mới sống lại.”',
      id: '"Pemulihanmu adalah waktu sendiri. Kamu hidup lagi saat punya ruang untuk tidak melakukan apa-apa."',
    }),
    description: T({
      ko: '사람을 만나거나 자극이 많은 환경에 오래 있으면 에너지가 소진되고, 혼자 조용히 있는 시간이 있어야 진짜 충전이 됩니다. 타인과의 시간이 즐겁더라도 그 후에는 반드시 혼자만의 회복 시간이 필요한 타입입니다.',
      en: 'When you spend too long in stimulating environments or with people, your energy drains. Quiet alone time is how you truly recharge. Even after fun social time, you still need a solo recovery window.',
      ja: '人に会ったり刺激の多い環境に長くいるとエネルギーが消耗し、静かな一人時間がないと本当に充電できません。楽しい時間の後でも、必ず一人回復タイムが必要なタイプです。',
      zhCN: '在社交或高刺激环境里待久了能量会被耗空，你需要安静的独处才能真正充电。就算聚会很开心，结束后也一定要留出独自恢复时间。',
      zhTW: '在社交或高刺激環境裡待久了能量會被耗空，你需要安靜的獨處才能真正充電。就算聚會很開心，結束後也一定要留出獨自恢復時間。',
      vi: 'Ở môi trường nhiều kích thích hay gặp người quá lâu sẽ rút cạn năng lượng của bạn; bạn cần khoảng lặng một mình để sạc lại. Dù thời gian với người khác có vui, sau đó bạn vẫn cần thời gian hồi phục riêng.',
      id: 'Terlalu lama di lingkungan ramai/menstimulasi atau bersama orang akan menguras energimu. Kamu butuh waktu tenang sendirian untuk benar-benar terisi. Bahkan setelah kumpul yang seru, kamu tetap perlu jeda pemulihan sendiri.',
    }),
    mechanism: T({
      ko: '외부 자극 차단 → 신경계 안정 → 내면 정리 → 에너지 회복',
      en: 'Block external stimuli → calm nervous system → inner整理 → restore energy',
      ja: '外部刺激遮断 → 神経系安定 → 内面整理 → エネルギー回復',
      zhCN: '切断外界刺激 → 神经系统稳定 → 内在整理 → 能量恢复',
      zhTW: '切斷外界刺激 → 神經系統穩定 → 內在整理 → 能量恢復',
      vi: 'Giảm kích thích bên ngoài → hệ thần kinh ổn định → sắp xếp nội tâm → hồi năng lượng',
      id: 'Memutus stimulus luar → menenangkan sistem saraf → merapikan batin → pulih energi',
    }),
    strength: T({
      ko: '혼자 있는 시간을 불편하지 않게 보낼 수 있는 내적 자원이 풍부함',
      en: 'Rich inner resources—you’re comfortable spending time alone.',
      ja: '一人時間を心地よく過ごせる内的資源が豊富。',
      zhCN: '内在资源充足，能自在地独处。',
      zhTW: '內在資源充足，能自在地獨處。',
      vi: 'Nội lực dồi dào—bạn không thấy khó chịu khi ở một mình.',
      id: 'Sumber daya batin kuat—kamu nyaman sendirian.',
    }),
    caution: T({
      ko: '혼자 있는 시간이 없으면 과민해지고, 너무 오래 고립되면 우울감이 올 수 있음',
      en: 'Without alone time you get irritable; too much isolation for too long can bring low mood.',
      ja: '一人時間がないと過敏に。逆に長すぎる孤立は気分の落ち込みにつながることも。',
      zhCN: '没有独处会变得敏感；长期过度孤立也可能带来低落。',
      zhTW: '沒有獨處會變得敏感；長期過度孤立也可能帶來低落。',
      vi: 'Thiếu thời gian một mình dễ cáu; nhưng cô lập quá lâu cũng có thể kéo mood xuống.',
      id: 'Tanpa waktu sendiri kamu mudah sensitif; tapi terlalu lama mengisolasi diri juga bisa bikin mood turun.',
    }),
    routineText: T({
      ko: ['퇴근 후 1시간은 완전히 혼자만의 시간으로 확보하기', '독서·명상·일기·조용한 음악 감상을 저녁 루틴으로 설정', '주말 반나절은 혼자 보내는 시간으로 계획하기', '카페나 도서관 같은 조용한 공공장소에서 혼자 시간 보내기', '스마트폰 알림 끄고 디지털 디톡스 시간 만들기'].join('\n'),
      en: ['Reserve one full hour after work for alone time', 'Set an evening routine: reading, meditation, journaling, calm music', 'Plan a half-day solo block on weekends', 'Spend solo time in quiet public places like cafés/libraries', 'Turn off notifications and do a small digital detox'].join('\n'),
      ja: ['退勤後の1時間は完全に一人時間を確保', '読書・瞑想・日記・静かな音楽を夜ルーティンに', '週末は半日を一人時間として計画', 'カフェや図書館など静かな公共空間で一人時間', '通知を切ってデジタルデトックス'].join('\n'),
      zhCN: ['下班后固定1小时“纯独处时间”', '晚间例行：读书/冥想/写日记/听安静音乐', '周末安排半天独处', '在咖啡馆/图书馆等安静公共场所独处', '关掉通知，做一段数字排毒'].join('\n'),
      zhTW: ['下班後固定1小時「純獨處時間」', '晚間例行：讀書/冥想/寫日記/聽安靜音樂', '週末安排半天獨處', '在咖啡館/圖書館等安靜公共場所獨處', '關掉通知，做一段數位排毒'].join('\n'),
      vi: ['Dành trọn 1 giờ sau khi tan làm cho “thời gian một mình”', 'Tạo routine tối: đọc sách/thiền/viết nhật ký/nghe nhạc nhẹ', 'Cuối tuần lên kế hoạch nửa ngày ở một mình', 'Ở một mình tại nơi công cộng yên tĩnh như quán cà phê/thư viện', 'Tắt thông báo và làm digital detox'].join('\n'),
      id: ['Sisihkan 1 jam setelah pulang kerja untuk waktu sendiri', 'Rutinitas malam: membaca/meditasi/jurnal/musik tenang', 'Akhir pekan: rencanakan setengah hari untuk sendiri', 'Habiskan waktu sendiri di tempat publik yang tenang seperti kafe/perpustakaan', 'Matikan notifikasi dan lakukan digital detox'].join('\n'),
    }),
    actionNow: T({
      ko: '폰 알림을 30분 끄고 조용히 창밖을 바라보기. 아무것도 안 해도 됩니다',
      en: 'Turn off notifications for 30 minutes and quietly look out the window. Doing nothing is allowed.',
      ja: '通知を30分オフにして静かに窓の外を見る。何もしなくて大丈夫。',
      zhCN: '把手机通知关30分钟，安静看向窗外。什么都不做也可以。',
      zhTW: '把手機通知關30分鐘，安靜看向窗外。什麼都不做也可以。',
      vi: 'Tắt thông báo 30 phút và lặng nhìn ra ngoài cửa sổ. Không làm gì cũng được.',
      id: 'Matikan notifikasi 30 menit dan tatap keluar jendela dengan tenang. Tidak melakukan apa-apa itu boleh.',
    }),
    shareLine: T({
      ko: '스트레스 해소 유형: 독립 충전 내향형 🌿 혼자 있어야 회복되는 유형 맞음... 억지로 사람 만났다 더 지친 거 이래서였구나 → 너는 어떤 해소 유형이야?',
      en: 'Stress relief type: Solo recharge introvert 🌿 So that’s why forcing myself to socialize drained me more… What’s your type?',
      ja: 'ストレス解消タイプ：独立チャージ内向型 🌿 無理に人に会うと余計疲れる理由これか…あなたはどのタイプ？',
      zhCN: '解压类型：独处充能内向型 🌿 原来硬社交会更累是因为这个…你是哪一型？',
      zhTW: '解壓類型：獨處充能內向型 🌿 原來硬社交會更累是因為這個…你是哪一型？',
      vi: 'Kiểu xả stress: Hướng nội tự sạc 🌿 Thảo nào gặp người “cố” lại mệt hơn… Bạn thuộc kiểu nào?',
      id: 'Tipe pelegaan stres: Introvert pengisi daya mandiri 🌿 Pantas ketemu orang “dipaksa” malah makin capek… Kamu tipe apa?',
    }),
  },
  {
    type: 'Type3',
    emoji: '🫂',
    title: T({
      ko: '연결로 회복하는, 사회적 에너지 해소형',
      en: 'Recover Through Connection: Social Energy Relief',
      ja: 'つながりで回復する、社会的エネルギー解消型',
      zhCN: '靠连接恢复：社交能量释放型',
      zhTW: '靠連結恢復：社交能量釋放型',
      vi: 'Hồi phục nhờ kết nối: Kiểu giải tỏa bằng xã hội',
      id: 'Pulih lewat koneksi: Tipe pelepas stres sosial',
    }),
    scoreBand: T({
      ko: '총점 12~19점 구간',
      en: 'Total score: 12–19',
      ja: '合計 12〜19点',
      zhCN: '总分 12–19',
      zhTW: '總分 12–19',
      vi: 'Tổng điểm: 12–19',
      id: 'Skor total: 12–19',
    }),
    tagLine: T({
      ko: '스트레스 해소 유형: 말하고 나눠야 진짜 풀리는 사람',
      en: 'Relief type: You feel better when you talk and share.',
      ja: '解消タイプ：話して分かち合ってこそ楽になる人。',
      zhCN: '解压类型：说出来、分享出来，才会真的松开。',
      zhTW: '解壓類型：說出來、分享出來，才會真的鬆開。',
      vi: 'Kiểu giải tỏa: Phải nói và chia sẻ thì mới nhẹ.',
      id: 'Tipe: Harus ngomong dan berbagi biar benar-benar lega.',
    }),
    hookLine: T({
      ko: '"당신에게 회복은 연결입니다. 들어주는 사람 한 명이 있으면 절반은 해결됩니다."',
      en: '"Recovery for you is connection. One person who listens solves half of it."',
      ja: '「あなたの回復はつながり。聞いてくれる人が一人いれば半分は解決。」',
      zhCN: '“你的恢复来自连接。有一个愿意听你说的人，就解决了一半。”',
      zhTW: '「你的恢復來自連結。有一個願意聽你說的人，就解決了一半。」',
      vi: '“Hồi phục với bạn là kết nối. Chỉ cần một người chịu lắng nghe là giải quyết được một nửa.”',
      id: '"Pemulihanmu adalah koneksi. Satu orang yang mau mendengarkan sudah menyelesaikan setengahnya."',
    }),
    description: T({
      ko: '혼자 삭이면 오히려 더 오래 힘들고, 친한 사람에게 털어놓고 나면 씻은 듯이 가벼워지는 타입입니다. 이야기를 나누면서 생각이 정리되고, 함께 웃는 과정에서 스트레스가 해소됩니다. 인간관계가 스트레스의 원인이기도 하지만 동시에 가장 강력한 회복 자원이기도 합니다.',
      en: 'Bottling it up makes it last longer, but talking to someone close makes you feel instantly lighter. You organize your thoughts through conversation, and laughter dissolves stress. Relationships can be stressors—but also your strongest recovery resource.',
      ja: '一人で抱えると長引きますが、親しい人に話すと洗い流したように軽くなるタイプ。会話で思考が整理され、一緒に笑う過程でストレスがほどけます。人間関係はストレス源にもなりますが、同時に最強の回復資源でもあります。',
      zhCN: '自己憋着反而会更久更难受，但和亲近的人倾诉后会瞬间轻很多。你在对话中整理思路，在一起大笑的过程中释放压力。关系既可能带来压力，也可能是你最强的恢复资源。',
      zhTW: '自己憋著反而會更久更難受，但和親近的人傾訴後會瞬間輕很多。你在對話中整理思路，在一起大笑的過程中釋放壓力。關係既可能帶來壓力，也可能是你最強的恢復資源。',
      vi: 'Tự chịu một mình khiến bạn khổ lâu hơn, nhưng nói ra với người thân thì nhẹ hẳn. Bạn sắp xếp suy nghĩ qua trò chuyện và giải tỏa stress bằng tiếng cười. Quan hệ có thể là nguồn stress, nhưng cũng là nguồn hồi phục mạnh nhất.',
      id: 'Memendam sendiri membuatnya lebih lama berat, tapi curhat ke orang dekat bikin lega seperti habis “dibersihkan”. Kamu merapikan pikiran lewat ngobrol, dan tawa melepaskan stres. Relasi bisa jadi sumber stres, tapi juga sumber pemulihan terkuatmu.',
    }),
    mechanism: T({
      ko: '언어화 → 감정 정리 → 공감·연결 경험 → 옥시토신 분비 → 안정감',
      en: 'Put into words → process emotions → feel empathy/connection → oxytocin → calm',
      ja: '言語化 → 感情整理 → 共感・つながり → オキシトシン → 安心',
      zhCN: '语言化 → 情绪整理 → 共情/连接 → 催产素 → 安稳',
      zhTW: '語言化 → 情緒整理 → 共情/連結 → 催產素 → 安穩',
      vi: 'Nói ra → sắp xếp cảm xúc → cảm nhận đồng cảm/kết nối → oxytocin → an tâm',
      id: 'Diceritakan → emosi tertata → empati/koneksi → oksitosin → rasa aman',
    }),
    strength: T({
      ko: '관계 속에서 회복력이 매우 빠름. 공감 능력이 높아 상대도 편하게 만듦',
      en: 'You recover fast in relationships. High empathy also makes others feel at ease.',
      ja: '関係の中で回復が速い。共感力が高く相手も安心する。',
      zhCN: '在关系里恢复很快；共情力高，也能让对方放松。',
      zhTW: '在關係裡恢復很快；共情力高，也能讓對方放鬆。',
      vi: 'Hồi phục rất nhanh trong mối quan hệ; bạn đồng cảm tốt nên người khác cũng thấy dễ chịu.',
      id: 'Pemulihanmu cepat dalam relasi; empati tinggi bikin orang lain juga nyaman.',
    }),
    caution: T({
      ko: '들어줄 사람이 없거나 혼자 있어야 하는 상황에서 회복이 더딤',
      en: 'Recovery slows when there’s no listener or you must be alone.',
      ja: '聞いてくれる人がいない／一人でいなきゃいけないと回復が遅い。',
      zhCN: '没人愿意听、或不得不独处时，恢复会变慢。',
      zhTW: '沒人願意聽、或不得不獨處時，恢復會變慢。',
      vi: 'Không có người nghe hoặc phải ở một mình thì hồi phục chậm hơn.',
      id: 'Kalau tidak ada yang mendengarkan atau harus sendiri, pulihnya lebih lambat.',
    }),
    routineText: T({
      ko: [
        '힘든 날에는 친구에게 먼저 연락하기. "요즘 힘들어. 잠깐 통화할 수 있어?" 한마디면 충분',
        '정기적인 친구 모임·수다 시간 캘린더에 고정하기',
        '직접 만나기 어렵다면 음성통화로 대체. 문자보다 목소리 연결이 훨씬 효과적',
        '혼자 있어야 하는 상황에서는 일기·음성 메모로 감정 언어화 연습',
        '커뮤니티·동호회 활동으로 연결 채널 다양하게 확보하기',
      ].join('\n'),
      en: [
        'On hard days, reach out first: “I’ve been struggling—can we talk for a minute?”',
        'Put regular friend catch-ups on your calendar',
        'If meeting is hard, do voice calls—hearing a voice helps more than texts',
        'When you must be alone, journal or record a voice memo to verbalize feelings',
        'Build multiple connection channels via communities/clubs',
      ].join('\n'),
      ja: [
        'つらい日は先に連絡。「最近しんどい、ちょっと通話できる？」一言でOK',
        '定期的な友達との時間をカレンダー固定',
        '会えないなら音声通話に。文字より声のつながりが効く',
        '一人の状況では日記やボイスメモで感情を言語化',
        'コミュニティ・サークルでつながりの窓口を増やす',
      ].join('\n'),
      zhCN: [
        '难熬的日子先联系朋友：“最近有点累，能通话几分钟吗？”一句就够',
        '把固定的朋友聚会/聊天时间写进日历',
        '不方便见面就语音通话：比文字更有“连接感”',
        '必须独处时，用日记/语音备忘把情绪说出来',
        '参加社群/兴趣小组，增加连接渠道',
      ].join('\n'),
      zhTW: [
        '難熬的日子先聯絡朋友：「最近有點累，能通話幾分鐘嗎？」一句就夠',
        '把固定的朋友聚會/聊天時間寫進日曆',
        '不方便見面就語音通話：比文字更有「連結感」',
        '必須獨處時，用日記/語音備忘把情緒說出來',
        '參加社群/興趣小組，增加連結渠道',
      ].join('\n'),
      vi: [
        'Ngày mệt, chủ động nhắn: “Dạo này mình hơi đuối, nói chuyện chút được không?”',
        'Cố định lịch gặp/gọi bạn bè định kỳ',
        'Không gặp được thì gọi thoại—giọng nói hiệu quả hơn nhắn tin',
        'Khi phải ở một mình, viết nhật ký hoặc ghi âm để “nói ra” cảm xúc',
        'Tham gia cộng đồng/CLB để đa dạng kênh kết nối',
      ].join('\n'),
      id: [
        'Hari berat, hubungi dulu: “Akhir-akhir ini berat, bisa telepon sebentar?”',
        'Jadwalkan rutin waktu ketemu/ngobrol dengan teman',
        'Kalau sulit bertemu, lakukan voice call—lebih efektif daripada chat',
        'Saat harus sendiri, tulis jurnal atau rekam voice memo untuk mengungkapkan emosi',
        'Ikut komunitas/klub supaya saluran koneksi lebih beragam',
      ].join('\n'),
    }),
    actionNow: T({
      ko: '가장 편한 친구에게 "요즘 어때?" 메시지 보내기. 상대도 당신을 기다리고 있을 수 있습니다',
      en: 'Message your easiest friend: “How have you been lately?” They may be waiting for you too.',
      ja: '一番気楽な友達に「最近どう？」と送る。相手もあなたを待ってるかも。',
      zhCN: '给最舒服的朋友发一句“最近怎么样？”对方也可能在等你。',
      zhTW: '給最舒服的朋友發一句「最近怎麼樣？」對方也可能在等你。',
      vi: 'Nhắn cho người bạn thoải mái nhất: “Dạo này sao rồi?” Có khi họ cũng đang chờ bạn.',
      id: 'Kirim pesan ke teman paling nyaman: “Akhir-akhir ini gimana?” Bisa jadi dia juga menunggumu.',
    }),
    shareLine: T({
      ko: '스트레스 해소 유형: 사회적 에너지 해소형 🫂 말해야 풀리는 유형... 혼자 삭이다 더 힘들었던 거 이래서 → 너는 어떤 해소 유형이야?',
      en: 'Stress relief type: Social energy 🫂 Now I get why bottling it up made it worse… What’s your type?',
      ja: 'ストレス解消タイプ：社会的エネルギー型 🫂 一人で抱えるほどつらくなる理由これだ…あなたはどのタイプ？',
      zhCN: '解压类型：社交能量释放型 🫂 原来憋着更难受是因为这个…你是哪一型？',
      zhTW: '解壓類型：社交能量釋放型 🫂 原來憋著更難受是因為這個…你是哪一型？',
      vi: 'Kiểu xả stress: Năng lượng xã hội 🫂 Thảo nào càng tự chịu càng mệt… Bạn thuộc kiểu nào?',
      id: 'Tipe pelegaan stres: Energi sosial 🫂 Pantas dipendam malah makin berat… Kamu tipe apa?',
    }),
  },
  {
    type: 'Type4',
    emoji: '🍜',
    title: T({
      ko: '즐거움으로 버티는, 보상 추구 도파민형',
      en: 'Reward-Seeking Dopamine Type',
      ja: '楽しみで持ちこたえる、ご褒美ドーパミン型',
      zhCN: '靠小确幸续命：奖励型多巴胺',
      zhTW: '靠小確幸續命：獎勵型多巴胺',
      vi: 'Kiểu “tự thưởng” dopamine',
      id: 'Tipe dopamin pencari hadiah',
    }),
    scoreBand: T({
      ko: '총점 20~27점 구간',
      en: 'Total score: 20–27',
      ja: '合計 20〜27点',
      zhCN: '总分 20–27',
      zhTW: '總分 20–27',
      vi: 'Tổng điểm: 20–27',
      id: 'Skor total: 20–27',
    }),
    tagLine: T({
      ko: '스트레스 해소 유형: 작은 즐거움이 가장 강력한 회복제인 사람',
      en: 'Relief type: Small pleasures are your strongest medicine.',
      ja: '解消タイプ：小さな楽しみが最強の回復薬。',
      zhCN: '解压类型：小快乐就是最强恢复剂。',
      zhTW: '解壓類型：小快樂就是最強恢復劑。',
      vi: 'Kiểu giải tỏa: Niềm vui nhỏ là “thuốc” mạnh nhất.',
      id: 'Tipe: Kesenangan kecil adalah obat pemulihan terkuat.',
    }),
    hookLine: T({
      ko: '"당신에게 회복은 보상입니다. 맛있는 것 하나, 좋아하는 것 하나가 하루를 살게 합니다."',
      en: '"Recovery for you is reward. One tasty thing or one favorite thing keeps the day going."',
      ja: '「あなたの回復はご褒美。美味しいもの一つ、好きなもの一つが一日を救う。」',
      zhCN: '“你的恢复来自奖励。一口好吃的、一集喜欢的内容，就能把一天救回来。”',
      zhTW: '「你的恢復來自獎勵。一口好吃的、一集喜歡的內容，就能把一天救回來。」',
      vi: '“Hồi phục với bạn là tự thưởng. Một món ngon hay một điều mình thích cũng đủ cứu cả ngày.”',
      id: '"Pemulihanmu adalah hadiah. Satu makanan enak atau satu hal favorit bisa menyelamatkan harimu."',
    }),
    description: T({
      ko: '큰 무언가보다 일상 속 작은 즐거움이 스트레스를 효과적으로 해소합니다. 맛있는 음식·좋아하는 드라마·향기로운 목욕·소소한 쇼핑처럼 자신을 위한 작은 보상이 에너지를 회복시키는 타입입니다. 이 즐거움이 없으면 의욕이 떨어지고 무기력해지는 경향이 있습니다.',
      en: 'Small everyday pleasures relieve your stress better than “big” things. Good food, a favorite show, a scented bath, a small purchase—tiny rewards restore your energy. Without them, motivation can drop and you may feel flat.',
      ja: '大きな何かより、日常の小さな楽しみでストレスがよく抜けるタイプ。美味しい食事、好きなドラマ、香りの入浴、ちょっとした買い物などの「自分へのご褒美」で回復します。楽しみがないと意欲が落ち、無気力になりがち。',
      zhCN: '比起“做一件大事”，你更靠日常小快乐有效解压：好吃的、喜欢的剧、香氛泡澡、小小购物，都能给你回电。缺少这些快乐时，你容易失去动力、变得无力。',
      zhTW: '比起「做一件大事」，你更靠日常小快樂有效解壓：好吃的、喜歡的劇、香氛泡澡、小小購物，都能給你回電。缺少這些快樂時，你容易失去動力、變得無力。',
      vi: 'Bạn xả stress tốt nhất bằng niềm vui nhỏ hằng ngày hơn là “cú hích lớn”. Đồ ăn ngon, phim yêu thích, tắm thơm, mua sắm nhỏ… những phần thưởng nhỏ nạp lại năng lượng cho bạn. Thiếu chúng, bạn dễ tụt động lực và uể oải.',
      id: 'Kamu lebih efektif melepas stres lewat kebahagiaan kecil sehari-hari daripada hal besar. Makanan enak, tontonan favorit, mandi aromaterapi, belanja kecil—hadiah kecil mengisi ulang energimu. Tanpa itu, motivasi turun dan kamu mudah lesu.',
    }),
    mechanism: T({
      ko: '즐거운 자극 → 도파민 분비 → 기분 전환 → 회복 에너지 확보',
      en: 'Pleasant stimulus → dopamine → mood shift → recovery energy',
      ja: '快刺激 → ドーパミン → 気分転換 → 回復エネルギー',
      zhCN: '愉快刺激 → 多巴胺 → 情绪切换 → 获得恢复能量',
      zhTW: '愉快刺激 → 多巴胺 → 情緒切換 → 獲得恢復能量',
      vi: 'Kích thích dễ chịu → dopamine → đổi mood → nạp năng lượng',
      id: 'Stimulus menyenangkan → dopamin → mood bergeser → energi pulih',
    }),
    strength: T({
      ko: '일상 속 소소한 행복을 잘 발견하는 능력. 작은 것으로도 회복됨',
      en: 'You’re good at spotting small happiness—and it works for you.',
      ja: '日常の小さな幸せを見つけるのが上手。小さくても回復できる。',
      zhCN: '很会发现小幸福，小的也能让你恢复。',
      zhTW: '很會發現小幸福，小的也能讓你恢復。',
      vi: 'Bạn giỏi tìm niềm vui nhỏ, và chỉ vậy cũng đủ hồi phục.',
      id: 'Kamu jago menemukan kebahagiaan kecil—dan itu sudah cukup untuk pulih.',
    }),
    caution: T({
      ko: '보상이 과식·충동구매·과도한 소비로 이어지지 않도록 주의',
      en: 'Watch that rewards don’t turn into overeating, impulse buys, or overspending.',
      ja: 'ご褒美が過食・衝動買い・浪費に繋がりすぎないよう注意。',
      zhCN: '注意别让奖励变成暴食/冲动消费/过度花钱。',
      zhTW: '注意別讓獎勵變成暴食/衝動消費/過度花錢。',
      vi: 'Cẩn thận để “tự thưởng” không thành ăn quá đà, mua bốc đồng hay tiêu quá tay.',
      id: 'Hati-hati agar self-reward tidak berubah jadi makan berlebihan, belanja impulsif, atau boros.',
    }),
    routineText: T({
      ko: ['매주 한 번 나를 위한 작은 보상 이벤트 미리 계획해두기', '힘든 날을 버틸 수 있는 "오늘의 작은 기대" 하나씩 만들기', '음식 보상을 할 때는 건강하면서도 맛있는 것으로 선택하기', '넷플릭스·유튜브 시청 시 시간 제한 설정으로 과소비 방지', '취미·창작 활동처럼 지속 가능한 즐거움 채널 하나 만들기'].join('\n'),
      en: ['Plan one small self-reward event each week', 'Create one “small thing to look forward to” for tough days', 'Choose rewards that are tasty but also reasonably healthy', 'Set time limits for Netflix/YouTube to avoid overconsumption', 'Build a sustainable joy channel like hobbies/creative activities'].join('\n'),
      ja: ['週1回、自分への小さなご褒美イベントを先に計画', 'つらい日を支える「今日の小さな楽しみ」を作る', '食のご褒美は美味しくて健康的な選択に', 'Netflix/YouTubeは時間制限で見過ぎ防止', '趣味や創作など持続可能な楽しみチャンネルを1つ作る'].join('\n'),
      zhCN: ['每周提前安排一次“小奖励”', '给难熬的日子准备一个“今天的小期待”', '用食物奖励时，选好吃又相对健康的', '追剧/刷视频设定时间限制，避免过量', '培养一个可持续的快乐渠道：兴趣/创作等'].join('\n'),
      zhTW: ['每週提前安排一次「小獎勵」', '給難熬的日子準備一個「今天的小期待」', '用食物獎勵時，選好吃又相對健康的', '追劇/刷影片設定時間限制，避免過量', '培養一個可持續的快樂渠道：興趣/創作等'].join('\n'),
      vi: ['Mỗi tuần lên kế hoạch một “sự kiện tự thưởng” nhỏ', 'Tạo một “điều nhỏ để mong chờ” cho ngày khó', 'Tự thưởng bằng đồ ăn thì chọn vừa ngon vừa tương đối lành mạnh', 'Giới hạn thời gian Netflix/YouTube để tránh “quá liều”', 'Tạo một kênh niềm vui bền vững như hobby/hoạt động sáng tạo'].join('\n'),
      id: ['Rencanakan satu event self-reward kecil tiap minggu', 'Buat satu “hal kecil untuk ditunggu” di hari berat', 'Kalau hadiah berupa makanan, pilih yang enak tapi tetap cukup sehat', 'Beri batas waktu Netflix/YouTube agar tidak kebablasan', 'Bangun satu saluran kebahagiaan yang berkelanjutan: hobi/kreasi'].join('\n'),
    }),
    actionNow: T({
      ko: '오늘 퇴근 후 먹고 싶었던 것 하나 미리 정해두기. 기대가 생기면 하루가 버텨집니다',
      en: 'Pick one thing you want after work today. Anticipation helps you get through the day.',
      ja: '今日の退勤後に食べたいものを一つ決める。楽しみがあると一日を乗り切れる。',
      zhCN: '先决定今天下班后要吃/做的一个小奖励。有期待，今天就能撑过去。',
      zhTW: '先決定今天下班後要吃/做的一個小獎勵。有期待，今天就能撐過去。',
      vi: 'Chọn trước một thứ bạn muốn ăn/làm sau khi tan làm hôm nay. Có mong chờ là bạn sẽ trụ được.',
      id: 'Tentukan satu hal yang kamu mau setelah pulang hari ini. Punya sesuatu untuk ditunggu bikin kamu kuat.',
    }),
    shareLine: T({
      ko: '스트레스 해소 유형: 보상 추구 도파민형 🍜 작은 즐거움이 회복제라는 거 맞음 ㅋㅋ 오늘 뭐 먹을지 정해야 버팀 → 너는 어떤 해소 유형이야?',
      en: 'Stress relief type: Reward-seeking dopamine 🍜 Small pleasures really are medicine… what should I eat today? What’s your type?',
      ja: 'ストレス解消タイプ：ご褒美ドーパミン型 🍜 小さな楽しみが回復剤なのわかるw 今日何食べよ…あなたはどのタイプ？',
      zhCN: '解压类型：奖励型多巴胺 🍜 小快乐真的是恢复剂哈哈…今天吃啥得先定。你是哪一型？',
      zhTW: '解壓類型：獎勵型多巴胺 🍜 小快樂真的是恢復劑哈哈…今天吃啥得先定。你是哪一型？',
      vi: 'Kiểu xả stress: Dopamine tự thưởng 🍜 Đúng là niềm vui nhỏ là thuốc… hôm nay ăn gì đây? Bạn thuộc kiểu nào?',
      id: 'Tipe pelegaan stres: Dopamin self-reward 🍜 Bener sih, kebahagiaan kecil itu obat… hari ini makan apa ya? Kamu tipe apa?',
    }),
  },
  {
    type: 'Type5',
    emoji: '🎨',
    title: T({
      ko: '감성으로 정화하는, 창작 감성 몰입형',
      en: 'Creative Immersion Type',
      ja: '感性で浄化する、創作没入型',
      zhCN: '用感性净化：创作沉浸型',
      zhTW: '用感性淨化：創作沉浸型',
      vi: 'Kiểu “đắm” vào sáng tạo',
      id: 'Tipe larut dalam kreativitas',
    }),
    scoreBand: T({
      ko: '총점 28~33점 구간',
      en: 'Total score: 28–33',
      ja: '合計 28〜33点',
      zhCN: '总分 28–33',
      zhTW: '總分 28–33',
      vi: 'Tổng điểm: 28–33',
      id: 'Skor total: 28–33',
    }),
    tagLine: T({
      ko: '스트레스 해소 유형: 감정을 표현하고 창작해야 진짜 풀리는 사람',
      en: 'Relief type: You feel relief when you express and create.',
      ja: '解消タイプ：表現・創作で本当にほどける人。',
      zhCN: '解压类型：表达与创作，才能真的松开。',
      zhTW: '解壓類型：表達與創作，才能真的鬆開。',
      vi: 'Kiểu giải tỏa: Phải biểu đạt và sáng tạo thì mới nhẹ.',
      id: 'Tipe: Harus mengekspresikan diri dan berkarya agar benar-benar lega.',
    }),
    hookLine: T({
      ko: '"당신에게 회복은 표현입니다. 감정이 밖으로 나와야 안이 비워집니다."',
      en: '"Recovery for you is expression. When emotions come out, the inside becomes lighter."',
      ja: '「あなたの回復は表現。感情が外に出ると中が空いていく。」',
      zhCN: '“你的恢复是表达。情绪出来了，内在才会腾空。”',
      zhTW: '「你的恢復是表達。情緒出來了，內在才會騰空。」',
      vi: '“Hồi phục với bạn là biểu đạt. Khi cảm xúc được đưa ra ngoài, bên trong mới nhẹ đi.”',
      id: '"Pemulihanmu adalah ekspresi. Saat emosi keluar, isi kepala jadi lebih lega."',
    }),
    description: T({
      ko: '음악·그림·글쓰기·사진·요리처럼 무언가를 만들거나 감성적인 콘텐츠에 깊이 몰입하는 과정에서 스트레스가 정화됩니다. 단순히 소비하는 것이 아니라 자신의 감정을 무언가로 표현하거나 예술적 자극을 통해 감정이 전환되는 타입입니다.',
      en: 'You’re cleansed by creating or deeply immersing in emotional content—music, drawing, writing, photography, cooking. It’s not just consuming; it’s expressing feelings or transforming them through artistic stimulus.',
      ja: '音楽・絵・文章・写真・料理など「作ること」や、感性に深く没入する過程でストレスが浄化されます。ただ消費するだけではなく、感情を形にしたり芸術刺激で感情が切り替わるタイプです。',
      zhCN: '你会在创作或深度沉浸于感性内容时被“净化”：音乐、绘画、写作、摄影、做饭。你不是单纯消费，而是把情绪表达出来，或在艺术刺激中完成情绪转换。',
      zhTW: '你會在創作或深度沉浸於感性內容時被「淨化」：音樂、繪畫、寫作、攝影、做飯。你不是單純消費，而是把情緒表達出來，或在藝術刺激中完成情緒轉換。',
      vi: 'Stress của bạn được “thanh lọc” khi tạo ra thứ gì đó hoặc đắm sâu vào nội dung giàu cảm xúc: nhạc, vẽ, viết, chụp ảnh, nấu ăn. Không chỉ tiêu thụ, bạn cần biểu đạt cảm xúc hoặc chuyển hóa chúng bằng kích thích nghệ thuật.',
      id: 'Stresmu “terbersihkan” saat kamu mencipta atau larut dalam konten emosional: musik, gambar, menulis, foto, memasak. Bukan sekadar konsumsi—kamu mengekspresikan emosi atau mengubahnya lewat rangsangan artistik.',
    }),
    mechanism: T({
      ko: '감정 → 창작·표현·몰입 → 감정 언어화·정화 → 내면 정리',
      en: 'Emotion → create/express/immerse → name & cleanse it → inner整理',
      ja: '感情 → 創作・表現・没入 → 言語化・浄化 → 内面整理',
      zhCN: '情绪 → 创作/表达/沉浸 → 语言化与净化 → 内在整理',
      zhTW: '情緒 → 創作/表達/沉浸 → 語言化與淨化 → 內在整理',
      vi: 'Cảm xúc → sáng tạo/biểu đạt/đắm chìm → gọi tên & thanh lọc → sắp xếp nội tâm',
      id: 'Emosi → berkarya/ekspresi/larut → menamai & membersihkan → merapikan batin',
    }),
    strength: T({
      ko: '자기 감정을 창작으로 승화하는 능력. 스트레스가 창의성의 원천이 됨',
      en: 'You can sublimate emotions into creativity—stress becomes fuel.',
      ja: '感情を創作に昇華できる。ストレスが創造性の源になる。',
      zhCN: '能把情绪升华为创作，压力反而成了创造力燃料。',
      zhTW: '能把情緒昇華為創作，壓力反而成了創造力燃料。',
      vi: 'Bạn có thể thăng hoa cảm xúc thành sáng tạo—stress thành “nhiên liệu”.',
      id: 'Kamu bisa mengubah emosi jadi karya—stres jadi bahan bakar kreativitas.',
    }),
    caution: T({
      ko: '창작할 환경이나 도구가 없으면 해소 수단이 없어져 막막해질 수 있음',
      en: 'Without a space or tools to create, you may feel stuck with no outlet.',
      ja: '創作環境や道具がないと、解消手段がなくて行き詰まりやすい。',
      zhCN: '缺少创作环境/工具时，容易觉得“没出口”。',
      zhTW: '缺少創作環境/工具時，容易覺得「沒出口」。',
      vi: 'Thiếu không gian/dụng cụ để sáng tạo có thể khiến bạn bế tắc vì không có lối xả.',
      id: 'Kalau tidak ada ruang/alat untuk berkarya, kamu bisa merasa buntu karena tak punya pelampiasan.',
    }),
    routineText: T({
      ko: ['매일 5분 자유 글쓰기. 떠오르는 것을 무엇이든 검열 없이 적기', '플레이리스트 만들기. 감정에 맞는 음악을 선별하는 것 자체가 치유', '스케치북·색연필 등 간단한 창작 도구 항상 가까이 두기', '감성 사진 찍기. 오늘 마음에 드는 것을 하나 포착하기', '요리·베이킹 등 결과물이 생기는 창작 활동 주 1회 시도'].join('\n'),
      en: ['5 minutes of free writing daily—no censoring', 'Make playlists; curating music to match emotions is healing', 'Keep simple tools (sketchbook, pencils) nearby', 'Take one “mood photo” of something you like today', 'Try one creative activity weekly with a tangible result (cooking/baking)'].join('\n'),
      ja: ['毎日5分のフリーライティング（検閲なし）', 'プレイリスト作り：感情に合う曲を選ぶ行為自体が癒し', 'スケッチブック・色鉛筆など簡単な道具を近くに置く', '感性写真：今日好きだと思ったものを1つ撮る', '料理・ベーキングなど成果物が残る創作を週1回'].join('\n'),
      zhCN: ['每天5分钟自由写作：想到什么写什么，不审查', '做歌单：按情绪挑歌本身就是疗愈', '随手放着简易工具：速写本/彩铅等', '拍一张“情绪照片”：今天喜欢的东西抓拍一下', '每周尝试一次有作品的创作：做饭/烘焙等'].join('\n'),
      zhTW: ['每天5分鐘自由寫作：想到什麼寫什麼，不審查', '做歌單：按情緒挑歌本身就是療癒', '隨手放著簡易工具：速寫本/彩鉛等', '拍一張「情緒照片」：今天喜歡的東西抓拍一下', '每週嘗試一次有作品的創作：做飯/烘焙等'].join('\n'),
      vi: ['Mỗi ngày 5 phút viết tự do—không kiểm duyệt', 'Tạo playlist; chọn nhạc đúng mood cũng là chữa lành', 'Luôn để gần dụng cụ đơn giản: sổ phác thảo, bút màu…', 'Chụp 1 tấm “ảnh cảm xúc” về thứ bạn thích hôm nay', 'Mỗi tuần thử 1 hoạt động sáng tạo có “thành phẩm”: nấu ăn/bánh…'].join('\n'),
      id: ['5 menit free writing tiap hari—tanpa sensor', 'Buat playlist; memilih musik sesuai emosi itu sendiri menyembuhkan', 'Sediakan alat sederhana (sketchbook, pensil warna) di dekatmu', 'Ambil satu “foto suasana” tentang hal yang kamu suka hari ini', 'Coba 1 aktivitas kreatif mingguan yang menghasilkan karya (masak/baking)'].join('\n'),
    }),
    actionNow: T({
      ko: '지금 기분을 한 문장으로 적어보기. 표현하면 감정이 정리됩니다',
      en: 'Write your current mood in one sentence. Expression organizes emotion.',
      ja: '今の気分を一文で書いてみる。表現すると感情が整理される。',
      zhCN: '把你现在的心情写成一句话。写出来，情绪就开始被整理。',
      zhTW: '把你現在的心情寫成一句話。寫出來，情緒就開始被整理。',
      vi: 'Viết tâm trạng hiện tại của bạn thành một câu. Biểu đạt giúp cảm xúc được sắp xếp.',
      id: 'Tulis perasaanmu sekarang dalam satu kalimat. Mengekspresikan diri membuat emosi lebih tertata.',
    }),
    shareLine: T({
      ko: '스트레스 해소 유형: 창작 감성 몰입형 🎨 표현해야 풀리는 유형... 이래서 음악 들을 때 제일 편했구나 → 처방전 저장해둠',
      en: 'Stress relief type: Creative immersion 🎨 So that’s why music feels safest… saving this routine.',
      ja: 'ストレス解消タイプ：創作没入型 🎨 表現しないとほどけない…音楽が一番楽な理由これ。処方箋保存。',
      zhCN: '解压类型：创作沉浸型 🎨 原来必须表达才会松开…怪不得听音乐最舒服。先存处方。',
      zhTW: '解壓類型：創作沉浸型 🎨 原來必須表達才會鬆開…怪不得聽音樂最舒服。先存處方。',
      vi: 'Kiểu xả stress: Đắm vào sáng tạo 🎨 Thảo nào nghe nhạc là thấy dễ chịu nhất… lưu “đơn thuốc” này.',
      id: 'Tipe pelegaan stres: Larut dalam kreativitas 🎨 Pantas dengerin musik paling bikin nyaman… simpan resepnya dulu.',
    }),
  },
  {
    type: 'Type6',
    emoji: '🛋️',
    title: T({
      ko: '완전한 멈춤으로 재충전하는, 무기력 회피 재충전형',
      en: 'Full Stop Recharge Type',
      ja: '完全停止で充電する、無気力回避リチャージ型',
      zhCN: '彻底停机充电：无力回避再充能型',
      zhTW: '徹底停機充電：無力回避再充能型',
      vi: 'Kiểu “dừng hẳn để sạc lại”',
      id: 'Tipe isi ulang dengan berhenti total',
    }),
    scoreBand: T({
      ko: '총점 34~36점 구간',
      en: 'Total score: 34–36',
      ja: '合計 34〜36点',
      zhCN: '总分 34–36',
      zhTW: '總分 34–36',
      vi: 'Tổng điểm: 34–36',
      id: 'Skor total: 34–36',
    }),
    tagLine: T({
      ko: '스트레스 해소 유형: 아무것도 안 해야 진짜 충전이 되는 사람',
      en: 'Relief type: You recharge for real only when you do nothing.',
      ja: '解消タイプ：何もしないことで本当に充電できる人。',
      zhCN: '解压类型：必须“什么都不做”才会真的回电。',
      zhTW: '解壓類型：必須「什麼都不做」才會真的回電。',
      vi: 'Kiểu giải tỏa: Bạn chỉ hồi phục thật sự khi không làm gì cả.',
      id: 'Tipe: Kamu benar-benar terisi ulang saat tidak melakukan apa-apa.',
    }),
    hookLine: T({
      ko: '"당신에게 회복은 완전한 멈춤입니다. 아무것도 하지 않는 것 자체가 치유입니다."',
      en: '"Recovery for you is a full stop. Doing nothing itself is healing."',
      ja: '「あなたの回復は完全な停止。何もしないこと自体が癒し。」',
      zhCN: '“你的恢复是彻底停下来。什么都不做本身就是疗愈。”',
      zhTW: '「你的恢復是徹底停下來。什麼都不做本身就是療癒。」',
      vi: '“Hồi phục với bạn là dừng hẳn. Không làm gì cũng chính là chữa lành.”',
      id: '"Pemulihanmu adalah berhenti total. Tidak melakukan apa-apa itu sendiri sudah menyembuhkan."',
    }),
    description: T({
      ko: '스트레스가 쌓이면 아무것도 하고 싶지 않아지고, 그 무기력함을 억지로 이기려 할수록 더 지치는 타입입니다. 이불 속에서 멍하니 있거나, 아무 계획 없이 하루를 보내거나, 완전히 모든 것을 내려놓는 시간이 진짜 회복입니다. 이것은 게으름이 아닙니다. 당신의 신경계가 필요로 하는 것입니다.',
      en: 'When stress piles up, you don’t want to do anything—and forcing yourself to “push through” makes you even more exhausted. Zoning out under a blanket, spending a day with zero plans, fully letting go—that’s real recovery for you. It’s not laziness; it’s what your nervous system needs.',
      ja: 'ストレスが溜まると何もしたくなくなり、その無気力を無理に押し切ろうとするほど消耗するタイプ。布団の中でぼーっとする、予定ゼロで一日を過ごす、すべてを手放す時間が本当の回復。怠けではなく、神経系が必要としているものです。',
      zhCN: '压力堆起来时你会什么都不想做，越是强迫自己“振作”，越容易更累。窝在被子里发呆、一天不做计划、彻底放下——这对你才是真恢复。这不是懒，是你的神经系统在求救与修复。',
      zhTW: '壓力堆起來時你會什麼都不想做，越是強迫自己「振作」，越容易更累。窩在被子裡發呆、一天不做計畫、徹底放下——這對你才是真恢復。這不是懶，是你的神經系統在求救與修復。',
      vi: 'Khi stress dồn lại, bạn chẳng muốn làm gì; càng cố “gồng lên” càng kiệt sức. Nằm im trong chăn, sống một ngày không kế hoạch, buông hết mọi thứ—đó mới là hồi phục thật sự. Đây không phải lười; đó là điều hệ thần kinh của bạn cần.',
      id: 'Saat stres menumpuk, kamu jadi tidak ingin melakukan apa pun; semakin dipaksa “kuat”, semakin capek. Rebahan di selimut, sehari tanpa rencana, melepas semuanya—itulah pemulihan yang nyata. Ini bukan malas; ini kebutuhan sistem sarafmu.',
    }),
    mechanism: T({
      ko: '완전 멈춤 → 신경계 과부하 해제 → 자연스러운 에너지 회복',
      en: 'Full stop → nervous system unloads → energy returns naturally',
      ja: '完全停止 → 神経系の過負荷解除 → 自然回復',
      zhCN: '彻底停下 → 神经系统卸载 → 能量自然回归',
      zhTW: '徹底停下 → 神經系統卸載 → 能量自然回歸',
      vi: 'Dừng hẳn → hạ tải hệ thần kinh → năng lượng tự quay lại',
      id: 'Berhenti total → beban sistem saraf turun → energi pulih alami',
    }),
    strength: T({
      ko: '번아웃 직전에 자신을 멈출 줄 아는 자기 보호 본능',
      en: 'A self-protection instinct—you know how to stop before burnout.',
      ja: '燃え尽き直前で止まれる自己防衛本能。',
      zhCN: '有自我保护本能，懂得在爆燃前按下暂停。',
      zhTW: '有自我保護本能，懂得在爆燃前按下暫停。',
      vi: 'Bản năng tự bảo vệ: biết dừng lại trước khi burnout.',
      id: 'Naluri melindungi diri: tahu kapan harus berhenti sebelum burnout.',
    }),
    caution: T({
      ko: '회복을 위한 멈춤과 우울감으로 인한 무기력을 구별하기. 2주 이상 지속되면 전문가 상담 고려',
      en: 'Differentiate recovery-rest from depressive numbness. If it lasts 2+ weeks, consider professional help.',
      ja: '回復の休息と、抑うつによる無気力を区別。2週間以上続くなら専門家相談も検討。',
      zhCN: '区分“为了恢复的休息”和“抑郁导致的无力”。持续两周以上可考虑求助专业人士。',
      zhTW: '區分「為了恢復的休息」和「憂鬱導致的無力」。持續兩週以上可考慮求助專業人士。',
      vi: 'Phân biệt nghỉ để hồi phục và vô lực do trầm buồn. Nếu kéo dài >2 tuần, cân nhắc gặp chuyên gia.',
      id: 'Bedakan istirahat pemulihan vs lemas karena depresi. Jika 2+ minggu, pertimbangkan konsultasi profesional.',
    }),
    routineText: T({
      ko: [
        '아무것도 안 하는 날을 미리 캘린더에 잡아두기. 계획된 쉬는 날이 죄책감을 줄임',
        '완전한 멈춤 시간에는 생산성 콘텐츠 금지. 가볍고 즐거운 것만 허용',
        '30분 정도 자연 속 멍하니 있기. 숲·공원·바다 등 자연 노출이 회복을 가속화',
        '회복 후 작은 행동 하나로 시동 걸기. 정리 하나, 샤워 하나가 재기의 시작',
        '무기력이 3일 이상 지속되면 가볍게 몸을 움직이는 것으로 전환 시도',
      ].join('\n'),
      en: [
        'Schedule a “do-nothing day” in advance—planned rest reduces guilt',
        'During full-stop time, avoid productivity content; allow only light, pleasant things',
        'Zone out in nature for ~30 minutes (park/forest/sea) to speed recovery',
        'After resting, restart with one tiny action: tidy one thing, take a shower',
        'If lethargy lasts 3+ days, try a gentle shift to light movement',
      ].join('\n'),
      ja: [
        '何もしない日を先にカレンダーに入れる（計画休みは罪悪感を減らす）',
        '完全停止中は生産性コンテンツ禁止。軽く楽しいものだけOK',
        '自然の中で30分ぼーっとする（森・公園・海など）',
        '回復後は小さな行動1つで再始動：片付け1つ、シャワー1つ',
        '無気力が3日以上続くなら、軽い運動への切り替えを試す',
      ].join('\n'),
      zhCN: [
        '提前把“什么都不做的一天”写进日历：计划休息能减少内疚',
        '彻底休息时，禁止生产力内容，只允许轻松愉快的东西',
        '去自然里发呆约30分钟：树林/公园/海边加速恢复',
        '休息后用一个小动作启动：整理一处、洗个澡都算开始',
        '无力感持续3天以上，可尝试转为轻度活动',
      ].join('\n'),
      zhTW: [
        '提前把「什麼都不做的一天」寫進日曆：計畫休息能減少內疚',
        '徹底休息時，禁止生產力內容，只允許輕鬆愉快的東西',
        '去自然裡發呆約30分鐘：樹林/公園/海邊加速恢復',
        '休息後用一個小動作啟動：整理一處、洗個澡都算開始',
        '無力感持續3天以上，可嘗試轉為輕度活動',
      ].join('\n'),
      vi: [
        'Lên lịch trước một ngày “không làm gì” — nghỉ có kế hoạch giảm cảm giác tội lỗi',
        'Trong lúc dừng hẳn, tránh nội dung “năng suất”; chỉ cho phép thứ nhẹ nhàng vui vẻ',
        'Ngồi ngẩn ngơ giữa thiên nhiên ~30 phút (công viên/rừng/biển) để hồi phục nhanh hơn',
        'Sau khi nghỉ, khởi động bằng 1 hành động nhỏ: dọn 1 góc, tắm 1 cái',
        'Nếu uể oải kéo dài >3 ngày, thử chuyển sang vận động nhẹ',
      ].join('\n'),
      id: [
        'Jadwalkan “hari tidak melakukan apa-apa” dari awal—istirahat terencana mengurangi rasa bersalah',
        'Saat berhenti total, hindari konten produktivitas; cukup yang ringan dan menyenangkan',
        'Melamun di alam ~30 menit (taman/hutan/pantai) untuk mempercepat pemulihan',
        'Setelah istirahat, nyalakan mesin dengan 1 aksi kecil: rapikan 1 hal, mandi 1 kali',
        'Jika lemas 3+ hari, coba beralih ke gerak ringan',
      ].join('\n'),
    }),
    actionNow: T({
      ko: '오늘 저녁 아무 계획도 잡지 않기. 완전히 비어있는 저녁이 가장 좋은 회복입니다',
      en: 'Make no plans for tonight. An empty evening is your best recovery.',
      ja: '今夜は予定を入れない。空っぽの夜が最高の回復。',
      zhCN: '今晚不要安排任何计划。彻底空出来的夜晚就是最好的恢复。',
      zhTW: '今晚不要安排任何計畫。徹底空出來的夜晚就是最好的恢復。',
      vi: 'Tối nay đừng lên lịch gì cả. Một buổi tối trống rỗng là hồi phục tốt nhất.',
      id: 'Malam ini jangan buat rencana apa pun. Malam yang kosong adalah pemulihan terbaik.',
    }),
    shareLine: T({
      ko: '스트레스 해소 유형: 무기력 회피 재충전형 🛋️ 아무것도 안 해야 충전된다는 거... 쉬는 게 회복이라는 말 저장각 → 너는 어떤 해소 유형이야?',
      en: 'Stress relief type: Full stop recharge 🛋️ Doing nothing is how I recharge… “rest is recovery” saved. What’s your type?',
      ja: 'ストレス解消タイプ：完全停止リチャージ型 🛋️ 何もしないのが充電…「休む＝回復」保存。あなたはどのタイプ？',
      zhCN: '解压类型：彻底停机充电 🛋️ 只有不做事才会回电…“休息就是恢复”先存了。你是哪一型？',
      zhTW: '解壓類型：徹底停機充電 🛋️ 只有不做事才會回電…「休息就是恢復」先存了。你是哪一型？',
      vi: 'Kiểu xả stress: Dừng hẳn để sạc 🛋️ Không làm gì mới nạp lại… lưu câu “nghỉ là hồi phục”. Bạn thuộc kiểu nào?',
      id: 'Tipe pelegaan stres: Berhenti total 🛋️ Nggak ngapa-ngapain baru keisi… “istirahat itu pemulihan” disimpan. Kamu tipe apa?',
    }),
  },
];
