/** 나의 연애 기대치 진단 — phase3-love-expectation-diagnosis · 12문항 4지선다 · A=0/B=1/C=2/D=3 · 7개 로케일 */

export type Phase3LoveExpectationDiagnosisLocaleKey = 'ko' | 'en' | 'ja' | 'zh-CN' | 'zh-TW' | 'vi' | 'id';

function localeMap(t: Record<Phase3LoveExpectationDiagnosisLocaleKey, string>): Record<Phase3LoveExpectationDiagnosisLocaleKey, string> {
  return t;
}

function opt(m: Record<Phase3LoveExpectationDiagnosisLocaleKey, string>, score: number): { text: Record<Phase3LoveExpectationDiagnosisLocaleKey, string>; score: number } {
  return { text: localeMap(m), score };
}

export interface Phase3LoveExpectationDiagnosisQuestion {
  id: number;
  question: Record<Phase3LoveExpectationDiagnosisLocaleKey, string>;
  options: { text: Record<Phase3LoveExpectationDiagnosisLocaleKey, string>; score: number }[];
}

export interface Phase3LoveExpectationDiagnosisResult {
  type: string;
  emoji: string;
  title: Record<Phase3LoveExpectationDiagnosisLocaleKey, string>;
  expectationSummary: Record<Phase3LoveExpectationDiagnosisLocaleKey, string>;
  quote: Record<Phase3LoveExpectationDiagnosisLocaleKey, string>;
  description: Record<Phase3LoveExpectationDiagnosisLocaleKey, string>;
  expectationType: Record<Phase3LoveExpectationDiagnosisLocaleKey, string>;
  expectationKeywords: Record<Phase3LoveExpectationDiagnosisLocaleKey, string>;
  strengths: Record<Phase3LoveExpectationDiagnosisLocaleKey, string>;
  cautions: Record<Phase3LoveExpectationDiagnosisLocaleKey, string>;
  guidanceAdvice: Record<Phase3LoveExpectationDiagnosisLocaleKey, string>;
  certificationPhrase: Record<Phase3LoveExpectationDiagnosisLocaleKey, string>;
  oneLiner: Record<Phase3LoveExpectationDiagnosisLocaleKey, string>;
  shareLine: Record<Phase3LoveExpectationDiagnosisLocaleKey, string>;
}

export function calculatePhase3LoveExpectationDiagnosisResult(answers: number[]): string {
  const total = answers.reduce((sum, s) => sum + (s ?? 0), 0);
  if (total <= 5) return 'Type1';
  if (total <= 11) return 'Type2';
  if (total <= 19) return 'Type3';
  if (total <= 27) return 'Type4';
  if (total <= 33) return 'Type5';
  return 'Type6';
}

export function calculatePhase3LoveExpectationDiagnosisDomainScores(answers: number[]) {
  const contactCommunication = (answers[0] ?? 0) + (answers[1] ?? 0);
  const timeMeeting = (answers[2] ?? 0) + (answers[3] ?? 0);
  const emotionalSupport = (answers[4] ?? 0) + (answers[5] ?? 0);
  const understandingEmpathy = (answers[6] ?? 0) + (answers[7] ?? 0);
  const futureDevotion = (answers[8] ?? 0) + (answers[9] ?? 0);
  const overallExpectLevel = (answers[10] ?? 0) + (answers[11] ?? 0);
  return {
    contactCommunication,
    timeMeeting,
    emotionalSupport,
    understandingEmpathy,
    futureDevotion,
    overallExpectLevel,
    total: answers.reduce((sum, s) => sum + (s ?? 0), 0),
  };
}

export const phase3LoveExpectationDiagnosisQuestions: Phase3LoveExpectationDiagnosisQuestion[] = [
  {
    id: 1,
    question: localeMap({
      ko: '연인의 연락 패턴에 대한 나의 기대는?',
      en: 'What are my expectations regarding my partner\'s contact patterns?',
      ja: '恋人の連絡パターンに対する私の期待は？',
      'zh-CN': '我对恋人联系模式的期待是？',
      'zh-TW': '我對戀人聯繫模式的期待是？',
      vi: 'Kỳ vọng của tôi về cách người yêu liên lạc là gì?',
      id: 'Apa harapanku tentang pola kontak pasangan?',
    }),
    options: [
      opt(localeMap({
        ko: '연락 빈도에 크게 기대가 없다. 바쁘면 나중에 해도 되고 연락이 뜸해도 별로 신경 쓰이지 않는다',
        en: 'I do not expect much about contact frequency. If they are busy, later is fine, and sparse contact does not bother me',
        ja: '連絡頻度に大きな期待はない。忙しければ後でもよく、連絡が少なくても気にならない',
        'zh-CN': '对联系频率没有太大期待。忙的话晚点也行，联系少也不太在意',
        'zh-TW': '對聯繫頻率沒有太大期待。忙的話晚點也行，聯繫少也不太在意',
        vi: 'Không kỳ vọng nhiều về tần suất liên lạc. Bận thì để sau, ít liên lạc cũng không phiền',
        id: 'Tidak banyak berharap soal frekuensi kontak. Sibuk nanti saja, kontak jarang pun tidak mengganggu',
    }), 0),
      opt(localeMap({
        ko: '하루에 한두 번 정도 안부 연락이 오면 충분하다. 너무 자주도 너무 뜸하지도 않은 정도',
        en: 'One or two check-in messages a day is enough—not too often, not too sparse',
        ja: '一日に1〜2回の安否連絡があれば十分。多すぎず少なすぎず',
        'zh-CN': '一天一两次问候联系就够了，不太频繁也不太稀疏',
        'zh-TW': '一天一兩次問候聯繫就夠了，不太頻繁也不太稀疏',
        vi: 'Một hai tin hỏi thăm mỗi ngày là đủ—không quá nhiều cũng không quá thưa',
        id: 'Satu atau dua pesan check-in sehari cukup—tidak terlalu sering atau terlalu jarang',
    }), 1),
      opt(localeMap({
        ko: '아침저녁으로 연락이 오길 기대한다. 중간에 생각날 때 먼저 연락해주면 더 좋다',
        en: 'I expect contact morning and evening. It is even better if they reach out first when they think of me',
        ja: '朝晩の連絡を期待する。思い出したときに先に連絡してくれるとより嬉しい',
        'zh-CN': '期待早晚联系，中间想到我时主动联系我更好',
        'zh-TW': '期待早晚聯繫，中間想到我時主動聯繫我更好',
        vi: 'Mong liên lạc sáng tối. Càng tốt nếu họ chủ động nhắn khi nghĩ đến mình',
        id: 'Mengharap kontak pagi dan malam. Lebih baik jika mereka menghubungi duluan saat teringat',
    }), 2),
      opt(localeMap({
        ko: '항상 연결되어 있는 느낌이어야 한다. 오래 연락이 없으면 불안해지고 먼저 연락이 오길 바란다',
        en: 'I need to feel always connected. I get anxious without contact for long and hope they reach out first',
        ja: '常につながっている感覚が必要。長く連絡がないと不安になり、先に連絡してほしい',
        'zh-CN': '需要一直连着的感觉。很久没联系会不安，希望对方先联系我',
        'zh-TW': '需要一直連著的感覺。很久沒聯繫會不安，希望對方先聯繫我',
        vi: 'Cần cảm giác luôn kết nối. Lâu không liên lạc sẽ lo và mong họ chủ động nhắn trước',
        id: 'Perlu merasa selalu terhubung. Lama tanpa kontak membuat cemas dan berharap mereka menghubungi dulu',
    }), 3),
    ],
  },
  {
    id: 2,
    question: localeMap({
      ko: '연인이 답장이 늦을 때 나는?',
      en: 'When my partner replies late, I:',
      ja: '恋人の返信が遅いとき、私は？',
      'zh-CN': '恋人回复慢时，我会？',
      'zh-TW': '戀人回覆慢時，我會？',
      vi: 'Khi người yêu trả lời chậm, tôi:',
      id: 'Saat pasangan membalas terlambat, aku:',
    }),
    options: [
      opt(localeMap({
        ko: '전혀 신경 쓰이지 않는다. 바쁠 수도 있고 각자 생활이 있다',
        en: 'Do not mind at all. They may be busy and we each have our own lives',
        ja: '全く気にしない。忙しいかもしれないし、それぞれの生活がある',
        'zh-CN': '完全不在意。可能很忙，各自有各自的生活',
        'zh-TW': '完全不在意。可能很忙，各自有各自的生活',
        vi: 'Hoàn toàn không bận tâm. Họ có thể bận và mỗi người có cuộc sống riêng',
        id: 'Sama sekali tidak peduli. Mungkin sibuk dan masing-masing punya hidup sendiri',
    }), 0),
      opt(localeMap({
        ko: '가끔 궁금하지만 오래 기다리면 먼저 연락하거나 그냥 넘긴다',
        en: 'Sometimes wonder, but if I wait long I reach out first or let it go',
        ja: 'たまに気になるが、長く待てば先に連絡するかそのまま流す',
        'zh-CN': '偶尔好奇，等久了会主动联系或就这样算了',
        'zh-TW': '偶爾好奇，等久了會主動聯繫或就這樣算了',
        vi: 'Đôi khi tò mò, nhưng đợi lâu thì chủ động nhắn hoặc bỏ qua',
        id: 'Kadang penasaran, tapi kalau lama menunggu aku hubungi dulu atau biarkan saja',
    }), 1),
      opt(localeMap({
        ko: '꽤 신경 쓰인다. 왜 늦는지, 무슨 일인지 생각하게 된다',
        en: 'It bothers me quite a bit. I wonder why they are late and what is going on',
        ja: 'かなり気になる。なぜ遅いのか、何があったのか考えてしまう',
        'zh-CN': '挺在意的，会想为什么迟回、发生了什么事',
        'zh-TW': '挺在意的，會想為什麼遲回、發生了什麼事',
        vi: 'Khá bận tâm. Tự hỏi vì sao trả lời chậm và chuyện gì đang xảy ra',
        id: 'Cukup mengganggu. Aku penasaran kenapa telat dan ada apa',
    }), 2),
      opt(localeMap({
        ko: '많이 불안해진다. 답장을 기다리는 동안 이런저런 생각이 든다. 확인됐다는 알림이 있으면 더 신경 쓰인다',
        en: 'I get very anxious. All kinds of thoughts run through my head while waiting. Read receipts bother me even more',
        ja: 'とても不安になる。返信を待つ間いろいろ考える。既読通知があるとさらに気になる',
        'zh-CN': '很不安，等回复时会想很多。有已读通知更在意',
        'zh-TW': '很不安，等回覆時會想很多。有已讀通知更在意',
        vi: 'Rất lo lắng. Chờ trả lời nghĩ linh tinh. Có thông báo đã đọc càng bận tâm hơn',
        id: 'Sangat cemas. Banyak pikiran saat menunggu balasan. Notifikasi dibaca membuat lebih was-was',
    }), 3),
    ],
  },
  {
    id: 3,
    question: localeMap({
      ko: '연인과의 만남 빈도에 대한 나의 기대는?',
      en: 'What are my expectations about how often we meet?',
      ja: '恋人との会う頻度に対する私の期待は？',
      'zh-CN': '我对和恋人见面频率的期待是？',
      'zh-TW': '我對和戀人見面頻率的期待是？',
      vi: 'Kỳ vọng của tôi về tần suất gặp người yêu là gì?',
      id: 'Apa harapanku tentang seberapa sering kami bertemu?',
    }),
    options: [
      opt(localeMap({
        ko: '자주 안 봐도 된다. 한 달에 몇 번만 봐도 관계가 유지된다고 생각한다',
        en: 'We do not need to meet often. A few times a month is enough to maintain the relationship',
        ja: 'あまり会わなくてもよい。月に数回会えば関係は保てる',
        'zh-CN': '不用经常见，一个月见几次也能维持关系',
        'zh-TW': '不用經常見，一個月見幾次也能維持關係',
        vi: 'Không cần gặp thường xuyên. Vài lần một tháng vẫn duy trì được quan hệ',
        id: 'Tidak perlu sering bertemu. Beberapa kali sebulan cukup untuk menjaga hubungan',
    }), 0),
      opt(localeMap({
        ko: '주 1~2회 정도가 적당하다. 서로 생활이 있으니 그 안에서 조율하면 된다',
        en: 'About once or twice a week is right. We each have lives and can adjust within that',
        ja: '週1〜2回くらいが適当。それぞれ生活があり、その中で調整すればよい',
        'zh-CN': '一周一两次比较合适，各自有生活，在其中协调就好',
        'zh-TW': '一週一兩次比較合適，各自有生活，在其中協調就好',
        vi: 'Khoảng một hai lần một tuần là vừa. Mỗi người có cuộc sống riêng và có thể điều chỉnh',
        id: 'Sekitar satu atau dua kali seminggu pas. Masing-masing punya hidup dan bisa menyesuaikan',
    }), 1),
      opt(localeMap({
        ko: '가능하면 자주 보고 싶다. 주 3회 이상이면 더 좋다. 만남이 많을수록 가깝게 느껴진다',
        en: 'I want to meet as often as possible. Three or more times a week feels closer',
        ja: 'できるだけ会いたい。週3回以上だとより近く感じる',
        'zh-CN': '尽可能多见，一周三次以上会觉得更亲近',
        'zh-TW': '盡可能多見，一週三次以上會覺得更親近',
        vi: 'Muốn gặp càng thường càng tốt. Ba lần/tuần trở lên cảm thấy gần hơn',
        id: 'Ingin bertemu sesering mungkin. Tiga kali seminggu atau lebih terasa lebih dekat',
    }), 2),
      opt(localeMap({
        ko: '시간이 날 때마다 보고 싶다. 만나지 못하는 날이 길어지면 관계가 멀어지는 것 같다',
        en: 'I want to meet whenever we have time. Long stretches without meeting feel like we are drifting apart',
        ja: '時間があるときは会いたい。会えない日が長いと関係が遠ざかる気がする',
        'zh-CN': '有时间就想见，见不到的日子长了会觉得关系变远',
        'zh-TW': '有時間就想見，見不到的日子長了會覺得關係變遠',
        vi: 'Muốn gặp mỗi khi có thời gian. Nhiều ngày không gặp cảm giác xa dần',
        id: 'Ingin bertemu setiap ada waktu. Lama tidak bertemu terasa hubungan makin jauh',
    }), 3),
    ],
  },
  {
    id: 4,
    question: localeMap({
      ko: '연인이 바빠서 약속을 자주 취소할 때 나는?',
      en: 'When my partner often cancels plans because they are busy, I:',
      ja: '恋人が忙しくて約束をよくキャンセルするとき、私は？',
      'zh-CN': '恋人因忙碌经常取消约会时，我会？',
      'zh-TW': '戀人因忙碌經常取消約會時，我會？',
      vi: 'Khi người yêu hay hủy hẹn vì bận, tôi:',
      id: 'Saat pasangan sering membatalkan janji karena sibuk, aku:',
    }),
    options: [
      opt(localeMap({
        ko: '이해한다. 각자 일이나 생활이 있으니 어쩔 수 없다. 나중에 보면 된다',
        en: 'Understand. We each have work and life—it happens. We can meet later',
        ja: '理解する。それぞれ仕事や生活があり仕方ない。後で会えばよい',
        'zh-CN': '理解，各自有工作和生活，没办法。以后见就行',
        'zh-TW': '理解，各自有工作和生活，沒辦法。以後見就行',
        vi: 'Thông cảm. Mỗi người có việc và cuộc sống—không tránh được. Gặp sau cũng được',
        id: 'Mengerti. Masing-masing punya pekerjaan dan hidup—wajar. Nanti bertemu saja',
    }), 0),
      opt(localeMap({
        ko: '아쉽지만 받아들인다. 단 너무 자주 반복되면 이야기를 꺼낸다',
        en: 'Feel disappointed but accept it. If it repeats too often, I bring it up',
        ja: '残念だが受け入れる。あまり繰り返すなら話題にする',
        'zh-CN': '遗憾但接受，太频繁重复会提出来谈',
        'zh-TW': '遺憾但接受，太頻繁重複會提出來談',
        vi: 'Tiếc nhưng chấp nhận. Nếu lặp lại quá nhiều sẽ nói ra',
        id: 'Kecewa tapi menerima. Kalau terlalu sering, aku angkat bicara',
    }), 1),
      opt(localeMap({
        ko: '서운하다. 바쁜 건 알지만 나를 우선순위에 두지 않는다는 느낌이 든다',
        en: 'Feel hurt. I know they are busy but it feels like I am not a priority',
        ja: '残る。忙しいのは分かるが、優先順位に入っていない気がする',
        'zh-CN': '觉得委屈，知道忙但感觉我没被放在优先位置',
        'zh-TW': '覺得委屈，知道忙但感覺我沒被放在優先位置',
        vi: 'Buồn. Biết họ bận nhưng cảm giác mình không được ưu tiên',
        id: 'Tersakiti. Tahu mereka sibuk tapi terasa aku bukan prioritas',
    }), 2),
      opt(localeMap({
        ko: '많이 상처받는다. 약속은 나에게 그 사람이 나를 중요하게 여긴다는 신호이기 때문이다',
        en: 'Feel deeply hurt. Plans are a sign that I matter to them',
        ja: 'とても傷つく。約束はその人が私を大切にしている証だと感じる',
        'zh-CN': '很受伤，约会对我来说是对方重视我的信号',
        'zh-TW': '很受傷，約會對我來說是對方重視我的信號',
        vi: 'Rất tổn thương. Hẹn hò là dấu hiệu cho thấy mình quan trọng với họ',
        id: 'Sangat terluka. Janji adalah tanda bahwa aku penting bagi mereka',
    }), 3),
    ],
  },
  {
    id: 5,
    question: localeMap({
      ko: '힘든 일이 생겼을 때 연인에게 기대하는 것은?',
      en: 'When something hard happens, what do I expect from my partner?',
      ja: 'つらいことが起きたとき、恋人に期待することは？',
      'zh-CN': '遇到难事时，我对恋人期待什么？',
      'zh-TW': '遇到難事時，我對戀人期待什麼？',
      vi: 'Khi có chuyện khó khăn, tôi kỳ vọng gì ở người yêu?',
      id: 'Saat ada hal sulit, apa yang kuharapkan dari pasangan?',
    }),
    options: [
      opt(localeMap({
        ko: '딱히 기대하지 않는다. 힘든 일은 스스로 해결하는 편이고 연인에게 기대려 하지 않는다',
        en: 'Not much. I tend to handle hard things myself and do not lean on my partner',
        ja: '特に期待しない。つらいことは自分で解決する方で、恋人に頼らない',
        'zh-CN': '不太期待，难事习惯自己解决，不太依赖恋人',
        'zh-TW': '不太期待，難事習慣自己解決，不太依賴戀人',
        vi: 'Không kỳ vọng nhiều. Tôi thường tự xử lý và không dựa vào người yêu',
        id: 'Tidak banyak. Aku cenderung menyelesaikan sendiri dan tidak bergantung pada pasangan',
    }), 0),
      opt(localeMap({
        ko: '들어주면 충분하다. 해결해줄 필요는 없고 공감해주는 것만으로도 된다',
        en: 'Listening is enough. They do not need to fix it—empathy alone is fine',
        ja: '聞いてくれれば十分。解決しなくてよく、共感だけでよい',
        'zh-CN': '愿意听就够了，不必解决，共情就可以',
        'zh-TW': '願意聽就夠了，不必解決，共情就可以',
        vi: 'Lắng nghe là đủ. Không cần giải quyết—đồng cảm là được',
        id: 'Didengarkan sudah cukup. Tidak perlu menyelesaikan—empati saja sudah baik',
    }), 1),
      opt(localeMap({
        ko: '적극적으로 위로해주길 바란다. 어떻게 해줄 수 있는지 먼저 물어봐줬으면 한다',
        en: 'I want active comfort. I hope they ask first how they can help',
        ja: '積極的な慰めを望む。どう助けられるか先に聞いてほしい',
        'zh-CN': '希望积极安慰，最好先问能怎么帮我',
        'zh-TW': '希望積極安慰，最好先問能怎麼幫我',
        vi: 'Mong được an ủi tích cực. Mong họ hỏi trước có thể giúp gì',
        id: 'Ingin penghiburan aktif. Berharap mereka tanya dulu bagaimana bisa membantu',
    }), 2),
      opt(localeMap({
        ko: '내 편이 되어서 함께 있어줬으면 한다. 말 이상으로 행동으로도 보여줬으면 한다',
        en: 'I want them on my side and present with me—not just words but actions too',
        ja: '味方になって一緒にいてほしい。言葉以上に行動でも示してほしい',
        'zh-CN': '希望站在我这边陪着我，不只是话，行动也要',
        'zh-TW': '希望站在我這邊陪著我，不只是話，行動也要',
        vi: 'Mong họ về phe mình và ở bên—not chỉ lời nói mà cả hành động',
        id: 'Ingin mereka di pihakku dan hadir—not hanya kata-kata tapi juga tindakan',
    }), 3),
    ],
  },
  {
    id: 6,
    question: localeMap({
      ko: '연인이 힘든 날 나에게 연락하지 않고 혼자 해결했다. 나는?',
      en: 'My partner had a hard day and handled it alone without contacting me. I:',
      ja: '恋人がつらい日を一人で乗り越え、連絡しなかった。私は？',
      'zh-CN': '恋人难过的一天独自解决，没有联系我。我会？',
      'zh-TW': '戀人難過的一天獨自解決，沒有聯繫我。我會？',
      vi: 'Người yêu có ngày khó khăn và tự xử lý, không liên lạc. Tôi:',
      id: 'Pasangan punya hari sulit dan menanganinya sendiri tanpa menghubungi. Aku:',
    }),
    options: [
      opt(localeMap({
        ko: '당연하다. 힘든 일을 꼭 공유해야 한다고 생각하지 않는다. 각자 알아서 해결하면 된다',
        en: 'Think it is natural. Hard things do not always need to be shared—we can handle them ourselves',
        ja: '当然だと思う。つらいことを必ず共有する必要はない。各自で解決すればよい',
        'zh-CN': '觉得理所当然，难事不必都分享，各自解决就好',
        'zh-TW': '覺得理所當然，難事不必都分享，各自解決就好',
        vi: 'Thấy bình thường. Chuyện khó không nhất thiết phải chia sẻ—tự xử lý được',
        id: 'Merasa wajar. Hal sulit tidak harus selalu dibagi—masing-masing bisa menyelesaikan',
    }), 0),
      opt(localeMap({
        ko: '나중에라도 이야기해주면 좋겠다는 생각은 든다. 하지만 먼저 물어보진 않는다',
        en: 'Would like them to tell me later, but I would not ask first',
        ja: '後で話してくれればよいと思う。ただ先には聞かない',
        'zh-CN': '希望后来告诉我，但不会先问',
        'zh-TW': '希望後來告訴我，但不會先問',
        vi: 'Mong sau này họ kể, nhưng tôi sẽ không hỏi trước',
        id: 'Ingin mereka cerita nanti, tapi aku tidak akan tanya dulu',
    }), 1),
      opt(localeMap({
        ko: '조금 섭섭하다. 나한테 말해줬으면 같이 이야기했을 텐데 라는 생각이 든다',
        en: 'Feel a bit left out. I think we could have talked if they had told me',
        ja: '少し寂しい。言ってくれれば一緒に話せたのにと思う',
        'zh-CN': '有点失落，要是告诉我就一起聊了',
        'zh-TW': '有點失落，要是告訴我就一起聊了',
        vi: 'Hơi buồn. Nghĩ nếu họ nói thì mình đã cùng trò chuyện',
        id: 'Agak kecewa. Pikir kalau mereka bilang, kita bisa bicara bersama',
    }), 2),
      opt(localeMap({
        ko: '많이 서운하다. 힘든 걸 나 몰래 혼자 감당했다는 게 우리 관계에서 내 자리가 어딘지 의심하게 만든다',
        en: 'Feel very hurt. Handling it alone makes me doubt my place in the relationship',
        ja: 'とても残る。一人で乗り越えたことが関係での自分の居場所を疑わせる',
        'zh-CN': '很失落，独自承受让我怀疑在这段关系里的位置',
        'zh-TW': '很失落，獨自承受讓我懷疑在這段關係裡的位置',
        vi: 'Rất buồn. Tự gánh một mình khiến tôi nghi ngờ vị trí của mình trong quan hệ',
        id: 'Sangat kecewa. Menanganinya sendiri membuatku meragukan posisiku dalam hubungan',
    }), 3),
    ],
  },
  {
    id: 7,
    question: localeMap({
      ko: '연인이 나의 기분이나 감정 변화를 알아채는 것에 대한 기대는?',
      en: 'What do I expect about my partner noticing my mood or emotional changes?',
      ja: '恋人が私の気分や感情の変化に気づくことへの期待は？',
      'zh-CN': '我对恋人察觉我心情或情绪变化的期待是？',
      'zh-TW': '我對戀人察覺我心情或情緒變化的期待是？',
      vi: 'Tôi kỳ vọng gì về việc người yêu nhận ra tâm trạng hoặc thay đổi cảm xúc của mình?',
      id: 'Apa harapanku tentang pasangan menyadari perubahan mood atau emosiku?',
    }),
    options: [
      opt(localeMap({
        ko: '말하지 않으면 모르는 게 당연하다. 굳이 눈치채줄 필요는 없다',
        en: 'If I do not say it, they do not need to know. No need to read my mind',
        ja: '言わなければ分からなくて当然。わざわざ察する必要はない',
        'zh-CN': '不说就不知道很正常，不必特意察觉',
        'zh-TW': '不說就不知道很正常，不必特意察覺',
        vi: 'Không nói thì không biết là bình thường. Không cần đoán ý',
        id: 'Kalau tidak dibilang, wajar tidak tahu. Tidak perlu bisa membaca pikiran',
    }), 0),
      opt(localeMap({
        ko: '뭔가 이상하다 싶을 때 물어봐주면 좋겠다. 알아서 다 알 필요는 없다',
        en: 'It would be nice if they ask when something seems off. They do not need to know everything',
        ja: 'おかしいと思ったら聞いてくれると嬉しい。全部分かる必要はない',
        'zh-CN': '觉得不对劲时问一下就好，不必全都知道',
        'zh-TW': '覺得不對勁時問一下就好，不必全都知道',
        vi: 'Hỏi khi thấy có gì lạ thì tốt. Không cần biết hết',
        id: 'Bagus jika mereka tanya saat ada yang aneh. Tidak perlu tahu semuanya',
    }), 1),
      opt(localeMap({
        ko: '내가 말하지 않아도 눈치채줬으면 한다. 그것이 나를 잘 안다는 신호라고 생각한다',
        en: 'I want them to notice even without me saying. That feels like they really know me',
        ja: '言わなくても察してほしい。それがよく分かってくれている証だと感じる',
        'zh-CN': '希望我不说也能察觉，那感觉像真的懂我',
        'zh-TW': '希望我不說也能察覺，那感覺像真的懂我',
        vi: 'Mong họ nhận ra dù mình không nói. Đó là dấu hiệu họ hiểu mình',
        id: 'Ingin mereka sadar meski aku tidak bilang. Itu terasa seperti mereka benar-benar mengenalku',
    }), 2),
      opt(localeMap({
        ko: '내 감정을 먼저 알아채고 먼저 다가와줬으면 한다. 말해야만 알아주는 관계는 조금 아쉽다',
        en: 'I want them to notice first and reach out. A relationship where I must speak to be understood feels lacking',
        ja: '先に気づいて近づいてほしい。言わないと分からない関係は少し物足りない',
        'zh-CN': '希望先察觉并主动靠近，必须说了才懂的关系有点遗憾',
        'zh-TW': '希望先察覺並主動靠近，必須說了才懂的關係有點遺憾',
        vi: 'Mong họ nhận ra trước và chủ động lại gần. Quan hệ phải nói mới hiểu hơi thiếu',
        id: 'Ingin mereka sadar dulu dan mendekat. Hubungan yang harus dibilang dulu baru paham terasa kurang',
    }), 3),
    ],
  },
  {
    id: 8,
    question: localeMap({
      ko: '연인이 나를 이해하지 못하거나 내 입장을 모를 때 나는?',
      en: 'When my partner does not understand me or my perspective, I:',
      ja: '恋人が私を理解できない、または私の立場が分からないとき、私は？',
      'zh-CN': '恋人不能理解我或不懂我的立场时，我会？',
      'zh-TW': '戀人不能理解我或不懂我的立場時，我會？',
      vi: 'Khi người yêu không hiểu mình hoặc không hiểu quan điểm của mình, tôi:',
      id: 'Saat pasangan tidak memahami aku atau sudut pandangku, aku:',
    }),
    options: [
      opt(localeMap({
        ko: '설명하면 되고 이해를 못 해도 괜찮다. 모든 것을 이해받아야 한다고 생각하지 않는다',
        en: 'Can explain and it is fine if they do not fully get it. I do not need to be understood in everything',
        ja: '説明すればよく、完全に理解されなくてもよい。すべて理解される必要はない',
        'zh-CN': '解释就好，不完全理解也行，不必事事被理解',
        'zh-TW': '解釋就好，不完全理解也行，不必事事被理解',
        vi: 'Giải thích là được, không hiểu hết cũng ổn. Không cần được hiểu mọi thứ',
        id: 'Bisa dijelaskan dan tidak apa-apa kalau tidak sepenuhnya paham. Tidak perlu dipahami dalam segala hal',
    }), 0),
      opt(localeMap({
        ko: '설명하면 이해하려고 노력해줬으면 한다. 완전히 이해는 못 해도 된다',
        en: 'Hope they try to understand if I explain. Full understanding is not required',
        ja: '説明すれば理解しようとしてほしい。完全な理解は必要ない',
        'zh-CN': '希望解释后愿意理解，不必完全懂',
        'zh-TW': '希望解釋後願意理解，不必完全懂',
        vi: 'Mong họ cố hiểu nếu mình giải thích. Không cần hiểu hoàn toàn',
        id: 'Berharap mereka berusaha paham jika aku jelaskan. Pemahaman penuh tidak wajib',
    }), 1),
      opt(localeMap({
        ko: '노력 없이 이해 못 하는 게 답답하다. 더 알려고 해줬으면 좋겠다는 생각이 든다',
        en: 'Feel frustrated when they do not try. I wish they would make more effort to know me',
        ja: '努力なく理解できないのがもどかしい。もっと知ろうとしてほしい',
        'zh-CN': '不努力理解会烦躁，希望更想了解我',
        'zh-TW': '不努力理解會煩躁，希望更想了解我',
        vi: 'Bực khi họ không cố hiểu. Mong họ nỗ lực hiểu mình hơn',
        id: 'Kesal kalau tidak berusaha paham. Berharap mereka lebih berusaha mengenalku',
    }), 2),
      opt(localeMap({
        ko: '내 입장을 이해 못 하면 많이 외롭고 혼자인 느낌이 든다. 연인이라면 나를 깊이 알아야 한다고 생각한다',
        en: 'Feel very lonely. As a partner, I believe they should know me deeply',
        ja: 'とても孤独に感じる。恋人なら深く知っていてほしい',
        'zh-CN': '很孤独，作为恋人应该深入了解我',
        'zh-TW': '很孤獨，作為戀人應該深入了解我',
        vi: 'Cảm thấy rất cô đơn. Là người yêu thì nên hiểu mình sâu sắc',
        id: 'Merasa sangat kesepian. Sebagai pasangan, mereka seharusnya mengenalku dalam-dalam',
    }), 3),
    ],
  },
  {
    id: 9,
    question: localeMap({
      ko: '연인이 나를 위해 희생하거나 양보하는 것에 대한 기대는?',
      en: 'What do I expect about my partner sacrificing or compromising for me?',
      ja: '恋人が私のために犠牲や譲歩をすることへの期待は？',
      'zh-CN': '我对恋人为我牺牲或让步的期待是？',
      'zh-TW': '我對戀人為我犧牲或讓步的期待是？',
      vi: 'Tôi kỳ vọng gì về việc người yêu hy sinh hoặc nhượng bộ vì mình?',
      id: 'Apa harapanku tentang pasangan berkorban atau berkompromi untukku?',
    }),
    options: [
      opt(localeMap({
        ko: '기대하지 않는다. 서로 희생 없이 편하게 지내는 게 맞다',
        en: 'I do not expect it. A comfortable relationship without constant sacrifice is best',
        ja: '期待しない。互いに犠牲なく快適に過ごすのがよい',
        'zh-CN': '不期待，彼此不牺牲、舒服相处最好',
        'zh-TW': '不期待，彼此不犧牲、舒服相處最好',
        vi: 'Không kỳ vọng. Quan hệ thoải mái không cần hy sinh liên tục là tốt nhất',
        id: 'Tidak mengharapkannya. Hubungan nyaman tanpa pengorbanan terus-menerus paling baik',
    }), 0),
      opt(localeMap({
        ko: '중요한 순간에는 서로 배려하면 충분하다. 매번 희생을 기대하지는 않는다',
        en: 'Mutual care in important moments is enough. I do not expect sacrifice every time',
        ja: '大切な瞬間に互いに配慮すれば十分。毎回の犠牲は期待しない',
        'zh-CN': '重要时刻互相体谅就够，不期待每次都牺牲',
        'zh-TW': '重要時刻互相體諒就夠，不期待每次都犧牲',
        vi: 'Quan tâm lẫn nhau trong khoảnh khắc quan trọng là đủ. Không kỳ vọng hy sinh mọi lúc',
        id: 'Saling peduli di momen penting sudah cukup. Tidak mengharap pengorbanan setiap saat',
    }), 1),
      opt(localeMap({
        ko: '가끔은 나를 위해 자신의 것을 내려놓을 수 있다는 것을 보여줬으면 한다',
        en: 'Sometimes I want to see they can set aside their own things for me',
        ja: '時には自分のものを下ろしてくれることを見せてほしい',
        'zh-CN': '有时希望看到能为我把自己的事先放下',
        'zh-TW': '有時希望看到能為我把自己的事先放下',
        vi: 'Đôi khi mong thấy họ có thể buông bỏ thứ của mình vì mình',
        id: 'Kadang ingin melihat mereka bisa menurunkan hal mereka sendiri untukku',
    }), 2),
      opt(localeMap({
        ko: '연인이라면 서로를 위해 기꺼이 희생할 수 있어야 한다. 그것이 진짜 사랑의 척도라고 생각한다',
        en: 'Partners should willingly sacrifice for each other. I see that as a measure of real love',
        ja: '恋人なら互いのために喜んで犠牲できなければならない。それが本当の愛の尺度だと思う',
        'zh-CN': '恋人应该愿意为彼此牺牲，那是真爱的尺度',
        'zh-TW': '戀人應該願意為彼此犧牲，那是真愛的尺度',
        vi: 'Người yêu nên sẵn sàng hy sinh vì nhau. Đó là thước đo tình yêu thật',
        id: 'Pasangan harus rela berkorban satu sama lain. Itu ukuran cinta sejati menurutku',
    }), 3),
    ],
  },
  {
    id: 10,
    question: localeMap({
      ko: '연인과의 미래 계획에 대한 기대는?',
      en: 'What do I expect about future plans with my partner?',
      ja: '恋人との未来計画への期待は？',
      'zh-CN': '我对和恋人的未来计划的期待是？',
      'zh-TW': '我對和戀人的未來計畫的期待是？',
      vi: 'Tôi kỳ vọng gì về kế hoạch tương lai với người yêu?',
      id: 'Apa harapanku tentang rencana masa depan dengan pasangan?',
    }),
    options: [
      opt(localeMap({
        ko: '딱히 없다. 지금 좋으면 됐고 미래는 그때 생각하면 된다',
        en: 'Not much. If things are good now, the future can wait',
        ja: '特にない。今がよければ未来はそのとき考えればよい',
        'zh-CN': '没什么期待，现在好就行，未来到时候再想',
        'zh-TW': '沒什麼期待，現在好就行，未來到時候再想',
        vi: 'Không nhiều. Bây giờ tốt là được, tương lai để sau',
        id: 'Tidak banyak. Kalau sekarang baik, masa depan nanti saja',
    }), 0),
      opt(localeMap({
        ko: '구체적이지 않아도 함께하고 싶다는 방향성이 있으면 충분하다',
        en: 'A general direction of wanting to be together is enough—even if not concrete',
        ja: '具体的でなくても一緒にいたいという方向性があれば十分',
        'zh-CN': '不必具体，有想一起走下去的方向就够',
        'zh-TW': '不必具體，有想一起走下去的方向就夠',
        vi: 'Chỉ cần hướng muốn ở bên nhau là đủ—dù chưa cụ thể',
        id: 'Arah ingin bersama sudah cukup—meski belum konkret',
    }), 1),
      opt(localeMap({
        ko: '어느 정도 구체적인 미래 이야기를 함께 나눴으면 한다. 같은 방향을 보고 있는지 확인하고 싶다',
        en: 'I want to share somewhat concrete future talks and confirm we look the same way',
        ja: 'ある程度具体的な未来の話を共有し、同じ方向を見ているか確認したい',
        'zh-CN': '希望有一定具体的未来对话，确认方向一致',
        'zh-TW': '希望有一定具體的未來對話，確認方向一致',
        vi: 'Muốn chia sẻ chuyện tương lai khá cụ thể và xác nhận cùng hướng',
        id: 'Ingin berbagi rencana masa depan yang cukup konkret dan memastikan arah yang sama',
    }), 2),
      opt(localeMap({
        ko: '단계별 계획을 함께 세우고 미래에 대한 이야기를 자주 나눴으면 한다. 불확실한 미래는 불안하다',
        en: 'I want step-by-step plans and frequent future talks. An uncertain future makes me anxious',
        ja: '段階的な計画と未来の話をよくしたい。不確かな未来は不安',
        'zh-CN': '希望分阶段计划并经常聊未来，不确定的未来让我不安',
        'zh-TW': '希望分階段計畫並經常聊未來，不確定的未來讓我不安',
        vi: 'Muốn lập kế hoạch từng bước và thường nói về tương lai. Tương lai mơ hồ gây lo',
        id: 'Ingin rencana bertahap dan sering bicara masa depan. Masa depan tidak pasti membuat cemas',
    }), 3),
    ],
  },
  {
    id: 11,
    question: localeMap({
      ko: '연인에 대한 나의 기대를 한마디로 표현한다면?',
      en: 'If I had to describe my expectations of my partner in one phrase, I would say:',
      ja: '恋人への期待を一言で表すなら？',
      'zh-CN': '用一句话形容我对恋人的期待，我会说？',
      'zh-TW': '用一句話形容我對戀人的期待，我會說？',
      vi: 'Nếu mô tả kỳ vọng với người yêu bằng một câu, tôi nói:',
      id: 'Jika harus menggambarkan harapanku pada pasangan dalam satu kalimat, aku bilang:',
    }),
    options: [
      opt(localeMap({
        ko: '기대가 거의 없다. 있어주는 것만으로 충분하다',
        en: 'Almost none. Just having them is enough',
        ja: 'ほとんどない。いてくれるだけで十分',
        'zh-CN': '几乎没什么，有他们在就够了',
        'zh-TW': '幾乎沒什麼，有他們在就夠了',
        vi: 'Gần như không có. Có họ là đủ',
        id: 'Hampir tidak ada. Ada mereka saja sudah cukup',
    }), 0),
      opt(localeMap({
        ko: '적당한 기대. 서로 편한 만큼만 해주면 된다',
        en: 'Moderate expectations—just what feels comfortable for both of us',
        ja: '適度な期待。お互いに心地よい程度でよい',
        'zh-CN': '适度期待，彼此舒服的程度就好',
        'zh-TW': '適度期待，彼此舒服的程度就好',
        vi: 'Kỳ vọng vừa phải—ở mức thoải mái cho cả hai',
        id: 'Harapan moderat—sejauh yang nyaman untuk kita berdua',
    }), 1),
      opt(localeMap({
        ko: '나름 기대가 있다. 연인이라면 이 정도는 해줬으면 하는 것들이 있다',
        en: 'I do have expectations. As a partner, there are things I hope they would do',
        ja: 'なかなか期待がある。恋人ならこれくらいはしてほしいことがある',
        'zh-CN': '还是有不少期待，作为恋人有些事希望对方做到',
        'zh-TW': '還是有不少期待，作為戀人有些事希望對方做到',
        vi: 'Tôi có kỳ vọng khá nhiều. Là người yêu thì có những điều mong họ làm',
        id: 'Aku memang punya harapan. Sebagai pasangan, ada hal yang kuharap mereka lakukan',
    }), 2),
      opt(localeMap({
        ko: '기대가 꽤 있는 편이다. 연인이라면 특별해야 한다고 생각하고 그것을 바란다',
        en: 'Quite a lot. I believe a partner should be special and I want that',
        ja: 'かなりある。恋人は特別であるべきだと思い、それを望む',
        'zh-CN': '期待挺多，恋人应该特别，我也希望如此',
        'zh-TW': '期待挺多，戀人應該特別，我也希望如此',
        vi: 'Khá nhiều. Tôi nghĩ người yêu nên đặc biệt và tôi mong điều đó',
        id: 'Cukup banyak. Aku percaya pasangan harus spesial dan aku menginginkannya',
    }), 3),
    ],
  },
  {
    id: 12,
    question: localeMap({
      ko: '연인과 기대치가 다르다는 걸 느꼈을 때 나는?',
      en: 'When I feel our expectations differ, I:',
      ja: '恋人と期待値が違うと感じたとき、私は？',
      'zh-CN': '感觉和恋人期待不同时，我会？',
      'zh-TW': '感覺和戀人期待不同時，我會？',
      vi: 'Khi cảm thấy kỳ vọng khác nhau, tôi:',
      id: 'Saat merasa harapan kami berbeda, aku:',
    }),
    options: [
      opt(localeMap({
        ko: '크게 문제라고 생각하지 않는다. 달라도 각자 방식대로 하면 된다',
        en: 'Do not see it as a big problem. Different is fine—we can each do our own way',
        ja: '大きな問題とは思わない。違っても各自のやり方でよい',
        'zh-CN': '不觉得是大问题，不同也可以各自的方式',
        'zh-TW': '不覺得是大問題，不同也可以各自的方式',
        vi: 'Không coi là vấn đề lớn. Khác cũng được—mỗi người theo cách mình',
        id: 'Tidak anggap masalah besar. Beda juga oke—masing-masing dengan caranya',
    }), 0),
      opt(localeMap({
        ko: '이야기를 나눠서 조율하면 된다. 서로 다를 수 있다는 걸 인정한다',
        en: 'Think we can talk and adjust. It is okay to be different',
        ja: '話して調整すればよいと思う。違っていてもよい',
        'zh-CN': '觉得可以谈并调整，不同也可以接受',
        'zh-TW': '覺得可以談並調整，不同也可以接受',
        vi: 'Nghĩ có thể nói chuyện và điều chỉnh. Khác nhau cũng được',
        id: 'Pikir bisa bicara dan menyesuaikan. Beda itu wajar',
    }), 1),
      opt(localeMap({
        ko: '맞춰가야 한다고 생각한다. 다르면 불편하고 내 기대치에 맞춰줬으면 하는 마음이 있다',
        en: 'Feel we should align. Difference feels uncomfortable and I want them to match my expectations',
        ja: '合わせていくべきだと思う。違うと居心地が悪く、自分の期待に合わせてほしい',
        'zh-CN': '觉得应该磨合，不同会不自在，希望对方符合我的期待',
        'zh-TW': '覺得應該磨合，不同會不自在，希望對方符合我的期待',
        vi: 'Cảm thấy nên hòa hợp. Khác nhau khó chịu và mong họ khớp kỳ vọng của mình',
        id: 'Merasa harus diselaraskan. Beda terasa tidak nyaman dan berharap mereka sesuai harapanku',
    }), 2),
      opt(localeMap({
        ko: '많이 힘들다. 기대치가 다르면 내가 사랑받지 못한다는 느낌이 든다',
        en: 'Struggle a lot. Different expectations feel like I am not loved',
        ja: 'とてもつらい。期待値が違うと愛されていない気がする',
        'zh-CN': '很难受，期待不同会觉得没被爱着',
        'zh-TW': '很難受，期待不同會覺得沒被愛著',
        vi: 'Rất khó chịu. Kỳ vọng khác nhau cảm giác như mình không được yêu',
        id: 'Sangat berat. Harapan berbeda terasa seperti aku tidak dicintai',
    }), 3),
    ],
  },
];

export const phase3LoveExpectationDiagnosisResults: Phase3LoveExpectationDiagnosisResult[] = [
  {
    type: "Type1",
    emoji: "🌿",
    title: localeMap({
      ko: '연인에게 거의 아무것도 바라지 않는 사람, 기대치 최소형',
      en: 'Someone Who Expects Almost Nothing from a Partner, Minimal Expectation Type',
      ja: '恋人にほとんど何も望まない人、期待値最小型',
      'zh-CN': '对恋人几乎无所求的人，最低期待型',
      'zh-TW': '對戀人幾乎無所求的人，最低期待型',
      vi: 'Người gần như không mong gì ở người yêu, Kiểu kỳ vọng tối thiểu',
      id: 'Orang yang hampir tidak berharap apa pun pada pasangan, Tipe Harapan Minimal',
    }),
    expectationSummary: localeMap({
      ko: '매우 낮음 / 존재만으로 충분한 타입',
      en: 'Very low / Presence alone is enough type',
      ja: '非常に低い / 存在だけで十分なタイプ',
      'zh-CN': '非常低 / 有你在就够的类型',
      'zh-TW': '非常低 / 有你在就夠的類型',
      vi: 'Rất thấp / Chỉ cần có mặt là đủ',
      id: 'Sangat rendah / Kehadiran saja sudah cukup',
    }),
    quote: localeMap({
      ko: '당신은 연인에게 거의 기대하지 않습니다. 있어주는 것만으로 충분하고 그 이상을 요구하는 것이 불편하게 느껴집니다.',
      en: 'You hardly expect anything from your partner. Their presence is enough, and asking for more feels uncomfortable.',
      ja: 'あなたは恋人にほとんど期待しません。そばにいてくれるだけで十分で、それ以上を求めるのは居心地が悪いと感じます。',
      'zh-CN': '你对恋人几乎没什么期待。有他们在就够了，要求更多会让你不自在。',
      'zh-TW': '你對戀人幾乎沒什麼期待。有他們在就夠了，要求更多會讓你不自在。',
      vi: 'Bạn gần như không kỳ vọng gì ở người yêu. Có họ là đủ, và yêu cầu thêm khiến bạn khó chịu.',
      id: 'Kamu hampir tidak berharap apa pun pada pasangan. Kehadiran mereka cukup, dan meminta lebih terasa tidak nyaman.',
    }),
    description: localeMap({
      ko: '연락 빈도에 무감하고 만남이 뜸해도 크게 흔들리지 않으며 힘든 일도 스스로 해결합니다. 이것이 성숙한 것처럼 보이지만 때로는 자신의 필요를 너무 억제하거나 관계에서 충분히 받지 못하고 있다는 신호일 수 있습니다.',
      en: 'You are unmoved by contact frequency, not shaken by sparse meetings, and handle hard things on your own. This can look mature, but sometimes it signals that you suppress your needs or are not receiving enough in the relationship.',
      ja: '連絡頻度に無関心で、会う機会が少なくても大きく揺れず、つらいことも自分で解決します。成熟に見えますが、時には自分の必要を抑えすぎている、または関係で十分に受け取れていないサインかもしれません。',
      'zh-CN': '对联系频率无感，见面少也不太动摇，难事自己解决。这看起来像成熟，但有时可能是过度压抑需求或在关系中没有得到足够回应的信号。',
      'zh-TW': '對聯繫頻率無感，見面少也不太動搖，難事自己解決。這看起來像成熟，但有時可能是過度壓抑需求或在關係中沒有得到足夠回應的訊號。',
      vi: 'Bạn không bận tâm tần suất liên lạc, ít gặp cũng không lay chuyển, và tự xử lý chuyện khó. Trông có vẻ trưởng thành, nhưng đôi khi là dấu hiệu bạn đang kìm nén nhu cầu hoặc chưa nhận đủ trong quan hệ.',
      id: 'Kamu tidak peduli frekuensi kontak, jarang bertemu pun tidak goyah, dan menyelesaikan hal sulit sendiri. Terlihat dewasa, tapi kadang menandakan kamu menekan kebutuhan atau belum cukup menerima dalam hubungan.',
    }),
    expectationType: localeMap({
      ko: '기대치 최소형 🌿',
      en: 'Minimal Expectation Type 🌿',
      ja: '期待値最小型 🌿',
      'zh-CN': '最低期待型 🌿',
      'zh-TW': '最低期待型 🌿',
      vi: 'Kiểu kỳ vọng tối thiểu 🌿',
      id: 'Tipe Harapan Minimal 🌿',
    }),
    expectationKeywords: localeMap({
      ko: '독립·자립·존재만으로 충분·요구 없음',
      en: 'Independence · Self-reliance · Presence is enough · No demands',
      ja: '独立・自立・存在だけで十分・要求なし',
      'zh-CN': '独立·自立·有你在就够·无要求',
      'zh-TW': '獨立·自立·有你在就夠·無要求',
      vi: 'Độc lập · Tự lập · Có mặt là đủ · Không đòi hỏi',
      id: 'Independen · Mandiri · Kehadiran cukup · Tanpa tuntutan',
    }),
    strengths: localeMap({
      ko: '상대방에게 부담을 주지 않음. 관계에서 갈등이 적음. 자립적인 삶이 탄탄함',
      en: 'Does not burden your partner. Less conflict in relationships. A solid independent life',
      ja: '相手に負担をかけない。関係の葛藤が少ない。自立した生活がしっかりしている',
      'zh-CN': '不给对方负担，关系中冲突少，独立生活稳固',
      'zh-TW': '不給對方負擔，關係中衝突少，獨立生活穩固',
      vi: 'Không làm phiền đối phương. Ít xung đột trong quan hệ. Cuộc sống độc lập vững',
      id: 'Tidak membebani pasangan. Konflik dalam hubungan lebih sedikit. Hidup mandiri yang kokoh',
    }),
    cautions: localeMap({
      ko: '기대가 너무 없으면 관계가 얕아지고 상대방이 나에게 신경을 덜 쓰게 될 수 있음\n"나는 바라는 게 없다"고 생각하는데 실제로는 받지 못해서 쌓이는 경우가 있음\n나의 필요를 표현하는 것이 약함이 아님. 연인에게 기대하는 것이 관계를 더 풍요롭게 만들 수 있음',
      en: 'Too little expectation can shallow the relationship and make your partner care less\nYou may think you want nothing while actually accumulating unmet needs\nExpressing your needs is not weakness. Expecting from a partner can enrich the relationship',
      ja: '期待が少なすぎると関係が浅くなり、相手が気にかけなくなることがある\n「望むことがない」と思っていても、実は受け取れずに溜まっている場合がある\n必要を表現することは弱さではない。恋人への期待は関係を豊かにできる',
      'zh-CN': '期待太少关系可能变浅，对方也可能更少关心你\n你以为无所求，实际可能是没得到而累积\n表达需求不是软弱，对恋人有期待能让关系更丰富',
      'zh-TW': '期待太少關係可能變淺，對方也可能更少關心你\n你以為無所求，實際可能是沒得到而累積\n表達需求不是軟弱，對戀人有期待能讓關係更豐富',
      vi: 'Kỳ vọng quá thấp có thể làm quan hệ nông và đối phương ít quan tâm hơn\nBạn nghĩ không mong gì nhưng thực ra đang tích lũy nhu cầu chưa được đáp ứng\nBày tỏ nhu cầu không phải yếu đuối. Kỳ vọng ở người yêu có thể làm quan hệ phong phú hơn',
      id: 'Harapan terlalu sedikit bisa membuat hubungan dangkal dan pasangan lebih acuh\nKamu pikir tidak menginginkan apa pun padahal kebutuhan terpendam\nMengekspresikan kebutuhan bukan kelemahan. Berharap pada pasangan bisa memperkaya hubungan',
    }),
    guidanceAdvice: localeMap({
      ko: '나도 받을 자격이 있다는 것을 인식하기. 작은 것이라도 원하는 것을 표현해보기',
      en: 'Recognize that you deserve to receive too. Try expressing even small things you want',
      ja: '自分も受け取る資格があると認識する。小さなことでも望むことを表現してみる',
      'zh-CN': '认识到你也值得被给予，试着表达哪怕很小的需求',
      'zh-TW': '認識到你也值得被給予，試著表達哪怕很小的需求',
      vi: 'Nhận ra bạn cũng xứng đáng được nhận. Thử bày tỏ cả những điều nhỏ bạn muốn',
      id: 'Sadari bahwa kamu juga layak menerima. Coba ungkapkan hal kecil yang kamu inginkan',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '당신이 바라는 것이 없는 게 아니라 바라도 된다는 것을 모를 수 있습니다. 연인에게 기대해도 괜찮습니다',
      en: 'Maybe it is not that you want nothing—you may not know you are allowed to want. It is okay to expect from your partner.',
      ja: '望むことがないのではなく、望んでよいと知らないのかもしれません。恋人に期待しても大丈夫です。',
      'zh-CN': '也许不是你不想要，而是你不知道可以要。对恋人有期待是可以的。',
      'zh-TW': '也許不是你不想要，而是你不知道可以要。對戀人有期待是可以的。',
      vi: 'Có thể không phải bạn không mong—mà bạn chưa biết mình được phép mong. Kỳ vọng ở người yêu là ổn.',
      id: 'Mungkin bukan kamu tidak menginginkan apa pun—kamu belum tahu boleh berharap. Mengharapkan pasangan itu oke.',
    }),
    shareLine: localeMap({
      ko: '내 연애 기대치: 최소형 🌿 연인에게 거의 아무것도 안 바란다는 거... 있어주는 것만으로 충분하다는 거 맞음 → 나 기대치 이 정도래 ㅠ 너는 몇 점이야?',
      en: 'My love expectations: Minimal Type 🌿 They say I hardly expect anything from my partner... just having them is enough—so true → What\'s your score?',
      ja: '私の恋愛期待値：最小型 🌿 恋人にほとんど何も望まない... いてくれるだけで十分、当たり → あなたは何点？',
      'zh-CN': '我的恋爱期待值：最低型 🌿 说我对恋人几乎无所求... 有你在就够太准了 → 你几分？',
      'zh-TW': '我的戀愛期待值：最低型 🌿 說我對戀人幾乎無所求... 有你在就夠太準了 → 你幾分？',
      vi: 'Kỳ vọng tình yêu: Tối thiểu 🌿 Bảo tôi gần như không mong gì... có là đủ—đúng quá → Bạn mấy điểm?',
      id: 'Harapan cintaku: Minimal 🌿 Katanya aku hampir tidak berharap apa pun... ada saja cukup—bener → Kamu berapa poin?',
    }),
  },
  {
    type: "Type2",
    emoji: "🌱",
    title: localeMap({
      ko: '각자의 삶 위에서 함께하는 사람, 자립 우선형',
      en: 'Someone Who Stays Together on Top of Separate Lives, Independence-First Type',
      ja: 'それぞれの生活の上で一緒にいる人、自立優先型',
      'zh-CN': '在各自生活之上相伴的人，自立优先型',
      'zh-TW': '在各自生活之上相伴的人，自立優先型',
      vi: 'Người bên nhau trên nền cuộc sống riêng, Kiểu ưu tiên độc lập',
      id: 'Orang yang bersama di atas kehidupan masing-masing, Tipe Independen Dulu',
    }),
    expectationSummary: localeMap({
      ko: '낮음 / 독립적이되 필요할 때 함께하는 타입',
      en: 'Low / Independent yet together when needed type',
      ja: '低い / 自立しつつ必要なとき一緒にいるタイプ',
      'zh-CN': '偏低 / 独立但需要时在一起的类型',
      'zh-TW': '偏低 / 獨立但需要時在一起的類型',
      vi: 'Thấp / Độc lập nhưng ở bên khi cần',
      id: 'Rendah / Mandiri tapi bersama saat dibutuhkan',
    }),
    quote: localeMap({
      ko: '당신의 기대치는 건강하게 낮은 편입니다. 연인에게 기대하되 지나치게 의존하지 않는 균형이 있습니다.',
      en: 'Your expectations are healthily on the lower side. You expect from your partner without leaning too much.',
      ja: 'あなたの期待値は健康的に低めです。恋人に期待しつつ、過度に依存しません。',
      'zh-CN': '你的期待值健康地偏低。会对恋人有期待，但不会过度依赖。',
      'zh-TW': '你的期待值健康地偏低。會對戀人有期待，但不會過度依賴。',
      vi: 'Kỳ vọng của bạn ở mức thấp lành mạnh. Bạn kỳ vọng người yêu nhưng không phụ thuộc quá mức.',
      id: 'Harapanmu sehat di sisi rendah. Kamu berharap pada pasangan tanpa terlalu bergantung.',
    }),
    description: localeMap({
      ko: '연락이 뜸해도 크게 불안하지 않고 각자의 생활을 존중하며 힘든 일은 스스로 처리하다가 필요할 때 연인에게 기댑니다. 관계가 내 삶의 전부가 되지 않는 건강한 구조를 가지고 있습니다.',
      en: 'Sparse contact does not make you anxious. You respect each other\'s lives, handle hard things yourself, and lean on your partner when needed. The relationship is not your whole life—a healthy structure.',
      ja: '連絡が少なくても大きく不安にならず、それぞれの生活を尊重し、つらいことは自分で処理し、必要なとき恋人に頼ります。関係が人生の全てではない健全な構造です。',
      'zh-CN': '联系少也不太焦虑，尊重各自生活，难事自己处理，需要时再依靠恋人。关系不是人生的全部，结构健康。',
      'zh-TW': '聯繫少也不太焦慮，尊重各自生活，難事自己處理，需要時再依靠戀人。關係不是人生的全部，結構健康。',
      vi: 'Ít liên lạc cũng không lo nhiều. Tôn trọng cuộc sống riêng, tự xử lý khó khăn và dựa vào người yêu khi cần. Quan hệ không phải cả cuộc đời—cấu trúc lành mạnh.',
      id: 'Kontak jarang tidak membuat cemas. Menghormati hidup masing-masing, menyelesaikan hal sulit sendiri, dan bersandar pada pasangan saat perlu. Hubungan bukan seluruh hidup—struktur sehat.',
    }),
    expectationType: localeMap({
      ko: '자립 우선형 🌱',
      en: 'Independence-First Type 🌱',
      ja: '自立優先型 🌱',
      'zh-CN': '自立优先型 🌱',
      'zh-TW': '自立優先型 🌱',
      vi: 'Kiểu ưu tiên độc lập 🌱',
      id: 'Tipe Independen Dulu 🌱',
    }),
    expectationKeywords: localeMap({
      ko: '자립·독립·필요할 때 함께·적당한 거리',
      en: 'Self-reliance · Independence · Together when needed · Healthy distance',
      ja: '自立・独立・必要なとき一緒・適度な距離',
      'zh-CN': '自立·独立·需要时在一起·适当距离',
      'zh-TW': '自立·獨立·需要時在一起·適當距離',
      vi: 'Tự lập · Độc lập · Bên nhau khi cần · Khoảng cách vừa phải',
      id: 'Mandiri · Independen · Bersama saat perlu · Jarak sehat',
    }),
    strengths: localeMap({
      ko: '관계에서 집착이 없어 상대방이 편안함을 느낌. 각자의 성장을 방해하지 않음',
      en: 'No clinginess in relationships—your partner feels at ease. You do not block each other\'s growth',
      ja: '関係に執着がなく、相手が楽に感じる。お互いの成長を妨げない',
      'zh-CN': '关系中不黏人，对方感到轻松，不阻碍彼此成长',
      'zh-TW': '關係中不黏人，對方感到輕鬆，不阻礙彼此成長',
      vi: 'Không bám víu trong quan hệ—đối phương cảm thấy thoải mái. Không cản trở sự phát triển của nhau',
      id: 'Tidak clingy dalam hubungan—pasangan merasa nyaman. Tidak menghalangi pertumbuhan masing-masing',
    }),
    cautions: localeMap({
      ko: '기대가 너무 낮으면 상대방이 내가 자신에게 관심이 없다고 느낄 수 있음. 가끔 나의 필요를 더 표현하는 연습 필요',
      en: 'Expectations that are too low may make your partner feel you are not interested. Practice expressing your needs more often',
      ja: '期待が低すぎると、相手が関心がないと感じることがある。必要をもっと表現する練習が必要',
      'zh-CN': '期待太低可能让对方觉得你不关心，需要更多练习表达需求',
      'zh-TW': '期待太低可能讓對方覺得你不關心，需要更多練習表達需求',
      vi: 'Kỳ vọng quá thấp có thể khiến đối phương nghĩ bạn không quan tâm. Cần luyện bày tỏ nhu cầu hơn',
      id: 'Harapan terlalu rendah bisa membuat pasangan merasa kamu tidak tertarik. Latih mengekspresikan kebutuhan lebih sering',
    }),
    guidanceAdvice: localeMap({
      ko: '독립적이고 서로의 공간을 존중하는 타입',
      en: 'A partner who is independent and respects each other\'s space',
      ja: '独立していてお互いの空間を尊重するタイプ',
      'zh-CN': '独立且尊重彼此空间的类型',
      'zh-TW': '獨立且尊重彼此空間的類型',
      vi: 'Người độc lập và tôn trọng không gian riêng của nhau',
      id: 'Pasangan yang independen dan menghormati ruang masing-masing',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '당신의 기대치는 건강한 범위에 있습니다. 이 균형을 유지하면서 나의 필요도 조금 더 표현해보세요',
      en: 'Your expectations are in a healthy range. Keep this balance and try expressing your needs a little more.',
      ja: 'あなたの期待値は健康的な範囲にあります。このバランスを保ちながら、必要ももう少し表現してみてください。',
      'zh-CN': '你的期待值在健康范围内。保持这个平衡，也试着多表达一点需求。',
      'zh-TW': '你的期待值在健康範圍內。保持這個平衡，也試著多表達一點需求。',
      vi: 'Kỳ vọng của bạn ở mức lành mạnh. Giữ cân bằng này và thử bày tỏ nhu cầu nhiều hơn một chút.',
      id: 'Harapanmu berada di rentang sehat. Pertahankan keseimbangan ini dan coba ungkapkan kebutuhan sedikit lebih banyak.',
    }),
    shareLine: localeMap({
      ko: '내 연애 기대치: 자립 우선형 🌱 독립적이되 필요할 때 함께하는 타입이래... 각자 생활 존중하는 거 맞음 → 나 기대치 이 정도래 너는 어떤 유형이야?',
      en: 'My love expectations: Independence-First 🌱 Independent yet together when needed... respecting separate lives—so true → What type are you?',
      ja: '私の恋愛期待値：自立優先型 🌱 独立しつつ必要なとき一緒... 各自の生活を尊重、当たり → あなたはどのタイプ？',
      'zh-CN': '我的恋爱期待值：自立优先型 🌱 独立但需要时在一起... 尊重各自生活太准 → 你是什么类型？',
      'zh-TW': '我的戀愛期待值：自立優先型 🌱 獨立但需要時在一起... 尊重各自生活太準 → 你是什麼類型？',
      vi: 'Kỳ vọng tình yêu: Ưu tiên độc lập 🌱 Độc lập nhưng ở bên khi cần... tôn trọng cuộc sống riêng—đúng quá → Bạn loại nào?',
      id: 'Harapan cintaku: Independen Dulu 🌱 Mandiri tapi bersama saat perlu... hormati hidup masing-masing—bener → Kamu tipe apa?',
    }),
  },
  {
    type: "Type3",
    emoji: "⚖️",
    title: localeMap({
      ko: '주고받는 균형을 원하는 사람, 균형 기대형',
      en: 'Someone Who Wants Balanced Give-and-Take, Balanced Expectation Type',
      ja: '与え合うバランスを望む人、均衡期待型',
      'zh-CN': '想要互相给予平衡的人，均衡期待型',
      'zh-TW': '想要互相給予平衡的人，均衡期待型',
      vi: 'Người mong sự cân bằng cho-nhận, Kiểu kỳ vọng cân bằng',
      id: 'Orang yang menginginkan keseimbangan saling memberi, Tipe Harapan Seimbang',
    }),
    expectationSummary: localeMap({
      ko: '보통 / 서로 적당히 맞춰가는 타입',
      en: 'Moderate / Mutually adjusting type',
      ja: '普通 / お互いに適度に合わせ合うタイプ',
      'zh-CN': '适中 / 彼此适度磨合的类型',
      'zh-TW': '適中 / 彼此適度磨合的類型',
      vi: 'Vừa phải / Cùng điều chỉnh lẫn nhau',
      id: 'Sedang / Saling menyesuaikan dengan proporsional',
    }),
    quote: localeMap({
      ko: '당신의 기대치는 적정 수준입니다. 너무 많이 바라지도 않고 너무 아무것도 안 바라지도 않습니다.',
      en: 'Your expectations are at a healthy level—not too much, not too little.',
      ja: 'あなたの期待値は適正な水準です。多すぎず少なすぎません。',
      'zh-CN': '你的期待值在合适水平，不多不少。',
      'zh-TW': '你的期待值在合適水準，不多不少。',
      vi: 'Kỳ vọng của bạn ở mức phù hợp—không quá nhiều cũng không quá ít.',
      id: 'Harapanmu di level sehat—tidak terlalu banyak, tidak terlalu sedikit.',
    }),
    description: localeMap({
      ko: '연락·만남·감정 지지 모두에서 서로 주고받는 균형을 원합니다. 기대가 충족되면 만족하고 충족되지 않으면 이야기를 꺼낼 수 있는 타입입니다. 가장 지속 가능한 연애 기대치 범위에 있습니다.',
      en: 'You want balance in contact, meetings, and emotional support. When expectations are met you feel satisfied; when not, you can talk about it. You are in the most sustainable range of love expectations.',
      ja: '連絡・会う頻度・感情サポートすべてで互いに与え合うバランスを望みます。期待が満たされれば満足し、満たされなければ話せるタイプです。最も持続可能な恋愛期待値の範囲にいます。',
      'zh-CN': '在联系、见面、情感支持上都希望互相平衡。期待被满足会满意，不满足也能谈。处于最可持续的恋爱期待范围。',
      'zh-TW': '在聯繫、見面、情感支持上都希望互相平衡。期待被滿足會滿意，不滿足也能談。處於最可持續的戀愛期待範圍。',
      vi: 'Bạn mong sự cân bằng trong liên lạc, gặp gỡ và hỗ trợ cảm xúc. Được đáp ứng thì hài lòng, không thì nói chuyện được. Bạn ở vùng kỳ vọng tình yêu bền vững nhất.',
      id: 'Kamu menginginkan keseimbangan dalam kontak, pertemuan, dan dukungan emosional. Terpenuhi maka puas; jika tidak, bisa dibicarakan. Kamu berada di rentang harapan cinta paling sustainable.',
    }),
    expectationType: localeMap({
      ko: '균형 기대형 ⚖️',
      en: 'Balanced Expectation Type ⚖️',
      ja: '均衡期待型 ⚖️',
      'zh-CN': '均衡期待型 ⚖️',
      'zh-TW': '均衡期待型 ⚖️',
      vi: 'Kiểu kỳ vọng cân bằng ⚖️',
      id: 'Tipe Harapan Seimbang ⚖️',
    }),
    expectationKeywords: localeMap({
      ko: '균형·주고받음·조율·적정 수준·상호성',
      en: 'Balance · Give-and-take · Adjustment · Healthy level · Reciprocity',
      ja: '均衡・与え合い・調整・適正水準・相互性',
      'zh-CN': '均衡·互相给予·磨合·合适水平·互惠',
      'zh-TW': '均衡·互相給予·磨合·合適水準·互惠',
      vi: 'Cân bằng · Cho-nhận · Điều chỉnh · Mức phù hợp · Tương hỗ',
      id: 'Keseimbangan · Saling memberi · Penyesuaian · Level sehat · Timbal balik',
    }),
    strengths: localeMap({
      ko: '기대치가 현실적이어서 실망이 적음. 이야기를 통해 서로 조율할 수 있는 능력',
      en: 'Realistic expectations mean less disappointment. You can adjust through conversation',
      ja: '期待値が現実的で失望が少ない。会話を通じて互いに調整できる',
      'zh-CN': '期待现实，失望少，能通过沟通互相调整',
      'zh-TW': '期待現實，失望少，能通過溝通互相調整',
      vi: 'Kỳ vọng thực tế nên ít thất vọng. Có thể điều chỉnh qua trò chuyện',
      id: 'Harapan realistis sehingga kecewa lebih sedikit. Bisa menyesuaikan lewat komunikasi',
    }),
    cautions: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    guidanceAdvice: localeMap({
      ko: '소통을 중요하게 여기고 서로 조율할 수 있는 타입',
      en: 'A partner who values communication and can adjust together',
      ja: 'コミュニケーションを大切にし、互いに調整できるタイプ',
      'zh-CN': '重视沟通、能一起磨合的类型',
      'zh-TW': '重視溝通、能一起磨合的類型',
      vi: 'Người coi trọng giao tiếp và có thể cùng điều chỉnh',
      id: 'Pasangan yang menghargai komunikasi dan bisa menyesuaikan bersama',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '당신의 기대치는 가장 건강한 범위에 있습니다. 이 균형을 유지하는 것이 관계를 오래 이어가는 힘입니다',
      en: 'Your expectations are in the healthiest range. Keeping this balance is what helps relationships last.',
      ja: 'あなたの期待値は最も健康的な範囲にあります。この均衡を保つことが関係を長く続ける力です。',
      'zh-CN': '你的期待值在最健康范围，保持这个平衡是让关系长久的力量。',
      'zh-TW': '你的期待值在最健康範圍，保持這個平衡是讓關係長久的力量。',
      vi: 'Kỳ vọng của bạn ở vùng lành mạnh nhất. Giữ cân bằng này là sức mạnh giúp quan hệ bền lâu.',
      id: 'Harapanmu berada di rentang paling sehat. Menjaga keseimbangan ini yang membuat hubungan bertahan lama.',
    }),
    shareLine: localeMap({
      ko: '내 연애 기대치: 균형 기대형 ⚖️ 적정 수준이래... 너무 많이 바라지도 않고 너무 안 바라지도 않는 거 맞음 → 나 기대치 이 정도래 커플이면 둘이 같이 해봐',
      en: 'My love expectations: Balanced Type ⚖️ They say I\'m at a healthy level... not too much, not too little—so true → Couples should try together',
      ja: '私の恋愛期待値：均衡型 ⚖️ 適正水準だって... 多すぎず少なすぎず、当たり → カップルなら二人でやってみて',
      'zh-CN': '我的恋爱期待值：均衡型 ⚖️ 说我是合适水平... 不多不少太准 → 情侣一起做吧',
      'zh-TW': '我的戀愛期待值：均衡型 ⚖️ 說我是合適水準... 不多不少太準 → 情侶一起做吧',
      vi: 'Kỳ vọng tình yêu: Cân bằng ⚖️ Bảo mức vừa phải... không quá nhiều cũng không quá ít—đúng quá → Cặp đôi làm cùng nhau nhé',
      id: 'Harapan cintaku: Seimbang ⚖️ Katanya level sehat... tidak terlalu banyak atau sedikit—bener → Pasangan coba berdua',
    }),
  },
  {
    type: "Type4",
    emoji: "💙",
    title: localeMap({
      ko: '내 마음을 알아줬으면 하는 사람, 세심 배려 기대형',
      en: 'Someone Who Wants Their Heart Understood, Attentive Care Expectation Type',
      ja: '自分の気持ちを分かってほしい人、細やかな配慮期待型',
      'zh-CN': '希望被懂心的人，细致关怀期待型',
      'zh-TW': '希望被懂心的人，細緻關懷期待型',
      vi: 'Người mong được hiểu trái tim mình, Kiểu kỳ vọng quan tâm tinh tế',
      id: 'Orang yang ingin hatinya dipahami, Tipe Harapan Perhatian Halus',
    }),
    expectationSummary: localeMap({
      ko: '높음 / 말하지 않아도 알아줬으면 하는 타입',
      en: 'High / Wants to be understood without having to say it type',
      ja: '高い / 言わなくても分かってほしいタイプ',
      'zh-CN': '偏高 / 希望不说也能被懂的类型',
      'zh-TW': '偏高 / 希望不說也能被懂的類型',
      vi: 'Cao / Mong được hiểu dù không nói',
      id: 'Tinggi / Ingin dipahami tanpa harus bilang',
    }),
    quote: localeMap({
      ko: '당신은 연인이 나를 깊이 이해하고 먼저 알아채줬으면 하는 기대가 있습니다. 표현하지 않아도 느껴줬으면 하는 마음입니다.',
      en: 'You expect your partner to understand you deeply and notice things first—even without you saying them.',
      ja: 'あなたは恋人が深く理解し、言わなくても先に気づいてほしいという期待があります。',
      'zh-CN': '你期待恋人深度理解你，即使不说也希望对方先察觉。',
      'zh-TW': '你期待戀人深度理解你，即使不說也希望對方先察覺。',
      vi: 'Bạn kỳ vọng người yêu hiểu mình sâu và nhận ra trước—dù bạn chưa nói.',
      id: 'Kamu berharap pasangan memahami dan menyadari hal-hal lebih dulu—meski kamu belum bilang.',
    }),
    description: localeMap({
      ko: '말하지 않아도 기분을 눈치채주고 먼저 다가와주고 나를 위해 무언가를 내려놓을 수 있다는 것을 보여주길 기대합니다. 이 기대가 충족될 때 깊이 사랑받는 느낌이 생깁니다.',
      en: 'You hope they notice your mood without words, reach out first, and show they can set things aside for you. When these expectations are met, you feel deeply loved.',
      ja: '言わなくても気分を察して、先に近づき、自分のために何かを下ろせることを見せてほしいと期待します。この期待が満たされると深く愛されていると感じます。',
      'zh-CN': '希望对方不说也能察觉心情、主动靠近、为你放下一些事。这些期待被满足时会感到被深深爱着。',
      'zh-TW': '希望對方不說也能察覺心情、主動靠近、為你放下一些事。這些期待被滿足時會感到被深深愛著。',
      vi: 'Bạn mong họ nhận ra tâm trạng dù không nói, chủ động lại gần và thể hiện có thể buông bỏ vì bạn. Khi được đáp ứng, bạn cảm thấy được yêu sâu sắc.',
      id: 'Kamu berharap mereka sadari mood tanpa kata, mendekat dulu, dan menunjukkan bisa menurunkan hal-hal demi kamu. Saat terpenuhi, kamu merasa dicintai dalam-dalam.',
    }),
    expectationType: localeMap({
      ko: '세심 배려 기대형 💙',
      en: 'Attentive Care Expectation Type 💙',
      ja: '細やかな配慮期待型 💙',
      'zh-CN': '细致关怀期待型 💙',
      'zh-TW': '細緻關懷期待型 💙',
      vi: 'Kiểu kỳ vọng quan tâm tinh tế 💙',
      id: 'Tipe Harapan Perhatian Halus 💙',
    }),
    expectationKeywords: localeMap({
      ko: '이해·눈치채줌·세심함·깊은 공감·나를 알아줌',
      en: 'Understanding · Noticing · Thoughtfulness · Deep empathy · Being known',
      ja: '理解・気づき・細やかさ・深い共感・分かってもらう',
      'zh-CN': '理解·察觉·细致·深度共情·被懂得',
      'zh-TW': '理解·察覺·細緻·深度共情·被懂得',
      vi: 'Hiểu · Nhận ra · Quan tâm · Đồng cảm sâu · Được hiểu',
      id: 'Pemahaman · Menyadari · Perhatian · Empati mendalam · Dikenal',
    }),
    strengths: localeMap({
      ko: '관계에서 깊은 연결을 추구함. 상대방을 잘 이해하려 노력함',
      en: 'Pursues deep connection in relationships. Tries hard to understand your partner',
      ja: '関係で深いつながりを求める。相手を理解しようと努力する',
      'zh-CN': '在关系中追求深度连接，也努力理解对方',
      'zh-TW': '在關係中追求深度連接，也努力理解對方',
      vi: 'Theo đuổi kết nối sâu trong quan hệ. Cố gắng hiểu đối phương',
      id: 'Mengejar koneksi mendalam dalam hubungan. Berusaha memahami pasangan',
    }),
    cautions: localeMap({
      ko: '"말하지 않아도 알아야지"라는 기대는 충족되지 않을 때 큰 실망으로 이어짐\n사람마다 눈치채는 능력이 다름. 표현을 통해 알려주는 것이 더 빠를 수 있음\n기대를 표현으로 바꿔보기. "이럴 때 이렇게 해줬으면 해"가 관계를 훨씬 편하게 만듦',
      en: 'Expecting "you should know without me saying" leads to big disappointment when unmet\nPeople differ in how well they read others. Telling them directly can be faster\nTry turning expectations into words. "When this happens, I\'d love it if you..." makes relationships easier',
      ja: '「言わなくても分かるべき」という期待は満たされないと大きな失望につながる\n人によって察する力は違う。表現で伝える方が早い場合がある\n期待を言葉に変えてみる。「こういう時こうしてほしい」が関係をずっと楽にする',
      'zh-CN': '“不说也该懂”的期待未满足时会大失望\n每个人察觉能力不同，直接表达可能更快\n把期待变成语言，“这种时候希望你怎么做”会让关系轻松很多',
      'zh-TW': '「不說也該懂」的期待未滿足時會大失望\n每個人察覺能力不同，直接表達可能更快\n把期待變成語言，「這種時候希望你怎麼做」會讓關係輕鬆很多',
      vi: 'Kỳ vọng “không nói cũng phải biết” dẫn đến thất vọng lớn khi không được đáp ứng\nMỗi người khác nhau về khả năng nhận ra. Nói thẳng có thể nhanh hơn\nThử biến kỳ vọng thành lời nói. “Lúc này mình muốn bạn...” giúp quan hệ dễ hơn nhiều',
      id: 'Mengharap "harusnya tahu tanpa dibilang" menimbulkan kekecewaan besar saat tidak terpenuhi\nSetiap orang berbeda dalam membaca perasaan. Mengungkapkan langsung bisa lebih cepat\nCoba ubah harapan jadi kata-kata. "Saat begini, aku ingin kamu..." membuat hubungan jauh lebih mudah',
    }),
    guidanceAdvice: localeMap({
      ko: '감수성이 높고 상대방 감정에 민감한 타입',
      en: 'A partner who is sensitive and attuned to emotions',
      ja: '感受性が高く、相手の感情に敏感なタイプ',
      'zh-CN': '感受力强、对情绪敏感的类型',
      'zh-TW': '感受力強、對情緒敏感的類型',
      vi: 'Người nhạy cảm và tinh ý với cảm xúc',
      id: 'Pasangan yang sensitif dan peka terhadap emosi',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '당신이 바라는 것들은 사랑받고 싶다는 자연스러운 마음입니다. 그 마음을 표현으로 바꾸면 훨씬 빠르게 채워질 수 있습니다',
      en: 'What you want is a natural wish to feel loved. Turning that wish into words can fill you much faster.',
      ja: 'あなたが望むことは愛されたいという自然な気持ちです。その気持ちを言葉に変えれば、ずっと早く満たされます。',
      'zh-CN': '你所渴望的是想被爱的自然心愿，把它变成表达会更快被满足。',
      'zh-TW': '你所渴望的是想被愛的自然心願，把它變成表達會更快被滿足。',
      vi: 'Điều bạn mong là mong muốn tự nhiên được yêu. Biến nó thành lời nói sẽ lấp đầy nhanh hơn nhiều.',
      id: 'Yang kamu inginkan adalah keinginan alami untuk merasa dicintai. Mengubahnya jadi kata-kata bisa memenuhi jauh lebih cepat.',
    }),
    shareLine: localeMap({
      ko: '내 연애 기대치: 세심 배려 기대형 💙 말 안 해도 알아줬으면 하는 타입이래... \'말해야 알아?\' 가 제일 힘든 말인 거 맞음 ㅠ → 나 기대치 이 정도래 너는?',
      en: 'My love expectations: Attentive Care 💙 They say I want to be understood without saying... \'You should just know\' is the hardest phrase—so true → What\'s yours?',
      ja: '私の恋愛期待値：細やか配慮型 💙 言わなくても分かってほしいタイプ... 「言わなきゃ分からないの？」が一番つらい、当たり → あなたは？',
      'zh-CN': '我的恋爱期待值：细致关怀型 💙 说不说也该懂... “说了才懂？”最难听太准 → 你呢？',
      'zh-TW': '我的戀愛期待值：細緻關懷型 💙 說不說也該懂... 「說了才懂？」最難聽太準 → 你呢？',
      vi: 'Kỳ vọng tình yêu: Quan tâm tinh tế 💙 Bảo mong được hiểu dù không nói... \'Phải nói mới biết?\' là câu khó nhất—đúng quá → Còn bạn?',
      id: 'Harapan cintaku: Perhatian Halus 💙 Katanya ingin dipahami tanpa bilang... \'Harus bilang dulu?\' paling menyakitkan—bener → Kamu?',
    }),
  },
  {
    type: "Type5",
    emoji: "🌟",
    title: localeMap({
      ko: '연인에게 많은 것을 원하는 사람, 높은 기대치형',
      en: 'Someone Who Wants a Lot from a Partner, High Expectation Type',
      ja: '恋人に多くを望む人、高い期待値型',
      'zh-CN': '对恋人想要很多的人，高期待型',
      'zh-TW': '對戀人想要很多的人，高期待型',
      vi: 'Người mong nhiều ở người yêu, Kiểu kỳ vọng cao',
      id: 'Orang yang menginginkan banyak dari pasangan, Tipe Harapan Tinggi',
    }),
    expectationSummary: localeMap({
      ko: '매우 높음 / 연인이 삶의 큰 부분을 채워줬으면 하는 타입',
      en: 'Very high / Wants partner to fill a large part of life type',
      ja: '非常に高い / 恋人が人生の大きな部分を満たしてほしいタイプ',
      'zh-CN': '很高 / 希望恋人填满生活大部分的类型',
      'zh-TW': '很高 / 希望戀人填滿生活大部分的類型',
      vi: 'Rất cao / Mong người yêu lấp đầy phần lớn cuộc sống',
      id: 'Sangat tinggi / Ingin pasangan mengisi sebagian besar hidup',
    }),
    quote: localeMap({
      ko: '당신은 연인에게 많은 것을 기대합니다. 연락·만남·이해·미래·헌신 모든 영역에서 충분히 받고 싶습니다.',
      en: 'You expect a lot from your partner. You want to receive enough in contact, meetings, understanding, future, and devotion.',
      ja: 'あなたは恋人に多くを期待します。連絡・会う頻度・理解・未来・献身すべての領域で十分に受け取りたいと思います。',
      'zh-CN': '你对恋人期待很多，希望在联系、见面、理解、未来、奉献各层面都足够被满足。',
      'zh-TW': '你對戀人期待很多，希望在聯繫、見面、理解、未來、奉獻各層面都足夠被滿足。',
      vi: 'Bạn kỳ vọng nhiều ở người yêu. Bạn muốn nhận đủ về liên lạc, gặp gỡ, hiểu biết, tương lai và cống hiến.',
      id: 'Kamu berharap banyak pada pasangan. Kamu ingin menerima cukup dalam kontak, pertemuan, pemahaman, masa depan, dan pengorbanan.',
    }),
    description: localeMap({
      ko: '연락이 늦으면 불안해지고 만남이 줄면 관계가 식는 것 같고 힘들 때 먼저 나서줬으면 하며 미래 계획도 함께 세우고 싶습니다. 이 기대들이 충족될 때 사랑받는다는 느낌이 강하게 옵니다.',
      en: 'Late replies make you anxious, fewer meetings feel like cooling off, you want them to step up when you struggle, and you want to plan the future together. When these expectations are met, you strongly feel loved.',
      ja: '返信が遅いと不安になり、会う回数が減ると関係が冷めるように感じ、つらい時に先に出てきてほしく、未来計画も一緒に立てたい。これらが満たされると強く愛されていると感じます。',
      'zh-CN': '回复慢会不安，见面少像关系变冷，难过时希望对方先站出来，也想一起规划未来。这些被满足时会强烈感到被爱。',
      'zh-TW': '回覆慢會不安，見面少像關係變冷，難過時希望對方先站出來，也想一起規劃未來。這些被滿足時會強烈感到被愛。',
      vi: 'Trả lời chậm khiến lo, ít gặp cảm giác nguội lạnh, lúc khó mong họ chủ động, và muốn lập kế hoạch tương lai cùng nhau. Khi được đáp ứng, bạn cảm thấy được yêu mạnh mẽ.',
      id: 'Balasan telat membuat cemas, pertemuan berkurang terasa hubungan mendingin, saat sulit ingin mereka maju dulu, dan ingin merencanakan masa depan bersama. Saat terpenuhi, kamu sangat merasa dicintai.',
    }),
    expectationType: localeMap({
      ko: '높은 기대치형 🌟',
      en: 'High Expectation Type 🌟',
      ja: '高い期待値型 🌟',
      'zh-CN': '高期待型 🌟',
      'zh-TW': '高期待型 🌟',
      vi: 'Kiểu kỳ vọng cao 🌟',
      id: 'Tipe Harapan Tinggi 🌟',
    }),
    expectationKeywords: localeMap({
      ko: '높은 기대·충분히 받고 싶음·연결·헌신·안심',
      en: 'High expectations · Want to receive enough · Connection · Devotion · Reassurance',
      ja: '高い期待・十分に受け取りたい・つながり・献身・安心',
      'zh-CN': '高期待·想充分得到·连接·奉献·安心',
      'zh-TW': '高期待·想充分得到·連接·奉獻·安心',
      vi: 'Kỳ vọng cao · Muốn nhận đủ · Kết nối · Cống hiến · An tâm',
      id: 'Harapan tinggi · Ingin menerima cukup · Koneksi · Pengorbanan · Rasa aman',
    }),
    strengths: localeMap({
      ko: '관계에 진지하게 임함. 사랑을 깊이 받고 싶은 만큼 줄 준비도 되어있음',
      en: 'Takes relationships seriously. As much as you want to receive love, you are ready to give deeply',
      ja: '関係に真剣に向き合う。深く受け取りたい分、与える準備もできている',
      'zh-CN': '对关系很认真，想深度接收爱的同时也准备深度给予',
      'zh-TW': '對關係很認真，想深度接收愛的同時也準備深度給予',
      vi: 'Nghiêm túc với quan hệ. Muốn nhận tình yêu sâu thì cũng sẵn sàng cho đi sâu',
      id: 'Serius dalam hubungan. Sebesar keinginan menerima cinta, kamu siap memberi dalam-dalam',
    }),
    cautions: localeMap({
      ko: '기대치가 높을수록 충족되지 않았을 때 실망과 상처가 큼\n모든 기대를 한 사람이 채워줄 수 없음. 일부는 친구·가족·자신에게서 채우는 분산 필요\n기대치를 상대방에게 명확히 표현하기. 알아서 해주길 바라면 갈등이 생김',
      en: 'The higher the expectations, the bigger the hurt when unmet\nOne person cannot fill every expectation. Some needs should come from friends, family, or yourself\nExpress expectations clearly. Hoping they will just know creates conflict',
      ja: '期待値が高いほど満たされないときの失望と傷が大きい\nすべての期待を一人で満たすことはできない。一部は友人・家族・自分から満たす分散が必要\n期待値を相手に明確に伝える。察してほしいだけだと葛藤が生じる',
      'zh-CN': '期待越高，未满足时失望和伤害越大\n一个人无法满足所有期待，部分需求要来自朋友、家人或自己\n明确表达期待，只等对方自己懂会产生冲突',
      'zh-TW': '期待越高，未滿足時失望和傷害越大\n一個人無法滿足所有期待，部分需求要來自朋友、家人或自己\n明確表達期待，只等對方自己懂會產生衝突',
      vi: 'Kỳ vọng càng cao, thất vọng và tổn thương càng lớn khi không được đáp ứng\nMột người không thể lấp mọi kỳ vọng. Một phần cần từ bạn bè, gia đình hoặc bản thân\nBày tỏ kỳ vọng rõ ràng. Chỉ mong họ tự hiểu sẽ gây xung đột',
      id: 'Semakin tinggi harapan, semakin besar luka saat tidak terpenuhi\nSatu orang tidak bisa memenuhi semua harapan. Sebagian perlu dari teman, keluarga, atau diri sendiri\nUngkapkan harapan dengan jelas. Hanya berharap mereka pahat sendiri menimbulkan konflik',
    }),
    guidanceAdvice: localeMap({
      ko: '헌신적이고 표현이 풍부하며 관계에 에너지를 많이 쏟는 타입',
      en: 'A devoted partner with rich expression who invests a lot in the relationship',
      ja: '献身的で表現が豊かで、関係に多くのエネルギーを注ぐタイプ',
      'zh-CN': '奉献、表达丰富、对关系投入很多的类型',
      'zh-TW': '奉獻、表達豐富、對關係投入很多的類型',
      vi: 'Người tận tụy, giàu sự bày tỏ và đầu tư nhiều vào quan hệ',
      id: 'Pasangan yang setia, ekspresif, dan banyak menginvestasikan energi pada hubungan',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '당신이 원하는 사랑의 크기가 큰 것은 잘못이 아닙니다. 다만 그 크기를 상대방이 알아야 맞춰줄 수 있습니다',
      en: 'Wanting a big love is not wrong. But your partner needs to know the size to meet it.',
      ja: '大きな愛を望むことは間違いではありません。ただ、その大きさを相手が知らなければ合わせられません。',
      'zh-CN': '想要很大的爱没有错，但对方需要知道大小才能配合。',
      'zh-TW': '想要很大的愛沒有錯，但對方需要知道大小才能配合。',
      vi: 'Mong một tình yêu lớn không sai. Nhưng đối phương cần biết kích cỡ mới đáp ứng được.',
      id: 'Menginginkan cinta yang besar bukan salah. Tapi pasangan perlu tahu ukurannya agar bisa menyesuaikan.',
    }),
    shareLine: localeMap({
      ko: '내 연애 기대치: 높은 기대치형 🌟 연인에게 많은 걸 바란다는 거... 기대치가 높을수록 실망도 크다는 거 뜨끔 ㅠ → 나 기대치 이 정도래 너는 몇 점이야?',
      en: 'My love expectations: High Type 🌟 They say I want a lot from my partner... higher expectations, bigger disappointment—ouch, so true → What\'s your score?',
      ja: '私の恋愛期待値：高期待型 🌟 恋人に多くを望む... 期待が高いほど失望も大きい、刺さる ㅠ → あなたは何点？',
      'zh-CN': '我的恋爱期待值：高期待型 🌟 说我对恋人想要很多... 期待越高失望越大扎心了 → 你几分？',
      'zh-TW': '我的戀愛期待值：高期待型 🌟 說我對戀人想要很多... 期待越高失望越大扎心了 → 你幾分？',
      vi: 'Kỳ vọng tình yêu: Cao 🌟 Bảo tôi mong nhiều ở người yêu... kỳ vọng cao thất vọng lớn—đau thật → Bạn mấy điểm?',
      id: 'Harapan cintaku: Tinggi 🌟 Katanya aku ingin banyak dari pasangan... harapan tinggi kecewa besar—kena banget → Kamu berapa poin?',
    }),
  },
  {
    type: "Type6",
    emoji: "❤️",
    title: localeMap({
      ko: '연인이 모든 것이어야 하는 사람, 완전 헌신 기대형',
      en: 'Someone Who Needs Their Partner to Be Everything, Total Devotion Expectation Type',
      ja: '恋人がすべてであるべきだと思う人、完全献身期待型',
      'zh-CN': '认为恋人应该是一切的人，完全奉献期待型',
      'zh-TW': '認為戀人應該是一切的人，完全奉獻期待型',
      vi: 'Người cần người yêu là tất cả, Kiểu kỳ vọng cống hiến toàn phần',
      id: 'Orang yang butuh pasangan menjadi segalanya, Tipe Harapan Pengorbanan Total',
    }),
    expectationSummary: localeMap({
      ko: '극강 / 연인이 삶의 중심이 되어줬으면 하는 타입',
      en: 'Extreme / Wants partner at the center of life type',
      ja: '極めて高い / 恋人が人生の中心にいてほしいタイプ',
      'zh-CN': '极高 / 希望恋人成为人生中心的类型',
      'zh-TW': '極高 / 希望戀人成為人生中心的類型',
      vi: 'Cực cao / Mong người yêu ở trung tâm cuộc sống',
      id: 'Ekstrem / Ingin pasangan di pusat hidup',
    }),
    quote: localeMap({
      ko: '당신에게 연인은 단순한 파트너가 아닙니다. 내 감정·시간·미래의 중심에 함께 있어주길 기대합니다.',
      en: 'Your partner is not just a partner. You expect them to be at the center of your emotions, time, and future.',
      ja: 'あなたにとって恋人は単なるパートナーではありません。感情・時間・未来の中心に一緒にいてほしいと期待します。',
      'zh-CN': '对你来说恋人不只是伴侣，你期待他们在情感、时间、未来的中心与你同在。',
      'zh-TW': '對你來說戀人不只是伴侶，你期待他們在情感、時間、未來的中心與你同在。',
      vi: 'Người yêu không chỉ là bạn đời. Bạn mong họ ở trung tâm cảm xúc, thời gian và tương lai của bạn.',
      id: 'Pasangan bukan sekadar partner. Kamu berharap mereka ada di pusat emosi, waktu, dan masa depanmu.',
    }),
    description: localeMap({
      ko: '항상 연결되어 있는 느낌, 힘든 날 먼저 다가와주는 것, 말하지 않아도 알아채주는 것, 나를 위해 기꺼이 희생하는 것, 함께하는 구체적인 미래. 이 모든 것이 충족되어야 사랑받는 느낌이 드는 타입입니다.',
      en: 'Always feeling connected, being approached first on hard days, being noticed without words, willing sacrifice, and a concrete shared future—all of these must be met for you to feel loved.',
      ja: '常につながっている感覚、つらい日に先に近づいてくれること、言わなくても察してくれること、喜んで犠牲になれること、一緒の具体的な未来。これらすべてが満たされて初めて愛されていると感じるタイプです。',
      'zh-CN': '要一直连着、难过时先靠近、不说也能察觉、愿意牺牲、有具体共同未来——这些都要满足才觉得被爱。',
      'zh-TW': '要一直連著、難過時先靠近、不說也能察覺、願意犧牲、有具體共同未來——這些都要滿足才覺得被愛。',
      vi: 'Luôn cảm giác kết nối, được chủ động lại gần ngày khó khăn, được nhận ra dù không nói, sẵn sàng hy sinh, và tương lai chung cụ thể—tất cả phải được đáp ứng mới cảm thấy được yêu.',
      id: 'Selalu terasa terhubung, didatangi dulu saat hari sulit, disadari tanpa kata, rela berkorban, dan masa depan konkret bersama—semua ini harus terpenuhi agar kamu merasa dicintai.',
    }),
    expectationType: localeMap({
      ko: '완전 헌신 기대형 ❤️',
      en: 'Total Devotion Expectation Type ❤️',
      ja: '完全献身期待型 ❤️',
      'zh-CN': '完全奉献期待型 ❤️',
      'zh-TW': '完全奉獻期待型 ❤️',
      vi: 'Kiểu kỳ vọng cống hiến toàn phần ❤️',
      id: 'Tipe Harapan Pengorbanan Total ❤️',
    }),
    expectationKeywords: localeMap({
      ko: '완전한 헌신·모든 것을 함께·항상 연결·나의 중심',
      en: 'Total devotion · Everything together · Always connected · My center',
      ja: '完全な献身・すべてを一緒に・常につながる・私の中心',
      'zh-CN': '完全奉献·一切都一起·始终连接·我的中心',
      'zh-TW': '完全奉獻·一切都一起·始終連接·我的中心',
      vi: 'Cống hiến toàn phần · Mọi thứ cùng nhau · Luôn kết nối · Trung tâm của tôi',
      id: 'Pengorbanan total · Segalanya bersama · Selalu terhubung · Pusat hidupku',
    }),
    strengths: localeMap({
      ko: '관계에 모든 것을 줄 준비가 되어있음. 깊고 강렬한 사랑을 할 수 있음',
      en: 'Ready to give everything to the relationship. Capable of deep, intense love',
      ja: '関係にすべてを捧げる準備がある。深く強烈な愛ができる',
      'zh-CN': '准备为关系付出一切，能进行深度而强烈的爱',
      'zh-TW': '準備為關係付出一切，能進行深度而強烈的愛',
      vi: 'Sẵn sàng cho đi tất cả vì quan hệ. Có thể yêu sâu và mãnh liệt',
      id: 'Siap memberikan segalanya untuk hubungan. Mampu mencintai dalam-dalam dan intens',
    }),
    cautions: localeMap({
      ko: '한 사람이 이 모든 기대를 채워주기는 매우 어려움. 기대치와 현실의 괴리가 지속되면 관계에서 지속적인 실망이 생김\n연인에 대한 기대가 클수록 의존도가 높아지고 연인이 부담을 느낄 수 있음\n나의 일부를 나 자신이 채우는 연습 필요. 연인은 삶의 파트너이지 삶 전체를 채워주는 사람은 아님',
      en: 'One person can rarely fill all these expectations. A lasting gap between expectation and reality leads to ongoing disappointment\nThe bigger the expectations, the higher the dependency—and the more burden your partner may feel\nPractice filling part of your needs yourself. A partner is a life partner, not someone who fills your entire life',
      ja: '一人ですべての期待を満たすのは非常に難しい。期待と現実のギャップが続くと関係で継続的な失望が生じる\n恋人への期待が大きいほど依存度が高まり、相手が負担を感じることがある\n自分で満たせる部分を見つける練習が必要。恋人は人生のパートナーであり、人生全体を満たす人ではない',
      'zh-CN': '一个人很难满足所有这些期待，期待与现实的持续差距会带来不断失望\n对恋人期待越大依赖越高，对方可能感到负担\n练习自己满足部分需求，恋人是人生伴侣，不是填满整个人生的人',
      'zh-TW': '一個人很難滿足所有這些期待，期待與現實的持續差距會帶來不斷失望\n對戀人期待越大依賴越高，對方可能感到負擔\n練習自己滿足部分需求，戀人是人生伴侶，不是填滿整個人生的人',
      vi: 'Một người hiếm khi lấp đầy mọi kỳ vọng này. Khoảng cách kéo dài giữa kỳ vọng và thực tế dẫn đến thất vọng liên tục\nKỳ vọng càng lớn, phụ thuộc càng cao—và đối phương có thể cảm thấy gánh nặng\nLuyện tự lấp một phần nhu cầu. Người yêu là bạn đời, không phải người lấp đầy cả cuộc đời',
      id: 'Satu orang jarang bisa memenuhi semua harapan ini. Celah berkepanjangan antara harapan dan realita menimbulkan kekecewaan terus-menerus\nSemakin besar harapan, semakin tinggi ketergantungan—dan pasangan bisa merasa terbebani\nLatih memenuhi sebagian kebutuhan sendiri. Pasangan adalah partner hidup, bukan pengisi seluruh hidup',
    }),
    guidanceAdvice: localeMap({
      ko: '내가 혼자서도 충족할 수 있는 것들 찾기. 연인에 대한 기대를 우선순위로 정리해보기. 가장 중요한 것에 집중하기',
      en: 'Find what you can satisfy on your own. Prioritize your expectations of your partner and focus on what matters most',
      ja: '自分一人で満たせるものを見つける。恋人への期待を優先順位づけし、最も大切なことに集中する',
      'zh-CN': '找到能自己满足的部分，给对恋人的期待排优先级，聚焦最重要的',
      'zh-TW': '找到能自己滿足的部分，給對戀人的期待排優先級，聚焦最重要的',
      vi: 'Tìm những gì bạn có thể tự thỏa mãn. Sắp xếp ưu tiên kỳ vọng với người yêu và tập trung vào điều quan trọng nhất',
      id: 'Temukan apa yang bisa kamu penuhi sendiri. Prioritaskan harapan pada pasangan dan fokus pada yang paling penting',
    }),
    certificationPhrase: localeMap({
      ko: '완전 헌신 기대형 ❤️ 기대치 최상위. 그만큼 사랑도 최대치로 줄 준비가 되어있습니다',
      en: 'Total Devotion Expectation Type ❤️ Top-tier expectations. You are equally ready to give love at maximum capacity',
      ja: '完全献身期待型 ❤️ 期待値最上級。それだけ愛も最大限に捧げる準備があります',
      'zh-CN': '达成完全奉献期待型 ❤️ 期待值顶级，同样准备以最大容量给予爱',
      'zh-TW': '達成完全奉獻期待型 ❤️ 期待值頂級，同樣準備以最大容量給予愛',
      vi: 'Kiểu cống hiến toàn phần ❤️ Kỳ vọng cao nhất. Bạn cũng sẵn sàng cho đi tình yêu ở mức tối đa',
      id: 'Tipe Harapan Pengorbanan Total ❤️ Harapan level tertinggi. Kamu juga siap memberi cinta kapasitas maksimum',
    }),
    oneLiner: localeMap({
      ko: '당신이 원하는 사랑은 크고 깊습니다. 그 크기만큼 자신에게도 같은 사랑을 돌려줄 수 있다면 더 건강해집니다',
      en: 'The love you want is big and deep. If you can give yourself the same love in return, you will become healthier.',
      ja: 'あなたが望む愛は大きく深いです。その大きさだけ自分にも同じ愛を返せれば、より健康になります。',
      'zh-CN': '你想要的爱很大很深，若能同样回馈给自己，会更健康。',
      'zh-TW': '你想要的愛很大很深，若能同樣回饋給自己，會更健康。',
      vi: 'Tình yêu bạn mong rất lớn và sâu. Nếu bạn cũng dành tình yêu đó cho chính mình, bạn sẽ khỏe mạnh hơn.',
      id: 'Cinta yang kamu inginkan besar dan dalam. Jika kamu juga memberi cinta yang sama pada diri sendiri, kamu akan lebih sehat.',
    }),
    shareLine: localeMap({
      ko: '내 연애 기대치: 완전 헌신 기대형 ❤️ 연인이 모든 것이어야 하는 타입이래... 솔직히 맞음 ㅠ 연애 상담 알아봐야겠다 → 나 기대치 이 정도래 너도 해봐',
      en: 'My love expectations: Total Devotion ❤️ They say my partner should be everything... honestly true ㅠ maybe I need relationship counseling → Try it too',
      ja: '私の恋愛期待値：完全献身型 ❤️ 恋人がすべてであるべきタイプ... 正直当たり ㅠ 恋愛相談調べなきゃ → あなたもやってみて',
      'zh-CN': '我的恋爱期待值：完全奉献型 ❤️ 说恋人应该是一切... 老实说太准了 ㅠ 该看看恋爱咨询了 → 你也试试',
      'zh-TW': '我的戀愛期待值：完全奉獻型 ❤️ 說戀人應該是一切... 老實說太準了 ㅠ 該看看戀愛諮詢了 → 你也試試',
      vi: 'Kỳ vọng tình yêu: Cống hiến toàn phần ❤️ Bảo người yêu phải là tất cả... thật sự đúng ㅠ nên tìm tư vấn tình cảm → Bạn thử nhé',
      id: 'Harapan cintaku: Pengorbanan Total ❤️ Katanya pasangan harus jadi segalanya... jujur bener ㅠ mungkin perlu konseling cinta → Kamu coba juga',
    }),
  },
];
