/** 나의 위험 감수 성향 — phase3-risk-tolerance · 12문항 4지선다 · A=0/B=1/C=2/D=3 · 7개 로케일 */

export type Phase3RiskToleranceLocaleKey = 'ko' | 'en' | 'ja' | 'zh-CN' | 'zh-TW' | 'vi' | 'id';

function localeMap(t: Record<Phase3RiskToleranceLocaleKey, string>): Record<Phase3RiskToleranceLocaleKey, string> {
  return t;
}

function opt(m: Record<Phase3RiskToleranceLocaleKey, string>, score: number): { text: Record<Phase3RiskToleranceLocaleKey, string>; score: number } {
  return { text: localeMap(m), score };
}

export interface Phase3RiskToleranceQuestion {
  id: number;
  question: Record<Phase3RiskToleranceLocaleKey, string>;
  options: { text: Record<Phase3RiskToleranceLocaleKey, string>; score: number }[];
}

export interface Phase3RiskToleranceResult {
  type: string;
  emoji: string;
  title: Record<Phase3RiskToleranceLocaleKey, string>;
  riskLevel: Record<Phase3RiskToleranceLocaleKey, string>;
  quote: Record<Phase3RiskToleranceLocaleKey, string>;
  description: Record<Phase3RiskToleranceLocaleKey, string>;
  riskType: Record<Phase3RiskToleranceLocaleKey, string>;
  riskAcceptanceLevel: Record<Phase3RiskToleranceLocaleKey, string>;
  financialDiagnosis: Record<Phase3RiskToleranceLocaleKey, string>;
  socialDiagnosis: Record<Phase3RiskToleranceLocaleKey, string>;
  physicalDiagnosis: Record<Phase3RiskToleranceLocaleKey, string>;
  careerDiagnosis: Record<Phase3RiskToleranceLocaleKey, string>;
  uncertaintyDiagnosis: Record<Phase3RiskToleranceLocaleKey, string>;
  strengths: Record<Phase3RiskToleranceLocaleKey, string>;
  caution: Record<Phase3RiskToleranceLocaleKey, string>;
  investmentStyle: Record<Phase3RiskToleranceLocaleKey, string>;
  entrepreneurshipStyle: Record<Phase3RiskToleranceLocaleKey, string>;
  certificationPhrase: Record<Phase3RiskToleranceLocaleKey, string>;
  oneLiner: Record<Phase3RiskToleranceLocaleKey, string>;
  shareLine: Record<Phase3RiskToleranceLocaleKey, string>;
}

export function calculatePhase3RiskToleranceResult(answers: number[]): string {
  const total = answers.reduce((sum, s) => sum + (s ?? 0), 0);
  if (total <= 5) return 'Type1';
  if (total <= 11) return 'Type2';
  if (total <= 19) return 'Type3';
  if (total <= 27) return 'Type4';
  if (total <= 33) return 'Type5';
  return 'Type6';
}

export function calculatePhase3RiskToleranceDomainScores(answers: number[]) {
  const financial = (answers[0] ?? 0) + (answers[1] ?? 0) + (answers[2] ?? 0);
  const social = (answers[3] ?? 0) + (answers[4] ?? 0) + (answers[5] ?? 0);
  const physical = (answers[6] ?? 0) + (answers[7] ?? 0);
  const career = (answers[8] ?? 0) + (answers[9] ?? 0);
  const uncertainty = (answers[10] ?? 0) + (answers[11] ?? 0);
  return {
    financial,
    social,
    physical,
    career,
    uncertainty,
    total: answers.reduce((sum, s) => sum + (s ?? 0), 0),
  };
}

export const phase3RiskToleranceQuestions: Phase3RiskToleranceQuestion[] = [
  {
    id: 1,
    question: localeMap({
      ko: '목돈 1,000만 원이 생겼다. 어떻게 운용하겠는가?',
      en: 'You receive a lump sum of 10 million won. How would you use it?',
      ja: '一時金1,000万ウォンが入った。どう運用する？',
      'zh-CN': '你有一笔1000万韩元的闲钱，会怎么打理？',
      'zh-TW': '你有一筆1000萬韓元的閒錢，會怎麼打理？',
      vi: 'Bạn nhận được một khoản 10 triệu won. Bạn sẽ dùng nó thế nào?',
      id: 'Kamu dapat dana sebesar 10 juta won. Bagaimana kamu mengelolanya?',
    }),
    options: [
      opt(localeMap({
        ko: '전액 은행 예금 또는 적금에 넣는다. 원금 손실은 절대 안 된다',
        en: 'Put it all in a bank deposit or savings. I absolutely cannot lose principal',
        ja: '全額を銀行預金や積立に入れる。元本割れは絶対に嫌',
        'zh-CN': '全部存银行定期或储蓄，绝对不能亏本金',
        'zh-TW': '全部存銀行定期或儲蓄，絕對不能虧本金',
        vi: 'Gửi hết vào tiết kiệm hoặc gửi ngân hàng. Tuyệt đối không chấp nhận mất vốn',
        id: 'Taruh semua di deposito atau tabungan bank. Pokok modal tidak boleh hilang',
    }), 0),
      opt(localeMap({
        ko: '대부분은 안전 자산에 두고 일부(10~20%)만 리스크 있는 자산에 투자한다',
        en: 'Keep most in safe assets and invest only 10–20% in risky assets',
        ja: '大半は安全資産、一部（10〜20%）だけリスク資産に',
        'zh-CN': '大部分放安全资产，只拿10~20%投有风险的产品',
        'zh-TW': '大部分放安全資產，只拿10~20%投有風險的產品',
        vi: 'Phần lớn giữ tài sản an toàn, chỉ 10–20% vào tài sản rủi ro',
        id: 'Sebagian besar di aset aman, hanya 10–20% di aset berisiko',
    }), 1),
      opt(localeMap({
        ko: '절반 정도는 주식·펀드 등에 투자하고 나머지는 안전 자산으로 분산한다',
        en: 'Invest about half in stocks/funds and keep the rest in safe assets',
        ja: '半分くらいを株・ファンドに、残りは安全資産で分散',
        'zh-CN': '大约一半投股票/基金，其余分散到安全资产',
        'zh-TW': '大約一半投股票/基金，其餘分散到安全資產',
        vi: 'Khoảng một nửa vào cổ phiếu/quỹ, phần còn lại phân tán vào tài sản an toàn',
        id: 'Sekitar setengah di saham/reksadana, sisanya diversifikasi ke aset aman',
    }), 2),
      opt(localeMap({
        ko: '높은 수익을 위해 공격적으로 투자한다. 잃을 수 있다는 것을 알면서도 기회에 베팅한다',
        en: 'Invest aggressively for high returns. I bet on opportunities knowing I could lose',
        ja: '高収益のために積極投資。失う覚悟はあっても機会に賭ける',
        'zh-CN': '为高收益积极投资，明知可能亏损也要抓住机会',
        'zh-TW': '為高收益積極投資，明知可能虧損也要抓住機會',
        vi: 'Đầu tư mạnh tay để lợi nhuận cao. Biết có thể mất nhưng vẫn cược vào cơ hội',
        id: 'Investasi agresif demi return tinggi. Siap rugi asal bisa bertaruh pada peluang',
    }), 3),
    ],
  },
  {
    id: 2,
    question: localeMap({
      ko: '투자한 자산이 30% 하락했다. 나는?',
      en: 'An investment you made has dropped 30%. What do you do?',
      ja: '投資した資産が30%下落した。あなたは？',
      'zh-CN': '你投资的资产跌了30%，你会？',
      'zh-TW': '你投資的資產跌了30%，你會？',
      vi: 'Tài sản bạn đầu tư giảm 30%. Bạn sẽ làm gì?',
      id: 'Investasi kamu turun 30%. Apa yang kamu lakukan?',
    }),
    options: [
      opt(localeMap({
        ko: '더 잃기 전에 전액 손절하고 다시는 이런 투자를 하지 않겠다고 다짐한다',
        en: 'Cut all losses immediately and swear never to make such investments again',
        ja: 'これ以上失う前に全額損切り。二度とこんな投資はしないと誓う',
        'zh-CN': '趁还没亏更多全部止损，发誓再也不做这种投资',
        'zh-TW': '趁還沒虧更多全部止損，發誓再也不做這種投資',
        vi: 'Cắt lỗ toàn bộ ngay và thề không bao giờ đầu tư kiểu này nữa',
        id: 'Cut loss semua segera dan bersumpah tidak akan investasi seperti ini lagi',
    }), 0),
      opt(localeMap({
        ko: '심리적으로 많이 흔들린다. 일부 정리하면서 상황을 지켜본다',
        en: 'I\'m shaken psychologically. I sell part of it and watch the situation',
        ja: '心理的にかなり揺れる。一部整理しながら様子を見る',
        'zh-CN': '心理波动很大，先卖一部分再观察',
        'zh-TW': '心理波動很大，先賣一部分再觀察',
        vi: 'Tâm lý rung lắc nhiều. Bán một phần và theo dõi tình hình',
        id: 'Mental goyah. Jual sebagian sambil pantau situasi',
    }), 1),
      opt(localeMap({
        ko: '시장 상황을 분석하고 원래 투자 근거가 유효하면 추가 매수를 고려한다',
        en: 'Analyze the market and consider buying more if my original thesis still holds',
        ja: '市場を分析し、投資根拠が有効なら追加買いも検討',
        'zh-CN': '分析市场，若投资逻辑仍成立就考虑加仓',
        'zh-TW': '分析市場，若投資邏輯仍成立就考慮加倉',
        vi: 'Phân tích thị trường và cân nhắc mua thêm nếu luận điểm ban đầu vẫn đúng',
        id: 'Analisis pasar dan pertimbangkan beli lagi jika alasan investasi masih valid',
    }), 2),
      opt(localeMap({
        ko: '오히려 기회다. 더 저렴하게 살 수 있는 구간이라 생각하고 적극적으로 추가 매수한다',
        en: 'See it as an opportunity. Buy more aggressively while it\'s cheaper',
        ja: 'むしろチャンス。もっと安く買える区間と考え積極的に追加買い',
        'zh-CN': '反而觉得是机会，趁便宜积极加仓',
        'zh-TW': '反而覺得是機會，趁便宜積極加倉',
        vi: 'Coi đó là cơ hội. Mua thêm tích cực khi giá rẻ hơn',
        id: 'Justru lihat sebagai peluang. Beli tambahan agresif saat lebih murah',
    }), 3),
    ],
  },
  {
    id: 3,
    question: localeMap({
      ko: '지인이 "확실한 투자 기회"라며 투자를 권유한다. 리스크가 있지만 수익률이 높다고 한다. 나는?',
      en: 'An acquaintance recommends a "sure investment opportunity"—risky but high return. What do you do?',
      ja: '知人が「確実な投資機会」と勧めてくる。リスクはあるが収益率は高い。あなたは？',
      'zh-CN': '熟人推荐一个“稳赚”的投资机会，有风险但收益高。你会？',
      'zh-TW': '熟人推薦一個「穩賺」的投資機會，有風險但收益高。你會？',
      vi: 'Người quen giới thiệu "cơ hội đầu tư chắc chắn"—có rủi ro nhưng lợi nhuận cao. Bạn sẽ?',
      id: 'Kenalan merekomendasikan "peluang investasi pasti"—berisiko tapi return tinggi. Kamu?',
    }),
    options: [
      opt(localeMap({
        ko: '리스크가 있다는 말에 바로 거절한다. 손실 가능성이 있는 것에 돈을 넣지 않는다',
        en: 'Decline immediately because there\'s risk. I won\'t put money in anything that could lose',
        ja: 'リスクがあると聞いた時点で断る。損失の可能性があるものには入れない',
        'zh-CN': '一听有风险就拒绝，可能亏钱的绝不投',
        'zh-TW': '一聽有風險就拒絕，可能虧錢的絕不投',
        vi: 'Từ chối ngay vì có rủi ro. Không bỏ tiền vào thứ có thể lỗ',
        id: 'Langsung tolak karena ada risiko. Tidak taruh uang di hal yang bisa rugi',
    }), 0),
      opt(localeMap({
        ko: '충분히 검증하고 공식적인 자료를 확인한 후에 소액만 고려해볼 수 있다',
        en: 'Verify thoroughly and check official documents before considering a small amount',
        ja: '十分検証し公式資料を確認した後、少額だけ検討できる',
        'zh-CN': '充分验证、查官方资料后，才可能考虑小额',
        'zh-TW': '充分驗證、查官方資料後，才可能考慮小額',
        vi: 'Xác minh kỹ và xem tài liệu chính thức trước khi cân nhắc số tiền nhỏ',
        id: 'Verifikasi matang dan cek dokumen resmi dulu, baru pertimbangkan nominal kecil',
    }), 1),
      opt(localeMap({
        ko: '해당 투자를 직접 조사해보고 근거가 충분하면 어느 정도 베팅할 수 있다',
        en: 'Research it myself and bet a reasonable amount if the evidence is solid',
        ja: '直接調査し、根拠が十分ならある程度賭けられる',
        'zh-CN': '自己调研，依据充分就愿意投一定金额',
        'zh-TW': '自己調研，依據充分就願意投一定金額',
        vi: 'Tự nghiên cứu và cược mức hợp lý nếu căn cứ đủ vững',
        id: 'Riset sendiri dan taruhan cukup besar jika buktinya kuat',
    }), 2),
      opt(localeMap({
        ko: '기회라고 판단되면 과감하게 투자한다. 리스크 없이 높은 수익은 없다',
        en: 'Invest boldly if it looks like a real opportunity. High returns need risk',
        ja: '機会だと判断すれば大胆に投資。高収益にリスクなしはない',
        'zh-CN': '判断是机会就大胆投，高收益不可能零风险',
        'zh-TW': '判斷是機會就大膽投，高收益不可能零風險',
        vi: 'Đầu tư mạnh nếu thấy là cơ hội thật. Lợi nhuận cao không thể không rủi ro',
        id: 'Investasi berani jika terlihat peluang. Return tinggi tanpa risiko tidak ada',
    }), 3),
    ],
  },
  {
    id: 4,
    question: localeMap({
      ko: '마음에 드는 사람이 생겼다. 거절당할 수도 있지만 먼저 연락해볼 것인가?',
      en: 'You like someone. Would you reach out first even if you might get rejected?',
      ja: '気になる人ができた。断られるかもしれないが先に連絡する？',
      'zh-CN': '有了喜欢的人，即使可能被拒，你会先联系吗？',
      'zh-TW': '有了喜歡的人，即使可能被拒，你會先聯繫嗎？',
      vi: 'Bạn thích ai đó. Bạn có chủ động liên hệ dù có thể bị từ chối?',
      id: 'Kamu suka seseorang. Kamu akan hubungi duluan meski mungkin ditolak?',
    }),
    options: [
      opt(localeMap({
        ko: '거절당하는 게 두려워서 먼저 나서기가 매우 어렵다. 상대방이 먼저 신호를 줄 때까지 기다린다',
        en: 'Too afraid of rejection. I wait until they show interest first',
        ja: '拒否されるのが怖くて先に出るのがとても難しい。相手の合図を待つ',
        'zh-CN': '太怕被拒绝，很难主动，等对方先给信号',
        'zh-TW': '太怕被拒絕，很難主動，等對方先給信號',
        vi: 'Sợ bị từ chối quá nên rất khó chủ động. Chờ đối phương ra tín hiệu trước',
        id: 'Terlalu takut ditolak. Tunggu sampai dia memberi sinyal dulu',
    }), 0),
      opt(localeMap({
        ko: '고민은 하지만 결국 직접 행동하기보다 간접적인 방법을 찾는 편이다',
        en: 'I hesitate and tend to find indirect ways rather than acting directly',
        ja: '悩むが結局直接行動より間接的な方法を探す',
        'zh-CN': '会纠结，但多半找间接方式而不是直接行动',
        'zh-TW': '會糾結，但多半找間接方式而不是直接行動',
        vi: 'Do dự và thường tìm cách gián tiếp hơn là hành động trực tiếp',
        id: 'Ragu dan cenderung cari cara tidak langsung daripada bertindak langsung',
    }), 1),
      opt(localeMap({
        ko: '용기를 내서 먼저 연락한다. 거절당하더라도 시도하지 않는 것보다는 낫다고 생각한다',
        en: 'I gather courage and reach out. Better to try than never try',
        ja: '勇気を出して先に連絡。断られても試さないよりマシ',
        'zh-CN': '鼓起勇气先联系，被拒也比不试强',
        'zh-TW': '鼓起勇氣先聯繫，被拒也比不試強',
        vi: 'Lấy can đảm chủ động liên hệ. Bị từ chối vẫn hơn không thử',
        id: 'Berani hubungi dulu. Ditolak pun lebih baik daripada tidak mencoba',
    }), 2),
      opt(localeMap({
        ko: '망설임 없이 바로 연락한다. 거절도 하나의 결과이고 시도하는 것 자체가 중요하다',
        en: 'Contact immediately without hesitation. Rejection is just one outcome',
        ja: 'ためらわずすぐ連絡。拒否も結果の一つ、試すこと自体が大事',
        'zh-CN': '毫不犹豫立刻联系，拒绝也是一种结果，尝试本身很重要',
        'zh-TW': '毫不猶豫立刻聯繫，拒絕也是一種結果，嘗試本身很重要',
        vi: 'Liên hệ ngay không do dự. Từ chối cũng là một kết quả, thử mới quan trọng',
        id: 'Hubungi langsung tanpa ragu. Penolakan juga hasil, yang penting mencoba',
    }), 3),
    ],
  },
  {
    id: 5,
    question: localeMap({
      ko: '많은 사람 앞에서 내 의견을 말해야 하는 상황이다. 그 의견이 다수의 의견과 다를 수 있다. 나는?',
      en: 'You must share your opinion in front of many people, and it may differ from the majority. What do you do?',
      ja: '多くの人の前で意見を言う場面。多数派と違うかもしれない。あなたは？',
      'zh-CN': '要在很多人面前发言，你的意见可能和多数不同。你会？',
      'zh-TW': '要在很多人面前發言，你的意見可能和多數不同。你會？',
      vi: 'Bạn phải nói ý kiến trước đám đông, và có thể khác đa số. Bạn sẽ?',
      id: 'Kamu harus menyampaikan pendapat di depan banyak orang, dan mungkin berbeda dari mayoritas. Kamu?',
    }),
    options: [
      opt(localeMap({
        ko: '내 의견보다 다수 의견을 따르는 편이다. 괜히 튀고 싶지 않다',
        en: 'I follow the majority. I don\'t want to stand out',
        ja: '自分の意見より多数派に従う。目立ちたくない',
        'zh-CN': '更倾向跟随多数，不想出头',
        'zh-TW': '更傾向跟隨多數，不想出頭',
        vi: 'Theo đa số hơn là ý kiến của mình. Không muốn nổi bật',
        id: 'Ikuti mayoritas. Tidak mau menonjol',
    }), 0),
      opt(localeMap({
        ko: '생각은 있지만 발언하기 전에 많이 망설이고 신중하게 표현한다',
        en: 'I have thoughts but hesitate a lot and express them very carefully',
        ja: '考えはあるが発言前にかなり迷い、慎重に表現する',
        'zh-CN': '有想法但会犹豫很久，表达很谨慎',
        'zh-TW': '有想法但會猶豫很久，表達很謹慎',
        vi: 'Có suy nghĩ nhưng do dự nhiều trước khi nói, diễn đạt rất thận trọng',
        id: 'Ada pikiran tapi ragu lama sebelum bicara, ekspresi sangat hati-hati',
    }), 1),
      opt(localeMap({
        ko: '필요하다면 다수 의견과 다르더라도 내 생각을 이야기한다. 건설적인 반론이 필요하다고 생각한다',
        en: 'If needed, I share my view even if it differs. Constructive dissent matters',
        ja: '必要なら多数と違っても話す。建設的反論が必要だと思う',
        'zh-CN': '必要时即使不同也会说，觉得需要建设性反对',
        'zh-TW': '必要時即使不同也會說，覺得需要建設性反對',
        vi: 'Nếu cần thì nói dù khác đa số. Phản biện mang tính xây dựng là cần thiết',
        id: 'Jika perlu, sampaikan meski berbeda. Protes konstruktif itu penting',
    }), 2),
      opt(localeMap({
        ko: '다수 의견과 달라도 적극적으로 발언한다. 오히려 소수 의견을 내는 것이 의미 있다고 생각한다',
        en: 'I speak up actively even against the majority. Minority views can matter',
        ja: '多数と違っても積極的に発言。少数意見こそ意味がある',
        'zh-CN': '即使和多数不同也积极发言，少数意见才有意义',
        'zh-TW': '即使和多數不同也積極發言，少數意見才有意義',
        vi: 'Nói tích cực dù khác đa số. Ý kiến thiểu số mới có ý nghĩa',
        id: 'Bicara aktif meski beda dari mayoritas. Pendapat minoritas justru bermakna',
    }), 3),
    ],
  },
  {
    id: 6,
    question: localeMap({
      ko: '전혀 모르는 사람들만 있는 모임에 혼자 참여하게 됐다. 나는?',
      en: 'You end up at a gathering where you know no one. What do you do?',
      ja: '知らない人だけの集まりに一人で参加することになった。あなたは？',
      'zh-CN': '你独自参加一个全是陌生人的聚会。你会？',
      'zh-TW': '你獨自參加一個全是陌生人的聚會。你會？',
      vi: 'Bạn tham gia một buổi gặp mặt toàn người lạ, một mình. Bạn sẽ?',
      id: 'Kamu ikut pertemuan penuh orang asing, sendirian. Kamu?',
    }),
    options: [
      opt(localeMap({
        ko: '최대한 눈에 띄지 않으려 하고 아는 사람이 생길 때까지 조용히 있는다',
        en: 'Stay quiet and low-profile until I know someone',
        ja: '目立たないようにして知り合いができるまで静かにいる',
        'zh-CN': '尽量低调，等有熟人再说话',
        'zh-TW': '盡量低調，等有熟人再說話',
        vi: 'Cố hòa nhập im lặng cho đến khi quen ai đó',
        id: 'Diam dan tidak menonjol sampai kenal seseorang',
    }), 0),
      opt(localeMap({
        ko: '먼저 말 걸기는 어렵지만 누군가 말을 걸어오면 자연스럽게 대화한다',
        en: 'Hard to start, but I talk naturally if someone approaches me',
        ja: '先に話しかけるのは難しいが、誰かが来れば自然に会話する',
        'zh-CN': '很难先开口，但有人搭话就能自然聊',
        'zh-TW': '很難先開口，但有人搭話就能自然聊',
        vi: 'Khó chủ động, nhưng ai bắt chuyện thì nói chuyện tự nhiên',
        id: 'Sulit mulai duluan, tapi kalau ditemui bicara dengan natural',
    }), 1),
      opt(localeMap({
        ko: '어색하더라도 먼저 다가가서 자기 소개를 하고 대화를 시작한다',
        en: 'Even if awkward, I introduce myself and start a conversation',
        ja: '気まずくても先に近づいて自己紹介し、会話を始める',
        'zh-CN': '就算尴尬也会主动自我介绍、开启对话',
        'zh-TW': '就算尷尬也會主動自我介紹、開啟對話',
        vi: 'Dù ngại vẫn chủ động giới thiệu và bắt chuyện',
        id: 'Meski canggung, say hello dulu dan mulai percakapan',
    }), 2),
      opt(localeMap({
        ko: '낯선 환경이 오히려 흥미롭다. 누구나 적극적으로 만나고 네트워크를 만드는 기회로 활용한다',
        en: 'Unfamiliar settings excite me. I actively meet people and build networks',
        ja: '未知の環境がむしろ面白い。積極的に会ってネットワークを作る',
        'zh-CN': '陌生环境反而有趣，积极认识人、拓展人脉',
        'zh-TW': '陌生環境反而有趣，積極認識人、拓展人脈',
        vi: 'Môi trường lạ lại thú vị. Chủ động gặp gỡ và xây network',
        id: 'Lingkungan asing justru menarik. Aktif kenalan dan bangun jaringan',
    }), 3),
    ],
  },
  {
    id: 7,
    question: localeMap({
      ko: '친구가 번지점프·스카이다이빙·래프팅 등 익스트림 액티비티를 제안했다. 나는?',
      en: 'A friend suggests extreme activities like bungee jumping, skydiving, or rafting. What do you do?',
      ja: '友人がバンジー・スカイダイビング・ラフティングなどを提案。あなたは？',
      'zh-CN': '朋友提议蹦极、跳伞、漂流等极限活动。你会？',
      'zh-TW': '朋友提議蹦極、跳傘、漂流等極限活動。你會？',
      vi: 'Bạn bè rủ nhảy bungee, nhảy dù, chèo thuyền v.v. Bạn sẽ?',
      id: 'Teman ajak bungee jump, skydiving, rafting, dll. Kamu?',
    }),
    options: [
      opt(localeMap({
        ko: '위험할 것 같아서 거절한다. 굳이 그런 경험을 할 필요를 못 느낀다',
        en: 'Decline—it seems dangerous and I don\'t feel the need',
        ja: '危なそうなので断る。わざわざその経験をする必要を感じない',
        'zh-CN': '觉得危险就拒绝，没必要专门体验',
        'zh-TW': '覺得危險就拒絕，沒必要專門體驗',
        vi: 'Từ chối vì nguy hiểm. Không thấy cần trải nghiệm đó',
        id: 'Tolak karena terlihat berbahaya. Tidak merasa perlu',
    }), 0),
      opt(localeMap({
        ko: '망설이다가 친구가 강하게 권유하면 따라가는 정도다. 혼자서는 안 한다',
        en: 'Hesitate, but might go if a friend pushes hard. Not alone',
        ja: '迷うが強く勧められれば付き合う程度。一人ではしない',
        'zh-CN': '会犹豫，朋友强烈邀请可能去，但不会独自去',
        'zh-TW': '會猶豫，朋友強烈邀請可能去，但不會獨自去',
        vi: 'Do dự, bạn ép mạnh thì có thể đi. Một mình thì không',
        id: 'Ragu, ikut kalau teman desak kuat. Sendirian tidak',
    }), 1),
      opt(localeMap({
        ko: '어느 정도 겁은 나지만 해보고 싶다는 마음이 더 크다. 적극적으로 참여한다',
        en: 'A bit scared but curiosity wins. I join actively',
        ja: '多少怖いがやってみたい気持ちの方が大きい。積極的に参加',
        'zh-CN': '有点怕但更想试，会积极参与',
        'zh-TW': '有點怕但更想試，會積極參與',
        vi: 'Hơi sợ nhưng muốn thử hơn. Tham gia tích cực',
        id: 'Agak takut tapi ingin coba lebih besar. Ikut aktif',
    }), 2),
      opt(localeMap({
        ko: '그 이상을 원한다. 번지점프 정도는 이미 해봤거나 더 강렬한 것을 찾고 있다',
        en: 'Want more. Bungee is old news or I\'m looking for something stronger',
        ja: 'それ以上を望む。バンジー程度は経験済みか、もっと強い刺激を探している',
        'zh-CN': '想要更刺激的，蹦极可能试过了或在找更强的',
        'zh-TW': '想要更刺激的，蹦極可能試過了或在找更強的',
        vi: 'Muốn hơn thế. Bungee có thể đã thử hoặc đang tìm cảm giác mạnh hơn',
        id: 'Mau lebih lagi. Bungee mungkin sudah pernah atau cari yang lebih ekstrem',
    }), 3),
    ],
  },
  {
    id: 8,
    question: localeMap({
      ko: '계획에 없던 완전히 새로운 것을 즉흥적으로 시도해볼 기회가 생겼다. 나는?',
      en: 'An unplanned chance to try something completely new appears. What do you do?',
      ja: '計画にない全く新しいことを即興で試す機会が来た。あなたは？',
      'zh-CN': '突然出现一个计划外、可以尝试全新事物的机会。你会？',
      'zh-TW': '突然出現一個計劃外、可以嘗試全新事物的機會。你會？',
      vi: 'Cơ hội thử điều hoàn toàn mới, không có trong kế hoạch. Bạn sẽ?',
      id: 'Kesempatan mencoba hal baru sepenuhnya, tidak terencana. Kamu?',
    }),
    options: [
      opt(localeMap({
        ko: '계획에 없던 것은 잘 하지 않는다. 충분히 알아보고 준비된 다음에 해야 한다',
        en: 'I don\'t do unplanned things. I need to research and prepare first',
        ja: '計画外のことはあまりしない。十分調べて準備してから',
        'zh-CN': '不太做计划外的事，要先了解清楚、准备好',
        'zh-TW': '不太做計劃外的事，要先了解清楚、準備好',
        vi: 'Không hay làm việc ngoài kế hoạch. Phải tìm hiểu và chuẩn bị trước',
        id: 'Tidak suka hal di luar rencana. Harus riset dan siap dulu',
    }), 0),
      opt(localeMap({
        ko: '흥미롭긴 하지만 선뜻 뛰어들기보다 일단 지켜보고 판단한다',
        en: 'Interesting, but I observe first rather than jump in',
        ja: '興味はあるがすぐ飛び込まず、まず様子を見る',
        'zh-CN': '有兴趣，但不会马上冲，先观察',
        'zh-TW': '有興趣，但不會馬上衝，先觀察',
        vi: 'Thú vị nhưng không nhảy vào ngay, quan sát trước',
        id: 'Menarik tapi tidak langsung loncat, amati dulu',
    }), 1),
      opt(localeMap({
        ko: '어느 정도 알아본 후 괜찮겠다 싶으면 시도한다. 즉흥적 결정도 할 수 있다',
        en: 'After some research, I try if it seems okay. Spontaneous decisions are possible',
        ja: 'ある程度調べて問題なさそうなら試す。即興決定もできる',
        'zh-CN': '稍微了解后觉得可行就试，也能即兴决定',
        'zh-TW': '稍微了解後覺得可行就試，也能即興決定',
        vi: 'Tìm hiểu qua, ổn thì thử. Có thể quyết định bốc đồng',
        id: 'Riset sedikit, kalau oke coba. Keputusan spontan juga bisa',
    }), 2),
      opt(localeMap({
        ko: '바로 해본다. 모르는 것은 해보면서 배우면 된다. 즉흥성 자체가 좋다',
        en: 'Try immediately. You learn by doing. Spontaneity itself feels good',
        ja: 'すぐやってみる。知らないことはやりながら学べばいい。即興性自体が好き',
        'zh-CN': '马上试，不懂就边做边学，即兴本身就很爽',
        'zh-TW': '馬上試，不懂就邊做邊學，即興本身就很爽',
        vi: 'Làm ngay. Không biết thì học trong lúc làm. Bản thân sự bốc đồng đã hay',
        id: 'Langsung coba. Tidak tahu ya belajar sambil jalan. Spontanitas sendiri enak',
    }), 3),
    ],
  },
  {
    id: 9,
    question: localeMap({
      ko: '현재 안정적인 직장이 있다. 그런데 연봉이 더 높지만 리스크가 있는 스타트업 또는 이직 제안이 왔다. 나는?',
      en: 'You have a stable job, but a higher-paying startup or job offer with risk arrives. What do you do?',
      ja: '安定した職があるが、給与は高いがリスクのあるスタートアップ/転職の話が来た。あなたは？',
      'zh-CN': '现在有稳定工作，但收到更高薪但有风险的创业/跳槽邀请。你会？',
      'zh-TW': '現在有穩定工作，但收到更高薪但有風險的創業/跳槽邀請。你會？',
      vi: 'Bạn có việc ổn định, nhưng nhận lời startup/chuyển việc lương cao hơn nhưng rủi ro. Bạn sẽ?',
      id: 'Kamu punya pekerjaan stabil, tapi dapat tawaran startup/pindah kerja gaji lebih tinggi tapi berisiko. Kamu?',
    }),
    options: [
      opt(localeMap({
        ko: '안정적인 현재 직장이 훨씬 낫다. 불확실한 곳으로 가는 것은 고려하지 않는다',
        en: 'Stable current job is much better. I won\'t consider uncertain moves',
        ja: '安定した今の職の方がはるかに良い。不確実なところへは行かない',
        'zh-CN': '稳定的工作好太多，不考虑不确定的去处',
        'zh-TW': '穩定的工作好太多，不考慮不確定的去處',
        vi: 'Việc ổn định hiện tại tốt hơn nhiều. Không cân nhắc nơi không chắc chắn',
        id: 'Pekerjaan stabil sekarang jauh lebih baik. Tidak pertimbangkan tempat tidak pasti',
    }), 0),
      opt(localeMap({
        ko: '조건을 꼼꼼히 따져보지만 결국 안정성을 선택하는 경향이 있다',
        en: 'I compare conditions carefully but tend to choose stability',
        ja: '条件を細かく見るが結局安定性を選ぶ傾向',
        'zh-CN': '会仔细比较条件，但倾向选稳定',
        'zh-TW': '會仔細比較條件，但傾向選穩定',
        vi: 'So sánh kỹ điều kiện nhưng thường chọn ổn định',
        id: 'Bandingkan syarat matang tapi cenderung pilih stabilitas',
    }), 1),
      opt(localeMap({
        ko: '가능성이 충분하다면 이직을 선택할 수 있다. 리스크와 보상을 계산해서 결정한다',
        en: 'I can move if the upside is strong enough. I weigh risk vs reward',
        ja: '可能性が十分なら移れる。リスクとリターンを計算して決める',
        'zh-CN': '可能性足够大可以换，会计算风险与回报',
        'zh-TW': '可能性足夠大可以換，會計算風險與回報',
        vi: 'Có thể chuyển nếu tiềm năng đủ lớn. Cân rủi ro và phần thưởng',
        id: 'Bisa pindah jika potensinya cukup. Hitung risiko vs imbalan',
    }), 2),
      opt(localeMap({
        ko: '성장 가능성이 보이면 바로 옮긴다. 안정보다 기회가 더 중요하다',
        en: 'Move immediately if growth potential is visible. Opportunity beats stability',
        ja: '成長可能性が見えればすぐ移る。安定より機会が重要',
        'zh-CN': '看到成长空间就立刻换，机会比稳定重要',
        'zh-TW': '看到成長空間就立刻換，機會比穩定重要',
        vi: 'Chuyển ngay nếu thấy tiềm năng tăng trưởng. Cơ hội quan trọng hơn ổn định',
        id: 'Pindah langsung jika ada potensi growth. Peluang lebih penting dari stabilitas',
    }), 3),
    ],
  },
  {
    id: 10,
    question: localeMap({
      ko: '회사를 그만두고 직접 사업을 시작하는 것에 대해 나는?',
      en: 'How do you feel about quitting your job to start your own business?',
      ja: '会社を辞めて直接事業を始めることについて、あなたは？',
      'zh-CN': '关于辞职自己创业，你怎么看？',
      'zh-TW': '關於辭職自己創業，你怎麼看？',
      vi: 'Bạn nghĩ gì về việc nghỉ việc để tự kinh doanh?',
      id: 'Bagaimana perasaanmu soal resign untuk memulai bisnis sendiri?',
    }),
    options: [
      opt(localeMap({
        ko: '상상하기 어렵다. 사업 실패의 리스크가 너무 크고 안정적인 수입이 더 중요하다',
        en: 'Hard to imagine. Business failure risk is too big; stable income matters more',
        ja: '想像しにくい。失敗リスクが大きすぎ、安定収入の方が重要',
        'zh-CN': '很难想象，创业失败风险太大，稳定收入更重要',
        'zh-TW': '很難想像，創業失敗風險太大，穩定收入更重要',
        vi: 'Khó tưởng tượng. Rủi ro thất bại quá lớn, thu nhập ổn định quan trọng hơn',
        id: 'Sulit dibayangkan. Risiko gagal terlalu besar, penghasilan stabil lebih penting',
    }), 0),
      opt(localeMap({
        ko: '충분한 준비와 자본이 있다면 고려해볼 수는 있지만 실행은 쉽지 않을 것 같다',
        en: 'Might consider with enough prep and capital, but executing would be hard',
        ja: '十分な準備と資本があれば検討できるが、実行は簡単ではなさそう',
        'zh-CN': '准备和资金够也许考虑，但真做很难',
        'zh-TW': '準備和資金夠也許考慮，但真做很難',
        vi: 'Có thể cân nhắc nếu chuẩn bị và vốn đủ, nhưng thực hiện không dễ',
        id: 'Bisa dipertimbangkan jika persiapan dan modal cukup, tapi eksekusi tidak mudah',
    }), 1),
      opt(localeMap({
        ko: '아이디어와 준비가 갖춰지면 충분히 할 수 있다고 생각한다. 실제로 준비 중이거나 계획이 있다',
        en: 'I can do it with idea and prep. I\'m preparing or already planning',
        ja: 'アイデアと準備があれば十分できる。準備中か計画がある',
        'zh-CN': '有想法和准备就能做，正在准备或已有计划',
        'zh-TW': '有想法和準備就能做，正在準備或已有計劃',
        vi: 'Làm được nếu có ý tưởng và chuẩn bị. Đang chuẩn bị hoặc đã có kế hoạch',
        id: 'Bisa dilakukan jika ada ide dan persiapan. Sedang menyiapkan atau sudah merencanakan',
    }), 2),
      opt(localeMap({
        ko: '이미 창업했거나 창업이 목표다. 직접 무언가를 만드는 것이 훨씬 매력적이다',
        en: 'Already started or it\'s my goal. Building something myself is far more appealing',
        ja: 'すでに起業したか、それが目標。直接何かを作る方がはるかに魅力的',
        'zh-CN': '已经创业或这就是目标，亲手创造更有吸引力',
        'zh-TW': '已經創業或這就是目標，親手創造更有吸引力',
        vi: 'Đã khởi nghiệp hoặc đó là mục tiêu. Tự tạo ra thứ gì đó hấp dẫn hơn nhiều',
        id: 'Sudah wirausaha atau itu tujuan. Membangun sesuatu sendiri jauh lebih menarik',
    }), 3),
    ],
  },
  {
    id: 11,
    question: localeMap({
      ko: '결과가 불확실한 상황에서 결정을 내려야 할 때 나는?',
      en: 'You must decide when the outcome is uncertain. What do you do?',
      ja: '結果が不確実な状況で決断しなければならない。あなたは？',
      'zh-CN': '必须在结果不确定的情况下做决定。你会？',
      'zh-TW': '必須在結果不確定的情況下做決定。你會？',
      vi: 'Bạn phải quyết định khi kết quả chưa chắc chắn. Bạn sẽ?',
      id: 'Kamu harus memutuskan saat hasilnya belum pasti. Kamu?',
    }),
    options: [
      opt(localeMap({
        ko: '결과를 충분히 예측할 수 있을 때까지 결정을 미루는 편이다. 불확실성 자체가 스트레스다',
        en: 'Delay until I can predict the outcome. Uncertainty itself is stressful',
        ja: '結果を十分予測できるまで先延ばし。不確実性自体がストレス',
        'zh-CN': '能预测结果前会拖延，不确定性本身就很压力',
        'zh-TW': '能預測結果前會拖延，不確定性本身就很壓力',
        vi: 'Hoãn đến khi dự đoán được kết quả. Bản thân sự không chắc chắn đã gây stress',
        id: 'Tunda sampai bisa memprediksi hasil. Ketidakpastian sendiri sudah stres',
    }), 0),
      opt(localeMap({
        ko: '불편하지만 어느 정도 정보를 수집한 후 결정한다. 불확실성이 완전히 제거되길 기다리지는 않는다',
        en: 'Uncomfortable, but decide after gathering some info. Won\'t wait for zero uncertainty',
        ja: '不快だがある程度情報を集めて決める。完全に消えるまで待たない',
        'zh-CN': '不舒服，但收集一些信息后会决定，不会等到完全确定',
        'zh-TW': '不舒服，但收集一些資訊後會決定，不會等到完全確定',
        vi: 'Khó chịu nhưng quyết sau khi thu thập thông tin. Không chờ hết mọi không chắc chắn',
        id: 'Tidak nyaman tapi putuskan setelah kumpulkan info. Tidak menunggu nol ketidakpastian',
    }), 1),
      opt(localeMap({
        ko: '불확실성을 받아들이고 현재 가진 정보로 최선의 결정을 내린다. 나머지는 실행하면서 수정한다',
        en: 'Accept uncertainty and decide with current info. Adjust while executing',
        ja: '不確実性を受け入れ、今ある情報で最善を決める。実行しながら修正',
        'zh-CN': '接受不确定，用现有信息做最好决定，边做边改',
        'zh-TW': '接受不確定，用現有資訊做最好決定，邊做邊改',
        vi: 'Chấp nhận không chắc chắn và quyết với thông tin hiện có. Sửa trong lúc thực hiện',
        id: 'Terima ketidakpastian dan putuskan dengan info sekarang. Koreksi sambil jalan',
    }), 2),
      opt(localeMap({
        ko: '불확실성이 오히려 기회라고 생각한다. 모두가 확신할 때는 이미 늦다. 불확실할 때 들어가야 한다',
        en: 'Uncertainty is opportunity. When everyone is sure, it\'s too late. Enter while unsure',
        ja: '不確実性こそ機会。全員が確信したら遅い。不確実なうちに入る',
        'zh-CN': '不确定才是机会，大家都确定时就晚了，要在不确定时进入',
        'zh-TW': '不確定才是機會，大家都確定時就晚了，要在不確定時進入',
        vi: 'Không chắc chắn mới là cơ hội. Ai cũng chắc thì đã muộn. Vào lúc còn mơ hồ',
        id: 'Ketidakpastian justru peluang. Saat semua yakin sudah telat. Masuk saat masih ragu',
    }), 3),
    ],
  },
  {
    id: 12,
    question: localeMap({
      ko: '지금 내가 삶에서 가장 두려워하는 것은?',
      en: 'What do you fear most in life right now?',
      ja: '今、人生で最も恐れていることは？',
      'zh-CN': '现在，人生中最害怕的是什么？',
      'zh-TW': '現在，人生中最害怕的是什麼？',
      vi: 'Hiện tại bạn sợ điều gì nhất trong cuộc sống?',
      id: 'Saat ini, apa yang paling kamu takuti dalam hidup?',
    }),
    options: [
      opt(localeMap({
        ko: '예상치 못한 손실 또는 실패. 쌓아온 것이 무너지는 것이 가장 두렵다',
        en: 'Unexpected loss or failure. Losing what I\'ve built is scariest',
        ja: '予想外の損失や失敗。築いたものが崩れるのが最も怖い',
        'zh-CN': '意外损失或失败，最怕辛苦积累的东西崩塌',
        'zh-TW': '意外損失或失敗，最怕辛苦累積的東西崩塌',
        vi: 'Mất mát hoặc thất bại bất ngờ. Sợ nhất là những gì đã xây sụp đổ',
        id: 'Kerugian atau kegagalan tak terduga. Paling takut yang sudah dibangun runtuh',
    }), 0),
      opt(localeMap({
        ko: '잘못된 선택으로 인한 후회. 충분히 알아보지 않고 결정해서 실수하는 것',
        en: 'Regret from wrong choices. Deciding without enough research',
        ja: '間違った選択による後悔。十分調べずに決めて失敗すること',
        'zh-CN': '错误选择带来的后悔，没了解清楚就决定',
        'zh-TW': '錯誤選擇帶來的後悔，沒了解清楚就決定',
        vi: 'Hối hận vì chọn sai. Quyết định khi chưa tìm hiểu đủ',
        id: 'Menyesal karena pilihan salah. Memutuskan tanpa riset cukup',
    }), 1),
      opt(localeMap({
        ko: '도전하지 않아서 생기는 후회. 시도해봤으면 됐을 텐데라는 생각이 더 두렵다',
        en: 'Regret from not trying. \'What if I had tried\' feels scarier',
        ja: '挑戦しなかった後悔。「やってみれば」と思う方が怖い',
        'zh-CN': '没挑战的后悔，「要是试过就好了」更可怕',
        'zh-TW': '沒挑戰的後悔，「要是試過就好了」更可怕',
        vi: 'Hối hận vì không thử. Nghĩ \'giá mà đã thử\' còn đáng sợ hơn',
        id: 'Menyesal karena tidak mencoba. \'Andai saja sudah coba\' lebih menakutkan',
    }), 2),
      opt(localeMap({
        ko: '안주하는 것. 변화 없이 같은 자리에 머무르는 것이 가장 두렵다',
        en: 'Staying put. Being stuck in the same place without change',
        ja: '現状維持。変化なく同じ場所に留まること',
        'zh-CN': '安于现状，没有变化、停在原地',
        'zh-TW': '安於現狀，沒有變化、停在原地',
        vi: 'An phận. Ở yên một chỗ không thay đổi',
        id: 'Berhenti di tempat. Tidak berubah dan tetap di posisi yang sama',
    }), 3),
    ],
  },
];

export const phase3RiskToleranceResults: Phase3RiskToleranceResult[] = [
  {
    type: "Type1",
    emoji: "🛡️",
    title: localeMap({
      ko: '안정이 최고의 전략인 사람, 안전 제일형',
      en: 'Safety Is the Best Strategy',
      ja: '安定こそ最高の戦略',
      'zh-CN': '稳定就是最好的策略',
      'zh-TW': '穩定就是最好的策略',
      vi: 'An toàn là chiến lược tốt nhất',
      id: 'Keamanan adalah strategi terbaik',
    }),
    riskLevel: localeMap({
      ko: '매우 낮음 / 리스크 회피 우선',
      en: 'Very low / Risk avoidance first',
      ja: '非常に低い / リスク回避優先',
      'zh-CN': '非常低 / 优先回避风险',
      'zh-TW': '非常低 / 優先迴避風險',
      vi: 'Rất thấp / Ưu tiên tránh rủi ro',
      id: 'Sangat rendah / Prioritas hindari risiko',
    }),
    quote: localeMap({
      ko: '당신에게 리스크는 피해야 할 것입니다. 그리고 그 선택이 당신에게는 최선일 수 있습니다.',
      en: 'For you, risk is something to avoid—and that choice may be your best move.',
      ja: 'あなたにとってリスクは避けるべきもの。そしてその選択が最善かもしれない。',
      'zh-CN': '对你来说，风险是要避开的东西——而这可能是最好的选择。',
      'zh-TW': '對你來說，風險是要避開的東西——而這可能是最好的選擇。',
      vi: 'Với bạn, rủi ro là thứ cần tránh—và lựa chọn đó có thể là tốt nhất.',
      id: 'Bagimu, risiko adalah hal yang harus dihindari—dan pilihan itu bisa jadi yang terbaik.',
    }),
    description: localeMap({
      ko: '손실 가능성이 있는 것에 돈을 넣지 않고 낯선 상황보다 예측 가능한 환경을 선호하며 직업은 안정성이 가장 중요한 기준이 됩니다. 위험을 회피하는 것이 소극적인 게 아닙니다. 확보된 것을 지키는 전략도 하나의 강력한 생존 방식입니다.',
      en: 'You won\'t put money where loss is possible, prefer predictable settings over unfamiliar ones, and put job stability first. Avoiding risk isn\'t passive—protecting what you\'ve secured is a powerful survival strategy.',
      ja: '損失の可能性があるものにお金を入れず、未知より予測可能な環境を好み、職の安定性を最優先する。リスク回避は消極的ではない。確保したものを守る戦略も強力な生存方式。',
      'zh-CN': '你不会把钱投到可能亏损的地方，比起陌生环境更偏好可预测的环境，工作稳定是第一标准。回避风险并不消极——守住已有成果也是强大的生存策略。',
      'zh-TW': '你不會把錢投到可能虧損的地方，比起陌生環境更偏好可預測的環境，工作穩定是第一標準。迴避風險並不消極——守住已有成果也是強大的生存策略。',
      vi: 'Bạn không bỏ tiền vào thứ có thể lỗ, thích môi trường dự đoán được hơn tình huống lạ, và ưu tiên ổn định nghề nghiệp. Tránh rủi ro không phải thụ động—bảo vệ những gì đã có cũng là chiến lược sống mạnh.',
      id: 'Kamu tidak taruh uang di hal yang bisa rugi, lebih suka lingkungan terprediksi daripada situasi asing, dan stabilitas kerja jadi prioritas. Menghindari risiko bukan pasif—melindungi yang sudah terkumpul juga strategi hidup yang kuat.',
    }),
    riskType: localeMap({
      ko: '안전 제일형 🛡️',
      en: 'Safety First Type 🛡️',
      ja: '安全第一型 🛡️',
      'zh-CN': '安全第一型 🛡️',
      'zh-TW': '安全第一型 🛡️',
      vi: 'Kiểu an toàn là trên hết 🛡️',
      id: 'Tipe keamanan dulu 🛡️',
    }),
    riskAcceptanceLevel: localeMap({
      ko: '매우 낮음 (0~15%)',
      en: 'Very low (0–15%)',
      ja: '非常に低い（0〜15%）',
      'zh-CN': '非常低（0~15%）',
      'zh-TW': '非常低（0~15%）',
      vi: 'Rất thấp (0–15%)',
      id: 'Sangat rendah (0–15%)',
    }),
    financialDiagnosis: localeMap({
      ko: '원금 보장 상품 선호. 주식·투자보다 예금·적금이 편함',
      en: 'Prefers principal-protected products. Deposits/savings feel safer than stocks',
      ja: '元本保証商品を好む。株・投資より預金・積立が安心',
      'zh-CN': '偏好保本产品，存款/储蓄比股票投资更安心',
      'zh-TW': '偏好保本產品，存款/儲蓄比股票投資更安心',
      vi: 'Thích sản phẩm bảo toàn vốn. Tiết kiệm/gửi ngân hàng an tâm hơn cổ phiếu',
      id: 'Suka produk jaminan pokok. Deposito/tabungan lebih nyaman daripada saham',
    }),
    socialDiagnosis: localeMap({
      ko: '먼저 나서기보다 환경이 갖춰질 때까지 기다리는 편',
      en: 'Waits for the right setting rather than stepping forward first',
      ja: '先に出るより環境が整うまで待つ',
      'zh-CN': '比起先出手，更倾向等环境成熟',
      'zh-TW': '比起先出手，更傾向等環境成熟',
      vi: 'Chờ bối cảnh sẵn sàng hơn là chủ động trước',
      id: 'Menunggu situasi siap daripada maju duluan',
    }),
    physicalDiagnosis: localeMap({
      ko: '익스트림 경험보다 안전하고 예측 가능한 경험 선호',
      en: 'Prefers safe, predictable experiences over extreme ones',
      ja: 'エクストリームより安全で予測可能な経験を好む',
      'zh-CN': '比起极限体验，更偏好安全可预测的体验',
      'zh-TW': '比起極限體驗，更偏好安全可預測的體驗',
      vi: 'Thích trải nghiệm an toàn, dự đoán được hơn mạo hiểm',
      id: 'Lebih suka pengalaman aman dan terprediksi daripada ekstrem',
    }),
    careerDiagnosis: localeMap({
      ko: '안정적인 직장이 최우선. 이직·창업보다 현재 유지 선호',
      en: 'Stable job is top priority. Prefers staying over switching or starting a business',
      ja: '安定職が最優先。転職・起業より現状維持',
      'zh-CN': '稳定工作最优先，比起跳槽/创业更倾向维持现状',
      'zh-TW': '穩定工作最優先，比起跳槽/創業更傾向維持現狀',
      vi: 'Việc ổn định là ưu tiên số 1. Giữ nguyên hơn chuyển việc/khởi nghiệp',
      id: 'Pekerjaan stabil prioritas utama. Pertahankan status quo daripada pindah/wirausaha',
    }),
    uncertaintyDiagnosis: localeMap({
      ko: '불확실한 상황 자체가 스트레스. 정보가 충분할 때 결정',
      en: 'Uncertainty itself is stressful. Decides when information is sufficient',
      ja: '不確実な状況自体がストレス。情報が十分なとき決める',
      'zh-CN': '不确定本身就有压力，信息充分时才决定',
      'zh-TW': '不確定本身就有壓力，資訊充分時才決定',
      vi: 'Bản thân sự không chắc chắn đã gây stress. Quyết khi đủ thông tin',
      id: 'Ketidakpastian sendiri sudah stres. Memutuskan saat informasi cukup',
    }),
    strengths: localeMap({
      ko: '충동적 손실이 없음. 쌓아온 것을 잘 지킴. 재무 관리 능력 우수',
      en: 'No impulsive losses. Good at protecting what you\'ve built. Strong financial discipline',
      ja: '衝動的損失がない。築いたものを守るのが上手。財務管理能力が優秀',
      'zh-CN': '没有冲动亏损，善于守住积累，财务管理能力强',
      'zh-TW': '沒有衝動虧損，善於守住累積，財務管理能力強',
      vi: 'Không lỗ do bốc đồng. Giữ tốt những gì đã xây. Quản lý tài chính giỏi',
      id: 'Tidak rugi impulsif. Hebat menjaga yang sudah dibangun. Disiplin keuangan kuat',
    }),
    caution: localeMap({
      ko: '기회 비용. 리스크를 완전히 피하는 것도 장기적으로는 리스크가 될 수 있음',
      en: 'Opportunity cost. Avoiding all risk can become a long-term risk itself',
      ja: '機会費用。リスクを完全回避することも長期的にはリスクになり得る',
      'zh-CN': '机会成本，完全回避风险长期看也可能成为风险',
      'zh-TW': '機會成本，完全迴避風險長期看也可能成為風險',
      vi: 'Chi phí cơ hội. Tránh mọi rủi ro lâu dài cũng có thể thành rủi ro',
      id: 'Biaya peluang. Menghindari semua risiko jangka panjang juga bisa jadi risiko',
    }),
    investmentStyle: localeMap({
      ko: '안전 자산 중심 포트폴리오. 예금·국채·배당주 위주',
      en: 'Safety-first portfolio: deposits, bonds, dividend stocks',
      ja: '安全資産中心。預金・国債・配当株中心',
      'zh-CN': '以安全资产为主：存款、国债、股息股',
      'zh-TW': '以安全資產為主：存款、國債、股息股',
      vi: 'Danh mục an toàn: tiết kiệm, trái phiếu, cổ phiếu cổ tức',
      id: 'Portofolio aman: deposito, obligasi, saham dividen',
    }),
    entrepreneurshipStyle: localeMap({
      ko: '창업보다 안정적 직장 선호. 사이드 프로젝트부터 소규모로 시작하는 것이 적합',
      en: 'Prefers stable employment. Side projects or small starts fit better',
      ja: '起業より安定職。サイドプロジェクトから小さく始めるのが適合',
      'zh-CN': '比起创业更偏好稳定工作，副业或小规模起步更合适',
      'zh-TW': '比起創業更偏好穩定工作，副業或小規模起步更合適',
      vi: 'Thích việc ổn định hơn khởi nghiệp. Side project hoặc bắt đầu nhỏ phù hợp hơn',
      id: 'Lebih suka pekerjaan stabil. Side project atau mulai kecil lebih cocok',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '지키는 것도 전략입니다. 다만 너무 지키려다 기회를 놓치지 않도록 가끔은 계산된 작은 도전을 해보는 것도 좋습니다',
      en: 'Protecting is also a strategy. Just don\'t miss opportunities by protecting too much—try a calculated small challenge now and then.',
      ja: '守ることも戦略。ただ守りすぎて機会を逃さないよう、たまには計算された小さな挑戦も。',
      'zh-CN': '守住也是策略，但别因过度保守错过机会，偶尔试试经过计算的小挑战也不错。',
      'zh-TW': '守住也是策略，但別因過度保守錯過機會，偶爾試試經過計算的小挑戰也不錯。',
      vi: 'Giữ cũng là chiến lược. Đừng vì giữ quá mà bỏ lỡ cơ hội—thỉnh thoảng thử thách nhỏ có tính toán.',
      id: 'Menjaga juga strategi. Jangan sampai kehilangan peluang karena terlalu protektif—coba tantangan kecil terhitung sesekali.',
    }),
    shareLine: localeMap({
      ko: '내 위험 감수 성향: 안전 제일형 🛡️ 원금 손실은 절대 안 된다는 유형... 지키는 것도 전략이래 맞음 → 위험 감수 결과 너는 어떤 유형이야?',
      en: 'My risk tolerance: Safety First Type 🛡️ Never okay with losing principal... protecting is a strategy too, so true → What\'s your risk type?',
      ja: '私のリスク許容度：安全第一型 🛡️ 元本割れ絶対NGタイプ…守るのも戦略って当たり → あなたはどのリスクタイプ？',
      'zh-CN': '我的风险承受力：安全第一型 🛡️ 绝对不能亏本金型…守住也是策略 太准 → 你是什么风险类型？',
      'zh-TW': '我的風險承受力：安全第一型 🛡️ 絕對不能虧本金型…守住也是策略 太準 → 你是什麼風險類型？',
      vi: 'Mức chấp nhận rủi ro của tôi: Kiểu an toàn là trên hết 🛡️ Tuyệt đối không mất vốn… giữ cũng là chiến lược, đúng quá → Bạn thuộc kiểu rủi ro nào?',
      id: 'Toleransi risiko-ku: Tipe keamanan dulu 🛡️ Pokok modal tidak boleh hilang… menjaga juga strategi, bener banget → Kamu tipe risiko apa?',
    }),
  },
  {
    type: "Type2",
    emoji: "🔍",
    title: localeMap({
      ko: '꼼꼼히 따지고 조심스럽게 가는, 신중 분석형',
      en: 'Careful and Measured',
      ja: '慎重に分析してから動く',
      'zh-CN': '仔细分析后再行动',
      'zh-TW': '仔細分析後再行動',
      vi: 'Cẩn trọng và có tính toán',
      id: 'Hati-hati dan terukur',
    }),
    riskLevel: localeMap({
      ko: '낮음 / 분석 후 소규모 리스크 수용',
      en: 'Low / Small risks after analysis',
      ja: '低い / 分析後に小規模リスクを受容',
      'zh-CN': '较低 / 分析后接受小规模风险',
      'zh-TW': '較低 / 分析後接受小規模風險',
      vi: 'Thấp / Chấp nhận rủi ro nhỏ sau phân tích',
      id: 'Rendah / Risiko kecil setelah analisis',
    }),
    quote: localeMap({
      ko: '당신은 리스크를 피하는 게 아니라 충분히 이해한 다음 움직이는 사람입니다.',
      en: 'You don\'t avoid risk—you move after you understand it well enough.',
      ja: 'あなたはリスクを避けるのではなく、十分理解してから動く人。',
      'zh-CN': '你不是回避风险，而是充分理解之后再行动。',
      'zh-TW': '你不是迴避風險，而是充分理解之後再行動。',
      vi: 'Bạn không tránh rủi ro—bạn hành động sau khi hiểu đủ.',
      id: 'Kamu tidak menghindari risiko—kamu bergerak setelah cukup memahaminya.',
    }),
    description: localeMap({
      ko: '완전한 회피보다는 충분한 정보 수집과 분석 후 소규모 리스크를 선택적으로 수용하는 타입입니다. 충동적인 결정보다 근거 있는 결정을 선호하고 작은 리스크를 통해 경험을 쌓아가며 점진적으로 확장하는 방식을 택합니다.',
      en: 'Rather than total avoidance, you gather information, analyze, then accept small risks selectively. You prefer evidence-based decisions over impulse and expand gradually through experience.',
      ja: '完全回避より情報収集と分析の後、小さなリスクを選択的に受け入れる。衝動より根拠ある決定を好み、小さなリスクで経験を積み段階的に広げる。',
      'zh-CN': '比起完全回避，你会先收集信息、分析，再有选择地接受小风险。比起冲动更偏好有依据的决定，通过小风险积累经验、逐步扩展。',
      'zh-TW': '比起完全迴避，你會先收集資訊、分析，再有選擇地接受小風險。比起衝動更偏好有依據的決定，透過小風險累積經驗、逐步擴展。',
      vi: 'Thay vì tránh hoàn toàn, bạn thu thập thông tin, phân tích, rồi chấp nhận rủi ro nhỏ có chọn lọc. Thích quyết định có căn cứ hơn bốc đồng và mở rộng dần qua trải nghiệm.',
      id: 'Daripada hindari total, kamu kumpulkan info, analisis, lalu terima risiko kecil secara selektif. Lebih suka keputusan berbasis bukti daripada impuls dan berkembang bertahap lewat pengalaman.',
    }),
    riskType: localeMap({
      ko: '신중 분석형 🔍',
      en: 'Careful Analyst Type 🔍',
      ja: '慎重分析型 🔍',
      'zh-CN': '谨慎分析型 🔍',
      'zh-TW': '謹慎分析型 🔍',
      vi: 'Kiểu phân tích thận trọng 🔍',
      id: 'Tipe analis hati-hati 🔍',
    }),
    riskAcceptanceLevel: localeMap({
      ko: '낮음-보통 (15~35%)',
      en: 'Low–moderate (15–35%)',
      ja: '低〜普通（15〜35%）',
      'zh-CN': '低~中等（15~35%）',
      'zh-TW': '低~中等（15~35%）',
      vi: 'Thấp–trung bình (15–35%)',
      id: 'Rendah–sedang (15–35%)',
    }),
    financialDiagnosis: localeMap({
      ko: '분산 투자 선호. 전체의 10~20%만 리스크 자산에 배분',
      en: 'Prefers diversification. Only 10–20% in risky assets',
      ja: '分散投資を好む。全体の10〜20%だけリスク資産',
      'zh-CN': '偏好分散投资，只有10~20%投入风险资产',
      'zh-TW': '偏好分散投資，只有10~20%投入風險資產',
      vi: 'Thích đa dạng hóa. Chỉ 10–20% vào tài sản rủi ro',
      id: 'Suka diversifikasi. Hanya 10–20% di aset berisiko',
    }),
    socialDiagnosis: localeMap({
      ko: '상황이 어느 정도 갖춰지면 먼저 나설 수 있음. 완전한 낯선 환경은 아직 부담',
      en: 'Can step forward once the situation is somewhat ready. Fully unfamiliar settings still feel heavy',
      ja: '状況が整えば先に出られる。完全な未知はまだ負担',
      'zh-CN': '环境差不多成熟时可以主动，完全陌生的场合仍有压力',
      'zh-TW': '環境差不多成熟時可以主動，完全陌生的場合仍有壓力',
      vi: 'Có thể chủ động khi tình huống ổn định phần nào. Môi trường hoàn toàn lạ vẫn áp lực',
      id: 'Bisa maju jika situasi cukup siap. Lingkungan asing total masih terasa berat',
    }),
    physicalDiagnosis: localeMap({
      ko: '안전이 보장된 범위 내에서 새로운 경험에 열려 있음',
      en: 'Open to new experiences within a safety guarantee',
      ja: '安全が担保された範囲なら新しい経験に前向き',
      'zh-CN': '在有安全保障的范围内愿意尝试新体验',
      'zh-TW': '在有安全保障的範圍內願意嘗試新體驗',
      vi: 'Sẵn sàng trải nghiệm mới trong phạm vi an toàn',
      id: 'Terbuka pada pengalaman baru dalam batas aman',
    }),
    careerDiagnosis: localeMap({
      ko: '충분한 준비 후 이직은 가능. 창업은 철저한 준비가 전제',
      en: 'Job change possible after thorough prep. Entrepreneurship needs solid preparation first',
      ja: '十分な準備後なら転職可能。起業は徹底準備が前提',
      'zh-CN': '充分准备后可以跳槽，创业需要充分准备为前提',
      'zh-TW': '充分準備後可以跳槽，創業需要充分準備為前提',
      vi: 'Có thể chuyển việc sau chuẩn bị kỹ. Khởi nghiệp cần chuẩn bị vững trước',
      id: 'Pindah kerja mungkin setelah persiapan matang. Wirausaha butuh persiapan solid dulu',
    }),
    uncertaintyDiagnosis: localeMap({
      ko: '정보가 어느 정도 쌓이면 불확실한 결정도 가능',
      en: 'Can decide under uncertainty once enough info is gathered',
      ja: '情報が一定程度集まれば不確実な決定も可能',
      'zh-CN': '信息积累到一定程度后，也能在不确定中做决定',
      'zh-TW': '資訊累積到一定程度後，也能在不確定中做決定',
      vi: 'Có thể quyết khi đã có đủ thông tin dù còn không chắc chắn',
      id: 'Bisa memutuskan di ketidakpastian setelah info cukup terkumpul',
    }),
    strengths: localeMap({
      ko: '충동적 손실이 적고 분석력이 뛰어남. 리스크 대비 수익 계산이 정교함',
      en: 'Few impulsive losses. Strong analysis. Precise risk-reward calculation',
      ja: '衝動的損失が少ない。分析力が優れ、リスク対リターン計算が精密',
      'zh-CN': '冲动亏损少，分析力强，风险收益计算精细',
      'zh-TW': '衝動虧損少，分析力強，風險收益計算精細',
      vi: 'Ít lỗ bốc đồng. Phân tích giỏi. Tính rủi ro/lợi nhuận chính xác',
      id: 'Sedikit rugi impulsif. Analisis kuat. Perhitungan risiko-imbalan presisi',
    }),
    caution: localeMap({
      ko: '과도한 분석 마비(Analysis Paralysis). 완벽한 조건을 기다리다 기회를 놓치는 경우',
      en: 'Analysis paralysis. Waiting for perfect conditions can mean missing opportunities',
      ja: '分析麻痺。完璧な条件を待ちすぎて機会を逃すことがある',
      'zh-CN': '分析瘫痪，等完美条件可能错过机会',
      'zh-TW': '分析癱瘓，等完美條件可能錯過機會',
      vi: 'Tê liệt phân tích. Chờ điều kiện hoàn hảo có thể bỏ lỡ cơ hội',
      id: 'Analysis paralysis. Menunggu kondisi sempurna bisa kehilangan peluang',
    }),
    investmentStyle: localeMap({
      ko: '안전 자산 70% + 성장 자산 30% 혼합 포트폴리오 적합',
      en: '70% safe + 30% growth mixed portfolio fits well',
      ja: '安全資産70%＋成長資産30%の混合ポートフォリオが適合',
      'zh-CN': '70%安全资产+30%成长资产的混合组合较合适',
      'zh-TW': '70%安全資產+30%成長資產的混合組合較合適',
      vi: 'Danh mục 70% an toàn + 30% tăng trưởng phù hợp',
      id: 'Portofolio 70% aman + 30% growth cocok',
    }),
    entrepreneurshipStyle: localeMap({
      ko: '부업·사이드 프로젝트로 시작해 리스크를 단계적으로 높이는 방식 적합',
      en: 'Start with side projects and raise risk step by step',
      ja: '副業・サイドから始め、段階的にリスクを上げる方式が適合',
      'zh-CN': '从副业/ side project 起步，逐步提高风险较合适',
      'zh-TW': '從副業/side project 起步，逐步提高風險較合適',
      vi: 'Bắt đầu từ side project và tăng rủi ro từng bước',
      id: 'Mulai dari side project dan naikkan risiko bertahap',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '신중함은 강점입니다. 다만 완벽한 조건은 오지 않는다는 것도 기억하세요',
      en: 'Caution is a strength. Just remember perfect conditions rarely arrive.',
      ja: '慎重さは強み。完璧な条件は来ないことも覚えておいて。',
      'zh-CN': '谨慎是优势，但也请记住完美条件很少出现。',
      'zh-TW': '謹慎是優勢，但也請記住完美條件很少出現。',
      vi: 'Thận trọng là điểm mạnh. Nhưng nhớ rằng điều kiện hoàn hảo hiếm khi tới.',
      id: 'Kehati-hatian adalah kekuatan. Ingat kondisi sempurna jarang datang.',
    }),
    shareLine: localeMap({
      ko: '내 위험 감수 성향: 신중 분석형 🔍 꼼꼼히 따진 다음 소규모 리스크만 수용... 완벽한 조건 기다리다 기회 놓친다는 거 뜨끔 ㅋㅋ → 너는 어떤 리스크 유형이야?',
      en: 'My risk tolerance: Careful Analyst Type 🔍 Only take small risks after checking everything... waiting for perfect conditions hits hard lol → What\'s your risk type?',
      ja: '私のリスク許容度：慎重分析型 🔍 しっかり調べてから小さなリスクだけ…完璧待ちで機会逃すって刺さる ㅋㅋ → あなたはどのリスクタイプ？',
      'zh-CN': '我的风险承受力：谨慎分析型 🔍 仔细研究后才接受小风险型…等完美条件错过机会 扎心了 哈哈 → 你是什么风险类型？',
      'zh-TW': '我的風險承受力：謹慎分析型 🔍 仔細研究後才接受小風險型…等完美條件錯過機會 扎心了 哈哈 → 你是什麼風險類型？',
      vi: 'Mức chấp nhận rủi ro của tôi: Kiểu phân tích thận trọng 🔍 Chỉ nhận rủi ro nhỏ sau khi nghiên cứu kỹ… chờ hoàn hảo rồi lỡ cơ hội, đúng quá haha → Bạn thuộc kiểu rủi ro nào?',
      id: 'Toleransi risiko-ku: Tipe analis hati-hati 🔍 Cek dulu baru terima risiko kecil… nunggu kondisi sempurna malah kelewat peluang wkwk → Kamu tipe risiko apa?',
    }),
  },
  {
    type: "Type3",
    emoji: "♟️",
    title: localeMap({
      ko: '계산하고 베팅하는, 전략적 리스크 테이커형',
      en: 'Calculated Risk Taker',
      ja: '計算して賭ける',
      'zh-CN': '计算后再下注',
      'zh-TW': '計算後再下注',
      vi: 'Người cược có tính toán',
      id: 'Pengambil risiko terhitung',
    }),
    riskLevel: localeMap({
      ko: '보통 / 분석 기반 균형 잡힌 리스크 수용',
      en: 'Moderate / Balanced risk with analysis',
      ja: '普通 / 分析に基づくバランス型リスク受容',
      'zh-CN': '中等 / 基于分析的平衡型风险承受',
      'zh-TW': '中等 / 基於分析的平衡型風險承受',
      vi: 'Trung bình / Rủi ro cân bằng dựa trên phân tích',
      id: 'Sedang / Risiko seimbang berbasis analisis',
    }),
    quote: localeMap({
      ko: '당신은 위험을 피하지도 무모하게 뛰어들지도 않습니다. 계산하고 베팅합니다.',
      en: 'You neither avoid risk nor jump in recklessly. You calculate, then bet.',
      ja: 'あなたはリスクを避けもせず、無謀にも飛び込まない。計算して賭ける。',
      'zh-CN': '你既不回避风险，也不盲目冲进去。你会计算，然后下注。',
      'zh-TW': '你既不迴避風險，也不盲目衝進去。你會計算，然後下注。',
      vi: 'Bạn không tránh rủi ro cũng không lao vào liều lĩnh. Bạn tính toán rồi mới cược.',
      id: 'Kamu tidak menghindari risiko juga tidak loncat sembarangan. Kamu hitung, lalu bertaruh.',
    }),
    description: localeMap({
      ko: '리스크와 수익의 비율을 계산하고 근거가 충분하면 과감하게 행동할 수 있는 타입입니다. 완전한 안전보다 기회를 택하는 경향이 있지만 충동적이지 않습니다. 불확실성 앞에서 현재 가진 정보로 최선의 결정을 내리고 실행하면서 수정하는 방식을 택합니다.',
      en: 'You weigh risk against reward and act boldly when the case is strong. You lean toward opportunity over total safety, but you\'re not impulsive. You decide with what you have and adjust while executing.',
      ja: 'リスクとリターンを計算し、根拠が十分なら大胆に動ける。完全な安全より機会を選ぶが衝動的ではない。今ある情報で最善を決め、実行しながら修正する。',
      'zh-CN': '你会计算风险与回报，依据充分时敢于行动。比起绝对安全更倾向机会，但不冲动。用现有信息做最好决定，边执行边调整。',
      'zh-TW': '你會計算風險與回報，依據充分時敢於行動。比起絕對安全更傾向機會，但不衝動。用現有資訊做最好決定，邊執行邊調整。',
      vi: 'Bạn cân rủi ro và lợi nhuận, hành động mạnh khi căn cứ đủ. Nghiêng về cơ hội hơn an toàn tuyệt đối nhưng không bốc đồng. Quyết với thông tin hiện có và chỉnh trong lúc thực hiện.',
      id: 'Kamu timbang risiko vs imbalan dan berani bertindak jika buktinya kuat. Lebih pilih peluang daripada aman total, tapi tidak impulsif. Putuskan dengan info sekarang dan koreksi sambil jalan.',
    }),
    riskType: localeMap({
      ko: '전략적 리스크 테이커형 ♟️',
      en: 'Strategic Risk Taker Type ♟️',
      ja: '戦略的リスクテイカー型 ♟️',
      'zh-CN': '战略性风险承担型 ♟️',
      'zh-TW': '戰略性風險承擔型 ♟️',
      vi: 'Kiểu nhận rủi ro chiến lược ♟️',
      id: 'Tipe pengambil risiko strategis ♟️',
    }),
    riskAcceptanceLevel: localeMap({
      ko: '보통-높음 (35~60%)',
      en: 'Moderate–high (35–60%)',
      ja: '普通〜高い（35〜60%）',
      'zh-CN': '中~高（35~60%）',
      'zh-TW': '中~高（35~60%）',
      vi: 'Trung bình–cao (35–60%)',
      id: 'Sedang–tinggi (35–60%)',
    }),
    financialDiagnosis: localeMap({
      ko: '분산 투자. 안전 자산과 성장 자산 균형. 시장 하락 시 추가 매수 고려',
      en: 'Diversified mix of safe and growth assets. May buy more on dips',
      ja: '安全資産と成長資産の分散。下落時は追加買いも検討',
      'zh-CN': '安全与成长资产分散配置，下跌时可能考虑加仓',
      'zh-TW': '安全與成長資產分散配置，下跌時可能考慮加倉',
      vi: 'Phân tán giữa tài sản an toàn và tăng trưởng. Có thể mua thêm khi giảm',
      id: 'Campuran aset aman dan growth. Bisa beli tambahan saat turun',
    }),
    socialDiagnosis: localeMap({
      ko: '낯선 환경에서도 먼저 나설 수 있음. 거절을 경험으로 받아들임',
      en: 'Can step forward even in unfamiliar settings. Treats rejection as experience',
      ja: '未知の環境でも先に出られる。拒否も経験として受け止める',
      'zh-CN': '陌生环境也能主动，把拒绝当作经验',
      'zh-TW': '陌生環境也能主動，把拒絕當作經驗',
      vi: 'Có thể chủ động cả trong môi trường lạ. Coi từ chối là trải nghiệm',
      id: 'Bisa maju bahkan di lingkungan asing. Menolak ditolak sebagai pengalaman',
    }),
    physicalDiagnosis: localeMap({
      ko: '새로운 경험에 적극적. 어느 정도의 익스트림도 즐김',
      en: 'Active about new experiences. Enjoys some level of extreme activities',
      ja: '新しい経験に積極的。ある程度のエクストリームも楽しむ',
      'zh-CN': '积极尝试新体验，一定程度享受极限活动',
      'zh-TW': '積極嘗試新體驗，一定程度享受極限活動',
      vi: 'Tích cực với trải nghiệm mới. Thích mức mạo hiểm nhất định',
      id: 'Aktif mencoba pengalaman baru. Menikmati aktivitas ekstrem sejumlah tertentu',
    }),
    careerDiagnosis: localeMap({
      ko: '가능성 있는 이직·스타트업 이동 가능. 창업 아이디어가 있고 준비 중',
      en: 'Open to promising job moves or startups. Has ideas and is preparing',
      ja: '可能性ある転職・スタートアップ移行可能。アイデアがあり準備中',
      'zh-CN': '可能的话愿意跳槽/加入创业公司，有想法并在准备',
      'zh-TW': '可能的話願意跳槽/加入新創公司，有想法並在準備',
      vi: 'Có thể chuyển việc/startup nếu tiềm năng đủ. Có ý tưởng và đang chuẩn bị',
      id: 'Terbuka pindah kerja/startup jika potensinya ada. Punya ide dan sedang menyiapkan',
    }),
    uncertaintyDiagnosis: localeMap({
      ko: '불확실성을 스트레스보다 기회로 인식하는 경향',
      en: 'Tends to see uncertainty as opportunity more than stress',
      ja: '不確実性をストレスより機会として認識する傾向',
      'zh-CN': '倾向把不确定看作机会而非压力',
      'zh-TW': '傾向把不確定看作機會而非壓力',
      vi: 'Thường coi không chắc chắn là cơ hội hơn là stress',
      id: 'Cenderung melihat ketidakpastian sebagai peluang, bukan stres',
    }),
    strengths: localeMap({
      ko: '기회를 포착하는 능력과 실행력이 균형 잡혀 있음. 분석과 행동 사이의 균형',
      en: 'Balanced ability to spot opportunities and execute. Good balance between analysis and action',
      ja: '機会を掴む力と実行力のバランス。分析と行動の均衡',
      'zh-CN': '捕捉机会与执行力的平衡，分析与行动之间拿捏得当',
      'zh-TW': '捕捉機會與執行力的平衡，分析與行動之間拿捏得當',
      vi: 'Cân bằng giữa nắm cơ hội và thực thi. Cân bằng phân tích và hành động',
      id: 'Keseimbangan menangkap peluang dan eksekusi. Balance analisis dan aksi',
    }),
    caution: localeMap({
      ko: '과신 리스크. 계산이 정확하다고 믿는 만큼 착각도 발생할 수 있음',
      en: 'Overconfidence risk. Believing your calculation is perfect can lead to blind spots',
      ja: '過信リスク。計算が正確だと信じすぎると盲点が生じる',
      'zh-CN': '过度自信风险，相信计算完全正确可能产生盲点',
      'zh-TW': '過度自信風險，相信計算完全正確可能產生盲點',
      vi: 'Rủi ro quá tự tin. Tin tính toán luôn đúng có thể tạo điểm mù',
      id: 'Risiko overconfidence. Percaya perhitungan sempurna bisa bikin blind spot',
    }),
    investmentStyle: localeMap({
      ko: '성장주·ETF·일부 대안 투자 혼합 포트폴리오. 분산 투자 필수',
      en: 'Growth stocks, ETFs, some alternative investments. Diversification essential',
      ja: '成長株・ETF・一部オルタナ投資。分散投資必須',
      'zh-CN': '成长股、ETF、部分另类投资，分散必不可少',
      'zh-TW': '成長股、ETF、部分另類投資，分散必不可少',
      vi: 'Cổ phiếu tăng trưởng, ETF, một phần đầu tư thay thế. Đa dạng hóa là bắt buộc',
      id: 'Saham growth, ETF, sebagian alternatif. Diversifikasi wajib',
    }),
    entrepreneurshipStyle: localeMap({
      ko: '충분한 준비 후 창업 가능. 린 스타트업 방식(빠른 실행·검증·수정) 적합',
      en: 'Can start a business after enough prep. Lean startup style fits well',
      ja: '十分な準備後なら起業可能。リーンスタートアップ方式が適合',
      'zh-CN': '准备充分后可以创业，精益创业方式较合适',
      'zh-TW': '準備充分後可以創業，精益創業方式較合適',
      vi: 'Có thể khởi nghiệp sau chuẩn bị đủ. Mô hình lean startup phù hợp',
      id: 'Bisa wirausaha setelah persiapan cukup. Gaya lean startup cocok',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '이 균형이 가장 오래 지속 가능한 리스크 전략입니다. 계산하되 너무 오래 계산하지 마세요',
      en: 'This balance is the most sustainable risk strategy. Calculate—but don\'t calculate forever.',
      ja: 'このバランスが最も持続可能なリスク戦略。計算しつつ、計算しすぎないで。',
      'zh-CN': '这种平衡是最可持续的风险策略。要计算，但别一直计算。',
      'zh-TW': '這種平衡是最可持續的風險策略。要計算，但別一直計算。',
      vi: 'Cân bằng này là chiến lược rủi ro bền nhất. Hãy tính toán—nhưng đừng tính mãi.',
      id: 'Keseimbangan ini strategi risiko paling sustainable. Hitung—tapi jangan hitung selamanya.',
    }),
    shareLine: localeMap({
      ko: '내 위험 감수 성향: 전략적 리스크 테이커형 ♟️ 계산하고 베팅하는 유형이래... 분석과 행동의 균형 맞음 → 위험 감수 결과 투자 관심층 다 해봐',
      en: 'My risk tolerance: Strategic Risk Taker Type ♟️ Calculate then bet... balance of analysis and action is spot on → If you\'re into investing, try this',
      ja: '私のリスク許容度：戦略的リスクテイカー型 ♟️ 計算して賭けるタイプ…分析と行動のバランス当たり → 投資好きならやってみて',
      'zh-CN': '我的风险承受力：战略性风险承担型 ♟️ 计算后再下注型…分析与行动的平衡 太准 → 对投资感兴趣的都试试',
      'zh-TW': '我的風險承受力：戰略性風險承擔型 ♟️ 計算後再下注型…分析與行動的平衡 太準 → 對投資感興趣的都試試',
      vi: 'Mức chấp nhận rủi ro của tôi: Kiểu nhận rủi ro chiến lược ♟️ Tính toán rồi mới cược… cân bằng phân tích và hành động, đúng quá → Ai quan tâm đầu tư thử đi',
      id: 'Toleransi risiko-ku: Tipe pengambil risiko strategis ♟️ Hitung dulu baru taruhan… balance analisis dan aksi, pas banget → Yang suka investasi coba deh',
    }),
  },
  {
    type: "Type4",
    emoji: "🚀",
    title: localeMap({
      ko: '기회가 보이면 먼저 달려드는, 적극적 모험형',
      en: 'Runs Toward Opportunity',
      ja: '機会が見えたら走る',
      'zh-CN': '看见机会就冲',
      'zh-TW': '看見機會就衝',
      vi: 'Lao về phía cơ hội',
      id: 'Berlari ke arah peluang',
    }),
    riskLevel: localeMap({
      ko: '높음 / 기회에 능동적으로 베팅',
      en: 'High / Actively bets on opportunity',
      ja: '高い / 機会に能動的に賭ける',
      'zh-CN': '较高 / 主动为机会下注',
      'zh-TW': '較高 / 主動為機會下注',
      vi: 'Cao / Chủ động cược vào cơ hội',
      id: 'Tinggi / Aktif bertaruh pada peluang',
    }),
    quote: localeMap({
      ko: '당신에게 리스크는 피해야 할 것이 아니라 수익의 원천입니다.',
      en: 'For you, risk isn\'t something to avoid—it\'s a source of reward.',
      ja: 'あなたにとってリスクは避けるものではなく、リターンの源。',
      'zh-CN': '对你来说，风险不是要避开的东西，而是回报的来源。',
      'zh-TW': '對你來說，風險不是要避開的東西，而是回報的來源。',
      vi: 'Với bạn, rủi ro không phải thứ cần tránh—mà là nguồn lợi nhuận.',
      id: 'Bagimu, risiko bukan hal yang dihindari—melainkan sumber imbalan.',
    }),
    description: localeMap({
      ko: '안정보다 기회를 우선시하고 불확실한 상황에서도 비교적 빠르게 결정하며 실패를 경험으로 받아들이는 타입입니다. 낯선 환경에서 오히려 에너지가 올라오고 현재 상태를 유지하는 것보다 성장과 변화를 선택하는 경향이 있습니다.',
      en: 'You prioritize opportunity over stability, decide relatively fast even in uncertainty, and treat failure as experience. Unfamiliar settings energize you, and you choose growth and change over staying the same.',
      ja: '安定より機会を優先し、不確実でも比較的早く決め、失敗を経験として受け止める。未知の環境でエネルギーが上がり、現状維持より成長と変化を選ぶ。',
      'zh-CN': '你优先机会而非稳定，在不确定中也能较快决定，把失败当作经验。陌生环境反而让你更有能量，比起维持现状更选择成长与变化。',
      'zh-TW': '你優先機會而非穩定，在不確定中也能較快決定，把失敗當作經驗。陌生環境反而讓你更有能量，比起維持現狀更選擇成長與變化。',
      vi: 'Bạn ưu tiên cơ hội hơn ổn định, quyết nhanh dù không chắc chắn, và coi thất bại là kinh nghiệm. Môi trường lạ làm bạn thêm năng lượng, chọn tăng trưởng và thay đổi hơn giữ nguyên.',
      id: 'Kamu prioritaskan peluang daripada stabilitas, memutuskan relatif cepat meski tidak pasti, dan melihat kegagalan sebagai pengalaman. Lingkungan asing justru memberi energi, memilih growth dan perubahan daripada diam di tempat.',
    }),
    riskType: localeMap({
      ko: '적극적 모험형 🚀',
      en: 'Active Adventurer Type 🚀',
      ja: '積極的冒険型 🚀',
      'zh-CN': '积极冒险型 🚀',
      'zh-TW': '積極冒險型 🚀',
      vi: 'Kiểu mạo hiểm chủ động 🚀',
      id: 'Tipe petualang aktif 🚀',
    }),
    riskAcceptanceLevel: localeMap({
      ko: '높음 (60~80%)',
      en: 'High (60–80%)',
      ja: '高い（60〜80%）',
      'zh-CN': '高（60~80%）',
      'zh-TW': '高（60~80%）',
      vi: 'Cao (60–80%)',
      id: 'Tinggi (60–80%)',
    }),
    financialDiagnosis: localeMap({
      ko: '공격적 투자 성향. 높은 변동성도 수용 가능. 다만 분산은 필요',
      en: 'Aggressive investing. Can accept high volatility, but still needs diversification',
      ja: '攻撃的投資。高い変動性も受容可能。ただし分散は必要',
      'zh-CN': '投资风格激进，可接受高波动，但仍需分散',
      'zh-TW': '投資風格激進，可接受高波動，但仍需分散',
      vi: 'Đầu tư mạnh tay. Chấp nhận biến động cao, nhưng vẫn cần đa dạng hóa',
      id: 'Investasi agresif. Bisa terima volatilitas tinggi, tapi tetap perlu diversifikasi',
    }),
    socialDiagnosis: localeMap({
      ko: '먼저 나서고 네트워크를 적극적으로 만드는 타입. 거절을 두려워하지 않음',
      en: 'Steps forward first and builds networks actively. Not afraid of rejection',
      ja: '先に出てネットワークを積極的に作る。拒否を恐れない',
      'zh-CN': '主动上前、积极拓展人脉，不怕被拒绝',
      'zh-TW': '主動上前、積極拓展人脈，不怕被拒絕',
      vi: 'Chủ động trước và xây network tích cực. Không sợ bị từ chối',
      id: 'Maju duluan dan bangun jaringan aktif. Tidak takut ditolak',
    }),
    physicalDiagnosis: localeMap({
      ko: '익스트림 경험을 즐김. 새로운 것을 즉흥적으로 시도하는 것이 자연스러움',
      en: 'Enjoys extreme experiences. Spontaneous new tries feel natural',
      ja: 'エクストリームを楽しむ。新しいことへの即興挑戦が自然',
      'zh-CN': '享受极限体验，即兴尝试新事物很自然',
      'zh-TW': '享受極限體驗，即興嘗試新事物很自然',
      vi: 'Thích trải nghiệm mạo hiểm. Thử mới bốc đồng rất tự nhiên',
      id: 'Menikmati pengalaman ekstrem. Coba hal baru spontan terasa natural',
    }),
    careerDiagnosis: localeMap({
      ko: '이직·스타트업·창업에 적극적. 안정보다 성장 가능성 우선',
      en: 'Active about job moves, startups, and entrepreneurship. Growth beats stability',
      ja: '転職・スタートアップ・起業に積極的。安定より成長可能性',
      'zh-CN': '对跳槽、创业、加入创业公司都很积极，成长比稳定重要',
      'zh-TW': '對跳槽、創業、加入新創公司都很積極，成長比穩定重要',
      vi: 'Tích cực với chuyển việc, startup, khởi nghiệp. Tăng trưởng quan trọng hơn ổn định',
      id: 'Aktif soal pindah kerja, startup, wirausaha. Growth lebih penting dari stabilitas',
    }),
    uncertaintyDiagnosis: localeMap({
      ko: '불확실성을 기회로 인식. 확실한 것은 이미 늦었다고 생각',
      en: 'Sees uncertainty as opportunity. Thinks certainty means you\'re late',
      ja: '不確実性を機会と認識。確実なものはもう遅いと考える',
      'zh-CN': '把不确定看作机会，觉得太确定就已经晚了',
      'zh-TW': '把不確定看作機會，覺得太確定就已經晚了',
      vi: 'Coi không chắc chắn là cơ hội. Nghĩ chắc chắn quá nghĩa là đã muộn',
      id: 'Melihat ketidakpastian sebagai peluang. Yakin berarti sudah telat',
    }),
    strengths: localeMap({
      ko: '기회 포착 속도가 빠름. 실패에서 빠르게 회복하는 능력. 변화에 강함',
      en: 'Fast at catching opportunities. Recovers quickly from failure. Strong in change',
      ja: '機会捕捉が速い。失敗からの回復が早い。変化に強い',
      'zh-CN': '抓机会快，失败后恢复快，适应变化强',
      'zh-TW': '抓機會快，失敗後恢復快，適應變化強',
      vi: 'Nắm cơ hội nhanh. Phục hồi sau thất bại nhanh. Mạnh trong thay đổi',
      id: 'Cepat menangkap peluang. Pulih cepat dari kegagalan. Kuat dalam perubahan',
    }),
    caution: localeMap({
      ko: '충분한 분석 없이 움직이는 과속 리스크. 레버리지 과다 사용 주의',
      en: 'Overspeed risk without enough analysis. Watch excessive leverage',
      ja: '分析不足での過速リスク。レバレッジ過多に注意',
      'zh-CN': '分析不足就行动的风险，注意过度杠杆',
      'zh-TW': '分析不足就行動的風險，注意過度槓桿',
      vi: 'Rủi ro đi quá nhanh khi thiếu phân tích. Cẩn thận đòn bẩy quá mức',
      id: 'Risiko terlalu cepat tanpa analisis cukup. Waspadai leverage berlebihan',
    }),
    investmentStyle: localeMap({
      ko: '성장주·스타트업 투자·암호화폐 등 고위험 고수익 자산 포함. 철저한 리스크 관리 필수',
      en: 'Growth stocks, startup investing, crypto, etc. Strict risk rules required',
      ja: '成長株・スタートアップ投資・暗号資産など。厳格なリスク管理必須',
      'zh-CN': '成长股、初创投资、加密货币等，必须严格风险管理',
      'zh-TW': '成長股、新創投資、加密貨幣等，必須嚴格風險管理',
      vi: 'Cổ phiếu tăng trưởng, đầu tư startup, crypto… cần quy tắc quản trị rủi ro chặt',
      id: 'Saham growth, investasi startup, crypto, dll. Aturan manajemen risiko ketat wajib',
    }),
    entrepreneurshipStyle: localeMap({
      ko: '창업 가능성이 높은 유형. 아이디어가 생기면 빠르게 실행하는 방식 선호',
      en: 'High startup potential. Prefers fast execution when ideas appear',
      ja: '起業可能性が高い。アイデアが出たら素早く実行する方式',
      'zh-CN': '创业可能性高，有想法就偏好快速执行',
      'zh-TW': '創業可能性高，有想法就偏好快速執行',
      vi: 'Tiềm năng khởi nghiệp cao. Thích thực thi nhanh khi có ý tưởng',
      id: 'Potensi wirausaha tinggi. Suka eksekusi cepat saat ide muncul',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '당신의 속도와 에너지는 강점입니다. 다만 속도가 빠를수록 방향 점검을 자주 해야 합니다',
      en: 'Your speed and energy are strengths. The faster you go, the more often you need to check direction.',
      ja: '速度とエネルギーは強み。速いほど方向確認をこまめに。',
      'zh-CN': '你的速度和能量是优势，越快越要经常校正方向。',
      'zh-TW': '你的速度和能量是優勢，越快越要經常校正方向。',
      vi: 'Tốc độ và năng lượng là điểm mạnh. Càng nhanh càng cần kiểm tra hướng thường xuyên.',
      id: 'Kecepatan dan energi adalah kekuatan. Semakin cepat, semakin sering cek arah.',
    }),
    shareLine: localeMap({
      ko: '내 위험 감수 성향: 적극적 모험형 🚀 기회 보이면 달려드는 유형이래... 안정보다 성장 우선하는 거 맞음 ㅋㅋ → 창업·투자 관심 있으면 해봐',
      en: 'My risk tolerance: Active Adventurer Type 🚀 Runs when opportunity shows up... growth over stability, so true lol → Try this if you\'re into startups or investing',
      ja: '私のリスク許容度：積極的冒険型 🚀 機会見たら走るタイプ…安定より成長、当たり ㅋㅋ → 起業・投資好きならやってみて',
      'zh-CN': '我的风险承受力：积极冒险型 🚀 看见机会就冲型…成长优先于稳定 太准 哈哈 → 对创业/投资感兴趣试试',
      'zh-TW': '我的風險承受力：積極冒險型 🚀 看見機會就衝型…成長優先於穩定 太準 哈哈 → 對創業/投資感興趣試試',
      vi: 'Mức chấp nhận rủi ro của tôi: Kiểu mạo hiểm chủ động 🚀 Thấy cơ hội là lao… ưu tiên tăng trưởng hơn ổn định, đúng quá haha → Ai thích startup/đầu tư thử đi',
      id: 'Toleransi risiko-ku: Tipe petualang aktif 🚀 Lihat peluang langsung gas… growth di atas stabilitas, bener wkwk → Suka startup/investasi? Coba deh',
    }),
  },
  {
    type: "Type5",
    emoji: "⚡",
    title: localeMap({
      ko: '불확실성에서 에너지를 얻는, 고위험 추구형',
      en: 'Energized by Uncertainty',
      ja: '不確実性からエネルギーを得る',
      'zh-CN': '从不确定中获得能量',
      'zh-TW': '從不確定中獲得能量',
      vi: 'Nạp năng lượng từ sự không chắc chắn',
      id: 'Energi dari ketidakpastian',
    }),
    riskLevel: localeMap({
      ko: '매우 높음 / 불확실성 자체를 즐기는 타입',
      en: 'Very high / Enjoys uncertainty itself',
      ja: '非常に高い / 不確実性自体を楽しむ',
      'zh-CN': '非常高 / 享受不确定本身',
      'zh-TW': '非常高 / 享受不確定本身',
      vi: 'Rất cao / Thích bản thân sự không chắc chắn',
      id: 'Sangat tinggi / Menikmati ketidakpastian itu sendiri',
    }),
    quote: localeMap({
      ko: '당신에게 불확실성은 스트레스가 아니라 흥분입니다. 리스크 없는 삶은 너무 지루합니다.',
      en: 'For you, uncertainty isn\'t stress—it\'s excitement. A life without risk feels too boring.',
      ja: 'あなたにとって不確実性はストレスではなく興奮。リスクのない人生は退屈すぎる。',
      'zh-CN': '对你来说，不确定不是压力而是兴奋。没有风险的人生太无聊。',
      'zh-TW': '對你來說，不確定不是壓力而是興奮。沒有風險的人生太無聊。',
      vi: 'Với bạn, không chắc chắn không phải stress mà là hứng khởi. Cuộc sống không rủi ro quá nhàm chán.',
      id: 'Bagimu, ketidakpastian bukan stres—melainkan excitement. Hidup tanpa risiko terlalu membosankan.',
    }),
    description: localeMap({
      ko: '안정적인 것에서 오히려 불편함을 느끼고 높은 변동성·불확실성·도전적 상황에서 더 집중하는 타입입니다. 시장이 폭락할 때 기회를 보고 모두가 두려워하는 구간에 들어가는 결단력이 있습니다. 창업·도전적 커리어·익스트림 경험에서 삶의 에너지를 얻습니다.',
      en: 'Stability feels uncomfortable; you focus better in high volatility and uncertainty. You see opportunity when markets crash and have the nerve to enter when others fear. You draw life energy from entrepreneurship, bold careers, and extreme experiences.',
      ja: '安定から逆に違和感。高い変動性・不確実性・挑戦的状況でより集中する。市場暴落時に機会を見て、皆が恐れる区間に入る決断力がある。起業・挑戦的キャリア・エクストリームからエネルギーを得る。',
      'zh-CN': '稳定反而让你不自在，在高波动、不确定、挑战性的情境中更专注。市场暴跌时看到机会，在别人恐惧时敢于进入。从创业、挑战性职业和极限体验中获得生命能量。',
      'zh-TW': '穩定反而讓你不自在，在高波動、不確定、挑戰性的情境中更專注。市場暴跌時看到機會，在別人恐懼時敢於進入。從創業、挑戰性職業和極限體驗中獲得生命能量。',
      vi: 'Ổn định lại khiến bạn khó chịu; bạn tập trung hơn trong biến động cao và không chắc chắn. Thấy cơ hội khi thị trường sụp và dám vào lúc người khác sợ. Lấy năng lượng từ khởi nghiệp, sự nghiệp táo bạo và trải nghiệm mạo hiểm.',
      id: 'Stabilitas justru terasa tidak nyaman; kamu lebih fokus di volatilitas tinggi dan ketidakpastian. Melihat peluang saat pasar crash dan punya nyali masuk saat orang lain takut. Energi hidup dari wirausaha, karier berani, dan pengalaman ekstrem.',
    }),
    riskType: localeMap({
      ko: '고위험 추구형 ⚡',
      en: 'High Risk Seeker Type ⚡',
      ja: '高リスク追求型 ⚡',
      'zh-CN': '高风险追求型 ⚡',
      'zh-TW': '高風險追求型 ⚡',
      vi: 'Kiểu tìm kiếm rủi ro cao ⚡',
      id: 'Tipe pencari risiko tinggi ⚡',
    }),
    riskAcceptanceLevel: localeMap({
      ko: '매우 높음 (80~95%)',
      en: 'Very high (80–95%)',
      ja: '非常に高い（80〜95%）',
      'zh-CN': '非常高（80~95%）',
      'zh-TW': '非常高（80~95%）',
      vi: 'Rất cao (80–95%)',
      id: 'Sangat tinggi (80–95%)',
    }),
    financialDiagnosis: localeMap({
      ko: '고위험 고수익 투자 선호. 시장 하락 시 적극 매수. 레버리지 활용 가능성 높음',
      en: 'Prefers high-risk high-reward investing. Likely to buy aggressively on dips. May use leverage',
      ja: '高リスク高リターン投資を好む。下落時に積極買い。レバレッジ活用の可能性',
      'zh-CN': '偏好高风险高收益投资，下跌时积极买入，可能使用杠杆',
      'zh-TW': '偏好高風險高收益投資，下跌時積極買入，可能使用槓桿',
      vi: 'Thích đầu tư rủi ro cao-lợi nhuận cao. Mua mạnh khi giảm. Có thể dùng đòn bẩy',
      id: 'Suka investasi high risk high return. Beli agresif saat turun. Mungkin pakai leverage',
    }),
    socialDiagnosis: localeMap({
      ko: '낯선 환경이 오히려 편함. 다양한 배경의 사람들과 빠르게 연결',
      en: 'Unfamiliar settings feel comfortable. Connects quickly with diverse people',
      ja: '未知の環境がむしろ楽。多様な背景の人と素早くつながる',
      'zh-CN': '陌生环境反而自在，能快速连接不同背景的人',
      'zh-TW': '陌生環境反而自在，能快速連接不同背景的人',
      vi: 'Môi trường lạ lại thoải mái. Kết nối nhanh với người đa dạng',
      id: 'Lingkungan asing justru nyaman. Cepat connect dengan orang beragam',
    }),
    physicalDiagnosis: localeMap({
      ko: '익스트림 경험을 즐기고 더 강한 자극을 찾는 경향',
      en: 'Enjoys extreme experiences and seeks stronger stimulation',
      ja: 'エクストリームを楽しみ、より強い刺激を求める',
      'zh-CN': '享受极限体验，并寻找更强刺激',
      'zh-TW': '享受極限體驗，並尋找更強刺激',
      vi: 'Thích trải nghiệm mạo hiểm và tìm kích thích mạnh hơn',
      id: 'Menikmati ekstrem dan mencari stimulasi lebih kuat',
    }),
    careerDiagnosis: localeMap({
      ko: '창업 또는 이미 창업 중. 불안정한 상황이 오히려 동기부여',
      en: 'Entrepreneurship or already building one. Instability can be motivating',
      ja: '起業またはすでに起業中。不安定さがむしろ動機付け',
      'zh-CN': '创业或已在创业，不稳定反而成为动力',
      'zh-TW': '創業或已在創業，不穩定反而成為動力',
      vi: 'Khởi nghiệp hoặc đang khởi nghiệp. Bất ổn có thể là động lực',
      id: 'Wirausaha atau sudah wirausaha. Ketidakstabilan bisa jadi motivasi',
    }),
    uncertaintyDiagnosis: localeMap({
      ko: '불확실성이 높을수록 집중력이 올라가는 패턴',
      en: 'Focus rises as uncertainty rises',
      ja: '不確実性が高いほど集中力が上がる',
      'zh-CN': '不确定越高，专注力越强',
      'zh-TW': '不確定越高，專注力越強',
      vi: 'Càng không chắc chắn càng tập trung hơn',
      id: 'Semakin tidak pasti, semakin fokus',
    }),
    strengths: localeMap({
      ko: '남들이 두려워하는 곳에서 기회를 찾는 능력. 위기 상황에서 빠른 결단',
      en: 'Finds opportunity where others fear. Fast decisions in crisis',
      ja: '皆が恐れる場所で機会を見つける。危機で素早い決断',
      'zh-CN': '在别人害怕处找机会，危机中决策快',
      'zh-TW': '在別人害怕處找機會，危機中決策快',
      vi: 'Tìm cơ hội nơi người khác sợ. Quyết nhanh trong khủng hoảng',
      id: 'Temukan peluang di tempat orang takut. Putus cepat saat krisis',
    }),
    caution: localeMap({
      ko: '과도한 리스크 노출로 인한 치명적 손실 가능성. 리스크 관리 시스템이 반드시 필요. 흥분 상태에서의 비합리적 결정 주의',
      en: 'Risk of fatal loss from overexposure. Need strict risk systems. Watch irrational decisions when excited',
      ja: '過度なリスク暴露による致命的損失の可能性。リスク管理システム必須。興奮時の非合理決定に注意',
      'zh-CN': '过度暴露可能导致致命损失，必须有风险管理系统，注意兴奋时的非理性决定',
      'zh-TW': '過度暴露可能導致致命損失，必須有風險管理系統，注意興奮時的非理性決定',
      vi: 'Nguy cơ thua lỗ nghiêm trọng do lộ rủi ro quá mức. Cần hệ thống quản trị rủi ro. Cẩn thận quyết định phi lý khi hưng phấn',
      id: 'Risiko kerugian fatal karena overexposure. Butuh sistem manajemen risiko ketat. Waspadai keputusan irasional saat excited',
    }),
    investmentStyle: localeMap({
      ko: '집중 투자·고수익 대안 투자 가능하나 반드시 손실 허용 한도 설정 필요',
      en: 'Concentrated or high-return alternatives possible, but must set loss limits',
      ja: '集中投資・高収益オルタナ可能。ただし損失許容上限の設定必須',
      'zh-CN': '可能集中投资或高收益另类资产，但必须设定亏损上限',
      'zh-TW': '可能集中投資或高收益另類資產，但必須設定虧損上限',
      vi: 'Có thể tập trung hoặc đầu tư thay thế lợi nhuận cao, nhưng phải đặt giới hạn lỗ',
      id: 'Bisa concentrated atau alternatif return tinggi, tapi wajib set batas kerugian',
    }),
    entrepreneurshipStyle: localeMap({
      ko: '창업에 가장 적합한 유형 중 하나. 다만 팀 구성 시 신중한 보완 인재 필요',
      en: 'One of the best fit types for startups. Needs careful complementary teammates',
      ja: '起業に最も適したタイプの一つ。ただしチーム補完人材が必要',
      'zh-CN': '最适合创业的类型之一，但需要谨慎搭配互补型队友',
      'zh-TW': '最適合創業的類型之一，但需要謹慎搭配互補型隊友',
      vi: 'Một trong các kiểu phù hợp khởi nghiệp nhất. Cần đồng đội bổ sung cẩn thận',
      id: 'Salah satu tipe paling cocok untuk startup. Butuh rekan tim pelengkap yang hati-hati',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '이 에너지는 강력한 무기입니다. 다만 총이 있다고 무조건 쏘는 게 아니라 언제 쏠지 아는 것이 진짜 실력입니다',
      en: 'This energy is a powerful weapon. Real skill is knowing when to pull the trigger—not firing just because you have a gun.',
      ja: 'このエネルギーは強力な武器。本当の実力はいつ引く金を引くか。銃があるから撃つわけではない。',
      'zh-CN': '这种能量是强大武器，真正的实力是知道何时扣扳机——不是有枪就乱射。',
      'zh-TW': '這種能量是強大武器，真正的實力是知道何時扣扳機——不是有槍就亂射。',
      vi: 'Năng lượng này là vũ khí mạnh. Thự lực thật là biết khi nào bóp cò—không phải có súng là bắn.',
      id: 'Energi ini senjata kuat. Skill sejati adalah tahu kapan menembak—bukan menembak karena punya senjata.',
    }),
    shareLine: localeMap({
      ko: '내 위험 감수 성향: 고위험 추구형 ⚡ 불확실성이 흥분이래... 시장 폭락할 때 오히려 기회 보이는 거 맞음 → 위험 감수 결과 너는 어떤 유형이야?',
      en: 'My risk tolerance: High Risk Seeker Type ⚡ Uncertainty is excitement... seeing opportunity when markets crash, so true → What\'s your risk type?',
      ja: '私のリスク許容度：高リスク追求型 ⚡ 不確実性が興奮…市場暴落時に機会見える、当たり → あなたはどのリスクタイプ？',
      'zh-CN': '我的风险承受力：高风险追求型 ⚡ 不确定就是兴奋型…市场暴跌反而看到机会 太准 → 你是什么风险类型？',
      'zh-TW': '我的風險承受力：高風險追求型 ⚡ 不確定就是興奮型…市場暴跌反而看到機會 太準 → 你是什麼風險類型？',
      vi: 'Mức chấp nhận rủi ro của tôi: Kiểu tìm rủi ro cao ⚡ Không chắc chắn là hứng khởi… thị trường sụp lại vẫn thấy cơ hội, đúng quá → Bạn thuộc kiểu rủi ro nào?',
      id: 'Toleransi risiko-ku: Tipe pencari risiko tinggi ⚡ Ketidakpastian itu excitement… pasar crash malah lihat peluang, bener → Kamu tipe risiko apa?',
    }),
  },
  {
    type: "Type6",
    emoji: "🌋",
    title: localeMap({
      ko: '극한의 불확실성에서 사는 사람, 극한 모험형',
      en: 'Lives in Extreme Uncertainty',
      ja: '極限の不確実性の中で生きる',
      'zh-CN': '活在极端不确定中',
      'zh-TW': '活在極端不確定中',
      vi: 'Sống trong sự không chắc chắn cực đoan',
      id: 'Hidup dalam ketidakpastian ekstrem',
    }),
    riskLevel: localeMap({
      ko: '극한 / 리스크 자체를 삶의 방식으로 통합한 타입',
      en: 'Extreme / Risk integrated into life itself',
      ja: '極限 / リスク自体を生き方に統合',
      'zh-CN': '极端 / 将风险融入生活方式',
      'zh-TW': '極端 / 將風險融入生活方式',
      vi: 'Cực đoan / Rủi ro được tích hợp vào cách sống',
      id: 'Ekstrem / Risiko jadi bagian gaya hidup',
    }),
    quote: localeMap({
      ko: '당신에게 안정은 정체이고 불확실성은 생존 조건입니다. 위험 없는 삶은 살아있는 것이 아니라고 느낍니다.',
      en: 'For you, stability is stagnation and uncertainty is a survival condition. A life without risk doesn\'t feel alive.',
      ja: 'あなたにとって安定は停滞、不確実性は生存条件。リスクのない人生は生きている感じがしない。',
      'zh-CN': '对你来说，稳定是停滞，不确定是生存条件。没有风险的人生不算活着。',
      'zh-TW': '對你來說，穩定是停滯，不確定是生存條件。沒有風險的人生不算活著。',
      vi: 'Với bạn, ổn định là trì trệ và không chắc chắn là điều kiện sinh tồn. Cuộc sống không rủi ro không cảm thấy sống.',
      id: 'Bagimu, stabilitas adalah stagnasi dan ketidakpastian adalah kondisi hidup. Hidup tanpa risiko tidak terasa hidup.',
    }),
    description: localeMap({
      ko: '모든 영역에서 최대 수준의 위험을 감수하는 타입입니다. 시장이 폭락할 때 레버리지를 넣고 아이디어가 생기면 즉시 실행하며 낯선 환경이 가장 편하고 안주하는 것이 가장 두려운 사람입니다. 역사적으로 큰 변화를 만든 사람들 중 이 유형이 많습니다. 동시에 가장 큰 실패도 이 유형에서 나옵니다.',
      en: 'You take maximum risk across every domain. You may leverage into market crashes, execute ideas instantly, feel most at home in unfamiliar settings, and fear staying put most of all. Many history-makers fit this type—and so do the biggest failures.',
      ja: 'すべての領域で最大レベルのリスクを取る。暴落時にレバレッジ、即実行、未知の環境が最も楽、現状維持が最も怖い。歴史を変えた人に多いタイプ。同時に最大の失敗もここから出る。',
      'zh-CN': '你在所有领域都承受最高级别的风险。市场暴跌时可能加杠杆，有想法就立刻执行，陌生环境最自在，最怕停在原地。历史上很多改变时代的人属于这一型，最大的失败也常来自这里。',
      'zh-TW': '你在所有領域都承受最高級別的風險。市場暴跌時可能加槓桿，有想法就立刻執行，陌生環境最自在，最怕停在原地。歷史上很多改變時代的人屬於這一型，最大的失敗也常來自這裡。',
      vi: 'Bạn nhận rủi ro tối đa ở mọi lĩnh vực. Có thể dùng đòn bẩy khi thị trường sụp, thực thi ý tưởng ngay, thoải nhất ở môi trường lạ, sợ nhất là đứng yên. Nhiều người thay đổi lịch sử thuộc kiểu này—và thất bại lớn nhất cũng vậy.',
      id: 'Kamu ambil risiko maksimum di semua domain. Bisa leverage saat pasar crash, eksekusi ide instan, paling nyaman di lingkungan asing, paling takut diam di tempat. Banyak pengubah sejarah tipe ini—dan kegagalan terbesar juga dari sini.',
    }),
    riskType: localeMap({
      ko: '극한 모험형 🌋',
      en: 'Extreme Adventurer Type 🌋',
      ja: '極限冒険型 🌋',
      'zh-CN': '极限冒险型 🌋',
      'zh-TW': '極限冒險型 🌋',
      vi: 'Kiểu mạo hiểm cực đoan 🌋',
      id: 'Tipe petualang ekstrem 🌋',
    }),
    riskAcceptanceLevel: localeMap({
      ko: '극한 (95~100%)',
      en: 'Extreme (95–100%)',
      ja: '極限（95〜100%）',
      'zh-CN': '极端（95~100%）',
      'zh-TW': '極端（95~100%）',
      vi: 'Cực đoan (95–100%)',
      id: 'Ekstrem (95–100%)',
    }),
    financialDiagnosis: localeMap({
      ko: '집중 투자·레버리지·대안 자산 활용. 이미 큰 수익 또는 큰 손실 경험이 있을 수 있음',
      en: 'Concentrated investing, leverage, alternative assets. May already have big wins or losses',
      ja: '集中投資・レバレッジ・オルタナ資産。大きな利益または損失経験がある可能性',
      'zh-CN': '集中投资、杠杆、另类资产，可能已有大盈或大亏经历',
      'zh-TW': '集中投資、槓桿、另類資產，可能已有大盈或大虧經歷',
      vi: 'Đầu tư tập trung, đòn bẩy, tài sản thay thế. Có thể đã từng lãi/lỗ lớn',
      id: 'Investasi concentrated, leverage, aset alternatif. Mungkin sudah pernah untung/rugi besar',
    }),
    socialDiagnosis: localeMap({
      ko: '어떤 환경에서도 주도권을 잡음. 거절·실패·충돌을 경험으로 소화함',
      en: 'Takes the lead in any setting. Processes rejection, failure, and conflict as experience',
      ja: 'どんな環境でも主導権。拒否・失敗・衝突を経験として消化',
      'zh-CN': '任何环境都掌握主导，把拒绝、失败、冲突都消化为经验',
      'zh-TW': '任何環境都掌握主導，把拒絕、失敗、衝突都消化為經驗',
      vi: 'Nắm quyền chủ động ở mọi bối cảnh. Biến từ chối, thất bại, xung đột thành kinh nghiệm',
      id: 'Ambil kendali di situasi apa pun. Telan penolakan, kegagalan, konflik sebagai pengalaman',
    }),
    physicalDiagnosis: localeMap({
      ko: '익스트림을 즐기고 이미 다양한 강도 높은 경험을 보유',
      en: 'Enjoys extreme activities and already has many high-intensity experiences',
      ja: 'エクストリームを楽しみ、すでに多様な高強度経験を持つ',
      'zh-CN': '享受极限活动，已有多种高强度体验',
      'zh-TW': '享受極限活動，已有多種高強度體驗',
      vi: 'Thích hoạt động mạo hiểm và đã có nhiều trải nghiệm cường độ cao',
      id: 'Menikmati ekstrem dan sudah punya banyak pengalaman intens',
    }),
    careerDiagnosis: localeMap({
      ko: '이미 창업했거나 창업을 삶의 방식으로 생각함',
      en: 'Already entrepreneurial or treats entrepreneurship as a way of life',
      ja: 'すでに起業しているか、起業を生き方として考えている',
      'zh-CN': '已经创业，或把创业当作生活方式',
      'zh-TW': '已經創業，或把創業當作生活方式',
      vi: 'Đã khởi nghiệp hoặc coi khởi nghiệp là cách sống',
      id: 'Sudah wirausaha atau anggap wirausaha sebagai gaya hidup',
    }),
    uncertaintyDiagnosis: localeMap({
      ko: '불확실성이 없는 상황이 오히려 불편. 도전과 변화가 일상',
      en: 'Feels uncomfortable without uncertainty. Challenge and change are daily life',
      ja: '不確実性がない状況が逆に不快。挑戦と変化が日常',
      'zh-CN': '没有不确定反而难受，挑战与变化是日常',
      'zh-TW': '沒有不確定反而難受，挑戰與變化是日常',
      vi: 'Thiếu không chắc chắn lại khó chịu. Thử thách và thay đổi là thường ngày',
      id: 'Tanpa ketidakpastian justru tidak nyaman. Tantangan dan perubahan adalah keseharian',
    }),
    strengths: localeMap({
      ko: '극한 상황에서의 결단력·실행력·회복력. 남들이 안 가는 길을 여는 능력',
      en: 'Decisiveness, execution, and recovery in extreme situations. Opens paths others won\'t take',
      ja: '極限状況での決断力・実行力・回復力。誰も行かない道を開く',
      'zh-CN': '极端情境下的决断力、执行力、恢复力，能走出别人不敢走的路',
      'zh-TW': '極端情境下的決斷力、執行力、恢復力，能走出別人不敢走的路',
      vi: 'Quyết đoán, thực thi, phục hồi trong tình huống cực đoan. Mở đường người khác không đi',
      id: 'Keputusan, eksekusi, recovery di situasi ekstrem. Buka jalan yang orang lain tidak ambil',
    }),
    caution: localeMap({
      ko: '치명적 리스크 노출 가능성. 반드시 최악의 시나리오를 미리 설정하고 그 이상의 리스크는 차단하는 시스템 필요. 주변 사람에게 미치는 영향도 고려 필요',
      en: 'Risk of fatal exposure. Must pre-set worst-case scenarios and block beyond them. Consider impact on people around you',
      ja: '致命的リスク暴露の可能性。最悪シナリオを事前設定し、それ以上は遮断。周囲への影響も考慮',
      'zh-CN': '存在致命风险暴露，必须预设最坏情景并阻断超出部分，也要考虑对周围人的影响',
      'zh-TW': '存在致命風險暴露，必須預設最壞情景並阻斷超出部分，也要考慮對周圍人的影響',
      vi: 'Nguy cơ lộ rủi ro chí mạng. Phải đặt kịch bản xấu nhất trước và chặn vượt mức. Cân nhắc ảnh hưởng tới người xung quanh',
      id: 'Risiko exposure fatal. Wajib set skenario terburuk dan blokir di atasnya. Pertimbangkan dampak ke orang sekitar',
    }),
    investmentStyle: localeMap({
      ko: '최고 수준의 투자 경험자가 많음. 단 포트폴리오의 일부는 반드시 하방 헤지',
      en: 'Often highly experienced investors. Still hedge part of the portfolio for downside',
      ja: '最高レベルの投資経験者が多い。ただしポートフォリオの一部は必ず下方向ヘッジ',
      'zh-CN': '常有顶级投资经验，但组合中仍须保留部分下行对冲',
      'zh-TW': '常有頂級投資經驗，但組合中仍須保留部分下行對沖',
      vi: 'Nhiều người có kinh nghiệm đầu tư cao. Vẫn phải hedge một phần danh mục cho downside',
      id: 'Banyak investor berpengalaman tinggi. Tetap hedge sebagian portofolio untuk downside',
    }),
    entrepreneurshipStyle: localeMap({
      ko: '가장 전형적인 창업가 유형. 실행력은 최강이지만 체계적 팀 구성과 리스크 관리자 필수',
      en: 'Classic founder type. Strongest execution, but needs systematic team and risk manager',
      ja: '最も典型的な起業家型。実行力最強だが、体系的チームとリスク管理者が必須',
      'zh-CN': '最典型的创业者类型，执行力最强，但必须有系统化团队与风险管理者',
      'zh-TW': '最典型的創業者類型，執行力最強，但必須有系統化團隊與風險管理者',
      vi: 'Kiểu founder điển hình nhất. Thực thi mạnh nhất, nhưng cần team có hệ thống và người quản trị rủi ro',
      id: 'Tipe founder paling klasik. Eksekusi terkuat, tapi butuh tim sistematis dan risk manager',
    }),
    certificationPhrase: localeMap({
      ko: '"극한 모험형 달성 🌋 리스크 감수 수준 최상위"',
      en: 'Extreme Adventurer Achieved 🌋 Top-tier risk tolerance',
      ja: '極限冒険型達成 🌋 リスク許容度最上位',
      'zh-CN': '极限冒险型达成 🌋 风险承受力顶级',
      'zh-TW': '極限冒險型達成 🌋 風險承受力頂級',
      vi: 'Đạt Kiểu mạo hiểm cực đoan 🌋 Mức chấp nhận rủi ro cao nhất',
      id: 'Extreme Adventurer tercapai 🌋 Toleransi risiko level atas',
    }),
    oneLiner: localeMap({
      ko: '당신이 방향만 맞게 움직인다면 아무도 따라잡기 어렵습니다. 그래서 방향이 가장 중요합니다',
      en: 'If you move in the right direction, almost no one can catch you. That\'s why direction matters most.',
      ja: '方向さえ合えば誰にも追いつかれない。だから方向が最も重要。',
      'zh-CN': '只要方向对了，几乎没人追得上你，所以方向最重要。',
      'zh-TW': '只要方向對了，幾乎沒人追得上你，所以方向最重要。',
      vi: 'Nếu hướng đi đúng, gần như không ai theo kịp. Vì vậy hướng đi quan trọng nhất.',
      id: 'Kalau arahnya benar, hampir tidak ada yang bisa mengejar. Makanya arah paling penting.',
    }),
    shareLine: localeMap({
      ko: '내 위험 감수 성향: 극한 모험형 🌋 안주가 가장 두렵다는 유형... 불확실성이 생존 조건이래 맞음 ㅋㅋ → 위험 감수 결과 투자·창업 관심층 해봐',
      en: 'My risk tolerance: Extreme Adventurer Type 🌋 Staying put is scariest... uncertainty is a survival condition, so true lol → If you\'re into investing or startups, try this',
      ja: '私のリスク許容度：極限冒険型 🌋 現状維持が最も怖いタイプ…不確実性が生存条件、当たり ㅋㅋ → 投資・起業好きならやってみて',
      'zh-CN': '我的风险承受力：极限冒险型 🌋 最怕安于现状型…不确定是生存条件 太准 哈哈 → 对投资/创业感兴趣试试',
      'zh-TW': '我的風險承受力：極限冒險型 🌋 最怕安於現狀型…不確定是生存條件 太準 哈哈 → 對投資/創業感興趣試試',
      vi: 'Mức chấp nhận rủi ro của tôi: Kiểu mạo hiểm cực đoan 🌋 Sợ nhất là đứng yên… không chắc chắn là điều kiện sống, đúng quá haha → Ai thích đầu tư/khởi nghiệp thử đi',
      id: 'Toleransi risiko-ku: Tipe petualang ekstrem 🌋 Paling takut stagnasi… ketidakpastian itu kondisi hidup, bener wkwk → Suka investasi/wirausaha? Coba deh',
    }),
  },
];
