/** 나의 찐친 조건 분석 — 12문항 4지선다 A=0 B=1 C=2 D=3, 총점 0~36 → 6유형 · 7개 로케일 */

export type Phase3RfLocaleKey = 'ko' | 'en' | 'ja' | 'zh-CN' | 'zh-TW' | 'vi' | 'id';

function ML(t: Record<Phase3RfLocaleKey, string>): Record<Phase3RfLocaleKey, string> {
  return t;
}

export interface Phase3RealFriendConditionAnalysisQuestion {
  id: number;
  question: Record<Phase3RfLocaleKey, string>;
  options: { text: Record<Phase3RfLocaleKey, string>; score: number }[];
}

export interface Phase3RealFriendConditionAnalysisResult {
  type: string;
  emoji: string;
  title: Record<Phase3RfLocaleKey, string>;
  shortDescription: Record<Phase3RfLocaleKey, string>;
  description: Record<Phase3RfLocaleKey, string>;
  scoreRange: Record<Phase3RfLocaleKey, string>;
  keywords: Record<Phase3RfLocaleKey, string>;
  whyStays: Record<Phase3RfLocaleKey, string>;
  whyDrifts: Record<Phase3RfLocaleKey, string>;
  oftenHeard: Record<Phase3RfLocaleKey, string>;
  happyMoment: Record<Phase3RfLocaleKey, string>;
  contactPattern: Record<Phase3RfLocaleKey, string>;
  bestMatch: Record<Phase3RfLocaleKey, string>;
  clashStyle: Record<Phase3RfLocaleKey, string>;
}

export const phase3RealFriendConditionAnalysisQuestions: Phase3RealFriendConditionAnalysisQuestion[] = [
  {
    id: 1,
    question: ML({
      ko: '오래 친하게 지내는 친구들의 공통점을 떠올려보면?',
      en: 'When you think about what your long-term friends have in common?',
      ja: '長く付き合っている友だちの共通点を思い浮かべると？',
      'zh-CN': '想想和你相处很久的朋友们有什么共同点？',
      'zh-TW': '想想和你相處很久的朋友們有什麼共同點？',
      vi: 'Khi nghĩ về điểm chung của những người bạn lâu năm của bạn?',
      id: 'Kalau dipikir, apa persamaan teman-teman yang sudah lama bersahabat denganmu?',
    }),
    options: [
      {
        text: ML({
          ko: '연락이 없어도 만나면 어제 본 것처럼 자연스러운 사람들이다',
          en: 'Even with little contact, meeting feels natural, like we saw each other yesterday',
          ja: '連絡がなくても会えば昨日会ったみたいに自然な人たち',
          'zh-CN': '不怎么联系，一见面也像昨天刚见过一样自然',
          'zh-TW': '不怎麼聯絡，一見面也像昨天剛見過一樣自然',
          vi: 'Ít liên lạc nhưng gặp lại vẫn tự nhiên như hôm qua vừa gặp',
          id: 'Jarang kontak tapi pas ketemu tetap natural kayak baru ketemu kemarin',
        }),
        score: 0,
      },
      {
        text: ML({
          ko: '힘들 때 먼저 연락하거나 알아채는 사람들이다',
          en: 'They reach out first or notice when I am struggling',
          ja: 'つらいときに先に連絡してくれたり気づいてくれる人たち',
          'zh-CN': '我难过时会先联系我或察觉到我状态的人',
          'zh-TW': '我難過時會先聯絡我或察覺到我狀態的人',
          vi: 'Khi mình khó khăn họ chủ động liên lạc hoặc nhận ra trước',
          id: 'Saat sulit mereka yang duluan hubungi atau sadar duluan',
        }),
        score: 1,
      },
      {
        text: ML({
          ko: '같이 있으면 항상 재밌고 에너지가 넘치는 사람들이다',
          en: 'Being together is always fun and full of energy',
          ja: '一緒にいると常に楽しくてエネルギーに満ちている',
          'zh-CN': '在一起总是很开心、充满活力',
          'zh-TW': '在一起總是很開心、充滿活力',
          vi: 'Ở cùng lúc nào cũng vui và tràn năng lượng',
          id: 'Bareng mereka selalu seru dan energik',
        }),
        score: 2,
      },
      {
        text: ML({
          ko: '서로의 가치관이나 목표가 비슷한 사람들이다',
          en: 'We share similar values and goals',
          ja: '価値観や目標がお互いに近い人たち',
          'zh-CN': '彼此价值观或目标相近的人',
          'zh-TW': '彼此價值觀或目標相近的人',
          vi: 'Có giá trị hoặc mục tiêu khá giống nhau',
          id: 'Nilai atau tujuan hidupnya mirip satu sama lain',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 2,
    question: ML({
      ko: '친구가 갑자기 연락을 뜸하게 하면 나는?',
      en: 'If a friend suddenly contacts you less often, you…',
      ja: '友だちからの連絡が急に減ったら、あなたは？',
      'zh-CN': '朋友突然联系变少，你会？',
      'zh-TW': '朋友突然聯絡變少，你會？',
      vi: 'Nếu bạn bè đột nhiên ít liên lạc hơn, bạn…',
      id: 'Kalau teman tiba-tiba jarang menghubungi, kamu…',
    }),
    options: [
      {
        text: ML({
          ko: '별로 신경 안 쓴다. 서로 바쁜 거 이해하고 언젠가 연락 오겠지',
          en: 'Do not worry much—we are both busy; they will reach out eventually',
          ja: 'あまり気にしない。互いに忙しいし、いつか連絡が来る',
          'zh-CN': '不太在意，理解彼此忙，总有一天会联系',
          'zh-TW': '不太在意，理解彼此忙，總有一天會聯絡',
          vi: 'Không bận tâm nhiều—cả hai đều bận, sẽ liên lạc lại thôi',
          id: 'Tidak terlalu mikir—sama-sama sibuk, nanti juga hubungi lagi',
        }),
        score: 0,
      },
      {
        text: ML({
          ko: '걱정이 된다. 무슨 일이 있는 건 아닌지 먼저 연락한다',
          en: 'Worry and reach out first to check if something is wrong',
          ja: '心配になる。何かあったのではと先に連絡する',
          'zh-CN': '会担心，先主动联系看是不是出了什么事',
          'zh-TW': '會擔心，先主動聯絡看是不是出了什麼事',
          vi: 'Lo lắng và chủ động liên lạc trước để hỏi han',
          id: 'Khawatir dan menghubungi duluan untuk pastikan tidak ada masalah',
        }),
        score: 1,
      },
      {
        text: ML({
          ko: '서운하다. 자주 연락하는 게 친밀함의 표시라고 생각한다',
          en: 'Feel hurt—I see frequent contact as a sign of closeness',
          ja: '寂しい。頻繁な連絡が親しさの証だと思う',
          'zh-CN': '有点失落，觉得常联系才是亲密',
          'zh-TW': '有點失落，覺得常聯絡才是親密',
          vi: 'Hơi buồn—mình nghĩ liên lạc thường xuyên mới là thân',
          id: 'Sedih—menurutku sering kontak itu tanda dekat',
        }),
        score: 2,
      },
      {
        text: ML({
          ko: '상황을 파악하려 한다. 내가 뭘 잘못한 건지 먼저 생각해본다',
          en: 'Try to read the situation and wonder if I did something wrong',
          ja: '状況を把握しようとする。自分が何か悪いことをしたか考える',
          'zh-CN': '想弄清状况，先反思是不是自己哪里做错了',
          'zh-TW': '想弄清狀況，先反思是不是自己哪裡做錯了',
          vi: 'Cố hiểu tình huống và tự hỏi mình có làm gì sai không',
          id: 'Mencoba pahami situasi dan cek dulu apakah aku yang salah',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 3,
    question: ML({
      ko: '친구에게 고민을 털어놓을 때 나는?',
      en: 'When you open up to a friend about worries, you…',
      ja: '友だちに悩みを打ち明けるとき、あなたは？',
      'zh-CN': '向朋友倾诉烦恼时，你更在意？',
      'zh-TW': '向朋友傾訴煩惱時，你更在意？',
      vi: 'Khi tâm sự với bạn về chuyện buồn, bạn…',
      id: 'Saat curhat ke teman, yang kamu utamakan…',
    }),
    options: [
      {
        text: ML({
          ko: '해결책보다 그냥 들어주는 것만으로도 충분하다',
          en: 'Having them listen is enough—I do not need fixes first',
          ja: '解決策より、とにかく聞いてもらえるだけで十分',
          'zh-CN': '比起解决办法，有人愿意听就够了',
          'zh-TW': '比起解決辦法，有人願意聽就夠了',
          vi: 'Chỉ cần được lắng nghe là đủ, chưa cần giải pháp ngay',
          id: 'Cukup didengarkan dulu, belum perlu solusi',
        }),
        score: 0,
      },
      {
        text: ML({
          ko: '감정적으로 공감해주고 내 편이 되어주는 게 중요하다',
          en: 'Emotional validation and being on my side matter most',
          ja: '感情的に共感してくれて、味方でいてくれることが大事',
          'zh-CN': '情绪上的共鸣和“站我这边”最重要',
          'zh-TW': '情緒上的共鳴和「站我這邊」最重要',
          vi: 'Quan trọng là đồng cảm và đứng về phía mình',
          id: 'Yang penting empati dan memihak ke aku',
        }),
        score: 1,
      },
      {
        text: ML({
          ko: '같이 웃으면서 털어버릴 수 있는 분위기가 되면 최고다',
          en: 'Best if we can laugh it off together',
          ja: '一緒に笑い飛ばせる雰囲気なら最高',
          'zh-CN': '最好能一起笑着把烦恼甩掉',
          'zh-TW': '最好能一起笑著把煩惱甩掉',
          vi: 'Tuyệt nhất là không khí cười xóa stress cùng nhau',
          id: 'Paling enak kalau bisa ketawa-ketawa bareng sampai plong',
        }),
        score: 2,
      },
      {
        text: ML({
          ko: '객관적인 시각으로 조언해주는 친구가 진짜 도움이 된다',
          en: 'A friend who gives objective advice truly helps',
          ja: '客観的な視点でアドバイスしてくれる友だちが本当の助けになる',
          'zh-CN': '能客观给建议的朋友才真正有帮助',
          'zh-TW': '能客觀給建議的朋友才真正有幫助',
          vi: 'Bạn cho lời khách quan mới thật sự giúp ích',
          id: 'Teman yang kasih saran objektif itu yang paling membantu',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 4,
    question: ML({
      ko: '나에게 찐친이란 어떤 사람인가요?',
      en: 'For you, a “real best friend” is someone who…',
      ja: 'あなたにとって「本当の親友」とはどんな人？',
      'zh-CN': '对你来说，“真朋友”是哪种人？',
      'zh-TW': '對你來說，「真朋友」是哪種人？',
      vi: 'Với bạn, “bạn thân đích thực” là người…',
      id: 'Bagimu, sahabat sejati itu orang yang…',
    }),
    options: [
      {
        text: ML({
          ko: '아무것도 안 해도 같이 있으면 편한 사람',
          en: 'You feel at ease together even when you do nothing',
          ja: '何もしなくても一緒にいるだけで落ち着く人',
          'zh-CN': '什么都不做待在一起也舒服的人',
          'zh-TW': '什麼都不做待在一起也舒服的人',
          vi: 'Chỉ cần ở cùng đã thấy thoải mái, không cần làm gì',
          id: 'Diam bareng aja sudah nyaman',
        }),
        score: 0,
      },
      {
        text: ML({
          ko: '기쁠 때도 힘들 때도 항상 내 곁에 있는 사람',
          en: 'Stays by my side in good times and bad',
          ja: '嬉しいときも辛いときも常にそばにいてくれる人',
          'zh-CN': '开心或难过都一直站在我身边的人',
          'zh-TW': '開心或難過都一直站在我身邊的人',
          vi: 'Vui hay buồn đều ở bên mình',
          id: 'Senang atau susah tetap di sampingku',
        }),
        score: 1,
      },
      {
        text: ML({
          ko: '만나면 항상 에너지가 생기고 기분이 좋아지는 사람',
          en: 'Meeting them always lifts my mood and energy',
          ja: '会うと必ず元気が出て気分が良くなる人',
          'zh-CN': '一见面就充满能量、心情变好',
          'zh-TW': '一見面就充滿能量、心情變好',
          vi: 'Gặp là thấy tràn năng lượng và vui hơn',
          id: 'Ketemu saja langsung dapat energi dan hati plong',
        }),
        score: 2,
      },
      {
        text: ML({
          ko: '서로를 자극하고 더 좋은 방향으로 이끌어주는 사람',
          en: 'We push each other toward growth in a good direction',
          ja: '互いを刺激し合い、より良い方向へ導き合う人',
          'zh-CN': '互相推动、一起往更好的方向走的人',
          'zh-TW': '互相推動、一起往更好的方向走的人',
          vi: 'Thúc đẩy nhau phát triển theo hướng tốt hơn',
          id: 'Saling dorong ke arah yang lebih baik',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 5,
    question: ML({
      ko: '친구와 오해나 갈등이 생겼을 때 나는?',
      en: 'When there is misunderstanding or conflict with a friend, you…',
      ja: '友だちと誤解や衝突が起きたとき、あなたは？',
      'zh-CN': '和朋友产生误会或冲突时，你会？',
      'zh-TW': '和朋友產生誤會或衝突時，你會？',
      vi: 'Khi hiểu lầm hoặc mâu thuẫn với bạn, bạn…',
      id: 'Saat salah paham atau konflik dengan teman, kamu…',
    }),
    options: [
      {
        text: ML({
          ko: '시간이 지나면 자연스럽게 해결되길 기다린다',
          en: 'Wait for it to resolve naturally over time',
          ja: '時間が経てば自然に解決すると待つ',
          'zh-CN': '等时间过去，自然和好',
          'zh-TW': '等時間過去，自然和好',
          vi: 'Chờ thời gian, tự khắc êm xuôi',
          id: 'Tunggu waktu, nanti juga reda sendiri',
        }),
        score: 0,
      },
      {
        text: ML({
          ko: '감정이 정리되면 먼저 연락해서 이야기를 나눈다',
          en: 'Once emotions settle, I reach out first to talk',
          ja: '感情が落ち着いたら先に連絡して話し合う',
          'zh-CN': '情绪平复后会主动联系把话说开',
          'zh-TW': '情緒平復後會主動聯絡把話說開',
          vi: 'Khi bình tĩnh lại thì chủ động liên lạc để nói chuyện',
          id: 'Setelah tenang, hubungi duluan untuk bicara',
        }),
        score: 1,
      },
      {
        text: ML({
          ko: '분위기가 무거워지는 게 싫어서 웃으면서 넘기려 한다',
          en: 'Try to joke past it—I dislike heavy vibes',
          ja: '重い空気が苦手で、笑ってごまかそうとする',
          'zh-CN': '不喜欢气氛太僵，想笑着带过',
          'zh-TW': '不喜歡氣氛太僵，想笑著帶過',
          vi: 'Ghét không khí nặng nên cố cười cho qua',
          id: 'Tidak suka suasana berat, coba lewat lewat canda',
        }),
        score: 2,
      },
      {
        text: ML({
          ko: '정확하게 뭐가 문제였는지 짚고 넘어가야 개운하다',
          en: 'Need to pinpoint what went wrong to feel clear again',
          ja: '何が問題だったかはっきりしてからでないとスッキリしない',
          'zh-CN': '必须把问题说清楚才觉得痛快',
          'zh-TW': '必須把問題說清楚才覺得痛快',
          vi: 'Phải nói rõ vấn đề mới thấy nhẹ người',
          id: 'Harus jelas masalahnya baru plong',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 6,
    question: ML({
      ko: '오랫동안 우정이 유지되는 이유를 꼽는다면?',
      en: 'If you name why a friendship lasts long, it is because…',
      ja: '長く友情が続く理由を挙げるとしたら？',
      'zh-CN': '若要说友谊为何能长久，那是因为…',
      'zh-TW': '若要說友誼為何能長久，那是因為…',
      vi: 'Nếu nói vì sao tình bạn bền lâu, đó là vì…',
      id: 'Kalau disebut persahabatan bisa awet karena…',
    }),
    options: [
      {
        text: ML({
          ko: '억지로 맞추지 않아도 자연스럽게 편했기 때문이다',
          en: 'It felt easy naturally, without forcing ourselves to fit',
          ja: '無理に合わせなくても自然に居心地が良かったから',
          'zh-CN': '不用勉强配合也自然舒服',
          'zh-TW': '不用勉強配合也自然舒服',
          vi: 'Không cần gượng gạo mà vẫn thoải mái',
          id: 'Tanpa dipaksain tetap nyaman',
        }),
        score: 0,
      },
      {
        text: ML({
          ko: '중요한 순간마다 서로 곁에 있어줬기 때문이다',
          en: 'We showed up for each other in important moments',
          ja: '大切な瞬間に互いにそばにいてくれたから',
          'zh-CN': '在重要时刻彼此都在身边',
          'zh-TW': '在重要時刻彼此都在身邊',
          vi: 'Ở bên nhau trong những khoảnh khắc quan trọng',
          id: 'Ada untuk satu sama lain di momen penting',
        }),
        score: 1,
      },
      {
        text: ML({
          ko: '함께한 추억이 많고 항상 재밌었기 때문이다',
          en: 'We share many fun memories together',
          ja: '一緒の思い出が多く、いつも楽しかったから',
          'zh-CN': '一起有很多快乐回忆',
          'zh-TW': '一起有很多快樂回憶',
          vi: 'Nhiều kỷ niệm vui và lúc nào cũng vui',
          id: 'Banyak kenangan seru bareng',
        }),
        score: 2,
      },
      {
        text: ML({
          ko: '서로 비슷한 방향을 보며 자극을 주고받았기 때문이다',
          en: 'We looked in a similar direction and motivated each other',
          ja: '似た方向を見て互いに刺激し合えたから',
          'zh-CN': '方向相近、互相激励',
          'zh-TW': '方向相近、互相激勵',
          vi: 'Cùng hướng và tiếp thêm động lực cho nhau',
          id: 'Arah mirip dan saling dorong maju',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 7,
    question: ML({
      ko: '친구를 오랫동안 못 만나다가 다시 만났을 때?',
      en: 'After not seeing a friend for a long time, you meet again—you feel…',
      ja: '長く会えなかった友だちに久しぶりに会ったとき？',
      'zh-CN': '和朋友很久没见又重逢时，你…',
      'zh-TW': '和朋友很久沒見又重逢時，你…',
      vi: 'Sau thời gian dài không gặp, gặp lại bạn—bạn…',
      id: 'Setelah lama tidak ketemu lalu bertemu lagi—kamu…',
    }),
    options: [
      {
        text: ML({
          ko: '바로 어색함이 사라진다. 원래부터 이랬던 것처럼 자연스럽다',
          en: 'Awkwardness vanishes; it feels like it always did',
          ja: 'すぐにぎこちなさが消える。元からこうだったみたいに自然',
          'zh-CN': '尴尬感马上消失，像从来都这样自然',
          'zh-TW': '尷尬感馬上消失，像從來都這樣自然',
          vi: 'Hết ngượng ngay; cứ như vốn dĩ đã thân thế',
          id: 'Canggung langsung hilang, natural seperti biasa',
        }),
        score: 0,
      },
      {
        text: ML({
          ko: '못 만난 사이 있었던 일들을 빠르게 공유하고 싶어진다',
          en: 'Want to quickly catch up on everything we missed',
          ja: '会えなかった間のことを早く共有したくなる',
          'zh-CN': '想赶紧补上没见面时发生的事',
          'zh-TW': '想趕緊補上沒見面時發生的事',
          vi: 'Muốn kể hết chuyện lúc không gặp',
          id: 'Pengin cepat cerita semua yang terlewat',
        }),
        score: 1,
      },
      {
        text: ML({
          ko: '어서 신나는 걸 같이 하고 싶다. 만남 자체가 설렌다',
          en: 'Want to do something fun together—the reunion itself excites me',
          ja: '早く一緒にワクワクすることしたい。再会自体がドキドキする',
          'zh-CN': '想赶快一起做开心的事，见面本身就兴奋',
          'zh-TW': '想趕快一起做開心的事，見面本身就興奮',
          vi: 'Muốn làm điều gì đó vui ngay—chỉ gặp lại đã hồi hộp',
          id: 'Pengin segera seru-seruan—ketemu saja sudah deg-degan',
        }),
        score: 2,
      },
      {
        text: ML({
          ko: '서로 그동안 어떻게 성장했는지 이야기하는 게 좋다',
          en: 'Prefer talking about how we have grown since then',
          ja: 'この間どう成長したか話し合うのが良い',
          'zh-CN': '喜欢聊彼此这段时间的成长',
          'zh-TW': '喜歡聊彼此這段時間的成長',
          vi: 'Thích nói về sự trưởng thành của nhau',
          id: 'Enak ngobrol perkembangan masing-masing',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 8,
    question: ML({
      ko: '내가 힘들 때 찐친에게 바라는 것은?',
      en: 'When you are struggling, what do you want from a best friend?',
      ja: '自分がつらいとき、親友に求めるものは？',
      'zh-CN': '你难过时，希望真朋友给你什么？',
      'zh-TW': '你難過時，希望真朋友給你什麼？',
      vi: 'Khi bạn đang khó khăn, bạn mong điều gì ở bạn thân?',
      id: 'Saat sulit, kamu harap apa dari sahabat?',
    }),
    options: [
      {
        text: ML({
          ko: '아무 말 없이 옆에 있어주는 것. 그것만으로 충분하다',
          en: 'Just sit with me in silence—that is enough',
          ja: '何も言わずにそばにいてくれること。それだけで十分',
          'zh-CN': '默默陪着我就够',
          'zh-TW': '默默陪著我就夠',
          vi: 'Chỉ cần lặng lẽ ở bên là đủ',
          id: 'Cukup diam di sampingku',
        }),
        score: 0,
      },
      {
        text: ML({
          ko: '내 이야기를 들어주고 내 편이 되어주는 것',
          en: 'Listen to me and be on my side',
          ja: '話を聞いてくれて、味方でいてくれること',
          'zh-CN': '听我说并站在我这边',
          'zh-TW': '聽我說並站在我這邊',
          vi: 'Lắng nghe và đứng về phía mình',
          id: 'Dengarkan dan pihak ke aku',
        }),
        score: 1,
      },
      {
        text: ML({
          ko: '기분 전환할 수 있게 밖에 데리고 나가주는 것',
          en: 'Take me out to clear my head',
          ja: '気分転換できるように外に連れ出してくれること',
          'zh-CN': '带我出门换换心情',
          'zh-TW': '帶我出門換換心情',
          vi: 'Kéo ra ngoài cho đổi không khí',
          id: 'Ajak keluar biar gak mumet',
        }),
        score: 2,
      },
      {
        text: ML({
          ko: '솔직하게 상황을 봐주고 현실적인 도움을 주는 것',
          en: 'Honestly assess the situation and give practical help',
          ja: '状況を正直に見て、現実的な助けをくれること',
          'zh-CN': '客观看状况并给实际帮助',
          'zh-TW': '客觀看狀況並給實際幫助',
          vi: 'Nhìn thật tình huống và giúp thực tế',
          id: 'Jujur lihat situasi dan bantu yang konkret',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 9,
    question: ML({
      ko: '친구 관계에서 가장 중요하게 생각하는 것은?',
      en: 'In friendship, what matters most to you?',
      ja: '友だち関係で一番大事にしていることは？',
      'zh-CN': '在友谊里你最看重什么？',
      'zh-TW': '在友誼裡你最看重什麼？',
      vi: 'Trong tình bạn, điều quan trọng nhất với bạn là gì?',
      id: 'Dalam persahabatan, yang paling kamu hargai?',
    }),
    options: [
      {
        text: ML({
          ko: '편안함. 꾸미지 않아도 되는 관계',
          en: 'Comfort—you can be yourself without performing',
          ja: '居心地の良さ。飾らなくていい関係',
          'zh-CN': '舒服，不用装的关系',
          'zh-TW': '舒服，不用裝的關係',
          vi: 'Thoải mái—không cần diễn',
          id: 'Nyaman—tanpa perlu pura-pura',
        }),
        score: 0,
      },
      {
        text: ML({
          ko: '신뢰. 어떤 상황에서도 믿을 수 있는 관계',
          en: 'Trust—I can rely on them in any situation',
          ja: '信頼。どんな状況でも頼れる関係',
          'zh-CN': '信任，任何情况都靠得住',
          'zh-TW': '信任，任何情況都靠得住',
          vi: 'Tin cậy—luôn có thể dựa vào',
          id: 'Percaya—bisa diandelin dalam situasi apa pun',
        }),
        score: 1,
      },
      {
        text: ML({
          ko: '즐거움. 함께 있으면 항상 재밌는 관계',
          en: 'Fun—it is always a good time together',
          ja: '楽しさ。一緒にいると常に楽しい関係',
          'zh-CN': '快乐，在一起总是好玩',
          'zh-TW': '快樂，在一起總是好玩',
          vi: 'Vui—ở cùng lúc nào cũng thú vị',
          id: 'Seru—bareng selalu asyik',
        }),
        score: 2,
      },
      {
        text: ML({
          ko: '성장. 서로를 더 좋은 방향으로 이끄는 관계',
          en: 'Growth—we pull each other toward better versions of ourselves',
          ja: '成長。互いをより良い方向へ導き合う関係',
          'zh-CN': '成长，互相往更好的方向带',
          'zh-TW': '成長，互相往更好的方向帶',
          vi: 'Trưởng thành—kéo nhau đi lên',
          id: 'Berkembang—saling arahkan ke arah lebih baik',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 10,
    question: ML({
      ko: '찐친과 나누는 대화 스타일은?',
      en: 'Your conversation style with a best friend is…',
      ja: '親友との会話スタイルは？',
      'zh-CN': '和真朋友的聊天风格是？',
      'zh-TW': '和真朋友的聊天風格是？',
      vi: 'Phong cách trò chuyện với bạn thân của bạn là…',
      id: 'Gaya ngobrol dengan sahabat itu…',
    }),
    options: [
      {
        text: ML({
          ko: '깊게 얘기하지 않아도 작은 것들을 공유하는 대화',
          en: 'Sharing small things without needing deep talk every time',
          ja: '深く話さなくても小さなことを共有する会話',
          'zh-CN': '不用深聊也分享日常小事',
          'zh-TW': '不用深聊也分享日常小事',
          vi: 'Chia sẻ chuyện nhỏ, không cần lúc nào cũng sâu',
          id: 'Bagi hal kecil, tidak harus selalu dalam',
        }),
        score: 0,
      },
      {
        text: ML({
          ko: '속 깊은 이야기를 솔직하게 나누는 대화',
          en: 'Honest, deep heart-to-heart talks',
          ja: '本音で深い話をする会話',
          'zh-CN': '坦诚聊心里话',
          'zh-TW': '坦誠聊心裡話',
          vi: 'Nói thật lòng, sâu sắc',
          id: 'Curhat jujur dan dalam',
        }),
        score: 1,
      },
      {
        text: ML({
          ko: '끊임없이 웃고 떠들고 공감하는 활기찬 대화',
          en: 'Nonstop laughing, chatter, and hype',
          ja: '笑いとおしゃべりと共感が止まらない明るい会話',
          'zh-CN': '一直笑、一直聊、互相捧场',
          'zh-TW': '一直笑、一直聊、互相捧場',
          vi: 'Cười nói không ngớt, đồng điệu năng lượng',
          id: 'Ketawa ngobrol terus, energi tinggi',
        }),
        score: 2,
      },
      {
        text: ML({
          ko: '서로의 생각과 관점을 자극하는 지적인 대화',
          en: 'Ideas and viewpoints that challenge each other',
          ja: '互いの考えや視点を刺激し合う知的な会話',
          'zh-CN': '互相激发想法与观点的脑力交流',
          'zh-TW': '互相激發想法與觀點的腦力交流',
          vi: 'Trao đổi ý tưởng, thách thức góc nhìn nhau',
          id: 'Diskusi ide dan sudut pandang yang menggugah',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 11,
    question: ML({
      ko: '친구 관계에서 가장 상처받는 순간은?',
      en: 'In friendship, what hurts you the most?',
      ja: '友だち関係で一番傷つく瞬間は？',
      'zh-CN': '友谊里最让你受伤的时刻是？',
      'zh-TW': '友誼裡最讓你受傷的時刻是？',
      vi: 'Trong tình bạn, khoảnh khắc nào làm bạn tổn thương nhất?',
      id: 'Dalam persahabatan, momen apa yang paling menyakitkan?',
    }),
    options: [
      {
        text: ML({
          ko: '강요받거나 맞춰야 한다는 압박을 느낄 때',
          en: 'Feeling pressured to conform or be forced',
          ja: '無理に合わせられたり、強要を感じるとき',
          'zh-CN': '感到被强迫或必须迎合时',
          'zh-TW': '感到被強迫或必須迎合時',
          vi: 'Cảm giác bị ép hoặc phải chiều theo',
          id: 'Merasa dipaksa atau harus mengikuti',
        }),
        score: 0,
      },
      {
        text: ML({
          ko: '내가 힘들 때 곁에 없거나 외면당했을 때',
          en: 'When they are absent or turn away while I am struggling',
          ja: '自分がつらいときにそばにいない、見捨てられたように感じるとき',
          'zh-CN': '我难过时不在身边或冷漠对待',
          'zh-TW': '我難過時不在身邊或冷漠對待',
          vi: 'Khi mình khó khăn họ không ở bên hoặc quay lưng',
          id: 'Saat aku susah mereka tidak ada atau cuek',
        }),
        score: 1,
      },
      {
        text: ML({
          ko: '같이 있는데 분위기가 어둡거나 에너지가 없을 때',
          en: 'Together but the vibe is heavy or drained',
          ja: '一緒にいるのに空気が重い、エネルギーがないとき',
          'zh-CN': '在一起却气氛沉闷、没能量',
          'zh-TW': '在一起卻氣氛沉悶、沒能量',
          vi: 'Ở cùng nhưng không khí u ám, thiếu năng lượng',
          id: 'Bareng tapi suasana berat atau lesu',
        }),
        score: 2,
      },
      {
        text: ML({
          ko: '나를 발전시키지 못하는 관계에서 시간을 낭비한다는 느낌이 들 때',
          en: 'Feeling I am wasting time in a relationship that does not help me grow',
          ja: '成長につながらない関係で時間を無駄にしている気がするとき',
          'zh-CN': '觉得在这段关系里浪费时间、无法成长',
          'zh-TW': '覺得在這段關係裡浪費時間、無法成長',
          vi: 'Cảm giác lãng phí thời gian với quan hệ không giúp mình tiến bộ',
          id: 'Merasa buang waktu di hubungan yang tidak bikin berkembang',
        }),
        score: 3,
      },
    ],
  },
  {
    id: 12,
    question: ML({
      ko: '지금 나의 찐친을 떠올렸을 때 가장 먼저 드는 감각은?',
      en: 'When you picture your best friend right now, the first feeling is…',
      ja: '今、親友を思い浮かべたとき、最初に湧く感覚は？',
      'zh-CN': '现在想起你的真朋友，最先出现的感觉是？',
      'zh-TW': '現在想起你的真朋友，最先出現的感覺是？',
      vi: 'Khi nghĩ đến bạn thân lúc này, cảm giác đầu tiên là…',
      id: 'Kalau bayangkan sahabatmu sekarang, perasaan pertama…',
    }),
    options: [
      {
        text: ML({
          ko: '편안함. 그 사람 생각만 해도 마음이 느슨해진다',
          en: 'Ease—even thinking of them relaxes you',
          ja: '安心。その人を思うだけで心がほぐれる',
          'zh-CN': '放松，想到TA就心里一松',
          'zh-TW': '放鬆，想到TA就心裡一鬆',
          vi: 'Thoải mái—chỉ nghĩ đến thôi đã thấy nhẹ người',
          id: 'Legan—cuma ingat saja sudah adem',
        }),
        score: 0,
      },
      {
        text: ML({
          ko: '안도감. 그 사람이 있어서 든든하다는 느낌이 든다',
          en: 'Relief—I feel secure because they exist',
          ja: '安堵。その人がいるから心強い',
          'zh-CN': '踏实，因为有TA在很安心',
          'zh-TW': '踏實，因為有TA在很安心',
          vi: 'An tâm—có họ là thấy vững',
          id: 'Tenang—ada mereka rasanya aman',
        }),
        score: 1,
      },
      {
        text: ML({
          ko: '설렘. 다음에 만나면 뭐 하지 생각이 먼저 난다',
          en: 'Excitement—I already think about what we will do next time',
          ja: 'ワクワク。次に会ったら何しようか考える',
          'zh-CN': '兴奋，先想下次见面要干嘛',
          'zh-TW': '興奮，先想下次見面要幹嘛',
          vi: 'Hồi hộp—nghĩ ngay chuyện lần sau gặp sẽ làm gì',
          id: 'Deg-degan—langsung mikir mau ngapain ketemu lagi',
        }),
        score: 2,
      },
      {
        text: ML({
          ko: '자극. 그 사람을 만나면 나도 더 잘 하고 싶어진다',
          en: 'Spark—seeing them makes me want to level up',
          ja: '刺激。会うと自分ももっと頑張りたくなる',
          'zh-CN': '被激励，见了面也想变得更好',
          'zh-TW': '被激勵，見了面也想變得更好',
          vi: 'Động lực—gặp họ là muốn cố gắng hơn',
          id: 'Termotivasi—ketemu mereka bikin pengen lebih baik',
        }),
        score: 3,
      },
    ],
  },
];

export const phase3RealFriendConditionAnalysisResults: Phase3RealFriendConditionAnalysisResult[] = [
  {
    type: 'Type1',
    emoji: '🌿',
    title: ML({
      ko: '아무것도 안 해도 편한, 무언의 동반자형 찐친',
      en: 'Quiet companion — comfort without trying',
      ja: '何もしなくても安心、無言の相棒型の親友',
      'zh-CN': '什么都不做也自在的无声陪伴型挚友',
      'zh-TW': '什麼都不做也自在的無聲陪伴型摯友',
      vi: 'Bạn thân kiểu đồng hành thầm lặng—thoải mái dù không làm gì',
      id: 'Sahabat pendamping diam—nyaman tanpa usaha',
    }),
    shortDescription: ML({
      ko: '나의 찐친 조건: 꾸미지 않아도 되는 편안함',
      en: 'Your best-friend standard: comfort without performing',
      ja: '親友条件：飾らなくていい安心感',
      'zh-CN': '你的真朋友标准：不用装也能安心',
      'zh-TW': '你的真朋友標準：不用裝也能安心',
      vi: 'Tiêu chí bạn thân: thoải mái mà không cần diễn',
      id: 'Kriteria sahabat: nyaman tanpa harus tampil sempurna',
    }),
    description: ML({
      ko:
        '당신의 찐친 기준은 하나입니다. 함께 있을 때 아무것도 안 해도 편한가.\n\n연락이 뜸해도 만나면 어제 본 것처럼 자연스럽고, 말이 없어도 어색하지 않고, 억지로 맞추지 않아도 되는 관계가 당신이 가장 오래 유지하는 우정입니다. 화려하지 않지만 가장 깊고 오래가는 찐친 조건을 가진 유형입니다.',
      en:
        'Your best-friend bar is simple: when you are together, do you feel at ease even if you do nothing?\n\nEven with little contact, reunions feel like yesterday; silence is not awkward; you do not have to force the fit. That is the friendship you keep longest. It may look plain, but it runs deep and lasts—this type carries the quietest, most enduring criteria.',
      ja:
        'あなたの親友基準は一つ。一緒にいて何もしなくても落ち着けるか。\n\n連絡が少なくても会えば昨日会ったみたいに自然で、言葉がなくても気まずくなく、無理に合わせなくていい関係が、あなたが一番長く続ける友情です。派手ではないが、いちばん深く長く続く親友条件を持つタイプです。',
      'zh-CN':
        '你对真朋友的标准其实很简单：在一起时，即使什么都不做也舒服吗？\n\n联系不多，见面也像昨天刚见过；不说话也不尴尬；不用勉强迎合——这种关系是你最能维持长久的友谊。看起来不张扬，却最深、最持久，属于最“耐看”的真朋友类型。',
      'zh-TW':
        '你對真朋友的標準其實很簡單：在一起時，即使什麼都不做也舒服嗎？\n\n聯絡不多，見面也像昨天剛見過；不說話也不尷尬；不用勉強迎合——這種關係是你最能維持長久的友誼。看起來不張揚，卻最深、最持久，屬於最「耐看」的真朋友類型。',
      vi:
        'Tiêu chí bạn thân của bạn chỉ cần một điều: khi ở cùng nhau, dù không làm gì vẫn thấy thoải mái?\n\nÍt liên lạc nhưng gặp lại vẫn tự nhiên như hôm qua; im lặng không ngượng; không cần gượng gạo—đó là tình bạn bạn duy trì lâu nhất. Có vẻ giản dị nhưng sâu và bền—kiểu này mang tiêu chí bền vững nhất.',
      id:
        'Kriteria sahabatmu sederhana: saat bareng, apakah tetap nyaman meski tidak melakukan apa pun?\n\nJarang kontak tapi ketemu tetap natural; diam pun tidak canggung; tidak perlu dipaksain—itu persahabatan yang paling awet bagimu. Terlihat biasa tapi paling dalam dan tahan lama.',
    }),
    scoreRange: ML({
      ko: '0~5점',
      en: '0–5 pts',
      ja: '0〜5点',
      'zh-CN': '0–5 分',
      'zh-TW': '0–5 分',
      vi: '0–5 điểm',
      id: '0–5 poin',
    }),
    keywords: ML({
      ko: '편안함·자연스러움·무언의 연결·여백·꾸밈없음',
      en: 'Comfort · ease · unspoken bond · space · no pretense',
      ja: '安心 · 自然さ · 言葉なしのつながり · 余白 · 飾らなさ',
      'zh-CN': '舒服·自然·无声连接·留白·不装',
      'zh-TW': '舒服·自然·無聲連接·留白·不裝',
      vi: 'Thoải mái · tự nhiên · kết nối thầm · khoảng trống · không giả tạo',
      id: 'Nyaman · natural · ikatan tanpa kata · ruang · tanpa pura-pura',
    }),
    whyStays: ML({
      ko: '서로에게 아무것도 요구하지 않아도 관계가 흔들리지 않기 때문',
      en: 'Because the bond stays steady even when neither side demands much',
      ja: '互いに何も求めなくても関係が揺らがないから',
      'zh-CN': '彼此不要求什么，关系也不动摇',
      'zh-TW': '彼此不要求什麼，關係也不動搖',
      vi: 'Vì mối quan hệ không lung lay dù không ai đòi hỏi nhiều',
      id: 'Karena hubungan tetap kokoh meski tidak menuntut satu sama lain',
    }),
    whyDrifts: ML({
      ko: '관계에 과도한 기대나 압박을 주는 사람과는 자연스럽게 거리가 생김',
      en: 'You naturally drift from people who pressure you with heavy expectations',
      ja: '関係に過度な期待や圧をかける人とは自然と距離ができる',
      'zh-CN': '对关系期待过高或施压的人，你会自然疏远',
      'zh-TW': '對關係期待過高或施壓的人，你會自然疏遠',
      vi: 'Tự nhiên xa người gây áp lực kỳ vọng quá lớn',
      id: 'Otomatis menjauh dari orang yang memberi tekanan atau ekspektasi berlebihan',
    }),
    oftenHeard: ML({
      ko: '"너랑 있으면 왜 이렇게 편하냐"',
      en: '“Why do I feel so comfortable with you?”',
      ja: '「なんであなたといるとこんなに楽なんだろ」',
      'zh-CN': '“跟你在一起怎么这么舒服”',
      'zh-TW': '「跟你在一起怎麼這麼舒服」',
      vi: '“Sao ở cạnh bạn thoải mái thế?”',
      id: '“Kok bareng kamu enak banget ya?”',
    }),
    happyMoment: ML({
      ko: '아무 계획 없이 그냥 같이 있는 것. 카페에서 각자 폰 보다가 집에 가는 것도 좋음',
      en: 'Being together with zero plans—even scrolling phones at a cafe then heading home feels good',
      ja: '計画なしでただ一緒にいること。カフェでそれぞれスマホを見て帰るのもいい',
      'zh-CN': '毫无计划地待在一起——咖啡馆各玩手机再回家也很好',
      'zh-TW': '毫無計畫地待在一起——咖啡廳各玩手機再回家也很好',
      vi: 'Ở cùng nhau không kế hoạch—cà phê mỗi người lướt điện thoại rồi về cũng vui',
      id: 'Bareng tanpa rencana—di kafe main HP masing-masing lalu pulang juga enak',
    }),
    contactPattern: ML({
      ko: '자주는 아니지만 연락하면 바로 온도가 원래대로 돌아옴',
      en: 'Not daily, but one message brings the vibe right back',
      ja: '頻繁ではないが、連絡すればすぐいつもの温度に戻る',
      'zh-CN': '不常联系，但一聊就回到熟悉的温度',
      'zh-TW': '不常聯絡，但一聊就回到熟悉的溫度',
      vi: 'Không liên lạc liên tục nhưng cứ nhắn là lại ấm ngay',
      id: 'Jarang chat tapi begitu ngobrol langsung hangat lagi',
    }),
    bestMatch: ML({
      ko: '비슷하게 편안함을 중시하는 사람. 또는 늘 곁에 있어주려는 신뢰형',
      en: 'Someone who also values ease—or a steady “I have your back” type',
      ja: '同じく安心を大事にする人。または常にそばにいてくれる信頼型',
      'zh-CN': '同样重视舒服的人，或总在身边的信赖型',
      'zh-TW': '同樣重視舒服的人，或總在身邊的信賴型',
      vi: 'Người cũng coi trọng sự thoải mái—hoặc kiểu luôn ở bên',
      id: 'Yang juga menghargai kenyamanan—atau tipe setia menemani',
    }),
    clashStyle: ML({
      ko: '매일 연락을 기대하거나 반응을 요구하는 사람',
      en: 'People who expect daily contact or constant reactions',
      ja: '毎日連絡や反応を求める人',
      'zh-CN': '期待每天联系或随时回应的人',
      'zh-TW': '期待每天聯絡或隨時回應的人',
      vi: 'Người đòi liên lạc mỗi ngày hoặc phản hồi liên tục',
      id: 'Yang mengharapkan chat tiap hari atau respons terus-menerus',
    }),
  },
  {
    type: 'Type2',
    emoji: '🤝',
    title: ML({
      ko: '힘들 때 가장 먼저 생각나는, 신뢰 안전망형 찐친',
      en: 'Trust safety net — the one you think of first when it is hard',
      ja: 'つらいとき真っ先に思い浮かぶ、信頼のセーフティネット型',
      'zh-CN': '难过时最先想到的信赖安全网型挚友',
      'zh-TW': '難過時最先想到的信賴安全網型摯友',
      vi: 'Lưới an toàn tin cậy—nhớ đến đầu tiên khi khó khăn',
      id: 'Jaring pengaman kepercayaan—yang pertama teringat saat susah',
    }),
    shortDescription: ML({
      ko: '나의 찐친 조건: 어떤 상황에서도 내 편인 사람',
      en: 'Your standard: someone on your side, no matter what',
      ja: '親友条件：どんな状況でも味方でいてくれる人',
      'zh-CN': '你的标准：无论如何都站你这边的人',
      'zh-TW': '你的標準：無論如何都站你這邊的人',
      vi: 'Tiêu chí: luôn đứng về phía bạn trong mọi tình huống',
      id: 'Kriteria: orang yang memihakmu dalam situasi apa pun',
    }),
    description: ML({
      ko:
        '당신의 찐친 조건은 신뢰입니다. 힘들 때 생각나는 사람이 찐친이고, 그 자리에 있는 사람이 찐친입니다.\n\n기쁜 날보다 힘든 날 곁에 있어줬던 사람과 우정이 깊어지는 유형입니다. 감정을 공유하고 서로의 편이 되어주는 경험이 쌓일수록 관계가 깊어집니다. 진심 어린 신뢰가 없으면 아무리 자주 만나도 찐친이라는 느낌이 들지 않습니다.',
      en:
        'Your criterion is trust. The person you think of when it is hard—and who shows up—is your real best friend.\n\nThis type bonds deepest with people who were there on hard days more than happy ones. The more you share feelings and stand up for each other, the deeper it goes. Without genuine trust, frequent hangouts still will not feel like “best friends.”',
      ja:
        'あなたの親友条件は信頼です。つらいときに思い浮かぶ人、そこにいてくれる人が親友です。\n\n嬉しい日よりつらい日にそばにいてくれた人と絆が深まるタイプです。感情を分かち合い、味方でいる経験が積み重なるほど深くなります。本当の信頼がなければ、会う回数が多くても親友の感覚は湧きません。',
      'zh-CN':
        '你的标准是信任。难过时会想到的人、真的在场的人，才是真朋友。\n\n你更容易与在艰难时刻陪伴你的人加深友谊。越多分享情绪、越互相撑腰，关系越深。没有真心信任，再常见面也不像“真朋友”。',
      'zh-TW':
        '你的標準是信任。難過時會想到的人、真的在場的人，才是真朋友。\n\n你更容易與在艱難時刻陪伴你的人加深友誼。越多分享情緒、越互相撐腰，關係越深。沒有真心信任，再常見面也不像「真朋友」。',
      vi:
        'Tiêu chí của bạn là tin cậy. Người bạn nghĩ đến khi khó khăn—và thực sự ở đó—mới là bạn thân.\n\nKiểu này gắn sâu với người đã ở bên trong ngày khó hơn ngày vui. Càng chia sẻ cảm xúc và đứng về phía nhau, càng sâu. Không có tin cậy thật, gặp thường xuyên vẫn không thấy “bạn thân.”',
      id:
        'Kriteriamu adalah kepercayaan. Orang yang kamu ingat saat susah—dan yang benar-benar ada—itu sahabat sejati.\n\nTipe ini terikat kuat dengan yang hadir di hari sulit lebih dari hari senang. Semakin berbagi perasaan dan saling memihak, semakin dalam. Tanpa kepercayaan tulus, sering ketemu pun tidak terasa “sahabat.”',
    }),
    scoreRange: ML({
      ko: '6~11점',
      en: '6–11 pts',
      ja: '6〜11点',
      'zh-CN': '6–11 分',
      'zh-TW': '6–11 分',
      vi: '6–11 điểm',
      id: '6–11 poin',
    }),
    keywords: ML({
      ko: '신뢰·공감·내 편·안전감·감정 연결',
      en: 'Trust · empathy · loyalty · safety · emotional bond',
      ja: '信頼 · 共感 · 味方 · 安心感 · 感情のつながり',
      'zh-CN': '信任·共情·站队·安全感·情绪连接',
      'zh-TW': '信任·共情·站隊·安全感·情緒連結',
      vi: 'Tin cậy · đồng cảm · đồng minh · an toàn · kết nối cảm xúc',
      id: 'Kepercayaan · empati · memihak · aman · ikatan emosi',
    }),
    whyStays: ML({
      ko: '중요한 순간마다 서로 곁에 있었던 공동의 기억이 깊은 유대감을 만듦',
      en: 'Shared memories of showing up in key moments build a deep bond',
      ja: '大切な瞬間に互いにそばにいた共同の記憶が深い絆をつくる',
      'zh-CN': '在重要时刻彼此在场的共同记忆造就深联结',
      'zh-TW': '在重要時刻彼此在場的共同記憶造就深聯結',
      vi: 'Ký ức cùng hiện diện trong khoảnh khắc quan trọng tạo gắn kết sâu',
      id: 'Ingatan bersama hadir di momen penting membangun ikatan dalam',
    }),
    whyDrifts: ML({
      ko: '힘든 순간에 외면당하거나 믿음이 깨지는 경험이 생기면 회복이 어려움',
      en: 'Being ignored in hard times or broken trust is hard to repair',
      ja: 'つらいときに見捨てられたり信頼が壊れると立ち直りにくい',
      'zh-CN': '难过时被冷落或信任破裂，很难修复',
      'zh-TW': '難過時被冷落或信任破裂，很難修復',
      vi: 'Bị lạnh nhạt lúc khó hoặc mất tin cậy thì khó hàn gắn',
      id: 'Ditinggal saat susah atau kepercayaan rusak sulit dipulihkan',
    }),
    oftenHeard: ML({
      ko: '"너는 나한테 너무 좋은 친구야"',
      en: '“You are such a good friend to me.”',
      ja: '「あなたは私にとってすごくいい友だち」',
      'zh-CN': '“你真是对我特别好的朋友”',
      'zh-TW': '「你真是對我特別好的朋友」',
      vi: '“Bạn là người bạn tuyệt vời với mình.”',
      id: '“Kamu teman yang luar biasa buat aku.”',
    }),
    happyMoment: ML({
      ko: '친구가 힘들 때 내가 곁에 있어줬고, 그게 친구에게 도움이 됐다는 걸 알 때',
      en: 'Knowing you were there when they struggled—and it truly helped',
      ja: '友だちがつらいときにそばにいて、それが助けになったとわかるとき',
      'zh-CN': '朋友难过时你在身边，而且知道那真的帮到了TA',
      'zh-TW': '朋友難過時你在身邊，而且知道那真的幫到了TA',
      vi: 'Biết mình đã ở bên khi họ khó khăn—và điều đó thật sự giúp ích',
      id: 'Tahu kamu ada saat mereka susah—dan itu benar-benar membantu',
    }),
    contactPattern: ML({
      ko: '평소보다 힘들 때 더 자주 연락. 안부보다 속 이야기를 먼저 꺼냄',
      en: 'More contact when life is rough—heart talk before small talk',
      ja: '普段よりつらいときに連絡が増える。世間話より本音を先に',
      'zh-CN': '比平常更难时联系更频，先聊心里话再寒暄',
      'zh-TW': '比平常更難時聯絡更頻，先聊心裡話再寒暄',
      vi: 'Khó khăn thì liên lạc nhiều hơn—nói chuyện trong trước hỏi han',
      id: 'Saat sulit lebih sering hubungi—curhat dulu baru basa-basi',
    }),
    bestMatch: ML({
      ko: '감정적 공감이 깊은 사람. 또는 편안함을 주는 무언의 동반자형',
      en: 'Deep emotional empathy—or the quiet companion who gives ease',
      ja: '感情の共感が深い人。または安心をくれる無言の相棒型',
      'zh-CN': '情绪共鸣深的人，或给你自在感的无声陪伴型',
      'zh-TW': '情緒共鳴深的人，或給你自在感的無聲陪伴型',
      vi: 'Người đồng cảm sâu—hoặc kiểu đồng hành thầm lặng cho bạn thoải mái',
      id: 'Yang empati emosinya dalam—atau pendamping tenang yang bikin nyaman',
    }),
    clashStyle: ML({
      ko: '감정보다 논리를 먼저 꺼내거나 공감 없이 바로 해결책을 제시하는 사람',
      en: 'People who lead with logic or instant fixes without empathy',
      ja: '感情より論理を先に出したり、共感なしですぐ解決策を出す人',
      'zh-CN': '先讲理、不给共情就直接给方案的人',
      'zh-TW': '先講理、不給共情就直接給方案的人',
      vi: 'Người ưu tiên lý trí hoặc đưa giải pháp ngay không đồng cảm',
      id: 'Yang utamakan logika atau langsung solusi tanpa empati',
    }),
  },
  {
    type: 'Type3',
    emoji: '🎉',
    title: ML({
      ko: '만나면 항상 에너지 폭발하는, 활기 에너지 공유형 찐친',
      en: 'Burst of energy — fun-first best friends',
      ja: '会うと常にエネルギー全開、活気シェア型の親友',
      'zh-CN': '见面就能量满格的活力共享型挚友',
      'zh-TW': '見面就能量滿格的活力共享型摯友',
      vi: 'Tràn năng lượng—bạn thân kiểu vui là chính',
      id: 'Energi meledak—sahabat yang utamakan seru',
    }),
    shortDescription: ML({
      ko: '나의 찐친 조건: 같이 있으면 항상 재밌는 사람',
      en: 'Your standard: time together is always fun',
      ja: '親友条件：一緒にいると常に楽しい人',
      'zh-CN': '你的标准：在一起总是好玩的人',
      'zh-TW': '你的標準：在一起總是好玩的人',
      vi: 'Tiêu chí: ở cùng lúc nào cũng vui',
      id: 'Kriteria: bareng selalu seru',
    }),
    description: ML({
      ko:
        '당신의 찐친 조건은 에너지입니다. 만났을 때 기분이 좋아지고 웃음이 나오는 사람이 찐친입니다.\n\n함께 있으면 자연스럽게 웃음이 나오고 에너지가 충전되는 사람과 우정이 깊어지는 유형입니다. 공유하는 추억과 함께한 경험이 많을수록 관계가 깊어집니다. 분위기가 어둡거나 에너지가 없는 관계는 아무리 진지해도 지속하기 어렵습니다.',
      en:
        'Your bar is energy. A real best friend is someone who lifts your mood and makes you laugh when you meet.\n\nThis type grows close with people who recharge you and spark laughter. The more shared fun and memories, the stronger the bond. A heavy, low-energy vibe is hard to sustain for you—even if the friendship is “serious.”',
      ja:
        'あなたの親友条件はエネルギーです。会うと気分が上がり、笑いが出る人が親友です。\n\n一緒にいると自然に笑えて充電される人と絆が深まるタイプです。楽しい思い出と経験が多いほど関係は強くなります。重くてエネルギーのない雰囲気は、どんなに真剣でも続きにくいです。',
      'zh-CN':
        '你的标准是能量。真朋友是见面就让你心情好、想笑的人。\n\n你更容易与让你充电、一起笑的人加深友谊。越多共同欢乐与回忆，关系越牢。气氛沉重、没活力的关系，对你而言很难长久——哪怕很“认真”。',
      'zh-TW':
        '你的標準是能量。真朋友是見面就讓你心情好、想笑的人。\n\n你更容易與讓你充電、一起笑的人加深友誼。越多共同歡樂與回憶，關係越牢。氣氛沉重、沒活力的關係，對你而言很難長久——哪怕很「認真」。',
      vi:
        'Tiêu chí của bạn là năng lượng. Bạn thân là người khiến bạn vui và cười khi gặp.\n\nKiểu này gắn sâu với người tiếp thêm năng lượng và cười cùng nhau. Càng nhiều kỷ niệm vui, càng chặt. Không khí nặng nề, thiếu năng lượng khó duy trì—dù tình bạn có “nghiêm túc” đến đâu.',
      id:
        'Kriteriamu adalah energi. Sahabat sejati bikin mood naik dan ketawa saat ketemu.\n\nTipe ini dekat dengan yang mengisi energi dan bikin tertawa. Semakin banyak kenangan seru, semakin kuat. Suasana berat dan lesu sulit bertahan bagimu—meski persahabatannya “serius.”',
    }),
    scoreRange: ML({
      ko: '12~19점',
      en: '12–19 pts',
      ja: '12〜19点',
      'zh-CN': '12–19 分',
      'zh-TW': '12–19 分',
      vi: '12–19 điểm',
      id: '12–19 poin',
    }),
    keywords: ML({
      ko: '즐거움·에너지·추억·웃음·활기',
      en: 'Joy · energy · memories · laughter · spark',
      ja: '楽しさ · エネルギー · 思い出 · 笑い · 活気',
      'zh-CN': '快乐·能量·回忆·笑声·活力',
      'zh-TW': '快樂·能量·回憶·笑聲·活力',
      vi: 'Vui · năng lượng · kỷ niệm · cười · sức sống',
      id: 'Gembira · energi · kenangan · tawa · semangat',
    }),
    whyStays: ML({
      ko: '함께했던 재밌는 기억이 많을수록 관계가 단단해짐',
      en: 'More fun memories together make the friendship solid',
      ja: '一緒に楽しんだ思い出が多いほど関係が強くなる',
      'zh-CN': '一起的快乐回忆越多，关系越牢',
      'zh-TW': '一起的快樂回憶越多，關係越牢',
      vi: 'Càng nhiều kỷ niệm vui cùng nhau, càng bền',
      id: 'Semakin banyak kenangan seru bareng, semakin kuat',
    }),
    whyDrifts: ML({
      ko: '만남의 빈도가 줄거나 함께 할 활동이 없어지면 자연스럽게 멀어짐',
      en: 'Meet less or run out of things to do together—you drift apart',
      ja: '会う回数が減ったり、一緒にできることがなくなると自然に離れる',
      'zh-CN': '见面变少或没有一起做的事，就会自然疏远',
      'zh-TW': '見面變少或沒有一起做的事，就會自然疏遠',
      vi: 'Gặp ít hơn hoặc hết việc làm chung—tự nhiên xa nhau',
      id: 'Jarang ketemu atau tidak ada aktivitas bareng—lama-lama menjauh',
    }),
    oftenHeard: ML({
      ko: '"너랑 있으면 시간 가는 줄 몰라"',
      en: '“Time flies when I am with you.”',
      ja: '「あなたといると時間が経つのがわからない」',
      'zh-CN': '“跟你在一起时间不知不觉就过了”',
      'zh-TW': '「跟你在一起時間不知不覺就過了」',
      vi: '“Ở cạnh bạn không biết trôi nhanh thế nào.”',
      id: '“Bareng kamu waktu cepat banget.”',
    }),
    happyMoment: ML({
      ko: '계획하지 않은 즉흥 여행이나 나들이에서 웃음이 터지는 순간',
      en: 'Laughing hard on a spontaneous trip or day out',
      ja: '計画なしの即興旅行やお出かけで笑いが爆発する瞬間',
      'zh-CN': '没计划的即兴出游里笑到停不下来的瞬间',
      'zh-TW': '沒計畫的即興出遊裡笑到停不下來的瞬間',
      vi: 'Cười nức nở trong chuyến đi phút chót không kế hoạch',
      id: 'Ketawa lepas dalam trip dadakan atau jalan-jalan spontan',
    }),
    contactPattern: ML({
      ko: '재밌는 것 발견하면 바로 공유. "이거 보고 너 생각났어"가 일상',
      en: 'Share fun finds instantly—“saw this and thought of you” is everyday life',
      ja: '面白いものを見つけたらすぐ共有。「これ見てあなた思い出した」が日常',
      'zh-CN': '发现好玩立刻分享，“看到这个就想到你”是日常',
      'zh-TW': '發現好玩立刻分享，「看到這個就想到你」是日常',
      vi: 'Thấy gì vui là gửi ngay—“thấy cái này là nhớ bạn” là chuyện thường',
      id: 'Temukan hal seru langsung share—“lihat ini inget kamu” jadi biasa',
    }),
    bestMatch: ML({
      ko: '비슷하게 에너지가 넘치는 사람. 또는 편안하게 받아주는 동반자형',
      en: 'Someone equally high-energy—or an easygoing companion who matches your vibe',
      ja: '同じくエネルギッシュな人。または受け止めてくれる相棒型',
      'zh-CN': '同样高能量的人，或轻松接住的陪伴型',
      'zh-TW': '同樣高能量的人，或輕鬆接住的陪伴型',
      vi: 'Cùng năng lượng cao—hoặc người đồng hành dễ chịu',
      id: 'Sama-sama energik—atau pendamping yang mudah menyatu',
    }),
    clashStyle: ML({
      ko: '감정이 무겁거나 자주 진지한 이야기만 꺼내는 사람',
      en: 'People who are always heavy or only want serious talk',
      ja: 'いつも重い、または深刻な話ばかりする人',
      'zh-CN': '气氛总是很沉重或只聊严肃话题的人',
      'zh-TW': '氣氛總是很沉重或只聊嚴肅話題的人',
      vi: 'Người luôn nặng nề hoặc chỉ muốn nói chuyện nghiêm túc',
      id: 'Yang selalu berat atau cuma mau obrolan serius',
    }),
  },
  {
    type: 'Type4',
    emoji: '🚀',
    title: ML({
      ko: '서로 자극하며 함께 성장하는, 동반 성장형 찐친',
      en: 'Growth partners — you lift each other up',
      ja: '互いを刺激し合い成長する、成長パートナー型の親友',
      'zh-CN': '互相推动共同成长的成长伙伴型挚友',
      'zh-TW': '互相推動共同成長的成長夥伴型摯友',
      vi: 'Cùng thúc đẩy phát triển—bạn thân kiểu đồng hành tăng trưởng',
      id: 'Saling dorong tumbuh—sahabat mitra pertumbuhan',
    }),
    shortDescription: ML({
      ko: '나의 찐친 조건: 서로를 더 나은 방향으로 이끄는 사람',
      en: 'Your standard: someone who pulls you toward a better direction',
      ja: '親友条件：互いをより良い方向へ導いてくれる人',
      'zh-CN': '你的标准：把你带向更好方向的人',
      'zh-TW': '你的標準：把你帶向更好方向的人',
      vi: 'Tiêu chí: người kéo bạn đi hướng tốt hơn',
      id: 'Kriteria: orang yang mengarahkan ke versi dirimu yang lebih baik',
    }),
    description: ML({
      ko:
        '당신의 찐친 조건은 성장입니다. 그 사람을 만나고 나면 더 잘 하고 싶어지는 사람이 찐친입니다.\n\n서로의 목표와 가치관이 비슷하고 자극을 주고받으며 성장하는 관계에서 우정이 깊어지는 유형입니다. 단순히 재밌는 것을 넘어 서로에게 영향을 주는 관계를 원합니다. 시간을 낭비하는 느낌이 드는 관계는 아무리 오래됐어도 점점 멀어집니다.',
      en:
        'Your criterion is growth. A best friend is someone who makes you want to do better after you meet.\n\nThis type deepens friendship when values align and you motivate each other. You want influence beyond “just fun.” If a bond feels like wasted time—even after years—you slowly drift away.',
      ja:
        'あなたの親友条件は成長です。会ったあとにより頑張りたくなる人が親友です。\n\n目標や価値観が近く、刺激し合って成長する関係で絆が深まるタイプです。単なる楽しさを超えて影響し合う関係を求めます。時間の無駄に感じる関係は、どれだけ長くても少しずつ離れます。',
      'zh-CN':
        '你的标准是成长。真朋友是见完之后让你想变得更好的人。\n\n价值观相近、互相激励成长时，友谊更深。你要的不只是好玩，而是彼此影响。若一段关系让你感觉在浪费时间——再久也会慢慢疏远。',
      'zh-TW':
        '你的標準是成長。真朋友是見完之後讓你想變得更好的人。\n\n價值觀相近、互相激勵成長時，友誼更深。你要的不只是好玩，而是彼此影響。若一段關係讓你感覺在浪費時間——再久也會慢慢疏遠。',
      vi:
        'Tiêu chí của bạn là phát triển. Bạn thân là người khiến bạn muốn cố gắng hơn sau mỗi lần gặp.\n\nKiểu này sâu sắc khi giá trị tương đồng và tiếp thêm động lực. Bạn muốn ảnh hưởng lẫn nhau, không chỉ vui. Nếu cảm giác lãng phí thời gian—dù đã lâu—bạn dần xa.',
      id:
        'Kriteriamu adalah pertumbuhan. Sahabat sejati bikinmu ingin lebih baik setelah bertemu.\n\nTipe ini dalam ketika nilai selaras dan saling dorong maju. Kamu ingar pengaruh, bukan cuma seru. Jika terasa buang waktu—meski sudah lama—lama-lama menjauh.',
    }),
    scoreRange: ML({
      ko: '20~27점',
      en: '20–27 pts',
      ja: '20〜27点',
      'zh-CN': '20–27 分',
      'zh-TW': '20–27 分',
      vi: '20–27 điểm',
      id: '20–27 poin',
    }),
    keywords: ML({
      ko: '성장·자극·가치관 공유·방향성·상호 발전',
      en: 'Growth · spark · shared values · direction · mutual lift',
      ja: '成長 · 刺激 · 価値観共有 · 方向性 · 相互発展',
      'zh-CN': '成长·激发·价值观·方向·共同进步',
      'zh-TW': '成長·激發·價值觀·方向·共同進步',
      vi: 'Tăng trưởng · động lực · giá trị · hướng đi · nâng nhau',
      id: 'Pertumbuhan · dorongan · nilai · arah · saling angkat',
    }),
    whyStays: ML({
      ko: '서로가 서로의 성장에 긍정적인 영향을 주고 있다는 것을 느끼기 때문',
      en: 'You feel you are positively shaping each other’s growth',
      ja: '互いの成長に良い影響を与え合っていると感じるから',
      'zh-CN': '因为能感觉到彼此在正向影响对方的成长',
      'zh-TW': '因為能感覺到彼此在正向影響對方的成長',
      vi: 'Vì cảm nhận được đang tác động tích cực đến sự trưởng thành của nhau',
      id: 'Karena merasa saling berpengaruh positif pada pertumbuhan',
    }),
    whyDrifts: ML({
      ko: '서로의 방향이 달라지거나 한쪽이 성장을 멈춘 느낌이 들 때',
      en: 'When your paths diverge or one side feels stuck',
      ja: '方向がずれたり、片方が成長を止めたように感じるとき',
      'zh-CN': '方向不同，或觉得一方停住不成长时',
      'zh-TW': '方向不同，或覺得一方停住不成長時',
      vi: 'Khi hướng đi khác nhau hoặc một bên như ngừng tiến bộ',
      id: 'Saat arah beda atau salah satu terasa stagnan',
    }),
    oftenHeard: ML({
      ko: '"너 보면 나도 열심히 해야겠다는 생각이 들어"',
      en: '“Seeing you makes me want to try harder.”',
      ja: '「あなたを見てると私も頑張ろうって思う」',
      'zh-CN': '“看到你我也想更努力”',
      'zh-TW': '「看到你我也想更努力」',
      vi: '“Nhìn bạn là mình muốn cố gắng hơn.”',
      id: '“Lihat kamu bikin aku pengen lebih giat.”',
    }),
    happyMoment: ML({
      ko: '오랜만에 만났는데 서로 달라져 있고 그 변화가 좋은 방향일 때',
      en: 'Reuniting after a while and seeing good change in each other',
      ja: '久しぶりに会って、お互い良い方向に変わっていると感じるとき',
      'zh-CN': '久别重逢，彼此都在往好的方向变化',
      'zh-TW': '久別重逢，彼此都在往好的方向變化',
      vi: 'Gặp lại sau lâu và thấy cả hai đều đổi theo hướng tốt',
      id: 'Bertemu lagi setelah lama dan lihat perubahan baik di satu sama lain',
    }),
    contactPattern: ML({
      ko: '일상적인 연락보다 의미 있는 내용을 공유하는 연락이 많음',
      en: 'Less small talk—more messages that actually mean something',
      ja: '日常の連絡より、意味のある内容を共有する連絡が多い',
      'zh-CN': '比起日常寒暄，更常分享有意义的内容',
      'zh-TW': '比起日常寒暄，更常分享有意義的內容',
      vi: 'Ít hỏi han xã giao—thường chia sẻ điều có ý nghĩa',
      id: 'Lebih sering bagi hal bermakna daripada basa-basi saja',
    }),
    bestMatch: ML({
      ko: '비슷한 방향과 목표를 가진 사람. 또는 신뢰를 기반으로 솔직한 피드백을 주는 사람',
      en: 'Similar goals—or someone who gives honest feedback built on trust',
      ja: '似た方向と目標の人。または信頼ベースで正直なフィードバックをくれる人',
      'zh-CN': '方向目标相近的人，或基于信任给真诚反馈的人',
      'zh-TW': '方向目標相近的人，或基於信任給真誠回饋的人',
      vi: 'Cùng hướng mục tiêu—hoặc người cho phản hồi thật trên nền tin cậy',
      id: 'Arah & tujuan mirip—atau yang kasih feedback jujur dari kepercayaan',
    }),
    clashStyle: ML({
      ko: '현실에 안주하거나 발전 없이 같은 자리에 머무는 것을 편안하게 여기는 사람',
      en: 'People comfy staying put with no growth or ambition',
      ja: '現状に安住し、成長なく同じ場所にいることを楽だと思う人',
      'zh-CN': '安于现状、停在原地还觉得舒服的人',
      'zh-TW': '安於現狀、停在原地還覺得舒服的人',
      vi: 'Người an phận, không tiến bộ mà vẫn thấy ổn',
      id: 'Yang nyaman diam tanpa perkembangan atau ambisi',
    }),
  },
  {
    type: 'Type5',
    emoji: '🌙',
    title: ML({
      ko: '말하지 않아도 다 아는, 텔레파시 감성형 찐친',
      en: 'Telepathic feelers — you just know',
      ja: '言わなくてもわかる、テレパシー感性型の親友',
      'zh-CN': '不说也懂的默契感性型挚友',
      'zh-TW': '不說也懂的默契感性型摯友',
      vi: 'Cảm giác thần giao—không nói cũng hiểu',
      id: 'Telepati perasaan—tanpa kata sudah paham',
    }),
    shortDescription: ML({
      ko: '나의 찐친 조건: 설명하지 않아도 통하는 사람',
      en: 'Your standard: someone who gets you without a long explanation',
      ja: '親友条件：説明しなくても通じ合う人',
      'zh-CN': '你的标准：不用多说也能懂的人',
      'zh-TW': '你的標準：不用多說也能懂的人',
      vi: 'Tiêu chí: hiểu nhau không cần giải thích dài',
      id: 'Kriteria: paham tanpa perlu penjelasan panjang',
    }),
    description: ML({
      ko:
        '당신의 찐친 조건은 감응입니다. 말하지 않아도 내 상태를 알아채는 사람, 설명하지 않아도 이해하는 사람이 찐친입니다.\n\n논리보다 감각으로 연결된 관계에서 우정이 깊어지는 유형입니다. 상대방이 내 감정을 자연스럽게 읽어주고 나도 상대방의 상태를 직감으로 아는 관계에서 가장 깊은 우정을 느낍니다. 설명이 많이 필요한 관계는 피곤하게 느껴질 수 있습니다.',
      en:
        'Your criterion is attunement. A best friend reads your state without a speech—and understands without a manual.\n\nThis type bonds through feeling more than logic. When they sense your emotions naturally and you intuit theirs, friendship feels deepest. Relationships that need constant explaining can feel exhausting.',
      ja:
        'あなたの親友条件は共感です。言わなくても状態を察してくれる人、説明しなくてもわかってくれる人が親友です。\n\n論理より感覚でつながる関係で絆が深まるタイプです。相手が自然に感情を読み取り、自分も直感で相手の状態を知る関係でいちばん深い友情を感じます。説明が多すぎる関係は疲れます。',
      'zh-CN':
        '你的标准是感应。真朋友是不用你说也能察觉你状态、不用解释也能懂你的人。\n\n你更容易在“感觉先于逻辑”的关系里加深友谊。彼此自然读懂情绪、凭直觉知道对方状态时，友谊最深。总要长篇解释的关系会让你疲惫。',
      'zh-TW':
        '你的標準是感應。真朋友是不用說也能察覺你狀態、不用解釋也能懂你的人。\n\n你更容易在「感覺先於邏輯」的關係裡加深友誼。彼此自然讀懂情緒、憑直覺知道對方狀態時，友誼最深。總要長篇解釋的關係會讓你疲憊。',
      vi:
        'Tiêu chí của bạn là đồng điệu. Bạn thân là người nhận ra trạng thái của bạn mà không cần nói nhiều—và hiểu mà không cần hướng dẫn.\n\nKiểu này gắn bằng cảm hơn lý. Khi họ cảm được cảm xúc bạn và bạn trực giác được họ, tình bạn sâu nhất. Quan hệ phải giải thích mãi có thể khiến bạn mệt.',
      id:
        'Kriteriamu adalah selaras. Sahabat sejati mengenali keadaanmu tanpa pidato—dan mengerti tanpa manual.\n\nTipe ini terikat lewat perasaan lebih dari logika. Saat mereka memahami emosimu secara alami dan kamu mengintuisi mereka, persahabatan terasa paling dalam. Hubungan yang perlu penjelasan terus-menerus bisa melelahkan.',
    }),
    scoreRange: ML({
      ko: '28~33점',
      en: '28–33 pts',
      ja: '28〜33点',
      'zh-CN': '28–33 分',
      'zh-TW': '28–33 分',
      vi: '28–33 điểm',
      id: '28–33 poin',
    }),
    keywords: ML({
      ko: '텔레파시·감응·직감·언어 너머의 연결·감수성',
      en: 'Telepathy · attunement · intuition · beyond words · sensitivity',
      ja: 'テレパシー · 共鳴 · 直感 · 言葉を超えたつながり · 感受性',
      'zh-CN': '默契·感应·直觉·超越语言·敏感',
      'zh-TW': '默契·感應·直覺·超越語言·敏感',
      vi: 'Thần giao · đồng điệu · trực giác · vượt lời nói · nhạy cảm',
      id: 'Telepati · selaras · intuisi · melampaui kata · sensitif',
    }),
    whyStays: ML({
      ko: '서로의 상태를 말하지 않아도 느끼는 감각적 연결이 있기 때문',
      en: 'Because you sense each other’s state without needing every detail said',
      ja: '言葉にしなくても互いの状態を感じ取れる感覚的つながりがあるから',
      'zh-CN': '因为彼此能感应状态，不必事事说透',
      'zh-TW': '因為彼此能感應狀態，不必事事說透',
      vi: 'Vì cảm được trạng thái nhau mà không cần nói hết',
      id: 'Karena bisa merasakan keadaan satu sama lain tanpa harus dijelaskan semua',
    }),
    whyDrifts: ML({
      ko: '오해가 생겼을 때 풀지 않고 각자 느낌으로만 해석하다 어긋나는 경우',
      en: 'Misunderstandings stay unresolved—only feelings, no clarity—and you drift',
      ja: '誤解が生じても解かず、それぞれの感覚だけで解釈してずれていく場合',
      'zh-CN': '误会不说开，只靠各自感觉解读，越偏越远',
      'zh-TW': '誤會不說開，只靠各自感覺解讀，越偏越遠',
      vi: 'Hiểu lầm không được giải—chỉ đoán bằng cảm xúc—rồi xa nhau',
      id: 'Salah paham tidak dibicarakan—cuma tafsir perasaan—lalu menjauh',
    }),
    oftenHeard: ML({
      ko: '"나 힘들다고 말 안 했는데 어떻게 알았어?"',
      en: '“I never said I was struggling—how did you know?”',
      ja: '「つらいって言ってないのに、どうしてわかったの？」',
      'zh-CN': '“我没说我难过，你怎么知道的？”',
      'zh-TW': '「我沒說我難過，你怎麼知道的？」',
      vi: '“Mình chưa nói là đang khó—sao bạn biết?”',
      id: '“Aku belum bilang sedih—kok kamu tahu?”',
    }),
    happyMoment: ML({
      ko: '같은 걸 보고 동시에 같은 생각을 했다는 걸 알게 되는 순간',
      en: 'Realizing you thought the same thing at the same moment',
      ja: '同じものを見て同時に同じことを思ったとわかる瞬間',
      'zh-CN': '同时看同一样东西、同时想到同一件事的瞬间',
      'zh-TW': '同時看同一樣東西、同時想到同一件事的瞬間',
      vi: 'Khoảnh khắc nhận ra cùng nghĩ một điều cùng lúc',
      id: 'Sadar kalian berpikir hal yang sama bersamaan',
    }),
    contactPattern: ML({
      ko: '일상적인 연락보다 뜬금없이 생각나서 보내는 연락이 많음',
      en: 'Less routine texting—more “randomly thought of you” pings',
      ja: '日常の連絡より、ふと思い出して送る連絡が多い',
      'zh-CN': '比起日常打卡，更多是突然想起你就发消息',
      'zh-TW': '比起日常打卡，更多是突然想起你就發訊息',
      vi: 'Ít nhắn theo routine—thường là nhớ bất chợt rồi nhắn',
      id: 'Jarang chat rutin—lebih sering kangen tiba-tiba lalu chat',
    }),
    bestMatch: ML({
      ko: '감수성이 비슷하고 감정을 직감으로 읽는 사람. 또는 편안함을 주는 무언의 동반자형',
      en: 'Similar sensitivity—or the quiet companion who gives calm',
      ja: '感受性が近く感情を直感で読む人。または安心をくれる無言の相棒型',
      'zh-CN': '敏感度相近、能直觉读情绪的人，或给你安心的无声陪伴型',
      'zh-TW': '敏感度相近、能直覺讀情緒的人，或給你安心的無聲陪伴型',
      vi: 'Nhạy cảm tương tự—hoặi người đồng hành yên lặng cho bạn thư thái',
      id: 'Sensitivitas mirip—atau pendamping tenang yang memberi ketenangan',
    }),
    clashStyle: ML({
      ko: '모든 것을 명확하게 말로 표현해야 이해하는 논리형 사람',
      en: 'Hyper-logical people who need everything spelled out in words',
      ja: 'すべてを言葉で明確に説明しないと理解できない論理型の人',
      'zh-CN': '凡事都要讲清楚、靠语言才能理解的逻辑型',
      'zh-TW': '凡事都要講清楚、靠語言才能理解的邏輯型',
      vi: 'Người kiểu logic—phải nói rõ từng chữ mới hiểu',
      id: 'Tipe logis—harus dijelaskan kata per kata baru paham',
    }),
  },
  {
    type: 'Type6',
    emoji: '⏳',
    title: ML({
      ko: '오래될수록 더 깊어지는, 시간 누적 숙성형 찐친',
      en: 'Time-aged bond — deeper with every chapter',
      ja: '長くなるほど深まる、時間熟成型の親友',
      'zh-CN': '越久越深的时光沉淀型挚友',
      'zh-TW': '越久越深的時光沉澱型摯友',
      vi: 'Càng lâu càng sâu—tình bạn “ủ” theo thời gian',
      id: 'Semakin lama semakin dalam—persahabatan yang matang bersama waktu',
    }),
    shortDescription: ML({
      ko: '나의 찐친 조건: 함께한 시간이 쌓인 사람',
      en: 'Your standard: history you built together',
      ja: '親友条件：一緒に積み重ねた時間のある人',
      'zh-CN': '你的标准：一起堆出来的时间',
      'zh-TW': '你的標準：一起堆出來的時間',
      vi: 'Tiêu chí: thời gian đã cùng nhau tích lũy',
      id: 'Kriteria: waktu yang sudah kalian bangun bersama',
    }),
    description: ML({
      ko:
        '당신의 찐친 조건은 시간입니다. 함께 웃고 울고 다투고 화해한 그 모든 시간이 쌓여야 비로소 찐친이 됩니다.\n\n함께 겪어온 경험의 두께가 우정의 기준인 유형입니다. 하루아침에 깊어지는 관계보다 오랜 시간 다양한 상황을 함께 통과한 관계에서 가장 깊은 우정을 느낍니다. 새로운 만남보다 오래된 관계를 더 소중히 여기는 경향이 있습니다.',
      en:
        'Your criterion is time. Laughing, crying, fighting, making up—all of it stacks until someone becomes a real best friend.\n\nThis type measures friendship by the thickness of shared life. Deeper than “clicking fast,” you feel closest after weathering many seasons together. You tend to treasure long history over shiny new connections.',
      ja:
        'あなたの親友条件は時間です。笑い、泣き、喧嘩し、仲直りした時間が積み重なって初めて親友になります。\n\n一緒に経験した厚みが友情の基準です。一夜で深まる関係より、長い時間いろいろな場面を乗り越えた関係でいちばん深い友情を感じます。新しい出会いより、育った関係を大切にする傾向があります。',
      'zh-CN':
        '你的标准是时间。一起笑过、哭过、吵过、和好过——这些堆起来，才成为真朋友。\n\n你用共同经历的厚度衡量友谊。比起一夜投缘，你更在穿越许多季节后感到最深。比起新鲜相遇，你往往更珍惜老关系。',
      'zh-TW':
        '你的標準是時間。一起笑過、哭過、吵過、和好過——這些堆起來，才成為真朋友。\n\n你用共同經歷的厚度衡量友誼。比起一夜投緣，你更在穿越許多季節後感到最深。比起新鮮相遇，你往往更珍惜老關係。',
      vi:
        'Tiêu chí của bạn là thời gian. Cười, khóc, cãi, làm lành—tất cả chồng lên nhau mới thành bạn thân.\n\nKiểu này đo tình bạn bằng độ dày trải nghiệm. Bạn cảm thấy gần nhất sau nhiều mùa cùng vượt qua, hơn là “hợp ngay lập tức.” Bạn thường trân trọng lịch sử dài hơn kết nối mới lạ.',
      id:
        'Kriteriamu adalah waktu. Tertawa, menangis, bertengkar, berbaikan—semuanya menumpuk sampai seseorang jadi sahabat sejati.\n\nTipe ini mengukur persahabatan dengan ketebalan hidup bersama. Lebih dalam dari “klik cepat,” kamu merasa paling dekat setelah melewati banyak musim. Cenderung menghargai sejarah panjang dibanding koneksi baru yang mengilap.',
    }),
    scoreRange: ML({
      ko: '34~36점',
      en: '34–36 pts',
      ja: '34〜36点',
      'zh-CN': '34–36 分',
      'zh-TW': '34–36 分',
      vi: '34–36 điểm',
      id: '34–36 poin',
    }),
    keywords: ML({
      ko: '시간·경험 축적·역사·숙성·오래됨의 가치',
      en: 'Time · lived history · shared story · aging bond · long-haul value',
      ja: '時間 · 経験の蓄積 · 歴史 · 熟成 · 長さの価値',
      'zh-CN': '时间·经历·历史·沉淀·长久的分量',
      'zh-TW': '時間·經歷·歷史·沉澱·長久的分量',
      vi: 'Thời gian · tích lũy · lịch sử · lắng đọng · giá trị lâu dài',
      id: 'Waktu · pengalaman · sejarah · matang · nilai jangka panjang',
    }),
    whyStays: ML({
      ko: '함께 겪은 수많은 상황들이 어떤 설명보다 강한 신뢰를 만들기 때문',
      en: 'So many shared moments build trust stronger than any explanation',
      ja: '一緒に乗り越えた数多の場面が、どんな説明より強い信頼をつくるから',
      'zh-CN': '一起经历的无数情境，比任何解释都更能建立信任',
      'zh-TW': '一起經歷的無數情境，比任何解釋都更能建立信任',
      vi: 'Vô số khoảnh khắc cùng trải tạo niềm tin mạnh hơn mọi lời giải thích',
      id: 'Banyak momen bersama membangun kepercayaan lebih kuat dari penjelasan',
    }),
    whyDrifts: ML({
      ko: '오랜 시간에도 불구하고 중요한 순간에 없었거나 배신감을 준 경우',
      en: 'Even after years, missing you in a key moment—or betrayal—breaks it',
      ja: '長くても、大切な瞬間にいなかったり、裏切りを感じたりすると壊れる',
      'zh-CN': '即使很久，若在关键时刻缺席或感到背叛，也会破裂',
      'zh-TW': '即使很久，若在關鍵時刻缺席或感到背叛，也會破裂',
      vi: 'Dù đã lâu, vắng mặt lúc quan trọng hoặc phản bội vẫn làm vỡ',
      id: 'Meski sudah lama, absen di momen kunci atau khianat tetap merusak',
    }),
    oftenHeard: ML({
      ko: '"우리 진짜 오래됐다"라는 말을 들을 때 가장 따뜻함을 느낌',
      en: 'You feel warmest when someone says, “We have really been through a lot of years.”',
      ja: '「私たち長いね」と言われたときいちばん温かい気持ちになる',
      'zh-CN': '听到“我们真的认识好久了”时最暖心',
      'zh-TW': '聽到「我們真的認識好久了」時最暖心',
      vi: 'Ấm nhất khi nghe “Ta đã bên nhau thật lâu rồi.”',
      id: 'Paling hangat saat dengar “Kita sudah lama banget ya.”',
    }),
    happyMoment: ML({
      ko: '"그때 우리 그랬잖아"로 시작하는 오래된 추억 이야기를 꺼낼 때',
      en: 'Old stories that start with “Remember when we…”',
      ja: '「あのときこうだったよね」で始まる昔話を語るとき',
      'zh-CN': '从“那时候我们…”开始翻老回忆的时候',
      'zh-TW': '從「那時候我們…」開始翻老回憶的時候',
      vi: 'Kể chuyện cũ bắt đầu bằng “Nhớ hồi đó ta…”',
      id: 'Cerita lama yang dimulai dengan “Ingat waktu kita…”',
    }),
    contactPattern: ML({
      ko: '자주는 아니지만 연락하면 오래된 일들이 자연스럽게 화제가 됨',
      en: 'Not constant—but when you talk, old shared chapters come up naturally',
      ja: '頻繁ではないが、連絡すると昔のことが自然に話題になる',
      'zh-CN': '不常联系，但一聊就会自然提起往事',
      'zh-TW': '不常聯絡，但一聊就會自然提起往事',
      vi: 'Không liên tục—nhưng cứ nhắn là chuyện cũ lại trào ra',
      id: 'Tidak tiap hari—tapi begitu ngobrol, cerita lama muncul sendiri',
    }),
    bestMatch: ML({
      ko: '함께한 시간을 소중히 여기는 사람. 또는 신뢰 안전망형처럼 중요한 순간마다 곁에 있어준 사람',
      en: 'Someone who treasures shared time—or a steady “there when it counts” type',
      ja: '一緒の時間を大切にする人。または大事な瞬間にそばにいてくれた信頼型',
      'zh-CN': '珍惜共同时光的人，或关键时刻总在身边的信赖型',
      'zh-TW': '珍惜共同時光的人，或關鍵時刻總在身邊的信賴型',
      vi: 'Người trân trọng thời gian chung—hoặc kiểu luôn có mặt lúc quan trọng',
      id: 'Yang menghargai waktu bersama—atau yang selalu ada di momen penting',
    }),
    clashStyle: ML({
      ko: '과거보다 현재만 중시하거나 관계를 쉽게 정리하는 사람',
      en: 'People who only care about “now” or discard bonds too easily',
      ja: '過去より今だけを重視したり、関係を簡単に切る人',
      'zh-CN': '只看当下、或轻易结束关系的人',
      'zh-TW': '只看當下、或輕易結束關係的人',
      vi: 'Chỉ sống “hiện tại” hoặc dễ bỏ mối quan hệ',
      id: 'Hanya peduli sekarang atau mudah memutus hubungan',
    }),
  },
];

export function calculatePhase3RealFriendConditionAnalysisResult(answers: number[]): string {
  const totalScore = answers.reduce((sum, score) => sum + score, 0);
  if (totalScore >= 0 && totalScore <= 5) return 'Type1';
  if (totalScore >= 6 && totalScore <= 11) return 'Type2';
  if (totalScore >= 12 && totalScore <= 19) return 'Type3';
  if (totalScore >= 20 && totalScore <= 27) return 'Type4';
  if (totalScore >= 28 && totalScore <= 33) return 'Type5';
  return 'Type6';
}
