/** 거리를 둬야 할 인맥 진단 — 12문항 4지선다, A=0 B=1 C=2 D=3, 총점 0~36 → Type1~6 */

export interface Phase3ToxicRelationshipDiagnosisQuestion {
  id: number;
  question: Record<string, string>;
  options: { text: Record<string, string>; score: number }[];
}

export interface Phase3ToxicRelationshipDiagnosisResult {
  type: string;
  emoji: string;
  title: Record<string, string>;
  shortDescription: Record<string, string>;
  description: Record<string, string>;
  diagnosisType: Record<string, string>;
  keyTraits: Record<string, string>;
  strategy: Record<string, string>;
  declaration: Record<string, string>;
  encouragement?: Record<string, string>;
  shareMessage: Record<string, string>;
}

export function calculatePhase3ToxicRelationshipDiagnosisResult(answers: number[]): string {
  const total = answers.reduce((sum, s) => sum + (s ?? 0), 0);
  if (total <= 5) return 'Type1';
  if (total <= 11) return 'Type2';
  if (total <= 19) return 'Type3';
  if (total <= 27) return 'Type4';
  if (total <= 33) return 'Type5';
  return 'Type6';
}

export const phase3ToxicRelationshipDiagnosisQuestions: Phase3ToxicRelationshipDiagnosisQuestion[] = [
  {
    id: 1,
    question: {
      ko: `내가 "요즘 좀 힘들어"라고 털어놨을 때 가장 자주 일어나는 일은?`,
      en: `When I open up and say "I've been having a hard time lately," what usually happens?`,
      ja: `「最近ちょっとしんどい」と話したとき、一番よく起こることは？`,
      'zh-CN': `当我说"最近有点累"时，通常会发生什么？`,
      'zh-TW': `當我說「最近有點累」時，通常會發生什麼事？`,
      vi: `Khi tôi thổ lộ "Gần đây tớ thấy khá mệt", điều gì thường xảy ra nhất?`,
      id: `Saat aku curhat "Belakangan ini aku agak capek," apa yang paling sering terjadi?`,
    },
    options: [
      {
        text: {
          ko: `잘 들어주고 공감해준다. 이야기하고 나면 가벼워진다`,
          en: `They listen well and empathize. I feel lighter after talking.`,
          ja: `しっかり聞いて共感してくれる。話した後は気持ちが軽くなる`,
          'zh-CN': `认真倾听并给予共鸣。聊完之后心里会轻松很多`,
          'zh-TW': `認真傾聽並給予共鳴。聊完之後心裡會輕鬆許多`,
          vi: `Họ lắng nghe và đồng cảm thật lòng. Sau khi nói ra tôi thấy nhẹ nhõm hơn`,
          id: `Dia mendengarkan dengan baik dan berempati. Setelah cerita, hatiku jadi lebih ringan`,
        },
        score: 0,
      },
      {
        text: {
          ko: `듣다가 슬그머니 자기 이야기로 넘어간다. 결국 내가 들어주고 온다`,
          en: `They quietly steer the conversation to themselves. In the end, I'm the one listening.`,
          ja: `聞いているうちにいつの間にか自分の話にすり替わる。結局私が聞き役になって帰ってくる`,
          'zh-CN': `听着听着话题就悄悄转到他们自己身上了。到最后反倒是我在听他们诉苦`,
          'zh-TW': `聽著聽著話題就悄悄轉到他們自己身上了。到最後反倒是我在聽他們訴苦`,
          vi: `Nghe một lúc thì họ lại lái sang chuyện của bản thân. Cuối cùng lại là tôi ngồi nghe họ`,
          id: `Sambil mendengarkan, dia diam-diam mengalihkan ke ceritanya sendiri. Ujung-ujungnya aku yang jadi pendengar`,
        },
        score: 1,
      },
      {
        text: {
          ko: `"나는 더 힘들어"로 받아친다. 고민 경쟁이 시작된다`,
          en: `They fire back with "I have it even worse." A competition of who's more miserable begins.`,
          ja: `「私の方がもっと大変」と返してくる。悩み比べが始まる`,
          'zh-CN': `对方会说"我比你更累"。于是就开始了一场"谁更苦"的比较`,
          'zh-TW': `對方會說「我比你更累」。於是就開始了一場「誰更苦」的比較`,
          vi: `Họ đáp lại "Tớ còn mệt hơn ấy". Thế là bắt đầu cuộc thi xem ai khổ hơn`,
          id: `Dia malah bilang "Aku lebih capek lagi". Lalu jadi kompetisi siapa yang lebih menderita`,
        },
        score: 2,
      },
      {
        text: {
          ko: `"그게 뭐가 힘들어?" 또는 공감 없이 바로 해결책을 강요한다`,
          en: `They say "Why is that even hard?" or skip empathy entirely and force a solution on me.`,
          ja: `「それが何がしんどいの？」と言うか、共感なしにすぐ解決策を押し付けてくる`,
          'zh-CN': `说"那有什么好累的？"，或者完全不表示理解，直接强行给出解决方案`,
          'zh-TW': `說「那有什麼好累的？」，或完全不表示理解，直接強行給出解決方案`,
          vi: `Họ nói "Vậy có gì mà mệt?" hoặc chẳng đồng cảm gì mà ép tôi phải nghe giải pháp ngay`,
          id: `Dia bilang "Itu doang capek?" atau langsung memaksakan solusi tanpa empati sama sekali`,
        },
        score: 3,
      },
    ],
  },
  {
    id: 2,
    question: {
      ko: `내게 좋은 일이 생겼을 때 그 사람의 반응 장면은?`,
      en: `When something good happens to me, how do they usually react?`,
      ja: `私に良いことがあったとき、その人の反応は？`,
      'zh-CN': `当我遇到好事时，那个人的反应通常是？`,
      'zh-TW': `當我遇到好事時，那個人的反應通常是？`,
      vi: `Khi tôi có tin vui, phản ứng của người đó thường là gì?`,
      id: `Saat aku mengalami hal baik, bagaimana biasanya reaksi orang itu?`,
    },
    options: [
      {
        text: {
          ko: `진심으로 기뻐해준다. 같이 신나하는 게 느껴진다`,
          en: `They're genuinely happy for me. I can feel them getting excited together with me.`,
          ja: `心から喜んでくれる。一緒に盛り上がってくれているのが伝わる`,
          'zh-CN': `会真心为我感到高兴，能感觉到他们也和我一起兴奋`,
          'zh-TW': `會真心為我感到高興，能感覺到他們也和我一起興奮`,
          vi: `Họ vui mừng thật lòng cho tôi. Tôi cảm nhận được họ cũng phấn khích cùng mình`,
          id: `Dia benar-benar senang untukku. Aku bisa merasakan dia ikut antusias bersamaku`,
        },
        score: 0,
      },
      {
        text: {
          ko: `기뻐해주는데 어딘가 어색하다. 반응이 빨리 넘어간다`,
          en: `They act happy, but it feels a bit off. They move past it quickly.`,
          ja: `喜んではくれるけどどこかぎこちない。反応がすぐに終わる`,
          'zh-CN': `会表现出高兴，但总觉得有点不自然，反应也很快就过去了`,
          'zh-TW': `會表現出高興，但總覺得有點不自然，反應也很快就過去了`,
          vi: `Họ tỏ ra vui nhưng có gì đó gượng gạo. Phản ứng qua rất nhanh`,
          id: `Dia terlihat senang tapi rasanya agak aneh. Reaksinya cepat berlalu`,
        },
        score: 1,
      },
      {
        text: {
          ko: `"나는 언제 그런 일이 생기냐"며 자기 이야기로 전환한다`,
          en: `They say "When will something like that ever happen to me?" and turn it into their own story.`,
          ja: `「私にはいつそんなことが起きるんだろう」と自分の話に切り替える`,
          'zh-CN': `会说"我什么时候才能遇到这种好事啊"，然后把话题转到自己身上`,
          'zh-TW': `會說「我什麼時候才能遇到這種好事啊」，然後把話題轉到自己身上`,
          vi: `Họ nói "Không biết khi nào tớ mới gặp chuyện như vậy" rồi chuyển sang nói về bản thân`,
          id: `Dia bilang "Kapan ya aku bisa dapat hal seperti itu" lalu mengalihkan ke ceritanya sendiri`,
        },
        score: 2,
      },
      {
        text: {
          ko: `"그게 그렇게 대단해?" 또는 슬쩍 깎아내리는 말 한마디가 따라온다`,
          en: `They say "Is that really such a big deal?" or slip in a subtle put-down.`,
          ja: `「それってそんなにすごいこと？」と言うか、こっそり見下すような一言が付いてくる`,
          'zh-CN': `会说"那有什么了不起的？"，或是悄悄补上一句贬低我的话`,
          'zh-TW': `會說「那有什麼了不起的？」，或是悄悄補上一句貶低我的話`,
          vi: `Họ nói "Có gì mà ghê gớm vậy?" hoặc kèm theo một câu dìm nhẹ`,
          id: `Dia bilang "Segitu doang bangga?" atau menyelipkan sindiran kecil yang meremehkan`,
        },
        score: 3,
      },
    ],
  },
  {
    id: 3,
    question: {
      ko: `내가 부탁을 거절했을 때 그 다음에 일어나는 일은?`,
      en: `When I turn down a favor, what happens next?`,
      ja: `お願いを断ったとき、その後どうなる？`,
      'zh-CN': `当我拒绝一个请求之后，接下来会发生什么？`,
      'zh-TW': `當我拒絕一個請求之後，接下來會發生什麼事？`,
      vi: `Khi tôi từ chối một lời đề nghị, điều gì xảy ra sau đó?`,
      id: `Saat aku menolak permintaan, apa yang terjadi setelahnya?`,
    },
    options: [
      {
        text: {
          ko: `"어 그래, 괜찮아"하고 자연스럽게 넘어간다`,
          en: `They just say "Oh sure, no worries" and move on naturally.`,
          ja: `「あ、そう、大丈夫」と自然に流してくれる`,
          'zh-CN': `会说"啊好，没关系"，然后很自然地就过去了`,
          'zh-TW': `會說「啊好，沒關係」，然後很自然地就過去了`,
          vi: `Họ chỉ nói "À được, không sao" rồi bỏ qua rất tự nhiên`,
          id: `Dia cuma bilang "Oh oke, gak masalah" dan berlalu begitu saja`,
        },
        score: 0,
      },
      {
        text: {
          ko: `알겠다고는 하는데 표정이 살짝 굳거나 며칠 연락이 뜸해진다`,
          en: `They say okay, but their expression stiffens a bit, or they go quiet for a few days.`,
          ja: `わかったとは言うけど表情が少し硬くなったり、数日連絡が減ったりする`,
          'zh-CN': `嘴上说没关系，但表情会微微僵住，或者接下来几天联系变少`,
          'zh-TW': `嘴上說沒關係，但表情會微微僵住，或者接下來幾天聯繫變少`,
          vi: `Họ nói được nhưng nét mặt hơi cứng lại, hoặc vài ngày sau ít liên lạc hơn`,
          id: `Dia bilang oke tapi ekspresinya sedikit kaku, atau jadi jarang menghubungi beberapa hari`,
        },
        score: 1,
      },
      {
        text: {
          ko: `며칠 동안 차갑게 군다. 내가 먼저 풀어야 하는 상황이 된다`,
          en: `They act cold for days, and I end up being the one who has to smooth things over.`,
          ja: `数日間冷たくする。結局私が先に機嫌を取らなければならない状況になる`,
          'zh-CN': `会冷淡好几天，最后变成要我先低头去缓和关系`,
          'zh-TW': `會冷淡好幾天，最後變成要我先低頭去緩和關係`,
          vi: `Họ lạnh nhạt vài ngày, và cuối cùng tôi phải là người chủ động làm lành trước`,
          id: `Dia bersikap dingin selama beberapa hari, dan aku yang harus mencairkan situasi lebih dulu`,
        },
        score: 2,
      },
      {
        text: {
          ko: `"그럼 나도 너 도움 안 줄 거야"식의 말이 나온다. 관계가 협상 테이블이 된다`,
          en: `They say things like "Then I won't help you either." The relationship turns into a negotiation table.`,
          ja: `「じゃあ私もあなたを助けない」的な言葉が出る。関係が交渉の場になる`,
          'zh-CN': `会说出"那我以后也不帮你了"之类的话，整段关系变成了一场谈判`,
          'zh-TW': `會說出「那我以後也不幫你了」之類的話，整段關係變成了一場談判`,
          vi: `Họ nói kiểu "Vậy thì tớ cũng không giúp bạn đâu". Mối quan hệ biến thành một cuộc thương lượng`,
          id: `Dia bilang hal seperti "Kalau begitu aku juga gak akan bantu kamu". Hubungan berubah jadi meja negosiasi`,
        },
        score: 3,
      },
    ],
  },
  {
    id: 4,
    question: {
      ko: `그 사람과 오래 있다 집에 돌아왔을 때 드는 느낌은?`,
      en: `After spending a long time with them and coming home, how do I feel?`,
      ja: `その人と長時間一緒にいて帰宅したとき、どんな気持ちになる？`,
      'zh-CN': `和那个人待了很久回到家后，我的感觉是？`,
      'zh-TW': `和那個人待了很久回到家後，我的感覺是？`,
      vi: `Sau khi ở lâu với người đó rồi về nhà, tôi cảm thấy thế nào?`,
      id: `Setelah lama bersama orang itu dan pulang ke rumah, apa yang aku rasakan?`,
    },
    options: [
      {
        text: {
          ko: `재밌었다. 에너지가 충전된 기분이다`,
          en: `It was fun. I feel recharged.`,
          ja: `楽しかった。エネルギーが満たされた気分になる`,
          'zh-CN': `很开心，感觉能量被充满了`,
          'zh-TW': `很開心，感覺能量被充滿了`,
          vi: `Rất vui. Tôi cảm thấy như được sạc đầy năng lượng`,
          id: `Menyenangkan. Aku merasa energiku terisi ulang`,
        },
        score: 0,
      },
      {
        text: {
          ko: `좀 피곤하다. 그래도 나쁘진 않았다`,
          en: `A bit tired, but it wasn't bad.`,
          ja: `ちょっと疲れる。でも悪くはなかった`,
          'zh-CN': `有点累，但整体来说还不错`,
          'zh-TW': `有點累，但整體來說還不錯`,
          vi: `Có chút mệt, nhưng không đến mức tệ`,
          id: `Agak lelah. Tapi tetap tidak buruk`,
        },
        score: 1,
      },
      {
        text: {
          ko: `이유를 모르겠는데 기운이 빠져있다. 기분이 묘하게 안 좋다`,
          en: `I don't know why, but I feel drained. Something about my mood feels off.`,
          ja: `理由はわからないけど元気がなくなっている。なんとなく気分が悪い`,
          'zh-CN': `说不出原因，就是感觉浑身没劲，心情莫名地不好`,
          'zh-TW': `說不出原因，就是感覺渾身沒勁，心情莫名地不好`,
          vi: `Không hiểu tại sao nhưng tôi thấy đuối sức. Tâm trạng cứ khó chịu kỳ lạ`,
          id: `Entah kenapa tapi rasanya lemas. Mood-ku jadi aneh dan tidak enak`,
        },
        score: 2,
      },
      {
        text: {
          ko: `"내가 왜 저 사람을 만났지"라는 생각이 든다. 후회가 온다`,
          en: `I think "Why did I even meet up with them?" Regret sets in.`,
          ja: `「なんで私はあの人に会ったんだろう」と思う。後悔が押し寄せる`,
          'zh-CN': `会想"我为什么要见那个人"，后悔的情绪涌上来`,
          'zh-TW': `會想「我為什麼要見那個人」，後悔的情緒湧上來`,
          vi: `Tôi nghĩ "Sao mình lại gặp người đó nhỉ". Cảm giác hối hận ùa về`,
          id: `Aku berpikir "Kenapa sih aku ketemu orang itu". Rasa menyesal muncul`,
        },
        score: 3,
      },
    ],
  },
  {
    id: 5,
    question: {
      ko: `다른 사람 이야기가 나왔을 때 그 사람은?`,
      en: `When someone else comes up in conversation, what do they do?`,
      ja: `他の人の話が出たとき、その人は？`,
      'zh-CN': `当聊到其他人时，那个人会怎么样？`,
      'zh-TW': `當聊到其他人時，那個人會怎麼樣？`,
      vi: `Khi nói về người khác, người đó sẽ thế nào?`,
      id: `Saat membahas orang lain, apa yang dilakukan orang itu?`,
    },
    options: [
      {
        text: {
          ko: `없는 사람 험담을 잘 하지 않는다. 대화가 건강하다`,
          en: `They rarely badmouth people who aren't there. Our conversations stay healthy.`,
          ja: `陰口をあまり言わない。会話が健全`,
          'zh-CN': `很少说不在场的人的坏话，聊天的氛围很健康`,
          'zh-TW': `很少說不在場的人的壞話，聊天的氛圍很健康`,
          vi: `Họ hiếm khi nói xấu người không có mặt. Cuộc trò chuyện luôn lành mạnh`,
          id: `Dia jarang menjelekkan orang yang tidak ada di tempat. Obrolan kami sehat`,
        },
        score: 0,
      },
      {
        text: {
          ko: `가끔 뒷담화를 하긴 하지만 심한 편은 아니다`,
          en: `They gossip occasionally, but it's not too severe.`,
          ja: `時々陰口を言うこともあるけどひどい方ではない`,
          'zh-CN': `偶尔会说说别人的闲话，但程度不算严重`,
          'zh-TW': `偶爾會說說別人的閒話，但程度不算嚴重`,
          vi: `Thỉnh thoảng có nói xấu người khác nhưng không quá nặng`,
          id: `Sesekali bergosip, tapi tidak terlalu parah`,
        },
        score: 1,
      },
      {
        text: {
          ko: `만나면 항상 누군가 뒷담화가 빠지지 않는다. 나도 모르게 동참하게 된다`,
          en: `Every time we meet, someone's getting talked about behind their back. I end up joining in without noticing.`,
          ja: `会うたびに必ず誰かの陰口が出る。気づかないうちに私も加わってしまう`,
          'zh-CN': `每次见面都少不了说别人的闲话，我也会不知不觉地跟着一起说`,
          'zh-TW': `每次見面都少不了說別人的閒話，我也會不知不覺地跟著一起說`,
          vi: `Mỗi lần gặp là kiểu gì cũng có chuyện nói xấu ai đó. Tôi cũng vô thức tham gia theo`,
          id: `Setiap ketemu selalu ada gosip tentang seseorang. Tanpa sadar aku pun ikut terlibat`,
        },
        score: 2,
      },
      {
        text: {
          ko: `내가 없을 때 내 이야기를 했다는 게 다른 경로로 들려온 적이 있다`,
          en: `I've found out through someone else that they talked about me behind my back.`,
          ja: `私がいないときに私の話をしていたことが別の経路で聞こえてきたことがある`,
          'zh-CN': `我曾经从别的渠道得知，我不在场的时候他们在说我的坏话`,
          'zh-TW': `我曾經從別的渠道得知，我不在場的時候他們在說我的壞話`,
          vi: `Tôi đã từng nghe qua người khác rằng lúc tôi không có mặt, họ nói về tôi`,
          id: `Aku pernah dengar dari sumber lain bahwa mereka membicarakanku saat aku tidak ada`,
        },
        score: 3,
      },
    ],
  },
  {
    id: 6,
    question: {
      ko: `그 사람이 실수나 잘못을 했을 때 장면은?`,
      en: `When they make a mistake or do something wrong, what happens?`,
      ja: `その人がミスや過ちを犯したとき、どうなる？`,
      'zh-CN': `当那个人犯错时，会是什么情形？`,
      'zh-TW': `當那個人犯錯時，會是什麼情形？`,
      vi: `Khi người đó phạm lỗi hoặc làm sai điều gì, chuyện gì sẽ xảy ra?`,
      id: `Saat orang itu membuat kesalahan, apa yang terjadi?`,
    },
    options: [
      {
        text: {
          ko: `인정하고 사과한다. 어른스럽게 처리한다`,
          en: `They own up and apologize. They handle it maturely.`,
          ja: `認めて謝る。大人らしく対応する`,
          'zh-CN': `会承认错误并道歉，处理方式很成熟`,
          'zh-TW': `會承認錯誤並道歉，處理方式很成熟`,
          vi: `Họ nhận lỗi và xin lỗi. Xử lý mọi việc rất trưởng thành`,
          id: `Dia mengakui dan meminta maaf. Menanganinya dengan dewasa`,
        },
        score: 0,
      },
      {
        text: {
          ko: `인정은 하는데 변명이 길다. 사과까지 가는 데 시간이 걸린다`,
          en: `They admit it, but with a long excuse. It takes a while to actually get to an apology.`,
          ja: `認めはするけど言い訳が長い。謝罪までに時間がかかる`,
          'zh-CN': `会承认，但找的借口很长，要花很久才会真正道歉`,
          'zh-TW': `會承認，但找的藉口很長，要花很久才會真正道歉`,
          vi: `Họ nhận lỗi nhưng biện minh dài dòng. Phải mất thời gian mới đi đến lời xin lỗi`,
          id: `Dia mengakui tapi dengan alasan yang panjang. Butuh waktu lama sampai benar-benar minta maaf`,
        },
        score: 1,
      },
      {
        text: {
          ko: `절대 먼저 사과하지 않는다. 오히려 상황을 내 탓으로 돌린다`,
          en: `They never apologize first. Instead, they turn the situation around and blame me.`,
          ja: `絶対に先に謝らない。むしろ状況を私のせいにする`,
          'zh-CN': `从来不会主动先道歉，反而会把事情怪到我头上`,
          'zh-TW': `從來不會主動先道歉，反而會把事情怪到我頭上`,
          vi: `Họ tuyệt đối không xin lỗi trước. Ngược lại còn đổ lỗi cho tôi`,
          id: `Dia sama sekali tidak pernah minta maaf lebih dulu. Malah membalikkan keadaan dan menyalahkanku`,
        },
        score: 2,
      },
      {
        text: {
          ko: `자기 잘못을 아예 인식하지 못하거나 "네가 나를 그렇게 느끼게 만든 거잖아"식으로 반응한다`,
          en: `They don't even recognize they did anything wrong, or respond with "You're the one who made me feel that way."`,
          ja: `自分の過ちを全く認識できないか、「あなたが私にそう感じさせたんじゃない」というふうに反応する`,
          'zh-CN': `完全意识不到自己的错误，或者反过来说"是你让我变成这样的"`,
          'zh-TW': `完全意識不到自己的錯誤，或者反過來說「是你讓我變成這樣的」`,
          vi: `Họ hoàn toàn không nhận ra lỗi của mình, hoặc phản ứng kiểu "Chính bạn khiến tớ làm vậy đấy"`,
          id: `Dia sama sekali tidak menyadari kesalahannya, atau malah bilang "Kamu yang bikin aku jadi begini"`,
        },
        score: 3,
      },
    ],
  },
  {
    id: 7,
    question: {
      ko: `나와 그 사람의 관계에서 주로 어떤 구도가 만들어지나요?`,
      en: `In my relationship with them, what dynamic tends to form?`,
      ja: `私とその人の関係では主にどんな構図ができる？`,
      'zh-CN': `在我和那个人的关系中，通常会形成什么样的模式？`,
      'zh-TW': `在我和那個人的關係中，通常會形成什麼樣的模式？`,
      vi: `Trong quan hệ giữa tôi và người đó, thường hình thành kiểu cân bằng nào?`,
      id: `Dalam hubunganku dengan orang itu, biasanya pola apa yang terbentuk?`,
    },
    options: [
      {
        text: {
          ko: `서로 받고 주는 균형이 있다. 편안하다`,
          en: `There's a balance of give and take. It feels comfortable.`,
          ja: `互いに与えて受け取る均衡がある。心地よい`,
          'zh-CN': `彼此之间有付出和获得的平衡，感觉很自在`,
          'zh-TW': `彼此之間有付出和獲得的平衡，感覺很自在`,
          vi: `Có sự cân bằng cho và nhận giữa hai bên. Cảm thấy thoải mái`,
          id: `Ada keseimbangan saling memberi dan menerima. Rasanya nyaman`,
        },
        score: 0,
      },
      {
        text: {
          ko: `내가 조금 더 맞춰주는 편이다. 가끔 피곤하지만 괜찮은 수준이다`,
          en: `I tend to accommodate them a bit more. It's tiring sometimes but manageable.`,
          ja: `私が少し多めに合わせる方だ。時々疲れるけど大丈夫なレベル`,
          'zh-CN': `我会稍微多迁就一些，偶尔会累，但还在可以接受的范围`,
          'zh-TW': `我會稍微多遷就一些，偶爾會累，但還在可以接受的範圍`,
          vi: `Tôi thường là người nhường nhịn nhiều hơn một chút. Có mệt nhưng vẫn ở mức chấp nhận được`,
          id: `Aku yang lebih sering menyesuaikan diri. Kadang lelah tapi masih dalam batas wajar`,
        },
        score: 1,
      },
      {
        text: {
          ko: `항상 내가 더 맞추고 내가 더 챙긴다. 어느 순간 역할이 고정됐다`,
          en: `I'm always the one adjusting and taking care of things. At some point, the roles became fixed.`,
          ja: `いつも私がもっと合わせて、もっと気を配る。いつの間にか役割が固定された`,
          'zh-CN': `一直都是我在迁就、我在照顾对方，不知不觉角色就固定下来了`,
          'zh-TW': `一直都是我在遷就、我在照顧對方，不知不覺角色就固定下來了`,
          vi: `Luôn là tôi nhường nhịn nhiều hơn, tôi chăm sóc nhiều hơn. Đến một lúc vai trò đã bị cố định`,
          id: `Selalu aku yang lebih menyesuaikan dan lebih memperhatikan. Entah kapan perannya jadi tetap seperti itu`,
        },
        score: 2,
      },
      {
        text: {
          ko: `나는 계속 퍼주는데 상대방은 당연하게 받는다. 고마워하는 것을 본 적이 없다`,
          en: `I keep giving and giving, while they just take it for granted. I've never seen them show gratitude.`,
          ja: `私はずっと与え続けているのに相手は当然のように受け取る。感謝されたのを見たことがない`,
          'zh-CN': `我一直不停地付出，对方却理所当然地接受，从来没见过他表示感谢`,
          'zh-TW': `我一直不停地付出，對方卻理所當然地接受，從來沒見過他表示感謝`,
          vi: `Tôi cứ mãi cho đi, còn đối phương thì coi đó là điều hiển nhiên. Tôi chưa từng thấy họ biết ơn`,
          id: `Aku terus memberi, tapi dia menerimanya seolah itu sudah sewajarnya. Aku belum pernah melihatnya berterima kasih`,
        },
        score: 3,
      },
    ],
  },
  {
    id: 8,
    question: {
      ko: `내가 잘 되거나 성장하는 것에 대해 그 사람은?`,
      en: `How do they react when I succeed or grow?`,
      ja: `私がうまくいったり成長したりすることについて、その人は？`,
      'zh-CN': `对于我变得顺利或成长，那个人是什么反应？`,
      'zh-TW': `對於我變得順利或成長，那個人是什麼反應？`,
      vi: `Về việc tôi thành công hay phát triển, người đó phản ứng thế nào?`,
      id: `Tentang keberhasilan atau perkembanganku, bagaimana reaksi orang itu?`,
    },
    options: [
      {
        text: {
          ko: `진심으로 응원하고 자랑스러워한다`,
          en: `They genuinely root for me and feel proud.`,
          ja: `心から応援して誇らしく思ってくれる`,
          'zh-CN': `会真心为我加油，并为我感到自豪`,
          'zh-TW': `會真心為我加油，並為我感到自豪`,
          vi: `Họ ủng hộ và tự hào về tôi một cách thật lòng`,
          id: `Dia benar-benar mendukung dan bangga padaku`,
        },
        score: 0,
      },
      {
        text: {
          ko: `응원은 하는데 자신도 모르게 비교 발언이 나올 때가 있다`,
          en: `They do support me, but sometimes a comparison slips out without them realizing.`,
          ja: `応援はするけど、自分でも気づかないうちに比較する発言が出ることがある`,
          'zh-CN': `会加油鼓励，但有时会不自觉地说出比较的话`,
          'zh-TW': `會加油鼓勵，但有時會不自覺地說出比較的話`,
          vi: `Có ủng hộ nhưng đôi khi vô thức lại nói câu so sánh`,
          id: `Dia mendukung, tapi kadang tanpa sadar mengucapkan perbandingan`,
        },
        score: 1,
      },
      {
        text: {
          ko: `나의 성취를 불편해하거나 분위기를 묘하게 만든다`,
          en: `They seem uncomfortable with my achievements or make the mood weirdly tense.`,
          ja: `私の成果を不快に思ったり、雰囲気を微妙にする`,
          'zh-CN': `会对我的成就感到不舒服，或者让气氛变得奇怪`,
          'zh-TW': `會對我的成就感到不舒服，或者讓氣氛變得奇怪`,
          vi: `Có vẻ khó chịu với thành tích của tôi hoặc làm không khí trở nên kỳ lạ`,
          id: `Dia terlihat tidak nyaman dengan pencapaianku atau membuat suasana jadi aneh`,
        },
        score: 2,
      },
      {
        text: {
          ko: `"운이 좋았던 거 아니야?" "네가 잘 한 게 맞아?"식으로 공을 깎아내린다`,
          en: `They downplay my credit with things like "Wasn't that just luck?" or "Are you sure it was actually you?"`,
          ja: `「運が良かったんじゃない？」「本当に君がうまくやったの？」というふうに功績を過小評価する`,
          'zh-CN': `会用"是不是运气好而已？""真的是你做得好吗？"这种话贬低我的功劳`,
          'zh-TW': `會用「是不是運氣好而已？」「真的是你做得好嗎？」這種話貶低我的功勞`,
          vi: `Họ hạ thấp công lao của tôi bằng câu "Chắc là do may mắn thôi?" hay "Có chắc là do bạn làm tốt không?"`,
          id: `Dia meremehkan usahaku dengan bilang "Itu cuma keberuntungan kan?" atau "Kamu yakin itu memang hasil kerjamu?"`,
        },
        score: 3,
      },
    ],
  },
  {
    id: 9,
    question: {
      ko: `다른 사람들 앞에서 나를 대하는 방식은?`,
      en: `How do they treat me in front of other people?`,
      ja: `他の人たちの前で私を扱う態度は？`,
      'zh-CN': `在其他人面前，那个人对待我的方式是？`,
      'zh-TW': `在其他人面前，那個人對待我的方式是？`,
      vi: `Trước mặt người khác, cách người đó đối xử với tôi là gì?`,
      id: `Bagaimana orang itu memperlakukanku di depan orang lain?`,
    },
    options: [
      {
        text: {
          ko: `둘만 있을 때와 비슷하게 존중해준다`,
          en: `They treat me with the same respect as when we're alone.`,
          ja: `二人だけのときと同じように尊重してくれる`,
          'zh-CN': `会像我们两人独处时一样尊重我`,
          'zh-TW': `會像我們兩人獨處時一樣尊重我`,
          vi: `Họ vẫn tôn trọng tôi giống như khi chỉ có hai người`,
          id: `Dia tetap menghargaiku seperti saat kami berdua saja`,
        },
        score: 0,
      },
      {
        text: {
          ko: `약간 달라지긴 하는데 크게 신경 쓸 수준은 아니다`,
          en: `It changes a little, but not enough to really bother me.`,
          ja: `少し変わることはあるけど大きく気にするほどではない`,
          'zh-CN': `会有一点点变化，但不到需要特别在意的程度`,
          'zh-TW': `會有一點點變化，但不到需要特別在意的程度`,
          vi: `Có thay đổi một chút nhưng chưa đến mức phải bận tâm nhiều`,
          id: `Ada sedikit perubahan tapi tidak sampai membuatku terlalu khawatir`,
        },
        score: 1,
      },
      {
        text: {
          ko: `사람들 앞에서 나를 은근히 웃음거리로 만들거나 망신 주는 말을 한다`,
          en: `In front of others, they subtly make me the butt of a joke or say embarrassing things about me.`,
          ja: `人前で私をこっそり笑いものにしたり、恥をかかせる発言をする`,
          'zh-CN': `会在别人面前悄悄拿我当笑话，或说让我出丑的话`,
          'zh-TW': `會在別人面前悄悄拿我當笑話，或說讓我出醜的話`,
          vi: `Trước mặt người khác, họ ngầm biến tôi thành trò cười hoặc nói lời khiến tôi mất mặt`,
          id: `Di depan orang lain, dia diam-diam menjadikanku bahan lelucon atau mengucapkan hal yang memalukan bagiku`,
        },
        score: 2,
      },
      {
        text: {
          ko: `나를 무시하거나 이용하는 게 더 노골적으로 드러난다`,
          en: `The way they disregard or use me becomes even more blatant.`,
          ja: `私を無視したり利用したりすることがもっと露骨に現れる`,
          'zh-CN': `无视或利用我的态度会表现得更加明显`,
          'zh-TW': `無視或利用我的態度會表現得更加明顯`,
          vi: `Việc họ coi thường hoặc lợi dụng tôi thể hiện càng rõ ràng hơn`,
          id: `Sikap merendahkan atau memanfaatkanku terlihat lebih terang-terangan`,
        },
        score: 3,
      },
    ],
  },
  {
    id: 10,
    question: {
      ko: `내 비밀이나 약한 부분을 공유했을 때 어떻게 됐나요?`,
      en: `When I shared a secret or a vulnerable part of myself, what happened?`,
      ja: `私の秘密や弱い部分を共有したとき、どうなった？`,
      'zh-CN': `当我分享自己的秘密或脆弱的一面时，结果如何？`,
      'zh-TW': `當我分享自己的秘密或脆弱的一面時，結果如何？`,
      vi: `Khi tôi chia sẻ bí mật hoặc điểm yếu của mình, điều gì đã xảy ra?`,
      id: `Saat aku membagikan rahasia atau sisi lemahku, apa yang terjadi?`,
    },
    options: [
      {
        text: {
          ko: `잘 지켜줬다. 신뢰할 수 있는 사람이다`,
          en: `They kept it well. They're someone I can trust.`,
          ja: `しっかり守ってくれた。信頼できる人だ`,
          'zh-CN': `会好好保守秘密，是个值得信任的人`,
          'zh-TW': `會好好保守秘密，是個值得信任的人`,
          vi: `Họ giữ kín rất tốt. Là người tôi có thể tin tưởng`,
          id: `Dia menjaganya dengan baik. Orang yang bisa dipercaya`,
        },
        score: 0,
      },
      {
        text: {
          ko: `대부분 지켰는데 한 번 실수처럼 흘린 적이 있다`,
          en: `They kept it most of the time, but once let it slip like it was an accident.`,
          ja: `ほとんど守ってくれたけど一度失敗のように漏らしたことがある`,
          'zh-CN': `大多数时候都能保密，但有一次像是不小心说漏了嘴`,
          'zh-TW': `大多數時候都能保密，但有一次像是不小心說漏了嘴`,
          vi: `Phần lớn là giữ được, nhưng có một lần lỡ nói ra như thể vô ý`,
          id: `Sebagian besar dijaga, tapi sekali pernah bocor seperti tidak sengaja`,
        },
        score: 1,
      },
      {
        text: {
          ko: `그 이야기가 나중에 다른 사람을 통해 돌아온 적이 있다`,
          en: `That story came back to me later through someone else.`,
          ja: `その話が後で別の人を通じて戻ってきたことがある`,
          'zh-CN': `那件事后来通过别人传回到我耳中过`,
          'zh-TW': `那件事後來透過別人傳回到我耳中過`,
          vi: `Chuyện đó sau này đã quay lại với tôi qua người khác`,
          id: `Cerita itu pernah kembali padaku lewat orang lain di kemudian hari`,
        },
        score: 2,
      },
      {
        text: {
          ko: `내 약점을 이용해 나를 조종하거나 상황에 따라 꺼내드는 느낌이 있다`,
          en: `It feels like they use my weakness to manipulate me or bring it up whenever it's convenient for them.`,
          ja: `私の弱点を利用して操ったり、状況に応じて持ち出したりする感じがある`,
          'zh-CN': `感觉他们会利用我的弱点来操控我，或是视情况把这件事拿出来说`,
          'zh-TW': `感覺他們會利用我的弱點來操控我，或是視情況把這件事拿出來說`,
          vi: `Cảm giác họ lợi dụng điểm yếu của tôi để điều khiển tôi, hoặc lôi ra tùy lúc cần`,
          id: `Rasanya dia memanfaatkan kelemahanku untuk mengendalikanku, atau mengungkitnya sesuai situasi yang menguntungkan dia`,
        },
        score: 3,
      },
    ],
  },
  {
    id: 11,
    question: {
      ko: `그 사람 연락이 오는 걸 봤을 때 나의 첫 반응은?`,
      en: `When I see them contacting me, what's my first reaction?`,
      ja: `その人から連絡が来たのを見たとき、私の最初の反応は？`,
      'zh-CN': `当我看到那个人联系我时，我的第一反应是？`,
      'zh-TW': `當我看到那個人聯繫我時，我的第一反應是？`,
      vi: `Khi thấy người đó liên lạc, phản ứng đầu tiên của tôi là gì?`,
      id: `Saat melihat orang itu menghubungi, apa reaksi pertamaku?`,
    },
    options: [
      {
        text: {
          ko: `반갑다. 기분이 좋아진다`,
          en: `I'm glad. It puts me in a good mood.`,
          ja: `嬉しい。気分が良くなる`,
          'zh-CN': `很开心，心情会变好`,
          'zh-TW': `很開心，心情會變好`,
          vi: `Vui mừng. Tâm trạng trở nên tốt hơn`,
          id: `Senang. Mood-ku jadi baik`,
        },
        score: 0,
      },
      {
        text: {
          ko: `별 감흥 없다. 그냥 확인한다`,
          en: `No real feeling either way. I just check it.`,
          ja: `特に感情はない。ただ確認するだけ`,
          'zh-CN': `没什么特别感觉，就是看一下而已`,
          'zh-TW': `沒什麼特別感覺，就是看一下而已`,
          vi: `Không có cảm xúc gì đặc biệt. Chỉ xem qua thôi`,
          id: `Tidak ada perasaan khusus. Cuma sekadar cek saja`,
        },
        score: 1,
      },
      {
        text: {
          ko: `뭔가 또 부탁인가 싶거나 살짝 피곤함이 먼저 온다`,
          en: `I wonder if it's another favor request, or a slight sense of tiredness hits first.`,
          ja: `また何かお願いなのかなと思ったり、少し疲労感が先にくる`,
          'zh-CN': `会先想"是不是又要拜托我什么事"，或先感到一丝疲惫`,
          'zh-TW': `會先想「是不是又要拜託我什麼事」，或先感到一絲疲憊`,
          vi: `Tôi nghĩ ngay "Lại có nhờ vả gì đây không" hoặc cảm thấy hơi mệt trước tiên`,
          id: `Aku langsung berpikir "Jangan-jangan mau minta bantuan lagi" atau merasa sedikit lelah lebih dulu`,
        },
        score: 2,
      },
      {
        text: {
          ko: `받기 싫다는 생각이 든다. 모른 척하고 싶어진다`,
          en: `I feel like I don't want to answer. I want to pretend I didn't see it.`,
          ja: `受け取りたくないと思う。見なかったふりをしたくなる`,
          'zh-CN': `会觉得不想接，想要假装没看到`,
          'zh-TW': `會覺得不想接，想要假裝沒看到`,
          vi: `Tôi cảm thấy không muốn trả lời. Muốn giả vờ như không thấy`,
          id: `Aku merasa tidak ingin merespons. Ingin berpura-pura tidak tahu`,
        },
        score: 3,
      },
    ],
  },
  {
    id: 12,
    question: {
      ko: `이 테스트를 하면서 가장 먼저 떠오른 사람은?`,
      en: `While taking this test, who's the first person that came to mind?`,
      ja: `このテストをしながら一番最初に思い浮かんだ人は？`,
      'zh-CN': `在做这个测试的过程中，第一个浮现在脑海里的人是？`,
      'zh-TW': `在做這個測驗的過程中，第一個浮現在腦海裡的人是？`,
      vi: `Trong lúc làm bài test này, ai là người đầu tiên hiện lên trong đầu tôi?`,
      id: `Saat mengisi tes ini, siapa orang pertama yang muncul di pikiranku?`,
    },
    options: [
      {
        text: {
          ko: `딱히 없다. 주변 사람들이 대체로 괜찮다`,
          en: `No one in particular. The people around me are generally fine.`,
          ja: `特にいない。周りの人たちは大体大丈夫`,
          'zh-CN': `没有特别想到谁，周围的人大体上都还不错`,
          'zh-TW': `沒有特別想到誰，周圍的人大體上都還不錯`,
          vi: `Không có ai đặc biệt. Những người quanh tôi nói chung đều ổn`,
          id: `Tidak ada yang khusus. Orang-orang di sekitarku pada umumnya baik-baik saja`,
        },
        score: 0,
      },
      {
        text: {
          ko: `한 명 정도 있긴 한데 심각한 건 아닌 것 같다`,
          en: `There's about one person, but it doesn't seem too serious.`,
          ja: `一人くらいいるけど深刻ではないと思う`,
          'zh-CN': `大概有一个人，但感觉不算严重`,
          'zh-TW': `大概有一個人，但感覺不算嚴重`,
          vi: `Có khoảng một người nhưng có lẽ không nghiêm trọng lắm`,
          id: `Ada sekitar satu orang, tapi sepertinya tidak terlalu serius`,
        },
        score: 1,
      },
      {
        text: {
          ko: `한 명이 바로 떠올랐다. 그리고 그 생각에 기분이 좀 불편해졌다`,
          en: `One person came to mind right away. And that thought made me feel a bit uneasy.`,
          ja: `一人すぐに思い浮かんだ。そしてその考えに少し気分が悪くなった`,
          'zh-CN': `立刻想到了一个人，而这个念头让我心里有点不舒服`,
          'zh-TW': `立刻想到了一個人，而這個念頭讓我心裡有點不舒服`,
          vi: `Có một người hiện lên ngay lập tức. Và suy nghĩ đó khiến tôi thấy khó chịu`,
          id: `Satu orang langsung muncul di pikiran. Dan pikiran itu membuatku sedikit tidak nyaman`,
        },
        score: 2,
      },
      {
        text: {
          ko: `여러 명이 동시에 떠올랐다. 나 이거 심각한 건가 싶다`,
          en: `Several people came to mind at once. I'm starting to wonder if this is actually serious.`,
          ja: `複数の人が同時に思い浮かんだ。これって深刻なのかなと思う`,
          'zh-CN': `好几个人同时浮现在脑海里，让我不禁怀疑这是不是很严重`,
          'zh-TW': `好幾個人同時浮現在腦海裡，讓我不禁懷疑這是不是很嚴重`,
          vi: `Nhiều người hiện lên cùng lúc. Tôi bắt đầu nghĩ liệu chuyện này có nghiêm trọng không`,
          id: `Beberapa orang muncul sekaligus. Aku mulai bertanya-tanya apakah ini serius`,
        },
        score: 3,
      },
    ],
  },
];

export const phase3ToxicRelationshipDiagnosisResults: Phase3ToxicRelationshipDiagnosisResult[] = [
  {
    type: 'Type1',
    emoji: '🟢',
    title: {
      ko: `거리둘 인맥 없는, 인맥 청정 구역`,
      en: `No One to Distance From, Clean Network Zone`,
      ja: `距離を置く相手がいない、人脈クリーンゾーン`,
      'zh-CN': `没有需要远离的人，人脉清净区`,
      'zh-TW': `沒有需要遠離的人，人脈清淨區`,
      vi: `Không có ai cần giữ khoảng cách, Vùng quan hệ sạch sẽ`,
      id: `Tidak Ada yang Perlu Dijauhi, Zona Lingkaran Pertemanan Bersih`,
    },
    shortDescription: {
      ko: `진단 결과: 주변 인간관계가 비교적 건강합니다`,
      en: `Diagnosis: Your relationships are relatively healthy.`,
      ja: `診断結果：周りの人間関係は比較的健全です`,
      'zh-CN': `诊断结果：你周围的人际关系相对健康`,
      'zh-TW': `診斷結果：你周圍的人際關係相對健康`,
      vi: `Kết quả chẩn đoán: Các mối quan hệ xung quanh bạn khá lành mạnh`,
      id: `Hasil diagnosis: Hubungan di sekitarmu relatif sehat`,
    },
    description: {
      ko: `당신의 인맥은 대체로 건강합니다. 에너지를 소모시키는 사람이 없거나 거의 없는 편입니다.\n\n만나고 나면 충전되는 사람들이 주변에 있고 관계에서 일방적으로 소진되는 패턴이 적습니다. 지금의 관계를 유지하면서 새로운 인맥을 만날 때 지금과 같은 기준을 유지하는 것이 중요합니다.`,
      en: `Your network is generally healthy. There are little to no people who drain your energy.\n\nYou have people around you who recharge you after meeting them, and there's not much of a one-sided draining pattern in your relationships. It's important to keep your current relationships while maintaining the same standards when meeting new people.`,
      ja: `あなたの人脈は概して健全です。エネルギーを消耗させる人がいない、またはほとんどいません。\n\n会うと元気をもらえる人たちが周りにいて、関係の中で一方的に消耗するパターンが少ないです。今の関係を維持しながら、新しい人脈に出会うときも今と同じ基準を保つことが大切です。`,
      'zh-CN': `你的人脉整体来说很健康，几乎没有会消耗你能量的人。\n\n你身边有见面后能让你充电的人，关系中很少出现单方面被消耗的模式。在维持现在的关系的同时，认识新朋友时也保持同样的标准很重要。`,
      'zh-TW': `你的人脈整體來說很健康，幾乎沒有會消耗你能量的人。\n\n你身邊有見面後能讓你充電的人，關係中很少出現單方面被消耗的模式。在維持現在的關係的同時，認識新朋友時也保持同樣的標準很重要。`,
      vi: `Mạng lưới quan hệ của bạn nói chung khá lành mạnh. Hầu như không có ai khiến bạn cạn năng lượng.\n\nBạn có những người xung quanh khiến bạn tràn đầy năng lượng sau khi gặp, và ít có kiểu quan hệ khiến bạn bị hao mòn một chiều. Điều quan trọng là duy trì các mối quan hệ hiện tại và giữ tiêu chuẩn tương tự khi gặp những người mới.`,
      id: `Lingkaran pertemananmu secara umum sehat. Hampir tidak ada orang yang menguras energimu.\n\nAda orang-orang di sekitarmu yang membuatmu terisi ulang setelah bertemu, dan jarang ada pola di mana kamu terkuras secara sepihak dalam hubungan. Penting untuk menjaga hubungan yang ada sekarang sambil tetap mempertahankan standar yang sama saat bertemu orang baru.`,
    },
    diagnosisType: {
      ko: `인맥 청정 구역 🟢`,
      en: `Clean Network Zone 🟢`,
      ja: `人脈クリーンゾーン 🟢`,
      'zh-CN': `人脉清净区 🟢`,
      'zh-TW': `人脈清淨區 🟢`,
      vi: `Vùng quan hệ sạch sẽ 🟢`,
      id: `Zona Lingkaran Pertemanan Bersih 🟢`,
    },
    keyTraits: {
      ko: `관계 에너지 균형 양호`,
      en: `Good relationship energy balance`,
      ja: `関係のエネルギーバランス良好`,
      'zh-CN': `关系能量平衡良好`,
      'zh-TW': `關係能量平衡良好`,
      vi: `Cân bằng năng lượng trong quan hệ tốt`,
      id: `Keseimbangan energi hubungan yang baik`,
    },
    strategy: {
      ko: `건강한 인맥도 관리가 필요합니다. 상대방 변화나 환경 변화로 관계 성격이 달라질 수 있으니 주기적으로 점검하는 습관이 도움됩니다\n\n현재 유지. 가끔 이 체크리스트로 인맥을 점검하세요`,
      en: `Even healthy relationships need maintenance. Since changes in the other person or in circumstances can shift the nature of a relationship, it helps to check in periodically.\n\nKeep things as they are. Just use this checklist occasionally to check up on your relationships.`,
      ja: `健全な人脈でも管理は必要です。相手の変化や環境の変化で関係の性質が変わることがあるので、定期的にチェックする習慣が役立ちます\n\n現状維持。時々このチェックリストで人脈を点検してください`,
      'zh-CN': `即使是健康的人脉也需要维护。因为对方的变化或环境的变化都可能改变关系的性质，养成定期检查的习惯会很有帮助\n\n保持现状。偶尔用这份清单检查一下你的人脉`,
      'zh-TW': `即使是健康的人脈也需要維護。因為對方的變化或環境的變化都可能改變關係的性質，養成定期檢查的習慣會很有幫助\n\n保持現狀。偶爾用這份清單檢查一下你的人脈`,
      vi: `Ngay cả những mối quan hệ lành mạnh cũng cần được chăm sóc. Vì sự thay đổi của người kia hoặc của môi trường có thể làm thay đổi bản chất mối quan hệ, nên việc kiểm tra định kỳ sẽ rất hữu ích\n\nGiữ nguyên như hiện tại. Đôi khi hãy dùng danh sách kiểm tra này để rà soát các mối quan hệ của bạn`,
      id: `Hubungan yang sehat pun tetap perlu dijaga. Karena perubahan pada orang lain atau lingkungan bisa mengubah sifat suatu hubungan, kebiasaan memeriksa secara berkala akan sangat membantu\n\nPertahankan kondisi saat ini. Sesekali gunakan checklist ini untuk memeriksa lingkaran pertemananmu`,
    },
    declaration: {
      ko: `내 에너지를 지키는 인간관계를 계속 유지하겠습니다 🟢`,
      en: `I will keep maintaining relationships that protect my energy 🟢`,
      ja: `私のエネルギーを守る人間関係をこれからも維持していきます 🟢`,
      'zh-CN': `我会继续维持能保护我能量的人际关系 🟢`,
      'zh-TW': `我會繼續維持能保護我能量的人際關係 🟢`,
      vi: `Tôi sẽ tiếp tục duy trì những mối quan hệ bảo vệ năng lượng của mình 🟢`,
      id: `Aku akan terus menjaga hubungan yang melindungi energiku 🟢`,
    },
    shareMessage: {
      ko: `거리둬야 할 인맥 진단: 인맥 청정 구역 🟢 거리둘 사람 없다는 결과... 주변 관리 잘 한 거 맞음 → 너는 어떤 결과 나왔어? 친구 태그해봐`,
      en: `Toxic Network Diagnosis: Clean Network Zone 🟢 Got the result that I have no one to distance from... guess I've managed my circle well → What result did you get? Tag a friend`,
      ja: `距離を置くべき人脈診断：人脈クリーンゾーン 🟢 距離を置くべき人がいないという結果...周りをうまく管理してたみたい → あなたはどんな結果が出た？友達をタグ付けしてみて`,
      'zh-CN': `该远离的人脉诊断：人脉清净区 🟢 测出没有需要远离的人...看来我把周围的关系维护得不错 → 你测出了什么结果？快去标记朋友试试吧`,
      'zh-TW': `該遠離的人脈診斷：人脈清淨區 🟢 測出沒有需要遠離的人...看來我把周圍的關係維護得不錯 → 你測出了什麼結果？快去標記朋友試試吧`,
      vi: `Chẩn đoán mối quan hệ cần tránh xa: Vùng quan hệ sạch sẽ 🟢 Kết quả là không có ai cần giữ khoảng cách... có vẻ tôi quản lý các mối quan hệ khá tốt → Bạn ra kết quả gì? Tag bạn bè thử xem`,
      id: `Diagnosis Lingkaran Pertemanan yang Perlu Dijauhi: Zona Bersih 🟢 Hasilnya tidak ada yang perlu dijauhi... berarti aku sudah mengelola lingkaranku dengan baik → Kamu dapat hasil apa? Coba tag temanmu`,
    },
  },
  {
    type: 'Type2',
    emoji: '🔋',
    title: {
      ko: `피곤하게 만드는 사람이 있는, 에너지 드레이너 보유형`,
      en: `There's Someone Who Tires You Out, Energy Drainer Holder`,
      ja: `疲れさせる人がいる、エナジードレイナー保有型`,
      'zh-CN': `有一个让你疲惫的人，能量吸血鬼持有型`,
      'zh-TW': `有一個讓你疲憊的人，能量吸血鬼持有型`,
      vi: `Có Người Khiến Bạn Mệt Mỏi, Kiểu Sở Hữu Người Hút Năng Lượng`,
      id: `Ada Orang yang Membuatmu Lelah, Tipe Pemegang Penguras Energi`,
    },
    shortDescription: {
      ko: `진단 결과: 만날 때마다 묘하게 기운이 빠지는 사람이 한 명 있습니다`,
      en: `Diagnosis: There's one person who mysteriously drains your energy every time you meet.`,
      ja: `診断結果：会うたびに不思議と気力が抜ける人が一人います`,
      'zh-CN': `诊断结果：有一个人，每次见面都会莫名让你感到没劲`,
      'zh-TW': `診斷結果：有一個人，每次見面都會莫名讓你感到沒勁`,
      vi: `Kết quả chẩn đoán: Có một người khiến bạn kỳ lạ mất sức mỗi lần gặp`,
      id: `Hasil diagnosis: Ada satu orang yang entah kenapa selalu menguras tenagamu setiap bertemu`,
    },
    description: {
      ko: `딱히 나쁜 짓을 한 건 아닌데 같이 있으면 이유 없이 피곤한 사람이 있습니다.\n\n부탁을 자주 하거나 자기 이야기만 하거나 만남 자체가 에너지를 가져가는 사람입니다. 나쁜 사람이 아니라 맞지 않는 사람인 경우가 많습니다. 거리를 완전히 끊기보다 만남의 빈도와 깊이를 조절하는 전략이 효과적입니다.`,
      en: `They haven't really done anything wrong, but being around them makes you tired for no clear reason.\n\nThey might ask for favors often, only talk about themselves, or simply be someone whose presence drains your energy. Often it's not that they're a bad person — you're just not a good match. Rather than cutting them off completely, adjusting the frequency and depth of your meetups is a more effective strategy.`,
      ja: `特に悪いことをしたわけではないのに一緒にいると理由もなく疲れる人がいます。\n\nお願いをよくしてきたり自分の話ばかりしたり、会うこと自体がエネルギーを奪う人です。悪い人ではなく合わない人であることが多いです。完全に距離を断つより、会う頻度と深さを調整する戦略が効果的です。`,
      'zh-CN': `对方并没有做什么明显不好的事，但和他在一起就是会莫名感到疲惫。\n\n这种人常常总是拜托你帮忙、只谈自己的事，或者光是见面这件事本身就在消耗你的能量。他不一定是坏人，更多时候只是彼此不合拍。与其彻底断绝往来，调整见面的频率和深度会更有效。`,
      'zh-TW': `對方並沒有做什麼明顯不好的事，但和他在一起就是會莫名感到疲憊。\n\n這種人常常總是拜託你幫忙、只談自己的事，或者光是見面這件事本身就在消耗你的能量。他不一定是壞人，更多時候只是彼此不合拍。與其徹底斷絕往來，調整見面的頻率和深度會更有效。`,
      vi: `Người đó không hẳn làm gì xấu, nhưng chỉ cần ở cùng là bạn thấy mệt mà không rõ lý do.\n\nHọ có thể thường xuyên nhờ vả, chỉ nói về bản thân, hoặc việc gặp mặt tự nó đã lấy đi năng lượng của bạn. Nhiều khi không phải họ là người xấu, mà chỉ là không hợp với bạn. Thay vì cắt đứt hoàn toàn, chiến lược điều chỉnh tần suất và mức độ gặp gỡ sẽ hiệu quả hơn.`,
      id: `Orang ini tidak benar-benar melakukan hal buruk, tapi berada di dekatnya membuatmu lelah tanpa alasan yang jelas.\n\nDia mungkin sering meminta bantuan, hanya membicarakan dirinya sendiri, atau sekadar bertemu dengannya sudah menguras energimu. Seringkali dia bukan orang jahat, hanya tidak cocok denganmu. Daripada memutus hubungan sepenuhnya, strategi mengatur frekuensi dan kedalaman pertemuan akan lebih efektif.`,
    },
    diagnosisType: {
      ko: `에너지 드레이너 보유형 🔋`,
      en: `Energy Drainer Holder 🔋`,
      ja: `エナジードレイナー保有型 🔋`,
      'zh-CN': `能量吸血鬼持有型 🔋`,
      'zh-TW': `能量吸血鬼持有型 🔋`,
      vi: `Kiểu Sở Hữu Người Hút Năng Lượng 🔋`,
      id: `Tipe Pemegang Penguras Energi 🔋`,
    },
    keyTraits: {
      ko: `만나고 나면 기운이 빠짐, 부탁이 많음, 대화가 일방향`,
      en: `Drained after meeting, frequent favors, one-way conversations`,
      ja: `会った後に元気がなくなる、お願いが多い、会話が一方通行`,
      'zh-CN': `见面后没精神，请求很多，对话是单方向`,
      'zh-TW': `見面後沒精神，請求很多，對話是單方向`,
      vi: `Mất sức sau khi gặp, hay nhờ vả, cuộc trò chuyện một chiều`,
      id: `Lemas setelah bertemu, sering meminta bantuan, percakapan satu arah`,
    },
    strategy: {
      ko: `만남 빈도를 스스로 조절하기. 억지로 자주 만날 필요 없음\n모임 장소를 시간 제한이 있는 곳으로 정하기 (카페 대신 밥 한 끼 등)\n"오늘은 일찍 가야 해"를 자연스럽게 사용하기`,
      en: `Control the frequency of meetups yourself. There's no need to force frequent meetings\nChoose meeting places with a natural time limit (a meal instead of a café, etc.)\nUse phrases like "I have to leave early today" naturally`,
      ja: `会う頻度を自分でコントロールする。無理に頻繁に会う必要はない\n集まる場所を時間制限のある所にする（カフェの代わりに食事など）\n「今日は早く帰らないと」を自然に使う`,
      'zh-CN': `自己掌控见面的频率，不必勉强频繁见面\n把见面的地点选在有时间限制的场所（比如吃一顿饭代替泡咖啡厅）\n自然地使用"今天要早点走"这类话`,
      'zh-TW': `自己掌控見面的頻率，不必勉強頻繁見面\n把見面的地點選在有時間限制的場所（比如吃一頓飯代替泡咖啡廳）\n自然地使用「今天要早點走」這類話`,
      vi: `Tự điều chỉnh tần suất gặp gỡ. Không cần cố gắng gặp nhau thường xuyên\nChọn nơi gặp mặt có giới hạn thời gian tự nhiên (một bữa ăn thay vì ngồi cà phê, v.v.)\nSử dụng câu như "Hôm nay tớ phải về sớm" một cách tự nhiên`,
      id: `Atur sendiri frekuensi bertemu. Tidak perlu memaksakan diri untuk sering bertemu\nPilih tempat bertemu yang punya batasan waktu alami (makan sekali dibanding ngobrol di kafe, dll)\nGunakan kalimat seperti "Hari ini aku harus pulang cepat" secara alami`,
    },
    declaration: {
      ko: `내 에너지를 소모시키는 사람과의 만남 빈도를 줄이겠습니다 🔋`,
      en: `I will reduce how often I meet with people who drain my energy 🔋`,
      ja: `私のエネルギーを消耗させる人との会う頻度を減らします 🔋`,
      'zh-CN': `我会减少和消耗我能量的人见面的频率 🔋`,
      'zh-TW': `我會減少和消耗我能量的人見面的頻率 🔋`,
      vi: `Tôi sẽ giảm tần suất gặp những người khiến tôi cạn năng lượng 🔋`,
      id: `Aku akan mengurangi frekuensi bertemu dengan orang yang menguras energiku 🔋`,
    },
    shareMessage: {
      ko: `거리둬야 할 인맥 진단: 에너지 드레이너 보유형 🔋 만나고 나면 이유 없이 피곤한 사람 있다는 거... 그 사람 떠올랐다면 맞음 → 친구 태그해봐`,
      en: `Toxic Network Diagnosis: Energy Drainer Holder 🔋 Turns out there's someone who tires me out for no reason after meeting them... if a person just popped into your head, that's them → Tag a friend`,
      ja: `距離を置くべき人脈診断：エナジードレイナー保有型 🔋 会った後に理由もなく疲れる人がいるってこと...その人が思い浮かんだなら当たり → 友達をタグ付けしてみて`,
      'zh-CN': `该远离的人脉诊断：能量吸血鬼持有型 🔋 见完面莫名感到疲惫的人真的存在...如果你脑中浮现出那个人就对了 → 快去标记朋友试试吧`,
      'zh-TW': `該遠離的人脈診斷：能量吸血鬼持有型 🔋 見完面莫名感到疲憊的人真的存在...如果你腦中浮現出那個人就對了 → 快去標記朋友試試吧`,
      vi: `Chẩn đoán mối quan hệ cần tránh xa: Kiểu Sở Hữu Người Hút Năng Lượng 🔋 Hóa ra có người khiến mình mệt vô cớ sau khi gặp... nếu bạn vừa nghĩ đến ai đó thì đúng rồi → Tag bạn bè thử xem`,
      id: `Diagnosis Lingkaran Pertemanan yang Perlu Dijauhi: Tipe Penguras Energi 🔋 Ternyata ada orang yang membuatku lelah tanpa alasan setelah bertemu... kalau ada orang yang langsung terlintas, itu dia → Coba tag temanmu`,
    },
  },
  {
    type: 'Type3',
    emoji: '💧',
    title: {
      ko: `감정을 소모시키는 사람이 있는, 감정 착취 인맥 보유형`,
      en: `There's Someone Draining Your Emotions, Emotional Vampire Network Holder`,
      ja: `感情を消耗させる人がいる、感情搾取人脈保有型`,
      'zh-CN': `有一个消耗你情绪的人，情感剥削型人脉持有者`,
      'zh-TW': `有一個消耗你情緒的人，情感剝削型人脈持有者`,
      vi: `Có Người Bào Mòn Cảm Xúc Bạn, Kiểu Sở Hữu Mạng Lưới Ma Cà Rồng Cảm Xúc`,
      id: `Ada Orang yang Menguras Emosimu, Tipe Pemilik Jaringan Vampir Emosional`,
    },
    shortDescription: {
      ko: `진단 결과: 내 감정을 써내려가게 만드는 사람이 있습니다`,
      en: `Diagnosis: There's someone who keeps depleting your emotions.`,
      ja: `診断結果：私の感情を消費させる人がいます`,
      'zh-CN': `诊断结果：有一个人在不断消耗你的情绪`,
      'zh-TW': `診斷結果：有一個人在不斷消耗你的情緒`,
      vi: `Kết quả chẩn đoán: Có một người khiến cảm xúc của bạn dần bị bào mòn`,
      id: `Hasil diagnosis: Ada seseorang yang terus-menerus mengikis emosimu`,
    },
    description: {
      ko: `내 고민을 들어주다가 결국 내가 위로해주고 오거나 내가 힘들 때 항상 그 사람이 더 힘들어지는 상황이 반복됩니다.\n\n감정 착취형은 나쁜 의도 없이 습관적으로 상대방의 감정을 소모시키는 패턴을 가진 사람입니다. 이 관계에서 나는 항상 공급자 역할을 하게 됩니다. 경계선을 설정하는 것이 핵심입니다.`,
      en: `You start out listening to their problems, but somehow end up being the one who comforts them — or whenever you're struggling, they always end up seeming even more upset. This keeps repeating.\n\nThe emotional vampire type isn't necessarily malicious; they habitually drain the emotions of people around them. In this relationship, you always end up playing the role of supplier. Setting boundaries is key.`,
      ja: `私の悩みを聞いてもらうつもりが結局私が慰めて帰ってきたり、私が大変なときいつもその人がもっと大変になる状況が繰り返されます。\n\n感情搾取型は悪意なく習慣的に相手の感情を消耗させるパターンを持つ人です。この関係で私は常に供給者の役割をすることになります。境界線を設定することが核心です。`,
      'zh-CN': `本来是我在诉说烦恼，结果最后却变成我去安慰对方；每次我难受的时候，那个人总会变得比我更难受。这种情况反复出现。\n\n情感剥削型的人并非有恶意，只是习惯性地消耗对方的情绪。在这段关系中，我总是扮演着提供者的角色。设立界限才是关键。`,
      'zh-TW': `本來是我在訴說煩惱，結果最後卻變成我去安慰對方；每次我難受的時候，那個人總會變得比我更難受。這種情況反覆出現。\n\n情感剝削型的人並非有惡意，只是習慣性地消耗對方的情緒。在這段關係中，我總是扮演著提供者的角色。設立界限才是關鍵。`,
      vi: `Tôi định tâm sự để được lắng nghe nhưng cuối cùng lại là người phải an ủi họ, hoặc mỗi khi tôi khó khăn thì người đó luôn tỏ ra khó khăn hơn. Chuyện này lặp đi lặp lại.\n\nKiểu người bào mòn cảm xúc không hẳn có ý xấu, họ chỉ theo thói quen khiến cảm xúc của người khác bị hao mòn. Trong mối quan hệ này, tôi luôn đóng vai người cho đi. Việc thiết lập ranh giới là điều then chốt.`,
      id: `Aku mulai dengan mendengarkan curhatannya, tapi ujung-ujungnya malah aku yang menghiburnya — atau setiap kali aku sedang sulit, dia selalu tampak lebih sulit lagi. Ini terus berulang.\n\nTipe vampir emosional tidak selalu bermaksud jahat; mereka secara kebiasaan menguras emosi orang di sekitarnya. Dalam hubungan ini, aku selalu berperan sebagai pemberi. Menetapkan batasan adalah kuncinya.`,
    },
    diagnosisType: {
      ko: `감정 착취 인맥 보유형 💧`,
      en: `Emotional Vampire Network Holder 💧`,
      ja: `感情搾取人脈保有型 💧`,
      'zh-CN': `情感剥削型人脉持有者 💧`,
      'zh-TW': `情感剝削型人脈持有者 💧`,
      vi: `Kiểu Sở Hữu Mạng Lưới Ma Cà Rồng Cảm Xúc 💧`,
      id: `Tipe Pemilik Jaringan Vampir Emosional 💧`,
    },
    keyTraits: {
      ko: `내가 위로자, 경청자 고정, 고민 경쟁, 감정 상호성 부재`,
      en: `I'm always the comforter, fixed as the listener, competing over who's more troubled, no emotional reciprocity`,
      ja: `私が慰め役、聞き役に固定、悩み比べ、感情の相互性の欠如`,
      'zh-CN': `我固定扮演安慰者与倾听者，烦恼互相攀比，缺乏情感互惠`,
      'zh-TW': `我固定扮演安慰者與傾聽者，煩惱互相攀比，缺乏情感互惠`,
      vi: `Tôi luôn là người an ủi, cố định là người lắng nghe, thi thố ai khổ hơn, thiếu sự tương hỗ cảm xúc`,
      id: `Aku selalu jadi penghibur, terjebak sebagai pendengar tetap, kompetisi siapa lebih susah, tidak ada resiprositas emosional`,
    },
    strategy: {
      ko: `"오늘은 나도 좀 지쳐서 나중에 이야기하자"를 연습하기\n모든 연락에 즉각 반응하지 않기. 내 컨디션 먼저 체크하기\n상대방이 감정을 쏟아낼 때 "나도 요즘 힘들어"라고 솔직하게 말해보기\n이 관계에서 나의 필요도 표현할 수 있는지 점검하기`,
      en: `Practice saying "I'm a bit worn out today too, let's talk later"\nDon't respond to every message instantly. Check your own condition first\nWhen they start pouring out emotions, try honestly saying "I've been struggling lately too"\nCheck whether you're able to express your own needs in this relationship`,
      ja: `「今日は私も少し疲れてるから後で話そう」を練習する\nすべての連絡にすぐ反応しない。まず自分の状態を確認する\n相手が感情を吐き出すとき「私も最近しんどい」と正直に言ってみる\nこの関係で自分の必要も表現できるか点検する`,
      'zh-CN': `练习说"我今天也有点累，我们晚点再聊"\n不要对每条消息都立刻回应，先检查自己的状态\n当对方倾诉情绪时，试着坦诚地说"我最近也挺累的"\n检查自己在这段关系中是否也能表达自己的需求`,
      'zh-TW': `練習說「我今天也有點累，我們晚點再聊」\n不要對每條訊息都立刻回應，先檢查自己的狀態\n當對方傾訴情緒時，試著坦誠地說「我最近也挺累的」\n檢查自己在這段關係中是否也能表達自己的需求`,
      vi: `Tập nói "Hôm nay tớ cũng thấy hơi mệt, để lúc khác nói tiếp nhé"\nKhông phản hồi ngay mọi liên lạc. Kiểm tra trạng thái của mình trước\nKhi đối phương trút hết cảm xúc, hãy thử nói thật lòng "Gần đây tớ cũng đang khó khăn"\nXem xét liệu bạn có thể bày tỏ nhu cầu của mình trong mối quan hệ này không`,
      id: `Latih untuk mengatakan "Hari ini aku juga agak capek, nanti kita ngobrol lagi ya"\nJangan langsung merespons setiap pesan. Periksa kondisimu sendiri dulu\nSaat dia mencurahkan emosinya, coba katakan dengan jujur "Aku juga sedang sulit belakangan ini"\nPeriksa apakah kamu bisa mengungkapkan kebutuhanmu sendiri dalam hubungan ini`,
    },
    declaration: {
      ko: `내 감정도 소중합니다. 일방적인 감정 소비를 멈추겠습니다 💧`,
      en: `My emotions matter too. I will stop the one-sided emotional drain 💧`,
      ja: `私の感情も大切です。一方的な感情消費を止めます 💧`,
      'zh-CN': `我的情绪也很重要，我会停止这种单方面的情绪消耗 💧`,
      'zh-TW': `我的情緒也很重要，我會停止這種單方面的情緒消耗 💧`,
      vi: `Cảm xúc của tôi cũng quan trọng. Tôi sẽ ngừng việc tiêu hao cảm xúc một chiều này 💧`,
      id: `Emosiku juga berharga. Aku akan menghentikan pengorbanan emosi yang sepihak ini 💧`,
    },
    shareMessage: {
      ko: `거리둬야 할 인맥 진단: 감정 착취 인맥 보유형 💧 내가 고민 털어놓으러 갔다가 내가 들어주고 오는 사람... 이래서 피곤했구나 → 친구 태그해봐`,
      en: `Toxic Network Diagnosis: Emotional Vampire Network Holder 💧 Someone I go to vent to, but end up listening to their problems instead... no wonder I've been so tired → Tag a friend`,
      ja: `距離を置くべき人脈診断：感情搾取人脈保有型 💧 悩みを話しに行ったのに結局私が聞いて帰ってくる人...だから疲れてたんだ → 友達をタグ付けしてみて`,
      'zh-CN': `该远离的人脉诊断：情感剥削型人脉持有者 💧 本来是我去诉苦，结果变成我在听对方倾诉...原来这就是为什么会这么累 → 快去标记朋友试试吧`,
      'zh-TW': `該遠離的人脈診斷：情感剝削型人脈持有者 💧 本來是我去訴苦，結果變成我在聽對方傾訴...原來這就是為什麼會這麼累 → 快去標記朋友試試吧`,
      vi: `Chẩn đoán mối quan hệ cần tránh xa: Kiểu Sở Hữu Ma Cà Rồng Cảm Xúc 💧 Định đi tâm sự nhưng cuối cùng lại thành người lắng nghe họ... hóa ra vì vậy mà mình mệt → Tag bạn bè thử xem`,
      id: `Diagnosis Lingkaran Pertemanan yang Perlu Dijauhi: Tipe Vampir Emosional 💧 Niatnya curhat, tapi ujung-ujungnya aku yang mendengarkan curhatannya... pantas saja aku selalu lelah → Coba tag temanmu`,
    },
  },
  {
    type: 'Type4',
    emoji: '⚠️',
    title: {
      ko: `은근히 깎아내리는 사람이 있는, 비교·독성형 인맥 보유형`,
      en: `There's Someone Who Subtly Puts You Down, Comparison & Toxic Put-Down Type`,
      ja: `こっそり見下す人がいる、比較・毒性型人脈保有型`,
      'zh-CN': `有一个暗中贬低你的人，比较·毒性打压型`,
      'zh-TW': `有一個暗中貶低你的人，比較・毒性打壓型`,
      vi: `Có Người Ngầm Hạ Thấp Bạn, Kiểu So Sánh & Dìm Hàng Độc Hại`,
      id: `Ada Orang yang Diam-diam Meremehkanmu, Tipe Perbandingan & Sindiran Toksik`,
    },
    shortDescription: {
      ko: `진단 결과: 나를 은근히 비교하거나 깎아내리는 사람이 있습니다`,
      en: `Diagnosis: There's someone who subtly compares you to others or puts you down.`,
      ja: `診断結果：私をこっそり比較したり見下したりする人がいます`,
      'zh-CN': `诊断结果：有一个人会暗中拿你比较或贬低你`,
      'zh-TW': `診斷結果：有一個人會暗中拿你比較或貶低你`,
      vi: `Kết quả chẩn đoán: Có một người ngầm so sánh hoặc hạ thấp bạn`,
      id: `Hasil diagnosis: Ada seseorang yang diam-diam membandingkan atau meremehkanmu`,
    },
    description: {
      ko: `잘 됐다고 하면 어딘가 불편해하거나 칭찬인 척 깎아내리는 말을 하는 사람. 처음엔 내가 예민한 줄 알았는데 패턴이 반복됩니다.\n\n이 유형은 의도적으로 나쁜 사람이 아닐 수도 있습니다. 하지만 이 관계에 지속적으로 노출되면 나도 모르게 자존감이 낮아지는 영향을 받습니다. 지금보다 거리를 늘리는 것이 필요합니다.`,
      en: `Someone who seems uncomfortable when things go well for you, or disguises a put-down as a compliment. At first you thought you were just being sensitive, but the pattern keeps repeating.\n\nThis type may not be intentionally malicious. But continued exposure to this relationship can gradually erode your self-esteem without you noticing. It's necessary to create more distance than you currently have.`,
      ja: `うまくいったと言うとどこか不快そうにしたり、褒めているようで実は見下す発言をする人。最初は自分が敏感なのかと思ったけどパターンが繰り返されます。\n\nこのタイプは意図的に悪い人ではないかもしれません。でもこの関係に持続的にさらされると自分でも気づかないうちに自尊心が下がる影響を受けます。今より距離を広げることが必要です。`,
      'zh-CN': `当我说事情进展顺利时，他会露出不自在的表情，或用貌似赞美的方式贬低我。一开始我以为是自己太敏感，但这种模式一再重复出现。\n\n这类型的人未必是故意使坏，但长期暴露在这种关系中，会不知不觉降低你的自尊。现在需要拉大与他之间的距离。`,
      'zh-TW': `當我說事情進展順利時，他會露出不自在的表情，或用貌似讚美的方式貶低我。一開始我以為是自己太敏感，但這種模式一再重複出現。\n\n這類型的人未必是故意使壞，但長期暴露在這種關係中，會不知不覺降低你的自尊。現在需要拉大與他之間的距離。`,
      vi: `Người khi nghe tôi kể chuyện tốt lại tỏ ra khó chịu, hoặc nói lời dìm hàng nhưng núp dưới danh nghĩa khen ngợi. Ban đầu tôi nghĩ mình quá nhạy cảm, nhưng kiểu này cứ lặp lại.\n\nKiểu người này chưa chắc cố ý xấu. Nhưng nếu tiếp tục tiếp xúc với mối quan hệ này, bạn sẽ vô thức bị giảm tự tin. Bây giờ cần phải tăng khoảng cách hơn nữa.`,
      id: `Orang yang terlihat tidak nyaman saat mendengar kabar baikku, atau menyamarkan sindiran sebagai pujian. Awalnya kukira aku hanya terlalu sensitif, tapi pola ini terus berulang.\n\nTipe ini mungkin tidak sengaja bermaksud jahat. Namun terus-menerus terpapar hubungan ini bisa perlahan menurunkan rasa percaya dirimu tanpa disadari. Kamu perlu menambah jarak lebih dari sekarang.`,
    },
    diagnosisType: {
      ko: `비교·독성형 인맥 보유형 ⚠️`,
      en: `Comparison & Toxic Put-Down Type ⚠️`,
      ja: `比較・毒性型人脈保有型 ⚠️`,
      'zh-CN': `比较·毒性打压型 ⚠️`,
      'zh-TW': `比較・毒性打壓型 ⚠️`,
      vi: `Kiểu So Sánh & Dìm Hàng Độc Hại ⚠️`,
      id: `Tipe Perbandingan & Sindiran Toksik ⚠️`,
    },
    keyTraits: {
      ko: `깎아내리기, 은근한 비교, 성취 불편함, 칭찬 뒤 한마디`,
      en: `Putting you down, subtle comparisons, discomfort with your success, a jab after every compliment`,
      ja: `見下し、こっそり比較、成果への不快感、褒め言葉の後の一言`,
      'zh-CN': `贬低他人，暗中比较，对成就感到不适，赞美之后再补一句`,
      'zh-TW': `貶低他人，暗中比較，對成就感到不適，讚美之後再補一句`,
      vi: `Dìm hàng, so sánh ngầm, khó chịu trước thành công, kèm một câu sau lời khen`,
      id: `Meremehkan, perbandingan tersembunyi, tidak nyaman dengan pencapaianmu, sindiran setelah pujian`,
    },
    strategy: {
      ko: `이 사람에게 성취나 기쁜 일을 먼저 공유하지 않기\n깎아내리는 말이 나왔을 때 "그렇게 생각하는구나"로 흘리기 연습\n이 사람과 보내는 시간을 점진적으로 줄이기\n나를 진심으로 응원해주는 사람과의 시간을 늘리기`,
      en: `Don't be the first to share your achievements or good news with this person\nWhen a put-down comes up, practice letting it slide with something like "I guess that's how you see it"\nGradually reduce the time you spend with this person\nSpend more time with people who genuinely support you`,
      ja: `この人に成果や嬉しいことを最初に共有しない\n見下す言葉が出たとき「そう思うんだね」で流す練習\nこの人と過ごす時間を徐々に減らす\n私を心から応援してくれる人との時間を増やす`,
      'zh-CN': `不要第一个把成就或喜事分享给这个人\n当对方说出贬低的话时，练习用"你是这么想的啊"这类话轻轻带过\n逐渐减少和这个人相处的时间\n增加和真心支持你的人相处的时间`,
      'zh-TW': `不要第一個把成就或喜事分享給這個人\n當對方說出貶低的話時，練習用「你是這麼想的啊」這類話輕輕帶過\n逐漸減少和這個人相處的時間\n增加和真心支持你的人相處的時間`,
      vi: `Không chia sẻ thành tích hay tin vui với người này trước tiên\nKhi họ nói lời dìm hàng, hãy tập cách cho qua bằng câu "Bạn nghĩ vậy à"\nGiảm dần thời gian dành cho người này\nTăng thời gian ở cạnh những người thật lòng ủng hộ bạn`,
      id: `Jangan menjadi orang pertama yang membagikan pencapaian atau kabar baik kepadanya\nSaat sindiran muncul, latih untuk membiarkannya lewat dengan kalimat seperti "Oh, begitu ya menurutmu"\nSecara bertahap kurangi waktu yang dihabiskan dengan orang ini\nPerbanyak waktu dengan orang yang benar-benar mendukungmu`,
    },
    declaration: {
      ko: `나를 깎아내리는 관계로부터 나를 지키겠습니다 ⚠️`,
      en: `I will protect myself from relationships that put me down ⚠️`,
      ja: `私を見下す関係から自分を守ります ⚠️`,
      'zh-CN': `我会保护自己远离贬低我的关系 ⚠️`,
      'zh-TW': `我會保護自己遠離貶低我的關係 ⚠️`,
      vi: `Tôi sẽ bảo vệ bản thân khỏi những mối quan hệ hạ thấp mình ⚠️`,
      id: `Aku akan melindungi diriku dari hubungan yang meremehkanku ⚠️`,
    },
    shareMessage: {
      ko: `거리둬야 할 인맥 진단: 비교·독성형 인맥 보유형 ⚠️ 잘 됐다고 했더니 묘하게 불편해하는 사람... 이거 내가 예민한 게 아니었음 → 친구 태그해봐`,
      en: `Toxic Network Diagnosis: Comparison & Toxic Put-Down Type ⚠️ Told them something went well and they got weirdly uncomfortable... turns out I wasn't being oversensitive → Tag a friend`,
      ja: `距離を置くべき人脈診断：比較・毒性型人脈保有型 ⚠️ うまくいったと言ったら妙に不快そうにする人...私が敏感だったわけじゃなかった → 友達をタグ付けしてみて`,
      'zh-CN': `该远离的人脉诊断：比较·毒性打压型 ⚠️ 说了好消息对方却露出诡异的不适感...原来不是我太敏感 → 快去标记朋友试试吧`,
      'zh-TW': `該遠離的人脈診斷：比較・毒性打壓型 ⚠️ 說了好消息對方卻露出詭異的不適感...原來不是我太敏感 → 快去標記朋友試試吧`,
      vi: `Chẩn đoán mối quan hệ cần tránh xa: Kiểu So Sánh & Dìm Hàng Độc Hại ⚠️ Kể chuyện tốt mà họ tỏ ra khó chịu kỳ lạ... hóa ra không phải mình nhạy cảm → Tag bạn bè thử xem`,
      id: `Diagnosis Lingkaran Pertemanan yang Perlu Dijauhi: Tipe Sindiran Toksik ⚠️ Cerita kabar baik tapi dia malah terlihat tidak nyaman... ternyata bukan aku yang terlalu sensitif → Coba tag temanmu`,
    },
  },
  {
    type: 'Type5',
    emoji: '🚨',
    title: {
      ko: `신뢰를 배신한 사람이 있는, 뒷담화·배신형 인맥 보유형`,
      en: `There's Someone Who Betrayed Your Trust, Gossip & Betrayal Type`,
      ja: `信頼を裏切った人がいる、陰口・裏切り型人脈保有型`,
      'zh-CN': `有一个背叛你信任的人，八卦·背叛型`,
      'zh-TW': `有一個背叛你信任的人，八卦・背叛型`,
      vi: `Có Người Phản Bội Niềm Tin Của Bạn, Kiểu Nói Xấu & Phản Bội`,
      id: `Ada Orang yang Mengkhianati Kepercayaanmu, Tipe Gosip & Pengkhianatan`,
    },
    shortDescription: {
      ko: `진단 결과: 내 이야기를 흘리거나 뒤에서 다른 말을 한 사람이 있습니다`,
      en: `Diagnosis: There's someone who leaked your story or said different things behind your back.`,
      ja: `診断結果：私の話を漏らしたり陰で違うことを言っている人がいます`,
      'zh-CN': `诊断结果：有一个人泄露过你的事，或在背后说了不一样的话`,
      'zh-TW': `診斷結果：有一個人洩露過你的事，或在背後說了不一樣的話`,
      vi: `Kết quả chẩn đoán: Có một người đã làm lộ chuyện của bạn hoặc nói khác đi ở phía sau`,
      id: `Hasil diagnosis: Ada seseorang yang membocorkan ceritamu atau berbicara berbeda di belakangmu`,
    },
    description: {
      ko: `내가 털어놓은 이야기가 다른 경로로 돌아오거나 없을 때 내 뒷담화를 한다는 걸 알게 됐습니다. 그런데 그 사람은 여전히 내 앞에서 친한 척합니다.\n\n신뢰는 한 번 깨지면 회복이 매우 어렵습니다. 이 유형과의 관계 지속은 내 개인 정보와 감정이 계속 노출되는 것을 의미합니다. 거리두기를 넘어 관계 재설정이 필요한 단계입니다.`,
      en: `The story you confided in them came back to you through another route, or you found out they talk behind your back when you're not around. And yet they still act close to you to your face.\n\nOnce trust is broken, it's very hard to rebuild. Continuing this relationship means your personal information and feelings keep being exposed. This calls for more than just distance — it's a stage where you need to reset the relationship entirely.`,
      ja: `私が打ち明けた話が別の経路で戻ってきたり、いないときに私の陰口を言っていることを知りました。それでもその人は私の前では相変わらず親しいふりをします。\n\n信頼は一度崩れると回復が非常に難しいです。このタイプとの関係を続けることは私の個人情報や感情がずっと露出することを意味します。距離を置くこと以上に、関係の再設定が必要な段階です。`,
      'zh-CN': `我曾私下透露的事情，后来从别的渠道传回给我；或者得知在我不在场时，那个人会说我的坏话。可是那个人在我面前依然装作很亲密。\n\n信任一旦破裂，就很难修复。继续维持和这种类型的人的关系，意味着我的隐私和情绪会不断地被暴露。这已经不只是保持距离，而是需要重新审视这段关系的阶段。`,
      'zh-TW': `我曾私下透露的事情，後來從別的渠道傳回給我；或者得知在我不在場時，那個人會說我的壞話。可是那個人在我面前依然裝作很親密。\n\n信任一旦破裂，就很難修復。繼續維持和這種類型的人的關係，意味著我的隱私和情緒會不斷地被暴露。這已經不只是保持距離，而是需要重新審視這段關係的階段。`,
      vi: `Câu chuyện tôi tâm sự đã quay lại với tôi qua một con đường khác, hoặc tôi biết được rằng lúc tôi không có mặt, họ đã nói xấu tôi. Nhưng người đó vẫn tỏ ra thân thiết trước mặt tôi.\n\nNiềm tin một khi đã đổ vỡ thì rất khó hồi phục. Việc tiếp tục mối quan hệ với kiểu người này đồng nghĩa với việc thông tin cá nhân và cảm xúc của tôi tiếp tục bị phơi bày. Đây là giai đoạn cần vượt qua việc giữ khoảng cách, cần thiết lập lại mối quan hệ.`,
      id: `Cerita yang aku curahkan kembali padaku melalui jalur lain, atau aku tahu bahwa dia menjelekkanku di belakang saat aku tidak ada. Namun orang itu tetap berpura-pura akrab di depanku.\n\nKepercayaan yang sekali retak sangat sulit dipulihkan. Melanjutkan hubungan dengan tipe ini berarti informasi pribadi dan perasaanku terus terekspos. Ini adalah tahap di mana kamu perlu lebih dari sekadar menjaga jarak — kamu perlu menata ulang hubungan itu.`,
    },
    diagnosisType: {
      ko: `뒷담화·배신형 인맥 보유형 🚨`,
      en: `Gossip & Betrayal Type 🚨`,
      ja: `陰口・裏切り型人脈保有型 🚨`,
      'zh-CN': `八卦·背叛型 🚨`,
      'zh-TW': `八卦・背叛型 🚨`,
      vi: `Kiểu Nói Xấu & Phản Bội 🚨`,
      id: `Tipe Gosip & Pengkhianatan 🚨`,
    },
    keyTraits: {
      ko: `비밀 유출, 뒷담화, 이중적 태도, 신뢰 파괴`,
      en: `Leaking secrets, gossiping, two-faced behavior, breaking trust`,
      ja: `秘密の漏洩、陰口、二重の態度、信頼の破壊`,
      'zh-CN': `泄露秘密，说人坏话，表里不一，破坏信任`,
      'zh-TW': `洩露秘密，說人壞話，表裡不一，破壞信任`,
      vi: `Làm lộ bí mật, nói xấu, hai mặt, phá vỡ niềm tin`,
      id: `Membocorkan rahasia, bergosip, sikap dua muka, merusak kepercayaan`,
    },
    strategy: {
      ko: `이 사람에게 더 이상 개인적인 이야기를 하지 않기. 대화 수위 낮추기\n친한 척하는 것에 맞춰줄 필요 없음. 의무적으로 가까이 지낼 이유 없음\n이 사람이 하는 이야기의 사실 여부를 그대로 믿지 않기\n이 관계에서 나의 에너지를 더 이상 투자하지 않기`,
      en: `Stop sharing personal stories with this person. Lower the level of your conversations\nYou don't need to play along with their pretend closeness. There's no obligation to stay close\nDon't take what this person says at face value\nStop investing your energy in this relationship`,
      ja: `この人にこれ以上個人的な話をしない。会話のレベルを下げる\n親しいふりに合わせる必要はない。義務的に親しくする理由はない\nこの人が言うことの事実かどうかをそのまま信じない\nこの関係に自分のエネルギーをこれ以上投資しない`,
      'zh-CN': `不要再对这个人透露任何私事，降低谈话的深度\n不必配合对方装亲密，没有义务勉强保持亲近\n不要轻信这个人所说的话是否属实\n不再为这段关系投入自己的能量`,
      'zh-TW': `不要再對這個人透露任何私事，降低談話的深度\n不必配合對方裝親密，沒有義務勉強保持親近\n不要輕信這個人所說的話是否屬實\n不再為這段關係投入自己的能量`,
      vi: `Không kể chuyện riêng tư với người này nữa. Hạ mức độ trò chuyện xuống\nKhông cần chiều theo sự thân thiết giả tạo của họ. Không có nghĩa vụ phải gần gũi\nKhông tin ngay những gì người này nói là sự thật\nKhông đầu tư năng lượng của mình vào mối quan hệ này nữa`,
      id: `Berhenti membagikan cerita pribadi dengan orang ini. Turunkan level pembicaraan\nTidak perlu mengikuti keakraban palsunya. Tidak ada kewajiban untuk tetap dekat\nJangan langsung percaya kebenaran dari apa yang dikatakan orang ini\nBerhenti menginvestasikan energimu pada hubungan ini`,
    },
    declaration: {
      ko: `내 이야기를 흘리는 사람에게 더 이상 나를 열지 않겠습니다 🚨`,
      en: `I will no longer open up to someone who leaks my stories 🚨`,
      ja: `私の話を漏らす人にこれ以上心を開きません 🚨`,
      'zh-CN': `我不会再对泄露我隐私的人敞开心扉 🚨`,
      'zh-TW': `我不會再對洩露我隱私的人敞開心扉 🚨`,
      vi: `Tôi sẽ không còn mở lòng với người làm lộ chuyện của tôi nữa 🚨`,
      id: `Aku tidak akan lagi membuka diri pada orang yang membocorkan ceritaku 🚨`,
    },
    shareMessage: {
      ko: `거리둬야 할 인맥 진단: 뒷담화·배신형 인맥 보유형 🚨 내 이야기 흘린 사람 있다는 거... 그 사람 떠올랐다면 거리두기 시작할 때 → 친구 태그해봐`,
      en: `Toxic Network Diagnosis: Gossip & Betrayal Type 🚨 Turns out someone leaked my stories... if a person just came to mind, it's time to start distancing → Tag a friend`,
      ja: `距離を置くべき人脈診断：陰口・裏切り型人脈保有型 🚨 私の話を漏らした人がいるということ...その人が思い浮かんだなら距離を置き始める時 → 友達をタグ付けしてみて`,
      'zh-CN': `该远离的人脉诊断：八卦·背叛型 🚨 竟然有人泄露过我的事...如果你脑中浮现出那个人，就是该开始保持距离的时候了 → 快去标记朋友试试吧`,
      'zh-TW': `該遠離的人脈診斷：八卦・背叛型 🚨 竟然有人洩露過我的事...如果你腦中浮現出那個人，就是該開始保持距離的時候了 → 快去標記朋友試試吧`,
      vi: `Chẩn đoán mối quan hệ cần tránh xa: Kiểu Nói Xấu & Phản Bội 🚨 Hóa ra có người đã làm lộ chuyện của mình... nếu bạn vừa nghĩ đến ai đó thì đã đến lúc bắt đầu giữ khoảng cách → Tag bạn bè thử xem`,
      id: `Diagnosis Lingkaran Pertemanan yang Perlu Dijauhi: Tipe Gosip & Pengkhianatan 🚨 Ternyata ada yang membocorkan ceritaku... kalau ada orang yang terlintas, saatnya mulai menjaga jarak → Coba tag temanmu`,
    },
  },
  {
    type: 'Type6',
    emoji: '🆘',
    title: {
      ko: `관계 자체가 위험한, 나르시시스트·가스라이팅형 인맥 보유형`,
      en: `A Relationship That's Dangerous Itself, Narcissist & Gaslighting Type`,
      ja: `関係自体が危険な、ナルシシスト・ガスライティング型人脈保有型`,
      'zh-CN': `关系本身就很危险，自恋・煤气灯操纵型`,
      'zh-TW': `關係本身就很危險，自戀・煤氣燈操縱型`,
      vi: `Mối Quan Hệ Bản Thân Đã Nguy Hiểm, Kiểu Ái Kỷ & Thao Túng Tâm Lý`,
      id: `Hubungan Itu Sendiri Berbahaya, Tipe Narsis & Gaslighting`,
    },
    shortDescription: {
      ko: `진단 결과: 이 관계에서 나는 지속적으로 혼란스럽고 소모되고 있습니다`,
      en: `Diagnosis: In this relationship, you're constantly confused and worn down.`,
      ja: `診断結果：この関係で私は継続的に混乱し消耗しています`,
      'zh-CN': `诊断结果：在这段关系中，你一直感到困惑和被消耗`,
      'zh-TW': `診斷結果：在這段關係中，你一直感到困惑和被消耗`,
      vi: `Kết quả chẩn đoán: Trong mối quan hệ này, bạn liên tục cảm thấy hoang mang và bị bào mòn`,
      id: `Hasil diagnosis: Dalam hubungan ini, kamu terus-menerus merasa bingung dan terkuras`,
    },
    description: {
      ko: `잘못된 건 항상 나인 것 같고 내가 예민한 건가 싶고 그 사람과 있으면 내가 점점 작아지는 느낌이 듭니다. 이건 나의 착각이 아닙니다.\n\n이 패턴은 단순한 불편한 인간관계를 넘어선 수준입니다. 자신의 잘못을 절대 인정하지 않고 상황을 당신 탓으로 돌리고 당신의 현실 인식을 흔드는 행동이 반복된다면 이것은 지금 당장 거리두기가 필요한 관계입니다.`,
      en: `It always feels like you're the one in the wrong, you wonder if you're just being too sensitive, and being around them makes you feel like you're shrinking. This is not your imagination.\n\nThis pattern goes beyond just an uncomfortable relationship. If they never admit fault, keep blaming situations on you, and repeatedly shake your grip on reality, this is a relationship that needs distance right now.`,
      ja: `いつも間違っているのは私のような気がして、私が敏感なのかと思い、その人と一緒にいると自分がどんどん小さくなる感じがします。これは私の思い違いではありません。\n\nこのパターンは単なる居心地の悪い人間関係を超えたレベルです。自分の過ちを絶対に認めず、状況をあなたのせいにし、あなたの現実認識を揺るがす行動が繰り返されるなら、これは今すぐ距離を置く必要がある関係です。`,
      'zh-CN': `总感觉出错的永远是我，怀疑自己是不是太敏感，和那个人在一起时会觉得自己越来越渺小。这不是我的错觉。\n\n这种模式已经超出了单纯令人不适的人际关系范畴。如果对方绝不承认自己的错误、总把情况怪到你头上，并反复动摇你对现实的判断，那么这是一段现在就需要立刻远离的关系。`,
      'zh-TW': `總感覺出錯的永遠是我，懷疑自己是不是太敏感，和那個人在一起時會覺得自己越來越渺小。這不是我的錯覺。\n\n這種模式已經超出了單純令人不適的人際關係範疇。如果對方絕不承認自己的錯誤、總把情況怪到你頭上，並反覆動搖你對現實的判斷，那麼這是一段現在就需要立刻遠離的關係。`,
      vi: `Cảm giác lỗi luôn thuộc về mình, tự hỏi liệu mình có quá nhạy cảm không, và khi ở cạnh người đó, bản thân dần trở nên nhỏ bé. Đây không phải là ảo tưởng của bạn.\n\nKiểu này đã vượt xa một mối quan hệ khó chịu thông thường. Nếu họ tuyệt đối không nhận lỗi, luôn đổ lỗi cho bạn, và liên tục làm lung lay nhận thức thực tế của bạn, đây là mối quan hệ cần được giữ khoảng cách ngay bây giờ.`,
      id: `Rasanya selalu akulah yang salah, aku bertanya-tanya apakah aku terlalu sensitif, dan berada di dekatnya membuatku merasa semakin kecil. Ini bukan khayalanmu.\n\nPola ini sudah melampaui sekadar hubungan yang tidak nyaman. Jika dia tidak pernah mengakui kesalahannya, selalu menyalahkanmu atas situasi, dan berulang kali mengguncang persepsimu tentang realita, ini adalah hubungan yang butuh jarak sekarang juga.`,
    },
    diagnosisType: {
      ko: `나르시시스트·가스라이팅형 인맥 보유형 🆘`,
      en: `Narcissist & Gaslighting Type 🆘`,
      ja: `ナルシシスト・ガスライティング型人脈保有型 🆘`,
      'zh-CN': `自恋・煤气灯操纵型 🆘`,
      'zh-TW': `自戀・煤氣燈操縱型 🆘`,
      vi: `Kiểu Ái Kỷ & Thao Túng Tâm Lý 🆘`,
      id: `Tipe Narsis & Gaslighting 🆘`,
    },
    keyTraits: {
      ko: `자기 잘못 미인정, 현실 왜곡, 약점 이용, 협박성 반응, 지속적 혼란감`,
      en: `Never admits fault, distorts reality, exploits your weaknesses, threatening reactions, constant confusion`,
      ja: `自己の過ちを認めない、現実の歪曲、弱点の利用、脅迫的な反応、継続的な混乱感`,
      'zh-CN': `不承认自己的错误，扭曲现实，利用弱点，威胁性反应，持续的困惑感`,
      'zh-TW': `不承認自己的錯誤，扭曲現實，利用弱點，威脅性反應，持續的困惑感`,
      vi: `Không nhận lỗi, bóp méo thực tế, lợi dụng điểm yếu, phản ứng mang tính đe dọa, cảm giác hoang mang liên tục`,
      id: `Tidak pernah mengakui kesalahan, memutarbalikkan realita, memanfaatkan kelemahan, reaksi mengancam, kebingungan yang terus-menerus`,
    },
    strategy: {
      ko: `이 관계를 점진적으로 축소하기. 갑작스러운 단절보다 서서히 줄이기\n이 사람의 말을 그대로 믿지 않기. 내 감각을 신뢰하기\n이 사람과의 대화를 가능한 한 짧게 유지하고 감정적으로 반응하지 않기\n신뢰할 수 있는 외부 사람과 이 관계에 대해 이야기해보기\n관계가 심각하게 느껴진다면 심리 전문가 상담을 고려하기`,
      en: `Gradually scale down this relationship. Ease off rather than cutting off abruptly\nDon't take what this person says at face value. Trust your own perception\nKeep conversations with this person as short as possible and avoid reacting emotionally\nTalk about this relationship with someone you trust outside of it\nIf the relationship feels serious, consider consulting a mental health professional`,
      ja: `この関係を段階的に縮小する。突然の断絶より徐々に減らす\nこの人の言葉をそのまま信じない。自分の感覚を信頼する\nこの人との会話を可能な限り短く保ち、感情的に反応しない\n信頼できる外部の人とこの関係について話してみる\n関係が深刻に感じられるなら心理専門家への相談を検討する`,
      'zh-CN': `逐步缩小这段关系，比起突然断绝，慢慢减少来往会更好\n不要轻信这个人所说的话，相信自己的感觉\n和这个人的对话尽量保持简短，不要有情绪化的反应\n找一个信任的外部人聊聊这段关系\n如果觉得这段关系已经很严重，考虑寻求心理专业人士的咨询`,
      'zh-TW': `逐步縮小這段關係，比起突然斷絕，慢慢減少來往會更好\n不要輕信這個人所說的話，相信自己的感覺\n和這個人的對話盡量保持簡短，不要有情緒化的反應\n找一個信任的外部人聊聊這段關係\n如果覺得這段關係已經很嚴重，考慮尋求心理專業人士的諮詢`,
      vi: `Giảm dần mối quan hệ này. Nên giảm từ từ thay vì cắt đứt đột ngột\nKhông tin ngay lời của người này. Hãy tin vào cảm nhận của chính mình\nGiữ các cuộc trò chuyện với người này càng ngắn càng tốt và không phản ứng theo cảm xúc\nHãy chia sẻ về mối quan hệ này với người bên ngoài mà bạn tin tưởng\nNếu cảm thấy mối quan hệ này nghiêm trọng, hãy xem xét tư vấn chuyên gia tâm lý`,
      id: `Kurangi hubungan ini secara bertahap. Lebih baik meredakan pelan-pelan daripada memutus secara tiba-tiba\nJangan langsung percaya kata-kata orang ini. Percayalah pada persepsimu sendiri\nJaga percakapan dengan orang ini seringkas mungkin dan jangan bereaksi secara emosional\nBicarakan tentang hubungan ini dengan orang luar yang kamu percaya\nJika hubungan ini terasa serius, pertimbangkan untuk berkonsultasi dengan ahli kesehatan mental`,
    },
    declaration: {
      ko: `나를 혼란스럽게 만드는 관계로부터 나를 지키겠습니다. 이것은 내 권리입니다 🆘`,
      en: `I will protect myself from relationships that confuse me. This is my right 🆘`,
      ja: `私を混乱させる関係から自分を守ります。これは私の権利です 🆘`,
      'zh-CN': `我会保护自己远离让我困惑的关系，这是我的权利 🆘`,
      'zh-TW': `我會保護自己遠離讓我困惑的關係，這是我的權利 🆘`,
      vi: `Tôi sẽ bảo vệ bản thân khỏi mối quan hệ khiến mình hoang mang. Đây là quyền của tôi 🆘`,
      id: `Aku akan melindungi diriku dari hubungan yang membuatku bingung. Ini adalah hakku 🆘`,
    },
    shareMessage: {
      ko: `거리둬야 할 인맥 진단: 나르시시스트형 인맥 보유형 🆘 이 관계에서 나를 지켜야 한다는 거... 힘든 게 내 잘못 아니었음 → 관계 리모델링 선언 시작`,
      en: `Toxic Network Diagnosis: Narcissist Type 🆘 I need to protect myself in this relationship... it turns out my struggle wasn't my fault → Starting a relationship reset declaration`,
      ja: `距離を置くべき人脈診断：ナルシシスト型人脈保有型 🆘 この関係で自分を守らなければならないということ...大変だったのは私のせいじゃなかった → 関係リモデリング宣言スタート`,
      'zh-CN': `该远离的人脉诊断：自恋型 🆘 原来在这段关系中我必须保护自己...这么辛苦并不是我的错 → 开始关系重塑宣言`,
      'zh-TW': `該遠離的人脈診斷：自戀型 🆘 原來在這段關係中我必須保護自己...這麼辛苦並不是我的錯 → 開始關係重塑宣言`,
      vi: `Chẩn đoán mối quan hệ cần tránh xa: Kiểu Ái Kỷ 🆘 Hóa ra tôi cần bảo vệ mình trong mối quan hệ này... sự khó khăn không phải lỗi của tôi → Bắt đầu tuyên bố cải tổ mối quan hệ`,
      id: `Diagnosis Lingkaran Pertemanan yang Perlu Dijauhi: Tipe Narsis 🆘 Ternyata aku harus melindungi diriku dalam hubungan ini... kesulitan ini bukan salahku → Mulai deklarasi menata ulang hubungan`,
    },
    encouragement: {
      ko: `이 관계에서 힘든 것은 당신의 약함이 아닙니다. 당신이 충분히 강하기 때문에 지금까지 버텨온 겁니다. 이제 나를 위한 선택을 해도 됩니다`,
      en: `Struggling in this relationship isn't a sign of your weakness. You've made it this far because you're strong enough to endure it. Now, it's okay to make a choice for yourself.`,
      ja: `この関係で辛いのはあなたの弱さではありません。あなたが十分に強いからこそ、今まで耐えてきたのです。これからは自分のための選択をしていいのです`,
      'zh-CN': `在这段关系中感到辛苦，并不代表你软弱。正是因为你足够坚强，才能一直撑到现在。现在，你可以为自己做出选择了`,
      'zh-TW': `在這段關係中感到辛苦，並不代表你軟弱。正是因為你足夠堅強，才能一直撐到現在。現在，你可以為自己做出選擇了`,
      vi: `Việc cảm thấy khó khăn trong mối quan hệ này không phải vì bạn yếu đuối. Chính vì bạn đủ mạnh mẽ nên mới có thể chịu đựng đến bây giờ. Giờ đây, bạn có thể lựa chọn vì chính mình`,
      id: `Merasa sulit dalam hubungan ini bukan tanda kelemahanmu. Kamu bisa bertahan sampai sekarang justru karena kamu cukup kuat. Sekarang, tidak apa-apa untuk membuat pilihan demi dirimu sendiri`,
    },
  },
];
