/** 나의 '경쟁심' DNA 분석 — phase3-competitive-dna · 12문항 4지선다 · A=0/B=1/C=2/D=3 · 7개 로케일 */

export type Phase3CompetitiveDnaLocaleKey = 'ko' | 'en' | 'ja' | 'zh-CN' | 'zh-TW' | 'vi' | 'id';

function localeMap(t: Record<Phase3CompetitiveDnaLocaleKey, string>): Record<Phase3CompetitiveDnaLocaleKey, string> {
  return t;
}

function opt(m: Record<Phase3CompetitiveDnaLocaleKey, string>, score: number): { text: Record<Phase3CompetitiveDnaLocaleKey, string>; score: number } {
  return { text: localeMap(m), score };
}

export interface Phase3CompetitiveDnaQuestion {
  id: number;
  question: Record<Phase3CompetitiveDnaLocaleKey, string>;
  options: { text: Record<Phase3CompetitiveDnaLocaleKey, string>; score: number }[];
}

export interface Phase3CompetitiveDnaResult {
  type: string;
  emoji: string;
  title: Record<Phase3CompetitiveDnaLocaleKey, string>;
  competitiveDna: Record<Phase3CompetitiveDnaLocaleKey, string>;
  quote: Record<Phase3CompetitiveDnaLocaleKey, string>;
  description: Record<Phase3CompetitiveDnaLocaleKey, string>;
  competitiveType: Record<Phase3CompetitiveDnaLocaleKey, string>;
  competitiveKeywords: Record<Phase3CompetitiveDnaLocaleKey, string>;
  strengths: Record<Phase3CompetitiveDnaLocaleKey, string>;
  cautions: Record<Phase3CompetitiveDnaLocaleKey, string>;
  bestEnvironments: Record<Phase3CompetitiveDnaLocaleKey, string>;
  sportsGameTypes: Record<Phase3CompetitiveDnaLocaleKey, string>;
  certificationPhrase: Record<Phase3CompetitiveDnaLocaleKey, string>;
  oneLiner: Record<Phase3CompetitiveDnaLocaleKey, string>;
  shareLine: Record<Phase3CompetitiveDnaLocaleKey, string>;
}

export function calculatePhase3CompetitiveDnaResult(answers: number[]): string {
  const total = answers.reduce((sum, s) => sum + (s ?? 0), 0);
  if (total <= 5) return 'Type1';
  if (total <= 11) return 'Type2';
  if (total <= 19) return 'Type3';
  if (total <= 27) return 'Type4';
  if (total <= 33) return 'Type5';
  return 'Type6';
}

export function calculatePhase3CompetitiveDnaDomainScores(answers: number[]) {
  const reaction = (answers[0] ?? 0) + (answers[1] ?? 0);
  const winLoss = (answers[2] ?? 0) + (answers[3] ?? 0);
  const motivation = (answers[4] ?? 0) + (answers[5] ?? 0);
  const comparison = (answers[6] ?? 0) + (answers[7] ?? 0);
  const strategy = (answers[8] ?? 0) + (answers[9] ?? 0);
  const lifeImpact = (answers[10] ?? 0) + (answers[11] ?? 0);
  return {
    reaction,
    winLoss,
    motivation,
    comparison,
    strategy,
    lifeImpact,
    total: answers.reduce((sum, s) => sum + (s ?? 0), 0),
  };
}

export const phase3CompetitiveDnaQuestions: Phase3CompetitiveDnaQuestion[] = [
  {
    id: 1,
    question: localeMap({
      ko: '누군가와 게임·스포츠·내기를 하게 됐다. 시작 직전 나는?',
      en: 'You are about to play a game, sport, or bet with someone. Right before it starts, you:',
      ja: '誰かとゲーム・スポーツ・賭けをすることになった。開始直前のあなたは？',
      'zh-CN': '你即将和别人进行游戏、运动或打赌。开始前一刻，你会？',
      'zh-TW': '你即將和別人進行遊戲、運動或打賭。開始前一刻，你會？',
      vi: 'Bạn sắp chơi game, thể thao hoặc cá cược với ai đó. Ngay trước khi bắt đầu, bạn:',
      id: 'Kamu akan main game, olahraga, atau taruhan dengan seseorang. Tepat sebelum mulai, kamu:',
    }),
    options: [
      opt(localeMap({
        ko: '별로 긴장되지 않는다. 어떻게 되든 상관없다는 마음이 더 크다',
        en: 'Do not feel very tense. I care more about whatever happens than winning',
        ja: 'あまり緊張しない。結果よりどうでもいいという気持ちの方が大きい',
        'zh-CN': '不太紧张，更在意结果怎样都行',
        'zh-TW': '不太緊張，更在意結果怎樣都行',
        vi: 'Không căng lắm. Tôi quan tâm việc thế nào cũng được hơn là thắng',
        id: 'Tidak terlalu tegang. Yang penting hasilnya bagaimana saja, bukan menang',
    }), 0),
      opt(localeMap({
        ko: '재밌겠다는 생각이 든다. 이기면 좋고 져도 즐기면 된다',
        en: 'Think it will be fun. Winning is nice, but enjoying it is enough',
        ja: '楽しそうと思う。勝てればいいが、楽しめれば十分',
        'zh-CN': '觉得会很好玩，赢了更好，输了玩得开心就行',
        'zh-TW': '覺得會很好玩，贏了更好，輸了玩得開心就行',
        vi: 'Nghĩ sẽ vui. Thắng thì tốt, thua cũng được miễn vui',
        id: 'Pikir akan seru. Menang bagus, tapi asal enjoy sudah cukup',
    }), 1),
      opt(localeMap({
        ko: '이기고 싶다는 마음이 생긴다. 질 수도 있지만 최선을 다하겠다는 각오가 선다',
        en: 'Feel like I want to win. I might lose, but I am ready to give my best',
        ja: '勝ちたい気持ちが湧く。負けるかもしれないが最善を尽くす覚悟ができる',
        'zh-CN': '想赢的心起来了，可能会输但会全力以赴',
        'zh-TW': '想贏的心起來了，可能會輸但會全力以赴',
        vi: 'Muốn thắng. Có thể thua nhưng sẵn sàng cố hết sức',
        id: 'Ingin menang. Bisa kalah tapi siap memberikan yang terbaik',
    }), 2),
      opt(localeMap({
        ko: '반드시 이겨야겠다는 생각이 강하게 든다. 지는 것은 처음부터 선택지에 없다',
        en: 'Strongly feel I must win. Losing was never an option from the start',
        ja: '必ず勝たなければという気持ちが強い。負ける選択肢は最初からない',
        'zh-CN': '强烈觉得必须赢，从一开始就不接受输',
        'zh-TW': '強烈覺得必須贏，從一開始就不接受輸',
        vi: 'Cảm giác phải thắng rất mạnh. Thua ngay từ đầu không phải lựa chọn',
        id: 'Sangat merasa harus menang. Kalah bukan pilihan sejak awal',
    }), 3),
    ],
  },
  {
    id: 2,
    question: localeMap({
      ko: '경쟁하는 상황이 갑자기 생겼다. 내 몸의 반응은?',
      en: 'A competitive situation suddenly arises. How does your body react?',
      ja: '競争する状況が突然生まれた。あなたの体の反応は？',
      'zh-CN': '竞争情况突然出现，你的身体反应是？',
      'zh-TW': '競爭情況突然出現，你的身體反應是？',
      vi: 'Tình huống cạnh tranh đột ngột xuất hiện. Cơ thể bạn phản ứng thế nào?',
      id: 'Situasi kompetitif tiba-tiba muncul. Reaksi tubuhmu?',
    }),
    options: [
      opt(localeMap({
        ko: '특별한 변화가 없다. 경쟁이든 아니든 비슷하다',
        en: 'No special change. It feels about the same whether it is competition or not',
        ja: '特別な変化はない。競争でもそうでなくても同じ',
        'zh-CN': '没有特别变化，竞争与否差不多',
        'zh-TW': '沒有特別變化，競爭與否差不多',
        vi: 'Không có thay đổi đặc biệt. Cạnh tranh hay không đều giống nhau',
        id: 'Tidak ada perubahan khusus. Sama saja kompetitif atau tidak',
    }), 0),
      opt(localeMap({
        ko: '약간 설레거나 흥미가 생기는 정도다',
        en: 'A little excited or interested',
        ja: '少しワクワクしたり興味が湧く程度',
        'zh-CN': '有点兴奋或感兴趣',
        'zh-TW': '有點興奮或感興趣',
        vi: 'Hơi hồi hộp hoặc thấy hứng thú một chút',
        id: 'Sedikit excited atau tertarik',
    }), 1),
      opt(localeMap({
        ko: '집중력이 올라가고 심박수가 빨라지는 게 느껴진다',
        en: 'Focus rises and I feel my heart rate speed up',
        ja: '集中力が上がり、心拍数が速くなるのを感じる',
        'zh-CN': '专注力上升，感觉心跳加快',
        'zh-TW': '專注力上升，感覺心跳加快',
        vi: 'Tập trung tăng và cảm thấy nhịp tim nhanh hơn',
        id: 'Fokus naik dan merasa detak jantung mempercepat',
    }), 2),
      opt(localeMap({
        ko: '아드레날린이 솟는 느낌이다. 몸이 먼저 반응한다. 이 느낌이 좋다',
        en: 'Adrenaline kicks in. My body reacts first. I like this feeling',
        ja: 'アドレナリンが湧く。体が先に反応する。この感覚が好き',
        'zh-CN': '肾上腺素涌上来，身体先反应，我喜欢这种感觉',
        'zh-TW': '腎上腺素湧上來，身體先反應，我喜歡這種感覺',
        vi: 'Adrenaline trào lên. Cơ thể phản ứng trước. Tôi thích cảm giác này',
        id: 'Adrenalin naik. Tubuh bereaksi duluan. Saya suka perasaan ini',
    }), 3),
    ],
  },
  {
    id: 3,
    question: localeMap({
      ko: '열심히 준비한 경쟁에서 졌다. 나는?',
      en: 'You lost a competition you prepared hard for. You:',
      ja: '一生懸命準備した競争で負けた。あなたは？',
      'zh-CN': '你认真准备的竞争输了，你会？',
      'zh-TW': '你認真準備的競爭輸了，你會？',
      vi: 'Bạn thua một cuộc cạnh tranh đã chuẩn bị kỹ. Bạn:',
      id: 'Kamu kalah dalam kompetisi yang sudah dipersiapkan matang. Kamu:',
    }),
    options: [
      opt(localeMap({
        ko: '아쉽지만 금방 털어낸다. 결과보다 과정이 중요하다고 생각한다',
        en: 'Feel a bit sorry but shake it off quickly. The process matters more than the result',
        ja: '少し残念だがすぐ切り替える。結果より過程が大切',
        'zh-CN': '有点遗憾但很快放下，过程比结果重要',
        'zh-TW': '有點遺憾但很快放下，過程比結果重要',
        vi: 'Hơi tiếc nhưng nhanh chóng gác lại. Quá trình quan trọng hơn kết quả',
        id: 'Sedikit menyesal tapi cepat move on. Proses lebih penting dari hasil',
    }), 0),
      opt(localeMap({
        ko: '좀 속상하지만 상대방이 잘한 것이라며 인정한다. 다음엔 더 잘하면 된다',
        en: 'Feel a bit upset but admit the opponent did well. I can do better next time',
        ja: '少し悔しいが相手が上手だったと認める。次はもっと頑張ればいい',
        'zh-CN': '有点失落但承认对手厉害，下次再努力就好',
        'zh-TW': '有點失落但承認對手厲害，下次再努力就好',
        vi: 'Hơi buồn nhưng thừa nhận đối thủ giỏi. Lần sau làm tốt hơn được',
        id: 'Agak kecewa tapi mengakui lawan bagus. Lain kali bisa lebih baik',
    }), 1),
      opt(localeMap({
        ko: '꽤 오래 아쉬움이 남는다. 어디서 놓쳤는지 분석하고 반드시 다음엔 이기겠다고 다짐한다',
        en: 'Regret lingers for a while. I analyze what I missed and vow to win next time',
        ja: 'かなり長く悔しさが残る。どこで失敗したか分析し、次は必ず勝つと誓う',
        'zh-CN': '遗憾会持续挺久，分析哪里失误，发誓下次一定要赢',
        'zh-TW': '遺憾會持續挺久，分析哪裡失誤，發誓下次一定要贏',
        vi: 'Tiếc khá lâu. Phân tích chỗ sai và quyết thắng lần sau',
        id: 'Penyesalan cukup lama. Analisis kekurangan dan bersumpah menang lain kali',
    }), 2),
      opt(localeMap({
        ko: '많이 힘들다. 패배를 인정하는 것 자체가 매우 어렵다. 이 결과를 오래 곱씹는다',
        en: 'It hits hard. Accepting defeat is very difficult. I dwell on this result for a long time',
        ja: 'かなり辛い。敗北を認めること自体が非常に難しい。この結果を長く引きずる',
        'zh-CN': '很难受，承认失败本身就很难，会反复想这个结果很久',
        'zh-TW': '很難受，承認失敗本身就會很難，會反覆想這個結果很久',
        vi: 'Rất khó chịu. Thừa nhận thua rất khó. Tôi nghĩ về kết quả này rất lâu',
        id: 'Sangat berat. Menerima kekalahan sangat sulit. Hasil ini terus terngiang lama',
    }), 3),
    ],
  },
  {
    id: 4,
    question: localeMap({
      ko: '경쟁 상대가 나보다 명백히 뛰어난 실력을 보여줬다. 나는?',
      en: 'Your opponent clearly showed skill far above yours. You:',
      ja: '競争相手が明らかに自分よりはるかに優れた実力を見せた。あなたは？',
      'zh-CN': '竞争对象明显展现出远在你之上的实力，你会？',
      'zh-TW': '競爭對象明顯展現出遠在你之上的實力，你會？',
      vi: 'Đối thủ thể hiện rõ ràng trình độ vượt trội hơn bạn. Bạn:',
      id: 'Lawan jelas menunjukkan skill jauh di atasmu. Kamu:',
    }),
    options: [
      opt(localeMap({
        ko: '대단하다고 생각하고 그냥 넘어간다. 다들 잘하는 게 있다',
        en: 'Think they are amazing and move on. Everyone is good at something',
        ja: 'すごいと思ってそのまま流す。誰にでも得意なことがある',
        'zh-CN': '觉得厉害就过了，每个人都有擅长的事',
        'zh-TW': '覺得厲害就過了，每個人都有擅長的事',
        vi: 'Nghĩ họ giỏi và bỏ qua. Ai cũng có thứ mình giỏi',
        id: 'Pikir mereka hebat dan lanjut. Semua punya keahlian',
    }), 0),
      opt(localeMap({
        ko: '저 사람한테서 배울 게 있겠다고 생각한다. 오히려 동기부여가 된다',
        en: 'Think I can learn from them. It actually motivates me',
        ja: 'その人から学べることがあると思う。むしろモチベーションになる',
        'zh-CN': '觉得可以从对方身上学到东西，反而更有动力',
        'zh-TW': '覺得可以從對方身上學到東西，反而更有動力',
        vi: 'Nghĩ có thể học hỏi từ họ. Thực ra còn thêm động lực',
        id: 'Pikir bisa belajar dari mereka. Justru jadi motivasi',
    }), 1),
      opt(localeMap({
        ko: '자극받는다. 나도 저 수준까지 올라가겠다는 목표가 생긴다',
        en: 'Feel stimulated. I set a goal to reach that level too',
        ja: '刺激を受ける。自分もそのレベルまで上がる目標ができる',
        'zh-CN': '被刺激到了，也会设定目标要达到那个水平',
        'zh-TW': '被刺激到了，也會設定目標要達到那個水平',
        vi: 'Bị kích thích. Đặt mục tiêu lên tới trình độ đó',
        id: 'Terasa terstimulasi. Buat target naik ke level itu juga',
    }), 2),
      opt(localeMap({
        ko: '지고 싶지 않다는 마음이 강하게 든다. 어떻게 하면 이길 수 있을지를 바로 생각하기 시작한다',
        en: 'Strongly do not want to lose. I immediately start thinking how to beat them',
        ja: '負けたくない気持ちが強い。どうすれば勝てるかすぐ考え始める',
        'zh-CN': '非常不想输，马上开始想怎么才能赢',
        'zh-TW': '非常不想輸，馬上開始想怎麼才能贏',
        vi: 'Rất không muốn thua. Ngay lập tức nghĩ cách thắng',
        id: 'Sangat tidak mau kalah. Langsung mikir cara mengalahkan',
    }), 3),
    ],
  },
  {
    id: 5,
    question: localeMap({
      ko: '내가 경쟁에서 가장 강하게 동기부여를 받는 순간은?',
      en: 'When do you feel most strongly motivated in competition?',
      ja: '競争で最も強く動機づけられる瞬間は？',
      'zh-CN': '在竞争中，你什么时候最受激励？',
      'zh-TW': '在競爭中，你什麼時候最受激勵？',
      vi: 'Khi nào bạn cảm thấy được động lực mạnh nhất trong cạnh tranh?',
      id: 'Kapan kamu paling termotivasi dalam kompetisi?',
    }),
    options: [
      opt(localeMap({
        ko: '딱히 경쟁 자체에서 동기를 얻지 않는다. 내 페이스대로 하는 게 더 좋다',
        en: 'I do not really get motivation from competition itself. I prefer my own pace',
        ja: '競争自体からはあまり動機を得ない。自分のペースの方がいい',
        'zh-CN': '不太从竞争本身获得动力，更按自己的节奏来',
        'zh-TW': '不太從競爭本身獲得動力，更按自己的節奏來',
        vi: 'Không thực sự lấy động lực từ cạnh tranh. Tôi thích nhịp của mình',
        id: 'Tidak terlalu termotivasi dari kompetisi itu sendiri. Lebih suka pace sendiri',
    }), 0),
      opt(localeMap({
        ko: '내가 어제보다 나아졌다는 것을 느낄 때. 상대방보다 기준은 어제의 나다',
        en: 'When I feel I improved compared to yesterday. My benchmark is yesterday\'s me, not others',
        ja: '昨日より良くなったと感じる時。基準は相手より昨日の自分',
        'zh-CN': '当感觉比昨天更好时，标准是比昨天的自己，不是别人',
        'zh-TW': '當感覺比昨天更好時，標準是比昨天的自己，不是別人',
        vi: 'Khi cảm thấy mình tốt hơn hôm qua. Chuẩn là bản thân hôm qua, không phải người khác',
        id: 'Saat merasa lebih baik dari kemarin. Patokannya diri kemarin, bukan orang lain',
    }), 1),
      opt(localeMap({
        ko: '상대방과 막상막하로 붙었을 때. 긴장감 속에서 최선을 내는 순간이 좋다',
        en: 'When I am neck and neck with an opponent. I love giving my best in that tension',
        ja: '相手と互角で競う時。緊張感の中で最善を出す瞬間が好き',
        'zh-CN': '和对手势均力敌时，喜欢在紧张感中全力以赴',
        'zh-TW': '和對手勢均力敵時，喜歡在緊張感中全力以赴',
        vi: 'Khi cạnh tranh sát sao với đối thủ. Tôi thích cố hết sức trong căng thẳng đó',
        id: 'Saat seimbang dengan lawan. Suka memberikan yang terbaik dalam ketegangan itu',
    }), 2),
      opt(localeMap({
        ko: '모두가 어렵다고 할 때, 또는 아무도 이기지 못했다고 할 때. 그 상황에서 내가 이겨내는 것',
        en: 'When everyone says it is hard, or when no one has won yet. Winning in that situation',
        ja: '誰もが難しいと言う時、または誰も勝てなかったと言う時。その状況で自分が勝ち抜くこと',
        'zh-CN': '当大家都说很难，或还没人赢过时，在那种情况下赢下来',
        'zh-TW': '當大家都說很難，或還沒人贏過時，在那種情況下贏下來',
        vi: 'Khi mọi người nói khó, hoặc chưa ai thắng. Chiến thắng trong tình huống đó',
        id: 'Saat semua bilang sulit, atau belum ada yang menang. Menang di situasi itu',
    }), 3),
    ],
  },
  {
    id: 6,
    question: localeMap({
      ko: '경쟁 없이 혼자 무언가를 하는 상황이다. 나는?',
      en: 'You are doing something alone without competition. You:',
      ja: '競争なしで一人で何かをしている状況。あなたは？',
      'zh-CN': '在没有竞争的情况下独自做某事，你会？',
      'zh-TW': '在沒有競爭的情況下獨自做某事，你會？',
      vi: 'Bạn đang làm gì đó một mình, không có cạnh tranh. Bạn:',
      id: 'Kamu melakukan sesuatu sendiri tanpa kompetisi. Kamu:',
    }),
    options: [
      opt(localeMap({
        ko: '오히려 편하다. 혼자 하는 게 경쟁 상황보다 훨씬 즐겁다',
        en: 'Actually feel more comfortable. Doing things alone is much more enjoyable than competing',
        ja: 'むしろ楽。一人でやる方が競争よりずっと楽しい',
        'zh-CN': '反而更自在，独自做比竞争情境愉快得多',
        'zh-TW': '反而更自在，獨自做比競爭情境愉快得多',
        vi: 'Thực ra thoải mái hơn. Làm một mình vui hơn nhiều so với cạnh tranh',
        id: 'Justru lebih nyaman. Sendiri jauh lebih enjoyable daripada kompetisi',
    }), 0),
      opt(localeMap({
        ko: '스스로 목표를 정하고 그것을 달성하는 것에서 의미를 찾는다',
        en: 'Set my own goals and find meaning in achieving them',
        ja: '自分で目標を定め、それを達成することに意味を見出す',
        'zh-CN': '自己设定目标，并在达成中找到意义',
        'zh-TW': '自己設定目標，並在達成中找到意義',
        vi: 'Tự đặt mục tiêu và tìm ý nghĩa trong việc đạt được chúng',
        id: 'Tetapkan target sendiri dan temukan makna dalam mencapainya',
    }), 1),
      opt(localeMap({
        ko: '어느 정도 괜찮지만 경쟁이 있을 때 더 집중이 잘 되는 건 사실이다',
        en: 'It is okay, but I focus better when there is competition',
        ja: 'ある程度は問題ないが、競争がある方が集中しやすいのは事実',
        'zh-CN': '还可以，但有竞争时确实更容易集中',
        'zh-TW': '還可以，但有競爭時確實更容易集中',
        vi: 'Ổn, nhưng thực tế có cạnh tranh thì tập trung tốt hơn',
        id: 'Cukup oke, tapi memang lebih fokus saat ada kompetisi',
    }), 2),
      opt(localeMap({
        ko: '비교 대상이 없으면 얼마나 잘하고 있는지 모른다는 게 답답하다. 순위·기록·비교가 있어야 더 잘할 수 있다',
        en: 'Without someone to compare to, it is frustrating not knowing how well I am doing. I need rankings, records, or comparison to do better',
        ja: '比較対象がないとどれだけできているか分からずもどかしい。順位・記録・比較がないとより良くできない',
        'zh-CN': '没有比较对象就不知道自己做得怎样，很憋屈，需要排名、记录、比较才能做得更好',
        'zh-TW': '沒有比較對象就不知道自己做得怎樣，很憋屈，需要排名、紀錄、比較才能做得更好',
        vi: 'Không có ai để so sánh thì khó chịu vì không biết mình làm tốt đến đâu. Cần xếp hạng, kỷ lục, so sánh mới làm tốt hơn',
        id: 'Tanpa pembanding, frustrasi tidak tahu seberapa baik performa. Butuh ranking, rekor, perbandingan untuk lebih baik',
    }), 3),
    ],
  },
  {
    id: 7,
    question: localeMap({
      ko: '주변 친구나 동료가 나보다 먼저 승진하거나 더 좋은 결과를 냈다. 나는?',
      en: 'A friend or colleague got promoted before you or achieved a better result. You:',
      ja: '周りの友人や同僚が自分より先に昇進したり、より良い結果を出した。あなたは？',
      'zh-CN': '身边的朋友或同事比你先升职或取得更好的成绩，你会？',
      'zh-TW': '身邊的朋友或同事比你先升職或取得更好的成績，你會？',
      vi: 'Bạn bè hoặc đồng nghiệp thăng tiến trước bạn hoặc đạt kết quả tốt hơn. Bạn:',
      id: 'Teman atau rekan kerja promosi lebih dulu atau hasilnya lebih baik. Kamu:',
    }),
    options: [
      opt(localeMap({
        ko: '잘됐네, 하고 진심으로 축하한다. 내 상황과 비교하지 않는다',
        en: 'Sincerely congratulate them. I do not compare it to my situation',
        ja: '本当によかったと心から祝福する。自分の状況と比較しない',
        'zh-CN': '真心祝贺，不会和自己的情况比较',
        'zh-TW': '真心祝賀，不會和自己的情況比較',
        vi: 'Chúc mừng chân thành. Tôi không so với tình huống của mình',
        id: 'Mengucapkan selamat tulus. Tidak membandingkan dengan situasiku',
    }), 0),
      opt(localeMap({
        ko: '축하는 하지만 나도 더 열심히 해야겠다는 자극이 된다. 부럽다는 마음이 긍정적 동력이 된다',
        en: 'Congratulate them but feel motivated to work harder. Envy becomes positive drive',
        ja: '祝福するが、自分ももっと頑張ろうという刺激になる。羨望が前向きな原動力になる',
        'zh-CN': '会祝贺，但也会激励自己更努力，羡慕变成正向动力',
        'zh-TW': '會祝賀，但也會激勵自己更努力，羨慕變成正向動力',
        vi: 'Chúc mừng nhưng cũng thấy cần cố gắng hơn. Ghen tị thành động lực tích cực',
        id: 'Ucapkan selamat tapi termotivasi kerja lebih keras. Iri jadi dorongan positif',
    }), 1),
      opt(localeMap({
        ko: '솔직히 뒤처진 것 같은 느낌이 든다. 나도 더 빠르게 올라가야겠다는 압박이 생긴다',
        en: 'Honestly feel left behind. Pressure builds to move up faster',
        ja: '正直、置いていかれた感じがする。もっと早く上がらなければというプレッシャーが生まれる',
        'zh-CN': '老实说会觉得被甩在后面，压力上来要更快往上走',
        'zh-TW': '老實說會覺得被甩在後面，壓力上來要更快往上走',
        vi: 'Thành thật cảm thấy bị bỏ lại. Áp lực phải tiến nhanh hơn',
        id: 'Jujur merasa ketinggalan. Tekanan untuk naik lebih cepat muncul',
    }), 2),
      opt(localeMap({
        ko: '내심 많이 신경 쓰인다. 왜 나는 아직인가, 무엇이 부족한가를 계속 생각하게 된다',
        en: 'It bothers me a lot inside. I keep thinking why I am not there yet and what I lack',
        ja: '内心かなり気になる。なぜ自分はまだなのか、何が足りないのかを考え続ける',
        'zh-CN': '内心很在意，会一直想为什么自己还没做到、缺什么',
        'zh-TW': '內心很在意，會一直想為什麼自己還沒做到、缺什麼',
        vi: 'Trong lòng rất bận tâm. Cứ nghĩ tại sao mình chưa được, thiếu gì',
        id: 'Sangat mengganggu di hati. Terus mikir kenapa belum, apa yang kurang',
    }), 3),
    ],
  },
  {
    id: 8,
    question: localeMap({
      ko: '내가 속한 그룹이나 팀이 다른 팀과 비교됐을 때 나는?',
      en: 'When your group or team is compared to another team, you:',
      ja: '自分が属するグループやチームが他チームと比較された時、あなたは？',
      'zh-CN': '当你所在的团队被和其他团队比较时，你会？',
      'zh-TW': '當你所在的團隊被和其他團隊比較時，你會？',
      vi: 'Khi nhóm hoặc đội của bạn được so với đội khác, bạn:',
      id: 'Saat grup atau timmu dibandingkan dengan tim lain, kamu:',
    }),
    options: [
      opt(localeMap({
        ko: '별로 신경 쓰이지 않는다. 비교가 그렇게 의미 있다고 생각하지 않는다',
        en: 'Do not care much. I do not think comparison is that meaningful',
        ja: 'あまり気にしない。比較がそれほど意味があるとは思わない',
        'zh-CN': '不太在意，不觉得比较有那么重要',
        'zh-TW': '不太在意，不覺得比較有那麼重要',
        vi: 'Không quan tâm lắm. Tôi không nghĩ so sánh có ý nghĩa lắm',
        id: 'Tidak terlalu peduli. Perbandingan tidak terlalu bermakna menurutku',
    }), 0),
      opt(localeMap({
        ko: '우리 팀이 더 잘할 수 있는 부분이 있으면 함께 올라가면 된다고 생각한다',
        en: 'Think we can grow together if there are areas we can improve',
        ja: 'うちのチームがもっと良くできる部分があれば一緒に上がればいいと思う',
        'zh-CN': '觉得我们团队还有可以更好的部分，一起提升就好',
        'zh-TW': '覺得我們團隊還有可以更好的部分，一起提升就好',
        vi: 'Nghĩ nếu có phần làm tốt hơn thì cùng nhau tiến lên',
        id: 'Pikir kalau ada bagian yang bisa lebih baik, naik bareng saja',
    }), 1),
      opt(localeMap({
        ko: '상대 팀보다 더 잘하고 싶은 마음이 생긴다. 팀 경쟁이 개인 경쟁보다 더 뜨거워지는 편이다',
        en: 'Want our team to do better than the other. Team competition gets me hotter than individual rivalry',
        ja: '相手チームよりうちが上手くなりたい。チーム競争の方が個人より熱くなる',
        'zh-CN': '想比对方团队更强，团队竞争比个人竞争更让我上头',
        'zh-TW': '想比對方團隊更強，團隊競爭比個人競爭更讓我上頭',
        vi: 'Muốn đội mình giỏi hơn đội kia. Cạnh tranh đội làm tôi nóng hơn cạnh tranh cá nhân',
        id: 'Ingin tim kita lebih baik dari tim lawan. Kompetisi tim lebih panas dari individual',
    }), 2),
      opt(localeMap({
        ko: '우리가 지거나 뒤처지는 건 받아들이기 어렵다. 어떻게 하면 이길 수 있는지를 바로 고민하기 시작한다',
        en: 'Hard to accept losing or falling behind. I immediately start thinking how to win',
        ja: '負ける・遅れるのは受け入れにくい。どうすれば勝てるかすぐ考え始める',
        'zh-CN': '很难接受落后或输掉，马上开始想怎么赢',
        'zh-TW': '很難接受落後或輸掉，馬上開始想怎麼贏',
        vi: 'Khó chấp nhận thua hoặc tụt lại. Ngay lập tức nghĩ cách thắng',
        id: 'Sulit terima kalah atau ketinggalan. Langsung mikir cara menang',
    }), 3),
    ],
  },
  {
    id: 9,
    question: localeMap({
      ko: '이기기 위해 전략을 짜는 것에 대해 나는?',
      en: 'About planning strategy to win, I:',
      ja: '勝つための戦略を立てることについて、私は？',
      'zh-CN': '关于为了赢而制定策略，我会？',
      'zh-TW': '關於為了贏而制定策略，我會？',
      vi: 'Về việc lập chiến lược để thắng, tôi:',
      id: 'Tentang merencanakan strategi untuk menang, saya:',
    }),
    options: [
      opt(localeMap({
        ko: '딱히 전략을 짜지 않는다. 자연스럽게 하다 보면 된다고 생각한다',
        en: 'Do not really plan strategy. I think things will work out naturally',
        ja: '特に戦略は立てない。自然にやっていけばいいと思う',
        'zh-CN': '不太制定策略，觉得顺其自然就好',
        'zh-TW': '不太制定策略，覺得順其自然就好',
        vi: 'Không lập chiến lược đặc biệt. Nghĩ cứ làm tự nhiên sẽ ổn',
        id: 'Tidak banyak bikin strategi. Pikir akan berjalan natural',
    }), 0),
      opt(localeMap({
        ko: '어느 정도 준비하지만 전략보다 내 실력을 키우는 것에 더 집중한다',
        en: 'Prepare to some extent, but focus more on improving my own skill than strategy',
        ja: 'ある程度準備するが、戦略より実力を上げる方に集中する',
        'zh-CN': '会做一些准备，但更专注提升实力而不是策略',
        'zh-TW': '會做一些準備，但更專注提升實力而不是策略',
        vi: 'Chuẩn bị ở mức nào đó, nhưng tập trung nâng kỹ năng hơn chiến lược',
        id: 'Siapkan sejauh ini, tapi lebih fokus tingkatkan skill daripada strategi',
    }), 1),
      opt(localeMap({
        ko: '이기기 위해 상대방을 분석하고 나의 강점을 활용하는 전략을 세우는 것이 자연스럽다',
        en: 'Naturally analyze opponents and build strategy using my strengths to win',
        ja: '相手を分析し、自分の強みを活かす戦略を立てるのが自然',
        'zh-CN': '会自然分析对手，制定发挥自己优势的策略',
        'zh-TW': '會自然分析對手，制定發揮自己優勢的策略',
        vi: 'Tự nhiên phân tích đối thủ và lập chiến lược dùng điểm mạnh để thắng',
        id: 'Natural menganalisis lawan dan susun strategi pakai kekuatan untuk menang',
    }), 2),
      opt(localeMap({
        ko: '경쟁 전 상대방을 철저히 분석하고 최적의 전략을 구성하는 것 자체가 즐겁다. 준비 단계부터 이미 경쟁이 시작된 것이다',
        en: 'Thoroughly analyzing opponents and building the best strategy before competition is fun. The competition already starts in prep',
        ja: '競争前に相手を徹底分析し最適戦略を組むこと自体が楽しい。準備段階からすでに競争が始まっている',
        'zh-CN': '赛前彻底分析对手、构建最优策略本身就很有趣，准备阶段竞争就已经开始了',
        'zh-TW': '賽前徹底分析對手、構建最優策略本身就很有趣，準備階段競爭就已經開始了',
        vi: 'Phân tích kỹ đối thủ và xây chiến lược tối ưu trước trận rất vui. Cạnh tranh đã bắt đầu từ lúc chuẩn bị',
        id: 'Menganalisis lawan dan susun strategi optimal sebelum kompetisi itu seru. Kompetisi sudah mulai dari persiapan',
    }), 3),
    ],
  },
  {
    id: 10,
    question: localeMap({
      ko: '경쟁에서 공정하지 않은 상황이 생겼다. 나는?',
      en: 'An unfair situation arises in competition. You:',
      ja: '競争で不公平な状況が生まれた。あなたは？',
      'zh-CN': '竞争中出现不公平的情况，你会？',
      'zh-TW': '競爭中出現不公平的情況，你會？',
      vi: 'Trong cạnh tranh xuất hiện tình huống không công bằng. Bạn:',
      id: 'Situasi tidak adil muncul dalam kompetisi. Kamu:',
    }),
    options: [
      opt(localeMap({
        ko: '어쩔 수 없지, 하고 받아들인다. 세상이 항상 공정하지는 않다',
        en: 'Accept it. The world is not always fair',
        ja: '仕方ないと受け入れる。世界は常に公平ではない',
        'zh-CN': '没办法，接受吧，世界并不总是公平',
        'zh-TW': '沒辦法，接受吧，世界並不總是公平',
        vi: 'Chấp nhận. Thế giới không phải lúc nào cũng công bằng',
        id: 'Terima saja. Dunia tidak selalu adil',
    }), 0),
      opt(localeMap({
        ko: '불공정하다는 것을 인지하지만 그 안에서 내가 할 수 있는 것에 집중한다',
        en: 'Recognize it is unfair but focus on what I can do within it',
        ja: '不公平だと認識するが、その中で自分にできることに集中する',
        'zh-CN': '知道不公平，但专注在自己能做的事上',
        'zh-TW': '知道不公平，但專注在自己能做的事上',
        vi: 'Nhận ra không công bằng nhưng tập trung vào phần mình làm được',
        id: 'Sadar tidak adil tapi fokus pada yang bisa kulakukan di dalamnya',
    }), 1),
      opt(localeMap({
        ko: '불공정함을 지적하거나 개선을 요구한다. 공정한 환경에서 이겨야 진정한 승리라고 생각한다',
        en: 'Call out unfairness or demand improvement. Real victory must come in a fair environment',
        ja: '不公平を指摘するか改善を求める。公正な環境で勝ってこそ本当の勝利',
        'zh-CN': '会指出不公或要求改善，认为在公平环境中赢才是真胜利',
        'zh-TW': '會指出不公或要求改善，認為在公平環境中贏才是真勝利',
        vi: 'Chỉ ra sự bất công hoặc đòi cải thiện. Chiến thắng thật phải ở môi trường công bằng',
        id: 'Tunjukkan ketidakadilan atau minta perbaikan. Kemenangan sejati harus di lingkungan adil',
    }), 2),
      opt(localeMap({
        ko: '매우 불편하다. 공정하지 않은 경쟁 자체가 의미 없다고 느끼거나 반대로 그 상황에서도 어떻게든 이기려는 강한 의지가 생긴다',
        en: 'Very uncomfortable. Unfair competition feels meaningless, or I get a strong will to win anyway',
        ja: '非常に不快。不公平な競争自体が意味ないと感じるか、逆にどうにかして勝とうという強い意志が生まれる',
        'zh-CN': '非常不舒服，觉得不公平的竞争没意义，或者反而更想无论如何都要赢',
        'zh-TW': '非常不舒服，覺得不公平的競爭沒意義，或者反而更想無論如何都要贏',
        vi: 'Rất khó chịu. Cạnh tranh không công bằng vô nghĩa, hoặc ngược lại ý chí thắng càng mạnh',
        id: 'Sangat tidak nyaman. Kompetisi tidak adil terasa meaningless, atau justru muncul tekad kuat untuk tetap menang',
    }), 3),
    ],
  },
  {
    id: 11,
    question: localeMap({
      ko: '경쟁심이 나의 일상과 관계에 어떻게 영향을 주는가?',
      en: 'How does competitiveness affect your daily life and relationships?',
      ja: '競争心はあなたの日常と人間関係にどう影響しますか？',
      'zh-CN': '竞争心如何影响你的日常和人际关系？',
      'zh-TW': '競爭心如何影響你的日常和人際關係？',
      vi: 'Tính cạnh tranh ảnh hưởng thế nào đến cuộc sống và quan hệ hàng ngày của bạn?',
      id: 'Bagaimana daya saing memengaruhi kehidupan sehari-hari dan relasi kamu?',
    }),
    options: [
      opt(localeMap({
        ko: '거의 영향을 주지 않는다. 경쟁심이 강한 편이 아니어서 일상도 관계도 비교적 편안하다',
        en: 'Almost no effect. I am not very competitive, so daily life and relationships stay relatively comfortable',
        ja: 'ほとんど影響しない。競争心が強い方ではないので日常も関係も比較的楽',
        'zh-CN': '几乎没影响，竞争心不算强，日常和关系都比较轻松',
        'zh-TW': '幾乎沒影響，競爭心不算強，日常和關係都比較輕鬆',
        vi: 'Hầu như không ảnh hưởng. Tôi không quá cạnh tranh nên đời sống và quan hệ khá thoải mái',
        id: 'Hampir tidak berpengaruh. Daya saingku tidak kuat, jadi hidup dan relasi relatif nyaman',
    }), 0),
      opt(localeMap({
        ko: '긍정적인 자극이 된다. 경쟁심이 나를 더 성장하게 만드는 연료가 된다',
        en: 'Positive stimulation. Competitiveness fuels my growth',
        ja: '前向きな刺激になる。競争心が成長の燃料になる',
        'zh-CN': '是正向刺激，竞争心成为成长的燃料',
        'zh-TW': '是正向刺激，競爭心成為成長的燃料',
        vi: 'Là kích thích tích cực. Tính cạnh tranh là nhiên liệu cho sự phát triển',
        id: 'Stimulasi positif. Daya saing jadi bahan bakar pertumbuhan',
    }), 1),
      opt(localeMap({
        ko: '대체로 긍정적이지만 가끔 너무 이기고 싶은 마음이 앞서서 스트레스를 받는 경우가 있다',
        en: 'Mostly positive, but sometimes wanting to win too much causes stress',
        ja: '概ね前向きだが、時々勝ちたい気持ちが先走ってストレスになることがある',
        'zh-CN': '大体是正向的，但偶尔太想赢会带来压力',
        'zh-TW': '大體是正向的，但偶爾太想贏會帶來壓力',
        vi: 'Phần lớn tích cực, nhưng đôi khi muốn thắng quá mức gây stress',
        id: 'Kebanyakan positif, tapi kadang ingin menang terlalu kuat bikin stress',
    }), 2),
      opt(localeMap({
        ko: '경쟁심이 강해서 삶 전반에 긴장감이 있다. 이기는 것이 의욕의 원천이지만 때로 지나친 경쟁심이 관계나 자신에게 부담이 되기도 한다',
        en: 'Strong competitiveness creates tension across life. Winning is my drive, but sometimes excessive competitiveness burdens relationships and myself',
        ja: '競争心が強く、人生全体に緊張感がある。勝つことが原動力だが、時に過剰な競争心が関係や自分に負担になる',
        'zh-CN': '竞争心强，整个人生都有紧张感，赢是动力，但有时过强的竞争心也会给关系和自己带来负担',
        'zh-TW': '競爭心強，整個人生都有緊張感，贏是動力，但有時過強的競爭心也會給關係和自己帶來負擔',
        vi: 'Tính cạnh tranh mạnh tạo căng thẳng suốt cuộc sống. Thắng là động lực nhưng đôi khi quá mức gây áp lực cho quan hệ và bản thân',
        id: 'Daya saing kuat bikin ketegangan di seluruh hidup. Menang jadi drive, tapi kadang berlebihan membebani relasi dan diri sendiri',
    }), 3),
    ],
  },
  {
    id: 12,
    question: localeMap({
      ko: '이기는 것과 잘하는 것 중 나에게 더 중요한 것은?',
      en: 'Which matters more to you: winning or doing well?',
      ja: '「勝つこと」と「上手くすること」のうち、あなたにとってより重要なのは？',
      'zh-CN': '对你来说，赢和做好哪个更重要？',
      'zh-TW': '對你來說，贏和做好哪個更重要？',
      vi: 'Điều nào quan trọng hơn với bạn: thắng hay làm tốt?',
      id: 'Mana yang lebih penting bagimu: menang atau melakukan dengan baik?',
    }),
    options: [
      opt(localeMap({
        ko: '둘 다 별로 중요하지 않다. 즐기는 것이 먼저다',
        en: 'Neither matters much. Enjoying it comes first',
        ja: 'どちらもあまり重要ではない。楽しむことが先',
        'zh-CN': '都不太重要，享受优先',
        'zh-TW': '都不太重要，享受優先',
        vi: 'Cả hai đều không quan trọng lắm. Thích thú mới là trước hết',
        id: 'Keduanya tidak terlalu penting. Enjoy dulu',
    }), 0),
      opt(localeMap({
        ko: '잘하는 것이 더 중요하다. 이기는 것은 잘하다 보면 따라오는 결과다',
        en: 'Doing well matters more. Winning follows when you do well',
        ja: '上手くすることの方が重要。上手くなれば勝つことはついてくる',
        'zh-CN': '做好更重要，做好了赢自然会来',
        'zh-TW': '做好更重要，做好了贏自然會來',
        vi: 'Làm tốt quan trọng hơn. Thắng sẽ theo khi bạn làm tốt',
        id: 'Melakukan dengan baik lebih penting. Menang mengikuti saat kamu bagus',
    }), 1),
      opt(localeMap({
        ko: '둘 다 중요하다. 잘해야 이길 수 있고 이기기 위해 더 잘하게 된다',
        en: 'Both matter. You must do well to win, and wanting to win makes you do better',
        ja: '両方重要。上手くなければ勝てないし、勝ちたいからより上手くなる',
        'zh-CN': '都重要，要做好才能赢，想赢才会做得更好',
        'zh-TW': '都重要，要做好才能贏，想贏才會做得更好',
        vi: 'Cả hai đều quan trọng. Phải làm tốt mới thắng, muốn thắng thì làm tốt hơn',
        id: 'Keduanya penting. Harus bagus untuk menang, ingin menang bikin lebih bagus',
    }), 2),
      opt(localeMap({
        ko: '이기는 것이 더 중요하다. 아무리 잘해도 지면 의미가 반감된다',
        en: 'Winning matters more. No matter how well I do, losing halves the meaning',
        ja: '勝つことの方が重要。どれだけ上手くても負ければ意味が半減する',
        'zh-CN': '赢更重要，做得再好，输了意义也会减半',
        'zh-TW': '贏更重要，做得再好，輸了意義也會減半',
        vi: 'Thắng quan trọng hơn. Dù làm tốt đến đâu, thua thì ý nghĩa giảm một nửa',
        id: 'Menang lebih penting. Seberapa bagus pun, kalah setengah maknanya hilang',
    }), 3),
    ],
  },
];

export const phase3CompetitiveDnaResults: Phase3CompetitiveDnaResult[] = [
  {
    type: "Type1",
    emoji: "🕊️",
    title: localeMap({
      ko: '경쟁보다 평화가 좋은 사람, 평화주의형',
      en: 'Pacifist Type 🕊️',
      ja: '平和主義型 🕊️',
      'zh-CN': '和平主义型 🕊️',
      'zh-TW': '和平主義型 🕊️',
      vi: 'Kiểu hòa bình 🕊️',
      id: 'Tipe Pacifist 🕊️',
    }),
    competitiveDna: localeMap({
      ko: '매우 낮음 / 경쟁보다 자신의 페이스를 선호',
      en: 'Very low / Prefers own pace over competition',
      ja: '非常に低い / 競争より自分のペースを好む',
      'zh-CN': '非常低 / 比起竞争更偏好自己的节奏',
      'zh-TW': '非常低 / 比起競爭更偏好自己的節奏',
      vi: 'Rất thấp / Thích nhịp của mình hơn cạnh tranh',
      id: 'Sangat rendah / Lebih suka pace sendiri daripada kompetisi',
    }),
    quote: localeMap({
      ko: '당신에게 경쟁은 굳이 해야 하는 이유를 모르겠는 것입니다. 이기는 것보다 편안한 것이 더 중요합니다.',
      en: 'To you, competition feels like something with no clear reason to do. Comfort matters more than winning.',
      ja: 'あなたにとって競争は、わざわざやる理由がよく分からないものです。勝つことより快適さの方が大切です。',
      'zh-CN': '对你来说，竞争似乎找不到非做不可的理由。比起赢，舒服更重要。',
      'zh-TW': '對你來說，競爭似乎找不到非做不可的理由。比起贏，舒服更重要。',
      vi: 'Với bạn, cạnh tranh là thứ không rõ vì sao phải làm. Thoải mái quan trọng hơn thắng.',
      id: 'Bagimu, kompetisi terasa seperti sesuatu tanpa alasan jelas untuk dilakukan. Kenyamanan lebih penting dari menang.',
    }),
    description: localeMap({
      ko: '게임에서 져도 크게 아쉽지 않고 동료가 더 빠르게 올라가도 별로 자극받지 않으며 혼자 내 페이스대로 하는 게 경쟁 상황보다 훨씬 편한 타입입니다. 경쟁을 즐기지 않는다는 게 의욕이 없다는 뜻이 아닙니다. 방향이 다를 뿐입니다.',
      en: 'You do not feel very sorry when you lose games, are not much stimulated when colleagues move ahead, and feel much more comfortable doing things at your own pace than in competitive situations. Not enjoying competition does not mean you lack drive. Your direction is just different.',
      ja: 'ゲームで負けても大きく残念に思わず、同僚が先に進んでもあまり刺激されず、競争より自分のペースで進む方がずっと楽なタイプです。競争を楽しめないことは、やる気がないという意味ではありません。方向が違うだけです。',
      'zh-CN': '游戏输了不太遗憾，同事走得更快也不太刺激，按自己节奏做事比竞争情境舒服得多。不爱竞争不代表没动力，只是方向不同。',
      'zh-TW': '遊戲輸了不太遺憾，同事走得更快也不太刺激，按自己節奏做事比競爭情境舒服得多。不愛競爭不代表沒動力，只是方向不同。',
      vi: 'Không quá tiếc khi thua game, không bị kích thích nhiều khi đồng nghiệp đi trước, và làm theo nhịp riêng thoải mái hơn nhiều so với cạnh tranh. Không thích cạnh tranh không có nghĩa là thiếu động lực. Chỉ là hướng đi khác.',
      id: 'Tidak terlalu menyesal kalah game, tidak terlalu terstimulasi saat rekan maju, dan jauh lebih nyaman dengan pace sendiri daripada situasi kompetitif. Tidak menikmati kompetisi bukan berarti tidak punya drive. Arahnya saja berbeda.',
    }),
    competitiveType: localeMap({
      ko: '평화주의형 🕊️',
      en: 'Pacifist Type 🕊️',
      ja: '平和主義型 🕊️',
      'zh-CN': '和平主义型 🕊️',
      'zh-TW': '和平主義型 🕊️',
      vi: 'Kiểu hòa bình 🕊️',
      id: 'Tipe Pacifist 🕊️',
    }),
    competitiveKeywords: localeMap({
      ko: '평화·자기 페이스·과정·즐김·비교 없음',
      en: 'Peace · Own pace · Process · Enjoyment · No comparison',
      ja: '平和・自分のペース・過程・楽しさ・比較なし',
      'zh-CN': '和平·自我节奏·过程·享受·不比较',
      'zh-TW': '和平·自我節奏·過程·享受·不比較',
      vi: 'Hòa bình · Nhịp riêng · Quá trình · Thích thú · Không so sánh',
      id: 'Kedamaian · Pace sendiri · Proses · Enjoy · Tanpa perbandingan',
    }),
    strengths: localeMap({
      ko: '타인과의 비교에서 오는 스트레스가 없음. 심리적으로 안정적\n경쟁보다 협력에서 강점 발휘. 팀 분위기를 부드럽게 만드는 역할\n결과보다 과정을 즐기기 때문에 지속 가능한 방식으로 오래 할 수 있음',
      en: 'No stress from comparing with others. Psychologically stable\nStrong in cooperation rather than competition. Softens team atmosphere\nCan keep going sustainably by enjoying the process more than results',
      ja: '他人との比較からくるストレスがない。心理的に安定\n競争より協力で強みを発揮。チームの雰囲気を柔らかくする\n結果より過程を楽しむので、持続可能な形で長く続けられる',
      'zh-CN': '不会因与他人比较而压力，心理较稳定\n更擅长合作而非竞争，能让团队氛围更柔和\n因为享受过程胜过结果，可以长期持续',
      'zh-TW': '不會因與他人比較而壓力，心理較穩定\n更擅長合作而非競爭，能讓團隊氛圍更柔和\n因為享受過程勝過結果，可以長期持續',
      vi: 'Không stress vì so sánh với người khác. Ổn định tâm lý\nMạnh ở hợp tác hơn cạnh tranh. Làm không khí nhóm dịu hơn\nCó thể đi lâu dài vì thích quá trình hơn kết quả',
      id: 'Tidak stress dari perbandingan dengan orang lain. Stabil secara psikologis\nKuat di kolaborasi daripada kompetisi. Melembutkan suasana tim\nBisa lanjut sustainable karena menikmati proses lebih dari hasil',
    }),
    cautions: localeMap({
      ko: '경쟁이 필요한 환경에서 상대적으로 동기부여가 어려울 수 있음\n너무 느슨한 기준이 성장의 속도를 늦출 수 있음',
      en: 'May find it harder to stay motivated in environments that require competition\nToo loose standards can slow growth',
      ja: '競争が必要な環境では相対的に動機づけが難しいことがある\n基準が緩すぎると成長速度が遅れる可能性',
      'zh-CN': '在需要竞争的环境中可能较难维持动力\n标准太松可能拖慢成长速度',
      'zh-TW': '在需要競爭的環境中可能較難維持動力\n標準太鬆可能拖慢成長速度',
      vi: 'Có thể khó duy trì động lực trong môi trường cần cạnh tranh\nTiêu chuẩn quá lỏng có thể làm chậm tăng trưởng',
      id: 'Bisa lebih sulit termotivasi di lingkungan yang butuh kompetisi\nStandar terlalu longgar bisa memperlambat pertumbuhan',
    }),
    bestEnvironments: localeMap({
      ko: '협업 중심·자율적 목표 설정·과정이 중요한 창의적 분야',
      en: 'Collaboration-focused · Self-set goals · Creative fields where process matters',
      ja: '協力中心・自律的な目標設定・過程が重要な創造的分野',
      'zh-CN': '以协作为中心·自主设定目标·重视过程的创意领域',
      'zh-TW': '以協作為中心·自主設定目標·重視過程的創意領域',
      vi: 'Tập trung hợp tác · Tự đặt mục tiêu · Lĩnh vực sáng tạo coi trọng quá trình',
      id: 'Berfokus kolaborasi · Target mandiri · Bidang kreatif yang menghargai proses',
    }),
    sportsGameTypes: localeMap({
      ko: '순위보다 경험이 중요한 캐주얼 게임·등산·요가·여행',
      en: 'Casual games where experience beats ranking · Hiking · Yoga · Travel',
      ja: '順位より体験が大切なカジュアルゲーム・登山・ヨガ・旅行',
      'zh-CN': '重体验轻排名的休闲游戏·登山·瑜伽·旅行',
      'zh-TW': '重體驗輕排名的休閒遊戲·登山·瑜伽·旅行',
      vi: 'Game casual coi trải nghiệm quan trọng hơn xếp hạng · Leo núi · Yoga · Du lịch',
      id: 'Game casual yang lebih penting pengalaman daripada ranking · Hiking · Yoga · Travel',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '경쟁하지 않아도 됩니다. 다만 내 기준을 조금 더 높이는 것과 경쟁은 다릅니다. 나 자신과의 작은 도전이 성장의 시작이 됩니다',
      en: 'You do not have to compete. But raising your own standard a little is different from competition. Small challenges with yourself are where growth begins',
      ja: '競争しなくてもいい。ただ自分の基準を少し上げることと競争は違う。自分との小さな挑戦が成長の始まり',
      'zh-CN': '不必竞争，但稍微提高自己的标准和竞争不同，与自己的小挑战才是成长的开始',
      'zh-TW': '不必競爭，但稍微提高自己的標準和競爭不同，與自己的小挑戰才是成長的開始',
      vi: 'Bạn không cần cạnh tranh. Nhưng nâng chuẩn của mình một chút khác với cạnh tranh. Thử thách nhỏ với bản thân là khởi đầu của tăng trưởng',
      id: 'Kamu tidak harus kompetisi. Tapi menaikkan standar sendiri sedikit berbeda dari kompetisi. Tantangan kecil dengan diri sendiri adalah awal pertumbuhan',
    }),
    shareLine: localeMap({
      ko: '내 경쟁심 DNA: 평화주의형 🕊️ 경쟁보다 평화가 좋은 유형이래... 게임에서 져도 별로 안 아쉬운 거 맞음 ㅋㅋ → 경쟁심 결과 너는 어떤 유형이야? 스포츠·게임 커뮤니티 공유해봐',
      en: 'My competitive DNA: Pacifist Type 🕊️ They say I prefer peace over competition... not feeling bad when I lose games is so true lol → What\'s your competitive DNA type? Share it in sports & gaming communities',
      ja: '私の競争心DNA：平和主義型 🕊️ 競争より平和が好きなタイプらしい…ゲームで負けてもあまり残念じゃないの当たり ㅋㅋ → あなたの競争心DNAはどのタイプ？スポーツ・ゲームコミュニティでシェアして',
      'zh-CN': '我的竞争心DNA：和平主义型 🕊️ 说是比起竞争更喜欢和平的类型…游戏输了也不太遗憾太准了哈哈 → 你的竞争心DNA是什么类型？分享到体育·游戏社区吧',
      'zh-TW': '我的競爭心DNA：和平主義型 🕊️ 說是比起競爭更喜歡和平的類型…遊戲輸了也不太遺憾太準了哈哈 → 你的競爭心DNA是什麼類型？分享到體育·遊戲社區吧',
      vi: 'DNA cạnh tranh của tôi: Kiểu hòa bình 🕊️ Bảo tôi thích hòa bình hơn cạnh tranh... thua game cũng không buồn lắm, đúng quá haha → Bạn thuộc kiểu nào? Chia sẻ trong cộng đồng thể thao & game',
      id: 'DNA daya saingku: Tipe Pacifist 🕊️ Katanya aku lebih suka damai daripada kompetisi... kalah game juga nggak terlalu sedih, bener wkwk → Kamu tipe apa? Share di komunitas sports & gaming',
    }),
  },
  {
    type: "Type2",
    emoji: "🌱",
    title: localeMap({
      ko: '어제의 나와 경쟁하는 사람, 자기성장형',
      en: 'Self-Growth Type 🌱',
      ja: '自己成長型 🌱',
      'zh-CN': '自我成长型 🌱',
      'zh-TW': '自我成長型 🌱',
      vi: 'Kiểu tự phát triển 🌱',
      id: 'Tipe Self-Growth 🌱',
    }),
    competitiveDna: localeMap({
      ko: '낮음-보통 / 타인이 아닌 어제의 나를 기준으로 삼는 타입',
      en: 'Low to moderate / Uses yesterday\'s self as the benchmark, not others',
      ja: '低〜普通 / 他人ではなく昨日の自分を基準にするタイプ',
      'zh-CN': '偏低-普通 / 以昨天的自己为标准，而不是他人',
      'zh-TW': '偏低-普通 / 以昨天的自己為標準，而不是他人',
      vi: 'Thấp đến trung bình / Lấy bản thân hôm qua làm chuẩn, không phải người khác',
      id: 'Rendah-sedang / Patokan diri kemarin, bukan orang lain',
    }),
    quote: localeMap({
      ko: '당신의 경쟁 상대는 남이 아닙니다. 항상 어제의 나입니다.',
      en: 'Your competition is not other people. It is always yesterday\'s you.',
      ja: 'あなたの競争相手は他人ではありません。いつも昨日の自分です。',
      'zh-CN': '你的竞争对象不是别人，永远是昨天的自己。',
      'zh-TW': '你的競爭對象不是別人，永遠是昨天的自己。',
      vi: 'Đối thủ cạnh tranh của bạn không phải người khác. Luôn là bạn của hôm qua.',
      id: 'Lawan kompetisimu bukan orang lain. Selalu dirimu kemarin.',
    }),
    description: localeMap({
      ko: '타인의 결과보다 자신의 발전에 집중하고 지는 것보다 배우는 것을 더 중요하게 여기며 경쟁보다 성장이 동기부여의 핵심인 타입입니다. 심리학자 캐롤 드웩이 말한 성장 마인드셋의 전형입니다.',
      en: 'You focus on your own progress more than others\' results, value learning over losing, and are motivated by growth more than competition. This is a classic growth mindset, as psychologist Carol Dweck described.',
      ja: '他人の結果より自分の成長に集中し、負けることより学ぶことを重視し、競争より成長が動機の核となるタイプです。心理学者キャロル・ドゥエックが語った成長マインドセットの典型です。',
      'zh-CN': '比起他人结果更关注自身进步，比起输赢更重视学习，比起竞争更以成长为动力。这是心理学家Carol Dweck所说的成长型思维典型。',
      'zh-TW': '比起他人結果更關注自身進步，比起輸贏更重視學習，比起競爭更以成長為動力。這是心理學家Carol Dweck所說的成長型思維典型。',
      vi: 'Tập trung vào sự phát triển của mình hơn kết quả người khác, coi học hỏi quan trọng hơn thua, và lấy tăng trưởng làm động lực hơn cạnh tranh. Đây là growth mindset điển hình theo Carol Dweck.',
      id: 'Fokus pada perkembangan sendiri lebih dari hasil orang lain, menghargai belajar lebih dari kalah, dan termotivasi pertumbuhan lebih dari kompetisi. Ini growth mindset klasik ala Carol Dweck.',
    }),
    competitiveType: localeMap({
      ko: '자기성장형 🌱',
      en: 'Self-Growth Type 🌱',
      ja: '自己成長型 🌱',
      'zh-CN': '自我成长型 🌱',
      'zh-TW': '自我成長型 🌱',
      vi: 'Kiểu tự phát triển 🌱',
      id: 'Tipe Self-Growth 🌱',
    }),
    competitiveKeywords: localeMap({
      ko: '성장·자기 기준·발전·배움·내적 동기',
      en: 'Growth · Self-standard · Progress · Learning · Inner drive',
      ja: '成長・自己基準・発展・学び・内的動機',
      'zh-CN': '成长·自我标准·进步·学习·内在动力',
      'zh-TW': '成長·自我標準·進步·學習·內在動力',
      vi: 'Tăng trưởng · Chuẩn bản thân · Tiến bộ · Học hỏi · Động lực nội tại',
      id: 'Pertumbuhan · Standar diri · Kemajuan · Belajar · Drive internal',
    }),
    strengths: localeMap({
      ko: '타인의 결과에 흔들리지 않고 장기적으로 꾸준히 성장하는 능력\n경쟁에서 져도 배움을 찾아내는 건강한 패배 수용 방식\n내적 동기가 강해서 외부 보상이 없어도 지속 가능',
      en: 'Ability to grow steadily long-term without being shaken by others\' results\nHealthy way to accept defeat by finding lessons\nStrong inner drive that keeps going even without external rewards',
      ja: '他人の結果に揺れず長期的に着実に成長する能力\n負けても学びを見出す健全な敗北受容\n外的報酬がなくても続けられる強い内的動機',
      'zh-CN': '不会因他人结果动摇，能长期稳定成长\n失败后也能找到学习点，健康的失败接受方式\n内在动力强，没有外部奖励也能持续',
      'zh-TW': '不會因他人結果動搖，能長期穩定成長\n失敗後也能找到學習點，健康的失敗接受方式\n內在動力強，沒有外部獎勵也能持續',
      vi: 'Khả năng tăng trưởng ổn định dài hạn mà không bị lay chuyển bởi kết quả người khác\nCách tiếp nhận thua lành mạnh bằng cách tìm bài học\nĐộng lực nội tại mạnh, vẫn duy trì được dù không có phần thưởng bên ngoài',
      id: 'Kemampuan tumbuh stabil jangka panjang tanpa goyah oleh hasil orang lain\nCara sehat menerima kekalahan dengan menemukan pelajaran\nDrive internal kuat yang tetap jalan tanpa reward eksternal',
    }),
    cautions: localeMap({
      ko: '외부 경쟁 상황에서 상대적으로 덜 불타오를 수 있음. 필요할 때 경쟁 자극도 활용하면 효과적\n자기 기준만 있다 보면 시장·환경 기준과 괴리가 생길 수 있음. 가끔 외부 기준도 참고하기',
      en: 'May burn less intensely in external competition. Using competitive stimulation when needed can help\nRelying only on self-standards can drift from market or environment standards. Check external benchmarks sometimes',
      ja: '外部競争では相対的に燃えにくい。必要な時に競争刺激も活用すると効果的\n自己基準だけだと市場・環境基準とズレることがある。時々外部基準も参考に',
      'zh-CN': '在外部竞争中相对不容易燃起来，需要时利用竞争刺激会更有效\n只有自我标准可能与市场/环境标准脱节，偶尔也要参考外部标准',
      'zh-TW': '在外部競爭中相對不容易燃起來，需要時利用競爭刺激會更有效\n只有自我標準可能與市場/環境標準脫節，偶爾也要參考外部標準',
      vi: 'Có thể ít bùng nổ hơn trong cạnh tranh bên ngoài. Dùng kích thích cạnh tranh khi cần sẽ hiệu quả\nChỉ có chuẩn cá nhân có thể lệch khỏi chuẩn thị trường/môi trường. Thỉnh thoảng tham khảo chuẩn bên ngoài',
      id: 'Bisa kurang membara di kompetisi eksternal. Stimulasi kompetitif saat perlu bisa membantu\nHanya standar diri bisa drift dari standar pasar/lingkungan. Sesekali cek benchmark eksternal',
    }),
    bestEnvironments: localeMap({
      ko: '자기 계발·장기 목표·기술 습득·예술·연구 분야',
      en: 'Self-development · Long-term goals · Skill acquisition · Art · Research',
      ja: '自己啓発・長期目標・スキル習得・芸術・研究分野',
      'zh-CN': '自我提升·长期目标·技能习得·艺术·研究',
      'zh-TW': '自我提升·長期目標·技能習得·藝術·研究',
      vi: 'Tự phát triển · Mục tiêu dài hạn · Học kỹ năng · Nghệ thuật · Nghiên cứu',
      id: 'Self-development · Target jangka panjang · Skill acquisition · Seni · Riset',
    }),
    sportsGameTypes: localeMap({
      ko: '개인 기록 경신형 (마라톤·수영·클라이밍)·RPG 레벨업형 게임',
      en: 'Personal record sports (marathon · swimming · climbing) · RPG level-up games',
      ja: '個人記録更新型（マラソン・水泳・クライミング）・RPGレベルアップ型ゲーム',
      'zh-CN': '个人纪录型（马拉松·游泳·攀岩）·RPG升级型游戏',
      'zh-TW': '個人紀錄型（馬拉松·游泳·攀岩）·RPG升級型遊戲',
      vi: 'Thể thao phá kỷ lục cá nhân (marathon · bơi · leo núi) · Game RPG level-up',
      id: 'Olahraga rekor pribadi (marathon · renang · climbing) · Game RPG level-up',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '어제의 나를 이기는 것이 가장 지속 가능한 경쟁입니다. 이 방식으로 10년을 가면 아무도 따라잡기 어렵습니다',
      en: 'Beating yesterday\'s you is the most sustainable competition. Keep this up for 10 years and no one will catch you easily',
      ja: '昨日の自分を超えることが最も持続可能な競争です。この方式で10年続ければ、誰も簡単には追いつけません',
      'zh-CN': '打败昨天的自己，是最可持续的竞争。用这种方式走10年，很难有人轻易追上',
      'zh-TW': '打敗昨天的自己，是最可持續的競爭。用這種方式走10年，很難有人輕易追上',
      vi: 'Vượt qua bản thân hôm qua là cuộc cạnh tranh bền vững nhất. Giữ cách này 10 năm thì khó ai bắt kịp',
      id: 'Mengalahkan dirimu kemarin adalah kompetisi paling sustainable. Jalani 10 tahun dengan cara ini, sulit ada yang mengejar',
    }),
    shareLine: localeMap({
      ko: '내 경쟁심 DNA: 자기성장형 🌱 어제의 나와 경쟁하는 유형이래... 남보다 내가 더 나아지는 게 더 중요하다는 거 맞음 → 경쟁심 결과 너는 어떤 유형이야?',
      en: 'My competitive DNA: Self-Growth Type 🌱 They say I compete with yesterday\'s me... caring more about improving myself than others is so true → What\'s your competitive DNA type?',
      ja: '私の競争心DNA：自己成長型 🌱 昨日の自分と競争するタイプらしい…他人より自分が成長することの方が大事、当たり → あなたの競争心DNAはどのタイプ？',
      'zh-CN': '我的竞争心DNA：自我成长型 🌱 说是和昨天的自己竞争的类型…比起别人更在意自己进步，太准了 → 你的竞争心DNA是什么类型？',
      'zh-TW': '我的競爭心DNA：自我成長型 🌱 說是和昨天的自己競爭的類型…比起別人更在意自己進步，太準了 → 你的競爭心DNA是什麼類型？',
      vi: 'DNA cạnh tranh của tôi: Kiểu tự phát triển 🌱 Bảo tôi cạnh tranh với bản thân hôm qua... quan tâm tự phát triển hơn người khác, đúng quá → Bạn thuộc kiểu nào?',
      id: 'DNA daya saingku: Tipe Self-Growth 🌱 Katanya aku bersaing dengan diri kemarin... lebih peduli perkembangan sendiri daripada orang lain, bener → Kamu tipe apa?',
    }),
  },
  {
    type: "Type3",
    emoji: "⚡",
    title: localeMap({
      ko: '경쟁을 즐기되 결과에 담담한, 건강한 승부형',
      en: 'Healthy Competitor Type ⚡',
      ja: '健全な勝負型 ⚡',
      'zh-CN': '健康胜负型 ⚡',
      'zh-TW': '健康勝負型 ⚡',
      vi: 'Kiểu cạnh tranh lành mạnh ⚡',
      id: 'Tipe Healthy Competitor ⚡',
    }),
    competitiveDna: localeMap({
      ko: '보통 / 이기고 싶지만 지는 것도 받아들이는 균형형',
      en: 'Moderate / Balanced type that wants to win but accepts losing',
      ja: '普通 / 勝ちたいが負けも受け入れるバランス型',
      'zh-CN': '普通 / 想赢但也接受输的平衡型',
      'zh-TW': '普通 / 想贏但也接受輸的平衡型',
      vi: 'Trung bình / Muốn thắng nhưng cũng chấp nhận thua',
      id: 'Sedang / Seimbang: ingin menang tapi menerima kalah',
    }),
    quote: localeMap({
      ko: '당신은 경쟁을 즐깁니다. 이기고 싶은 마음도 있지만 지는 것도 경쟁의 일부라는 걸 압니다.',
      en: 'You enjoy competition. You want to win, but you also know losing is part of it.',
      ja: 'あなたは競争を楽しみます。勝ちたい気持ちもありますが、負けることも競争の一部だと分かっています。',
      'zh-CN': '你享受竞争，想赢，但也知道输是竞争的一部分。',
      'zh-TW': '你享受競爭，想贏，但也知道輸是競爭的一部分。',
      vi: 'Bạn thích cạnh tranh. Bạn muốn thắng, nhưng cũng biết thua là một phần của nó.',
      id: 'Kamu menikmati kompetisi. Ingin menang, tapi juga tahu kalah bagian darinya.',
    }),
    description: localeMap({
      ko: '경쟁 상황에서 집중력이 올라가고 이기고 싶은 마음이 생기지만 패배를 담담하게 받아들이고 다음 기회를 준비하는 균형 잡힌 경쟁심을 가진 타입입니다. 경쟁심이 스트레스가 아닌 활력이 됩니다.',
      en: 'Your focus rises in competitive situations, you want to win, yet you accept defeat calmly and prepare for the next chance. You have balanced competitiveness that becomes energy, not stress.',
      ja: '競争状況で集中力が上がり、勝ちたい気持ちも生まれる一方で、敗北を淡々と受け入れ次の機会を準備するバランスの取れた競争心を持つタイプです。競争心はストレスではなく活力になります。',
      'zh-CN': '竞争时专注力上升，也想赢，但能平静接受失败并准备下一次机会。竞争心不是压力，而是活力。',
      'zh-TW': '競爭時專注力上升，也想贏，但能平靜接受失敗並準備下一次機會。競爭心不是壓力，而是活力。',
      vi: 'Tập trung tăng trong cạnh tranh, muốn thắng, nhưng chấp nhận thua bình tĩnh và chuẩn bị cơ hội tiếp theo. Tính cạnh tranh cân bằng trở thành năng lượng, không phải stress.',
      id: 'Fokus naik dalam kompetisi, ingin menang, tapi menerima kekalahan dengan tenang dan siapkan peluang berikutnya. Daya saing seimbang jadi energi, bukan stress.',
    }),
    competitiveType: localeMap({
      ko: '건강한 승부형 ⚡',
      en: 'Healthy Competitor Type ⚡',
      ja: '健全な勝負型 ⚡',
      'zh-CN': '健康胜负型 ⚡',
      'zh-TW': '健康勝負型 ⚡',
      vi: 'Kiểu cạnh tranh lành mạnh ⚡',
      id: 'Tipe Healthy Competitor ⚡',
    }),
    competitiveKeywords: localeMap({
      ko: '즐김·균형·승부욕·성숙·회복력',
      en: 'Enjoyment · Balance · Drive · Maturity · Resilience',
      ja: '楽しさ・バランス・勝負心・成熟・回復力',
      'zh-CN': '享受·平衡·胜负欲·成熟·恢复力',
      'zh-TW': '享受·平衡·勝負欲·成熟·恢復力',
      vi: 'Thích thú · Cân bằng · Khát thắng · Trưởng thành · Phục hồi',
      id: 'Enjoy · Balance · Drive · Maturity · Resilience',
    }),
    strengths: localeMap({
      ko: '경쟁에서 좋은 성과를 내면서도 관계를 유지하는 균형 능력\n패배에서 배움을 찾고 빠르게 회복하는 탄력성\n팀 경쟁에서도 개인 경쟁에서도 좋은 파트너가 됨',
      en: 'Balanced ability to perform well in competition while keeping relationships\nResilience to learn from defeat and recover quickly\nGood partner in both team and individual competition',
      ja: '競争で良い成果を出しながら関係も維持するバランス能力\n敗北から学びを見つけ素早く回復するタフさ\nチーム競争でも個人競争でも良いパートナーになれる',
      'zh-CN': '竞争中表现好又能维持关系的平衡能力\n从失败中学习并快速恢复的韧性\n团队和个人竞争里都是好搭档',
      'zh-TW': '競爭中表現好又能維持關係的平衡能力\n從失敗中學習並快速恢復的韌性\n團隊和個人競爭裡都是好搭檔',
      vi: 'Cân bằng giữa thành tích tốt và duy trì quan hệ\nPhục hồi nhanh, học từ thất bại\nLà đối tác tốt cả trong cạnh tranh đội và cá nhân',
      id: 'Kemampuan seimbang: perform baik sambil jaga relasi\nResilience belajar dari kekalahan dan pulih cepat\nPartner bagus di kompetisi tim maupun individual',
    }),
    cautions: localeMap({
      ko: '막상막하 상황에서 더 집중력이 올라가는 패턴\n이기면 기쁘고 지면 아쉽지만 그 감정이 오래 가지 않음',
      en: 'Focus rises more in neck-and-neck situations\nHappy when winning, regretful when losing, but those feelings do not last long',
      ja: '互角の状況でより集中力が上がるパターン\n勝てば嬉しく、負ければ残念だが、その感情は長く続かない',
      'zh-CN': '势均力敌时专注力更高\n赢了开心，输了遗憾，但情绪不会持续太久',
      'zh-TW': '勢均力敵時專注力更高\n贏了開心，輸了遺憾，但情緒不會持續太久',
      vi: 'Tập trung tăng hơn khi cạnh tranh sát sao\nThắng thì vui, thua thì tiếc nhưng cảm xúc không kéo dài',
      id: 'Fokus naik lebih saat seimbang\nSenang saat menang, sedih saat kalah, tapi emosi tidak lama',
    }),
    bestEnvironments: localeMap({
      ko: '팀 스포츠·리그·대회·경쟁이 있는 직무 환경',
      en: 'Team sports · Leagues · Tournaments · Jobs with healthy competition',
      ja: 'チームスポーツ・リーグ・大会・競争がある職務環境',
      'zh-CN': '团队运动·联赛·大赛·有竞争的工作环境',
      'zh-TW': '團隊運動·聯賽·大賽·有競爭的工作環境',
      vi: 'Thể thao đội · Giải đấu · Hội thi · Môi trường công việc có cạnh tranh',
      id: 'Tim sports · Liga · Turnamen · Pekerjaan dengan kompetisi sehat',
    }),
    sportsGameTypes: localeMap({
      ko: '팀 스포츠(축구·농구)·멀티플레이 게임·보드게임',
      en: 'Team sports (soccer · basketball) · Multiplayer games · Board games',
      ja: 'チームスポーツ（サッカー・バスケ）・マルチプレイゲーム・ボードゲーム',
      'zh-CN': '团队运动（足球·篮球）·多人游戏·桌游',
      'zh-TW': '團隊運動（足球·籃球）·多人遊戲·桌遊',
      vi: 'Thể thao đội (bóng đá · bóng rổ) · Game multiplayer · Board game',
      id: 'Tim sports (sepak bola · basket) · Game multiplayer · Board game',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '당신의 경쟁심은 가장 오래 지속 가능한 농도입니다. 이 균형을 유지하면 어떤 경쟁 환경에서도 오래 살아남습니다',
      en: 'Your competitiveness is the most sustainable level. Keep this balance and you will survive any competitive environment for a long time',
      ja: 'あなたの競争心は最も持続可能な濃度です。このバランスを保てば、どんな競争環境でも長く生き残れます',
      'zh-CN': '你的竞争心是最可持续的浓度，保持这个平衡，在任何竞争环境都能长久生存',
      'zh-TW': '你的競爭心是最可持續的濃度，保持這個平衡，在任何競爭環境都能長久生存',
      vi: 'Tính cạnh tranh của bạn ở mức bền vững nhất. Giữ cân bằng này thì sống sót lâu trong mọi môi trường cạnh tranh',
      id: 'Daya saingmu di level paling sustainable. Jaga balance ini dan kamu akan survive lama di lingkungan kompetitif apa pun',
    }),
    shareLine: localeMap({
      ko: '내 경쟁심 DNA: 건강한 승부형 ⚡ 이기고 싶지만 져도 담담한 유형이래... 막상막하 상황에서 집중력 올라가는 거 맞음 ㅋㅋ → 경쟁심 결과 너는 몇 점이야?',
      en: 'My competitive DNA: Healthy Competitor Type ⚡ They say I want to win but stay calm when I lose... focus rising in close matches is so true lol → What\'s your competitive DNA score?',
      ja: '私の競争心DNA：健全な勝負型 ⚡ 勝ちたいけど負けても淡々タイプらしい…互角の時に集中力上がるの当たり ㅋㅋ → あなたの競争心DNAは何点？',
      'zh-CN': '我的竞争心DNA：健康胜负型 ⚡ 说是想赢但输了也淡定…势均力敌时专注力上升太准了哈哈 → 你的竞争心DNA几分？',
      'zh-TW': '我的競爭心DNA：健康勝負型 ⚡ 說是想贏但輸了也淡定…勢均力敵時專注力上升太準了哈哈 → 你的競爭心DNA幾分？',
      vi: 'DNA cạnh tranh của tôi: Kiểu cạnh tranh lành mạnh ⚡ Bảo muốn thắng nhưng thua vẫn bình tĩnh... tập trung tăng khi sát sao, đúng quá haha → Bạn được mấy điểm?',
      id: 'DNA daya saingku: Tipe Healthy Competitor ⚡ Katanya ingin menang tapi kalah tetap tenang... fokus naik saat seimbang, bener wkwk → Skor DNA daya saingmu berapa?',
    }),
  },
  {
    type: "Type4",
    emoji: "🔥",
    title: localeMap({
      ko: '불타오르면 멈추지 않는 사람, 열정 승부사형',
      en: 'Passionate Competitor Type 🔥',
      ja: '情熱勝負師型 🔥',
      'zh-CN': '热情胜负者型 🔥',
      'zh-TW': '熱情勝負者型 🔥',
      vi: 'Kiểu đam mê cạnh tranh 🔥',
      id: 'Tipe Passionate Competitor 🔥',
    }),
    competitiveDna: localeMap({
      ko: '높음 / 경쟁에서 강하게 불타오르고 이기기 위해 전략을 짜는 타입',
      en: 'High / Burns strongly in competition and plans strategy to win',
      ja: '高い / 競争で強く燃え上がり、勝つための戦略を立てるタイプ',
      'zh-CN': '高 / 在竞争中强烈燃烧，并制定取胜策略的类型',
      'zh-TW': '高 / 在競爭中強烈燃燒，並制定取勝策略的類型',
      vi: 'Cao / Bùng cháy mạnh trong cạnh tranh và lập chiến lược để thắng',
      id: 'Tinggi / Membara kuat dalam kompetisi dan merencanakan strategi untuk menang',
    }),
    quote: localeMap({
      ko: '당신은 경쟁이 시작되면 다릅니다. 이기고 싶은 마음이 집중력을 극대화하고 전략을 만들어냅니다.',
      en: 'When competition starts, you become different. The will to win maximizes focus and creates strategy.',
      ja: '競争が始まるとあなたは変わります。勝ちたい気持ちが集中力を最大化し、戦略を生み出します。',
      'zh-CN': '竞争一开始你就变了，想赢的心会把专注力拉满，也会催生策略。',
      'zh-TW': '競爭一開始你就變了，想贏的心會把專注力拉滿，也會催生策略。',
      vi: 'Khi cạnh tranh bắt đầu, bạn khác đi. Ý chí thắng tối đa hóa tập trung và tạo ra chiến lược.',
      id: 'Saat kompetisi dimulai, kamu berubah. Keinginan menang memaksimalkan fokus dan menciptakan strategi.',
    }),
    description: localeMap({
      ko: '경쟁 상황에서 아드레날린이 솟고 상대방을 분석하고 전략을 세우는 것 자체를 즐기며 막상막하의 긴장감 속에서 최선을 내는 순간이 짜릿한 타입입니다. 경쟁이 있어야 잠재력이 터지는 유형입니다.',
      en: 'Adrenaline rises in competition, you enjoy analyzing opponents and building strategy, and giving your best in neck-and-neck tension feels thrilling. You are the type whose potential explodes when competition exists.',
      ja: '競争状況でアドレナリンが湧き、相手を分析し戦略を立てること自体を楽しみ、互角の緊張感の中で最善を出す瞬間が快感なタイプです。競争があるからこそ潜在能力が爆発するタイプです。',
      'zh-CN': '竞争时肾上腺素上升，享受分析对手和制定策略，在势均力敌的紧张感中全力以赴的瞬间很刺激。你是需要竞争才能爆发潜力的人。',
      'zh-TW': '競爭時腎上腺素上升，享受分析對手和制定策略，在勢均力敵的緊張感中全力以赴的瞬間很刺激。你是需要競爭才能爆發潛力的人。',
      vi: 'Adrenaline tăng trong cạnh tranh, thích phân tích đối thủ và lập chiến lược, và khoảnh khắc cố hết sức trong căng thẳng sát sao rất kích thích. Bạn là kiểu người tiềm năng bùng nổ khi có cạnh tranh.',
      id: 'Adrenalin naik dalam kompetisi, menikmati analisis lawan dan strategi, dan momen memberikan yang terbaik dalam ketegangan seimbang terasa thrilling. Tipe yang potensinya meledak saat ada kompetisi.',
    }),
    competitiveType: localeMap({
      ko: '열정 승부사형 🔥',
      en: 'Passionate Competitor Type 🔥',
      ja: '情熱勝負師型 🔥',
      'zh-CN': '热情胜负者型 🔥',
      'zh-TW': '熱情勝負者型 🔥',
      vi: 'Kiểu đam mê cạnh tranh 🔥',
      id: 'Tipe Passionate Competitor 🔥',
    }),
    competitiveKeywords: localeMap({
      ko: '열정·전략·집중·승부욕·분석',
      en: 'Passion · Strategy · Focus · Drive · Analysis',
      ja: '情熱・戦略・集中・勝負心・分析',
      'zh-CN': '热情·策略·专注·胜负欲·分析',
      'zh-TW': '熱情·策略·專注·勝負欲·分析',
      vi: 'Đam mê · Chiến lược · Tập trung · Khát thắng · Phân tích',
      id: 'Passion · Strategi · Fokus · Drive · Analisis',
    }),
    strengths: localeMap({
      ko: '경쟁 상황에서 퍼포먼스가 극대화됨. 압박 상황에서 오히려 잘함\n이기기 위한 준비와 분석 능력이 탁월함\n경쟁이 있는 환경에서 주도권을 잡는 경향이 있음',
      en: 'Performance maximizes in competition. You do better under pressure\nExcellent preparation and analysis to win\nTendency to take initiative in competitive environments',
      ja: '競争状況でパフォーマンスが最大化。プレッシャー下でこそ上手くなる\n勝つための準備と分析能力が優れている\n競争がある環境で主導権を握る傾向',
      'zh-CN': '竞争时表现最大化，压力下反而更强\n为赢而做的准备和分析能力出色\n在竞争环境中容易掌握主导权',
      'zh-TW': '競爭時表現最大化，壓力下反而更強\n為贏而做的準備和分析能力出色\n在競爭環境中容易掌握主導權',
      vi: 'Hiệu suất tối đa trong cạnh tranh. Áp lực càng cao càng làm tốt\nChuẩn bị và phân tích để thắng xuất sắc\nXu hướng nắm chủ động trong môi trường cạnh tranh',
      id: 'Performa maksimal dalam kompetisi. Lebih bagus di bawah tekanan\nPersiapan dan analisis untuk menang sangat bagus\nCenderung ambil inisiatif di lingkungan kompetitif',
    }),
    cautions: localeMap({
      ko: '패배 후 아쉬움이 꽤 오래 남는 편. 결과에 감정 소모가 있을 수 있음\n경쟁이 없는 환경에서 동기부여가 떨어지는 경향. 인위적인 경쟁 구도를 만들면 도움이 됨\n경쟁심이 강한 만큼 주변 사람에게 부담을 주지 않도록 의식하기',
      en: 'Regret after losing can linger. Emotional cost from results is possible\nMotivation may drop without competition. Creating artificial rivalry can help\nBe mindful not to burden others with strong competitiveness',
      ja: '敗北後の悔しさがかなり長く残る。結果への感情消耗がある\n競争がない環境では動機が下がる。人工的な競争構図を作ると助けになる\n競争心が強い分、周囲に負担をかけないよう意識する',
      'zh-CN': '失败后遗憾会持续较久，结果可能带来情绪消耗\n没有竞争时动力会下降，制造竞争结构会有帮助\n竞争心强，也要注意别给身边人带来负担',
      'zh-TW': '失敗後遺憾會持續較久，結果可能帶來情緒消耗\n沒有競爭時動力會下降，製造競爭結構會有幫助\n競爭心強，也要注意別給身邊人帶來負擔',
      vi: 'Tiếc nuối sau thua có thể kéo dài. Có thể tiêu hao cảm xúc vì kết quả\nĐộng lực giảm khi không có cạnh tranh. Tạo đối thủ giả có thể giúp\nCẩn thận không làm người xung quanh áp lực vì tính cạnh tranh mạnh',
      id: 'Penyesalan setelah kalah bisa lama. Ada biaya emosional dari hasil\nMotivasi turun tanpa kompetisi. Membuat rivalry buatan bisa membantu\nWaspadai agar daya saing kuat tidak membebani orang sekitar',
    }),
    bestEnvironments: localeMap({
      ko: '영업·스포츠·경쟁이 있는 게임·대회·리그',
      en: 'Sales · Sports · Competitive games · Tournaments · Leagues',
      ja: '営業・スポーツ・競争のあるゲーム・大会・リーグ',
      'zh-CN': '销售·运动·有竞争的游戏·大赛·联赛',
      'zh-TW': '銷售·運動·有競爭的遊戲·大賽·聯賽',
      vi: 'Bán hàng · Thể thao · Game cạnh tranh · Giải đấu · Giải',
      id: 'Sales · Olahraga · Game kompetitif · Turnamen · Liga',
    }),
    sportsGameTypes: localeMap({
      ko: '격투게임·전략 게임(스타크래프트·체스)·1:1 스포츠(테니스·배드민턴)',
      en: 'Fighting games · Strategy games (StarCraft · chess) · 1:1 sports (tennis · badminton)',
      ja: '格闘ゲーム・戦略ゲーム（スタークラフト・チェス）・1対1スポーツ（テニス・バドミントン）',
      'zh-CN': '格斗游戏·策略游戏（星际争霸·国际象棋）·1对1运动（网球·羽毛球）',
      'zh-TW': '格鬥遊戲·策略遊戲（星際爭霸·國際象棋）·1對1運動（網球·羽毛球）',
      vi: 'Game đối kháng · Game chiến thuật (StarCraft · cờ vua) · Thể thao 1:1 (tennis · cầu lông)',
      id: 'Fighting game · Strategy game (StarCraft · catur) · Olahraga 1:1 (tennis · badminton)',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '당신은 경쟁이 있어야 진짜 실력이 나오는 사람입니다. 그 에너지를 잘 방향 잡으면 어디서든 두드러집니다',
      en: 'You are someone whose real skill shows when competition exists. Channel that energy well and you will stand out anywhere',
      ja: 'あなたは競争があってこそ本当の実力が出る人です。そのエネルギーをうまく方向づければ、どこでも目立ちます',
      'zh-CN': '你是需要竞争才会拿出真正实力的人，把能量导向正确方向，到哪里都会突出',
      'zh-TW': '你是需要競爭才會拿出真正實力的人，把能量導向正確方向，到哪裡都會突出',
      vi: 'Bạn là người chỉ thể hiện thự lực thật khi có cạnh tranh. Định hướng năng lượng đó tốt thì nổi bật ở đâu cũng được',
      id: 'Kamu orang yang skill sejati muncul saat ada kompetisi. Arahkan energi itu dengan baik dan kamu akan menonjol di mana pun',
    }),
    shareLine: localeMap({
      ko: '내 경쟁심 DNA: 열정 승부사형 🔥 경쟁 시작되면 불타오르는 유형이래... 전략 짜는 것 자체가 즐겁다는 거 완전 맞음 → 경쟁심 결과 스포츠·게임 유저 다 해봐',
      en: 'My competitive DNA: Passionate Competitor Type 🔥 They say I ignite when competition starts... enjoying strategy itself is so me → All sports & gaming users, try this competitive DNA test',
      ja: '私の競争心DNA：情熱勝負師型 🔥 競争が始まると燃えるタイプらしい…戦略を立てること自体が楽しい、完全に当たり → スポーツ・ゲームユーザー全員やってみて',
      'zh-CN': '我的竞争心DNA：热情胜负者型 🔥 说是竞争一开始就会燃烧的类型…享受制定策略太准了 → 体育·游戏用户都来测测',
      'zh-TW': '我的競爭心DNA：熱情勝負者型 🔥 說是競爭一開始就會燃燒的類型…享受制定策略太準了 → 體育·遊戲用戶都來測測',
      vi: 'DNA cạnh tranh của tôi: Kiểu đam mê cạnh tranh 🔥 Bảo tôi bùng lên khi cạnh tranh bắt đầu... thích lập chiến lược, đúng quá → Fan thể thao & game thử hết đi',
      id: 'DNA daya saingku: Tipe Passionate Competitor 🔥 Katanya aku membara saat kompetisi dimulai... suka strategi itu banget aku → Semua user sports & gaming coba deh',
    }),
  },
  {
    type: "Type5",
    emoji: "⚔️",
    title: localeMap({
      ko: '경쟁이 삶의 에너지원인 사람, 극강 경쟁형',
      en: 'Extreme Competitor Type ⚔️',
      ja: '極限競争型 ⚔️',
      'zh-CN': '极致竞争型 ⚔️',
      'zh-TW': '極致競爭型 ⚔️',
      vi: 'Kiểu cạnh tranh cực đoan ⚔️',
      id: 'Tipe Extreme Competitor ⚔️',
    }),
    competitiveDna: localeMap({
      ko: '매우 높음 / 경쟁 자체가 살아있다는 느낌을 주는 타입',
      en: 'Very high / Competition itself makes you feel truly alive',
      ja: '非常に高い / 競争そのものが生きている実感を与えるタイプ',
      'zh-CN': '非常高 / 竞争本身就会让你感到真正活着的类型',
      'zh-TW': '非常高 / 競爭本身就會讓你感到真正活著的類型',
      vi: 'Rất cao / Bản thân cạnh tranh khiến bạn cảm thấy thực sự sống',
      id: 'Sangat tinggi / Kompetisi sendiri membuatmu merasa benar-benar hidup',
    }),
    quote: localeMap({
      ko: '당신에게 경쟁은 취미가 아닙니다. 경쟁이 있어야 진짜 살아있는 느낌이 납니다.',
      en: 'To you, competition is not a hobby. You only feel truly alive when there is competition.',
      ja: 'あなたにとって競争は趣味ではありません。競争があってこそ本当に生きている感覚が生まれます。',
      'zh-CN': '对你来说，竞争不是爱好。只有有竞争时，你才会感到真正活着。',
      'zh-TW': '對你來說，競爭不是愛好。只有有競爭時，你才會感到真正活著。',
      vi: 'Với bạn, cạnh tranh không phải sở thích. Chỉ khi có cạnh tranh bạn mới cảm thấy thực sự sống.',
      id: 'Bagimu, kompetisi bukan hobi. Hanya saat ada kompetisi kamu merasa benar-benar hidup.',
    }),
    description: localeMap({
      ko: '경쟁이 없는 상황이 오히려 불편하고 지는 것을 받아들이는 것이 매우 어려우며 어떤 상황에서도 상대방을 분석하고 이길 방법을 찾는 것이 자동으로 작동하는 타입입니다. 이 수준의 경쟁심은 엄청난 성과를 만들어내는 동시에 관리가 필요한 에너지입니다.',
      en: 'Situations without competition feel uncomfortable, accepting defeat is very hard, and analyzing opponents and finding ways to win runs automatically in any situation. This level of competitiveness creates huge results but also needs management.',
      ja: '競争がない状況がむしろ不快で、負けを受け入れることが非常に難しく、どんな状況でも相手を分析し勝つ方法を探すことが自動的に作動するタイプです。このレベルの競争心は大きな成果を生むと同時に、管理が必要なエネルギーでもあります。',
      'zh-CN': '没有竞争反而让你不自在，很难接受失败，任何情况下都会自动分析对手、寻找取胜方法。这种竞争心会创造巨大成果，也需要被管理。',
      'zh-TW': '沒有競爭反而讓你不自在，很難接受失敗，任何情況下都會自動分析對手、尋找取勝方法。這種競爭心會創造巨大成果，也需要被管理。',
      vi: 'Không có cạnh tranh lại khó chịu, rất khó chấp nhận thua, và phân tích đối thủ tìm cách thắng tự động chạy trong mọi tình huống. Mức cạnh tranh này tạo thành tích lớn nhưng cũng cần quản lý.',
      id: 'Situasi tanpa kompetisi justru tidak nyaman, menerima kekalahan sangat sulit, dan analisis lawan plus cara menang berjalan otomatis. Level daya saing ini hasilkan prestasi besar tapi juga perlu dikelola.',
    }),
    competitiveType: localeMap({
      ko: '극강 경쟁형 ⚔️',
      en: 'Extreme Competitor Type ⚔️',
      ja: '極限競争型 ⚔️',
      'zh-CN': '极致竞争型 ⚔️',
      'zh-TW': '極致競爭型 ⚔️',
      vi: 'Kiểu cạnh tranh cực đoan ⚔️',
      id: 'Tipe Extreme Competitor ⚔️',
    }),
    competitiveKeywords: localeMap({
      ko: '승리·압도·준비·분석·지지 않음',
      en: 'Victory · Dominance · Preparation · Analysis · Never lose',
      ja: '勝利・圧倒・準備・分析・負けない',
      'zh-CN': '胜利·压倒·准备·分析·不接受输',
      'zh-TW': '勝利·壓倒·準備·分析·不接受輸',
      vi: 'Chiến thắng · Áp đảo · Chuẩn bị · Phân tích · Không chấp nhận thua',
      id: 'Kemenangan · Dominasi · Persiapan · Analisis · Tidak kalah',
    }),
    strengths: localeMap({
      ko: '극도의 집중력과 준비성. 경쟁에서 최대한 유리한 위치를 만드는 능력\n아무도 이기지 못했다는 상황에서 오히려 동기부여가 올라감\n역경·역전 상황에서 포기하지 않는 끈질김',
      en: 'Extreme focus and preparation. Ability to create the most favorable position in competition\nMotivation rises when no one else has won\nRelentless persistence in adversity and comeback situations',
      ja: '極度の集中力と準備性。競争で最大限有利な位置を作る能力\n誰も勝てなかった状況でこそ動機が上がる\n逆境・逆転状況でも諦めない粘り強さ',
      'zh-CN': '极度专注与准备，能在竞争中创造最有利位置\n在“还没人赢过”的情况下反而更有动力\n逆境与逆转中也不放弃',
      'zh-TW': '極度專注與準備，能在競爭中創造最有利位置\n在「還沒人贏過」的情況下反而更有動力\n逆境與逆轉中也不放棄',
      vi: 'Tập trung và chuẩn bị cực cao. Khả năng tạo vị thế thuận lợi nhất\nĐộng lực tăng khi chưa ai thắng\nBền bỉ không bỏ cuộc trong nghịch cảnh và lật kèo',
      id: 'Fokus dan persiapan ekstrem. Kemampuan membuat posisi paling menguntungkan\nMotivasi naik saat belum ada yang menang\nKegigihan tanpa menyerah di adversity dan comeback',
    }),
    cautions: localeMap({
      ko: '패배를 받아들이기 어려워 심리적 소모가 클 수 있음\n경쟁심이 관계에 영향을 줄 수 있음. 협력이 필요한 상황에서도 경쟁 프레임으로 보는 경향\n이기는 것 자체가 목적이 되면 방향이 흐려질 수 있음. 무엇을 위해 이기는지를 주기적으로 점검하기',
      en: 'Hard to accept defeat, so psychological cost can be high\nCompetitiveness can affect relationships. May see cooperation through a competitive frame\nIf winning becomes the goal itself, direction can blur. Periodically check what you are winning for',
      ja: '敗北を受け入れにくく心理的消耗が大きい\n競争心が人間関係に影響する。協力が必要な場面でも競争フレームで見る傾向\n勝つこと自体が目的になると方向がぼやける。何のために勝つのか定期的に点検',
      'zh-CN': '难接受失败，心理消耗可能很大\n竞争心可能影响关系，合作场景也会用竞争框架看\n若赢本身变成目的，方向会模糊，要定期检查为了什么而赢',
      'zh-TW': '難接受失敗，心理消耗可能很大\n競爭心可能影響關係，合作場景也會用競爭框架看\n若贏本身變成目的，方向會模糊，要定期檢查為了什麼而贏',
      vi: 'Khó chấp nhận thua nên tốn nhiều tâm lý\nTính cạnh tranh có thể ảnh hưởng quan hệ. Dễ nhìn hợp tác qua lăng kính cạnh tranh\nNếu thắng thành mục tiêu, hướng đi mờ đi. Định kỳ hỏi mình thắng để làm gì',
      id: 'Sulit terima kekalahan, biaya psikologis bisa besar\nDaya saing bisa memengaruhi relasi. Cenderung lihat kolaborasi lewat frame kompetitif\nJika menang jadi tujuan, arah bisa blur. Cek berkala menang untuk apa',
    }),
    bestEnvironments: localeMap({
      ko: '프로 스포츠·e스포츠·영업·투자·경쟁이 치열한 분야',
      en: 'Pro sports · Esports · Sales · Investment · Highly competitive fields',
      ja: 'プロスポーツ・eスポーツ・営業・投資・競争が激しい分野',
      'zh-CN': '职业体育·电竞·销售·投资·竞争激烈的领域',
      'zh-TW': '職業體育·電競·銷售·投資·競爭激烈的領域',
      vi: 'Thể thao chuyên nghiệp · Esports · Bán hàng · Đầu tư · Lĩnh vực cạnh tranh khốc liệt',
      id: 'Pro sports · Esports · Sales · Investasi · Bidang kompetitif ekstrem',
    }),
    sportsGameTypes: localeMap({
      ko: '랭크 게임·프로리그·무술·격투 스포츠',
      en: 'Ranked games · Pro leagues · Martial arts · Combat sports',
      ja: 'ランクゲーム・プロリーグ・武道・格闘スポーツ',
      'zh-CN': '排位游戏·职业联赛·武术·格斗运动',
      'zh-TW': '排位遊戲·職業聯賽·武術·格鬥運動',
      vi: 'Game xếp hạng · Giải pro · Võ thuật · Thể thao đối kháng',
      id: 'Ranked game · Pro league · Bela diri · Combat sports',
    }),
    certificationPhrase: localeMap({
      ko: '',
      en: '',
      ja: '',
      'zh-CN': '',
      'zh-TW': '',
      vi: '',
      id: '',
    }),
    oneLiner: localeMap({
      ko: '당신의 경쟁심은 강력한 무기입니다. 그 에너지가 올바른 방향으로 향할 때 아무도 당신을 막기 어렵습니다. 다만 이기는 것이 수단이 되어야 하고 목적이 되면 소진됩니다',
      en: 'Your competitiveness is a powerful weapon. When that energy points the right way, no one can stop you. But winning must be the means, not the goal, or you will burn out',
      ja: 'あなたの競争心は強力な武器です。そのエネルギーが正しい方向に向けば誰も止められません。ただ勝つことは目的ではなく手段でなければ、消耗します',
      'zh-CN': '你的竞争心是强大武器，能量指向正确方向时很难被阻挡。但赢应是手段而非目的，否则会被耗尽',
      'zh-TW': '你的競爭心是強大武器，能量指向正確方向時很難被阻擋。但贏應是手段而非目的，否則會被耗盡',
      vi: 'Tính cạnh tranh của bạn là vũ khí mạnh. Khi năng lượng đó hướng đúng, khó ai cản được. Nhưng thắng phải là phương tiện, không phải mục tiêu, nếu không sẽ kiệt sức',
      id: 'Daya saingmu senjata kuat. Saat energi itu mengarah benar, sulit dihentikan. Tapi menang harus jadi cara, bukan tujuan, atau kamu akan burnout',
    }),
    shareLine: localeMap({
      ko: '내 경쟁심 DNA: 극강 경쟁형 ⚔️ 경쟁이 삶의 에너지원이래... 경쟁 없는 상황이 오히려 불편하다는 거 맞음 ㅋㅋ → 경쟁심 결과 너는 어떤 유형이야?',
      en: 'My competitive DNA: Extreme Competitor Type ⚔️ They say competition is my life fuel... feeling uncomfortable without competition is so true lol → What\'s your competitive DNA type?',
      ja: '私の競争心DNA：極限競争型 ⚔️ 競争が人生のエネルギー源らしい…競争がないと逆に不快、当たり ㅋㅋ → あなたの競争心DNAはどのタイプ？',
      'zh-CN': '我的竞争心DNA：极致竞争型 ⚔️ 说竞争是生活能量来源…没有竞争反而不自在太准了哈哈 → 你的竞争心DNA是什么类型？',
      'zh-TW': '我的競爭心DNA：極致競爭型 ⚔️ 說競爭是生活能量來源…沒有競爭反而不自在太準了哈哈 → 你的競爭心DNA是什麼類型？',
      vi: 'DNA cạnh tranh của tôi: Kiểu cạnh tranh cực đoan ⚔️ Bảo cạnh tranh là nhiên liệu sống... không có cạnh tranh lại khó chịu, đúng quá haha → Bạn thuộc kiểu nào?',
      id: 'DNA daya saingku: Tipe Extreme Competitor ⚔️ Katanya kompetisi bahan bakar hidupku... tanpa kompetisi malah tidak nyaman, bener wkwk → Kamu tipe apa?',
    }),
  },
  {
    type: "Type6",
    emoji: "🏆",
    title: localeMap({
      ko: '모든 상황이 경쟁인 사람, 경쟁 DNA 마스터형',
      en: 'Competitive DNA Master Type 🏆',
      ja: '競争DNAマスター型 🏆',
      'zh-CN': '竞争DNA大师型 🏆',
      'zh-TW': '競爭DNA大師型 🏆',
      vi: 'Kiểu bậc thầy DNA cạnh tranh 🏆',
      id: 'Tipe Competitive DNA Master 🏆',
    }),
    competitiveDna: localeMap({
      ko: '극강 / 삶 전체가 경쟁이고 반드시 이겨야 하는 타입',
      en: 'Extreme / Life itself is competition and you must win',
      ja: '極限 / 人生全体が競争で、必ず勝たなければならないタイプ',
      'zh-CN': '极致 / 整个人生就是竞争，且必须赢的类型',
      'zh-TW': '極致 / 整個人生就是競爭，且必須贏的類型',
      vi: 'Cực đoan / Cả cuộc đời là cạnh tranh và bạn phải thắng',
      id: 'Ekstrem / Hidup sendiri adalah kompetisi dan kamu harus menang',
    }),
    quote: localeMap({
      ko: '당신에게 삶은 하나의 거대한 경쟁입니다. 그리고 당신은 반드시 그 안에서 이겨야 합니다.',
      en: 'To you, life is one giant competition. And you must win within it.',
      ja: 'あなたにとって人生は一つの巨大な競争です。そしてその中で必ず勝たなければなりません。',
      'zh-CN': '对你来说，人生就是一场巨大的竞争，而你必须在其中赢下来。',
      'zh-TW': '對你來說，人生就是一場巨大的競爭，而你必須在其中贏下來。',
      vi: 'Với bạn, cuộc đời là một cuộc cạnh tranh khổng lồ. Và bạn phải thắng trong đó.',
      id: 'Bagimu, hidup adalah satu kompetisi raksasa. Dan kamu harus menang di dalamnya.',
    }),
    description: localeMap({
      ko: '12가지 모두에서 가장 강한 경쟁심을 선택했습니다. 경쟁이 시작되는 순간 아드레날린이 폭발하고 상대방 분석이 자동으로 시작되며 패배는 곱씹고 다음엔 반드시 이기겠다는 다짐이 따라옵니다. 이 수준의 경쟁심은 역사적으로 가장 큰 성취를 만들어낸 사람들에게서 발견되는 패턴입니다.',
      en: 'You chose the strongest competitive instinct on all 12 questions. The moment competition starts, adrenaline explodes, opponent analysis begins automatically, and defeat is replayed with a vow to win next time. This level of competitiveness is the pattern found in people who made history\'s greatest achievements.',
      ja: '12問すべてで最も強い競争心を選びました。競争が始まる瞬間にアドレナリンが爆発し、相手分析が自動的に始まり、敗北は反芻され次は必ず勝つという誓いが続きます。このレベルの競争心は、歴史上最大の成果を生んだ人々に見られるパターンです。',
      'zh-CN': '12题都选了最强竞争心。竞争一开始肾上腺素就爆发，自动开始分析对手，失败后会反复咀嚼并发誓下次必赢。这种竞争心是历史上最大成就者常见的模式。',
      'zh-TW': '12題都選了最強競爭心。競爭一開始腎上腺素就爆發，自動開始分析對手，失敗後會反覆咀嚼並發誓下次必贏。這種競爭心是歷史上最大成就者常見的模式。',
      vi: 'Bạn chọn mức cạnh tranh mạnh nhất ở cả 12 câu. Khi cạnh tranh bắt đầu, adrenaline bùng nổ, phân tích đối thủ tự chạy, thua thì nhai lại và quyết thắng lần sau. Mức này là pattern của những người tạo thành tựu lớn nhất lịch sử.',
      id: 'Kamu memilih daya saing paling kuat di semua 12 pertanyaan. Saat kompetisi dimulai, adrenalin meledak, analisis lawan otomatis jalan, kekalahan direplay dengan sumpah menang lain kali. Level ini adalah pola orang dengan pencapaian terbesar sejarah.',
    }),
    competitiveType: localeMap({
      ko: '경쟁 DNA 마스터형 🏆',
      en: 'Competitive DNA Master Type 🏆',
      ja: '競争DNAマスター型 🏆',
      'zh-CN': '竞争DNA大师型 🏆',
      'zh-TW': '競爭DNA大師型 🏆',
      vi: 'Kiểu bậc thầy DNA cạnh tranh 🏆',
      id: 'Tipe Competitive DNA Master 🏆',
    }),
    competitiveKeywords: localeMap({
      ko: '승리 집착·완전한 준비·역전·절대 포기 없음·삶이 경쟁',
      en: 'Victory obsession · Full preparation · Comeback · Never give up · Life is competition',
      ja: '勝利への執着・完全な準備・逆転・絶対に諦めない・人生が競争',
      'zh-CN': '胜利执念·完全准备·逆转·绝不放弃·人生即竞争',
      'zh-TW': '勝利執念·完全準備·逆轉·絕不放棄·人生即競爭',
      vi: 'Ám ảnh chiến thắng · Chuẩn bị toàn diện · Lật kèo · Không bao giờ bỏ cuộc · Cuộc đời là cạnh tranh',
      id: 'Obsesi kemenangan · Persiapan penuh · Comeback · Tidak pernah menyerah · Hidup adalah kompetisi',
    }),
    strengths: localeMap({
      ko: '어떤 경쟁 환경에서도 최고 수준의 준비와 집중력을 발휘함\n불리한 상황에서도 포기하지 않는 극한의 끈질김\n경쟁이 치열할수록 오히려 더 날카로워지는 패턴\n이 경쟁심이 팀을 이끄는 방향으로 작동하면 강력한 리더십이 됨',
      en: 'Top-level preparation and focus in any competitive environment\nExtreme persistence that never gives up even in unfavorable situations\nGets sharper as competition intensifies\nWhen this drive leads a team, it becomes powerful leadership',
      ja: 'どんな競争環境でも最高水準の準備と集中力を発揮\n不利な状況でも諦めない極限の粘り強さ\n競争が激しくなるほど鋭くなるパターン\nこの競争心がチームを導く方向に働けば強力なリーダーシップになる',
      'zh-CN': '任何竞争环境都能拿出顶级准备与专注\n不利局面也不放弃\n竞争越激烈越锋利\n这种竞争心若用于带队，就是强大领导力',
      'zh-TW': '任何競爭環境都能拿出頂級準備與專注\n不利局面也不放棄\n競爭越激烈越鋒利\n這種競爭心若用於帶隊，就是強大領導力',
      vi: 'Chuẩn bị và tập trung đỉnh cao trong mọi môi trường cạnh tranh\nBền bỉ cực hạn, không bỏ cuộc dù bất lợi\nCàng cạnh tranh khốc liệt càng sắc bén\nKhi drive này dẫn dắt đội, trở thành leadership mạnh',
      id: 'Persiapan dan fokus level top di lingkungan kompetitif apa pun\nKegigihan ekstrem, tidak menyerah meski situasi buruk\nMakin tajam saat kompetisi makin sengit\nSaat drive ini memimpin tim, jadi leadership kuat',
    }),
    cautions: localeMap({
      ko: '삶 전체가 경쟁 프레임이 되면 협력·휴식·관계가 희생될 수 있음\n이기는 것 자체에 집착하면 본래 목적을 잃는 경우가 생김\n패배 후 심리적 회복에 많은 에너지가 소모될 수 있음. 회복 루틴 필수\n모든 것을 경쟁으로 보면 가까운 사람들이 지쳐 떠나는 경우가 있음. 경쟁 프레임을 끄는 연습도 필요',
      en: 'If all of life becomes a competition frame, cooperation, rest, and relationships can be sacrificed\nObsession with winning itself can make you lose the original purpose\nRecovery after defeat may consume a lot of energy. Recovery routines are essential\nSeeing everything as competition can exhaust close people. Practice turning off the competition frame',
      ja: '人生全体が競争フレームになると協力・休息・関係が犠牲になる\n勝つこと自体に執着すると本来の目的を失う\n敗北後の回復に多くのエネルギーが必要。回復ルーティン必須\nすべてを競争と見ると近い人が疲れ去る。競争フレームを切る練習も必要',
      'zh-CN': '若整个人生都是竞争框架，合作、休息、关系都可能被牺牲\n执着于赢本身会失去原本目的\n失败后恢复很耗能量，必须有恢复routine\n把一切都看成竞争会让亲近的人疲惫离开，也要练习关闭竞争框架',
      'zh-TW': '若整個人生都是競爭框架，合作、休息、關係都可能被犧牲\n執著於贏本身會失去原本目的\n失敗後恢復很耗能量，必須有恢復routine\n把一切都看成競爭會讓親近的人疲憊離開，也要練習關閉競爭框架',
      vi: 'Nếu cả đời là khung cạnh tranh, hợp tác, nghỉ ngơi, quan hệ có thể bị hy sinh\nÁm ảnh thắng có thể làm mất mục đích ban đầu\nPhục hồi sau thua tốn nhiều năng lượng. Cần routine phục hồi\nCoi mọi thứ là cạnh tranh khiến người thân mệt mỏi. Hãy luyện tắt khung cạnh tranh',
      id: 'Jika seluruh hidup jadi frame kompetisi, kolaborasi, istirahat, relasi bisa dikorbankan\nObsesi menang bisa bikin kehilangan tujuan awal\nPemulihan setelah kalah butuh banyak energi. Recovery routine wajib\nMelihat semua sebagai kompetisi bisa membuat orang dekat lelah pergi. Latih mematikan frame kompetisi',
    }),
    bestEnvironments: localeMap({
      ko: '프로 스포츠·e스포츠 프로팀·창업·극한 경쟁 산업',
      en: 'Pro sports · Pro esports teams · Startups · Extreme competition industries',
      ja: 'プロスポーツ・eスポーツプロチーム・起業・極限競争産業',
      'zh-CN': '职业体育·职业电竞战队·创业·极限竞争产业',
      'zh-TW': '職業體育·職業電競戰隊·創業·極限競爭產業',
      vi: 'Thể thao chuyên nghiệp · Đội esports pro · Startup · Ngành cạnh tranh cực hạn',
      id: 'Pro sports · Tim esports pro · Startup · Industri kompetisi ekstrem',
    }),
    sportsGameTypes: localeMap({
      ko: '프로 랭크 최상위·격투기·철인 3종·팀을 이끄는 주장 포지션',
      en: 'Top pro rank · MMA · Ironman triathlon · Team captain role',
      ja: 'プロランク最上位・格闘技・アイアンマン・チームを率いるキャプテン',
      'zh-CN': '职业排位顶层·综合格斗·铁人三项·带队队长位置',
      'zh-TW': '職業排位頂層·綜合格鬥·鐵人三項·帶隊隊長位置',
      vi: 'Rank pro cao nhất · MMA · Ironman · Vai trò đội trưởng',
      id: 'Rank pro top · MMA · Ironman triathlon · Peran kapten tim',
    }),
    certificationPhrase: localeMap({
      ko: '"경쟁 DNA 마스터 달성 🏆 삶 전체가 경쟁이고 반드시 이깁니다"',
      en: 'Competitive DNA Master Achieved 🏆 Life is competition and I must win',
      ja: '競争DNAマスター達成 🏆 人生全体が競争で、必ず勝ちます',
      'zh-CN': '竞争DNA大师达成 🏆 整个人生就是竞争，我必须赢',
      'zh-TW': '競爭DNA大師達成 🏆 整個人生就是競爭，我必須贏',
      vi: 'Đạt Bậc thầy DNA cạnh tranh 🏆 Cuộc đời là cạnh tranh và tôi phải thắng',
      id: 'Competitive DNA Master tercapai 🏆 Hidup adalah kompetisi dan aku harus menang',
    }),
    oneLiner: localeMap({
      ko: '이 경쟁심은 세상을 바꾼 사람들이 가진 것과 같습니다. 다만 최고의 경쟁자는 언제 경쟁하고 언제 멈출지도 압니다. 그 지혜가 더해지면 진짜 마스터입니다',
      en: 'This competitiveness is what people who changed the world had. But the greatest competitors also know when to compete and when to stop. Add that wisdom and you become a true master',
      ja: 'この競争心は世界を変えた人々が持っていたものと同じです。ただ最高の競争者は、いつ競争し、いつ止めるかも知っています。その知恵が加われば本当のマスターです',
      'zh-CN': '这种竞争心与改变世界的人相同，但最强的竞争者也知道何时竞争、何时停下，加上这份智慧才是真大师',
      'zh-TW': '這種競爭心與改變世界的人相同，但最強的競爭者也知道何時競爭、何時停下，加上這份智慧才是真大師',
      vi: 'Tính cạnh tranh này giống những người đã thay đổi thế giới. Nhưng đối thủ vĩ đại nhất cũng biết khi nào cạnh tranh và khi nào dừng. Thêm trí tuệ đó mới thành bậc thầy thật',
      id: 'Daya saing ini sama dengan yang dimiliki orang yang mengubah dunia. Tapi kompetitor terhebat juga tahu kapan bersaing dan kapan berhenti. Tambahkan kebijaksanaan itu dan kamu jadi master sejati',
    }),
    shareLine: localeMap({
      ko: '내 경쟁심 DNA: 마스터형 🏆 삶 전체가 경쟁이래... 반드시 이겨야 한다는 거 맞음 → 경쟁심 결과 랭겜 유저 다 해봐 몇 점 나왔어?',
      en: 'My competitive DNA: Master Type 🏆 They say my whole life is competition... having to win no matter what is so true → Ranked gamers, try this — what score did you get?',
      ja: '私の競争心DNA：マスター型 🏆 人生全体が競争らしい…必ず勝たなければ、当たり → ランクゲームユーザー全員やってみて、何点出た？',
      'zh-CN': '我的竞争心DNA：大师型 🏆 说整个人生都是竞争…必须赢太准了 → 排位玩家都来测测，你几分？',
      'zh-TW': '我的競爭心DNA：大師型 🏆 說整個人生都是競爭…必須贏太準了 → 排位玩家都來測測，你幾分？',
      vi: 'DNA cạnh tranh của tôi: Kiểu Master 🏆 Bảo cả đời là cạnh tranh... phải thắng bằng mọi giá, đúng quá → Fan rank game thử đi, mấy điểm?',
      id: 'DNA daya saingku: Tipe Master 🏆 Katanya hidupku seluruhnya kompetisi... harus menang apapun risikonya, bener → Ranked gamer coba deh, skor berapa?',
    }),
  },
];
