/** 나의 '리더십' 스타일 — 12문항 4지선다, A=0 B=1 C=2 D=3, 총점 0~36 → Type1~6 · 7개 로케일 */

export type Phase3LeadershipStyleLocaleKey = 'ko' | 'en' | 'ja' | 'zh-CN' | 'zh-TW' | 'vi' | 'id';

function localeMap(t: Record<Phase3LeadershipStyleLocaleKey, string>): Record<Phase3LeadershipStyleLocaleKey, string> {
  return t;
}

function opt(m: Record<Phase3LeadershipStyleLocaleKey, string>, score: number): { text: Record<Phase3LeadershipStyleLocaleKey, string>; score: number } {
  return { text: localeMap(m), score };
}

export interface Phase3LeadershipStyleQuestion {
  id: number;
  question: Record<Phase3LeadershipStyleLocaleKey, string>;
  options: { text: Record<Phase3LeadershipStyleLocaleKey, string>; score: number }[];
}

export interface Phase3LeadershipStyleResult {
  type: string;
  emoji: string;
  title: Record<Phase3LeadershipStyleLocaleKey, string>;
  shortDescription: Record<Phase3LeadershipStyleLocaleKey, string>;
  description: Record<Phase3LeadershipStyleLocaleKey, string>;
  leadershipStyle: Record<Phase3LeadershipStyleLocaleKey, string>;
  leadershipKeywords: Record<Phase3LeadershipStyleLocaleKey, string>;
  teamRole: Record<Phase3LeadershipStyleLocaleKey, string>;
  strength: Record<Phase3LeadershipStyleLocaleKey, string>;
  weakness: Record<Phase3LeadershipStyleLocaleKey, string>;
  goodEnvironment: Record<Phase3LeadershipStyleLocaleKey, string>;
  goodMatch: Record<Phase3LeadershipStyleLocaleKey, string>;
  coverLetterPhrase: Record<Phase3LeadershipStyleLocaleKey, string>;
  coverLetterMaterial: Record<Phase3LeadershipStyleLocaleKey, string>;
  shareLine: Record<Phase3LeadershipStyleLocaleKey, string>;
}

export function calculatePhase3LeadershipStyleResult(answers: number[]): string {
  const total = answers.reduce((sum, s) => sum + (s ?? 0), 0);
  if (total <= 5) return 'Type1';
  if (total <= 11) return 'Type2';
  if (total <= 19) return 'Type3';
  if (total <= 27) return 'Type4';
  if (total <= 33) return 'Type5';
  return 'Type6';
}

export const phase3LeadershipStyleQuestions: Phase3LeadershipStyleQuestion[] = [
  {
    id: 1,
    question: localeMap({
      ko: '상황: 팀 프로젝트 첫 회의가 시작됐다. 아직 아무도 말을 꺼내지 않은 상황이다. 나는?',
      en: 'Situation: The first team project meeting has started. No one has spoken yet. I would…',
      ja: '状況：チームプロジェクトの初回会議が始まった。まだ誰も発言していない。私は？',
      'zh-CN': '情况：团队项目第一次会议开始了。还没有人开口。我会？',
      'zh-TW': '情況：團隊專案第一次會議開始了。還沒有人開口。我會？',
      vi: 'Tình huống: Buổi họp đầu tiên của dự án nhóm đã bắt đầu. Chưa ai lên tiếng. Tôi sẽ…',
      id: 'Situasi: Rapat pertama proyek tim dimulai. Belum ada yang bicara. Saya…',
    }),
    options: [
      opt(localeMap({
        ko: '팀원들 표정을 살피며 편하게 이야기할 수 있는 분위기를 먼저 만든다',
        en: 'Read team members\' expressions and create a comfortable atmosphere for conversation first',
        ja: 'チームメンバーの表情を見て、話しやすい雰囲気を先に作る',
        'zh-CN': '观察队员表情，先营造轻松交流的氛围',
        'zh-TW': '觀察隊員表情，先營造輕鬆交流的氛圍',
        vi: 'Quan sát biểu cảm đồng đội và tạo không khí thoải mái để nói chuyện trước',
        id: 'Mengamati ekspresi anggota tim dan menciptakan suasana nyaman untuk bicara terlebih dahulu',
    }), 0),
      opt(localeMap({
        ko: '"각자 생각해온 것을 돌아가면서 이야기해보면 어떨까요?"라고 제안한다',
        en: 'Suggest, "How about we take turns sharing what each of us has been thinking?"',
        ja: '「それぞれ考えてきたことを順番に話してみませんか？」と提案する',
        'zh-CN': '提议：「要不要轮流说说各自的想法？」',
        'zh-TW': '提議：「要不要輪流說說各自的想法？」',
        vi: 'Đề xuất: "Mọi người lần lượt chia sẻ suy nghĩ của mình nhé?"',
        id: 'Mengusulkan, "Bagaimana kalau kita bergiliran berbagi apa yang sudah kita pikirkan?"',
    }), 1),
      opt(localeMap({
        ko: '"우선 오늘 회의에서 결정해야 할 것들을 정리해볼게요"라며 구조를 잡는다',
        en: 'Set structure by saying, "Let me first organize what we need to decide in today\'s meeting"',
        ja: '「まず今日の会議で決めるべきことを整理しましょう」と構造を作る',
        'zh-CN': '说「先把今天会议要决定的事项整理一下」，搭建结构',
        'zh-TW': '說「先把今天會議要決定的事項整理一下」，搭建結構',
        vi: 'Dựng cấu trúc: "Trước tiên tôi sẽ tổng hợp những gì cần quyết định trong cuộc họp hôm nay"',
        id: 'Menyusun struktur: "Mari kita rapikan dulu hal-hal yang perlu diputuskan di rapat hari ini"',
    }), 2),
      opt(localeMap({
        ko: '"이 프로젝트로 우리가 만들어야 할 방향이 뭔지 먼저 얘기해봐요"라며 주도한다',
        en: 'Take the lead: "Let\'s first talk about what direction we need to create with this project"',
        ja: '「このプロジェクトで作るべき方向性を先に話しましょう」と主導する',
        'zh-CN': '主导说：「先聊聊这个项目我们要打造的方向」',
        'zh-TW': '主導說：「先聊聊這個專案我們要打造的方向」',
        vi: 'Dẫn dắt: "Hãy nói trước về hướng đi chúng ta cần tạo ra với dự án này"',
        id: 'Memimpin: "Mari bicara dulu arah apa yang harus kita capai dengan proyek ini"',
    }), 3),
    ],
  },
  {
    id: 2,
    question: localeMap({
      ko: '상황: 팀원 중 한 명이 맡은 역할을 잘 못하고 있는 것 같다. 나는?',
      en: 'Situation: A team member seems to be struggling with their assigned role. I would…',
      ja: '状況：チームメンバーの一人が担当役割をうまくこなせていないようだ。私は？',
      'zh-CN': '情况：有一名队员似乎没做好分配的角色。我会？',
      'zh-TW': '情況：有一名隊員似乎沒做好分配的角色。我會？',
      vi: 'Tình huống: Một thành viên có vẻ không làm tốt vai trò được giao. Tôi sẽ…',
      id: 'Situasi: Salah satu anggota tim sepertinya kesulitan dengan peran yang diberikan. Saya…',
    }),
    options: [
      opt(localeMap({
        ko: '그 팀원이 어려워하는 부분을 먼저 물어보고 내가 도울 수 있는 것을 찾는다',
        en: 'Ask what they are struggling with first and find what I can help with',
        ja: 'そのメンバーが苦手な部分を先に聞き、自分が助けられることを探す',
        'zh-CN': '先问对方哪里困难，找出我能帮上的地方',
        'zh-TW': '先問對方哪裡困難，找出我能幫上的地方',
        vi: 'Hỏi trước phần nào họ gặp khó và tìm cách mình có thể giúp',
        id: 'Menanyakan dulu bagian mana yang sulit dan mencari apa yang bisa saya bantu',
    }), 0),
      opt(localeMap({
        ko: '팀 전체에 "혹시 도움이 필요한 사람 있어요?"라고 열어놓는다',
        en: 'Open it to the whole team: "Does anyone need help?"',
        ja: 'チーム全体に「助けが必要な人はいますか？」と問いかける',
        'zh-CN': '向全队开放提问：「有人需要帮助吗？」',
        'zh-TW': '向全隊開放提問：「有人需要幫助嗎？」',
        vi: 'Mở cho cả nhóm: "Có ai cần giúp đỡ không?"',
        id: 'Membuka ke seluruh tim: "Ada yang butuh bantuan?"',
    }), 1),
      opt(localeMap({
        ko: '그 팀원에게 직접 피드백을 주고 어떻게 개선할 수 있는지 같이 생각해본다',
        en: 'Give direct feedback and think together about how to improve',
        ja: 'そのメンバーに直接フィードバックを与え、改善方法を一緒に考える',
        'zh-CN': '直接给出反馈，一起思考如何改进',
        'zh-TW': '直接給出回饋，一起思考如何改進',
        vi: 'Đưa phản hồi trực tiếp và cùng suy nghĩ cách cải thiện',
        id: 'Memberi feedback langsung dan bersama-sama memikirkan cara memperbaikinya',
    }), 2),
      opt(localeMap({
        ko: '역할 재배분이 필요하다면 과감하게 조정하고 진행한다',
        en: 'Boldly adjust roles if redistribution is needed and move forward',
        ja: '役割の再配分が必要なら大胆に調整して進める',
        'zh-CN': '若需重新分配角色，就果断调整并推进',
        'zh-TW': '若需重新分配角色，就果斷調整並推進',
        vi: 'Nếu cần phân vai lại thì điều chỉnh dứt khoát và tiến hành',
        id: 'Jika perlu redistribusi peran, menyesuaikan dengan tegas dan melanjutkan',
    }), 3),
    ],
  },
  {
    id: 3,
    question: localeMap({
      ko: '상황: 프로젝트 방향에 대해 팀원들 의견이 갈려서 결론이 안 나고 있다. 나는?',
      en: 'Situation: Team opinions on the project direction are divided and no conclusion is reached. I would…',
      ja: '状況：プロジェクトの方向性について意見が分かれ、結論が出ない。私は？',
      'zh-CN': '情况：项目方向上队员意见分歧，得不出结论。我会？',
      'zh-TW': '情況：專案方向上隊員意見分歧，得不出結論。我會？',
      vi: 'Tình huống: Ý kiến về hướng dự án bị chia rẽ và chưa có kết luận. Tôi sẽ…',
      id: 'Situasi: Pendapat tentang arah proyek terpecah dan belum ada kesimpulan. Saya…',
    }),
    options: [
      opt(localeMap({
        ko: '각 의견의 좋은 점을 찾아 조합할 방법을 생각해본다',
        en: 'Find the strengths in each opinion and think about how to combine them',
        ja: '各意見の良い点を見つけ、組み合わせる方法を考える',
        'zh-CN': '找出各意见的优点，思考如何组合',
        'zh-TW': '找出各意見的優點，思考如何組合',
        vi: 'Tìm điểm hay trong từng ý kiến và nghĩ cách kết hợp',
        id: 'Mencari kelebihan tiap pendapat dan memikirkan cara menggabungkannya',
    }), 0),
      opt(localeMap({
        ko: '충분히 들은 뒤 팀이 동의할 수 있는 공통점을 찾아 정리한다',
        en: 'After listening enough, find common ground the team can agree on and summarize',
        ja: '十分に聞いた後、チームが合意できる共通点を見つけて整理する',
        'zh-CN': '充分听取后，找出团队能达成共识的共同点并整理',
        'zh-TW': '充分聽取後，找出團隊能達成共識的共同點並整理',
        vi: 'Sau khi lắng nghe đủ, tìm điểm chung mà nhóm có thể đồng ý và tổng hợp',
        id: 'Setelah cukup mendengarkan, mencari titik temu yang bisa disepakati tim dan merangkumnya',
    }), 1),
      opt(localeMap({
        ko: '각 의견의 장단점을 데이터나 근거로 분석해서 정리해준다',
        en: 'Analyze the pros and cons of each opinion with data or evidence and summarize',
        ja: '各意見の長所と短所をデータや根拠で分析して整理する',
        'zh-CN': '用数据或依据分析各意见利弊并整理',
        'zh-TW': '用數據或依據分析各意見利弊並整理',
        vi: 'Phân tích ưu nhược điểm từng ý kiến bằng dữ liệu hoặc căn cứ và tổng hợp',
        id: 'Menganalisis kelebihan dan kekurangan tiap pendapat dengan data atau bukti lalu merangkum',
    }), 2),
      opt(localeMap({
        ko: '내가 판단한 최선의 방향을 제시하고 그 이유를 설득한다',
        en: 'Present what I judge as the best direction and persuade with my reasons',
        ja: '自分が判断した最善の方向性を提示し、その理由で説得する',
        'zh-CN': '提出我认为的最佳方向，并用理由说服',
        'zh-TW': '提出我認為的最佳方向，並用理由說服',
        vi: 'Đưa ra hướng đi tốt nhất theo phán đoán của mình và thuyết phục bằng lý do',
        id: 'Menyampaikan arah terbaik menurut penilaian saya dan meyakinkan dengan alasan',
    }), 3),
    ],
  },
  {
    id: 4,
    question: localeMap({
      ko: '상황: 마감이 3일 남았는데 진행 속도가 너무 느리다. 나는?',
      en: 'Situation: The deadline is 3 days away but progress is too slow. I would…',
      ja: '状況：締切まで3日なのに進行速度が遅すぎる。私は？',
      'zh-CN': '情况：离截止日期还有3天，但进度太慢。我会？',
      'zh-TW': '情況：離截止日期還有3天，但進度太慢。我會？',
      vi: 'Tình huống: Còn 3 ngày đến hạn mà tiến độ quá chậm. Tôi sẽ…',
      id: 'Situasi: Tenggat 3 hari lagi tapi progres terlalu lambat. Saya…',
    }),
    options: [
      opt(localeMap({
        ko: '팀원들이 지쳐있는 건 아닌지 먼저 확인하고 필요하면 도움을 자처한다',
        en: 'Check first if team members are exhausted and volunteer help if needed',
        ja: 'チームメンバーが疲れていないか先に確認し、必要なら手伝いを申し出る',
        'zh-CN': '先确认队员是否疲惫，必要时主动帮忙',
        'zh-TW': '先確認隊員是否疲憊，必要時主動幫忙',
        vi: 'Kiểm tra trước xem đồng đội có mệt không và tình nguyện giúp nếu cần',
        id: 'Memastikan dulu apakah anggota tim kelelahan dan menawarkan bantuan jika perlu',
    }), 0),
      opt(localeMap({
        ko: '팀 전체 상황을 공유하고 각자 어느 부분에서 막혀있는지 파악한다',
        en: 'Share the overall team situation and identify where each person is stuck',
        ja: 'チーム全体の状況を共有し、各自がどこで詰まっているか把握する',
        'zh-CN': '共享全队情况，了解各自卡在哪里',
        'zh-TW': '共享全隊情況，了解各自卡在哪裡',
        vi: 'Chia sẻ tình hình chung của nhóm và xác định ai đang bị kẹt ở đâu',
        id: 'Berbagi situasi tim secara keseluruhan dan memetakan di mana masing-masing terhambat',
    }), 1),
      opt(localeMap({
        ko: '현재 진행 상황을 수치로 파악하고 우선순위를 재조정한다',
        en: 'Quantify current progress and readjust priorities',
        ja: '現在の進捗を数値で把握し、優先順位を再調整する',
        'zh-CN': '用数据掌握当前进度，重新调整优先级',
        'zh-TW': '用數據掌握當前進度，重新調整優先順序',
        vi: 'Nắm tiến độ hiện tại bằng số liệu và điều chỉnh lại ưu tiên',
        id: 'Mengukur progres saat ini secara numerik dan menyesuaikan ulang prioritas',
    }), 2),
      opt(localeMap({
        ko: '"이 기간 안에 반드시 끝낸다"는 방향을 명확히 하고 속도를 높인다',
        en: 'Clarify the direction "We must finish within this period" and increase speed',
        ja: '「この期間内に必ず終わらせる」という方向性を明確にし、速度を上げる',
        'zh-CN': '明确方向「必须在这个期限内完成」，加快速度',
        'zh-TW': '明確方向「必須在這個期限內完成」，加快速度',
        vi: 'Làm rõ hướng đi "Phải hoàn thành trong thời hạn này" và tăng tốc',
        id: 'Memperjelas arah "Kita harus selesai dalam periode ini" dan mempercepat',
    }), 3),
    ],
  },
  {
    id: 5,
    question: localeMap({
      ko: '상황: 팀원이 아이디어를 냈는데 실현 가능성이 낮아 보인다. 나는?',
      en: 'Situation: A team member shared an idea that seems low in feasibility. I would…',
      ja: '状況：チームメンバーがアイデアを出したが、実現可能性が低そうだ。私は？',
      'zh-CN': '情况：队员提出了一个想法，但可行性看起来不高。我会？',
      'zh-TW': '情況：隊員提出了一個想法，但可行性看起來不高。我會？',
      vi: 'Tình huống: Một thành viên đưa ra ý tưởng nhưng có vẻ khó thực hiện. Tôi sẽ…',
      id: 'Situasi: Seorang anggota tim mengajukan ide yang tampaknya sulit direalisasikan. Saya…',
    }),
    options: [
      opt(localeMap({
        ko: '일단 아이디어를 충분히 들어주고 좋은 점을 먼저 인정한다',
        en: 'Listen to the idea fully first and acknowledge its good points',
        ja: 'まずアイデアを十分に聞き、良い点を先に認める',
        'zh-CN': '先充分听取想法，先认可优点',
        'zh-TW': '先充分聽取想法，先認可優點',
        vi: 'Lắng nghe đầy đủ ý tưởng trước và công nhận điểm hay',
        id: 'Mendengarkan ide sepenuhnya dulu dan mengakui kelebihannya terlebih dahulu',
    }), 0),
      opt(localeMap({
        ko: '"이 아이디어 어떻게 생각해요?"라며 팀 전체 의견을 물어본다',
        en: 'Ask the whole team, "What do you think of this idea?"',
        ja: '「このアイデア、どう思いますか？」とチーム全体の意見を聞く',
        'zh-CN': '问全队：「大家觉得这个想法怎么样？」',
        'zh-TW': '問全隊：「大家覺得這個想法怎麼樣？」',
        vi: 'Hỏi cả nhóm: "Mọi người nghĩ gì về ý tưởng này?"',
        id: 'Menanyakan ke seluruh tim, "Bagaimana menurut kalian ide ini?"',
    }), 1),
      opt(localeMap({
        ko: '실현 가능성을 구체적으로 분석해주며 어떤 조건이 갖춰지면 가능한지 함께 생각한다',
        en: 'Analyze feasibility specifically and think together about what conditions would make it possible',
        ja: '実現可能性を具体的に分析し、どんな条件が整えば可能か一緒に考える',
        'zh-CN': '具体分析可行性，一起思考满足什么条件可以实现',
        'zh-TW': '具體分析可行性，一起思考滿足什麼條件可以實現',
        vi: 'Phân tích cụ thể tính khả thi và cùng nghĩ điều kiện nào sẽ làm nó khả thi',
        id: 'Menganalisis kelayakan secara spesifik dan bersama-sama memikirkan kondisi apa yang diperlukan',
    }), 2),
      opt(localeMap({
        ko: '"이 방향보다 더 효과적인 방법이 있어요"라며 대안을 제시한다',
        en: 'Suggest an alternative: "There is a more effective approach than this direction"',
        ja: '「この方向より効果的な方法があります」と代替案を提示する',
        'zh-CN': '提出替代方案：「有比这个方向更有效的方法」',
        'zh-TW': '提出替代方案：「有比這個方向更有效的方法」',
        vi: 'Đề xuất phương án thay thế: "Có cách hiệu quả hơn hướng này"',
        id: 'Menyampaikan alternatif: "Ada cara yang lebih efektif dari arah ini"',
    }), 3),
    ],
  },
  {
    id: 6,
    question: localeMap({
      ko: '상황: 팀 내에 갈등이 생겼다. 두 팀원이 의견 충돌로 분위기가 냉랭해졌다. 나는?',
      en: 'Situation: Conflict arose in the team. Two members clashed and the atmosphere turned cold. I would…',
      ja: '状況：チーム内で対立が起きた。二人の意見がぶつかり、雰囲気が冷えた。私は？',
      'zh-CN': '情况：团队内出现冲突。两名队员意见对立，气氛变冷。我会？',
      'zh-TW': '情況：團隊內出現衝突。兩名隊員意見對立，氣氛變冷。我會？',
      vi: 'Tình huống: Xung đột nổ ra trong nhóm. Hai thành viên va chạm ý kiến, không khí lạnh đi. Tôi sẽ…',
      id: 'Situasi: Konflik muncul di tim. Dua anggota bentrok dan suasana menjadi dingin. Saya…',
    }),
    options: [
      opt(localeMap({
        ko: '각자를 따로 만나 속마음을 들어주고 감정을 먼저 풀어준다',
        en: 'Meet each person separately, listen to their feelings, and release emotions first',
        ja: 'それぞれと個別に会い、本音を聞いて感情を先に解く',
        'zh-CN': '分别见面，倾听心声，先化解情绪',
        'zh-TW': '分別見面，傾聽心聲，先化解情緒',
        vi: 'Gặp riêng từng người, lắng nghe tâm sự và giải tỏa cảm xúc trước',
        id: 'Bertemu masing-masing secara terpisah, mendengarkan isi hati, dan melepaskan emosi terlebih dahulu',
    }), 0),
      opt(localeMap({
        ko: '전체 자리를 마련해서 두 사람이 서로 이야기할 수 있게 중재한다',
        en: 'Set up a meeting for both to talk to each other and mediate',
        ja: '全体の場を設け、二人が話し合えるよう仲介する',
        'zh-CN': '安排全体场合，居中协调让两人互相沟通',
        'zh-TW': '安排全體場合，居中協調讓兩人互相溝通',
        vi: 'Tổ chức buổi gặp để hai người nói chuyện với nhau và làm trung gian',
        id: 'Menyediakan forum agar keduanya bisa saling bicara dan menjadi mediator',
    }), 1),
      opt(localeMap({
        ko: '갈등의 원인을 파악하고 구체적인 해결 방안을 제시한다',
        en: 'Identify the cause of the conflict and propose specific solutions',
        ja: '対立の原因を把握し、具体的な解決策を提示する',
        'zh-CN': '找出冲突原因，提出具体解决方案',
        'zh-TW': '找出衝突原因，提出具體解決方案',
        vi: 'Xác định nguyên nhân xung đột và đề xuất giải pháp cụ thể',
        id: 'Mengidentifikasi penyebab konflik dan mengusulkan solusi konkret',
    }), 2),
      opt(localeMap({
        ko: '"지금 감정보다 결과가 중요하다"며 팀이 집중해야 할 것을 상기시킨다',
        en: 'Remind the team what to focus on: "Results matter more than emotions right now"',
        ja: '「今は感情より結果が重要だ」と、チームが集中すべきことを思い出させる',
        'zh-CN': '提醒团队该聚焦的事：「现在结果比情绪更重要」',
        'zh-TW': '提醒團隊該聚焦的事：「現在結果比情緒更重要」',
        vi: 'Nhắc nhóm tập trung vào điều quan trọng: "Bây giờ kết quả quan trọng hơn cảm xúc"',
        id: 'Mengingatkan tim fokus pada hal penting: "Sekarang hasil lebih penting daripada emosi"',
    }), 3),
    ],
  },
  {
    id: 7,
    question: localeMap({
      ko: '상황: 팀 프로젝트가 잘 마무리됐다. 공이 누구에게 있냐는 이야기가 나왔다. 나는?',
      en: 'Situation: The team project finished well. A discussion arose about who deserves credit. I would…',
      ja: '状況：チームプロジェクトがうまく終わった。誰の手柄かという話が出た。私は？',
      'zh-CN': '情况：团队项目顺利结束。开始讨论功劳归谁。我会？',
      'zh-TW': '情況：團隊專案順利結束。開始討論功勞歸誰。我會？',
      vi: 'Tình huống: Dự án nhóm kết thúc tốt. Có cuộc thảo luận về ai xứng đáng được ghi nhận. Tôi sẽ…',
      id: 'Situasi: Proyek tim selesai dengan baik. Muncul pembicaraan soal siapa yang pantas mendapat pujian. Saya…',
    }),
    options: [
      opt(localeMap({
        ko: '"팀원들이 각자 잘해줘서 된 거예요"라며 공을 돌린다',
        en: 'Deflect credit: "It worked because each team member did well"',
        ja: '「チームメンバーそれぞれが頑張ったからです」と手柄を回す',
        'zh-CN': '把功劳让出去：「是因为每位队员都做得很好」',
        'zh-TW': '把功勞讓出去：「是因為每位隊員都做得很好」',
        vi: 'Chuyển công: "Là nhờ mỗi thành viên đều làm tốt"',
        id: 'Mengalihkan pujian: "Ini berhasil karena setiap anggota tim bekerja dengan baik"',
    }), 0),
      opt(localeMap({
        ko: '각자가 어떤 기여를 했는지 구체적으로 짚어주며 다 같이 인정한다',
        en: 'Specifically point out each person\'s contribution and acknowledge everyone together',
        ja: '各自の貢献を具体的に指摘し、みんなで認める',
        'zh-CN': '具体指出各自的贡献，一起认可',
        'zh-TW': '具體指出各自的貢獻，一起認可',
        vi: 'Chỉ rõ đóng góp của từng người và cùng nhau ghi nhận',
        id: 'Menunjuk secara spesifik kontribusi masing-masing dan mengakui semuanya bersama',
    }), 1),
      opt(localeMap({
        ko: '성공 요인을 분석하며 다음에 더 잘할 수 있는 점도 함께 정리한다',
        en: 'Analyze success factors and also organize what can be done better next time',
        ja: '成功要因を分析し、次により良くできる点も一緒に整理する',
        'zh-CN': '分析成功因素，同时整理下次可以做得更好的地方',
        'zh-TW': '分析成功因素，同時整理下次可以做得更好的地方',
        vi: 'Phân tích yếu tố thành công và tổng hợp điểm có thể làm tốt hơn lần sau',
        id: 'Menganalisis faktor keberhasilan dan merangkum hal yang bisa lebih baik lain kali',
    }), 2),
      opt(localeMap({
        ko: '"우리가 방향을 잘 잡고 밀어붙인 덕분"이라며 전략적 결정을 강조한다',
        en: 'Emphasize strategic decisions: "Because we set the direction well and pushed through"',
        ja: '「方向性をうまく定めて押し切ったから」と戦略的決定を強調する',
        'zh-CN': '强调战略决策：「因为我们方向定得好并推进到底」',
        'zh-TW': '強調戰略決策：「因為我們方向定得好並推進到底」',
        vi: 'Nhấn mạnh quyết định chiến lược: "Vì chúng ta định hướng tốt và đẩy mạnh đến cùng"',
        id: 'Menekankan keputusan strategis: "Karena kita menetapkan arah dengan baik dan mendorong sampai selesai"',
    }), 3),
    ],
  },
  {
    id: 8,
    question: localeMap({
      ko: '상황: 새 팀원이 합류했는데 적응을 못 하고 있는 것 같다. 나는?',
      en: 'Situation: A new team member joined but seems unable to adapt. I would…',
      ja: '状況：新しいチームメンバーが加わったが、適応できていないようだ。私は？',
      'zh-CN': '情况：新队员加入了，但似乎还没适应。我会？',
      'zh-TW': '情況：新隊員加入了，但似乎還沒適應。我會？',
      vi: 'Tình huống: Thành viên mới gia nhập nhưng có vẻ chưa thích nghi. Tôi sẽ…',
      id: 'Situasi: Anggota tim baru bergabung tapi sepertinya belum bisa beradaptasi. Saya…',
    }),
    options: [
      opt(localeMap({
        ko: '먼저 다가가서 불편한 점이 없는지 물어보고 옆에서 챙겨준다',
        en: 'Approach first, ask if anything is uncomfortable, and look after them',
        ja: '先に声をかけ、不便がないか聞き、そばでフォローする',
        'zh-CN': '先主动接近，问有没有不便，并在旁照顾',
        'zh-TW': '先主動接近，問有沒有不便，並在旁照顧',
        vi: 'Chủ động tiếp cận trước, hỏi có điều gì bất tiện không và quan tâm bên cạnh',
        id: 'Mendekati dulu, menanyakan apakah ada ketidaknyamanan, dan mendampingi',
    }), 0),
      opt(localeMap({
        ko: '팀 전체가 새 팀원을 환영하는 분위기를 자연스럽게 만든다',
        en: 'Naturally create an atmosphere where the whole team welcomes the new member',
        ja: 'チーム全体が新メンバーを歓迎する雰囲気を自然に作る',
        'zh-CN': '自然营造全队欢迎新成员的氛围',
        'zh-TW': '自然營造全隊歡迎新成員的氛圍',
        vi: 'Tự nhiên tạo không khí cả nhóm chào đón thành viên mới',
        id: 'Secara alami menciptakan suasana tim menyambut anggota baru',
    }), 1),
      opt(localeMap({
        ko: '새 팀원에게 프로젝트 전체 맥락을 정리해서 설명해준다',
        en: 'Organize and explain the overall project context to the new member',
        ja: '新メンバーにプロジェクト全体の文脈を整理して説明する',
        'zh-CN': '为新成员整理并讲解项目整体背景',
        'zh-TW': '為新成員整理並講解專案整體背景',
        vi: 'Tổng hợp và giải thích bối cảnh tổng thể của dự án cho thành viên mới',
        id: 'Merangkum dan menjelaskan konteks proyek secara keseluruhan kepada anggota baru',
    }), 2),
      opt(localeMap({
        ko: '새 팀원의 강점을 파악해서 역할을 빠르게 배정한다',
        en: 'Identify the new member\'s strengths and quickly assign roles',
        ja: '新メンバーの強みを把握し、役割を素早く割り当てる',
        'zh-CN': '了解新成员的优势，快速分配角色',
        'zh-TW': '了解新成員的優勢，快速分配角色',
        vi: 'Nắm điểm mạnh của thành viên mới và phân vai nhanh chóng',
        id: 'Mengidentifikasi kekuatan anggota baru dan segera menetapkan peran',
    }), 3),
    ],
  },
  {
    id: 9,
    question: localeMap({
      ko: '상황: 회의 중 팀원 한 명이 계속 소극적이고 말을 잘 안 한다. 나는?',
      en: 'Situation: During a meeting, one team member stays passive and barely speaks. I would…',
      ja: '状況：会議中、チームメンバーの一人がずっと消極的であまり話さない。私は？',
      'zh-CN': '情况：会议中有一名队员一直比较被动，不太说话。我会？',
      'zh-TW': '情況：會議中有一名隊員一直比較被動，不太說話。我會？',
      vi: 'Tình huống: Trong cuộc họp, một thành viên liên tục thụ động và ít nói. Tôi sẽ…',
      id: 'Situasi: Saat rapat, satu anggota tim terus pasif dan jarang bicara. Saya…',
    }),
    options: [
      opt(localeMap({
        ko: '눈치채고 회의 후 따로 "괜찮아요?"라고 먼저 말을 건넨다',
        en: 'Notice it and after the meeting ask separately, "Are you okay?"',
        ja: '気づいて会議後に個別に「大丈夫ですか？」と声をかける',
        'zh-CN': '察觉后在会后单独问「你还好吗？」',
        'zh-TW': '察覺後在會後單獨問「你還好嗎？」',
        vi: 'Nhận ra và sau họp hỏi riêng: "Bạn ổn chứ?"',
        id: 'Menyadarinya dan setelah rapat menanyakan secara terpisah, "Kamu baik-baik saja?"',
    }), 0),
      opt(localeMap({
        ko: '회의 중 그 팀원에게 직접 의견을 물어보는 기회를 만든다',
        en: 'Create an opportunity during the meeting to directly ask that member\'s opinion',
        ja: '会議中にそのメンバーに直接意見を聞く機会を作る',
        'zh-CN': '在会议中创造机会，直接询问该成员意见',
        'zh-TW': '在會議中創造機會，直接詢問該成員意見',
        vi: 'Tạo cơ hội trong cuộc họp để trực tiếp hỏi ý kiến thành viên đó',
        id: 'Menciptakan kesempatan saat rapat untuk langsung menanyakan pendapat anggota tersebut',
    }), 1),
      opt(localeMap({
        ko: '다음 회의 전에 미리 각자 의견을 적어오도록 구조를 바꿔본다',
        en: 'Change the structure so everyone writes their opinions before the next meeting',
        ja: '次の会議前に各自意見を書いてくるよう構造を変える',
        'zh-CN': '调整结构，让下次会议前各自先写下意见',
        'zh-TW': '調整結構，讓下次會議前各自先寫下意見',
        vi: 'Thay đổi cấu trúc để mọi người viết ý kiến trước cuộc họp tiếp theo',
        id: 'Mengubah struktur agar semua menulis pendapat sebelum rapat berikutnya',
    }), 2),
      opt(localeMap({
        ko: '"모두가 참여해야 좋은 결과가 나온다"며 적극 참여를 독려한다',
        en: 'Encourage active participation: "Good results come when everyone participates"',
        ja: '「全員が参加してこそ良い結果が出る」と積極的参加を促す',
        'zh-CN': '鼓励积极参与：「大家都参与才会有好结果」',
        'zh-TW': '鼓勵積極參與：「大家都參與才會有好結果」',
        vi: 'Khuyến khích tham gia tích cực: "Mọi người cùng tham gia mới có kết quả tốt"',
        id: 'Mendorong partisipasi aktif: "Hasil yang baik datang ketika semua ikut serta"',
    }), 3),
    ],
  },
  {
    id: 10,
    question: localeMap({
      ko: '상황: 팀이 예상보다 좋은 성과를 냈다. 팀원들이 쉬고 싶어한다. 나는?',
      en: 'Situation: The team achieved better results than expected. Members want to rest. I would…',
      ja: '状況：チームが予想以上の成果を出した。メンバーは休みたがっている。私は？',
      'zh-CN': '情况：团队取得了超出预期的成果。队员想休息。我会？',
      'zh-TW': '情況：團隊取得了超出預期的成果。隊員想休息。我會？',
      vi: 'Tình huống: Nhóm đạt kết quả tốt hơn dự kiến. Mọi người muốn nghỉ ngơi. Tôi sẽ…',
      id: 'Situasi: Tim mencapai hasil lebih baik dari perkiraan. Anggota ingin istirahat. Saya…',
    }),
    options: [
      opt(localeMap({
        ko: '"잘 했어요. 오늘은 쉬어요"라며 먼저 쉬는 것을 지지한다',
        en: 'Support resting first: "Well done. Let\'s rest today"',
        ja: '「よく頑張りました。今日は休みましょう」と先に休息を支持する',
        'zh-CN': '先支持休息：「做得很好，今天就休息吧」',
        'zh-TW': '先支持休息：「做得很好，今天就休息吧」',
        vi: 'Ủng hộ nghỉ ngơi trước: "Làm tốt lắm. Hôm nay nghỉ đi"',
        id: 'Mendukung istirahat dulu: "Kerja bagus. Hari ini kita istirahat"',
    }), 0),
      opt(localeMap({
        ko: '팀원들과 함께 성과를 축하하는 자리를 만든다',
        en: 'Create an occasion to celebrate the achievement with team members',
        ja: 'チームメンバーと一緒に成果を祝う場を作る',
        'zh-CN': '和队员一起创造庆祝成果的机会',
        'zh-TW': '和隊員一起創造慶祝成果的機會',
        vi: 'Tạo dịp cùng đồng đội ăn mừng thành tích',
        id: 'Membuat momen untuk merayakan pencapaian bersama anggota tim',
    }), 1),
      opt(localeMap({
        ko: '이번 성과의 원인을 분석하고 다음 단계를 준비한다',
        en: 'Analyze the causes of this achievement and prepare the next steps',
        ja: '今回の成果の原因を分析し、次のステップを準備する',
        'zh-CN': '分析这次成果的原因，准备下一步',
        'zh-TW': '分析這次成果的原因，準備下一步',
        vi: 'Phân tích nguyên nhân thành tích lần này và chuẩn bị bước tiếp theo',
        id: 'Menganalisis penyebab pencapaian ini dan menyiapkan langkah berikutnya',
    }), 2),
      opt(localeMap({
        ko: '"이 기세를 유지하면 더 큰 것도 가능하다"며 다음 목표를 제시한다',
        en: 'Present the next goal: "If we keep this momentum, we can achieve even bigger things"',
        ja: '「この勢いを保てば、もっと大きなことも可能だ」と次の目標を提示する',
        'zh-CN': '提出下一个目标：「保持这股势头，还能做到更大」',
        'zh-TW': '提出下一個目標：「保持這股勢頭，還能做到更大」',
        vi: 'Đưa ra mục tiêu tiếp theo: "Giữ đà này thì còn làm được điều lớn hơn"',
        id: 'Menyampaikan target berikutnya: "Kalau momentum ini dijaga, hal yang lebih besar pun mungkin"',
    }), 3),
    ],
  },
  {
    id: 11,
    question: localeMap({
      ko: '상황: 프로젝트 도중 외부 변수로 계획을 완전히 바꿔야 하는 상황이 됐다. 나는?',
      en: 'Situation: Mid-project, external variables require completely changing the plan. I would…',
      ja: '状況：プロジェクト途中で外部要因により計画を完全に変えなければならなくなった。私は？',
      'zh-CN': '情况：项目中途因外部变量必须彻底改变计划。我会？',
      'zh-TW': '情況：專案中途因外部變數必須徹底改變計畫。我會？',
      vi: 'Tình huống: Giữa dự án, biến số bên ngoài buộc phải thay đổi hoàn toàn kế hoạch. Tôi sẽ…',
      id: 'Situasi: Di tengah proyek, variabel eksternal mengharuskan rencana diubah total. Saya…',
    }),
    options: [
      opt(localeMap({
        ko: '팀원들이 당황하지 않도록 먼저 안정감을 주려 한다',
        en: 'Try to give stability first so team members don\'t panic',
        ja: 'チームメンバーが慌てないよう、先に安心感を与える',
        'zh-CN': '先给予稳定感，避免队员慌乱',
        'zh-TW': '先給予穩定感，避免隊員慌亂',
        vi: 'Cố tạo cảm giác ổn định trước để đồng đội không hoảng loạn',
        id: 'Memberi rasa stabil terlebih dahulu agar anggota tim tidak panik',
    }), 0),
      opt(localeMap({
        ko: '팀 전체와 상황을 공유하고 새로운 방향을 함께 결정한다',
        en: 'Share the situation with the whole team and decide the new direction together',
        ja: 'チーム全体と状況を共有し、新しい方向性を一緒に決める',
        'zh-CN': '与全队共享情况，一起决定新方向',
        'zh-TW': '與全隊共享情況，一起決定新方向',
        vi: 'Chia sẻ tình huống với cả nhóm và cùng quyết định hướng mới',
        id: 'Berbagi situasi dengan seluruh tim dan memutuskan arah baru bersama',
    }), 1),
      opt(localeMap({
        ko: '변화된 상황을 빠르게 분석하고 수정 계획을 만든다',
        en: 'Quickly analyze the changed situation and create a revised plan',
        ja: '変化した状況を素早く分析し、修正計画を作る',
        'zh-CN': '快速分析变化后的情况，制定修改计划',
        'zh-TW': '快速分析變化後的情況，制定修改計畫',
        vi: 'Phân tích nhanh tình huống thay đổi và lập kế hoạch điều chỉnh',
        id: 'Menganalisis situasi yang berubah dengan cepat dan membuat rencana revisi',
    }), 2),
      opt(localeMap({
        ko: '"방향이 바뀌어도 우리가 달성해야 할 것은 같다"며 핵심을 잡는다',
        en: 'Focus on the core: "Even if the direction changes, what we must achieve stays the same"',
        ja: '「方向が変わっても、達成すべきことは同じだ」と核心を掴む',
        'zh-CN': '抓住核心：「方向变了，我们要达成的目标不变」',
        'zh-TW': '抓住核心：「方向變了，我們要達成的目標不變」',
        vi: 'Nắm cốt lõi: "Dù hướng đi thay đổi, điều ta phải đạt vẫn như cũ"',
        id: 'Menjaga inti: "Meski arah berubah, hal yang harus kita capai tetap sama"',
    }), 3),
    ],
  },
  {
    id: 12,
    question: localeMap({
      ko: '상황: 이 테스트를 팀원들과 같이 하게 됐다. 나는?',
      en: 'Situation: I am taking this test together with team members. I would…',
      ja: '状況：このテストをチームメンバーと一緒に受けることになった。私は？',
      'zh-CN': '情况：要和队员们一起做这个测试。我会？',
      'zh-TW': '情況：要和隊員們一起做這個測驗。我會？',
      vi: 'Tình huống: Tôi sẽ làm bài test này cùng các thành viên trong nhóm. Tôi sẽ…',
      id: 'Situasi: Saya akan mengerjakan tes ini bersama anggota tim. Saya…',
    }),
    options: [
      opt(localeMap({
        ko: '팀원들이 재밌게 할 수 있도록 먼저 분위기를 띄운다',
        en: 'First liven the atmosphere so team members can have fun',
        ja: 'チームメンバーが楽しめるよう、先に雰囲気を盛り上げる',
        'zh-CN': '先活跃气氛，让队员玩得开心',
        'zh-TW': '先活躍氣氛，讓隊員玩得開心',
        vi: 'Khuấy động không khí trước để đồng đội vui vẻ',
        id: 'Menyemarakkan suasana dulu agar anggota tim bisa menikmati',
    }), 0),
      opt(localeMap({
        ko: '"다들 결과 공유해봐요. 서로 알아가면 좋을 것 같아서"라고 제안한다',
        en: 'Suggest, "Let\'s share our results. It would be good to get to know each other"',
        ja: '「みんな結果を共有しよう。お互いを知るのに良さそう」と提案する',
        'zh-CN': '提议：「大家分享结果吧，互相了解会很好」',
        'zh-TW': '提議：「大家分享結果吧，互相了解會很好」',
        vi: 'Đề xuất: "Mọi người chia sẻ kết quả nhé. Biết nhau hơn sẽ tốt"',
        id: 'Mengusulkan, "Yuk bagikan hasilnya. Lebih baik kita saling kenal"',
    }), 1),
      opt(localeMap({
        ko: '각자 결과를 보고 팀 내 역할 분담에 어떻게 활용할지 생각해본다',
        en: 'Look at each result and think about how to use them for team role division',
        ja: '各自の結果を見て、チーム内の役割分担にどう活かすか考える',
        'zh-CN': '看各自结果，思考如何用于团队内分工',
        'zh-TW': '看各自結果，思考如何用於團隊內分工',
        vi: 'Xem kết quả từng người và nghĩ cách dùng cho phân công vai trò trong nhóm',
        id: 'Melihat hasil masing-masing dan memikirkan cara memanfaatkannya untuk pembagian peran tim',
    }), 2),
      opt(localeMap({
        ko: '팀 리더십 유형 분포를 파악해서 앞으로 팀 운영에 반영하려 한다',
        en: 'Understand the team\'s leadership type distribution and reflect it in future team operations',
        ja: 'チームのリーダーシップタイプ分布を把握し、今後のチーム運営に反映する',
        'zh-CN': '掌握团队领导力类型分布，用于今后的团队运营',
        'zh-TW': '掌握團隊領導力類型分布，用於今後的團隊運營',
        vi: 'Nắm phân bố kiểu lãnh đạo của nhóm để áp dụng vào vận hành team sau này',
        id: 'Memahami distribusi tipe kepemimpinan tim untuk diterapkan dalam operasional tim ke depan',
    }), 3),
    ],
  },
];

export const phase3LeadershipStyleResults: Phase3LeadershipStyleResult[] = [
  {
    type: "Type1",
    emoji: "🤝",
    title: localeMap({
      ko: '팀의 온도를 지키는 사람, 서번트 리더십형',
      en: 'The One Who Keeps the Team\'s Temperature, Servant Leadership Type',
      ja: 'チームの温度を保つ人、サーバント・リーダーシップ型',
      'zh-CN': '守护团队温度的人，服务型领导型',
      'zh-TW': '守護團隊溫度的人，服務型領導型',
      vi: 'Người giữ nhiệt độ nhóm, kiểu lãnh đạo phục vụ',
      id: 'Penjaga suhu tim, tipe kepemimpinan pelayan',
    }),
    shortDescription: localeMap({
      ko: '당신이 있는 팀에서는 아무도 혼자 힘들어하지 않습니다.',
      en: 'On a team with you, no one struggles alone.',
      ja: 'あなたがいるチームでは、誰も一人で苦しまない。',
      'zh-CN': '有你在的团队里，没有人独自承受困难。',
      'zh-TW': '有你在的團隊裡，沒有人獨自承受困難。',
      vi: 'Trong nhóm có bạn, không ai phải vất vả một mình.',
      id: 'Di tim yang ada kamu, tidak ada yang berjuang sendirian.',
    }),
    description: localeMap({
      ko: '팀원의 감정과 상태를 먼저 챙기고 내가 앞에 나서기보다 팀원들이 각자 잘 할 수 있는 환경을 만드는 데 집중하는 리더십입니다. 팀이 어려울 때 가장 먼저 손을 내미는 사람입니다.',
      en: 'A leadership style focused on caring for team members\' emotions and conditions first, and on creating an environment where everyone can do their best rather than stepping to the front yourself. You are the first to reach out when the team is struggling.',
      ja: 'チームメンバーの感情と状態を先に気にかけ、自分が前に出るより、各自が力を発揮できる環境づくりに集中するリーダーシップです。チームが苦しいとき、真っ先に手を差し伸べる人です。',
      'zh-CN': '这是一种优先关心队员情绪与状态、比起自己出头更专注于营造让每个人发挥所长的环境的领导力。团队困难时，你是第一个伸出手的人。',
      'zh-TW': '這是一種優先關心隊員情緒與狀態、比起自己出頭更專注於營造讓每個人發揮所長的環境的領導力。團隊困難時，你是第一個伸出手的人。',
      vi: 'Đây là kiểu lãnh đạo ưu tiên cảm xúc và trạng thái của thành viên, tập trung tạo môi trường để mọi người phát huy thay vì tự mình đứng ra trước. Bạn là người đầu tiên vươn tay khi nhóm gặp khó.',
      id: 'Gaya kepemimpinan yang mengutamakan emosi dan kondisi anggota tim, fokus menciptakan lingkungan agar semua bisa bekerja optimal alih-alih tampil di depan. Kamu yang pertama mengulurkan tangan saat tim kesulitan.',
    }),
    leadershipStyle: localeMap({
      ko: '서번트 리더십 🤝',
      en: 'Servant Leadership 🤝',
      ja: 'サーバント・リーダーシップ 🤝',
      'zh-CN': '服务型领导 🤝',
      'zh-TW': '服務型領導 🤝',
      vi: 'Lãnh đạo phục vụ 🤝',
      id: 'Kepemimpinan pelayan 🤝',
    }),
    leadershipKeywords: localeMap({
      ko: '배려·지지·신뢰 형성·심리적 안전감',
      en: 'Care · Support · Trust building · Psychological safety',
      ja: '配慮・支援・信頼形成・心理的安全',
      'zh-CN': '关怀·支持·建立信任·心理安全感',
      'zh-TW': '關懷·支持·建立信任·心理安全感',
      vi: 'Quan tâm · Hỗ trợ · Xây dựng niềm tin · An toàn tâm lý',
      id: 'Perhatian · Dukungan · Membangun kepercayaan · Rasa aman psikologis',
    }),
    teamRole: localeMap({
      ko: '팀 분위기 관리·갈등 완충·사각지대 케어',
      en: 'Team mood management · Conflict buffering · Caring for blind spots',
      ja: 'チーム雰囲気管理・対立の緩和・盲点ケア',
      'zh-CN': '团队氛围管理·冲突缓冲·关注盲区',
      'zh-TW': '團隊氛圍管理·衝突緩衝·關注盲區',
      vi: 'Quản lý không khí nhóm · Giảm xung đột · Chăm sóc góc khuất',
      id: 'Mengelola suasana tim · Meredam konflik · Merawat titik buta',
    }),
    strength: localeMap({
      ko: '팀원들이 자발적으로 움직이는 심리적 안전감 형성. 장기 팀워크에서 가장 강함',
      en: 'Builds psychological safety that motivates voluntary action. Strongest in long-term teamwork.',
      ja: 'メンバーが自発的に動く心理的安全を形成。長期チームワークで最も強い。',
      'zh-CN': '形成让队员自发行动的心理安全感，在长期团队合作中最强。',
      'zh-TW': '形成讓隊員自發行動的心理安全感，在長期團隊合作中最強。',
      vi: 'Tạo cảm giác an toàn tâm lý giúp mọi người chủ động hành động. Mạnh nhất trong teamwork dài hạn.',
      id: 'Membentuk rasa aman psikologis yang mendorong inisiatif. Paling kuat dalam teamwork jangka panjang.',
    }),
    weakness: localeMap({
      ko: '빠른 결정이 필요한 순간에 느려질 수 있음. 때로는 방향 제시가 필요함',
      en: 'Can be slow when quick decisions are needed. Direction-setting is sometimes necessary.',
      ja: '迅速な決断が必要な場面では遅くなることがある。時には方向提示が必要。',
      'zh-CN': '需要快速决策时可能偏慢，有时也需要给出方向。',
      'zh-TW': '需要快速決策時可能偏慢，有時也需要給出方向。',
      vi: 'Có thể chậm khi cần quyết định nhanh. Đôi khi vẫn cần chỉ hướng.',
      id: 'Bisa lambat saat butuh keputusan cepat. Terkadang perlu memberi arah.',
    }),
    goodEnvironment: localeMap({
      ko: '장기 프로젝트·다양한 구성원·심리적 안정이 중요한 팀',
      en: 'Long-term projects · Diverse members · Teams where psychological stability matters',
      ja: '長期プロジェクト・多様なメンバー・心理的安定が重要なチーム',
      'zh-CN': '长期项目·多元成员·重视心理稳定的团队',
      'zh-TW': '長期專案·多元成員·重視心理穩定的團隊',
      vi: 'Dự án dài hạn · Thành viên đa dạng · Nhóm coi trọng ổn định tâm lý',
      id: 'Proyek jangka panjang · Anggota beragam · Tim yang mengutamakan stabilitas psikologis',
    }),
    goodMatch: localeMap({
      ko: '방향을 잡아주는 변혁형·결단을 내리는 카리스마형과 조합 시 최강',
      en: 'Strongest paired with transformational types who set direction and charismatic types who decide',
      ja: '方向を示す変革型・決断するカリスマ型と組み合わせると最強',
      'zh-CN': '与定方向的变革型、做决断的魅力型组合最强',
      'zh-TW': '與定方向的變革型、做決斷的魅力型組合最強',
      vi: 'Mạnh nhất khi kết hợp với kiểu biến đổi định hướng và kiểu quyết đoán',
      id: 'Paling kuat jika dipadukan dengan tipe transformasional pengarah dan tipe karismatik pengambil keputusan',
    }),
    coverLetterPhrase: localeMap({
      ko: '저는 팀 프로젝트에서 팀원 개개인의 상태를 먼저 살피고 각자가 강점을 발휘할 수 있는 환경을 만드는 역할을 해왔습니다',
      en: 'In team projects, I have focused on checking each member\'s condition first and creating an environment where everyone can leverage their strengths.',
      ja: 'チームプロジェクトでは、メンバー一人ひとりの状態を先に見て、各自が強みを発揮できる環境づくりを担ってきました。',
      'zh-CN': '在团队项目中，我习惯先关注每位队员的状态，并营造让各自发挥优势的环境。',
      'zh-TW': '在團隊專案中，我習慣先關注每位隊員的狀態，並營造讓各自發揮優勢的環境。',
      vi: 'Trong dự án nhóm, tôi thường quan sát trạng thái từng thành viên trước và tạo môi trường để mọi người phát huy điểm mạnh.',
      id: 'Dalam proyek tim, saya terbiasa memperhatikan kondisi tiap anggota terlebih dahulu dan menciptakan lingkungan agar semua bisa memaksimalkan kekuatan mereka.',
    }),
    coverLetterMaterial: localeMap({
      ko: '팀원이 어려움을 겪을 때 먼저 다가가서 해결한 경험·심리적 안전감을 만들어 팀 성과를 높인 사례',
      en: 'Experience approaching a struggling teammate first to help · Cases where building psychological safety improved team performance',
      ja: 'メンバーが苦しいときに先に声をかけて解決した経験・心理的安全を作りチーム成果を高めた事例',
      'zh-CN': '队员遇到困难时主动接近并解决的经历·营造心理安全感提升团队绩效的案例',
      'zh-TW': '隊員遇到困難時主動接近並解決的經歷·營造心理安全感提升團隊績效的案例',
      vi: 'Kinh nghiệm chủ động giúp đỡ khi đồng đội gặp khó · Trường hợp tạo an toàn tâm lý và nâng hiệu suất nhóm',
      id: 'Pengalaman mendekati anggota yang kesulitan dan membantu · Contoh membangun rasa aman psikologis untuk meningkatkan kinerja tim',
    }),
    shareLine: localeMap({
      ko: '내 리더십 스타일: 서번트형 🤝 팀원 먼저 챙기는 유형이래... 내 팀원들은 혼자 힘들어하지 않는다는 거 인정 → 너는 어떤 리더십 스타일이야? 자소서 소재로도 써봐',
      en: 'My leadership style: Servant type 🤝 They say I take care of teammates first... Admit it, my team never struggles alone → What\'s your leadership style? Try it for your cover letter too.',
      ja: '私のリーダーシップスタイル：サーバント型 🤝 チームメンバーを先に気にかけるタイプらしい…一人で苦しまないって認めて → あなたはどんなリーダーシップ？',
      'zh-CN': '我的领导风格：服务型 🤝 说是会先照顾队员的类型…承认吧，我的队员不会独自硬扛 → 你是什么领导风格？也可以当求职信素材',
      'zh-TW': '我的領導風格：服務型 🤝 說是會先照顧隊員的類型…承認吧，我的隊員不會獨自硬扛 → 你是什麼領導風格？也可以當求職信素材',
      vi: 'Phong cách lãnh đạo của tôi: Kiểu phục vụ 🤝 Bảo là lo cho đồng đội trước… thừa nhận đi, nhóm tôi không ai vất vả một mình → Bạn thuộc kiểu nào?',
      id: 'Gaya kepemimpinanku: Tipe pelayan 🤝 Katanya aku yang urus tim dulu… akui deh, timku nggak ada yang ngeluh sendirian → Kamu tipe apa? Bisa buat bahan cover letter juga',
    }),
  },
  {
    type: "Type2",
    emoji: "🗣️",
    title: localeMap({
      ko: '모두의 목소리를 담는 사람, 민주적 리더십형',
      en: 'The One Who Holds Everyone\'s Voice, Democratic Leadership Type',
      ja: 'みんなの声を受け止める人、民主的リーダーシップ型',
      'zh-CN': '容纳所有人声音的人，民主领导型',
      'zh-TW': '容納所有人聲音的人，民主領導型',
      vi: 'Người lắng nghe mọi tiếng nói, kiểu lãnh đạo dân chủ',
      id: 'Penampung suara semua orang, tipe kepemimpinan demokratis',
    }),
    shortDescription: localeMap({
      ko: '당신이 있는 회의에서는 아무도 소외되지 않습니다.',
      en: 'In meetings with you, no one is left out.',
      ja: 'あなたがいる会議では、誰も置き去りにされない。',
      'zh-CN': '有你在的会议里，没有人被边缘化。',
      'zh-TW': '有你在的會議裡，沒有人被邊緣化。',
      vi: 'Trong cuộc họp có bạn, không ai bị bỏ rơi.',
      id: 'Dalam rapat yang ada kamu, tidak ada yang terpinggirkan.',
    }),
    description: localeMap({
      ko: '팀원 모두의 의견을 끌어내고 그 안에서 공통점을 찾아 합의점을 만드는 리더십입니다. 결정을 독단적으로 내리지 않고 팀 전체가 동의한 방향으로 나아가게 합니다. 팀원들이 결정에 주인의식을 갖게 만드는 것이 강점입니다.',
      en: 'A leadership style that draws out everyone\'s opinions, finds common ground, and builds consensus. Rather than deciding alone, you move the team in a direction everyone agrees on. Your strength is giving members ownership over decisions.',
      ja: 'チーム全員の意見を引き出し、その中から共通点を見つけ合意点を作るリーダーシップです。独断的に決めず、チーム全体が納得した方向へ進めます。決定への当事者意識を持たせるのが強みです。',
      'zh-CN': '这是一种引出所有队员意见、在其中找共同点并形成共识的领导力。不独断决策，而是让团队朝大家都认同的方向前进。擅长让队员对决定有主人翁意识。',
      'zh-TW': '這是一種引出所有隊員意見、在其中找共同點並形成共識的領導力。不獨斷決策，而是讓團隊朝大家都認同的方向前進。擅長讓隊員對決定有主人翁意識。',
      vi: 'Kiểu lãnh đạo khai thác ý kiến mọi người, tìm điểm chung và tạo thỏa thuận. Không quyết định độc đoán mà dẫn nhóm theo hướng mọi người đồng ý. Mạnh ở việc tạo cảm giác chủ động với quyết định.',
      id: 'Gaya kepemimpinan yang menggali pendapat semua anggota, mencari titik temu, dan membangun konsensus. Tidak memutuskan sendiri, melainkan mengarahkan tim ke arah yang disepakati bersama. Kuat dalam memberi rasa kepemilikan atas keputusan.',
    }),
    leadershipStyle: localeMap({
      ko: '민주적 리더십 🗣️',
      en: 'Democratic Leadership 🗣️',
      ja: '民主的リーダーシップ 🗣️',
      'zh-CN': '民主领导 🗣️',
      'zh-TW': '民主領導 🗣️',
      vi: 'Lãnh đạo dân chủ 🗣️',
      id: 'Kepemimpinan demokratis 🗣️',
    }),
    leadershipKeywords: localeMap({
      ko: '소통·합의·참여·수평적 관계',
      en: 'Communication · Consensus · Participation · Horizontal relationships',
      ja: 'コミュニケーション・合意・参加・水平関係',
      'zh-CN': '沟通·共识·参与·平等关系',
      'zh-TW': '溝通·共識·參與·平等關係',
      vi: 'Giao tiếp · Thỏa thuận · Tham gia · Quan hệ bình đẳng',
      id: 'Komunikasi · Konsensus · Partisipasi · Relasi horizontal',
    }),
    teamRole: localeMap({
      ko: '회의 진행·의견 조율·팀 합의 도출',
      en: 'Facilitating meetings · Coordinating opinions · Building team consensus',
      ja: '会議進行・意見調整・チーム合意形成',
      'zh-CN': '主持会议·协调意见·达成团队共识',
      'zh-TW': '主持會議·協調意見·達成團隊共識',
      vi: 'Điều phối họp · Hòa giải ý kiến · Tạo đồng thuận nhóm',
      id: 'Memimpin rapat · Menyelaraskan pendapat · Membentuk konsensus tim',
    }),
    strength: localeMap({
      ko: '팀 전체의 참여도와 주인의식이 높아짐. 다양한 의견이 반영된 결과물 도출',
      en: 'Higher participation and ownership across the team. Outcomes reflect diverse opinions.',
      ja: 'チーム全体の参加度と当事者意識が高まる。多様な意見が反映された成果。',
      'zh-CN': '提升全队参与度与主人翁意识，产出融合多元意见的成果。',
      'zh-TW': '提升全隊參與度與主人翁意識，產出融合多元意見的成果。',
      vi: 'Tăng mức tham gia và tinh thần chủ động của cả nhóm. Kết quả phản ánh nhiều quan điểm.',
      id: 'Partisipasi dan rasa kepemilikan tim meningkat. Hasil mencerminkan beragam pendapat.',
    }),
    weakness: localeMap({
      ko: '의사결정이 느려질 수 있음. 의견이 너무 다를 때 합의가 어렵고 시간이 오래 걸림',
      en: 'Decisions can be slow. When opinions diverge too much, consensus is hard and takes time.',
      ja: '意思決定が遅くなることがある。意見が大きく分かれると合意に時間がかかる。',
      'zh-CN': '决策可能偏慢，意见分歧大时难以达成共识且耗时。',
      'zh-TW': '決策可能偏慢，意見分歧大時難以達成共識且耗時。',
      vi: 'Quyết định có thể chậm. Khi ý kiến quá khác nhau, khó thỏa thuận và mất thời gian.',
      id: 'Keputusan bisa lambat. Saat pendapat terlalu berbeda, konsensus sulit dan memakan waktu.',
    }),
    goodEnvironment: localeMap({
      ko: '창의적 문제 해결·다양한 전문성이 모인 팀·구성원의 자율성이 중요한 환경',
      en: 'Creative problem-solving · Teams with diverse expertise · Environments that value autonomy',
      ja: '創造的な問題解決・多様な専門性のチーム・メンバーの自律性が重要な環境',
      'zh-CN': '创意解决问题·多元专业团队·重视成员自主性的环境',
      'zh-TW': '創意解決問題·多元專業團隊·重視成員自主性的環境',
      vi: 'Giải quyết vấn đề sáng tạo · Nhóm đa chuyên môn · Môi trường coi trọng tự chủ',
      id: 'Penyelesaian masalah kreatif · Tim dengan keahlian beragam · Lingkungan yang menghargai otonomi',
    }),
    goodMatch: localeMap({
      ko: '빠른 결단의 카리스마형·구조를 잡는 전략형과 조합 시 균형',
      en: 'Balanced when paired with charismatic types for quick decisions and strategic types for structure',
      ja: '迅速な決断のカリスマ型・構造を作る戦略型と組み合わせるとバランスが取れる',
      'zh-CN': '与快速决断的魅力型、搭建结构的战略型组合更平衡',
      'zh-TW': '與快速決斷的魅力型、搭建結構的戰略型組合更平衡',
      vi: 'Cân bằng hơn khi kết hợp với kiểu quyết đoán và kiểu chiến lược',
      id: 'Lebih seimbang jika dipadukan dengan tipe karismatik pengambil keputusan dan tipe strategis penyusun struktur',
    }),
    coverLetterPhrase: localeMap({
      ko: '저는 팀 의사결정 과정에서 구성원 모두의 의견을 수렴하고 합의점을 찾는 방식으로 팀의 방향성을 설정해왔습니다',
      en: 'In team decision-making, I have set direction by gathering everyone\'s opinions and finding consensus.',
      ja: 'チームの意思決定では、構成員全員の意見を集め、合意点を見つける方法で方向性を定めてきました。',
      'zh-CN': '在团队决策中，我通过收集所有成员意见并寻找共识来设定方向。',
      'zh-TW': '在團隊決策中，我透過收集所有成員意見並尋找共識來設定方向。',
      vi: 'Trong quyết định nhóm, tôi thu thập ý kiến mọi người và tìm điểm đồng thuận để định hướng.',
      id: 'Dalam pengambilan keputusan tim, saya mengumpulkan pendapat semua anggota dan mencari konsensus untuk menetapkan arah.',
    }),
    coverLetterMaterial: localeMap({
      ko: '의견 충돌이 있는 팀에서 모두가 납득할 수 있는 결론을 이끌어낸 경험',
      en: 'Experience leading a divided team to a conclusion everyone could accept',
      ja: '意見が対立するチームで、全員が納得できる結論を導いた経験',
      'zh-CN': '在意见冲突的团队中引导出大家都能接受的结论的经历',
      'zh-TW': '在意見衝突的團隊中引導出大家都能接受的結論的經歷',
      vi: 'Kinh nghiệm dẫn dắt nhóm ý kiến xung đột đến kết luận mọi người chấp nhận',
      id: 'Pengalaman memimpin tim dengan konflik pendapat menuju kesimpulan yang diterima semua',
    }),
    shareLine: localeMap({
      ko: '내 리더십 스타일: 민주형 🗣️ 모두의 의견 담아서 합의 이끄는 유형이래... 회의에서 아무도 소외 안 된다는 거 맞음 → 너는 어떤 리더십 스타일이야?',
      en: 'My leadership style: Democratic type 🗣️ They say I lead consensus by holding everyone\'s voice... True, no one gets left out in my meetings → What\'s your leadership style?',
      ja: '私のリーダーシップスタイル：民主型 🗣️ みんなの意見を集めて合意を導くタイプらしい…会議で誰も置き去りにしないのは本当 → あなたは？',
      'zh-CN': '我的领导风格：民主型 🗣️ 说是汇总意见引导共识的类型…会议里没人被落下，没错 → 你是什么领导风格？',
      'zh-TW': '我的領導風格：民主型 🗣️ 說是彙總意見引導共識的類型…會議裡沒人被落下，沒錯 → 你是什麼領導風格？',
      vi: 'Phong cách lãnh đạo của tôi: Kiểu dân chủ 🗣️ Bảo là gom ý kiến dẫn đến thỏa thuận… đúng là họp không ai bị bỏ rơi → Bạn thuộc kiểu nào?',
      id: 'Gaya kepemimpinanku: Tipe demokratis 🗣️ Katanya aku kumpulin suara semua buat konsensus… bener, di rapatku nggak ada yang kelewat → Kamu tipe apa?',
    }),
  },
  {
    type: "Type3",
    emoji: "📈",
    title: localeMap({
      ko: '팀원을 성장시키는 사람, 코칭 리더십형',
      en: 'The One Who Grows Team Members, Coaching Leadership Type',
      ja: 'チームメンバーを成長させる人、コーチング・リーダーシップ型',
      'zh-CN': '培养队员成长的人，教练型领导',
      'zh-TW': '培養隊員成長的人，教練型領導',
      vi: 'Người giúp thành viên trưởng thành, kiểu lãnh đạo huấn luyện',
      id: 'Pengembang anggota tim, tipe kepemimpinan coaching',
    }),
    shortDescription: localeMap({
      ko: '당신 팀의 팀원들은 프로젝트가 끝나고 나서 더 성장해있습니다.',
      en: 'On your team, members grow more by the time the project ends.',
      ja: 'あなたのチームでは、プロジェクトが終わる頃にメンバーがより成長している。',
      'zh-CN': '在你的团队里，项目结束时队员会比之前更成长。',
      'zh-TW': '在你的團隊裡，專案結束時隊員會比之前更成長。',
      vi: 'Trong nhóm của bạn, thành viên trưởng thành hơn khi dự án kết thúc.',
      id: 'Di tim kamu, anggota tumbuh lebih baik saat proyek selesai.',
    }),
    description: localeMap({
      ko: '결과물만큼 팀원의 성장을 중요하게 여기고 피드백을 통해 팀원이 스스로 문제를 해결하도록 돕는 리더십입니다. 답을 직접 주기보다 팀원이 스스로 찾아낼 수 있도록 질문하고 구조를 만들어줍니다.',
      en: 'A leadership style that values member growth as much as outcomes and helps them solve problems through feedback. Rather than giving answers directly, you ask questions and build structure so members can find solutions themselves.',
      ja: '成果物と同じくらいメンバーの成長を大切にし、フィードバックを通じて自ら問題を解決できるよう支援するリーダーシップです。答えを直接与えるより、質問と構造づくりで自分で見つけられるようにします。',
      'zh-CN': '这是一种与成果同样重视队员成长、通过反馈帮助队员自主解决问题的领导力。与其直接给答案，不如通过提问和搭建结构让他们自己找到答案。',
      'zh-TW': '這是一種與成果同樣重視隊員成長、透過回饋幫助隊員自主解決問題的領導力。與其直接給答案，不如透過提問和搭建結構讓他們自己找到答案。',
      vi: 'Kiểu lãnh đạo coi trọng sự trưởng thành của thành viên như kết quả, giúp họ tự giải quyết vấn đề qua phản hồi. Thay vì đưa đáp án, bạn đặt câu hỏi và tạo cấu trúc để họ tự tìm ra.',
      id: 'Gaya kepemimpinan yang menganggap pertumbuhan anggota sepenting hasil, membantu mereka menyelesaikan masalah lewat feedback. Alih-alih memberi jawaban langsung, kamu bertanya dan membangun struktur agar mereka menemukannya sendiri.',
    }),
    leadershipStyle: localeMap({
      ko: '코칭 리더십 📈',
      en: 'Coaching Leadership 📈',
      ja: 'コーチング・リーダーシップ 📈',
      'zh-CN': '教练型领导 📈',
      'zh-TW': '教練型領導 📈',
      vi: 'Lãnh đạo huấn luyện 📈',
      id: 'Kepemimpinan coaching 📈',
    }),
    leadershipKeywords: localeMap({
      ko: '성장·피드백·질문·잠재력 발굴',
      en: 'Growth · Feedback · Questions · Unlocking potential',
      ja: '成長・フィードバック・質問・潜在力の発掘',
      'zh-CN': '成长·反馈·提问·发掘潜力',
      'zh-TW': '成長·回饋·提問·發掘潛力',
      vi: 'Trưởng thành · Phản hồi · Câu hỏi · Khai phá tiềm năng',
      id: 'Pertumbuhan · Feedback · Pertanyaan · Menggali potensi',
    }),
    teamRole: localeMap({
      ko: '팀원 역량 개발·피드백 제공·문제 해결 구조화',
      en: 'Developing member capabilities · Providing feedback · Structuring problem-solving',
      ja: 'メンバーの能力開発・フィードバック提供・問題解決の構造化',
      'zh-CN': '队员能力开发·提供反馈·结构化问题解决',
      'zh-TW': '隊員能力開發·提供回饋·結構化問題解決',
      vi: 'Phát triển năng lực thành viên · Đưa phản hồi · Cấu trúc hóa giải quyết vấn đề',
      id: 'Mengembangkan kapabilitas anggota · Memberi feedback · Menstrukturkan penyelesaian masalah',
    }),
    strength: localeMap({
      ko: '팀원 개개인의 역량이 올라가 장기적으로 팀 전체 수준이 높아짐. 신뢰 관계 형성',
      en: 'Individual capabilities rise, raising the team\'s overall level long-term. Builds trust.',
      ja: '個々の能力が上がり、長期的にチーム全体のレベルが高まる。信頼関係を築く。',
      'zh-CN': '每位队员能力提升，长期拉高团队整体水平，并形成信任关系。',
      'zh-TW': '每位隊員能力提升，長期拉高團隊整體水準，並形成信任關係。',
      vi: 'Năng lực từng người tăng, nâng trình độ cả nhóm về lâu dài. Xây dựng niềm tin.',
      id: 'Kapabilitas tiap anggota naik, meningkatkan level tim jangka panjang. Membangun kepercayaan.',
    }),
    weakness: localeMap({
      ko: '빠른 결과가 필요할 때 코칭 과정이 느리게 느껴질 수 있음',
      en: 'The coaching process can feel slow when fast results are needed.',
      ja: '早い結果が必要なとき、コーチング過程が遅く感じられることがある。',
      'zh-CN': '需要快速出结果时，教练过程可能显得偏慢。',
      'zh-TW': '需要快速出結果時，教練過程可能顯得偏慢。',
      vi: 'Khi cần kết quả nhanh, quá trình coaching có thể cảm thấy chậm.',
      id: 'Saat butuh hasil cepat, proses coaching bisa terasa lambat.',
    }),
    goodEnvironment: localeMap({
      ko: '구성원 성장이 중요한 팀·멘토링 역할이 필요한 환경·장기 프로젝트',
      en: 'Teams where member growth matters · Environments needing mentoring · Long-term projects',
      ja: 'メンバーの成長が重要なチーム・メンタリングが必要な環境・長期プロジェクト',
      'zh-CN': '重视成员成长的团队·需要 mentoring 的环境·长期项目',
      'zh-TW': '重視成員成長的團隊·需要 mentoring 的環境·長期專案',
      vi: 'Nhóm coi trọng sự trưởng thành · Môi trường cần mentoring · Dự án dài hạn',
      id: 'Tim yang mengutamakan pertumbuhan · Lingkungan butuh mentoring · Proyek jangka panjang',
    }),
    goodMatch: localeMap({
      ko: '속도를 높이는 카리스마형·방향을 잡는 변혁형과 조합 시 강력',
      en: 'Powerful paired with charismatic types that increase speed and transformational types that set direction',
      ja: 'スピードを上げるカリスマ型・方向を示す変革型と組み合わせると強力',
      'zh-CN': '与提升速度的魅力型、把握方向的变革型组合很强',
      'zh-TW': '與提升速度的魅力型、把握方向的變革型組合很強',
      vi: 'Mạnh khi kết hợp với kiểu quyết đoán tăng tốc và kiểu biến đổi định hướng',
      id: 'Kuat jika dipadukan dengan tipe karismatik penggerak kecepatan dan tipe transformasional pengarah',
    }),
    coverLetterPhrase: localeMap({
      ko: '저는 팀 프로젝트에서 팀원이 스스로 문제를 해결할 수 있도록 구체적인 피드백과 질문을 통해 역량 개발을 지원해왔습니다',
      en: 'In team projects, I have supported capability development through specific feedback and questions so members can solve problems on their own.',
      ja: 'チームプロジェクトでは、具体的なフィードバックと質問を通じて、メンバーが自ら問題を解決できるよう能力開発を支援してきました。',
      'zh-CN': '在团队项目中，我通过具体反馈和提问支持队员自主解决问题、提升能力。',
      'zh-TW': '在團隊專案中，我透過具體回饋和提問支持隊員自主解決問題、提升能力。',
      vi: 'Trong dự án nhóm, tôi hỗ trợ phát triển năng lực bằng phản hồi và câu hỏi cụ thể để thành viên tự giải quyết vấn đề.',
      id: 'Dalam proyek tim, saya mendukung pengembangan kapabilitas lewat feedback dan pertanyaan spesifik agar anggota menyelesaikan masalah sendiri.',
    }),
    coverLetterMaterial: localeMap({
      ko: '성과가 낮은 팀원에게 피드백을 제공해 성과를 끌어올린 경험·신입 팀원의 성장을 도운 경험',
      en: 'Experience raising performance through feedback for low-performing members · Experience helping new members grow',
      ja: '成果が低いメンバーにフィードバックを提供して成果を引き上げた経験・新入メンバーの成長を支援した経験',
      'zh-CN': '通过反馈帮助低绩效队员提升表现的经历·帮助新队员成长的经历',
      'zh-TW': '透過回饋幫助低績效隊員提升表現的經歷·幫助新隊員成長的經歷',
      vi: 'Kinh nghiệm nâng hiệu suất thành viên kém bằng phản hồi · Kinh nghiệm giúp thành viên mới trưởng thành',
      id: 'Pengalaman meningkatkan kinerja anggota lemah lewat feedback · Pengalaman membantu pertumbuhan anggota baru',
    }),
    shareLine: localeMap({
      ko: '내 리더십 스타일: 코칭형 📈 팀원 성장시키는 유형이래... 피드백 주는 거 자연스럽게 하는 거 맞음 ㅋㅋ → 자소서 리더십 소재 고민이면 해봐',
      en: 'My leadership style: Coaching type 📈 They say I grow teammates... Giving feedback comes naturally, right? → Try this if you need cover letter leadership material.',
      ja: '私のリーダーシップスタイル：コーチング型 📈 チームメンバーを成長させるタイプらしい…フィードバックが自然 → 自己PRのリーダーシップ素材にどうぞ',
      'zh-CN': '我的领导风格：教练型 📈 说是培养队员成长的类型…给反馈很自然吧 ㅋㅋ → 求职信领导力素材发愁就试试',
      'zh-TW': '我的領導風格：教練型 📈 說是培養隊員成長的類型…給回饋很自然吧 ㅋㅋ → 求職信領導力素材發愁就試試',
      vi: 'Phong cách lãnh đạo của tôi: Kiểu coaching 📈 Bảo là giúp đồng đội trưởng thành… cho feedback tự nhiên đúng không → Thử nếu đang thiếu ý tưởng cho CV',
      id: 'Gaya kepemimpinanku: Tipe coaching 📈 Katanya aku grow tim… ngasih feedback memang natural kan → Coba deh kalau lagi cari bahan leadership buat cover letter',
    }),
  },
  {
    type: "Type4",
    emoji: "🌟",
    title: localeMap({
      ko: '팀에 비전을 심는 사람, 변혁적 리더십형',
      en: 'The One Who Plants Vision in the Team, Transformational Leadership Type',
      ja: 'チームにビジョンを植える人、変革的リーダーシップ型',
      'zh-CN': '在团队中植入愿景的人，变革型领导',
      'zh-TW': '在團隊中植入願景的人，變革型領導',
      vi: 'Người gieo tầm nhìn vào nhóm, kiểu lãnh đạo biến đổi',
      id: 'Penanam visi di tim, tipe kepemimpinan transformasional',
    }),
    shortDescription: localeMap({
      ko: '당신이 있는 팀은 그냥 일이 아니라 의미 있는 일을 하고 있다고 느낍니다.',
      en: 'On a team with you, work feels meaningful—not just tasks.',
      ja: 'あなたがいるチームでは、ただの仕事ではなく意味のある仕事をしていると感じる。',
      'zh-CN': '有你在的团队会觉得做的不是普通工作，而是有意义的事。',
      'zh-TW': '有你在的團隊會覺得做的不是普通工作，而是有意義的事。',
      vi: 'Nhóm có bạn cảm thấy mình không chỉ làm việc mà đang làm điều có ý nghĩa.',
      id: 'Tim yang ada kamu merasa sedang melakukan pekerjaan bermakna, bukan sekadar tugas.',
    }),
    description: localeMap({
      ko: '팀이 지금 하는 일이 왜 중요한지 이해하게 만들고 더 큰 목표를 향해 동기를 부여하는 리더십입니다. 결과물보다 팀이 나아가는 방향과 의미에 집중하며 팀원들의 내적 동기를 이끌어냅니다.',
      en: 'A leadership style that helps the team understand why their work matters and motivates them toward bigger goals. Focused on direction and meaning rather than outputs alone, it draws out members\' intrinsic motivation.',
      ja: 'チームが今の仕事がなぜ重要かを理解し、より大きな目標へ動機づけするリーダーシップです。成果物より進む方向と意味に集中し、内発的動機を引き出します。',
      'zh-CN': '这是一种让团队理解当下工作为何重要、并激励大家朝向更大目标前进的领导力。比起结果更关注方向与意义，激发队员的内在动力。',
      'zh-TW': '這是一種讓團隊理解當下工作為何重要、並激勵大家朝向更大目標前進的領導力。比起結果更關注方向與意義，激發隊員的內在動力。',
      vi: 'Kiểu lãnh đạo giúp nhóm hiểu vì sao công việc hiện tại quan trọng và thúc đẩy họ hướng tới mục tiêu lớn hơn. Tập trung vào hướng đi và ý nghĩa, khai thác động lực nội tại.',
      id: 'Gaya kepemimpinan yang membantu tim memahami mengapa pekerjaan mereka penting dan memotivasi menuju tujuan lebih besar. Fokus pada arah dan makna, menggali motivasi intrinsik anggota.',
    }),
    leadershipStyle: localeMap({
      ko: '변혁적 리더십 🌟',
      en: 'Transformational Leadership 🌟',
      ja: '変革的リーダーシップ 🌟',
      'zh-CN': '变革型领导 🌟',
      'zh-TW': '變革型領導 🌟',
      vi: 'Lãnh đạo biến đổi 🌟',
      id: 'Kepemimpinan transformasional 🌟',
    }),
    leadershipKeywords: localeMap({
      ko: '비전·동기부여·의미·영향력',
      en: 'Vision · Motivation · Meaning · Influence',
      ja: 'ビジョン・動機づけ・意味・影響力',
      'zh-CN': '愿景·激励·意义·影响力',
      'zh-TW': '願景·激勵·意義·影響力',
      vi: 'Tầm nhìn · Động lực · Ý nghĩa · Ảnh hưởng',
      id: 'Visi · Motivasi · Makna · Pengaruh',
    }),
    teamRole: localeMap({
      ko: '방향 설정·팀 동기부여·의미 부여',
      en: 'Setting direction · Motivating the team · Creating meaning',
      ja: '方向設定・チームの動機づけ・意味付け',
      'zh-CN': '设定方向·激励团队·赋予意义',
      'zh-TW': '設定方向·激勵團隊·賦予意義',
      vi: 'Định hướng · Truyền động lực · Tạo ý nghĩa',
      id: 'Menetapkan arah · Memotivasi tim · Memberi makna',
    }),
    strength: localeMap({
      ko: '팀원들의 내적 동기가 높아져 자발적이고 창의적인 기여가 늘어남',
      en: 'Higher intrinsic motivation leads to more voluntary and creative contributions.',
      ja: '内発的動機が高まり、自発的で創造的な貢献が増える。',
      'zh-CN': '队员内在动力提升，自发且富有创意的贡献增多。',
      'zh-TW': '隊員內在動力提升，自發且富有創意的貢獻增多。',
      vi: 'Động lực nội tại tăng, đóng góp chủ động và sáng tạo nhiều hơn.',
      id: 'Motivasi intrinsik meningkat, kontribusi spontan dan kreatif bertambah.',
    }),
    weakness: localeMap({
      ko: '현실적인 실행 계획 수립이 약할 수 있음. 구체적인 실행 역할이 함께 필요',
      en: 'Realistic execution planning may be weaker. Needs partners for concrete execution.',
      ja: '現実的な実行計画が弱くなることがある。具体的な実行役が必要。',
      'zh-CN': '制定现实执行计划可能偏弱，需要具体执行角色配合。',
      'zh-TW': '制定現實執行計畫可能偏弱，需要具體執行角色配合。',
      vi: 'Lập kế hoạch thực thi thực tế có thể yếu, cần vai trò thực thi cụ thể.',
      id: 'Perencanaan eksekusi realistis bisa lemah, perlu peran eksekusi konkret.',
    }),
    goodEnvironment: localeMap({
      ko: '새로운 도전·창의성이 필요한 프로젝트·팀 동기가 낮은 상황',
      en: 'New challenges · Projects needing creativity · Situations with low team motivation',
      ja: '新しい挑戦・創造性が必要なプロジェクト・チームの動機が低い状況',
      'zh-CN': '新挑战·需要创意的项目·团队动力偏低的状况',
      'zh-TW': '新挑戰·需要創意的專案·團隊動力偏低的狀況',
      vi: 'Thử thách mới · Dự án cần sáng tạo · Khi động lực nhóm thấp',
      id: 'Tantangan baru · Proyek butuh kreativitas · Saat motivasi tim rendah',
    }),
    goodMatch: localeMap({
      ko: '실행력의 카리스마형·구체적 계획의 전략형과 조합 시 최강',
      en: 'Strongest paired with charismatic types for execution and strategic types for concrete plans',
      ja: '実行力のカリスマ型・具体計画の戦略型と組み合わせると最強',
      'zh-CN': '与执行力强的魅力型、具体规划的战略型组合最强',
      'zh-TW': '與執行力強的魅力型、具體規劃的戰略型組合最強',
      vi: 'Mạnh nhất khi kết hợp với kiểu quyết đoán mạnh về thực thi và kiểu chiến lược lập kế hoạch cụ thể',
      id: 'Paling kuat jika dipadukan dengan tipe karismatik eksekutor dan tipe strategis perencana',
    }),
    coverLetterPhrase: localeMap({
      ko: '저는 팀 프로젝트에서 구성원들이 프로젝트의 의미와 목표를 명확히 이해하도록 방향을 제시하고 팀의 내적 동기를 이끌어내는 역할을 해왔습니다',
      en: 'In team projects, I have set direction so members clearly understand the project\'s meaning and goals, drawing out the team\'s intrinsic motivation.',
      ja: 'チームプロジェクトでは、メンバーがプロジェクトの意味と目標を明確に理解できるよう方向を示し、内発的動機を引き出す役割を担ってきました。',
      'zh-CN': '在团队项目中，我提出方向，让成员清楚理解项目意义与目标，激发团队内在动力。',
      'zh-TW': '在團隊專案中，我提出方向，讓成員清楚理解專案意義與目標，激發團隊內在動力。',
      vi: 'Trong dự án nhóm, tôi định hướng để mọi người hiểu rõ ý nghĩa và mục tiêu, khai thác động lực nội tại của nhóm.',
      id: 'Dalam proyek tim, saya memberi arah agar anggota memahami makna dan tujuan proyek, serta menggali motivasi intrinsik tim.',
    }),
    coverLetterMaterial: localeMap({
      ko: '팀 사기가 낮을 때 방향을 재설정해서 분위기를 바꾼 경험·의미 있는 프로젝트로 팀을 이끈 경험',
      en: 'Experience resetting direction when morale was low · Experience leading the team through a meaningful project',
      ja: 'チームの士気が低いときに方向を再設定して雰囲気を変えた経験・意味あるプロジェクトでチームを導いた経験',
      'zh-CN': '团队士气低时重新设定方向扭转氛围的经历·带领团队完成有意义项目的经历',
      'zh-TW': '團隊士氣低時重新設定方向扭轉氛圍的經歷·帶領團隊完成有意義專案的經歷',
      vi: 'Kinh nghiệm định hướng lại khi tinh thần nhóm thấp · Kinh nghiệm dẫn nhóm qua dự án có ý nghĩa',
      id: 'Pengalaman menetapkan ulang arah saat moral tim rendah · Pengalaman memimpin tim dalam proyek bermakna',
    }),
    shareLine: localeMap({
      ko: '내 리더십 스타일: 변혁형 🌟 팀에 비전 심는 유형이래... 방향 제시하는 거 자연스럽게 하는 편 → 너는 어떤 리더십 스타일이야? 자소서 소재로 써봐',
      en: 'My leadership style: Transformational type 🌟 They say I plant vision in the team... Setting direction comes naturally → What\'s your leadership style? Try it for your cover letter.',
      ja: '私のリーダーシップスタイル：変革型 🌟 チームにビジョンを植えるタイプらしい…方向提示が自然 → あなたは？',
      'zh-CN': '我的领导风格：变革型 🌟 说是给团队植入愿景的类型…定方向很自然 → 你是什么领导风格？可以当求职信素材',
      'zh-TW': '我的領導風格：變革型 🌟 說是給團隊植入願景的類型…定方向很自然 → 你是什麼領導風格？可以當求職信素材',
      vi: 'Phong cách lãnh đạo của tôi: Kiểu biến đổi 🌟 Bảo là gieo tầm nhìn cho nhóm… chỉ hướng tự nhiên → Bạn thuộc kiểu nào?',
      id: 'Gaya kepemimpinanku: Tipe transformasional 🌟 Katanya aku tanam visi di tim… arahin tim memang natural → Kamu tipe apa? Bisa buat cover letter',
    }),
  },
  {
    type: "Type5",
    emoji: "⚡",
    title: localeMap({
      ko: '팀을 앞에서 이끄는 사람, 카리스마 리더십형',
      en: 'The One Who Leads from the Front, Charismatic Leadership Type',
      ja: 'チームを前から引く人、カリスマ・リーダーシップ型',
      'zh-CN': '在前方带领团队的人，魅力型领导',
      'zh-TW': '在前方帶領團隊的人，魅力型領導',
      vi: 'Người dẫn dắt nhóm từ phía trước, kiểu lãnh đạo quyến rũ',
      id: 'Pemimpin dari depan, tipe kepemimpinan karismatik',
    }),
    shortDescription: localeMap({
      ko: '당신이 있는 팀은 어렵고 복잡한 상황에서도 멈추지 않습니다.',
      en: 'On a team with you, they don\'t stop—even in tough, complex situations.',
      ja: 'あなたがいるチームは、難しく複雑な状況でも止まらない。',
      'zh-CN': '有你在的团队，即使困难复杂也不会停下。',
      'zh-TW': '有你在的團隊，即使困難複雜也不會停下。',
      vi: 'Nhóm có bạn không dừng lại dù tình huống khó và phức tạp.',
      id: 'Tim yang ada kamu tidak berhenti meski situasinya sulit dan rumit.',
    }),
    description: localeMap({
      ko: '빠른 판단과 강한 추진력으로 팀이 앞으로 나아가게 만드는 리더십입니다. 갈등이 있거나 방향이 흔들릴 때 명확한 결정을 내리고 팀을 이끄는 역할을 자연스럽게 맡습니다. 위기 상황에서 가장 빛나는 리더십입니다.',
      en: 'A leadership style that moves the team forward with quick judgment and strong drive. When conflict arises or direction wavers, you naturally make clear decisions and lead. It shines brightest in crisis.',
      ja: '迅速な判断と強い推進力でチームを前に進めるリーダーシップです。対立や方向の揺れがあるとき、明確な決断を下してチームを導く役割を自然に担います。危機で最も輝きます。',
      'zh-CN': '这是一种以快速判断和强推动力让团队前进的领导力。冲突或方向动摇时，会自然做出明确决策并带领团队，在危机中最闪耀。',
      'zh-TW': '這是一種以快速判斷和強推動力讓團隊前進的領導力。衝突或方向動搖時，會自然做出明確決策並帶領團隊，在危機中最閃耀。',
      vi: 'Kiểu lãnh đạo đẩy nhóm tiến lên bằng phán đoán nhanh và động lực mạnh. Khi xung đột hoặc hướng đi lung lay, bạn tự nhiên quyết đoán và dẫn dắt. Tỏa sáng nhất trong khủng hoảng.',
      id: 'Gaya kepemimpinan yang mendorong tim maju dengan penilaian cepat dan dorongan kuat. Saat konflik atau arah goyah, kamu natural mengambil keputusan jelas dan memimpin. Paling bersinar saat krisis.',
    }),
    leadershipStyle: localeMap({
      ko: '카리스마 리더십 ⚡',
      en: 'Charismatic Leadership ⚡',
      ja: 'カリスマ・リーダーシップ ⚡',
      'zh-CN': '魅力型领导 ⚡',
      'zh-TW': '魅力型領導 ⚡',
      vi: 'Lãnh đạo quyến rũ ⚡',
      id: 'Kepemimpinan karismatik ⚡',
    }),
    leadershipKeywords: localeMap({
      ko: '결단력·추진력·명확성·위기 대응',
      en: 'Decisiveness · Drive · Clarity · Crisis response',
      ja: '決断力・推進力・明確性・危機対応',
      'zh-CN': '决断力·推动力·明确性·危机应对',
      'zh-TW': '決斷力·推動力·明確性·危機應對',
      vi: 'Quyết đoán · Thúc đẩy · Rõ ràng · Ứng phó khủng hoảng',
      id: 'Ketegasan · Dorongan · Kejelasan · Respons krisis',
    }),
    teamRole: localeMap({
      ko: '방향 결정·위기 관리·팀 추진력 유지',
      en: 'Decision-making · Crisis management · Maintaining team momentum',
      ja: '方向決定・危機管理・チームの推進力維持',
      'zh-CN': '方向决策·危机管理·维持团队推进力',
      'zh-TW': '方向決策·危機管理·維持團隊推進力',
      vi: 'Quyết định hướng đi · Quản lý khủng hoảng · Duy trì đà nhóm',
      id: 'Pengambilan keputusan arah · Manajemen krisis · Menjaga momentum tim',
    }),
    strength: localeMap({
      ko: '빠른 실행력·위기 상황 돌파·강한 팀 응집력 형성',
      en: 'Fast execution · Breaking through crises · Strong team cohesion',
      ja: '迅速な実行力・危機突破・強いチーム結束',
      'zh-CN': '快速执行力·突破危机·形成强团队凝聚力',
      'zh-TW': '快速執行力·突破危機·形成強團隊凝聚力',
      vi: 'Thực thi nhanh · Vượt qua khủng hoảng · Gắn kết nhóm mạnh',
      id: 'Eksekusi cepat · Menembus krisis · Kohesi tim kuat',
    }),
    weakness: localeMap({
      ko: '팀원 의견을 충분히 반영하지 못할 수 있음. 심리적 안전감 관리가 필요',
      en: 'May not reflect member opinions enough. Psychological safety needs attention.',
      ja: 'メンバーの意見を十分に反映できないことがある。心理的安全の管理が必要。',
      'zh-CN': '可能未能充分反映队员意见，需要注意心理安全感。',
      'zh-TW': '可能未能充分反映隊員意見，需要注意心理安全感。',
      vi: 'Có thể chưa phản ánh đủ ý kiến thành viên, cần chú ý an toàn tâm lý.',
      id: 'Mungkin belum cukup mengakomodasi pendapat anggota, perlu perhatian pada rasa aman psikologis.',
    }),
    goodEnvironment: localeMap({
      ko: '빠른 결정이 필요한 환경·위기 상황·단기 집중 프로젝트',
      en: 'Environments needing quick decisions · Crises · Short, focused projects',
      ja: '迅速な決断が必要な環境・危機状況・短期集中プロジェクト',
      'zh-CN': '需要快速决策的环境·危机状况·短期集中项目',
      'zh-TW': '需要快速決策的環境·危機狀況·短期集中專案',
      vi: 'Môi trường cần quyết định nhanh · Khủng hoảng · Dự án ngắn hạn tập trung',
      id: 'Lingkungan butuh keputusan cepat · Krisis · Proyek fokus jangka pendek',
    }),
    goodMatch: localeMap({
      ko: '팀원을 챙기는 서번트형·의견을 모으는 민주형과 조합 시 균형',
      en: 'Balanced when paired with servant types who care for members and democratic types who gather opinions',
      ja: 'メンバーをケアするサーバント型・意見を集める民主型と組み合わせるとバランスが取れる',
      'zh-CN': '与照顾队员的服务型、收集意见的民主型组合更平衡',
      'zh-TW': '與照顧隊員的服務型、收集意見的民主型組合更平衡',
      vi: 'Cân bằng hơn khi kết hợp với kiểu phục vụ và kiểu dân chủ',
      id: 'Lebih seimbang jika dipadukan dengan tipe pelayan dan tipe demokratis',
    }),
    coverLetterPhrase: localeMap({
      ko: '저는 팀 프로젝트에서 명확한 방향 결정과 강한 추진력으로 팀이 어려운 상황에서도 목표를 향해 나아갈 수 있도록 이끌었습니다',
      en: 'In team projects, I have led with clear direction and strong drive so the team could keep moving toward goals even in difficult situations.',
      ja: 'チームプロジェクトでは、明確な方向決定と強い推進力で、困難な状況でも目標に向かって進めるようチームを導きました。',
      'zh-CN': '在团队项目中，我以明确方向决策和强推动力，带领团队在困难中仍朝目标前进。',
      'zh-TW': '在團隊專案中，我以明確方向決策和強推動力，帶領團隊在困難中仍朝目標前進。',
      vi: 'Trong dự án nhóm, tôi dẫn dắt bằng quyết định rõ ràng và động lực mạnh để nhóm vẫn tiến tới mục tiêu dù khó khăn.',
      id: 'Dalam proyek tim, saya memimpin dengan arah jelas dan dorongan kuat agar tim tetap menuju target meski situasinya sulit.',
    }),
    coverLetterMaterial: localeMap({
      ko: '마감 위기 상황에서 팀을 이끌어 결과물을 낸 경험·갈등 상황에서 빠른 결정으로 돌파한 경험',
      en: 'Experience delivering results by leading the team through deadline crises · Experience breaking through conflict with quick decisions',
      ja: '締切危機でチームを導いて成果を出した経験・対立状況で迅速な決断で突破した経験',
      'zh-CN': '在截止危机中带领团队产出成果的经历·在冲突中以快速决策突破的经历',
      'zh-TW': '在截止危機中帶領團隊產出成果的經歷·在衝突中以快速決策突破的經歷',
      vi: 'Kinh nghiệm dẫn nhóm hoàn thành sản phẩm trong khủng hoảng deadline · Kinh nghiệm vượt xung đột bằng quyết định nhanh',
      id: 'Pengalaman memimpin tim menyelesaikan deliverable saat krisis deadline · Pengalaman menembus konflik dengan keputusan cepat',
    }),
    shareLine: localeMap({
      ko: '내 리더십 스타일: 카리스마형 ⚡ 위기 상황에서 빛나는 유형이래... 마감 때 팀 이끄는 거 내 스타일 맞음 ㅋㅋ → 너는 어떤 유형이야?',
      en: 'My leadership style: Charismatic type ⚡ They say I shine in crisis... Leading the team at deadlines is my style → What\'s your type?',
      ja: '私のリーダーシップスタイル：カリスマ型 ⚡ 危機で輝くタイプらしい…締切前にチームを引くのは自分のスタイル → あなたは？',
      'zh-CN': '我的领导风格：魅力型 ⚡ 说是危机中闪耀的类型…截止前带团队就是我的风格 ㅋㅋ → 你是什么类型？',
      'zh-TW': '我的領導風格：魅力型 ⚡ 說是危機中閃耀的類型…截止前帶團隊就是我的風格 ㅋㅋ → 你是什麼類型？',
      vi: 'Phong cách lãnh đạo của tôi: Kiểu quyến rũ ⚡ Bảo là tỏa sáng lúc khủng hoảng… dẫn team lúc deadline đúng gu tôi → Bạn thuộc kiểu nào?',
      id: 'Gaya kepemimpinanku: Tipe karismatik ⚡ Katanya aku shine pas krisis… memimpin tim saat deadline memang gaya ku → Kamu tipe apa?',
    }),
  },
  {
    type: "Type6",
    emoji: "🎯",
    title: localeMap({
      ko: '성과를 설계하는 사람, 전략적 리더십형',
      en: 'The One Who Designs Results, Strategic Leadership Type',
      ja: '成果を設計する人、戦略的リーダーシップ型',
      'zh-CN': '设计成果的人，战略型领导',
      'zh-TW': '設計成果的人，戰略型領導',
      vi: 'Người thiết kế kết quả, kiểu lãnh đạo chiến lược',
      id: 'Perancang hasil, tipe kepemimpinan strategis',
    }),
    shortDescription: localeMap({
      ko: '당신이 있는 팀은 왜 잘 됐는지 설명할 수 있습니다.',
      en: 'On a team with you, they can explain why things went well.',
      ja: 'あなたがいるチームは、なぜうまくいったか説明できる。',
      'zh-CN': '有你在的团队，能解释为什么做得好。',
      'zh-TW': '有你在的團隊，能解釋為什麼做得好。',
      vi: 'Nhóm có bạn giải thích được vì sao làm tốt.',
      id: 'Tim yang ada kamu bisa menjelaskan mengapa hasilnya baik.',
    }),
    description: localeMap({
      ko: '팀의 상황을 체계적으로 분석하고 최적의 전략을 설계하며 팀이 효율적으로 움직이도록 구조를 만드는 리더십입니다. 감정보다 데이터를 중심으로 판단하고 성과에 집중합니다.',
      en: 'A leadership style that systematically analyzes the team\'s situation, designs optimal strategy, and builds structure for efficient movement. Judgment centers on data over emotion, with a focus on performance.',
      ja: 'チームの状況を体系的に分析し、最適な戦略を設計して効率的に動ける構造を作るリーダーシップです。感情よりデータを中心に判断し、成果に集中します。',
      'zh-CN': '这是一种系统分析团队状况、设计最优策略、搭建高效运作结构的领导力。以数据而非情绪为中心判断，聚焦成果。',
      'zh-TW': '這是一種系統分析團隊狀況、設計最優策略、搭建高效運作結構的領導力。以數據而非情緒為中心判斷，聚焦成果。',
      vi: 'Kiểu lãnh đạo phân tích có hệ thống, thiết kế chiến lược tối ưu và tạo cấu trúc vận hành hiệu quả. Phán đoán dựa trên dữ liệu hơn cảm xúc, tập trung vào kết quả.',
      id: 'Gaya kepemimpinan yang menganalisis situasi tim secara sistematis, merancang strategi optimal, dan membangun struktur agar tim bergerak efisien. Penilaian berpusat pada data, fokus pada kinerja.',
    }),
    leadershipStyle: localeMap({
      ko: '전략적 리더십 🎯',
      en: 'Strategic Leadership 🎯',
      ja: '戦略的リーダーシップ 🎯',
      'zh-CN': '战略型领导 🎯',
      'zh-TW': '戰略型領導 🎯',
      vi: 'Lãnh đạo chiến lược 🎯',
      id: 'Kepemimpinan strategis 🎯',
    }),
    leadershipKeywords: localeMap({
      ko: '분석·구조화·목표 중심·효율성',
      en: 'Analysis · Structuring · Goal focus · Efficiency',
      ja: '分析・構造化・目標中心・効率性',
      'zh-CN': '分析·结构化·目标导向·效率',
      'zh-TW': '分析·結構化·目標導向·效率',
      vi: 'Phân tích · Cấu trúc hóa · Tập trung mục tiêu · Hiệu quả',
      id: 'Analisis · Struktur · Fokus tujuan · Efisiensi',
    }),
    teamRole: localeMap({
      ko: '전략 수립·우선순위 결정·성과 관리',
      en: 'Strategy planning · Priority setting · Performance management',
      ja: '戦略立案・優先順位決定・成果管理',
      'zh-CN': '战略制定·优先级决策·绩效管理',
      'zh-TW': '戰略制定·優先順序決策·績效管理',
      vi: 'Lập chiến lược · Quyết định ưu tiên · Quản lý hiệu suất',
      id: 'Perencanaan strategi · Penetapan prioritas · Manajemen kinerja',
    }),
    strength: localeMap({
      ko: '체계적인 실행 계획·높은 목표 달성률·논리적 의사결정',
      en: 'Systematic execution plans · High goal achievement · Logical decision-making',
      ja: '体系的な実行計画・高い目標達成率・論理的な意思決定',
      'zh-CN': '系统化执行计划·高目标达成率·逻辑化决策',
      'zh-TW': '系統化執行計畫·高目標達成率·邏輯化決策',
      vi: 'Kế hoạch thực thi có hệ thống · Tỷ lệ đạt mục tiêu cao · Quyết định logic',
      id: 'Rencana eksekusi sistematis · Pencapaian target tinggi · Keputusan logis',
    }),
    weakness: localeMap({
      ko: '팀원의 감정적 측면이 소홀해질 수 있음. 관계 관리 역할이 함께 필요',
      en: 'The emotional side of members may be neglected. Relationship management partners are needed.',
      ja: 'メンバーの感情的側面がおろそかになりやすい。関係管理の役割が必要。',
      'zh-CN': '可能忽略队员情感层面，需要关系管理角色配合。',
      'zh-TW': '可能忽略隊員情感層面，需要關係管理角色配合。',
      vi: 'Có thể bỏ qua khía cạnh cảm xúc của thành viên, cần vai trò quản lý quan hệ.',
      id: 'Aspek emosional anggota bisa terabaikan, perlu peran manajemen relasi.',
    }),
    goodEnvironment: localeMap({
      ko: '복잡한 프로젝트·성과 측정이 명확한 환경·다수의 변수가 있는 상황',
      en: 'Complex projects · Environments with clear performance metrics · Many variables',
      ja: '複雑なプロジェクト・成果測定が明確な環境・多数の変数がある状況',
      'zh-CN': '复杂项目·绩效衡量清晰的环境·变量多的情况',
      'zh-TW': '複雜專案·績效衡量清晰的環境·變數多的情況',
      vi: 'Dự án phức tạp · Môi trường đo lường hiệu suất rõ · Nhiều biến số',
      id: 'Proyek kompleks · Lingkungan dengan metrik kinerja jelas · Banyak variabel',
    }),
    goodMatch: localeMap({
      ko: '팀원을 챙기는 서번트형·비전을 제시하는 변혁형과 조합 시 완성형',
      en: 'A complete team when paired with servant types who care for members and transformational types who provide vision',
      ja: 'メンバーをケアするサーバント型・ビジョンを示す変革型と組み合わせると完成形',
      'zh-CN': '与照顾队员的服务型、提供愿景的变革型组合成完整团队',
      'zh-TW': '與照顧隊員的服務型、提供願景的變革型組合成完整團隊',
      vi: 'Hoàn thiện khi kết hợp với kiểu phục vụ và kiểu biến đổi đưa tầm nhìn',
      id: 'Jadi tim lengkap jika dipadukan dengan tipe pelayan dan tipe transformasional pengarah visi',
    }),
    coverLetterPhrase: localeMap({
      ko: '저는 팀 프로젝트에서 현황을 데이터로 분석하고 우선순위를 명확히 설정해 팀이 효율적으로 목표를 달성할 수 있는 전략을 수립했습니다',
      en: 'In team projects, I analyzed the situation with data, set clear priorities, and built strategy for efficient goal achievement.',
      ja: 'チームプロジェクトでは、現状をデータで分析し、優先順位を明確に設定して、チームが効率的に目標を達成できる戦略を立てました。',
      'zh-CN': '在团队项目中，我用数据分析现状、明确优先级，制定让团队高效达成目标的战略。',
      'zh-TW': '在團隊專案中，我用數據分析現況、明確優先順序，制定讓團隊高效達成目標的戰略。',
      vi: 'Trong dự án nhóm, tôi phân tích hiện trạng bằng dữ liệu, đặt ưu tiên rõ ràng và xây chiến lược giúp nhóm đạt mục tiêu hiệu quả.',
      id: 'Dalam proyek tim, saya menganalisis kondisi dengan data, menetapkan prioritas jelas, dan menyusun strategi agar tim mencapai target secara efisien.',
    }),
    coverLetterMaterial: localeMap({
      ko: '복잡한 프로젝트를 체계적으로 정리해서 성과를 낸 경험·우선순위 재조정으로 팀 효율을 높인 경험',
      en: 'Experience delivering results by organizing complex projects systematically · Experience boosting team efficiency by reprioritizing',
      ja: '複雑なプロジェクトを体系的に整理して成果を出した経験・優先順位の再調整でチーム効率を高めた経験',
      'zh-CN': '系统化整理复杂项目并产出成果的经历·通过重调优先级提升团队效率的经历',
      'zh-TW': '系統化整理複雜專案並產出成果的經歷·透過重調優先順序提升團隊效率的經歷',
      vi: 'Kinh nghiệm tổ chức dự án phức tạp có hệ thống và đạt kết quả · Kinh nghiệm nâng hiệu quả nhóm bằng điều chỉnh ưu tiên',
      id: 'Pengalaman menyelesaikan proyek kompleks secara sistematis · Pengalaman meningkatkan efisiensi tim lewat reprioritisasi',
    }),
    shareLine: localeMap({
      ko: '내 리더십 스타일: 전략형 🎯 데이터로 성과 설계하는 유형이래... 왜 잘 됐는지 설명 가능한 팀 만든다는 거 → 자소서 리더십 소재 고민이면 이거 해봐',
      en: 'My leadership style: Strategic type 🎯 They say I design results with data... I build teams that can explain why they succeeded → Try this for cover letter leadership material.',
      ja: '私のリーダーシップスタイル：戦略型 🎯 データで成果を設計するタイプらしい…なぜうまくいったか説明できるチーム → 自己PR素材にどうぞ',
      'zh-CN': '我的领导风格：战略型 🎯 说是用数据设计成果的类型…能解释为什么成功的团队 → 求职信领导力素材发愁就试试',
      'zh-TW': '我的領導風格：戰略型 🎯 說是用數據設計成果的類型…能解釋為什麼成功的團隊 → 求職信領導力素材發愁就試試',
      vi: 'Phong cách lãnh đạo của tôi: Kiểu chiến lược 🎯 Bảo là thiết kế kết quả bằng dữ liệu… tạo team giải thích được vì sao thành công → Thử nếu thiếu ý tưởng CV',
      id: 'Gaya kepemimpinanku: Tipe strategis 🎯 Katanya aku rancang hasil pakai data… bikin tim yang bisa jelasin kenapa sukses → Coba deh kalau lagi cari bahan leadership',
    }),
  },
];
