/** 어른들 멘붕! 초등 수학 퀴즈 — phase3-elementary-math-adults-quiz */
function T(o: {
  ko: string;
  en: string;
  ja: string;
  'zh-CN': string;
  'zh-TW': string;
  vi: string;
  id: string;
}): Record<string, string> {
  return o;
}

export interface Phase3ElementaryMathAdultsQuizOption {
  text: Record<string, string>;
  isCorrect: boolean;
}

export interface Phase3ElementaryMathAdultsQuizQuestion {
  id: number;
  question: Record<string, string>;
  options: Phase3ElementaryMathAdultsQuizOption[];
  correctExplanation: Record<string, string>;
  wrongTraps: Record<string, string>;
}

export interface Phase3ElementaryMathAdultsQuizResult {
  type: string;
  emoji: string;
  title: Record<string, string>;
  shortDescription: Record<string, string>;
  description: Record<string, string>;
  levelLabel: Record<string, string>;
  honorTitle: Record<string, string>;
  oneLiner: Record<string, string>;
  todoToday: Record<string, string>;
  /** SNS 한 줄 — {count} = 맞힌 개수 */
  shareLine: Record<string, string>;
}

export const phase3ElementaryMathAdultsQuizQuestions: Phase3ElementaryMathAdultsQuizQuestion[] = [
  {
    id: 1,
    question: T({
      ko: '다음 계산의 정답은?\n1 + 1 + 1 + 1 + 1 × 0',
      en: 'What is the result?\n1 + 1 + 1 + 1 + 1 × 0',
      ja: '次の計算の答えは？\n1 + 1 + 1 + 1 + 1 × 0',
      'zh-CN': '下面算式的结果是？\n1 + 1 + 1 + 1 + 1 × 0',
      'zh-TW': '下面算式的答案是？\n1 + 1 + 1 + 1 + 1 × 0',
      vi: 'Kết quả của phép tính sau là?\n1 + 1 + 1 + 1 + 1 × 0',
      id: 'Berapa hasil perhitungan berikut?\n1 + 1 + 1 + 1 + 1 × 0',
    }),
    options: [
      { text: T({ ko: '0', en: '0', ja: '0', 'zh-CN': '0', 'zh-TW': '0', vi: '0', id: '0' }), isCorrect: false },
      { text: T({ ko: '4', en: '4', ja: '4', 'zh-CN': '4', 'zh-TW': '4', vi: '4', id: '4' }), isCorrect: true },
      { text: T({ ko: '5', en: '5', ja: '5', 'zh-CN': '5', 'zh-TW': '5', vi: '5', id: '5' }), isCorrect: false },
      { text: T({ ko: '3', en: '3', ja: '3', 'zh-CN': '3', 'zh-TW': '3', vi: '3', id: '3' }), isCorrect: false },
    ],
    correctExplanation: T({
      ko: '곱셈은 덧셈보다 먼저 계산합니다(연산 순서). 1×0=0을 먼저 계산한 후 1+1+1+1+0=4. 많은 어른들이 왼쪽에서 오른쪽으로 차례로 계산해서 0이라고 답합니다. 초등 3학년 연산 순서 개념입니다.',
      en: 'Multiplication comes before addition (order of operations). First 1×0=0, then 1+1+1+1+0=4. Many adults compute left-to-right and answer 0. This is grade-3 order of operations.',
      ja: '掛け算は足し算より先です（演算の順序）。まず1×0=0、次に1+1+1+1+0=4。左から順に計算して0と答える大人が多いです。小学3年生の考え方です。',
      'zh-CN': '先算乘法再算加法（运算顺序）。先算1×0=0，再算1+1+1+1+0=4。很多人从左往右算会答0。这是小学三年级的运算顺序。',
      'zh-TW': '先算乘法再算加法（運算順序）。先算1×0=0，再算1+1+1+1+0=4。很多人從左往右算會答0。這是小學三年級的運算順序。',
      vi: 'Nhân trước cộng sau (thứ tự phép tính). Trước 1×0=0, rồi 1+1+1+1+0=4. Nhiều người lớn tính trái sang phải nên chọn 0. Đây là khái niệm lớp 3.',
      id: 'Perkalian sebelum penjumlahan (urutan operasi). Dulu 1×0=0, lalu 1+1+1+1+0=4. Banyak orang dewasa menghitung kiri ke kanan dan menjawab 0. Ini konsep kelas 3 SD.',
    }),
    wrongTraps: T({
      ko: '• 0이라고 답한 분: 전부 더한 다음 ×0을 했군요. 곱셈 먼저입니다.\n• 5라고 답한 분: ×0을 무시했군요.',
      en: '• If you chose 0: you added everything first, then ×0. Multiply first.\n• If you chose 5: you ignored the ×0.',
      ja: '• 0の人：全部足してから×0にした？掛け算が先です。\n• 5の人：×0を無視した？',
      'zh-CN': '• 选0：先全加再×0。应先算乘法。\n• 选5：忽略了×0。',
      'zh-TW': '• 選0：先全加再×0。應先算乘法。\n• 選5：忽略了×0。',
      vi: '• Chọn 0: cộng hết rồi mới ×0. Phải nhân trước.\n• Chọn 5: bỏ qua ×0.',
      id: '• Pilih 0: menjumlahkan dulu lalu ×0. Kalikan dulu.\n• Pilih 5: mengabaikan ×0.',
    }),
  },
  {
    id: 2,
    question: T({
      ko: '다음 중 소수(素數)가 아닌 것은?',
      en: 'Which of these is NOT a prime number?',
      ja: '次のうち素数でないのはどれ？',
      'zh-CN': '下列哪个不是质数？',
      'zh-TW': '下列哪一個不是質數？',
      vi: 'Số nào sau đây KHÔNG phải số nguyên tố?',
      id: 'Manakah di bawah ini BUKAN bilangan prima?',
    }),
    options: [
      { text: T({ ko: '2', en: '2', ja: '2', 'zh-CN': '2', 'zh-TW': '2', vi: '2', id: '2' }), isCorrect: false },
      { text: T({ ko: '3', en: '3', ja: '3', 'zh-CN': '3', 'zh-TW': '3', vi: '3', id: '3' }), isCorrect: false },
      { text: T({ ko: '7', en: '7', ja: '7', 'zh-CN': '7', 'zh-TW': '7', vi: '7', id: '7' }), isCorrect: false },
      { text: T({ ko: '9', en: '9', ja: '9', 'zh-CN': '9', 'zh-TW': '9', vi: '9', id: '9' }), isCorrect: true },
    ],
    correctExplanation: T({
      ko: '소수란 1과 자기 자신으로만 나누어지는 수입니다. 9=3×3으로 약수가 1, 3, 9 세 개이므로 소수가 아닙니다. 2, 3, 7은 모두 소수입니다. 참고로 1은 소수가 아닙니다(이것도 많이 헷갈리는 함정입니다).',
      en: 'A prime has exactly two distinct positive divisors: 1 and itself. 9=3×3 has divisors 1, 3, 9—so it is not prime. 2, 3, and 7 are prime. Note: 1 is not prime (common trap).',
      ja: '素数は1と自分自身だけで割り切れる数です。9=3×3で約数は1,3,9の三つなので素数ではありません。2,3,7は素数。1は素数ではありません（よくある落とし穴）。',
      'zh-CN': '质数只有1和本身两个正因数。9=3×3，因数有1、3、9三个，不是质数。2、3、7是质数。注意：1不是质数（常见陷阱）。',
      'zh-TW': '質數只有1和本身兩個正因數。9=3×3，因數有1、3、9三個，不是質數。2、3、7是質數。注意：1不是質數（常見陷阱）。',
      vi: 'Số nguyên tố chỉ chia hết cho 1 và chính nó. 9=3×3 có ước 1,3,9 nên không phải số nguyên tố. 2,3,7 là số nguyên tố. Lưu ý: 1 không phải số nguyên tố (bẫy thường gặp).',
      id: 'Bilangan prima hanya habis dibagi 1 dan dirinya. 9=3×3 punya pembagi 1,3,9 jadi bukan prima. 2,3,7 prima. Catatan: 1 bukan prima (jebakan umum).',
    }),
    wrongTraps: T({
      ko: '• 2라고 답한 분: 2는 짝수이지만 유일하게 소수인 짝수입니다.\n• 1이 소수라고 생각했다면: 1은 약수가 1개뿐이라 소수가 아닙니다.',
      en: '• If you picked 2: 2 is the only even prime.\n• If you thought 1 was prime: 1 has only one divisor, so it is not prime.',
      ja: '• 2を選んだ人：2は唯一の偶数の素数です。\n• 1が素数？：1の約数は1つだけなので素数ではありません。',
      'zh-CN': '• 选2：2是唯一的偶质数。\n• 以为1是质数：1只有一个因数，不是质数。',
      'zh-TW': '• 選2：2是唯一的偶質數。\n• 以為1是質數：1只有一個因數，不是質數。',
      vi: '• Chọn 2: 2 là số nguyên tố chẵn duy nhất.\n• Tưởng 1 là số nguyên tố: 1 chỉ có một ước.',
      id: '• Pilih 2: 2 adalah bilangan prima genap tunggal.\n• Kira 1 prima: 1 hanya punya satu pembagi.',
    }),
  },
  {
    id: 3,
    question: T({
      ko: '다음 계산의 정답은?\n48 ÷ 2(9 + 3) = ?',
      en: 'What is the result?\n48 ÷ 2(9 + 3) = ?',
      ja: '次の計算の答えは？\n48 ÷ 2(9 + 3) = ?',
      'zh-CN': '下面算式的结果是？\n48 ÷ 2(9 + 3) = ?',
      'zh-TW': '下面算式的答案是？\n48 ÷ 2(9 + 3) = ?',
      vi: 'Kết quả là?\n48 ÷ 2(9 + 3) = ?',
      id: 'Berapa hasilnya?\n48 ÷ 2(9 + 3) = ?',
    }),
    options: [
      { text: T({ ko: '2', en: '2', ja: '2', 'zh-CN': '2', 'zh-TW': '2', vi: '2', id: '2' }), isCorrect: false },
      { text: T({ ko: '288', en: '288', ja: '288', 'zh-CN': '288', 'zh-TW': '288', vi: '288', id: '288' }), isCorrect: true },
      { text: T({ ko: '4', en: '4', ja: '4', 'zh-CN': '4', 'zh-TW': '4', vi: '4', id: '4' }), isCorrect: false },
      { text: T({ ko: '96', en: '96', ja: '96', 'zh-CN': '96', 'zh-TW': '96', vi: '96', id: '96' }), isCorrect: false },
    ],
    correctExplanation: T({
      ko: '연산 순서: 괄호 먼저 → 9+3=12. 그다음 나눗셈과 곱셈은 왼쪽에서 오른쪽 순서. 48÷2=24, 24×12=288. 이 문제는 전 세계적으로 논란이 된 적 있는 유명한 함정 문제입니다. 2(9+3)를 하나의 묶음으로 보느냐 아니냐가 핵심인데 현대 수학 표기법에서는 48÷2×(9+3)로 해석해서 288이 됩니다.',
      en: 'Order: parentheses first → 9+3=12. Then division and multiplication left to right: 48÷2=24, 24×12=288. This famous “viral” problem is debated worldwide; standard school notation treats it as 48÷2×(9+3)=288.',
      ja: '順序：かっこ内が先→9+3=12。次に割り算と掛け算は左から。48÷2=24、24×12=288。世界中で論争になった有名な問題で、標準的には48÷2×(9+3)=288と解釈されます。',
      'zh-CN': '顺序：先算括号→9+3=12。再从左到右算乘除：48÷2=24，24×12=288。这是全球热议的“网红题”，按常见书写习惯为48÷2×(9+3)=288。',
      'zh-TW': '順序：先算括號→9+3=12。再從左到右算乘除：48÷2=24，24×12=288。這是全球熱議的題目，常見寫法為48÷2×(9+3)=288。',
      vi: 'Thứ tự: ngoặc trước → 9+3=12. Rồi chia và nhân trái sang phải: 48÷2=24, 24×12=288. Bài nổi tiếng tranh cãi toàn cầu; cách phổ biến là 48÷2×(9+3)=288.',
      id: 'Urutan: kurung dulu → 9+3=12. Lalu bagi dan kali kiri ke kanan: 48÷2=24, 24×12=288. Soal viral yang sering diperdebatkan; penafsiran umum 48÷2×(9+3)=288.',
    }),
    wrongTraps: T({
      ko: '• 2라고 답한 분: 48÷(2×12)=2로 계산했군요. 48÷24=2. 이 해석도 논란이 있지만 표준 풀이는 288입니다.\n• 이 문제에서 틀려도 너무 억울해하지 마세요. 전 세계 수학자들도 논쟁했던 문제입니다.',
      en: '• If you got 2: you may have computed 48÷(2×12)=2. That grouping is debated; the common textbook path here is 288.\n• Don’t feel alone—mathematicians have argued over this one too.',
      ja: '• 2の人：48÷(2×12)のようにくくったかも。議論はありますが、ここでは288が一般的です。\n• 落ち込みすぎないで。世界中で議論された問題です。',
      'zh-CN': '• 得2：可能按48÷(2×12)分组。这种理解有争议，常见课标解法是288。\n• 别太在意，这道题全球都吵过。',
      'zh-TW': '• 得2：可能按48÷(2×12)分組。此解讀有爭議，常見教法為288。\n• 別太在意，全球都討論過這題。',
      vi: '• Ra 2: có thể tính 48÷(2×12). Cách nhóm này tranh cãi; lời giải phổ biến ở đây là 288.\n• Đừng buồn—cả thế giới cũng tranh luận bài này.',
      id: '• Dapat 2: mungkin 48÷(2×12). Tafsiran itu diperdebatkan; jawaban umum di sini 288.\n• Jangan minder—soal ini juga diperdebatkan matematikawan.',
    }),
  },
  {
    id: 4,
    question: T({
      ko: '다음 분수를 계산한 결과는?\n1/2 + 1/3 = ?',
      en: 'Add the fractions:\n1/2 + 1/3 = ?',
      ja: '次の分数の和は？\n1/2 + 1/3 = ?',
      'zh-CN': '计算下面分数的和：\n1/2 + 1/3 = ?',
      'zh-TW': '計算下面分數的和：\n1/2 + 1/3 = ?',
      vi: 'Tính tổng:\n1/2 + 1/3 = ?',
      id: 'Jumlahkan pecahan:\n1/2 + 1/3 = ?',
    }),
    options: [
      { text: T({ ko: '2/5', en: '2/5', ja: '2/5', 'zh-CN': '2/5', 'zh-TW': '2/5', vi: '2/5', id: '2/5' }), isCorrect: false },
      { text: T({ ko: '1/6', en: '1/6', ja: '1/6', 'zh-CN': '1/6', 'zh-TW': '1/6', vi: '1/6', id: '1/6' }), isCorrect: false },
      { text: T({ ko: '5/6', en: '5/6', ja: '5/6', 'zh-CN': '5/6', 'zh-TW': '5/6', vi: '5/6', id: '5/6' }), isCorrect: true },
      { text: T({ ko: '2/6', en: '2/6', ja: '2/6', 'zh-CN': '2/6', 'zh-TW': '2/6', vi: '2/6', id: '2/6' }), isCorrect: false },
    ],
    correctExplanation: T({
      ko: '분수의 덧셈은 통분이 먼저입니다. 공통분모 6으로 통분하면 3/6 + 2/6 = 5/6. 초등 5학년 분수 덧셈 핵심 개념입니다.',
      en: 'Find a common denominator first. With denominator 6: 3/6 + 2/6 = 5/6. Core grade-5 fraction addition.',
      ja: '分数の足し算は通分が先。分母6なら3/6 + 2/6 = 5/6。小学5年生の基本です。',
      'zh-CN': '分数加法要先通分。公分母6：3/6 + 2/6 = 5/6。这是小学五年级核心概念。',
      'zh-TW': '分數加法要先通分。公分母6：3/6 + 2/6 = 5/6。這是小學五年級核心概念。',
      vi: 'Cộng phân số phải quy đồng trước. Mẫu 6: 3/6 + 2/6 = 5/6. Kiến thức lớp 5.',
      id: 'Jumlah pecahan: samakan penyebut dulu. Penyebut 6: 3/6 + 2/6 = 5/6. Konsep kelas 5.',
    }),
    wrongTraps: T({
      ko: '• 2/5라고 답한 분: 분자끼리 더하고 분모끼리 더했군요(1+1=2, 2+3=5). 이건 틀린 방법입니다.\n• 2/6라고 답한 분: 통분 후 분자를 제대로 계산하지 않았습니다.',
      en: '• 2/5: adding numerators and denominators (1+1)/(2+3)—wrong rule.\n• 2/6: after finding a common denominator, the numerators weren’t added correctly.',
      ja: '• 2/5：分子同士・分母同士を足した（誤り）。\n• 2/6：通分後の分子の計算が足りない。',
      'zh-CN': '• 选2/5：分子加分子、分母加分母（错误）。\n• 选2/6：通分后分子没加对。',
      'zh-TW': '• 選2/5：分子加分子、分母加分母（錯誤）。\n• 選2/6：通分後分子沒加對。',
      vi: '• 2/5: cộng tử với tử, mẫu với mẫu—sai.\n• 2/6: sau quy đồng, chưa cộng đúng tử số.',
      id: '• 2/5: menjumlahkan pembilang+pembilang, penyebut+penyebut—salah.\n• 2/6: setelah samakan penyebut, pembilang belum dijumlah benar.',
    }),
  },
  {
    id: 5,
    question: T({
      ko: '다음 문장에서 올바른 단위 변환은?\n2.5km = ? m',
      en: 'Which conversion is correct?\n2.5 km = ? m',
      ja: '正しい単位換算は？\n2.5km = ? m',
      'zh-CN': '哪一项单位换算正确？\n2.5km = ? m',
      'zh-TW': '哪一項單位換算正確？\n2.5km = ? m',
      vi: 'Phép đổi đơn vị nào đúng?\n2,5 km = ? m',
      id: 'Konversi satuan mana yang benar?\n2,5 km = ? m',
    }),
    options: [
      { text: T({ ko: '250m', en: '250 m', ja: '250m', 'zh-CN': '250m', 'zh-TW': '250m', vi: '250 m', id: '250 m' }), isCorrect: false },
      { text: T({ ko: '25m', en: '25 m', ja: '25m', 'zh-CN': '25m', 'zh-TW': '25m', vi: '25 m', id: '25 m' }), isCorrect: false },
      { text: T({ ko: '2500m', en: '2500 m', ja: '2500m', 'zh-CN': '2500m', 'zh-TW': '2500m', vi: '2500 m', id: '2500 m' }), isCorrect: true },
      { text: T({ ko: '0.025m', en: '0.025 m', ja: '0.025m', 'zh-CN': '0.025m', 'zh-TW': '0.025m', vi: '0,025 m', id: '0,025 m' }), isCorrect: false },
    ],
    correctExplanation: T({
      ko: '1km = 1000m이므로 2.5km = 2.5 × 1000 = 2500m. 초등 4학년 단위 환산 개념입니다. 소수점 위치를 헷갈려서 250m라고 답하는 어른들이 매우 많습니다.',
      en: '1 km = 1000 m, so 2.5 km = 2.5 × 1000 = 2500 m. Grade-4 unit conversion. Many adults misplace the decimal and answer 250 m.',
      ja: '1km=1000mなので2.5km=2500m。小学4年生の単位換算。小数点をずらして250mと答える大人が多いです。',
      'zh-CN': '1km=1000m，故2.5km=2500m。小学四年级单位换算。很多人小数点错位答250m。',
      'zh-TW': '1km=1000m，故2.5km=2500m。小學四年級單位換算。很多人小數點錯位答250m。',
      vi: '1 km = 1000 m nên 2,5 km = 2500 m. Lớp 4. Nhiều người lớn nhầm dấu phẩy chọn 250 m.',
      id: '1 km = 1000 m, jadi 2,5 km = 2500 m. Kelas 4. Banyak orang salah titik desimal dan jawab 250 m.',
    }),
    wrongTraps: T({
      ko: '• 250m라고 답한 분: 1km=100m로 착각했거나 소수점을 한 자리만 이동했습니다.\n• 0.025m라고 답한 분: km가 m보다 크다는 걸 반대로 이해했습니다.',
      en: '• 250 m: you may think 1 km = 100 m or move the decimal only one place.\n• 0.025 m: km and m size reversed.',
      ja: '• 250m：1km=100mと思ったか、小数点が1桁だけ。\n• 0.025m：kmとmの大小が逆。',
      'zh-CN': '• 250m：误以为1km=100m或小数点只移一位。\n• 0.025m：千米与米的大小关系搞反。',
      'zh-TW': '• 250m：誤以為1km=100m或小數點只移一位。\n• 0.025m：公里與公尺大小搞反。',
      vi: '• 250 m: tưởng 1 km = 100 m hoặc chỉ dời dấu một chữ số.\n• 0,025 m: nhầm km lớn hơn m theo chiều ngược.',
      id: '• 250 m: mengira 1 km = 100 m atau hanya geser desimal satu digit.\n• 0,025 m: membalik mana yang lebih besar—km vs m.',
    }),
  },
  {
    id: 6,
    question: T({
      ko: '12와 18의 최소공배수는?',
      en: 'What is the least common multiple (LCM) of 12 and 18?',
      ja: '12と18の最小公倍数は？',
      'zh-CN': '12和18的最小公倍数是？',
      'zh-TW': '12和18的最小公倍數是？',
      vi: 'Bội chung nhỏ nhất (BCNN) của 12 và 18 là?',
      id: 'Kelipatan persekutuan terkecil (KPK) dari 12 dan 18?',
    }),
    options: [
      { text: T({ ko: '6', en: '6', ja: '6', 'zh-CN': '6', 'zh-TW': '6', vi: '6', id: '6' }), isCorrect: false },
      { text: T({ ko: '216', en: '216', ja: '216', 'zh-CN': '216', 'zh-TW': '216', vi: '216', id: '216' }), isCorrect: false },
      { text: T({ ko: '36', en: '36', ja: '36', 'zh-CN': '36', 'zh-TW': '36', vi: '36', id: '36' }), isCorrect: true },
      { text: T({ ko: '72', en: '72', ja: '72', 'zh-CN': '72', 'zh-TW': '72', vi: '72', id: '72' }), isCorrect: false },
    ],
    correctExplanation: T({
      ko: '12=2²×3, 18=2×3². 최소공배수는 각 인수의 최대 지수를 곱합니다. 2²×3²=4×9=36. 검증: 36÷12=3, 36÷18=2. 참고로 6은 최대공약수입니다. 최소공배수와 최대공약수를 혼동하는 어른들이 많습니다.',
      en: '12=2²×3, 18=2×3². LCM uses the highest power of each prime: 2²×3²=36. Check: 36÷12=3, 36÷18=2. Note: 6 is the GCD—many confuse LCM and GCD.',
      ja: '12=2²×3、18=2×3²。最小公倍数は各素因数の最大の指数を掛ける。2²×3²=36。6は最大公約数。LCMとGCDを混同しやすい。',
      'zh-CN': '12=2²×3，18=2×3²。最小公倍数取各质因数最高次幂：2²×3²=36。6是最大公约数。很多人混淆最小公倍数与最大公约数。',
      'zh-TW': '12=2²×3，18=2×3²。最小公倍數取各質因數最高次方：2²×3²=36。6是最大公因數。很多人混淆LCM與GCD。',
      vi: '12=2²×3, 18=2×3². BCNN lấy lũy thừa lớn nhất: 2²×3²=36. 6 là ƯCLN—hay nhầm BCNN với ƯCLN.',
      id: '12=2²×3, 18=2×3². KPK pakai pangkat tertinggi: 2²×3²=36. 6 adalah FPB—sering tertukar dengan KPK.',
    }),
    wrongTraps: T({
      ko: '• 6이라고 답한 분: 최대공약수와 최소공배수를 혼동했습니다.\n• 216이라고 답한 분: 12×18을 그냥 곱했군요. 그건 공배수이지만 최소가 아닙니다.',
      en: '• 6: that is the GCD, not the LCM.\n• 216: 12×18 is a common multiple but not the least.',
      ja: '• 6：最大公約数です。最小公倍数ではありません。\n• 216：12×18は公倍数ですが最小ではありません。',
      'zh-CN': '• 选6：那是最大公约数，不是最小公倍数。\n• 216：12×18是公倍数但不是最小。',
      'zh-TW': '• 選6：那是最大公因數，不是最小公倍數。\n• 216：12×18是公倍數但不是最小。',
      vi: '• 6: đó là ƯCLN, không phải BCNN.\n• 216: 12×18 là bội chung nhưng không phải nhỏ nhất.',
      id: '• 6: itu FPB, bukan KPK.\n• 216: 12×18 adalah kelipatan persekutuan tapi bukan terkecil.',
    }),
  },
  {
    id: 7,
    question: T({
      ko: '다음 계산의 정답은?\n0.1 × 0.1 = ?',
      en: 'What is the result?\n0.1 × 0.1 = ?',
      ja: '答えは？\n0.1 × 0.1 = ?',
      'zh-CN': '结果是？\n0.1 × 0.1 = ?',
      'zh-TW': '答案是？\n0.1 × 0.1 = ?',
      vi: 'Kết quả?\n0,1 × 0,1 = ?',
      id: 'Hasilnya?\n0,1 × 0,1 = ?',
    }),
    options: [
      { text: T({ ko: '0.1', en: '0.1', ja: '0.1', 'zh-CN': '0.1', 'zh-TW': '0.1', vi: '0,1', id: '0,1' }), isCorrect: false },
      { text: T({ ko: '1', en: '1', ja: '1', 'zh-CN': '1', 'zh-TW': '1', vi: '1', id: '1' }), isCorrect: false },
      { text: T({ ko: '0.2', en: '0.2', ja: '0.2', 'zh-CN': '0.2', 'zh-TW': '0.2', vi: '0,2', id: '0,2' }), isCorrect: false },
      { text: T({ ko: '0.01', en: '0.01', ja: '0.01', 'zh-CN': '0.01', 'zh-TW': '0.01', vi: '0,01', id: '0,01' }), isCorrect: true },
    ],
    correctExplanation: T({
      ko: '소수점 곱셈: 0.1×0.1 = 1/10 × 1/10 = 1/100 = 0.01. 소수점이 두 번 이동합니다. 0.1+0.1=0.2와 헷갈려서 0.2라고 답하거나, 그냥 0.1이라고 답하는 어른들이 많습니다. 초등 5학년 소수 곱셈 핵심 개념입니다.',
      en: 'Decimal multiplication: 0.1×0.1 = 1/10 × 1/10 = 1/100 = 0.01—the decimal moves two places. Many confuse it with 0.1+0.1=0.2 or answer 0.1. Grade-5 decimals.',
      ja: '小数の掛け算：0.1×0.1=0.01。小数点が二つ動きます。0.1+0.1=0.2と混同したり0.1と答える人が多いです。',
      'zh-CN': '小数乘法：0.1×0.1=0.01，小数点移动两位。易与0.1+0.1=0.2混淆或误答0.1。五年级小数乘法。',
      'zh-TW': '小數乘法：0.1×0.1=0.01，小數點移動兩位。易與0.1+0.1=0.2混淆或誤答0.1。五年級小數乘法。',
      vi: 'Nhân số thập phân: 0,1×0,1=0,01—dấu phẩy dời hai lần. Hay nhầm với 0,1+0,1=0,2 hoặc chọn 0,1.',
      id: 'Perkalian desimal: 0,1×0,1=0,01—koma bergeser dua kali. Sering tertukar dengan 0,1+0,1=0,2 atau jawab 0,1.',
    }),
    wrongTraps: T({
      ko: '• 0.1이라고 답한 분: 1×1=1이니까 소수점 위치만 그대로 가져왔군요.\n• 0.2라고 답한 분: 곱하기를 더하기로 혼동했습니다.',
      en: '• 0.1: treating 1×1=1 but forgetting to shift the decimal twice.\n• 0.2: multiplication mistaken for addition (0.1+0.1).',
      ja: '• 0.1：1×1=1だけ見て小数点を忘れた。\n• 0.2：掛け算を足し算と混同。',
      'zh-CN': '• 0.1：只想到1×1=1，忘了小数点移位。\n• 0.2：把乘法当成加法。',
      'zh-TW': '• 0.1：只想到1×1=1，忘了小數點移位。\n• 0.2：把乘法當成加法。',
      vi: '• 0,1: chỉ nghĩ 1×1=1 mà quên dời dấu phẩy.\n• 0,2: nhầm nhân với cộng.',
      id: '• 0,1: hanya pikir 1×1=1 tanpa geser koma.\n• 0,2: mengira perkalian sebagai penjumlahan.',
    }),
  },
  {
    id: 8,
    question: T({
      ko: '다음 중 각도의 합이 180°가 아닌 도형은?',
      en: 'Which does NOT have angles totaling 180°?',
      ja: '次のうち、角の和が180°にならないのは？',
      'zh-CN': '下列哪个图形的角之和不是180°？',
      'zh-TW': '下列哪個圖形的角之和不是180°？',
      vi: 'Hình nào sau đây KHÔNG có tổng góc bằng 180°?',
      id: 'Manakah yang JUMLAH sudutnya BUKAN 180°?',
    }),
    options: [
      {
        text: T({
          ko: '삼각형의 내각의 합',
          en: 'Sum of interior angles of a triangle',
          ja: '三角形の内角の和',
          'zh-CN': '三角形内角和',
          'zh-TW': '三角形內角和',
          vi: 'Tổng góc trong của tam giác',
          id: 'Jumlah sudut dalam segitiga',
        }),
        isCorrect: false,
      },
      {
        text: T({
          ko: '일직선의 각도',
          en: 'Angles on a straight line',
          ja: '一直線上の角',
          'zh-CN': '直线上的角',
          'zh-TW': '直線上的角',
          vi: 'Góc trên một đường thẳng',
          id: 'Sudut pada garis lurus',
        }),
        isCorrect: false,
      },
      {
        text: T({
          ko: '직사각형의 내각의 합',
          en: 'Sum of interior angles of a rectangle',
          ja: '長方形の内角の和',
          'zh-CN': '长方形内角和',
          'zh-TW': '長方形內角和',
          vi: 'Tổng góc trong của hình chữ nhật',
          id: 'Jumlah sudut dalam persegi panjang',
        }),
        isCorrect: true,
      },
      {
        text: T({
          ko: '이등변삼각형의 내각의 합',
          en: 'Sum of interior angles of an isosceles triangle',
          ja: '二等辺三角形の内角の和',
          'zh-CN': '等腰三角形内角和',
          'zh-TW': '等腰三角形內角和',
          vi: 'Tổng góc trong của tam giác cân',
          id: 'Jumlah sudut dalam segitiga sama kaki',
        }),
        isCorrect: false,
      },
    ],
    correctExplanation: T({
      ko: '직사각형의 내각의 합은 90°×4=360°입니다. 삼각형은 어떤 종류든 내각의 합이 항상 180°이고, 일직선도 180°입니다. 직사각형은 사각형이므로 내각의 합은 360°. 초등 4학년 도형 개념입니다.',
      en: 'A rectangle’s interior angles sum to 90°×4=360°. Any triangle’s interior angles sum to 180°; a straight line is also 180°. A rectangle is a quadrilateral—total 360°. Grade-4 geometry.',
      ja: '長方形の内角の和は360°。三角形は種類を問わず180°。直線上も180°。長方形は四角形なので360°。小学4年生の図形。',
      'zh-CN': '长方形内角和为360°。任意三角形内角和为180°，平角也是180°。长方形是四边形，内角和360°。四年级几何。',
      'zh-TW': '長方形內角和為360°。任意三角形內角和為180°，平角也是180°。長方形是四邊形，內角和360°。四年級幾何。',
      vi: 'Hình chữ nhật: tổng góc trong 360°. Mọi tam giác đều 180°; đường thẳng cũng 180°. Hình chữ nhật là tứ giác—360°.',
      id: 'Persegi panjang: jumlah sudut dalam 360°. Segitiga apa pun 180°; garis lurus 180°. Persegi panjang adalah segi empat—360°.',
    }),
    wrongTraps: T({
      ko: '• 삼각형이라고 답한 분: 직각삼각형 예외가 있다고 생각했나요? 삼각형은 항상 180°입니다.\n• 이등변삼각형이라고 답한 분: 이등변삼각형도 삼각형이므로 내각의 합은 180°입니다.',
      en: '• Triangle: every triangle’s interior angles sum to 180°—no exception for “right” or “isosceles.”\n• Isosceles triangle: still a triangle—still 180°.',
      ja: '• 三角形：どんな三角形も内角の和は180°です。\n• 二等辺三角形：三角形なので180°です。',
      'zh-CN': '• 选三角形：任意三角形内角和都是180°。\n• 选等腰三角形：仍是三角形，内角和仍是180°。',
      'zh-TW': '• 選三角形：任意三角形內角和都是180°。\n• 選等腰三角形：仍是三角形，內角和仍是180°。',
      vi: '• Tam giác: mọi tam giác đều 180°.\n• Tam giác cân: vẫn là tam giác—vẫn 180°.',
      id: '• Segitiga: semua segitiga 180°.\n• Segitiga sama kaki: tetap segitiga—tetap 180°.',
    }),
  },
  {
    id: 9,
    question: T({
      ko: '어떤 수를 4로 나누면 나머지가 3이고 3으로 나누면 나머지가 1입니다. 이 수 중 가장 작은 자연수는?',
      en: 'A number leaves remainder 3 when divided by 4, and remainder 1 when divided by 3. What is the smallest such natural number?',
      ja: 'ある自然数を4で割ると余りが3、3で割ると余りが1。最も小さいのは？',
      'zh-CN': '某自然数除以4余3，除以3余1。满足条件的最小自然数是？',
      'zh-TW': '某自然數除以4餘3，除以3餘1。滿足條件的最小自然數是？',
      vi: 'Một số tự nhiên chia cho 4 dư 3, chia cho 3 dư 1. Số nhỏ nhất thỏa mãn là?',
      id: 'Bilangan asli dibagi 4 bersisa 3, dibagi 3 bersisa 1. Bilangan terkecil yang memenuhi?',
    }),
    options: [
      { text: T({ ko: '5', en: '5', ja: '5', 'zh-CN': '5', 'zh-TW': '5', vi: '5', id: '5' }), isCorrect: false },
      { text: T({ ko: '6', en: '6', ja: '6', 'zh-CN': '6', 'zh-TW': '6', vi: '6', id: '6' }), isCorrect: false },
      { text: T({ ko: '7', en: '7', ja: '7', 'zh-CN': '7', 'zh-TW': '7', vi: '7', id: '7' }), isCorrect: true },
      { text: T({ ko: '11', en: '11', ja: '11', 'zh-CN': '11', 'zh-TW': '11', vi: '11', id: '11' }), isCorrect: false },
    ],
    correctExplanation: T({
      ko: '조건 ①: 4로 나누면 나머지 3 → 해당하는 수: 3, 7, 11, 15, 19… 조건 ②: 3으로 나누면 나머지 1 → 해당하는 수: 1, 4, 7, 10, 13… 두 조건을 동시에 만족하는 가장 작은 자연수: 7(7÷4=1…3, 7÷3=2…1). 초등 5학년 나머지 있는 나눗셈 응용 문제입니다.',
      en: 'Numbers ≡3 (mod 4): 3,7,11,… Numbers ≡1 (mod 3): 1,4,7,10,… The smallest common value is 7 (7÷4 remainder 3; 7÷3 remainder 1). Grade-5 remainders.',
      ja: '条件①：4で割って余り3→3,7,11… 条件②：3で割って余り1→1,4,7,10… 共通の最小は7。小学5年生の余りの問題。',
      'zh-CN': '除以4余3：3,7,11…除以3余1：1,4,7,10…同时满足的最小自然数是7。五年级余数应用。',
      'zh-TW': '除以4餘3：3,7,11…除以3餘1：1,4,7,10…同時滿足的最小自然數是7。五年級餘數應用。',
      vi: 'Chia 4 dư 3: 3,7,11… Chia 3 dư 1: 1,4,7,10… Số nhỏ nhất chung là 7.',
      id: 'Bagi 4 sisa 3: 3,7,11… Bagi 3 sisa 1: 1,4,7,10… Terkecil yang memenuhi keduanya adalah 7.',
    }),
    wrongTraps: T({
      ko: '• 5라고 답한 분: 5÷4=1…1(나머지가 3이 아닙니다).\n• 11이라고 답한 분: 조건 ①은 맞지만 11÷3=3…2(나머지가 1이 아닙니다).',
      en: '• 5: 5÷4 leaves remainder 1, not 3.\n• 11: satisfies the first condition but 11÷3 leaves remainder 2, not 1.',
      ja: '• 5：5÷4の余りは1。\n• 11：11÷3の余りは2。',
      'zh-CN': '• 5：5÷4余1，不是3。\n• 11：11÷3余2，不是1。',
      'zh-TW': '• 5：5÷4餘1，不是3。\n• 11：11÷3餘2，不是1。',
      vi: '• 5: 5÷4 dư 1, không phải 3.\n• 11: 11÷3 dư 2, không phải 1.',
      id: '• 5: 5÷4 bersisa 1, bukan 3.\n• 11: 11÷3 bersisa 2, bukan 1.',
    }),
  },
  {
    id: 10,
    question: T({
      ko: '다음 규칙에서 빈칸에 들어갈 숫자는?\n1, 1, 2, 3, 5, 8, 13, ( ? )',
      en: 'What number fills the blank?\n1, 1, 2, 3, 5, 8, 13, ( ? )',
      ja: '空欄に入る数は？\n1, 1, 2, 3, 5, 8, 13, ( ? )',
      'zh-CN': '按规律填空：\n1, 1, 2, 3, 5, 8, 13, ( ? )',
      'zh-TW': '依規律填空：\n1, 1, 2, 3, 5, 8, 13, ( ? )',
      vi: 'Số nào điền vào chỗ trống?\n1, 1, 2, 3, 5, 8, 13, ( ? )',
      id: 'Bilangan apa yang mengisi?\n1, 1, 2, 3, 5, 8, 13, ( ? )',
    }),
    options: [
      { text: T({ ko: '18', en: '18', ja: '18', 'zh-CN': '18', 'zh-TW': '18', vi: '18', id: '18' }), isCorrect: false },
      { text: T({ ko: '20', en: '20', ja: '20', 'zh-CN': '20', 'zh-TW': '20', vi: '20', id: '20' }), isCorrect: false },
      { text: T({ ko: '21', en: '21', ja: '21', 'zh-CN': '21', 'zh-TW': '21', vi: '21', id: '21' }), isCorrect: true },
      { text: T({ ko: '26', en: '26', ja: '26', 'zh-CN': '26', 'zh-TW': '26', vi: '26', id: '26' }), isCorrect: false },
    ],
    correctExplanation: T({
      ko: '이 수열은 피보나치 수열입니다. 앞 두 수를 더하면 다음 수가 됩니다. 1+1=2, 1+2=3, 2+3=5, 3+5=8, 5+8=13, 8+13=21. 초등 수학 심화 과정에서 등장하는 규칙 찾기 문제입니다.',
      en: 'This is the Fibonacci sequence: each term is the sum of the two before it. …8+13=21. A classic pattern-spotting problem.',
      ja: 'フィボナッチ数列です。前二つの和が次の項。8+13=21。',
      'zh-CN': '这是斐波那契数列：每项等于前两项之和。8+13=21。',
      'zh-TW': '這是費波那契數列：每項等於前兩項之和。8+13=21。',
      vi: 'Đây là dãy Fibonacci: mỗi số bằng tổng hai số trước. 8+13=21.',
      id: 'Ini deret Fibonacci: setiap suku jumlah dua suku sebelumnya. 8+13=21.',
    }),
    wrongTraps: T({
      ko: '• 18이라고 답한 분: 앞 수에 5를 더하는 패턴이라고 생각했군요(13+5=18).\n• 20이라고 답한 분: 앞 수에 7을 더하는 패턴이라고 생각했군요(13+7=20).\n• 26이라고 답한 분: 앞 수에 13을 더했군요(13+13=26).',
      en: '• 18: “add 5 each time” (13+5)—wrong rule.\n• 20: “add 7” (13+7)—wrong.\n• 26: 13+13—wrong.',
      ja: '• 18：+5のパターンと思った。\n• 20：+7と思った。\n• 26：13+13と思った。',
      'zh-CN': '• 18：误以为每次加5。\n• 20：误以为加7。\n• 26：用13+13。',
      'zh-TW': '• 18：誤以為每次加5。\n• 20：誤以為加7。\n• 26：用13+13。',
      vi: '• 18: tưởng cộng 5.\n• 20: tưởng cộng 7.\n• 26: 13+13.',
      id: '• 18: mengira +5.\n• 20: mengira +7.\n• 26: 13+13.',
    }),
  },
];

export const phase3ElementaryMathAdultsQuizResults: Phase3ElementaryMathAdultsQuizResult[] = [
  {
    type: 'Band1',
    emoji: '🆘',
    title: T({
      ko: '초등 수학 비상',
      en: 'Elementary math emergency',
      ja: '算数ピンチ',
      'zh-CN': '小学数学告急',
      'zh-TW': '小學數學告急',
      vi: 'Toán tiểu học báo động',
      id: 'Matematika SD darurat',
    }),
    shortDescription: T({
      ko: '"선생님, 저 이 반에 다시 다니면 안 될까요?"',
      en: '"Teacher… can I retake this grade?"',
      ja: '「先生、このクラスもう一度よろしいですか？」',
      'zh-CN': '「老师，我能重修这班吗？」',
      'zh-TW': '「老師，我能重修這班嗎？」',
      vi: '"Cô ơi, em có thể học lại lớp này không?"',
      id: '"Bu, saya bisa naik kelas ini lagi?"',
    }),
    description: T({
      ko: '어른이 된 지금 초등 수학이 이렇게 낯설게 느껴진다니. 연산 순서, 분수, 소수점이 이미 기억 저 너머로 사라진 상태입니다. 부끄럽지 않습니다. 지금 당장 검색해서 틀린 문제를 다시 풀어보세요. 처음 배울 때보다 훨씬 빨리 이해될 거예요.',
      en: 'Elementary math feels foreign again—order of operations, fractions, decimals are hazy. No shame. Look up what you missed; you’ll relearn faster than the first time.',
      ja: '大人になってから算数がこんなに難しく感じるなんて。恥ずかしくないです。今すぐ調べて復習しましょう。',
      'zh-CN': '成年后小学数学变得陌生，运算顺序、分数、小数都模糊了。不必羞愧，马上查资料重做错题，会比第一次学更快。',
      'zh-TW': '成年後小學數學變得陌生，運算順序、分數、小數都模糊了。不必羞愧，馬上查資料重做錯題，會比第一次學更快。',
      vi: 'Toán tiểu học giờ xa lạ—thứ tự phép tính, phân số, thập phân mờ nhạt. Đừng ngại, tra lại bài sai—bạn sẽ hiểu nhanh hơn lần đầu.',
      id: 'Matematika SD terasa asing—urutan operasi, pecahan, desimal kabur. Jangan malu, cari ulang soal salah—kamu paham lebih cepat dari pertama kali.',
    }),
    levelLabel: T({
      ko: '수학 빨간 딱지 위기',
      en: 'Math red-flag alert',
      ja: '算数・赤札クラス',
      'zh-CN': '数学红灯危机',
      'zh-TW': '數學紅燈危機',
      vi: 'Toán báo đỏ',
      id: 'Matematika lampu merah',
    }),
    honorTitle: T({
      ko: '"담임 선생님이 부모님 연락처 찾는 중"',
      en: '"Homeroom teacher is looking up your parents\' number"',
      ja: '「担任が保護者の連絡先を探している」',
      'zh-CN': '「班主任正在找家长电话」',
      'zh-TW': '「導師正在找家長電話」',
      vi: '"Giáo viên chủ nhiệm đang tìm số phụ huynh"',
      id: '"Wali kelas sedang mencari nomor orang tua"',
    }),
    oneLiner: T({
      ko: 'Q1에서 0이라고 답했다면 전 세계 수억 명이 같이 틀렸습니다. 혼자가 아니에요.',
      en: 'If you picked 0 on Q1, hundreds of millions worldwide did too—you’re not alone.',
      ja: 'Q1で0と答えたなら、世界中の何億人も同じ。一人じゃない。',
      'zh-CN': '第1题选0的话，全球数亿人和你一样错——你不是一个人。',
      'zh-TW': '第1題選0的話，全球數億人和你一樣錯——你不是一個人。',
      vi: 'Nếu chọn 0 ở câu 1, hàng trăm triệu người cũng vậy—bạn không cô đơn.',
      id: 'Jika pilih 0 di soal 1, ratusan juta orang juga—kamu tidak sendirian.',
    }),
    todoToday: T({
      ko: '연산 순서(사칙연산 우선순위) 검색하기',
      en: 'Search: order of operations (PEMDAS)',
      ja: '検索：演算の順序（先に掛け算・割り算）',
      'zh-CN': '搜索：运算顺序（四则运算优先级）',
      'zh-TW': '搜尋：運算順序（四則運算優先順序）',
      vi: 'Tìm kiếm: thứ tự phép tính (ưu tiên nhân chia)',
      id: 'Cari: urutan operasi (perkalian/pembagian dulu)',
    }),
    shareLine: T({
      ko: '초등 수학 퀴즈 {count}개 맞힘 🆘 이게 초등 문제라는 게 말이 되냐... 너도 해봐 자존심 걸어',
      en: 'Elementary math quiz: {count}/10 🆘 How is this “elementary”? Try it—ego on the line.',
      ja: '小学生算数クイズ {count}/10 🆘 これが小学生レベル？自慢に挑戦して。',
      'zh-CN': '小学数学测验对了{count}题 🆘 这也叫小学题？来试试，赌上自尊。',
      'zh-TW': '小學數學測驗對了{count}題 🆘 這也叫小學題？來試試，賭上自尊。',
      vi: 'Quiz toán tiểu học: {count}/10 🆘 Đây mà là “tiểu học”? Thử đi—cược cái tôi.',
      id: 'Kuis matematika SD: {count}/10 🆘 Ini masih “SD”? Coba—taruh gengsi.',
    }),
  },
  {
    type: 'Band2',
    emoji: '🤔',
    title: T({
      ko: '수학 기억 중간 어딘가',
      en: 'Math memory: somewhere in the middle',
      ja: '算数の記憶、どこか中途半端',
      'zh-CN': '数学记忆半吊子',
      'zh-TW': '數學記憶半吊子',
      vi: 'Trí nhớ toán: chừng nửa vời',
      id: 'Ingatan matematika: setengah-setengah',
    }),
    shortDescription: T({
      ko: '"분명히 배웠는데 왜 이렇게 헷갈리지?"',
      en: '"I know I learned this—why is it so fuzzy?"',
      ja: '「習ったはずなのに、なんでこんなに曖昧？」',
      'zh-CN': '「明明学过，怎么这么糊？」',
      'zh-TW': '「明明學過，怎麼這麼糊？」',
      vi: '"Chắc là học rồi mà sao cứ lờ mờ?"',
      id: '"Kan sudah belajar—kok masih blur?"',
    }),
    description: T({
      ko: '기본 개념은 남아있지만 디테일에서 흔들리는 상태입니다. 아마 쉬운 문제는 맞혔는데 분수 통분이나 연산 순서에서 막혔을 거예요. 30대 이상이라면 평균 점수 구간입니다. 창피한 점수가 아닙니다.',
      en: 'Basics are still there, but details wobble—maybe easy items were fine, but common fraction steps or order of operations tripped you. If you’re 30+, this band is very average. Nothing to be ashamed of.',
      ja: '基礎は残っているけど細部で揺れる。簡単なのは取れたが分数の通分や順序でつまずいたかも。30代以上なら平均ゾーン。恥ずかしくない。',
      'zh-CN': '大概念还在，细节会晃。可能简单题对了，分数通分或运算顺序卡住了。30岁以上很常见，别觉得丢人。',
      'zh-TW': '大概念還在，細節會晃。可能簡單題對了，分數通分或運算順序卡住了。30歲以上很常見，別覺得丟人。',
      vi: 'Nền tảng còn nhưng chi tiết lung lay—có thể câu dễ đúng nhưng quy đồng hoặc thứ tự phép tính vấp. Trên 30 tuổi rất bình thường.',
      id: 'Konsep dasar ada tapi detail goyah—mungkin soal mudah benar tapi pecahan atau urutan operasi macet. Di atas 30 tahun sangat umum.',
    }),
    levelLabel: T({
      ko: '수학 기억 중간 어딘가',
      en: 'Mid-tier math memory',
      ja: '記憶は中くらい',
      'zh-CN': '数学记忆中游',
      'zh-TW': '數學記憶中游',
      vi: 'Trí nhớ toán mức giữa',
      id: 'Ingatan matematika menengah',
    }),
    honorTitle: T({
      ko: '"기억은 나는데 계산이 안 되는 사람"',
      en: '"Remembers the idea, can’t run the numbers"',
      ja: '「覚えてるのに計算が追いつかない人」',
      'zh-CN': '「记得概念，算不出来」',
      'zh-TW': '「記得概念，算不出來」',
      vi: '"Nhớ ý mà không tính ra"',
      id: '"Ingat konsepnya, hitungnya macet"',
    }),
    oneLiner: T({
      ko: '분수 통분 문제에서 분자끼리 더했다면 전 세계 인구의 절반이 같이 틀립니다.',
      en: 'If you added numerators and denominators on a fraction problem, half the planet has been there.',
      ja: '分数で分子同士・分母同士を足したなら、世界中の仲間がいます。',
      'zh-CN': '分数题把分子加分子、分母加分母的话，全球一半人都踩过坑。',
      'zh-TW': '分數題把分子加分子、分母加分母的話，全球一半人都踩過坑。',
      vi: 'Nếu cộng tử với tử, mẫu với mẫu—nửa thế giới cũng từng vậy.',
      id: 'Kalau menjumlahkan pembilang+pembilang—setengah dunia pernah begitu.',
    }),
    todoToday: T({
      ko: '분수 덧셈 통분 개념 복습하기',
      en: 'Review: adding fractions with common denominators',
      ja: '復習：分数の足し算（通分）',
      'zh-CN': '复习：分数加法与通分',
      'zh-TW': '複習：分數加法與通分',
      vi: 'Ôn: cộng phân số và quy đồng',
      id: 'Ulang: penjumlahan pecahan dan penyamakan penyebut',
    }),
    shareLine: T({
      ko: '초등 수학 퀴즈 {count}개 맞힘 🤔 Q1 함정에 걸렸다는 거 창피해서 말 못 함 → 너도 도전해봐',
      en: 'Elementary math quiz: {count}/10 🤔 Too embarrassed to admit Q1 got me—your turn.',
      ja: '算数クイズ {count}/10 🤔 Q1の罠、言えない…君も挑戦して。',
      'zh-CN': '小学测验对了{count}题 🤔 第1题坑不好意思说——你也来。',
      'zh-TW': '小學測驗對了{count}題 🤔 第1題坑不好意思說——你也來。',
      vi: 'Quiz toán: {count}/10 🤔 Ngại nói câu 1 dính bẫy—thử đi.',
      id: 'Kuis matematika: {count}/10 🤔 Malu ngaku soal 1 kena jebakan—coba kamu.',
    }),
  },
  {
    type: 'Band3',
    emoji: '👍',
    title: T({
      ko: '수학 감각 양호',
      en: 'Solid math sense',
      ja: '算数センス良好',
      'zh-CN': '数学感觉不错',
      'zh-TW': '數學感覺不錯',
      vi: 'Cảm toán khá tốt',
      id: 'Nalar matematika bagus',
    }),
    shortDescription: T({
      ko: '"초등 수학은 아직 건재합니다."',
      en: '"Your elementary math is still in good shape."',
      ja: '「小学校の算数、まだ生きてます。」',
      'zh-CN': '「小学数学还在线。」',
      'zh-TW': '「小學數學還在線。」',
      vi: '"Toán tiểu học vẫn còn đó."',
      id: '"Matematika SD kamu masih oke."',
    }),
    description: T({
      ko: '연산 순서, 분수, 단위 변환까지 대부분 잘 기억하고 있는 상태입니다. 고난이도 문제 1~2개에서 막혔을 가능성이 높지만 그건 대부분의 어른들이 틀리는 문제입니다. 수학 감각이 살아있는 사람입니다.',
      en: 'You mostly remember order of operations, fractions, and unit conversion. If 1–2 hard ones stumped you, that’s where most adults slip too. Your math sense is alive.',
      ja: '演算順序・分数・単位換算はだいたいOK。難問で1〜2問つまずいても大人はみんなそう。センスは生きてます。',
      'zh-CN': '运算顺序、分数、单位换算大多记得住。难题错一两道很正常，大人也常错。你的数感还在。',
      'zh-TW': '運算順序、分數、單位換算大多記得住。難題錯一兩道很正常，大人也常錯。你的數感還在。',
      vi: 'Bạn nhớ phần lớn thứ tự phép tính, phân số, đổi đơn vị. Sai 1–2 câu khó là chuyện thường với người lớn.',
      id: 'Kamu masih ingat urutan operasi, pecahan, konversi satuan. Salah 1–2 soal sulit itu wajar untuk orang dewasa.',
    }),
    levelLabel: T({
      ko: '수학 감각 양호',
      en: 'Healthy math intuition',
      ja: '算数センス良好',
      'zh-CN': '数学感觉良好',
      'zh-TW': '數學感覺良好',
      vi: 'Cảm toán tốt',
      id: 'Nalar matematika sehat',
    }),
    honorTitle: T({
      ko: '"초등학교 수학은 졸업한 사람"',
      en: '"Officially graduated elementary math"',
      ja: '「小学校の算数は卒業した人」',
      'zh-CN': '「小学数学已毕业」',
      'zh-TW': '「小學數學已畢業」',
      vi: '"Đã tốt nghiệp toán tiểu học"',
      id: '"Lulus matematika SD"',
    }),
    oneLiner: T({
      ko: '피보나치 수열이나 나머지 조건 문제까지 맞혔다면 진짜 대단한 겁니다.',
      en: 'If you nailed Fibonacci or the remainder puzzle, that’s genuinely impressive.',
      ja: 'フィボナッチや余りの問題まで取れたなら本当にすごい。',
      'zh-CN': '斐波那契或余数题也对了，真的很强。',
      'zh-TW': '費波那契或餘數題也對了，真的很強。',
      vi: 'Nếu làm đúng Fibonacci hoặc bài số dư—rất ấn tượng.',
      id: 'Kalau benar Fibonacci atau soal sisa—keren banget.',
    }),
    todoToday: T({
      ko: '틀린 문제 하나만 다시 풀어보기',
      en: 'Redo just one missed problem',
      ja: '間違えた問題を1問だけやり直す',
      'zh-CN': '只做一道错题重练',
      'zh-TW': '只做一道錯題重練',
      vi: 'Làm lại một câu sai',
      id: 'Ulang satu soal yang salah',
    }),
    shareLine: T({
      ko: '초등 수학 퀴즈 {count}개 맞힘 👍 7개 이상이면 나름 수학 감각 살아있는 거래 → 너는 몇 개야?',
      en: 'Elementary math quiz: {count}/10 👍 Seven or more means your sense is alive—how many did you get?',
      ja: '算数クイズ {count}/10 👍 7以上ならセンスあり。君は？',
      'zh-CN': '小学测验对了{count}题 👍 7题以上算数感在线——你对了几个？',
      'zh-TW': '小學測驗對了{count}題 👍 7題以上算數感在線——你對了幾個？',
      vi: 'Quiz toán: {count}/10 👍 Từ 7 trở lên là cảm toán còn tốt—bạn được mấy?',
      id: 'Kuis matematika: {count}/10 👍 7+ berarti nalar masih hidup—kamu dapat berapa?',
    }),
  },
  {
    type: 'Band4',
    emoji: '🏆',
    title: T({
      ko: '초등 수학 천재',
      en: 'Elementary math ace',
      ja: '小学生算数エース',
      'zh-CN': '小学数学大神',
      'zh-TW': '小學數學大神',
      vi: 'Cao thủ toán tiểu học',
      id: 'Jago matematika SD',
    }),
    shortDescription: T({
      ko: '"혹시 수학 선생님이신가요?"',
      en: '"Are you secretly a math teacher?"',
      ja: '「もしかして算数の先生？」',
      'zh-CN': '「难道是数学老师？」',
      'zh-TW': '「難道是數學老師？」',
      vi: '"Hay là giáo viên toán?"',
      id: '"Jangan-jangan guru matematika?"',
    }),
    description: T({
      ko: '피보나치 수열까지 맞혔다면 당신은 초등 수학을 완전히 마스터한 사람입니다. 함정 문제도 피해가고, 개념도 정확하게 기억하고 있습니다. 이 결과를 친구들에게 자랑하세요. 아마 대부분의 친구들은 이 점수를 못 받을 겁니다.',
      en: 'If you cleared Fibonacci too, you’ve mastered elementary math. You dodged traps and held the concepts. Flex this to friends—most won’t hit this score.',
      ja: 'フィボナッチまで正解なら、小学校の算数は完全制覇。ワナも回避、概念も正確。自慢していいレベル。',
      'zh-CN': '连斐波那契都对，你已基本通关小学数学。避开陷阱、概念清晰——值得向朋友炫耀，多数人拿不到这分数。',
      'zh-TW': '連費波那契都對，你已基本通關小學數學。避開陷阱、概念清晰——值得向朋友炫耀，多數人拿不到這分數。',
      vi: 'Làm đúng cả Fibonacci là bạn đã nắm vững toán tiểu học. Tránh bẫy, giữ khái niệm—khoe bạn bè đi, đa số không đạt điểm này.',
      id: 'Benar Fibonacci artinya kamu menguasai matematika SD. Menghindari jebakan, konsep tepat—bangga ke teman, kebanyakan tidak dapat skor ini.',
    }),
    levelLabel: T({
      ko: '초등 수학 만렙',
      en: 'Max-level elementary math',
      ja: '小学生算数フルコンプ',
      'zh-CN': '小学数学满级',
      'zh-TW': '小學數學滿級',
      vi: 'Max cấp toán tiểu học',
      id: 'Level max matematika SD',
    }),
    honorTitle: T({
      ko: '"담임 선생님이 가장 아끼던 학생"',
      en: '"The teacher’s favorite student"',
      ja: '「担任が一番可愛がってた生徒」',
      'zh-CN': '「班主任最偏爱的学生」',
      'zh-TW': '「導師最偏愛的學生」',
      vi: '"Học trò cưng của cô chủ nhiệm"',
      id: '"Murid favorit wali kelas"',
    }),
    oneLiner: T({
      ko: 'Q3에서 288 맞혔다고요? 전 세계에서 절반이 2라고 답하는 문제인데...',
      en: 'You got 288 on Q3? Half the internet still fights over that problem…',
      ja: 'Q3で288？世界中で議論の問題ですよ…',
      'zh-CN': '第3题算出288？全球一半人还在吵那题……',
      'zh-TW': '第3題算出288？全球一半人還在吵那題……',
      vi: 'Ra 288 ở câu 3? Nửa thế giới vẫn cãi bài đó…',
      id: 'Dapat 288 di soal 3? Setengah dunia masih debat soal itu…',
    }),
    todoToday: T({
      ko: '이 퀴즈 친구한테 공유하고 "나 10개 맞혔음" 자랑하기',
      en: 'Share this quiz and humble-brag: “I got 10/10.”',
      ja: '友達にシェアして「10問全問正解」と自慢する',
      'zh-CN': '把测验分享给朋友，凡尔赛一下「我全对」',
      'zh-TW': '把測驗分享給朋友，炫耀「我全對」',
      vi: 'Chia sẻ quiz và khoe “mình 10/10”',
      id: 'Bagikan kuis dan bangga “aku 10/10”',
    }),
    shareLine: T({
      ko: '초등 수학 퀴즈 {count}개 맞힘 🏆 Q3 연산 순서 함정 맞혔다 ㅋㅋ 친구야 너도 자존심 걸고 도전해봐',
      en: 'Elementary math quiz: {count}/10 🏆 Beat the Q3 order-of-ops trap—your turn, friend.',
      ja: '算数クイズ {count}/10 🏆 Q3の罠クリア！友達も挑戦して。',
      'zh-CN': '小学测验对了{count}题 🏆 第3题运算顺序坑过了——朋友也来赌自尊。',
      'zh-TW': '小學測驗對了{count}題 🏆 第3題運算順序坑過了——朋友也來賭自尊。',
      vi: 'Quiz toán: {count}/10 🏆 Qua bẫy câu 3—bạn thử đi.',
      id: 'Kuis matematika: {count}/10 🏆 Lewati jebakan soal 3—teman coba.',
    }),
  },
];

export function calculatePhase3ElementaryMathAdultsQuizResult(answers: number[]): string {
  const total = answers.reduce((s, v) => s + v, 0);
  if (total <= 3) return 'Band1';
  if (total <= 6) return 'Band2';
  if (total <= 8) return 'Band3';
  return 'Band4';
}
